<DOC>
<DOCNO>

<s docid="AP880917-0157" num="1" wdcount="1"> AP880917-0157</s>
</DOCNO>
<FILEID>

<s docid="AP880917-0157" num="2" wdcount="2"> AP-NR-09-17-88 2111EDT</s>
</FILEID>
<FIRST>

<s docid="AP880917-0157" num="3" wdcount="5"> r i AM-Israel-DogShow 09-17 0309</s>
</FIRST>
<SECOND>

<s docid="AP880917-0157" num="4" wdcount="2"> AM-Israel-Dog Show,0317</s>
</SECOND>
<HEAD>

<s docid="AP880917-0157" num="5" wdcount="8"> Thousands of Israelis Turn Out For Dog Show</s>
</HEAD>
<BYLINE>

<s docid="AP880917-0157" num="6" wdcount="4"> By NICOLAS B. TATRO</s>
</BYLINE>
<BYLINE>

<s docid="AP880917-0157" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880917-0157" num="8" wdcount="4"> TEL AVIV, Israel (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880917-0157" num="9" wdcount="25"> Taking a break from the headaches of the Palestinian uprising and Israel's election campaign, thousands of Israelis turned out Saturday for a canine beauty pageant.</s>

<s docid="AP880917-0157" num="10" wdcount="31"> Marco, a feisty boxer owned by Dov Amir, padded off with the champion's trophy after beating out 800 other pretty pooches in Israel's dog-of-the-year contest held in Tel Aviv's Exhibition Center.</s>

<s docid="AP880917-0157" num="11" wdcount="40"> ``We can find time for other things besides the intefadeh,'' said organizer Avi Marshak, using the Arabic word for uprising to describe the 9-month-old wave of Palestinian violence aimed at ending Israel's occupation of the West Bank and Gaza Strip.</s>

<s docid="AP880917-0157" num="12" wdcount="9"> About 20,000 people attended the two-day show, organizers said.</s>

<s docid="AP880917-0157" num="13" wdcount="38"> Israeli couples in cutoff jeans and short-sleeved shirts pushed baby strollers from ring to ring to view the more than 50 different breeds ranging from tiny lap dogs like the Yorkshire terriers to Great Danes and St. Bernards.</s>

<s docid="AP880917-0157" num="14" wdcount="26"> Marshak said the contest was sanctioned by the World Kennel Club based in Brussels, Belgium, and had judges from the Netherlands, South Africa, Italy and Britain.</s>

<s docid="AP880917-0157" num="15" wdcount="20"> But although the competition was billed as an international event, organizers conceded there were few if any contestants from abroad.</s>

<s docid="AP880917-0157" num="16" wdcount="23"> This was in contrast to 1987, before the uprising began, when a World Dog Show competition attracted scores of foreign competitors to Israel.</s>

<s docid="AP880917-0157" num="17" wdcount="33"> ``Even so, we don't feel the intefadeh here,'' said Rafi Shahaf, a veterinarian, who was interviewed in the show ring where Conan, his steel gray Mastino Napoletano, had just taken a blue ribbon.</s>

<s docid="AP880917-0157" num="18" wdcount="16"> The show briefly pushed the Nov. 1 general elections out of the limelight for the doglovers.</s>

<s docid="AP880917-0157" num="19" wdcount="25"> Experts say the razor-tight race between the right-wing Likud Party and the left-leaning Labor Party could determine the future of the Israeli-occupied Palestinian lands .</s>
</TEXT>
</DOC>
