<DOC>
<DOCNO>

<s docid="AP880310-0062" num="1" wdcount="1"> AP880310-0062</s>
</DOCNO>
<FILEID>

<s docid="AP880310-0062" num="2" wdcount="2"> AP-NR-03-10-88 0557EST</s>
</FILEID>
<FIRST>

<s docid="AP880310-0062" num="3" wdcount="5"> r a PM-DogLunch 03-10 0239</s>
</FIRST>
<SECOND>

<s docid="AP880310-0062" num="4" wdcount="2"> PM-Dog Lunch,0247</s>
</SECOND>
<HEAD>

<s docid="AP880310-0062" num="5" wdcount="6"> Lunch at Sardi's a Canine Affair</s>
</HEAD>
<DATELINE>

<s docid="AP880310-0062" num="6" wdcount="3"> NEW YORK (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880310-0062" num="7" wdcount="22"> With no seats and no food for the guests of honor, everyone agreed that lunch at Sardi's had gone to the dogs.</s>

<s docid="AP880310-0062" num="8" wdcount="16"> Two dogs, to be specific, the city's top police dog and the nation's top show dog.</s>

<s docid="AP880310-0062" num="9" wdcount="30"> The Dog Fanciers Club organized the event Wednesday to honor Champion Great Elms Prince Charming II, a fluffy little Pomeranian, and Nero, a big, amiable bruiser of a German shepherd.</s>

<s docid="AP880310-0062" num="10" wdcount="11"> ``He's a very friendly dog,'' said Nero's master, Officer Joseph Faraguna.</s>

<s docid="AP880310-0062" num="11" wdcount="13"> ``In all the arrests I've made with him, he's only bitten four times''.</s>

<s docid="AP880310-0062" num="12" wdcount="8"> Nero specializes in sniffing out bombs and narcotics.</s>

<s docid="AP880310-0062" num="13" wdcount="17"> He has helped the Police Department make hundreds of arrests and has ``apprehended'' more than 50 felons.</s>

<s docid="AP880310-0062" num="14" wdcount="24"> Nero was kept on his long leather leash while Prince emerged from his elegant, padded carrying case only long enough to pose for photographers.</s>

<s docid="AP880310-0062" num="15" wdcount="20"> The Pomeranian was named best in show at the prestigious Westminister Kennel Club Show in Madison Square Garden last month.</s>

<s docid="AP880310-0062" num="16" wdcount="25"> Prince, long used to being coddled and primped, seemed oblivious to all the attention until Nero grew bold enough to prod him on the chin.</s>

<s docid="AP880310-0062" num="17" wdcount="6"> Then he blinked and drew back.</s>

<s docid="AP880310-0062" num="18" wdcount="18"> But neither Nero nor Prince got any lunch from the luncheon at Sardi's, a prominent midtown Manhattan restaurant.</s>

<s docid="AP880310-0062" num="19" wdcount="15"> Prince, said his agent and master Skip Piazza, ``doesn't have a very large diet anyway.''</s>
</TEXT>
</DOC>
