<DOC>
<DOCNO>

<s docid="LA020489-0060" num="1" wdcount="1"> LA020489-0060</s>
</DOCNO>
<DOCID>

<s docid="LA020489-0060" num="2" wdcount="1"> 14074</s>
</DOCID>
<DATE>
<P>

<s docid="LA020489-0060" num="3" wdcount="6"> February 4, 1989, Saturday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA020489-0060" num="4" wdcount="9"> View; Part 5; Page 18; Column 3; View Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA020489-0060" num="5" wdcount="2"> 209 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA020489-0060" num="6" wdcount="11"> FAMILY SPOTS: SPORTS ARENA BEING GROOMED FOR DOG SHOW ON SUNDAY</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA020489-0060" num="7" wdcount="3"> By ELLEN MELINKOFF</s>
</P>
</BYLINE>
<TEXT>
<P>

<s docid="LA020489-0060" num="8" wdcount="26"> More than 2,500 dogs, representing 138 breeds, will compete for prizes at Sunday's All Breed Dog Show and Obedience Trials at the Los Angeles Sports Arena.</s>

<s docid="LA020489-0060" num="9" wdcount="32"> For families who are thinking about getting a dog, this is a chance to size up the possibilities and talk with pet owners about the advantages and disadvantages of different breeds .</s>
</P>
<P>

<s docid="LA020489-0060" num="10" wdcount="16"> Around the arena, owners will be busy grooming and cajoling their charges into center-ring readiness .</s>
</P>
<P>

<s docid="LA020489-0060" num="11" wdcount="16"> Between judgings, a troupe of Dobermans will jump through hoops and barrels and will scale walls.</s>

<s docid="LA020489-0060" num="12" wdcount="18"> In the scent relay, teams of dogs will jump over hurdles and locate the jackets of their owners.</s>

<s docid="LA020489-0060" num="13" wdcount="13"> There will also be a demonstration of how dogs herd farm animals .</s>
</P>
<P>

<s docid="LA020489-0060" num="14" wdcount="54"> Other attractions include the appearance of Warren Eckstein, radio host of "Pet Show," who will answer behavioral questions about dogs (as well as cats, pigs and goldfish, if he's asked); free veterinary advice; a demonstration of how 4-H youngsters help train puppies to become guide dogs, and more than 70 vendors selling dog paraphernalia.</s>

<s docid="LA020489-0060" num="15" wdcount="19"> A computer is provided for visitors' use to find out which breeds would best suit their life styles .</s>
</P>
<P>

<s docid="LA020489-0060" num="16" wdcount="8"> Show hours are 8 a.m. to 9 p.m.</s>

<s docid="LA020489-0060" num="17" wdcount="5"> Admission: adults, $4.50; children, $1.</s>

<s docid="LA020489-0060" num="18" wdcount="4"> Information: (818) 789-8350 .</s>
</P>
</TEXT>
<TYPE>
<P>

<s docid="LA020489-0060" num="19" wdcount="1"> Column</s>
</P>
</TYPE>
</DOC>
