<DOC>
<DOCNO>

<s docid="SJMN91-06058250" num="1" wdcount="1"> SJMN91-06058250</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06058250" num="2" wdcount="1"> 06058250</s>
</ACCESS>
<CAPTION>

<s docid="SJMN91-06058250" num="3" wdcount="13"> Photo; PHOTO: William Wegman and one of his constant companions curl up .</s>
</CAPTION>
<DESCRIPT>

<s docid="SJMN91-06058250" num="4" wdcount="5"> NEW-YORK; ARTS; PROFESSIONAL; ANIMAL; PET</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06058250" num="5" wdcount="13"> ON A recent day, the telephone rang in the home of William Wegman.</s>

<s docid="SJMN91-06058250" num="6" wdcount="14"> The photographer, known for his hilarious portraits of his Weimaraners, picked up. "Hello" .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06058250" num="7" wdcount="1"> Living</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06058250" num="8" wdcount="7"> A DOG'S BEST FRIEND IS WILLIAM WEGMAN</s>
</HEADLINE>
<MEMO>

<s docid="SJMN91-06058250" num="9" wdcount="1"> Pets</s>
</MEMO>
<TEXT>

<s docid="SJMN91-06058250" num="10" wdcount="1"> Woof.</s>

<s docid="SJMN91-06058250" num="11" wdcount="9"> In this house, man and dogs speak as one.</s>

<s docid="SJMN91-06058250" num="12" wdcount="5"> Their relationship is unusually tender.</s>

<s docid="SJMN91-06058250" num="13" wdcount="16"> One need only listen while Wegman murmurs to Fay Ray and Battina, her 1 1/2-year-old daughter.</s>

<s docid="SJMN91-06058250" num="14" wdcount="42"> On Valentine's Day, for example, he said, "I'll take them out and play with them longer."; "But I don't want to be known as a dog zombie," said Wegman, who did go to the Westminster Kennel Club Dog Show without the dogs.</s>

<s docid="SJMN91-06058250" num="15" wdcount="10"> "I go to movies and have friends and play sports.</s>

<s docid="SJMN91-06058250" num="16" wdcount="11"> I swim, play tennis and wind surf."; Battina begs to differ.</s>

<s docid="SJMN91-06058250" num="17" wdcount="12"> "When Bill leaves, Batty howls," said Andrea Beeman, an assistant to Wegman.</s>

<s docid="SJMN91-06058250" num="18" wdcount="20"> Man and dog; Their home is one floor of a former Orthodox synagogue on the Lower East Side of Manhattan.</s>

<s docid="SJMN91-06058250" num="19" wdcount="28"> During a recent visit, it was possible to see how the artist gets two even-tempered, relaxed, normal dogs to slip into florid housedresses or scratch each other's backs.</s>

<s docid="SJMN91-06058250" num="20" wdcount="6"> The three simply adore each other.</s>

<s docid="SJMN91-06058250" num="21" wdcount="17"> "I'd never heard of Weimaraners," said the artist, who was born 47 years ago in Longmeadow, Mass.</s>

<s docid="SJMN91-06058250" num="22" wdcount="23"> His life with Weimaraners began in 1970, the year he bought a new video camera and Man Ray, a puppy that cost $35.</s>

<s docid="SJMN91-06058250" num="23" wdcount="13"> Wegman had never photographed dogs before, but Man Ray was a perfect subject.</s>

<s docid="SJMN91-06058250" num="24" wdcount="8"> "He was gray and neutral," the artist said.</s>

<s docid="SJMN91-06058250" num="25" wdcount="25"> "I could do him as a dog, a man, a sculpture, a character, a bat, a frog, an elephant, an Airedale, a dinosaur, a poodle.</s>

<s docid="SJMN91-06058250" num="26" wdcount="51"> I never got tired of him."; A dog's life; Had he been a different breed he would have been a "character actor," Wegman said, "like Lassie."; When Man Ray, who had become world famous, died of cancer in 1981, at the age of 11 years and 8 months, the artist mourned.</s>

<s docid="SJMN91-06058250" num="27" wdcount="18"> "I dreamed that he came back to life," said Wegman, who spent three years living without a dog.</s>

<s docid="SJMN91-06058250" num="28" wdcount="22"> "It was kind of liberating, the years I didn't have a dog."; In 1984, however, he got another Weimaraner, which was stolen.</s>

<s docid="SJMN91-06058250" num="29" wdcount="8"> Yet another dog died of Parvo, a virus.</s>

<s docid="SJMN91-06058250" num="30" wdcount="38"> In 1985, he got Fay Ray, who is now a familiar face not only among artists but among children who watch "Sesame Street."; As a breed, Weimaraners combine "a lap-dog sensibility with a hunting capability," the artist said.</s>

<s docid="SJMN91-06058250" num="31" wdcount="16"> They curl up on his lap, but since they are pointers, they can hold a pose.</s>

<s docid="SJMN91-06058250" num="32" wdcount="8"> They are also good companions for an artist.</s>

<s docid="SJMN91-06058250" num="33" wdcount="3"> They are affectionate.</s>

<s docid="SJMN91-06058250" num="34" wdcount="4"> They do not drool.</s>

<s docid="SJMN91-06058250" num="35" wdcount="3"> They have style.</s>

<s docid="SJMN91-06058250" num="36" wdcount="11"> Like world-famous fashion models, these dogs are lean, supple and fit.</s>

<s docid="SJMN91-06058250" num="37" wdcount="29"> In Wegman's home, which comprises 2,000 square feet with 20-foot-high ceilings, they live a life unencumbered -- one assumes -- by thoughts of fame or fortune, and seldom hunger.</s>

<s docid="SJMN91-06058250" num="38" wdcount="14"> Each morning Wegman feeds them Eukanuba dog food, which he considers the best around.</s>

<s docid="SJMN91-06058250" num="39" wdcount="5"> "It's the highest in protein".</s>

<s docid="SJMN91-06058250" num="40" wdcount="2"> he said.</s>

<s docid="SJMN91-06058250" num="41" wdcount="11"> He often adds a spoonful of plain yogurt or cottage cheese.</s>

<s docid="SJMN91-06058250" num="42" wdcount="7"> The dogs eat again at 6 p.m.</s>

<s docid="SJMN91-06058250" num="43" wdcount="10"> The house is designed for both human and canine comfort.</s>

<s docid="SJMN91-06058250" num="44" wdcount="11"> There is nowhere that Wegman goes that the dogs do not.</s>

<s docid="SJMN91-06058250" num="45" wdcount="9"> The yard is a run of dirt and concrete.</s>

<s docid="SJMN91-06058250" num="46" wdcount="25"> If their master does not play with them, the dogs just scratch, sniff, get bored and go to the door to wait for him .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06058250" num="47" wdcount="5"> ELAINE LOUIE, New York Times</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06058250" num="48" wdcount="1"> USA</s>
</COUNTRY>
<EDITION>

<s docid="SJMN91-06058250" num="49" wdcount="2"> Morning Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06058250" num="50" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06058250" num="51" wdcount="4"> SAN JOSE MERCURY NEWS</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06058250" num="52" wdcount="1"> 910227</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06058250" num="53" wdcount="1"> Wednesday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06058250" num="54" wdcount="1"> February</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06058250" num="55" wdcount="1"> 12D</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06058250" num="56" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06058250" num="57" wdcount="1"> WEST</s>
</REGION>
<FEATURE>

<s docid="SJMN91-06058250" num="58" wdcount="1"> PHOTO</s>
</FEATURE>
<STATE>

<s docid="SJMN91-06058250" num="59" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06058250" num="60" wdcount="1"> 594</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06058250" num="61" wdcount="5"> Wednesday February 27, 1991 00058250,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06058250" num="62" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06058250" num="63" wdcount="1"> 1</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06058250" num="64" wdcount="1"> ENG</s>
</LANGUAGE>
</DOC>
