<DOC>
<DOCNO>

<s docid="SJMN91-06044329" num="1" wdcount="1"> SJMN91-06044329</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06044329" num="2" wdcount="1"> 06044329</s>
</ACCESS>
<CAPTION>

<s docid="SJMN91-06044329" num="3" wdcount="21"> Photo; PHOTO: Cap Carpenter -- Extra; Taffe McFadden, foreground, grooms Rosie, a light miniature poodle, at the McFaddens' Campbell shop; (color)</s>
</CAPTION>
<DESCRIPT>

<s docid="SJMN91-06044329" num="4" wdcount="5"> ANIMAL; CONTEST; PET; SERVICE; BUSINESS</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06044329" num="5" wdcount="7"> It's a dog's life for Bill McFadden.</s>

<s docid="SJMN91-06044329" num="6" wdcount="18"> The 32-year-old professional dog handler knows that the secret to producing champions is just plain, doggone hard work.</s>

<s docid="SJMN91-06044329" num="7" wdcount="10"> He puts in 18-hour days grooming and conditioning his charges.</s>

<s docid="SJMN91-06044329" num="8" wdcount="18"> And, like a racehorse jockey, he crisscrosses the country showing the dogs for a variety of owners .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06044329" num="9" wdcount="2"> Extra 3</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06044329" num="10" wdcount="9"> GROOMING DOGS FOR SUCCESS COUPLE COMB OUT CHAMP CANINES</s>
</HEADLINE>
<MEMO>

<s docid="SJMN91-06044329" num="11" wdcount="4"> Also ran in WT12</s>
</MEMO>
<TEXT>

<s docid="SJMN91-06044329" num="12" wdcount="23"> McFadden and his wife, Taffe, run their dog handling business in Campbell and do it primarily for the enjoyment and satisfaction it brings.</s>

<s docid="SJMN91-06044329" num="13" wdcount="15"> Those who think you can get rich handling dogs are barking up the wrong tree.</s>

<s docid="SJMN91-06044329" num="14" wdcount="14"> "We make a good living but the overhead is high and the hours long.</s>

<s docid="SJMN91-06044329" num="15" wdcount="20"> Before a show we sometimes work around the clock brushing and cleaning the dogs, working on their coats," said McFadden.</s>

<s docid="SJMN91-06044329" num="16" wdcount="35"> "And breeds such as poodles have to be highly trimmed."; McFadden said he handles an average of 20 to 25 dogs at each show and works around 120 shows a year all over the U.S.</s>

<s docid="SJMN91-06044329" num="17" wdcount="14"> The dogs are frequent winners in best of breed and best of show categories.</s>

<s docid="SJMN91-06044329" num="18" wdcount="11"> "We finish with close to 100 champions a year," he said.</s>

<s docid="SJMN91-06044329" num="19" wdcount="11"> As a handler, McFadden emphasizes that he doesn't do obedience training.</s>

<s docid="SJMN91-06044329" num="20" wdcount="15"> His job is to trim and condition the dogs and prepare them physically and mentally.</s>

<s docid="SJMN91-06044329" num="21" wdcount="15"> The aim, he said, is to have a "confident and happy dog" entering a competition.</s>

<s docid="SJMN91-06044329" num="22" wdcount="22"> Over the last seven years, McFadden and his wife have shown dogs representing approximately 75 percent of the 135 breeds of dog.</s>

<s docid="SJMN91-06044329" num="23" wdcount="22"> Taffe McFadden, a Vancouver, British Columbia native who has been involved in dog handling since she was a child, specializes in poodles.</s>

<s docid="SJMN91-06044329" num="24" wdcount="12"> The couple also owns two standard poodles and breed wire fox terriers.</s>

<s docid="SJMN91-06044329" num="25" wdcount="35"> McFadden's latest product, a Kerry blue terrier named Kerrageen's Hotspur, won the best of show prize at the 81st Golden Gate Kennel Club Dog Show held Feb. 2-3 at the Cow Palace in San Francisco.</s>

<s docid="SJMN91-06044329" num="26" wdcount="10"> More than 2,000 purebred dogs participated in the national competition.</s>

<s docid="SJMN91-06044329" num="27" wdcount="21"> It was the 37th best in show win by Kerrageen's Hotspur, making him the top Kerry blue terrier of all time.</s>

<s docid="SJMN91-06044329" num="28" wdcount="12"> The dog is owned by Bryan Percy and Judy Hertwell of Seattle.</s>

<s docid="SJMN91-06044329" num="29" wdcount="24"> Kerrageen's Hotspur was scheduled to join McFadden in New York City last week for the Westminster Kennel Club Dog Show at Madison Square Garden.</s>

<s docid="SJMN91-06044329" num="30" wdcount="32"> Recognized as one of the most prestigious shows in all of dogdom, Westminster is also, with the exception of the Kentucky Derby, the longest continuous sporting event held in the U.S .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06044329" num="31" wdcount="6"> MICHAEL CRONK, Mercury News Staff Writer</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06044329" num="32" wdcount="1"> USA</s>
</COUNTRY>
<EDITION>

<s docid="SJMN91-06044329" num="33" wdcount="2"> Morning Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06044329" num="34" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06044329" num="35" wdcount="4"> SAN JOSE MERCURY NEWS</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06044329" num="36" wdcount="1"> 910213</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06044329" num="37" wdcount="1"> Wednesday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06044329" num="38" wdcount="1"> February</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06044329" num="39" wdcount="1"> 1</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06044329" num="40" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06044329" num="41" wdcount="1"> WEST</s>
</REGION>
<FEATURE>

<s docid="SJMN91-06044329" num="42" wdcount="1"> PHOTO</s>
</FEATURE>
<STATE>

<s docid="SJMN91-06044329" num="43" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06044329" num="44" wdcount="1"> 442</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06044329" num="45" wdcount="5"> Wednesday February 13, 1991 00044329,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06044329" num="46" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06044329" num="47" wdcount="1"> 1</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06044329" num="48" wdcount="1"> ENG</s>
</LANGUAGE>
</DOC>
