<DOC>
<DOCNO>

<s docid="WSJ890726-0004" num="1" wdcount="1"> WSJ890726-0004</s>
</DOCNO>
<DD>

<s docid="WSJ890726-0004" num="2" wdcount="2"> = 890726</s>
</DD>
<AN>

<s docid="WSJ890726-0004" num="3" wdcount="2"> 890726-0004 .</s>
</AN>
<HL>

<s docid="WSJ890726-0004" num="4" wdcount="27"> It's the Same Way in Any Business: @ Retiring Early Is Rarely Optional @ ---- @ By Robert Daniels @ Staff Reporter of The Wall Street Journal</s>
</HL>
<DD>

<s docid="WSJ890726-0004" num="5" wdcount="1"> 07/26/89</s>
</DD>
<SO>

<s docid="WSJ890726-0004" num="6" wdcount="4"> WALL STREET JOURNAL (J)</s>
</SO>
<DATELINE>

<s docid="WSJ890726-0004" num="7" wdcount="2"> NEW YORK</s>
</DATELINE>
<TEXT>

<s docid="WSJ890726-0004" num="8" wdcount="1"> Walk.</s>

<s docid="WSJ890726-0004" num="9" wdcount="2"> Sit. Stay.</s>

<s docid="WSJ890726-0004" num="10" wdcount="2"> Roll over.</s>

<s docid="WSJ890726-0004" num="11" wdcount="3"> Go to court.</s>

<s docid="WSJ890726-0004" num="12" wdcount="16"> Such is the life of one German short-haired pointer, a show dog bearing the name CH.</s>

<s docid="WSJ890726-0004" num="13" wdcount="4"> Robin Crest Lorien Corniche.</s>

<s docid="WSJ890726-0004" num="14" wdcount="11"> Cory, as he is called for short, isn't any run-of-the-litter critter.</s>

<s docid="WSJ890726-0004" num="15" wdcount="2"> The "CH".</s>

<s docid="WSJ890726-0004" num="16" wdcount="6"> in his name stands for champion.</s>

<s docid="WSJ890726-0004" num="17" wdcount="17"> He has won 245 show awards as Best of Breed and 19 awards as Best in Show.</s>

<s docid="WSJ890726-0004" num="18" wdcount="10"> Basically, his problem comes from serving more than one master.</s>

<s docid="WSJ890726-0004" num="19" wdcount="20"> One of the dog's three owners thinks the kennel-club world has seen enough of Cory, who is four years old.</s>

<s docid="WSJ890726-0004" num="20" wdcount="12"> The other two owners think he has plenty of prizes still ahead.</s>

<s docid="WSJ890726-0004" num="21" wdcount="40"> In what is fast becoming a pit-bull match, the one owner, Anthony Attalla, is suing the other two, John and Rita Remondi, charging that they have been showing Cory even though he is officially retired (as announced in Dog News).</s>

<s docid="WSJ890726-0004" num="22" wdcount="34"> In the suit, filed in federal district court in Manhattan, Mr. Attalla says, "Cory has achieved the pinnacle of success . . . and any further competition would only diminish what he has accomplished".</s>

<s docid="WSJ890726-0004" num="23" wdcount="12"> Mr. Attalla claims that his work with Cory is no gravy train.</s>

<s docid="WSJ890726-0004" num="24" wdcount="33"> In the suit, he says that under the owners' agreement he lays out fees and other expenses for showing the animal and he decides when to show -- or to retire -- Cory.</s>

<s docid="WSJ890726-0004" num="25" wdcount="14"> So far, Mr. Attalla says, he's spent over $125,000, the amount sought in damages.</s>

<s docid="WSJ890726-0004" num="26" wdcount="10"> In return, he is entitled to all ribbons and awards.</s>

<s docid="WSJ890726-0004" num="27" wdcount="10"> The Remondis are in charge of caring for the dog.</s>

<s docid="WSJ890726-0004" num="28" wdcount="12"> Despite the retirement, the suit says, the Remondis showed Cory twice recently.</s>

<s docid="WSJ890726-0004" num="29" wdcount="9"> (He placed fourth and then didn't place at all).</s>

<s docid="WSJ890726-0004" num="30" wdcount="11"> For now, a judge's order temporarily bars them from further shows.</s>

<s docid="WSJ890726-0004" num="31" wdcount="32"> In a memo filed in court, Mr. Remondi claims that Mr. Attalla retired the dog "simply and solely to better" the chances that Mr. Attalla's agent would win with a rival Rover.</s>

<s docid="WSJ890726-0004" num="32" wdcount="28"> The Remondis also say Mr. Attalla has bought a Rottweiler to show in another category and doesn't want to spend money on both Cory and the other dog.</s>

<s docid="WSJ890726-0004" num="33" wdcount="14"> They claim that Mr. Attalla has breached the pact by not paying certain expenses.</s>

<s docid="WSJ890726-0004" num="34" wdcount="6"> Stud fees are also at issue.</s>

<s docid="WSJ890726-0004" num="35" wdcount="29"> The Remondis argue that the retirement "fraudulently" deprives them of their opportunity to show Cory, a dog who they assert "is in the best condition of his life" .</s>
</TEXT>
</DOC>
