<DOC>
<DOCNO>

<s docid="FT931-2858" num="1" wdcount="1"> FT931-2858</s>
</DOCNO>
<PROFILE>

<s docid="FT931-2858" num="2" wdcount="1"> _AN-DCRCHACTFT</s>
</PROFILE>
<DATE>

<s docid="FT931-2858" num="3" wdcount="1"> 930318</s>
</DATE>
<HEADLINE>

<s docid="FT931-2858" num="4" wdcount="27"> FT 18 MAR 93 / World Stock Markets: Bombs rock Bombay in budget aftermath - RC Murthy on a market which has seen speculation, and savage disappointment</s>
</HEADLINE>
<BYLINE>

<s docid="FT931-2858" num="5" wdcount="3"> By RC MURTHY</s>
</BYLINE>
<TEXT>

<s docid="FT931-2858" num="6" wdcount="24"> The 29-storey Jijobhoy Towers, home of the Bombay Stock Exchange, was rocked by two powerful bombs last Friday, leaving 60 dead and 200 injured.</s>

<s docid="FT931-2858" num="7" wdcount="12"> The market reopened on Monday in an attempt to return to normal.</s>

<s docid="FT931-2858" num="8" wdcount="30"> It has had to compromise - trading has been restricted to an hour a day, and dealing has moved back to the traditional ring, where it stopped a year ago.</s>

<s docid="FT931-2858" num="9" wdcount="17"> Dealers seemed to like this, the BSE index rising by 5.6 per cent on Monday and Tuesday.</s>

<s docid="FT931-2858" num="10" wdcount="23"> But another bomb blast in Calcutta triggered nervous selling yesterday, and the index came back by 50.62, or 2.1 per cent, to 2,409.23.</s>

<s docid="FT931-2858" num="11" wdcount="44"> All this has taken place against a volatile background: the Bombay equity market, over the past six weeks or so, has had to contend first with unusually bullish speculation, before the national budget on February 27, and subsequently with some savage expressions of disappointment.</s>

<s docid="FT931-2858" num="12" wdcount="18"> Dr Manmohan Singh, the Indian finance minister, disappointed traders in the budget at the end of last month.</s>

<s docid="FT931-2858" num="13" wdcount="19"> He postponed corporate tax reforms by a year, denying hopes of a tax cut recommended by an expert group.</s>

<s docid="FT931-2858" num="14" wdcount="28"> He did reduce excise and import duties on a broad front, but left out the cement and steel sectors, where share prices had been boosted by pre-budget speculation.</s>

<s docid="FT931-2858" num="15" wdcount="20"> To top it all, Dr Singh refused to equate domestic investors with their overseas counterparts in taxing short-term capital gains.</s>

<s docid="FT931-2858" num="16" wdcount="28"> He lowered the tax to 30 per cent from 65 per cent for expatriate Indians and foreign investors but for local investors it remained at 44.5 per cent.</s>

<s docid="FT931-2858" num="17" wdcount="19"> Taking the tax concessions for granted, traders had driven up share prices in February to make a kill later.</s>

<s docid="FT931-2858" num="18" wdcount="9"> Instead, the budget turned out to be a nightmare.</s>

<s docid="FT931-2858" num="19" wdcount="38"> While industry and business welcomed the statement which, for once, did not propose any new tax, Professor Rusi Taraporewala, the stock market theorist and academic, said a reduction in import duties would leave corporate profits ex-growth this year.</s>

<s docid="FT931-2858" num="20" wdcount="30"> The relative lack of financial concessions meant that disappointed traders sold with a vengeance and, until the weekend, the market seemed bottomless as equity prices plummeted to a 13-month low.</s>

<s docid="FT931-2858" num="21" wdcount="38"> Overseas investors fuelled the downtrend as they sold some half a million shares of Reliance Industries, arbitraging between the share price on the Bombay stock exchange and the market price of its Euro-issue of global depository receipts (GDRs).</s>

<s docid="FT931-2858" num="22" wdcount="20"> The opportunity arose after a change in Indian regulations which allows international investors to convert GDRs into the underlying stock.</s>

<s docid="FT931-2858" num="23" wdcount="23"> At the current conversion rate of Rs31 per US dollar, the Reliance GDR fetched Rs170 per share against the BSE quotation of Rs210.</s>

<s docid="FT931-2858" num="24" wdcount="24"> The BSE 30-share index plunged by more than one-fifth to 2,287 on March 10, from 2,893 at the post-budget trading session on February 27.</s>

<s docid="FT931-2858" num="25" wdcount="27"> Share prices rebounded last week, taking the index to 2,361 and the uptrend, on balance, has continued this week in spite of the bomb blast on Friday.</s>

<s docid="FT931-2858" num="26" wdcount="22"> Whether or not the surge will turn into a strong rally will depend on the ability of bulls to maintain their momentum.</s>

<s docid="FT931-2858" num="27" wdcount="31"> They are hoping that foreign portfolio investment will pick up with the restoration of trading after 'Black Friday', and the successful sale of Reliance stock on the BSE by international investors.</s>

<s docid="FT931-2858" num="28" wdcount="32"> The Indian stock markets have been passing through a series of crises since December, when activists of the Bhartiya Janta party pulled down the Babri mosque at Ayodhya, sparking off communal riots.</s>

<s docid="FT931-2858" num="29" wdcount="14"> Mr Mark Bulloch of Jardine Fleming takes the domestic political situation in his stride.</s>

<s docid="FT931-2858" num="30" wdcount="13"> 'Nothing dramatic has happened as far as foreign investors are concerned,' he says.</s>

<s docid="FT931-2858" num="31" wdcount="6"> 'They are appraising the political situation'.</s>

<s docid="FT931-2858" num="32" wdcount="12"> In the meantime, there is no compulsion for local investors to sell.</s>

<s docid="FT931-2858" num="33" wdcount="34"> In this, they are more fortunate than they were in previous years, when they were under pressure to take advantage of a long-term capital gains tax exemption before the financial year ended in March.</s>

<s docid="FT931-2858" num="34" wdcount="27"> The exemption has been replaced by a flat 20 per cent tax this year which, according to dealers, puts bulls and bears on an even footing .</s>
</TEXT>
<XX>

<s docid="FT931-2858" num="35" wdcount="1"> Countries:-</s>
</XX>
<CN>

<s docid="FT931-2858" num="36" wdcount="4"> INZ India, Asia .</s>
</CN>
<XX>

<s docid="FT931-2858" num="37" wdcount="1"> Industries:-</s>
</XX>
<IN>

<s docid="FT931-2858" num="38" wdcount="6"> P6231 Security and Commodity Exchanges .</s>
</IN>
<XX>

<s docid="FT931-2858" num="39" wdcount="1"> Types:-</s>
</XX>
<TP>

<s docid="FT931-2858" num="40" wdcount="4"> CMMT Comment & Analysis.</s>

<s docid="FT931-2858" num="41" wdcount="4"> MKTS Market data .</s>
</TP>
<PUB>

<s docid="FT931-2858" num="42" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT931-2858" num="43" wdcount="3"> London Page 39</s>
</PAGE>
</DOC>
