<DOC>
<DOCNO>

<s docid="FT931-3764" num="1" wdcount="1"> FT931-3764</s>
</DOCNO>
<PROFILE>

<s docid="FT931-3764" num="2" wdcount="1"> _AN-DCNAOAEXFT</s>
</PROFILE>
<DATE>

<s docid="FT931-3764" num="3" wdcount="1"> 930313</s>
</DATE>
<HEADLINE>

<s docid="FT931-3764" num="4" wdcount="21"> FT 13 MAR 93 / Bombay blasts leave 200 dead: Federal troops flown in after wave of bombings on commercial targets</s>
</HEADLINE>
<BYLINE>

<s docid="FT931-3764" num="5" wdcount="5"> By ALEXANDER NICOLL, Asia Editor</s>
</BYLINE>
<TEXT>

<s docid="FT931-3764" num="6" wdcount="31"> THE INDIAN government flew federal paramilitary troops into Bombay last night after more than a dozen bombs exploded in the city, killing about 200 people and injuring more than a thousand.</s>

<s docid="FT931-3764" num="7" wdcount="15"> The devices, mostly car bombs, appeared to be a systematic attack on India's commercial heart.</s>

<s docid="FT931-3764" num="8" wdcount="8"> All exploded within 90 minutes in the afternoon.</s>

<s docid="FT931-3764" num="9" wdcount="22"> Among the targets were the Bombay Stock Exchange, the landmark Air India building, a shopping complex, and two hotels near the airport.</s>

<s docid="FT931-3764" num="10" wdcount="33"> The identity of the bombers was unknown, but the attacks were a severe setback to India's attempts to heal the wounds created by recent intercommunal violence, which has caused deep shock throughout India.</s>

<s docid="FT931-3764" num="11" wdcount="29"> More than 2,000 people died in riots, including over 700 in Bombay, after the razing of a mosque at Ayodhya in northern India by Hindu zealots on December 6.</s>

<s docid="FT931-3764" num="12" wdcount="34"> The bombs appeared designed to stir a renewal of communal strife and to undermine efforts by the government of Mr PV Narasimha Rao to open up the economy and attract foreign investment and tourism.</s>

<s docid="FT931-3764" num="13" wdcount="29"> One of the targets was close to the headquarters of Shiv Sena, a Hindu nationalist party accused of fomenting violence during the riots, in which most victims were Moslems.</s>

<s docid="FT931-3764" num="14" wdcount="18"> National and local state leaders appealed for calm in an attempt to prevent a renewed outbreak of violence.</s>

<s docid="FT931-3764" num="15" wdcount="15"> Mr Rao urged the nation to ignore rumours after the 'inhuman and criminal bomb blasts'.</s>

<s docid="FT931-3764" num="16" wdcount="29"> Mr Sharad Pawar, the former federal defence minister just re-appointed chief minister of Maharashtra state, said all roads into Bombay had been blocked and the army put on alert.</s>

<s docid="FT931-3764" num="17" wdcount="23"> He said: 'It is aimed at disrupting the economy and it appears a conscious effort because only Bombay seems to be the target'.</s>

<s docid="FT931-3764" num="18" wdcount="18"> Mr Shankarrao Chavan, the federal home (interior) minister, told parliament in New Delhi: 'We suspect an international conspiracy'.</s>

<s docid="FT931-3764" num="19" wdcount="23"> The Indian High Commission in London said the attacks were 'part of the externally supported terrorism which has targeted India for some time'.</s>

<s docid="FT931-3764" num="20" wdcount="12"> However, Indian officials stopped short of directly accusing Pakistan, the country's arch-enemy.</s>

<s docid="FT931-3764" num="21" wdcount="30"> The bomb attacks were spread throughout the city and were clearly aimed at the city's better-off business people - in contrast to the riots in which victims were mainly poor.</s>

<s docid="FT931-3764" num="22" wdcount="35"> At the 28-storey stock exchange building, about 3,000 people were on the second-storey trading floor when a bomb exploded in the underground car park, hurling shards of glass across the floor and into the street.</s>

<s docid="FT931-3764" num="23" wdcount="9"> Some victims were crushed in the stampede to escape.</s>

<s docid="FT931-3764" num="24" wdcount="10"> Outside, burned bodies lay among litter from shattered buildings .</s>
</TEXT>
<XX>

<s docid="FT931-3764" num="25" wdcount="1"> Countries:-</s>
</XX>
<CN>

<s docid="FT931-3764" num="26" wdcount="4"> INZ India, Asia .</s>
</CN>
<XX>

<s docid="FT931-3764" num="27" wdcount="1"> Industries:-</s>
</XX>
<IN>

<s docid="FT931-3764" num="28" wdcount="7"> P9229 Public Order and Safety, NEC .</s>
</IN>
<XX>

<s docid="FT931-3764" num="29" wdcount="1"> Types:-</s>
</XX>
<TP>

<s docid="FT931-3764" num="30" wdcount="3"> PEOP Personnel News.</s>

<s docid="FT931-3764" num="31" wdcount="4"> GOVT Legal issues .</s>
</TP>
<PUB>

<s docid="FT931-3764" num="32" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT931-3764" num="33" wdcount="3"> London Page 24</s>
</PAGE>
</DOC>
