<DOC>
<DOCNO>

<s docid="FT931-2981" num="1" wdcount="1"> FT931-2981</s>
</DOCNO>
<PROFILE>

<s docid="FT931-2981" num="2" wdcount="1"> _AN-DCRCHAHVFT</s>
</PROFILE>
<DATE>

<s docid="FT931-2981" num="3" wdcount="1"> 930317</s>
</DATE>
<HEADLINE>

<s docid="FT931-2981" num="4" wdcount="10"> FT 17 MAR 93 / Explosion kills 45 in Calcutta</s>
</HEADLINE>
<BYLINE>

<s docid="FT931-2981" num="5" wdcount="4"> By Our Foreign Staff</s>
</BYLINE>
<TEXT>

<s docid="FT931-2981" num="6" wdcount="35"> INDIA suffered a fresh wave of terror last night when an explosion destroyed two blocks of flats in the centre of the city of Calcutta, killing at least 45 people and injuring scores of others.</s>

<s docid="FT931-2981" num="7" wdcount="33"> Police said a bomb exploded in the crowded trade and residential district of Bowbazaar shortly after midnight, causing two blocks of flats to collapse and trapping up to 70 people in the rubble.</s>

<s docid="FT931-2981" num="8" wdcount="42"> The identity of the bombers was unknown but the explosion comes just five days after over 250 people were killed and at least 1,200 injured in a series of bomb attacks aimed at the heart of the Indian business capital of Bombay.</s>

<s docid="FT931-2981" num="9" wdcount="38"> A militant Sikh group fighting for independence for the Indian state of Punjab has claimed responsibility for the Bombay blasts, but police are unconvinced, saying they were carried out by a foreign group in connivance with 'local criminals'.</s>

<s docid="FT931-2981" num="10" wdcount="37"> In what many interpreted as a reference to Pakistan, with whom India has fought three wars, last week Mr Shankarrao Chavan, the federal home (interior) minister, told parliament in New Delhi that he suspected 'an international conspiracy'.</s>

<s docid="FT931-2981" num="11" wdcount="33"> Most of the estimated 125 people living in the Calcutta flats were in their beds when the blast occurred, setting fire to both buildings, according to officials in the city's central control room.</s>

<s docid="FT931-2981" num="12" wdcount="12"> At least 45 people were dead on arrival at hospital, they said.</s>

<s docid="FT931-2981" num="13" wdcount="23"> Last Friday a series of car bombs exploded in Bombay in what the government described as a systematic attack on India's commercial heart.</s>

<s docid="FT931-2981" num="14" wdcount="22"> Among the targets were the Bombay Stock Exchange, the landmark Air India building, a shopping complex, and two hotels near the airport.</s>

<s docid="FT931-2981" num="15" wdcount="28"> The attacks in Calcutta and Bombay are a severe setback to attempts to heal the wounds created by recent intercommunal violence, which has caused deep shock throughout India.</s>

<s docid="FT931-2981" num="16" wdcount="29"> More than 2,000 people died in riots, including over 700 in Bombay, after the razing of a mosque at Ayodhya in northern India by Hindu zealots on December 6.</s>

<s docid="FT931-2981" num="17" wdcount="39"> Some fear the wave of bomb attacks is designed to stir a renewal of communal strife and undermine efforts by the government of Mr P V Narasimha Rao to open up the economy and attract foreign investment and tourism.</s>

<s docid="FT931-2981" num="18" wdcount="20"> Last night national and local state leaders appealed for calm in an attempt to prevent a renewed outbreak of violence.</s>

<s docid="FT931-2981" num="19" wdcount="15"> Mr Rao urged the nation to ignore rumours after the 'inhuman and criminal blast' .</s>
</TEXT>
<XX>

<s docid="FT931-2981" num="20" wdcount="1"> Countries:-</s>
</XX>
<CN>

<s docid="FT931-2981" num="21" wdcount="4"> INZ India, Asia .</s>
</CN>
<XX>

<s docid="FT931-2981" num="22" wdcount="1"> Industries:-</s>
</XX>
<IN>

<s docid="FT931-2981" num="23" wdcount="7"> P9229 Public Order and Safety, NEC .</s>
</IN>
<XX>

<s docid="FT931-2981" num="24" wdcount="1"> Types:-</s>
</XX>
<TP>

<s docid="FT931-2981" num="25" wdcount="4"> GOVT Legal issues .</s>
</TP>
<PUB>

<s docid="FT931-2981" num="26" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT931-2981" num="27" wdcount="3"> London Page 4</s>
</PAGE>
</DOC>
