<DOC>
<DOCNO>

<s docid="FT931-3664" num="1" wdcount="1"> FT931-3664</s>
</DOCNO>
<PROFILE>

<s docid="FT931-3664" num="2" wdcount="1"> _AN-DCOCJAB3FT</s>
</PROFILE>
<DATE>

<s docid="FT931-3664" num="3" wdcount="1"> 930315</s>
</DATE>
<HEADLINE>

<s docid="FT931-3664" num="4" wdcount="23"> FT 15 MAR 93 / Bombay stays calm in the face of horror: The city seems determined to put Friday's outrage behind it</s>
</HEADLINE>
<BYLINE>

<s docid="FT931-3664" num="5" wdcount="3"> By STEFAN WAGSTYL</s>
</BYLINE>
<TEXT>

<s docid="FT931-3664" num="6" wdcount="47"> MR TEG BAHADUR Thapar was serving lunch from his stall outside the Bombay stock exchange on Friday when he was showered with flying glass and broken concrete in one of 13 explosions which rocked the city and left at least 255 people killed and over 1,200 injured.</s>

<s docid="FT931-3664" num="7" wdcount="11"> 'I'm lucky to be alive,' he said from his hospital bed.</s>

<s docid="FT931-3664" num="8" wdcount="3"> 'Who did this?</s>

<s docid="FT931-3664" num="9" wdcount="6"> Who can stop this happening again'?</s>

<s docid="FT931-3664" num="10" wdcount="11"> Across Bombay people were asking themselves the same questions this weekend.</s>

<s docid="FT931-3664" num="11" wdcount="20"> They sensed there was an enormous difference from the riots which scarred the city in December and again in January.</s>

<s docid="FT931-3664" num="12" wdcount="24"> Those were caused by a traditional mix of crime, political agitation and ancient Hindu-Moslem hatreds stirred by the destruction of the mosque in Ayodhya.</s>

<s docid="FT931-3664" num="13" wdcount="12"> The weapons used were mostly primitive - knives, clubs and petrol bottles.</s>

<s docid="FT931-3664" num="14" wdcount="22"> Friday's outrage, by contrast, bears the deadly stamp of high-technology terrorism, complete with Semtex plastic explosive, high-grade timers, efficient organisation and money.</s>

<s docid="FT931-3664" num="15" wdcount="24"> The only comparable previous incident was the assassination in 1991 of Mr Rajiv Gandhi, the former prime minister, by Sri Lanka's Tamil Tiger terrorists.</s>

<s docid="FT931-3664" num="16" wdcount="23"> But that was a single bomb aimed at one man - the explosions in Bombay were designed to terrorise the nation's commercial capital.</s>

<s docid="FT931-3664" num="17" wdcount="9"> Bombay accounts for 35 per cent of India's exports.</s>

<s docid="FT931-3664" num="18" wdcount="17"> Mr P V Narasimha Rao, the prime minister, described the blasts as an attack on India's economy.</s>

<s docid="FT931-3664" num="19" wdcount="26"> The immediate assumption both at the highest level and in the streets of Bombay was that those responsible must have been foreigners or had foreign help.</s>

<s docid="FT931-3664" num="20" wdcount="54"> But these suggestions were seen in Bombay as a deliberate attempt to deflect attention from the people who in the popular mind are the real suspects - Moslem extremists who might have taken revenge for the riots which hit India after the Ayodhya mosque's destruction and which left 2,000 dead, including 700 in Bombay.</s>

<s docid="FT931-3664" num="21" wdcount="26"> If Moslems are found to have staged the attacks, the Indian authorities will certainly suspect that the operation was supported from a Moslem country, notably Pakistan.</s>

<s docid="FT931-3664" num="22" wdcount="5"> The implications would be vast.</s>

<s docid="FT931-3664" num="23" wdcount="15"> Breaking diplomatic relations would be the minimum step Delhi could take on a dangerous road.</s>

<s docid="FT931-3664" num="24" wdcount="25"> Mr Rao chose his words carefully during his visit to Bombay: 'There is a definite possibility that our search may not stop within the country.</s>

<s docid="FT931-3664" num="25" wdcount="17"> I do not want to name anybody because it will have ramifications within and outside the country'.</s>

<s docid="FT931-3664" num="26" wdcount="14"> There is no evidence linking the attacks to Moslem extremists, let alone to Pakistan.</s>

<s docid="FT931-3664" num="27" wdcount="21"> Even if Moslem groups are found to be responsible for the bombings, they could have been supplied from other Moslem countries.</s>

<s docid="FT931-3664" num="28" wdcount="13"> India would still face a diplomatic crisis but hardly on the same scale.</s>

<s docid="FT931-3664" num="29" wdcount="18"> For the moment, such concerns seem remote from the streets on Bombay, where the atmosphere yesterday was calm.</s>

<s docid="FT931-3664" num="30" wdcount="15"> Workmen were clearing away rubble at the blast sites, including the blackened stock exchange building.</s>

<s docid="FT931-3664" num="31" wdcount="9"> Bombayites seemed determined to put the outrage behind them.</s>

<s docid="FT931-3664" num="32" wdcount="23"> At the Gymkhana Club and dozens of other sports grounds, hundreds of men and boys were playing cricket as they do every Sunday.</s>

<s docid="FT931-3664" num="33" wdcount="14"> Others were walking along the seafront by the arch of the Gateway of India.</s>

<s docid="FT931-3664" num="34" wdcount="27"> The stock exchange authorities plan to re-start trading as soon as they can -probably today - using an old trading floor the exchange vacated only last year.</s>

<s docid="FT931-3664" num="35" wdcount="23"> Businessmen estimated the main loss to the city would be the loss of life and injuries and the damage caused to blasted buildings.</s>

<s docid="FT931-3664" num="36" wdcount="15"> They did not expect the same widespread disruption to production as occurred during the riots.</s>

<s docid="FT931-3664" num="37" wdcount="27"> Some of the credit for the limited disruption should go the government and the police for promptly calling paramilitary and regular troops to help patrol sensitive districts.</s>

<s docid="FT931-3664" num="38" wdcount="27"> But much more should go to the people of Bombay, who, so far at least, have refused to be goaded into violent protest by the bombers .</s>
</TEXT>
<XX>

<s docid="FT931-3664" num="39" wdcount="1"> Countries:-</s>
</XX>
<CN>

<s docid="FT931-3664" num="40" wdcount="4"> INZ India, Asia .</s>
</CN>
<XX>

<s docid="FT931-3664" num="41" wdcount="1"> Industries:-</s>
</XX>
<IN>

<s docid="FT931-3664" num="42" wdcount="3"> P8661 Religious Organizations.</s>

<s docid="FT931-3664" num="43" wdcount="7"> P9229 Public Order and Safety, NEC .</s>
</IN>
<XX>

<s docid="FT931-3664" num="44" wdcount="1"> Types:-</s>
</XX>
<TP>

<s docid="FT931-3664" num="45" wdcount="3"> PEOP Personnel News.</s>

<s docid="FT931-3664" num="46" wdcount="4"> GOVT Government News .</s>
</TP>
<PUB>

<s docid="FT931-3664" num="47" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT931-3664" num="48" wdcount="3"> London Page 5</s>
</PAGE>
</DOC>
