<DOC>
<DOCNO>

<s docid="FT931-4176" num="1" wdcount="1"> FT931-4176</s>
</DOCNO>
<PROFILE>

<s docid="FT931-4176" num="2" wdcount="1"> _AN-DCLBZAA9FT</s>
</PROFILE>
<DATE>

<s docid="FT931-4176" num="3" wdcount="1"> 930312</s>
</DATE>
<HEADLINE>

<s docid="FT931-4176" num="4" wdcount="11"> FT 12 MAR 93 / Indian stock market denies flouting rules</s>
</HEADLINE>
<BYLINE>

<s docid="FT931-4176" num="5" wdcount="6"> By STEFAN WAGSTYL and RC MURTHY</s>
</BYLINE>
<DATELINE>

<s docid="FT931-4176" num="6" wdcount="1"> BOMBAY</s>
</DATELINE>
<TEXT>

<s docid="FT931-4176" num="7" wdcount="33"> A ROW has erupted between the Bombay stock exchange, India's largest stock market, and the Securities and Exchange Board of India, the securities watchdog, over the board's recent first-ever inspection of stockbrokers' books.</s>

<s docid="FT931-4176" num="8" wdcount="27"> The Sebi has accused stockbrokers of flouting the exchange's rules, including regulations on margin trading designed to limit the risk of members defaulting through excessive speculative investments.</s>

<s docid="FT931-4176" num="9" wdcount="16"> It has also accused the exchange authorities of failing to enforce rules and of poor administration.</s>

<s docid="FT931-4176" num="10" wdcount="19"> The stock exchange denied the allegations, saying they were 'baseless, made out of context and blown out of proportion'.</s>

<s docid="FT931-4176" num="11" wdcount="49"> The argument will do nothing to restore investors' faith in the stock market where, as measured by the Bombay stock exchange's 30-share index, shares have fallen 48 per cent from their peak early last year, including a 320 points fall since the government's budget was announced two weeks ago.</s>

<s docid="FT931-4176" num="12" wdcount="6"> Yesterday the index closed at 2330.</s>

<s docid="FT931-4176" num="13" wdcount="28"> Foreign investors, who are being wooed by India as a source of much-needed capital, will also be concerned at the latest allegations of poor management at the exchange.</s>

<s docid="FT931-4176" num="14" wdcount="46"> In one of its most damaging passages, the inspectors' report alleges that D S Prabhoodas, a leading firm headed by Mr Hemendra Kothari, a former BSE president, and by Mr Jaswant Chotalal, a member of the BSE's governing body, avoided margin payments totalling Rs185.4m (Pounds 4.08m).</s>

<s docid="FT931-4176" num="15" wdcount="27"> Mr Kothari said yesterday that most of the transactions covered by the report were off-exchange deals directly between financial institutions for which margin payments were not required.</s>

<s docid="FT931-4176" num="16" wdcount="16"> Mr M R Mayya, the BSE's executive director, said BSE rules permitted such bilateral off-exchange transactions.</s>

<s docid="FT931-4176" num="17" wdcount="12"> Sebi also accused the exchange of mismanaging the administration of its building.</s>

<s docid="FT931-4176" num="18" wdcount="24"> This week's argument is only the latest in a series of disputes which began almost as soon as Sebi started operations a year ago.</s>

<s docid="FT931-4176" num="19" wdcount="17"> It was established by Mr Manmohan Singh, the finance minister, as a crucial element in financial reform.</s>

<s docid="FT931-4176" num="20" wdcount="12"> Brokers claim the Sebi is heavy-handed and fails to understand their needs.</s>

<s docid="FT931-4176" num="21" wdcount="22"> They say rules must be applied flexibly and many firms are extremely small and unable to carry the cost of extra regulations.</s>

<s docid="FT931-4176" num="22" wdcount="21"> But the finance minister is backing Sebi to the hilt and singled it out for praise in his recent budget speech.</s>

<s docid="FT931-4176" num="23" wdcount="39"> Finance ministry officials believe loose regulations allow brokers and others to dodge taxes and also contributed to last year's securities market scandal in which banks, including the UK's Standard Chartered Bank, lost a combined gross total of Rs40bn .</s>
</TEXT>
<XX>

<s docid="FT931-4176" num="24" wdcount="1"> Countries:-</s>
</XX>
<CN>

<s docid="FT931-4176" num="25" wdcount="4"> INZ India, Asia .</s>
</CN>
<XX>

<s docid="FT931-4176" num="26" wdcount="1"> Industries:-</s>
</XX>
<IN>

<s docid="FT931-4176" num="27" wdcount="5"> P6231 Security and Commodity Exchanges.</s>

<s docid="FT931-4176" num="28" wdcount="7"> P9651 Regulation of Miscellaneous Commercial Sectors .</s>
</IN>
<XX>

<s docid="FT931-4176" num="29" wdcount="1"> Types:-</s>
</XX>
<TP>

<s docid="FT931-4176" num="30" wdcount="3"> TECH Standards .</s>
</TP>
<PUB>

<s docid="FT931-4176" num="31" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT931-4176" num="32" wdcount="3"> London Page 4</s>
</PAGE>
</DOC>
