<DOC>
<DOCNO>

<s docid="AP891019-0037" num="1" wdcount="1"> AP891019-0037</s>
</DOCNO>
<FILEID>

<s docid="AP891019-0037" num="2" wdcount="2"> AP-NR-10-19-89 0248EDT</s>
</FILEID>
<FIRST>

<s docid="AP891019-0037" num="3" wdcount="5"> r a PM-Quake-Relief 10-19 0725</s>
</FIRST>
<SECOND>

<s docid="AP891019-0037" num="4" wdcount="1"> PM-Quake-Relief,0754</s>
</SECOND>
<HEAD>

<s docid="AP891019-0037" num="5" wdcount="5"> Relief Pours Into Bay Area</s>
</HEAD>
<BYLINE>

<s docid="AP891019-0037" num="6" wdcount="3"> By ARTHUR ALLEN</s>
</BYLINE>
<BYLINE>

<s docid="AP891019-0037" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<TEXT>

<s docid="AP891019-0037" num="8" wdcount="35"> Private groups and officials from Tokyo to London to Charleston, S.C., offered help to the ruptured San Francisco Bay area, but some said relief for the earthquake could drain coffers already strained by previous disasters.</s>

<s docid="AP891019-0037" num="9" wdcount="30"> Los Angeles, long San Francisco's West Coast competitor but equally at the mercy of the San Andreas Fault, quickly shipped doctors, sonic equipment and fire investigators to the Bay Area.</s>

<s docid="AP891019-0037" num="10" wdcount="31"> The mayor of a sister city in disaster, Charleston's Joseph P. Riley Jr., sent a plane load of drinking water, a symbolic return of the support his city got after Hugo.</s>

<s docid="AP891019-0037" num="11" wdcount="19"> ``I know we still have and will have great needs here and charity certainly begins at home,'' Riley said.</s>

<s docid="AP891019-0037" num="12" wdcount="9"> ``However, it would be wrong for this community ...</s>

<s docid="AP891019-0037" num="13" wdcount="17"> not to reach in (our pockets) and contribute to those who are hurt and suffering right now''.</s>

<s docid="AP891019-0037" num="14" wdcount="14"> San Francisco Mayor Art Agnos has estimated damage $2 billion in his city alone.</s>

<s docid="AP891019-0037" num="15" wdcount="29"> The Salvation Army had the food cooking almost before the earth quit shaking in Northern California, while the Red Cross opened the doors and unfolded cots in 25 shelters.</s>

<s docid="AP891019-0037" num="16" wdcount="15"> ``We don't wait for anybody,'' said Col. Leon Ferraez, communications director of the Salvation Army.</s>

<s docid="AP891019-0037" num="17" wdcount="8"> ``We're there the minute the news is on''.</s>

<s docid="AP891019-0037" num="18" wdcount="16"> According to Ferraez, the organization dispatched 12 mobile canteens to the hardest-hit earthquake areas within minutes.</s>

<s docid="AP891019-0037" num="19" wdcount="26"> All Salvation Army centers in the Bay Area, including 34 community service centers and scores of other units, have been turned over to the relief effort.</s>

<s docid="AP891019-0037" num="20" wdcount="14"> Los Angeles donated sonic equipment to help detect sounds of people trapped in rubble.</s>

<s docid="AP891019-0037" num="21" wdcount="18"> And officials in Los Alamos, N.M., dispatched a device used to locate survivors of last year's Armenian quake.</s>

<s docid="AP891019-0037" num="22" wdcount="18"> Israel offered the services of a special army rescue squad that also helped dig out victims in Armenia.</s>

<s docid="AP891019-0037" num="23" wdcount="12"> A French disaster relief agency offered to send special teams of searchers.</s>

<s docid="AP891019-0037" num="24" wdcount="20"> A team of British engineers were to fly to San Francisco today to help assess structural damage from the quake.</s>

<s docid="AP891019-0037" num="25" wdcount="25"> The Bay Area has a large Asian population, and callers from Japan and the Philippines and other countries jammed phone lines trying to reach relatives.</s>

<s docid="AP891019-0037" num="26" wdcount="18"> The Osaka, Japan, city government announced it was sending $10,000 to San Francisco, a sister city since 1957.</s>

<s docid="AP891019-0037" num="27" wdcount="31"> Los Angeles Mayor Tom Bradley sent police and fire investigators to assess damage from the quake, and convened his own emergency council in a special meeting to discuss other possible measures.</s>

<s docid="AP891019-0037" num="28" wdcount="20"> ``I am joining millions of Californians as we intensely watch the damage of the large San Francisco earthquake,'' said Bradley.</s>

<s docid="AP891019-0037" num="29" wdcount="23"> ``We all know the horrors of an earthquake and we express our deep-felt sympathy for the people of the San Francisco Bay area''.</s>

<s docid="AP891019-0037" num="30" wdcount="33"> An Anheuser-Busch Inc. brewery in Fairfield, 35 miles northeast of San Francisco, interrupted normal operations to fill cans with drinking water instead of beer for free shipment to relief agencies, the company said.</s>

<s docid="AP891019-0037" num="31" wdcount="26"> Coast Guard offices across the West Coast provided San Francisco with as many boats and helicopters as could be spared, said Coast Guard spokeswoman Elizabeth Neely.</s>

<s docid="AP891019-0037" num="32" wdcount="37"> The Red Cross sent 290 units of blood from Los Angeles; the San Diego Blood Bank rushed 50 units to San Francisco within an hour of the quake; more than 400 units were sent from Portland, Ore.</s>

<s docid="AP891019-0037" num="33" wdcount="14"> ``Giving makes them feel good,'' said Trudy Sullivan, a Red Cross spokeswoman in Portland.</s>

<s docid="AP891019-0037" num="34" wdcount="28"> Even the Internal Revenue Service got into the act, announcing it would waive penalties for taxpayers unable to file returns or make scheduled payments because of the earthquake.</s>

<s docid="AP891019-0037" num="35" wdcount="21"> President Bush directed $273 million in immediate aid for quake victims and said he would visit the area Friday or Saturday.</s>

<s docid="AP891019-0037" num="36" wdcount="31"> But some officials said the disaster could strain the coffers of private agencies and those of the Federal Emergency Management Agency, which was criticized for its response to the storm-lashed Carolinas.</s>

<s docid="AP891019-0037" num="37" wdcount="23"> The Red Cross began its fiscal year July 1 with $18.5 million in its disaster budget, and had spent 40 percent by September.</s>

<s docid="AP891019-0037" num="38" wdcount="18"> Then Hugo came along, triggering an effort the agency estimates will cost $42 million _ the most ever.</s>

<s docid="AP891019-0037" num="39" wdcount="33"> ``When a major earthquake and a major hurricane hit back-to-back, you can bet it will stretch Red Cross disaster resources and manpower,'' said Bob Vessey, director of disaster services in Washington, D.C .</s>
</TEXT>
</DOC>
