<DOC>
<DOCNO>

<s docid="AP891017-0204" num="1" wdcount="1"> AP891017-0204</s>
</DOCNO>
<FILEID>

<s docid="AP891017-0204" num="2" wdcount="2"> AP-NR-10-17-89 2325EDT</s>
</FILEID>
<FIRST>

<s docid="AP891017-0204" num="3" wdcount="5"> r a AM-Quake-Odds 10-17 0456</s>
</FIRST>
<SECOND>

<s docid="AP891017-0204" num="4" wdcount="1"> AM-Quake-Odds,0468</s>
</SECOND>
<HEAD>

<s docid="AP891017-0204" num="5" wdcount="11"> Area Where Earthquake Hit Seen as Highly Probable in 1988 Report</s>
</HEAD>
<HEAD>

<s docid="AP891017-0204" num="6" wdcount="3"> With AM-SF Quake</s>
</HEAD>
<BYLINE>

<s docid="AP891017-0204" num="7" wdcount="3"> By MICHAEL FLEEMAN</s>
</BYLINE>
<BYLINE>

<s docid="AP891017-0204" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP891017-0204" num="9" wdcount="3"> PASADENA, Calif. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP891017-0204" num="10" wdcount="29"> The major earthquake that struck the San Francisco Bay area Tuesday occurred in a region seismologists targeted as having the highest probability of a strong quake in Northern California.</s>

<s docid="AP891017-0204" num="11" wdcount="6"> A 1988 report by the U.S.</s>

<s docid="AP891017-0204" num="12" wdcount="28"> Geological Survey placed the probability of an earthquake of 6.5 magnitude on the Richter scale at 30 percent by the year 2018 in the Southern Santa Cruz mountains.</s>

<s docid="AP891017-0204" num="13" wdcount="38"> The high probability is based on several factors, including length of time since the last major earthquake struck the area in 1906, said Clarence Allen, professor of Geology and Geophysics at the California Institue of Technology in Pasadena.</s>

<s docid="AP891017-0204" num="14" wdcount="9"> ``This is not to say we predicted the earthquake.</s>

<s docid="AP891017-0204" num="15" wdcount="16"> It just has to do with the probability of an earthquake in this area,'' Allen said.</s>

<s docid="AP891017-0204" num="16" wdcount="28"> He noted that the 1988 report, titled ``Probabilities of Large Earthquakes Occurring in California on the San Andreas Fault,'' presented information that was already widely known among scientists.</s>

<s docid="AP891017-0204" num="17" wdcount="12"> Allen said this information should have alerted officials to take preventive steps.</s>

<s docid="AP891017-0204" num="18" wdcount="4"> Frank Baldwin of U.S.</s>

<s docid="AP891017-0204" num="19" wdcount="14"> Geological Survey's Earthquake Center said the quake's magnitude was 6.9 on the Richter scale.</s>

<s docid="AP891017-0204" num="20" wdcount="15"> It was centered in the Santa Cruz, Calif., area, 75 miles south of San Francico.</s>

<s docid="AP891017-0204" num="21" wdcount="13"> The Richter scale is a measure of ground motion as recorded on seismographs.</s>

<s docid="AP891017-0204" num="22" wdcount="8"> A reading of 6 can cause severe damage.</s>

<s docid="AP891017-0204" num="23" wdcount="14"> A quake of 7 magnitude, a ``major'' earthquake, is capable of widespread heavy damage.</s>

<s docid="AP891017-0204" num="24" wdcount="15"> Initial reports indicated widespread damage from Tuesday's quake, especially affecting highways and old masonry buildings.</s>

<s docid="AP891017-0204" num="25" wdcount="15"> ``It's not like an earthquake of this size in this area is a calamitous event.</s>

<s docid="AP891017-0204" num="26" wdcount="10"> It's something we should therefore be ready for,'' Allen said.</s>

<s docid="AP891017-0204" num="27" wdcount="33"> The damage in the Bay area occurred to the same kind of structures heavily damaged in the 1987 Whittier quake in the Los Angeles area, which registered a 5.9 Richter reading, Allen said.</s>

<s docid="AP891017-0204" num="28" wdcount="17"> ``I think we'll learn a lot from an engineering point of view from this earthquake,'' he said.</s>

<s docid="AP891017-0204" num="29" wdcount="12"> ``What will be important is to see how the modern structures behaved''.</s>

<s docid="AP891017-0204" num="30" wdcount="26"> Allen said many of the same kinds of older structures that appeared to have been damaged in San Francisco also exist in the Los Angeles region.</s>

<s docid="AP891017-0204" num="31" wdcount="22"> In addition, some of the roadways and overpasses in the area have roughly the same kind of construction as the Bay Bridge.</s>

<s docid="AP891017-0204" num="32" wdcount="16"> In some areas of Southern California, there is a higher probability of a major quake occurring.</s>

<s docid="AP891017-0204" num="33" wdcount="30"> The highest, the USGS says, is in the central California town of Parkfield, where there is a 90 percent probability of a magnitude 6 earthquake by the year 2018 .</s>
</TEXT>
</DOC>
