<DOC>
<DOCNO>

<s docid="AP891017-0199" num="1" wdcount="1"> AP891017-0199</s>
</DOCNO>
<FILEID>

<s docid="AP891017-0199" num="2" wdcount="2"> AP-NR-10-17-89 2158EDT</s>
</FILEID>
<FIRST>

<s docid="AP891017-0199" num="3" wdcount="7"> u a AM-SFQuake 6thLd-Writethru a0817 10-17 0875</s>
</FIRST>
<SECOND>

<s docid="AP891017-0199" num="4" wdcount="7"> AM-SF Quake, 6th Ld - Writethru, a0817,0894</s>
</SECOND>
<HEAD>

<s docid="AP891017-0199" num="5" wdcount="1"> URGENT</s>
</HEAD>
<HEAD>

<s docid="AP891017-0199" num="6" wdcount="7"> Eds: CBS says one dead, major damage.</s>

<s docid="AP891017-0199" num="7" wdcount="3"> new quotes .</s>
</HEAD>
<HEAD>

<s docid="AP891017-0199" num="8" wdcount="4"> Earthquake Rocks San Francisco</s>
</HEAD>
<HEAD>

<s docid="AP891017-0199" num="9" wdcount="4"> Laserphoto NY56, Others Upcoming</s>
</HEAD>
<BYLINE>

<s docid="AP891017-0199" num="10" wdcount="3"> By RICH CARTIERE</s>
</BYLINE>
<BYLINE>

<s docid="AP891017-0199" num="11" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP891017-0199" num="12" wdcount="3"> SAN FRANCISCO (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP891017-0199" num="13" wdcount="37"> A violent earthquake rocked Northern California during Tuesday evening's rush hour, caving in a section of the San Francisco Bay Bridge, terrifying World Series fans in Candlestick Park and shaking buildings as far as 200 miles away.</s>

<s docid="AP891017-0199" num="14" wdcount="10"> CBS-TV reported one person had been killed on the bridge.</s>

<s docid="AP891017-0199" num="15" wdcount="32"> There were no other immediate confirmed reports of deaths or injuries, but ABC-TV and CNN both said some people were injured at Candlestick, where the game was canceled and fans were evacuated.</s>

<s docid="AP891017-0199" num="16" wdcount="26"> It was not immediately clear how extensive the damage was from the quake, which struck at 5:04 p.m. PDT and registered 6.9 on the Richter scale.</s>

<s docid="AP891017-0199" num="17" wdcount="15"> It was centered near Hollister, 80 miles southeast of San Francisco in San Benito County.</s>

<s docid="AP891017-0199" num="18" wdcount="23"> ``The thing struck just as everyone was going home,'' said Tom Mullins, a spokesman for the California Office of Emergency Services in Sacramento.</s>

<s docid="AP891017-0199" num="19" wdcount="15"> ``We've got reports coming in from San Benito and Santa Clara counties of heavy damage''.</s>

<s docid="AP891017-0199" num="20" wdcount="24"> CBS said the California Highway Patrol reported a J.C. Penney building in downtown Hollister collapsed and a bridge on Highway 101 in Hollister collapsed.</s>

<s docid="AP891017-0199" num="21" wdcount="18"> There were unconfirmed reports that a shopping mall collapsed in San Jose, 50 miles south of San Francisco.</s>

<s docid="AP891017-0199" num="22" wdcount="14"> San Francisco Airport was evacuated, and some people there were hit with falling plaster.</s>

<s docid="AP891017-0199" num="23" wdcount="21"> One major fire was blazing in San Francisco's Marina District and another near the library at University of California at Berkeley.</s>

<s docid="AP891017-0199" num="24" wdcount="10"> A huge plume of smoke visible for miles over Berkeley.</s>

<s docid="AP891017-0199" num="25" wdcount="19"> Hundreds of people fled Bay Area Rapid Transit subway and elevated stations in San Francisco and East Bay suburbs.</s>

<s docid="AP891017-0199" num="26" wdcount="5"> The system was shut down.</s>

<s docid="AP891017-0199" num="27" wdcount="29"> Televised footage of the bridge connecting Oakland and San Francisco showed that a 30-foot section of the upper deck had collapsed, leaving two cars dangling between the two levels.</s>

<s docid="AP891017-0199" num="28" wdcount="10"> Reports said most occupants got out of their cars safely.</s>

<s docid="AP891017-0199" num="29" wdcount="32"> In Washington, President Bush said the federal government was prepared to send help to the earthquake area in California and he was sending Transportation Secretary Samuel Skinner there to assess the damage.</s>

<s docid="AP891017-0199" num="30" wdcount="18"> At City Hall in San Francisco a radio reporter told listeners, ``The entire building started to shake ...</s>

<s docid="AP891017-0199" num="31" wdcount="11"> you could hear people yelling and screaming all over the building''.</s>

<s docid="AP891017-0199" num="32" wdcount="13"> She said there were ``obvious problems'' at the health department across the street.</s>

<s docid="AP891017-0199" num="33" wdcount="19"> ``Water was literally gushing out of the building from a window on the second floor,'' the unidentified reporter said.</s>

<s docid="AP891017-0199" num="34" wdcount="23"> Citizens of Marin, north of San Francisco, were warned to shut off their gas because the smell of gas was all over town.</s>

<s docid="AP891017-0199" num="35" wdcount="4"> Frank Baldwin of U.S.</s>

<s docid="AP891017-0199" num="36" wdcount="14"> Geological Survey's Earthquake Center said the quake's magnitude was 6.9 on the Richter scale.</s>

<s docid="AP891017-0199" num="37" wdcount="25"> It occurred at 5:04 p.m. PDT and was centered in the Santa Cruz, Calif., area, 75 miles south of San Francico on the Pacific Coast.</s>

<s docid="AP891017-0199" num="38" wdcount="15"> The quake was felt as far away as Reno, Nev., 225 miles to the northeast.</s>

<s docid="AP891017-0199" num="39" wdcount="17"> The quake knocked out phones and power, including electricity at The Associated Press bureau in San Francisco.</s>

<s docid="AP891017-0199" num="40" wdcount="19"> The San Mateo bridge, which crosses the bay about 10 miles south of Candlestick Park was closed for inspection.</s>

<s docid="AP891017-0199" num="41" wdcount="25"> San Francisco Police Officer Dwayne Collins said there were reports that buildings and statues in the historic South of Market district near downtown had collapsed.</s>

<s docid="AP891017-0199" num="42" wdcount="17"> ``I thought I was losing my balance, then I saw the lamppost sway one foot each direction.</s>

<s docid="AP891017-0199" num="43" wdcount="29"> Then I saw falling glass, broken glass on the street, but luckily not near me, `` said Les Galvacs who was walking down Market Street in downtown San Francisco.</s>

<s docid="AP891017-0199" num="44" wdcount="14"> David Balague, 22, was on the 14th floor of the Bank of America building.</s>

<s docid="AP891017-0199" num="45" wdcount="5"> ``I've never been so scared.</s>

<s docid="AP891017-0199" num="46" wdcount="8"> People were fighting to get under the desks''.</s>

<s docid="AP891017-0199" num="47" wdcount="28"> Fans at Candlestick screamed as the stadium swayed shortly before the San Francisco Giants and Oakland Athletics were to have begun the third game of the World Series.</s>

<s docid="AP891017-0199" num="48" wdcount="38"> ``This upper deck was absolutely shaking, the light stanchions were blowing back and forth, phones have gone out,'' Suzyn Waldman, a reporter covering the World Series for WFAN-AM in New York told listeners shortly after the quake hit.</s>

<s docid="AP891017-0199" num="49" wdcount="19"> ``Everyone is standing around here, people in the upper deck absolutely terrified to move not knowing what to do''.</s>

<s docid="AP891017-0199" num="50" wdcount="24"> A man in Saratoga, southwest of San Jose, told a San Francisco radio station, ``My house is OK, but everything in it is gone.</s>

<s docid="AP891017-0199" num="51" wdcount="10"> My refrigerator is standing in the middle of the kitchen''.</s>

<s docid="AP891017-0199" num="52" wdcount="18"> He said 10,000 gallons of water from his swimming pool crashed through his picture window into his home.</s>

<s docid="AP891017-0199" num="53" wdcount="13"> The Richter scale is a measure of ground motion as recorded on seismographs.</s>

<s docid="AP891017-0199" num="54" wdcount="11"> Every increase of one number means a tenfold increase in magnitude.</s>

<s docid="AP891017-0199" num="55" wdcount="15"> Thus a reading of 7.5 reflects an earthquake 10 times stronger than one of 6.5.</s>

<s docid="AP891017-0199" num="56" wdcount="11"> An earthquake of 6 on the scale can cause severe damage.</s>

<s docid="AP891017-0199" num="57" wdcount="12"> A 7 reading is a ``major'' earthquake, capable of widespread heavy damage.</s>

<s docid="AP891017-0199" num="58" wdcount="24"> The San Francisco earthquake of 1906, which occurred before the Richter scale was devised, has been estimated at 8.3 on the Richter scale .</s>
</TEXT>
</DOC>
