<DOC>
<DOCNO>

<s docid="AP891018-0084" num="1" wdcount="1"> AP891018-0084</s>
</DOCNO>
<FILEID>

<s docid="AP891018-0084" num="2" wdcount="2"> AP-NR-10-18-89 0621EDT</s>
</FILEID>
<FIRST>

<s docid="AP891018-0084" num="3" wdcount="6"> u a PM-Quake-Threat Bjt 10-18 0548</s>
</FIRST>
<SECOND>

<s docid="AP891018-0084" num="4" wdcount="2"> PM-Quake-Threat, Bjt,0565</s>
</SECOND>
<HEAD>

<s docid="AP891018-0084" num="5" wdcount="12"> While LA Awaits `The Big One,' Another Killer Quake Hits San Francisco</s>
</HEAD>
<BYLINE>

<s docid="AP891018-0084" num="6" wdcount="3"> By LEE SIEGEL</s>
</BYLINE>
<BYLINE>

<s docid="AP891018-0084" num="7" wdcount="3"> AP Science Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP891018-0084" num="8" wdcount="3"> LOS ANGELES (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP891018-0084" num="9" wdcount="28"> Ever since the 1906 earthquake devastated San Francisco, many scientists have believed the next ``big one'' would strike the Los Angeles end of the mighty San Andreas Fault.</s>

<s docid="AP891018-0084" num="10" wdcount="37"> But studies in recent years have reminded the Bay Area that it also faced another seismic disaster, and those studies became a reality Tuesday when a quake measuring 6.9 on the Richter scale rocked the Bay area.</s>

<s docid="AP891018-0084" num="11" wdcount="43"> A 1985 paper in the Geophysical Research Letters predicted a 6.9-magnitude quake could happen any time on a portion of the San Andreas Fault that stretches 50 miles from Palo Alto southward through the Santa Cruz Mountains and on to San Juan Bautista.</s>

<s docid="AP891018-0084" num="12" wdcount="23"> The quake was centered on the San Andreas segment described in the article, but Tom Heaton, the scientist in charge of the U.S.</s>

<s docid="AP891018-0084" num="13" wdcount="20"> Geological Survey office in Pasadena, said it wasn't clear yet whether it broke all or part of the 50-mile segment.</s>

<s docid="AP891018-0084" num="14" wdcount="20"> The epicenter of the quake was about 8 miles northeast of Santa Cruz and 75 miles south of San Francisco.</s>

<s docid="AP891018-0084" num="15" wdcount="29"> The 1985 study, by Columbia University geology professor Christopher Scholz, was among several that produced conflicting estimates on the likelihood and size of the quake that finally happened Tuesday.</s>

<s docid="AP891018-0084" num="16" wdcount="35"> These studies gave various interpretations of how much stress inside the Earth was released by the great San Francisco earthquake of 1906, which had a magnitude of about 8.3 and killed at least 2,500 people.</s>

<s docid="AP891018-0084" num="17" wdcount="23"> The bigger a quake, the more stress it relieves, and thus the longer it takes for the same size quake to happen again.</s>

<s docid="AP891018-0084" num="18" wdcount="22"> Scholz pointed to evidence that the 1906 quake didn't relieve as much stress in the Santa Cruz Mountains as other scientists believed.</s>

<s docid="AP891018-0084" num="19" wdcount="17"> That suggested a bigger quake might happen in the San Francisco Bay area sooner than some believed.</s>

<s docid="AP891018-0084" num="20" wdcount="2"> Others disagreed.</s>

<s docid="AP891018-0084" num="21" wdcount="21"> Faced with conflicting estimates, the Geological Survey issued a July 1988 report that it said represented a consensus on the debate.</s>

<s docid="AP891018-0084" num="22" wdcount="19"> The report said the 50-mile segment had a 20 percent likelihood of producing a magnitude-7 quake within 30 years.</s>

<s docid="AP891018-0084" num="23" wdcount="22"> It said the southernmost 20 miles of that segment had a 30 percent chance of generating a magnitude-6.5 quake within 30 years.</s>

<s docid="AP891018-0084" num="24" wdcount="13"> Tuesday's jolt was centered within those southernmost 20 miles of the fault segment.</s>

<s docid="AP891018-0084" num="25" wdcount="13"> ``Clearly, scientists had identified this segment as a particularly hazardous one,'' Heaton said.</s>

<s docid="AP891018-0084" num="26" wdcount="16"> ``There was some debate about the length of the rupture and the size of the earthquake''.</s>

<s docid="AP891018-0084" num="27" wdcount="20"> The last great southern California quake, in 1857, killed very few people in a region that was then sparsely populated.</s>

<s docid="AP891018-0084" num="28" wdcount="27"> Thus most assumed that Los Angeles, not the Bay Area, would fall victim to the next seismic catastrophe; the 1988 USGS report cast doubt on this assumption.</s>

<s docid="AP891018-0084" num="29" wdcount="38"> Federal emergency officials have estimated that the next ``big one'' _ a quake like the 1906 San Francisco quake _ could kill 3,000 to 14,000 people in southern California, and 3,000 to 11,000 people in the Bay Area.</s>

<s docid="AP891018-0084" num="30" wdcount="18"> As bad as Tuesday's quake was, ``it was not a 1906 earthquake,'' Geological Survey director Dalas Peck said.</s>

<s docid="AP891018-0084" num="31" wdcount="10"> ``The question is not whether a big earthquake is coming.</s>

<s docid="AP891018-0084" num="32" wdcount="7"> The question is when,'' Peck said .</s>
</TEXT>
</DOC>
