<DOC>
<DOCNO>

<s docid="AP891017-0195" num="1" wdcount="1"> AP891017-0195</s>
</DOCNO>
<FILEID>

<s docid="AP891017-0195" num="2" wdcount="2"> AP-NR-10-17-89 2050EDT</s>
</FILEID>
<FIRST>

<s docid="AP891017-0195" num="3" wdcount="7"> u a AM-SFQuake 3rdLd-Writethru a0805 10-17 0340</s>
</FIRST>
<SECOND>

<s docid="AP891017-0195" num="4" wdcount="5"> AM-SF Quake, 3rd Ld-Writethru, a0805,0344</s>
</SECOND>
<HEAD>

<s docid="AP891017-0195" num="5" wdcount="1"> URGENT</s>
</HEAD>
<HEAD>

<s docid="AP891017-0195" num="6" wdcount="7"> Eds: UPDATES throughout with magnitude, other details.</s>

<s docid="AP891017-0195" num="7" wdcount="3"> No pickup .</s>
</HEAD>
<HEAD>

<s docid="AP891017-0195" num="8" wdcount="4"> Earthquake Rocks San Francisco</s>
</HEAD>
<DATELINE>

<s docid="AP891017-0195" num="9" wdcount="3"> SAN FRANCISCO (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP891017-0195" num="10" wdcount="27"> A major earthquake rocked northern California Tuesday evening, collapsing part of the San Francisco Bay Bridge and shaking Candlestick Park and buildings up to 95 miles away.</s>

<s docid="AP891017-0195" num="11" wdcount="9"> Some buildings may have collapsed, said Police Officer D.</s>

<s docid="AP891017-0195" num="12" wdcount="29"> Collins. There were reports of injuries at Candlestick, where fans were waiting for the World Series to begin, and the stadium was evacuated, ABC-TV and Cable News Network reported.</s>

<s docid="AP891017-0195" num="13" wdcount="24"> The quake, which lasted about 15 seconds, measured 6.5 on the Richter scale, according to seismologists at the California Institute of Technology in Pasadena.</s>

<s docid="AP891017-0195" num="14" wdcount="12"> The preliminary reading was from the Alaska Tsunami warning system, Caltech said.</s>

<s docid="AP891017-0195" num="15" wdcount="21"> Televised footage of the bridge showed that a 30-foot section of the span's upper deck had collapsed onto the bottom level.</s>

<s docid="AP891017-0195" num="16" wdcount="12"> Fans at Candlestick screamed as the stadium swayed for about 15 seconds.</s>

<s docid="AP891017-0195" num="17" wdcount="24"> Players from the San Francisco Giants and the Oakland Athletics were on the field and stood around as fans began to leave their seats.</s>

<s docid="AP891017-0195" num="18" wdcount="7"> Buildings in San Francisco swayed several feet.</s>

<s docid="AP891017-0195" num="19" wdcount="25"> The quake shook buildings in Sacramento, 95 miles to the northeast, and was felt as far away as Reno, Nev., 225 miles to the east.</s>

<s docid="AP891017-0195" num="20" wdcount="17"> The quake knocked out phones and power, including electricity at The Associated Press' bureau in San Francisco.</s>

<s docid="AP891017-0195" num="21" wdcount="13"> The Richter scale is a measure of ground motion as recorded on seismographs.</s>

<s docid="AP891017-0195" num="22" wdcount="11"> Every increase of one number means a tenfold increase in magnitude.</s>

<s docid="AP891017-0195" num="23" wdcount="15"> Thus a reading of 7.5 reflects an earthquake 10 times stronger than one of 6.5.</s>

<s docid="AP891017-0195" num="24" wdcount="25"> An earthquake of 3.5 on the Richter scale can cause slight damage in the local area, 4 moderate damage, 5 considerable damage, 6 severe damage.</s>

<s docid="AP891017-0195" num="25" wdcount="21"> A 7 reading is a ``major'' earthquake, capable of widespread heavy damage; 8 is a ``great'' quake, capable of tremendous damage.</s>

<s docid="AP891017-0195" num="26" wdcount="24"> The San Francisco earthquake of 1906, which occurred before the Richter scale was devised, has been estimated at 8.3 on the Richter scale .</s>
</TEXT>
</DOC>
