<DOC>
<DOCNO>

<s docid="LA102089-0172" num="1" wdcount="1"> LA102089-0172</s>
</DOCNO>
<DOCID>

<s docid="LA102089-0172" num="2" wdcount="1"> 123452</s>
</DOCID>
<DATE>
<P>

<s docid="LA102089-0172" num="3" wdcount="6"> October 20, 1989, Friday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA102089-0172" num="4" wdcount="10"> Special Section; Part Q; Page 6; Column 1; Metro Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA102089-0172" num="5" wdcount="2"> 956 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA102089-0172" num="6" wdcount="4"> THE BAY AREA QUAKE;</s>
</P>
<P>

<s docid="LA102089-0172" num="7" wdcount="2"> PRESSURE POINTS;</s>
</P>
<P>

<s docid="LA102089-0172" num="8" wdcount="6"> WHAT WORKED, WHAT DIDN'T, AND WHY;</s>
</P>
<P>

<s docid="LA102089-0172" num="9" wdcount="1"> BUILDINGS;</s>
</P>
<P>

<s docid="LA102089-0172" num="10" wdcount="6"> SURVIVAL MAY DEPEND ON SOLID FOUNDATIONS</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA102089-0172" num="11" wdcount="6"> By ROBERT WELKOS, TIMES STAFF WRITER</s>
</P>
</BYLINE>
<TEXT>
<P>

<s docid="LA102089-0172" num="12" wdcount="20"> On Telegraph Hill, Jerry Lubenow got his biggest shock when he arrived at his apartment after the deadly earthquake .</s>
</P>
<P>

<s docid="LA102089-0172" num="13" wdcount="14"> "There was no damage to our place or in our neighborhood," he said .</s>
</P>
<P>

<s docid="LA102089-0172" num="14" wdcount="14"> The only thing Lubenow could figure out was that "Telegraph Hill is on rock".</s>

<s docid="LA102089-0172" num="15" wdcount="28"> He then talked to friends who live on Nob Hill and Russian Hill, which are also situated on rock, and learned that their residences also avoided damage .</s>
</P>
<P>

<s docid="LA102089-0172" num="16" wdcount="12"> "You almost feel guilty," he said, referring to his own good fortune.</s>

<s docid="LA102089-0172" num="17" wdcount="14"> "(It's) like living through the blitz in London in the Second World War" .</s>
</P>
<P>

<s docid="LA102089-0172" num="18" wdcount="19"> Only a few miles away in San Francisco's affluent Marina District, dozens of fashionable townhouses were damaged or destroyed.</s>

<s docid="LA102089-0172" num="19" wdcount="11"> Some buckled and pitched forward off their foundations into the street.</s>

<s docid="LA102089-0172" num="20" wdcount="13"> Others appeared outwardly sound but sustained interior damage that rendered them uninhabitable .</s>
</P>
<P>

<s docid="LA102089-0172" num="21" wdcount="29"> Why did some of the luxury, four-story apartment buildings collapse at the Marina while in nearby Chinatown, shops made of unreinforced masonry sustained little damage in the 6.9 temblor?</s>
</P>
<P>

<s docid="LA102089-0172" num="22" wdcount="28"> Why did high-rises that form the elegant San Francisco skyline escape virtually unscathed while an office building in the city's southeast district peel apart, killing five pedestrians below?</s>
</P>
<P>

<s docid="LA102089-0172" num="23" wdcount="38"> "The buildings that collapsed did so because of a combination of two things: very poor soil and very poor structural design," said Peter I. Yanev, chairman of EQE Engineering Inc., a structural engineering firm in San Francisco .</s>
</P>
<P>

<s docid="LA102089-0172" num="24" wdcount="35"> "They were on top of the worst soil conditions in the city," explained Yanev, who said he has traveled to "all the major earthquakes" in the last 20 years studying their impact on construction .</s>
</P>
<P>

<s docid="LA102089-0172" num="25" wdcount="29"> The soil beneath the Marina District, where six buildings burned down or collapsed, is made up of landfill partly dredged from the bay more than 70 years ago .</s>
</P>
<P>

<s docid="LA102089-0172" num="26" wdcount="25"> Yanev said many of the buildings in the neighborhood were erected in the early part of this century when there were no earthquake codes .</s>
</P>
<P>

<s docid="LA102089-0172" num="27" wdcount="23"> "What collapsed and killed some people were four-story apartment buildings that had garages built all the way along the bottom (floor)," Yanev said.</s>

<s docid="LA102089-0172" num="28" wdcount="11"> "So, you have a bunch of garages underneath all these apartments.</s>

<s docid="LA102089-0172" num="29" wdcount="11"> You effectively have no walls on one side of the building.</s>

<s docid="LA102089-0172" num="30" wdcount="13"> The connections just break, and the front end falls into the street" .</s>
</P>
<P>

<s docid="LA102089-0172" num="31" wdcount="11"> Yanev called the two conditions a "disaster waiting to happen" .</s>
</P>
<P>

<s docid="LA102089-0172" num="32" wdcount="26"> "Should we have an earthquake centered off the Golden Gate Bridge instead of Santa Cruz, you'd probably have hundreds of these buildings collapse," he said .</s>
</P>
<P>

<s docid="LA102089-0172" num="33" wdcount="18"> Experts said they did not anticipate that the Marina District would be the major problem in an earthquake.</s>

<s docid="LA102089-0172" num="34" wdcount="16"> The worst areas, they believed, would be Chinatown and the Tenderloin, where brick buildings abound .</s>
</P>
<P>

<s docid="LA102089-0172" num="35" wdcount="29"> Chinatown survived relatively intact, Yanev said, because it is located "up in the hills" atop "very firm soil," and the epicenter of the temblor was many miles away .</s>
</P>
<P>

<s docid="LA102089-0172" num="36" wdcount="17"> In the city's high-rise office towers, a few broken windows and other cosmetic damage could be seen.</s>

<s docid="LA102089-0172" num="37" wdcount="12"> A preliminary survey found only three skyscrapers rendered unsafe by the quake.</s>

<s docid="LA102089-0172" num="38" wdcount="12"> But most buildings, including the landmark Transamerica Pyramid, were not touched .</s>
</P>
<P>

<s docid="LA102089-0172" num="39" wdcount="25"> Jay Cahill, an owner of Cahill Construction Co., a contractor that built several high-rises in the city, said the earthquake codes "did their job" .</s>
</P>
<P>

<s docid="LA102089-0172" num="40" wdcount="22"> "What this quake proves is that the engineers were right" when they said tall buildings could withstand a strong quake, he said.</s>

<s docid="LA102089-0172" num="41" wdcount="23"> They said the downtown buildings are constructed to withstand a quake of at least 8 magnitude with an epicenter in San Francisco .</s>
</P>
<P>

<s docid="LA102089-0172" num="42" wdcount="19"> Earthquake experts said they were not surprised that the high-rises swayed with the earthquake while four-story buildings collapsed .</s>
</P>
<P>

<s docid="LA102089-0172" num="43" wdcount="38"> "An earthquake means that the ground shakes, and that means force is applied to the sides of buildings," said George C. Lee, acting director of the National Center for Earthquake Engineering Research at the University of Buffalo .</s>
</P>
<P>

<s docid="LA102089-0172" num="44" wdcount="27"> When architects design skyscrapers, Lee said, they factor in wind gusts and earth movement -- forces that are not considered as much when constructing smaller buildings .</s>
</P>
<P>

<s docid="LA102089-0172" num="45" wdcount="26"> In smaller buildings, he said, contractors usually make sure that vertical forces -- such as snow and ice -- cannot force a structure to collapse .</s>
</P>
<P>

<s docid="LA102089-0172" num="46" wdcount="38"> Throughout the Bay Area, residents were left to puzzle over why the earthquake savaged some buildings and bypassed others, much like San Francisco was left to wonder why the Marina District was hard hit and others spared .</s>
</P>
<P>

<s docid="LA102089-0172" num="47" wdcount="26"> In Santa Cruz, initial damages were estimated at $350 million, and 30% of the downtown mall -- the heart of the city -- was severely damaged.</s>

<s docid="LA102089-0172" num="48" wdcount="13"> An estimated 20 commercial buildings must be razed, a county official said .</s>
</P>
<P>

<s docid="LA102089-0172" num="49" wdcount="16"> In Los Gatos, 30 miles northeast of Santa Cruz, portions of the downtown area were destroyed.</s>

<s docid="LA102089-0172" num="50" wdcount="14"> Several dozen Victorian homes were shifted off their foundations, and numerous chimneys crumbled .</s>
</P>
<P>

<s docid="LA102089-0172" num="51" wdcount="29"> San Francisco fire officials said as many as 60 buildings in the Marina District may have to be torn down because of structural instability caused by the earthquake .</s>
</P>
<P>

<s docid="LA102089-0172" num="52" wdcount="13"> "Some of the buildings are extremely hazardous," Assistant Fire Chief Frank Blackburn said.</s>

<s docid="LA102089-0172" num="53" wdcount="6"> "They are four-story buildings above garages.</s>

<s docid="LA102089-0172" num="54" wdcount="10"> All they had were vertical columns holding up the structures.</s>

<s docid="LA102089-0172" num="55" wdcount="27"> If you picture a building sitting on columns with no lateral support on those columns, when you get sideways motion, the buildings slide left and right" .</s>
</P>
<P>

<s docid="LA102089-0172" num="56" wdcount="16"> Blackburn said many residents are not going to be able to get their belongings out .</s>
</P>
<P>

<s docid="LA102089-0172" num="57" wdcount="10"> "If a (big) aftershock comes, it'll collapse," he said .</s>
</P>
<P>
</P>
<P>

<s docid="LA102089-0172" num="58" wdcount="6"> Buildings collapsed like cakes without yeast.</s>

<s docid="LA102089-0172" num="59" wdcount="18"> One fourth-floor apartment dweller stepped through her window onto the street after her building crumbled beneath her .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA102089-0172" num="60" wdcount="12"> Photo, Military police guard Marina District building that was damaged by quake.</s>

<s docid="LA102089-0172" num="61" wdcount="3"> United Press International</s>
</P>
</GRAPHIC>
<SUBJECT>
<P>

<s docid="LA102089-0172" num="62" wdcount="22"> BUILDING COLLAPSES; EARTHQUAKES -- SAN FRANCISCO; EARTHQUAKES -- NORTHERN CALIFORNIA; OAKLAND (CA); SURVIVAL; EARTHQUAKE SAFETY; BUILDING SAFETY; APARTMENTS; HOUSING -- SAN FRANCISCO</s>
</P>
</SUBJECT>
</DOC>
