<DOC>
<DOCNO>

<s docid="LA102389-0075" num="1" wdcount="1"> LA102389-0075</s>
</DOCNO>
<DOCID>

<s docid="LA102389-0075" num="2" wdcount="1"> 124632</s>
</DOCID>
<DATE>
<P>

<s docid="LA102389-0075" num="3" wdcount="6"> October 23, 1989, Monday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA102389-0075" num="4" wdcount="8"> Part A; Page 18; Column 2; Metro Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA102389-0075" num="5" wdcount="2"> 902 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA102389-0075" num="6" wdcount="3"> BAY AREA QUAKE;</s>
</P>
<P>

<s docid="LA102389-0075" num="7" wdcount="8"> SISTER CITIES IN THE ANNALS OF NATURAL DISASTERS;</s>
</P>
<P>

<s docid="LA102389-0075" num="8" wdcount="25"> HISTORY: CHARLESTON AND SAN FRANCISCO ARE ON OPPOSITE ENDS OF THE COUNTRY, BUT A HURRICANE AND A QUAKE BRING THEM TOGETHER IN TIME'S LEDGER .</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA102389-0075" num="9" wdcount="9"> By LARRY GREEN and BOB SECTER, TIMES STAFF WRITERS</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA102389-0075" num="10" wdcount="2"> SAN FRANCISCO</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA102389-0075" num="11" wdcount="24"> Although they are a continent apart, the cities of Charleston, S.C., and San Francisco now share a fateful page in the ledger of time.</s>

<s docid="LA102389-0075" num="12" wdcount="21"> They are the scenes of two of the century's costliest, back-to-back natural disasters: Hurricane Hugo and the Bay Area earthquake .</s>
</P>
<P>

<s docid="LA102389-0075" num="13" wdcount="51"> There are dramatic similarities and profound differences in the ways these two cities were affected and altered in the first week after they were ravaged by two powerful forces of nature -- one that angrily swept across the land from the sea and one that violently rumbled beneath the earth .</s>
</P>
<P>

<s docid="LA102389-0075" num="14" wdcount="39"> "From the standpoint of compassion, of all the people in America we can feel the hurt that the San Francisco area is going through the most," Charleston Mayor Joseph P. Riley Jr. said Sunday, one month after Hugo hit.</s>

<s docid="LA102389-0075" num="15" wdcount="22"> "We know it means, at best, the disruption of normal life for some time and, at worst, the loss of life" .</s>
</P>
<P>

<s docid="LA102389-0075" num="16" wdcount="3"> Charleston had warning.</s>

<s docid="LA102389-0075" num="17" wdcount="4"> San Francisco did not.</s>

<s docid="LA102389-0075" num="18" wdcount="27"> Unlike earthquakes, hurricanes can be tracked by planes and radar, their paths predicted with sufficient certainty for those in harm's way to secure property and to flee.</s>

<s docid="LA102389-0075" num="19" wdcount="26"> Still, at least 28 deaths in the Carolinas are blamed on Hugo, while at least 60 deaths have been attributed to the Bay Area earthquake .</s>
</P>
<P>

<s docid="LA102389-0075" num="20" wdcount="31"> Hugo, 500 miles across with winds topping 175 m.p.h., left virtually every street and every neighborhood littered with storm debris and 80% of the city's buildings with some degree of damage.</s>

<s docid="LA102389-0075" num="21" wdcount="18"> Five days after the storm, many city residents remained inconvenienced, most without electricity, many without safe drinking water.</s>

<s docid="LA102389-0075" num="22" wdcount="4"> Street lights didn't work.</s>

<s docid="LA102389-0075" num="23" wdcount="16"> Broken glass and other debris left the roadsides lined with cars stopped by flat tires .</s>
</P>
<P>

<s docid="LA102389-0075" num="24" wdcount="17"> By contrast the streets in most of San Francisco were passable within a day of the earthquake.</s>

<s docid="LA102389-0075" num="25" wdcount="5"> Electricity was largely restored overnight.</s>

<s docid="LA102389-0075" num="26" wdcount="9"> And most broken natural gas lines were quickly repaired.</s>

<s docid="LA102389-0075" num="27" wdcount="13"> Restaurants in Chinatown, North Beach and along Fillmore Street were crowded Saturday night.</s>

<s docid="LA102389-0075" num="28" wdcount="15"> Cable cars began carrying passengers Sunday and the curtain went up on the opera .</s>
</P>
<P>

<s docid="LA102389-0075" num="29" wdcount="11"> "Their streets were immediately passable," said Charleston Police Chief Ruben Greenberg.</s>

<s docid="LA102389-0075" num="30" wdcount="11"> "We were gridlocked for two days because of the debris" .</s>
</P>
<P>

<s docid="LA102389-0075" num="31" wdcount="30"> And a week after the hurricane, Charleston -- which like San Francisco has a tourism-based economy -- was still trying to cope with mountains of broken trees and shattered roofs.</s>

<s docid="LA102389-0075" num="32" wdcount="27"> It was more than 10 days before restaurants and other stores began to slowly reopen and twice as long for night life to begin to return .</s>
</P>
<P>

<s docid="LA102389-0075" num="33" wdcount="3"> Tour Buses Return</s>
</P>
<P>

<s docid="LA102389-0075" num="34" wdcount="21"> By Sunday, tourists and tour buses could be seen outside hotels near Fisherman's Wharf and at other locations favored by visitors.</s>

<s docid="LA102389-0075" num="35" wdcount="9"> Tourism is a $2.5-billion-a-year business in San Francisco .</s>
</P>
<P>

<s docid="LA102389-0075" num="36" wdcount="19"> It took almost three weeks for businesses that cater to tourists to get back on their feet in Charleston.</s>

<s docid="LA102389-0075" num="37" wdcount="25"> It's likely to take a lot longer for the tourists themselves to return in numbers that made it one of the city's biggest industries .</s>
</P>
<P>

<s docid="LA102389-0075" num="38" wdcount="18"> Citywide, Charleston had 68 buildings collapse, compared to 60 buildings destroyed just in San Francisco's Marina District .</s>
</P>
<P>

<s docid="LA102389-0075" num="39" wdcount="10"> In Charleston most of the damage could be quickly assessed.</s>

<s docid="LA102389-0075" num="40" wdcount="3"> It was visible.</s>

<s docid="LA102389-0075" num="41" wdcount="11"> In San Francisco much of the damage may still be undetected.</s>

<s docid="LA102389-0075" num="42" wdcount="17"> Water mains and gas lines weakened by the heaving earth may not break for weeks or months.</s>

<s docid="LA102389-0075" num="43" wdcount="17"> Structural damage to houses, in many instances, will become apparent over a long period of time .</s>
</P>
<P>

<s docid="LA102389-0075" num="44" wdcount="9"> "When a hurricane is over, it's over," Greenberg said.</s>

<s docid="LA102389-0075" num="45" wdcount="5"> "Not so with an earthquake.</s>

<s docid="LA102389-0075" num="46" wdcount="4"> You have aftershocks" .</s>
</P>
<P>

<s docid="LA102389-0075" num="47" wdcount="9"> Charleston also escaped widespread damage to its infrastructure .</s>
</P>
<P>

<s docid="LA102389-0075" num="48" wdcount="30"> "We lost no major economic area like the Bay Bridge," said Greenberg, who was once San Francisco's undersheriff and who returned with emergency supplies to help the Santa Cruz police.</s>

<s docid="LA102389-0075" num="49" wdcount="4"> "That's an economic lifeline.</s>

<s docid="LA102389-0075" num="50" wdcount="7"> All we lost was one minor bridge.</s>

<s docid="LA102389-0075" num="51" wdcount="8"> They're going to have humongous traffic problems" .</s>
</P>
<P>

<s docid="LA102389-0075" num="52" wdcount="7"> Hugo left Charleston isolated from the world.</s>

<s docid="LA102389-0075" num="53" wdcount="26"> Communications broke down soon after the storm crossed the coastline about midnight and it was daybreak before the nation began to learn of the widespread damage.</s>

<s docid="LA102389-0075" num="54" wdcount="8"> Even local residents were left without any information.</s>

<s docid="LA102389-0075" num="55" wdcount="30"> The hurricane knocked out all local television and radio stations, and local officials for almost two days depended on a Florida radio station to deliver vital information and warnings .</s>
</P>
<P>

<s docid="LA102389-0075" num="56" wdcount="23"> Millions were watching the pregame World Series program when the earthquake struck, and instantly word was out that there had been a disaster.</s>

<s docid="LA102389-0075" num="57" wdcount="16"> San Francisco stations were able to broadcast to residents who had battery-powered radios and TVs .</s>
</P>
<P>

<s docid="LA102389-0075" num="58" wdcount="22"> Damage estimates from Hugo have ranged as high as $5 billion, while earthquake damage estimates Sunday reached the $6.6 billion mark .</s>
</P>
<P>

<s docid="LA102389-0075" num="59" wdcount="34"> Besides that black page in the ledger of history, both San Francisco and Charleston also have another experience in common: Both have experienced frustrating delays in getting disaster relief from the federal government .</s>
</P>
<P>

<s docid="LA102389-0075" num="60" wdcount="36"> Greenberg, who has now watched the federal government respond to two of America's worst disasters, said he sees relatively few differences between how the Federal Emergency Management Agency worked in South Carolina and Northern California .</s>
</P>
<P>

<s docid="LA102389-0075" num="61" wdcount="14"> "There's nothing that needs to be done in a hurry with them," he said.</s>

<s docid="LA102389-0075" num="62" wdcount="11"> "They just plop along like one of the horses at Disneyland.</s>

<s docid="LA102389-0075" num="63" wdcount="4"> Just plop, plop, plop.</s>

<s docid="LA102389-0075" num="64" wdcount="11"> They are repeating the mistakes of South Carolina in California" .</s>
</P>
</TEXT>
<SUBJECT>
<P>

<s docid="LA102389-0075" num="65" wdcount="17"> EARTHQUAKES -- SAN FRANCISCO; EARTHQUAKES -- NORTHERN CALIFORNIA; HURRICANES -- SOUTH CAROLINA; SAN FRANCISCO; CHARLESTON (SC); DISASTERS</s>
</P>
</SUBJECT>
</DOC>
