<DOC>
<DOCNO>

<s docid="LA101889-0108" num="1" wdcount="1"> LA101889-0108</s>
</DOCNO>
<DOCID>

<s docid="LA101889-0108" num="2" wdcount="1"> 122234</s>
</DOCID>
<DATE>
<P>

<s docid="LA101889-0108" num="3" wdcount="6"> October 18, 1989, Wednesday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA101889-0108" num="4" wdcount="9"> Sports; Part C; Page 9; Column 2; Sports Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA101889-0108" num="5" wdcount="2"> 241 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA101889-0108" num="6" wdcount="3"> THE WORLD SERIES;</s>
</P>
<P>

<s docid="LA101889-0108" num="7" wdcount="3"> OAKLAND ATHLETICS VS.</s>

<s docid="LA101889-0108" num="8" wdcount="3"> SAN FRANCISCO GIANTS;</s>
</P>
<P>

<s docid="LA101889-0108" num="9" wdcount="10"> EXPERIENCE AT CANDLESTICK IS ONE REPORTER WILL NOT SOON FORGET</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA101889-0108" num="10" wdcount="3"> By LARRY STEWART</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA101889-0108" num="11" wdcount="2"> SAN FRANCISCO</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA101889-0108" num="12" wdcount="7"> There are events one never forgets .</s>
</P>
<P>

<s docid="LA101889-0108" num="13" wdcount="16"> Anyone who was alive in 1963 remembers where he was when President Kennedy was assassinated .</s>
</P>
<P>

<s docid="LA101889-0108" num="14" wdcount="20"> And anyone who was at Candlestick Park Tuesday night for Game 3 of the World Series will never forget .</s>
</P>
<P>

<s docid="LA101889-0108" num="15" wdcount="18"> I was in a trailer just outside the stadium, about to watch the telecast when the earthquake hit.</s>

<s docid="LA101889-0108" num="16" wdcount="11"> It was shortly after the network went on the air .</s>
</P>
<P>

<s docid="LA101889-0108" num="17" wdcount="20"> My immediate reaction was that a jet was flying very low overhead, but soon I knew what was happening .</s>
</P>
<P>

<s docid="LA101889-0108" num="18" wdcount="23"> To me, the earthquake was not as bad as the Whittier quake in October, 1987, mainly because I was awake this time .</s>
</P>
<P>

<s docid="LA101889-0108" num="19" wdcount="10"> I opened the door to the trailer and looked out.</s>

<s docid="LA101889-0108" num="20" wdcount="34"> The stadium was shaking and the special concrete joint -- one of several strategically spaced around the top of the stadium to prevent earthquake damage -- was doing was it was designed to do.</s>

<s docid="LA101889-0108" num="21" wdcount="17"> It was opening and closing as if the place was made of cardboard instead of concrete .</s>
</P>
<P>

<s docid="LA101889-0108" num="22" wdcount="26"> A few people were running out of the stadium, but there did not seem to be great alarm, because the quake did not last long .</s>
</P>
<P>

<s docid="LA101889-0108" num="23" wdcount="8"> I walked into the stadium to interview fans.</s>

<s docid="LA101889-0108" num="24" wdcount="7"> And again, I sensed little panic .</s>
</P>
<P>

<s docid="LA101889-0108" num="25" wdcount="16"> Most people stayed in their seats, waiting to hear whether the game would be postponed .</s>
</P>
<P>

<s docid="LA101889-0108" num="26" wdcount="16"> And later, when fans started leaving en masse, the reaction of those I talked to varied.</s>

<s docid="LA101889-0108" num="27" wdcount="18"> Those who were sitting in the upper deck seemed considerably more shaken than those in the lower levels.</s>

<s docid="LA101889-0108" num="28" wdcount="2"> LARRY STEWART</s>
</P>
</TEXT>
<SUBJECT>
<P>

<s docid="LA101889-0108" num="29" wdcount="23"> WORLD SERIES; SAN FRANCISCO GIANTS (BASEBALL TEAM); OAKLAND A'S (BASEBALL TEAM); EARTHQUAKES -- SAN FRANCISCO; EARTHQUAKES -- NORTHERN CALIFORNIA; CANDLESTICK PARK; DISASTERS; REPORTERS</s>
</P>
</SUBJECT>
</DOC>
