<DOC>
<DOCNO>

<s docid="LA102089-0177" num="1" wdcount="1"> LA102089-0177</s>
</DOCNO>
<DOCID>

<s docid="LA102089-0177" num="2" wdcount="1"> 123463</s>
</DOCID>
<DATE>
<P>

<s docid="LA102089-0177" num="3" wdcount="6"> October 20, 1989, Friday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA102089-0177" num="4" wdcount="10"> Special Section; Part Q; Page 12; Column 4; Metro Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA102089-0177" num="5" wdcount="2"> 151 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA102089-0177" num="6" wdcount="4"> THE BAY AREA QUAKE;</s>
</P>
<P>

<s docid="LA102089-0177" num="7" wdcount="2"> WHAT NEXT?</s>
</P>
<P>

<s docid="LA102089-0177" num="8" wdcount="6"> PONDERING THE LESSONS, HEALING THE SCARS</s>
</P>
</HEADLINE>
<TEXT>
<P>

<s docid="LA102089-0177" num="9" wdcount="17"> "I've been wandering around San Francisco and it's like the blind man trying to feel an elephant.</s>

<s docid="LA102089-0177" num="10" wdcount="11"> We're just now figuring out bits and pieces of this disaster".</s>

<s docid="LA102089-0177" num="11" wdcount="10"> -- Tom Tobin, of the California Seismic Safety Commission .</s>
</P>
<P>
</P>
<P>

<s docid="LA102089-0177" num="12" wdcount="8"> "It was like somebody slugging a punching bag.</s>

<s docid="LA102089-0177" num="13" wdcount="10"> Usually earthquakes pass, but this one went on and on.</s>

<s docid="LA102089-0177" num="14" wdcount="8"> It just wouldn't stop...It was very, very bad".</s>

<s docid="LA102089-0177" num="15" wdcount="18"> -- Schoolteacher Flora Churnin, who was at her Silicon Valley town of Sunnyvale when the earthquake struck .</s>
</P>
<P>
</P>
<P>

<s docid="LA102089-0177" num="16" wdcount="8"> "At first I thought the smoke was fog.</s>

<s docid="LA102089-0177" num="17" wdcount="9"> Then I could see a big ball of flame".</s>

<s docid="LA102089-0177" num="18" wdcount="23"> -- Cecile Candone, who was driving south toward San Francisco from the Sonoma wine country when she spotted the Marina district fire .</s>
</P>
<P>
</P>
<P>

<s docid="LA102089-0177" num="19" wdcount="14"> "This upper deck was absolutely shaking, the light stanchions were blowing back and forth".</s>

<s docid="LA102089-0177" num="20" wdcount="19"> -- Suzyn Waldman, a reporter covering the World Series at Candlestick Park for a New York radio station .</s>
</P>
</TEXT>
<SUBJECT>
<P>

<s docid="LA102089-0177" num="21" wdcount="12"> EARTHQUAKES -- SAN FRANCISCO; EARTHQUAKES -- NORTHERN CALIFORNIA; OAKLAND (CA); DISASTER VICTIMS</s>
</P>
</SUBJECT>
</DOC>
