<DOC>
<DOCNO>

<s docid="LA101889-0066" num="1" wdcount="1"> LA101889-0066</s>
</DOCNO>
<DOCID>

<s docid="LA101889-0066" num="2" wdcount="1"> 122132</s>
</DOCID>
<DATE>
<P>

<s docid="LA101889-0066" num="3" wdcount="6"> October 18, 1989, Wednesday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA101889-0066" num="4" wdcount="8"> Part A; Page 4; Column 4; Metro Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA101889-0066" num="5" wdcount="2"> 1204 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA101889-0066" num="6" wdcount="12"> SCIENTISTS LAST YEAR HAD PINPOINTED TUESDAY'S SITE AS LIKELY TO BE JOLTED</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA101889-0066" num="7" wdcount="6"> By KENNETH REICH, TIMES STAFF WRITER</s>
</P>
</BYLINE>
<TEXT>
<P>

<s docid="LA101889-0066" num="8" wdcount="49"> Tuesday's earthquake, the strongest on the San Andreas fault since the San Francisco quake on April 18, 1906, came in a place that had been identified by scientists just last year as the most likely spot for a major jolt in Northern California within the next 30 years .</s>
</P>
<P>

<s docid="LA101889-0066" num="9" wdcount="41"> The epicenter of the temblor, eight miles east-northeast of the city of Santa Cruz in the Santa Cruz Mountains, was at virtually the same spot as earthquakes in the 5-magnitude range that occurred on June 27, 1988, and Aug. 8, 1989.</s>

<s docid="LA101889-0066" num="10" wdcount="9"> A 6.5-magnitude quake was centered there in 1865 .</s>
</P>
<P>

<s docid="LA101889-0066" num="11" wdcount="2"> The U.S.</s>

<s docid="LA101889-0066" num="12" wdcount="33"> Geological Survey, in a 1988 report on regions of high earthquake probability in California, said there was a 30% chance of another 6.5-magnitude earthquake in the immediate vicinity by the year 2018 .</s>
</P>
<P>

<s docid="LA101889-0066" num="13" wdcount="60"> The report cited even higher probabilities for major temblors on the San Andreas near Parkfield in central California and Coachella in Southern California in the same period, but it pinpointed the Santa Cruz mountains as the most vulnerable spot in Northern California, in part because the area marked the southernmost point of maximum ground slippage during the 1906 earthquake .</s>
</P>
<P>

<s docid="LA101889-0066" num="14" wdcount="42"> A period of 83 years is short as far as earthquake intervals go, and during this time, scientists said Tuesday night, pressure was probably building up in the southern neighboring segment of the San Andreas, which had not slipped as much .</s>
</P>
<P>

<s docid="LA101889-0066" num="15" wdcount="32"> Thomas Heaton, the Geological Survey scientist in charge of the agency's Pasadena field office, said that the 1987 and 1988 earthquakes now must be seen as "preshocks" of the Tuesday's 6.9 temblor.</s>

<s docid="LA101889-0066" num="16" wdcount="20"> He said "foreshocks" would not be the proper term, since months had elapsed before the more powerful earthquake struck .</s>
</P>
<P>

<s docid="LA101889-0066" num="17" wdcount="9"> Heaton said that a still larger shock is unlikely.</s>

<s docid="LA101889-0066" num="18" wdcount="27"> But he joined Caltech scientists in saying that aftershocks as strong as 5.9 magnitude should be expected, and that the pattern of aftershocks could last for months.</s>

<s docid="LA101889-0066" num="19" wdcount="18"> A 5.9 aftershock would be as strong as the 1987 Whittier quake in the Los Angeles area .</s>
</P>
<P>

<s docid="LA101889-0066" num="20" wdcount="22"> After both the 1987 and the 1988 earthquakes in the Santa Cruz mountains, the state Office of Emergency Services and the U.S.</s>

<s docid="LA101889-0066" num="21" wdcount="24"> Geological Survey issued warnings of increased risk of sizable shakes, ranging up to 6.5 magnitude, within the next few days in the vicinity .</s>
</P>
<P>

<s docid="LA101889-0066" num="22" wdcount="22"> But these warnings said that if nothing happened, then the chances of a major earthquake would recede to normal for the vicinity.</s>

<s docid="LA101889-0066" num="23" wdcount="26"> The trouble was, the area was more prone to quakes at this time than any other place in the Bay Area on the San Andreas Fault.</s>

<s docid="LA101889-0066" num="24" wdcount="20"> Only the nearby Hayward fault may harbor as great a danger of a catastrophic earthquake in the Bay Area .</s>
</P>
<P>

<s docid="LA101889-0066" num="25" wdcount="22"> The San Andreas, the longest and best-known earthquake fault in California, extends from Point Arena in Mendocino County to the Salton Sea.</s>

<s docid="LA101889-0066" num="26" wdcount="18"> It has been the site of the deadliest and most destructive earthquakes in the state's recorded history .</s>
</P>
<P>

<s docid="LA101889-0066" num="27" wdcount="60"> Although Tuesday's quake was powerful, Waverly Person, chief of the National Earthquake Information Service in Golden, Colo., cautioned that at 6.9 magnitude, it should be considered only a "strong" shock, not a "major" one, as a quake in the 7.0 to 7.9 range would be classified, or a "great" one, as a quake of 8.0 or above would be .</s>
</P>
<P>

<s docid="LA101889-0066" num="28" wdcount="34"> Person and others in the Geological Survey warned Tuesday night that the probability is 40% that a temblor more powerful than Tuesday's will strike in Southern California sometime in the next three decades .</s>
</P>
<P>

<s docid="LA101889-0066" num="29" wdcount="28"> But, as it was, Tuesday's quake was about four times stronger than the devastating Sylmar-San Fernando earthquake of 1971 and 10 times stronger than the 1987 Whittier quake.</s>

<s docid="LA101889-0066" num="30" wdcount="15"> Each point of magnitude represents a 10-fold increase in the power of an earthquake .</s>
</P>
<P>

<s docid="LA101889-0066" num="31" wdcount="27"> Person said that, like most San Andreas earthquakes, this was most likely to be a strike-slip quake, with one side of the fault grinding horizontally past another.</s>

<s docid="LA101889-0066" num="32" wdcount="30"> But he said a final evaluation would have to await on-scene inspection teams that will be sent into the epicenter area today by the Geological Survey's Menlo Park office .</s>
</P>
<P>

<s docid="LA101889-0066" num="33" wdcount="39"> Jim Dewey, a research geophysicist at the National Earthquake Center, said preliminary evaluations indicated that the fracture was about 10 miles deep, and that the quake rupture extended about 30 miles south down the fault from the epicenter .</s>
</P>
<P>

<s docid="LA101889-0066" num="34" wdcount="34"> Person said that the area of strongest shaking was around Santa Cruz, although this evaluation too will have to await field evaluations, as will a final confirmation of the magnitude of the earthquake .</s>
</P>
<P>

<s docid="LA101889-0066" num="35" wdcount="55"> The nearest metropolitan area to Tuesday's earthquake, San Jose, has seen nearly a dozen earthquakes of 5 magnitude or greater in the last 10 years, but several of them have been on the Calaveras fault, which generally runs just east of San Jose, more than 10 miles east of San Andreas at this point .</s>
</P>
<P>

<s docid="LA101889-0066" num="36" wdcount="25"> Scientists do not yet understand whether the quakes on the Calaveras fault may have been a precursor, or somehow added pressure, on the San Andreas.</s>

<s docid="LA101889-0066" num="37" wdcount="24"> But when a 5.1 earthquake did strike on the Calaveras in 1988, some earthquake scientists expressed concern that this could be the case .</s>
</P>
<P>

<s docid="LA101889-0066" num="38" wdcount="19"> Between the late 1950s and 1979, there were no quakes of magnitude 5 or larger near the Bay Area.</s>

<s docid="LA101889-0066" num="39" wdcount="30"> But in August, 1979, a 6.4-magnitude quake struck under Coyote Lake east of Gilroy and south of San Jose, and since then there have been a number of quakes .</s>
</P>
<P>

<s docid="LA101889-0066" num="40" wdcount="19"> In August, Geological Survey scientists had expressed concern at the step-up in 5-magnitude quakes south of the Bay Area.</s>

<s docid="LA101889-0066" num="41" wdcount="19"> They noted that a similar series of moderately strong quakes had preceded the San Francisco quake of 1906 .</s>
</P>
<P>

<s docid="LA101889-0066" num="42" wdcount="45"> Meanwhile, a New Mexico scientist who studies tidal forces, supported by two eyewitnesses, said Tuesday night that at a private lecture in San Francisco on Oct. 10, he had stated that a strong quake in the vicinity was probable on or about Oct. 16 .</s>
</P>
<P>

<s docid="LA101889-0066" num="43" wdcount="6"> Iben Browning, of Sandia Park, N.</s>

<s docid="LA101889-0066" num="44" wdcount="21"> M., said he had based his prediction on an assessment of tidal forces caused by the moon's relationship with the Earth.</s>

<s docid="LA101889-0066" num="45" wdcount="23"> He said he had decided to keep the assessment private because he feared that publicity about it would cause people to panic .</s>
</P>
<P>
</P>
<P>

<s docid="LA101889-0066" num="46" wdcount="3"> MAJOR QUAKE DAMAGE</s>
</P>
<P>

<s docid="LA101889-0066" num="47" wdcount="8"> 1 -- Major fires hit Marina District .</s>
</P>
<P>

<s docid="LA101889-0066" num="48" wdcount="17"> 2 -- Civic Center area buildings damaged, a 4-story building south of Market collapsed, killing 5 .</s>
</P>
<P>

<s docid="LA101889-0066" num="49" wdcount="14"> 3 -- Central Freeway (101 inside San Francisco city limits) buckled and closed .</s>
</P>
<P>

<s docid="LA101889-0066" num="50" wdcount="8"> 4 -- Embarcadero Freeway damaged and shut .</s>
</P>
<P>

<s docid="LA101889-0066" num="51" wdcount="8"> 5 -- Interstate 280 from junction with Rt.</s>

<s docid="LA101889-0066" num="52" wdcount="5"> 101 to downtown closed .</s>
</P>
<P>

<s docid="LA101889-0066" num="53" wdcount="7"> 6 -- Candlestick Park damaged, evacuated .</s>
</P>
<P>

<s docid="LA101889-0066" num="54" wdcount="12"> 7 -- San Francisco Airport closed, control tower reportedly in shambles .</s>
</P>
<P>

<s docid="LA101889-0066" num="55" wdcount="17"> 8 -- Portion of San Francisco-Oakland Bay Bridge at eastern end collapsed; one person reported killed .</s>
</P>
<P>

<s docid="LA101889-0066" num="56" wdcount="10"> 9 -- Bay Area Rapid Transit system shut down .</s>
</P>
<P>

<s docid="LA101889-0066" num="57" wdcount="10"> 10 -- Double-decked portion of Interstate 880 (Nimitz Freeway) collapsed.</s>

<s docid="LA101889-0066" num="58" wdcount="11"> Estimates were as high as 200 dead and hundreds injured .</s>
</P>
<P>

<s docid="LA101889-0066" num="59" wdcount="15"> 11 -- Highway 17 in Oakland closed at Summit St. overcrossing because of collapse .</s>
</P>
<P>

<s docid="LA101889-0066" num="60" wdcount="6"> 12 -- Oakland Airport closed .</s>
</P>
<P>
</P>
<P>

<s docid="LA101889-0066" num="61" wdcount="4"> OTHER AREAS OF DAMAGE</s>
</P>
<P>

<s docid="LA101889-0066" num="62" wdcount="16"> Major damage to interchange of Bayshore Fwy (101) and State Route 92 in San Mateo .</s>
</P>
<P>

<s docid="LA101889-0066" num="63" wdcount="9"> Damage to 3rd Avenue overpass in San Mateo .</s>
</P>
<P>

<s docid="LA101889-0066" num="64" wdcount="12"> Portions of Interstate 280 closed in Los Altos due to buckling .</s>
</P>
<P>

<s docid="LA101889-0066" num="65" wdcount="8"> Two killed at Santa Cruz shopping mall .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA101889-0066" num="66" wdcount="10"> Map, MAJOR QUAKE DAMAGE, ROBERT ALLEN / Los Angeles Times</s>
</P>
</GRAPHIC>
<SUBJECT>
<P>

<s docid="LA101889-0066" num="67" wdcount="22"> EARTHQUAKES -- SAN FRANCISCO; FORECASTS; EARTHQUAKES -- CALIFORNIA; SAN ANDREAS FAULT; SANTA CRUZ (CA); CALAVERAS FAULT; SCIENTISTS; SEISMOLOGY; EARTHQUAKES -- NORTHERN CALIFORNIA</s>
</P>
</SUBJECT>
</DOC>
