<DOC>
<DOCNO>

<s docid="AP880713-0121" num="1" wdcount="1"> AP880713-0121</s>
</DOCNO>
<FILEID>

<s docid="AP880713-0121" num="2" wdcount="2"> AP-NR-07-13-88 1353EDT</s>
</FILEID>
<FIRST>

<s docid="AP880713-0121" num="3" wdcount="7"> u a PM-DroughtRdp 4thLd-Writethru a0658 07-13 0694</s>
</FIRST>
<SECOND>

<s docid="AP880713-0121" num="4" wdcount="7"> PM-Drought Rdp, 4th Ld - Writethru, a0658,0706</s>
</SECOND>
<HEAD>

<s docid="AP880713-0121" num="5" wdcount="5"> Deluge in Some Drought Areas</s>
</HEAD>
<NOTE>

<s docid="AP880713-0121" num="6" wdcount="11"> Eds: LEADS with 4 grafs to update with arrival of hay.</s>

<s docid="AP880713-0121" num="7" wdcount="8"> Picks up 5th graf pvs, `The Agriculture ...'.</s>

<s docid="AP880713-0121" num="8" wdcount="15"> SUBS grafs 14 through 16, `The first...', to update with arrival and plans for distribution.</s>

<s docid="AP880713-0121" num="9" wdcount="7"> Picks up 17th graf pvs, `The delay...'.</s>

<s docid="AP880713-0121" num="10" wdcount="3"> ^With PM-Drought-Congress, Bjt</s>
</NOTE>
<BYLINE>

<s docid="AP880713-0121" num="11" wdcount="3"> By JONATHAN OATIS</s>
</BYLINE>
<BYLINE>

<s docid="AP880713-0121" num="12" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<TEXT>

<s docid="AP880713-0121" num="13" wdcount="36"> Heavy rain deluged some drought-hit areas as Congress began working on a package of relief for America's farmers, and farmers in Kentucky today greeted the arrival of the first shipment of hay airlifted free from Oregon.</s>

<s docid="AP880713-0121" num="14" wdcount="40"> ``Everything looks so good with a bit of rain over the past 24 hours,'' farmer Herman Krone said Tuesday at his 2,800-acre farm in southern Illinois, which President Reagan plans to visit Thursday during a tour of the drought-stricken area.</s>

<s docid="AP880713-0121" num="15" wdcount="15"> However, Krone said, almost one-third of his 1,200 acres of corn already have been lost.</s>

<s docid="AP880713-0121" num="16" wdcount="32"> Marth Wilkinson, wife of Kentucky Gov. Wallace Wilkinson and business manager of the family's farm, was at Louisville's Standiford Field today for the arrival of the first hay shipment from Portland, Ore.</s>

<s docid="AP880713-0121" num="17" wdcount="26"> United Parcel Service plans to ship free of charge 20 to 30 tons of hay from Portland to Louisville each day for the next two weeks.</s>

<s docid="AP880713-0121" num="18" wdcount="16"> The Agriculture Department, meanwhile, issued a report predicting severe damage to the harvest from the drought.</s>

<s docid="AP880713-0121" num="19" wdcount="21"> It estimated, for example, that corn output this year would shrivel to 5.2 billion bushels, down from 7.06 billion last year.</s>

<s docid="AP880713-0121" num="20" wdcount="20"> The dry weather is ``the largest drought that our nation has ever experienced,'' Agriculture Secretary Richard E. Lyng told legislators.</s>

<s docid="AP880713-0121" num="21" wdcount="17"> ``I think history will show that it's truly more mammoth than any of us has ever experienced''.</s>

<s docid="AP880713-0121" num="22" wdcount="13"> Extremely heavy rain fell Tuesday in sections of Texas, Louisiana, Oklahoma and Arkansas.</s>

<s docid="AP880713-0121" num="23" wdcount="31"> In Texas, more than 6 inches fell in 75 minutes in Mesquite, washing a pickup truck and several cars into a creek and leaving some homes 8 inches deep in water.</s>

<s docid="AP880713-0121" num="24" wdcount="17"> Water was up to the tops of cars in Garland and street flooding was reported in Heath.</s>

<s docid="AP880713-0121" num="25" wdcount="7"> Nearly 6 inches fell in DeQueen, Ark.</s>

<s docid="AP880713-0121" num="26" wdcount="18"> Showers and thunderstorms were widespread over the Middle Atlantic States, the Tennessee Valley and the Gulf Coast states.</s>

<s docid="AP880713-0121" num="27" wdcount="8"> Thunderstorms boomed today over the Dakotas and Minnesota.</s>

<s docid="AP880713-0121" num="28" wdcount="34"> In Washington, the House and Senate Agriculture committees began working on wide-ranging legislation that would provide payments of up to $100,000 each to farmers whose crops have been wiped out by the dry spell.</s>

<s docid="AP880713-0121" num="29" wdcount="5"> House Agriculture Committee Chairman E.</s>

<s docid="AP880713-0121" num="30" wdcount="14"> ``Kika'' de la Garza, D-Texas, called for final action on the measure by mid-August.</s>

<s docid="AP880713-0121" num="31" wdcount="15"> The drought has dried up pastures, forcing livestock farmers to go far afield for hay.</s>

<s docid="AP880713-0121" num="32" wdcount="29"> The hay that arrived in Kentuky today will be stored at a fairgrounds, and distributed next week by lottery to farmers, who will pay for the hay, officials said.</s>

<s docid="AP880713-0121" num="33" wdcount="19"> ``It seems like everyone in the state wants this hay,'' state Department of Agriculture spokesman Roger Nesbitt said Tuesday.</s>

<s docid="AP880713-0121" num="34" wdcount="27"> The delay has angered some farmers, such as Bernetta Smith, who expects to run out of hay for her 147 beef cows in one to two days.</s>

<s docid="AP880713-0121" num="35" wdcount="13"> ``I don't see any sense in storing it because people need this hay.</s>

<s docid="AP880713-0121" num="36" wdcount="6"> I don't understand it,'' she said.</s>

<s docid="AP880713-0121" num="37" wdcount="37"> At least 50 truckloads of hay gathered from the Carolinas and Virginia are being shipped to Ohio on Thursday in a drive organized by the Charlotte Motor Speedway and the National Association for Stock Car Auto Racing.</s>

<s docid="AP880713-0121" num="38" wdcount="14"> Despite the recent rain, communities with dried-up water supplies continue to restrict water use.</s>

<s docid="AP880713-0121" num="39" wdcount="36"> Until the drought ends, the 650 residents of Vintondale, Pa., about 50 miles east of Pittsburgh, will have to do without running water from 7 p.m. to 7 a.m. every day, Mayor Michael Palovich said Tuesday.</s>

<s docid="AP880713-0121" num="40" wdcount="15"> Palovich said he was trying to arrange for an emergency supply to be trucked in.</s>

<s docid="AP880713-0121" num="41" wdcount="14"> The drought has had a silver lining for anglers in the Reno, Nevada, area.</s>

<s docid="AP880713-0121" num="42" wdcount="36"> The state Board of Wildlife Commissioners removed the limit on catches at Rye Patch and Lahontan reservoirs because the reservoirs are expected to be dry by the end of summer, leaving fish high and dry .</s>
</TEXT>
</DOC>
