<DOC>
<DOCNO>

<s docid="AP880714-0156" num="1" wdcount="1"> AP880714-0156</s>
</DOCNO>
<FILEID>

<s docid="AP880714-0156" num="2" wdcount="2"> AP-NR-07-14-88 2104EDT</s>
</FILEID>
<FIRST>

<s docid="AP880714-0156" num="3" wdcount="5"> r a AM-DroughtSymposium 07-14 0283</s>
</FIRST>
<SECOND>

<s docid="AP880714-0156" num="4" wdcount="2"> AM-Drought Symposium,0290</s>
</SECOND>
<HEAD>

<s docid="AP880714-0156" num="5" wdcount="5"> Expert Suggests Planets Affect Drought</s>
</HEAD>
<HEAD>

<s docid="AP880714-0156" num="6" wdcount="3"> With AM-Drought-Northeast Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP880714-0156" num="7" wdcount="4"> By JOHN A. BOLT</s>
</BYLINE>
<BYLINE>

<s docid="AP880714-0156" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880714-0156" num="9" wdcount="3"> SMYRNA, Ga. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880714-0156" num="10" wdcount="27"> Weather experts discussed the drought Thursday and its possible causes and effects, and said they hoped to produce a consensus on how much longer it will last.</s>

<s docid="AP880714-0156" num="11" wdcount="15"> All of the speakers at the 1988 Drought Symposium called for more research and study.</s>

<s docid="AP880714-0156" num="12" wdcount="10"> ``There's an enormous number of possibilities that one could chase.</s>

<s docid="AP880714-0156" num="13" wdcount="13"> The next business of the scientist is to eliminate the possibilities of ...</s>

<s docid="AP880714-0156" num="14" wdcount="24"> and extend the range of analysis and look for cause and effect,'' said David Rodenhuis, director of the federal Climate Analysis Center in Washington.</s>

<s docid="AP880714-0156" num="15" wdcount="24"> The symposium attended by 13 state and national experts was sponsored by The Weather Channel, an Atlanta-based cable network, which broadcast the meeting live.</s>

<s docid="AP880714-0156" num="16" wdcount="41"> John Hope, the network's hurricane specialist and a former forecaster with the National Hurricane Center in Miami, Fla., said the drought in the Southeast might be lessened or ended in the next few months by a heavier than normal hurricane season.</s>

<s docid="AP880714-0156" num="17" wdcount="20"> Hope said current weather conditions point to more tropical storms, more of which should become hurricanes, in this hurricane season.</s>

<s docid="AP880714-0156" num="18" wdcount="19"> He stressed that a hurricane's effect on drought is variable, depending on the intensity and speed of the storm.</s>

<s docid="AP880714-0156" num="19" wdcount="20"> Nevertheless, he said, some Southeastern states get as much as 25 pecent of their rainfall in some months from hurricanes.</s>

<s docid="AP880714-0156" num="20" wdcount="25"> Georgia state climatologist Gayther Plummer told the symposium he thought the position of the planet Jupiter had something to do with drought in the Southeast.</s>

<s docid="AP880714-0156" num="21" wdcount="9"> However, Rodenhuis said he was skeptical about Plummer's thesis.</s>

<s docid="AP880714-0156" num="22" wdcount="14"> ``It's very necessary to be cautious and analytical about the issue,'' he said .</s>
</TEXT>
</DOC>
