<DOC>
<DOCNO>

<s docid="AP880715-0065" num="1" wdcount="1"> AP880715-0065</s>
</DOCNO>
<FILEID>

<s docid="AP880715-0065" num="2" wdcount="2"> AP-NR-07-15-88 0637EDT</s>
</FILEID>
<FIRST>

<s docid="AP880715-0065" num="3" wdcount="5"> r a PM-DroughtSymposium 07-15 0450</s>
</FIRST>
<SECOND>

<s docid="AP880715-0065" num="4" wdcount="2"> PM-Drought Symposium,0463</s>
</SECOND>
<HEAD>

<s docid="AP880715-0065" num="5" wdcount="10"> Experts: Public Interest In Climate May Dry Up After Drought</s>
</HEAD>
<DATELINE>

<s docid="AP880715-0065" num="6" wdcount="3"> SMYRNA, Ga. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880715-0065" num="7" wdcount="32"> Public interest in the Earth's troubled climate may be washed away with the heavy rains that are needed to end the current U.S. drought, weather experts warned during a drought symposium here.</s>

<s docid="AP880715-0065" num="8" wdcount="19"> ``Society tends to flit from hysteria to hysteria,'' said Pat Michaels, Virginia's state climatologist and moderator of the symposium.</s>

<s docid="AP880715-0065" num="9" wdcount="30"> He said the 1988 drought, although not as dry as a 1986 drought in many places, has drawn much attention because some of the affected areas include large media centers.</s>

<s docid="AP880715-0065" num="10" wdcount="3"> ``I'm worried ...</s>

<s docid="AP880715-0065" num="11" wdcount="25"> that when the next drought happens, we are going to have to rediscover the climate problem,'' said Michaels, president of the Association of State Climatologists.</s>

<s docid="AP880715-0065" num="12" wdcount="35"> Experts said Thursday that the greenhouse effect _ the warming of the Earth's atmosphere _ has brought needed attention to changes in the global climate, even though it is not directly related to the drought.</s>

<s docid="AP880715-0065" num="13" wdcount="33"> Many of the 13 climatologists and meterologists at the symposium agreed that the Earth's temperature is warming, but they debated whether it is a short- or long-term phenomenon and its impact on Earth.</s>

<s docid="AP880715-0065" num="14" wdcount="35"> However, Alan Hecht, director of the National Climate Program in Washington, D.C., said the uncertainty means policymakers should begin to deal with the possible effects, especially undertaking policies that ``make sense in their own right''.</s>

<s docid="AP880715-0065" num="15" wdcount="21"> Mankind must reduce reliance on fossil fuels, he said, by becoming more energy efficient, replanting forests and investigating alternative energy supplies.</s>

<s docid="AP880715-0065" num="16" wdcount="27"> Scientists have warned in recent years that Earth's atmosphere is gaining in carbon dioxide and other gases, which trap heat and cause the overall temperature to rise.</s>

<s docid="AP880715-0065" num="17" wdcount="21"> Besides fossil fuels, the depletion of forests in South America has been blamed for the increase of carbon dioxide and methane.</s>

<s docid="AP880715-0065" num="18" wdcount="19"> Some have warned that higher temperature will change the character of many countries, for example drying out the U.S.</s>

<s docid="AP880715-0065" num="19" wdcount="6"> Midwest or melting polar ice caps.</s>

<s docid="AP880715-0065" num="20" wdcount="17"> The symposium was sponsored by The Weather Channel, an Atlanta-based cable network, which broadcast the meeting live.</s>

<s docid="AP880715-0065" num="21" wdcount="23"> Earlier Thursday, the climatologists were told the movement of planets and the moon and sunspots may help lead to drought in the Southeast.</s>

<s docid="AP880715-0065" num="22" wdcount="35"> ``There is some evidence that as Jupiter goes around the sun at its fastest point, there are drought conditions in the Southeast in the months of April and October,'' Georgia state climatologist Gayther Plummer said.</s>

<s docid="AP880715-0065" num="23" wdcount="19"> However, David Rodenhuis, director of the federal Climate Analysis Center in Washington, said he was skeptical of Plummer's thesis.</s>

<s docid="AP880715-0065" num="24" wdcount="12"> ``There's an enormous number of possibilities that one could chase,'' Rodenhuis said.</s>

<s docid="AP880715-0065" num="25" wdcount="9"> ``The next business of the scientist is to ...</s>

<s docid="AP880715-0065" num="26" wdcount="11"> extend the range of analysis and look for cause and effect.''</s>
</TEXT>
</DOC>
