<DOC>
<DOCNO>

<s docid="AP880714-0085" num="1" wdcount="1"> AP880714-0085</s>
</DOCNO>
<FILEID>

<s docid="AP880714-0085" num="2" wdcount="2"> AP-NR-07-14-88 1057EDT</s>
</FILEID>
<FIRST>

<s docid="AP880714-0085" num="3" wdcount="7"> r w PM-WeatherForecast 1stLd-Writethru a0469 07-14 0519</s>
</FIRST>
<SECOND>

<s docid="AP880714-0085" num="4" wdcount="5"> PM-Weather Forecast, 1st Ld-Writethru, a0469,530</s>
</SECOND>
<HEAD>

<s docid="AP880714-0085" num="5" wdcount="3"> Most of U.S.</s>

<s docid="AP880714-0085" num="6" wdcount="9"> To Be Hot, Dry Until Mid-August, Weather Service Says</s>
</HEAD>
<NOTE>

<s docid="AP880714-0085" num="7" wdcount="16"> Eds: Top 5 grafs new to include climate assessment, picks up 3rd graf pvs, That area.</s>

<s docid="AP880714-0085" num="8" wdcount="6"> Adds 2 grafs at end .</s>
</NOTE>
<DATELINE>

<s docid="AP880714-0085" num="9" wdcount="2"> WASHINGTON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880714-0085" num="10" wdcount="22"> Weather forecasters today were offering drought-stricken farmers little prospect of relief in separate outlooks for the next 30 days and three months.</s>

<s docid="AP880714-0085" num="11" wdcount="30"> A new climate assessment of the ongoing drought said ``many areas now experiencing extreme drought have less than a 4 percent chance of recovering from the drought within 3 months''.</s>

<s docid="AP880714-0085" num="12" wdcount="15"> The disappointing forecast came as President Reagan headed to the Midwest to inspect drought-plagued farms.</s>

<s docid="AP880714-0085" num="13" wdcount="14"> On Tuesday the Agriculture Department reported sharp declines in the outlook for several crops.</s>

<s docid="AP880714-0085" num="14" wdcount="43"> That was followed Wednesday by a 30-day forecast from the National Weather Service saying that drought-stricken areas from the Dakotas east to New York and from the Canadian border to Oklahoma, Arkansas and Tennessee are likely to continue to be short of rain.</s>

<s docid="AP880714-0085" num="15" wdcount="24"> That area, which includes the major grain-growing states where crops already are suffering, is given a 55 percent chance of less than normal rainfall.</s>

<s docid="AP880714-0085" num="16" wdcount="24"> And some states in the center of the area, stretching from West Virginia to Nebraska and from Wisconsin to Missouri, may be even drier.</s>

<s docid="AP880714-0085" num="17" wdcount="12"> They are given a 60 percent chance of being short of precipitation.</s>

<s docid="AP880714-0085" num="18" wdcount="25"> A slice of southern California, including Los Angeles, is the driest area in the forecast, with a 70 percent chance of having below normal rainfall.</s>

<s docid="AP880714-0085" num="19" wdcount="12"> The rest of coastal California also will be dry, the forecast said.</s>

<s docid="AP880714-0085" num="20" wdcount="30"> The outlook also says there's a 55 percent chance of hotter than normal temperatures through the U.S. heartland from New England to Idaho and from the Canadian border to Oklahoma.</s>

<s docid="AP880714-0085" num="21" wdcount="27"> Within that area, the chances of high temperatures are above 65 percent in Wyoming, while central Midwestern states have a 60 percent chance of above average temperatures.</s>

<s docid="AP880714-0085" num="22" wdcount="19"> Wetter than normal weather is predicted for west and south Texas, and parts of New Mexico, Arizona and Utah.</s>

<s docid="AP880714-0085" num="23" wdcount="19"> Normal precipitation is forecast for the Atlantic and Gulf coast states, along with the Northwest and northern Mountain States.</s>

<s docid="AP880714-0085" num="24" wdcount="21"> The Weather Service said normal temperatures are expected for the Atlantic states from Virginia south, and for the Gulf Coast states.</s>

<s docid="AP880714-0085" num="25" wdcount="24"> West Texas and New Mexico may be cooler than normal, but the far West is expected to see its normal quota of summer heat.</s>

<s docid="AP880714-0085" num="26" wdcount="35"> The separate drought impact assessment, issued by the National Oceanic and Atmospheric Administration's Climate Office, points out that predicting an end to the drought is a complex thing, since dry spells have no normal lifetime.</s>

<s docid="AP880714-0085" num="27" wdcount="24"> The low 4 percent probability of an end within 3 months is based simply on a statistical analysis of past droughts, the agency said.</s>

<s docid="AP880714-0085" num="28" wdcount="29"> The report noted that as of the end of June, 29 percent of the continental United States was experiencing severe or extreme drought, with parts of 35 states affected.</s>

<s docid="AP880714-0085" num="29" wdcount="28"> That puts the current drought on the same level as the one in 1911, but still less severe than the droughts of 1936, 1931, 1956 and 1934 .</s>
</TEXT>
</DOC>
