<DOC>
<DOCNO>

<s docid="AP880716-0052" num="1" wdcount="1"> AP880716-0052</s>
</DOCNO>
<FILEID>

<s docid="AP880716-0052" num="2" wdcount="2"> AP-NR-07-16-88 0800EDT</s>
</FILEID>
<FIRST>

<s docid="AP880716-0052" num="3" wdcount="5"> u a PM-Drought-States 07-16 1070</s>
</FIRST>
<SECOND>

<s docid="AP880716-0052" num="4" wdcount="1"> PM-Drought-States,1149</s>
</SECOND>
<HEAD>

<s docid="AP880716-0052" num="5" wdcount="5"> State-By-State Survey of Drought Developments</s>
</HEAD>
<BYLINE>

<s docid="AP880716-0052" num="6" wdcount="4"> By The Associated Press</s>
</BYLINE>
<TEXT>

<s docid="AP880716-0052" num="7" wdcount="10"> Here is a state-by-state summary of the latest drought developments:</s>
</TEXT>
<HEAD>

<s docid="AP880716-0052" num="8" wdcount="1"> ALABAMA</s>
</HEAD>
<TEXT>

<s docid="AP880716-0052" num="9" wdcount="21"> Recent rain in central and south Alabama haven't helped cities' water supplies enough to lift surcharges and limits on outdoor watering.</s>

<s docid="AP880716-0052" num="10" wdcount="32"> Northern Alabama has missed most of the rain and the region's top crop, cotton, is in a critical situation, said John Trotman, state director of the Agricultural Stabilization and Conservation Service .</s>
</TEXT>
<HEAD>

<s docid="AP880716-0052" num="11" wdcount="1"> GEORGIA</s>
</HEAD>
<TEXT>

<s docid="AP880716-0052" num="12" wdcount="24"> Georgia's carpet industry may be forced to reduce production and lay off workers if the drought continues for an extended period, industry officials said.</s>

<s docid="AP880716-0052" num="13" wdcount="33"> ``It is something you don't like to think about, but if you don't have water, you can't run your mills,'' said John A. Shaheen, vice chairman of World Carpets Inc. in Dalton .</s>
</TEXT>
<HEAD>

<s docid="AP880716-0052" num="14" wdcount="1"> ILLINOIS</s>
</HEAD>
<TEXT>

<s docid="AP880716-0052" num="15" wdcount="21"> The drought has inflicted serious damage to wildlife along the Illinois River, even though the water level has remained near normal.</s>

<s docid="AP880716-0052" num="16" wdcount="35"> Wayne Herndon, a biologist with the state Department of Conservation, said the drought, now nearly midway through its second summer, has damaged the river's backwater lakes, virtually eliminating a year's supply of the river's gamefish.</s>

<s docid="AP880716-0052" num="17" wdcount="37"> The mercury hit 100 degrees Friday at O'Hare International Airport, bettering the previous high for the day of 99 and establishing a second record by giving the city its fifth 100-degree or better temperature of the summer.</s>

<s docid="AP880716-0052" num="18" wdcount="12"> Chicago sweltered through four 100-degree days in 1934, 1947 and 1953 .</s>
</TEXT>
<HEAD>

<s docid="AP880716-0052" num="19" wdcount="1"> INDIANA</s>
</HEAD>
<TEXT>

<s docid="AP880716-0052" num="20" wdcount="31"> Thunderstorms brought rain, lightning and 70 mph winds to northern Indiana Friday night, causing widespread power outages in the city of Fort Wayne and apparently causing a toy factory to collapse.</s>

<s docid="AP880716-0052" num="21" wdcount="4"> No injuries were reported.</s>

<s docid="AP880716-0052" num="22" wdcount="26"> The Indiana Board of Health issued a heat warning as temperatures soared above 100 and humidity levels boosted the heat index to more than 110 degrees.</s>

<s docid="AP880716-0052" num="23" wdcount="14"> The National Weather Service said the conditions likely would continue through the weekend .</s>
</TEXT>
<HEAD>

<s docid="AP880716-0052" num="24" wdcount="1"> IOWA</s>
</HEAD>
<TEXT>

<s docid="AP880716-0052" num="25" wdcount="31"> National Guardsmen stood by with 400 gallons of drinking water for about 50 homes in Elk Horn while officials tried to find more water to get the town through the drought.</s>

<s docid="AP880716-0052" num="26" wdcount="2"> The U.S.</s>

<s docid="AP880716-0052" num="27" wdcount="20"> Agriculture Department announced Agriculture Secretary Richard Lyng would visit Iowa as part of a 10-state tour of drought areas .</s>
</TEXT>
<HEAD>

<s docid="AP880716-0052" num="28" wdcount="1"> KANSAS</s>
</HEAD>
<TEXT>

<s docid="AP880716-0052" num="29" wdcount="13"> Severe thunderstorms spawning tornadoes and strong winds rolled across central Kansas Friday night.</s>

<s docid="AP880716-0052" num="30" wdcount="18"> A tornado touched down near Clay Center, destroying an unoccupied mobile home and damaging barns and hog sheds.</s>

<s docid="AP880716-0052" num="31" wdcount="9"> High winds also damaged trees and power lines .</s>
</TEXT>
<HEAD>

<s docid="AP880716-0052" num="32" wdcount="1"> KENTUCKY</s>
</HEAD>
<TEXT>

<s docid="AP880716-0052" num="33" wdcount="23"> Agriculture Commissioner Ward ``Butch'' Burnette returned from Oregon, saying he had prospects for perhaps 10,000 tons of hay, badly needed by cattle producers.</s>

<s docid="AP880716-0052" num="34" wdcount="28"> One railroad, CSX Transportation Corp., offered to bring the hay free of charge from Chicago if the Union Pacific or Burlington Northern lines could get it to Chicago.</s>

<s docid="AP880716-0052" num="35" wdcount="15"> Thirty tons of Oregon hay arrived by jet in Louisville, courtesy of United Parcel Service.</s>

<s docid="AP880716-0052" num="36" wdcount="11"> That shipment, like several others, was earmarked for distribution Monday .</s>
</TEXT>
<HEAD>

<s docid="AP880716-0052" num="37" wdcount="1"> MICHIGAN</s>
</HEAD>
<TEXT>

<s docid="AP880716-0052" num="38" wdcount="21"> Severe thunderstorms accompanied by high winds and hail moved over much of Michigan on Friday, downing trees and causing power outages.</s>

<s docid="AP880716-0052" num="39" wdcount="17"> Concern over the effects of the drought on the timber industry outweighed relief brought by the showers.</s>

<s docid="AP880716-0052" num="40" wdcount="33"> ``You have to take more precautions, and you can't use certain machinery with exhaust systems that send sparks that might set a fire,'' said Matt Repar, who has been logging for 28 years.</s>

<s docid="AP880716-0052" num="41" wdcount="2"> The U.S.</s>

<s docid="AP880716-0052" num="42" wdcount="19"> Forest Service has banned all machinery with internal combustion engines from the Upper Peninsula's Hiawatha National Forest after noon.</s>

<s docid="AP880716-0052" num="43" wdcount="24"> John McGregor of the state Department of Natural Resources has said that if the drought keeps up, the state may ban commercial logging .</s>
</TEXT>
<HEAD>

<s docid="AP880716-0052" num="44" wdcount="1"> MINNESOTA</s>
</HEAD>
<TEXT>

<s docid="AP880716-0052" num="45" wdcount="21"> A brief thunderstorm brought little relief following record heat that helped kill 3,000 young turkeys near Princeton and prompted health warnings.</s>

<s docid="AP880716-0052" num="46" wdcount="20"> Friday's high of 102 degrees in the Twin Cities topped the previous record for the date, 101 degrees i 1931.</s>

<s docid="AP880716-0052" num="47" wdcount="20"> With the ``heat index'' _ the summertime equivalent of the wind-chill factor _ forecasters said 102 degrees felt like 114.</s>

<s docid="AP880716-0052" num="48" wdcount="26"> ``This is the kind of situation that is really bad for the sick and elderly, and especially the elderly,'' said Greg Spoden, assistant state climatologist .</s>
</TEXT>
<HEAD>

<s docid="AP880716-0052" num="49" wdcount="1"> MISSOURI</s>
</HEAD>
<TEXT>

<s docid="AP880716-0052" num="50" wdcount="25"> Gov. John Ashcroft issued his second statewide heat alert of the summer, urging private and public organizations to aid those suffering from the sizzling temperatures.</s>

<s docid="AP880716-0052" num="51" wdcount="34"> ``Unless we act now to gear up public and private efforts to care for those without shelter from the stifling heat, the potential for human loss over the weekend is staggering,'' Ashcroft said .</s>
</TEXT>
<HEAD>

<s docid="AP880716-0052" num="52" wdcount="1"> MONTANA</s>
</HEAD>
<TEXT>

<s docid="AP880716-0052" num="53" wdcount="26"> More than 700 firefighters battled a lightning-caused blaze that combined with other fires and spread to 14,800 acres in the Custer National Forest of southeast Montana.</s>

<s docid="AP880716-0052" num="54" wdcount="19"> Bulldozers, helicopters and bombers dropping fire retardant fought the blaze in the tinder-dry forest on the South Dakota border</s>
</TEXT>
<HEAD>

<s docid="AP880716-0052" num="55" wdcount="2"> NORTH DAKOTA</s>
</HEAD>
<TEXT>

<s docid="AP880716-0052" num="56" wdcount="38"> The Army Corps of Engineers has further reduced the flow of water through Orwell Dam on the Otter Tail River near Fergus Falls, Minn., a main feeder of the Red River, which runs along the Minnesota-North Dakota border.</s>

<s docid="AP880716-0052" num="57" wdcount="17"> The reduction could affect Fargo's supply of water, according to Ron Hendrickson, city water plant superintendent .</s>
</TEXT>
<HEAD>

<s docid="AP880716-0052" num="58" wdcount="1"> OHIO</s>
</HEAD>
<TEXT>

<s docid="AP880716-0052" num="59" wdcount="15"> Gov. Richard Celeste signed an executive order banning open burning because of extraordinary dry conditions.</s>

<s docid="AP880716-0052" num="60" wdcount="22"> In Columbus, farmers began loading up their shares of more than 40,000 bales of hay delivered this week from three Southern states.</s>

<s docid="AP880716-0052" num="61" wdcount="16"> Farmers in the southwestern corner of the state postponed cloud-seeding because there were no clouds .</s>
</TEXT>
<HEAD>

<s docid="AP880716-0052" num="62" wdcount="2"> SOUTH DAKOTA</s>
</HEAD>
<TEXT>

<s docid="AP880716-0052" num="63" wdcount="9"> Representatives from Japanese flour mills visited with wheat producers.</s>

<s docid="AP880716-0052" num="64" wdcount="27"> Ben Handcock, executive director of the South Dakota Wheat Commission, said the Japanese would buy wheat, but probably not from this year's crop because of the drought.</s>

<s docid="AP880716-0052" num="65" wdcount="18"> ``They heard about the drought the same as everybody else did and they think we're out of wheat.</s>

<s docid="AP880716-0052" num="66" wdcount="25"> The fact of the matter is that we have a lot of good quality wheat left from last year and previous years,'' Handcock said .</s>
</TEXT>
<HEAD>

<s docid="AP880716-0052" num="67" wdcount="1"> TENNESSEE</s>
</HEAD>
<TEXT>

<s docid="AP880716-0052" num="68" wdcount="19"> Farmers say the drought is causing a shortage of feed, grass and water, leading them to sell more livestock.</s>

<s docid="AP880716-0052" num="69" wdcount="10"> At the Tennessee-Kentucky Livestock Inc. auction barn in Guthrie, Ky.</s>

<s docid="AP880716-0052" num="70" wdcount="14"> , livestock sales have doubled, said an owner of the barn, Dorris Bryant .</s>
</TEXT>
<HEAD>

<s docid="AP880716-0052" num="71" wdcount="1"> WISCONSIN</s>
</HEAD>
<TEXT>

<s docid="AP880716-0052" num="72" wdcount="20"> Gov. Tommy G. Thompson signed a drought relief bill Friday making $35 million in emergency loans available to Wisconsin farmers.</s>

<s docid="AP880716-0052" num="73" wdcount="14"> Legislators said it could help up to 5,000 farmers avoid losing their farms .</s>
</TEXT>
</DOC>
