<DOC>
<DOCNO>

<s docid="AP880711-0221" num="1" wdcount="1"> AP880711-0221</s>
</DOCNO>
<FILEID>

<s docid="AP880711-0221" num="2" wdcount="2"> AP-NR-07-11-88 1633EDT</s>
</FILEID>
<FIRST>

<s docid="AP880711-0221" num="3" wdcount="5"> r f AM-Drought-Lyng 07-11 0286</s>
</FIRST>
<SECOND>

<s docid="AP880711-0221" num="4" wdcount="1"> AM-Drought-Lyng,0297</s>
</SECOND>
<HEAD>

<s docid="AP880711-0221" num="5" wdcount="11"> Lyng Says Drought Could Prompt Relaxed Crop Acreage Controls Next Year</s>
</HEAD>
<DATELINE>

<s docid="AP880711-0221" num="6" wdcount="2"> WASHINGTON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880711-0221" num="7" wdcount="29"> The drought may force the government to ease crop acreage controls next year to help the United States rebuild its grain inventories, Agriculture Secretary Richard E. Lyng said Monday.</s>

<s docid="AP880711-0221" num="8" wdcount="30"> But the United States ``will continue to be a major player'' in world agriculture and in 1989 ``should be able to bounce back'' from this year's drought losses, he said.</s>

<s docid="AP880711-0221" num="9" wdcount="18"> Lyng's remarks were prepared for delivery at a meeting of farm magazine, extension, advertising, co-op and broadcast editors.</s>

<s docid="AP880711-0221" num="10" wdcount="29"> A larger portion of the United States suffered from some degree of drought stress in May and June than at any point since records began in 1895, he said.</s>

<s docid="AP880711-0221" num="11" wdcount="22"> Moreover, on July 2, about 35 percent of the contiguous United States was in the ``severe to extreme'' drought category, he said.</s>

<s docid="AP880711-0221" num="12" wdcount="21"> In 1934, more than 60 percent was so rated, and in August 1954 more than 50 percent was in that category.</s>

<s docid="AP880711-0221" num="13" wdcount="33"> ``Because of the large early season area now experiencing drought in the U.S., 1988 appears to have the potential to approach or exceed the drought-affected areas of the 1930s and 1950s,'' Lyng said.</s>

<s docid="AP880711-0221" num="14" wdcount="39"> Even with the severe drought, there will be an adequate supply of food grains and livestock feed grains so that the United States ``will be able to take care of our domestic needs and our export demand,'' he said.</s>

<s docid="AP880711-0221" num="15" wdcount="20"> Lyng said total consumption of 1988 crops will probably be somewhat less than previously estimated because prices are much higher.</s>

<s docid="AP880711-0221" num="16" wdcount="29"> ``But it is important to note that we will have no shortages, that we will still be able to accommodate the needs of our overseas buyers,'' he said .</s>
</TEXT>
</DOC>
