<DOC>
<DOCNO>

<s docid="AP880711-0056" num="1" wdcount="1"> AP880711-0056</s>
</DOCNO>
<FILEID>

<s docid="AP880711-0056" num="2" wdcount="2"> AP-NR-07-11-88 0957EDT</s>
</FILEID>
<FIRST>

<s docid="AP880711-0056" num="3" wdcount="5"> r i PM-WorldFood 07-11 0314</s>
</FIRST>
<SECOND>

<s docid="AP880711-0056" num="4" wdcount="2"> PM-World Food,0322</s>
</SECOND>
<HEAD>

<s docid="AP880711-0056" num="5" wdcount="9"> U.N. Agency Projects Food Shortages Due To U.S. Drought</s>
</HEAD>
<DATELINE>

<s docid="AP880711-0056" num="6" wdcount="2"> ROME (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880711-0056" num="7" wdcount="26"> The crippling drought hitting North America is expected to reduce world grain stocks to levels that may cause food shortages in many poor countries, the U.N.</s>

<s docid="AP880711-0056" num="8" wdcount="6"> Food and Agriculture Organization reported today.</s>

<s docid="AP880711-0056" num="9" wdcount="29"> The agency projects world cereal production in 1988 to total 1.785 billion tons, only two million tons more than last year's level, which was already below the expected production.</s>

<s docid="AP880711-0056" num="10" wdcount="37"> If the drought in the United States ended now, grain production would fall close to the low levels of 1983, when a drought and farmers' participation in a government crop reduction program decreased output, the agency reported.</s>

<s docid="AP880711-0056" num="11" wdcount="32"> As a result, world grain stocks are projected to fall below 310 million tons, or 17 percent of the level the agency considers necessary to safeguard world food security, the report said.</s>

<s docid="AP880711-0056" num="12" wdcount="18"> If crop conditions in the United States and Canada continue to deteriorate, the ratio could drop even further.</s>

<s docid="AP880711-0056" num="13" wdcount="20"> ``Such a development would have serious implications for the food security, particularly of many low-income, food-deficit countries,'' the report said.</s>

<s docid="AP880711-0056" num="14" wdcount="20"> The high grain prices resulting from a lower supply would hit poor, food-importing countries the hardest, the U.N. agency warned.</s>

<s docid="AP880711-0056" num="15" wdcount="13"> It said the rising prices could also reduce food aid from developed countries.</s>

<s docid="AP880711-0056" num="16" wdcount="17"> The most severely hit crops are coarse grains _ mostly maize, barley and oats, the report said.</s>

<s docid="AP880711-0056" num="17" wdcount="11"> The agency projected good harvests in other parts of the world.</s>

<s docid="AP880711-0056" num="18" wdcount="24"> In Asia the yearly monsoon rains started on time, and production in Europe and the Soviet is expected to be larger than last year.</s>

<s docid="AP880711-0056" num="19" wdcount="13"> Grain production in South America should be slightly lower this year than last.</s>

<s docid="AP880711-0056" num="20" wdcount="19"> In the Sahel region of sub-Saharan Africa, however, locusts flourishing in unexpectedly heavy rains have damaged this year's harvest.</s>

<s docid="AP880711-0056" num="21" wdcount="14"> Potential crop losses from the pests could hit 1 million tons, FAO said .</s>
</TEXT>
</DOC>
