<DOC>
<DOCNO>

<s docid="AP880712-0250" num="1" wdcount="1"> AP880712-0250</s>
</DOCNO>
<FILEID>

<s docid="AP880712-0250" num="2" wdcount="2"> AP-NR-07-12-88 0025EDT</s>
</FILEID>
<FIRST>

<s docid="AP880712-0250" num="3" wdcount="6"> r f PM-BusinessHighlights 1stAdd 07-12 0537</s>
</FIRST>
<SECOND>

<s docid="AP880712-0250" num="4" wdcount="4"> PM-Business Highlights, 1st Add,0567</s>
</SECOND>
<BYLINE>

<s docid="AP880712-0250" num="5" wdcount="4"> By The Associated Press</s>
</BYLINE>
<TEXT>

<s docid="AP880712-0250" num="6" wdcount="39"> Kentucky's governor has criticized the federal government for being too slow in dealing with the drought, and Iowa's governor warns that farmers in his state still face potential disaster despite up to five inches of rain over the weekend.</s>

<s docid="AP880712-0250" num="7" wdcount="25"> Crews began installing pumps on barges Monday to haul fresh water to southern Louisiana towns plagued by rising salt levels in the lower Mississippi River.</s>

<s docid="AP880712-0250" num="8" wdcount="39"> Meanwhile, House Speaker Jim Wright said in Washington he hopes that a relief package with disaster payments of up to $100,000 for drought-stricken farmers will win committee approval and be ready for floor action in Congress this week .</s>
</TEXT>
<DATELINE>

<s docid="AP880712-0250" num="9" wdcount="2"> WASHINGTON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880712-0250" num="10" wdcount="28"> The drought may force the government to ease crop acreage controls next year to help the United States rebuild its grain inventories, says Agriculture Secretary Richard E. Lyng.</s>

<s docid="AP880712-0250" num="11" wdcount="31"> But the United States will continue to be a major player in world agriculture and in 1989 should be able to bounce back from this year's drought losses, he said Monday.</s>

<s docid="AP880712-0250" num="12" wdcount="30"> A larger portion of the United States suffered from some degree of drought stress in May and June than at any point since records began in 1895, Lyng said .</s>
</TEXT>
<DATELINE>

<s docid="AP880712-0250" num="13" wdcount="2"> CHICAGO (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880712-0250" num="14" wdcount="35"> Grain and soybean futures have dropped to their lowest levels in more than five weeks as weekend rains in the Midwest prompted a third straight day of plummeting prices on the Chicago Board of Trade.</s>

<s docid="AP880712-0250" num="15" wdcount="19"> July soybeans fell 66 cents a bushel Monday to $8.58, the lowest price for that contract since June 3.</s>

<s docid="AP880712-0250" num="16" wdcount="17"> Corn for July delivery dropped 20 cents to $2.89 a bushel, the lowest level since June 15.</s>

<s docid="AP880712-0250" num="17" wdcount="8"> Wheat and oat futures also closed lower .</s>
</TEXT>
<DATELINE>

<s docid="AP880712-0250" num="18" wdcount="3"> NEW YORK (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880712-0250" num="19" wdcount="33"> Crude oil futures prices have hit their lowest closing level since late 1986, hurt by a selloff that traders blame on too much supply and renewed skepticism about OPEC's ability to restrain production.</s>

<s docid="AP880712-0250" num="20" wdcount="26"> Monday's decline erased gains made last week that had been based on fears of supply disruptions caused by the oil platform explosion in the North Sea.</s>

<s docid="AP880712-0250" num="21" wdcount="30"> On the New York Mercantile Exchange, an important barometer of price trends, the August-delivery price for West Texas Intermediate crude settled at $14.78 per barrel, down from $15.46 late Friday.</s>

<s docid="AP880712-0250" num="22" wdcount="20"> It was the lowest closing price for the near-month crude contract since a $14.71 close on Nov. 3, 1986 .</s>
</TEXT>
<DATELINE>

<s docid="AP880712-0250" num="23" wdcount="2"> WASHINGTON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880712-0250" num="24" wdcount="33"> Savings institution depositors withdrew more money from their accounts than they deposited in May for the first time in seven months, while losses continued to erode the ailing industry's capital, the government reports.</s>

<s docid="AP880712-0250" num="25" wdcount="22"> The Federal Home Loan Bank Board said Monday net withdrawals at the nation's 3,102 federally insured S&Ls totaled $941 million in May.</s>

<s docid="AP880712-0250" num="26" wdcount="16"> But the decline came after seven consecutive months of net deposit gains totaling $28 billion .</s>
</TEXT>
<BYLINE>

<s docid="AP880712-0250" num="27" wdcount="4"> By The Associated Press</s>
</BYLINE>
<TEXT>

<s docid="AP880712-0250" num="28" wdcount="8"> Stock prices crept higher Monday in quiet trading.</s>

<s docid="AP880712-0250" num="29" wdcount="12"> The Dow Jones average of 30 industrials rose 5.16 points to 2,111.31.</s>

<s docid="AP880712-0250" num="30" wdcount="10"> The dollar limbed to recent highs against several major currencies.</s>

<s docid="AP880712-0250" num="31" wdcount="4"> Gold prices fell sharply.</s>

<s docid="AP880712-0250" num="32" wdcount="13"> Bond prices rose modestly in quiet trading following a week of steady decline.</s>

<s docid="AP880712-0250" num="33" wdcount="13"> Grain and soybean futures plunged, while wheat and oat futures also declined .</s>
</TEXT>
</DOC>
