<DOC>
<DOCNO>

<s docid="AP880713-0175" num="1" wdcount="1"> AP880713-0175</s>
</DOCNO>
<FILEID>

<s docid="AP880713-0175" num="2" wdcount="2"> AP-NR-07-13-88 2035EDT</s>
</FILEID>
<FIRST>

<s docid="AP880713-0175" num="3" wdcount="5"> r a AM-Drought-States 07-13 1050</s>
</FIRST>
<SECOND>

<s docid="AP880713-0175" num="4" wdcount="1"> AM-Drought-States,1131</s>
</SECOND>
<HEAD>

<s docid="AP880713-0175" num="5" wdcount="5"> State-By-State Survey of Drought Developments</s>
</HEAD>
<BYLINE>

<s docid="AP880713-0175" num="6" wdcount="4"> By The Associated Press</s>
</BYLINE>
<TEXT>

<s docid="AP880713-0175" num="7" wdcount="9"> Here is a state-by-state summary of drought developments Wednesday:</s>
</TEXT>
<HEAD>

<s docid="AP880713-0175" num="8" wdcount="1"> ALABAMA</s>
</HEAD>
<TEXT>

<s docid="AP880713-0175" num="9" wdcount="24"> The Alabama National Guard is still hauling up to 25,000 gallons of water a day to 10 communities across the state despite recent rains.</s>

<s docid="AP880713-0175" num="10" wdcount="16"> At the height of the drought last month, the Guard was hauling water to 12 locations.</s>

<s docid="AP880713-0175" num="11" wdcount="22"> The Guard's water-hauling program has been in continuous operation since last July in west-central Alabama because of a low water table .</s>
</TEXT>
<HEAD>

<s docid="AP880713-0175" num="12" wdcount="1"> GEORGIA</s>
</HEAD>
<TEXT>

<s docid="AP880713-0175" num="13" wdcount="23"> In an effort to help Georgia farmers locate hay, the state Department of Agriculture announced it will start compiling a list of sources.</s>

<s docid="AP880713-0175" num="14" wdcount="14"> Commissioner Tommy Irvin urged those with a surplus for sale to contact the department.</s>

<s docid="AP880713-0175" num="15" wdcount="10"> He said information will be compiled and updated regularly .</s>
</TEXT>
<HEAD>

<s docid="AP880713-0175" num="16" wdcount="1"> ILLINOIS</s>
</HEAD>
<TEXT>

<s docid="AP880713-0175" num="17" wdcount="20"> State Treasurer Jerry Cosentino announced a program to provide drought-stricken farmers with access to commercial loans with below-market interest rates.</s>

<s docid="AP880713-0175" num="18" wdcount="30"> The treasurer's office will commit $50 million to banks at a lower-than-normal interest yield and in turn those banks will offer farmers loans with rates as low as 10 percent.</s>

<s docid="AP880713-0175" num="19" wdcount="20"> ``I know what the farmers first need is rain but that is out of our hands right now,'' Cosentino said.</s>

<s docid="AP880713-0175" num="20" wdcount="8"> ``The next best thing they can get ...</s>

<s docid="AP880713-0175" num="21" wdcount="11"> would be additional funds to carry them over until next year.''</s>
</TEXT>
<HEAD>

<s docid="AP880713-0175" num="22" wdcount="1"> INDIANA</s>
</HEAD>
<TEXT>

<s docid="AP880713-0175" num="23" wdcount="27"> A group of Indiana farmers sued a New Jersey insurance company, saying the company acted in bad faith when it reneged on $2.5 million in drought insurance.</s>

<s docid="AP880713-0175" num="24" wdcount="30"> The lawsuit seeks an ``undeterminable'' amount of damages from Pio-Gard Agency of Ohio Inc. and Federal Insurance Co., a subsidiary of the Chubb Group Insurance Cos. of Warren, N.J .</s>
</TEXT>
<HEAD>

<s docid="AP880713-0175" num="25" wdcount="1"> IOWA</s>
</HEAD>
<TEXT>

<s docid="AP880713-0175" num="26" wdcount="22"> Forecasters say Iowa's weather is returning to the hot, dry drought pattern which settled over the state for much of June .</s>
</TEXT>
<HEAD>

<s docid="AP880713-0175" num="27" wdcount="1"> KENTUCKY</s>
</HEAD>
<TEXT>

<s docid="AP880713-0175" num="28" wdcount="26"> The first emergency shipment of Oregon hay to help drought-stricken Kentucky farmers arrived, but logistical problems forced agriculture officials to delay its distribution until next week.</s>

<s docid="AP880713-0175" num="29" wdcount="23"> ``It's a nightmare trying to find a fair way to do this,'' said Roger Nesbitt, a spokesman for the Kentucky Department of Agriculture.</s>

<s docid="AP880713-0175" num="30" wdcount="22"> Nesbitt said Wednesday's 20-ton shipment, flown free from Portland, Ore., by United Parcel Service, will be sold to farmers on Monday .</s>
</TEXT>
<HEAD>

<s docid="AP880713-0175" num="31" wdcount="1"> MINNESOTA</s>
</HEAD>
<TEXT>

<s docid="AP880713-0175" num="32" wdcount="35"> Heavy rain fell on some of the driest areas of central and east-central Minnesota, but it was ``way, way below what we should have, as far as precipitation goes,'' a National Weather Service hydrologist said.</s>

<s docid="AP880713-0175" num="33" wdcount="3"> ``We need ...</s>

<s docid="AP880713-0175" num="34" wdcount="28"> a widespread distribution over a long period of time, say maybe 10 inches of rainfall to get us back to what we normally should be,'' Gary McDevitt said.</s>

<s docid="AP880713-0175" num="35" wdcount="25"> It was the heaviest rainfall for the east-central part of the state since April 26, when the area got about a half-inch of rain .</s>
</TEXT>
<HEAD>

<s docid="AP880713-0175" num="36" wdcount="1"> MISSISSIPPI</s>
</HEAD>
<TEXT>

<s docid="AP880713-0175" num="37" wdcount="13"> Weather experts say Mississippi could see above normal rainfall in the coming week.</s>

<s docid="AP880713-0175" num="38" wdcount="20"> Rainfall during the week ending Wednesday averaged 1 inch in some areas, with some extreme northern counties receiving greater amounts.</s>

<s docid="AP880713-0175" num="39" wdcount="21"> But the weather service said all Mississippi farm communities still had only 30 percent to 50 percent of normal moisture .</s>
</TEXT>
<HEAD>

<s docid="AP880713-0175" num="40" wdcount="1"> MISSOURI</s>
</HEAD>
<TEXT>

<s docid="AP880713-0175" num="41" wdcount="22"> Road builders in the Kansas City area say the effects of dry weather in the Midwest this year are not all bad.</s>

<s docid="AP880713-0175" num="42" wdcount="31"> Engineers say several highway projects in the area will be open to traffic at least a month earlier than expected because of fewer interruptions caused by rain and wet weather. __</s>
</TEXT>
<HEAD>

<s docid="AP880713-0175" num="43" wdcount="1"> MONTANA</s>
</HEAD>
<TEXT>

<s docid="AP880713-0175" num="44" wdcount="20"> As many as 20 fires, sparked by lightning from thunderstorms, have blackened about 1,500 acres in the Custer National Forest.</s>

<s docid="AP880713-0175" num="45" wdcount="11"> The fires are being fought by from 150 to 200 firefighters.</s>

<s docid="AP880713-0175" num="46" wdcount="21"> A lightning-caused fire in the Bob Marshall Wilderness Area of northwest Montana was being allowed to burn naturally, officials said .</s>
</TEXT>
<HEAD>

<s docid="AP880713-0175" num="47" wdcount="1"> NEBRASKA</s>
</HEAD>
<TEXT>

<s docid="AP880713-0175" num="48" wdcount="23"> State Agriculture Director Roy Frederick said Nebraska farmers probably will have better crops than are expected nationwide and may benefit from higher prices.</s>

<s docid="AP880713-0175" num="49" wdcount="34"> Nebraska's outlook for the corn crop is rosier than national predictions because 75 percent of the corn comes from irrigated acres and Nebraska has received more rain than some other states, he said .</s>
</TEXT>
<HEAD>

<s docid="AP880713-0175" num="50" wdcount="2"> NORTH DAKOTA</s>
</HEAD>
<TEXT>

<s docid="AP880713-0175" num="51" wdcount="20"> Gov. George Sinner has asked federal officials to declare all 53 North Dakota counties disaster areas because of the drought.</s>

<s docid="AP880713-0175" num="52" wdcount="20"> Sinner says the drought has wiped out small grain crops and is beginning to take a toll on row crops.</s>

<s docid="AP880713-0175" num="53" wdcount="31"> The State Agricultural Statistics Service said North Dakota farmers will abandon 31 percent of their spring wheat this year and harvest the smallest crop in 19 years because of the drought.</s>

<s docid="AP880713-0175" num="54" wdcount="10"> That compares to a normal abandonment of about 5 percent.</s>

<s docid="AP880713-0175" num="55" wdcount="13"> Abandonment has not been so high in the state since the 1930s .</s>
</TEXT>
<HEAD>

<s docid="AP880713-0175" num="56" wdcount="1"> OHIO</s>
</HEAD>
<TEXT>

<s docid="AP880713-0175" num="57" wdcount="1"> Lt.</s>

<s docid="AP880713-0175" num="58" wdcount="32"> Gov. Paul Leonard, who heads a state drought task force, said he would not advocate statewide mandatory water restrictions but said local governments should have the authority to impose restrictions where necessary.</s>

<s docid="AP880713-0175" num="59" wdcount="30"> In central Ohio, farmers awaited what will be the largest haylift of the season _ 50 truckloads of hay from the South scheduled to arrive Thursday night in Columbus .</s>
</TEXT>
<HEAD>

<s docid="AP880713-0175" num="60" wdcount="2"> SOUTH DAKOTA</s>
</HEAD>
<TEXT>

<s docid="AP880713-0175" num="61" wdcount="13"> Thunderstorms hit Brown County with heavy rain and hail that damaged drought-stricken crops.</s>

<s docid="AP880713-0175" num="62" wdcount="11"> Rain was heavy north and east of Aberdeen and spotty elsewhere.</s>

<s docid="AP880713-0175" num="63" wdcount="19"> Stanley and Thelma Dennert, who live three miles west of Houghton, reported 3.75 inches of rain within an hour.</s>

<s docid="AP880713-0175" num="64" wdcount="9"> ``It was hard with a little bit of hail.</s>

<s docid="AP880713-0175" num="65" wdcount="9"> It really came down in sheets,'' said Mrs. Dennert.</s>

<s docid="AP880713-0175" num="66" wdcount="16"> Authorities said no tornado sightings were confirmed, but about a dozen funnel clouds were reported .</s>
</TEXT>
<HEAD>

<s docid="AP880713-0175" num="67" wdcount="1"> TENNESSEE</s>
</HEAD>
<TEXT>

<s docid="AP880713-0175" num="68" wdcount="20"> The drought-plagued Mississippi River measured seventh-tenths of a foot higher than expected at Memphis because of rainfall throughout West Tennessee.</s>

<s docid="AP880713-0175" num="69" wdcount="33"> The Mississippi was still 21 feet lower than normal for this time of year, however, and the Coast Guard said the slight rise had no effect on commercial traffic on the river .</s>
</TEXT>
<HEAD>

<s docid="AP880713-0175" num="70" wdcount="1"> WISCONSIN</s>
</HEAD>
<TEXT>

<s docid="AP880713-0175" num="71" wdcount="14"> The drought has dried up summer jobs at the Stokley USA cannery in Merrill.</s>

<s docid="AP880713-0175" num="72" wdcount="33"> During most summers, the plant provides three months' employment for about 300 workers on three shifts, but this year there are only 225 seasonal employees on two shifts, said Vern Warren, plant manager.</s>

<s docid="AP880713-0175" num="73" wdcount="7"> ``It's been on and off so far.</s>

<s docid="AP880713-0175" num="74" wdcount="14"> The drought conditions have made it a little difficult for us,'' Warren said .</s>
</TEXT>
</DOC>
