<DOC>
<DOCNO>

<s docid="AP891116-0133" num="1" wdcount="1"> AP891116-0133</s>
</DOCNO>
<FILEID>

<s docid="AP891116-0133" num="2" wdcount="2"> AP-NR-11-16-89 2015EST</s>
</FILEID>
<FIRST>

<s docid="AP891116-0133" num="3" wdcount="5"> r a AM-Tornadoes-Survivors 11-16 0484</s>
</FIRST>
<SECOND>

<s docid="AP891116-0133" num="4" wdcount="1"> AM-Tornadoes-Survivors,0498</s>
</SECOND>
<HEAD>

<s docid="AP891116-0133" num="5" wdcount="6"> Young Survivor: `Everybody Wanted Their Mom'</s>
</HEAD>
<HEAD>

<s docid="AP891116-0133" num="6" wdcount="4"> With AM-Southern Tornadoes, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP891116-0133" num="7" wdcount="3"> By HOYT HARWELL</s>
</BYLINE>
<BYLINE>

<s docid="AP891116-0133" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP891116-0133" num="9" wdcount="3"> HUNTSVILLE, Ala. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP891116-0133" num="10" wdcount="16"> Employees at a jewelry store huddled in the vault while the shop came down around them.</s>

<s docid="AP891116-0133" num="11" wdcount="17"> A man in an apartment building stayed in his bathtub while the bathroom walls crumbled and fell.</s>

<s docid="AP891116-0133" num="12" wdcount="42"> Those were among the stories people in this northern Alabama city swapped on Thursday as they assessed the damage from a tornado that whipped through the heart of the city in a flash, leaving at least 17 people dead and hundreds homeless.</s>

<s docid="AP891116-0133" num="13" wdcount="23"> ``Everybody was screaming and windows started breaking and the roof started to fall,'' recalled Vincent Davis, a fourth-grader at Jones Valley Elementary School.</s>

<s docid="AP891116-0133" num="14" wdcount="6"> ``The whole top story flew off.</s>

<s docid="AP891116-0133" num="15" wdcount="4"> Everybody wanted their mom''.</s>

<s docid="AP891116-0133" num="16" wdcount="15"> Vincent was staying late at school Wednesday when the twister hit shortly after 4:30 p.m.</s>

<s docid="AP891116-0133" num="17" wdcount="22"> He was taken to a hospital with minor injuries; five of about 30 children in a kindergarten class also were reported hurt.</s>

<s docid="AP891116-0133" num="18" wdcount="19"> Lynn Culpepper was in his bathtub at the Waterford Square apartments, where at least a dozen buildings were destroyed.</s>

<s docid="AP891116-0133" num="19" wdcount="17"> ``The next thing I knew, glass was breaking and I was rolling on the ground,'' he recalled.</s>

<s docid="AP891116-0133" num="20" wdcount="16"> ``It was just black, and then there was this tumbling feeling with debris flying around everywhere.</s>

<s docid="AP891116-0133" num="21" wdcount="21"> When I opened my eyes and looked around, there was just a pile of rubble where the apartments used to be''.</s>

<s docid="AP891116-0133" num="22" wdcount="9"> Culpepper's head and arms were cut in the collapse.</s>

<s docid="AP891116-0133" num="23" wdcount="28"> Manager Bob Husman of a Golbro jewelry store ordered employees into the vault shortly before the roof and walls crashed down on him, 20 feet from the vault.</s>

<s docid="AP891116-0133" num="24" wdcount="12"> ``In the jewelry business, the vault is the safest place,'' he said.</s>

<s docid="AP891116-0133" num="25" wdcount="11"> ``I had structural steel on me but managed to crawl out.</s>

<s docid="AP891116-0133" num="26" wdcount="7"> It was the worst kind of nightmare''.</s>

<s docid="AP891116-0133" num="27" wdcount="17"> The employees in the vault were dug out an hour after the collapse, shaken but not hurt.</s>

<s docid="AP891116-0133" num="28" wdcount="10"> Rick Snider was in the bakery aisle of a supermarket.</s>

<s docid="AP891116-0133" num="29" wdcount="9"> ``Part of the roof was coming off,'' he said.</s>

<s docid="AP891116-0133" num="30" wdcount="9"> ``Some ladies were crying, but it was quite calm.</s>

<s docid="AP891116-0133" num="31" wdcount="9"> A checkout lady was hit with a cash register.</s>

<s docid="AP891116-0133" num="32" wdcount="14"> People were shouting, `Can I help'? and they were leading people to the light.</s>

<s docid="AP891116-0133" num="33" wdcount="7"> There was no screaming or hysterical stuff.</s>

<s docid="AP891116-0133" num="34" wdcount="9"> I came out and I couldn't believe the damage''.</s>

<s docid="AP891116-0133" num="35" wdcount="12"> For Ed Rolan, a medic, the devastation brought back memories of Vietnam.</s>

<s docid="AP891116-0133" num="36" wdcount="19"> Rolan, who was driving home when the tornado hit, went right to work helping the stricken motorists around him.</s>

<s docid="AP891116-0133" num="37" wdcount="15"> ``One lady was thrown from her car and I thought she was dead,'' he said.</s>

<s docid="AP891116-0133" num="38" wdcount="12"> ``I came back by her later and saw she had changed positions.</s>

<s docid="AP891116-0133" num="39" wdcount="10"> It took 30 minutes to get a stretcher to her''.</s>

<s docid="AP891116-0133" num="40" wdcount="13"> The enormity of the death and destruction ``sank in very quickly,'' Rolan said.</s>

<s docid="AP891116-0133" num="41" wdcount="11"> ``This is the closest to death I have been since Vietnam.''</s>
</TEXT>
</DOC>
