<DOC>
<DOCNO>

<s docid="AP891116-0115" num="1" wdcount="1"> AP891116-0115</s>
</DOCNO>
<FILEID>

<s docid="AP891116-0115" num="2" wdcount="2"> AP-NR-11-16-89 1340EST</s>
</FILEID>
<FIRST>

<s docid="AP891116-0115" num="3" wdcount="7"> u a PM-SouthernTornadoes 4thLd-Writethru a0583 11-16 1208</s>
</FIRST>
<SECOND>

<s docid="AP891116-0115" num="4" wdcount="5"> PM-Southern Tornadoes, 4th Ld-Writethru, a0583,1242</s>
</SECOND>
<HEAD>

<s docid="AP891116-0115" num="5" wdcount="7"> Twister Rips Through Alabama City, Killing 17</s>
</HEAD>
<HEAD>

<s docid="AP891116-0115" num="6" wdcount="5"> Eds: SUBS 5th graf, `Gov.</s>

<s docid="AP891116-0115" num="7" wdcount="13"> Guy'... with 3 grafs to UPDATE with 25-mile path, tornado watches in Northeast.</s>

<s docid="AP891116-0115" num="8" wdcount="5"> Picks up 6th graf, `Elsewhere:'</s>
</HEAD>
<HEAD>

<s docid="AP891116-0115" num="9" wdcount="4"> LaserPhotos WX9, HUN3; LaserGraphic</s>
</HEAD>
<BYLINE>

<s docid="AP891116-0115" num="10" wdcount="3"> By HOYT HARWELL</s>
</BYLINE>
<BYLINE>

<s docid="AP891116-0115" num="11" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP891116-0115" num="12" wdcount="3"> HUNTSVILLE, Ala. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP891116-0115" num="13" wdcount="31"> Rescuers crawled through collapsed homes and shops today looking for more victims of a tornado that carved a 3-mile stretch of destruction, killing 17 people, injuring 463 and leaving 1,000 homeless.</s>

<s docid="AP891116-0115" num="14" wdcount="29"> ``It's like taking six to 10 city blocks and putting them in a blender and putting it on liquefy,'' said rescue worker Bob Caraway, whose specialty is cave rescues.</s>

<s docid="AP891116-0115" num="15" wdcount="19"> He was among those called out to help dig through rubble for survivors or the bodies of the dead.</s>

<s docid="AP891116-0115" num="16" wdcount="26"> The tornado was one of a series that touched down Wednesday in an arc spanning at least seven states from the Deep South to the Midwest.</s>

<s docid="AP891116-0115" num="17" wdcount="12"> The other tornadoes caused at least 19 injuries and far-flung property damage.</s>

<s docid="AP891116-0115" num="18" wdcount="28"> In Huntsville, teams with cranes and floodlights searched for the injured or dead, hampered by wind-whipped rain and temperatures that plummeted overnight from 73 degrees into the 30s.</s>

<s docid="AP891116-0115" num="19" wdcount="16"> Gov. Guy Hunt sent 50 National Guardsmen to help and said he would view damage Friday.</s>

<s docid="AP891116-0115" num="20" wdcount="21"> His spokesman, Terry Abbott, said aerial surveys indicate the twister hopped along a 25-mile path, much of it straight through Huntsville.</s>

<s docid="AP891116-0115" num="21" wdcount="9"> By this afternoon, severe thunderstorms were crossing the Northeast.</s>

<s docid="AP891116-0115" num="22" wdcount="33"> The National Weather Service put out a tornado watch for parts of Maryland, Delaware, Pennsylvania, New Jersey, New York, all of Connecticut and Rhode Island, and parts of Massachusetts, Vermont and New Hampshire.</s>

<s docid="AP891116-0115" num="23" wdcount="27"> In Pennsylvania, the weather service said it received unconfirmed reports of a tornado that turned over a car and knocked down trees and power lines near Gettysburg.</s>

<s docid="AP891116-0115" num="24" wdcount="35"> Elsewhere: _In Georgia, 19 people were injured, four critically, and at least 200 people were evacuated after a tornado strus.C., and a tornado toppled trees, downed power lines and damaged 20 houses near Greenwood, S.C.</s>

<s docid="AP891116-0115" num="25" wdcount="7"> No injuries were reported in either state.</s>

<s docid="AP891116-0115" num="26" wdcount="10"> _Tornadoes caused minor property damage in Mississippi, Kentucky and Indiana.</s>

<s docid="AP891116-0115" num="27" wdcount="26"> _In West Virginia, high winds believed to be tornadoes swept Jefferson County early today, overturning trailers, blowing roofs off homes and downing power lines, authorities said.</s>

<s docid="AP891116-0115" num="28" wdcount="6"> Four people were injured, two seriously.</s>

<s docid="AP891116-0115" num="29" wdcount="22"> _Heavy thunderstorms destroyed at least a dozen homes in Alorton, Ill., killing one person and injuring 20 others, five seriously, authorities said.</s>

<s docid="AP891116-0115" num="30" wdcount="22"> The tornado struck Huntsville with virtually no warning Wednesday afternoon as the city's streets grew busy with the approach of rush hour.</s>

<s docid="AP891116-0115" num="31" wdcount="24"> In a matter of seconds, cars were hurled through the air and crushed, and apartments and stores looked as if they had been bombed.</s>

<s docid="AP891116-0115" num="32" wdcount="13"> ``It was fast,'' said Lucy Lee Rusk, whose apartment was battered by debris.</s>

<s docid="AP891116-0115" num="33" wdcount="11"> ``It was like one big pop and that's when everything went''.</s>

<s docid="AP891116-0115" num="34" wdcount="36"> The National Weather Service had issued a tornado watch earlier in the day, but did not issue a more urgent tornado warning until 4:39 p.m. CST, when the tornado was spotted at the municipal golf course.</s>

<s docid="AP891116-0115" num="35" wdcount="9"> By then, it was already tearing up the city.</s>

<s docid="AP891116-0115" num="36" wdcount="18"> A watch means a tornado is considered possible, while a warning means a tornado is believed to exist.</s>

<s docid="AP891116-0115" num="37" wdcount="3"> Huntsville Police Maj.</s>

<s docid="AP891116-0115" num="38" wdcount="30"> Robert Moder said this morning that 463 people were injured by the twister, which plowed through a school and rural areas as well as a shopping mall and adjacent apartments.</s>

<s docid="AP891116-0115" num="39" wdcount="33"> Police Chief Richard Ottman initially put the number of dead at 19, but his clerk, Kitty Whitworth, later said the death toll was lowered to 17 after police confirmed the count of bodies.</s>

<s docid="AP891116-0115" num="40" wdcount="10"> She said police had no firm reports of people missing.</s>

<s docid="AP891116-0115" num="41" wdcount="24"> No children in the school were killed, but about 30 youngsters were in a kindergarten class at the building, and five were reported injured.</s>

<s docid="AP891116-0115" num="42" wdcount="10"> Most of the dead were in apartments, stores or cars.</s>

<s docid="AP891116-0115" num="43" wdcount="21"> Mayor Steve Hettinger estimated the number of homeless at 1,000 and said officials were preparing a request for federal disaster assistance.</s>

<s docid="AP891116-0115" num="44" wdcount="31"> A worker at a building owned by the Madison County Jaycees said 42 people were staying there early today, and described the mood of the survivors as ``shock, mostly, and disbelief''.</s>

<s docid="AP891116-0115" num="45" wdcount="28"> ``They're thankful to be alive and they're thankful their families are alive,'' he said, adding that the shelter had received calls from around the country from worried relatives.</s>

<s docid="AP891116-0115" num="46" wdcount="23"> The tornado was Alabama's deadliest since a 1975 twister killed 22 people in Birmingham, said Danny Cooper, state emergency management director in Montgomery.</s>

<s docid="AP891116-0115" num="47" wdcount="20"> Along a highway near a destroyed apartment complex, cars were flipped and smashed into telephone poles and crushed by trees.</s>

<s docid="AP891116-0115" num="48" wdcount="17"> The roadway was strewn with used bandages and medical gloves left by emergency workers treating the injured.</s>

<s docid="AP891116-0115" num="49" wdcount="16"> Humana Hospital administrator David Miller said doctors had difficulty reaching the hospital because of blocked roads.</s>

<s docid="AP891116-0115" num="50" wdcount="11"> Those in the tornado's path spoke with awe of its fury.</s>

<s docid="AP891116-0115" num="51" wdcount="37"> ``It came in with a huge roar, an enormous amount of water, and it just started shaking and tearing at everything it could get hold of,'' said real estate broker Ike Carroll, who was in his car.</s>

<s docid="AP891116-0115" num="52" wdcount="17"> Heavy overhead power lines ``started snapping just like a circus performer would snap his whip,'' Carroll said.</s>

<s docid="AP891116-0115" num="53" wdcount="18"> ``All of these heavy arcing, flashing lines that were just popping and snapping over the top of us.</s>

<s docid="AP891116-0115" num="54" wdcount="15"> ... It was as if you were looking into an arc-welder, they were so bright''.</s>

<s docid="AP891116-0115" num="55" wdcount="33"> Kenneth Lenhard had undergone an operation at the Crestwood Hospital on Wednesday and returned to his room about an hour before a window in the next room blew out as the tornado passed.</s>

<s docid="AP891116-0115" num="56" wdcount="13"> ``There wasn't anything I could do, so I covered my head,'' Lenhard said.</s>

<s docid="AP891116-0115" num="57" wdcount="9"> ``I thought, `What the heck, I'm already half dead'.</s>

<s docid="AP891116-0115" num="58" wdcount="19"> '' The downtown Jones Valley Elementary School, the Waterford Square and adjacent Queensbury apartment complexes were reduced to rubble.</s>

<s docid="AP891116-0115" num="59" wdcount="15"> Kindergarteners were the only pupils left at the school by the time the twister hit.</s>

<s docid="AP891116-0115" num="60" wdcount="29"> The city is home to NASA's Marshall Space Flight Center and the Army's Redstone Arsenal, but no serious damage was reported from the space agency or weapons testing center.</s>

<s docid="AP891116-0115" num="61" wdcount="20"> At least two other tornadoes were reported in Alabama, injuring at least three people in addition to the Huntsville total.</s>

<s docid="AP891116-0115" num="62" wdcount="25"> Near Palmetto, Ga., resident Jeff Bryant said his home at the Sweetbriar Mobile Home Park near Interstate 85 began to vibrate when the twister approached.</s>

<s docid="AP891116-0115" num="63" wdcount="12"> ``Then we heard a large, loud, swirling and humming noise,'' he recalled.</s>

<s docid="AP891116-0115" num="64" wdcount="11"> ``It didn't sound like a train like everybody says it does.</s>

<s docid="AP891116-0115" num="65" wdcount="6"> I lived near a train track.</s>

<s docid="AP891116-0115" num="66" wdcount="7"> It did not sound like a train.</s>

<s docid="AP891116-0115" num="67" wdcount="11"> It sounded more like a jet aircraft at very close range''.</s>

<s docid="AP891116-0115" num="68" wdcount="11"> Thomas Farr was driving on Interstate 85 when the tornado hit.</s>

<s docid="AP891116-0115" num="69" wdcount="15"> ``It was picking up cars and tossing them like toys off the interstate,'' he said.</s>

<s docid="AP891116-0115" num="70" wdcount="6"> ``I saw one 18-wheeler flip over.</s>

<s docid="AP891116-0115" num="71" wdcount="29"> The car in front of us was flipped about 100 yards, and the guy was thrown out of his passenger window and landed 50 feet from his car .</s>
</TEXT>
</DOC>
