<DOC>
<DOCNO>

<s docid="AP891115-0199" num="1" wdcount="1"> AP891115-0199</s>
</DOCNO>
<FILEID>

<s docid="AP891115-0199" num="2" wdcount="2"> AP-NR-11-15-89 2054EST</s>
</FILEID>
<FIRST>

<s docid="AP891115-0199" num="3" wdcount="5"> u a AM-WeatherpageWeather 1stLd-Writethru a0739</s>
</FIRST>
<SECOND>

<s docid="AP891115-0199" num="4" wdcount="5"> AM-Weatherpage Weather, 1st Ld-Writethru, a0739,0667</s>
</SECOND>
<HEAD>

<s docid="AP891115-0199" num="5" wdcount="7"> Severe Weather Erupts Over Mississippi Valley, Southeast</s>
</HEAD>
<HEAD>

<s docid="AP891115-0199" num="6" wdcount="20"> Eds: LEADS with 4 grafs to UPDATE with lethal tornado in Alabama; picks up 3rd graf pvs, `People in ...</s>

<s docid="AP891115-0199" num="7" wdcount="10"> INSERTS 2 grafs after 8th graf pvs, `Thunderstorms crossing ...</s>

<s docid="AP891115-0199" num="8" wdcount="9"> ,' to UPDATE with storms hitting Georgia, Ohio .</s>
</HEAD>
<BYLINE>

<s docid="AP891115-0199" num="9" wdcount="4"> By The Associated Press</s>
</BYLINE>
<TEXT>

<s docid="AP891115-0199" num="10" wdcount="29"> Thunderstorms wreaked havoc across the middle Mississippi Valley and the Southeast on Wednesday with lethal tornadoes, wind up to 100 mph and hail up to the size of baseballs.</s>

<s docid="AP891115-0199" num="11" wdcount="9"> At least four tornadoes pounded the Huntsville, Ala., area.</s>

<s docid="AP891115-0199" num="12" wdcount="25"> One twister smashed into a residential district, a shopping area and a school, killing at least two people and causing dozens of injuries, police said.</s>

<s docid="AP891115-0199" num="13" wdcount="25"> Southern Illinois was also hard hit by the storms, with one woman killed by a falling tree, about 20 people injured and power lines downed.</s>

<s docid="AP891115-0199" num="14" wdcount="20"> Elsewhere, snow fell from the northern Rockies to the upper Great Lakes, while unseasonably mild weather continued in the East.</s>

<s docid="AP891115-0199" num="15" wdcount="40"> People in Alorton, Ill., a village of 2,700 about five miles southeast of East St. Louis, were injured when trees fell on their houses or mobile homes, said Bill Gamblin of the St. Clair County Emergency Services and Disaster Agency.</s>

<s docid="AP891115-0199" num="16" wdcount="34"> At Parks College in Cahokia, Ill., eight miles south of East St. Louis, aircraft hangers were twisted and flattened and small aircraft tossed around the airport by high winds, the National Weather Service said.</s>

<s docid="AP891115-0199" num="17" wdcount="16"> Storms in the area generated wind estimated at 80 to 100 mph, the weather service said.</s>

<s docid="AP891115-0199" num="18" wdcount="18"> The thunderstorms developed along and ahead of a strong cold front and swept eastward from Missouri and Arkansas.</s>

<s docid="AP891115-0199" num="19" wdcount="33"> Thunderstorms crossing northeastern Arkansas whipped up high wind which blew away metal roofing being installed on a high school gymnasium at Lepanto and dumped hail up to 2 inches in diameter at Leachville.</s>

<s docid="AP891115-0199" num="20" wdcount="19"> Heavy thunderstorms, possibly a tornado, struck the north Georgia town of Palmetto late Wednesday, causing extensive damage, authorities said.</s>

<s docid="AP891115-0199" num="21" wdcount="25"> In central and southwest Ohio, thunderstorms packing winds up to 66 mph destroyed barns and a trailer home and tore the roofs off several buildings.</s>

<s docid="AP891115-0199" num="22" wdcount="7"> Some injuries but no fatalities were reported.</s>

<s docid="AP891115-0199" num="23" wdcount="32"> An afternoon thunderstorm in east-central Alabama formed a tornado which damaged at least one home, and the Clay County Sheriff's office said an unknown number of people were injured in one house.</s>

<s docid="AP891115-0199" num="24" wdcount="26"> Thunderstorms sweeping across Tennessee spun off a tornado in southeastern Madison Country, and dropped hail as big as baseballs north of Jackson, the weather service said.</s>

<s docid="AP891115-0199" num="25" wdcount="15"> Hail stones as big as tennis balls fell near Huntingburg, Ind., the weather service said.</s>

<s docid="AP891115-0199" num="26" wdcount="18"> The heaviest rainfall during the six hours up to 1 p.m. EST was 1.22 inches at Peru, Ind.</s>

<s docid="AP891115-0199" num="27" wdcount="21"> Wind up to 65 mph damaged roofs, power lines and trees in parts of Kentucky and Louisiana, the weather service said.</s>

<s docid="AP891115-0199" num="28" wdcount="23"> Severe thunderstorms also developed over Alabama and South Carolina during the afternoon, and the weather service reported a tornado north of Greenwood, S.C.</s>

<s docid="AP891115-0199" num="29" wdcount="16"> Other showers and thunderstorms, with locally heavy rain, were widely scattered along the northern Atlantic Coast.</s>

<s docid="AP891115-0199" num="30" wdcount="18"> Light snow associated with an arctic cold front extended from eastern Wyoming and northeastern Colorado into western Minnesota.</s>

<s docid="AP891115-0199" num="31" wdcount="11"> Snow also fell across parts of northern Wisconsin and Upper Michigan.</s>

<s docid="AP891115-0199" num="32" wdcount="21"> As much as 1 to 2 feet of snow was possible by Thursday morning along the Lake Superior shore of Wisconsin.</s>

<s docid="AP891115-0199" num="33" wdcount="28"> Strong northwesterly wind ushering the cold air into the north-central states gusted above 40 mph during the afternoon, creating wind chill readings colder than 25 degrees below zero.</s>

<s docid="AP891115-0199" num="34" wdcount="21"> Snow, high wind and rapidly falling temperatures associated with the cold front briefly produced near-blizzard conditions in Nebraska late Wednesday morning.</s>

<s docid="AP891115-0199" num="35" wdcount="27"> Unseasonably warm weather continued in the East with afternoon readings in the 60s in New England, and in the 80s over Florida, southern Texas and southern Louisiana.</s>

<s docid="AP891115-0199" num="36" wdcount="17"> Wednesday morning's low for the Lower 48 states was 9 degrees above zero at Ely, Nev .</s>
</TEXT>
</DOC>
