<DOC>
<DOCNO>

<s docid="AP891118-0136" num="1" wdcount="1"> AP891118-0136</s>
</DOCNO>
<FILEID>

<s docid="AP891118-0136" num="2" wdcount="2"> AP-NR-11-18-89 2045EST</s>
</FILEID>
<FIRST>

<s docid="AP891118-0136" num="3" wdcount="7"> r a AM-AlabamaTornado 1stLd-Writethru a0610 11-18 0790</s>
</FIRST>
<SECOND>

<s docid="AP891118-0136" num="4" wdcount="5"> AM-Alabama Tornado, 1st Ld-Writethru, a0610,0645</s>
</SECOND>
<HEAD>

<s docid="AP891118-0136" num="5" wdcount="9"> Feds, State Promise Huntsville: `Whatever's Needed Will be Done'</s>
</HEAD>
<HEAD>

<s docid="AP891118-0136" num="6" wdcount="20"> Eds: LEADS with 7 grafs to UPDATE with Marilyn Quayle visit to Huntsville; picks up 4th graf, ``President Bush ''...</s>

<s docid="AP891118-0136" num="7" wdcount="6"> SUBS 11th graf, ``The state ...</s>

<s docid="AP891118-0136" num="8" wdcount="9"> ,'' to DELETE now-redundant first reference to Hunt .</s>
</HEAD>
<BYLINE>

<s docid="AP891118-0136" num="9" wdcount="3"> By PAUL NEWBERRY</s>
</BYLINE>
<BYLINE>

<s docid="AP891118-0136" num="10" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP891118-0136" num="11" wdcount="3"> HUNTSVILLE, Ala. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP891118-0136" num="12" wdcount="22"> Marilyn Quayle, wife of Vice President Dan Quayle, praised the heroism of this tornado-ravaged northern Alabama city's residents during a visit Saturday.</s>

<s docid="AP891118-0136" num="13" wdcount="26"> Mrs. Quayle personally thanked workers cleaning up the debris left by Wednesday's twister and visited some of the injured at Crestwood Hospital during her 2-hour tour.</s>

<s docid="AP891118-0136" num="14" wdcount="13"> The tornado left 18 people dead, hundreds injured and up to 1,000 homeless.</s>

<s docid="AP891118-0136" num="15" wdcount="14"> The youngest victim, a 2-year-old girl, died Friday after being taken off life-support systems.</s>

<s docid="AP891118-0136" num="16" wdcount="11"> ``The community is filled with heroes _ people who without ...</s>

<s docid="AP891118-0136" num="17" wdcount="26"> regard to their own personal danger helped other citizens so that they could survive,'' said Mrs. Quayle, who was accompanied by Gov. Guy Hunt and U.S.</s>

<s docid="AP891118-0136" num="18" wdcount="6"> Sens. Howell Heflin and Richard Shelby.</s>

<s docid="AP891118-0136" num="19" wdcount="31"> Mrs. Quayle, who made similar visits to San Francisco after the Oct. 17 earthquake and Charleston, S.C., after Hurricane Hugo, also praised corporations that have made donations to help Huntsville recover.</s>

<s docid="AP891118-0136" num="20" wdcount="27"> Federal and state officials have promised to do whatever is necessary to help Huntsville, even if disaster relief funds are squeezed by Hurricane Hugo and the quake.</s>

<s docid="AP891118-0136" num="21" wdcount="19"> ``We're here to get the job done,'' Grant Peterson, associate director of the Federal Emergency Management Agency, said Friday.</s>

<s docid="AP891118-0136" num="22" wdcount="5"> ``Whatever's needed will be done''.</s>

<s docid="AP891118-0136" num="23" wdcount="25"> President Bush declared Huntsville a disaster area, but FEMA may have to do some financial juggling to deal with this year's rash of natural disasters.</s>

<s docid="AP891118-0136" num="24" wdcount="11"> Parts of eight states have been declared eligible for federal relief.</s>

<s docid="AP891118-0136" num="25" wdcount="12"> ``Any one disaster like Hugo or the earthquake in California exceeds ...</s>

<s docid="AP891118-0136" num="26" wdcount="10"> what we have in a normal year alone,'' Peterson said.</s>

<s docid="AP891118-0136" num="27" wdcount="35"> Congress provided $1.1 billion in supplemental funds to FEMA after Hugo devastated the Caribbean and the East Coast in September, and $1.2 billion following the earthquake that ravaged parts of northern California on Oct. 17.</s>

<s docid="AP891118-0136" num="28" wdcount="11"> So far, about $1.3 billion has been allocated to disaster victims.</s>

<s docid="AP891118-0136" num="29" wdcount="12"> Peterson said he's not yet concerned about FEMA meeting its financial obligations.</s>

<s docid="AP891118-0136" num="30" wdcount="18"> ``I would say that to ask for any more money at this point would be premature,'' he said.</s>

<s docid="AP891118-0136" num="31" wdcount="20"> Peterson and his aides urged patience during the arduous task of processing thousands of relief requests from the Huntsville area.</s>

<s docid="AP891118-0136" num="32" wdcount="19"> ``If everything works well, in seven to 10 days we should get the first checks out,'' Peterson said Friday.</s>

<s docid="AP891118-0136" num="33" wdcount="13"> ``I'll make sure that we expedite these requests to meet the people's needs''.</s>

<s docid="AP891118-0136" num="34" wdcount="31"> The state will have to ante up 25 percent of the cost of providing clothing and temporary housing for tornado victims, with the federal government pitching in the other 75 percent.</s>

<s docid="AP891118-0136" num="35" wdcount="16"> Gov. Hunt said he expected the Alabama Legislature to come up with whatever money is needed.</s>

<s docid="AP891118-0136" num="36" wdcount="13"> ``The state doesn't budget for disasters,'' said Danny Cooper, Alabama's emergency management director.</s>

<s docid="AP891118-0136" num="37" wdcount="8"> ``We take care of them at the time''.</s>

<s docid="AP891118-0136" num="38" wdcount="13"> Hunt stressed that government agencies won't be able to shoulder the entire load.</s>

<s docid="AP891118-0136" num="39" wdcount="34"> He requested donations to agencies such as the American Red Cross, which set up a shelter for the homeless as rescue workers dug through the rubble in those desperate hours after the tornado struck.</s>

<s docid="AP891118-0136" num="40" wdcount="29"> The tornado hit Huntsville with devastating force _ winds were estimated at 250 mph _ and virtually no warning about 4:30 p.m. Wednesday, leaving a 10-mile-long path of destruction.</s>

<s docid="AP891118-0136" num="41" wdcount="10"> A shopping center and clusters of apartment buildings were leveled.</s>

<s docid="AP891118-0136" num="42" wdcount="13"> Cars were piled atop each other like the remnants of a demolition derby.</s>

<s docid="AP891118-0136" num="43" wdcount="11"> Cooper said 119 homes were destroyed and 125 had lesser damage.</s>

<s docid="AP891118-0136" num="44" wdcount="17"> Three churches, two schools, 35 businesses and 10 public buildings were either destroyed or suffered heavy damage.</s>

<s docid="AP891118-0136" num="45" wdcount="17"> Neighbors pitched in to help Debra McKay and her family pick through the rubble of their home.</s>

<s docid="AP891118-0136" num="46" wdcount="28"> The only things standing were the walls around two bathrooms and an adjacent hallway _ the area where Ms. McKay and her three children rode out the storm.</s>

<s docid="AP891118-0136" num="47" wdcount="8"> ``I know the Lord spared us,'' she said.</s>

<s docid="AP891118-0136" num="48" wdcount="8"> ``I woke up a different person this morning''.</s>

<s docid="AP891118-0136" num="49" wdcount="22"> Officials said several truckloads of food have rolled into Huntsville but the city is running out of places to store the goods.</s>

<s docid="AP891118-0136" num="50" wdcount="7"> ``There's a sense of thankfulness,'' Hunt said.</s>

<s docid="AP891118-0136" num="51" wdcount="9"> ``It's heartwarming to see how people have come together''.</s>

<s docid="AP891118-0136" num="52" wdcount="19"> Huntsville is home to NASA's Marshall Space Flight Center, the Army's Redstone Arsenal and a number of high-tech industries.</s>

<s docid="AP891118-0136" num="53" wdcount="15"> Mayor Steve Hettinger said the city would be able to withstand the tornado's financial impact.</s>

<s docid="AP891118-0136" num="54" wdcount="10"> ``Huntsville has a strong economy, a diverse economy,'' he said.</s>

<s docid="AP891118-0136" num="55" wdcount="7"> ``That's not the source of our concern.''</s>
</TEXT>
</DOC>
