<DOC>
<DOCNO>

<s docid="AP891116-0184" num="1" wdcount="1"> AP891116-0184</s>
</DOCNO>
<FILEID>

<s docid="AP891116-0184" num="2" wdcount="2"> AP-NR-11-16-89 1930EST</s>
</FILEID>
<FIRST>

<s docid="AP891116-0184" num="3" wdcount="5"> u a AM-WeatherpageWeather 11-16 0565</s>
</FIRST>
<SECOND>

<s docid="AP891116-0184" num="4" wdcount="2"> AM-Weatherpage Weather,0581</s>
</SECOND>
<HEAD>

<s docid="AP891116-0184" num="5" wdcount="10"> Powerful Storm Pushes North, Brings Floods and Destruction to Northeast</s>
</HEAD>
<BYLINE>

<s docid="AP891116-0184" num="6" wdcount="4"> By The Associated Press</s>
</BYLINE>
<TEXT>

<s docid="AP891116-0184" num="7" wdcount="21"> A powerful storm system brought strong winds and heavy thunderstorms to the Northeast on Thursday, causing flooding and widespread property damage.</s>

<s docid="AP891116-0184" num="8" wdcount="14"> Seven children died when a wall collapsed in a school cafeteria near Newburgh, N.Y.</s>

<s docid="AP891116-0184" num="9" wdcount="21"> Tornadoes were reported in New Jersey, Delaware, Virginia and New York, although the National Weather Service was unable to confirm them.</s>

<s docid="AP891116-0184" num="10" wdcount="25"> The same storm system caused tornadoes in seven states in the South and Midwest on Wednesday, and was blamed for 17 deaths in Huntsville, Ala.</s>

<s docid="AP891116-0184" num="11" wdcount="16"> The storm was particularly violent because it occurred along a line of extreme variations in temperature.</s>

<s docid="AP891116-0184" num="12" wdcount="16"> High temperature records fell in advance of the storm and sharply colder weather lurked behind it.</s>

<s docid="AP891116-0184" num="13" wdcount="19"> Record highs were recorded in Binghamton, N.Y., where it was 61 degrees, Bridgeport, Conn., (66), and Burlington, Vt., (69).</s>

<s docid="AP891116-0184" num="14" wdcount="11"> A record was also set in Miami, where it was 89.</s>

<s docid="AP891116-0184" num="15" wdcount="11"> Thunderstorms continued across the Ohio Valley overnight and during the morning.</s>

<s docid="AP891116-0184" num="16" wdcount="25"> Storms that might have been tornadoes damaged a residence and a store near Richmond, Va., and uprooted about 600 feet of trees near Wilmington, Del.</s>

<s docid="AP891116-0184" num="17" wdcount="18"> Other storms that might have been tornados were reported near Peekskill, N.Y., and Piscataway, N.J., during the afternoon.</s>

<s docid="AP891116-0184" num="18" wdcount="22"> Strong thunderstorms caused a concrete-and-glass wall to blow in on a cafeteria during lunchtime at the East Coldenham Elementary School near Newburgh.</s>

<s docid="AP891116-0184" num="19" wdcount="7"> Seven children were killed and 18 injured.</s>

<s docid="AP891116-0184" num="20" wdcount="25"> There were reports of damage from strong thunderstorms and gusty winds in eastern Virginia, Maryland, Delaware, New Jersey, eastern Pennsylvania and eastern New York state.</s>

<s docid="AP891116-0184" num="21" wdcount="37"> Winds gusted to 65 mph in Baltimore, 76 mph in Lancaster, Pa., and 100 mph at Great Valley, Pa. A tornado watch was posted for northeast New York state, much of Vermont and much of New Hampshire.</s>

<s docid="AP891116-0184" num="22" wdcount="8"> Thunderstorms also produced locally heavy rain and flooding.</s>

<s docid="AP891116-0184" num="23" wdcount="11"> A flood warning was posted over portions of upstate New York.</s>

<s docid="AP891116-0184" num="24" wdcount="20"> Nearly two inches of rain fell east of Utica, N.Y., at the Little Falls Reservoir, which overflowed and caused flooding.</s>

<s docid="AP891116-0184" num="25" wdcount="13"> Water was eroding the Lyons Pond Dam near Dolgeville, N.Y., causing flooding there.</s>

<s docid="AP891116-0184" num="26" wdcount="8"> Snow was falling west of the cold front.</s>

<s docid="AP891116-0184" num="27" wdcount="15"> A winter storm warning was posted for northwest Wisconsin, in the snowbelt near Lake Superior.</s>

<s docid="AP891116-0184" num="28" wdcount="17"> Winter storm warnings were posted for much of lower Michigan, northwestern upper Michigan and north central Indiana.</s>

<s docid="AP891116-0184" num="29" wdcount="9"> Winds gusted to 63 mph at Whitefish Point, Mi.</s>

<s docid="AP891116-0184" num="30" wdcount="10"> , and near blizzard conditions extended over eastern upper Michigan.</s>

<s docid="AP891116-0184" num="31" wdcount="18"> Overnight snowfall across upper Michigan included 12 inches at Van Riper State Park and 10 inches near Neguanee.</s>

<s docid="AP891116-0184" num="32" wdcount="27"> Heavier snowfall during the 6 hours ending at 1 p.m. EST included 4 inches at Houghton Lake, Mich., 3 inches at Marquette, Pellston, Saginaw and Sault Ste.</s>

<s docid="AP891116-0184" num="33" wdcount="11"> Marie, all in Michigan, and 2 inches at South Bend, Ind.</s>

<s docid="AP891116-0184" num="34" wdcount="14"> Heavy snow warnings were posted for the northwest and northern mountain portions of Pennsylvania.</s>

<s docid="AP891116-0184" num="35" wdcount="9"> A snow squall warning was posted for northeast Ohio.</s>

<s docid="AP891116-0184" num="36" wdcount="32"> Cold weather was expected to invade the Southeast, with warnings of freezing overnight temperatures posted for Friday morning in Georgia, Alabama, northwest Florida, most of Mississippi and all but extreme southeast Louisiana.</s>

<s docid="AP891116-0184" num="37" wdcount="16"> The low temperature for the nation Thursday morning was 8 degrees below zero at Bismarck, N.D.</s>

<s docid="AP891116-0184" num="38" wdcount="23"> Temperatures around the nation at 3 p.m. EST ranged from 7 degrees at Fergus Falls, Minn., to 88 degrees at Miami, Fla .</s>
</TEXT>
</DOC>
