<DOC>
<DOCNO>

<s docid="AP891117-0002" num="1" wdcount="1"> AP891117-0002</s>
</DOCNO>
<FILEID>

<s docid="AP891117-0002" num="2" wdcount="2"> AP-NR-11-17-89 2349EST</s>
</FILEID>
<FIRST>

<s docid="AP891117-0002" num="3" wdcount="7"> u a AM-AlabamaTornado 1stLd-Writethru a0720 11-17 0590</s>
</FIRST>
<SECOND>

<s docid="AP891117-0002" num="4" wdcount="5"> AM-Alabama Tornado, 1st Ld-Writethru, a0720,0603</s>
</SECOND>
<HEAD>

<s docid="AP891117-0002" num="5" wdcount="7"> Federal Relief OK'd; Governor Visits the Grieving</s>
</HEAD>
<HEAD>

<s docid="AP891117-0002" num="6" wdcount="32"> Eds: INSERTS 1 graf after 7th graf, `More than '... to UPDATE with Hunt asking flags be flown at half-staff, Marilyn Quayle to visit city; picks up 8th graf, `President Bush ...'</s>
</HEAD>
<HEAD>

<s docid="AP891117-0002" num="7" wdcount="3"> With AM-Storm-School, Bjt</s>
</HEAD>
<HEAD>

<s docid="AP891117-0002" num="8" wdcount="3"> LaserPhotos HUN4, MY1</s>
</HEAD>
<BYLINE>

<s docid="AP891117-0002" num="9" wdcount="3"> By PAUL NEWBERRY</s>
</BYLINE>
<BYLINE>

<s docid="AP891117-0002" num="10" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP891117-0002" num="11" wdcount="3"> HUNTSVILLE, Ala. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP891117-0002" num="12" wdcount="31"> Federal aid was approved Friday for tornado-ravaged Huntsville, where 17 died and several hundred were injured or lost their homes, and Gov. Guy Hunt toured hospitals and visited with grieving families.</s>

<s docid="AP891117-0002" num="13" wdcount="37"> ``I've been around a lot of tornadoes, but I've not seen the type of damage on as broad a scale as I've seen this morning,'' Hunt said after a helicopter tour of the 10-mile-long path of destruction.</s>

<s docid="AP891117-0002" num="14" wdcount="30"> State emergency management officials estimated the damage in excess of $100 million in the agency's letter to President Bush requesting a disaster declaration, said Terry Abbott, the governor's press secretary.</s>

<s docid="AP891117-0002" num="15" wdcount="17"> ``I've never seen as much rubble from a tornado before,'' said Danny Cooper, the state agency's director.</s>

<s docid="AP891117-0002" num="16" wdcount="26"> He listed 119 houses destroyed, 125 with minor damage, and three churches, two schools, 35 businesses and 10 public buildings either destroyed or suffering heavy damage.</s>

<s docid="AP891117-0002" num="17" wdcount="15"> Wind in the tornado was estimated at 250 mph when the twister hit Wednesday afternoon.</s>

<s docid="AP891117-0002" num="18" wdcount="20"> More than 400 people were injured, with about 80 still under care in hospitals when Hunt visited patients' rooms Friday.</s>

<s docid="AP891117-0002" num="19" wdcount="8"> City officials said about 1,000 were left homeless.</s>

<s docid="AP891117-0002" num="20" wdcount="33"> Hunt asked that flags around the state be lowered to half-staff through Tuesday in memory of the victims, and Marilyn Quayle, wife of the vice president, planned to visit the battered city Saturday.</s>

<s docid="AP891117-0002" num="21" wdcount="19"> President Bush issued a disaster declaration Friday morning to clear the way for tornado victims to receive federal relief.</s>

<s docid="AP891117-0002" num="22" wdcount="22"> Cooper said about $1 million may be needed in the form of individual and family grants to provide clothing and temporary housing.</s>

<s docid="AP891117-0002" num="23" wdcount="14"> The federal government pays 75 percent of the cost and the state 25 percent.</s>

<s docid="AP891117-0002" num="24" wdcount="26"> Grant Peterson, associate director of the federal Emergency Management Agency, said Friday he hopes that offices can be opened Sunday to take applications for disaster relief.</s>

<s docid="AP891117-0002" num="25" wdcount="12"> He said assistance checks may be in the mail within a week.</s>

<s docid="AP891117-0002" num="26" wdcount="13"> FEMA's reaction time was criticized after South Carolina was struck by a hurricane.</s>

<s docid="AP891117-0002" num="27" wdcount="23"> Police spokesman Ronnie Fudge said several truckloads of food had arrived but the city is running out of places to store the goods.</s>

<s docid="AP891117-0002" num="28" wdcount="13"> He urged that people donate money to relief agencies rather than send food.</s>

<s docid="AP891117-0002" num="29" wdcount="25"> Hunt visited privately Friday morning with families of some of the 17 killed in the tornado, The victims ranged in age from 7 to 67.</s>

<s docid="AP891117-0002" num="30" wdcount="28"> Two of the dead, John and Wanda Lewis, were found holding each other beneath a table, crushed by a collapsed ceiling at Gates Cleaners, where Lewis was manager.</s>

<s docid="AP891117-0002" num="31" wdcount="11"> Much of Westbury Mall was reduced to rubble by the tornado.</s>

<s docid="AP891117-0002" num="32" wdcount="17"> ``To look at that building, it's hard to understand why more people were not killed,'' Hunt said.</s>

<s docid="AP891117-0002" num="33" wdcount="11"> Hunt also stopped at a school heavily damaged by the tornado.</s>

<s docid="AP891117-0002" num="34" wdcount="10"> A hole in one outside wall exposed a caved-in classroom.</s>

<s docid="AP891117-0002" num="35" wdcount="19"> Because the tornado struck at 4:30 p.m., most of the classrooms were empty and only six children were injured.</s>

<s docid="AP891117-0002" num="36" wdcount="23"> School personnel and painters in the building were credited with helping protect about 30 youngsters in extended hours and kindergarten day care programs.</s>

<s docid="AP891117-0002" num="37" wdcount="9"> Some children were moved into a closet for safety.</s>

<s docid="AP891117-0002" num="38" wdcount="17"> ``There were a lot of heroes, or more people would have been killed,'' said the governor .</s>
</TEXT>
</DOC>
