<DOC>
<DOCNO>

<s docid="AP890121-0123" num="1" wdcount="1"> AP890121-0123</s>
</DOCNO>
<FILEID>

<s docid="AP890121-0123" num="2" wdcount="2"> AP-NR-01-21-89 1825EST</s>
</FILEID>
<FIRST>

<s docid="AP890121-0123" num="3" wdcount="5"> u a AM-SchoolShooting 01-21 0396</s>
</FIRST>
<SECOND>

<s docid="AP890121-0123" num="4" wdcount="2"> AM-School Shooting,0406</s>
</SECOND>
<HEAD>

<s docid="AP890121-0123" num="5" wdcount="6"> Memorial Services Remember Five Slain Children</s>
</HEAD>
<HEAD>

<s docid="AP890121-0123" num="6" wdcount="4"> With AM-School Shooting-Profile Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP890121-0123" num="7" wdcount="3"> By JOHN HOWARD</s>
</BYLINE>
<BYLINE>

<s docid="AP890121-0123" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890121-0123" num="9" wdcount="3"> STOCKTON, Calif. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890121-0123" num="10" wdcount="21"> Grieving relatives and friends gathered at memorial services Saturday to mourn the five school children slain by a camouflage-garbed, suicidal drifter.</s>

<s docid="AP890121-0123" num="11" wdcount="47"> ``Although there are some people in the United States who do bad things, most of the people in the United States do good things,'' said Patricia Busher, principal of Cleveland Elementary School, where the killings and the woundings of 29 students and one teacher happened last Tuesday.</s>

<s docid="AP890121-0123" num="12" wdcount="11"> ``The tragedy that occurred at our school could have happened anywhere.</s>

<s docid="AP890121-0123" num="13" wdcount="13"> There is no way to protect us from this kind of tragedy ...</s>

<s docid="AP890121-0123" num="14" wdcount="3"> this senseless tragedy.</s>

<s docid="AP890121-0123" num="15" wdcount="15"> In time, some of the cutting edge of the pain will go away,'' Busher said.</s>

<s docid="AP890121-0123" num="16" wdcount="25"> Her speech, at a memorial service attended by 200 people for the four Cambodian children killed, was translated as she spoke into the Cambodian language.</s>

<s docid="AP890121-0123" num="17" wdcount="33"> ``Tragedy has followed you,'' state Sen. John Garamendi told the families, refugees from a country where more than 1 million people were killed in executions and enforced hardship after a 1975 communist takeover.</s>

<s docid="AP890121-0123" num="18" wdcount="22"> The service, held in Central Methodist Church, was for 8-year-old Oeun Lim, 9-year-old Rathanan Or, 8-year-old Ram Chun and 6-year-old Sokhim An.</s>

<s docid="AP890121-0123" num="19" wdcount="19"> During the morning, a Catholic funeral mass and burial were held for 6-year-old Thuy Tran, daughter of Vietnamese refugees.</s>

<s docid="AP890121-0123" num="20" wdcount="13"> Another memorial service for the four Cambodians was planned Sunday at a mortuary.</s>

<s docid="AP890121-0123" num="21" wdcount="19"> Gov. George Deukmejian planned to speak at a service Monday morning for all five children at Stockton Civic Auditorium.</s>

<s docid="AP890121-0123" num="22" wdcount="17"> People attending that service were asked to follow a Southeast Asian cultural tradition and wear black-and-white ribbons.</s>

<s docid="AP890121-0123" num="23" wdcount="43"> Patrick Edward Purdy, who turned a gun on himself after firing more than 100 rounds from an AK-47 semi-automatic assault rifle at Cleveland Elementary, where he had attended grade school, was buried Friday in an unmarked grave in a family plot at Lodi.</s>

<s docid="AP890121-0123" num="24" wdcount="12"> Ten of the wounded children and the wounded teacher remained hospitalized Saturday.</s>

<s docid="AP890121-0123" num="25" wdcount="5"> Three children were discharged Friday.</s>

<s docid="AP890121-0123" num="26" wdcount="20"> Stockton police said they have located all of Purdy's close relatives, except for his mother, identified as 43-year-old Kathy Snyder.</s>

<s docid="AP890121-0123" num="27" wdcount="35"> Police said she has had four different surnames and that when she renewed her driver's license a year ago, she used an address in La Mesa that turned out to be a chemical shed .</s>
</TEXT>
</DOC>
