<DOC>
<DOCNO>

<s docid="AP890118-0013" num="1" wdcount="1"> AP890118-0013</s>
</DOCNO>
<FILEID>

<s docid="AP890118-0013" num="2" wdcount="2"> AP-NR-01-18-89 0021EST</s>
</FILEID>
<FIRST>

<s docid="AP890118-0013" num="3" wdcount="7"> u a AM-SchoolShooting-Gunman 1stLd-Writethru a0atedPress 01-18 0480</s>
</FIRST>
<SECOND>

<s docid="AP890118-0013" num="4" wdcount="7"> AM-School Shooting-Gunman, 1st Ld - Writethru, a0418,0490</s>
</SECOND>
<HEAD>

<s docid="AP890118-0013" num="5" wdcount="8"> School Gunman Described as Loner And Childhood Alcoholic</s>
</HEAD>
<HEAD>

<s docid="AP890118-0013" num="6" wdcount="15"> Eds: CORRECTS gunman's age in lead and name to Purdy in 11th graf bgng ``However.''</s>
</HEAD>
<HEAD>

<s docid="AP890118-0013" num="7" wdcount="3"> With AM-School Shooting</s>
</HEAD>
<BYLINE>

<s docid="AP890118-0013" num="8" wdcount="3"> By BOB BAUM</s>
</BYLINE>
<BYLINE>

<s docid="AP890118-0013" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890118-0013" num="10" wdcount="3"> SANDY, Ore. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890118-0013" num="11" wdcount="33"> The 26-year-old drifter with a long criminal record who launched a mute, murderous assault on a California elementary school Tuesday was described by his aunt as a loner and childhood alcoholic, police said.</s>

<s docid="AP890118-0013" num="12" wdcount="50"> Patrick E. Purdy purchased an AK-47 rifle in this Portland suburb several months ago, then returned to his hometown of Stockton, Calif., where he used the gun to kill five children and wound 29 others, along with a teacher, at Cleveland Elementary School before taking his own life, authorities said.</s>

<s docid="AP890118-0013" num="13" wdcount="32"> Purdy, who went by the alias of Patrick West, had lived with an aunt and uncle in Sandy from the first of July until late October, said Sandy Police Chief Fred Punzel.</s>

<s docid="AP890118-0013" num="14" wdcount="29"> He later moved to Lodi, Calif., where he listed his mailing address under the name of his grandmother, Julia Chumbley, although he did not live with her, authorities said.</s>

<s docid="AP890118-0013" num="15" wdcount="2"> ``I'm shocked.</s>

<s docid="AP890118-0013" num="16" wdcount="3"> It's just horrible.</s>

<s docid="AP890118-0013" num="17" wdcount="19"> I don't understand why and I probably won't ever know why,'' said Ms. Chumbley, a 63-year-old retired cannery worker.</s>

<s docid="AP890118-0013" num="18" wdcount="12"> ``It troubles me to think that such a terrible thing can happen.</s>

<s docid="AP890118-0013" num="19" wdcount="4"> It's like a nightmare.</s>

<s docid="AP890118-0013" num="20" wdcount="9"> This sort of thing happens to others, not you.</s>

<s docid="AP890118-0013" num="21" wdcount="3"> Your own grandson''.</s>

<s docid="AP890118-0013" num="22" wdcount="8"> Stockton is about 15 miles southwest of Lodi.</s>

<s docid="AP890118-0013" num="23" wdcount="20"> Punzel said Purdy's aunt, Julie Michael, ``told me he was a loner and as a child he was an alcoholic''.</s>

<s docid="AP890118-0013" num="24" wdcount="20"> Mrs. Michael said through a closed front door at her residence that she was too upset to talk to reporters.</s>

<s docid="AP890118-0013" num="25" wdcount="18"> Her next-door neighbor, Pat Thomas, 45, said she met West when he lived with his relatives last summer.</s>

<s docid="AP890118-0013" num="26" wdcount="10"> ``He seemed like a real nice young man,'' she said.</s>

<s docid="AP890118-0013" num="27" wdcount="6"> ``He was here looking for work''.</s>

<s docid="AP890118-0013" num="28" wdcount="30"> However, Purdy had an ``extensive criminal history,'' mostly in the Los Angeles area, said Lucian Neely, deputy police chief in Stockton, an agricultural city 60 miles east of San Francisco.</s>

<s docid="AP890118-0013" num="29" wdcount="13"> Purdy had no criminal record in Sandy, Clackamas County or Portland, authorities said.</s>

<s docid="AP890118-0013" num="30" wdcount="21"> Neely said Purdy originally was from Stockton and that he had purchased the gun at the Sandy Trading Post Aug. 3.</s>

<s docid="AP890118-0013" num="31" wdcount="17"> Punzel said Mrs. Michael told him Purdy left Oregon for a job as a boilermaker in Texas.</s>

<s docid="AP890118-0013" num="32" wdcount="10"> That job fell through and he went to Memphis, Tenn.</s>

<s docid="AP890118-0013" num="33" wdcount="17"> The aunt and uncle last heard from Purdy at Thanksgiving, when he was in Connecticut, Punzel said.</s>

<s docid="AP890118-0013" num="34" wdcount="27"> His mother lives in Sacramento, Calif., and his father was killed in 1980 or 1981 when he was struck by a car as a pedestrian, Punzel said.</s>

<s docid="AP890118-0013" num="35" wdcount="23"> State Division of Motor Vehicles records identify Purdy as 5-foot-11, 150 pounds, with blue eyes and blond hair, said spokesman Dave Davis .</s>
</TEXT>
</DOC>
