<DOC>
<DOCNO>

<s docid="AP890118-0094" num="1" wdcount="1"> AP890118-0094</s>
</DOCNO>
<FILEID>

<s docid="AP890118-0094" num="2" wdcount="2"> AP-NR-01-18-89 1018EST</s>
</FILEID>
<FIRST>

<s docid="AP890118-0094" num="3" wdcount="5"> r a PM-SchoolShooting-Greenwood 01-18 0279</s>
</FIRST>
<SECOND>

<s docid="AP890118-0094" num="4" wdcount="2"> PM-School Shooting-Greenwood,0286</s>
</SECOND>
<HEAD>

<s docid="AP890118-0094" num="5" wdcount="8"> S.C. School Where Two Were Slain Offers Condolences</s>
</HEAD>
<HEAD>

<s docid="AP890118-0094" num="6" wdcount="4"> With PM-School Shooting, Bjt</s>
</HEAD>
<DATELINE>

<s docid="AP890118-0094" num="7" wdcount="3"> GREENWOOD, S.C. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890118-0094" num="8" wdcount="33"> A South Carolina school where a gunman killed two 8-year-old girls Sept. 26 will send cards and offer words of encouragement to a California school that lost five pupils in a shooting rampage.</s>

<s docid="AP890118-0094" num="9" wdcount="30"> ``We will tell them they can survive this,'' said Kat Finkbeiner, a physical education teacher whose jaw was shattered in the shooting spree last year at Greenwood's Oakland Elementary School.</s>

<s docid="AP890118-0094" num="10" wdcount="11"> ``I would tell them, `Lean on your community, share the sorrow'.</s>

<s docid="AP890118-0094" num="11" wdcount="4"> We've lived through this.</s>

<s docid="AP890118-0094" num="12" wdcount="5"> I know we can help''.</s>

<s docid="AP890118-0094" num="13" wdcount="28"> On Sept. 26, a man with a history of mental problems opened fire with a handgun at Oakland Elementary School, killing two youngsters and wounding nine other people.</s>

<s docid="AP890118-0094" num="14" wdcount="9"> Ms. Finkbeiner helped subdue the gunman, Jamie Wilson, 19.</s>

<s docid="AP890118-0094" num="15" wdcount="36"> On Tuesday, a 26-year-old drifter with a long crimnal record opened fire with an assault rifle at Cleveland Elementary School in Stockton, Calif., killing five children and wounding 30 other people before taking his own life.</s>

<s docid="AP890118-0094" num="16" wdcount="2"> ``It's unpleasant.</s>

<s docid="AP890118-0094" num="17" wdcount="17"> It's unhappy, but they can live through it; they can be happy another day,'' Ms. Finkbeiner said.</s>

<s docid="AP890118-0094" num="18" wdcount="35"> Children at the Greenwood school will be asked to send cards to the California school, while the principal, Eleanor Rice, and Ms. Finkbeiner said they will contact officials at the Stockton school to offer encouragement.</s>

<s docid="AP890118-0094" num="19" wdcount="5"> ``Our wounds have not closed.</s>

<s docid="AP890118-0094" num="20" wdcount="4"> We are still hurting.</s>

<s docid="AP890118-0094" num="21" wdcount="11"> It makes us more compassionate for these people,'' the principal said.</s>

<s docid="AP890118-0094" num="22" wdcount="23"> Eveline Higginbotham, the third-grade teacher in whose classroom the two little girls died, said the California tragedy ``just brings it all back again''.</s>

<s docid="AP890118-0094" num="23" wdcount="7"> ``I'm just in shock,'' she said .</s>
</TEXT>
</DOC>
