<DOC>
<DOCNO>

<s docid="AP890117-0160" num="1" wdcount="1"> AP890117-0160</s>
</DOCNO>
<FILEID>

<s docid="AP890117-0160" num="2" wdcount="2"> AP-NR-01-17-89 1651EST</s>
</FILEID>
<FIRST>

<s docid="AP890117-0160" num="3" wdcount="7"> u a BC-SchoolSchooting 2ndLd-Writethru a0671 01-17 0200</s>
</FIRST>
<SECOND>

<s docid="AP890117-0160" num="4" wdcount="5"> BC-School Schooting, 2nd Ld-Writethru, a0671,0204</s>
</SECOND>
<HEAD>

<s docid="AP890117-0160" num="5" wdcount="1"> URGENT</s>
</HEAD>
<HEAD>

<s docid="AP890117-0160" num="6" wdcount="6"> Six Children Killed in Shooting Spree</s>
</HEAD>
<HEAD>

<s docid="AP890117-0160" num="7" wdcount="7"> Eds: UPDATES throughout with fatalities, details .</s>
</HEAD>
<DATELINE>

<s docid="AP890117-0160" num="8" wdcount="3"> STOCKTON, Calif. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890117-0160" num="9" wdcount="33"> A man fired several dozen shots from an automatic rifle in an elementary school Tuesday, killing six children, wounding at least 35 other people and then shooting himself in the head, authorities said.</s>

<s docid="AP890117-0160" num="10" wdcount="22"> ``We have at least one suspect in custody who has a gunshot wound to the head,'' Deputy Police Chief Ralph Tribble said.</s>

<s docid="AP890117-0160" num="11" wdcount="15"> Bruce Fernandez, spokesman for the county office of emergency services, said six people had died.</s>

<s docid="AP890117-0160" num="12" wdcount="4"> Ellen Rich at St.</s>

<s docid="AP890117-0160" num="13" wdcount="24"> Joseph's Medical Center said eight victims were being treated there, and said the total, including those being treated at other hospitals, was 35 wounded.</s>

<s docid="AP890117-0160" num="14" wdcount="18"> ``We have at least 30 people that we've sent out to area hospitals,'' said Police Chief Jack Calkins.</s>

<s docid="AP890117-0160" num="15" wdcount="10"> The attack at Cleveland Elementary School came shortly before noon.</s>

<s docid="AP890117-0160" num="16" wdcount="16"> Other children were kept in their rooms, said John Klose, Stockton Unified School District information officer.</s>

<s docid="AP890117-0160" num="17" wdcount="23"> Police Sgt. James Monk said his office learned that a ``man went berserk with an automatic weapon and we have several (people) down''.</s>

<s docid="AP890117-0160" num="18" wdcount="12"> ``Several dozen shots were heard from an automatic rifle,'' said Monk .</s>
</TEXT>
</DOC>
