<DOC>
<DOCNO>

<s docid="AP890118-0051" num="1" wdcount="1"> AP890118-0051</s>
</DOCNO>
<FILEID>

<s docid="AP890118-0051" num="2" wdcount="2"> AP-NR-01-18-89 0434EST</s>
</FILEID>
<FIRST>

<s docid="AP890118-0051" num="3" wdcount="6"> r a PM-SchoolShooting-Scene Bjt 01-18 0637</s>
</FIRST>
<SECOND>

<s docid="AP890118-0051" num="4" wdcount="3"> PM-School Shooting-Scene, Bjt,0654</s>
</SECOND>
<HEAD>

<s docid="AP890118-0051" num="5" wdcount="7"> Neighborhood in Shock at School's `Killing Field'</s>
</HEAD>
<BYLINE>

<s docid="AP890118-0051" num="6" wdcount="3"> By KATHLEEN GRUBB</s>
</BYLINE>
<BYLINE>

<s docid="AP890118-0051" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890118-0051" num="8" wdcount="3"> STOCKTON, Calif. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890118-0051" num="9" wdcount="35"> Children whose families escaped the horrors of the Vietnam War saw their schoolyard turned into a killing field, the target of a silent gunman armed with a rifle and a pistol bearing the word ``victory''.</s>

<s docid="AP890118-0051" num="10" wdcount="26"> After the massacre at recess, the bodies of three Southeast Asian children were outlined in blue on the playground of Cleveland Elementary School where they died.</s>

<s docid="AP890118-0051" num="11" wdcount="14"> Two others had been dragged by teachers inside to a classroom, but also died.</s>

<s docid="AP890118-0051" num="12" wdcount="9"> Twenty-nine other pupils were wounded, along with a teacher.</s>

<s docid="AP890118-0051" num="13" wdcount="5"> ``There was shooting all over.</s>

<s docid="AP890118-0051" num="14" wdcount="27"> ... I was scared,'' said sixth-grader Binh Hoang, who was born in Vietnam in 1975 in the final days of war and had never before heard gunfire.</s>

<s docid="AP890118-0051" num="15" wdcount="6"> ``Everybody was crying in my class''.</s>

<s docid="AP890118-0051" num="16" wdcount="37"> Police said a drifter identified as Patrick Edward Purdy, 26, armed with two handguns and an AK-47 assault rifle, entered the school grounds around noontime Tuesday and fired about 60 rounds before he shot himself to death.</s>

<s docid="AP890118-0051" num="17" wdcount="21"> Afterward, a large handgun and the assault rifle lay on the ground near a pool of blood and the gunman's body.</s>

<s docid="AP890118-0051" num="18" wdcount="9"> The word ``victory'' was written on the pistol handle.</s>

<s docid="AP890118-0051" num="19" wdcount="17"> Binh said she was sitting in math class when the shooting began outside the wood-and-stucco school building.</s>

<s docid="AP890118-0051" num="20" wdcount="9"> Her teacher told students to get under their desks.</s>

<s docid="AP890118-0051" num="21" wdcount="25"> The gunfire startled Michael Cuevas, whose first thought was that the University of the Pacific fraternities near his house were firing their miniature cannon again.</s>

<s docid="AP890118-0051" num="22" wdcount="23"> But the shots repeated too rapidly for a cannon, and the scream of sirens that followed told him this time was no prank.</s>

<s docid="AP890118-0051" num="23" wdcount="32"> ``I never thought a tragedy of this magnitude could happen in Stockton,'' said Cuevas, a 29-year-old marine clerk at the Port of Stockton who lives down the street from the elementary school.</s>

<s docid="AP890118-0051" num="24" wdcount="9"> ``It's always in some other town, some other place.</s>

<s docid="AP890118-0051" num="25" wdcount="6"> It's a shock to my senses.</s>

<s docid="AP890118-0051" num="26" wdcount="13"> I don't think it's even hit me as hard as it's going to.</s>

<s docid="AP890118-0051" num="27" wdcount="11"> You don't know whether to be excited, or confused or what''.</s>

<s docid="AP890118-0051" num="28" wdcount="22"> Police cars and news reporters crowded the street, which typically is busy only when parents pick up and drop off their children.</s>

<s docid="AP890118-0051" num="29" wdcount="14"> ``Why here''? said Jeff Russell, 37, who was born and reared in the neighborhood.</s>

<s docid="AP890118-0051" num="30" wdcount="8"> ``This has always been a sleepy little town.</s>

<s docid="AP890118-0051" num="31" wdcount="8"> (The shooting) put us back on the map''.</s>

<s docid="AP890118-0051" num="32" wdcount="36"> Lutheran and Baptist churches border the school in a neighborhood of ranch-style homes, postage-stamp lawns and streets lined with sycamore and oak trees in this agricultural city of 150,000 people 60 miles southeast of San Francisco.</s>

<s docid="AP890118-0051" num="33" wdcount="21"> The 40-year-old neighborhood near the University of the Pacific is still home to many retired couples who raised their familes there.</s>

<s docid="AP890118-0051" num="34" wdcount="13"> But the city has been changing with the influx of Southeast Asian refugees.</s>

<s docid="AP890118-0051" num="35" wdcount="23"> When school officials called clergy to console grieving families, Buddhist priests in sandals and saffron robes arrived along with their white-collared Christian counterparts.</s>

<s docid="AP890118-0051" num="36" wdcount="21"> About 60 percent of Cleveland Elementary's students are of Southeast Asian descent, said John Klose, spokesman for the Stockton School District.</s>

<s docid="AP890118-0051" num="37" wdcount="10"> The five children who were killed were Vietnamese and Cambodian.</s>

<s docid="AP890118-0051" num="38" wdcount="10"> ``This is one of our best neighborhood schools,'' Klose said.</s>

<s docid="AP890118-0051" num="39" wdcount="24"> ``Of all of our schools that I would think of something like this happening, this would be the last one I would think of''.</s>

<s docid="AP890118-0051" num="40" wdcount="20"> Across the street, Sarah Abbott stood astride her bicycle and gazed at the school where she graduated ``many years ago''.</s>

<s docid="AP890118-0051" num="41" wdcount="31"> The professional nanny said she was at the house of her 97-year-old grandfather about a block from the school when the gunman set his car on fire before starting to shoot.</s>

<s docid="AP890118-0051" num="42" wdcount="11"> ``When the car exploded, my grandpa's house just shook,'' Abbott said.</s>

<s docid="AP890118-0051" num="43" wdcount="3"> ``It scared me.</s>

<s docid="AP890118-0051" num="44" wdcount="6"> ... It was just too close.''</s>
</TEXT>
</DOC>
