<DOC>
<DOCNO>

<s docid="AP890121-0050" num="1" wdcount="1"> AP890121-0050</s>
</DOCNO>
<FILEID>

<s docid="AP890121-0050" num="2" wdcount="2"> AP-NR-01-21-89 0750EST</s>
</FILEID>
<FIRST>

<s docid="AP890121-0050" num="3" wdcount="5"> r a PM-SchoolShooting 01-21 0480</s>
</FIRST>
<SECOND>

<s docid="AP890121-0050" num="4" wdcount="2"> PM-School Shooting,0493</s>
</SECOND>
<HEAD>

<s docid="AP890121-0050" num="5" wdcount="7"> Prayers, Counseling in Aftermath of School Shooting</s>
</HEAD>
<BYLINE>

<s docid="AP890121-0050" num="6" wdcount="3"> By KATHLEEN MACLAY</s>
</BYLINE>
<BYLINE>

<s docid="AP890121-0050" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890121-0050" num="8" wdcount="3"> STOCKTON, Calif. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890121-0050" num="9" wdcount="26"> Grief-stricken family and friends mourned the deaths of five school children gunned down during recess, while the killer was buried nearly unnoticed in a nearby town.</s>

<s docid="AP890121-0050" num="10" wdcount="20"> Parents and teachers continued counseling the children who witnessed Tuesday's schoolyard slayings, trying to help them deal with the tragedy.</s>

<s docid="AP890121-0050" num="11" wdcount="31"> Patrick Purdy, 24, opened fire outside the Cleveland Elementary School with an AK-47 semiautomatic assault rifle, firing more than 100 rounds, killing five children and wounding 29 others and one teacher.</s>

<s docid="AP890121-0050" num="12" wdcount="26"> Three days and nights of prayer began Thursday for two of the youngsters killed, and services for the other children were being held today and Monday.</s>

<s docid="AP890121-0050" num="13" wdcount="8"> Gov. George Deukmejian was to attend Monday's services.</s>

<s docid="AP890121-0050" num="14" wdcount="12"> Purdy was buried Friday in nearby Lodi, said his grandmother, Julia Chumbley.</s>

<s docid="AP890121-0050" num="15" wdcount="18"> He was interred following a service at Cherokee Memorial Cemetery, which several of his relatives attended, she said.</s>

<s docid="AP890121-0050" num="16" wdcount="15"> Fourteen of the wounded students were still hospitalized, but most were reported in improved conditions.</s>

<s docid="AP890121-0050" num="17" wdcount="33"> At Cleveland School, about three-quarters of the school's 970 pupils had returned to classes by Friday, about three times the number who attended Wednesday, but it was anything but a routine school day.</s>

<s docid="AP890121-0050" num="18" wdcount="22"> Counselors and school psychologists were assisting teachers in classrooms, and some parents sat in with their children to comfort and reassure them.</s>

<s docid="AP890121-0050" num="19" wdcount="37"> One mother, who asked not to be identified, told reporters that her youngest son, a 7-year-old second grader who was on playground when the shootings occurred, would only come back to school if she stayed with him.</s>

<s docid="AP890121-0050" num="20" wdcount="27"> ``They're making it back, slowly but surely,'' she said, adding that she planned to spend Friday as she did Thursday, at her son's side in the classroom.</s>

<s docid="AP890121-0050" num="21" wdcount="25"> Cleveland School is in the heart of California's third-largest community of refugees from Southeast Asia, and nearly two-thirds of the school's population is from Asia.</s>

<s docid="AP890121-0050" num="22" wdcount="16"> All of the dead children were from refugee families, as were 19 of the 29 wounded.</s>

<s docid="AP890121-0050" num="23" wdcount="46"> School authorities said they were particularly concerned that the killing might not only revive the psychological trauma of the horrors they experienced in Southeast Asia, but that those families might flee from the area without accepting counseling if they feared a racial motive in the attack.</s>

<s docid="AP890121-0050" num="24" wdcount="17"> ``We want to pass the word to the community that this is not a racist act ...</s>

<s docid="AP890121-0050" num="25" wdcount="7"> It could happen to anybody, anywhere, anytime.</s>

<s docid="AP890121-0050" num="26" wdcount="8"> This is a crazy action from one individual.</s>

<s docid="AP890121-0050" num="27" wdcount="14"> It is not racism,'' said An Tran of the Southeast Asian Refugee Resettlement Program.</s>

<s docid="AP890121-0050" num="28" wdcount="24"> Stockton Police Capt. Dennis Perry also repeated that there was no evidence that Purdy, who committed suicide after the attack, was specifically targeting Asians.</s>

<s docid="AP890121-0050" num="29" wdcount="9"> ``It wasn't any one race or group of people.</s>

<s docid="AP890121-0050" num="30" wdcount="19"> He hated everybody,'' Perry said of Purdy, who as a child 14 years earlier had attended Cleveland School .</s>
</TEXT>
</DOC>
