<DOC>
<DOCNO>

<s docid="AP890117-0004" num="1" wdcount="1"> AP890117-0004</s>
</DOCNO>
<FILEID>

<s docid="AP890117-0004" num="2" wdcount="2"> AP-NR-01-17-89 2352EST</s>
</FILEID>
<FIRST>

<s docid="AP890117-0004" num="3" wdcount="6"> u a AM-SchoolShooting-Refugees 1stLd-Writethru 01-17 0348</s>
</FIRST>
<SECOND>

<s docid="AP890117-0004" num="4" wdcount="7"> AM-School Shooting-Refugees, 1st Ld - Writethru, a0779,0350</s>
</SECOND>
<HEAD>

<s docid="AP890117-0004" num="5" wdcount="11"> Asian Translators Rushed in to Help Parents of Children in Shooting</s>
</HEAD>
<HEAD>

<s docid="AP890117-0004" num="6" wdcount="21"> Eds: SUBS 5th graf, `In recent...,' to CORRECT that 60 percent of children, sted 70 to 80 percent, are Southeast Asian</s>
</HEAD>
<DATELINE>

<s docid="AP890117-0004" num="7" wdcount="3"> STOCKTON, Calif. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890117-0004" num="8" wdcount="40"> Within hours of the schoolyard shootings that left five children and the gunman dead and 30 wounded Tuesday, dozens of translators rushed to assist the many Southeast Asian parents who arrived at the hospital desperate for word of their youngsters.</s>

<s docid="AP890117-0004" num="9" wdcount="7"> ``I would imagine it is absolute panic.</s>

<s docid="AP890117-0004" num="10" wdcount="38"> They are not sure what happened, not sure what's going on around them,'' said Laura Dixon, of the Charterhouse Center refugee program, in Stockton, describing the scene translators found when they arrived at San Joaquin County General Hospital.</s>

<s docid="AP890117-0004" num="11" wdcount="41"> Many of the parents speak no English and were unable to ask whether their children were among those killed or wounded when a heavily armed gunman in combat fatigues invaded Cleveland Elementary School and opened fire before taking his own life.</s>

<s docid="AP890117-0004" num="12" wdcount="36"> ``They do have people on staff at the hospital, but they are so overloaded they need every extra person they can secure,'' said Dixon, whose organization began calling throughout Stockton for volunteers speaking Southeast Asian languages.</s>

<s docid="AP890117-0004" num="13" wdcount="16"> About a dozen translators were sent to the county hospital, after officials there called for help.</s>

<s docid="AP890117-0004" num="14" wdcount="24"> In recent years, thousands of Southeast Asians have settled in Stockton, drawn in part by the farming and fishing that flourish in the area.</s>

<s docid="AP890117-0004" num="15" wdcount="19"> School officials said 60 percent of the children were Southeast Asian refugees _ either from Cambodia, Laos or Thailand.</s>

<s docid="AP890117-0004" num="16" wdcount="12"> All five of the children killed were of this background, authorities said.</s>

<s docid="AP890117-0004" num="17" wdcount="31"> A Stockton woman who runs an after-school program teaching English to Cambodian refugees dispatched 25 translators, including volunteers from all over the city, to the school and the hospital, Dixon said.</s>

<s docid="AP890117-0004" num="18" wdcount="29"> The San Joaquin County Mental Health Department told Dixon a grief center might be established at Charterhouse to help survivors, whose recovery will be complicated by the language barrier.</s>

<s docid="AP890117-0004" num="19" wdcount="11"> Charterhouse is funded by the Episcopal Church and private donations .</s>
</TEXT>
</DOC>
