<DOC>
<DOCNO>

<s docid="AP890119-0221" num="1" wdcount="1"> AP890119-0221</s>
</DOCNO>
<FILEID>

<s docid="AP890119-0221" num="2" wdcount="2"> AP-NR-01-19-89 2308EST</s>
</FILEID>
<FIRST>

<s docid="AP890119-0221" num="3" wdcount="5"> r a AM-PurdySketch 01-19 0441</s>
</FIRST>
<SECOND>

<s docid="AP890119-0221" num="4" wdcount="2"> AM-Purdy Sketch,0456</s>
</SECOND>
<HEAD>

<s docid="AP890119-0221" num="5" wdcount="4"> With AM-School Shooting Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP890119-0221" num="6" wdcount="4"> By The Associated Press</s>
</BYLINE>
<TEXT>

<s docid="AP890119-0221" num="7" wdcount="20"> Here is a profile of the gunman who took the lives of five children at a Stockton, Calif., school Tuesday.</s>

<s docid="AP890119-0221" num="8" wdcount="19"> It is based on information from police and relatives, and on background reported by the Sacramento Bee newspaper .</s>
</TEXT>
<TEXT>

<s docid="AP890119-0221" num="9" wdcount="10"> NAME: Patrick Edward Purdy, also called self Eddie Purdy West.</s>

<s docid="AP890119-0221" num="10" wdcount="2"> AGE: 24.</s>

<s docid="AP890119-0221" num="11" wdcount="8"> DESCRIPTION: 5-foot-11, 150 pounds, blue eyes, blond hair.</s>

<s docid="AP890119-0221" num="12" wdcount="11"> FAMILY: Parents married in Stockton, Calif., and divorced after short time.</s>

<s docid="AP890119-0221" num="13" wdcount="19"> Mother remarried and took Purdy to Lake Tahoe, Nev., area and on to Sacramento area, where she still lives.</s>

<s docid="AP890119-0221" num="14" wdcount="16"> Father, a Lodi, Calif., taxi company employee, was struck and killed by car in September 1981.</s>

<s docid="AP890119-0221" num="15" wdcount="9"> CHILDHOOD: Described by aunt as child alcoholic and loner.</s>

<s docid="AP890119-0221" num="16" wdcount="22"> EDUCATION: Records indicate a Patrick Edward Purdy attended Cleveland Elementary School, scene of Tuesday's shooting, through third grade, from 1969 to 1973.</s>

<s docid="AP890119-0221" num="17" wdcount="5"> Dropped out of high school.</s>

<s docid="AP890119-0221" num="18" wdcount="17"> Early in 1988, began attending vocational classes in welding at San Joaquin Delta Community College in Stockton.</s>

<s docid="AP890119-0221" num="19" wdcount="12"> EMPLOYMENT: Began drifting 10 years ago, crisscrossing country in search of work.</s>

<s docid="AP890119-0221" num="20" wdcount="20"> Worked for now-defunct Green Keys Nursery in Key West, Fla., from October 1984 to April 1985, using name Eddie West.</s>

<s docid="AP890119-0221" num="21" wdcount="14"> Left nursery to work briefly for construction company, then apparently departed for West Coast.</s>

<s docid="AP890119-0221" num="22" wdcount="18"> Was hired in January 1988 and worked for about a month at Numeri Tech, a Stockton machine shop.</s>

<s docid="AP890119-0221" num="23" wdcount="20"> In June 1988, traveled to Oregon, where worked in Portland as welder, then continued on to Colorado, Texas and Connecticut.</s>

<s docid="AP890119-0221" num="24" wdcount="4"> Workers at Blount Bros.</s>

<s docid="AP890119-0221" num="25" wdcount="19"> Construction Co. in Memphis, Tenn., said Purdy worked with them for short time in October 1988 as boilermaker mechanic.</s>

<s docid="AP890119-0221" num="26" wdcount="31"> ARRESTS: 1980, Los Angeles, charges involving prostitution; 1982, Los Angeles, marijuana charge; 1983, Beverly Hills, weapons charge; 1983, Los Angeles, charge of receiving stolen property; (date unreported), Woodland, Calif., robbery charge.</s>

<s docid="AP890119-0221" num="27" wdcount="9"> Apparently served time in jail for last two offenses.</s>

<s docid="AP890119-0221" num="28" wdcount="26"> OTHER PROBLEMS: In 1986, his mother called Stockton police to complain that he and his half-brother vandalized her car after she refused demands for drug money.</s>

<s docid="AP890119-0221" num="29" wdcount="30"> Twice tried to kill himself while in police custody in El Dorado County in April 1987, after he and half-brother fired at trees near Lake Tahoe with a semi-automatic pistol.</s>

<s docid="AP890119-0221" num="30" wdcount="20"> Made a rope out of torn shirt and tried to hang himself, then tried to cut his wrists, police said.</s>

<s docid="AP890119-0221" num="31" wdcount="13"> When arrested, was carrying a book about the white supremicist group Aryan Nations.</s>

<s docid="AP890119-0221" num="32" wdcount="20"> Told an El Dorado County sheriff's deputy it was his ``duty to help the suppressed and to overthrow the suppressor''.</s>

<s docid="AP890119-0221" num="33" wdcount="15"> In subsequent mental health report, was described as dangerous and suffering from ``mild mental retardation.''</s>
</TEXT>
</DOC>
