<DOC>
<DOCNO>

<s docid="LA011889-0131" num="1" wdcount="1"> LA011889-0131</s>
</DOCNO>
<DOCID>

<s docid="LA011889-0131" num="2" wdcount="1"> 7233</s>
</DOCID>
<DATE>
<P>

<s docid="LA011889-0131" num="3" wdcount="7"> January 18, 1989, Wednesday, Late Final Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA011889-0131" num="4" wdcount="9"> Part 1; Page 1; Column 3; Late Final Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA011889-0131" num="5" wdcount="2"> 499 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA011889-0131" num="6" wdcount="8"> GUNMAN ATTENDED SCHOOL HE TURNED INTO WAR ZONE;</s>
</P>
<P>

<s docid="LA011889-0131" num="7" wdcount="6"> KILLER OF 5 A 'NORMAL STUDENT'</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA011889-0131" num="8" wdcount="9"> By DAN MORAIN and CARL INGRAM, Times Staff Writers</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA011889-0131" num="9" wdcount="1"> STOCKTON</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA011889-0131" num="10" wdcount="38"> Patrick Edward Purdy, who turned a powerful assault rifle on a crowded school playground Tuesday, killing five children and wounding 29 more, had been a student at the school from kindergarten through third grade, officials said today .</s>
</P>
<P>

<s docid="LA011889-0131" num="11" wdcount="22"> The revelation's significance was not immediately clear, although it appeared to suggest that the attack at Cleveland Elementary was not altogether random.</s>

<s docid="LA011889-0131" num="12" wdcount="29"> Police officials said they still had not determined what set off Purdy, a troubled drifter in his mid-20s with a history of relatively minor brushes with the law .</s>
</P>
<P>

<s docid="LA011889-0131" num="13" wdcount="24"> The midday attack, which lasted only minutes, ended when Purdy mortally wounded himself in the head with a pistol, leaving his motive unexplained .</s>
</P>
<P>

<s docid="LA011889-0131" num="14" wdcount="22"> "I don't understand why, and I probably won't ever know why," said Purdy's grandmother, 63-year-old Julia Chumbley, who lives nearby in Lodi.</s>

<s docid="LA011889-0131" num="15" wdcount="23"> Other relatives described Purdy as a child alcoholic and a loner who had bounced across America, looking for work as a welder .</s>
</P>
<P>

<s docid="LA011889-0131" num="16" wdcount="27"> Cleveland Elementary was in session today, although only a little more than 200 pupils -- roughly one-fourth of the student body -- showed up for classes .</s>
</P>
<P>

<s docid="LA011889-0131" num="17" wdcount="21"> Those who did attend were greeted at the school by escorts who guided them through a thicket of reporters and cameras.</s>

<s docid="LA011889-0131" num="18" wdcount="20"> Counselors were stationed in each classroom to help the children come to grips with the horror of the previous day.</s>

<s docid="LA011889-0131" num="19" wdcount="11"> Each child was given a stuffed animal at the principal's office.</s>

<s docid="LA011889-0131" num="20" wdcount="10"> Teachers said they did not know what to expect .</s>
</P>
<P>

<s docid="LA011889-0131" num="21" wdcount="16"> "I'll just try to get through the day," said Vicki Braga, who teaches fourth grade .</s>
</P>
<P>

<s docid="LA011889-0131" num="22" wdcount="19"> The front entrance of the school was decorated with bouquets of yellow gladioli, purple mums and five red roses.</s>

<s docid="LA011889-0131" num="23" wdcount="12"> Someone also had placed there a pink teddy bear with angel's wings.</s>

<s docid="LA011889-0131" num="24" wdcount="15"> A banner stretched across the front said "Racists are ugly -- let's stop them" .</s>
</P>
<P>

<s docid="LA011889-0131" num="25" wdcount="21"> The banner's message enunciated an early suspicion that the racial composition of the student body might have contributed to Purdy's motivation.</s>

<s docid="LA011889-0131" num="26" wdcount="18"> More than 600 of the 980 students are the sons and daughters of refugees from Southeast Asia .</s>
</P>
<P>

<s docid="LA011889-0131" num="27" wdcount="15"> Police, however, said there was as yet no evidence that race played a role .</s>
</P>
<P>

<s docid="LA011889-0131" num="28" wdcount="24"> "Whether he had some feelings against the Southeast Asian community as a whole, we haven't determined that," said Stockton Police Capt. Dennis Perry .</s>
</P>
<P>

<s docid="LA011889-0131" num="29" wdcount="23"> Investigators had not yet determined if any teachers at Cleveland Elementary were there when Purdy was in attendance from 1969 to 1973 .</s>
</P>
<P>

<s docid="LA011889-0131" num="30" wdcount="10"> His record at the school showed "normal behavior," officials said.</s>

<s docid="LA011889-0131" num="31" wdcount="13"> He transferred out in the third grade to a school in Sacramento .</s>
</P>
<P>

<s docid="LA011889-0131" num="32" wdcount="14"> Police investigators last night searched the Lodi motel room where Purdy had been staying.</s>

<s docid="LA011889-0131" num="33" wdcount="16"> He had checked in the day after Christmas, and was paid up through Jan. 23 .</s>
</P>
<P>

<s docid="LA011889-0131" num="34" wdcount="28"> They found more than 100 plastic toy soldiers arrayed about the room, along with toy jeeps and tanks, in what appeared to be a imaginary battle scene .</s>
</P>
<P>

<s docid="LA011889-0131" num="35" wdcount="9"> "What the significance is, I don't know," Perry said.</s>

<s docid="LA011889-0131" num="36" wdcount="10"> "He obviously had a military hang-up of some kind" .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA011889-0131" num="37" wdcount="17"> Photo, Two children arrive with a man at Stockton school this morning where gunman killed five Tuesday.</s>

<s docid="LA011889-0131" num="38" wdcount="2"> Associated Press</s>
</P>
</GRAPHIC>
</DOC>
