<DOC>
<DOCNO>

<s docid="LA012189-0073" num="1" wdcount="1"> LA012189-0073</s>
</DOCNO>
<DOCID>

<s docid="LA012189-0073" num="2" wdcount="1"> 8221</s>
</DOCID>
<DATE>
<P>

<s docid="LA012189-0073" num="3" wdcount="6"> January 21, 1989, Saturday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA012189-0073" num="4" wdcount="8"> Part 1; Page 27; Column 1; Metro Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA012189-0073" num="5" wdcount="2"> 900 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA012189-0073" num="6" wdcount="10"> BUDDHIST MOURNING RITES HELD FOR CHILDREN SLAIN AT STOCKTON SCHOOL</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA012189-0073" num="7" wdcount="9"> By LOUIS SAHAGUN and STEPHEN BRAUN, Times Staff Writers</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA012189-0073" num="8" wdcount="1"> STOCKTON</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA012189-0073" num="9" wdcount="41"> Incense burned and Buddhist monks in saffron-colored robes chanted prayers of mourning Friday as the immigrant families of children slain in this week's schoolyard massacre were joined by scores of other members of Stockton's Asian community in vigils of grief .</s>
</P>
<P>

<s docid="LA012189-0073" num="10" wdcount="53"> City officials readied the city's Civic Auditorium for a Monday memorial ceremony for the families and friends of a Vietnamese student and four Cambodian pupils gunned down in the playground at Cleveland Elementary School Tuesday by armed drifter Patrick Edward Purdy, who killed himself with a single pistol shot to the head .</s>
</P>
<P>

<s docid="LA012189-0073" num="11" wdcount="20"> A separate funeral for 6-year-old Thuy Tran, the Vietnamese student killed in the shooting spree, will be held today .</s>
</P>
<P>

<s docid="LA012189-0073" num="12" wdcount="34"> Vu-Duc Vuong, executive director of the city's Center for Southeast Asian Resettlement, said citizens throughout California will be asked to take part Monday in a five-minute period of silence starting at 11:45 a.m .</s>
</P>
<P>

<s docid="LA012189-0073" num="13" wdcount="11"> "Five minutes for five children who are dead," Vuong said .</s>
</P>
<P>
</P>
<P>

<s docid="LA012189-0073" num="14" wdcount="2"> Conditions Improved</s>
</P>
<P>

<s docid="LA012189-0073" num="15" wdcount="23"> Fourteen of the 29 students injured in the attack remained in hospitals Friday, but in almost all cases, their conditions were reported improved.</s>

<s docid="LA012189-0073" num="16" wdcount="9"> One teacher was also wounded and remains hospitalized .</s>
</P>
<P>

<s docid="LA012189-0073" num="17" wdcount="22"> Buddhist priests led prayers at the homes of three Cambodian families Friday in mourning ceremonies that last three days and three nights.</s>

<s docid="LA012189-0073" num="18" wdcount="24"> More than 100 people gathered at the Village Oak apartments, where the families of two victims, 8-year-old Ram Chun and 6-year-old Sokhim An, live.</s>

<s docid="LA012189-0073" num="19" wdcount="15"> Neighbors provided the five robed monks with incense, rice and money during their vigil .</s>
</P>
<P>

<s docid="LA012189-0073" num="20" wdcount="26"> But a similar vigil at the home of a third victim, Rathanan Or, 9, was marred by a bitter reunion between the dead boy's parents .</s>
</P>
<P>

<s docid="LA012189-0073" num="21" wdcount="39"> Kim Ly, 40, a Cambodian refugee from Ohio who recognized his son's face among televised pictures of children slain in the mass shooting spree, met for the first time since 1979 with family members grieving for his son .</s>
</P>
<P>
</P>
<P>

<s docid="LA012189-0073" num="22" wdcount="2"> Watching News</s>
</P>
<P>

<s docid="LA012189-0073" num="23" wdcount="37"> Ly said he was watching a news report about the massacre Tuesday morning in which five children and the gunman were killed when he spotted the picture of a 9-year-old victim he recognized as his lost son.</s>

<s docid="LA012189-0073" num="24" wdcount="20"> In a telephone call later that day, a Stockton official verified that "my son had been killed at school" .</s>
</P>
<P>

<s docid="LA012189-0073" num="25" wdcount="7"> "I almost passed out," Ly said .</s>
</P>
<P>

<s docid="LA012189-0073" num="26" wdcount="28"> Now remarried with a 2-year-old son, Ly flew alone to Stockton on Thursday, where he was reunited with In Or, 36, Rathanan's mother and Ly's former wife .</s>
</P>
<P>

<s docid="LA012189-0073" num="27" wdcount="10"> Ly insisted that Or knew of his existence in Ohio.</s>

<s docid="LA012189-0073" num="28" wdcount="21"> Or had told reporters after Tuesday's shooting that her husband was reported killed in a firefight in Cambodia a decade ago.</s>

<s docid="LA012189-0073" num="29" wdcount="34"> Or said Friday that she had no idea Ly had survived, and she complained that Ly had not been in touch with her or her children since he arrived in the United States .</s>
</P>
<P>

<s docid="LA012189-0073" num="30" wdcount="16"> "He never introduced himself as the father of my boy until he was dead," Or said.</s>

<s docid="LA012189-0073" num="31" wdcount="13"> "If he loved the kids, why didn't he come to support his child"?</s>
</P>
<P>

<s docid="LA012189-0073" num="32" wdcount="14"> Ly said he had been in touch with his former family by sending money.</s>

<s docid="LA012189-0073" num="33" wdcount="29"> He also said that soon after he had emigrated to Ohio, he learned that his wife and children were living in Stockton and tried unsuccessfully to visit them .</s>
</P>
<P>

<s docid="LA012189-0073" num="34" wdcount="18"> "When I learned they were alive, I flew out here, but she didn't meet me," Ly said .</s>
</P>
<P>

<s docid="LA012189-0073" num="35" wdcount="33"> Ly, who had been a captain in the Cambodian army, said that he became separated from Or, then three months pregnant with Rathanan, when the country was occupied by Khmer Rouge guerrillas .</s>
</P>
<P>

<s docid="LA012189-0073" num="36" wdcount="32"> He said he made his way to Thailand and came to the United States in 1980, settling in Canton, Ohio, where he has worked since as a cook in a German-American club.</s>

<s docid="LA012189-0073" num="37" wdcount="13"> When he first arrived, thinking his family had perished, Ly said he remarried.</s>

<s docid="LA012189-0073" num="38" wdcount="22"> He said that Or has been angry with him since she learned that he was alive and had a new wife .</s>
</P>
<P>

<s docid="LA012189-0073" num="39" wdcount="20"> The families of the five victims are being aided by funds provided by the San Joaquin County Victim/Witness Assistance Program.</s>

<s docid="LA012189-0073" num="40" wdcount="36"> The state-supported agency will provide up to $2,800 for each funeral and up to $46,000 for hospital and counseling expenses for victims and relatives, said Diane Beatrice, a spokeswoman for the county district attorney's office .</s>
</P>
<P>

<s docid="LA012189-0073" num="41" wdcount="29"> Beatrice added that "thousands and thousands of dollars" have been donated to the Cleveland School Memorial Fund, a program set up to help the families of the victims .</s>
</P>
<P>

<s docid="LA012189-0073" num="42" wdcount="10"> Meanwhile, Gov. George Deukmejian, in an unusual letter to Atty.</s>

<s docid="LA012189-0073" num="43" wdcount="24"> Gen John K. Van de Kamp, asked Friday for a complete report on Purdy's criminal record and detailed information about his weapons purchases .</s>
</P>
<P>

<s docid="LA012189-0073" num="44" wdcount="25"> A spokesman for Van de Kamp said the attorney general will cooperate fully with the governor and provide him with whatever information he requests .</s>
</P>
<P>

<s docid="LA012189-0073" num="45" wdcount="45"> Kevin Brett, the governor's press secretary, said in Sacramento that Deukmejian is seeking the information to help him assess various legislative proposals stemming from the shooting, including a proposed ban on the sale of military-style assault weapons, such as the AK-47 that Purdy used .</s>
</P>
<P>

<s docid="LA012189-0073" num="46" wdcount="42"> "The deaths of five children and the injury of 30 others, all victims of a wanton and senseless act by a person who had a criminal record, raises a number of questions," Deukmejian said in his letter to the attorney general .</s>
</P>
<P>

<s docid="LA012189-0073" num="47" wdcount="11"> Purdy was buried Friday in Lodi, a family spokesman said .</s>
</P>
<P>

<s docid="LA012189-0073" num="48" wdcount="9"> Sahagun reported from Stockton and Braun from Los Angeles.</s>

<s docid="LA012189-0073" num="49" wdcount="13"> Staff writer Richard C. Paddock in Sacramento also contributed to the article .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA012189-0073" num="50" wdcount="17"> Photo, Family and friends of slain student, Rathanan Or, 9, gather for Buddhist prayer service at home.</s>

<s docid="LA012189-0073" num="51" wdcount="22"> ROSEMARY KAUL / Los Angeles Times; Photo, Kim Ly, estranged father of Rathanan Or, who recognized son's face in TV news pictures.</s>

<s docid="LA012189-0073" num="52" wdcount="6"> MARSHA TRAEGER / Los Angeles Times</s>
</P>
</GRAPHIC>
<SUBJECT>
<P>

<s docid="LA012189-0073" num="53" wdcount="18"> RELIGIOUS SERVICES; BUDDHISM; MASS MURDERS -- CALIFORNIA; MURDER SUICIDES -- CALIFORNIA; STOCKTON (CA) -- SCHOOLS; PURDY, PATRICK EDWARD</s>
</P>
</SUBJECT>
</DOC>
