<DOC>
<DOCNO>

<s docid="AP890421-0186" num="1" wdcount="1"> AP890421-0186</s>
</DOCNO>
<FILEID>

<s docid="AP890421-0186" num="2" wdcount="2"> AP-NR-04-21-89 2325EST</s>
</FILEID>
<FIRST>

<s docid="AP890421-0186" num="3" wdcount="7"> u a AM-BattleshipStatus 1stLd-Writethru a0741 04-21 0562</s>
</FIRST>
<SECOND>

<s docid="AP890421-0186" num="4" wdcount="5"> AM-Battleship Status, 1st Ld-Writethru, a0741,0574</s>
</SECOND>
<HEAD>

<s docid="AP890421-0186" num="5" wdcount="6"> Iowa Investigators Review Videotape of Disaster</s>
</HEAD>
<HEAD>

<s docid="AP890421-0186" num="6" wdcount="19"> Eds: Leads with 6 grafs to UPDATE with Washington Post reports; picks up 3rd graf: `Meanwhile, NBC .. .</s>
</HEAD>
<HEAD>

<s docid="AP890421-0186" num="7" wdcount="2"> LaserPhotos NK2,3</s>
</HEAD>
<DATELINE>

<s docid="AP890421-0186" num="8" wdcount="3"> NORFOLK, Va. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890421-0186" num="9" wdcount="30"> The damaged battleship USS Iowa steamed home from Puerto Rico on Friday while investigators on board interviewed crewmen and reviewed an amateur videotape of the explosion that killed 47 sailors.</s>

<s docid="AP890421-0186" num="10" wdcount="32"> Ens. Karl Johnson, an Atlantic Fleet spokesman, said the Navy would not release the exact position of the ship, which was expected to reach its home port here about 5:30 p.m. Sunday.</s>

<s docid="AP890421-0186" num="11" wdcount="43"> The Washington Post reported in its Saturday editions that crewmen in the upper chambers of the gun turret were killed by the explosion and fire while sailors working several levels below suffocated when the blast sucked all the oxygen out of the spaces.</s>

<s docid="AP890421-0186" num="12" wdcount="18"> Navy investigators also said the explosion left two fully loaded gun barrels in the turret, the newspaper reported.</s>

<s docid="AP890421-0186" num="13" wdcount="31"> The explosion came after two of the three guns had been loaded and just after the crew had been given permission to load and fire the center gun, the newspaper said.</s>

<s docid="AP890421-0186" num="14" wdcount="27"> After the fire was extinguished, crew men worked quickly to remove the shells and powder from the other two guns before they could explode, the newspaper said.</s>

<s docid="AP890421-0186" num="15" wdcount="35"> Meanwhile, NBC News reported that the exact cause of the blast in one of the ship's three 16-inch gun turrets on Wednesday may never be known because the destruction inside the turret was so complete.</s>

<s docid="AP890421-0186" num="16" wdcount="29"> The Navy released photographs of the firefighting effort, which authorities said required two hours to put out the blaze and cool off the turret before anyone could enter it.</s>

<s docid="AP890421-0186" num="17" wdcount="36"> During the trip home, investigators on board were reviewing a videotape of the turret taken by an Iowa officer who had wanted to record the firing of the big guns when the explosion occurred, said Lt.</s>

<s docid="AP890421-0186" num="18" wdcount="6"> Cmdr. James Cudler, a Pentagon spokesman.</s>

<s docid="AP890421-0186" num="19" wdcount="15"> He said the investigators had not decided whether to release the tape to the public.</s>

<s docid="AP890421-0186" num="20" wdcount="6"> Investigators were also interviewing crew members.</s>

<s docid="AP890421-0186" num="21" wdcount="36"> Maj. Tom Johnston, a spokesman for the Atlantic Fleet in Norfolk, said he had no information on the cause of death of the 47 crewmen.Navy officials have refused to speculate on the cause of the explosion.</s>

<s docid="AP890421-0186" num="22" wdcount="15"> In Norfolk, memorial services for the 47 victims are tentatively set for 9 a.m. Monday.</s>

<s docid="AP890421-0186" num="23" wdcount="6"> President George Bush is to attend.</s>

<s docid="AP890421-0186" num="24" wdcount="25"> Johnson said the ship is steaming under its own power, and repeated the Navy's daily report that the ship is seaworthy and in no danger.</s>

<s docid="AP890421-0186" num="25" wdcount="11"> The 887-foot, 58,000-ton battleship has armor up to 17 inches thick.</s>

<s docid="AP890421-0186" num="26" wdcount="17"> Navy officials have said that the explosion in the No. 2 gun turret damaged only the turret.</s>

<s docid="AP890421-0186" num="27" wdcount="20"> The top members of the Senate Armed Services Committee said Friday the panel will hold hearings on the fiery explosion.</s>

<s docid="AP890421-0186" num="28" wdcount="14"> The explosion occurred during open seas gun practice 300 miles north of Puerto Rico.</s>

<s docid="AP890421-0186" num="29" wdcount="26"> The Pentagon said the blast ripped through the middle gun of the three-gun turret, and that that gun had not been fired prior to the explosion.</s>

<s docid="AP890421-0186" num="30" wdcount="16"> The Pentagon has ordered that no 16-inch gun will be fired until the investigation is complete.</s>

<s docid="AP890421-0186" num="31" wdcount="20"> Ships with those guns _ the battleships Iowa, New Jersey, Missouri and Wisconsin _ were built during World War II.</s>

<s docid="AP890421-0186" num="32" wdcount="12"> Some critics have said the 16-inch guns are outmoded and dangerous .</s>
</TEXT>
</DOC>
