<DOC>
<DOCNO>

<s docid="AP890420-0176" num="1" wdcount="1"> AP890420-0176</s>
</DOCNO>
<FILEID>

<s docid="AP890420-0176" num="2" wdcount="2"> AP-NR-04-20-89 1934EST</s>
</FILEID>
<FIRST>

<s docid="AP890420-0176" num="3" wdcount="5"> u w AM-Battleship-Explosion 4th-writethru a0747getTurkeyFranks''.</s>

<s docid="AP890420-0176" num="4" wdcount="2"> 04-20 1148</s>
</FIRST>
<SECOND>

<s docid="AP890420-0176" num="5" wdcount="3"> AM-Battleship-Explosion, 4th-writethru, a0747,1170</s>
</SECOND>
<HEAD>

<s docid="AP890420-0176" num="6" wdcount="15"> Eds: To update with Bush attending service, adds new graf after 4th previous, The Iowa</s>
</HEAD>
<BYLINE>

<s docid="AP890420-0176" num="7" wdcount="3"> By BRYAN BRUMLEY</s>
</BYLINE>
<BYLINE>

<s docid="AP890420-0176" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890420-0176" num="9" wdcount="2"> WASHINGTON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890420-0176" num="10" wdcount="35"> The bodies of 47 sailors killed in the gun explosion on the Iowa arrived in the United States on Thursday as the Navy tried to figure out what caused the battleship's turret to blow up.</s>

<s docid="AP890420-0176" num="11" wdcount="22"> None of the guns in the no. 2 turret had been fired before the explosion instantly killed the seamen, Navy officials said.</s>

<s docid="AP890420-0176" num="12" wdcount="21"> They discarded a theory that the blast had been sparked by red-hot debris left in the gun's breech by earlier rounds.</s>

<s docid="AP890420-0176" num="13" wdcount="33"> The Navy organized a board of inquiry and placed a moratorium on firing 16-inch guns, found only on the Iowa and its three sister battleships, the New Jersey, the Wisconsin and the Missouri.</s>

<s docid="AP890420-0176" num="14" wdcount="48"> The Iowa was headed back to its home port at Norfolk, Va., while the bodies of the dead were flown to the military mortuary at Dover Air Force Base in Delaware and families of the battleship's 1,600 crewmen waited to learn whether their relatives were among the dead.</s>

<s docid="AP890420-0176" num="15" wdcount="23"> At the White House, chief of staff John Sununu announced President Bush will attend a memorial service Monday for the victims in Norfolk.</s>

<s docid="AP890420-0176" num="16" wdcount="25"> He said the president had heard of the service and told his staff ``if it could be fitted in, he wanted to be there ...</s>

<s docid="AP890420-0176" num="17" wdcount="5"> wants to be a part''.</s>

<s docid="AP890420-0176" num="18" wdcount="23"> The blast occurred Wednesday morning northeast of Puerto Rico as the Iowa took part in firing exercises that were part of naval training.</s>

<s docid="AP890420-0176" num="19" wdcount="34"> A spokesman for the Atlantic Fleet and the ship's former captain both said the explosion in the No. 2 turret could have been triggered by red-hot debris from earlier firings in the three-gun turret.</s>

<s docid="AP890420-0176" num="20" wdcount="23"> But Cmdr. Mark Baker, chief of the Navy's Pentagon press office, said later that none of the turret's three guns had been fired.</s>

<s docid="AP890420-0176" num="21" wdcount="35"> Only four rounds of 22 scheduled to be fired as part of a training exercise had been fired, he said, and all had been from the No. 1 turret, forward of the one that exploded.</s>

<s docid="AP890420-0176" num="22" wdcount="20"> No eyewitnesses survived Wednesday's explosion behind one of the 16-inch guns on the Iowa, one of the largest warships ever.</s>

<s docid="AP890420-0176" num="23" wdcount="56"> Pentagon officials declined to speculate publicly about the exact cause of the disaster, the worst to strike a Navy ship since 1977, but two officers _ Capt. Paul Hanley, a fleet spokesman, and Capt. Larry Seaquist, the ship's former captain _ said a possible explanation was that red-hot debris from a previous round ignited new charges.</s>

<s docid="AP890420-0176" num="24" wdcount="14"> But Seaquist stressed, ``We simply do not know what caused that powder to go''.</s>

<s docid="AP890420-0176" num="25" wdcount="36"> Baker said no guns in the No. 2 turret had been fired and the order had just been given to the No. 2 turret crew to load and prepare the center gun when the explosion occurred.</s>

<s docid="AP890420-0176" num="26" wdcount="26"> ``We have no eyewitnesses to what actually transpired,'' Defense Secretary Dick Cheney told reporters as he headed back to Washington from a NATO meeting in Brussels.</s>

<s docid="AP890420-0176" num="27" wdcount="21"> The Iowa sailed to Roosevelt Roads Navy Base in Puerto Rico to unload the bodies, which were then flown to Delaware.</s>

<s docid="AP890420-0176" num="28" wdcount="19"> Navy investigators boarded the ship as it left for Norfolk, where it is expected to arrive Sunday or Monday.</s>

<s docid="AP890420-0176" num="29" wdcount="19"> Navy Secretary William Ball attended a memorial service at the Delaware base, home of the armed services' largest mortuary.</s>

<s docid="AP890420-0176" num="30" wdcount="12"> The flag-draped coffins were carried off a plane by Navy honor guards.</s>

<s docid="AP890420-0176" num="31" wdcount="19"> Around the United States, Navy officers and chaplains broke the bad news to the dead men's next of kin.</s>

<s docid="AP890420-0176" num="32" wdcount="17"> The job began just before midnight Wednesday, when officials in Norfolk received the list of the dead.</s>

<s docid="AP890420-0176" num="33" wdcount="23"> ``I've done it many times and I'll never get used to it,'' said Cmdr. Doug Palmer, acting chaplain for the Norfolk Navy Base.</s>

<s docid="AP890420-0176" num="34" wdcount="8"> Five men had families in the Norfolk area.</s>

<s docid="AP890420-0176" num="35" wdcount="27"> The commander of the U.S. 2nd Fleet, Adm. Jerome Johnson, who was on board the Iowa, told reporters in Puerto Rico, ``The fire and explosion was instantaneous''.</s>

<s docid="AP890420-0176" num="36" wdcount="27"> Cheney indicated the casualties were all in the swiveling gun house at the top of the turret, rather than the mechanical compartments and ammunition magazines below it.</s>

<s docid="AP890420-0176" num="37" wdcount="16"> Eleven men escaped from powder magazines deep within the ship at the base of the turret.</s>

<s docid="AP890420-0176" num="38" wdcount="14"> A dozen crew members suffered minor injuries fighting the fire caused by the explosion.</s>

<s docid="AP890420-0176" num="39" wdcount="12"> They were treated and returned to duty, said Pentagon spokesman Fred Hoffman.</s>

<s docid="AP890420-0176" num="40" wdcount="37"> At the White House, President Bush brushed aside suggestions that the explosion was due to the age of the Iowa, a World War II leviathan brought out of mothballs during the military buildup of the Reagan administration.</s>

<s docid="AP890420-0176" num="41" wdcount="26"> Asked about the ship's safety, Bush said he wanted to insure that procedures were checked ``to be sure that safety is at the highest point ...</s>

<s docid="AP890420-0176" num="42" wdcount="27"> but I wouldn't jump to the conclusion that because that kind of powder was put into these turrets in that way that makes a useful platform obsolete''.</s>

<s docid="AP890420-0176" num="43" wdcount="17"> Adm. Richard D. Milligan, a former commander of the New Jersey, began the board of inquiry's investigation.</s>

<s docid="AP890420-0176" num="44" wdcount="12"> Hoffman said he could not predict when the investigation would be completed.</s>

<s docid="AP890420-0176" num="45" wdcount="12"> Seaquist told reporters, ``It seems from the reports that those powders exploded''.</s>

<s docid="AP890420-0176" num="46" wdcount="21"> He referred to the six 110-pound sacks of powder rammed into each gun after it is loaded with a 1,900-pound shell.</s>

<s docid="AP890420-0176" num="47" wdcount="20"> Seaquist said a pressurized air system that clears debris from the breech at a gun's rear must be operated manually.</s>

<s docid="AP890420-0176" num="48" wdcount="21"> Each gun has a one-inch diameter tube carrying air under 3,000 pounds of pressure to blow debris from the 62-foot barrel.</s>

<s docid="AP890420-0176" num="49" wdcount="41"> The only officer killed was Lt. j.g. Phillip Edward Buch from Las Cruces, N.M., who would normally be in a small compartment at the rear of the swivelling top of the turret, adjacent to the room in which shells are loaded.</s>

<s docid="AP890420-0176" num="50" wdcount="44"> Naval officers familiar with the Iowa said an explosion can occur if a gun breech is cracked, or from a shell that ``cooks off'' _ ignites prematurely from the heat of the barrel or smoldering debris left in the barrel from the previous round.</s>

<s docid="AP890420-0176" num="51" wdcount="14"> ``The first thing that comes to mind is something like a cook-off,'' said Hanley.</s>

<s docid="AP890420-0176" num="52" wdcount="9"> ``It could have been a bag or a projectile.</s>

<s docid="AP890420-0176" num="53" wdcount="5"> We just don't know yet''.</s>

<s docid="AP890420-0176" num="54" wdcount="31"> None of the four battleships of the Iowa class, which saw service in World War II and the Korean and Vietnam wars, has ever sustained such an explosion, Pentagon officials said.</s>

<s docid="AP890420-0176" num="55" wdcount="41"> Wednesday's explosion brought the worst loss of life for the Navy since a 1977 accident off Spain, in which 49 sailors died when a launch returning them to the USS Guam and the USS Trenton was struck by a Spanish freighter.</s>

<s docid="AP890420-0176" num="56" wdcount="29"> Except for two World War II Japanese battleships and the current Navy aircraft carriers, the 58,000-ton ships of the Iowa class are the largest warships in the world .</s>
</TEXT>
</DOC>
