<DOC>
<DOCNO>

<s docid="AP890423-0090" num="1" wdcount="1"> AP890423-0090</s>
</DOCNO>
<FILEID>

<s docid="AP890423-0090" num="2" wdcount="2"> AP-NR-04-23-89 2320EST</s>
</FILEID>
<FIRST>

<s docid="AP890423-0090" num="3" wdcount="7"> r a AM-Battleship-Explosion 4thLd-Writethru a0742 04-23 0918</s>
</FIRST>
<SECOND>

<s docid="AP890423-0090" num="4" wdcount="6"> AM-Battleship-Explosion, 4th Ld - Writethru, a0742,0939</s>
</SECOND>
<HEAD>

<s docid="AP890423-0090" num="5" wdcount="6"> Iowa Returns Home to Somber Reception</s>
</HEAD>
<HEAD>

<s docid="AP890423-0090" num="6" wdcount="26"> Eds: SUBS 5th graf, `The surviving...,' to clarify that only two of the surviving No. 2 turret crewmen stood atop the turret as ship landed .</s>
</HEAD>
<BYLINE>

<s docid="AP890423-0090" num="7" wdcount="3"> By D.W. PAGE</s>
</BYLINE>
<BYLINE>

<s docid="AP890423-0090" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890423-0090" num="9" wdcount="3"> NORFOLK, Va. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890423-0090" num="10" wdcount="35"> The scarred battleship USS Iowa made a somber return Sunday to its home port, where about 3,000 family members and friends of the crew welcomed loved ones who escaped an explosion that killed 47 sailors.</s>

<s docid="AP890423-0090" num="11" wdcount="34"> Sailors in whites with black arm bands lined the rails as the huge vessel docked at the Norfolk Naval Base's Pier 5 at 5:41 p.m., just one minute later than Navy officials had estimated.</s>

<s docid="AP890423-0090" num="12" wdcount="16"> Twenty minutes later, families started filing aboard the ship, exchanging tearful embraces with the returning sailors.</s>

<s docid="AP890423-0090" num="13" wdcount="17"> ``They wanted to get here on schedule and were anxious to get home,'' said Capt. Steven Karalekas.</s>

<s docid="AP890423-0090" num="14" wdcount="19"> The explosion Wednesday flashed through the Iowa's No. 2 gun turret, which extends six decks down into the ship.</s>

<s docid="AP890423-0090" num="15" wdcount="21"> There were 11 survivors inside the turret, all on the lowest deck loading powder from the ship's magazines, the Navy said.</s>

<s docid="AP890423-0090" num="16" wdcount="35"> Two of the surviving crewmen of No. 2 turret stood on top of the fire-blackened turret as the ship pulled into the pier, with full crews on the ship's two other turrets, the Navy said.</s>

<s docid="AP890423-0090" num="17" wdcount="23"> The No. 2 turret was in the same position as when the explosion occurred, facing right with the left and right guns elevated.</s>

<s docid="AP890423-0090" num="18" wdcount="9"> The center gun, where the blast occurred, was depressed.</s>

<s docid="AP890423-0090" num="19" wdcount="26"> When the 887-foot vessel first appeared there were scattered cheers by those on the dock, but all remained silent as the ship pulled into the pier.</s>

<s docid="AP890423-0090" num="20" wdcount="19"> The somber mood was heightened by the lack of bands, and few waves were exchanged as the ship docked.</s>

<s docid="AP890423-0090" num="21" wdcount="18"> Adm. Powell Carter, commander in chief of the Atlantic Fleet, was on the dock to greet the vessel.</s>

<s docid="AP890423-0090" num="22" wdcount="16"> As it docked, three Marines raised a flag to half-mast at the stern of the ship.</s>

<s docid="AP890423-0090" num="23" wdcount="25"> The Navy kept the news media about 300 yards from the families, and reporters were not allowed to talk with the families or the crewmen.</s>

<s docid="AP890423-0090" num="24" wdcount="20"> The violence and power of the turret explosion was shown in an amateur videotape released by the Navy on Sunday.</s>

<s docid="AP890423-0090" num="25" wdcount="23"> The tape was made by an officer on the bridge of the Iowa who wanted to record the firing of the big guns.</s>

<s docid="AP890423-0090" num="26" wdcount="36"> The detonation, which appears to blast away the gasket-like rubber ``bloomers'' that seal the turret's gun slits, is followed by a jet of intense fire and thick smoke from the front and base of the gunhouse.</s>

<s docid="AP890423-0090" num="27" wdcount="16"> The videotape cut immediately to damage control firefighters spraying heavy streams of water onto the turret.</s>

<s docid="AP890423-0090" num="28" wdcount="15"> Throughout the Norfolk area, churches dedicated prayers Sunday morning to the families of Iowa crewmen.</s>

<s docid="AP890423-0090" num="29" wdcount="27"> ``We have lost 47 of our number in a tragic way,'' said Cmdr. John L. Fitzgerald, a chaplain, in a service at the Norfolk Naval Air Station.</s>

<s docid="AP890423-0090" num="30" wdcount="14"> ``Our faith helps us to handle what science cannot answer, the mystery of death''.</s>

<s docid="AP890423-0090" num="31" wdcount="26"> A red rose, a yellow ribbon with the number 47 on it and a book containing the names of the dead were taken to the altar.</s>

<s docid="AP890423-0090" num="32" wdcount="24"> Fitzgerald said the Iowa tragedy and that of a recently lost Soviet submarine ``put political differences aside and unite the human family as one''.</s>

<s docid="AP890423-0090" num="33" wdcount="19"> On Monday morning, President Bush will lead a memorial service in a base hangar that can accommodate 3,000 people.</s>

<s docid="AP890423-0090" num="34" wdcount="19"> The families of the victims were invited, but Navy officials said they did not know how many would attend.</s>

<s docid="AP890423-0090" num="35" wdcount="11"> None of the victims listed the Norfolk area as their hometown.</s>

<s docid="AP890423-0090" num="36" wdcount="8"> The explosion occurred during exercises off Puerto Rico.</s>

<s docid="AP890423-0090" num="37" wdcount="17"> The Pentagon said it happened before the middle 16-inch gun of the three-gun turret had been fired.</s>

<s docid="AP890423-0090" num="38" wdcount="25"> The guns, the largest on any ship at sea, use six 110-pound bags of black powder to fire a 2,700-pound projectile up to 23 miles.</s>

<s docid="AP890423-0090" num="39" wdcount="20"> The Navy has refused to speculate on the cause of the explosion, which damaged only the inside of the turret.</s>

<s docid="AP890423-0090" num="40" wdcount="39"> But Navy teams who entered the turret immediately after the blast found the No. 2 gun's breech open and undamaged, with the practice projectile that the gun was to have fired still there, The New York Times reported Sunday.</s>

<s docid="AP890423-0090" num="41" wdcount="22"> This indicated the explosion occurred while the powder bags were still being loaded into the gun, the Times said, citing unidentified sources.</s>

<s docid="AP890423-0090" num="42" wdcount="23"> Navy gunnery officers believe the explosion occurred when the bags were being transferred from a powder hoist to the gun, the newspaper said.</s>

<s docid="AP890423-0090" num="43" wdcount="35"> They said flame and hot gases from the blast went down the hoist to the lowest deck; if the transfer of powder to the guns had been complete, the hoist would have been sealed off.</s>

<s docid="AP890423-0090" num="44" wdcount="25"> The Iowa and its sister ships, the battleships Missouri, New Jersey and Wisconsin, were commissioned during World War II and mothballed after the Korean War.</s>

<s docid="AP890423-0090" num="45" wdcount="10"> They were recommissioned by the Reagan administration in the 1980s.</s>

<s docid="AP890423-0090" num="46" wdcount="21"> Defense Secretary Dick Cheney said Sunday that the administration plans to keep all four battleships in the fleet despite the explosion.</s>

<s docid="AP890423-0090" num="47" wdcount="40"> ``They are effective, they were relatively cheap to bring back into the service compared to new ships, they are good cruise missile platforms, so I think they do have a role to play,'' Cheney said on NBC's ``Meet the Press''.</s>

<s docid="AP890423-0090" num="48" wdcount="22"> Critics have charged that the battleship's 16-inch guns are antiquated and dangerous; gunners say they are among the most accurate available .</s>
</TEXT>
</DOC>
