<DOC>
<DOCNO>

<s docid="AP890421-0013" num="1" wdcount="1"> AP890421-0013</s>
</DOCNO>
<FILEID>

<s docid="AP890421-0013" num="2" wdcount="2"> AP-NR-04-21-89 0056EST</s>
</FILEID>
<FIRST>

<s docid="AP890421-0013" num="3" wdcount="6"> r w PM-BattleshipExplosion Bjt 04-21 0714</s>
</FIRST>
<SECOND>

<s docid="AP890421-0013" num="4" wdcount="3"> PM-Battleship Explosion, Bjt,700</s>
</SECOND>
<HEAD>

<s docid="AP890421-0013" num="5" wdcount="6"> Investigators Search Ship While Families Grieve</s>
</HEAD>
<BYLINE>

<s docid="AP890421-0013" num="6" wdcount="3"> By DONNA CASSATA</s>
</BYLINE>
<BYLINE>

<s docid="AP890421-0013" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890421-0013" num="8" wdcount="2"> WASHINGTON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890421-0013" num="9" wdcount="39"> Investigators aboard the USS Iowa searched for clues to the cause of a fiery explosion that claimed the lives of 47 sailors as the damaged battleship headed home and grief-stricken families dealt with the loss of their loved ones.</s>

<s docid="AP890421-0013" num="10" wdcount="43"> Officials refused to speculate publicly on what caused the worst disaster to strike a Navy ship in more than a decade, a blast that ripped through the Iowa's No. 2 gun turret during naval exercises Wednesday in the Atlantic north of Puerto Rico.</s>

<s docid="AP890421-0013" num="11" wdcount="26"> Although naval gunnery experts combed the vessel Thursday, their task was complicated by the absence of survivors from the swiveling gun housing where the explosion occurred.</s>

<s docid="AP890421-0013" num="12" wdcount="17"> Eleven men escaped from powder magazines located deep within the ship at the base of the turret.</s>

<s docid="AP890421-0013" num="13" wdcount="25"> ``We have no eyewitnesses to what actually transpired,'' Defense Secretary Dick Cheney told reporters as he returned to Washington from a NATO meeting in Brussels.</s>

<s docid="AP890421-0013" num="14" wdcount="32"> The Navy imposed a moratorium on firing 16-inch guns found on the Iowa and its three sister battleships, the New Jersey, the Wisconsin and the Missouri, pending an investigation of the disaster.</s>

<s docid="AP890421-0013" num="15" wdcount="33"> Adm. Richard D. Milligan, a former commander of the New Jersey, began the board of inquiry's investigation, and Pentagon spokesman Fred Hoffman said he could not predict when the investigation would be completed.</s>

<s docid="AP890421-0013" num="16" wdcount="38"> As the Iowa headed toward its home port in Norfolk, Va., the flag-draped, metal coffins containing the bodies of the 47 seamen killed arrived at the Dover Air Force Base in Delaware, site of the largest military mortuary.</s>

<s docid="AP890421-0013" num="17" wdcount="13"> Navy honor guards carried the coffins off a camouflaged C-5 Galaxy cargo plane.</s>

<s docid="AP890421-0013" num="18" wdcount="33"> The bodies had been airlifted by helicopter from the Iowa while it was anchored offshore from Roosevelt Roads Naval Station in Puerto Rico, and placed on the cargo plane for the flight home.</s>

<s docid="AP890421-0013" num="19" wdcount="18"> Across the nation, teams of Navy officers and chaplains broke the news to the sailors' next of kin.</s>

<s docid="AP890421-0013" num="20" wdcount="19"> ``It's the greatest tragedy any of us can suffer,'' said Rear Adm. Jimmy Pappas, the base commander in Norfolk.</s>

<s docid="AP890421-0013" num="21" wdcount="19"> ``It's the most difficult thing you have to do'' to tell someone that a loved one has been killed.</s>

<s docid="AP890421-0013" num="22" wdcount="28"> Ernest Hanyecz Sr., of Bordentown, N.J., stayed up all night trying to get information about his 27-year-old son Ernest before learning Thursday that he was among those killed.</s>

<s docid="AP890421-0013" num="23" wdcount="30"> ``As long as they play their war games, there will be more deaths and innocent people will die,'' said Hanyecz, whose son joined the Navy at the age of 17.</s>

<s docid="AP890421-0013" num="24" wdcount="19"> The dead included one officer, Lt. j.g. Phillip Edward Buch, 24, of Las Cruces, N.M., and 46 enlisted men.</s>

<s docid="AP890421-0013" num="25" wdcount="14"> Most victims were single and from 18 to 22 years old, said Navy officials.</s>

<s docid="AP890421-0013" num="26" wdcount="11"> A memorial service will be held Monday on the Norfolk base.</s>

<s docid="AP890421-0013" num="27" wdcount="22"> Adm. Jerome Johnson, the commander of the U.S. 2nd Fleet who was aboard the Iowa, said ``the fire and explosion was instantaneous''.</s>

<s docid="AP890421-0013" num="28" wdcount="10"> Navy officials aboard the Iowa had scheduled firing 22 rounds.</s>

<s docid="AP890421-0013" num="29" wdcount="32"> Four rounds were fired from the No. 1 turret and immediately after the commander had given the order to load and prepare the gun in the No. 2 turret, the explosion occurred.</s>

<s docid="AP890421-0013" num="30" wdcount="24"> Capt. Larry Seaquist, a former captain of the Iowa, told reporters earlier in the day, ``It seems from the reports that those powders exploded''.</s>

<s docid="AP890421-0013" num="31" wdcount="18"> Six 110-pound sacks of powder are rammed into each gun after it is loaded with a 1,900-pound shell.</s>

<s docid="AP890421-0013" num="32" wdcount="31"> Naval officers familiar with the Iowa said an explosion can occur if a gun breech is cracked, but Seaquist stressed, ``we simply do not know what caused that powder to go''.</s>

<s docid="AP890421-0013" num="33" wdcount="31"> None of the four battleships of the Iowa class, which saw service in World War II and the Korean and Vietnam wars, had previously experienced such an explosion, Pentagon officials said.</s>

<s docid="AP890421-0013" num="34" wdcount="41"> Wednesday's explosion brought the worst loss of life for the Navy since a 1977 accident off Spain, in which 49 sailors died when a launch returning them to the USS Guam and the USS Trenton was struck by a Spanish freighter.</s>

<s docid="AP890421-0013" num="35" wdcount="29"> Except for two World War II Japanese battleships and the current Navy aircraft carriers, the 58,000-ton ships of the Iowa class are the largest warships in the world .</s>
</TEXT>
</DOC>
