<DOC>
<DOCNO>

<s docid="AP890425-0013" num="1" wdcount="1"> AP890425-0013</s>
</DOCNO>
<FILEID>

<s docid="AP890425-0013" num="2" wdcount="2"> AP-NR-04-25-89 0144EST</s>
</FILEID>
<FIRST>

<s docid="AP890425-0013" num="3" wdcount="7"> r a AM-BattleshipExplosion 3rdLd-Writethru a0746 04-25 1018</s>
</FIRST>
<SECOND>

<s docid="AP890425-0013" num="4" wdcount="5"> AM-Battleship Explosion, 3rd Ld-Writethru, a0746,1046</s>
</SECOND>
<HEAD>

<s docid="AP890425-0013" num="5" wdcount="6"> President, Ship Captain Honor Iowa's Dead</s>
</HEAD>
<HEAD>

<s docid="AP890425-0013" num="6" wdcount="22"> Eds: INSERTS 1 graf after 24th, ```Nobody in...,' to UPDATE with skipper refusing to say definitely whether turret can be repaired .</s>
</HEAD>
<HEAD>

<s docid="AP890425-0013" num="7" wdcount="4"> LaserPhotos NKX5,6,8,9,10,11,13,15, LaserColor NKX5C,NKX9C</s>
</HEAD>
<BYLINE>

<s docid="AP890425-0013" num="8" wdcount="3"> By D.W. PAGE</s>
</BYLINE>
<BYLINE>

<s docid="AP890425-0013" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890425-0013" num="10" wdcount="3"> NORFOLK, Va. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890425-0013" num="11" wdcount="31"> Thousands of grieving friends and relatives of the fallen 47 crewmen from the battleship USS Iowa gathered quietly Monday and heard President Bush praise their loved ones as ``brothers in eternity''.</s>

<s docid="AP890425-0013" num="12" wdcount="30"> ``We join today in mourning for the 47 who perished, and in fact, for the 11 who survived,'' the president told a packed memorial service at Norfolk Naval Air Station.</s>

<s docid="AP890425-0013" num="13" wdcount="14"> ``They all were, in the words of a poet, `the men behind the guns'.</s>

<s docid="AP890425-0013" num="14" wdcount="12"> ``They came from Hidalgo, Texas; Cleveland, Ohio; Tampa, Florida; Costa Mesa, California.</s>

<s docid="AP890425-0013" num="15" wdcount="22"> They came to the Navy as strangers, served the Navy as shipmates and friends, and left the Navy as brothers in eternity.</s>

<s docid="AP890425-0013" num="16" wdcount="15"> In the finest Navy tradition, they served proudly on a great battleship, the USS Iowa''.</s>

<s docid="AP890425-0013" num="17" wdcount="29"> The president, a World War II Navy pilot, said he was proud to recommission the Iowa in 1984 and said it had earned 11 battle stars in two wars.</s>

<s docid="AP890425-0013" num="18" wdcount="31"> But with the still-unexplained fire and explosion last Wednesday in the battleship's No. 2 gun turret, he said, ``Fate has written a sorrowful chapter in the history of this great ship''.</s>

<s docid="AP890425-0013" num="19" wdcount="34"> The Iowa's commander, Capt. Fred P. Moosally, said the turret's crew was the best gun crew on the ship, and called its chief _ Chief Gunner's Mate Reginald Owen Ziegler of Port Gibson, N.Y.</s>

<s docid="AP890425-0013" num="20" wdcount="5"> _ ``my No. 1 chief''.</s>

<s docid="AP890425-0013" num="21" wdcount="23"> Victims' relatives and hundreds of sailors and officers in dress blues were among the 6,000 people crowded into a hangar for the service.</s>

<s docid="AP890425-0013" num="22" wdcount="21"> A bouquet of red roses was placed in front of the podium; behind were an American flag and the battleship's banners.</s>

<s docid="AP890425-0013" num="23" wdcount="10"> Outside, another 2,000 people listened to the service on loudspeakers.</s>

<s docid="AP890425-0013" num="24" wdcount="33"> As many as 500 Iowa crewmen were unable to attend the service because they were delayed by traffic and were not permitted to enter the hangar because of security measures to protect Bush.</s>

<s docid="AP890425-0013" num="25" wdcount="13"> Many were angry they could not attend, said Machinist's Mate David Finn, 38.</s>

<s docid="AP890425-0013" num="26" wdcount="8"> ``It was very important to them,'' Finn said.</s>

<s docid="AP890425-0013" num="27" wdcount="39"> The service came a day after the World War II-era battleship eased into its home port, its gun barrels scorched and its 1,500 crewmen at the rails in white uniforms and black armbands in memory of their dead shipmates.</s>

<s docid="AP890425-0013" num="28" wdcount="15"> Moosally told the crowd of mourners that he remembered the men of turret No. 2.</s>

<s docid="AP890425-0013" num="29" wdcount="26"> ``I remember their faces as they toiled at their guns, sweating an honest sweat that comes from young men dedicated to a great cause,'' he said.</s>

<s docid="AP890425-0013" num="30" wdcount="29"> ``I remember as they talked among themselves, looking so much like sailors of the past, sharing the exuberance of the times and the dreams of the future,'' he said.</s>

<s docid="AP890425-0013" num="31" wdcount="12"> ``They were the life, the spirit and the soul of our ship.</s>

<s docid="AP890425-0013" num="32" wdcount="8"> ... They made the ultimate sacrifice for us.</s>

<s docid="AP890425-0013" num="33" wdcount="16"> ... The men of Turret Two will be part of the spirit of the Iowa forever''.</s>

<s docid="AP890425-0013" num="34" wdcount="32"> Bush recounted seeing the Iowa off the coast of the Philippines as a naval aviator in World War II, and the great sense of confidence the big ship lent to the fleet.</s>

<s docid="AP890425-0013" num="35" wdcount="18"> Addressing the children of the victims, he said: ``You must never forget that your father was America's pride''.</s>

<s docid="AP890425-0013" num="36" wdcount="25"> At the end of the service, while the Navy Hymn was played, President and Mrs. Bush greeted and consoled the families of the lost men.</s>

<s docid="AP890425-0013" num="37" wdcount="12"> After the 45-minute service, the families attended a private reception with Moosally.</s>

<s docid="AP890425-0013" num="38" wdcount="9"> The Navy said 45 victims' families attended the service.</s>

<s docid="AP890425-0013" num="39" wdcount="20"> At a press briefing following the reception, Moosally praised the hundreds of men who fought the fire for their courage.</s>

<s docid="AP890425-0013" num="40" wdcount="9"> ``God gave birth to 500 heroes,'' the captain said.</s>

<s docid="AP890425-0013" num="41" wdcount="10"> ``Fire on a ship is the most terrifying fear ...</s>

<s docid="AP890425-0013" num="42" wdcount="5"> you have nowhere to run.</s>

<s docid="AP890425-0013" num="43" wdcount="7"> ``Our extensive training paid off,'' he said.</s>

<s docid="AP890425-0013" num="44" wdcount="17"> ``Besides the firefighting crews, we had cooks, engineers, deck seamen, Marines all fighting to save the ship''.</s>

<s docid="AP890425-0013" num="45" wdcount="35"> Moosally said the blast occurred just as he was turning to Vice Adm. Jerome Johnson, commander of the 2nd Fleet, to tell him to watch the No. 2 turret because it contained his best crew.</s>

<s docid="AP890425-0013" num="46" wdcount="7"> ``This was my best turret,'' Moosally said.</s>

<s docid="AP890425-0013" num="47" wdcount="11"> He said turret chief Ziegler ``was the most meticulous of men.</s>

<s docid="AP890425-0013" num="48" wdcount="11"> He was my No. 1 chief of the 84 chiefs aboard.</s>

<s docid="AP890425-0013" num="49" wdcount="12"> ``Nobody in that turret did anything unless they were qualified,'' Moosally said.</s>

<s docid="AP890425-0013" num="50" wdcount="27"> Moosally refused to give a definite answer to reporters' questions about whether the damaged turret could be repaired, saying the battleship could operate without it if necessary.</s>

<s docid="AP890425-0013" num="51" wdcount="20"> All but 11 men in the huge gun turret died almost instantly last Wednesday when the explosion ripped through it.</s>

<s docid="AP890425-0013" num="52" wdcount="14"> At the time, the Iowa was conducting open seas gun exercises off Puerto Rico.</s>

<s docid="AP890425-0013" num="53" wdcount="10"> The Navy said the investigation into the blast is continuing.</s>

<s docid="AP890425-0013" num="54" wdcount="12"> Navy officials have refused to speculate on the cause of the explosion.</s>

<s docid="AP890425-0013" num="55" wdcount="30"> Cmdr. John P. Morse, the Iowa's weapons officer, said the guns were thoroughly inspected the morning of the accident, and Moosally said he had no hesitation about the guns' safety.</s>

<s docid="AP890425-0013" num="56" wdcount="15"> ``I'll be in the turret for the first shot to go off,'' the captain said.</s>

<s docid="AP890425-0013" num="57" wdcount="38"> One of the survivors, Gunner's Mate 3rd Class Kendall L. Truitt, 21, of Tampa, Fla., said that at first the men down in the powder magazine in the lowest level of the turret didn't know anything was wrong.</s>

<s docid="AP890425-0013" num="58" wdcount="14"> ``We were waiting for the gun to fire, and we weren't sure,'' he said.</s>

<s docid="AP890425-0013" num="59" wdcount="26"> When the men discovered that no one was answering the interior turret communications link, Truitt ordered the powder returned to the magazine and the compartment evacuated.</s>

<s docid="AP890425-0013" num="60" wdcount="22"> The sailors found smoke everywhere as they climbed through hatches and up ladders outside the turret toward the sea deck, Truitt recalled.</s>

<s docid="AP890425-0013" num="61" wdcount="27"> ``My first thought was that I'd better get to a lifeboat station, because if the fire got to the magazine things would be bad,'' he said .</s>
</TEXT>
</DOC>
