<DOC>
<DOCNO>

<s docid="AP890422-0035" num="1" wdcount="1"> AP890422-0035</s>
</DOCNO>
<FILEID>

<s docid="AP890422-0035" num="2" wdcount="2"> AP-NR-04-22-89 0551EST</s>
</FILEID>
<FIRST>

<s docid="AP890422-0035" num="3" wdcount="5"> r a PM-BattleshipMemorial 04-22 0578</s>
</FIRST>
<SECOND>

<s docid="AP890422-0035" num="4" wdcount="2"> PM-Battleship Memorial,0596</s>
</SECOND>
<HEAD>

<s docid="AP890422-0035" num="5" wdcount="6"> Hundreds Honor The USS Iowa Dead</s>
</HEAD>
<HEAD>

<s docid="AP890422-0035" num="6" wdcount="2"> LaserPhoto NK1</s>
</HEAD>
<BYLINE>

<s docid="AP890422-0035" num="7" wdcount="3"> By D.W. PAGE</s>
</BYLINE>
<BYLINE>

<s docid="AP890422-0035" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890422-0035" num="9" wdcount="3"> NORFOLK, Va. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890422-0035" num="10" wdcount="29"> Hundreds of people gathered to honor the 47 sailors who died on the USS Iowa as victims of a tragedy that ``reaches into little towns all over the country''.</s>

<s docid="AP890422-0035" num="11" wdcount="36"> ``Words are never sufficient at a time like this to express the feelings that we share,'' Norfolk Mayor Joseph Leafe told the more than 750 people who came to Friday's memorial at the Elizabeth River waterfront.</s>

<s docid="AP890422-0035" num="12" wdcount="15"> The 58,000-ton battleship was steaming toward its home port here and was to arrive Sunday.</s>

<s docid="AP890422-0035" num="13" wdcount="21"> Meanwhile, Navy investigators on board studied an amateur videotape for clues into Wednesday's explosion in the ship's No. 2 gun turret.</s>

<s docid="AP890422-0035" num="14" wdcount="28"> Lt. Cmdr. James Cudler, a Pentagon spokesman, said the explosion occurred as an Iowa officer was making a videotape to record the firing of the ship's big guns.</s>

<s docid="AP890422-0035" num="15" wdcount="13"> Cudler said Navy officials had not decided whether to release the tape publicly.</s>

<s docid="AP890422-0035" num="16" wdcount="42"> Crewmen in the upper chambers of the gun turret were killed by the explosion and fire while sailors working several levels below suffocated when the blast sucked out all the oxygen, according to a report in today's editions of The Washington Post.</s>

<s docid="AP890422-0035" num="17" wdcount="21"> Maj. Tom Johnston, a spokesman for the Atlantic Fleet in Norfolk, said he had no information on the causes of death.</s>

<s docid="AP890422-0035" num="18" wdcount="31"> The explosion came after two of the three guns had been loaded and just after the crew had been given permission to load and fire the center gun, the newspaper said.</s>

<s docid="AP890422-0035" num="19" wdcount="22"> After the fire was extinguished, crewmen worked quickly to remove the shells and powder from the other two guns, the newspaper said.</s>

<s docid="AP890422-0035" num="20" wdcount="24"> NBC News reported Friday that the exact cause of the explosion may never be known because the devastation inside the turret was so complete.</s>

<s docid="AP890422-0035" num="21" wdcount="19"> The top members of the Senate Armed Services Committee said the panel will hold hearings on the fiery explosion.</s>

<s docid="AP890422-0035" num="22" wdcount="20"> The Pentagon has ordered the 16-inch guns on all four World War II-era battleships silenced until the investigation is finished.</s>

<s docid="AP890422-0035" num="23" wdcount="11"> Some critics have said the 16-inch guns are outmoded and dangerous.</s>

<s docid="AP890422-0035" num="24" wdcount="18"> Jim Smith, 63, of Norfolk, said he attended the memorial because he considered the dead men his shipmates.</s>

<s docid="AP890422-0035" num="25" wdcount="9"> ``I served aboard the battleship North Carolina in 1946.</s>

<s docid="AP890422-0035" num="26" wdcount="15"> I know about those big guns .... I know these things can happen,'' he said.</s>

<s docid="AP890422-0035" num="27" wdcount="9"> ``At times like this, everyone seems to pull together.</s>

<s docid="AP890422-0035" num="28" wdcount="4"> We become one family''.</s>

<s docid="AP890422-0035" num="29" wdcount="22"> Joan Taplett, wife of a Navy commander, said she brought her 3-year-old son so he would always remember the men who died.</s>

<s docid="AP890422-0035" num="30" wdcount="4"> ``I'm from South Dakota.</s>

<s docid="AP890422-0035" num="31" wdcount="19"> ... When I heard that one of the men killed was from there, I had to come,'' she said.</s>

<s docid="AP890422-0035" num="32" wdcount="7"> ``I guess I'm here for his parents.</s>

<s docid="AP890422-0035" num="33" wdcount="8"> Something like this touches all of us ...</s>

<s docid="AP890422-0035" num="34" wdcount="11"> It reaches into little towns all over the country,'' she said.</s>

<s docid="AP890422-0035" num="35" wdcount="18"> David L. Hanson, a 23-year-old electrician's mate 3rd class from Bison, S.D., population 457, was among those killed.</s>

<s docid="AP890422-0035" num="36" wdcount="30"> A wreath of 47 yellow carnations was cast into the river, a Norfolk police honor guard gave a 21-gun salute and a Navy bugler played taps at the 15-minute ceremony.</s>

<s docid="AP890422-0035" num="37" wdcount="11"> ``On the USS Iowa, 47 young men died too soon ...</s>

<s docid="AP890422-0035" num="38" wdcount="13"> We will remember, and honor and grieve as a nation,'' Gov. Gerald L.</s>

<s docid="AP890422-0035" num="39" wdcount="2"> Baliles said.</s>

<s docid="AP890422-0035" num="40" wdcount="25"> The Navy is planning a ceremony for the crew and family members Monday morning at Norfolk Naval Base, with President Bush scheduled to attend .</s>
</TEXT>
</DOC>
