<DOC>
<DOCNO>

<s docid="AP890421-0062" num="1" wdcount="1"> AP890421-0062</s>
</DOCNO>
<FILEID>

<s docid="AP890421-0062" num="2" wdcount="2"> AP-NR-04-21-89 0736EST</s>
</FILEID>
<FIRST>

<s docid="AP890421-0062" num="3" wdcount="7"> r a PM-Battleship-Critics 1stLd-Writethru a0423 04-21 0736</s>
</FIRST>
<SECOND>

<s docid="AP890421-0062" num="4" wdcount="6"> PM-Battleship-Critics, 1st Ld - Writethru, a0423,0750</s>
</SECOND>
<HEAD>

<s docid="AP890421-0062" num="5" wdcount="7"> Critics Call Battleship's 16-Inch Guns Outmoded, Dangerous</s>
</HEAD>
<HEAD>

<s docid="AP890421-0062" num="6" wdcount="23"> Eds: SUBS lead to CORRECT miles to 23 sted 20; SUBS grafs 18-19, `It supported...', to DELETE reference to Vietnam and add upgrading.</s>

<s docid="AP890421-0062" num="7" wdcount="6"> Also in Friday AMs report .</s>
</HEAD>
<BYLINE>

<s docid="AP890421-0062" num="8" wdcount="3"> By ROBERT DVORCHAK</s>
</BYLINE>
<BYLINE>

<s docid="AP890421-0062" num="9" wdcount="3"> AP National Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890421-0062" num="10" wdcount="3"> NEW YORK (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890421-0062" num="11" wdcount="33"> The 16-inch guns on the USS Iowa, which can lob a shell the weight of a Volkswagen 23 miles, have an outdated design that is unfit in the nuclear missile age, critics say.</s>

<s docid="AP890421-0062" num="12" wdcount="5"> ``They're old-fashioned and inherently dangerous.</s>

<s docid="AP890421-0062" num="13" wdcount="19"> They all ought to be eliminated,'' retired Rear Adm. Eugene LaRocque of the Center for Defense Information said Thursday.</s>

<s docid="AP890421-0062" num="14" wdcount="21"> ``I don't know what more it takes to get people to recognize this ancient technology is no longer appropriate on warships''.</s>

<s docid="AP890421-0062" num="15" wdcount="34"> But the Navy defended the 16-inch gun, the mightiest in use on any ocean, after an explosion killed 47 sailors Wednesday aboard the battleship Iowa while a turret crew loaded gunpowder for target practice.</s>

<s docid="AP890421-0062" num="16" wdcount="3"> ``This gun ...</s>

<s docid="AP890421-0062" num="17" wdcount="8"> remains the finest naval gun in the world.</s>

<s docid="AP890421-0062" num="18" wdcount="26"> It was the pinnacle of gun design art, and it is still a front-line system,'' said Capt. Larry Seaquist, commander of the Iowa until last May.</s>

<s docid="AP890421-0062" num="19" wdcount="22"> The main criticism is that the big gun requires gunpowder packed in silk bags to fire 16-inch-diameter shells from its 62-foot-long barrel.</s>

<s docid="AP890421-0062" num="20" wdcount="28"> It works like the breech-loaded guns that roared during the Civil War: A shell is placed into a barrel and then charged with gunpowder in a separate package.</s>

<s docid="AP890421-0062" num="21" wdcount="32"> In the Iowa's case, 660 pounds of powder _ six 110-pound bags _ is needed to fire a projectile weighing up to 2,700 pounds at a speed of 2,500 feet per second.</s>

<s docid="AP890421-0062" num="22" wdcount="6"> An electric spark ignites the powder.</s>

<s docid="AP890421-0062" num="23" wdcount="27"> The extremely flammable silk is supposed to burn away during the burst, but some red-hot debris may remain or explosive gases can build up in the barrel.</s>

<s docid="AP890421-0062" num="24" wdcount="33"> Air pressurized to 3,000 pounds per square inch can be blown into the breech to clear away debris to guard against a ``blowback,'' which happens when powder ignites before the breech is closed.</s>

<s docid="AP890421-0062" num="25" wdcount="9"> In newer guns, powder is packed in metal containers.</s>

<s docid="AP890421-0062" num="26" wdcount="12"> Missiles, the backbone of the modern Navy's attack capability, have integrated propellants.</s>

<s docid="AP890421-0062" num="27" wdcount="39"> Capt. James Bush of the Center for Defense Information, a private think tank often critical of Pentagon policy, said the Iowa explosion could have been caused by smoldering debris, a blowback or a mishap in the handling of powder.</s>

<s docid="AP890421-0062" num="28" wdcount="3"> ``It wasn't unexpected.</s>

<s docid="AP890421-0062" num="29" wdcount="4"> It wasn't a surprise.</s>

<s docid="AP890421-0062" num="30" wdcount="4"> This is dangerous technology.</s>

<s docid="AP890421-0062" num="31" wdcount="4"> It's archaic,'' Bush said.</s>

<s docid="AP890421-0062" num="32" wdcount="13"> ``These are the only guns in the Navy that still used bagged powder''.</s>

<s docid="AP890421-0062" num="33" wdcount="21"> The Navy said Thursday that none of the guns in the Iowa turret had been fired before the explosion took place.</s>

<s docid="AP890421-0062" num="34" wdcount="31"> The Navy also on Thursday placed a moratorium on firing the big guns, found only on the Iowa and its three sister battleships, the New Jersey, the Wisconsin and the Missouri.</s>

<s docid="AP890421-0062" num="35" wdcount="19"> In a larger sense, critics say the battleships themselves, once the mainstay of gunboat diplomacy, have outlived their purpose.</s>

<s docid="AP890421-0062" num="36" wdcount="13"> Despite 16-inch-thick armor plating, the battlewagons are vulnerable to submarine and missile attack.</s>

<s docid="AP890421-0062" num="37" wdcount="22"> The 20-mile range of the 16-inch guns is almost worthless in an era when missiles can be fired at much greater distances.</s>

<s docid="AP890421-0062" num="38" wdcount="14"> ``We can do almost anything with a missile and do it better,'' Bush said.</s>

<s docid="AP890421-0062" num="39" wdcount="15"> Battleships reached their heyday in World War I and were intended to fight other ships.</s>

<s docid="AP890421-0062" num="40" wdcount="20"> The Iowa, first launched in 1942, was the first of an entire class of U.S. battlewagons built to conquer Japan.</s>

<s docid="AP890421-0062" num="41" wdcount="30"> It supported Marine amphibious landings and shelled shore targets, but the aircraft carrier emerged as the Navy's top weapon because naval battles were waged without ships ever seeing each other.</s>

<s docid="AP890421-0062" num="42" wdcount="6"> The Iowa also fought off Korea.</s>

<s docid="AP890421-0062" num="43" wdcount="20"> The Iowa and three sister warships were ordered out of mothballs in the Reagan administration's military buildup six years ago.</s>

<s docid="AP890421-0062" num="44" wdcount="12"> They were upgraded with Tomahawk cruise missiles, 20mm guns and Harpoon missiles.</s>

<s docid="AP890421-0062" num="45" wdcount="22"> One of the battleships, the New Jersey, bombarded Syrian and Druze positions in Lebanon as part the U.S. peacekeeping role in 1983.</s>

<s docid="AP890421-0062" num="46" wdcount="19"> But the 16-inch guns often missed their targets, which the Navy blamed on unreliable powder from World War II.</s>

<s docid="AP890421-0062" num="47" wdcount="16"> ``There was no military need to return these ships to active duty,'' said the CDI's LaRocque.</s>

<s docid="AP890421-0062" num="48" wdcount="18"> ``Their only military utility is to bombard Third World countries, and the era of gunboat diplomacy is over.''</s>
</TEXT>
</DOC>
