<DOC>
<DOCNO>

<s docid="AP890424-0026" num="1" wdcount="1"> AP890424-0026</s>
</DOCNO>
<FILEID>

<s docid="AP890424-0026" num="2" wdcount="2"> AP-NR-04-24-89 0129EST</s>
</FILEID>
<FIRST>

<s docid="AP890424-0026" num="3" wdcount="5"> r w PM-BattleshipInvestigation 04-24 0408</s>
</FIRST>
<SECOND>

<s docid="AP890424-0026" num="4" wdcount="2"> PM-Battleship Investigation,400</s>
</SECOND>
<HEAD>

<s docid="AP890424-0026" num="5" wdcount="10"> Iowa Explosion Investigators Will Seek Evidence of Human, Mechanical Error</s>
</HEAD>
<DATELINE>

<s docid="AP890424-0026" num="6" wdcount="2"> WASHINGTON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890424-0026" num="7" wdcount="32"> Navy investigators will be looking at all possibilities of human or mechanical error in their effort to determine what caused the explosion that killed 47 aboard the battleship USS Iowa, officials say.</s>

<s docid="AP890424-0026" num="8" wdcount="17"> It could take months before the probe is completed and the results released publicly, Navy spokesman Lt.</s>

<s docid="AP890424-0026" num="9" wdcount="5"> Cmdr. Alan Dooley said Sunday.</s>

<s docid="AP890424-0026" num="10" wdcount="23"> A seven-member team of investigators boarded the battleship a day after the explosion flashed through the Iowa's No. 2 gun turret on Wednesday.</s>

<s docid="AP890424-0026" num="11" wdcount="32"> ``They're looking at any evidence of human error or mechanical error, or anything technical,'' said Lt. Janet Mescus, a spokeswoman at the Navy's information center at Norfolk, Va., the ship's home port.</s>

<s docid="AP890424-0026" num="12" wdcount="7"> The Iowa returned to Norfolk on Sunday.</s>

<s docid="AP890424-0026" num="13" wdcount="21"> ``They're moving as quickly as they can,'' Lt. Mescus said, but added, ``They want to be thorough and that takes time''.</s>

<s docid="AP890424-0026" num="14" wdcount="13"> Dooley said the investigation would be ``fairly complex'' because there were no witnesses.</s>

<s docid="AP890424-0026" num="15" wdcount="21"> There were 11 survivors inside the turret, all on the lowest deck loading powder from the ship's magazines, the Navy said.</s>

<s docid="AP890424-0026" num="16" wdcount="33"> Dooley said no information would be released until the probe is completed, and the Navy has refused to speculate on the cause of the explosion, which damaged only the inside of the turret.</s>

<s docid="AP890424-0026" num="17" wdcount="40"> But The New York Times reported Sunday that Navy teams who entered the turret immediately after the blast found the No. 2 gun's breech open and undamaged, with the practice projectile that the gun was to have fired still there.</s>

<s docid="AP890424-0026" num="18" wdcount="28"> The Times cited unidentified sources as saying this indicated the explosion occurred while the bags containing 550 pounds of propellant powder were still being loaded into the gun.</s>

<s docid="AP890424-0026" num="19" wdcount="23"> Navy gunnery officers believe the explosion occurred when the bags were being transferred from a powder hoist to the gun, the newspaper said.</s>

<s docid="AP890424-0026" num="20" wdcount="35"> They said flame and hot gases from the blast went down the hoist to the lowest deck; if the transfer of powder to the guns had been complete, the hoist would have been sealed off.</s>

<s docid="AP890424-0026" num="21" wdcount="32"> The Navy on Sunday released an amateur videotape of the explosion, which was made by an officer on the bridge of the Iowa who wanted to record the firing of the guns.</s>

<s docid="AP890424-0026" num="22" wdcount="30"> The investigation team is headed by Rear Adm. Richard D. Milligan, former commanding officer of the battleship USS New Jersey, and it also includes experts on gunnery and weapons .</s>
</TEXT>
</DOC>
