<DOC>
<DOCNO>

<s docid="LA041989-0141" num="1" wdcount="1"> LA041989-0141</s>
</DOCNO>
<DOCID>

<s docid="LA041989-0141" num="2" wdcount="1"> 46451</s>
</DOCID>
<DATE>
<P>

<s docid="LA041989-0141" num="3" wdcount="6"> April 19, 1989, Wednesday, P.M. Final</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA041989-0141" num="4" wdcount="9"> Part A; Page 1; Column 3; Late Final Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA041989-0141" num="5" wdcount="2"> 463 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA041989-0141" num="6" wdcount="6"> BLAST KILLS 47 ON BATTLESHIP IOWA;</s>
</P>
<P>

<s docid="LA041989-0141" num="7" wdcount="9"> EXPLOSION IN GUN TURRET ROCKS VESSEL NEAR PUERTO RICO</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA041989-0141" num="8" wdcount="4"> From Times Wire Services</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA041989-0141" num="9" wdcount="1"> WASHINGTON</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA041989-0141" num="10" wdcount="33"> A fiery explosion in a giant gun turret rocked the refitted battleship Iowa on maneuvers in the Atlantic today, killing at least 47 sailors and injuring an undetermined number, the Pentagon said .</s>
</P>
<P>

<s docid="LA041989-0141" num="11" wdcount="37"> Defense Department spokesman Dan Howard said the explosion may have resulted from the blast of a 110-pound gunpowder bag used to fire shells that weigh more than a ton a distance of up to 23 miles .</s>
</P>
<P>

<s docid="LA041989-0141" num="12" wdcount="11"> The 16-inch guns are the biggest in the Navy arsenal .</s>
</P>
<P>

<s docid="LA041989-0141" num="13" wdcount="12"> "We assume it was a powder bag," Howard said in Brussels .</s>
</P>
<P>

<s docid="LA041989-0141" num="14" wdcount="38"> Another spokesman said at least 47 crewmen were killed in the explosion that ripped through the turret when one of the giant guns was being fired during a training exercise about 330 miles northeast of Puerto Rico .</s>
</P>
<P>
</P>
<P>

<s docid="LA041989-0141" num="15" wdcount="4"> No Danger of Sinking</s>
</P>
<P>

<s docid="LA041989-0141" num="16" wdcount="8"> The crew extinguished the fire that broke out.</s>

<s docid="LA041989-0141" num="17" wdcount="13"> The spokesman said he had no word on the number of injured .</s>
</P>
<P>

<s docid="LA041989-0141" num="18" wdcount="22"> The aircraft carrier Coral Sea steamed to the scene, sending out helicopters to land supplies and medical crews on the ship .</s>
</P>
<P>

<s docid="LA041989-0141" num="19" wdcount="11"> The Iowa headed toward Roosevelt Roads Naval Base in Puerto Rico.</s>

<s docid="LA041989-0141" num="20" wdcount="8"> It was in no danger of sinking .</s>
</P>
<P>

<s docid="LA041989-0141" num="21" wdcount="20"> "We lost fine young lives," President Bush said during a photo session with congressional leaders at the White House .</s>
</P>
<P>

<s docid="LA041989-0141" num="22" wdcount="12"> "It's a great tragedy and a matter of terrible sadness," Bush said.</s>

<s docid="LA041989-0141" num="23" wdcount="16"> He said he wanted to "express my regrets, especially to the families" of the victims .</s>
</P>
<P>
</P>
<P>

<s docid="LA041989-0141" num="24" wdcount="4"> Guns Date From 1943</s>
</P>
<P>

<s docid="LA041989-0141" num="25" wdcount="28"> Defense Secretary Dick Cheney and Joint Chiefs of Staff Chairman Adm. William Crowe were informed of the incident while attending a NATO defense ministers meeting in Brussels .</s>
</P>
<P>

<s docid="LA041989-0141" num="26" wdcount="8"> The Iowa's 16-inch guns are in three turrets.</s>

<s docid="LA041989-0141" num="27" wdcount="10"> The explosion took place in the No. 2 turret .</s>
</P>
<P>

<s docid="LA041989-0141" num="28" wdcount="36"> The guns are originals dating from the ship's first commissioning at the height of World War II in 1943 as a sister ship of the Missouri, aboard which the Japanese signed the war-ending surrender document .</s>
</P>
<P>

<s docid="LA041989-0141" num="29" wdcount="11"> The powder bags are stored below decks in heavily armored magazines.</s>

<s docid="LA041989-0141" num="30" wdcount="19"> Defense officials traveling with Cheney said seawater was pumped into the magazine where the fire and explosion occurred .</s>
</P>
<P>

<s docid="LA041989-0141" num="31" wdcount="34"> Each of the ship's nine guns requires a crew of 60 to 70 to operate it, with 20 to 30 people in the turret and the others below, sending up shells and powder bags.</s>

<s docid="LA041989-0141" num="32" wdcount="9"> The powder bags are loaded behind the shells .</s>
</P>
<P>
</P>
<P>

<s docid="LA041989-0141" num="33" wdcount="2"> Often Refurbished</s>
</P>
<P>

<s docid="LA041989-0141" num="34" wdcount="8"> "It's rather labor-intensive," a Pentagon spokesman said .</s>
</P>
<P>

<s docid="LA041989-0141" num="35" wdcount="24"> The Iowa itself has been refurbished many times since it was commissioned and was most recently put back into service in December, 1982 .</s>
</P>
<P>

<s docid="LA041989-0141" num="36" wdcount="26"> The ship was deployed in the Persian Gulf region between September, 1987, and February, 1988, as a symbol of America's ability to strike deep into Iran.</s>

<s docid="LA041989-0141" num="37" wdcount="9"> It also saw service in the Korean War .</s>
</P>
<P>

<s docid="LA041989-0141" num="38" wdcount="19"> The ship, 58,000 tons fully loaded, sails out of Norfolk, Va., and carries a crew of about 1,600 .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA041989-0141" num="39" wdcount="10"> Photo, Battleship Iowa loads munitions and supplies in Hampton Roads.</s>

<s docid="LA041989-0141" num="40" wdcount="2"> Associated Press</s>
</P>
</GRAPHIC>
<TYPE>
<P>

<s docid="LA041989-0141" num="41" wdcount="1"> Wire</s>
</P>
</TYPE>
</DOC>
