<DOC>
<DOCNO>

<s docid="LA042389-0098" num="1" wdcount="1"> LA042389-0098</s>
</DOCNO>
<DOCID>

<s docid="LA042389-0098" num="2" wdcount="1"> 47781</s>
</DOCID>
<DATE>
<P>

<s docid="LA042389-0098" num="3" wdcount="6"> April 23, 1989, Sunday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA042389-0098" num="4" wdcount="8"> Part 1; Page 4; Column 1; National Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA042389-0098" num="5" wdcount="2"> 358 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA042389-0098" num="6" wdcount="6"> AUTOPSIES OF 12 IOWA VICTIMS COMPLETED</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA042389-0098" num="7" wdcount="4"> From Times Wire Services</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA042389-0098" num="8" wdcount="6"> DOVER AIR FORCE BASE, Del .</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA042389-0098" num="9" wdcount="40"> A dozen of the 47 sailors killed in an explosion aboard the battleship Iowa have undergone pathology exams, and an official said four of them were dressed in full military uniform and sent to their hometowns Saturday for burial .</s>
</P>
<P>

<s docid="LA042389-0098" num="10" wdcount="58"> Air Force spokesman Capt. Walter Thorp said Saturday it will take as long as 10 days to complete the pathology process on the remaining 35 sailors who died when gunpowder exploded in the No. 2 turret of the Iowa on Wednesday, as the World War II-era battleship was conducting an exercise 200 miles northeast of Puerto Rico .</s>
</P>
<P>

<s docid="LA042389-0098" num="11" wdcount="24"> Although autopsies are not conducted at the base as a matter of policy, the Navy requested forensics exams for each of the sailors .</s>
</P>
<P>

<s docid="LA042389-0098" num="12" wdcount="38"> As Navy officials continued their inquiry into the explosion, sailors aboard the Wisconsin, sister ship to the Iowa, opened their ship Saturday in Norfolk, Va., to talk about their pride in battleships and the sense of loss .</s>
</P>
<P>
</P>
<P>

<s docid="LA042389-0098" num="13" wdcount="3"> Sailors Knew Victims</s>
</P>
<P>

<s docid="LA042389-0098" num="14" wdcount="24"> "The one thing on our mind is the tragic loss of many of our ex-shipmates," said Capt. Jerry M. Blesch, commander of the Wisconsin.</s>

<s docid="LA042389-0098" num="15" wdcount="17"> With only four battleships in the Navy, many aboard the Iowa once served on the Wisconsin .</s>
</P>
<P>
</P>
<P>

<s docid="LA042389-0098" num="16" wdcount="3"> 'Face Same Dangers'</s>
</P>
<P>

<s docid="LA042389-0098" num="17" wdcount="25"> "These are all old ships," said Lt. Matt Schatzle, 25, of Gulfport, Miss., who commands the three 16-inch guns of the Wisconsin's turret No. 3.</s>

<s docid="LA042389-0098" num="18" wdcount="21"> "The crews have a connection with all the old sailors who served on the same ships back in World War II.</s>

<s docid="LA042389-0098" num="19" wdcount="14"> . . . They do the same jobs, they face the same dangers" .</s>
</P>
<P>

<s docid="LA042389-0098" num="20" wdcount="34"> Norfolk Naval Base prepared to welcome home the Iowa, which is expected to arrive at the world's largest naval station this afternoon, and local merchants offered free services to families of the victims .</s>
</P>
<P>

<s docid="LA042389-0098" num="21" wdcount="21"> Lt. Cmdr. Alan Dooley said a team of six investigators was aboard the ship, searching for clues to the blast .</s>
</P>
<P>

<s docid="LA042389-0098" num="22" wdcount="49"> He said no cause of death has been announced for any sailors, but the Washington Post reported that seamen in the upper chambers of gun turret No. 2 died instantly in the fiery explosion, whereas those in the lower levels were suffocated as the blast siphoned off their oxygen.</s>

<s docid="LA042389-0098" num="23" wdcount="9"> Dooley refused to comment on the newspaper report .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA042389-0098" num="24" wdcount="18"> Photo, Gunner's Mate 2nd Class Thomas Lowney points out breech of 16-inch gun in turret on battleship Wisconsin.</s>

<s docid="LA042389-0098" num="25" wdcount="12"> Turret is similar to one on sister ship Iowa where explosion occurred.</s>

<s docid="LA042389-0098" num="26" wdcount="2"> Associated Press</s>
</P>
</GRAPHIC>
<TYPE>
<P>

<s docid="LA042389-0098" num="27" wdcount="1"> Wire</s>
</P>
</TYPE>
<SUBJECT>
<P>

<s docid="LA042389-0098" num="28" wdcount="20"> IOWA (SHIP); DISASTER VICTIMS; EXPLOSIONS -- UNITED STATES; SHIP ACCIDENTS -- NAVY (U.S.); SHIP ACCIDENTS -- UNITED STATES; NAVY (U.S).</s>

<s docid="LA042389-0098" num="29" wdcount="7"> -- PERSONNEL; AUTOPSIES; MILITARY SHIPS; MILITARY MANEUVERS</s>
</P>
</SUBJECT>
</DOC>
