<DOC>
<DOCNO>

<s docid="LA042489-0051" num="1" wdcount="1"> LA042489-0051</s>
</DOCNO>
<DOCID>

<s docid="LA042489-0051" num="2" wdcount="1"> 48181</s>
</DOCID>
<DATE>
<P>

<s docid="LA042489-0051" num="3" wdcount="6"> April 24, 1989, Monday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA042489-0051" num="4" wdcount="8"> Part 1; Page 4; Column 1; National Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA042489-0051" num="5" wdcount="2"> 613 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA042489-0051" num="6" wdcount="12"> FAMILY, FRIENDS OF CREW WATCH IN SILENCE AS IOWA RETURNS TO PORT</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA042489-0051" num="7" wdcount="3"> From Associated Press</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA042489-0051" num="8" wdcount="3"> NORFOLK, Va .</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA042489-0051" num="9" wdcount="35"> The scarred battleship Iowa made a somber return Sunday to its home port, where about 3,000 family members and friends of the crew welcomed loved ones who escaped an explosion that killed 47 sailors .</s>
</P>
<P>

<s docid="LA042489-0051" num="10" wdcount="22"> Sailors in whites with black arm bands lined the rails as the huge vessel docked at the Norfolk Naval Base's Pier 5.</s>

<s docid="LA042489-0051" num="11" wdcount="17"> Twenty minutes later, families started filing aboard the ship, exchanging tearful embraces with the returning sailors .</s>
</P>
<P>

<s docid="LA042489-0051" num="12" wdcount="19"> The explosion Wednesday flashed through the Iowa's No. 2 gun turret, which extends six decks down into the ship.</s>

<s docid="LA042489-0051" num="13" wdcount="25"> There were 11 survivors inside the turret, all on the lowest deck where they were loading powder from the ship's magazines, the Navy said .</s>
</P>
<P>
</P>
<P>

<s docid="LA042489-0051" num="14" wdcount="4"> Crewmen Stand on Turret</s>
</P>
<P>

<s docid="LA042489-0051" num="15" wdcount="33"> Two of the surviving crewmen of No. 2 turret stood on top of the fire-blackened turret as the ship pulled into the pier, with full crews on the ship's two other turrets .</s>
</P>
<P>

<s docid="LA042489-0051" num="16" wdcount="26"> When the vessel first appeared there were scattered cheers among those on the dock, but all remained silent as the ship pulled into the pier .</s>
</P>
<P>

<s docid="LA042489-0051" num="17" wdcount="17"> Adm. Powell F. Carter, commander in chief of the Atlantic Fleet, was there to greet the vessel.</s>

<s docid="LA042489-0051" num="18" wdcount="15"> As the ship docked, three Marines raised a flag to half-staff at the stern .</s>
</P>
<P>

<s docid="LA042489-0051" num="19" wdcount="25"> The Navy kept the news media about 300 yards from the families, and reporters were not allowed to talk with the families or crewmen .</s>
</P>
<P>

<s docid="LA042489-0051" num="20" wdcount="20"> The violence and power of the turret explosion was shown in an amateur videotape released by the Navy on Sunday.</s>

<s docid="LA042489-0051" num="21" wdcount="24"> The tape was made by an officer on the bridge of the Iowa who wanted to record the firing of the big guns .</s>
</P>
<P>
</P>
<P>

<s docid="LA042489-0051" num="22" wdcount="4"> Jet of Intense Fire</s>
</P>
<P>

<s docid="LA042489-0051" num="23" wdcount="37"> The detonation, which appears to blast away the gasket-like rubber "bloomers" that seal the turret's gun slits, is followed by a jet of intense fire and thick smoke from the front and base of the gunhouse .</s>
</P>
<P>

<s docid="LA042489-0051" num="24" wdcount="16"> The videotape cut immediately to damage-control firefighters spraying heavy streams of water onto the turret .</s>
</P>
<P>

<s docid="LA042489-0051" num="25" wdcount="15"> Churches throughout the area dedicated prayers Sunday morning to the families of Iowa crewmen .</s>
</P>
<P>

<s docid="LA042489-0051" num="26" wdcount="27"> "We have lost 47 of our number in a tragic way," said Cmdr. John L. Fitzgerald, a chaplain, in a service at the Norfolk Naval Air Station.</s>

<s docid="LA042489-0051" num="27" wdcount="15"> "Our faith helps us to handle what science cannot answer, the mystery of death" .</s>
</P>
<P>

<s docid="LA042489-0051" num="28" wdcount="27"> A red rose, a yellow ribbon with the number 47 on it and a book containing the names of the dead were taken to the altar .</s>
</P>
<P>

<s docid="LA042489-0051" num="29" wdcount="18"> This morning, President Bush will lead a memorial service in a base hangar that can accommodate 3,000 people.</s>

<s docid="LA042489-0051" num="30" wdcount="20"> The families of the victims were invited, but Navy officials said they did not know how many would attend .</s>
</P>
<P>

<s docid="LA042489-0051" num="31" wdcount="8"> The explosion occurred during exercises off Puerto Rico.</s>

<s docid="LA042489-0051" num="32" wdcount="17"> The Pentagon said it happened before the middle 16-inch gun of the three-gun turret had been fired.</s>

<s docid="LA042489-0051" num="33" wdcount="26"> The guns, the largest on any ship at sea, use six 110-pound bags of black powder to fire a 2,700-pound projectile up to 23 miles .</s>
</P>
<P>
</P>
<P>

<s docid="LA042489-0051" num="34" wdcount="3"> Recommissioned by Reagan</s>
</P>
<P>

<s docid="LA042489-0051" num="35" wdcount="24"> The Iowa and its sister ships, the Missouri, New Jersey and Wisconsin, were commissioned during World War II and mothballed after the Korean War.</s>

<s docid="LA042489-0051" num="36" wdcount="9"> They were recommissioned during the Ronald Reagan Administration .</s>
</P>
<P>

<s docid="LA042489-0051" num="37" wdcount="29"> Defense Secretary Dick Cheney said Sunday that he believes the four battleships still "have merit" as weapons in the U.S. arsenal and have a future in the modern Navy.</s>

<s docid="LA042489-0051" num="38" wdcount="31"> On NBC's "Meet the Press," Cheney called the ships "one way to supplement" the usefulness of carrier battle groups "in terms of a show of force and showing the flag" .</s>
</P>
<P>

<s docid="LA042489-0051" num="39" wdcount="5"> "They are effective," he said.</s>

<s docid="LA042489-0051" num="40" wdcount="28"> "They were relatively cheap to bring back into service compared to new ships; they're good cruise missile platforms, so I do think they have a role to play.</s>

<s docid="LA042489-0051" num="41" wdcount="14"> The question is how you do that and how you pay for it" .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA042489-0051" num="42" wdcount="23"> Photo, Iowa returns home -- Sailors line decks of battleship Iowa, where explosion killed 47 last week, as it steams into Norfolk, Va.</s>

<s docid="LA042489-0051" num="43" wdcount="11"> Guns at left are in No. 2 turret, where blast occurred.</s>

<s docid="LA042489-0051" num="44" wdcount="8"> About 3,000 relatives and friends greeted the ship.</s>

<s docid="LA042489-0051" num="45" wdcount="2"> Associated Press</s>
</P>
</GRAPHIC>
<TYPE>
<P>

<s docid="LA042489-0051" num="46" wdcount="1"> Wire</s>
</P>
</TYPE>
<SUBJECT>
<P>

<s docid="LA042489-0051" num="47" wdcount="2"> NAVY (U.S).</s>

<s docid="LA042489-0051" num="48" wdcount="20"> -- PERSONNEL; SHIP ACCIDENTS -- NAVY (U.S.); EXPLOSIONS -- UNITED STATES; FIRES; CASUALTIES; IOWA (SHIP); RELIGIOUS SERVICES; MEMORIALS; BUSH, GEORGE</s>
</P>
</SUBJECT>
</DOC>
