<DOC>
<DOCNO>

<s docid="AP890316-0012" num="1" wdcount="1"> AP890316-0012</s>
</DOCNO>
<FILEID>

<s docid="AP890316-0012" num="2" wdcount="2"> AP-NR-03-16-89 0135EST</s>
</FILEID>
<FIRST>

<s docid="AP890316-0012" num="3" wdcount="5"> r w PM-WalterMears 03-16 0791</s>
</FIRST>
<SECOND>

<s docid="AP890316-0012" num="4" wdcount="2"> PM-Walter Mears,820</s>
</SECOND>
<HEAD>

<s docid="AP890316-0012" num="5" wdcount="9"> A Week Later, Only Ripples Left from Tower Defeat</s>
</HEAD>
<HEAD>

<s docid="AP890316-0012" num="6" wdcount="4"> An AP News Analysis</s>
</HEAD>
<BYLINE>

<s docid="AP890316-0012" num="7" wdcount="4"> By WALTER R. MEARS</s>
</BYLINE>
<BYLINE>

<s docid="AP890316-0012" num="8" wdcount="3"> AP Special Correspondent</s>
</BYLINE>
<DATELINE>

<s docid="AP890316-0012" num="9" wdcount="2"> WASHINGTON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890316-0012" num="10" wdcount="2"> John G.</s>

<s docid="AP890316-0012" num="11" wdcount="8"> Tower has fallen, but the sky has not.</s>

<s docid="AP890316-0012" num="12" wdcount="21"> For all the forecasts of dire results if the Senate blocked Tower's path to the Pentagon, business is proceeding as usual.</s>

<s docid="AP890316-0012" num="13" wdcount="14"> President Bush said the case was closed and accepted Democratic assurances of future cooperation.</s>

<s docid="AP890316-0012" num="14" wdcount="24"> That doesn't undo the resentment among some of Tower's more ardent Republican allies in the Senate and in some corners of the White House.</s>

<s docid="AP890316-0012" num="15" wdcount="17"> Bush lieutenants claimed they had heard what sounded like assurances of support from a dozen Senate Democrats.</s>

<s docid="AP890316-0012" num="16" wdcount="13"> They ended up with only three Democrats in the close-to-party-line vote against Tower.</s>

<s docid="AP890316-0012" num="17" wdcount="19"> Nevertheless, a week after the former Texas senator was denied confirmation as secretary of defens, the waters have closed.</s>

<s docid="AP890316-0012" num="18" wdcount="11"> There will be ripples, and some of them could be wave-sized.</s>

<s docid="AP890316-0012" num="19" wdcount="30"> The good-behavior rules set in the debate over Tower's drinking habits and his lucrative defense consulting business are certain to be invoked as precedents whenever Republicans spot a Democratic target.</s>

<s docid="AP890316-0012" num="20" wdcount="15"> ``We've established what will be known as the Tower standards,'' said Sen. John Warner, R-Va.</s>

<s docid="AP890316-0012" num="21" wdcount="17"> That argument will be used by House Republicans challenging the financial conduct of House Speaker Jim Wright.</s>

<s docid="AP890316-0012" num="22" wdcount="23"> But it will be a debating point, not a turning point, in a Wright controversy that was ordained long before the Tower episode.</s>

<s docid="AP890316-0012" num="23" wdcount="17"> While President Bush was unwavering in his support of Tower, he burned no bridges to congressional Democrats.</s>

<s docid="AP890316-0012" num="24" wdcount="29"> He insisted that Tower was the best man for the job and he spoke out repeatedly for his choice, even after it was clear that the nomination was doomed.</s>

<s docid="AP890316-0012" num="25" wdcount="16"> But he didn't get nasty about it, saying there was no point in escalating the fight.</s>

<s docid="AP890316-0012" num="26" wdcount="10"> ``That's over,'' he said 24 hours after the Tower defeat.</s>

<s docid="AP890316-0012" num="27" wdcount="2"> ``That's history.</s>

<s docid="AP890316-0012" num="28" wdcount="8"> And now we are going to go forward''.</s>

<s docid="AP890316-0012" num="29" wdcount="27"> The 53-47 vote against Tower was a setback to Bush in the sense that it always is a defeat when Congress denies a president something he wants.</s>

<s docid="AP890316-0012" num="30" wdcount="19"> But this denial did not cost Bush a program, or a major campaign pledge, or the support of voters.</s>

<s docid="AP890316-0012" num="31" wdcount="24"> Indeed, it could turn out that the Senate did the president a favor by sending Tower back to Texas instead of to the Pentagon.</s>

<s docid="AP890316-0012" num="32" wdcount="25"> It was a break Bush could not make with a political ally who had been after the Pentagon job since Ronald Reagan was elected president.</s>

<s docid="AP890316-0012" num="33" wdcount="16"> Tower had not been a Reagan man _ he had supported Bush for the 1980 nomination.</s>

<s docid="AP890316-0012" num="34" wdcount="35"> And the Reagan White House went to some lengths to rule the senator out of the job he sought, declaring that the new president would not be nominating any Senate Republican for any Cabinet post.</s>

<s docid="AP890316-0012" num="35" wdcount="29"> After Tower's long wait, Bush displayed his own loyalty, all the way to a losing vote when the standard, somewhat safer course would have been to withdraw the nominee.</s>

<s docid="AP890316-0012" num="36" wdcount="23"> Tower not only shunned withdrawal; he offered conditions that had to be humiliating, if only the Senate would let him have the job.</s>

<s docid="AP890316-0012" num="37" wdcount="11"> Tower promised to quit drinking, taking the pledge on national television.</s>

<s docid="AP890316-0012" num="38" wdcount="14"> And when that didn't work, he offered to become the first-ever probationary Cabinet member.</s>

<s docid="AP890316-0012" num="39" wdcount="30"> Republicans proposed that he get the job for a six-month trial and then return for reconfirmation, a gimmick that would have changed the system and could have haunted the presidency.</s>

<s docid="AP890316-0012" num="40" wdcount="2"> No deal.</s>

<s docid="AP890316-0012" num="41" wdcount="18"> So Tower became the ninth Cabinet nominee ever to be rejected, the first who was a former senator.</s>

<s docid="AP890316-0012" num="42" wdcount="28"> Bush said he had been fighting for the right of a president to appoint his own Cabinet, but he avoided language that would have raised the political stakes.</s>

<s docid="AP890316-0012" num="43" wdcount="5"> Tower did not restrain himself.</s>

<s docid="AP890316-0012" num="44" wdcount="18"> Battling for the job, he said withdrawal would damage Bush and rejection would be ``damning the president's judgment''.</s>

<s docid="AP890316-0012" num="45" wdcount="15"> He said his nomination had been turned into a vehicle for a major presidential defeat.</s>

<s docid="AP890316-0012" num="46" wdcount="38"> Tower's advocates on the Senate floor said grave constitutional issues were at stake, that the authority of the presidency was on the line, that the Senate will come to rue the rules it wrote in the Tower decision.</s>

<s docid="AP890316-0012" num="47" wdcount="16"> But Bush said all along that the outcome, either way, would not hurt on other issues.</s>

<s docid="AP890316-0012" num="48" wdcount="18"> Sen. Sam Nunn, chairman of the Armed Services Committee and the pivotal figure in the Tower defeat, agreed.</s>

<s docid="AP890316-0012" num="49" wdcount="14"> He told his Georgia constituents that the Tower rejection would not hurt Bush's leadership.</s>

<s docid="AP890316-0012" num="50" wdcount="16"> ``In Washington, `triumphs' and `setbacks' are short-lived,'' Nunn said, ``and that's particularly true of the president.''</s>
</TEXT>
<NOTE>

<s docid="AP890316-0012" num="51" wdcount="2"> EDITOR'S NOTE</s>
</NOTE>
<TEXT>

<s docid="AP890316-0012" num="52" wdcount="24"> Walter R. Mears, vice president and columnist for The Associated Press, has reported on Washington and national politics for more than 25 years .</s>
</TEXT>
</DOC>
