<DOC>
<DOCNO>

<s docid="AP890211-0110" num="1" wdcount="1"> AP890211-0110</s>
</DOCNO>
<FILEID>

<s docid="AP890211-0110" num="2" wdcount="2"> AP-NR-02-11-89 1458EST</s>
</FILEID>
<FIRST>

<s docid="AP890211-0110" num="3" wdcount="5"> r w AM-Tower 02-11 0681</s>
</FIRST>
<SECOND>

<s docid="AP890211-0110" num="4" wdcount="1"> AM-Tower,650</s>
</SECOND>
<HEAD>

<s docid="AP890211-0110" num="5" wdcount="8"> Contradictions Cited In Tower Testimony About Defense Firm</s>
</HEAD>
<BYLINE>

<s docid="AP890211-0110" num="6" wdcount="3"> By LEE BYRD</s>
</BYLINE>
<BYLINE>

<s docid="AP890211-0110" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890211-0110" num="8" wdcount="2"> WASHINGTON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890211-0110" num="9" wdcount="29"> Defense Secretary-designate John Tower contradicted an earlier sworn statement when he told the Senate his work for a British firm involved no military matters, according to reports published Saturday.</s>

<s docid="AP890211-0110" num="10" wdcount="17"> Meanwhile, new questions were raised about the thoroughness of the FBI's background investigation of the embattled nominee.</s>

<s docid="AP890211-0110" num="11" wdcount="21"> One newspaper reported that several bizarre accidents, including early-morning car crashes and a hotel fire, apparently were overlooked in the probe.</s>

<s docid="AP890211-0110" num="12" wdcount="44"> The Senate Armed Services Committee has put the nomination of Tower, a former Texas senator and onetime chairman of the committee, on hold while it takes a second look at Tower's personal habits, including his use of alcohol, and his links to defense contractors.</s>

<s docid="AP890211-0110" num="13" wdcount="31"> Tower, who has declined to be interviewed while his nomination is pending, has denied in his Senate testimony any problem with alcohol or any conflicts of interest concerning his business ties.</s>

<s docid="AP890211-0110" num="14" wdcount="22"> A White House spokesman, Stephen Hart, declined on Saturday to comment on the latest reports, saying ``it's (the nomination) before the committee''.</s>

<s docid="AP890211-0110" num="15" wdcount="15"> Tower's designated spokesman, attorney Paul Eggers of Dallas, did not answer a reporter's calls Saturday.</s>

<s docid="AP890211-0110" num="16" wdcount="36"> In written testimony to the Senate panel on Jan. 26, Tower said he could ``recall no actions in connection with any defense activities'' in connection with his work for the U.S. subsidiary of British Aerospace, Inc.</s>

<s docid="AP890211-0110" num="17" wdcount="34"> That statement, according to two publications, The Los Angeles Times and the Legal Times, did not square with information which Tower provided to divorce attorneys working for his second wife in June of 1987.</s>

<s docid="AP890211-0110" num="18" wdcount="47"> In the divorce deposition, Tower said he went to work for British Aerospace eight weeks after resigning as the nation's chief strategic arms negotiator and advised the company on how to sell training jets, fighter planes and missile systems to the Pentagon, the Los Angeles Times reported.</s>

<s docid="AP890211-0110" num="19" wdcount="26"> Tower told the Senate committee he worked chiefly on selling commercial aircraft to U.S. airlines and also advised the firm on trade legislation and currency fluctuations.</s>

<s docid="AP890211-0110" num="20" wdcount="15"> He said he earned $265,000 from the company between June of 1986 and last December.</s>

<s docid="AP890211-0110" num="21" wdcount="36"> The Legal Times said Tower told the divorce attorneys that he was retained by British Aerospace for his advice on how to sell weapons systems to the Pentagon, and that he listed the various weapons involved.</s>

<s docid="AP890211-0110" num="22" wdcount="26"> The deposition was never filed in court because Tower did not contest the divorce, but a copy was obtained by the FBI, the Legal Times said.</s>

<s docid="AP890211-0110" num="23" wdcount="20"> It said its reporters were allowed by attorneys to read it with the understanding that it not be quoted directly.</s>

<s docid="AP890211-0110" num="24" wdcount="29"> The New York Post reported Saturday that the FBI apparently has not bothered to talk to Tower's neighbors, examine certain police records or investigate several car accidents involving Tower.</s>

<s docid="AP890211-0110" num="25" wdcount="42"> The Post, citing syndicated columnist Cody Shearer, said the incidents included an early-morning episode on June 6, 1967, when Tower was trapped in his hotel suite in Dallas by a blaze he accidentally set by dropping a cigarette on an overstuffed armchair.</s>

<s docid="AP890211-0110" num="26" wdcount="21"> When firemen broke into his room to remove him, ``he was reportedly in no condition to free himself,'' the Post said.</s>

<s docid="AP890211-0110" num="27" wdcount="41"> The newspaper also said Tower wrecked his car in two early-morning accidents within weeks of one another in 1970, and, two years earlier, he drove into a bicycle ridden by James Patrick Montoya, son of the late Sen. Joseph Montoya, D-N.M.</s>

<s docid="AP890211-0110" num="28" wdcount="7"> , on his way home from work.</s>

<s docid="AP890211-0110" num="29" wdcount="6"> The youth was not seriously hurt.</s>

<s docid="AP890211-0110" num="30" wdcount="19"> FBI spokesman Bill Carter refused comment on specifics of the Tower investigation, but said ``We will follow any lead''.</s>

<s docid="AP890211-0110" num="31" wdcount="44"> On Friday, Tower authorized the release of a statement that recent hospital tests showed no evidence of alcohol abuse, and Vice President Dan Quayle said, ``I have never seen drinking being a factor in John Tower's life other than a social glass of wine''.</s>

<s docid="AP890211-0110" num="32" wdcount="26"> Eggers, meanwhile, acknowledged that there was ``no question'' that Tower sometimes drank too much in the early 1970s, but he said: ``He is not an alcoholic.</s>

<s docid="AP890211-0110" num="33" wdcount="8"> He's not had a drinking problem for years.''</s>
</TEXT>
</DOC>
