<DOC>
<DOCNO>

<s docid="AP890309-0143" num="1" wdcount="1"> AP890309-0143</s>
</DOCNO>
<FILEID>

<s docid="AP890309-0143" num="2" wdcount="2"> AP-NR-03-09-89 1633EST</s>
</FILEID>
<FIRST>

<s docid="AP890309-0143" num="3" wdcount="7"> b w PM-Tower 11thLd-Writethru a0714-a0715 03-09 0889</s>
</FIRST>
<SECOND>

<s docid="AP890309-0143" num="4" wdcount="4"> PM-Tower, 11th Ld-Writethru, a0714-a0715,850</s>
</SECOND>
<HEAD>

<s docid="AP890309-0143" num="5" wdcount="1"> URGENT</s>
</HEAD>
<HEAD>

<s docid="AP890309-0143" num="6" wdcount="4"> Senate Votes Down Tower</s>
</HEAD>
<HEAD>

<s docid="AP890309-0143" num="7" wdcount="5"> Eds: Adds details, historic background</s>
</HEAD>
<BYLINE>

<s docid="AP890309-0143" num="8" wdcount="4"> By LAWRENCE L. KNUTSON</s>
</BYLINE>
<BYLINE>

<s docid="AP890309-0143" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890309-0143" num="10" wdcount="2"> WASHINGTON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890309-0143" num="11" wdcount="29"> The Democratic-controlled Senate today rejected the nomination of former Texas Sen. John Tower as defense secretary, delivering a major rebuke to President Bush just 49 days into his term.</s>

<s docid="AP890309-0143" num="12" wdcount="26"> The Senate's 53-47 vote came after a bitter and divisive debate focused on Tower's drinking habits, behavior toward women and his business dealings with defense contractors.</s>

<s docid="AP890309-0143" num="13" wdcount="33"> It was only the ninth time in 200 years that the Senate has voted to reject a president's Cabinet choice and the only time it has done so early in a new administration.</s>

<s docid="AP890309-0143" num="14" wdcount="18"> Vice President Dan Quayle presided over the Senate during the roll call, underscoring Bush's commitment to the nominee.</s>

<s docid="AP890309-0143" num="15" wdcount="18"> The Senate galleries were packed and virtually all senators were in their seats as the roll was called.</s>

<s docid="AP890309-0143" num="16" wdcount="18"> ``The nomination of John Tower to be secretary of defense is not confirmed,'' Quayle intoned after the vote.</s>

<s docid="AP890309-0143" num="17" wdcount="25"> Kansas GOP Sen. Nancy Kassebaum provided the biggest surprise of the final hours of debate when she became the sole Republican to declare her opposition.</s>

<s docid="AP890309-0143" num="18" wdcount="21"> She said her ``most serious concerns'' were over Tower's activities as a defense consultant after serving as an arms control negotiator.</s>

<s docid="AP890309-0143" num="19" wdcount="18"> She also expressed doubts that he would pay enough attention to ensuring fairness for women in the military.</s>

<s docid="AP890309-0143" num="20" wdcount="26"> Tower's Republican defenders began to speak of him in the past tense and the nominee also appeared to accept defeat, even before the roll was called.</s>

<s docid="AP890309-0143" num="21" wdcount="26"> ``Just moments ago I took a call from John Tower,'' said Sen. John Warner of Virginia, the senior GOP member of the Senate Armed Services Committee.</s>

<s docid="AP890309-0143" num="22" wdcount="10"> ``His head is high, his voice is strong,'' Warner said.</s>

<s docid="AP890309-0143" num="23" wdcount="19"> ``He asked me to convey thanks _ in his words _ to the troops who rallied to his support''.</s>

<s docid="AP890309-0143" num="24" wdcount="23"> Senate Majority Leader George Mitchell, D-Maine, moved to repair damage caused by the bitter struggle to relations between the Senate and President Bush.</s>

<s docid="AP890309-0143" num="25" wdcount="13"> ``I know what's in my heart and in my mind,'' he told reporters.</s>

<s docid="AP890309-0143" num="26" wdcount="20"> ``I want to directly, clearly and unambiguously say that this doesn't represent an effort to be harmful to the president''.</s>

<s docid="AP890309-0143" num="27" wdcount="35"> Dole agreed to a late-afternoon vote on the nomination after acknowledging the collapse of a last-minute bid to give Tower an extraordinary six-month trial period as defense secretary to prove he could abstain from drinking.</s>

<s docid="AP890309-0143" num="28" wdcount="26"> There was no doubt about the outcome as the Senate went through the motions of debating the nomination through the final hours before the roll call.</s>

<s docid="AP890309-0143" num="29" wdcount="8"> The last few undecided senators declared their positions.</s>

<s docid="AP890309-0143" num="30" wdcount="5"> Sen. John B. Breaux, D-La.</s>

<s docid="AP890309-0143" num="31" wdcount="7"> , said he would vote against Tower.</s>

<s docid="AP890309-0143" num="32" wdcount="5"> Sen. James M. Jeffords, R-Vt.</s>

<s docid="AP890309-0143" num="33" wdcount="7"> , said he would support the nomination.</s>

<s docid="AP890309-0143" num="34" wdcount="19"> Senators from both parties credited Tower's defeat to the decision to oppose him made by Sen. Sam Nunn, D-Ga.</s>

<s docid="AP890309-0143" num="35" wdcount="7"> , chairman of the Armed Services Committee.</s>

<s docid="AP890309-0143" num="36" wdcount="18"> ``When he made his decision all the other Democrats wheeled in behind him,'' said Sen. John Chafee, R-R.I.</s>

<s docid="AP890309-0143" num="37" wdcount="25"> With the prospect of defeat seemingly inevitable, White House press secretary Marlin Fitzwater said, ``If necessary, we'll come up with a (new) candidate very rapidly''.</s>

<s docid="AP890309-0143" num="38" wdcount="36"> Names most frequently mentioned in White House speculation as a replacement for Tower if his nomination failed are Sen. Warner, a former secretary of the Navy; former Defense Secretary Donald Rumsfeld; former Rep. Jack Edwards, R-Ala.</s>

<s docid="AP890309-0143" num="39" wdcount="6"> and national security adviser Brent Scowcroft.</s>

<s docid="AP890309-0143" num="40" wdcount="16"> Scowcroft replied ``No'' when asked this morning if he was in line for the Pentagon job.</s>

<s docid="AP890309-0143" num="41" wdcount="41"> ``It must be clear to all that people like the chief of staff and the national security adviser, any number of congressmen and senators and any number of other outside experts have candidates on the tip of their tongue,'' Fitzwater said.</s>

<s docid="AP890309-0143" num="42" wdcount="8"> ``But the time has not come,'' he added.</s>

<s docid="AP890309-0143" num="43" wdcount="11"> ``The time will come as soon as the vote is completed.</s>

<s docid="AP890309-0143" num="44" wdcount="5"> We will wait until then''.</s>

<s docid="AP890309-0143" num="45" wdcount="23"> The most recent Associated Press survey showed 52 Democrats and one Republican committed to vote against Tower or leaning strongly in that direction.</s>

<s docid="AP890309-0143" num="46" wdcount="14"> It showed 41 Republicans and three Democrats declared for Tower or leaning his way.</s>

<s docid="AP890309-0143" num="47" wdcount="18"> Nevertheless, the White House said it wanted to see the nomination go all the way to a vote.</s>

<s docid="AP890309-0143" num="48" wdcount="17"> Tower, meanwhile, reported for work at the Pentagon where he and his three daughters had coffee together.</s>

<s docid="AP890309-0143" num="49" wdcount="9"> He then continued a review of various administration proposals.</s>

<s docid="AP890309-0143" num="50" wdcount="13"> ``I hope and believe we can work together on important matters,'' Mitchell said.</s>

<s docid="AP890309-0143" num="51" wdcount="13"> ``The tension of this issue will have no long-lasting effect on the relationship.</s>

<s docid="AP890309-0143" num="52" wdcount="18"> I want to say from the bottom of my heart that I hope this will be the case''.</s>

<s docid="AP890309-0143" num="53" wdcount="28"> The already slim chance Tower would be confirmed was dealt a crushing blow on Wednesday as a parade of previously undecided Democratic senators announced they would vote ``no''.</s>

<s docid="AP890309-0143" num="54" wdcount="21"> Only Democrat Lloyd Bentsen of Texas said he would vote ``yes,'' joining just two other Democrats who have made that decision.</s>

<s docid="AP890309-0143" num="55" wdcount="4"> Sens. Charles Robb, D-Va.</s>

<s docid="AP890309-0143" num="56" wdcount="4"> , Joseph Lieberman, D-Conn.</s>

<s docid="AP890309-0143" num="57" wdcount="5"> , J. Bennett Johnston, D-La.</s>

<s docid="AP890309-0143" num="58" wdcount="4"> , Dale Bumpers, D-Ark.</s>

<s docid="AP890309-0143" num="59" wdcount="5"> , and Claiborne Pell, D-R.I.</s>

<s docid="AP890309-0143" num="60" wdcount="8"> , all said they would vote against Tower.</s>

<s docid="AP890309-0143" num="61" wdcount="40"> Johnston said his reading of the FBI report on Tower leaves him with the clear impression that Tower's personality changes when he drinks heavily, leading to ``a recklessness in the social sense'' entirely different from his behavior when sober .</s>
</TEXT>
</DOC>
