<DOC>
<DOCNO>

<s docid="AP890105-0224" num="1" wdcount="1"> AP890105-0224</s>
</DOCNO>
<FILEID>

<s docid="AP890105-0224" num="2" wdcount="2"> AP-NR-01-05-89 2302EST</s>
</FILEID>
<FIRST>

<s docid="AP890105-0224" num="3" wdcount="5"> u a AM-TowerHospitalized 01-05 0229</s>
</FIRST>
<SECOND>

<s docid="AP890105-0224" num="4" wdcount="2"> AM-Tower Hospitalized,0237</s>
</SECOND>
<HEAD>

<s docid="AP890105-0224" num="5" wdcount="4"> Defense Secretary-Designate Tower Hospitalized</s>
</HEAD>
<DATELINE>

<s docid="AP890105-0224" num="6" wdcount="2"> DALLAS (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890105-0224" num="7" wdcount="19"> Retired Sen. John Tower, the defense secretary-designate, underwent surgery Thursday to remove a colon polyp, a hospital spokesman said.</s>

<s docid="AP890105-0224" num="8" wdcount="18"> ``Senator Tower is resting comfortably and is listed in fair condition,'' hospital spokesman Steve Habgood said Thursday night.</s>

<s docid="AP890105-0224" num="9" wdcount="9"> ``The senator is expected to make a full recovery''.</s>

<s docid="AP890105-0224" num="10" wdcount="32"> Tower, 63, a U.S. senator from Texas for 24 years, was admitted to Baylor University Medical Center on Wednesday after undergoing a colonscopy examination last week that revealed the polyp, Habgood said.</s>

<s docid="AP890105-0224" num="11" wdcount="23"> A preliminary biopsy of the polyp showed it was benign, Habgood said, but further results would be announced Friday by Tower's surgeon, Dr.</s>

<s docid="AP890105-0224" num="12" wdcount="4"> R.D. Dignan, of Dallas.</s>

<s docid="AP890105-0224" num="13" wdcount="8"> Thursday's surgery took approximately three hours, Habgood said.</s>

<s docid="AP890105-0224" num="14" wdcount="14"> When Tower underwent the colonscopy examination, a rectal polyp also was discovered and removed.</s>

<s docid="AP890105-0224" num="15" wdcount="16"> Tests of that growth showed it to contain some ``malignant but well differentiated cells,'' Habgood said.</s>

<s docid="AP890105-0224" num="16" wdcount="24"> Further explanation of the first polyp removal would have to come from Tower's surgeon, who was unavailable for comment Thursday night, the spokesman said.</s>

<s docid="AP890105-0224" num="17" wdcount="14"> After leaving the Senate in 1985, Tower went into business as a defense consultant.</s>

<s docid="AP890105-0224" num="18" wdcount="19"> He also served as an arms negotiator for President Reagan and he headed the White House's Iran-Contra investigative panel.</s>

<s docid="AP890105-0224" num="19" wdcount="11"> President-elect Bush designated Tower as his defense secretary on Dec. 16.</s>

<s docid="AP890105-0224" num="20" wdcount="8"> The nomination is subject to Senate approval .</s>
</TEXT>
</DOC>
