<DOC>
<DOCNO>

<s docid="AP890228-0146" num="1" wdcount="1"> AP890228-0146</s>
</DOCNO>
<FILEID>

<s docid="AP890228-0146" num="2" wdcount="2"> AP-NR-02-28-89 1758EST</s>
</FILEID>
<FIRST>

<s docid="AP890228-0146" num="3" wdcount="5"> u w AM-Tower-Combest 02-28 0468</s>
</FIRST>
<SECOND>

<s docid="AP890228-0146" num="4" wdcount="1"> AM-Tower-Combest,440</s>
</SECOND>
<HEAD>

<s docid="AP890228-0146" num="5" wdcount="6"> Congressman Mum on Tower Drinking Reports</s>
</HEAD>
<HEAD>

<s docid="AP890228-0146" num="6" wdcount="3"> With AM-Tower Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP890228-0146" num="7" wdcount="3"> By JENNIFER DIXON</s>
</BYLINE>
<BYLINE>

<s docid="AP890228-0146" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890228-0146" num="9" wdcount="2"> WASHINGTON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890228-0146" num="10" wdcount="44"> Rep. Larry Combest, R-Texas, issued a terse statement Tuesday supporting Defense-Secretary designate John Tower but refused to comment on a published report that he told Senate Armed Services Committee leaders that Tower used to drink up to a bottle of scotch at a sitting.</s>

<s docid="AP890228-0146" num="11" wdcount="42"> An unidentified congressional source told The Washington Post that Combest's statement about Tower's drinking habits in the 1970s came down on Sen. Sam Nunn, the committee chairman, ``like a ton of bricks'' and was a factor in Nunn's opposition to the nomination.</s>

<s docid="AP890228-0146" num="12" wdcount="33"> The newspaper reported that Combest later gave a different story to the FBI, saying that Tower and a group of friends _ not Tower alone _ had frequently consumed a bottle of scotch.</s>

<s docid="AP890228-0146" num="13" wdcount="11"> After meeting with staff and advisers, Combest, who worked for then-Sen.</s>

<s docid="AP890228-0146" num="14" wdcount="12"> Tower in the 1970s, issued a two-sentence statement supporting his fellow Texan.</s>

<s docid="AP890228-0146" num="15" wdcount="24"> ``As a member of Congress, I have tremendous respect and full confidence in the senator and his abilities to lead this country's armed forces.</s>

<s docid="AP890228-0146" num="16" wdcount="15"> In my judgment, John Tower will be a superb secretary of defense,'' the statement said.</s>

<s docid="AP890228-0146" num="17" wdcount="18"> Combest spokesman Rich Adams refused to comment further, and said Combest was not available to speak to reporters.</s>

<s docid="AP890228-0146" num="18" wdcount="29"> The Washington Post reported that Combest described for Nunn and Sen. John W. Warner of Virginia, the ranking Republican on the committee, Tower's heavy drinking bouts in the 1970s.</s>

<s docid="AP890228-0146" num="19" wdcount="30"> A congressional source was quoted as saying that Combest told the senators that Tower would drink as much as a full bottle of scotch two or three times a week.</s>

<s docid="AP890228-0146" num="20" wdcount="28"> Trudi Boyd, Combest's administrative assistant, told the Post that Combest originally went to Nunn and Warner to tell them Tower had ended his previous excessive abuse of alcohol.</s>

<s docid="AP890228-0146" num="21" wdcount="19"> Boyd also told the Post that a ``group of people'' drank the entire bottle of scotch, not Tower alone.</s>

<s docid="AP890228-0146" num="22" wdcount="18"> That was the account Combest gave the FBI following his talk with Nunn and Warner, the newspaper said.</s>

<s docid="AP890228-0146" num="23" wdcount="20"> It said that in that account, Combest said that he had only seen Tower drunk on two or three occasions.</s>

<s docid="AP890228-0146" num="24" wdcount="21"> Tower has acknowledged that he drank excessively in the 1970s, but says he has reduced his intake to wine with dinner.</s>

<s docid="AP890228-0146" num="25" wdcount="16"> On Sunday, he promised to not drink a drop of alcohol if confirmed as defense secretary.</s>

<s docid="AP890228-0146" num="26" wdcount="18"> Combest, 43, worked for Tower for seven years, 1971-1978, as a legislative assistant handling agricultural legislation and policy.</s>

<s docid="AP890228-0146" num="27" wdcount="15"> Tower served in the Senate for 24 years, deciding not to seek re-election in 1984.</s>

<s docid="AP890228-0146" num="28" wdcount="13"> He was chairman of the Senate Armed Services Committee from 1981 through 1984.</s>

<s docid="AP890228-0146" num="29" wdcount="22"> The committee, now controlled by Democrats, voted 11-9 along party lines last Thursday to recommend the full Senate reject Tower's nomination .</s>
</TEXT>
</DOC>
