<DOC>
<DOCNO>

<s docid="LA020489-0035" num="1" wdcount="1"> LA020489-0035</s>
</DOCNO>
<DOCID>

<s docid="LA020489-0035" num="2" wdcount="1"> 14013</s>
</DOCID>
<DATE>
<P>

<s docid="LA020489-0035" num="3" wdcount="6"> February 4, 1989, Saturday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA020489-0035" num="4" wdcount="8"> Part 1; Page 1; Column 3; National Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA020489-0035" num="5" wdcount="2"> 913 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA020489-0035" num="6" wdcount="8"> TOWER PROBED ON NEW CHARGE OF BEING DRUNK</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA020489-0035" num="7" wdcount="7"> By JOHN M. BRODER, Times Staff Writer</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA020489-0035" num="8" wdcount="1"> WASHINGTON</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA020489-0035" num="9" wdcount="45"> In its renewed investigation of defense secretary nominee John Tower, the FBI is checking allegations that Tower was recently involved in an episode of public drunkenness, sources said Friday -- allegations that call into question his insistence that he has no current drinking problem .</s>
</P>
<P>

<s docid="LA020489-0035" num="10" wdcount="17"> Tower testified in confirmation hearings earlier this week that his problems with alcohol are behind him .</s>
</P>
<P>

<s docid="LA020489-0035" num="11" wdcount="42"> But a senior member of the Armed Services Committee, who asked not to be identified, said Friday that the new allegation, if true, suggests that the former Texas senator's drinking problem "may be ongoing" and that his confirmation remains in doubt .</s>
</P>
<P>

<s docid="LA020489-0035" num="12" wdcount="32"> The charge received Wednesday by the committee was very specific, giving the date and place of the alleged incident, and was made by an informant who identified herself, a knowledgeable source said.</s>

<s docid="LA020489-0035" num="13" wdcount="23"> The episode allegedly occurred within the last year at the Monocle, a Capitol Hill restaurant frequented by lawmakers, lobbyists and congressional aides .</s>
</P>
<P>

<s docid="LA020489-0035" num="14" wdcount="42"> Two other allegations under scrutiny by the FBI's special inquiries unit, which is working around the clock this weekend on the Tower matter, involve assertions of another incident of public intoxication and of a recent affair with an unidentified Dallas woman .</s>
</P>
<P>

<s docid="LA020489-0035" num="15" wdcount="20"> If the new charges should be verified by the FBI, Tower's nomination is doomed, an authoritative committee source said .</s>
</P>
<P>

<s docid="LA020489-0035" num="16" wdcount="21"> FBI agents spent two hours at the Monocle Friday, interviewing the owner, the maitre d', bartenders and waiters, The Times learned.</s>

<s docid="LA020489-0035" num="17" wdcount="17"> The agents were told that Tower, when he was in the Senate, "used to drink martinis" .</s>
</P>
<P>
</P>
<P>

<s docid="LA020489-0035" num="18" wdcount="4"> Wine or Tonic Water</s>
</P>
<P>

<s docid="LA020489-0035" num="19" wdcount="32"> But one source said that no one on the staff contradicted Tower's statement that in recent years he has moderated his once-heavy drinking and now drinks only an occasional glass of wine.</s>

<s docid="LA020489-0035" num="20" wdcount="16"> In fact, in recent weeks, the staff told agents, he often has ordered tonic water .</s>
</P>
<P>

<s docid="LA020489-0035" num="21" wdcount="20"> None of the staff could recall any recent incident of improper behavior by Tower at the restaurant, sources said .</s>
</P>
<P>

<s docid="LA020489-0035" num="22" wdcount="19"> On Thursday, the Armed Services Committee had been set to approve the Tower nomination, but Chairman Sam Nunn (D-Ga).</s>

<s docid="LA020489-0035" num="23" wdcount="20"> abruptly canceled the vote because of the new charges, which he referred immediately to FBI Director William S. Sessions .</s>
</P>
<P>

<s docid="LA020489-0035" num="24" wdcount="26"> The bureau already had conducted an extensive background investigation of Tower, a 24-year Senate veteran who headed the Armed Services panel from 1981 to 1985 .</s>
</P>
<P>

<s docid="LA020489-0035" num="25" wdcount="16"> When he nominated Tower, President Bush said he was "totally satisfied" with the FBI check .</s>
</P>
<P>
</P>
<P>

<s docid="LA020489-0035" num="26" wdcount="4"> No Results Until Tuesday</s>
</P>
<P>

<s docid="LA020489-0035" num="27" wdcount="18"> Nunn said he did not expect the latest FBI inquiry to be completed until at least Tuesday .</s>
</P>
<P>

<s docid="LA020489-0035" num="28" wdcount="13"> Tower Friday refused to comment, as he has throughout the confirmation inquiry .</s>
</P>
<P>

<s docid="LA020489-0035" num="29" wdcount="20"> Some Tower supporters complain that committee Democrats are turning the confirmation process into a "circus" for partisan political reasons .</s>
</P>
<P>

<s docid="LA020489-0035" num="30" wdcount="24"> "This is terribly cruel to a man who's just sort of hanging out there," said committee member Malcolm Wallop (R-Wyo.), a Tower supporter .</s>
</P>
<P>

<s docid="LA020489-0035" num="31" wdcount="34"> White House spokesman Marlin Fitzwater said that "our feeling is simply that we believe he will be confirmed but that, whenever there are any new concerns raised, they need to be looked into" .</s>
</P>
<P>

<s docid="LA020489-0035" num="32" wdcount="24"> A senior White House staff member, who asked not to be identified, said Administration officials were getting impatient with the delays in Tower's confirmation.</s>

<s docid="LA020489-0035" num="33" wdcount="12"> "Everybody kind of wants to get our Cabinet in," the aide said.</s>

<s docid="LA020489-0035" num="34" wdcount="11"> "People want to see him confirmed and on the job" .</s>
</P>
<P>

<s docid="LA020489-0035" num="35" wdcount="8"> House Armed Services Committee Chairman Les Aspin (D-Wis).</s>

<s docid="LA020489-0035" num="36" wdcount="15"> said that the controversy has already hobbled Tower's ability to lead the Pentagon effectively .</s>
</P>
<P>

<s docid="LA020489-0035" num="37" wdcount="24"> "This whole nomination process is going to present a problem for him at the Pentagon in terms of running the place," Aspin said .</s>
</P>
<P>
</P>
<P>

<s docid="LA020489-0035" num="38" wdcount="4"> Tower Urged to Withdraw</s>
</P>
<P>

<s docid="LA020489-0035" num="39" wdcount="22"> And two influential defense industry trade magazines on Monday will call for Tower to withdraw from consideration for the Pentagon post .</s>
</P>
<P>

<s docid="LA020489-0035" num="40" wdcount="30"> In an editorial prepared for Monday's issue, Defense News, a trade paper widely read by defense contractors and on Capitol Hill, says: "Withdrawal is necessary because the record of Mr.</s>

<s docid="LA020489-0035" num="41" wdcount="18"> Tower's professional life raises substantive doubt that he can perform with utmost effectiveness . . . " .</s>
</P>
<P>

<s docid="LA020489-0035" num="42" wdcount="34"> Army Times, another prominent defense community publication, says Tower is unsuited for the Defense Department post because of his work as a consultant to defense contractors shortly after leaving government service in 1986 .</s>
</P>
<P>

<s docid="LA020489-0035" num="43" wdcount="21"> It said that "the speed and greed with which Tower spun through the revolving door (between government and industry) is appalling".</s>

<s docid="LA020489-0035" num="44" wdcount="26"> Tower has said that he was paid a total of more than $750,000 by six defense firms in the two years after leaving government service .</s>
</P>
<P>

<s docid="LA020489-0035" num="45" wdcount="26"> Tower's profitable consulting work had raised concerns among a number of members of the Armed Services Committee but did not appear to threaten his nomination .</s>
</P>
<P>
</P>
<P>

<s docid="LA020489-0035" num="46" wdcount="3"> Called Morally Unfit</s>
</P>
<P>

<s docid="LA020489-0035" num="47" wdcount="37"> Tower's personal conduct, however, became an issue in the hearings on Tuesday, when conservative critic Paul Weyrich charged that the former senator was morally unfit for the post because of a history of drinking and womanizing .</s>
</P>
<P>

<s docid="LA020489-0035" num="48" wdcount="28"> After a lengthy closed session in which Tower was allowed to respond to Weyrich's charges, Nunn asked the nominee publicly whether he had a problem with alcohol .</s>
</P>
<P>

<s docid="LA020489-0035" num="49" wdcount="6"> "I have none, senator," Tower replied.</s>

<s docid="LA020489-0035" num="50" wdcount="8"> "I am a man of some discipline" .</s>
</P>
<P>

<s docid="LA020489-0035" num="51" wdcount="18"> Staff writers Ronald J. Ostrow, Robert L. Jackson, Melissa Healy and James Gerstenzang contributed to this story .</s>
</P>
</TEXT>
<SUBJECT>
<P>

<s docid="LA020489-0035" num="52" wdcount="15"> TOWER, JOHN; MORALITY; ALCOHOLISM; POLICE INVESTIGATIONS; CONSULTANTS; DEPARTMENT OF DEFENSE (U.S.); POLITICAL APPOINTMENTS; BUSH, GEORGE</s>
</P>
</SUBJECT>
</DOC>
