<DOC>
<DOCNO>

<s docid="LA021189-0003" num="1" wdcount="1"> LA021189-0003</s>
</DOCNO>
<DOCID>

<s docid="LA021189-0003" num="2" wdcount="1"> 16962</s>
</DOCID>
<DATE>
<P>

<s docid="LA021189-0003" num="3" wdcount="6"> February 11, 1989, Saturday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA021189-0003" num="4" wdcount="8"> Part 1; Page 1; Column 4; National Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA021189-0003" num="5" wdcount="2"> 1209 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA021189-0003" num="6" wdcount="6"> MAJOR TOWER DISCREPANCY FOUND BY PANEL</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA021189-0003" num="7" wdcount="7"> By JOHN M. BRODER and RONALD J.</s>

<s docid="LA021189-0003" num="8" wdcount="4"> OSTROW, Times Staff Writers</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA021189-0003" num="9" wdcount="1"> WASHINGTON</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA021189-0003" num="10" wdcount="35"> The Senate panel weighing John Tower's nomination to be defense secretary has found a substantial discrepancy in Tower's descriptions of his business dealings with a British aircraft and weapons manufacturer, congressional sources said Friday .</s>
</P>
<P>

<s docid="LA021189-0003" num="11" wdcount="24"> Tower testified last week that he had represented British Aerospace Inc. only on civil aviation matters, not as a consultant on military systems .</s>
</P>
<P>

<s docid="LA021189-0003" num="12" wdcount="27"> But, in a divorce deposition, taken in June, 1987, Tower stated that he had given the company advice on "selling certain systems to the Defense Department" .</s>
</P>
<P>

<s docid="LA021189-0003" num="13" wdcount="21"> In the deposition, Tower said he represented the firm on a range of military programs and was paid $8,000 a month.</s>

<s docid="LA021189-0003" num="14" wdcount="12"> Records show that the payments continued from June, 1986, until December, 1988.</s>

<s docid="LA021189-0003" num="15" wdcount="19"> Also, he served on the board of directors of the company, the U.S. subsidiary of British Aerospace PLC .</s>
</P>
<P>
</P>
<P>

<s docid="LA021189-0003" num="16" wdcount="3"> Concerns About Veracity</s>
</P>
<P>

<s docid="LA021189-0003" num="17" wdcount="29"> The discrepancy, sources said, has prompted concerns about the veracity and completeness of Tower's testimony before the Senate Armed Services Committee, the panel hearing testimony on his confirmation .</s>
</P>
<P>

<s docid="LA021189-0003" num="18" wdcount="26"> And it raises the question of whether Tower should have registered as a lobbyist for foreign interests under the Foreign Agents Registration Act, they said .</s>
</P>
<P>

<s docid="LA021189-0003" num="19" wdcount="16"> Tower's relationships with arms makers are central to reservations expressed by some senators about his nomination.</s>

<s docid="LA021189-0003" num="20" wdcount="52"> Lawmakers from both parties have said they are concerned that there would be a continuing appearance of conflict of interest hanging over Tower because of his employment by weapons firms, which brought him at least $760,000 in 2 1/2 years -- not including the more than $200,000 British Aerospace paid him .</s>
</P>
<P>

<s docid="LA021189-0003" num="21" wdcount="23"> In his testimony, Tower has described his lobbying and consulting work for a half-dozen U.S. defense firms that do business with the Pentagon.</s>

<s docid="LA021189-0003" num="22" wdcount="27"> The addition of the British firm to the list would add another -- and the first foreign-based firm -- whose interests could pose a potential conflict .</s>
</P>
<P>

<s docid="LA021189-0003" num="23" wdcount="26"> Sources said the apparent discrepancy in testimony raises the prospect that Tower could be recalled to testify under oath about his work for the firm .</s>
</P>
<P>

<s docid="LA021189-0003" num="24" wdcount="11"> Tower aides said they had no comment on the matter .</s>
</P>
<P>

<s docid="LA021189-0003" num="25" wdcount="22"> A lengthy FBI investigation into Tower's business dealings and his personal behavior has stalled a vote by the committee on his confirmation.</s>

<s docid="LA021189-0003" num="26" wdcount="31"> The FBI is looking into new charges about Tower's alleged drinking, womanizing and receipt of campaign contributions and has said that it cannot complete the inquiry for another 10 days .</s>
</P>
<P>

<s docid="LA021189-0003" num="27" wdcount="38"> The FBI is trying to determine whether Tower, who left the Senate in 1985 after 24 years, received illegal corporate campaign contributions from a military electronics firm that later became part of Unisys Corp., sources said Friday .</s>
</P>
<P>

<s docid="LA021189-0003" num="28" wdcount="20"> The allegation was raised by a witness in the FBI's massive Ill Wind probe into corruption in Pentagon weapons-buying .</s>
</P>
<P>

<s docid="LA021189-0003" num="29" wdcount="42"> Federal investigators have not uncovered any evidence that Tower was aware that his 1984 campaign fund received any illicit contributions from consultants employed by former Unisys executive Charles F. Gardner, said to be a central figure in the Pentagon bribery investigation .</s>
</P>
<P>

<s docid="LA021189-0003" num="30" wdcount="28"> A Unisys spokesman said Friday that the company was conducting an internal inquiry into the matter but had found no evidence of involvement by current corporate employees .</s>
</P>
<P>

<s docid="LA021189-0003" num="31" wdcount="7"> Armed Services Committee Chairman Sam Nunn (D-Ga).</s>

<s docid="LA021189-0003" num="32" wdcount="30"> and other committee members are said to be troubled by these issues and have indicated that they may vote against Tower unless the apparent conflicts and questions are resolved .</s>
</P>
<P>

<s docid="LA021189-0003" num="33" wdcount="27"> The sworn deposition about Tower's business dealings was never filed in court because Tower chose not to contest the divorce from his second wife, Lilla Burt Cummings.</s>

<s docid="LA021189-0003" num="34" wdcount="27"> But the document was obtained by the FBI as part of its background investigation of the nominee and is included in the committee's file on Tower .</s>
</P>
<P>
</P>
<P>

<s docid="LA021189-0003" num="35" wdcount="2"> Tower's Testimony</s>
</P>
<P>

<s docid="LA021189-0003" num="36" wdcount="35"> Tower told the committee in written and oral testimony that he was employed only by the American unit of British Aerospace and that he worked chiefly on selling the company's commercial jets to U.S. airlines.</s>

<s docid="LA021189-0003" num="37" wdcount="19"> He said also that he advised the firm on U.S. trade legislation and gave opinions on currency fluctuations .</s>
</P>
<P>

<s docid="LA021189-0003" num="38" wdcount="36"> Tower told the committee that he could "recall no actions in connection with any defense activities" and did not include his income from British Aerospace among his earnings from consulting work done for defense contractors .</s>
</P>
<P>

<s docid="LA021189-0003" num="39" wdcount="36"> In the divorce papers, however, Tower said that he went to work for British Aerospace Inc. on June 1, 1986, eight weeks after resigning as chief negotiator in the U.S.-Soviet strategic arms reductions talks in Geneva.</s>

<s docid="LA021189-0003" num="40" wdcount="27"> Around the same time, he entered into lucrative consulting arrangements with major defense firms, including Rockwell International Inc., Textron Inc., LTV Corp. and Martin Marietta Corp .</s>
</P>
<P>

<s docid="LA021189-0003" num="41" wdcount="21"> In the deposition, Tower said that Rockwell paid him $120,000 a year but said he was "underutilized" by the firm .</s>
</P>
<P>

<s docid="LA021189-0003" num="42" wdcount="23"> He said he advised British Aerospace on its chances of selling its training jets, fighter planes and missile systems to the Pentagon .</s>
</P>
<P>
</P>
<P>

<s docid="LA021189-0003" num="43" wdcount="3"> Deposition Cites Weapons</s>
</P>
<P>

<s docid="LA021189-0003" num="44" wdcount="38"> Among the British Aerospace products Tower tried to sell to U.S. military officials were the Tornado fighter, the Hawk trainer, the Rapier anti-aircraft missile and the Seawolf short-range air defense missile for ships, according to the deposition .</s>
</P>
<P>

<s docid="LA021189-0003" num="45" wdcount="28"> He said in the document that he had been valuable to the firm because he was "plugged in in this town" and "knows the defense business pretty well".</s>

<s docid="LA021189-0003" num="46" wdcount="11"> He said that his contacts throughout government made him "marketable" .</s>
</P>
<P>

<s docid="LA021189-0003" num="47" wdcount="24"> The complex Foreign Agents Registration Act requires individuals working for or representing foreign entities in the United States to register with the Justice Department.</s>

<s docid="LA021189-0003" num="48" wdcount="9"> No registration by Tower is on file, officials said.</s>

<s docid="LA021189-0003" num="49" wdcount="3"> In related developments:</s>
</P>
<P>

<s docid="LA021189-0003" num="50" wdcount="29"> -- Vice President Dan Quayle, talking to reporters on a flight to Florida, said that he had known Tower for eight years and "I have never seen him inebriated.</s>

<s docid="LA021189-0003" num="51" wdcount="19"> I have never seen drinking be a factor in John Tower's life, other than a social glass of wine.</s>

<s docid="LA021189-0003" num="52" wdcount="40"> . . . Those of us who know him, worked with him, can attest to the fact that he has not had this problem, it did not affect him when he was chairman of the Senate Armed Services Committee" .</s>
</P>
<P>

<s docid="LA021189-0003" num="53" wdcount="24"> When asked whether womanizing is a relevant topic for inquiry, he replied: "You have to look at the qualifications of the secretary of defense.</s>

<s docid="LA021189-0003" num="54" wdcount="18"> Whether he will be a capable secretary of defense and do the job of being secretary of defense.</s>

<s docid="LA021189-0003" num="55" wdcount="6"> Let's focus on the qualifications" .</s>
</P>
<P>

<s docid="LA021189-0003" num="56" wdcount="23"> -- Tower's doctor said Friday that he has no evidence to indicate that the former Texas senator suffered any medical symptoms of alcoholism.</s>

<s docid="LA021189-0003" num="57" wdcount="2"> Dr. R.</s>

<s docid="LA021189-0003" num="58" wdcount="37"> D. Dignan, who performed surgery to remove a polyp from Tower's colon on Jan. 5, said that after the operation he advised Tower to limit his drinking to one or two glasses of wine with dinner .</s>
</P>
<P>

<s docid="LA021189-0003" num="59" wdcount="30"> -- A longtime Bush political adviser said that Bush "knew what he was doing" when he named Tower to the post and would not withdraw the nomination, despite the controversy.</s>

<s docid="LA021189-0003" num="60" wdcount="19"> As for Tower, this adviser said: "He's one tough little s.o.b. and he's not going to back off" .</s>
</P>
<P>

<s docid="LA021189-0003" num="61" wdcount="14"> Staff writers Jack Nelson, Melissa Healy and James Gerstenzang contributed to this story .</s>
</P>
</TEXT>
<SUBJECT>
<P>

<s docid="LA021189-0003" num="62" wdcount="21"> TOWER, JOHN; POLITICAL APPOINTMENTS; BUSH, GEORGE; CONFLICT OF INTEREST; LOBBYING; DEFENSE INDUSTRY -- UNITED STATES; DEPARTMENT OF DEFENSE (U.S) -- CONTRACTS</s>
</P>
</SUBJECT>
</DOC>
