<DOC>
<DOCNO>

<s docid="LA020189-0050" num="1" wdcount="1"> LA020189-0050</s>
</DOCNO>
<DOCID>

<s docid="LA020189-0050" num="2" wdcount="1"> 12632</s>
</DOCID>
<DATE>
<P>

<s docid="LA020189-0050" num="3" wdcount="6"> February 1, 1989, Wednesday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA020189-0050" num="4" wdcount="8"> Part 1; Page 1; Column 3; National Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA020189-0050" num="5" wdcount="2"> 811 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA020189-0050" num="6" wdcount="6"> TOWER'S 'MORAL CHARACTER' HIT BY CONSERVATIVE</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA020189-0050" num="7" wdcount="6"> By MELISSA HEALY, Times Staff Writer</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA020189-0050" num="8" wdcount="1"> WASHINGTON</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA020189-0050" num="9" wdcount="38"> In the first eruption of controversy at a confirmation hearing for a Bush Administration Cabinet nominee, a prominent conservative told a Senate panel Tuesday that John Tower may lack the "moral character" to be secretary of defense .</s>
</P>
<P>

<s docid="LA020189-0050" num="10" wdcount="41"> "Over the course of many years, I have encountered the nominee in a condition -- lack of sobriety -- as well as with women to whom he was not married," conservative activist Paul M. Weyrich told the Senate Armed Services Committee.</s>

<s docid="LA020189-0050" num="11" wdcount="16"> "I encountered it frequently enough to the point where it made an impression," he added .</s>
</P>
<P>

<s docid="LA020189-0050" num="12" wdcount="21"> Criticism from Weyrich and other witnesses prompted some committee members to temper the panel's earlier praise for the former Texas senator.</s>

<s docid="LA020189-0050" num="13" wdcount="28"> But several members conceded that, while their former colleague may not be the ideal candidate for the Pentagon's top job, he probably will win Senate approval anyway .</s>
</P>
<P>

<s docid="LA020189-0050" num="14" wdcount="27"> "We've had a surplus of rumors concerning the nominee, and a shortage of witnesses with personal testimony and personal knowledge," said committee Chairman Sam Nunn (D-Ga.) .</s>
</P>
<P>

<s docid="LA020189-0050" num="15" wdcount="27"> Weyrich, president of the conservative Free Congress Foundation, testified that Tower's behavior makes him unfit to lead the Pentagon into an era of belt-tightening and management reform.</s>

<s docid="LA020189-0050" num="16" wdcount="36"> In an extraordinary challenge to Tower's nomination, Weyrich also suggested that Tower's moral shortcomings could make him vulnerable to attempts by foreign governments "to bring pressure on the United States government and on him personally .</s>
</P>
<P>

<s docid="LA020189-0050" num="17" wdcount="26"> "It is unrealistic to expect moral behavior in matters of public trust from someone who does not exhibit such behavior in his personal life," Weyrich said.</s>

<s docid="LA020189-0050" num="18" wdcount="6"> "Private morals have public effects" .</s>
</P>
<P>

<s docid="LA020189-0050" num="19" wdcount="26"> Tower, 63 and twice-divorced, served 24 years in the Senate from Texas, including a tenure as chairman of the Armed Services Committee from 1981 to 1984.</s>

<s docid="LA020189-0050" num="20" wdcount="33"> He has been dogged by reports that he is a hard-drinker and a womanizer and that his hawkish views on defense do not square with the budgetary austerity that the Pentagon faces .</s>
</P>
<P>

<s docid="LA020189-0050" num="21" wdcount="26"> In announcing Tower as his choice for the post on Dec. 16, President Bush called the talk "a lot of rumors that proved to be groundless".</s>

<s docid="LA020189-0050" num="22" wdcount="21"> Saying that "Nixon went to China," Bush added that Tower's record of support for Pentagon spending hikes could be overturned .</s>
</P>
<P>

<s docid="LA020189-0050" num="23" wdcount="30"> But Weyrich's attack raised anew the issue of Tower's fitness for the job, after two days of testimony last week in which Tower won broad praise from committee members .</s>
</P>
<P>
</P>
<P>

<s docid="LA020189-0050" num="24" wdcount="3"> Ties to Contractors</s>
</P>
<P>

<s docid="LA020189-0050" num="25" wdcount="27"> Fulbright Institute scholar William C. Jackson Jr. and William G. Phillips, president of the Washington-based National Council for Industrial Defense, joined Weyrich Tuesday in opposing Tower's nomination.</s>

<s docid="LA020189-0050" num="26" wdcount="41"> Phillips echoed Jackson's complaint that Tower's lucrative ties to defense contractors and past support for big defense budgets raise "serious doubts that John Tower is the best man for the job . . . at this time in our history" .</s>
</P>
<P>

<s docid="LA020189-0050" num="27" wdcount="8"> A leading committee Democrat acknowledged this point .</s>
</P>
<P>

<s docid="LA020189-0050" num="28" wdcount="38"> "I . . . wondered why the President of the United States chose John Tower for this job, given the emphasis that he has placed on ethics and the appearance of wrongdoing," said Nebraska Sen. James J. Exon.</s>

<s docid="LA020189-0050" num="29" wdcount="11"> "But the facts of the matter are that he has" .</s>
</P>
<P>

<s docid="LA020189-0050" num="30" wdcount="41"> Sen. John W. Warner (R-Va.), in clarifying the grounds on which Senate committees may assess presidential nominees, told witnesses that "it is not a function of the Senate to say that this individual, this nominee, is the best man qualified" .</s>
</P>
<P>

<s docid="LA020189-0050" num="31" wdcount="33"> Weyrich also told the committee that President Bush's transition team "received hundreds of letters" opposing Tower's nomination, some of which "contain specific allegations of moral impropriety on the part of Mr. Tower" .</s>
</P>
<P>

<s docid="LA020189-0050" num="32" wdcount="26"> In a closed session of the committee, Weyrich was unable to add to his own observations with more than hearsay, according to Sen. Malcolm Wallop (R-Wyo.).</s>

<s docid="LA020189-0050" num="33" wdcount="18"> Weyrich also acknowledged that he had no personal knowledge of the existence or content of the letters .</s>
</P>
<P>

<s docid="LA020189-0050" num="34" wdcount="45"> But the allegation, reviewed in advance by the committee, prompted Nunn and Warner, the panel's ranking minority member, to write White House counsel C. Boyden Gray asking whether the allegations were investigated by the FBI and addressed in the bureau's report to the committee .</s>
</P>
<P>

<s docid="LA020189-0050" num="35" wdcount="36"> Wallop, a Tower supporter and a leading Senate conservative, termed it "troublesome" that "innuendoes have been made, the insinuations are on the table, but the cameras do not record the fact that they are unsustainable" .</s>
</P>
<P>

<s docid="LA020189-0050" num="36" wdcount="25"> In open testimony, Weyrich also reflected widespread concerns among conservative activists that Tower is not committed to the Pentagon's "Star Wars" missile defense program .</s>
</P>
<P>

<s docid="LA020189-0050" num="37" wdcount="12"> "He considers SDI (the Strategic Defense Initiative) a bargaining chip," Weyrich said.</s>

<s docid="LA020189-0050" num="38" wdcount="3"> "We don't" .</s>
</P>
<P>

<s docid="LA020189-0050" num="39" wdcount="27"> The panel hopes to complete its deliberations by the end of this week, Nunn said, and expects to meet once more today to consider Tower's nomination .</s>
</P>
</TEXT>
<SUBJECT>
<P>

<s docid="LA020189-0050" num="40" wdcount="9"> TOWER, JOHN; POLITICAL APPOINTMENTS; BUSH, GEORGE; WEYRICH, PAUL M</s>
</P>
</SUBJECT>
</DOC>
