<DOC>
<DOCNO>

<s docid="SJMN91-06097121" num="1" wdcount="1"> SJMN91-06097121</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06097121" num="2" wdcount="1"> 06097121</s>
</ACCESS>
<CAPTION>

<s docid="SJMN91-06097121" num="3" wdcount="25"> Photos (2); PHOTO: Associated Press; Martha Kirkendall, executive assistant to former Sen. John Tower, collects her emotions Friday at an interview in Tower's Dallas office.</s>

<s docid="SJMN91-06097121" num="4" wdcount="16"> PHOTO: David Woo -- Knight-Ridder News Service; Former Sen. John Tower and his daughter Marian. (Color)</s>
</CAPTION>
<DESCRIPT>

<s docid="SJMN91-06097121" num="5" wdcount="5"> PAST; CONGRESS; TEXAS; OFFICIAL; ......</s>

<s docid="SJMN91-06097121" num="6" wdcount="5"> FAMILY; DEATH; AVIATION; ACCIDENT; GEORGIA</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06097121" num="7" wdcount="28"> Former Sen. John Tower of Texas and his daughter were among 23 people killed Friday when the twin-engine commuter plane they were aboard crashed while trying to land.</s>

<s docid="SJMN91-06097121" num="8" wdcount="31"> Astronaut Manley Lanier "Sonny" Carter Jr., who flew on a 1989 space shuttle mission and was in training for a shuttle trip later this year, also died in the crash .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06097121" num="9" wdcount="1"> Front</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06097121" num="10" wdcount="10"> CRASH KILLS TOWER, 22 OTHERS EX-SENATOR'S DAUGHTER ALSO AMONG VICTIMS</s>
</HEADLINE>
<MEMO>

<s docid="SJMN91-06097121" num="11" wdcount="6"> See related article on page 15A</s>
</MEMO>
<TEXT>

<s docid="SJMN91-06097121" num="12" wdcount="30"> Another victim was Dr. Nicholas Davies, president-elect of the American College of Physicians, a 60,000-member industry group, said Dr. Louis Felder, who worked with Davies at Piedmont Hospital in Atlanta.</s>

<s docid="SJMN91-06097121" num="13" wdcount="16"> None of the 20 passengers or three crew members aboard Atlantic Southeast Airlines Flight 2311 survived.</s>

<s docid="SJMN91-06097121" num="14" wdcount="20"> The crash followed by one day the plane-helicopter collision that killed Sen. John Heinz of Pennsylvania and six other people.</s>

<s docid="SJMN91-06097121" num="15" wdcount="31"> Tower, 65, and his daughter Marian, 35, boarded the 30-passenger, turboprop Embraer 120 in Atlanta and were headed to Sea Island, off the Georgia coast, for a party in Tower's honor.</s>

<s docid="SJMN91-06097121" num="16" wdcount="11"> Officials said they did not know the cause of the crash.</s>

<s docid="SJMN91-06097121" num="17" wdcount="27"> The plane was descending in clear weather, authorities said, when it went down at 2:47 p.m. about three miles northeast of the runway at the Brunswick-Glynco Jetport.</s>

<s docid="SJMN91-06097121" num="18" wdcount="12"> Witnesses said the plane appeared to have fallen straight from the sky.</s>

<s docid="SJMN91-06097121" num="19" wdcount="5"> "It just went straight down.</s>

<s docid="SJMN91-06097121" num="20" wdcount="18"> There was no cropping of trees," said Lt. Jack Hopper of the Glynn County Police Department, quoting witnesses.</s>

<s docid="SJMN91-06097121" num="21" wdcount="23"> "It started in on its nose, and I knew it was in trouble," said James Griner, who lives a quarter-mile from the airport.</s>

<s docid="SJMN91-06097121" num="22" wdcount="15"> "I went to the plane, but I couldn't get to it because of the fire.</s>

<s docid="SJMN91-06097121" num="23" wdcount="32"> . . . When I got to it, it looked compacted."; Atlantic Southeast's senior vice president, John Beiser, said officials had no indication from the pilot that the flight was in trouble.</s>

<s docid="SJMN91-06097121" num="24" wdcount="24"> Donald Day, the airline's manager of consumer affairs, described the aircraft as "extremely sophisticated and fuel-efficient, one of the backbones of our commuter fleet".</s>

<s docid="SJMN91-06097121" num="25" wdcount="14"> He said the plane was new and had been put in service in December.</s>

<s docid="SJMN91-06097121" num="26" wdcount="12"> The Brazilian-made Embraer 120 is manufactured by Empresa Brasileira de Aeronautica SA.</s>

<s docid="SJMN91-06097121" num="27" wdcount="19"> In 1984, an Embraer 110 Bandeirante, an earlier model of the 120, crashed in Jacksonville, Fla., killing 13 people.</s>

<s docid="SJMN91-06097121" num="28" wdcount="21"> The Federal Aviation Administration subsequently ordered an inspection of all Embraers for possible sheared or worn rivets in the tail sections.</s>

<s docid="SJMN91-06097121" num="29" wdcount="27"> Tower's death prompted words of grief and praise among his former colleagues on Capitol Hill, even those who helped derail his elevation to the Cabinet in 1989.</s>

<s docid="SJMN91-06097121" num="30" wdcount="40"> "I'm deeply saddened by the loss of John Tower, a tough, able friend and patriot," said Sen. Lloyd Bentsen, D-Texas, who broke ranks with most Democrats to support President Bush's nomination of the 24-year Senate veteran to be defense secretary.</s>

<s docid="SJMN91-06097121" num="31" wdcount="16"> "He was intelligent and had independence of judgment."; Senate Armed Services Committee Chairman Sam Nunn, D-Ga.</s>

<s docid="SJMN91-06097121" num="32" wdcount="15"> , who led the successful fight against Tower's confirmation, said: "America had lost a patriot.</s>

<s docid="SJMN91-06097121" num="33" wdcount="21"> . . . He fought for freedom and worked diligently to make the world more secure."; "It's so sad," Bush said.</s>

<s docid="SJMN91-06097121" num="34" wdcount="6"> "It is a tragic loss" .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06097121" num="35" wdcount="4"> Mercury News Wire Services</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06097121" num="36" wdcount="1"> USA</s>
</COUNTRY>
<CITY>

<s docid="SJMN91-06097121" num="37" wdcount="3"> Brunswick, Ga .</s>
</CITY>
<EDITION>

<s docid="SJMN91-06097121" num="38" wdcount="2"> Morning Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06097121" num="39" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06097121" num="40" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06097121" num="41" wdcount="1"> 910406</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06097121" num="42" wdcount="1"> Saturday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06097121" num="43" wdcount="1"> April</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06097121" num="44" wdcount="1"> 1A</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06097121" num="45" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06097121" num="46" wdcount="1"> WEST</s>
</REGION>
<FEATURE>

<s docid="SJMN91-06097121" num="47" wdcount="1"> PHOTO</s>
</FEATURE>
<STATE>

<s docid="SJMN91-06097121" num="48" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06097121" num="49" wdcount="1"> 570</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06097121" num="50" wdcount="5"> Saturday April 6, 1991 00097121,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06097121" num="51" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06097121" num="52" wdcount="1"> 1</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06097121" num="53" wdcount="2"> ENG FRONT</s>
</LANGUAGE>
</DOC>
