<DOC>
<DOCNO>

<s docid="WSJ910213-0136" num="1" wdcount="1"> WSJ910213-0136</s>
</DOCNO>
<DOCID>

<s docid="WSJ910213-0136" num="2" wdcount="2"> 910213-0136 .</s>
</DOCID>
<HL>

<s docid="WSJ910213-0136" num="3" wdcount="17"> LEISURE & ARTS -- Bookshelf: He Doesn't Drink or Chase Women, He Says ---- By William Murchison</s>
</HL>
<DATE>

<s docid="WSJ910213-0136" num="4" wdcount="1"> 02/13/91</s>
</DATE>
<SO>

<s docid="WSJ910213-0136" num="5" wdcount="6"> WALL STREET JOURNAL (J), PAGE A10</s>
</SO>
<LP>

<s docid="WSJ910213-0136" num="6" wdcount="2"> John G.</s>

<s docid="WSJ910213-0136" num="7" wdcount="18"> Tower, conservative Republican senator from Texas, son of a respected Methodist preacher, boozed it up and fooled around.</s>

<s docid="WSJ910213-0136" num="8" wdcount="10"> His first marriage fell apart; his second made him miserable.</s>

<s docid="WSJ910213-0136" num="9" wdcount="14"> All the while, he preened himself as the first statewide Republican officeholder since Reconstruction.</s>

<s docid="WSJ910213-0136" num="10" wdcount="2"> John G.</s>

<s docid="WSJ910213-0136" num="11" wdcount="28"> Tower wasn't -- isn't -- St. John the Divine, as he himself acknowledges with semi-charming candor in "Consequences: A Personal and Political Memoir (Little, Brown, 388 pages, $22.95).</s>

<s docid="WSJ910213-0136" num="12" wdcount="12"> Did he deserve, even so, public flagellation as George Bush's defense-secretary nominee?</s>
</LP>
<TEXT>

<s docid="WSJ910213-0136" num="13" wdcount="5"> You would obviously expect Mr.</s>

<s docid="WSJ910213-0136" num="14" wdcount="10"> Tower to say no, and he obliges: volubly and passionately.</s>

<s docid="WSJ910213-0136" num="15" wdcount="22"> If that was all there was to "Consequences," we could scan the dust jacket and invest our savings in local real estate.</s>

<s docid="WSJ910213-0136" num="16" wdcount="19"> "Consequences" reads a bit like a political Stephen King story as the small senator swelled into a Beltway monster.</s>

<s docid="WSJ910213-0136" num="17" wdcount="30"> Politics never has been for the squeamish, but the Tower controversy leaves a much more disagreeable taste than did the senator's caperings (which mostly took place in the '70s anyway).</s>

<s docid="WSJ910213-0136" num="18" wdcount="26"> Were the writing less stiff and the narrative technique less choppy, "Consequences" might have been a classic case study of late 20th-century politics out of control.</s>

<s docid="WSJ910213-0136" num="19" wdcount="2"> Given Mr.</s>

<s docid="WSJ910213-0136" num="20" wdcount="26"> Tower's qualifications for the job -- intelligence, patriotism and past chairmanship of the Armed Services Committee -- the nomination should have sailed through with flying colors.</s>

<s docid="WSJ910213-0136" num="21" wdcount="6"> Instead it sank like the Bismarck.</s>

<s docid="WSJ910213-0136" num="22" wdcount="7"> Clearly and apparently to his surprise, Mr.</s>

<s docid="WSJ910213-0136" num="23" wdcount="19"> Tower had made many enemies since his arrival in Washington in 1961, often rubbing even supporters the wrong way.</s>

<s docid="WSJ910213-0136" num="24" wdcount="14"> The senator from the Lone Star State could be lordly, in his English-cut suits.</s>

<s docid="WSJ910213-0136" num="25" wdcount="31"> Once, meeting with the editors of my newspaper which had backed him strongly, he thought nothing of tilting back in his chair, crossing his tiny, well-shod feet atop the conference table.</s>

<s docid="WSJ910213-0136" num="26" wdcount="13"> When the Tower hearings opened, all manner of accusations came to public notice.</s>

<s docid="WSJ910213-0136" num="27" wdcount="19"> The New Right activist Paul Weyrich claimed to have seen the senator consorting with A Lady Not His Wife.</s>

<s docid="WSJ910213-0136" num="28" wdcount="5"> It was reported that Mr.</s>

<s docid="WSJ910213-0136" num="29" wdcount="17"> Tower had chased a secretary around his desk and had fondled women at Bergstrom Air Force Base.</s>

<s docid="WSJ910213-0136" num="30" wdcount="17"> The second wife, whom the senator had recently divorced, possessed a repertory of tales she cheerfully volunteered.</s>

<s docid="WSJ910213-0136" num="31" wdcount="4"> At his hotel, Mr.</s>

<s docid="WSJ910213-0136" num="32" wdcount="12"> Tower was accorded that doubtful tribute to instant-celebrity status, the media stakeout.</s>

<s docid="WSJ910213-0136" num="33" wdcount="29"> The nominee issued fervent denials: He drank only wine, having long since sworn off scotch; he'd never chased secretaries; his services for defense-industry clients had been proper and modest.</s>

<s docid="WSJ910213-0136" num="34" wdcount="8"> None of the charges, at least on Mr.</s>

<s docid="WSJ910213-0136" num="35" wdcount="8"> Tower's showing, proved to have the least substance.</s>

<s docid="WSJ910213-0136" num="36" wdcount="2"> No use.</s>

<s docid="WSJ910213-0136" num="37" wdcount="14"> Dirt is dirtier than purity is pure, as one of John O'Hara's characters observes.</s>

<s docid="WSJ910213-0136" num="38" wdcount="4"> Sen. Sam Nunn, Mr.</s>

<s docid="WSJ910213-0136" num="39" wdcount="24"> Tower's successor as Armed Services Committee chairman, seemed initially to smile on the nomination; then the rumor mill started churning and he changed fronts.</s>

<s docid="WSJ910213-0136" num="40" wdcount="17"> While endeavoring to look statesmanlike, Sen. Nunn leaned on moderate Democrats who would otherwise have supported Tower.</s>

<s docid="WSJ910213-0136" num="41" wdcount="8"> Sen. Nunn made the campaign personal, says Mr.</s>

<s docid="WSJ910213-0136" num="42" wdcount="9"> Tower -- vote for me or vote for him.</s>

<s docid="WSJ910213-0136" num="43" wdcount="9"> Most Democrats, in the end, went with Sen. Nunn.</s>

<s docid="WSJ910213-0136" num="44" wdcount="5"> What was all this about?</s>

<s docid="WSJ910213-0136" num="45" wdcount="2"> Morality? Mr.</s>

<s docid="WSJ910213-0136" num="46" wdcount="24"> Tower suggests instead that Sen. Nunn, a presidential hopeful, discovered and seized an opportunity to show who was really No. 1 on national defense.</s>

<s docid="WSJ910213-0136" num="47" wdcount="16"> Sen. Nunn had every reason to know that the moral and ethical charges leveled at Mr.</s>

<s docid="WSJ910213-0136" num="48" wdcount="9"> Tower, and investigated exhaustively by the FBI, were flimsy.</s>

<s docid="WSJ910213-0136" num="49" wdcount="6"> Yet he waved them about anyway.</s>

<s docid="WSJ910213-0136" num="50" wdcount="24"> When the media retailed lurid and unsubstantiated stories, Sen. Nunn pursed his lips like a Georgia Sunday-school superintendent and suggested that a drunken Mr.</s>

<s docid="WSJ910213-0136" num="51" wdcount="7"> Tower might accidentally press the nuclear button.</s>

<s docid="WSJ910213-0136" num="52" wdcount="3"> "Sam Nunn," Mr.</s>

<s docid="WSJ910213-0136" num="53" wdcount="19"> Tower insists, "used the FBI inquiries to discredit me and to strike at the president of the United States.</s>

<s docid="WSJ910213-0136" num="54" wdcount="14"> The essential chain of good judgment and goodwill broke down during my confirmation process".</s>

<s docid="WSJ910213-0136" num="55" wdcount="6"> Sen. Nunn has company on Mr.</s>

<s docid="WSJ910213-0136" num="56" wdcount="3"> Tower's dishonor roll.</s>

<s docid="WSJ910213-0136" num="57" wdcount="42"> There is Sen. Ernest Hollings ("a study in arrogance and pomposity"), Sen. James Exon ("one of the most excessive regular boozers in the Senate") and NBC's Andrea Mitchell ("the most viciously partisan reporter I've ever seen"), along with the Washington press corps.</s>

<s docid="WSJ910213-0136" num="58" wdcount="19"> Sen. John Warner, a Republican, is depicted as falling all over himself to stay in good with Sen. Nunn.</s>

<s docid="WSJ910213-0136" num="59" wdcount="28"> Mr. Tower feels, not without reason, that he was arraigned on morals charges by cynical colleagues and media personages whom no one ever mistook for Southern Baptist deacons.</s>

<s docid="WSJ910213-0136" num="60" wdcount="11"> "I don't so much resent my rejection by the Senate," Mr.</s>

<s docid="WSJ910213-0136" num="61" wdcount="8"> Tower insists, "as the way it was done".</s>

<s docid="WSJ910213-0136" num="62" wdcount="11"> "Tower, you were lynched," Mike Wallace, the CBS correspondent, told him.</s>

<s docid="WSJ910213-0136" num="63" wdcount="8"> Worse yet, the lynch mob remains at large.</s>

<s docid="WSJ910213-0136" num="64" wdcount="2"> --- Mr.</s>

<s docid="WSJ910213-0136" num="65" wdcount="11"> Murchison is a senior columnist for the Dallas Morning News .</s>
</TEXT>
</DOC>
