<DOC>
<DOCNO>

<s docid="AP881025-0196" num="1" wdcount="1"> AP881025-0196</s>
</DOCNO>
<FILEID>

<s docid="AP881025-0196" num="2" wdcount="2"> AP-NR-10-25-88 2051EDT</s>
</FILEID>
<FIRST>

<s docid="AP881025-0196" num="3" wdcount="5"> u i AM-BookerPrize 10-25 0401</s>
</FIRST>
<SECOND>

<s docid="AP881025-0196" num="4" wdcount="2"> AM-Booker Prize,0414</s>
</SECOND>
<HEAD>

<s docid="AP881025-0196" num="5" wdcount="5"> Australian Novelist Wins Booker Prize</s>
</HEAD>
<DATELINE>

<s docid="AP881025-0196" num="6" wdcount="2"> LONDON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP881025-0196" num="7" wdcount="21"> Australian novelist Peter Carey was awarded the coveted Booker Prize for fiction Tuesday night for his love story, ``Oscar and Lucinda''.</s>

<s docid="AP881025-0196" num="8" wdcount="24"> A panel of five judges unanimously announced the award of the $26,250 prize after an 80-minute deliberation during a banquet at London's ancient Guildhall.</s>

<s docid="AP881025-0196" num="9" wdcount="23"> The judges made their selection from 102 books published in Britain in the past 12 months and which they read in their homes.</s>

<s docid="AP881025-0196" num="10" wdcount="38"> Carey, who lives in Sydney with his wife and son, said in a brief speech that like the other five finalists he had been asked to attend with a short speech in his pocket in case he won.</s>

<s docid="AP881025-0196" num="11" wdcount="30"> ``If I'd known I was going to win I think I would have taken a bit more trouble with my handwriting,'' he said as he stared down at his notes.</s>

<s docid="AP881025-0196" num="12" wdcount="18"> He was unsuccessful in the prize competition in 1985 when his novel, ``Illywhacker,'' was among the final six.</s>

<s docid="AP881025-0196" num="13" wdcount="28"> Carey called the award a ``great honor'' and he thanked the prize sponsors for ``provoking so much passionate discussion about literature _ perhaps there will be more tomorrow''.</s>

<s docid="AP881025-0196" num="14" wdcount="11"> ``Everyone who loves good books benefits from this, surely,'' he added.</s>

<s docid="AP881025-0196" num="15" wdcount="11"> The winning novel is a fitting choice for Australia's bicentennial year.</s>

<s docid="AP881025-0196" num="16" wdcount="26"> It tells of a romance between an English gambler and an Australian heiress who meet on a steamship's maiden voyage to Australia in the mid-19th century.</s>

<s docid="AP881025-0196" num="17" wdcount="14"> The story weaves in Australian history from its founding in 1788 by British immigrants.</s>

<s docid="AP881025-0196" num="18" wdcount="36"> Panel chairman Michael Foot, a writer and former leader of the opposition Labor Party, said the judges agreed that entries this year had been ``exceptionally strong'' and that choosing the last six novels was extremely difficult.</s>

<s docid="AP881025-0196" num="19" wdcount="22"> ``We hope there will be no criticisms but if there are, then people should start reading the books for themselves,'' Foot said.</s>

<s docid="AP881025-0196" num="20" wdcount="9"> Carey was the only non-Briton in the final six.</s>

<s docid="AP881025-0196" num="21" wdcount="36"> The son of an auto dealer, he was born in Bacchus Marsh, Victoria, and attended Geelong Church of England Grammar School, Melbourne, where the Prince of Wales was also a pupil as an 18-year-old in 1966.</s>

<s docid="AP881025-0196" num="22" wdcount="12"> Carey was an advertising copywriter before turning to writing books in 1965.</s>

<s docid="AP881025-0196" num="23" wdcount="8"> The first Booker Prize was awarded in 1969.</s>

<s docid="AP881025-0196" num="24" wdcount="23"> It is administered by Book Trust, an educational charity promoting books, and is sponsored by Booker, an international food and farming business .</s>
</TEXT>
</DOC>
