<DOC>
<DOCNO>

<s docid="AP890922-0224" num="1" wdcount="1"> AP890922-0224</s>
</DOCNO>
<FILEID>

<s docid="AP890922-0224" num="2" wdcount="2"> AP-NR-09-22-89 2252EDT</s>
</FILEID>
<FIRST>

<s docid="AP890922-0224" num="3" wdcount="5"> r i AM-BookerPrize 09-22 0362</s>
</FIRST>
<SECOND>

<s docid="AP890922-0224" num="4" wdcount="2"> AM-Booker Prize,0374</s>
</SECOND>
<HEAD>

<s docid="AP890922-0224" num="5" wdcount="8"> Bookmakers Pick Japanese Author to Win Booker Prize</s>
</HEAD>
<DATELINE>

<s docid="AP890922-0224" num="6" wdcount="2"> LONDON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890922-0224" num="7" wdcount="30"> Six novels have been nominated for the Booker Prize, Britain's most prestigious fiction award, and bookmakers say the favorite is ``The Remains of the Day'' by Japanese author Kazuo Ishiguro.</s>

<s docid="AP890922-0224" num="8" wdcount="18"> The award, to be announced Oct. 26, carries a $31,600 prize funded by the Booker McConnell food company.</s>

<s docid="AP890922-0224" num="9" wdcount="26"> Oddsmaker William Hill gave 7-to-4 odds on Ishiguro's novel about a butler's travels through Britain's West Country and said it was ``a firm favorite'' to win.</s>

<s docid="AP890922-0224" num="10" wdcount="32"> Ishiguro, previously nominated for the award, ``was beaten as the Booker favorite in 1986, which makes his chances that much stronger this time in our view,'' said William Hill spokesman Graham Sharpe.</s>

<s docid="AP890922-0224" num="11" wdcount="32"> The other books nominated are: _ ``Cat's Eye,'' a story of painter Elaine Risley and her return to her childhood home in Toronto by Canadian author Margaret Atwood, also a previous nominee.</s>

<s docid="AP890922-0224" num="12" wdcount="25"> _ ``The Book of Evidence,'' a prison story of kidnap and murder convict Freddie Montgomery by John Banville, literary editor of The Irish Times newspaper.</s>

<s docid="AP890922-0224" num="13" wdcount="17"> _ ``Jigsaw,'' by Sybille Bedford, an autobiographical novel about an adolescent's travels through Germany, Italy and France.</s>

<s docid="AP890922-0224" num="14" wdcount="29"> _ ``A Disaffection,'' Scottish novelist James Kelman's story about a school teacher, Patrick Doyle, whose professional frustrations are fueled by a drinking problem and unrequited love for a colleague.</s>

<s docid="AP890922-0224" num="15" wdcount="22"> _ ``Restoration,'' British author Rose Tremain's story of Robert Merivel, a favorite of King Charles II who married the monarch's youngest mistress.</s>

<s docid="AP890922-0224" num="16" wdcount="25"> ``We expect more interest in this year's Booker Prize than ever before, partly thanks to last year's controversy over Salman Rushdie's `Satanic Verses,''' Sharpe said.</s>

<s docid="AP890922-0224" num="17" wdcount="24"> Rushdie was nominated for the prize last year but it was won by Australian author Peter Carey for his love story ``Oscar and Lucinda''.</s>

<s docid="AP890922-0224" num="18" wdcount="30"> Rushdie, a British citizen, has been in hiding since Feb. 14 when the late Iranian leader Ayatollah Ruhollah Khomeini ordered he be killed for allegedly blaspheming Islam in ``Satanic Verses''.</s>

<s docid="AP890922-0224" num="19" wdcount="37"> This year's six nominees were chosen Thursday from 102 books considered by a panel headed by David Lodge, a British literary critic and novelist who was nominated for the prize last year for his book, ``Nice Work.''</s>
</TEXT>
</DOC>
