<DOC>
<DOCNO>

<s docid="AP891026-0208" num="1" wdcount="1"> AP891026-0208</s>
</DOCNO>
<FILEID>

<s docid="AP891026-0208" num="2" wdcount="2"> AP-NR-10-26-89 2229EDT</s>
</FILEID>
<FIRST>

<s docid="AP891026-0208" num="3" wdcount="7"> u i AM-BookerPrize 1stLd-Writethru a0768 10-26 0283</s>
</FIRST>
<SECOND>

<s docid="AP891026-0208" num="4" wdcount="5"> AM-Booker Prize, 1st Ld-Writethru, a0768,0287</s>
</SECOND>
<HEAD>

<s docid="AP891026-0208" num="5" wdcount="7"> Kazuo Ishiguro Wins Britain's Top Literary Prize</s>
</HEAD>
<HEAD>

<s docid="AP891026-0208" num="6" wdcount="12"> Eds: LEADS throughout to UPDATE with comment by Ishiguro, EDITS to conform.</s>

<s docid="AP891026-0208" num="7" wdcount="2"> No pickup</s>
</HEAD>
<DATELINE>

<s docid="AP891026-0208" num="8" wdcount="2"> LONDON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP891026-0208" num="9" wdcount="24"> Japanese writer Kazuo Ishiguro won the 1989 Booker Prize, Britain's top literary award, for his novel ``The Remains of the Day,'' judges announced Thursday.</s>

<s docid="AP891026-0208" num="10" wdcount="5"> The prize is worth $32,000.</s>

<s docid="AP891026-0208" num="11" wdcount="20"> Judges praised the novel, a love story about a butler's English vacation, as ``a cunningly structured and beautifully paced performance''.</s>

<s docid="AP891026-0208" num="12" wdcount="37"> Other finalists this year were Canadian Margaret Atwood for ``Cat's Eye,'' Irish author John Banville for ``Book of Evidence,'' Scotland's James Kelman for ``A Disaffection'' and English writers Sybille Bedford for ``Jigsaw'' and Rose Tremain for ``Restoration''.</s>

<s docid="AP891026-0208" num="13" wdcount="40"> After receiving the prize, Ishiguro paid tribute to Salman Rushdie, the 1988 runner-up for the award, who went into hiding in February when he was threatened with death by Moslems who said his novel ``The Satanic Verses'' blasphemed their faith.</s>

<s docid="AP891026-0208" num="14" wdcount="34"> ``Now that circumstances have changed, when perhaps it is inconvenient for many people to support his writing, I just felt it was fitting that we should not turn our backs on him,'' Ishiguro said.</s>

<s docid="AP891026-0208" num="15" wdcount="4"> Rushdie lives in England.</s>

<s docid="AP891026-0208" num="16" wdcount="14"> Ishiguro, 39, arrived in England at age 6 and now lives in south London.</s>

<s docid="AP891026-0208" num="17" wdcount="4"> He writes in English.</s>

<s docid="AP891026-0208" num="18" wdcount="31"> In announcing the winner, the judges said: ```The Remains of the Day' renders with humor and pathos a memorable character and explores the large, vexed themes of class, tradition and duty.</s>

<s docid="AP891026-0208" num="19" wdcount="7"> It was narrowly preferred but universally admired''.</s>

<s docid="AP891026-0208" num="20" wdcount="19"> Ishiguro was a finalist for the Booker Prize in 1986 for his novel ``An Artist of the Floating World''.</s>

<s docid="AP891026-0208" num="21" wdcount="14"> The Booker Prize is sponsored by Booker, an international food and agriculture business .</s>
</TEXT>
</DOC>
