<DOC>
<DOCNO>

<s docid="AP901016-0112" num="1" wdcount="1"> AP901016-0112</s>
</DOCNO>
<FILEID>

<s docid="AP901016-0112" num="2" wdcount="2"> AP-NY-10-16-90 1631EDT</s>
</FILEID>
<FIRST>

<s docid="AP901016-0112" num="3" wdcount="5"> u i AM-BookerPrize 10-16 0375</s>
</FIRST>
<SECOND>

<s docid="AP901016-0112" num="4" wdcount="2"> AM-Booker Prize,0431</s>
</SECOND>
<HEAD>

<s docid="AP901016-0112" num="5" wdcount="7"> A.S. Byatt Wins Britain's Top Literary Prize</s>
</HEAD>
<BYLINE>

<s docid="AP901016-0112" num="6" wdcount="3"> By MAGGIE JACKSON</s>
</BYLINE>
<BYLINE>

<s docid="AP901016-0112" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP901016-0112" num="8" wdcount="2"> LONDON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP901016-0112" num="9" wdcount="33"> Critic and novelist A.S. Byatt on Tuesday won the Booker Prize, Britain's most prestigious literary award, for her tale of two young scholars investigating the lives of a pair of imaginary Victorian poets.</s>

<s docid="AP901016-0112" num="10" wdcount="24"> The five judges deliberated two hours before awarding the $39,000 prize to Antonia Byatt for ``Possession,'' one of six finalists in the 21-year-old competition.</s>

<s docid="AP901016-0112" num="11" wdcount="15"> Last year's Booker winner was Kazuo Ishiguro for his novel, ``The Remains of the Day''.</s>

<s docid="AP901016-0112" num="12" wdcount="26"> Television executive Sir Denis Forman, chairman of the judge's panel, announced the prize at a banquet in London's Elizabethan Guildhall, seat of the city's Lord Mayor.</s>

<s docid="AP901016-0112" num="13" wdcount="29"> ``There was very strong individual support for several books on the short list and finally `Possession' by A.S. Byatt was the winner by a majority vote,'' said the judges.</s>

<s docid="AP901016-0112" num="14" wdcount="28"> ``The panel was unanimous, however, in agreeing that the standard of the other five novels was exceptionally high and this made their decision unusually interesting and unusually difficult''.</s>

<s docid="AP901016-0112" num="15" wdcount="26"> Ms. Byatt, who earlier this month won the $43,000 Irish Times-Aer Lingus prize for international fiction for the same work, has published five novels since 1964.</s>

<s docid="AP901016-0112" num="16" wdcount="35"> In ``Possession,'' she tells how two graduate students piece together the relationship and lives of two imaginary Victorian poets from fragments of their letters and by retracing the poets' journeys across England and to France.</s>

<s docid="AP901016-0112" num="17" wdcount="14"> The influence of the past on the living is a theme throughout the book.</s>

<s docid="AP901016-0112" num="18" wdcount="17"> Ms. Byatt, born in 1936, is the daughter of a lawyer and sister of novelist Margaret Drabble.</s>

<s docid="AP901016-0112" num="19" wdcount="21"> Her first novel, ``Shadow of a Sun,'' concerned the efforts of a woman to escape the shadow of her novelist father.</s>

<s docid="AP901016-0112" num="20" wdcount="29"> A 1978 work, ``The Virgin in the Garden,'' makes allegorical allusions to Shakespeare and other English literary geniuses in a tale of a play performed at a country house.</s>

<s docid="AP901016-0112" num="21" wdcount="20"> Ms. Byatt taught English and American literature at University College in London until 1983, when she quit to write fulltime.</s>

<s docid="AP901016-0112" num="22" wdcount="41"> Other finalists this year were 1979 Booker Prize winner Penelope Fitzgerald with ``The Gate of Angels,'' Irish novelist John McGahern's ``Amongst Women,'' Canadian-born Mordecai Richler's ``Solomon Gursky Was Here,'' Brian Moore's ``Lies of Silence,'' and Beryl Bainbridge's ``An Awfully Big Adventure''.</s>

<s docid="AP901016-0112" num="23" wdcount="16"> They were chosen from a list of 113 books published in the United Kingdom in 1989.</s>

<s docid="AP901016-0112" num="24" wdcount="19"> The Booker Prize is sponsored by Booker, an international food and agriculture business, and administered by The Book Trust.</s>

<s docid="AP901016-0112" num="25" wdcount="7"> It is Britain's top literary award .</s>
</TEXT>
</DOC>
