<DOC>
<DOCNO>

<s docid="AP901008-0174" num="1" wdcount="1"> AP901008-0174</s>
</DOCNO>
<FILEID>

<s docid="AP901008-0174" num="2" wdcount="2"> AP-NY-10-08-90 1302EDT</s>
</FILEID>
<FIRST>

<s docid="AP901008-0174" num="3" wdcount="6"> a e AM-APArts:BookerPrize Adv12 10-08 0310</s>
</FIRST>
<SECOND>

<s docid="AP901008-0174" num="4" wdcount="5"> AM-AP Arts: Booker Prize, Adv12,0344</s>
</SECOND>
<NOTE>

<s docid="AP901008-0174" num="5" wdcount="1"> $Adv12</s>
</NOTE>
<NOTE>

<s docid="AP901008-0174" num="6" wdcount="8"> For Release Friday AMs, Oct. 12, and Thereafter</s>
</NOTE>
<HEAD>

<s docid="AP901008-0174" num="7" wdcount="4"> With AM-AP Arts: Britain-Publishing</s>
</HEAD>
<HEAD>

<s docid="AP901008-0174" num="8" wdcount="7"> The Booker - Britain's Favorite Literary Prize</s>
</HEAD>
<DATELINE>

<s docid="AP901008-0174" num="9" wdcount="2"> LONDON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP901008-0174" num="10" wdcount="30"> The Booker Prize is Britain's literary event of the year, guaranteed to boost sales of the chosen novel after the award announcement Oct. 16, and dinner in London's ancient Guildhall.</s>

<s docid="AP901008-0174" num="11" wdcount="22"> The prize to the author is a check for 20,000 pounds (nearly $38,000), sponsored by Booker, an international food and agriculture business.</s>

<s docid="AP901008-0174" num="12" wdcount="42"> ``British publishers are very secretive about their sales but we know that when Thomas Keneally won it in 1982 for `Schindler's Ark,' his publishers, who had printed 15,000 copies, sold 75,000 over the next 23 weeks,'' said Christine Shaw of Book Trust.</s>

<s docid="AP901008-0174" num="13" wdcount="13"> The trust is a charity promoting reading and books and administers the prize.</s>

<s docid="AP901008-0174" num="14" wdcount="22"> ``The prize has become internationally known, and the worldwide demand for the winning book, in English and translations, is spectacular,'' said Shaw.</s>

<s docid="AP901008-0174" num="15" wdcount="29"> The prize was first awarded in 1969 after talks between Booker and the Publishers' Association on the need for a significant literary award to encourage and reward good writing.</s>

<s docid="AP901008-0174" num="16" wdcount="12"> British publishers can submit three new novels by British and Commonwealth writers.</s>

<s docid="AP901008-0174" num="17" wdcount="6"> There were 110 submissions last year.</s>

<s docid="AP901008-0174" num="18" wdcount="32"> A management committee of authors, booksellers, librarians and the sponsors chooses a jury of five: a writer or two, an academic, a politician interested in literature and a literary editor or critic.</s>

<s docid="AP901008-0174" num="19" wdcount="21"> Each juror reads every book submitted, lists about six favorites and meets the other jurors to select and announce six finalists.</s>

<s docid="AP901008-0174" num="20" wdcount="36"> As public debate rages over who's in, who's out and who might win, with bookmakers across the country calling the odds, the jurors meet again and finally select the winner on the afternoon of announcement day.</s>

<s docid="AP901008-0174" num="21" wdcount="34"> This year's finalists: Beryl Bainbridge ``An Awfully Big Adventure,'' A.S. Byatt ``Possession,'' Penelope Fitzgerald ``The Gate of Angels,'' John McGahern ``Amongst Women,'' Brian Moore ``Lies of Silence'' and Mordecai Richler ``Solomon Gursky Was Here.''</s>
</TEXT>
<NOTE>

<s docid="AP901008-0174" num="22" wdcount="7"> End Adv for Friday AMs, Oct. 12</s>
</NOTE>
<TEXT>
</TEXT>
</DOC>
