<DOC>
<DOCNO>

<s docid="FT923-3822" num="1" wdcount="1"> FT923-3822</s>
</DOCNO>
<PROFILE>

<s docid="FT923-3822" num="2" wdcount="1"> _AN-CIJB4AC0FT</s>
</PROFILE>
<DATE>

<s docid="FT923-3822" num="3" wdcount="1"> 920910</s>
</DATE>
<HEADLINE>

<s docid="FT923-3822" num="4" wdcount="9"> FT 10 SEP 92 / Arts: Booker Prize shortlist</s>
</HEADLINE>
<BYLINE>

<s docid="FT923-3822" num="5" wdcount="2"> By J.</s>

<s docid="FT923-3822" num="6" wdcount="3"> D. F. JONES</s>
</BYLINE>
<TEXT>

<s docid="FT923-3822" num="7" wdcount="25"> THE annual Booker ballyhoo got going again yesterday when the judges for this year's Pounds 20,000 prize for British (and Commonwealth) fiction announced the shortlist.</s>

<s docid="FT923-3822" num="8" wdcount="39"> The Prize (courtesy of Booker plc, the food and agri-business group) is no longer the richest literary award but it guarantees great prestige, and sales, for the winner, and, say its admirers, helpfully brings The Novel to public attention.</s>

<s docid="FT923-3822" num="9" wdcount="33"> Its critics say that the autumn brouhaha distorts the annual fiction industry and the intense media hype of the shortlisted authors does a disservice to the hordes of other gifted but unlisted writers.</s>

<s docid="FT923-3822" num="10" wdcount="6"> This year's shortlist contains no surprises.</s>

<s docid="FT923-3822" num="11" wdcount="32"> London's litterati have for weeks been betting on Michael Ondaatje's The English Patient - those of them who have seen a proof copy because it is not officially published until next week.</s>

<s docid="FT923-3822" num="12" wdcount="11"> Last night the bookmakers William Hill made it the 5-2 favourite.</s>

<s docid="FT923-3822" num="13" wdcount="11"> The shortlist is: Serenity House by Christopher Hope (MacMillan Pounds 14.99).</s>

<s docid="FT923-3822" num="14" wdcount="11"> Black comedy by a master South Africa-born specialist in the trade.</s>

<s docid="FT923-3822" num="15" wdcount="26"> Set in a Highgate 'eventide refuge' where euthanasia is an unspoken word and its senior citizen, Max Montfalcon, turns out to be a geriatric Nazi scientist.</s>

<s docid="FT923-3822" num="16" wdcount="12"> The FT review next Saturday will describe it as 'surreal farce ..</s>

<s docid="FT923-3822" num="17" wdcount="3"> scabrously enjoyable '..</s>

<s docid="FT923-3822" num="18" wdcount="9"> The Butcher's Boy by Patrick McCabe (Picador Pounds 14.99).</s>

<s docid="FT923-3822" num="19" wdcount="15"> An Irish murderer, a soft-in-the-head orphan jailed for life, recalls his life in grisly detail.</s>

<s docid="FT923-3822" num="20" wdcount="20"> The FT reviewer said that 'the misery and deprivation of working class life have never been so brutally evoked '..</s>

<s docid="FT923-3822" num="21" wdcount="21"> Black Dogs by Ian McEwan (Secker & Warburg Pounds 14.99). McEwan's fiction is uniquely disturbing - some would say deliberately offensive.</s>

<s docid="FT923-3822" num="22" wdcount="6"> He is the novelist of misanthropy.</s>

<s docid="FT923-3822" num="23" wdcount="21"> This is the tale of a failed marriage, episodically told, and the black dogs of evil are both metaphorical and literal.</s>

<s docid="FT923-3822" num="24" wdcount="9"> The English Patient by Michael Ondaatje (Bloomsbury Pounds 14.99).</s>

<s docid="FT923-3822" num="25" wdcount="38"> The Sri Lankan poet and novelist Ondaatje, who lives in Canada, has followed 'in the skin of a lion' with an extraordinary book about four characters in a Tuscan villa in the closing months of the last war.</s>

<s docid="FT923-3822" num="26" wdcount="11"> The central metaphor is bombs - disposal of, and then Hiroshima.</s>

<s docid="FT923-3822" num="27" wdcount="24"> The 'English patient' is a central mystery around which the others' stories orbit: he fell out of the sky in flames; who is he?</s>

<s docid="FT923-3822" num="28" wdcount="11"> The FT review on Saturday will hail it as a masterpiece.</s>

<s docid="FT923-3822" num="29" wdcount="10"> Daughters of the House by Michele Roberts (Virago Pounds 14.99).</s>

<s docid="FT923-3822" num="30" wdcount="9"> The surprise contender because it is not yet published.</s>

<s docid="FT923-3822" num="31" wdcount="18"> Roberts comes from an Anglo-French Catholic background and this informs her new novel with a strong rural-Normandy atmosphere.</s>

<s docid="FT923-3822" num="32" wdcount="6"> Two cousins, one pious, one worldly.</s>

<s docid="FT923-3822" num="33" wdcount="6"> Shades of Saint Therese of Lisieux.</s>

<s docid="FT923-3822" num="34" wdcount="12"> Lots of action in the kitchen; something is hidden in the cellar.</s>

<s docid="FT923-3822" num="35" wdcount="9"> Sacred Hunger by Barry Unsworth (Hamish Hamilton Pounds 15.99).</s>

<s docid="FT923-3822" num="36" wdcount="17"> Unsworth's massive novel about the 1750s slave trade came out early this year to widespread critical praise.</s>

<s docid="FT923-3822" num="37" wdcount="12"> The shipboard detail - the horrors of the trade -are brilliantly done.</s>

<s docid="FT923-3822" num="38" wdcount="22"> The judges will have to rule on the characterisation of the European protagonists who go off to found a Utopia in Florida.</s>

<s docid="FT923-3822" num="39" wdcount="28"> The judges this year, who will include Independent journalist Mark Lawson and John Coldstream, literary editor of The Daily Telegraph, will be chaired by the biographer Victoria Glendinning.</s>

<s docid="FT923-3822" num="40" wdcount="13"> The winner will be named at a Guildhall dinner on Tuesday October 13.</s>

<s docid="FT923-3822" num="41" wdcount="16"> Last year the prize was won by Ben Okri, for his book The Famished Road .</s>
</TEXT>
<PUB>

<s docid="FT923-3822" num="42" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT923-3822" num="43" wdcount="3"> London Page 15</s>
</PAGE>
</DOC>
