<DOC>
<DOCNO>

<s docid="FT943-3897" num="1" wdcount="1"> FT943-3897</s>
</DOCNO>
<PROFILE>

<s docid="FT943-3897" num="2" wdcount="1"> _AN-EILDEAC1FT</s>
</PROFILE>
<DATE>

<s docid="FT943-3897" num="3" wdcount="1"> 940912</s>
</DATE>
<HEADLINE>

<s docid="FT943-3897" num="4" wdcount="22"> FT 12 SEP 94 / Arts: Literature turns over an old leaf - Jackie Wullschlager looks at changing attitudes to the novel</s>
</HEADLINE>
<BYLINE>

<s docid="FT943-3897" num="5" wdcount="3"> By JACKIE WULLSCHLAGER</s>
</BYLINE>
<TEXT>

<s docid="FT943-3897" num="6" wdcount="41"> It is a sensational shortlist: a bestseller about love and hypnotism, a blockbuster about battles and brides in Ruritania, and a pornographic shocker about teenage sex and baby murder so explicit that only an obscure Newcastle publisher would risk printing it.</s>

<s docid="FT943-3897" num="7" wdcount="26"> Out are the eminences gris of Victorian letters - novels by Thomas Hardy and Mrs Humphry Ward, who advised Gladstone and Roosevelt, didn't make the grade.</s>

<s docid="FT943-3897" num="8" wdcount="24"> This week the shortlist for the hypothetical 1894 Booker Prize will be announced by six judges, including biographer Victoria Glendinning and broadcaster Melvyn Bragg.</s>

<s docid="FT943-3897" num="9" wdcount="52"> They have avoided dull and worthy classics and chosen six books which stirred the fin de siecle world and remain compelling today: George du Maurier's Trilby, Anthony Hope's The Prisoner of Zenda, George Moore's Esther Waters, Kipling's Jungle Book, George Gissing's In the Year of Jubilee and RL Stevenson's The Ebb Tide.</s>

<s docid="FT943-3897" num="10" wdcount="22"> The winner will be revealed on October 15 (four days after the 1994 Booker Prize ceremony) at the Cheltenham Festival of Literature.</s>

<s docid="FT943-3897" num="11" wdcount="24"> Like today's Booker Prize, it is a publishing gimmick; Everyman, which is backing the spoof award, is a significant publisher of classic Victorian novels.</s>

<s docid="FT943-3897" num="12" wdcount="12"> But the retrospective Booker is also a fascinating exercise in historical reconstruction.</s>

<s docid="FT943-3897" num="13" wdcount="18"> It raises questions about how the relationship between literature and society has changed in the past 100 years.</s>

<s docid="FT943-3897" num="14" wdcount="3"> First, the similarities.</s>

<s docid="FT943-3897" num="15" wdcount="7"> A good yarn is a good yarn.</s>

<s docid="FT943-3897" num="16" wdcount="37"> Of the 1894 books, Trilby is the tale of a tone-deaf model who sings like an angel when mesmerised by the sinister hypnotist Svengali, then croaks like a crow when he dies during one of her concerts.</s>

<s docid="FT943-3897" num="17" wdcount="18"> The Prisoner of Zenda tells of an Englishman impersonating the King of Ruritania and rescuing him from demons.</s>

<s docid="FT943-3897" num="18" wdcount="29"> On the 1994 list Romesh Guneskera's Reef is about a Sri Lankan servant boy and his mysterious master, while Jill Paton Walsh's Knowledge of Angels re-enacts the wolf-child legend.</s>

<s docid="FT943-3897" num="19" wdcount="9"> All the books on both lists are gripping stories.</s>

<s docid="FT943-3897" num="20" wdcount="5"> The lists share key themes.</s>

<s docid="FT943-3897" num="21" wdcount="29"> Both, for instance, have books about colonial exploitation - Stevenson's The Ebb Tide and Abdulrazak Gurnah's Paradise, which is set in the First World War in German East Africa.</s>

<s docid="FT943-3897" num="22" wdcount="5"> Both provoke in similar ways.</s>

<s docid="FT943-3897" num="23" wdcount="36"> The controversial books of 1894 were Trilby, with its louche vie boheme milieu, and Esther Waters, in which a 17-year-old girl is seduced, impregnated and offered the services of a professional baby killer for a fiver.</s>

<s docid="FT943-3897" num="24" wdcount="26"> It is now seen as Moore's best work, but in 1894 it had problems finding a publisher and the powerful circulating libraries refused to take it.</s>

<s docid="FT943-3897" num="25" wdcount="12"> A century on, the relationship between fiction and sexual morality remains vexed.</s>

<s docid="FT943-3897" num="26" wdcount="29"> Last week, a Times critic complained about the inclusion of Alan Hollinghurst's candid novel of homosexual love, The Folding Star, on the Booker list, because it offended Judaeo-Christian ethics.</s>

<s docid="FT943-3897" num="27" wdcount="30"> But even if Hollinghurst wins the Booker, his novel will not become the succes de scandale of Esther Waters and Trilby, which became the bestselling novel of the 19th century.</s>

<s docid="FT943-3897" num="28" wdcount="21"> For the great difference between then and now is that in 1894 a Booker Prize was not needed to sell fiction.</s>

<s docid="FT943-3897" num="29" wdcount="22"> Today, we accept the gap between literary writing, such as Hollinghurst's, and popular bestsellers by writers like Jeffrey Archer and Barbara Cartland.</s>

<s docid="FT943-3897" num="30" wdcount="23"> This is the gap the Booker tries to bridge by giving high-level publicity to works which would not normally reach a mass audience.</s>

<s docid="FT943-3897" num="31" wdcount="18"> The trick works - last year's winner, Roddy Doyle's Paddy Clarke Ha Ha Ha sold 360,000 hardback copies.</s>

<s docid="FT943-3897" num="32" wdcount="8"> Before the short-list was announced it sold 10,600.</s>

<s docid="FT943-3897" num="33" wdcount="9"> The Victorians, in contrast, were lovers of contemporary fiction.</s>

<s docid="FT943-3897" num="34" wdcount="19"> Novels accounted for 20 per cent of published books, and no distinction was made between high and low art.</s>

<s docid="FT943-3897" num="35" wdcount="19"> In the mid 19th century, Dickens made Pounds 12,000 for Little Dorrit, the equivalent of nearly Pounds 400,000 today.</s>

<s docid="FT943-3897" num="36" wdcount="29"> Between 1861 and 1894, when the population of the UK was half that of today and the literate population smaller still, Mrs Henry Wood's East Lynne sold 400,000 copies.</s>

<s docid="FT943-3897" num="37" wdcount="24"> All the 1894 Booker writers were popular names; they were also serious, skilful writers whose books can be reread with pleasure 100 years later.</s>

<s docid="FT943-3897" num="38" wdcount="12"> Why was fiction so much closer to the public heart in 1894?</s>

<s docid="FT943-3897" num="39" wdcount="8"> Social, cultural and psychological reasons play a part.</s>

<s docid="FT943-3897" num="40" wdcount="39"> Socially, the 1890s reading public was a vastly more homogenous group than today: a small number of middle class authors wrote for a middle class audience at a time when to be literate was to belong to an elite.</s>

<s docid="FT943-3897" num="41" wdcount="11"> The idea of a two-tier, up and down-market, fiction was irrelevant.</s>

<s docid="FT943-3897" num="42" wdcount="22"> Culturally, these writers and readers were certain of their place in the mainstream, and the novel was their political and intellectual forum.</s>

<s docid="FT943-3897" num="43" wdcount="18"> Today we no longer share the Victorian confidence in the novel as a key genre of our age.</s>

<s docid="FT943-3897" num="44" wdcount="26"> Modernism and the overturning of the traditional form by Joyce and Woolf weakened 20th-century belief in the novel and encouraged the divergence between highbrow and lowbrow.</s>

<s docid="FT943-3897" num="45" wdcount="23"> The dominance of film and television has made novels a more marginal form and perhaps they no longer attract the most creative talents.</s>

<s docid="FT943-3897" num="46" wdcount="20"> George du Maurier originally offered the outline of Trilby to Henry James, who he thought would write a better novel.</s>

<s docid="FT943-3897" num="47" wdcount="12"> Today du Maurier would have sold it to Hollywood or the BBC.</s>

<s docid="FT943-3897" num="48" wdcount="33"> The fantasy element of fiction, in which we identify with characters as if we know them, was answered in the 19th century by the novel; in the 20th century we have TV soaps.</s>

<s docid="FT943-3897" num="49" wdcount="42"> Just as the tabloid newspapers feature characters from EastEnders, so when Dickens' The Old Curiosity Shop was running as a serial there was widespread press speculation on whether Little Nell would die, and readers wrote in begging for her to be saved.</s>

<s docid="FT943-3897" num="50" wdcount="16"> Sentimentality, accessibility, topicality - what characterises today's soaps were clear features of the novel in 1894.</s>

<s docid="FT943-3897" num="51" wdcount="32"> Both In the Year of Jubilee and Esther Waters, for example, centre on the burning 1890s debate about marriage, feminism and the 'New Woman', yet both are also tearjerkers which everyone enjoyed.</s>

<s docid="FT943-3897" num="52" wdcount="18"> The 1894 books are compelling because they prefigure our own times and yet are set back from them.</s>

<s docid="FT943-3897" num="53" wdcount="32"> Trilby is a tale of hypnotism and the unconscious a decade away from Freud; The Ebb Tide paved the way for Conrad's Heart of Darkness and the first questioning of colonial oppression.</s>

<s docid="FT943-3897" num="54" wdcount="16"> It is unlikely that the 1994 Booker choices will speak as eloquently of new trends today.</s>

<s docid="FT943-3897" num="55" wdcount="29"> Whereas the 1894 titles had contemporary settings, many of the 1994 books are historical (such as Paradise) or are driven by nostalgia (such as Beside the Ocean of Time).</s>

<s docid="FT943-3897" num="56" wdcount="26"> Which book will win on October 15? Stevenson will get the sympathy vote because he died in 1894 in Samoa, the setting of The Ebb Tide.</s>

<s docid="FT943-3897" num="57" wdcount="50"> Jungle Book will get the retrospective vote, because it is the best-known today and has fashionable mythic overtones in the lost paradise of Mowgli's jungle; its position on the list may also rescue it from schmaltzy Disney associations and confirm it as a serious novel about a young man's self-discovery.</s>

<s docid="FT943-3897" num="58" wdcount="5"> My vote goes to Trilby.</s>

<s docid="FT943-3897" num="59" wdcount="37"> Soft-focus, ideologically shaky - in its anti-Semitic portrait of Svengali - and sometimes sloppy, it is a story of demonic possession and haunts the imagination like a fairy tale long after better-written works have faded from memory.</s>

<s docid="FT943-3897" num="60" wdcount="32"> Like Rebecca, the popular novel by du Maurier's granddaughter, it is a natural equivalent of what the current Booker Prize seeks to create: a combination of the classic and the bestseller .</s>
</TEXT>
<XX>

<s docid="FT943-3897" num="61" wdcount="1"> Countries:-</s>
</XX>
<CN>

<s docid="FT943-3897" num="62" wdcount="5"> GBZ United Kingdom, EC .</s>
</CN>
<XX>

<s docid="FT943-3897" num="63" wdcount="1"> Industries:-</s>
</XX>
<IN>

<s docid="FT943-3897" num="64" wdcount="3"> P2731 Book Publishing.</s>

<s docid="FT943-3897" num="65" wdcount="4"> P8999 Services, NEC .</s>
</IN>
<XX>

<s docid="FT943-3897" num="66" wdcount="1"> Types:-</s>
</XX>
<TP>

<s docid="FT943-3897" num="67" wdcount="4"> NEWS General News .</s>
</TP>
<PUB>

<s docid="FT943-3897" num="68" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT943-3897" num="69" wdcount="3"> London Page 13</s>
</PAGE>
</DOC>
