<DOC>
<DOCNO>

<s docid="FT944-16774" num="1" wdcount="1"> FT944-16774</s>
</DOCNO>
<PROFILE>

<s docid="FT944-16774" num="2" wdcount="1"> _AN-EJLD6AB9FT</s>
</PROFILE>
<DATE>

<s docid="FT944-16774" num="3" wdcount="1"> 941012</s>
</DATE>
<HEADLINE>

<s docid="FT944-16774" num="4" wdcount="11"> FT 12 OCT 94 / Judges split as Kelman wins Booker</s>
</HEADLINE>
<BYLINE>

<s docid="FT944-16774" num="5" wdcount="7"> By ANNALENA MCAFEE, Arts and Literary Editor</s>
</BYLINE>
<TEXT>

<s docid="FT944-16774" num="6" wdcount="42"> After hours of heated delib-eration - under a system described as 'mad' by one judge - the Pounds 20,000 Booker Prize for fiction last night went to Mr James Kelman for How Late It Was, How Late, published by Secker and Warburg.</s>

<s docid="FT944-16774" num="7" wdcount="41"> The novel, a story of Scottish low-life narrated largely in Glaswegian dialect, is unlikely to prove a popular choice with booksellers, who have damned all six books shortlisted for the prize as boring, elitist and - worst of all - unsaleable.</s>

<s docid="FT944-16774" num="8" wdcount="19"> Professor John Bayley, chairman of the Booker judges, acknowledged that Mr Kelman's book in particular might be deemed inaccessible.</s>

<s docid="FT944-16774" num="9" wdcount="18"> 'We had an extremely difficult final meeting and were very divided,' he said after three hours of debate.</s>

<s docid="FT944-16774" num="10" wdcount="19"> Rabbi Julia Neuberger, the only woman on the judging panel, said she was made extremely cross by the decision.</s>

<s docid="FT944-16774" num="11" wdcount="10"> 'It's just a drunken Scotsman railing against bureaucracy,' she said.</s>

<s docid="FT944-16774" num="12" wdcount="6"> 'My eyes are stretched in disbelief.</s>

<s docid="FT944-16774" num="13" wdcount="6"> The voting system is completely mad.</s>

<s docid="FT944-16774" num="14" wdcount="10"> Kelman was the least favourite of the three front runners.</s>

<s docid="FT944-16774" num="15" wdcount="12"> If it had been a short story it would have been fine'.</s>

<s docid="FT944-16774" num="16" wdcount="17"> Mr Kelman's book is, according to some observers, the most difficult work to have won the prize.</s>

<s docid="FT944-16774" num="17" wdcount="28"> In his acceptance speech, Mr Kelman, perceived by some as a Scottish isolationist, anticipated the criticism, by declaring: 'My culture and my language have the right to exist'.</s>

<s docid="FT944-16774" num="18" wdcount="35"> One guest at the prize-giving dinner at London's Guildhall, Mr Salman Rushdie, who won the prize in 1981 with Midnight's Children, remarked: 'James Kelman is good, but not as good as he thinks he is'.</s>

<s docid="FT944-16774" num="19" wdcount="11"> The Booker prize has, in its 26-year history, always provoked controversy.</s>

<s docid="FT944-16774" num="20" wdcount="11"> But this year's rows have been of a particularly fine vintage.</s>

<s docid="FT944-16774" num="21" wdcount="12"> Prof Bayley went on record with a rousing condemnation of contemporary fiction.</s>

<s docid="FT944-16774" num="22" wdcount="34"> Another judge, Mr James Wood, literary critic of The Guardian, was attacked for failing to reveal that a young novelist being considered for the award, Ms Claire Messud, was in fact Mrs James Wood.</s>

<s docid="FT944-16774" num="23" wdcount="16"> Most damaging of all was the verdict of the booksellers, who dismissed the shortlist as narcoleptic.</s>

<s docid="FT944-16774" num="24" wdcount="35"> The other contenders were The Folding Star by Alan Hollinghurst, Beside the Ocean of Time by George Mackay Brown, Paradise by Abdulrazak Gurnah, Reef by Romesh Gunesekera and Knowledge of Angels by Jill Paton Walsh.</s>

<s docid="FT944-16774" num="25" wdcount="19"> In spite of heavy publicity, the novels nominated have been selling 50 per cent less than last year's shortlist.</s>

<s docid="FT944-16774" num="26" wdcount="13"> Last year's winner, Roddy Doyle's Paddy Clarke Ha Ha Ha, sold 350,000 copies.</s>

<s docid="FT944-16774" num="27" wdcount="12"> 'Kelman's novel is unlikely to come anywhere near that,' one bookseller said.</s>

<s docid="FT944-16774" num="28" wdcount="16"> Mr Kelman was also shortlisted for the prize in 1989 for his novel A Disaffection .</s>
</TEXT>
<XX>

<s docid="FT944-16774" num="29" wdcount="1"> Countries:-</s>
</XX>
<CN>

<s docid="FT944-16774" num="30" wdcount="5"> GBZ United Kingdom, EC .</s>
</CN>
<XX>

<s docid="FT944-16774" num="31" wdcount="1"> Industries:-</s>
</XX>
<IN>

<s docid="FT944-16774" num="32" wdcount="4"> P8999 Services, NEC .</s>
</IN>
<XX>

<s docid="FT944-16774" num="33" wdcount="1"> Types:-</s>
</XX>
<TP>

<s docid="FT944-16774" num="34" wdcount="4"> NEWS General News .</s>
</TP>
<PUB>

<s docid="FT944-16774" num="35" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT944-16774" num="36" wdcount="3"> London Page 12</s>
</PAGE>
</DOC>
