<DOC>
<DOCNO>

<s docid="FT943-5106" num="1" wdcount="1"> FT943-5106</s>
</DOCNO>
<PROFILE>

<s docid="FT943-5106" num="2" wdcount="1"> _AN-EIFD0ACCFT</s>
</PROFILE>
<DATE>

<s docid="FT943-5106" num="3" wdcount="1"> 940906</s>
</DATE>
<HEADLINE>

<s docid="FT943-5106" num="4" wdcount="10"> FT 06 SEP 94 / Booker shortlist fields a 'B-team'</s>
</HEADLINE>
<BYLINE>

<s docid="FT943-5106" num="5" wdcount="7"> By ANNALENA MCAFEE, Arts and Literary Editor</s>
</BYLINE>
<TEXT>

<s docid="FT943-5106" num="6" wdcount="25"> The shortlist of six for the Pounds 20,000 Booker Prize for fiction, announced yesterday, immediately prompted the question 'Who'? from many in the publishing industry.</s>

<s docid="FT943-5106" num="7" wdcount="13"> According to one insider, some on the list 'are B-team writers at best'.</s>

<s docid="FT943-5106" num="8" wdcount="64"> The six include Alan Hollinghurst's The Folding Star (published by Chatto and Windus), a melancholy study of homosexual obsession which was tipped as a likely candidate from the initial 'long list' of 15, The Reef (Granta) by young Sri Lankan writer Romesh Gunesekera and How Late It Was, How Late (Secker and Warburg) by gritty Glasgow realist James Kelman, which was almost universally well-reviewed.</s>

<s docid="FT943-5106" num="9" wdcount="50"> As for the other three - Knowledge of Angels (Green Bay) a philosophical fable by children's author Jill Paton Walsh, Paradise (Hamish Hamilton) by Zanzibar-born writer Abdulrazak Gurnah and Beside the Ocean of Time (John Murray) by 72-year-old Orcadian poet George Mackay Brown - 'frankly, they don't make the grade'.</s>

<s docid="FT943-5106" num="10" wdcount="43"> The shortlist for the Booker, the UK's most hyped literary prize and one of the most lucrative, is all the more surprising in a bumper year for new fiction fulfilling the criteria - English language and non-American - for consideration for the award.</s>

<s docid="FT943-5106" num="11" wdcount="25"> Margaret Atwood's The Robber Bride seems an astonishing omission, as do new novels by Peter Ackroyd, Peter Carey, Candia McWilliam, William Trevor and Jim Crace.</s>

<s docid="FT943-5106" num="12" wdcount="26"> But if the shortlist of the final six candidates for the prize may be disappointing, the traditional controversy surrounding the award is as rife as ever.</s>

<s docid="FT943-5106" num="13" wdcount="50"> One unsurprising omission from the final selection was When The World Was Steady, a first novel by Claire Messud, which was on the 'long list' before it was pointed out that the author was the wife of James Wood, chief literary reviewer of The Guardian newspaper and a Booker judge.</s>

<s docid="FT943-5106" num="14" wdcount="31"> Professor John Bayley, chairman of the Booker panel and husband of former Booker Prize winner Dame Iris Murdoch, expressed surprise at Mr Wood's failure to reveal his relationship with Ms Messud.</s>

<s docid="FT943-5106" num="15" wdcount="18"> But it is the final list, rather than the controversy, that discredits the award according to some critics.</s>

<s docid="FT943-5106" num="16" wdcount="17"> 'This list,' said one man of letters, 'must have dealt a final death blow to the Booker'.</s>

<s docid="FT943-5106" num="17" wdcount="14"> The winner, selected from an original 130, will be announced on October 11 .</s>
</TEXT>
<XX>

<s docid="FT943-5106" num="18" wdcount="1"> Countries:-</s>
</XX>
<CN>

<s docid="FT943-5106" num="19" wdcount="5"> GBZ United Kingdom, EC .</s>
</CN>
<XX>

<s docid="FT943-5106" num="20" wdcount="1"> Industries:-</s>
</XX>
<IN>

<s docid="FT943-5106" num="21" wdcount="4"> P8999 Services, NEC .</s>
</IN>
<XX>

<s docid="FT943-5106" num="22" wdcount="1"> Types:-</s>
</XX>
<TP>

<s docid="FT943-5106" num="23" wdcount="4"> NEWS General News .</s>
</TP>
<PUB>

<s docid="FT943-5106" num="24" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT943-5106" num="25" wdcount="3"> London Page 10</s>
</PAGE>
</DOC>
