<DOC>
<DOCNO>

<s docid="WSJ871110-0154" num="1" wdcount="1"> WSJ871110-0154</s>
</DOCNO>
<HL>

<s docid="WSJ871110-0154" num="2" wdcount="12"> 'Moon Tiger': A Dark Horse Takes the Booker --- By Terry Trucco</s>
</HL>
<DD>

<s docid="WSJ871110-0154" num="3" wdcount="1"> 11/10/87</s>
</DD>
<SO>

<s docid="WSJ871110-0154" num="4" wdcount="4"> WALL STREET JOURNAL (J)</s>
</SO>
<DATELINE>

<s docid="WSJ871110-0154" num="5" wdcount="1"> LONDON</s>
</DATELINE>
<TEXT>

<s docid="WSJ871110-0154" num="6" wdcount="17"> On the day of the Big Event, Ladbroke, the large British betting agency, posted the final odds.</s>

<s docid="WSJ871110-0154" num="7" wdcount="19"> Brian Moore was the favorite at 7-4, followed by Peter Ackroyd (5-2), Iris Murdoch (3-1) and Chinua Achebe (9-2).</s>

<s docid="WSJ871110-0154" num="8" wdcount="14"> The two dark horses, Nina Bawden and Penelope Lively, were each tipped at 7-1.</s>

<s docid="WSJ871110-0154" num="9" wdcount="19"> You may have noticed a distinctly literary tilt to that lineup, an affinity with the bookshelf, not the bookie.</s>

<s docid="WSJ871110-0154" num="10" wdcount="17"> All of those people published new works of fiction here in Britain during the past 12 months.</s>

<s docid="WSJ871110-0154" num="11" wdcount="39"> And for the last few weeks, literary punters throughout the British Isles have been placing bets on which of those writers would win the Booker Prize, the best-known, best-liked and, almost incidentally, most prestigious fiction award in the land.</s>

<s docid="WSJ871110-0154" num="12" wdcount="19"> In recent weeks the Booker contenders have received almost as much press coverage as the Charles and Di rift.</s>

<s docid="WSJ871110-0154" num="13" wdcount="15"> And nearly every article, from book reviews to author interviews, has featured the latest odds.</s>

<s docid="WSJ871110-0154" num="14" wdcount="24"> The betting is done largely by literary insiders, says Graham Sharpe, who sets the Booker odds at William Hill, Britain's other big betting agency.</s>

<s docid="WSJ871110-0154" num="15" wdcount="19"> "They read the books, hear the gossip and want to pull off a little coup for themselves," he says.</s>

<s docid="WSJ871110-0154" num="16" wdcount="24"> Last year's winner, "The Old Devils" by Kingsley Amis, was a 5-2 favorite, but this year, anyone who chose the victor made some dough.</s>

<s docid="WSJ871110-0154" num="17" wdcount="14"> "When she accepted her prize for "Moon Tiger," Penelope Lively looked surprised and pleased.</s>

<s docid="WSJ871110-0154" num="18" wdcount="22"> "I'm not a betting woman, and I have slight reservations about books becoming a spectator sport," she said in soft Oxbridge tones.</s>

<s docid="WSJ871110-0154" num="19" wdcount="15"> "But those who are in the know tell me that 7-1 was an irresistible flutter".</s>

<s docid="WSJ871110-0154" num="20" wdcount="10"> Her 65-year-old mother was among those who made a killing.</s>

<s docid="WSJ871110-0154" num="21" wdcount="30"> America has the Pulitzer Prize for fiction and the National Book Awards, but in terms of excitement, hoopla and man-on-the-street interest, there's nothing akin to the 15,000-pound ($26,000) Booker Prize.</s>

<s docid="WSJ871110-0154" num="22" wdcount="16"> With the possible exception of France's respected Prix Goncourt, there's nothing quite like it anywhere else.</s>

<s docid="WSJ871110-0154" num="23" wdcount="20"> Britons wryly compare the Booker to the Academy Awards, and though there's just one prize and no envelope, similarities exist.</s>

<s docid="WSJ871110-0154" num="24" wdcount="10"> There's a team of judges and a pool of candidates.</s>

<s docid="WSJ871110-0154" num="25" wdcount="16"> This year each British publisher could submit three new titles, for a grand total of 93.</s>

<s docid="WSJ871110-0154" num="26" wdcount="38"> As one judge noted wearily, "By August, I was in more than a slight panic, sometimes reading all day and evening; reading while standing at the bus stop, reading while cooking, reading, almost, while talking on the telephone".</s>

<s docid="WSJ871110-0154" num="27" wdcount="17"> Next comes the "short-list," the judges' top six, which was announced with great fanfare in late September.</s>

<s docid="WSJ871110-0154" num="28" wdcount="14"> This year the works included Brian Moore's political thriller "The Color of Blood" (E.P.</s>

<s docid="WSJ871110-0154" num="29" wdcount="18"> Dutton, 182 pages, $16.95); Peter Ackroyd's "Chatterton" (Grove Press, 240 pages, $17.95); Nina Bawden's "Circles of Deceit" (St.</s>

<s docid="WSJ871110-0154" num="30" wdcount="38"> Martin's Press, 208 pages, $14.95); Iris Murdoch's 23rd novel "The Book and the Brotherhood" (Viking, 608 pages, $19.95); Nigerian writer Chinua Achebe's "Anthills of the Savannah" (Doubleday, 240 pages, $16.95); and "Moon Tiger" (Grove Press, 216 pages, $15.95).</s>

<s docid="WSJ871110-0154" num="31" wdcount="33"> The awards presentation came on the last Thursday in October, and like any major awards presentation, it came complete with limousines, banquet (salmon mousse, champagne sorbet and English roast beef) and television cameras.</s>

<s docid="WSJ871110-0154" num="32" wdcount="15"> The suspense was genuine; the judges chose the winner just three hours before the announcement.</s>

<s docid="WSJ871110-0154" num="33" wdcount="18"> To be sure, the ratings for the prime-time broadcast didn't upstage those of "Eastenders," Britain's popular soap opera.</s>

<s docid="WSJ871110-0154" num="34" wdcount="22"> Yet interest was sufficient for Andre Deutsch, "Moon Tiger's" British publisher, to order up an additional 20,000 copies almost the minute Mrs.</s>

<s docid="WSJ871110-0154" num="35" wdcount="9"> Lively -- and the nation -- heard the news.</s>

<s docid="WSJ871110-0154" num="36" wdcount="26"> By British standards, sales figures for recent Booker winners are stunning, from "The Old Devils" (80,000 hard-cover copies) to Anita Brookner's "Hotel du Lac" (40,000 copies).</s>

<s docid="WSJ871110-0154" num="37" wdcount="22"> Even Keri Hulme's "The Bone People," a look at Maori culture that most readers found impenetrable, reached a respectable 21,000 in 1985.</s>

<s docid="WSJ871110-0154" num="38" wdcount="18"> Short-listed authors are just a few paces behind, sharing the best-seller list with Dick Francis and Scott Turow.</s>

<s docid="WSJ871110-0154" num="39" wdcount="17"> Heinemann initially printed 3,000 copies of "Anthills of the Savannah," the usual run for contemporary literary fiction.</s>

<s docid="WSJ871110-0154" num="40" wdcount="6"> So far, 10,000 copies have sold.</s>

<s docid="WSJ871110-0154" num="41" wdcount="17"> "Being short-listed probably changed the destiny of that book," declares a member of the Heinemann sales staff.</s>

<s docid="WSJ871110-0154" num="42" wdcount="18"> Indeed, there's currently talk of initiating a similar prize with a similar purse for the year's best biography.</s>

<s docid="WSJ871110-0154" num="43" wdcount="23"> Another notable spinoff is the Booker harpies, readers intent on digesting all six titles, then vigorously disputing the choices, which never please everyone.</s>

<s docid="WSJ871110-0154" num="44" wdcount="28"> This year the Sunday Times offered readers a complete autographed collection of the six books for the equivalent of $112, perfect fodder for the literary cocktail party cot.</s>

<s docid="WSJ871110-0154" num="45" wdcount="7"> It wasn't always this way, of course.</s>

<s docid="WSJ871110-0154" num="46" wdcount="20"> Headlines were modest back in 1969 when P.H. Newby won the first ever Booker Prize for "Something to Answer For".</s>

<s docid="WSJ871110-0154" num="47" wdcount="22"> (The wonderfully appropriate name comes from Booker-McConnell PLC, the international food and agriculture conglomerate that puts up the prize money each year).</s>

<s docid="WSJ871110-0154" num="48" wdcount="28"> The idea was to devise a British equivalent to the Prix Goncourt, and like that august French award, the Booker attracted attention the minute it kicked up controversy.</s>

<s docid="WSJ871110-0154" num="49" wdcount="20"> The early fuss was kept within the literary world, with critics sniping over choices and the prize's varied ground rules.</s>

<s docid="WSJ871110-0154" num="50" wdcount="40"> The real world took notice in 1974, when Elizabeth Jane Howard, one of the three judges, wrote a letter to the Times claiming that in her opinion Kingsley Amis's "Ending Up," one of the short-listed books, was his best ever.</s>

<s docid="WSJ871110-0154" num="51" wdcount="12"> As it happens, she was married to Mr. Amis at the time.</s>

<s docid="WSJ871110-0154" num="52" wdcount="3"> He didn't win.</s>

<s docid="WSJ871110-0154" num="53" wdcount="26"> But many credit the Booker's current appeal to the 1982 competition and Thomas Keneally's "Schindler's Ark," or "Schindler's List" as it is known in the U.S.</s>

<s docid="WSJ871110-0154" num="54" wdcount="25"> Written as a novel, the book told the true story of a remarkable German who saved the lives of hundreds of Jews in concentration camps.</s>

<s docid="WSJ871110-0154" num="55" wdcount="14"> But even after it won the Booker, people argued that it wasn't a novel.</s>

<s docid="WSJ871110-0154" num="56" wdcount="18"> "The more people questioned it, the more it sold," says Ion Trewin, editorial director at Hodder & Stoughton.</s>

<s docid="WSJ871110-0154" num="57" wdcount="13"> "That was the first year the prize caught the media and public imagination.</s>

<s docid="WSJ871110-0154" num="58" wdcount="8"> Suddenly the Booker gained inches on front pages".</s>

<s docid="WSJ871110-0154" num="59" wdcount="27"> Oh yes, "Moon Tigers" is a dying woman's recollection of her life as a World War II war correspondent and her affair with a young tank officer.</s>

<s docid="WSJ871110-0154" num="60" wdcount="11"> --- Ms. Trucco is a free-lance writer based in London .</s>
</TEXT>
</DOC>
