<DOC>
<DOCNO>

<s docid="AP900119-0051" num="1" wdcount="1"> AP900119-0051</s>
</DOCNO>
<FILEID>

<s docid="AP900119-0051" num="2" wdcount="2"> AP-NR-01-19-90 0645EST</s>
</FILEID>
<FIRST>

<s docid="AP900119-0051" num="3" wdcount="5"> r a PM-PreschoolMolest-Scene 01-19 0404</s>
</FIRST>
<SECOND>

<s docid="AP900119-0051" num="4" wdcount="2"> PM-Preschool Molest-Scene,0420</s>
</SECOND>
<HEAD>

<s docid="AP900119-0051" num="5" wdcount="8"> `I'd Like to Have No Memories of This'</s>
</HEAD>
<HEAD>

<s docid="AP900119-0051" num="6" wdcount="4"> With PM-Preschool Molest, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP900119-0051" num="7" wdcount="3"> By JENNIFER BOWLES</s>
</BYLINE>
<BYLINE>

<s docid="AP900119-0051" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900119-0051" num="9" wdcount="4"> MANHATTAN BEACH, Calif. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900119-0051" num="10" wdcount="28"> ``Ray Will Die'' is scrawled in big black letters on the faded green paint of the McMartin Pre-School, testimony to the rage inflamed by the notorious child-molesting case.</s>

<s docid="AP900119-0051" num="11" wdcount="20"> Former McMartin teachers Raymond Buckey and his mother, Peggy McMartin Buckey, were acquitted Thursday of 52 charges of molesting students.</s>

<s docid="AP900119-0051" num="12" wdcount="7"> Jurors were deadlocked on 13 other counts.</s>

<s docid="AP900119-0051" num="13" wdcount="35"> Whatever happens on those charges, few in this upper-middle-class Los Angeles suburb would disagree with the judge in the trial, William Pounders, who once said, ``The case has poisoned everyone who had contact with it''.</s>

<s docid="AP900119-0051" num="14" wdcount="33"> Sue Brown, a receptionist at a medical office across the street from the school, said she had two friends who were involved in the case and had been convinced of the Buckeys' guilt.</s>

<s docid="AP900119-0051" num="15" wdcount="8"> ``I think they got off scot-free,'' Brown said.</s>

<s docid="AP900119-0051" num="16" wdcount="5"> ``I'm really sick about it''.</s>

<s docid="AP900119-0051" num="17" wdcount="24"> Alan Lagunoff, whose son, now 10, testified against the Buckeys, stood in front of the run-down, long-closed nursery school and talked about his disappointment.</s>

<s docid="AP900119-0051" num="18" wdcount="23"> ``The defense did everything to prolong the case and the prosecution did not do enough research to prosecute the case properly,'' he said.</s>

<s docid="AP900119-0051" num="19" wdcount="21"> A cold wind blasted leaves across the schoolyard as Lagunoff leaned on the rusted chain-link fence surrounding the dilapidated L-shaped building.</s>

<s docid="AP900119-0051" num="20" wdcount="14"> ``I'd like to see the school become a center for abused children,'' he said.</s>

<s docid="AP900119-0051" num="21" wdcount="13"> ``It should be put to some good use rather than tear it down''.</s>

<s docid="AP900119-0051" num="22" wdcount="7"> But another longtime Manhattan Beach resident disagreed.</s>

<s docid="AP900119-0051" num="23" wdcount="10"> ``I'd like to see it torn down,'' said Brenda Platt.</s>

<s docid="AP900119-0051" num="24" wdcount="8"> ``I'd like to have no memories of this''.</s>

<s docid="AP900119-0051" num="25" wdcount="26"> Platt, who has two children aged 1 and 3, said she has serious doubts about placing them in a day-care center because of the McMartin trial.</s>

<s docid="AP900119-0051" num="26" wdcount="13"> ``I think (the McMartin case) is a disgrace to Manhattan Beach and society.</s>

<s docid="AP900119-0051" num="27" wdcount="5"> It's totally upsetting,'' Platt said.</s>

<s docid="AP900119-0051" num="28" wdcount="11"> Linda Geisert, another resident of the beach city, was also upset.</s>

<s docid="AP900119-0051" num="29" wdcount="15"> ``I'm greatly disappointed in the legal system and quite frankly in the jurors,'' Geisert said.</s>

<s docid="AP900119-0051" num="30" wdcount="18"> For all his disappointment, Lagunoff said he did not feel the prosecutors should retry the remaining 13 counts.</s>

<s docid="AP900119-0051" num="31" wdcount="11"> ``It would be just more of the same circus,'' he said.</s>

<s docid="AP900119-0051" num="32" wdcount="14"> ``We put so much faith and hope in our courts,'' said Robert Canter, 74.</s>

<s docid="AP900119-0051" num="33" wdcount="8"> ``And this is what we get _ frustration.''</s>
</TEXT>
</DOC>
