<DOC>
<DOCNO>

<s docid="AP900118-0183" num="1" wdcount="1"> AP900118-0183</s>
</DOCNO>
<FILEID>

<s docid="AP900118-0183" num="2" wdcount="2"> AP-NR-01-18-90 2219EST</s>
</FILEID>
<FIRST>

<s docid="AP900118-0183" num="3" wdcount="5"> r a AM-PreschoolMolest-Reax 01-18 0866</s>
</FIRST>
<SECOND>

<s docid="AP900118-0183" num="4" wdcount="2"> AM-Preschool Molest-Reax,0899</s>
</SECOND>
<HEAD>

<s docid="AP900118-0183" num="5" wdcount="8"> Parents, Jurors and Family Members React To Verdicts</s>
</HEAD>
<HEAD>

<s docid="AP900118-0183" num="6" wdcount="4"> With AM-Preschool Molest, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP900118-0183" num="7" wdcount="4"> By RICHARD DE ATLEY</s>
</BYLINE>
<BYLINE>

<s docid="AP900118-0183" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900118-0183" num="9" wdcount="3"> LOS ANGELES (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900118-0183" num="10" wdcount="30"> Thursday's acquittals in the McMartin Pre-School molestation case outraged parents who said prosecutors botched it, while those on the defense side proclaimed a triumph of justice over hysteria and hype.</s>

<s docid="AP900118-0183" num="11" wdcount="16"> Mother-and-son defendants Peggy McMartin Buckey, 63, and Raymond Buckey, 31, wept as the verdicts were announced.</s>

<s docid="AP900118-0183" num="12" wdcount="17"> Jurors found the pair innocent of 52 charges and couldn't reach a verdict on 13 other counts.</s>

<s docid="AP900118-0183" num="13" wdcount="12"> Prosecutors must decide whether to try those charges in a new trial.</s>

<s docid="AP900118-0183" num="14" wdcount="10"> ``I just said, `I told you Ray,''' Mrs. Buckey said.</s>

<s docid="AP900118-0183" num="15" wdcount="8"> Asked if her son was surprised, she said.</s>

<s docid="AP900118-0183" num="16" wdcount="4"> ``He had fear, definitely''.</s>

<s docid="AP900118-0183" num="17" wdcount="11"> Buckey avoided reporters and slipped out the courthouse with his lawyer.</s>

<s docid="AP900118-0183" num="18" wdcount="14"> ``If it can happen to seven innocent people it can happen to you, too.</s>

<s docid="AP900118-0183" num="19" wdcount="17"> If it had not been in my faith in God I wouldn't be here today,'' she said.</s>

<s docid="AP900118-0183" num="20" wdcount="17"> But several parents of former students at the school said the Buckeys won because the system lost.</s>

<s docid="AP900118-0183" num="21" wdcount="18"> ``It was never done properly,'' said parent Alan Lagunoff, who moved to Central California from suburban Manhattan Beach.</s>

<s docid="AP900118-0183" num="22" wdcount="14"> ``I have to sit back and figure out what to do with my son.</s>

<s docid="AP900118-0183" num="23" wdcount="19"> I fear that because of this verdict, no child will be seen as a credible witness from now on''.</s>

<s docid="AP900118-0183" num="24" wdcount="17"> His son, now 10, attended the school for 1 years but wasn't a witness at the trial.</s>

<s docid="AP900118-0183" num="25" wdcount="14"> ``I don't think it's worth it to bring this thing back into the courts.</s>

<s docid="AP900118-0183" num="26" wdcount="9"> It will just be another six-year travesty,'' Lagunoff said.</s>

<s docid="AP900118-0183" num="27" wdcount="26"> ``The system is not going to protect children,'' said Jackie McGauley, a parent who believes her child had been molested but didn't testify in the case.</s>

<s docid="AP900118-0183" num="28" wdcount="14"> ``I don't know what the message is that the jury wanted to get out.</s>

<s docid="AP900118-0183" num="29" wdcount="5"> I'm anxious to hear that''.</s>

<s docid="AP900118-0183" num="30" wdcount="30"> Charles Buckey, father of Raymond and husband of Mrs. Buckey, suggested Deputy District Attorney Lael Rubin, who prosecuted the case for its entire six years, was motivated by personal ambition.</s>

<s docid="AP900118-0183" num="31" wdcount="16"> ``My concern primarily was Lael Rubin, who is `anything goes' in order to secure a conviction.</s>

<s docid="AP900118-0183" num="32" wdcount="11"> ... If you don't win, you don't get promoted,'' he said.</s>

<s docid="AP900118-0183" num="33" wdcount="20"> Juror Brenda Williams said the evidence failed to convince the jury beyond a reasonable doubt in 52 of the charges.</s>

<s docid="AP900118-0183" num="34" wdcount="24"> ``Even if you accept that the children were molested, it didn't necessarily mean they were molested at the McMartin Pre-School,'' Ms. Williams told reporters.</s>

<s docid="AP900118-0183" num="35" wdcount="37"> Raymond Buckey spent nearly five years in jail without bail during the case, which defense attorneys said was the result of community hysteria sparked by bizarre allegations by the alcoholic mother of one child at the preschool.</s>

<s docid="AP900118-0183" num="36" wdcount="31"> Some observers accused then-District Attorney Robert Philibosian of using the spectacular charges to boost his failing re-election campaign against Ira Reiner, who beat him and now runs the district attorney's office.</s>

<s docid="AP900118-0183" num="37" wdcount="11"> Philibosian, however, insisted he would not have handled the matter differently.</s>

<s docid="AP900118-0183" num="38" wdcount="22"> ``Ira Reiner has had that case for five years, and I am not going to take any public criticism directed at me.</s>

<s docid="AP900118-0183" num="39" wdcount="13"> Let him respond to the criticism,'' said Philibosian, now in private law practice.</s>

<s docid="AP900118-0183" num="40" wdcount="25"> Also criticized was the decision by investigators to use a private child therapy group, Children's Institute International, to conduct the original interviews with the children.</s>

<s docid="AP900118-0183" num="41" wdcount="13"> Defense attorneys maintained that questions by the institute's researchers were leading and prejudicial.</s>

<s docid="AP900118-0183" num="42" wdcount="2"> Jurors agreed.</s>

<s docid="AP900118-0183" num="43" wdcount="14"> ``We never got the children's stories in their own words,'' said juror John Breese.</s>

<s docid="AP900118-0183" num="44" wdcount="10"> Children's Institute officials didn't immediately return telephone calls seeking comment.</s>

<s docid="AP900118-0183" num="45" wdcount="29"> Originally, there were seven defendants, including Raymond Buckey's sister, Peggy Ann Buckey, and Virginia McMartin, the founder of the school, mother of Mrs. Buckey and grandmother of Raymond Buckey.</s>

<s docid="AP900118-0183" num="46" wdcount="27"> Hundreds of allegations of child molestation were filed in the case, which gained worldwide attention with its tales of underground tunnels at the school and Satanic rituals.</s>

<s docid="AP900118-0183" num="47" wdcount="25"> The focus of the case shifted dramatically over the years as Reiner reduced the number of charges and dropped five defendants after reviewing the case.</s>

<s docid="AP900118-0183" num="48" wdcount="6"> The underground tunnels were never found.</s>

<s docid="AP900118-0183" num="49" wdcount="8"> No proof was ever produced of Satanic rituals.</s>

<s docid="AP900118-0183" num="50" wdcount="13"> Reiner said the system must be changed to prevent such long, expensive prosecution.</s>

<s docid="AP900118-0183" num="51" wdcount="19"> ``It took far too long and cost far too much money to have what has been called perfect justice.</s>

<s docid="AP900118-0183" num="52" wdcount="21"> We need reform,'' Reiner said, adding that in trying to describe the case, ``Insane is the word that comes to mind''.</s>

<s docid="AP900118-0183" num="53" wdcount="18"> The case was the longest and the costliest in American judicial history, at 2 years and $15 million.</s>

<s docid="AP900118-0183" num="54" wdcount="25"> Superior Court Judge William Pounders said he did what he could to limit its length, cutting 50 witnesses and narrowing the scope of the case.</s>

<s docid="AP900118-0183" num="55" wdcount="12"> For parents and others, there was more to ponder than legal questions.</s>

<s docid="AP900118-0183" num="56" wdcount="4"> ``Life is not fair.</s>

<s docid="AP900118-0183" num="57" wdcount="8"> I tell my children all the time ...</s>

<s docid="AP900118-0183" num="58" wdcount="20"> there is no such thing as fair,'' said Robert Currie, whose son attended McMartin but didn't testify at the trial.</s>

<s docid="AP900118-0183" num="59" wdcount="16"> ``It's really a travesty for a case to take this long,'' said Ms. Rubin, the prosecutor.</s>

<s docid="AP900118-0183" num="60" wdcount="17"> ``...Not only for the families, the children in this case, but also for the defendants as well.''</s>
</TEXT>
</DOC>
