<DOC>
<DOCNO>

<s docid="AP900117-0193" num="1" wdcount="1"> AP900117-0193</s>
</DOCNO>
<FILEID>

<s docid="AP900117-0193" num="2" wdcount="2"> AP-NR-01-17-90 2158EST</s>
</FILEID>
<FIRST>

<s docid="AP900117-0193" num="3" wdcount="5"> u a AM-PreschoolMolest 01-17 0508</s>
</FIRST>
<SECOND>

<s docid="AP900117-0193" num="4" wdcount="2"> AM-Preschool Molest,0523</s>
</SECOND>
<HEAD>

<s docid="AP900117-0193" num="5" wdcount="5"> Jurors Deadlocked on 13 Charges</s>
</HEAD>
<BYLINE>

<s docid="AP900117-0193" num="6" wdcount="3"> By LINDA DEUTSCH</s>
</BYLINE>
<BYLINE>

<s docid="AP900117-0193" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900117-0193" num="8" wdcount="3"> LOS ANGELES (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900117-0193" num="9" wdcount="31"> Jurors who have reached verdicts on 52 counts in the McMartin preschool molestation case said Wednesday they are deadlocked on the remaining 13 charges in the nation's longest, costliest criminal trial.</s>

<s docid="AP900117-0193" num="10" wdcount="34"> Superior Court Judge William Pounders received a note from the jurors as they ended their day's deliberation and called a hearing for Thursday to discuss the deadlock and possibly opening the 52 sealed verdicts.</s>

<s docid="AP900117-0193" num="11" wdcount="39"> In an interview Wednesday evening, Pounders said he would deal with the deadlocked counts first, either declaring a mistrial on those counts and reading the sealed verdicts, or sending the jury back to resume deliberations on the undecided counts.</s>

<s docid="AP900117-0193" num="12" wdcount="13"> He said the verdicts could also be read before sending the jury back.</s>

<s docid="AP900117-0193" num="13" wdcount="20"> However, the judge noted that ``The attorneys are hopeful all the counts will be resolved before we take any verdicts''.</s>

<s docid="AP900117-0193" num="14" wdcount="19"> Pounders said he would discuss the matter with attorneys before quizzing jurors on whether they want to deliberate further.</s>

<s docid="AP900117-0193" num="15" wdcount="32"> The jurors are deciding whether Raymond Buckey, 31, and his mother, Peggy McMartin Buckey, 63, are guilty or innocent of charges they molested children at their family-owned McMartin Pre-School in Manhattan Beach.</s>

<s docid="AP900117-0193" num="16" wdcount="16"> The jury that spent 2 years hearing evidence in the case have agreed on 52 verdicts.</s>

<s docid="AP900117-0193" num="17" wdcount="5"> They have all been sealed.</s>

<s docid="AP900117-0193" num="18" wdcount="17"> None of the verdicts is official until it is announced in court and affirmed by the jury.</s>

<s docid="AP900117-0193" num="19" wdcount="8"> Jurors are in their ninth week of deliberations.</s>

<s docid="AP900117-0193" num="20" wdcount="19"> Buckey and his mother are charged with 64 counts of child molestation and the one shared count of conspiracy.</s>

<s docid="AP900117-0193" num="21" wdcount="18"> One of the charges which apparently has divided the jurors is the conspiracy charge which names both defendants.</s>

<s docid="AP900117-0193" num="22" wdcount="31"> Jurors asked twice for an explanation of how they could convict one defendant and acquit the other on that joint charge, but seemed perplexed after they received an explanation earlier Wednesday.</s>

<s docid="AP900117-0193" num="23" wdcount="31"> After conferring with lawyers, Pounders told jurors they could convict just one of the defendants on the charge ``if you feel that the defendant conspired with one or more other persons''.</s>

<s docid="AP900117-0193" num="24" wdcount="18"> However, he noted the conspiracy count includes eight alleged overt acts, some of them naming only one defendant.</s>

<s docid="AP900117-0193" num="25" wdcount="19"> A split verdict, he said, would require elimination of overt acts alleged against a defendant acquitted of the charge.</s>

<s docid="AP900117-0193" num="26" wdcount="16"> It was at that point, he said, that some jurors began shaking their heads in confusion.</s>

<s docid="AP900117-0193" num="27" wdcount="17"> Buckey and his mother were the only defendants required to stand trial after an 18-month preliminary hearing.</s>

<s docid="AP900117-0193" num="28" wdcount="14"> Five women teachers who worked at the McMartin Pre-School had charges against them dismissed.</s>

<s docid="AP900117-0193" num="29" wdcount="21"> Among those were Buckey's sister, Peggy Ann, and his grandmother, Virginia McMartin, who founded the prestigious but now defunct nursery school.</s>

<s docid="AP900117-0193" num="30" wdcount="12"> On Tuesday, deliberations were halted at midday because a juror became ill.</s>

<s docid="AP900117-0193" num="31" wdcount="16"> On Wednesday, the talks did not begin until 1 p.m. because another juror's child was ill.</s>

<s docid="AP900117-0193" num="32" wdcount="24"> No alternates remain in the case and the judge has worried that losing one of the 12 remaining jurors would force a mistrial .</s>
</TEXT>
</DOC>
