<DOC>
<DOCNO>

<s docid="AP900118-0205" num="1" wdcount="1"> AP900118-0205</s>
</DOCNO>
<FILEID>

<s docid="AP900118-0205" num="2" wdcount="2"> AP-NR-01-18-90 2346EST</s>
</FILEID>
<FIRST>

<s docid="AP900118-0205" num="3" wdcount="7"> u a BC-PreschoolMolest-Chronology 1stLd-Writethru a0638 01-18 0835</s>
</FIRST>
<SECOND>

<s docid="AP900118-0205" num="4" wdcount="5"> BC-Preschool Molest-Chronology, 1st Ld-Writethru, a0638,0856</s>
</SECOND>
<HEAD>

<s docid="AP900118-0205" num="5" wdcount="8"> Chronology of Events in Nation's Longest Criminal Case</s>
</HEAD>
<NOTE>

<s docid="AP900118-0205" num="6" wdcount="6"> Eds: SUBS grafs 12-15, bgn `Dec.</s>

<s docid="AP900118-0205" num="7" wdcount="6"> 19...,' to rearrange in chronological order.</s>

<s docid="AP900118-0205" num="8" wdcount="7"> Picks up 16th graf pvs, `April 20'...</s>

<s docid="AP900118-0205" num="9" wdcount="3"> Note contents .</s>
</NOTE>
<DATELINE>

<s docid="AP900118-0205" num="10" wdcount="3"> LOS ANGELES (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900118-0205" num="11" wdcount="13"> The McMartin Pre-school molestation case was the longest criminal trial in U.S. history.</s>

<s docid="AP900118-0205" num="12" wdcount="7"> Here is a chronology of the case:</s>
</TEXT>
<TEXT>

<s docid="AP900118-0205" num="13" wdcount="1"> _Aug.</s>

<s docid="AP900118-0205" num="14" wdcount="33"> 12, 1983: Judy Johnson makes a phone call to Manhattan Beach Police Department and tells Detective Jane Hoag that she believes her 2-year-old son was molested by Raymond Buckey at the McMartin Pre-School.</s>

<s docid="AP900118-0205" num="15" wdcount="18"> _Sept. 7, 1983: Ms. Hoag arrests Buckey, but he is released later that day for lack of evidence.</s>

<s docid="AP900118-0205" num="16" wdcount="35"> Police continue the investigation and stir controversy by sending letters to 200 parents naming Buckey as a child molestation suspect and asking them to interrogate their children about oral sex, fondling of genitals and sodomy.</s>

<s docid="AP900118-0205" num="17" wdcount="29"> _Fall of 1983 to spring of 1984: Nearly 400 children are interviewed by Children's Institute International, and 41 are listed as victims in a complaint filed by the state.</s>

<s docid="AP900118-0205" num="18" wdcount="22"> _Feb. 2, 1984: KABC-TV reporter Wayne Satz, in a newscast, describes dozens of alleged acts of oral copulation and sodomy with children.</s>

<s docid="AP900118-0205" num="19" wdcount="53"> _March 22, 1984: Public outcry prompts Los Angeles District Attorney Robert Philibosian to send the case to grand jurors, who indict Buckey; his mother, Peggy McMartin Buckey; his sister, Peggy Ann Buckey; his grandmother Virginia McMartin, and three employees, Mary Ann Jackson, Babette Spitler and Betty Raidor, on 115 charges of child molestation.</s>

<s docid="AP900118-0205" num="20" wdcount="10"> _March 24, 1984: All seven defendants are arrested and jailed.</s>

<s docid="AP900118-0205" num="21" wdcount="8"> Buckey and his mother are held without bail.</s>

<s docid="AP900118-0205" num="22" wdcount="9"> Bail for he others ranges from $50,000 to $350,000.</s>

<s docid="AP900118-0205" num="23" wdcount="13"> Lael Rubin, Christine Johnston and Glenn Stevens are assigned to the prosecution team.</s>

<s docid="AP900118-0205" num="24" wdcount="15"> Stevens is later removed for expressing doubts about evidence, and Ms. Johnston asks for reassignment.</s>

<s docid="AP900118-0205" num="25" wdcount="31"> _April 20, 1984: The seven defendants plead innocent at an arraignment, during which they are charged with sexually abusing 18 children over 10 years and using death threats to silence them.</s>

<s docid="AP900118-0205" num="26" wdcount="14"> _June 6, 1984: A preliminary hearing starts with Municipal Judge Aviva K. Bobb presiding.</s>

<s docid="AP900118-0205" num="27" wdcount="17"> Thirteen of the 41 alleged victims chosen from CII interviews take the stand during the 18-month hearing.</s>

<s docid="AP900118-0205" num="28" wdcount="34"> _Jan. 22, 1985: The first child witness in the preliminary hearing testifies that he and other pupils played ``naked games'' and that he had been touched on his genitals by some of the defendants.</s>

<s docid="AP900118-0205" num="29" wdcount="30"> _Jan. 9, 1986: Judge Bobb orders all seven defendants to stand trial in Superior Court on 135 counts of molestation and conspiracy, ending the longest preliminary hearing in California history.</s>

<s docid="AP900118-0205" num="30" wdcount="10"> The cost of the hearing was estimated at $4 million.</s>

<s docid="AP900118-0205" num="31" wdcount="41"> _Jan. 17, 1986: District Attorney Ira Reiner says there is insufficient evidence to warrant a trial for five of the seven defendants and asks dismissal of charges against Virginia McMartin, Peggy Ann Buckey, Mary Ann Jackson, Babette Spitler and Betty Raidor.</s>

<s docid="AP900118-0205" num="32" wdcount="15"> The remaining defendants, Buckey and his mother, still face 100 counts of molestation and conspiracy.</s>

<s docid="AP900118-0205" num="33" wdcount="13"> _Jan. 23, 1986: Mrs. Buckey is released on $295,000 bail, reduced from $495,000.</s>

<s docid="AP900118-0205" num="34" wdcount="27"> _Dec. 19, 1986: Judy Johnson, the mother who made the first allegations against Buckey, is found dead, naked and face down in her home, at age 44.</s>

<s docid="AP900118-0205" num="35" wdcount="17"> The coroner says she died of fatty metamorphosis of the liver, an ailment commonly found in alcoholics.</s>

<s docid="AP900118-0205" num="36" wdcount="9"> _April 20, 1987: The trial begins with jury selection.</s>

<s docid="AP900118-0205" num="37" wdcount="14"> By July 1, 12 jurors and six alternates are chosen from 500 prospective panelists.</s>

<s docid="AP900118-0205" num="38" wdcount="22"> _July 13, 1987: Opening statements begin after efforts to move the case elsewhere are quashed by Superior Court Judge William R. Pounders.</s>

<s docid="AP900118-0205" num="39" wdcount="31"> _July 29, 1987: The first parent to testify says his daughter's behavior indicates she may have been abused at the school, but he didn't recognize the warning signs at the time.</s>

<s docid="AP900118-0205" num="40" wdcount="29"> _Dec. 10, 1987: Paul Bynum, 39, a former police officer who once served as a defense investigator in the case, is found dead from an apparent self-inflicted gunshot wound.</s>

<s docid="AP900118-0205" num="41" wdcount="14"> _Oct. 17, 1988: The judge dismisses eight molestation counts against Buckey and his mother.</s>

<s docid="AP900118-0205" num="42" wdcount="16"> They now face a combined 65 counts of molestation and conspiracy involving 11 former McMartin pupils.</s>

<s docid="AP900118-0205" num="43" wdcount="16"> _Feb. 15, 1989: Buckey is released on $1.5 million bail after being jailed nearly five years.</s>

<s docid="AP900118-0205" num="44" wdcount="33"> _April 27, 1989: The trial, hitting the 2-year, 4-day mark, becomes the longest criminal hearing in U.S. history when it surpasses by one day the Hillside Strangler trial of Angelo Buono in 1982-83.</s>

<s docid="AP900118-0205" num="45" wdcount="22"> _May 16, 1989: Peggy McMartin Buckey takes the stand for the first time and strongly denies she ever sexually assaulted her students.</s>

<s docid="AP900118-0205" num="46" wdcount="14"> _July 26, 1989: Buckey takes the stand and denies he has ever molested children.</s>

<s docid="AP900118-0205" num="47" wdcount="12"> _Nov. 2, 1989: Jurors adjourn to select a foreman and begin deliberations.</s>

<s docid="AP900118-0205" num="48" wdcount="13"> The eight-men, four-women panel must sift through volumes of testimony from 124 witnesses.</s>

<s docid="AP900118-0205" num="49" wdcount="13"> _Jan. 18, 1990: The jury acquits Buckey and his mother of 52 counts.</s>

<s docid="AP900118-0205" num="50" wdcount="22"> The judge declares a mistrial on 13 other counts _ 12 against Buckey and one against both Buckey and his mother .</s>
</TEXT>
</DOC>
