<DOC>
<DOCNO>

<s docid="AP900119-0041" num="1" wdcount="1"> AP900119-0041</s>
</DOCNO>
<FILEID>

<s docid="AP900119-0041" num="2" wdcount="2"> AP-NR-01-19-90 0509EST</s>
</FILEID>
<FIRST>

<s docid="AP900119-0041" num="3" wdcount="5"> r a PM-PreschoolMolest-Blame 01-19 0406</s>
</FIRST>
<SECOND>

<s docid="AP900119-0041" num="4" wdcount="2"> PM-Preschool Molest-Blame,0417</s>
</SECOND>
<HEAD>

<s docid="AP900119-0041" num="5" wdcount="6"> Blame Plentiful in Preschool Molestation Case</s>
</HEAD>
<HEAD>

<s docid="AP900119-0041" num="6" wdcount="4"> With PM-Preschool Molest, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP900119-0041" num="7" wdcount="3"> By MICHAEL FLEEMAN</s>
</BYLINE>
<BYLINE>

<s docid="AP900119-0041" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900119-0041" num="9" wdcount="3"> LOS ANGELES (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900119-0041" num="10" wdcount="28"> There was plenty of blame to go around at the end of the lengthy and traumatic McMartin Pre-School molestation trial, but no one was willing to accept it.</s>

<s docid="AP900119-0041" num="11" wdcount="23"> In the nation's longest and costliest trial, Raymond Buckey and his mother, Peggy McMartin Buckey, were acquitted Thursday on 52 child molestation charges.</s>

<s docid="AP900119-0041" num="12" wdcount="7"> The jury deadlocked on 13 other charges.</s>

<s docid="AP900119-0041" num="13" wdcount="13"> Afterward, the district attorney who filed the case criticized the current district attorney.</s>

<s docid="AP900119-0041" num="14" wdcount="10"> The current district attorney blamed his predecessor and defense attorneys.</s>

<s docid="AP900119-0041" num="15" wdcount="13"> And some of the parents of children who attended the school blamed everybody.</s>

<s docid="AP900119-0041" num="16" wdcount="26"> ``The system is not going to protect children,'' said Jackie McGauley, a parent who believes her child had been molested but didn't testify in the case.</s>

<s docid="AP900119-0041" num="17" wdcount="13"> ``Life is not fair,'' said Robert Curry, whose son attended the McMartin school.</s>

<s docid="AP900119-0041" num="18" wdcount="8"> ``I tell my children all the time ...</s>

<s docid="AP900119-0041" num="19" wdcount="7"> there is no such thing as fair''.</s>

<s docid="AP900119-0041" num="20" wdcount="16"> The district attorney who originally pursued the case said he would not have done anything differently.</s>

<s docid="AP900119-0041" num="21" wdcount="39"> Robert Philibosian, now in private practice, angrily dismissed accusations that he played up the McMartin case in 1984 _ with the news media acting as eager accomplices _ to boost his public profile as he ran for district attorney.</s>

<s docid="AP900119-0041" num="22" wdcount="15"> ``I was a professional prosecutor for 16 years before this case was brought,'' he said.</s>

<s docid="AP900119-0041" num="23" wdcount="25"> ``To have people who know very little about professional or prosecutorial ethics, to criticize me personally that I have some political motive is totally unjustified''.</s>

<s docid="AP900119-0041" num="24" wdcount="16"> Philibosian instead pointed the finger at the man who defeated him, current District Attorney Ira Reiner.</s>

<s docid="AP900119-0041" num="25" wdcount="26"> Philibosian said Reiner hurt prosecutor's chances by dismissing charges against five of the original seven defendants and criticizing the case in a 1986 ``60 Minutes'' interview.</s>

<s docid="AP900119-0041" num="26" wdcount="42"> But Reiner, calling his dismissal of charges for lack of evidence ``the decision we're proud of,'' said the trial took so long because of the state's ponderous criminal justice system, delay tactics by defense attorneys and a mess left behind by Philibosian.</s>

<s docid="AP900119-0041" num="27" wdcount="8"> ``This is a case I inherited,'' Reiner said.</s>

<s docid="AP900119-0041" num="28" wdcount="23"> In interviews, many jurors said they believed some of the children were molested, but the prosecution never established that the defendants were responsible.</s>

<s docid="AP900119-0041" num="29" wdcount="25"> ``Even if you accept that the children were molested, it didn't necessarily mean they were molested at the McMartin Pre-School,'' said juror Brenda Williams .</s>
</TEXT>
</DOC>
