<DOC>
<DOCNO>

<s docid="AP900118-0190" num="1" wdcount="1"> AP900118-0190</s>
</DOCNO>
<FILEID>

<s docid="AP900118-0190" num="2" wdcount="2"> AP-NR-01-18-90 2233EST</s>
</FILEID>
<FIRST>

<s docid="AP900118-0190" num="3" wdcount="5"> r a AM-PreschoolMolest-Jury 01-18 0788</s>
</FIRST>
<SECOND>

<s docid="AP900118-0190" num="4" wdcount="2"> AM-Preschool Molest-Jury,0813</s>
</SECOND>
<HEAD>

<s docid="AP900118-0190" num="5" wdcount="7"> Jury Denounces Child Therapy Center, Police Letter</s>
</HEAD>
<HEAD>

<s docid="AP900118-0190" num="6" wdcount="4"> With Preschool Molest, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP900118-0190" num="7" wdcount="3"> By LINDA DEUTSCH</s>
</BYLINE>
<BYLINE>

<s docid="AP900118-0190" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900118-0190" num="9" wdcount="3"> LOS ANGELES (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900118-0190" num="10" wdcount="27"> Jurors in the McMartin Pre-School molestation case denounced the techniques of a child therapy center and a police department letter that inflamed parents and ignited the case.</s>

<s docid="AP900118-0190" num="11" wdcount="45"> Seven jurors who spoke with reporters in a joint news conference after acquitting Raymond Buckey and his mother, Peggy McMartin Buckey, on 52 molestation charges Thursday said they felt some children who testified may have been molested _ but not at the family-run McMartin Pre-School.</s>

<s docid="AP900118-0190" num="12" wdcount="21"> And they said some children may have merely repeated stories told them by their parents and interviewers at Children's Institute International.</s>

<s docid="AP900118-0190" num="13" wdcount="23"> The private child therapy center, which specializes in abused children, videotaped interviews with children from the McMartin school after reports of molestations surfaced.</s>

<s docid="AP900118-0190" num="14" wdcount="21"> Jurors saw the tapes in which interviewers used anatomically explicit puppets and leading questions to elicit descriptions of molestation from children.</s>

<s docid="AP900118-0190" num="15" wdcount="19"> Asked what led to acquittals, juror Brenda Williams focused on the taped interviews from the center jurors call CII.</s>

<s docid="AP900118-0190" num="16" wdcount="12"> ``The CII interviews _ I could not accept them,'' Mrs. Williams said.</s>

<s docid="AP900118-0190" num="17" wdcount="11"> ``I believe the children believe what they were saying was true.</s>

<s docid="AP900118-0190" num="18" wdcount="30"> But at CII, I could not tell if the children were saying what was told to them (by interviewers) or if they were repeating what their parents had told them.</s>

<s docid="AP900118-0190" num="19" wdcount="28"> ``If the CII tapes had not been entered into evidence and I had not seen them, I could have believed the children a little more,''' Mrs. Williams said.</s>

<s docid="AP900118-0190" num="20" wdcount="7"> ``The CII tapes did not help me.</s>

<s docid="AP900118-0190" num="21" wdcount="17"> They gave me a lot of reasonable doubt,'' agreed juror Julie Peters, 47, a supermarket meat wrapper.</s>

<s docid="AP900118-0190" num="22" wdcount="15"> ``The children were never allowed to say in their own words what happened to them.</s>

<s docid="AP900118-0190" num="23" wdcount="5"> All the questions were leading.</s>

<s docid="AP900118-0190" num="24" wdcount="21"> They never had a chance to tell their stories,'' said juror John Breese, 51, a medical technician and grandfather of five.</s>

<s docid="AP900118-0190" num="25" wdcount="16"> ``I tried to believe the children,'' said juror Daryl Hutchins 28, an oil company lease operator.</s>

<s docid="AP900118-0190" num="26" wdcount="12"> ``But if the child was so contaminated (by the interviews) I couldn't''.</s>

<s docid="AP900118-0190" num="27" wdcount="22"> Equal criticism was aimed at a letter sent in 1983 by the Manhattan Beach Police Department to parents of McMartin school children.</s>

<s docid="AP900118-0190" num="28" wdcount="16"> The letter alerted parents to a claim of molestation at the school and to Buckey's arrest.</s>

<s docid="AP900118-0190" num="29" wdcount="16"> ``The police letter should never have been sent,'' said juror Sally Cordova, 27, a supermarket checker.</s>

<s docid="AP900118-0190" num="30" wdcount="8"> ``It put the information out there too early.</s>

<s docid="AP900118-0190" num="31" wdcount="4"> The whole city knew''.</s>

<s docid="AP900118-0190" num="32" wdcount="18"> At that point, jurors said, they felt parents had been programmed to believe their children had been molested.</s>

<s docid="AP900118-0190" num="33" wdcount="20"> ``One child said his parents told him that he was molested even before he went to CII,'' Mrs. Williams recalled.</s>

<s docid="AP900118-0190" num="34" wdcount="22"> The panelists said they threw out entirely the most fantastic allegations, including some children's accounts of being molested in a car wash.</s>

<s docid="AP900118-0190" num="35" wdcount="7"> ``We just dismissed those,'' said Mrs. Williams.</s>

<s docid="AP900118-0190" num="36" wdcount="26"> They said a series of medical slides shown to them lacked impact because they weren't sure what they were seeing in the photos of children's genitals.</s>

<s docid="AP900118-0190" num="37" wdcount="13"> Although they acquitted defendants of most charges, the jurors deadlocked on 13 counts.</s>

<s docid="AP900118-0190" num="38" wdcount="28"> Some said they were unsure whether Buckey was a molester but were sure the prosecution had failed to prove its molestation allegations against him beyond a reasonable doubt.</s>

<s docid="AP900118-0190" num="39" wdcount="20"> Jurors said they didn't rule out that some children in the case were molested _ but not by these defendants.</s>

<s docid="AP900118-0190" num="40" wdcount="25"> ``Even if you accept that the children were molested,'' said juror Mark Bassett, ``the evidence didn't establish that they were molested at the McMartin Pre-School''.</s>

<s docid="AP900118-0190" num="41" wdcount="19"> The panelists said they were aware of the trial's enormous toll on defendants as well as children and parents.</s>

<s docid="AP900118-0190" num="42" wdcount="9"> ``I think everybody is a victim,'' said Ms. Peters.</s>

<s docid="AP900118-0190" num="43" wdcount="11"> ``I don't think anybody came out of this case a winner.</s>

<s docid="AP900118-0190" num="44" wdcount="8"> I think it's sad because everybody lost something.</s>

<s docid="AP900118-0190" num="45" wdcount="8"> The defendants _ their lives have been ruined.</s>

<s docid="AP900118-0190" num="46" wdcount="6"> They lost their business, their reputation.</s>

<s docid="AP900118-0190" num="47" wdcount="2"> It's sad''.</s>

<s docid="AP900118-0190" num="48" wdcount="10"> Mrs. Williams added, ``The children have to live with this.</s>

<s docid="AP900118-0190" num="49" wdcount="7"> The parents have to live with this.</s>

<s docid="AP900118-0190" num="50" wdcount="10"> There's nothing I can say that will make it better''.</s>

<s docid="AP900118-0190" num="51" wdcount="16"> As for themselves, the jurors said their lives were ``put on hold'' for nearly three years.</s>

<s docid="AP900118-0190" num="52" wdcount="13"> Bassett lost his job as a research computer scientist when his company folded.</s>

<s docid="AP900118-0190" num="53" wdcount="4"> Mrs. Williams got married.</s>

<s docid="AP900118-0190" num="54" wdcount="13"> Breese said his wife died during the trial and he has since remarried.</s>

<s docid="AP900118-0190" num="55" wdcount="12"> ``It's been very hard,'' said Mrs. Williams, a telephone company service representative.</s>

<s docid="AP900118-0190" num="56" wdcount="11"> ``There were days when I thought I couldn't stand it anymore.</s>

<s docid="AP900118-0190" num="57" wdcount="9"> ``I don't really know my job anymore,'' she said.</s>

<s docid="AP900118-0190" num="58" wdcount="11"> ``It's going to be hard getting back into the real world''.</s>

<s docid="AP900118-0190" num="59" wdcount="10"> The jury foreman and four other jurors declined interviews .</s>
</TEXT>
</DOC>
