<DOC>
<DOCNO>

<s docid="AP900119-0024" num="1" wdcount="1"> AP900119-0024</s>
</DOCNO>
<FILEID>

<s docid="AP900119-0024" num="2" wdcount="2"> AP-NR-01-19-90 0337EST</s>
</FILEID>
<FIRST>

<s docid="AP900119-0024" num="3" wdcount="5"> r a PM-PreschoolMolest-Therapists 01-19 0429</s>
</FIRST>
<SECOND>

<s docid="AP900119-0024" num="4" wdcount="2"> PM-Preschool Molest-Therapists,0444</s>
</SECOND>
<HEAD>

<s docid="AP900119-0024" num="5" wdcount="8"> Social Worker Defends Child Interviews in McMartin Case</s>
</HEAD>
<HEAD>

<s docid="AP900119-0024" num="6" wdcount="4"> With PM-Preschool Molest, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP900119-0024" num="7" wdcount="3"> By MICHAEL FLEEMAN</s>
</BYLINE>
<BYLINE>

<s docid="AP900119-0024" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900119-0024" num="9" wdcount="3"> LOS ANGELES (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900119-0024" num="10" wdcount="27"> A therapist defended her interviews of alleged victims in the McMartin Pre-School molestation trial, despite criticism by several jurors who said leading questions undermined the prosecution's case.</s>

<s docid="AP900119-0024" num="11" wdcount="24"> The jury on Thursday acquitted Raymond Buckey and his mother, Peggy McMartin Buckey, of 52 child molestation counts and deadlocked on 13 other counts.</s>

<s docid="AP900119-0024" num="12" wdcount="32"> Therapist Kee McFarlane later defended her work with hundreds of McMartin students, and suggested that the goals of therapy are at odds with the legal standards required for a successful criminal prosecution.</s>

<s docid="AP900119-0024" num="13" wdcount="19"> ``What is in the interest of children is not always in the interest of the legal system,'' she said.</s>

<s docid="AP900119-0024" num="14" wdcount="24"> Evidence introduced by prosecutors in what became the longest and most expensive criminal trial in U.S. history included videotaped interviews of the alleged victims.</s>

<s docid="AP900119-0024" num="15" wdcount="32"> Many of the interviews were conducted at an early stage of the sexual abuse investigation by MacFarlane, a social worker and director of the Child Sexual Abuse Center at Children's Institute International.</s>

<s docid="AP900119-0024" num="16" wdcount="23"> MacFarlane said Thursday she still believes children from the school had been molested and that they had not fabricated their accounts of abuse.</s>

<s docid="AP900119-0024" num="17" wdcount="22"> ``This agency would never have gone all the way through what we have if we did not believe these children,'' she said.</s>

<s docid="AP900119-0024" num="18" wdcount="17"> At least seven jurors who attended a news conference agreed the evidence showed children had been molested.</s>

<s docid="AP900119-0024" num="19" wdcount="13"> But the jurors were sharply critical of the interviewers' technique at the institute.</s>

<s docid="AP900119-0024" num="20" wdcount="19"> ``The children were never allowed to say in their own words what happened to them,'' said juror John Breese.</s>

<s docid="AP900119-0024" num="21" wdcount="5"> ``All the questions were leading''.</s>

<s docid="AP900119-0024" num="22" wdcount="29"> ``If the CII tapes had not been entered into evidence and I had not seen them, I could have believed the children a little more,'' juror Brenda Williams said.</s>

<s docid="AP900119-0024" num="23" wdcount="19"> But MacFarlane said that the interviewing techniques were sound, noting that small children must be interviewed differently than adults.</s>

<s docid="AP900119-0024" num="24" wdcount="9"> ``I didn't put words into their mouths,'' she said.</s>

<s docid="AP900119-0024" num="25" wdcount="10"> ``I tried to enable them to get over their fears''.</s>

<s docid="AP900119-0024" num="26" wdcount="20"> MacFarlane acknowledged that some procedures could have been done differently, including conducting more interviews over a longer period of time.</s>

<s docid="AP900119-0024" num="27" wdcount="19"> She called the outcome of the case a ``tragic consequence of an attempt to prevent trauma to these children''.</s>

<s docid="AP900119-0024" num="28" wdcount="17"> But the institute's executive director, Mary M. Emmons, said some good may come out of the case.</s>

<s docid="AP900119-0024" num="29" wdcount="24"> ``It has greatly increased the awareness about the issue of child sexual abuse and about the problems of prosecuting these cases,'' she said .</s>
</TEXT>
</DOC>
