<DOC>
<DOCNO>

<s docid="LA012190-0194" num="1" wdcount="1"> LA012190-0194</s>
</DOCNO>
<DOCID>

<s docid="LA012190-0194" num="2" wdcount="1"> 165252</s>
</DOCID>
<DATE>
<P>

<s docid="LA012190-0194" num="3" wdcount="6"> January 21, 1990, Sunday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA012190-0194" num="4" wdcount="8"> Part A; Page 33; Column 1; Metro Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA012190-0194" num="5" wdcount="2"> 886 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA012190-0194" num="6" wdcount="9"> TRIAL FINALE IS ONLY THE BEGINNING OF TV DEALS;</s>
</P>
<P>

<s docid="LA012190-0194" num="7" wdcount="12"> MEDIA: MCMARTIN STORY IS HEADED FOR THE SMALL SCREEN AND BOOKSTORE SHELVES.</s>

<s docid="LA012190-0194" num="8" wdcount="12"> BUT RETELLING THE CASE PRESENTS SOME TRICKY LEGAL AND MORAL PROBLEMS .</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA012190-0194" num="9" wdcount="6"> By SCOTT HARRIS, TIMES STAFF WRITER</s>
</P>
</BYLINE>
<TEXT>
<P>

<s docid="LA012190-0194" num="10" wdcount="9"> Geraldo Rivera was interviewing Peggy Ann Buckey on TV.</s>

<s docid="LA012190-0194" num="11" wdcount="13"> Abby Mann watched, listened -- and saw the makings of a movie .</s>
</P>
<P>

<s docid="LA012190-0194" num="12" wdcount="21"> Prosecutors had just dropped charges of child molestation against Buckey, one of the original seven defendants in the McMartin Pre-School case.</s>

<s docid="LA012190-0194" num="13" wdcount="31"> In that 1986 interview, Peggy Buckey was "quite eloquent" in arguing that charges against her brother, Ray, and mother, Peggy McMartin Buckey, should be dropped as well, Mann recalled Friday .</s>
</P>
<P>

<s docid="LA012190-0194" num="14" wdcount="21"> Mann, an Oscar- and Emmy-winning screenwriter and producer, recognized a theme he had tapped before: the hysteria of a witch hunt.</s>

<s docid="LA012190-0194" num="15" wdcount="22"> Soon, Mann became a controversial figure in the case itself -- but he got the inside track on movie and book deals.</s>

<s docid="LA012190-0194" num="16" wdcount="30"> And Thursday's not-guilty verdicts in Ray and Peggy McMartin Buckey's trial gave Mann the happy ending he was hoping for -- happy, at least, from his point of view .</s>
</P>
<P>

<s docid="LA012190-0194" num="17" wdcount="42"> But Mann and his wife, Myra, who have an 800-page manuscript in the works for Random House and say they are close to finishing a screenplay, aren't expected to monopolize the telling of the 6-year-old McMartin case -- or the perspective .</s>
</P>
<P>

<s docid="LA012190-0194" num="18" wdcount="24"> At least two other books are planned, and at least one prominent television movie producer besides Mann says he is developing a McMartin project.</s>

<s docid="LA012190-0194" num="19" wdcount="17"> That producer, who requested anonymity, said he is certain other producers are considering projects as well .</s>
</P>
<P>

<s docid="LA012190-0194" num="20" wdcount="8"> "It's definitely a TV thing," one agent said.</s>

<s docid="LA012190-0194" num="21" wdcount="14"> "Just one of those perfect, high-concept, lurid television M-O-Ws" -- an acronym for movies-of-the-week.</s>

<s docid="LA012190-0194" num="22" wdcount="17"> "The producer chases down participants, gets rights -- and then it's an easy sale to networks" .</s>
</P>
<P>

<s docid="LA012190-0194" num="23" wdcount="7"> Not that easy, network executives say .</s>
</P>
<P>

<s docid="LA012190-0194" num="24" wdcount="37"> Unlike the hottest true-life property of the moment -- the Stuart murder case in Boston, which has CBS and The Fries Co. racing to produce the first docudrama -- McMartin creates some tricky legal and moral problems.</s>

<s docid="LA012190-0194" num="25" wdcount="17"> The jury's deadlock on 13 counts creates an ambiguity: Is Ray Buckey a villain or a victim?</s>
</P>
<P>

<s docid="LA012190-0194" num="26" wdcount="28"> "None of the three networks would touch Ray Buckey's story," predicted Steven White, an independent producer who used to be a movie executive for both NBC and ABC.</s>

<s docid="LA012190-0194" num="27" wdcount="9"> "First, the man is still accused of 13 crimes.</s>

<s docid="LA012190-0194" num="28" wdcount="21"> . . . If I were sitting in my old job, I wouldn't touch this thing with a 10-foot pole" .</s>
</P>
<P>

<s docid="LA012190-0194" num="29" wdcount="33"> "It raises so many legal and ethical questions at this point it would have to be looked at with a microscope," said Larry Strichman, a senior executive in movie development at CBS .</s>
</P>
<P>

<s docid="LA012190-0194" num="30" wdcount="8"> "What is the story you want to tell?</s>

<s docid="LA012190-0194" num="31" wdcount="10"> Is it a story of justice done or justice denied?</s>

<s docid="LA012190-0194" num="32" wdcount="14"> And it's real unclear at the moment what the answer to that question is.</s>

<s docid="LA012190-0194" num="33" wdcount="14"> Unlike a documentary, it's hard to take an ambiguous position in a docudrama" .</s>
</P>
<P>

<s docid="LA012190-0194" num="34" wdcount="8"> Producers think network qualms can be overcome, however.</s>

<s docid="LA012190-0194" num="35" wdcount="21"> One pointed out that the Billionaire Boys Club docudrama was broadcast before all the trials regarding the slayings were over .</s>
</P>
<P>

<s docid="LA012190-0194" num="36" wdcount="8"> "There are no rules," the producer said .</s>
</P>
<P>

<s docid="LA012190-0194" num="37" wdcount="10"> Hollywood's role in the McMartin case came to prominence early.</s>

<s docid="LA012190-0194" num="38" wdcount="18"> Not long after the first allegations of child molestation six years ago, several producers pitched projects to networks.</s>

<s docid="LA012190-0194" num="39" wdcount="15"> Though no explicit McMartin story was produced, child abuse and molestation was a recurring subject.</s>

<s docid="LA012190-0194" num="40" wdcount="22"> One CBS fictional movie last year -- "Did You Know the Muffin Man"? -- featured a preschool and satanic child molesters .</s>
</P>
<P>

<s docid="LA012190-0194" num="41" wdcount="44"> Mann, whose writing credits include the Academy Award-winning "Judgment at Nuremberg" in 1961, won an Emmy for "The Marcus-Nelson Murders," a three-hour "Kojak" drama based on a true case in which a black youth was wrongly convicted of the killings of two white women.</s>

<s docid="LA012190-0194" num="42" wdcount="14"> The prosecutors, the media and the community seemed blinded by hysteria, Mann said .</s>
</P>
<P>

<s docid="LA012190-0194" num="43" wdcount="17"> Gaining the confidence of the McMartin defendants, the Manns were ultimately hired as "investigators" by the defense.</s>

<s docid="LA012190-0194" num="44" wdcount="29"> That and their earlier alliance with former prosecutor Glenn Stevens sparked charges from parents of alleged child molestation victims of a conspiracy to obstruct justice for monetary gain .</s>
</P>
<P>

<s docid="LA012190-0194" num="45" wdcount="50"> Stevens, who said he had asked to be removed from the McMartin trial team in October, 1985, said he and Mann agreed in March, 1986, to produce a book and movie about the case with the understanding that their discussions would become public after the trial and appeals were over.</s>

<s docid="LA012190-0194" num="46" wdcount="18"> But in late 1986, Mann released interviews with Stevens in which Stevens said he doubted the defendants' guilt.</s>

<s docid="LA012190-0194" num="47" wdcount="18"> Mann said his attorneys had advised him that to withhold them would be an obstruction of justice .</s>
</P>
<P>

<s docid="LA012190-0194" num="48" wdcount="19"> Outraged parents suggested the real aim was a not-guilty verdict, which would improve the value of Mann's movie deal.</s>

<s docid="LA012190-0194" num="49" wdcount="20"> But Stevens and the Manns have said their ambition from the start has been to get the truth out .</s>
</P>
<P>

<s docid="LA012190-0194" num="50" wdcount="9"> At least two other perspectives may reach the bookstores.</s>

<s docid="LA012190-0194" num="51" wdcount="32"> Ray Buckey's lawyer, Danny Davis, and writer Gordon Dillow, former columnist for the defunct Los Angeles Herald Examiner, have a book proposal that is being pitched to a variety of publishers .</s>
</P>
<P>

<s docid="LA012190-0194" num="52" wdcount="22"> Times staff writer Lois Timnick, who covered the case from its early stages through the trial, also is planning a book .</s>
</P>
<P>

<s docid="LA012190-0194" num="53" wdcount="9"> Mann said his script isn't a courtroom drama .</s>
</P>
<P>

<s docid="LA012190-0194" num="54" wdcount="5"> "It's not a trial movie.</s>

<s docid="LA012190-0194" num="55" wdcount="6"> It's what happens to human beings.</s>

<s docid="LA012190-0194" num="56" wdcount="8"> I intend to be fair to the parents.</s>

<s docid="LA012190-0194" num="57" wdcount="6"> I don't mean to be vindicative.</s>

<s docid="LA012190-0194" num="58" wdcount="15"> . . . For the most part, I have great sympathy for the parents" .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA012190-0194" num="59" wdcount="11"> Photo, Producer Abby Mann is writing a McMartin book and screenplay.</s>

<s docid="LA012190-0194" num="60" wdcount="3"> Los Angeles Times</s>
</P>
</GRAPHIC>
<TYPE>
<P>

<s docid="LA012190-0194" num="61" wdcount="2"> Series; Sidebar</s>
</P>
</TYPE>
<SUBJECT>
<P>

<s docid="LA012190-0194" num="62" wdcount="30"> TELEVISION PROGRAMS; VIRGINIA MCMARTIN PRESCHOOL; BUCKEY, RAYMOND; BUCKEY, PEGGY MCMARTIN; CHILD ABUSE; CHILD MOLESTATION; TRIALS; MANN, ABBY; MOTION PICTURES; MOTION PICTURE PRODUCERS; BOOKS; MOTION PICTURE INDUSTRY; TELEVISION INDUSTRY; WRITERS; REPORTERS</s>
</P>
</SUBJECT>
</DOC>
