<DOC>
<DOCNO>

<s docid="LA011990-0091" num="1" wdcount="1"> LA011990-0091</s>
</DOCNO>
<DOCID>

<s docid="LA011990-0091" num="2" wdcount="1"> 164172</s>
</DOCID>
<DATE>
<P>

<s docid="LA011990-0091" num="3" wdcount="6"> January 19, 1990, Friday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA011990-0091" num="4" wdcount="8"> Part A; Page 1; Column 5; Metro Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA011990-0091" num="5" wdcount="2"> 3292 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA011990-0091" num="6" wdcount="4"> MCMARTIN VERDICT: NOT GUILTY;</s>
</P>
<P>

<s docid="LA011990-0091" num="7" wdcount="13"> JUSTICE: THE JURY'S FINDINGS CLOSE THE LONGEST AND COSTLIEST CRIMINAL TRIAL IN HISTORY.</s>

<s docid="LA011990-0091" num="8" wdcount="14"> NO DECISION HAS BEEN MADE ON RETRYING RAY BUCKEY ON 13 UNDECIDED COUNTS .</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA011990-0091" num="9" wdcount="9"> By LOIS TIMNICK and CAROL McGRAW, TIMES STAFF WRITERS</s>
</P>
</BYLINE>
<TEXT>
<P>

<s docid="LA011990-0091" num="10" wdcount="40"> Ray Buckey and his mother, Peggy McMartin Buckey, were found not guilty Thursday of molesting children at the family-run McMartin Pre-School in Manhattan Beach, a verdict which brought to a close the longest and costliest criminal trial in history .</s>
</P>
<P>

<s docid="LA011990-0091" num="11" wdcount="39"> An eight-man, four-woman jury -- 10 of the members parents themselves -- acquitted the Buckeys of 52 counts of molestation after deliberating for nine weeks over evidence that had been presented over the course of more than two years.</s>

<s docid="LA011990-0091" num="12" wdcount="19"> The jury reported it was deadlocked on 13 remaining counts, and a mistrial was declared on those allegations .</s>
</P>
<P>

<s docid="LA011990-0091" num="13" wdcount="32"> Ray Buckey, 31, left the courtroom without comment -- free on his own recognizance until a decision is reached on whether the district attorney will retry him on the 13 undecided counts.</s>

<s docid="LA011990-0091" num="14" wdcount="10"> But his 63-year-old mother and co-defendant reacted with anger .</s>
</P>
<P>

<s docid="LA011990-0091" num="15" wdcount="14"> "I've gone through hell and now we've lost everything," she said outside the court.</s>

<s docid="LA011990-0091" num="16" wdcount="24"> "My concern was for my son and what they've done to him . . . because my son would never harm a child" .</s>
</P>
<P>

<s docid="LA011990-0091" num="17" wdcount="32"> Most jurors said later that they believed the children who testified had been molested, but that the prosecution had failed to prove beyond a reasonable doubt that the Buckeys were culpable .</s>
</P>
<P>

<s docid="LA011990-0091" num="18" wdcount="18"> "I am not convinced that he (Ray Buckey) is innocent," said juror Sally Cordova, 27, a supermarket checker.</s>

<s docid="LA011990-0091" num="19" wdcount="11"> "But it was not proven to me that he did it.</s>

<s docid="LA011990-0091" num="20" wdcount="15"> Whether I believe he did it and whether it was proven are very different" .</s>
</P>
<P>

<s docid="LA011990-0091" num="21" wdcount="12"> The end of the case came in a tense and crowded courtroom.</s>

<s docid="LA011990-0091" num="22" wdcount="44"> The Buckeys, who spent years in jail as the case progressed through the judicial system, had sat silently, staring straight ahead, as the jury filed into the room shortly before 10:30 a.m. and the gallery of reporters and spectators grew quiet in anticipation .</s>
</P>
<P>

<s docid="LA011990-0091" num="23" wdcount="21"> "All the verdicts are the same," said Los Angeles Superior Court Judge William Pounders, handing them to his court clerk .</s>
</P>
<P>

<s docid="LA011990-0091" num="24" wdcount="25"> Clerk Stan Ferrell listed the counts numerically and then, reading from the verdict form, delivered in a single, almost anti-climactic sentence the historic trial's close:</s>
</P>
<P>

<s docid="LA011990-0091" num="25" wdcount="14"> "We the jury in the above entitled actions find the defendants not guilty" .</s>
</P>
<P>

<s docid="LA011990-0091" num="26" wdcount="13"> The quiet of the courtroom was split by a few gasps and sobs.</s>

<s docid="LA011990-0091" num="27" wdcount="14"> At first, the defendants remained stoic, then their eyes began to rim with tears.</s>

<s docid="LA011990-0091" num="28" wdcount="5"> Ray Buckey's lower lip quivered.</s>

<s docid="LA011990-0091" num="29" wdcount="9"> His mother dabbed at her eyes with a handkerchief.</s>

<s docid="LA011990-0091" num="30" wdcount="4"> They said nothing .</s>
</P>
<P>

<s docid="LA011990-0091" num="31" wdcount="9"> Afterward, Peggy McMartin Buckey insisted she was not bitter.</s>

<s docid="LA011990-0091" num="32" wdcount="22"> "I knew God would set my son and me free because we have done nothing," she said as she was driven away.</s>

<s docid="LA011990-0091" num="33" wdcount="23"> Her optimism was not matched by her son, however, who she said had "had fear, definitely," about what the jury would decide .</s>
</P>
<P>

<s docid="LA011990-0091" num="34" wdcount="32"> "I held his hand," Buckey's mother said after the verdicts were announced, "and I told him: 'I told you, Ray,' and he felt like he wanted to cry but he didn't" .</s>
</P>
<P>

<s docid="LA011990-0091" num="35" wdcount="35"> The acquittals concluded the longest criminal trial in history, a case that stemmed from a 2 1/2-year-old's report to his mother six years ago that he had been sodomized at his school by a "Mr.</s>

<s docid="LA011990-0091" num="36" wdcount="29"> Ray". The case ultimately cost taxpayers more than $15 million, altered scores of lives and careers, and provided a national focal point for the issue of child abuse .</s>
</P>
<P>

<s docid="LA011990-0091" num="37" wdcount="26"> Judge Pounders said he was not surprised by the verdicts: "I found it difficult to determine how they would view the evidence in the first place.</s>

<s docid="LA011990-0091" num="38" wdcount="24"> I thought that based on the evidence that was presented, the jury could do almost anything and still find rational support for it .</s>
</P>
<P>

<s docid="LA011990-0091" num="39" wdcount="26"> "It is very difficult to test the credibility of children, and when you go beyond that, the natural tendency for adults is to look for corroboration.</s>

<s docid="LA011990-0091" num="40" wdcount="11"> It was very difficult to find corroboration in this case" .</s>
</P>
<P>

<s docid="LA011990-0091" num="41" wdcount="23"> Asked if the case was worth its cost in money, lives and stress, Pounders said he thinks society benefited from the case .</s>
</P>
<P>

<s docid="LA011990-0091" num="42" wdcount="23"> "People will be much more alert to the possibility of this type of offense taking place at preschool and at schools," Pounders said.</s>

<s docid="LA011990-0091" num="43" wdcount="12"> "People are no longer dropping their children off and walking away blindly.</s>

<s docid="LA011990-0091" num="44" wdcount="3"> They look back.</s>

<s docid="LA011990-0091" num="45" wdcount="6"> They check things out more" .</s>
</P>
<P>

<s docid="LA011990-0091" num="46" wdcount="33"> In the crowded courthouse hallways, parents of alleged victims lashed out at the prosecutors for bungling the case and insisted that their children had not been well served by the judicial system .</s>
</P>
<P>

<s docid="LA011990-0091" num="47" wdcount="15"> "The system doesn't allow us to protect kids," said the father of two alleged victims.</s>

<s docid="LA011990-0091" num="48" wdcount="9"> "I have no doubt these children were abused .</s>
</P>
<P>

<s docid="LA011990-0091" num="49" wdcount="17"> Said a tearful mother: "I guess maybe it's OK to (molest) kids! I can't believe this" .</s>
</P>
<P>

<s docid="LA011990-0091" num="50" wdcount="11"> The children themselves reacted calmly and stood by their accounts .</s>
</P>
<P>

<s docid="LA011990-0091" num="51" wdcount="16"> "We all know that we are telling the truth," said a 15-year-old boy who had testified.</s>

<s docid="LA011990-0091" num="52" wdcount="13"> "No matter what the jury says, whatever anybody says, this is the truth.</s>

<s docid="LA011990-0091" num="53" wdcount="4"> We were molested" .</s>
</P>
<P>

<s docid="LA011990-0091" num="54" wdcount="21"> Another of the children said that, when the clerk read "not guilty" on the verdict form, "my stomach just hollowed out.</s>

<s docid="LA011990-0091" num="55" wdcount="4"> I was beyond tears.</s>

<s docid="LA011990-0091" num="56" wdcount="12"> Those words will stick with me probably the rest of my life.</s>

<s docid="LA011990-0091" num="57" wdcount="7"> I'll never forget those two words" .</s>
</P>
<P>

<s docid="LA011990-0091" num="58" wdcount="7"> Jurors were critical of the prosecutors' methods.</s>

<s docid="LA011990-0091" num="59" wdcount="23"> In particular, they cited the prosecution's reliance on videotapes of controversial pretrial interviews of the young witnesses at a Los Angeles child-abuse center.</s>

<s docid="LA011990-0091" num="60" wdcount="29"> They also criticized the Manhattan Beach Police Department's decision, early in the investigation, to send out form letters to parents announcing an investigation had begun and soliciting information .</s>
</P>
<P>

<s docid="LA011990-0091" num="61" wdcount="23"> "The children," said juror John Breese, 51, a biomedical technician, "were never allowed to say in their own words what happened to them.</s>

<s docid="LA011990-0091" num="62" wdcount="4"> That was crucial" .</s>
</P>
<P>

<s docid="LA011990-0091" num="63" wdcount="18"> Said jury foreman Luis Chang, an electrical engineer: "The key evidence that swayed me was the interview tapes.</s>

<s docid="LA011990-0091" num="64" wdcount="6"> They were too biased, too leading.</s>

<s docid="LA011990-0091" num="65" wdcount="7"> That's the main crux of it" .</s>
</P>
<P>

<s docid="LA011990-0091" num="66" wdcount="31"> All said they had entered the jury deliberation room with open minds, not only because the judge had so instructed, but also because the disjointed testimony had left them confused .</s>
</P>
<P>

<s docid="LA011990-0091" num="67" wdcount="37"> "I went into the jury room as confused and uncertain as I was the day I first sat in the jury box the first day of this trial," said Brenda Williams, 38, a Pacific Bell service representative.</s>

<s docid="LA011990-0091" num="68" wdcount="45"> "I felt I had missed out on something, maybe I had dozed off during some important testimony and I was hoping some of my fellow jurors had something in their notes that I didn't have in mine that would make it all come together" .</s>
</P>
<P>

<s docid="LA011990-0091" num="69" wdcount="16"> Said juror Mark Bassett, 33, a computer specialist: "We just didn't really know what happened" .</s>
</P>
<P>

<s docid="LA011990-0091" num="70" wdcount="2"> Deputy Dist.</s>

<s docid="LA011990-0091" num="71" wdcount="25"> Atty Lael Rubin, who prosecuted the case, said a decision has not been made about whether to pursue the 13 counts involved in a mistrial.</s>

<s docid="LA011990-0091" num="72" wdcount="20"> These counts involve 12 molestation charges against Ray Buckey, and a conspiracy count that accused both him and his mother.</s>

<s docid="LA011990-0091" num="73" wdcount="12"> The conspiracy count against Peggy McMartin Buckey was dismissed outright Thursday .</s>
</P>
<P>

<s docid="LA011990-0091" num="74" wdcount="17"> "We ultimately must respect the jury's decision," Rubin said, "even though I personally disagree with it .</s>
</P>
<P>

<s docid="LA011990-0091" num="75" wdcount="13"> "The system worked well for them," she said in reference to the Buckeys.</s>

<s docid="LA011990-0091" num="76" wdcount="3"> "They were lucky.</s>

<s docid="LA011990-0091" num="77" wdcount="18"> I just hope to God that years from now we don't hear about Ray Buckey molesting children" .</s>
</P>
<P>

<s docid="LA011990-0091" num="78" wdcount="4"> Los Angeles County Dist.</s>

<s docid="LA011990-0091" num="79" wdcount="23"> Atty. Ira Reiner blamed the criminal justice system for the length of the trial, and said he backs two state court-reform initiatives .</s>
</P>
<P>

<s docid="LA011990-0091" num="80" wdcount="12"> "Too much time and too much money has gone into this case.</s>

<s docid="LA011990-0091" num="81" wdcount="3"> This is insane.</s>

<s docid="LA011990-0091" num="82" wdcount="22"> The very idea a case can go to trial for 2 1/2 years and there can be a rational result is preposterous.</s>

<s docid="LA011990-0091" num="83" wdcount="12"> The McMartin case is the very worst example that we have, period.</s>

<s docid="LA011990-0091" num="84" wdcount="7"> But it does not stand alone" .</s>
</P>
<P>

<s docid="LA011990-0091" num="85" wdcount="13"> Defense attorneys Dean Gits and Danny Davis were beaming after the verdict announcement.</s>

<s docid="LA011990-0091" num="86" wdcount="35"> "I feel great," Gits said, indicating he had found hope that the decision would go the defense way last week when the jury informed the judge it was reaching deadlock on a conspiracy count .</s>
</P>
<P>

<s docid="LA011990-0091" num="87" wdcount="34"> With the acquittal, Pounders freed more than $3 million worth of property that had been posted by Buckey supporters as bail last year so that he could be released after five years in jail.</s>

<s docid="LA011990-0091" num="88" wdcount="19"> Buckey's mother had been free on a smaller bail amount earlier after spending nearly two years in jail .</s>
</P>
<P>

<s docid="LA011990-0091" num="89" wdcount="51"> The McMartin case -- which included allegations not only of rape, sodomy, oral copulation, and other sex crimes, but also of pornographic photography sessions, "naked games," field trips away from the school for illicit purposes, animal mutilation, threats and satanic-like ritual and sacrifice -- began in the fall of 1983 .</s>
</P>
<P>

<s docid="LA011990-0091" num="90" wdcount="19"> The mother of a 2 1/2-year-old complained to Manhattan Beach police that her son had been sodomized by "Mr.</s>

<s docid="LA011990-0091" num="91" wdcount="12"> Ray," and subsequent physical examinations indicated he had been sexually abused .</s>
</P>
<P>

<s docid="LA011990-0091" num="92" wdcount="44"> Buckey was arrested in September of that year, but was released as the investigation continued and widened to include six other teachers at the Manhattan Beach nursery school, among them his grandmother, dozens of "uncharged suspects," and eight other South Bay nursery schools .</s>
</P>
<P>

<s docid="LA011990-0091" num="93" wdcount="29"> The Manhattan Beach Police Department sent a form letter to hundreds of McMartin school parents asking for information, and a wave of hysteria swept through the affluent beach town.</s>

<s docid="LA011990-0091" num="94" wdcount="30"> Many parents took their youngsters to Children's Institute International, a Los Angeles child-abuse diagnostic and treatment center, for evaluation; the majority were told that their children had been victimized .</s>
</P>
<P>

<s docid="LA011990-0091" num="95" wdcount="33"> In March, 1984, Ray Buckey was rearrested, along with his sister, Peggy Ann Buckey, his mother, Peggy McMartin Buckey, his grandmother, Virginia McMartin, and teachers Betty Raidor, Babette Spitler and Mary Ann Jackson.</s>

<s docid="LA011990-0091" num="96" wdcount="29"> A county grand jury had indicted them on 115 counts; that indictment was superseded in May by a criminal complaint charging them with 208 counts involving 41 children .</s>
</P>
<P>

<s docid="LA011990-0091" num="97" wdcount="12"> The case was hastily filed, and it was flawed from the beginning.</s>

<s docid="LA011990-0091" num="98" wdcount="21"> Then-Dist. Atty. Robert Philibosian, running for reelection, and the media, which caught wind of the investigation, were pressing for action .</s>
</P>
<P>

<s docid="LA011990-0091" num="99" wdcount="55"> Children's Institute International, deluged with concerned parents, enlisted untrained therapists to assess the children, resulting in videotaped interviews filled with leading and suggestive questions that would later prove embarrassing to the prosecution and provide the defense with grounds for claiming that the alleged victims had been programmed to believe that they had been molested .</s>
</P>
<P>

<s docid="LA011990-0091" num="100" wdcount="2"> Hysteria grew.</s>

<s docid="LA011990-0091" num="101" wdcount="47"> Hundreds of South Bay children had fallen victim to a nationwide conspiracy and pornography ring, it was alleged, and an angry mob spray-painted "Ray Must Die" on the walls of the nursery school and began digging up an adjacent vacant lot in search of animal remains .</s>
</P>
<P>

<s docid="LA011990-0091" num="102" wdcount="43"> The 18-month preliminary hearing, which began in the fall of 1984, was marked by frequent shouting matches between three prosecutors, nine defense attorneys and Municipal Judge Aviva Bobb, and lengthy questioning of child witnesses that lasted in one instance for 16 days .</s>
</P>
<P>

<s docid="LA011990-0091" num="103" wdcount="24"> Los Angeles was riveted by the daily images of youngsters clambering atop a booster chair in their Sunday best to face their alleged molesters.</s>

<s docid="LA011990-0091" num="104" wdcount="18"> They munched cookies, swigged root beer, and sometimes sobbed as they told of their experiences at McMartin .</s>
</P>
<P>

<s docid="LA011990-0091" num="105" wdcount="35"> Perhaps the most poignant moment came when an 8-year-old girl told in a wispy voice of having been raped, photographed, tied up and placed in a dark closet by her teachers five years earlier .</s>
</P>
<P>

<s docid="LA011990-0091" num="106" wdcount="28"> In the end, Bobb ordered all seven defendants to stand trial on 135 charges, telling each, "The court believes there is sufficient cause to believe you are guilty".</s>

<s docid="LA011990-0091" num="107" wdcount="18"> The remaining charges had been dropped after only 14 of the scheduled child witnesses came forward to testify.</s>

<s docid="LA011990-0091" num="108" wdcount="21"> One child was allowed to testify by closed-circuit television, under a new state law passed especially for the McMartin case .</s>
</P>
<P>

<s docid="LA011990-0091" num="109" wdcount="44"> But a week later, in January, 1986, the new district attorney, Ira Reiner, who had inherited the case from Philibosian, dropped charges against five of the seven defendants, citing "incredibly weak evidence" and deciding to proceed only against Ray Buckey and his mother .</s>
</P>
<P>

<s docid="LA011990-0091" num="110" wdcount="10"> The trial itself began with jury selection in April, 1987.</s>

<s docid="LA011990-0091" num="111" wdcount="4"> Testimony began in July.</s>

<s docid="LA011990-0091" num="112" wdcount="19"> The scope of the trial was narrowed again when several parents decided not to allow their children to testify.</s>

<s docid="LA011990-0091" num="113" wdcount="21"> Eventually nine of 11 named victims took the witness stand, all sticking to their earlier accounts, but for minor inconsistencies .</s>
</P>
<P>

<s docid="LA011990-0091" num="114" wdcount="29"> Toddlers at the time of their alleged abuse and now nearing adolescence, they described in graphic detail the abuses they say they suffered at the hands of the Buckeys.</s>

<s docid="LA011990-0091" num="115" wdcount="7"> Their testimony was often raw and unsettling.</s>

<s docid="LA011990-0091" num="116" wdcount="13"> The children's allegations were supported by medical evidence testified to by physicians .</s>
</P>
<P>

<s docid="LA011990-0091" num="117" wdcount="15"> But both Buckey and his mother also took the stand and staunchly maintained their innocence.</s>

<s docid="LA011990-0091" num="118" wdcount="21"> And fellow teachers, including former defendants, testified that no improprieties in the small school could have occurred without their knowledge .</s>
</P>
<P>

<s docid="LA011990-0091" num="119" wdcount="39"> The prosecution sought to show that the children repeatedly had been abused sexually, but silenced for years by threats, and also that their child-like efforts to tell their parents that something was wrong had been ignored or misinterpreted .</s>
</P>
<P>

<s docid="LA011990-0091" num="120" wdcount="27"> The defense contended that nothing untoward happened at the school, but that the children were programmed by therapists to believe that something bad had happened to them.</s>

<s docid="LA011990-0091" num="121" wdcount="19"> It claimed that their stories defied common sense and that the medical evidence was unreliable and perhaps fabricated .</s>
</P>
<P>

<s docid="LA011990-0091" num="122" wdcount="24"> The 6-year-long case was marked by twists and turns and tragedies, prompting the judge to comment that it had "poisoned" everyone it had touched.</s>

<s docid="LA011990-0091" num="123" wdcount="11"> Day after day, it was punctuated with the unexpected and bizarre:</s>
</P>
<P>

<s docid="LA011990-0091" num="124" wdcount="26"> * Ailing family matriarch Virginia McMartin, now 82, wrote poetry, conducted colorful hallway interviews and tested the judge's patience with such outbursts as, "This awful court.</s>

<s docid="LA011990-0091" num="125" wdcount="3"> These awful people.</s>

<s docid="LA011990-0091" num="126" wdcount="4"> These awful lies" .</s>
</P>
<P>

<s docid="LA011990-0091" num="127" wdcount="54"> * Therapist Kee MacFarlane, who conducted many of the interviews in which children first disclosed that they had been molested, came under fire when it was revealed not only that she had minimal previous experience in the field but also that she was involved romantically with the television newsman who broke the story .</s>
</P>
<P>

<s docid="LA011990-0091" num="128" wdcount="34"> * Former prosecutor Glenn Stevens became a key defense witness after leaking information that he believed that the defendants were innocent, and signed a movie contract to tell his revised version of events .</s>
</P>
<P>

<s docid="LA011990-0091" num="129" wdcount="51"> * A 10-year-old boy, testifying at the preliminary hearing, identified everyone from the city attorney and a movie star to a priest and four nuns as among his molesters, and painted a picture of marching with his classmates to a cemetery where they dug up corpses with shovels and pick-axes .</s>
</P>
<P>
</P>
<P>

<s docid="LA011990-0091" num="130" wdcount="6"> KEY FIGURES IN THE McMARTIN TRIAL</s>
</P>
<P>

<s docid="LA011990-0091" num="131" wdcount="2"> THE JUDGE:</s>
</P>
<P>

<s docid="LA011990-0091" num="132" wdcount="2"> WILLIAM R.</s>

<s docid="LA011990-0091" num="133" wdcount="8"> POUNDERS, 50 -- Superior Court judge since 1985.</s>

<s docid="LA011990-0091" num="134" wdcount="24"> A former state prosecutor who also did appellate work, he was assigned to the case after the litigants rejected three other judges as prejudiced.</s>

<s docid="LA011990-0091" num="135" wdcount="43"> An intellectual who often uses expressions derived from his Air Force experience building nuclear missiles, Pounders' strengths are meticulous organization and an extensive knowledge of the law, which he augments with a 3-by-5 index card file system, as well as a new computer.</s>

<s docid="LA011990-0091" num="136" wdcount="17"> A graduate of Loyola Law School, he is widely respected as a fair and thorough judge .</s>
</P>
<P>

<s docid="LA011990-0091" num="137" wdcount="2"> THE DEFENDANTS:</s>
</P>
<P>

<s docid="LA011990-0091" num="138" wdcount="27"> RAY BUCKEY, 31 -- Key defendant in the McMartin case, Buckey is the grandson of nursery school founder Virginia McMartin and son of co-defendant Peggy McMartin Buckey.</s>

<s docid="LA011990-0091" num="139" wdcount="35"> A quiet man who is a college dropout and has admitted having problems with drugs and alcohol, Buckey worked briefly at a San Diego child care center before joining his family's enterprise in Manhattan Beach.</s>

<s docid="LA011990-0091" num="140" wdcount="21"> He was charged on 52 counts of child molestation involving 11 children and one count of conspiracy shared with his mother.</s>

<s docid="LA011990-0091" num="141" wdcount="7"> He denied all allegations against him .</s>
</P>
<P>

<s docid="LA011990-0091" num="142" wdcount="20"> PEGGY MCMARTIN BUCKEY, 63 -- Co-defendant in the McMartin case, she both directed the Virginia McMartin Pre-School and taught there.</s>

<s docid="LA011990-0091" num="143" wdcount="8"> She also hired her son as a teacher.</s>

<s docid="LA011990-0091" num="144" wdcount="31"> A talkative, religious woman who drew pictures throughout the tedious proceedings and crocheted during breaks, she was charged on 12 counts of molestation involving four children and one count of conspiracy.</s>

<s docid="LA011990-0091" num="145" wdcount="17"> She has maintained that neither she nor any member of her staff engaged in improper conduct .</s>
</P>
<P>

<s docid="LA011990-0091" num="146" wdcount="2"> THE PROSECUTORS:</s>
</P>
<P>

<s docid="LA011990-0091" num="147" wdcount="2"> LAEL R.</s>

<s docid="LA011990-0091" num="148" wdcount="4"> RUBIN, 47 -- Co-prosecutor.</s>

<s docid="LA011990-0091" num="149" wdcount="27"> A former high school English teacher, Rubin was a latecomer to the legal profession, graduating from the University of West Los Angeles School of Law in 1978.</s>

<s docid="LA011990-0091" num="150" wdcount="43"> She quickly distinguished herself after joining the district attorney's office, successfully prosecuting "Black Cathy" Wilson for child pornography, Harry Sassounian for the assassination of the Turkish consul general in Los Angeles, and his brother, Harout Sassounian, for firebombing the Turkish consul general's house.</s>

<s docid="LA011990-0091" num="151" wdcount="12"> She is the only original prosecutor remaining on the McMartin case .</s>
</P>
<P>

<s docid="LA011990-0091" num="152" wdcount="6"> ROGER J. GUNSON, 50 -- Co-prosecutor.</s>

<s docid="LA011990-0091" num="153" wdcount="33"> A 20-year veteran of the district attorney's office and a graduate of UCLA Law School, the soft-spoken, unassuming Gunson most recently served as head deputy in the Sex Crimes and Child Abuse Division.</s>

<s docid="LA011990-0091" num="154" wdcount="27"> He successfully prosecuted film director Roman Polanski for unlawful sex with a minor, and Susan Brophy, wife of former state assemblyman Bill Brophy, for vehicular manslaughter .</s>
</P>
<P>

<s docid="LA011990-0091" num="155" wdcount="3"> THE DEFENSE ATTORNEYS:</s>
</P>
<P>

<s docid="LA011990-0091" num="156" wdcount="2"> DANIEL G.</s>

<s docid="LA011990-0091" num="157" wdcount="8"> DAVIS, 43 -- Defense attorney representing Ray Buckey.</s>

<s docid="LA011990-0091" num="158" wdcount="30"> A graduate of the University of Texas law school, Davis was a civil attorney with the firm of Lillick McHose & Charles for two years before turning to criminal law.</s>

<s docid="LA011990-0091" num="159" wdcount="18"> Initially hired by the Buckey family, he was appointed to finish the case after their money ran out.</s>

<s docid="LA011990-0091" num="160" wdcount="7"> He owns the now-defunct nursery school .</s>
</P>
<P>

<s docid="LA011990-0091" num="161" wdcount="2"> DEAN R.</s>

<s docid="LA011990-0091" num="162" wdcount="9"> GITS, 45 -- Defense attorney representing Peggy McMartin Buckey.</s>

<s docid="LA011990-0091" num="163" wdcount="25"> A gentlemanly, cum laude graduate of the William Mitchell College of Law in St. Paul, Gits describes himself as "a simple country lawyer from Minnesota".</s>

<s docid="LA011990-0091" num="164" wdcount="32"> Known for his painstakingly thorough work, he was a deputy public defender for nearly nine years before going into private practice with the firm of Overland, Berke, Wesley, Gits, Randolph & Levanas.</s>

<s docid="LA011990-0091" num="165" wdcount="10"> He has more than 15 years of criminal trial experience.</s>

<s docid="LA011990-0091" num="166" wdcount="11"> He was court-appointed to the McMartin case at its beginning .</s>
</P>
<P>
</P>
<P>

<s docid="LA011990-0091" num="167" wdcount="3"> McMARTIN TRIAL CHRONOLOGY</s>
</P>
<P>

<s docid="LA011990-0091" num="168" wdcount="11"> Aug. 12, 1983 -- Initial complaint filed against Ray Buckey .</s>
</P>
<P>

<s docid="LA011990-0091" num="169" wdcount="10"> Sept. 7, 1983 -- Ray Buckey arrested and released .</s>
</P>
<P>

<s docid="LA011990-0091" num="170" wdcount="25"> March 22, 1984 -- Buckey and six others, including his sister, mother and grandmother, are indicted on 115 counts of child molestation and conspiracy .</s>
</P>
<P>

<s docid="LA011990-0091" num="171" wdcount="14"> May 23, 1984 -- District attorney's office files 208-count complaint that supersedes indictment .</s>
</P>
<P>

<s docid="LA011990-0091" num="172" wdcount="11"> June 8, 1984 -- Preliminary hearing for Ray Buckey begins .</s>
</P>
<P>

<s docid="LA011990-0091" num="173" wdcount="12"> Aug. 17, 1984 -- Consolidated preliminary hearing for seven defendants begins .</s>
</P>
<P>

<s docid="LA011990-0091" num="174" wdcount="20"> October, 1984 -- Sheriff's task force is created to investigate "uncharged McMartin suspects" and other South Bay nursery schools .</s>
</P>
<P>

<s docid="LA011990-0091" num="175" wdcount="17"> Jan. 9, 1986 -- Municipal Court Judge Aviva Bobb orders all seven defendants to stand trial .</s>
</P>
<P>

<s docid="LA011990-0091" num="176" wdcount="17"> Jan. 17, 1986 -- District Atty. Ira Reiner drops charges against five of the seven defendants .</s>
</P>
<P>

<s docid="LA011990-0091" num="177" wdcount="16"> Dec. 19, 1986 -- Mother whose allegations triggered investigation is found dead in her home .</s>
</P>
<P>

<s docid="LA011990-0091" num="178" wdcount="8"> April 20, 1987 -- Jury selection begins .</s>
</P>
<P>

<s docid="LA011990-0091" num="179" wdcount="25"> July 13, 1987 -- Trial of Ray Buckey and Peggy McMartin Buckey gets under way with opening statements, followed by presentation of prosecution's case .</s>
</P>
<P>

<s docid="LA011990-0091" num="180" wdcount="11"> Oct. 19, 1988 -- Defense begins presentation of its case .</s>
</P>
<P>

<s docid="LA011990-0091" num="181" wdcount="8"> Oct. 12, 1989 -- Final arguments begin .</s>
</P>
<P>

<s docid="LA011990-0091" num="182" wdcount="10"> Nov. 2, 1989 -- Case goes to the jury .</s>
</P>
<P>

<s docid="LA011990-0091" num="183" wdcount="11"> Nov. 29, 1989 -- First verdict returned, kept under seal .</s>
</P>
<P>

<s docid="LA011990-0091" num="184" wdcount="8"> Jan. 11, 1990 -- Fifty-second verdict returned .</s>
</P>
<P>

<s docid="LA011990-0091" num="185" wdcount="11"> Jan. 17, 1990 -- Jury deadlocks on remaining 13 counts .</s>
</P>
<P>

<s docid="LA011990-0091" num="186" wdcount="7"> Jan. 18, 1990 -- Verdicts announced .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA011990-0091" num="187" wdcount="17"> Photo, COLOR, Defendants Ray Buckey and his mother, Peggy McMartin Buckey, after the jury verdicts were read.</s>

<s docid="LA011990-0091" num="188" wdcount="21"> Photo, Peggy McMartin Buckey embraces Daniel Davis, her son's attorney, in the courthouse hallway after the 'not guilty' verdicts were read.</s>

<s docid="LA011990-0091" num="189" wdcount="9"> RICK MEYER / Los Angeles Times; Photo, WILLIAM R.</s>

<s docid="LA011990-0091" num="190" wdcount="11"> POUNDERS; Photo, RAY BUCKEY; Photo, PEGGY MCMARTIN BUCKEY; Photo, LAEL R.</s>

<s docid="LA011990-0091" num="191" wdcount="4"> RUBIN; Photo, ROGER J.</s>

<s docid="LA011990-0091" num="192" wdcount="4"> GUNSON; Photo, DANIEL G.</s>

<s docid="LA011990-0091" num="193" wdcount="5"> DAVIS; Photo, DEAN R. GITS</s>
</P>
</GRAPHIC>
<TYPE>
<P>

<s docid="LA011990-0091" num="194" wdcount="1"> Chronology</s>
</P>
</TYPE>
<SUBJECT>
<P>

<s docid="LA011990-0091" num="195" wdcount="13"> VIRGINIA MCMARTIN PRESCHOOL; BUCKEY, RAYMOND; BUCKEY, PEGGY MCMARTIN; CHILD ABUSE; CHILD MOLESTATION; TRIALS</s>
</P>
</SUBJECT>
</DOC>
