<DOC>
<DOCNO>

<s docid="LA012290-0036" num="1" wdcount="1"> LA012290-0036</s>
</DOCNO>
<DOCID>

<s docid="LA012290-0036" num="2" wdcount="1"> 165354</s>
</DOCID>
<DATE>
<P>

<s docid="LA012290-0036" num="3" wdcount="6"> January 22, 1990, Monday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA012290-0036" num="4" wdcount="9"> Metro; Part B; Page 1; Column 5; Metro Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA012290-0036" num="5" wdcount="2"> 624 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA012290-0036" num="6" wdcount="8"> MCMARTIN CASE FALLOUT TAKES ITS TOLL ON MINISTER;</s>
</P>
<P>

<s docid="LA012290-0036" num="7" wdcount="25"> RELIGION: HE SAYS YEARS OF 'EXTREME STRESS' FIGHTING RUMORS THAT SATANIC RITUALS WERE PERFORMED AT HIS CHURCH HAVE FORCED HIM TO SEEK DISABILITY RETIREMENT .</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA012290-0036" num="8" wdcount="6"> By SHAWN HUBLER, TIMES STAFF WRITER</s>
</P>
</BYLINE>
<TEXT>
<P>

<s docid="LA012290-0036" num="9" wdcount="41"> A Hermosa Beach minister who for years has tried in vain to quell rumors tying his church to the McMartin Pre-School scandal announced Sunday that the "extreme stress" of fallout from the case has forced him to seek disability retirement .</s>
</P>
<P>

<s docid="LA012290-0036" num="10" wdcount="62"> The Rev. John D. Eales of St. Cross Episcopal Church -- where McMartin pupils claimed they had been forced to take part in satanic rituals -- told the congregation during his sermon that, "after much prayer and consultation," he realized his health could not withstand the continuing harassment and vandalization the church has borne as a result of the unsubstantiated claims .</s>
</P>
<P>

<s docid="LA012290-0036" num="11" wdcount="42"> The McMartin case, which prompted the longest and most expensive criminal trial in U.S. history, ended Thursday with the acquittal of defendants Ray Buckey and Peggy McMartin Buckey on a total of 52 counts of child molestation at the Manhattan Beach school.</s>

<s docid="LA012290-0036" num="12" wdcount="8"> The jurors deadlocked on 13 other counts .</s>
</P>
<P>

<s docid="LA012290-0036" num="13" wdcount="17"> Nonetheless, the case continues to divide and haunt the South Bay communities where it was centered .</s>
</P>
<P>

<s docid="LA012290-0036" num="14" wdcount="28"> St. Cross was never named as a defendant in the case and neither Eales nor any other official of the venerable seaside church was ever formally charged .</s>
</P>
<P>

<s docid="LA012290-0036" num="15" wdcount="42"> But since 1985, the church has struggled to shake a McMartin pupil's allegation during the preliminary hearing that, six years earlier, he and other students had been forced to witness animal sacrifices and satanic rituals at the altar of St. Cross .</s>
</P>
<P>

<s docid="LA012290-0036" num="16" wdcount="23"> When the then-10-year-old boy's allegation was reported in the local media, other children claimed that they too had been abused at the church.</s>

<s docid="LA012290-0036" num="17" wdcount="29"> Though investigators using sophisticated equipment checked the altar and found no trace of blood, attendance dropped drastically at the church and the church-run preschool, which closed soon afterward .</s>
</P>
<P>

<s docid="LA012290-0036" num="18" wdcount="30"> The allegations never died, despite the passage of time and the announcement by Los Angeles County sheriff's investigators that they had found no evidence to support the children's claims .</s>
</P>
<P>

<s docid="LA012290-0036" num="19" wdcount="30"> Periodically over the years, Eales said, he would receive threatening phone calls at the church and rectory, and the harassment increased as the McMartin case began to wind down .</s>
</P>
<P>

<s docid="LA012290-0036" num="20" wdcount="14"> Twice in December, the church and rectory were pelted with bottles and rotten eggs.</s>

<s docid="LA012290-0036" num="21" wdcount="36"> In a note left in the rectory driveway after the second attack, the vandals, who identified themselves as "the Beach Cities' Conscience," warned that "there is simply no place for Satan worship in this town" .</s>
</P>
<P>

<s docid="LA012290-0036" num="22" wdcount="35"> The harassment was exacerbated by the arrest shortly after Christmas of a youth counselor at the church, who was charged with molesting two teen-age boys he had met through his work at St. Cross .</s>
</P>
<P>

<s docid="LA012290-0036" num="23" wdcount="36"> The counselor, it turned out, was a convicted child molester who had been brought into the fold about a year and a half earlier by an assistant pastor who was hired after the McMartin case broke.</s>

<s docid="LA012290-0036" num="24" wdcount="25"> Then, just days after that assistant pastor resigned, the McMartin verdict came down, and, according to several church members, the anonymous phone calls returned .</s>
</P>
<P>

<s docid="LA012290-0036" num="25" wdcount="23"> "It's kind of like a violin string -- you can only tighten it so far and then it snaps," Eales said Sunday .</s>
</P>
<P>

<s docid="LA012290-0036" num="26" wdcount="32"> Though at 61 Eales has 11 more years until the diocese would mandate his retirement, he said his doctors told him that "the kind of stress you have been under kills" .</s>
</P>
<P>

<s docid="LA012290-0036" num="27" wdcount="42"> Because of that, he said, he plans to extend a medical leave already scheduled to allow for some minor surgery next week and retire a year short of the 10-year tenure that was his goal when he came to St. Cross .</s>
</P>
<P>

<s docid="LA012290-0036" num="28" wdcount="17"> His decision shocked and saddened parishioners, who credited Eales with shepherding the church through difficult times .</s>
</P>
<P>

<s docid="LA012290-0036" num="29" wdcount="9"> Said Ron Russell, a 16-year member of the congregation:</s>
</P>
<P>

<s docid="LA012290-0036" num="30" wdcount="16"> "We brought a good, strong man in here, and -- well, this has ruined him" .</s>
</P>
</TEXT>
<SUBJECT>
<P>

<s docid="LA012290-0036" num="31" wdcount="21"> EALES, JOHN D; SAINT CROSS EPISCOPAL CHURCH; VIRGINIA MCMARTIN PRESCHOOL; CHILD MOLESTATION; OCCULT SCIENCES; CLERGY; CHURCHES; HARASSMENT; VANDALISM; RUMORS; RETIREMENT; STRESS</s>
</P>
</SUBJECT>
</DOC>
