<DOC>
<DOCNO>

<s docid="AP900805-0060" num="1" wdcount="1"> AP900805-0060</s>
</DOCNO>
<FILEID>

<s docid="AP900805-0060" num="2" wdcount="2"> AP-NR-08-05-90 2113EDT</s>
</FILEID>
<FIRST>

<s docid="AP900805-0060" num="3" wdcount="7"> u i AM-UN-Iraq-Kuwait 3rdLd-Writethru a0792 08-05 0574</s>
</FIRST>
<SECOND>

<s docid="AP900805-0060" num="4" wdcount="4"> AM-UN-Iraq-Kuwait, 3rd Ld-Writethru, a0792,0585</s>
</SECOND>
<HEAD>

<s docid="AP900805-0060" num="5" wdcount="9"> United State Pushes for Iraqi Sanctions at United Nations</s>
</HEAD>
<NOTE>

<s docid="AP900805-0060" num="6" wdcount="19"> Eds: LEADS thruout to UPDATE with U.S. ambassador's comments, comments from Britain, Cuba; DELETES outdated material thruout; no pickup</s>
</NOTE>
<HEAD>

<s docid="AP900805-0060" num="7" wdcount="3"> With AM-Iraq-Kuwait, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP900805-0060" num="8" wdcount="3"> By VICTORIA GRAHAM</s>
</BYLINE>
<BYLINE>

<s docid="AP900805-0060" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<TEXT>

<s docid="AP900805-0060" num="10" wdcount="22"> UNITED NATIONS _ The United States urged other U.N. members at talks Sunday to impose broad economic and military sanctions on Iraq.</s>

<s docid="AP900805-0060" num="11" wdcount="12"> Western diplomats said the world body is expected to adopt the measures.</s>

<s docid="AP900805-0060" num="12" wdcount="3"> Should the U.N.</s>

<s docid="AP900805-0060" num="13" wdcount="22"> Security Council impose comprehensive sanctions, it would be the first time since 1967 it has taken such action against a member state.</s>

<s docid="AP900805-0060" num="14" wdcount="15"> The last time such sanctions were imposed was against the white minority government of Rhodesia.</s>

<s docid="AP900805-0060" num="15" wdcount="18"> Western diplomats said they expected up to 14 positive votes on the 15-member council for sanctions against Iraq.</s>

<s docid="AP900805-0060" num="16" wdcount="17"> They said they expected no vetoes, allowing the legally binding measure to be adopted, probably on Monday.</s>

<s docid="AP900805-0060" num="17" wdcount="6"> They said Cuba was the holdout.</s>

<s docid="AP900805-0060" num="18" wdcount="27"> U.S. Ambassador Thomas R. Pickering told reporters after closed-door talks Sunday that the council discussed ``the absolute necessity of moving ahead toward a broad resolution of sanctions''.</s>

<s docid="AP900805-0060" num="19" wdcount="7"> He said he expected a vote Monday.</s>

<s docid="AP900805-0060" num="20" wdcount="15"> Pickering said the United States had circulated six or seven drafts of a detailed resolution.</s>

<s docid="AP900805-0060" num="21" wdcount="27"> It calls for an embargo on Iraq's oil exports, an embargo on imports to Iraq, and a halt to all arms and other military supplies for Iraq.</s>

<s docid="AP900805-0060" num="22" wdcount="24"> British Ambassador Crispen Tickell told reporters later that he detected ``strong support, with the exception of one member, for action and a vote tomorrow''.</s>

<s docid="AP900805-0060" num="23" wdcount="17"> Speaking of Iraqi President Saddam Hussein, Canadian Ambassador L. Yves Fortier declared, ``This madman must be stopped''.</s>

<s docid="AP900805-0060" num="24" wdcount="36"> Cuban envoy Ricardo Alarcon said Cuba would vote for sanctions against Iraq only if the council imposed sanctions on South Africa for occupying Namibia, Israel for occupying Palestinian territories and the United States for invading Panama.</s>

<s docid="AP900805-0060" num="25" wdcount="28"> In Kuwait, the Iraqi-installed provisional government, in a statement carried by the Iraqi News Agency, told other countries to refrain from taking ``punishing measures'' against it or Iraq.</s>

<s docid="AP900805-0060" num="26" wdcount="15"> The provisional government said countries ``have to remember they have interests and citizens in Kuwait''.</s>

<s docid="AP900805-0060" num="27" wdcount="30"> Kuwait's U.N. Ambassador Mohammad Abulhasan told reporters that the Iraqi-installed government was employing ``pure blackmail'' by saying it could not ensure the safety of foreigners if their governments support sanctions.</s>

<s docid="AP900805-0060" num="28" wdcount="29"> In Aspen, Colo., British Prime Minister Margaret Thatcher renewed her call for the United Nations to apply a total economic embargo against Iraq unless it withdraws immediately from Kuwait.</s>

<s docid="AP900805-0060" num="29" wdcount="12"> ``Iraq's invasion of Kuwait defies every principle for which the U.N. stands.</s>

<s docid="AP900805-0060" num="30" wdcount="13"> If we let it succeed, no small country can ever feel safe again.</s>

<s docid="AP900805-0060" num="31" wdcount="15"> The law of the jungle takes over,'' she said, in remarks at the Aspen Institute.</s>

<s docid="AP900805-0060" num="32" wdcount="21"> The U.N. role in the Iraq-Kuwait crisis assumed increasing importance after divided Arab nations cancelled an emergency summit on the invasion.</s>

<s docid="AP900805-0060" num="33" wdcount="25"> On Thursday, the Security Council condemned Iraq's invasion, demanded immediate and unconditional troop withdrawal, and threatened to impose sanctions if Iraq did not pull out.</s>

<s docid="AP900805-0060" num="34" wdcount="36"> Sunday's session was scheduled after weekend meetings of the council's five permanent members _ the United States, the Soviet Union, China, Britain and France _ and between the United States and representatives of the Non-Aligned Movement.</s>

<s docid="AP900805-0060" num="35" wdcount="10"> They are the nations with the power to veto proposals.</s>

<s docid="AP900805-0060" num="36" wdcount="30"> The United States contends that stiff sanctions by a united international front are necessary to punish Iraq and to force it to withdraw from Kuwait, which was invaded Thursday .</s>
</TEXT>
</DOC>
