<DOC>
<DOCNO>

<s docid="AP900802-0057" num="1" wdcount="1"> AP900802-0057</s>
</DOCNO>
<FILEID>

<s docid="AP900802-0057" num="2" wdcount="2"> AP-NR-08-02-90 0406EDT</s>
</FILEID>
<FIRST>

<s docid="AP900802-0057" num="3" wdcount="7"> b i AM-Kuwait 10thLd-Writethru a0480 08-02 1029</s>
</FIRST>
<SECOND>

<s docid="AP900802-0057" num="4" wdcount="4"> AM-Kuwait, 10th Ld-Writethru, a0480,1067</s>
</SECOND>
<HEAD>

<s docid="AP900802-0057" num="5" wdcount="9"> Iraq Invades Kuwait, Says Kuwaiti Gov't Has Been Overthrown</s>
</HEAD>
<NOTE>

<s docid="AP900802-0057" num="6" wdcount="16"> Eds: UPDATES thruout with emir's palace taken, country being ravaged, American Embassy surrounded, British Embassy shelled.</s>

<s docid="AP900802-0057" num="7" wdcount="3"> No pickup .</s>
</NOTE>
<DATELINE>

<s docid="AP900802-0057" num="8" wdcount="2"> KUWAIT (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900802-0057" num="9" wdcount="19"> Tank-led Iraqi troops invaded Kuwait before dawn Thursday, seizing the ruler's palace and other government buildings, Kuwaiti officials reported.</s>

<s docid="AP900802-0057" num="10" wdcount="15"> , The Iraqi government of President Saddam Hussein said the Kuwaiti government had been overthrown.</s>

<s docid="AP900802-0057" num="11" wdcount="35"> The invasion comes nearly two weeks after Iraq massed troops on Kuwait's border in a dispute over an oilfield and Kuwait's violation of OPEC oil production quotas, which had kept down the price of crude.</s>

<s docid="AP900802-0057" num="12" wdcount="15"> ``The Iraqis have occupied all of Kuwait''! one Kuwaiti official shouted in a telephone interview.</s>

<s docid="AP900802-0057" num="13" wdcount="27"> ``They have seized all administrative buildings, including the information ministry which houses the (state-run) radio and television stations,'' said the official, who spoke on condition of anonymity.</s>

<s docid="AP900802-0057" num="14" wdcount="22"> Diplomats said about 350 Iraqi tanks wheeled into the capital a few hours after crossing the border 40 miles away before dawn.</s>

<s docid="AP900802-0057" num="15" wdcount="30"> The invaders, whose forces far outnumber those of smaller Kuwait, were led by the elite Republican Guard that did the brunt of the fighting in the 1980-88 war with Iran.</s>

<s docid="AP900802-0057" num="16" wdcount="11"> The troops set up roadblocks at major intersections in the capital.</s>

<s docid="AP900802-0057" num="17" wdcount="17"> The invaders surrounded the palace of the ruler of Kuwait, Sheik Jaber al-Ahmed al-Sabah, the official said.</s>

<s docid="AP900802-0057" num="18" wdcount="16"> Residents in the palace's vicinity said it was seized after two hours of heavy artillery barrages.</s>

<s docid="AP900802-0057" num="19" wdcount="19"> The whereabouts of the emir, whose family has ruled the city-state for almost 250 years, was not immediately known.</s>

<s docid="AP900802-0057" num="20" wdcount="10"> The bombardment of ports and airports was vicious, eyewitnesses said.</s>

<s docid="AP900802-0057" num="21" wdcount="13"> Thousands of residents attempted to flee south toward Saudi Arabia in their cars.</s>

<s docid="AP900802-0057" num="22" wdcount="13"> Kuwait's official radio broadcast a desperate plea for help from other Arab nations.</s>

<s docid="AP900802-0057" num="23" wdcount="34"> The Kuwaiti Embassy in Washington reported only that there were many casualties in the fighting, which follows a flareup in a protracted dispute over a border oil field, but gave no numbers early Thursday.</s>

<s docid="AP900802-0057" num="24" wdcount="15"> Residents said there were about 50 tanks around the emir's palace and the neighboring U.S.</s>

<s docid="AP900802-0057" num="25" wdcount="8"> Embassy. The embassy did no answer its telephones.</s>

<s docid="AP900802-0057" num="26" wdcount="18"> The British Embassy was hit by shellfire and the Sheraton and Hilton hotels evacuated their clientele, sources said.</s>

<s docid="AP900802-0057" num="27" wdcount="11"> The air space over Kuwait was closed, with airliners turned away.</s>

<s docid="AP900802-0057" num="28" wdcount="25"> The Bush administration demanded immediate withdrawal of the Iraqi forces and added that it was ``reviewing all options in its response to the Iraqi aggression''.</s>

<s docid="AP900802-0057" num="29" wdcount="35"> U.S. warships have been on ``short-term'' alert 600 miles southeast of the Iraq-Kuwait border since July 24 because of the tensions in the oil-rich Persian Gulf region, scene of heavy fighting in the Iran-Iraq war.</s>

<s docid="AP900802-0057" num="30" wdcount="12"> The White House said it had no reports of harm to Americans.</s>

<s docid="AP900802-0057" num="31" wdcount="28"> The United States has extensive business ties to Kuwait, and the U.S. community in the nation _ slightly smaller than New Jersey _ is sizeable, in the thousands.</s>

<s docid="AP900802-0057" num="32" wdcount="23"> The White House denounced the incursion, issuing a statement that said, ``The United States strongly condemns the Iraqi military invasion of Kuwait ...</s>

<s docid="AP900802-0057" num="33" wdcount="21"> ``We have conveyed this message to the Iraqi ambassador in Washington and to the Iraqi government through our embassy in Baghdad.</s>

<s docid="AP900802-0057" num="34" wdcount="14"> ``We deplore this blatant use of military aggression in violation of the U.N. charter''.</s>

<s docid="AP900802-0057" num="35" wdcount="17"> In New York, U.N. officials said the Security Council was to begin an emergency meeting early Thursday.</s>

<s docid="AP900802-0057" num="36" wdcount="4"> Reaction was swift elsewhere.</s>

<s docid="AP900802-0057" num="37" wdcount="30"> The British government said the ``armed incursion is clearly a grave threat to peace and stability in the area and of immediate concern to the international community as a whole''.</s>

<s docid="AP900802-0057" num="38" wdcount="47"> The Iraqi action was expected to dominate talks between President Bush and Prime Minister Margaret Thatcher when they meet later Thursday in Aspen, Colo. Iraqi officials on Wednesday had abruptly walked out on talks in Jiddah, Saudi Arabia, complaining that the Kuwaiti representatives were not negotiating seriously.</s>

<s docid="AP900802-0057" num="39" wdcount="26"> President Hosni Mubarak of Egypt had intervened beginning July 25 to set up the talks in a bid to cool tensions between the two OPEC members.</s>

<s docid="AP900802-0057" num="40" wdcount="13"> In Baghdad, Saddam's government announced Thursday that the Kuwaiti government had been toppled.</s>

<s docid="AP900802-0057" num="41" wdcount="20"> Kuwait radio went off the air briefly, but came back on different wavelenghs with martial music and Kuwaiti patriotic songs.</s>

<s docid="AP900802-0057" num="42" wdcount="27"> Saddam's ruling council issued a statement from Baghdad saying an interim government had been established in Kuwait but the claim could not be immediately and independently confirmed.</s>

<s docid="AP900802-0057" num="43" wdcount="22"> ``Iraq has responded to the request from interim government of free Kuwait and decided to cooperate with it,'' the Iraqi statement said.</s>

<s docid="AP900802-0057" num="44" wdcount="21"> It said the troops _ no numbers were given _ were in Kuwait to defend the revolution and the Kuwaiti people.</s>

<s docid="AP900802-0057" num="45" wdcount="9"> There was no further identification of the revolutionary government.</s>

<s docid="AP900802-0057" num="46" wdcount="16"> Iraq warned too that any foreign troops trying to interfere with its actions would be attacked.</s>

<s docid="AP900802-0057" num="47" wdcount="12"> More than 60 percent of the country's 1.8 million residents are foreigners.</s>

<s docid="AP900802-0057" num="48" wdcount="25"> Kuwaiti forces had engaged the Iraqi invaders with heavy artillery in a failed attempt to repulse them, government officials contacted by telephone earlier Thursday said.</s>

<s docid="AP900802-0057" num="49" wdcount="27"> Iraqi, which is the size of California, has an estimated 1 million troops among its 17 million populace, compared to 20,300 members of the Kuwait armed forces.</s>

<s docid="AP900802-0057" num="50" wdcount="19"> In Baghdad, the official radio interspersed martial music with songs with slogans like, ``Greetings to the Revolution in Kuwait''.</s>

<s docid="AP900802-0057" num="51" wdcount="11"> The invasion followed massive troop movements to the south on Wednesday.</s>

<s docid="AP900802-0057" num="52" wdcount="27"> In Kuwait early Thursday, the rattle of automatic guns sounded and explosions in rapid succession shook local residents from their sleep and the Kuwaiti Cabinet quickly assembled.</s>

<s docid="AP900802-0057" num="53" wdcount="27"> Residents in downtown Kuwait reported formations of French-made Mirage jet fighters of the Kuwaiti air force taking to the skies in the direction of the border region.</s>

<s docid="AP900802-0057" num="54" wdcount="19"> The streets were empty; some people on rooftops of their houses reported hearing gunblasts growing in intensity and speed.</s>

<s docid="AP900802-0057" num="55" wdcount="22"> Moments later army tanks and armored personnel carriers were moving in the direction of the Royal Palace, apparently to reinforce the guards.</s>

<s docid="AP900802-0057" num="56" wdcount="11"> Kuwait is a former British protectorate that gained independence in 1961.</s>

<s docid="AP900802-0057" num="57" wdcount="16"> Its residents are among the wealthiest in the world because of the country's vast oil reserves.</s>

<s docid="AP900802-0057" num="58" wdcount="21"> In Tokyo, the dollar moved sharply higher along with oil prices during morning trading Thursday on news of Iraq's invasion .</s>
</TEXT>
</DOC>
