<DOC>
<DOCNO>

<s docid="AP900803-0004" num="1" wdcount="1"> AP900803-0004</s>
</DOCNO>
<FILEID>

<s docid="AP900803-0004" num="2" wdcount="2"> AP-NR-08-03-90 0819EDT</s>
</FILEID>
<FIRST>

<s docid="AP900803-0004" num="3" wdcount="5"> r i PM-Iraq-Analysis 08-03 0895</s>
</FIRST>
<SECOND>

<s docid="AP900803-0004" num="4" wdcount="1"> PM-Iraq-Analysis,0923</s>
</SECOND>
<HEAD>

<s docid="AP900803-0004" num="5" wdcount="8"> Saddam Grabs Kuwait to Fulfill Territorial, Financial Ambitions</s>
</HEAD>
<NOTE>

<s docid="AP900803-0004" num="6" wdcount="7"> Eds: Also in Friday AMs report .</s>
</NOTE>
<HEAD>

<s docid="AP900803-0004" num="7" wdcount="3"> With PM-Iraq-Kuwait, Bjt</s>
</HEAD>
<HEAD>

<s docid="AP900803-0004" num="8" wdcount="6"> LaserPhotos NY4, LON2 of Aug. 2</s>
</HEAD>
<HEAD>

<s docid="AP900803-0004" num="9" wdcount="4"> An AP News Analysis</s>
</HEAD>
<BYLINE>

<s docid="AP900803-0004" num="10" wdcount="3"> By NEIL MacFARQUHAR</s>
</BYLINE>
<BYLINE>

<s docid="AP900803-0004" num="11" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900803-0004" num="12" wdcount="3"> NICOSIA, Cyprus (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900803-0004" num="13" wdcount="22"> Iraqi President Saddam Hussein seemed determined to solve his financial problems and fulfill territorial ambitions by dethroning the government of neighboring Kuwait.</s>

<s docid="AP900803-0004" num="14" wdcount="25"> The invasion, unprecedented in modern Arab history, reflected the brutality Saddam has used to crush all opposition at home since coming to power in 1979.</s>

<s docid="AP900803-0004" num="15" wdcount="28"> The sentence for criticizing Saddam is death, and the president considered Kuwait's oil overproduction and the subsequent fall in the price of oil a personal affront to Iraq.</s>

<s docid="AP900803-0004" num="16" wdcount="16"> ``Iraqis will not forget the saying that cutting necks is better than cutting means of living.</s>

<s docid="AP900803-0004" num="17" wdcount="21"> Oh God Almighty, be witness that we have warned them,'' he said last month after prices tumbled below $14 per barrel.</s>

<s docid="AP900803-0004" num="18" wdcount="29"> He accused Kuwait and the United Arab Emirates of costing Iraq $14 billion in lost oil revenue by ignoring their quotas assigned by the Organization of Petroleum Exporting Countries.</s>

<s docid="AP900803-0004" num="19" wdcount="37"> He also accused Kuwait of stealing $2.4 billion by pumping oil from a disputed field that straddled their border, and demanded that Kuwait write off an estimated $15 billion it loaned Iraq during the Persian Gulf war.</s>

<s docid="AP900803-0004" num="20" wdcount="15"> Saddam was reported to be incensed that Kuwait was demanding repayment for the wartime loans.</s>

<s docid="AP900803-0004" num="21" wdcount="27"> Saddam said he fought the war to protect the Arabs from the fundamentalist revolution fomented by the late Ayatollah Ruhollah Khomeini in Persian, mainly Shiite Moslem Iran.</s>

<s docid="AP900803-0004" num="22" wdcount="28"> Never mind that Iraq started the war in 1980 by invading Iran after a series of border skirmishes along the Shatt-al-Arab waterway, Iraq's only outlet to the Gulf.</s>

<s docid="AP900803-0004" num="23" wdcount="20"> Despite claims that the war was an unprecedented victory, the long conflict stalled Iraq's development, dragging on for eight years.</s>

<s docid="AP900803-0004" num="24" wdcount="6"> It has still not formally ended.</s>

<s docid="AP900803-0004" num="25" wdcount="19"> The war bills kept the government from delivering material benefits promised to the Iraqi people directly after the war.</s>

<s docid="AP900803-0004" num="26" wdcount="18"> The 1990 budget slashed funds for imports and Iraqis were told to brace for another year of austerity.</s>

<s docid="AP900803-0004" num="27" wdcount="7"> Private investment has failed to take hold.</s>

<s docid="AP900803-0004" num="28" wdcount="10"> Iraq ended the war an estimated $70 billion in debt.</s>

<s docid="AP900803-0004" num="29" wdcount="14"> Its main gulf port of Basra is still blocked and its oil infrastructure damaged.</s>

<s docid="AP900803-0004" num="30" wdcount="21"> Tens of thousands of Iraqi prisoners of war languish in Iranian prisons and an estimated 500,000 Iraqis were killed or wounded.</s>

<s docid="AP900803-0004" num="31" wdcount="13"> Despite its puny size, Kuwait's oil reserves almost match Iraq's 100 billion barrels.</s>

<s docid="AP900803-0004" num="32" wdcount="24"> By controlling Kuwait, Saddam could help solve the financial hangover from the Persian Gulf war and fulfill Iraq's longstanding wish for more gulf coastline.</s>

<s docid="AP900803-0004" num="33" wdcount="26"> Iraq's 100,000 troops massed at the border in the past few weeks were believed part of a pressure campaign to make Kuwait capitulate to Iraq's demands.</s>

<s docid="AP900803-0004" num="34" wdcount="35"> But Kuwait's pledge two weeks ago to obey new OPEC quotas and Saddam's promise to Egyptian President Hosni Mubarak that he would not invade lulled the Arab world into the sense the crisis was over.</s>

<s docid="AP900803-0004" num="35" wdcount="20"> Homage to the cause of Arab unity has been paramount in Middle East politics since postwar independence from colonial powers.</s>

<s docid="AP900803-0004" num="36" wdcount="33"> Although a civil war in Yemen in the 1960s brought Egyptian and Saudi Arabian intervention on opposing sides, no Arab state has ever directly deposed the government of a fellow Arab League member.</s>

<s docid="AP900803-0004" num="37" wdcount="18"> Despite Iraqi claims that it is helping internal opposition liberate Kuwait, it has long coveted the tiny emirate.</s>

<s docid="AP900803-0004" num="38" wdcount="24"> The Iraqi government refused to recognize its independence in 1961 and threatened to attack then, but backed down when Britain landed troops in Kuwait.</s>

<s docid="AP900803-0004" num="39" wdcount="8"> The invasion shook Kuwait's neighbors along the Gulf.</s>

<s docid="AP900803-0004" num="40" wdcount="22"> It proved the decade-old Gulf Cooperation Council that groups Saudi Arabia, Bahrain, Qatar, the United Arab Emirates, Oman and Kuwait was toothless.</s>

<s docid="AP900803-0004" num="41" wdcount="14"> The GCC did not issue a statement, much less implement its mutual defense treaty.</s>

<s docid="AP900803-0004" num="42" wdcount="23"> While Iraq was unlikely to invade Saudi Arabia, it could use the precedent of Kuwait to browbeat its neighbors on local policy issues.</s>

<s docid="AP900803-0004" num="43" wdcount="20"> Bombing an oil field would be a sufficient reminder of what happened to Kuwait when it balked at Iraqi demands.</s>

<s docid="AP900803-0004" num="44" wdcount="19"> Also in a region entirely ruled by absolute monarchs, the fall of one makes the rest feel extremely vulnerable.</s>

<s docid="AP900803-0004" num="45" wdcount="18"> In a series of bellicose statements in recent months, Saddam has sought to focus domestic attention outside Iraq.</s>

<s docid="AP900803-0004" num="46" wdcount="23"> In March he threatened to burn half of Israel with Iraq's chemical weapons _ banned under international law _ if Iraq was attacked.</s>

<s docid="AP900803-0004" num="47" wdcount="23"> It was a popular stance among Arabs frustrated with the lack of progress toward peace and a Palestinian nation in the Arab-Israeli conflict.</s>

<s docid="AP900803-0004" num="48" wdcount="14"> Then Britain arrested several people on charges they were smuggling nuclear triggers into Baghdad.</s>

<s docid="AP900803-0004" num="49" wdcount="23"> Weeks later, police in Europe impounded what they said was parts to a supergun capable of firing chemical or nuclear shells into Israel.</s>

<s docid="AP900803-0004" num="50" wdcount="16"> Saddam cried foul, claiming the West was trying to wreck the scientific progress of the Arabs.</s>

<s docid="AP900803-0004" num="51" wdcount="22"> Saddam has sought to inherit the mantle of the late Egyptian President Gamal Abdel Nassar as the leader of the Arab world.</s>

<s docid="AP900803-0004" num="52" wdcount="12"> His relentless personality cult has dubbed him ``The Knight of the Arabs''.</s>

<s docid="AP900803-0004" num="53" wdcount="9"> For Kuwait on Thursday, he was a dark knight.</s>

<s docid="AP900803-0004" num="54" wdcount="20"> Asked the reason for the invasion, Kuwait's ambassador to Washington Sheik Saud Nasir Al-Sabah said at a news conference: ``Ambition.</s>

<s docid="AP900803-0004" num="55" wdcount="6"> Hegemony. Control of the whole area.</s>

<s docid="AP900803-0004" num="56" wdcount="7"> There is not any reason for it.''</s>
</TEXT>
</DOC>
