<DOC>
<DOCNO>

<s docid="AP900802-0077" num="1" wdcount="1"> AP900802-0077</s>
</DOCNO>
<FILEID>

<s docid="AP900802-0077" num="2" wdcount="2"> AP-NR-08-02-90 0708EDT</s>
</FILEID>
<FIRST>

<s docid="AP900802-0077" num="3" wdcount="7"> u i PM-Iraq-Kuwait 3rdLd-Writethru 1stAdd 08-02 0658</s>
</FIRST>
<SECOND>

<s docid="AP900802-0077" num="4" wdcount="6"> PM-Iraq-Kuwait, 3rd Ld-Writethru, 1st Add, a0544,0675</s>
</SECOND>
<HEAD>

<s docid="AP900802-0077" num="5" wdcount="4"> KUWAIT: in Kuwait .</s>
</HEAD>
<TEXT>

<s docid="AP900802-0077" num="6" wdcount="18"> The British Embassy was hit by shellfire and the Sheraton and Hilton hotels evacuated their clientele, sources said.</s>

<s docid="AP900802-0077" num="7" wdcount="21"> Swiss charge d'affaires Franco Bessoni said on French radio that the palace was taken after bombardment by Iraqi MiG jet fighters.</s>

<s docid="AP900802-0077" num="8" wdcount="8"> ``You can see black smoke over there ....</s>

<s docid="AP900802-0077" num="9" wdcount="6"> No one dares to go out.</s>

<s docid="AP900802-0077" num="10" wdcount="4"> You can hear gunfire.</s>

<s docid="AP900802-0077" num="11" wdcount="9"> The entire foreign community is staying indoors,'' he said.</s>

<s docid="AP900802-0077" num="12" wdcount="20"> ``It's chaos, military jets are flying over all the time, Kathy McGregor, a Canadian, said by telephone at about midday.</s>

<s docid="AP900802-0077" num="13" wdcount="8"> She said she could still hear artillery fire.</s>

<s docid="AP900802-0077" num="14" wdcount="11"> The air space over Kuwait was closed, with airliners turned away.</s>

<s docid="AP900802-0077" num="15" wdcount="8"> Iraq also sealed its own borders and airspace.</s>

<s docid="AP900802-0077" num="16" wdcount="24"> Iraq said in a statement that it had ``responded to the request from interim government of free Kuwait and decided to cooperate with it''.</s>

<s docid="AP900802-0077" num="17" wdcount="21"> It said its troops _ no numbers were given _ were in Kuwait to defend the revolution and the Kuwaiti people.</s>

<s docid="AP900802-0077" num="18" wdcount="9"> There was no further identification of the revolutionary government.</s>

<s docid="AP900802-0077" num="19" wdcount="18"> Saddam's ruling council also warned that any foreign troops trying to interfere with its actions would be attacked.</s>

<s docid="AP900802-0077" num="20" wdcount="21"> Kuwaiti forces had engaged the Iraqi invaders with heavy artillery in their failed attempt to repulse them, Kuwaiti officials said earlier.</s>

<s docid="AP900802-0077" num="21" wdcount="22"> The invaders were led by the elite Republican Guard that did the brunt of the fighting in the 1980-88 war with Iran.</s>

<s docid="AP900802-0077" num="22" wdcount="22"> Iraq has an estimated 1 million troops _ including reservists _ among its 16 million people, compared to 20,300 troops in Kuwait.</s>

<s docid="AP900802-0077" num="23" wdcount="26"> Iraqi radio said 15 army divisions were being recalled and ordered all men born between 1960 and 1966 to report to the army within three days.</s>

<s docid="AP900802-0077" num="24" wdcount="10"> Today's fighting quickly sent oil prices surging in international markets.</s>

<s docid="AP900802-0077" num="25" wdcount="24"> The price of North Sea Brent crude for September delivery was quoted early today at $22.30 a barrel against Wednesday's London close of $20.40.</s>

<s docid="AP900802-0077" num="26" wdcount="20"> Iraq, the world's second-largest oil producer, had demanded higher oil prices at last month's OPEC oil cartel meeting in Geneva.</s>

<s docid="AP900802-0077" num="27" wdcount="23"> Saddam had threatened military action against Kuwait and the United Arab Emirates for exceeding their cartel production quotas and driving crude prices down.</s>

<s docid="AP900802-0077" num="28" wdcount="8"> OPEC agreed to cut output to boost prices.</s>

<s docid="AP900802-0077" num="29" wdcount="16"> The invasion came a day after talks between Kuwait and Iraq collapsed in Jiddah, Saudi Arabia.</s>

<s docid="AP900802-0077" num="30" wdcount="9"> Kuwait had apparently refused to bend to Iraqi demands.</s>

<s docid="AP900802-0077" num="31" wdcount="27"> The crisis began July 17 when Saddam accused Kuwait of trying to wreck the debt-ridden Iraqi economy with oil overproduction and began massing troops on Kuwait's border.</s>

<s docid="AP900802-0077" num="32" wdcount="17"> He also accused Kuwait of stealing $2.4 billion in oil drilled from the border oil field, Rumailah.</s>

<s docid="AP900802-0077" num="33" wdcount="18"> Iraq also demanded the Kuwaiti island of Bubiyan, which is opposite Iraq's only outlets to the Persian Gulf.</s>

<s docid="AP900802-0077" num="34" wdcount="27"> Iraq, which reportedly massed about 100,000 troops at the border on Wednesday, has been engaged in a major defense buildup since Saddam came to power in 1979.</s>

<s docid="AP900802-0077" num="35" wdcount="14"> But the Iran-Iraq war left it with a foreign debt of about $70 billion.</s>

<s docid="AP900802-0077" num="36" wdcount="13"> Iraq borrowed $10 billion to $20 billion from Kuwait wants that debt forgiven.</s>

<s docid="AP900802-0077" num="37" wdcount="26"> In Kuwait early today, the rattle of automatic guns sounded and explosions in rapid succession shook residents from their sleep and the Kuwaiti Cabinet quickly assembled.</s>

<s docid="AP900802-0077" num="38" wdcount="23"> The Cabinet was holed up at the headquarters of the Supreme Defense Council with telephone and telex links cut off, said official sources.</s>

<s docid="AP900802-0077" num="39" wdcount="15"> Kuwaiti radio briefly stopped broadcasting, then went back on the air on a different wavelength.</s>

<s docid="AP900802-0077" num="40" wdcount="18"> A speaker believed to be Crown Prince and Prime Minister Sheik Saad al-Abdullah al-Sabah appealed for Arab support.</s>

<s docid="AP900802-0077" num="41" wdcount="14"> ``Oh Arabs, Kuwait's blood and honor is being violated, rush to its rescue ...</s>

<s docid="AP900802-0077" num="42" wdcount="16"> the children, the women, the old men of Kuwait are calling on you,'' the speaker said.</s>

<s docid="AP900802-0077" num="43" wdcount="17"> Kuwait, nearly the size of New Jersey, is a former British protectorate that gained independence in 1961.</s>

<s docid="AP900802-0077" num="44" wdcount="17"> Its residents are among the wealthiest in the world because of the country's vast oil reserves .</s>
</TEXT>
</DOC>
