<DOC>
<DOCNO>

<s docid="AP900805-0019" num="1" wdcount="1"> AP900805-0019</s>
</DOCNO>
<FILEID>

<s docid="AP900805-0019" num="2" wdcount="2"> AP-NR-08-05-90 0937EDT</s>
</FILEID>
<FIRST>

<s docid="AP900805-0019" num="3" wdcount="6"> u i BC-Iraq-Kuwait 3rdLd-Writethru 08-05 0810</s>
</FIRST>
<SECOND>

<s docid="AP900805-0019" num="4" wdcount="3"> BC-Iraq-Kuwait, 3rd Ld-Writethru,a0696,0829</s>
</SECOND>
<HEAD>

<s docid="AP900805-0019" num="5" wdcount="7"> Iraqi-Installed Kuwaiti Government Says Withdrawal Under Way</s>
</HEAD>
<NOTE>

<s docid="AP900805-0019" num="6" wdcount="32"> Eds: New thruout to UPDATE comment on formerly missing Americans, reporters in Iraq brought to see returning Iraqi soldiers, Jordan refusing to back new Kuwaiti government, denial that new government contains Iraqis.</s>

<s docid="AP900805-0019" num="7" wdcount="3"> No pickup .</s>
</NOTE>
<BYLINE>

<s docid="AP900805-0019" num="8" wdcount="3"> By SALAH NASRAWI</s>
</BYLINE>
<BYLINE>

<s docid="AP900805-0019" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900805-0019" num="10" wdcount="3"> BAGHDAD, Iraq (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900805-0019" num="11" wdcount="31"> The radio of Kuwait's new Iraqi-installed government claimed that Iraqi troops began pulling out of Kuwait on Sunday, but the United States said it doubted a withdrawal was really under way.</s>

<s docid="AP900805-0019" num="12" wdcount="35"> The radio announcement came three days after Iraq invaded Kuwait and one day after Baghdad said it had replaced the oil-rich kingdom's ousted monarchy with a new government made up of nine Kuwaiti army offices.</s>

<s docid="AP900805-0019" num="13" wdcount="33"> Iraq also said Saturday that it was creating a new Kuwaiti army and that 100,000 Iraqis, the approximate number of soldiers Baghdad took over Kuwait with, had volunteered for the new military force.</s>

<s docid="AP900805-0019" num="14" wdcount="35"> In other developments: _The White House continued to seek the immediate and unconditional withdrawl of all Iraqi troops, and it thanked the many nations who have condemned the invasion and imposed economic sanctions on Baghdad.</s>

<s docid="AP900805-0019" num="15" wdcount="23"> _After several days of debate, Japan on Sunday banned all oil imports from Iraq and Kuwait and halted Japanese exports to both countries.</s>

<s docid="AP900805-0019" num="16" wdcount="21"> Tokyo said it would suspend all loans to Iraq and Kuwait, ban Japanese investment there, and freeze Iraqi assets in Japan.</s>

<s docid="AP900805-0019" num="17" wdcount="23"> Japan, which imports 99 percent of its oil, had relied on Iraq and Kuwait for more than 11 percent of its oil imports.</s>

<s docid="AP900805-0019" num="18" wdcount="26"> The White House hailed Japan's move and said Prime Minister Toshiki Kaifu called President Bush on Sunday at Camp David to inform him about the sanctions.</s>

<s docid="AP900805-0019" num="19" wdcount="32"> _Although tens of thousands of Iraqi troops reportedly remained massed near Kuwait's border with Saudi Arabia, Washington said on Sunday there was no indication that any soldiers had moved into Saudi Arabia.</s>

<s docid="AP900805-0019" num="20" wdcount="22"> _The White House said that 11 American oil workers rounded up after the invasion had been brought to Baghdad, talked with U.S.</s>

<s docid="AP900805-0019" num="21" wdcount="7"> Embassy officials, and were in good shape.</s>

<s docid="AP900805-0019" num="22" wdcount="8"> It said that accounts for all missing Americans.</s>

<s docid="AP900805-0019" num="23" wdcount="22"> _An unconfirmed report said a warplane from the deposed emir's air force in Kuwait bombed an Iraqi military headquarters near Kuwait city.</s>

<s docid="AP900805-0019" num="24" wdcount="17"> It was not clear where the plane came from or whether its reported attack caused any damage.</s>

<s docid="AP900805-0019" num="25" wdcount="21"> The radio of Kuwait's new government, monitored in Bahrain, quoted its ``military correspondent'' as saying the pullout began at 8 a.m.</s>

<s docid="AP900805-0019" num="26" wdcount="2"> (1 a.m.</s>

<s docid="AP900805-0019" num="27" wdcount="25"> EDT). Iraqi President Saddam Hussein allowed reporters based in Baghdad to be taken south to Basra overnight to observe the first Iraqi troops return home.</s>

<s docid="AP900805-0019" num="28" wdcount="27"> But at the White House, press secretary Marlin Fitzwater said on Sunday morning: ``We have no independent or confirmable information on this report (of the withdrawl beginning).</s>

<s docid="AP900805-0019" num="29" wdcount="13"> Saddam Hussein's actions in the past have raised serious skepticism about his intentions''.</s>

<s docid="AP900805-0019" num="30" wdcount="19"> Iraq declared earlier that the provisional government installed by Baghdad is capable of ensuring security in the occupied country.</s>

<s docid="AP900805-0019" num="31" wdcount="11"> Baghdad television has said the new government is headed by Col.</s>

<s docid="AP900805-0019" num="32" wdcount="23"> Ala Hussein Ali and that he holds the positions of prime minister, commander-in-chief of the armed forces, minister of defense and interior minister.</s>

<s docid="AP900805-0019" num="33" wdcount="9"> The other eight members were lieutenant colonels and majors.</s>

<s docid="AP900805-0019" num="34" wdcount="24"> But Kuwait's embassy in Amman, Jordan, on Sunday dismissed the new government as ``a list of fake names'' and said Ali is Saddam's son-in-law.</s>

<s docid="AP900805-0019" num="35" wdcount="11"> A similar report appeared in one of Cairo's leading newspapers, Al-Ahram.</s>

<s docid="AP900805-0019" num="36" wdcount="17"> It quoted the Kuwait Embassy in Tunis which said that Ali works with Saddam's administration in Baghdad.</s>

<s docid="AP900805-0019" num="37" wdcount="22"> The Iraqi news agency carried a Kuwait-datelined statement it said was from the provisional government, denying any of its members were Iraqis.</s>

<s docid="AP900805-0019" num="38" wdcount="25"> In Jordan, Prime Minister Mudar Badran said his nation will not recognize the new government because that would hinder Arab efforts to end the conflict.</s>

<s docid="AP900805-0019" num="39" wdcount="11"> U.S., French and British warships, meanwhile, steamed toward the Persian Gulf.</s>

<s docid="AP900805-0019" num="40" wdcount="16"> President Bush said Friday that if Iraq moved against Saudi Arabia it would be attacking U.S.</s>

<s docid="AP900805-0019" num="41" wdcount="2"> ``vital interests''.</s>

<s docid="AP900805-0019" num="42" wdcount="18"> On Saturday, Bush said in Washington that the use of force in resolving the crisis remains an option.</s>

<s docid="AP900805-0019" num="43" wdcount="13"> Saudi Arabia ships 1.2 million barrels of oil to the United States daily.</s>

<s docid="AP900805-0019" num="44" wdcount="37"> Fitzwater said on Sunday that there was no indication Iraqi forces had moved into Saudi Arabia, even though tens of thousands of them have been reported to be within 5 to 10 miles of the Saudi border.</s>

<s docid="AP900805-0019" num="45" wdcount="22"> In Washington, Iraqi ambassador Mohammed al-Mashat on Saturday denied U.S. and other foreign reports suggesting that Iraq plans to invade Saudi Arabia.</s>

<s docid="AP900805-0019" num="46" wdcount="20"> Saddam ordered the invasion of Kuwait after accusing it of stealing oil from a field that straddles their disputed border.</s>

<s docid="AP900805-0019" num="47" wdcount="32"> He also blamed Kuwait for a fall in oil prices that cost Iraq $14 billion, saying it contributed to the oil glut by cheating on its OPEC oil cartel production quotas .</s>
</TEXT>
</DOC>
