<DOC>
<DOCNO>

<s docid="AP900801-0004" num="1" wdcount="1"> AP900801-0004</s>
</DOCNO>
<FILEID>

<s docid="AP900801-0004" num="2" wdcount="2"> AP-NR-08-01-90 2330EDT</s>
</FILEID>
<FIRST>

<s docid="AP900801-0004" num="3" wdcount="6"> b w AM-IraqOffensive 1stLd-Writethru 08-01 0344</s>
</FIRST>
<SECOND>

<s docid="AP900801-0004" num="4" wdcount="4"> AM-Iraq Offensive, 1st Ld-Writethru,a0825,300</s>
</SECOND>
<HEAD>

<s docid="AP900801-0004" num="5" wdcount="4"> Kuwait Claims Iraqi Invasion</s>
</HEAD>
<NOTE>

<s docid="AP900801-0004" num="6" wdcount="19"> EDs: SUBS 4th graf: ``Earlier in,'' to name ambassador; INSERTS 7th graf: ``The United,'' to note joint USA-UAE exercises</s>
</NOTE>
<DATELINE>

<s docid="AP900801-0004" num="7" wdcount="2"> WASHINGTON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900801-0004" num="8" wdcount="14"> Iraqi troops have launched an offensive against Kuwait, the Kuwaiti embassy said Wednesday night.</s>

<s docid="AP900801-0004" num="9" wdcount="22"> Faleh Bader, director of the ambassador's office, said, ``We confirm there is an offensive at Kuwait border and we have no comment''.</s>

<s docid="AP900801-0004" num="10" wdcount="9"> The attack started about midnight, Kuwaiti time (5 p.m.</s>

<s docid="AP900801-0004" num="11" wdcount="3"> EDT), Bader said.</s>

<s docid="AP900801-0004" num="12" wdcount="24"> Earlier in the day, the Iraqi ambassador, Mohamed Al-Mashat, was summoned to the State Department afternoon for a meeting with Assistant Secretary John Kelly.</s>

<s docid="AP900801-0004" num="13" wdcount="36"> Department spokesman Richard Boucher said Kelly repeated to the Iraqi envoy the U.S. desire for a peaceful solution to the tensions with Kuwait and urged Iraq to respect to sovereignty of all nations in the region.</s>

<s docid="AP900801-0004" num="14" wdcount="38"> Kelly told a House subcommittee Tuesday that while the United States has no treaty obligations that would mandate military support for Kuwait, the United States does believe strongly in respect for territories of all states in the region.</s>

<s docid="AP900801-0004" num="15" wdcount="22"> The United States, whose Persian Gulf naval patrols helped Iraq defeat Iran in the 1980-1988 war, has six warships in the area.</s>

<s docid="AP900801-0004" num="16" wdcount="21"> They have been conducting exercises since July 23 with forces of the United Arab Emirates, some 700 miles southest of Kuwait.</s>

<s docid="AP900801-0004" num="17" wdcount="47"> Iraq had moved about 100,000 troops to its border with Kuwait after claiming that Kuwait's production of oil beyond quotas of the OPEC cartel had depressed the world price, thus diminishing Iraq's revenue, and that Kuwait had been stealing oil from a field that straddles the border.</s>

<s docid="AP900801-0004" num="18" wdcount="29"> Iraqi officials on Wednesday walked out on talks in Jiddah, Saudia Arabia aimed at resolving the 2-week-old crisis with neighboring Kuwait and complained that Kuwait was not negotiating seriously.</s>

<s docid="AP900801-0004" num="19" wdcount="15"> Iraq threatened to invade once before, in 1961 after Britain ended its protectorate over Kuwait.</s>

<s docid="AP900801-0004" num="20" wdcount="33"> Iraq then claimed Kuwait as part of its territory, but the appearance on the Kuwaiti side of the border of troops from Britain and other Arab states deterred further action by Iraq .</s>
</TEXT>
</DOC>
