<DOC>
<DOCNO>

<s docid="AP900802-0135" num="1" wdcount="1"> AP900802-0135</s>
</DOCNO>
<FILEID>

<s docid="AP900802-0135" num="2" wdcount="2"> AP-NR-08-02-90 1504EDT</s>
</FILEID>
<FIRST>

<s docid="AP900802-0135" num="3" wdcount="6"> u i PM-Iraq-Kuwait 10thLd-Writethru 08-02 1032</s>
</FIRST>
<SECOND>

<s docid="AP900802-0135" num="4" wdcount="3"> PM-Iraq-Kuwait, 10th Ld-Writethru,a0684-71,1068</s>
</SECOND>
<HEAD>

<s docid="AP900802-0135" num="5" wdcount="1"> URGENT</s>
</HEAD>
<HEAD>

<s docid="AP900802-0135" num="6" wdcount="4"> Iraq Invades Kuwait; U.S.</s>

<s docid="AP900802-0135" num="7" wdcount="3"> Responds With Sanctions</s>
</HEAD>
<NOTE>

<s docid="AP900802-0135" num="8" wdcount="29"> Eds: Inserts 1 graf after 12th, `A Pentagon'... to UPDATE with Baker to fly to Moscow for joint statement, sub 20th, `Egypt's Middle'... to UPDATE with diplomats confirming death.</s>

<s docid="AP900802-0135" num="9" wdcount="8"> Pickup 1st graf of a0571, `Kuwait radio.. .</s>
</NOTE>
<HEAD>

<s docid="AP900802-0135" num="10" wdcount="3"> LaserPhotos NY4,5,6,8; LaserGraphics</s>
</HEAD>
<BYLINE>

<s docid="AP900802-0135" num="11" wdcount="3"> By STEPHANIE McGEHEE</s>
</BYLINE>
<DATELINE>

<s docid="AP900802-0135" num="12" wdcount="2"> KUWAIT (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900802-0135" num="13" wdcount="10"> Iraq's powerful army invaded this small oil-rich kingdom early today.</s>

<s docid="AP900802-0135" num="14" wdcount="20"> Tank-led troops quickly seized the ruler's palace and government buildings, and the emir fled to Saudi Arabia, Kuwaiti officials said.</s>

<s docid="AP900802-0135" num="15" wdcount="22"> Kuwait's U.S. ambassador said the Iraqis occupied all government buildings in the capital and were moving south toward the country's oil facilities.</s>

<s docid="AP900802-0135" num="16" wdcount="6"> He appealed for U.S. military intervention.</s>

<s docid="AP900802-0135" num="17" wdcount="5"> A Pentagon source said U.S.</s>

<s docid="AP900802-0135" num="18" wdcount="19"> Navy ships were diverted to the region, but President Bush said the subject of intervention was not being discussed.</s>

<s docid="AP900802-0135" num="19" wdcount="16"> ``The Iraqis have occupied all of Kuwait''! a Kuwaiti government official shouted in a telephone interview.</s>

<s docid="AP900802-0135" num="20" wdcount="16"> Diplomatic sources in the Persian Gulf estimated that more than 200 Kuwaitis were killed or wounded.</s>

<s docid="AP900802-0135" num="21" wdcount="29"> The Iraqi government of President Saddam Hussein claimed it invaded at the request of revolutionaries who had already staged a coup and established ``The Provisional Government of Free Kuwait''.</s>

<s docid="AP900802-0135" num="22" wdcount="10"> Kuwait and U.N. diplomats labeled the coup report a farce.</s>

<s docid="AP900802-0135" num="23" wdcount="24"> The assault followed two weeks of tension between Kuwait and Iraq, caused by Iraqi accusations that Kuwait stole oil from a disputed border area.</s>

<s docid="AP900802-0135" num="24" wdcount="21"> Saddam also accused Kuwait of exceeding OPEC production quotas, thus driving down the price of oil, a major Iraqi revenue source.</s>

<s docid="AP900802-0135" num="25" wdcount="22"> The attack had wide-ranging ramifications: _Oil prices soared $3 a barrel in early trading because of fears the invasion would disrupt supplies.</s>

<s docid="AP900802-0135" num="26" wdcount="6"> Prices were about $2 higher later.</s>

<s docid="AP900802-0135" num="27" wdcount="18"> _President Bush signed orders freezing Iraqi assets in the United States and blocking most Iraqi imports, including oil.</s>

<s docid="AP900802-0135" num="28" wdcount="22"> Oil accounts for 97 percent of Iraqi imports to the United States and makes up about 3.5 percent of U.S. oil consumption.</s>

<s docid="AP900802-0135" num="29" wdcount="11"> Bush also froze Kuwaiti assets to prevent Iraq from seizing them.</s>

<s docid="AP900802-0135" num="30" wdcount="10"> _The Soviet Union, Iraq's main arms supplier, halted weapons sales.</s>

<s docid="AP900802-0135" num="31" wdcount="2"> _The U.N.</s>

<s docid="AP900802-0135" num="32" wdcount="15"> Security Council voted 14-0 to denounce the invasion and demanded immediate withdrawal of Iraqi troops.</s>

<s docid="AP900802-0135" num="33" wdcount="31"> _A Pentagon source said the aircraft carrier USS Independence, escorted by a six-ship battle group, was diverted from the Indian Ocean toward the gulf, where other U.S. ships were already patrolling.</s>

<s docid="AP900802-0135" num="34" wdcount="29"> _Secretary of State James A. Baker III planned to fly to Moscow to issue a rare joint statement Friday with Soviet Foreign Minister Eduard A. Shevardnadze about the invasion.</s>

<s docid="AP900802-0135" num="35" wdcount="28"> The plan, which was announced in Washington, illustrates the dramatic improvement in relations between the superpowers, who once routinely lined up on opposite sides of most regional disputes.</s>

<s docid="AP900802-0135" num="36" wdcount="20"> Kuwait's U.S. ambassador, Sheik Saud Nasir al-Sabah, told reporters in Washington: ``We are desperate for any help we can get''.</s>

<s docid="AP900802-0135" num="37" wdcount="6"> He appealed specifically for American intervention.</s>

<s docid="AP900802-0135" num="38" wdcount="15"> In recent days, diplomats said Iraq had massed more than 100,000 troops at the border.</s>

<s docid="AP900802-0135" num="39" wdcount="7"> Kuwait's entire armed forces has 20,300 soldiers.</s>

<s docid="AP900802-0135" num="40" wdcount="16"> Bush said the United States would ``take whatever steps necessary'' to defend interests in the gulf.</s>

<s docid="AP900802-0135" num="41" wdcount="12"> Asked if this included military force, Bush said: ``We're not discussing intervention''.</s>

<s docid="AP900802-0135" num="42" wdcount="10"> But he said he would not discuss military options publicly.</s>

<s docid="AP900802-0135" num="43" wdcount="19"> It was the first time in modern history an Arab nation had invaded another and taken over its government.</s>

<s docid="AP900802-0135" num="44" wdcount="15"> Kuwait's army was no match for Iraq, battle-hardened after eight years of war with Iran.</s>

<s docid="AP900802-0135" num="45" wdcount="24"> Iraq has emerged as the Arab world's strongest and most militant military power, and Saddam has a vast arsenal of chemical and conventional weapons.</s>

<s docid="AP900802-0135" num="46" wdcount="22"> Diplomats said about 350 Iraqi tanks wheeled into the capital a few hours after crossing the border 40 miles away at dawn.</s>

<s docid="AP900802-0135" num="47" wdcount="17"> Witnesses said the bombardment of ports and military airports by artillery and the air force was vicious.</s>

<s docid="AP900802-0135" num="48" wdcount="12"> The invaders surrounded the palace of Kuwait's ruler, Sheik Jaber al-Ahmed al-Sabah.</s>

<s docid="AP900802-0135" num="49" wdcount="14"> Residents said the palace was seized after about two hours of heavy artillery barrages.</s>

<s docid="AP900802-0135" num="50" wdcount="19"> Diplomats said Sheik Fahd al-Ahmed al-Sabah, one of the emir's brothers, was killed while trying to defend the palace.</s>

<s docid="AP900802-0135" num="51" wdcount="15"> There were about 50 tanks around the palace and the neighboring American Embassy, residents said.</s>

<s docid="AP900802-0135" num="52" wdcount="11"> The al-Sabah family has ruled the city-state for almost 250 years.</s>

<s docid="AP900802-0135" num="53" wdcount="11"> The Kuwaiti ambassador said the leaders were safe in Saudi Arabia.</s>

<s docid="AP900802-0135" num="54" wdcount="35"> Operating from an unknown location, al-Ahmed's government responded to the formation of the provisional government by stating: ``Kuwait is Kuwait to its people, let by the emir, Sheik Jaber, and his Crown Prince Sheik Saad.</s>

<s docid="AP900802-0135" num="55" wdcount="6"> God preserve them from all harm''.</s>

<s docid="AP900802-0135" num="56" wdcount="29"> For its part, the provisional government announced through Baghdad's official Iraqi News Agency that it was dissolving parliament and would hold ``free and honest elections'' at a future date.</s>

<s docid="AP900802-0135" num="57" wdcount="20"> The Iraqi forces were led by the elite Republican Guard, which did the brunt of fighting in the Iran-Iraq war.</s>

<s docid="AP900802-0135" num="58" wdcount="15"> Troops set up roadblocks at major intersections and shot at cars that did not stop.</s>

<s docid="AP900802-0135" num="59" wdcount="19"> Baghdad television said Iraq qould withdraw its forces within days or weeks, depending on how quickly the situation stabilized.</s>

<s docid="AP900802-0135" num="60" wdcount="11"> Kuwait's land and sea borders were closed, as was the airport.</s>

<s docid="AP900802-0135" num="61" wdcount="22"> Diplomats said the invasion was too swift to arrange the evacuation of nationals, and foreigners were asked to keep a low profile.</s>

<s docid="AP900802-0135" num="62" wdcount="24"> There are about 4,000 Americans among the large expatriate community in Kuwait, where more than 60 percent of the 1.8 million residents are foreigners.</s>

<s docid="AP900802-0135" num="63" wdcount="21"> U.S. officials monitoring the situation had no reports of harm to U.S. citizens in Iraq, White House spokesman Roman Popadiuk said.</s>

<s docid="AP900802-0135" num="64" wdcount="18"> Foreigners reached by telephone said they watched from their windows or dived for cover as the invasion began.</s>

<s docid="AP900802-0135" num="65" wdcount="9"> ``We were totally unprepared,'' said Catherine Baker of Illinois.</s>

<s docid="AP900802-0135" num="66" wdcount="11"> ``One feels like there should have been a bit of warning''.</s>

<s docid="AP900802-0135" num="67" wdcount="19"> The British Embassy was hit by shell-fire and the Sheraton and Hilton hotels evacuated their clientele, the diplomats said.</s>

<s docid="AP900802-0135" num="68" wdcount="16"> The invasion came hours after Iraq broke off talks intended to mend its differences with Kuwait.</s>

<s docid="AP900802-0135" num="69" wdcount="13"> Iraqi first threatened military action against its former ally Kuwait two weeks ago.</s>

<s docid="AP900802-0135" num="70" wdcount="9"> Washington declared its support for Kuwait from the start.</s>

<s docid="AP900802-0135" num="71" wdcount="16"> During the Iran-Iraq war, American ships protected U.S.-flagged Kuwaiti tankers from attacks in the gulf .</s>
</TEXT>
<HEAD>

<s docid="AP900802-0135" num="72" wdcount="5"> Kuwait radio, 1st graf, a0571</s>
</HEAD>
</DOC>
