<DOC>
<DOCNO>

<s docid="LA080390-0085" num="1" wdcount="1"> LA080390-0085</s>
</DOCNO>
<DOCID>

<s docid="LA080390-0085" num="2" wdcount="1"> 256481</s>
</DOCID>
<DATE>
<P>

<s docid="LA080390-0085" num="3" wdcount="6"> August 3, 1990, Friday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA080390-0085" num="4" wdcount="8"> Part A; Page 1; Column 3; Foreign Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA080390-0085" num="5" wdcount="2"> 1276 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA080390-0085" num="6" wdcount="7"> BUSH EMBARGOES TRADE AND FREEZES IRAQ ASSETS</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA080390-0085" num="7" wdcount="6"> By DAVID LAUTER, TIMES STAFF WRITER</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA080390-0085" num="8" wdcount="3"> ASPEN, Colo .</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA080390-0085" num="9" wdcount="36"> President Bush embargoed all trade with Iraq and froze the nation's assets in the United States on Thursday while refusing to rule out the use of U.S. troops to rescue Kuwait from its Iraqi invaders .</s>
</P>
<P>

<s docid="LA080390-0085" num="10" wdcount="22"> The trade embargo bars imports of oil from Iraq, which account for 3% to 4% of total U.S. oil supplies, officials said.</s>

<s docid="LA080390-0085" num="11" wdcount="25"> The move also prohibits Iraq from buying U.S. grain and other foodstuffs, which represent the other chief element of trade between the two nations .</s>
</P>
<P>

<s docid="LA080390-0085" num="12" wdcount="30"> Iraq's "naked aggression" against Kuwait has created "an emergency in the Persian Gulf," Bush said in a speech to the Aspen Institute, a nonprofit organization that focuses on global issues.</s>

<s docid="LA080390-0085" num="13" wdcount="16"> The United States, he said, would insist on "immediate and unconditional withdrawal" of Iraqi troops .</s>
</P>
<P>

<s docid="LA080390-0085" num="14" wdcount="14"> Referring to Iraqi President Saddam Hussein, Bush declared: "We find his behavior intolerable" .</s>
</P>
<P>

<s docid="LA080390-0085" num="15" wdcount="35"> The trade embargo represents the strongest international response so far to Iraq's massive invasion of its small and poorly defended neighbor, but it stopped short of the military intervention requested by desperate Kuwait officials .</s>
</P>
<P>

<s docid="LA080390-0085" num="16" wdcount="42"> But according to Bush Administration sources, the Pentagon stepped up air patrols in the Persian Gulf and began moving warships, equipment and supplies into the area in a signal to Iraq that the United States would act to halt further aggression .</s>
</P>
<P>

<s docid="LA080390-0085" num="17" wdcount="28"> A second executive order signed by the President early Thursday froze Kuwait's assets in the United States, a step taken to prevent Iraq from seizing Kuwaiti property .</s>
</P>
<P>

<s docid="LA080390-0085" num="18" wdcount="31"> "We expect our friends to stand by us in our time of need," Kuwait's ambassador to the United States, Sheik Saud al Nasir al Sabah, said at a Washington news conference.</s>

<s docid="LA080390-0085" num="19" wdcount="14"> "I think the U.S. intervention at this stage is both paramount and important" .</s>
</P>
<P>

<s docid="LA080390-0085" num="20" wdcount="24"> However, Iraq's ambassador to Washington, Mohammed al Mashat, said Iraq had invaded Kuwait in response to a request from the nation's "interim free government".</s>

<s docid="LA080390-0085" num="21" wdcount="15"> He warned the West not to consider "any foreign interference in the current events" .</s>
</P>
<P>

<s docid="LA080390-0085" num="22" wdcount="27"> Iraq's explanation was quickly denounced by the State Department, which said Baghdad's claim that its troops moved into Kuwait at that country's request is "patent fraud" .</s>
</P>
<P>

<s docid="LA080390-0085" num="23" wdcount="25"> In a related development, the State Department confirmed that invading Iraqi troops had rounded up six American oil field workers near the border of Kuwait.</s>

<s docid="LA080390-0085" num="24" wdcount="6"> Their whereabouts is not known .</s>
</P>
<P>

<s docid="LA080390-0085" num="25" wdcount="39"> Despite Bush's refusal to rule out military action, it appeared an unlikely option given the strength of Iraq's military, the limited U.S. forces in the region and the opposition to U.S. intervention from other countries in the area .</s>
</P>
<P>

<s docid="LA080390-0085" num="26" wdcount="18"> Officials said the Bush Administration's energies are focused mainly on organizing international economic and diplomatic pressure against Iraq.</s>

<s docid="LA080390-0085" num="27" wdcount="20"> Even so, the strongest economic weapon, an international ban on Iraqi oil exports, also appears unlikely to be employed .</s>
</P>
<P>

<s docid="LA080390-0085" num="28" wdcount="48"> At a joint news conference with British Prime Minister Margaret Thatcher, who is scheduled to give a speech to the nonprofit Aspen Institute on Sunday, Bush said that Secretary of State James A. Baker III will discuss the Persian Gulf situation with Soviet officials in Moscow today .</s>
</P>
<P>

<s docid="LA080390-0085" num="29" wdcount="38"> In Ulan Bator, Mongolia, where Baker was on an Asian visit, a Baker spokeswoman said that the United States and the Soviet Union plan to issue a joint statement later today condemning the Iraqi invasion of Kuwait .</s>
</P>
<P>

<s docid="LA080390-0085" num="30" wdcount="17"> Baker will meet with Soviet Foreign Minister Eduard A. Shevardnadze on a brief refueling stop in Moscow.</s>

<s docid="LA080390-0085" num="31" wdcount="27"> The meeting was arranged after Baker met with the Soviet ambassador to Mongolia, who described the Kremlin's plans for a strong Soviet stand on the invasion .</s>
</P>
<P>

<s docid="LA080390-0085" num="32" wdcount="36"> Baker, at a news conference in Ulan Bator early today, said there have been no reports of U.S casualties in Kuwait and that "the integrity of foreign embassies seems to have been preserved so far" .</s>
</P>
<P>

<s docid="LA080390-0085" num="33" wdcount="18"> He said the estimate of the number of Iraqi troops in Kuwait varies from 50,000 to 100,000 .</s>
</P>
<P>

<s docid="LA080390-0085" num="34" wdcount="21"> Bush flew to Colorado after meeting early in the morning with his National Security Council to discuss the Persian Gulf situation.</s>

<s docid="LA080390-0085" num="35" wdcount="16"> Originally, the President had planned to spend the night in Colorado and return to Washington today.</s>

<s docid="LA080390-0085" num="36" wdcount="9"> Instead, he returned to Washington on Thursday night .</s>
</P>
<P>

<s docid="LA080390-0085" num="37" wdcount="23"> Before leaving the capital Thursday morning, Bush told reporters at the White House that he was "not contemplating" any U.S. military involvement .</s>
</P>
<P>

<s docid="LA080390-0085" num="38" wdcount="17"> But later in the day, at the news conference with Thatcher, Bush moved away from that pledge.</s>

<s docid="LA080390-0085" num="39" wdcount="21"> He said that he had met during the day with top defense advisers and "we're not ruling any options out" .</s>
</P>
<P>

<s docid="LA080390-0085" num="40" wdcount="30"> The trade embargo imposed by Bush would cut off all commerce with Iraq, except news reporting, exports of publications and shipments of emergency relief supplies of food and medicine .</s>
</P>
<P>

<s docid="LA080390-0085" num="41" wdcount="18"> Like Bush, Thatcher has frozen Iraqi and Kuwaiti assets, but she has not imposed a trade embargo .</s>
</P>
<P>

<s docid="LA080390-0085" num="42" wdcount="17"> Iraq is highly dependent on oil exports to finance its large armed forces and considerable national debt.</s>

<s docid="LA080390-0085" num="43" wdcount="32"> But Europe and Japan are far more dependent on Middle Eastern oil than is the United States, and an international oil embargo on Iraq would be painful for many U.S. allies .</s>
</P>
<P>

<s docid="LA080390-0085" num="44" wdcount="17"> At the joint news conference, Thatcher called for U.N. actions to impose additional trade sanctions against Iraq.</s>

<s docid="LA080390-0085" num="45" wdcount="10"> Asked about an oil embargo, however, she stopped short .</s>
</P>
<P>

<s docid="LA080390-0085" num="46" wdcount="8"> "We are prepared to support in the (U.N).</s>

<s docid="LA080390-0085" num="47" wdcount="19"> Security Council those measures which collectively we can agree to and which collectively we can make effective," she said.</s>

<s docid="LA080390-0085" num="48" wdcount="6"> "Those are the two tests" .</s>
</P>
<P>

<s docid="LA080390-0085" num="49" wdcount="36"> Bush spent the day discussing the Iraqi invasion with senior advisers and other heads of state, including the heads of Egypt, Yemen and Jordan, Arab leaders whom the President described as "friends of the United States".</s>

<s docid="LA080390-0085" num="50" wdcount="25"> The Arab leaders, Bush said, had appealed to him for "restraint" and "a short period of time" in which to develop an "Arab solution" .</s>
</P>
<P>

<s docid="LA080390-0085" num="51" wdcount="25"> Bush expressed sympathy with the Arab effort but added that "I made clear to them that it had gone beyond simply a regional dispute" .</s>
</P>
<P>

<s docid="LA080390-0085" num="52" wdcount="20"> Later Thursday, the White House said that Bush had spoken with King Fahd of Saudi Arabia for about 30 minutes.</s>

<s docid="LA080390-0085" num="53" wdcount="22"> The statement said the two leaders agreed that the invasion was "unacceptable" and "discussed possible options for dealing with the situation" .</s>
</P>
<P>

<s docid="LA080390-0085" num="54" wdcount="17"> At a news conference in Washington, Kuwaiti ambassador Saud appealed to the United States for military assistance.</s>

<s docid="LA080390-0085" num="55" wdcount="24"> "My people are suffering," Saud said, adding that Kuwait is requesting aid "from everyone who has conscience and fair play around this world" .</s>
</P>
<P>

<s docid="LA080390-0085" num="56" wdcount="24"> Referring to Kuwait's request for U.S. military intervention, he said: "We don't stand a chance if we don't get aid from our friends" .</s>
</P>
<P>

<s docid="LA080390-0085" num="57" wdcount="30"> Mashat, Baghdad's ambassador to the United States, said in a statement given to reporters in Washington that Iraq hoped to withdraw its forces within a few days or weeks .</s>
</P>
<P>

<s docid="LA080390-0085" num="58" wdcount="19"> "The events currently occurring in Kuwait are an internal affair with which Iraq has no relation," Mashat said .</s>
</P>
<P>

<s docid="LA080390-0085" num="59" wdcount="19"> Meanwhile, the United States asked Iraq to account for the six missing American oil company employees in Kuwait .</s>
</P>
<P>

<s docid="LA080390-0085" num="60" wdcount="24"> Times staff writers Maura Reynolds, Michael Ross and Don Shannon, in Washington, and Jim Mann, in Ulan Bator, Mongolia, contributed to this story .</s>
</P>
<P>

<s docid="LA080390-0085" num="61" wdcount="3"> More on Invasion</s>
</P>
<P>

<s docid="LA080390-0085" num="62" wdcount="14"> U.S. FORCES SHIFTED -- U.S. warships and planes deploy quickly to the troubled area.</s>

<s docid="LA080390-0085" num="63" wdcount="6"> But American options are limited. A10</s>
</P>
<P>

<s docid="LA080390-0085" num="64" wdcount="24"> NO MAJOR IMPACT -- The broad embargo that Bush imposed on Iraq is not expected to have a major impact on its economy. A11</s>
</P>
<P>

<s docid="LA080390-0085" num="65" wdcount="17"> AN ARAB DILEMMA -- Arab ministers, in disarray, cannot agree on a response to the crisis. A12</s>
</P>
<P>

<s docid="LA080390-0085" num="66" wdcount="18"> MARKET POUNDED -- The stock market was rocked by Iraq's invasion of Kuwait; the Dow slid 34.66. D1</s>
</P>
</TEXT>
<SUBJECT>
<P>

<s docid="LA080390-0085" num="67" wdcount="77"> IRAQ -- FOREIGN RELATIONS -- KUWAIT; MILITARY CONFRONTATIONS; UNITED STATES -- TRADE -- IRAQ; OIL -- IRAQ; UNITED STATES -- FOREIGN RELATIONS -- IRAQ; EMBARGOES; UNITED STATES -- FOREIGN ASSETS -- IRAQ; UNITED STATES -- FOREIGN ASSETS -- KUWAIT; IMPOUNDMENT; PERSIAN GULF; UNITED STATES -- ARMED FORCES; MILITARY MANEUVERS; UNITED STATES -- FOREIGN RELATIONS -- KUWAIT; AMERICANS -- KUWAIT; MISSING PERSONS; THATCHER, MARGARET; ENGLAND -- FOREIGN RELATIONS -- KUWAIT; ENGLAND -- FOREIGN RELATIONS -- IRAQ; ECONOMIC SANCTIONS</s>
</P>
</SUBJECT>
</DOC>
