<DOC>
<DOCNO>

<s docid="SJMN91-06164210" num="1" wdcount="1"> SJMN91-06164210</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06164210" num="2" wdcount="1"> 06164210</s>
</ACCESS>
<CAPTION>

<s docid="SJMN91-06164210" num="3" wdcount="21"> Photo, diagram; PHOTO: Associated Press; U.S. troops on guard at Clark Air Base as huge plume rises from Mount Pinatubo eruption.</s>

<s docid="SJMN91-06164210" num="4" wdcount="6"> (Color); DIAGRAM: Jeff Fulaski--Knight0Ridder News Service.</s>

<s docid="SJMN91-06164210" num="5" wdcount="5"> How volcanoes are formed .</s>
</CAPTION>
<DESCRIPT>

<s docid="SJMN91-06164210" num="6" wdcount="2"> VOLCANO; PHILIPPINES</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06164210" num="7" wdcount="17"> Mount Pinatubo erupted with six thundering explosions today, shooting a giant plume of ash 15 miles high.</s>

<s docid="SJMN91-06164210" num="8" wdcount="15"> Molten rock and hot gas poured from the volcano, and nearby residents fled in panic.</s>

<s docid="SJMN91-06164210" num="9" wdcount="6"> A Filipino serving with the U.S.</s>

<s docid="SJMN91-06164210" num="10" wdcount="29"> Navy became the first reported fatality related to the eruption when his car collided with a bus on an ash-slicked road north of the Subic Bay naval base .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06164210" num="11" wdcount="1"> Front</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06164210" num="12" wdcount="15"> THERE WAS PANIC EVERYWHERE VOLCANO ON A RAMPAGE ASH FILLS THE SKY; LAVA, GAS GUSH</s>
</HEADLINE>
<TEXT>

<s docid="SJMN91-06164210" num="13" wdcount="20"> Residents of nearby Angeles panicked when a huge, gray-greenish mushroom cloud burst from the volcano and turned day to night.</s>

<s docid="SJMN91-06164210" num="14" wdcount="6"> Thousands of fleeing people packed roads.</s>

<s docid="SJMN91-06164210" num="15" wdcount="16"> "Stones as big as my head were falling down from the mountains," said Rolly Soria, 18.</s>

<s docid="SJMN91-06164210" num="16" wdcount="7"> "There was panic everywhere," said Manuel Romualdo.</s>

<s docid="SJMN91-06164210" num="17" wdcount="3"> "Children were crying.</s>

<s docid="SJMN91-06164210" num="18" wdcount="31"> We had to grab whatever we could."; Scientists warned of more, possibly larger eruptions from the 4,795-foot volcano, which was dormant for six centuries until it began spewing steam in April.</s>

<s docid="SJMN91-06164210" num="19" wdcount="18"> "This could be only the beginning," said Raymundo Punongbayan, director of the Philippine Institute of Vulcanology and Seismology.</s>

<s docid="SJMN91-06164210" num="20" wdcount="20"> Angeles, a city of 300,000, is adjacent to Clark Air Base, but authorities had not ordered a general evacuation there.</s>

<s docid="SJMN91-06164210" num="21" wdcount="14"> Hundreds of Americans fled Clark, home to 15,000 American military personnel and their families.</s>

<s docid="SJMN91-06164210" num="22" wdcount="9"> Most of the base's residents had been evacuated Monday.</s>

<s docid="SJMN91-06164210" num="23" wdcount="10"> The base did not appear immediately threatened by volcanic flow.</s>

<s docid="SJMN91-06164210" num="24" wdcount="19"> Seismologists said searing gas, ash and molten rock raced at great speed down the mountain's western and northern slopes.</s>

<s docid="SJMN91-06164210" num="25" wdcount="28"> They said most of the debris flowed into the Marella, Maraunot and O'Donnell rivers and that there had been no reports that property or homes had been damaged.</s>

<s docid="SJMN91-06164210" num="26" wdcount="18"> About 3,000 Aeta tribesman, descendants of the original inhabitants of the Philippines, fled the slopes of Mount Pinatubo.</s>

<s docid="SJMN91-06164210" num="27" wdcount="31"> At a refugee center in Olongapo, 35 miles southwest of the volcano, survivors told of the sky growing dark, then of hearing a tremendous explosion followed by a rain of ash.</s>

<s docid="SJMN91-06164210" num="28" wdcount="26"> They said they scampered for safety with their belongings and livestock over roads slippery with ashfall, many wearing cardboard boxes to protect themselves from the ash.</s>

<s docid="SJMN91-06164210" num="29" wdcount="11"> "They were stunned by the eruption," television reporter Bert Basa said.</s>

<s docid="SJMN91-06164210" num="30" wdcount="34"> "Their faces turned ashen, and it looked like their hair was standing on end."; Ash was so thick in the air that at noon, motorists were driving with their headlights and windshield wipers on.</s>

<s docid="SJMN91-06164210" num="31" wdcount="32"> A photographer who circled the volcano in an airplane said an aerial gunnery range at Clark was covered with ash, as were mountains in the Zambales range, normally lush, green tropical peaks.</s>

<s docid="SJMN91-06164210" num="32" wdcount="17"> Today's first eruption began at 8:40 a.m. with a tremendous blast that sent forth a mushroom cloud.</s>

<s docid="SJMN91-06164210" num="33" wdcount="19"> It was followed by a second explosion a few minutes later and a third, smaller blast at 11:49 a.m.</s>

<s docid="SJMN91-06164210" num="34" wdcount="24"> The huge plume could be seen in Manila, 60 miles to the south, and reporters at the scene said it blocked out the sun.</s>

<s docid="SJMN91-06164210" num="35" wdcount="9"> The cloud drifted westward into the South China Sea.</s>

<s docid="SJMN91-06164210" num="36" wdcount="9"> Two more thundering explosions rocked Mount Pinatubo late today.</s>

<s docid="SJMN91-06164210" num="37" wdcount="17"> The Philippine Institute of Vulcanology and Seismology said the explosions occurred at 10:52 p.m. and 11:05 p.m.</s>

<s docid="SJMN91-06164210" num="38" wdcount="15"> The second explosion sent a plume of ash and steam 80,000 feet into the sky.</s>

<s docid="SJMN91-06164210" num="39" wdcount="8"> Shortly after midnight, a sixth explosion was reported.</s>

<s docid="SJMN91-06164210" num="40" wdcount="17"> Seismologists said the volcano had plenty of built-up magma and even more severe eruptions could come later.</s>

<s docid="SJMN91-06164210" num="41" wdcount="16"> "The crisis has not ended yet," said Punongbayan, of the Philippine Institute of Vulcanology and Seismology.</s>

<s docid="SJMN91-06164210" num="42" wdcount="22"> "We have signs that the volcano is preparing for another one."; Punongbayan warned people within a 15-mile radius of Pinatubo to flee.</s>

<s docid="SJMN91-06164210" num="43" wdcount="27"> "The smoke is very thick like a dark mushroom in the sky," television reporter Gus Abelgas said in a broadcast from Botolan, near the volcano's western slopes.</s>

<s docid="SJMN91-06164210" num="44" wdcount="11"> He said strong tremors preceded the nighttime eruptions and continued afterward.</s>

<s docid="SJMN91-06164210" num="45" wdcount="17"> President Corazon Aquino visited refugee centers near Angeles briefly before returning to Manila for independence day celebrations.</s>

<s docid="SJMN91-06164210" num="46" wdcount="27"> The Americans who fled Clark with a few belongings Monday moved in with sailors and their families at Subic Bay naval base, 50 miles to the southwest.</s>

<s docid="SJMN91-06164210" num="47" wdcount="9"> Clark is one of the biggest U.S. bases overseas.</s>

<s docid="SJMN91-06164210" num="48" wdcount="24"> Punongbayan said Tuesday that the site was in the path of the volcanic flow from Mount Pinatubo during its last major eruption, in 1380.</s>

<s docid="SJMN91-06164210" num="49" wdcount="27"> About 19,000 Filipinos earlier had been evacuated from three provinces near the volcano's slopes and were housed in 25 makeshift evacuation centers outside the projected danger zone.</s>

<s docid="SJMN91-06164210" num="50" wdcount="8"> Officials said more were evacuated after today's eruption.</s>

<s docid="SJMN91-06164210" num="51" wdcount="21"> About 10 people in Moraza, a village on the western slope of the mountain, were refusing to leave, relief officials said.</s>

<s docid="SJMN91-06164210" num="52" wdcount="38"> They told rescuers that they would not leave their livestock and if the animals die, "we will die with them."; On April 2, Pinatubo produced a small hydrothermal explosion caused by underground water meeting hot rocks deep inside.</s>

<s docid="SJMN91-06164210" num="53" wdcount="11"> On June 3, the volcano spewed ash in a mild eruption.</s>

<s docid="SJMN91-06164210" num="54" wdcount="22"> That same day, 4,452-foot Mount Unzen in Japan erupted with an explosion of superheated gas, ashes and rocks that killed 38 people.</s>

<s docid="SJMN91-06164210" num="55" wdcount="11"> Experts say there is apparently no connection between Unzen and Pinatubo.</s>

<s docid="SJMN91-06164210" num="56" wdcount="12"> There are about 21 active and 200 dormant volcanoes in the Philippines.</s>

<s docid="SJMN91-06164210" num="57" wdcount="16"> The last major eruption was the Taal volcano, about 50 miles south of Manila, in 1965.</s>

<s docid="SJMN91-06164210" num="58" wdcount="7"> That explosion killed about 200 people .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06164210" num="59" wdcount="2"> Associated Press</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06164210" num="60" wdcount="1"> USA</s>
</COUNTRY>
<CITY>

<s docid="SJMN91-06164210" num="61" wdcount="2"> Manila, Philippines</s>
</CITY>
<EDITION>

<s docid="SJMN91-06164210" num="62" wdcount="2"> Stock Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06164210" num="63" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06164210" num="64" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06164210" num="65" wdcount="1"> 910612</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06164210" num="66" wdcount="1"> Wednesday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06164210" num="67" wdcount="1"> June</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06164210" num="68" wdcount="1"> 1A</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06164210" num="69" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06164210" num="70" wdcount="1"> WEST</s>
</REGION>
<FEATURE>

<s docid="SJMN91-06164210" num="71" wdcount="2"> DIAGRAM; PHOTO</s>
</FEATURE>
<STATE>

<s docid="SJMN91-06164210" num="72" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06164210" num="73" wdcount="1"> 917</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06164210" num="74" wdcount="5"> Wednesday June 12, 1991 00164210,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06164210" num="75" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06164210" num="76" wdcount="1"> 1</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06164210" num="77" wdcount="2"> ENG FRONT</s>
</LANGUAGE>
</DOC>
