<DOC>
<DOCNO>

<s docid="SJMN91-06167046" num="1" wdcount="1"> SJMN91-06167046</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06167046" num="2" wdcount="1"> 06167046</s>
</ACCESS>
<DESCRIPT>

<s docid="SJMN91-06167046" num="3" wdcount="2"> PHILIPPINES; VOLCANO</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06167046" num="4" wdcount="32"> Mount Pinatubo rumbled today with explosions that hurled ash and gas more than 12 miles high, and a typhoon brought heavy rain that could unleash tons of debris from the jagged slopes.</s>

<s docid="SJMN91-06167046" num="5" wdcount="17"> Seven explosions were recorded from the 4,800-foot tropical volcano today, and scientists said more were expected .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06167046" num="6" wdcount="1"> Front</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06167046" num="7" wdcount="6"> NEW EXPLOSIONS ROCK PHILIPPINES' MOUNT PINATUBO</s>
</HEADLINE>
<MEMO>

<s docid="SJMN91-06167046" num="8" wdcount="9"> The Los Angeles Times contributed to this report .</s>
</MEMO>
<TEXT>

<s docid="SJMN91-06167046" num="9" wdcount="22"> Typhoon Yunya, packing 80 mph winds, slammed into the eastern coast of Luzon island, which includes Mount Pinatubo, early in the day.</s>

<s docid="SJMN91-06167046" num="10" wdcount="25"> But it quickly weakened to a tropical storm with 60 mph winds by the time it was centered about 70 miles east of the volcano.</s>

<s docid="SJMN91-06167046" num="11" wdcount="30"> Still, heavy rains churned up by the typhoon drenched Manila and the provinces near the volcano, raising fears of mudflows that could bury whole towns up to 25 miles away.</s>

<s docid="SJMN91-06167046" num="12" wdcount="35"> Meanwhile, President Corazon Aquino dismissed a British newspaper report that Americans had warned her of possible radioactive contamination if the volcano damages nuclear storage sites at Clark Air Base, abandoned Monday by nearly 15,000 Americans.</s>

<s docid="SJMN91-06167046" num="13" wdcount="45"> The U.S. military began flying home hundreds of the 28,000 Americans who crowded onto Subic Bay Naval Base as a bizarre tropical blizzard of thick volcanic ash caused power failures across the base Friday during a third day of increasingly violent eruptions of Mount Pinatubo.</s>

<s docid="SJMN91-06167046" num="14" wdcount="16"> Showers of 'mud drops'; "It looks like it's snowing outside," said military spokeswoman Capt. Kim Urie.</s>

<s docid="SJMN91-06167046" num="15" wdcount="30"> Headlights and street lamps were turned on at midafternoon as a "dark, black cloud" passed over the giant Navy base and dropped a gritty rain of "mud drops," she said.</s>

<s docid="SJMN91-06167046" num="16" wdcount="30"> At least four people have died, 24 have been hurt and four have been listed as missing since Pinatubo began erupting Sunday, after lying dormant for six centuries, officials said.</s>

<s docid="SJMN91-06167046" num="17" wdcount="8"> About 84,000 people, including Americans, have been evacuated.</s>

<s docid="SJMN91-06167046" num="18" wdcount="11"> Police said 12 people had been arrested for looting at Clark.</s>

<s docid="SJMN91-06167046" num="19" wdcount="29"> Five explosions shook the mountain early today, showering ash over a wide area and providing a spectacular pre-dawn display of nature's fireworks against a backdrop of lightning and rain.</s>

<s docid="SJMN91-06167046" num="20" wdcount="15"> Friday, eight thunderous explosions shot a cloud of ash and steam nearly 19 miles high.</s>

<s docid="SJMN91-06167046" num="21" wdcount="25"> Friday's eruptions hurled ash over Clark, 10 miles east of the volcano, and Subic, 25 miles southwest, where the Clark personnel had been temporarily housed.</s>

<s docid="SJMN91-06167046" num="22" wdcount="9"> Gray ash also fell in Manila, 60 miles south.</s>

<s docid="SJMN91-06167046" num="23" wdcount="27"> At Subic, base spokesman Robert Coble said generators had to be shut down from time to time to clean out volcanic ash, plunging the base into darkness.</s>

<s docid="SJMN91-06167046" num="24" wdcount="16"> River temperatures rising; Temperatures in local rivers were rising because of the volcanic debris, officials said.</s>

<s docid="SJMN91-06167046" num="25" wdcount="28"> After sunset, the volcano spewed two streams of orange, glowing material from its crater in what scientists thought was the first appearance of lava during the weeklong eruptions.</s>

<s docid="SJMN91-06167046" num="26" wdcount="31"> Raymundo Punongbayan, director of the Philippine Institute of Vulcanology and Seismology, said Friday's blasts were part of a single eruption, the largest since Mount Pinatubo awoke Sunday from its 600-year slumber.</s>

<s docid="SJMN91-06167046" num="27" wdcount="35"> A British newspaper, the Guardian, reported Thursday that the Americans declared a nuclear alert at Clark late Wednesday and informed governments in Manila and Hong Kong that "a nuclear accident in the region was possible".</s>

<s docid="SJMN91-06167046" num="28" wdcount="27"> But Aquino told reporters the story was "baseless and purely fabricated."; The United States refuses to confirm or deny that it stores nuclear weapons in the Philippines.</s>

<s docid="SJMN91-06167046" num="29" wdcount="26"> Foreign Secretary Raul Manglapus also said the eruption should have no effect on talks on the future of Clark and Subic, where leases expire Sept. 16.</s>

<s docid="SJMN91-06167046" num="30" wdcount="13"> The talks are deadlocked over compensation and the duration of a new agreement.</s>

<s docid="SJMN91-06167046" num="31" wdcount="18"> Punongbayan said Mount Pinatubo could remain active for years if it follows the pattern of similar Philippine volcanoes.</s>

<s docid="SJMN91-06167046" num="32" wdcount="6"> That would leave Clark unusable .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06167046" num="33" wdcount="2"> Associated Press</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06167046" num="34" wdcount="1"> USA</s>
</COUNTRY>
<CITY>

<s docid="SJMN91-06167046" num="35" wdcount="2"> MANILA, Philippines</s>
</CITY>
<EDITION>

<s docid="SJMN91-06167046" num="36" wdcount="2"> Morning Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06167046" num="37" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06167046" num="38" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06167046" num="39" wdcount="1"> 910615</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06167046" num="40" wdcount="1"> Saturday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06167046" num="41" wdcount="1"> June</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06167046" num="42" wdcount="1"> 4A</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06167046" num="43" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06167046" num="44" wdcount="1"> WEST</s>
</REGION>
<STATE>

<s docid="SJMN91-06167046" num="45" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06167046" num="46" wdcount="1"> 615</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06167046" num="47" wdcount="5"> Saturday June 15, 1991 00167046,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06167046" num="48" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06167046" num="49" wdcount="1"> 1</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06167046" num="50" wdcount="1"> ENG</s>
</LANGUAGE>
</DOC>
