<DOC>
<DOCNO>

<s docid="SJMN91-06165048" num="1" wdcount="1"> SJMN91-06165048</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06165048" num="2" wdcount="1"> 06165048</s>
</ACCESS>
<CAPTION>

<s docid="SJMN91-06165048" num="3" wdcount="26"> Photo, maps (2); PHOTO: Associated Press; U.S. soldiers at Clark Air Base in the Philippines eye a cloud of volcanic ash from Mount Pinatubo on Wednesday.</s>

<s docid="SJMN91-06165048" num="4" wdcount="15"> Most of the 16,000 Americans who live or work at the base had been evacuated.</s>

<s docid="SJMN91-06165048" num="5" wdcount="17"> MAP: Knight-Ridder News Service; World's deadliest volcano eruptions; MAP: Alan Baseden -- Mercury News; Philippines, Eruption site</s>
</CAPTION>
<DESCRIPT>

<s docid="SJMN91-06165048" num="6" wdcount="3"> VOLCANO; PHILIPPINES; DISASTER</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06165048" num="7" wdcount="37"> Three major new eruptions rocked Mount Pinatubo late Wednesday night and early today, forcing another emergency evacuation of Clark Air Base and increasing fears of even more violent explosions from the long-dormant volcano in the days ahead.</s>

<s docid="SJMN91-06165048" num="8" wdcount="18"> Mudslides also threatened after fierce thunderstorms and lightning Wednesday illuminated afternoon skies eerily darkened by giant volcanic clouds.</s>

<s docid="SJMN91-06165048" num="9" wdcount="24"> As much as two inches of coarse gray ash and fist-sized pieces of pumice fell along a 50-mile stretch southwest of the volcano .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06165048" num="10" wdcount="1"> Front</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06165048" num="11" wdcount="11"> VOLCANO'S FURY FORCES MORE TO FLEE FIST-SIZED ROCKS RAIN IN PHILIPPINES</s>
</HEADLINE>
<MEMO>

<s docid="SJMN91-06165048" num="12" wdcount="8"> Mercury News wire services contributed to this report.</s>

<s docid="SJMN91-06165048" num="13" wdcount="11"> See also related story on page 22A of this section .</s>
</MEMO>
<TEXT>

<s docid="SJMN91-06165048" num="14" wdcount="29"> An eruption this morning caused an earthquake so strong it "sent seismograph needles off the chart," and registered 60 miles south in Manila, said Jessie Daligdig, a government geologist.</s>

<s docid="SJMN91-06165048" num="15" wdcount="24"> Villagers tied wet kerchiefs on their faces and used rakes, shovels and pieces of wood to push the blanket of snow-like ash from roads.</s>

<s docid="SJMN91-06165048" num="16" wdcount="23"> At times, winds whipped the grit into the air, forcing cars to use windshield wipers and headlights in blizzard-like conditions through the afternoon.</s>

<s docid="SJMN91-06165048" num="17" wdcount="14"> Two people have been reported killed so far, a Filipino serving in the U.S.</s>

<s docid="SJMN91-06165048" num="18" wdcount="32"> Navy who died in a traffic accident on an ash-slick road and a Filipino boy reported to have died after inhaling sulfuric fumes that began to seep from the volcano last weekend.</s>

<s docid="SJMN91-06165048" num="19" wdcount="51"> The initial explosions on Mount Pinatubo at 8:51 a.m. Wednesday sent a 10-mile-high mushroom cloud of swirling ash and rock fragments into the skies over Clark Air Base, forcing the Air Force to evacuate hundreds of American volunteers who had stayed behind to guard it and to tend sensitive communications equipment.</s>

<s docid="SJMN91-06165048" num="20" wdcount="33"> Most of the 16,000 Americans who live and work at Clark were evacuated Monday, when scientists said it was clear that the volcano, dormant for more than six centuries, was returning to life.</s>

<s docid="SJMN91-06165048" num="21" wdcount="33"> U.S. officials have refused to say whether nuclear weapons are stored at Clark, but they denied news reports suggesting a radiation danger if weapons depots on the base were hit by molten rock.</s>

<s docid="SJMN91-06165048" num="22" wdcount="22"> Many of the villages in the vicinity were holding Independence Day celebrations when heavy gray clouds first began raining ash Wednesday morning.</s>

<s docid="SJMN91-06165048" num="23" wdcount="31"> The mayor in San Marcelino, 17 miles southwest of the volcano, was giving a speech to several thousand people when dark clouds suddenly blotted the sun and turned day to night.</s>

<s docid="SJMN91-06165048" num="24" wdcount="15"> Calixto Macalma Jr., a police intelligence officer, said people panicked as it began "raining sand".</s>

<s docid="SJMN91-06165048" num="25" wdcount="12"> Church bells pealed in alarm, sirens wailed and many ran for shelter.</s>

<s docid="SJMN91-06165048" num="26" wdcount="23"> Philippine civil defense officials said that they had evacuated 19,369 people from villages within a 12-mile radius of the volcano by late Wednesday.</s>

<s docid="SJMN91-06165048" num="27" wdcount="20"> Along the roads, some people wore cardboard boxes on their heads for protection; some rode their water buffaloes to safety.</s>

<s docid="SJMN91-06165048" num="28" wdcount="19"> At least 330 villagers, who had ignored earlier warnings to flee Aglao hamlet, finally abandoned their homes Wednesday afternoon.</s>

<s docid="SJMN91-06165048" num="29" wdcount="15"> "There were big stones, like this," said one woman who escaped, holding out her fists.</s>

<s docid="SJMN91-06165048" num="30" wdcount="32"> "We are very scared."; Thousands of residents of Angeles City, east of the volcano, initially fled in panic from the booming morning blasts and greenish-gray mushroom cloud that towered over the area.</s>

<s docid="SJMN91-06165048" num="31" wdcount="17"> Passenger jeeps sped through the streets, refusing to stop for riders as the drivers drove for cover.</s>

<s docid="SJMN91-06165048" num="32" wdcount="8"> Most residents later returned to the sprawling city.</s>

<s docid="SJMN91-06165048" num="33" wdcount="19"> But officials issued no general evacuation order for Angeles, even though the city is next to Clark Air Base.</s>

<s docid="SJMN91-06165048" num="34" wdcount="41"> U.S. geologists advising the Philippine government said most of Angeles was not at risk, apparently basing their assessment on earth samples indicating that earlier eruptions had reached the area on which Clark now stands but had spared what is now Angeles.</s>

<s docid="SJMN91-06165048" num="35" wdcount="24"> President Corazon Aquino helicoptered to refugee centers near Angeles briefly before returning to Manila for an Independence Day rally and parade at Luneta Park.</s>

<s docid="SJMN91-06165048" num="36" wdcount="10"> She authorized the release of $1.42 million for relief efforts.</s>

<s docid="SJMN91-06165048" num="37" wdcount="41"> Raymundo Punongbayan, director of the Philippine Institute of Volcanology and Seismology, said scientists could not estimate how much magma was still pent up inside Mount Pinatubo, but said more eruptions at least as violent are expected within the next three days.</s>

<s docid="SJMN91-06165048" num="38" wdcount="8"> "All we can do is wait," he said.</s>

<s docid="SJMN91-06165048" num="39" wdcount="6"> "The crisis is not over" .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06165048" num="40" wdcount="3"> Los Angeles Times</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06165048" num="41" wdcount="1"> USA</s>
</COUNTRY>
<CITY>

<s docid="SJMN91-06165048" num="42" wdcount="3"> San Marcelino, Philippines</s>
</CITY>
<EDITION>

<s docid="SJMN91-06165048" num="43" wdcount="2"> Morning Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06165048" num="44" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06165048" num="45" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06165048" num="46" wdcount="1"> 910613</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06165048" num="47" wdcount="1"> Thursday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06165048" num="48" wdcount="1"> June</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06165048" num="49" wdcount="1"> 1A</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06165048" num="50" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06165048" num="51" wdcount="1"> WEST</s>
</REGION>
<FEATURE>

<s docid="SJMN91-06165048" num="52" wdcount="2"> PHOTO; MAP</s>
</FEATURE>
<STATE>

<s docid="SJMN91-06165048" num="53" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06165048" num="54" wdcount="1"> 764</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06165048" num="55" wdcount="5"> Thursday June 13, 1991 00165048,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06165048" num="56" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06165048" num="57" wdcount="1"> 1</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06165048" num="58" wdcount="2"> ENG FRONT</s>
</LANGUAGE>
</DOC>
