<DOC>
<DOCNO>

<s docid="SJMN91-06163112" num="1" wdcount="1"> SJMN91-06163112</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06163112" num="2" wdcount="1"> 06163112</s>
</ACCESS>
<CAPTION>

<s docid="SJMN91-06163112" num="3" wdcount="19"> Photo; PHOTO: Associated Press; OUT OF HARM'S WAY -- Two mothers and their children await aid after evacuation Monday.</s>

<s docid="SJMN91-06163112" num="4" wdcount="32"> The tribal refugees from the impending disaster were among thousands of Filipinos living near the volcano, as well as most Americans at Clark Air Base, who have been forced to flee .</s>
</CAPTION>
<DESCRIPT>

<s docid="SJMN91-06163112" num="5" wdcount="3"> VOLCANO; FORECAST; PHILIPPINES</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06163112" num="6" wdcount="39"> Mount Pinatubo, the Philippine volcano that erupted Saturday after six centuries of quiet, is likely to explode in the next few days or weeks with force comparable to the Mount St. Helens explosion, a U.S. government scientist said Monday.</s>

<s docid="SJMN91-06163112" num="7" wdcount="19"> "I think we could see a major explosive eruption any time," said Peter Lipman, a volcanologist at the U.S.</s>

<s docid="SJMN91-06163112" num="8" wdcount="6"> Geological Survey office in Menlo Park.</s>

<s docid="SJMN91-06163112" num="9" wdcount="25"> Lipman is in daily contact with five USGS scientists in the Philippines who have been studying the volcano since April, when it first stirred .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06163112" num="10" wdcount="1"> Front</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06163112" num="11" wdcount="7"> HUGE ERUPTION LIKELY IN PHILIPPINES 'ANY TIME'</s>
</HEADLINE>
<TEXT>

<s docid="SJMN91-06163112" num="12" wdcount="29"> A huge cloud of ash-laden steam rose up to 11,500 feet above the volcano today, spreading ash over a six-mile radius, the Philippine Institute of Vulcanology and Seismology said.</s>

<s docid="SJMN91-06163112" num="13" wdcount="21"> If it does erupt, the deadly hot ash produced by the volcano could sweep across adjoining Clark Air Base, he said.</s>

<s docid="SJMN91-06163112" num="14" wdcount="22"> Also in peril are the 350,000 residents of Angeles City, where the air base is located, about 50 miles north of Manila.</s>

<s docid="SJMN91-06163112" num="15" wdcount="24"> Even if the volcano does not erupt, the threat of eruption is likely to keep the base closed for weeks at least, Lipman said.</s>

<s docid="SJMN91-06163112" num="16" wdcount="24"> Scientists doubt it's more than coincidence that the eruption is occurring at the same time as the Mount Unzen volcano in Japan, he said.</s>

<s docid="SJMN91-06163112" num="17" wdcount="26"> The five USGS scientists are among the few remaining people at Clark Air Base, which was evacuated along with thousands of Filipinos living near the volcano.</s>

<s docid="SJMN91-06163112" num="18" wdcount="36"> The researchers, along with 10 Filipino scientists and their equipment, today moved to a bunker on the east edge of the air base, 12 miles from the volcano, where they should be safe from ash avalanches.</s>

<s docid="SJMN91-06163112" num="19" wdcount="24"> Mount Pinatubo is typical of hundreds of volcanoes that make up the "Ring of Fire" on the Pacific coasts of Asia and the Americas.</s>

<s docid="SJMN91-06163112" num="20" wdcount="71"> (These volcanoes -- including Mount Lassen in Shasta County, and Mount Rainier and Mount St. Helens in Washington, all in the Cascade Range -- arise where one of the earth's immense crust plates is slowly diving beneath another.); Pinatubo's last eruption, 600 years ago, is thought to have yielded at least as much molten rock -- half a cubic kilometer -- as Mount St. Helens did when it erupted in 1980.</s>

<s docid="SJMN91-06163112" num="21" wdcount="23"> Until volcanologists' attention was drawn to it by a cluster of earthquakes beneath the volcano this spring, it had not been studied well.</s>

<s docid="SJMN91-06163112" num="22" wdcount="24"> Other recent volcanoes that erupted on the same scale were El Chichon in Mexico in 1983 and Nevado del Ruiz in Colombia in 1985.</s>

<s docid="SJMN91-06163112" num="23" wdcount="42"> If it does have a massive eruption, Pinatubo's primary means of causing death and destruction would be hellish avalanches of hot ash -- 1,000 degrees or more, flowing and billowing at up to 100 mph, engulfing and searing all in their path.</s>

<s docid="SJMN91-06163112" num="24" wdcount="22"> "In the worst case, a really big eruption, all of Clark Air Force Base could be covered" with glowing ash, Lipman said.</s>

<s docid="SJMN91-06163112" num="25" wdcount="14"> Just being caught in a cloud of ash blowing off the avalanche is fatal.</s>

<s docid="SJMN91-06163112" num="26" wdcount="10"> That is what killed 38 people in Japan last week.</s>

<s docid="SJMN91-06163112" num="27" wdcount="17"> Such ash also would wreak havoc with the engines of planes at the air base, Lipman said.</s>

<s docid="SJMN91-06163112" num="28" wdcount="26"> Planes flying through clouds of volcanic ash -- indistinguishable on radar from rain clouds -- run the risk of having their engines stalled by the grit.</s>

<s docid="SJMN91-06163112" num="29" wdcount="11"> So far, the winds have blown ash away from the base.</s>

<s docid="SJMN91-06163112" num="30" wdcount="20"> But winds of the summer monsoon weather pattern, expected to begin any day, would send ash directly toward the base.</s>

<s docid="SJMN91-06163112" num="31" wdcount="31"> The volcano's activity -- measured by seismometers detecting slight earthquakes in its molten rock plumbing system -- is increasing in a way that suggests a large eruption is imminent, Lipman said.</s>

<s docid="SJMN91-06163112" num="32" wdcount="18"> The scientists also are monitoring tiltmeters on the volcano's slopes, to watch it swell as magma builds inside.</s>

<s docid="SJMN91-06163112" num="33" wdcount="12"> On clear days they fly above the crater to measure sulfur emissions.</s>

<s docid="SJMN91-06163112" num="34" wdcount="16"> Their predictions might be a false alarm -- the volcano may have done its worst already.</s>

<s docid="SJMN91-06163112" num="35" wdcount="26"> But it would take several weeks of declining quakes and sulfur emissions before scientists would be reasonably confident that the military could return to the base.</s>

<s docid="SJMN91-06163112" num="36" wdcount="21"> Volcanologists know of no reason the volcano's activity could be linked to the volcano in Japan, which is of comparable size.</s>

<s docid="SJMN91-06163112" num="37" wdcount="15"> "No reputable scientist I know of" is drawing a connection between the two, Lipman said.</s>

<s docid="SJMN91-06163112" num="38" wdcount="11"> More than 500 volcanoes have erupted in historical time, he noted.</s>

<s docid="SJMN91-06163112" num="39" wdcount="9"> "Two out of 500 is no big deal" .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06163112" num="40" wdcount="6"> DAVID ANSLEY, Mercury News Staff Writer</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06163112" num="41" wdcount="1"> USA</s>
</COUNTRY>
<EDITION>

<s docid="SJMN91-06163112" num="42" wdcount="2"> Stock Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06163112" num="43" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06163112" num="44" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06163112" num="45" wdcount="1"> 910611</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06163112" num="46" wdcount="1"> Tuesday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06163112" num="47" wdcount="1"> June</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06163112" num="48" wdcount="1"> 6A</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06163112" num="49" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06163112" num="50" wdcount="1"> WEST</s>
</REGION>
<FEATURE>

<s docid="SJMN91-06163112" num="51" wdcount="1"> PHOTO</s>
</FEATURE>
<STATE>

<s docid="SJMN91-06163112" num="52" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06163112" num="53" wdcount="1"> 773</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06163112" num="54" wdcount="5"> Tuesday June 11, 1991 00163112,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06163112" num="55" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06163112" num="56" wdcount="1"> 1</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06163112" num="57" wdcount="1"> ENG</s>
</LANGUAGE>
</DOC>
