<DOC>
<DOCNO>

<s docid="SJMN91-06162032" num="1" wdcount="1"> SJMN91-06162032</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06162032" num="2" wdcount="1"> 06162032</s>
</ACCESS>
<CAPTION>

<s docid="SJMN91-06162032" num="3" wdcount="33"> Photo, map; PHOTO: Associated Press; Carloads of American service members and their families roll out of Clark Air Base in the Philippines today (Color) (Ran only in the Street edition); MAP: Associated Press.</s>

<s docid="SJMN91-06162032" num="4" wdcount="3"> Mount Pinatubo. (Color)</s>
</CAPTION>
<DESCRIPT>

<s docid="SJMN91-06162032" num="5" wdcount="2"> VOLCANO; PHILIPPINES</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06162032" num="6" wdcount="33"> Thousands of Americans piled into cars and buses with dogs, cats and duffel bags and left Clark Air Base today after scientists warned that the eruption of a nearby volcano could turn catastrophic.</s>

<s docid="SJMN91-06162032" num="7" wdcount="38"> The decision to evacuate one of the largest overseas U.S. military bases was made early today after searing gases, ash and rock shot out of 4,795-foot Mount Pinatubo on Sunday at speeds of up to 60 mph .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06162032" num="8" wdcount="1"> Front</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06162032" num="9" wdcount="8"> ANOTHER VOLCANO ERUPTS AMERICANS FLEE BASE IN PHILIPPINES</s>
</HEADLINE>
<TEXT>

<s docid="SJMN91-06162032" num="10" wdcount="20"> The volcano, about 10 miles west of the air base, came to life last week after six centuries of dormancy.</s>

<s docid="SJMN91-06162032" num="11" wdcount="16"> No casualties have been reported, but experts are concerned that a major eruption could occur soon.</s>

<s docid="SJMN91-06162032" num="12" wdcount="27"> Gases, ash and molten rock continued to pour out of the mountain today, enshrouding it in thick, gray clouds of ash and steam that rose 12,000 feet.</s>

<s docid="SJMN91-06162032" num="13" wdcount="26"> The Philippine Institute of Vulcanology and Seismology said it detected rhythmic ground movements today that indicated molten material was rising to the surface of the craters.</s>

<s docid="SJMN91-06162032" num="14" wdcount="37"> Institute Director Raymundo Punongbayan said Mount Pinatubo was in the "early eruptive stage" and "after that we will have bigger ones."; He said most of the ash and molten rocks had been flowing westward away from Clark.</s>

<s docid="SJMN91-06162032" num="15" wdcount="27"> But he said geological studies showed that in the previous eruption 600 years ago, the main flow cut across what is now the western portion of Clark.</s>

<s docid="SJMN91-06162032" num="16" wdcount="29"> Rains fell across the area Sunday night, and officials warned residents in the lush, green lowlands west of the mountain to move to higher ground to escape mud flows.</s>

<s docid="SJMN91-06162032" num="17" wdcount="4"> Air Force spokesman Lt.</s>

<s docid="SJMN91-06162032" num="18" wdcount="18"> Col. Ron Rand announced the evacuation in a 5 a.m. broadcast over the U.S. military's Far East Network.</s>

<s docid="SJMN91-06162032" num="19" wdcount="33"> An hour later, the first vehicles began rolling out of Clark for the U.S.-run Subic Bay naval base, where the 14,500 troops, dependents and civilian employees will be housed until the danger passes.</s>

<s docid="SJMN91-06162032" num="20" wdcount="9"> Another 1,500 troops remained at Clark to provide security.</s>

<s docid="SJMN91-06162032" num="21" wdcount="15"> The Clark command center operated with a skeletal crew, but the base's operations were suspended.</s>

<s docid="SJMN91-06162032" num="22" wdcount="18"> The base is a major terminal for the worldwide network of flights operated by the Military Airlift Command.</s>

<s docid="SJMN91-06162032" num="23" wdcount="16"> The miles-long convoy jammed the two-lane roads leading to Subic, about 50 miles southwest of Clark.</s>

<s docid="SJMN91-06162032" num="24" wdcount="18"> U.S. Marines patrolled the highways, which pass through areas where Communist guerrillas operate, and U.S. helicopters hovered overhead.</s>

<s docid="SJMN91-06162032" num="25" wdcount="12"> By late afternoon, U.S. officials said all the evacuees had reached Subic.</s>

<s docid="SJMN91-06162032" num="26" wdcount="27"> "If it's going to blow, I hope it does it fast so I can go home before the cockroaches take my house," said Staff Sgt. Mike Huffman.</s>

<s docid="SJMN91-06162032" num="27" wdcount="19"> Clark Air Base is in Angeles, a city of more than 300,000 people about 50 miles north of Manila.</s>

<s docid="SJMN91-06162032" num="28" wdcount="15"> In Angeles, residents reported no ash fell today but said the air smelled of sulfur.</s>

<s docid="SJMN91-06162032" num="29" wdcount="38"> In southern Japan today, Mount Unzen continued to shake and spew hot ash and rocks, and heavy rain was falling on the tons of ash and rock it disgorged over the past week, raising fears of deadly mudslides.</s>

<s docid="SJMN91-06162032" num="30" wdcount="29"> Areas around the 4,452-foot volcano covered by evacuation warnings were expanded to protect people against possible slides of volcanic debris that could be triggered by the rain, police said.</s>

<s docid="SJMN91-06162032" num="31" wdcount="28"> An explosion of superheated gas, ashes and rocks from the mountain one week ago claimed 38 lives, and a larger flow over the weekend razed dozens more homes.</s>

<s docid="SJMN91-06162032" num="32" wdcount="23"> In all, about 9,800 people have been evacuated from communities at the foot of the mountain, said police in Nagasaki, 30 miles away.</s>

<s docid="SJMN91-06162032" num="33" wdcount="32"> Mount Unzen and Mount Pinatubo belong to the "Ring of Fire" that circles the Pacific where shifting plates of the Earth's crust push against each other, triggering periodic volcanic eruptions and earthquakes.</s>

<s docid="SJMN91-06162032" num="34" wdcount="20"> In the Philippines, officials have evacuated more than 12,000 people in three provinces since Mount Pinatubo began erupting last week.</s>

<s docid="SJMN91-06162032" num="35" wdcount="14"> About 3,100 of them are primitive Aeta tribes people who lived on Pinatubo's slopes.</s>

<s docid="SJMN91-06162032" num="36" wdcount="13"> Many of them walked or traveled by ox cart to flee the volcano.</s>

<s docid="SJMN91-06162032" num="37" wdcount="27"> But reporters found that some evacuees are returning to their homes each morning to tend to livestock and crops and heading back to evacuation centers at sundown.</s>

<s docid="SJMN91-06162032" num="38" wdcount="22"> Punongbayan said he flew to the area and warned people there would be no time to escape once a major eruption begins.</s>

<s docid="SJMN91-06162032" num="39" wdcount="32"> There was no indication how long the Americans evacuated from Clark would stay at Subic, but they were ordered to take along important papers and food, water and clothing for three days.</s>

<s docid="SJMN91-06162032" num="40" wdcount="30"> Subic base spokesman Bob Coble said families at the naval installation had been asked to take in evacuees and that others would double up in bachelor officer and enlisted quarters.</s>

<s docid="SJMN91-06162032" num="41" wdcount="18"> Mount Pinatubo, which last had a major eruption in 1380, began to show signs of activity in April.</s>

<s docid="SJMN91-06162032" num="42" wdcount="10"> Last week, it belched small amounts of steam and ash.</s>

<s docid="SJMN91-06162032" num="43" wdcount="12"> There are about 21 active and 200 dormant volcanoes in the Philippines.</s>

<s docid="SJMN91-06162032" num="44" wdcount="18"> The last major eruption occurred in 1965, when the Taal volcano, about 50 miles south of Manila, exploded.</s>

<s docid="SJMN91-06162032" num="45" wdcount="6"> About 200 people were killed .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06162032" num="46" wdcount="2"> Associated Press</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06162032" num="47" wdcount="1"> USA</s>
</COUNTRY>
<CITY>

<s docid="SJMN91-06162032" num="48" wdcount="2"> Manila, Philippines</s>
</CITY>
<EDITION>

<s docid="SJMN91-06162032" num="49" wdcount="2"> Stock Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06162032" num="50" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06162032" num="51" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06162032" num="52" wdcount="1"> 910610</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06162032" num="53" wdcount="1"> Monday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06162032" num="54" wdcount="1"> June</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06162032" num="55" wdcount="1"> 1A</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06162032" num="56" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06162032" num="57" wdcount="1"> WEST</s>
</REGION>
<FEATURE>

<s docid="SJMN91-06162032" num="58" wdcount="2"> PHOTO; MAP</s>
</FEATURE>
<STATE>

<s docid="SJMN91-06162032" num="59" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06162032" num="60" wdcount="1"> 868</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06162032" num="61" wdcount="5"> Monday June 10, 1991 00162032,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06162032" num="62" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06162032" num="63" wdcount="1"> 1</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06162032" num="64" wdcount="2"> ENG FRONT</s>
</LANGUAGE>
</DOC>
