<DOC>
<DOCNO>

<s docid="AP890715-0076" num="1" wdcount="1"> AP890715-0076</s>
</DOCNO>
<FILEID>

<s docid="AP890715-0076" num="2" wdcount="2"> AP-NR-07-15-89 1301EST</s>
</FILEID>
<FIRST>

<s docid="AP890715-0076" num="3" wdcount="5"> r w AM-Senate-Ambassadors 07-15 0899</s>
</FIRST>
<SECOND>

<s docid="AP890715-0076" num="4" wdcount="1"> AM-Senate-Ambassadors,840</s>
</SECOND>
<HEAD>

<s docid="AP890715-0076" num="5" wdcount="6"> Senate Democrats Question ``Unqualified'' Bush Appointees</s>
</HEAD>
<BYLINE>

<s docid="AP890715-0076" num="6" wdcount="4"> By LAWRENCE L. KNUTSON</s>
</BYLINE>
<BYLINE>

<s docid="AP890715-0076" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890715-0076" num="8" wdcount="2"> WASHINGTON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890715-0076" num="9" wdcount="33"> Joseph B. Gildenhorn, the lawyer and real estate developer named by President Bush as U.S. ambassador to Switzerland, and his immediate family gave nearly $230,000 to Republican campaigns since 1984, disclosure statements show.</s>

<s docid="AP890715-0076" num="10" wdcount="38"> Gildenhorn, according to Senate sources, is one of several Bush ambassadorial nominees who have been rated ``unqualified'' by the American Academy of Diplomacy, an organization composed of former high ranking diplomats, including all living former secretaries of state.</s>

<s docid="AP890715-0076" num="11" wdcount="31"> One of a lengthy and growing list of Bush supporters and contributors named to diplomatic posts, Gildenhorn gave $100,000 during the 1988 presidential campaign to the Republican National State Elections Committee.</s>

<s docid="AP890715-0076" num="12" wdcount="15"> The gift was not subject to the disclosure requirements of the Federal Election Campaign Act.</s>

<s docid="AP890715-0076" num="13" wdcount="45"> The 84 contributions made between 1984 and early this year by Gildenhorn and members of his immediate family are being used by Senate Democrats to illustrate their complaint that too many GOP contributors are being given choice diplomatic posts better reserved for Foreign Service professionals.</s>

<s docid="AP890715-0076" num="14" wdcount="14"> Gildenhorn said Friday he could not comment because he is ``in a confirmation process''.</s>

<s docid="AP890715-0076" num="15" wdcount="31"> A report prepared by the State Department for the Foreign Relations Committee said Gildenhorn would make an ``excellent'' candidate for an ambassadorship because of his ``solid background in law and management''.</s>

<s docid="AP890715-0076" num="16" wdcount="5"> It also cited another qualification.</s>

<s docid="AP890715-0076" num="17" wdcount="21"> ``Mr. Gildenhorn has been a strong Republican supporter being a member of the Eagles and Team 100,'' the State Department said.</s>

<s docid="AP890715-0076" num="18" wdcount="29"> The Republican Eagles are contributors of $10,000 or more in a single year to the Republican National Committee, while Team 100 designates people who have donated $100,000 or more.</s>

<s docid="AP890715-0076" num="19" wdcount="27"> Gildenhorn's political contributions are listed on a disclosure form submitted to the Senate Foreign Relations Committee, which has set a hearing on the nomination for this week.</s>

<s docid="AP890715-0076" num="20" wdcount="21"> They totaled $14,675 in 1984, $17,000 in 1985; $25,469.97 in 1986; $25,250 in 1987; $104,350 in 1988; and $11,000 this year.</s>

<s docid="AP890715-0076" num="21" wdcount="3"> The total: $197,744.97.</s>

<s docid="AP890715-0076" num="22" wdcount="32"> Additionally, his wife, Alma Lee, gave $20,125 over the six years, including $13,000 in 1988; his daughter, Carolyn, gave $2,000; his son, Michael, gave $4,050 and his father, Oscar Gildenhorn, gave $5,750.</s>

<s docid="AP890715-0076" num="23" wdcount="18"> That brings the total contributions made by Gildenhorn and his family to the GOP to $229,669.97 since 1984.</s>

<s docid="AP890715-0076" num="24" wdcount="16"> Gildenhorn gave $50,000 during the period to the Republican National Committee or to the Republican Eagles.</s>

<s docid="AP890715-0076" num="25" wdcount="34"> He gave $2,500 in 1985 and $5,000 in 1986 to the Fund for the American Future, a Bush political action committee and contributed the legal limit of $1,000 to the Bush campaign in 1987.</s>

<s docid="AP890715-0076" num="26" wdcount="10"> Gildenhorn also gave thousands of dollars to Republican congressional candidates.</s>

<s docid="AP890715-0076" num="27" wdcount="8"> Included were gifts to the campaigns of Sens.</s>

<s docid="AP890715-0076" num="28" wdcount="3"> Rudy Boschwitz, R-Minn.</s>

<s docid="AP890715-0076" num="29" wdcount="6"> Bill Cohen, R-Maine; Pete Domenici, R-N.M.</s>

<s docid="AP890715-0076" num="30" wdcount="3"> Arlen Specter, R-Pa.</s>

<s docid="AP890715-0076" num="31" wdcount="3"> John Warner, R-Va.</s>

<s docid="AP890715-0076" num="32" wdcount="12"> Orrin Hatch, R-Utah; Bob Kasten, R-Wis. and former Sen. Paula Hawkins, R-Fla.</s>

<s docid="AP890715-0076" num="33" wdcount="18"> Gildenhorn, 59, is a senior partner in Brown, Gildenhorn and Jacobs, a law firm specializing in real estate.</s>

<s docid="AP890715-0076" num="34" wdcount="29"> He is also president of the JBG Real Estate Associates and JBG Properties Inc. Gildenhorn is also vice chairman of the board of directors of the Sovran Bank here.</s>

<s docid="AP890715-0076" num="35" wdcount="14"> He is a graduate of the University of Maryland and Yale University Law School.</s>

<s docid="AP890715-0076" num="36" wdcount="56"> Other ambassadorial nominees rated as unqualified by the American Academy of Diplomacy include Florida real estate developer Joseph Zappala, nominated as ambassador to Spain; Melvin L. Sembler, a real estate executive in Florida named to be ambassador to Australia; and Della M. Newman, a Seattle, Wash., real estate broker named to be ambassador to New Zealand.</s>

<s docid="AP890715-0076" num="37" wdcount="13"> No action has been taken by the Senate on any of those nominations.</s>

<s docid="AP890715-0076" num="38" wdcount="6"> According to Sen. Paul Sarbanes, D-Md.</s>

<s docid="AP890715-0076" num="39" wdcount="22"> , who first raised the issue of political contributions, Zappala and Sembler each contributed more than $100,000 to Republican candidates and causes.</s>

<s docid="AP890715-0076" num="40" wdcount="13"> Mrs. Newman served as chairman of the Washington state Bush for President committee.</s>

<s docid="AP890715-0076" num="41" wdcount="27"> Ambassador David Popper, president of the Academy of Diplomacy, declined to confirm that Gildenhorn and the other three nominees had been rated as unqualified to become ambassadors.</s>

<s docid="AP890715-0076" num="42" wdcount="26"> But he said the academy does offer such ratings, making its judgments based on a comparison of the nominee's biography and the requirements of the job.</s>

<s docid="AP890715-0076" num="43" wdcount="37"> He said the nonpartisan academy has no objections to political appointees as such but does believe political nominees should be qualified to run a complex embassy and represent the United States abroad with ``dignity, respect and ability''.</s>

<s docid="AP890715-0076" num="44" wdcount="31"> Twenty of 29 ambassadorial nomination made by Bush in the first six months of his administration have gone to non-professionals, many of them large contributors to Republican causes, committee sources said.</s>

<s docid="AP890715-0076" num="45" wdcount="16"> Sarbanes says the appointments are larding the diplomatic corps with amateurs rewarded for purely political services.</s>

<s docid="AP890715-0076" num="46" wdcount="5"> ``Political throwaways,'' Sarbanes calls them.</s>

<s docid="AP890715-0076" num="47" wdcount="44"> ``I think the time has come, very frankly, to get off the money merry-go-round and ask some very difficult questions, essentially about when extensive political contributions are going to be a sufficient basis to gain an ambassadorial nomination,'' Sarbanes told the committee last month.</s>

<s docid="AP890715-0076" num="48" wdcount="31"> ``It's not true in every instance, but in most of these cases you seem to have to be over the $100,000 mark in order to make the consideration list,'' Sarbanes said.</s>

<s docid="AP890715-0076" num="49" wdcount="18"> Sarbanes says he is not against political ambassadors as such, noting that many of them compiled distinguished records.</s>

<s docid="AP890715-0076" num="50" wdcount="12"> ``It is not the political ambassadors that are the problem,'' Sarbanes said.</s>

<s docid="AP890715-0076" num="51" wdcount="5"> ``It is ambassadors without qualifications.''</s>
</TEXT>
</DOC>
