<DOC>
<DOCNO>

<s docid="AP890517-0106" num="1" wdcount="1"> AP890517-0106</s>
</DOCNO>
<FILEID>

<s docid="AP890517-0106" num="2" wdcount="2"> AP-NR-05-17-89 1321EST</s>
</FILEID>
<FIRST>

<s docid="AP890517-0106" num="3" wdcount="5"> r w PM-Secchia-Italy 05-17 0254</s>
</FIRST>
<SECOND>

<s docid="AP890517-0106" num="4" wdcount="1"> PM-Secchia-Italy,250</s>
</SECOND>
<HEAD>

<s docid="AP890517-0106" num="5" wdcount="6"> Senate Panel OKs Envoy to Italy</s>
</HEAD>
<DATELINE>

<s docid="AP890517-0106" num="6" wdcount="2"> WASHINGTON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890517-0106" num="7" wdcount="41"> The Senate Foreign Relations Committee today endorsed the nomination of Michigan Republican activist Peter F. Secchia as ambassador to Italy, but the panel's chairman said he feared Secchia might ``embarrass the United States'' because of his ``penchant for making gross remarks''.</s>

<s docid="AP890517-0106" num="8" wdcount="20"> The committee's vote was 13-0 in favor of Secchia, a former Republican national committeeman for Michigan and lumber industry executive.</s>

<s docid="AP890517-0106" num="9" wdcount="6"> The chairman, Sen. Claiborne Pell, D-R.I.</s>

<s docid="AP890517-0106" num="10" wdcount="6"> , and Sen. Alan Cranston, D-Calif.</s>

<s docid="AP890517-0106" num="11" wdcount="8"> , voted ``present,'' meaning they took no position.</s>

<s docid="AP890517-0106" num="12" wdcount="14"> Pell inserted into the hearing record newspaper accounts ``containing the distasteful specifics of Mr.</s>

<s docid="AP890517-0106" num="13" wdcount="2"> Secchia's remarks''.</s>

<s docid="AP890517-0106" num="14" wdcount="37"> At his confirmation hearing earlier this month, Secchia pledged to be far more careful as a diplomat in his use of colorful language than he had been in his different role as a political organizer and enthusiast.</s>

<s docid="AP890517-0106" num="15" wdcount="6"> But Pell said he was unpersuaded.</s>

<s docid="AP890517-0106" num="16" wdcount="11"> ``Tact and careful speech are hallmarks of successful diplomats,'' Pell said.</s>

<s docid="AP890517-0106" num="17" wdcount="17"> ``Mr. Secchia has demonstrated that he would bring opposite qualities to the position of ambassador to Italy''.</s>

<s docid="AP890517-0106" num="18" wdcount="26"> ``Italian friends of mine telephoned me from Rome, aghast at the prospect of having Mr. Secchia represent the United States in their country,'' the chairman said.</s>

<s docid="AP890517-0106" num="19" wdcount="27"> ``I believe that this nomination is a mistake, and in all likelihood Mr. Secchia will be an embarrasment to the administration and the United States,'' Pell said.</s>

<s docid="AP890517-0106" num="20" wdcount="24"> But he said that since Secchia is ``the president's choice'' he would not try to block the nomination or delay action on it .</s>
</TEXT>
</DOC>
