<DOC>
<DOCNO>

<s docid="AP890801-0134" num="1" wdcount="1"> AP890801-0134</s>
</DOCNO>
<FILEID>

<s docid="AP890801-0134" num="2" wdcount="2"> AP-NR-08-01-89 2053EDT</s>
</FILEID>
<FIRST>

<s docid="AP890801-0134" num="3" wdcount="5"> r i AM-UN-American 08-01 0274</s>
</FIRST>
<SECOND>

<s docid="AP890801-0134" num="4" wdcount="1"> AM-UN-American,0284</s>
</SECOND>
<HEAD>

<s docid="AP890801-0134" num="5" wdcount="8"> Ronald Spiers Replaces Joseph Reed As Top U.S.</s>

<s docid="AP890801-0134" num="6" wdcount="4"> Official at U.N .</s>
</HEAD>
<DATELINE>

<s docid="AP890801-0134" num="7" wdcount="3"> UNITED NATIONS (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890801-0134" num="8" wdcount="28"> Ronald I. Spiers, a veteran U.S. diplomat, will be the new undersecretary-general for General Assembly affairs, the top-ranking American post at the world body, U.N. officials said Tuesday.</s>

<s docid="AP890801-0134" num="9" wdcount="17"> Spiers was ambassador to Pakistan from 1981-83 and has served as ambassador to the Bahamas and Turkey.</s>

<s docid="AP890801-0134" num="10" wdcount="27"> He replaces Joseph Verner Reed, a banker who served in the post from 1987 until leaving last winter to become chief of protocol for the United States.</s>

<s docid="AP890801-0134" num="11" wdcount="33"> Although Spiers' nomination as undersecretary-general for Political and General Assembly Affairs and Secretariat Services had been an open secret for months, Secretary-General Javier Perez de Cuellar announced it was effective as of Tuesday.</s>

<s docid="AP890801-0134" num="12" wdcount="19"> Spiers, 64, is a career foreign service officer, most recently serving as undersecretary of state for management since 1983.</s>

<s docid="AP890801-0134" num="13" wdcount="21"> Spiers has been a member of the U.S. delegation to the United Nations; was director of political affairs for the U.S.</s>

<s docid="AP890801-0134" num="14" wdcount="15"> Arms Control and Disarmament Agency; and was director of NATO Affairs for the State Department.</s>

<s docid="AP890801-0134" num="15" wdcount="11"> From 1966-69, Spiers was counselor for political affairs in the U.S.</s>

<s docid="AP890801-0134" num="16" wdcount="3"> Embassy in London.</s>

<s docid="AP890801-0134" num="17" wdcount="17"> In 1969, he became assistant secretary of State in charge of the department's Bureau of Political-Military Affairs.</s>

<s docid="AP890801-0134" num="18" wdcount="18"> When the Bahamas became independent from Britain in 1973, Spiers became the first U.S. ambassador to that nation.</s>

<s docid="AP890801-0134" num="19" wdcount="14"> He became charge d'affaires in London in 1974, and was minister of the U.S.</s>

<s docid="AP890801-0134" num="20" wdcount="11"> Embassy there until 1977, when he was appointed ambassador to Turkey.</s>

<s docid="AP890801-0134" num="21" wdcount="23"> In 1980 he returned to the State Department as director of Intelligence and Research, and was appointed ambassador to Pakistan in 1981 .</s>
</TEXT>
</DOC>
