<DOC>
<DOCNO>

<s docid="AP900510-0029" num="1" wdcount="1"> AP900510-0029</s>
</DOCNO>
<FILEID>

<s docid="AP900510-0029" num="2" wdcount="2"> AP-NR-05-10-90 0303EDT</s>
</FILEID>
<FIRST>

<s docid="AP900510-0029" num="3" wdcount="5"> r w PM-Nicaragua-Ambassador 05-10 0413</s>
</FIRST>
<SECOND>

<s docid="AP900510-0029" num="4" wdcount="1"> PM-Nicaragua-Ambassador,410</s>
</SECOND>
<HEAD>

<s docid="AP900510-0029" num="5" wdcount="8"> Veteran Diplomat Displaces First Choice for Managua Post</s>
</HEAD>
<BYLINE>

<s docid="AP900510-0029" num="6" wdcount="3"> By GEORGE GEDDA</s>
</BYLINE>
<BYLINE>

<s docid="AP900510-0029" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900510-0029" num="8" wdcount="2"> WASHINGTON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900510-0029" num="9" wdcount="26"> The Bush administration is expected to name career diplomat Harry Shlaudeman as the first U.S. ambassador to Nicaragua in almost two years, a U.S. official says.</s>

<s docid="AP900510-0029" num="10" wdcount="37"> The administration had planned to send another career diplomat, Melissa Wells, to Managua but had a change of heart after concluding she might face a prolonged Senate confirmation fight because she has been a target of conservatives.</s>

<s docid="AP900510-0029" num="11" wdcount="38"> The administration is eager to have an ambassador in Managua quickly because of the delicate political situation there now that U.S.-backed President Violeta Chamorro has taken over after almost 11 years of rule by the leftist Sandinista party.</s>

<s docid="AP900510-0029" num="12" wdcount="20"> Mrs. Chamorro faces the demanding challenges of reviving Nicaragua's bankrupt economy and achieving national reconciliation after long years of warfare.</s>

<s docid="AP900510-0029" num="13" wdcount="12"> The United States has had no ambassador to Nicaragua since July 1988.</s>

<s docid="AP900510-0029" num="14" wdcount="26"> At the time, the Sandinista government expelled Ambassador Richard Melton and seven others at the embassy on grounds they were interfering in the country's internal affairs.</s>

<s docid="AP900510-0029" num="15" wdcount="15"> The Reagan administration retaliated by expelling eight Nicaraguan envoys in Washington, including Ambassador Carlos Tunnermann.</s>

<s docid="AP900510-0029" num="16" wdcount="29"> Shlaudeman, who has served as ambassador to Argentina, Peru, Brazil and Venezuela, is a premier State Department specialist on Latin America and is expected to win easy Senate confirmation.</s>

<s docid="AP900510-0029" num="17" wdcount="29"> He retired from the foreign service a year ago but was called back to duty last fall to serve as a State Department liaison with the Nicaraguan Contra rebels.</s>

<s docid="AP900510-0029" num="18" wdcount="27"> Shlaudeman, who will turn 64 next week, was approached by a senior State Department official weeks ago about going to Managua but said he was not interested.</s>

<s docid="AP900510-0029" num="19" wdcount="15"> He told intimates he would agree to go only if asked personally by President Bush.</s>

<s docid="AP900510-0029" num="20" wdcount="23"> When Bush telephoned him earlier this week, Shlaudeman agreed to the appointment, the U.S. official, who spoke on condition of anonymity, said Wednesday.</s>

<s docid="AP900510-0029" num="21" wdcount="29"> In addition to his ambassadorial posts, Shlaudeman was the top Latin America aide to President Ford in the mid-1970s and a diplomatic trouble-shooter in Central America under President Reagan.</s>

<s docid="AP900510-0029" num="22" wdcount="8"> The U.S. official said Sen. Jesse Helms, R-N.C.</s>

<s docid="AP900510-0029" num="23" wdcount="19"> , and several of his conservative allies would not assure the administration that they would not delay Wells' nomination.</s>

<s docid="AP900510-0029" num="24" wdcount="22"> When Wells was nominated to be ambassador to Mozambique in late 1986, Helms and his colleagues blocked her appointment for 11 months.</s>

<s docid="AP900510-0029" num="25" wdcount="20"> They took the action as a means of expressing opposition to the Reagan administration's friendship toward Mozambique's Marxist government .</s>
</TEXT>
</DOC>
