<DOC>
<DOCNO>

<s docid="AP900420-0006" num="1" wdcount="1"> AP900420-0006</s>
</DOCNO>
<FILEID>

<s docid="AP900420-0006" num="2" wdcount="2"> AP-NR-04-20-90 0155EDT</s>
</FILEID>
<FIRST>

<s docid="AP900420-0006" num="3" wdcount="6"> r w PM-US-Nicaragua Bjt 04-20 0434</s>
</FIRST>
<SECOND>

<s docid="AP900420-0006" num="4" wdcount="2"> PM-US-Nicaragua, Bjt,430</s>
</SECOND>
<HEAD>

<s docid="AP900420-0006" num="5" wdcount="9"> Woman Ready to be Tapped as Ambassador to Nicaragua</s>
</HEAD>
<BYLINE>

<s docid="AP900420-0006" num="6" wdcount="3"> By GEORGE GEDDA</s>
</BYLINE>
<BYLINE>

<s docid="AP900420-0006" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900420-0006" num="8" wdcount="2"> WASHINGTON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900420-0006" num="9" wdcount="31"> President Bush is expected to name a female career diplomat as U.S. ambassador to Nicaragua as that country prepares for a new era under President-elect Violeta Chamorro, according to informed sources.</s>

<s docid="AP900420-0006" num="10" wdcount="20"> The sources said Thursday it is virtually certain the appointment will go to Melissa Wells, 57, currently ambassador to Mozambique.</s>

<s docid="AP900420-0006" num="11" wdcount="21"> They said the administration believed a female ambassador could relate better than a man to Mrs. Chamorro, who takes office Wednesday.</s>

<s docid="AP900420-0006" num="12" wdcount="14"> They also said the administration is eager to have more women in key posts.</s>

<s docid="AP900420-0006" num="13" wdcount="11"> Only rarely have U.S. ambassadorships in Latin America gone to women.</s>

<s docid="AP900420-0006" num="14" wdcount="3"> In choosing Ms.</s>

<s docid="AP900420-0006" num="15" wdcount="24"> Wells, the administration passed over several male career diplomats with long experience in that region, said the sources, who asked not to be identified.</s>

<s docid="AP900420-0006" num="16" wdcount="14"> Ms. Wells, who was born in Estonia, has no prior experience in Latin America.</s>

<s docid="AP900420-0006" num="17" wdcount="7"> Her personnel record indicates she speaks Spanish.</s>

<s docid="AP900420-0006" num="18" wdcount="30"> Wells' name was submitted to the White House by Secretary of State James A. Baker III for the Managua post, and approval is considered ``99.9 percent certain,'' one source said.</s>

<s docid="AP900420-0006" num="19" wdcount="16"> The United States and Nicaragua have not had ambassadors in each other's capitals since July 1988.</s>

<s docid="AP900420-0006" num="20" wdcount="5"> The Sandinista government expelled then-U.S.</s>

<s docid="AP900420-0006" num="21" wdcount="18"> ambassador Richard Melton and seven other U.S. diplomats on the grounds they were interfering in Nicaragua's internal affairs.</s>

<s docid="AP900420-0006" num="22" wdcount="20"> The Reagan administration retaliated by expelling Nicaraguan Ambassador Carlos Tunnermann and seven of his subordinates from the Nicaraguan embassy here.</s>

<s docid="AP900420-0006" num="23" wdcount="26"> But a new era in U.S.-Nicaraguan relations is expected to open with the inauguration of Mrs. Chamorro, who defeated President Daniel Ortega in elections this February.</s>

<s docid="AP900420-0006" num="24" wdcount="17"> Vice President Dan Quayle and a large congressional delegation are expected to represent Bush at her inaugural.</s>

<s docid="AP900420-0006" num="25" wdcount="22"> The administration has asked Congress for $300 million in assistance to Nicaragua, part of which would be used for resettling Contra rebels.</s>

<s docid="AP900420-0006" num="26" wdcount="25"> But the request has been stalled by Senate Democrats, some of whom believe that Eastern Europe has a greater claim on U.S. resources than Nicaragua.</s>

<s docid="AP900420-0006" num="27" wdcount="30"> Wells' nomination as ambassador to Mozambique in 1986 encountered strong opposition from Senate conservatives who held up the appointment for 11 months in protest against U.S. policy toward that country.</s>

<s docid="AP900420-0006" num="28" wdcount="8"> The nomination finally was approved in September 1987.</s>

<s docid="AP900420-0006" num="29" wdcount="4"> Sen. Jesse Helms, R-N.C.</s>

<s docid="AP900420-0006" num="30" wdcount="28"> , a leader of the campaign to hold up Wells' nomination, said he wanted to pressure the administration into dealing with rightist guerrillas opposed to Mozambique's Marxist government.</s>

<s docid="AP900420-0006" num="31" wdcount="20"> Mozambique has since moderated its policies and is now off the U.S. government's list of countries under Marxist rule .</s>
</TEXT>
</DOC>
