<DOC>
<DOCNO>

<s docid="AP900102-0114" num="1" wdcount="1"> AP900102-0114</s>
</DOCNO>
<FILEID>

<s docid="AP900102-0114" num="2" wdcount="2"> AP-NR-01-02-90 1736EDT</s>
</FILEID>
<FIRST>

<s docid="AP900102-0114" num="3" wdcount="6"> u w AM-PanamaAmbassador 1stLd-Writethru 01-02 0418</s>
</FIRST>
<SECOND>

<s docid="AP900102-0114" num="4" wdcount="4"> AM-Panama Ambassador, 1st Ld-Writethru,340</s>
</SECOND>
<HEAD>

<s docid="AP900102-0114" num="5" wdcount="8"> Bush Names Deane Hinton as Ambassador to Panama</s>
</HEAD>
<NOTE>

<s docid="AP900102-0114" num="6" wdcount="9"> Eds: ADDS 2 grafs to UPDATE with Mitchell reaction</s>
</NOTE>
<HEAD>

<s docid="AP900102-0114" num="7" wdcount="3"> With AM-Panama, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP900102-0114" num="8" wdcount="3"> By RITA BEAMISH</s>
</BYLINE>
<BYLINE>

<s docid="AP900102-0114" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900102-0114" num="10" wdcount="2"> WASHINGTON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900102-0114" num="11" wdcount="17"> President Bush has named career diplomat Deane Hinton as ambassador to Panama, the White House announced Tuesday.</s>

<s docid="AP900102-0114" num="12" wdcount="36"> Hinton, currently ambassador to Costa Rica, replaces Ambassador Arthur H. Davis, who was recalled by Bush in protest of what the administration considered the stealing of the Panamanian elections last May by Gen. Manuel Antonio Noriega.</s>

<s docid="AP900102-0114" num="13" wdcount="24"> Bush sent Davis back to Panama City after the Dec. 20 invasion of Panama by U.S. forces and installation of Guillermo Endara as president.</s>

<s docid="AP900102-0114" num="14" wdcount="13"> Independent observers mostly concluded Endara had won the elections by a hefty margin.</s>

<s docid="AP900102-0114" num="15" wdcount="13"> Bush named Hinton as a recess appointment because Congress is not in session.</s>

<s docid="AP900102-0114" num="16" wdcount="20"> That means Hinton can serve until the end of next year before he must go before the Senate for confirmation.</s>

<s docid="AP900102-0114" num="17" wdcount="31"> The appointment of the 66-year-old Hinton, with his long expierience on Latin American issues, is seen as a signal of the importance Bush is placing on restoring normal relations with Panama.</s>

<s docid="AP900102-0114" num="18" wdcount="25"> Those relations steadily deteriorated after the United States indicted Noriega, once a ally particularly of the U.S. intelligence community, on drug trafficking charges in Florida.</s>

<s docid="AP900102-0114" num="19" wdcount="9"> Hinton has been ambassador to Costa Rica since 1987.</s>

<s docid="AP900102-0114" num="20" wdcount="20"> Before that he was ambassador to Pakistan from 1983 to 1987, and ambassador to El Salvador from 1981 to 1983.</s>

<s docid="AP900102-0114" num="21" wdcount="53"> He was assistant secretary of state for economic and business affairs from 1979 to 1981, and before that U.S. representative to the 12-nation European Community, headquartered in Brussels, a State Department adviser on economic affairs, and director and economic counselor of the State Department's Agency for economic Development in Chile and in Guatemala.</s>

<s docid="AP900102-0114" num="22" wdcount="20"> Davis, a former State Department consultant and former ambassador to Paraguay, was sent to Panama by President Reagan in 1986.</s>

<s docid="AP900102-0114" num="23" wdcount="25"> Bush wanted to name his own ambassador and the time was appropriate with the installation of a new government in Panama, said one administration official.</s>

<s docid="AP900102-0114" num="24" wdcount="26"> Officials described Hinton as ``an experienced Latin America hand'' and a good person to have in place with the volatile developments in the South American country.</s>

<s docid="AP900102-0114" num="25" wdcount="26"> On Capitol Hill, Senate Majority Leader George Mitchell, D-Maine, called Hinton highly qualified for the post because of his ``wide-ranging experience and expertise in Central America''.</s>

<s docid="AP900102-0114" num="26" wdcount="26"> However, Mitchell said he hoped Bush would send the appointment to the Senate after Congress convenes Jan. 23 despite the nature of the recess appointment .</s>
</TEXT>
</DOC>
