<DOC>
<DOCNO>

<s docid="FBIS3-13911" num="1" wdcount="1"> FBIS3-13911</s>
</DOCNO>
<HT>

<s docid="FBIS3-13911" num="2" wdcount="1"> "drnes055_m_94004"</s>
</HT>
<HEADER>
<AU>

<s docid="FBIS3-13911" num="3" wdcount="1"> FBIS-NES-94-055</s>
</AU>

<s docid="FBIS3-13911" num="4" wdcount="3"> Document Type:Daily Report</s>
<DATE1>

<s docid="FBIS3-13911" num="5" wdcount="3"> 22 Mar 1994</s>
</DATE1>
</HEADER>
<F>

<s docid="FBIS3-13911" num="6" wdcount="1"> JORDAN</s>
</F>
<H3>
<TI>

<s docid="FBIS3-13911" num="7" wdcount="6"> Paper Profiles, Views New U.S. Ambassador</s>
</TI>
</H3>
<F>

<s docid="FBIS3-13911" num="8" wdcount="10"> JN2203103194 Amman AL-RA'Y in Arabic 22 Mar 94 p 22</s>
</F>
<F>

<s docid="FBIS3-13911" num="9" wdcount="1"> JN2203103194</s>
</F>
<F>

<s docid="FBIS3-13911" num="10" wdcount="2"> Amman AL-RA'Y</s>
</F>
<TEXT>

<s docid="FBIS3-13911" num="11" wdcount="1"> Language:</s>
<F>

<s docid="FBIS3-13911" num="12" wdcount="1"> Arabic</s>
</F>

<s docid="FBIS3-13911" num="13" wdcount="2"> Article Type:BFN</s>
<F>

<s docid="FBIS3-13911" num="14" wdcount="9"> ["Highlights" column by Fahd al-Fanik: "The New U.S .</s>
</F>

<s docid="FBIS3-13911" num="15" wdcount="13"> Ambassador"] [Text] The new U.S. ambassador to Jordan, Wesley Egan, is a heavyweight.</s>

<s docid="FBIS3-13911" num="16" wdcount="7"> Once the second man in the U.S.</s>

<s docid="FBIS3-13911" num="17" wdcount="16"> Embassy in Cairo, he also served in Saudi Arabia, two African countries, and a European nation.</s>

<s docid="FBIS3-13911" num="18" wdcount="24"> His choice for the new job signals the importance the United States attaches to Jordan in terms of inter-Arab politics and the Arab-Israeli dispute.</s>

<s docid="FBIS3-13911" num="19" wdcount="44"> Before Egan's appointment became final, he had to go through a grueling test in the U.S. Senate, where Senator Daniel Moynihan, the Zionist Democrat from New York, presided over the hearing that scrutinized the would-be ambassador's credentials and went on to confirm his nomination.</s>

<s docid="FBIS3-13911" num="20" wdcount="27"> In his testimony, Egan told the hearing he would work to develop relations between the United States and Jordan and enhance Jordan's role in the peace process.</s>

<s docid="FBIS3-13911" num="21" wdcount="23"> He pointed out that Jordan signed a joint agenda with Israel that will presumably culminate in a peace treaty between the two countries.</s>

<s docid="FBIS3-13911" num="22" wdcount="31"> His said his top priority in Amman will be to propel the peace process forward and recognize Jordan's energetic role in the effort to bring about a comprehensive Middle East peace.</s>

<s docid="FBIS3-13911" num="23" wdcount="18"> Mr. Egan will pay special attention to stability in Jordan, and watch its democratic march and economic development.</s>

<s docid="FBIS3-13911" num="24" wdcount="49"> He will also watch Jordan's approach to a number of other issues: human rights, compliance with the sanctions resolution against Iraq, terminating the boycott of U.S. companies doing business with Israel, the potential for foreign investment both in Jordan and elsewhere in the region, and the fight against terrorism.</s>

<s docid="FBIS3-13911" num="25" wdcount="30"> Much as I take exception to some of the issues that will engage the new ambassador's attention, I concern myself here with a lecture Moynihan delivered at the confirmation hearing.</s>

<s docid="FBIS3-13911" num="26" wdcount="30"> Discussing the West Bank and Gaza, he dismissed as inappropriate the designation attached to them as occupied territories, and asked: If these are occupied territories, who were they occupied by?</s>

<s docid="FBIS3-13911" num="27" wdcount="28"> These territories, contended the senator, were never the sovereign domain of anyone; it was Jordan that occupied the West Bank at the founding of the state of Israel.</s>

<s docid="FBIS3-13911" num="28" wdcount="18"> What Israel did was to take the West Bank from Jordan the way it took Gaza from Egypt.</s>

<s docid="FBIS3-13911" num="29" wdcount="21"> Previously, these territories were part of the British mandate, and before that they fell within the realm of the Ottoman Empire.</s>

<s docid="FBIS3-13911" num="30" wdcount="14"> Mr. Moynihan's point, in other words, is that these territories are up for grabs.</s>

<s docid="FBIS3-13911" num="31" wdcount="13"> The United States, he noted, never recognized Jordan's sovereignty over the West Bank.</s>

<s docid="FBIS3-13911" num="32" wdcount="14"> His bottom line: Israel did not occupy territory that was under another nation's sovereignty.</s>

<s docid="FBIS3-13911" num="33" wdcount="12"> This Zionist senator's remarks are not supposed to be Washington's official line.</s>

<s docid="FBIS3-13911" num="34" wdcount="43"> However, they do mirror an undeclared U.S. line dictated by the all-powerful Zionist lobby -- a line that is now all but declared with the bizarre voting stance of the United States toward the UN Security Council resolution condemning the Hebron massacre .</s>
</TEXT>
</DOC>
