<DOC>
<DOCNO>

<s docid="LA020389-0041" num="1" wdcount="1"> LA020389-0041</s>
</DOCNO>
<DOCID>

<s docid="LA020389-0041" num="2" wdcount="1"> 13561</s>
</DOCID>
<DATE>
<P>

<s docid="LA020389-0041" num="3" wdcount="6"> February 3, 1989, Friday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA020389-0041" num="4" wdcount="8"> Part 1; Page 14; Column 1; National Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA020389-0041" num="5" wdcount="2"> 545 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA020389-0041" num="6" wdcount="9"> BUSH PICKS CONTRA AID FIGURE AS ENVOY TO MEXICO</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA020389-0041" num="7" wdcount="6"> By DOYLE McMANUS, Times Staff Writer</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA020389-0041" num="8" wdcount="1"> WASHINGTON</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA020389-0041" num="9" wdcount="33"> President Bush has decided to nominate John D. Negroponte, a veteran diplomat who helped direct U.S. aid to Nicaraguan rebels, to the key position of ambassador to Mexico, Administration officials said Thursday .</s>
</P>
<P>

<s docid="LA020389-0041" num="10" wdcount="25"> Negroponte, a 28-year Foreign Service veteran, served as U.S. ambassador to Honduras from 1981 through 1985, when the CIA was secretly funding the Contras .</s>
</P>
<P>

<s docid="LA020389-0041" num="11" wdcount="15"> Mexico's leftist opposition party already has criticized the appointment, which has not been formally announced.</s>

<s docid="LA020389-0041" num="12" wdcount="23"> But Bush Administration officials said they are confident that the Mexican government of President Carlos Salinas de Gortari will accept the nomination .</s>
</P>
<P>
</P>
<P>

<s docid="LA020389-0041" num="13" wdcount="3"> Can Reject Nomination</s>
</P>
<P>

<s docid="LA020389-0041" num="14" wdcount="16"> Under diplomatic practice, the White House notifies other governments in advance of its choices for ambassadors.</s>

<s docid="LA020389-0041" num="15" wdcount="17"> The foreign government can reject the nomination, but rejection would be considered an unusual diplomatic slap .</s>
</P>
<P>

<s docid="LA020389-0041" num="16" wdcount="33"> Meanwhile, Bush's choice as assistant secretary of state for Latin America, Democratic political consultant Bernard Aronson, ran into objections from several Republican members of the Senate Foreign Relations Committee, congressional aides said .</s>
</P>
<P>

<s docid="LA020389-0041" num="17" wdcount="8"> The two senior Republicans on the panel, Sens.</s>

<s docid="LA020389-0041" num="18" wdcount="3"> Jesse Helms (R-N.</s>

<s docid="LA020389-0041" num="19" wdcount="23"> C). and Richard G. Lugar (R-Ind.), both expressed concern about Aronson's appointment to Secretary of State James A. Baker III, the aides said.</s>

<s docid="LA020389-0041" num="20" wdcount="29"> Helms questioned the appointment of a Democrat to the post, and Lugar expressed concern that Aronson had no experience with the economic issues facing South America, they said .</s>
</P>
<P>

<s docid="LA020389-0041" num="21" wdcount="33"> The aides said it appears unlikely that the senators will attempt to block Aronson's nomination but that the former aide to President Jimmy Carter will face tough questioning in his confirmation hearings .</s>
</P>
<P>

<s docid="LA020389-0041" num="22" wdcount="39"> Negroponte created controversy in Honduras as a vigorous proponent of the then-secret Contra effort; and Honduran opposition leaders, who said he acted as though he were the governor of a colony, dubbed him Washington's "proconsul" in the country .</s>
</P>
<P>

<s docid="LA020389-0041" num="23" wdcount="34"> But he later concluded that it had been a mistake for the Ronald Reagan Administration to aid the rebels secretly without building more public support for its policy in Central America, associates said .</s>
</P>
<P>

<s docid="LA020389-0041" num="24" wdcount="8"> Negroponte was most recently a deputy to Lt.</s>

<s docid="LA020389-0041" num="25" wdcount="35"> Gen. Colin L. Powell, President Reagan's last national security adviser, and had been an aide to Henry A. Kissinger, then national security adviser to President Richard M. Nixon, during the Vietnam war in 1970-73 .</s>
</P>
<P>

<s docid="LA020389-0041" num="26" wdcount="14"> He has also worked on negotiations with Mexico on environmental and tuna-fishing issues .</s>
</P>
<P>

<s docid="LA020389-0041" num="27" wdcount="13"> "He's one of the smartest operators in the business," a former aide said.</s>

<s docid="LA020389-0041" num="28" wdcount="8"> "He's very good at working the bureaucracy" .</s>
</P>
<P>

<s docid="LA020389-0041" num="29" wdcount="36"> State Department officials said that they had expected Mexican leftists to register complaints about the appointment because of Negroponte's support of the Contras but that they are confident that Salinas' government will not object formally .</s>
</P>
<P>

<s docid="LA020389-0041" num="30" wdcount="25"> "They will blow a little steam off in the press, but I don't think the Mexican government would dream of rejecting him," one official said.</s>

<s docid="LA020389-0041" num="31" wdcount="15"> "They don't want to get relations with the Bush Administration off on that footing" .</s>
</P>
<P>

<s docid="LA020389-0041" num="32" wdcount="10"> Negroponte, 49, will succeed Charles Pilliod, an Ohio industrialist .</s>
</P>
<P>

<s docid="LA020389-0041" num="33" wdcount="12"> Staff writer Marjorie Miller in Mexico City contributed to this story .</s>
</P>
</TEXT>
<TYPE>
<P>

<s docid="LA020389-0041" num="34" wdcount="1"> Appointment</s>
</P>
</TYPE>
<SUBJECT>
<P>

<s docid="LA020389-0041" num="35" wdcount="31"> UNITED STATES -- FOREIGN RELATIONS -- MEXICO; BUSH, GEORGE; POLITICAL APPOINTMENTS; UNITED STATES -- AMBASSADORS; NEGROPONTE, JOHN D; NICARAGUA -- REVOLTS; UNITED STATES -- FOREIGN AID -- NICARAGUA; GUERRILLAS -- NICARAGUA</s>
</P>
</SUBJECT>
</DOC>
