<DOC>
<DOCNO>

<s docid="LA020289-0065" num="1" wdcount="1"> LA020289-0065</s>
</DOCNO>
<DOCID>

<s docid="LA020289-0065" num="2" wdcount="1"> 13111</s>
</DOCID>
<DATE>
<P>

<s docid="LA020289-0065" num="3" wdcount="6"> February 2, 1989, Thursday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA020289-0065" num="4" wdcount="8"> Part 1; Page 17; Column 1; National Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA020289-0065" num="5" wdcount="2"> 376 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA020289-0065" num="6" wdcount="9"> BUSH REPORTEDLY PICKS EX-CIA OFFICER AS AMBASSADOR TO CHINA</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA020289-0065" num="7" wdcount="6"> By JIM MANN, Times Staff Writer</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA020289-0065" num="8" wdcount="1"> WASHINGTON</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA020289-0065" num="9" wdcount="23"> President Bush, filling a key overseas post, has decided to nominate a former CIA officer as ambassador to China, sources said Wednesday .</s>
</P>
<P>

<s docid="LA020289-0065" num="10" wdcount="29"> The choice is James R. Lilley, a career intelligence officer who served as CIA station chief in China when Bush headed the U.S. liaison office there in 1974-75 .</s>
</P>
<P>

<s docid="LA020289-0065" num="11" wdcount="40"> Word of the expected nomination came as Bush's choice to be assistant secretary of state for Latin America, Democratic political consultant Bernard Aronson, ran into objections from several Republican members of the Senate Foreign Relations Committee, congressional aides said .</s>
</P>
<P>

<s docid="LA020289-0065" num="12" wdcount="8"> The two senior Republicans on the panel, Sens.</s>

<s docid="LA020289-0065" num="13" wdcount="3"> Jesse Helms (R-N.C).</s>

<s docid="LA020289-0065" num="14" wdcount="23"> and Richard G. Lugar (R-Ind.), both expressed concern about Aronson's appointment to Secretary of State James A. Baker III, the aides said .</s>
</P>
<P>
</P>
<P>

<s docid="LA020289-0065" num="15" wdcount="4"> May Face Tough Questioning</s>
</P>
<P>

<s docid="LA020289-0065" num="16" wdcount="31"> They said that it appears unlikely the senators would attempt to block Aronson's nomination but said that the former Jimmy Carter aide will face tough questioning in his confirmation hearings .</s>
</P>
<P>

<s docid="LA020289-0065" num="17" wdcount="14"> Lilley, 60, was born in China, the son of an American oilman working there.</s>

<s docid="LA020289-0065" num="18" wdcount="30"> He has also served on the National Security Council staff, as head of the unofficial U.S. office in Taiwan and as a deputy assistant secretary of state for East Asia.</s>

<s docid="LA020289-0065" num="19" wdcount="16"> He will replace Winston Lord, who has headed the American Embassy in Beijing since 1985 .</s>
</P>
<P>

<s docid="LA020289-0065" num="20" wdcount="13"> For the last three years, Lilley served as U.S. ambassador to South Korea.</s>

<s docid="LA020289-0065" num="21" wdcount="37"> In that job, he was the principal American contact with South Korean leaders during the turbulent period when former President Chun Doo Hwan resigned and the current president, Roh Tae Woo, won a bitterly contested election .</s>
</P>
<P>
</P>
<P>

<s docid="LA020289-0065" num="22" wdcount="3"> Returns to Washington</s>
</P>
<P>

<s docid="LA020289-0065" num="23" wdcount="32"> Lilley left Seoul last month and returned to Washington, hoping to be appointed as assistant secretary of state in charge of U.S. policy in East Asia and the Pacific, sources said .</s>
</P>
<P>

<s docid="LA020289-0065" num="24" wdcount="24"> However, he failed to get that job, in part because newly appointed Deputy Secretary of State Lawrence S. Eagleburger opposed him, the sources said.</s>

<s docid="LA020289-0065" num="25" wdcount="26"> Eagleburger was said to have been promoting two other candidates -- Lord and U.S. Ambassador to the Philippines Nicholas Platt -- for the Asian post .</s>
</P>
<P>

<s docid="LA020289-0065" num="26" wdcount="16"> Eagleburger and Lord served together as aides to former Secretary of State Henry A. Kissinger .</s>
</P>
</TEXT>
<TYPE>
<P>

<s docid="LA020289-0065" num="27" wdcount="1"> Appointment</s>
</P>
</TYPE>
<SUBJECT>
<P>

<s docid="LA020289-0065" num="28" wdcount="19"> POLITICAL APPOINTMENTS; BUSH, GEORGE; UNITED STATES -- AMBASSADORS; UNITED STATES -- EMBASSIES -- CHINA; LILLEY, JAMES R; ARONSON, BERNARD</s>
</P>
</SUBJECT>
</DOC>
