<DOC>
<DOCNO>

<s docid="LA072689-0050" num="1" wdcount="1"> LA072689-0050</s>
</DOCNO>
<DOCID>

<s docid="LA072689-0050" num="2" wdcount="1"> 86911</s>
</DOCID>
<DATE>
<P>

<s docid="LA072689-0050" num="3" wdcount="6"> July 26, 1989, Wednesday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA072689-0050" num="4" wdcount="8"> Part 1; Page 13; Column 1; National Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA072689-0050" num="5" wdcount="2"> 350 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA072689-0050" num="6" wdcount="8"> 3 AMBASSADORIAL NOMINATIONS SQUEAK BY IN SENATE COMMITTEE</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA072689-0050" num="7" wdcount="4"> From Times Wire Services</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA072689-0050" num="8" wdcount="1"> WASHINGTON</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA072689-0050" num="9" wdcount="26"> Three of President Bush's ambassadorial nominees, whom Democrats said had no qualifications except political connections, won narrow approval Tuesday from the Senate Foreign Relations Committee .</s>
</P>
<P>

<s docid="LA072689-0050" num="10" wdcount="5"> Sen. Charles S. Robb (D-Va).</s>

<s docid="LA072689-0050" num="11" wdcount="33"> joined the Republican members as the panel first voted, 10 to 9, to send to the Senate floor the nomination of Florida real estate developer Joseph Zappala to be ambassador to Spain .</s>
</P>
<P>

<s docid="LA072689-0050" num="12" wdcount="39"> Then, in voice votes, the committee approved the equally controversial nominations of Florida real estate developer Marvin Sembler to be ambassador to Australia and Della Newman, a Seattle, Wash., real estate broker, to be ambassador to New Zealand .</s>
</P>
<P>

<s docid="LA072689-0050" num="13" wdcount="47"> Robb said later that he was troubled over Zappala's "quite thin" qualifications for the job but that he felt he had made an "implicit" commitment to vote for the nominee when he interviewed him May 11 and did not clearly indicate that he would oppose him .</s>
</P>
<P>

<s docid="LA072689-0050" num="14" wdcount="22"> Sen. Paul S. Sarbanes (D-Md.), who led the opposition to the nominations, vowed to carry the fight to the Senate floor .</s>
</P>
<P>

<s docid="LA072689-0050" num="15" wdcount="20"> "One looks through this resume wondering why this person has been appointed to this position," Sarbanes said of Zappala .</s>
</P>
<P>

<s docid="LA072689-0050" num="16" wdcount="15"> "The answer is to be found in the appendix, which lists the campaign contributions" .</s>
</P>
<P>

<s docid="LA072689-0050" num="17" wdcount="22"> Zappala reported to the committee that he contributed $126,000 last year to Republican campaigns and gave $17,900 in the previous two years.</s>

<s docid="LA072689-0050" num="18" wdcount="29"> His prior governmental experience, described on the ambassadorial evaluation form submitted to the committee, consisted mainly of chairing campaign finance committees for President Bush and the Republican Party .</s>
</P>
<P>
</P>
<P>

<s docid="LA072689-0050" num="19" wdcount="2"> Other Approvals</s>
</P>
<P>

<s docid="LA072689-0050" num="20" wdcount="19"> In other action, the committee routinely approved the nomination of Shirley Temple Black to be ambassador to Czechoslovakia .</s>
</P>
<P>

<s docid="LA072689-0050" num="21" wdcount="57"> It also approved the nominations of Thomas Melady to be ambassador to the Vatican, William Howard Taft IV to be the permanent U.S. representative on the Council of the North Atlantic Treaty Organization, Keith L. Brown to be ambassador to Denmark, and Joseph Gildenhorn, a Washington lawyer and real estate developer, to be ambassador to Switzerland .</s>
</P>
</TEXT>
<TYPE>
<P>

<s docid="LA072689-0050" num="22" wdcount="2"> Appointment; Wire</s>
</P>
</TYPE>
<SUBJECT>
<P>

<s docid="LA072689-0050" num="23" wdcount="21"> UNITED STATES -- AMBASSADORS; POLITICAL APPOINTMENTS; POLITICAL CONTRIBUTIONS; ZAPPALA, JOSEPH; NEWMAN, DELLA; SEMBLER, MARVIN; BUSH, GEORGE; UNITED STATES -- GOVERNMENT OFFICIALS</s>
</P>
</SUBJECT>
</DOC>
