<DOC>
<DOCNO>

<s docid="WSJ920203-0038" num="1" wdcount="1"> WSJ920203-0038</s>
</DOCNO>
<DOCID>

<s docid="WSJ920203-0038" num="2" wdcount="2"> 920203-0038 .</s>
</DOCID>
<HL>

<s docid="WSJ920203-0038" num="3" wdcount="9"> Politics & Policy: U.N. Ambassador To Be Appointed U.S.</s>

<s docid="WSJ920203-0038" num="4" wdcount="15"> Envoy to India ---- By Robert S. Greenberger Staff Reporter of The Wall Street Journal</s>
</HL>
<DATE>

<s docid="WSJ920203-0038" num="5" wdcount="1"> 02/03/92</s>
</DATE>
<SO>

<s docid="WSJ920203-0038" num="6" wdcount="6"> WALL STREET JOURNAL (J), PAGE A8</s>
</SO>
<NS>

<s docid="WSJ920203-0038" num="7" wdcount="3"> UNITED NATIONS (UNN)</s>
</NS>
<GV>

<s docid="WSJ920203-0038" num="8" wdcount="5"> EXECUTIVE (EXE) STATE DEPARTMENT (STD)</s>
</GV>
<RE>

<s docid="WSJ920203-0038" num="9" wdcount="11"> FAR EAST (FE) INDIA (II) NORTH AMERICA (NME) UNITED STATES (US)</s>
</RE>
<LP>

<s docid="WSJ920203-0038" num="10" wdcount="29"> WASHINGTON -- President Bush plans to name United Nations Ambassador Thomas Pickering as U.S. envoy to India, and appoint the current head of the foreign service to succeed him.</s>

<s docid="WSJ920203-0038" num="11" wdcount="36"> The White House, according to a U.S. official, hasn't yet informed the Senate, which must confirm the nominations of Mr. Pickering and Foreign Service Director General Edward Perkins, a former U.S. envoy to South Africa .</s>
</LP>
<TEXT>

<s docid="WSJ920203-0038" num="12" wdcount="21"> With the end of the Cold War, the U.N. is playing an increasingly important role in working to resolve regional disputes.</s>

<s docid="WSJ920203-0038" num="13" wdcount="21"> It has led efforts to end civil wars in El Salvador and Cambodia, and it also helped monitor elections in Namibia.</s>

<s docid="WSJ920203-0038" num="14" wdcount="6"> Last Friday, during an unprecedented U.N.</s>

<s docid="WSJ920203-0038" num="15" wdcount="16"> Security Council meeting of heads of state, President Bush reaffirmed the U.N.'s leading role in peacemaking.</s>

<s docid="WSJ920203-0038" num="16" wdcount="9"> The assignment in India could be an important one.</s>

<s docid="WSJ920203-0038" num="17" wdcount="26"> India and its neighbor Pakistan remain embroiled in a long, bitter feud that has the potential of becoming one of the world's few remaining nuclear standoffs.</s>

<s docid="WSJ920203-0038" num="18" wdcount="10"> Mr. Pickering was one of President Bush's first ambassadorial appointments.</s>

<s docid="WSJ920203-0038" num="19" wdcount="39"> He served at the U.N. during the time the administration was involved in the delicate negotiations that led to the formation of the coalition against Iraq in the Persian Gulf War and the U.N. sanctions against Saddam Hussein's regime.</s>

<s docid="WSJ920203-0038" num="20" wdcount="14"> But some senior State Department officials have been irritated by what they call Mr.</s>

<s docid="WSJ920203-0038" num="21" wdcount="6"> Pickering's propensity for the media spotlight.</s>

<s docid="WSJ920203-0038" num="22" wdcount="31"> During the 1980s, when the Reagan administration drew the line against communist-backed insurgences in Central America, Mr. Pickering played an active role in that effort as U.S. envoy to El Salvador.</s>

<s docid="WSJ920203-0038" num="23" wdcount="28"> Mr. Perkins was the U.S. ambassador to South Africa in 1986, when the U.S. imposed economic sanctions against that nation's white-minority government to pressure it to end apartheid.</s>

<s docid="WSJ920203-0038" num="24" wdcount="32"> Mr. Perkins, who is black, traveled widely across South Africa during this period, making sure he was seen in black townships, attending church services and funerals, as well as in white communities.</s>

<s docid="WSJ920203-0038" num="25" wdcount="20"> Mr. Pickering, reached over the weekend, refused to comment on his future plans, and Mr. Perkins couldn't be reached .</s>
</TEXT>
</DOC>
