<DOC>
<DOCNO>

<s docid="AP900208-0116" num="1" wdcount="1"> AP900208-0116</s>
</DOCNO>
<FILEID>

<s docid="AP900208-0116" num="2" wdcount="2"> AP-NR-02-08-90 1331EST</s>
</FILEID>
<FIRST>

<s docid="AP900208-0116" num="3" wdcount="5"> r i AM-India-Kashmir 02-08 0581</s>
</FIRST>
<SECOND>

<s docid="AP900208-0116" num="4" wdcount="1"> AM-India-Kashmir,0598</s>
</SECOND>
<HEAD>

<s docid="AP900208-0116" num="5" wdcount="9"> Militants Kill Paramilitary Soldiers as Violence Continues in Kashmir</s>
</HEAD>
<BYLINE>

<s docid="AP900208-0116" num="6" wdcount="3"> By DILIP GANGULY</s>
</BYLINE>
<BYLINE>

<s docid="AP900208-0116" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900208-0116" num="8" wdcount="3"> SRINAGAR, India (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900208-0116" num="9" wdcount="26"> Moslem militants armed with automatic rifles shot and killed two unarmed paramilitary soldiers on Thursday in Srinagar, the flashpoint of a violent separatist campaign, officials said.</s>

<s docid="AP900208-0116" num="10" wdcount="24"> Witnesses said a cigarette vendor also was killed in the attack, which occurred outside the vendor's kiosk in the Chanpora suburb of the city.</s>

<s docid="AP900208-0116" num="11" wdcount="13"> A bystander was injured, said the witnesses, who spoke on condition of anonymity.</s>

<s docid="AP900208-0116" num="12" wdcount="32"> The deaths brought to 81 the number of people killed since Jan. 20 in clashes between security forces and Moslem militants fighting for secession of the Moslem-dominated Kashmir region from Hindu-majority India.</s>

<s docid="AP900208-0116" num="13" wdcount="19"> Most victims have been protesters shot while defying a curfew imposed Jan. 20 when government forces launched a crackdown.</s>

<s docid="AP900208-0116" num="14" wdcount="29"> A senior police official, who spoke on condition of anonymity, said militants exploded bombs in a government building and a government-run bank in Srinagar's outskirts Thursday, causing severe damage.</s>

<s docid="AP900208-0116" num="15" wdcount="4"> There were no casualties.</s>

<s docid="AP900208-0116" num="16" wdcount="16"> The official also blamed militants for a fire that broke out in a downtown shopping center.</s>

<s docid="AP900208-0116" num="17" wdcount="7"> No casualties were reported in the blaze.</s>

<s docid="AP900208-0116" num="18" wdcount="8"> Security was strengthened across Srinagar after the incidents.</s>

<s docid="AP900208-0116" num="19" wdcount="17"> New roadblocks were set up and more paramilitary troops were deployed on the streets, the official said.</s>

<s docid="AP900208-0116" num="20" wdcount="16"> Some soldiers patrolled in trucks while others perched with machine guns on the sides of roads.</s>

<s docid="AP900208-0116" num="21" wdcount="25"> A curfew that was to have begun at 6 p.m. instead took effect in the afternoon in three areas of the city after the shootings.</s>

<s docid="AP900208-0116" num="22" wdcount="41"> The two paramilitary Border Security Force officers were shot with Chinese-designed AK-47 rifles from close range as they walked from their camp toward the cigarette kiosk, 100 yards from the camp's gate, said Ashok Patel, inspector-general of the Border Security Force.</s>

<s docid="AP900208-0116" num="23" wdcount="13"> He said the men were unarmed and were not in uniform when attacked.</s>

<s docid="AP900208-0116" num="24" wdcount="12"> It was the first reported slaying by Moslem militants of paramilitary troops.</s>

<s docid="AP900208-0116" num="25" wdcount="35"> The Border Security Force, known to be a more disciplined and tougher force that the state constabulary, is normally deployed on international borders but has been increasingly used to put down the Kashmir secessionist movement.</s>

<s docid="AP900208-0116" num="26" wdcount="11"> State police began preparations to counter violence Friday, the Moslem sabbath.</s>

<s docid="AP900208-0116" num="27" wdcount="17"> On past sabbath days, speeches have been broadcast from mosques urging people to fight for Kashmir's independence.</s>

<s docid="AP900208-0116" num="28" wdcount="33"> Gov. Jagmohan, known to be a tough administrator who ordered the Jan. 20 crackdown, on Thursday appealed for peace in Kashmir, the Himalayan valley once popular for its gardens, lakes and apple orchards.</s>

<s docid="AP900208-0116" num="29" wdcount="39"> ``Let us impress once again on our young brothers to see the futility of the cult of guns and understand the magnitude of all-round misery that it has caused,'' he said in a letter released by the state government.</s>

<s docid="AP900208-0116" num="30" wdcount="31"> Jagmohan, a Hindu who uses only one name, wrote the letter to the father of a Moslem youth who was killed in a bomb explosion in a shopping complex on Wednesday.</s>

<s docid="AP900208-0116" num="31" wdcount="20"> Kashmir was divided between India and Pakistan after the two countries were partitioned on gaining independence from Britain in 1947.</s>

<s docid="AP900208-0116" num="32" wdcount="18"> Srinagar and the surrounding areas of the valley became part of Jammu-Kashmir state, India's only predominantly Moslem state.</s>

<s docid="AP900208-0116" num="33" wdcount="23"> Sixty-four percent of the state's 5 million people are Moslems, but nationwide, Moslems make up 12 percent of India's population of 880 million.</s>

<s docid="AP900208-0116" num="34" wdcount="31"> Kashmiri militants had earlier campaigned for union with Pakistan, which claims Kashmir because of its predominant Moslem population, but now they demand independence and the status of a neutral country .</s>
</TEXT>
</DOC>
