<DOC>
<DOCNO>

<s docid="AP900224-0094" num="1" wdcount="1"> AP900224-0094</s>
</DOCNO>
<FILEID>

<s docid="AP900224-0094" num="2" wdcount="2"> AP-NR-02-24-90 1452EST</s>
</FILEID>
<FIRST>

<s docid="AP900224-0094" num="3" wdcount="5"> r i AM-Kashmir 02-24 0558</s>
</FIRST>
<SECOND>

<s docid="AP900224-0094" num="4" wdcount="1"> AM-Kashmir,0579</s>
</SECOND>
<HEAD>

<s docid="AP900224-0094" num="5" wdcount="9"> Tens of Thousands March to Moslem Shrine Demanding Freedom</s>
</HEAD>
<DATELINE>

<s docid="AP900224-0094" num="6" wdcount="3"> SRINAGAR, India (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900224-0094" num="7" wdcount="7"> Tens of thousands of people chanting ``Freedom!</s>

<s docid="AP900224-0094" num="8" wdcount="22"> Freedom''! trekked to a Moslem saint's shrine Saturday to campaign for the secession of Kashmir from India, witnesses and pro-separatist activists said.</s>

<s docid="AP900224-0094" num="9" wdcount="22"> At least three people died in two separate incidents on Saturday in Kashmir, the center of the four-decade-old separatist campaign, witnesses said.</s>

<s docid="AP900224-0094" num="10" wdcount="25"> The deaths brought to 109 the number of people killed since Jan. 20 in the latest round of the secessionist violence and the government crackdown.</s>

<s docid="AP900224-0094" num="11" wdcount="32"> Meanwhile, the president of the Pakistan state of Kashmir said in an interview Saturday that Kashmiris there had begun smuggling arms across the border to Moslem insurgents fighting for independence from India.</s>

<s docid="AP900224-0094" num="12" wdcount="36"> President Abdul Qayyum, speaking to a reporter who traveled to Pakistan's Kashmir, said the people of his state also had been sheltering insurgents since India launched the military crackdown in its state of Jammu-Kashmir last month.</s>

<s docid="AP900224-0094" num="13" wdcount="36"> In India's Kashmir, the 600-year-old shrine of Shiekh Nuruddin Wali at Charift Sharief, 20 miles northwest of Srinagar, became a sea of humanity as Moslem men, women and children poured in from Srinagar and nearby towns.</s>

<s docid="AP900224-0094" num="14" wdcount="20"> Vehicles stopped 10 miles from the shrine as people thronged the roads, said witnesses, who spoke on condition of anonymity.</s>

<s docid="AP900224-0094" num="15" wdcount="20"> Supporters of the militants said they went to the shrine to seek the saint's blessings to ``liberate'' Kashmir from India.</s>

<s docid="AP900224-0094" num="16" wdcount="29"> In Srinagar, the summer capital of Jammu-Kashmir state, residents were told by Moslem militants to put their clocks back by 30 minutes to correspond with the Pakistan standard time.</s>

<s docid="AP900224-0094" num="17" wdcount="21"> The militants, led by the Jammu-Kashmir Liberation Front, are demanding either independence for Jammu-Kashmir, the only Indian state dominated by Moslems.</s>

<s docid="AP900224-0094" num="18" wdcount="18"> Groups of young Moslem men sat at street corners, stopping passers-by and telling them to adjust their watches.</s>

<s docid="AP900224-0094" num="19" wdcount="19"> At least six fights broke out when people refused to comply, said witnesses who spoke on condition of anonymity.</s>

<s docid="AP900224-0094" num="20" wdcount="26"> On Friday, at least 200,000 people marched to the office of the United Nations Military Observers Group in Srinagar, demanding a plebiscite in Kashmir, police said.</s>

<s docid="AP900224-0094" num="21" wdcount="9"> Witnesses claimed that more than 600,000 people took part.</s>

<s docid="AP900224-0094" num="22" wdcount="23"> The U.N. group is posted to maintain a cease-fire line drawn between Indian- and Pakistani-held Kashmir after a 1948-49 war over the region.</s>

<s docid="AP900224-0094" num="23" wdcount="23"> Residents, speaking on condition of anonymity, said security forces fatally shot two men shouting anti-Indian slogans at Khrew, 15 miles southeast of Srinagar.</s>

<s docid="AP900224-0094" num="24" wdcount="22"> In Srinagar, suspected Moslem militants shot and killed Ashok Kumar, a Hindu government employee, witnesses said, also speaking on condition of anonymity.</s>

<s docid="AP900224-0094" num="25" wdcount="8"> Kumar was suspected to be a police informer.</s>

<s docid="AP900224-0094" num="26" wdcount="11"> India routinely accuses Pakistan of arming, training and supporting the militants.</s>

<s docid="AP900224-0094" num="27" wdcount="17"> The government in Islamabad denies the charge but says the Kashmiri people have a right to self-determination.</s>

<s docid="AP900224-0094" num="28" wdcount="23"> An AP reporter who traveled to Pakistan's Kashmir last week said state-run banks in the region have begun collections to help the uprising.</s>

<s docid="AP900224-0094" num="29" wdcount="14"> Signs in dozens of banks called for donations for ``a holy war against India''.</s>

<s docid="AP900224-0094" num="30" wdcount="37"> Naveed Hussain, a government spokesman in Pakistan's Kashmir, said in an interview that $5,000 had been raised in a week and that the money would be used to train Kashmiri militia groups in territory held by Pakistan.</s>

<s docid="AP900224-0094" num="31" wdcount="23"> Kashmir was divided between India and Pakistan after the two countries were partitioned following the end of British colonial rule in 1947 .</s>
</TEXT>
</DOC>
