<DOC>
<DOCNO>

<s docid="AP900821-0092" num="1" wdcount="1"> AP900821-0092</s>
</DOCNO>
<FILEID>

<s docid="AP900821-0092" num="2" wdcount="2"> AP-NR-08-21-90 1348EST</s>
</FILEID>
<FIRST>

<s docid="AP900821-0092" num="3" wdcount="5"> r i AM-India-Pakistan 08-21 0479</s>
</FIRST>
<SECOND>

<s docid="AP900821-0092" num="4" wdcount="1"> AM-India-Pakistan,0497</s>
</SECOND>
<HEAD>

<s docid="AP900821-0092" num="5" wdcount="6"> Border Clashes Continuning, Says Prime Minister</s>
</HEAD>
<BYLINE>

<s docid="AP900821-0092" num="6" wdcount="3"> By DILIP GANGULY</s>
</BYLINE>
<BYLINE>

<s docid="AP900821-0092" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900821-0092" num="8" wdcount="4"> NEW DELHI, India (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900821-0092" num="9" wdcount="28"> The army on Tuesday dispatched tanks and troop reinforcements to the frontier with Pakistan, where soldiers from the two nations have been fighting recently, officials and witnesses said.</s>

<s docid="AP900821-0092" num="10" wdcount="19"> Prime Minister V.P. Singh told Parliament that Indian armed forces were ``fully prepared to effectively deal with any eventuality''.</s>

<s docid="AP900821-0092" num="11" wdcount="16"> Indian and Pakistani troops clashed in a remote border area in the disputed Kashmir region Monday.</s>

<s docid="AP900821-0092" num="12" wdcount="13"> Singh, who is also defense minister, said exchange of fire also occurred Tuesday.</s>

<s docid="AP900821-0092" num="13" wdcount="38"> In Pakistan, a Defense Ministry spokesman, who cannot be identified under briefing rules, said Tuesday that Indian and Pakistani soldiers exchanged artillery fire in the Kel sector along the cease-fire line dividing Kashmir into Pakistani and Indian regions.</s>

<s docid="AP900821-0092" num="14" wdcount="9"> He said there were no casualties among Pakistani soldiers.</s>

<s docid="AP900821-0092" num="15" wdcount="24"> The Pakistani official also said that on Monday and Tuesday, Indian soldiers fired on Pakistani civilians traveling on a mountain road, injuring four people.</s>

<s docid="AP900821-0092" num="16" wdcount="12"> He also said Indian soldiers fired on an ambulance and a bus.</s>

<s docid="AP900821-0092" num="17" wdcount="10"> There was no report from India on the alleged firing.</s>

<s docid="AP900821-0092" num="18" wdcount="16"> Despite the tension, officials from both sides said the incidents did not appear to be serious.</s>

<s docid="AP900821-0092" num="19" wdcount="33"> ``There is no cause for any undue concern since we trust that these localized incidents will be contained and the situation defused,'' United News of India quoted Singh as saying in the Parliament.</s>

<s docid="AP900821-0092" num="20" wdcount="12"> Singh said directors of military operations from both countries were in touch.</s>

<s docid="AP900821-0092" num="21" wdcount="4"> He did not elaborate.</s>

<s docid="AP900821-0092" num="22" wdcount="10"> The Pakistani official said: ``This is not a serious situation.</s>

<s docid="AP900821-0092" num="23" wdcount="5"> It's just in one sector.</s>

<s docid="AP900821-0092" num="24" wdcount="7"> It could be just a local incident.</s>

<s docid="AP900821-0092" num="25" wdcount="8"> We don't know what it will lead to.</s>

<s docid="AP900821-0092" num="26" wdcount="7"> We'll just have to wait and see''.</s>

<s docid="AP900821-0092" num="27" wdcount="14"> India and Pakistan have gone to war twice over Kashmir, in 1965 and 1971.</s>

<s docid="AP900821-0092" num="28" wdcount="13"> Both sides claim Kashmir, which has been divided into Indian and Pakistani sectors.</s>

<s docid="AP900821-0092" num="29" wdcount="7"> Tensions over Kashmir flared again this summer.</s>

<s docid="AP900821-0092" num="30" wdcount="21"> India accuses Pakistan of supporting a Moslem secessionist movement in the Indian sector by providing arms and training to Moslem militants.</s>

<s docid="AP900821-0092" num="31" wdcount="19"> Pakistan, an Islamic state, denies the charge but says it will back any movement for self-determination by Kashmir's people.</s>

<s docid="AP900821-0092" num="32" wdcount="13"> Jammu-Kashmir state is the only one of India's states with a Moslem majority.</s>

<s docid="AP900821-0092" num="33" wdcount="23"> At least 1,034 people have been killed in the Kashmir valley since New Delhi cracked down on the secessionist movement on Jan. 20.</s>

<s docid="AP900821-0092" num="34" wdcount="23"> Military officials in Jammu, the summer capital of India-held Kashmir, said Tuesday that tanks and troops reinforcements were dispatched to the border areas.</s>

<s docid="AP900821-0092" num="35" wdcount="27"> At least 20 tanks and 30 trucks with soldiers left their quarters at Kaluchak and Baridrahamna for the frontier, said witnesses, who spoke on condition of anonymity.</s>

<s docid="AP900821-0092" num="36" wdcount="29"> Indian military officials said the additional troops were sent to Rajauri and Poonch sectors, which were the scenes of fierce battles in the wars of 1965 and 1971 .</s>
</TEXT>
</DOC>
