<DOC>
<DOCNO>

<s docid="AP900718-0069" num="1" wdcount="1"> AP900718-0069</s>
</DOCNO>
<FILEID>

<s docid="AP900718-0069" num="2" wdcount="2"> AP-NR-07-18-90 0944EDT</s>
</FILEID>
<FIRST>

<s docid="AP900718-0069" num="3" wdcount="5"> r i PM-India-Kashmir 07-18 0405</s>
</FIRST>
<SECOND>

<s docid="AP900718-0069" num="4" wdcount="1"> PM-India-Kashmir,0416</s>
</SECOND>
<HEAD>

<s docid="AP900718-0069" num="5" wdcount="6"> India Imposes Direct Rule in Kashmir</s>
</HEAD>
<BYLINE>

<s docid="AP900718-0069" num="6" wdcount="3"> By DILIP GANGULY</s>
</BYLINE>
<BYLINE>

<s docid="AP900718-0069" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900718-0069" num="8" wdcount="4"> NEW DELHI, India (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900718-0069" num="9" wdcount="23"> The government today imposed direct federal rule in Kashmir, where Indian security forces are battling to put down a rebellion by Moslem separatists.</s>

<s docid="AP900718-0069" num="10" wdcount="16"> The action follows the killing Tuesday of at least 29 Moslem militants by Indian security forces.</s>

<s docid="AP900718-0069" num="11" wdcount="26"> In the Pakistani capital of Islamabad, meanwhile, India and Pakistan opened negotiations today aimed at repairing relations threatened by the rebellion in the disputed northern region.</s>

<s docid="AP900718-0069" num="12" wdcount="28"> Relations between Pakistan and India worsened in January when Indian soldiers cracked down on Moslem militants in Kashmir who are seeking independence from India or union with Pakistan.</s>

<s docid="AP900718-0069" num="13" wdcount="11"> At least 792 people have been killed in Kashmir since then.</s>

<s docid="AP900718-0069" num="14" wdcount="15"> India has accused Pakistan of arming and training the militants, a charge Pakistan has denied.</s>

<s docid="AP900718-0069" num="15" wdcount="23"> Before direct federal rule was imposed today on Jammu-Kashmir state, it was administered temporarily by a governor, a federal representative, since Jan. 18.</s>

<s docid="AP900718-0069" num="16" wdcount="22"> The announcement of federal rule reflected the belief that Jammu-Kashmir state was too unstable to be run by an elected local government.</s>

<s docid="AP900718-0069" num="17" wdcount="28"> On Tuesday, at least 29 militants were killed by Indian security forces in Kashmir, the Moslem-dominated northern part of Jammu-Kashmir state and the center of the secessionist campaign.</s>

<s docid="AP900718-0069" num="18" wdcount="29"> Officials, who cannot be identified under briefing rules, said 21 militants were killed in a battle with the Border Security Force in Poonch, 400 miles northwest of New Delhi.</s>

<s docid="AP900718-0069" num="19" wdcount="20"> Hours later in the same area, troops killed eight militants who slipped across the border from Pakistan, said the officials.</s>

<s docid="AP900718-0069" num="20" wdcount="21"> The guards also arrested four militants and seized 14 automatic rifles, two machine guns and two rocket launchers, the officials said.</s>

<s docid="AP900718-0069" num="21" wdcount="24"> Indian officials maintain that Kashmiri militants regularly cross over to Pakistan through the border and return by the same route after reciving arms training.</s>

<s docid="AP900718-0069" num="22" wdcount="18"> Pakistan denies it is training or helping the militants, but calls the separatist struggle a fight for self-determination.</s>

<s docid="AP900718-0069" num="23" wdcount="14"> India and Pakistan have fought two previous wars over Kashmir, in 1948 and 1965.</s>

<s docid="AP900718-0069" num="24" wdcount="5"> Both were won by India.</s>

<s docid="AP900718-0069" num="25" wdcount="17"> About 65 percent of Jammu-Kashmir's 6 million people are Moslems, making it India's only Moslem majority state.</s>

<s docid="AP900718-0069" num="26" wdcount="11"> Nationwide, Moslems make up 12 percent of India's 880 million people.</s>

<s docid="AP900718-0069" num="27" wdcount="8"> Hindus make up 82 percent of the population.</s>

<s docid="AP900718-0069" num="28" wdcount="27"> Kashmiri separatists earlier demanded union with Pakistan, an Islamic country, but they have recently been fighting for total independence and the status of a neutral country .</s>
</TEXT>
</DOC>
