<DOC>
<DOCNO>

<s docid="AP900524-0130" num="1" wdcount="1"> AP900524-0130</s>
</DOCNO>
<FILEID>

<s docid="AP900524-0130" num="2" wdcount="2"> AP-NR-05-24-90 1646EDT</s>
</FILEID>
<FIRST>

<s docid="AP900524-0130" num="3" wdcount="5"> u i AM-Kashmir 05-24 0393</s>
</FIRST>
<SECOND>

<s docid="AP900524-0130" num="4" wdcount="1"> AM-Kashmir,0409</s>
</SECOND>
<HEAD>

<s docid="AP900524-0130" num="5" wdcount="7"> Pakistan's Leader Accuses India of Kashmir Genocide</s>
</HEAD>
<BYLINE>

<s docid="AP900524-0130" num="6" wdcount="3"> By SHARON HERBAUGH</s>
</BYLINE>
<BYLINE>

<s docid="AP900524-0130" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900524-0130" num="8" wdcount="3"> ISLAMABAD, Pakistan (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900524-0130" num="9" wdcount="26"> Prime Minister Benazir Bhutto on Thursday accused India of waging ``genocide'' in secession-minded Kashmir and of trying to start a war with Pakistan to deflect attention.</s>

<s docid="AP900524-0130" num="10" wdcount="16"> Her remarks raised tensions further between India and Pakistan, which have been feuding over Indian-controlled Kashmir.</s>

<s docid="AP900524-0130" num="11" wdcount="28"> The two countries, which have fought wars over the area in 1949 and 1965, have in recent weeks again built up their military forces near the common border.</s>

<s docid="AP900524-0130" num="12" wdcount="30"> ``India is indulging in genocide,'' Ms. Bhutto said at a news conference Thursday after returning from a weeklong tour of eight Moslem countries in the Middle East and North Africa.</s>

<s docid="AP900524-0130" num="13" wdcount="11"> ``Islamic scholars are being killed and innocent people are being slaughtered.</s>

<s docid="AP900524-0130" num="14" wdcount="7"> This is deplorable,'' said the prime minister.</s>

<s docid="AP900524-0130" num="15" wdcount="17"> She was referring to the assassination of Maulvi Mohammad Farooq, the top Moslem cleric in Indian Kashmir.</s>

<s docid="AP900524-0130" num="16" wdcount="12"> During his funeral procession Monday, Indian forces shot to death 58 people.</s>

<s docid="AP900524-0130" num="17" wdcount="33"> Ms. Bhutto returned late Wednesday from visits to Iran, Turkey, Syria, Jordan, North Yemen, Egypt, Libya and Tunisia, a high-profile diplomatic offensive to drum up support for Pakistan's stand on the Kashmir issue.</s>

<s docid="AP900524-0130" num="18" wdcount="22"> Hindu-dominated India accuses Pakistan of arming and training Kashmiri militants fighting for secession of Jammu-Kashmir, India's only state with a Moslem majority.</s>

<s docid="AP900524-0130" num="19" wdcount="10"> Pakistan, which is dominated by Moslems, denies the Indian charge.</s>

<s docid="AP900524-0130" num="20" wdcount="20"> Since the Indian government ordered a crackdown on the militants in late January, more than 400 people have been killed.</s>

<s docid="AP900524-0130" num="21" wdcount="27"> During her trip abroad, Ms. Bhutto said all her host countries agreed that India and Pakistan needed to find a lasting political settlement of the 43-year-old dispute.</s>

<s docid="AP900524-0130" num="22" wdcount="18"> However, she added, ``If subjected to aggression, we would have the full support of the Arab Islamic nations.</s>

<s docid="AP900524-0130" num="23" wdcount="9"> Pakistan, I was assured, would never be left alone''.</s>

<s docid="AP900524-0130" num="24" wdcount="10"> ``We believe the threats to peace are grave,'' she said.</s>

<s docid="AP900524-0130" num="25" wdcount="21"> ``We cannot rule out the possibility of an armed conflict, but we do not believe war is inevitable,'' she told reporters.</s>

<s docid="AP900524-0130" num="26" wdcount="8"> Ms. Bhutto said she opposes an independent Kashmir.</s>

<s docid="AP900524-0130" num="27" wdcount="16"> She said it was not envisioned when India and Pakistan gained independence in a 1947 partition.</s>

<s docid="AP900524-0130" num="28" wdcount="11"> The prime minister again called for talks between Pakistan and India.</s>

<s docid="AP900524-0130" num="29" wdcount="15"> She also said a neutral body should look into the charges made by both sides.</s>

<s docid="AP900524-0130" num="30" wdcount="7"> India has already rejected both suggestions .</s>
</TEXT>
</DOC>
