<DOC>
<DOCNO>

<s docid="AP900724-0090" num="1" wdcount="1"> AP900724-0090</s>
</DOCNO>
<FILEID>

<s docid="AP900724-0090" num="2" wdcount="2"> AP-NR-07-24-90 1204EDT</s>
</FILEID>
<FIRST>

<s docid="AP900724-0090" num="3" wdcount="5"> r i PM-India-Kashmir 07-24 0310</s>
</FIRST>
<SECOND>

<s docid="AP900724-0090" num="4" wdcount="1"> PM-India-Kashmir,0322</s>
</SECOND>
<HEAD>

<s docid="AP900724-0090" num="5" wdcount="8"> Indian Guards Kill 20 Moslem Militants in Kashmir</s>
</HEAD>
<DATELINE>

<s docid="AP900724-0090" num="6" wdcount="3"> SRINAGAR, India (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900724-0090" num="7" wdcount="26"> Indian frontier guards shot and killed 20 Moslem militants and arrested nine others after they sneaked into India-held Kashmir from Pakistan, a senior official said today.</s>

<s docid="AP900724-0090" num="8" wdcount="30"> The militants were killed late Monday at Kupwara, 56 miles north of Srinagar during gunbattle with Indian guards, said the Kashmir official, who cannot be identified under standing briefing regulations.</s>

<s docid="AP900724-0090" num="9" wdcount="24"> India, alarmed by a spurt in Moslem separatist activities in Kashmir, has stepped up border patrol to stop alleged infiltration of separatists from Pakistan.</s>

<s docid="AP900724-0090" num="10" wdcount="15"> A total of 80 Moslem militants have died in frontier incidents in the past week.</s>

<s docid="AP900724-0090" num="11" wdcount="27"> Indian officials maintain that Kashmiri militants regularly cross over to Pakistan through the porous border and return by the same route after reciving arms training in Pakistan.</s>

<s docid="AP900724-0090" num="12" wdcount="22"> Pakistan denies it is training or helping the militants, but says it supports the separatism, terming it a fight for self determination.</s>

<s docid="AP900724-0090" num="13" wdcount="20"> The Kashmir official said the fighting erupted when the militants fired at Indian border guards after crossing over from Pakistan.</s>

<s docid="AP900724-0090" num="14" wdcount="14"> Indian guards seized 22 AK-47 rifles, three machine guns and 1,425 rounds of ammunitions.</s>

<s docid="AP900724-0090" num="15" wdcount="16"> Kashmiri separatists are fighting for independence of the Moslem dominated Jammu-Kashmir from the predominantly Hindu India.</s>

<s docid="AP900724-0090" num="16" wdcount="15"> At least five more Moslem separatists were killed in three separate incidents across Kashmir today.</s>

<s docid="AP900724-0090" num="17" wdcount="25"> The deaths brought the total number of people killed to at least 863 since Jan. 20, when the government launched a crackdown on the separatists.</s>

<s docid="AP900724-0090" num="18" wdcount="17"> About 65 percent of Jammu-Kashmir's 6 million people are Moslems, making it India's only Moslem majority state.</s>

<s docid="AP900724-0090" num="19" wdcount="11"> Nationwide, Moslems make up 12 percent of India's 880 million people.</s>

<s docid="AP900724-0090" num="20" wdcount="8"> Hindus make up 82 percent of the population.</s>

<s docid="AP900724-0090" num="21" wdcount="26"> Kashmiri separatists earlier demanded union with Pakistan, an Islamic country, but have recently been fighting for total independence and the status of a neutral country .</s>
</TEXT>
</DOC>
