<DOC>
<DOCNO>

<s docid="AP900330-0086" num="1" wdcount="1"> AP900330-0086</s>
</DOCNO>
<FILEID>

<s docid="AP900330-0086" num="2" wdcount="2"> AP-NR-03-30-90 1236EST</s>
</FILEID>
<FIRST>

<s docid="AP900330-0086" num="3" wdcount="5"> r i AM-India-Kashmir 03-30 0476</s>
</FIRST>
<SECOND>

<s docid="AP900330-0086" num="4" wdcount="1"> AM-India-Kashmir,0499</s>
</SECOND>
<HEAD>

<s docid="AP900330-0086" num="5" wdcount="10"> Moslems Mourn Slain Militant Leader, Vow to Continue Secession Fight</s>
</HEAD>
<DATELINE>

<s docid="AP900330-0086" num="6" wdcount="3"> SRINAGAR, India (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900330-0086" num="7" wdcount="28"> A leader of the Moslem separatist movement in Kashmir tried to hurl a grenade into a police bunker Friday but was killed in a volley of police gunfire.</s>

<s docid="AP900330-0086" num="8" wdcount="10"> Tens of thousands of Moslems gathered later for the funeral.</s>

<s docid="AP900330-0086" num="9" wdcount="16"> Comrades fired into the air and vowed to carry on the fight for independence from India.</s>

<s docid="AP900330-0086" num="10" wdcount="16"> Ashfaq Majid Wani, 28, was a leader of the Jammu-Kashmir Liberation Front, a leading separatist group.</s>

<s docid="AP900330-0086" num="11" wdcount="8"> He was the front's area commander in Srinagar.</s>

<s docid="AP900330-0086" num="12" wdcount="22"> Police said he tried to throw the grenade at a police bunker in downtown Srinagar while riding by on a motor scooter.</s>

<s docid="AP900330-0086" num="13" wdcount="11"> The grenade went off after officers opened fire with automatic weapons.</s>

<s docid="AP900330-0086" num="14" wdcount="10"> Three other people died in the melee, the police said.</s>

<s docid="AP900330-0086" num="15" wdcount="23"> Hours later, thousands of residents gathered near Wani's house in an attempt to hold a funeral procession in defiance of a government curfew.</s>

<s docid="AP900330-0086" num="16" wdcount="24"> But soldiers and police prevented the procession and took Wani's body to a burial ground in a government ambulance escorted by a police jeep.</s>

<s docid="AP900330-0086" num="17" wdcount="20"> Women wailed and beat their chest as Wani's body was taken out of the ambulance and placed near the grave.</s>

<s docid="AP900330-0086" num="18" wdcount="18"> Men shouted: ``Ashfaq's blood will usher independence''! A group militants fired pistols and automatic rifles in the air.</s>

<s docid="AP900330-0086" num="19" wdcount="6"> Witnesses estimated the crowd at 40,000.</s>

<s docid="AP900330-0086" num="20" wdcount="17"> The firing continued intermittently for more than one hour until the body wa interred at 5 p.m.</s>

<s docid="AP900330-0086" num="21" wdcount="20"> ``We will carry forward Asfaq's mission, which was to gain independence,'' said one militant leader holding a Soviet-designed Kalashnikov rifle.</s>

<s docid="AP900330-0086" num="22" wdcount="6"> He refused to give his name.</s>

<s docid="AP900330-0086" num="23" wdcount="36"> The secessionist movement has been alternately simmering and flaring since 1948, when the Hindu ruler of the old princely state of Kashmir, faced with the option of merging either with India or Islamic Pakistan, chose India.</s>

<s docid="AP900330-0086" num="24" wdcount="16"> The two countries then were one year old, having been partitioned from the British colonial India.</s>

<s docid="AP900330-0086" num="25" wdcount="9"> India and Pakistan have fought two wars over Kashmir.</s>

<s docid="AP900330-0086" num="26" wdcount="20"> They left the region split into the Pakistan-held territory called Azad Kashmir, or free Kashmir, and the Indian-controlled Jammu-Kashmir state.</s>

<s docid="AP900330-0086" num="27" wdcount="12"> Jammu-Kashmir is the only state in India that is dominated by Moslems.</s>

<s docid="AP900330-0086" num="28" wdcount="8"> Most of India's 880 million people are Hindu.</s>

<s docid="AP900330-0086" num="29" wdcount="24"> At least 233 people have been killed in Kashmir since Jan. 20 when the government launched a crackdown on increasing violence by Moslem separatists.</s>

<s docid="AP900330-0086" num="30" wdcount="22"> Official sources said Indian soldiers shot and killed 10 Moslem separatists Friday who were trying to slip into Pakistani-held territory of Kashmir.</s>

<s docid="AP900330-0086" num="31" wdcount="15"> They said the men were in a group 22 that opened fire on the soldiers.</s>

<s docid="AP900330-0086" num="32" wdcount="15"> The 12 surviving militants were arrested, said the sources, who spoke on condition of anonymity.</s>

<s docid="AP900330-0086" num="33" wdcount="10"> Also Friday, police fatally shot a curfew violated in Srinagar.</s>

<s docid="AP900330-0086" num="34" wdcount="18"> The body of a suspected police informer was found in Srinagar, and officials said militants claimed responsibility .</s>
</TEXT>
</DOC>
