<DOC>
<DOCNO>

<s docid="AP900212-0061" num="1" wdcount="1"> AP900212-0061</s>
</DOCNO>
<FILEID>

<s docid="AP900212-0061" num="2" wdcount="2"> AP-NR-02-12-90 0917EST</s>
</FILEID>
<FIRST>

<s docid="AP900212-0061" num="3" wdcount="7"> u i PM-Kashmir 1stLd-Writethru a0484 02-12 0661</s>
</FIRST>
<SECOND>

<s docid="AP900212-0061" num="4" wdcount="6"> PM-Kashmir, 1st Ld - Writethru, a0484,0680</s>
</SECOND>
<HEAD>

<s docid="AP900212-0061" num="5" wdcount="2"> Precede ISLAMABAD</s>
</HEAD>
<HEAD>

<s docid="AP900212-0061" num="6" wdcount="9"> Pakistani Troops Said To Fire On Indian Security Forces</s>
</HEAD>
<NOTE>

<s docid="AP900212-0061" num="7" wdcount="15"> Eds: LEADS thruout to UPDATE with Indian claim that Pakistanis fired on Indian troops, details.</s>

<s docid="AP900212-0061" num="8" wdcount="2"> Changes byline.</s>

<s docid="AP900212-0061" num="9" wdcount="3"> No pickup .</s>
</NOTE>
<BYLINE>

<s docid="AP900212-0061" num="10" wdcount="3"> By VIJAY JOSHI</s>
</BYLINE>
<BYLINE>

<s docid="AP900212-0061" num="11" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900212-0061" num="12" wdcount="4"> NEW DELHI, India (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900212-0061" num="13" wdcount="25"> Pakistani troops fired on Indian security forces who stopped a mob of Pakistani protesters from storming across the border into disputed Kashmir, officials said today.</s>

<s docid="AP900212-0061" num="14" wdcount="15"> At least three demonstrators were killed Sunday night, a Defense Ministry spokesman said in Islamabad.</s>

<s docid="AP900212-0061" num="15" wdcount="12"> Pakistan's state-run TV said the Indian guards killed as many as six.</s>

<s docid="AP900212-0061" num="16" wdcount="27"> The trouble started after Indian border guards opened fire on hundreds of Pakistanis who tried to cross a cease-fire line separating Pakistan-controlled Kashmir from the Indian-held region.</s>

<s docid="AP900212-0061" num="17" wdcount="28"> A spokesman for the Indian Defense Ministry said Pakistani troops then fired about 200 rounds from light and medium weapons at Indian border posts in the Uri sector.</s>

<s docid="AP900212-0061" num="18" wdcount="16"> Indian forces returned fire and the exchange continued for about half an hour, the spokesman said.</s>

<s docid="AP900212-0061" num="19" wdcount="4"> No one was hurt.</s>

<s docid="AP900212-0061" num="20" wdcount="8"> A Pakistani official in Islamabad denied the accusations.</s>

<s docid="AP900212-0061" num="21" wdcount="25"> ``Pakistani military authorities and the Foreign Secretary are in touch with Indian authorities to remove the misunderstanding,'' said Additional Foreign Secretary Khalid Mahmood in Islamabad.</s>

<s docid="AP900212-0061" num="22" wdcount="31"> Pakistan's top diplomat in New Delhi, Bashir Babar, was summoned to India's Foreign Ministry on Sunday and today and apprised of India's concern over the events, an Indian government spokesman said.</s>

<s docid="AP900212-0061" num="23" wdcount="11"> A fluid 840-mile cease-fire line separates the Indian and Pakistani Kashmirs.</s>

<s docid="AP900212-0061" num="24" wdcount="16"> Pakistan and Indian twice have gone to war over Kashmir, in 1948 and again in 1965.</s>

<s docid="AP900212-0061" num="25" wdcount="28"> On Feb. 5, at least one person was killed and 12 wounded when Pakistani mobs tried to cross the cease-fire line near Jammu, 95 miles to the south.</s>

<s docid="AP900212-0061" num="26" wdcount="28"> The two demonstrations at the cease-fire line were to express support for Moslem militants who are fighting for independence for the Moslem-dominated state from the predominantly Hindu India.</s>

<s docid="AP900212-0061" num="27" wdcount="25"> On Sunday, the Pakistani mob retreated when soldiers of India's paramilitary border security force opened fire, said the Indian spokesman who refused to be identified.</s>

<s docid="AP900212-0061" num="28" wdcount="16"> ``The mob returned a second time by which time it had become slightly dark,'' he said.</s>

<s docid="AP900212-0061" num="29" wdcount="8"> ``That is when the Pakistani troops opened fire''.</s>

<s docid="AP900212-0061" num="30" wdcount="20"> A Pakistani spokesman, who also refused to be identified, said Pakistani army patrols repulsed a mob of some 1,200 demonstrators.</s>

<s docid="AP900212-0061" num="31" wdcount="15"> Small groups broke away from the crowd and slipped into the Indian-held territory, he said.</s>

<s docid="AP900212-0061" num="32" wdcount="24"> An official of the Indian border security force, which normally patrols the border, said the Indian army today took control of the cease-fire line.</s>

<s docid="AP900212-0061" num="33" wdcount="16"> Some men in the intruding crowd were armed with guns which they fired occasionally, he said.</s>

<s docid="AP900212-0061" num="34" wdcount="13"> ``It was becoming very difficult, our troops had to open fire,'' he said.</s>

<s docid="AP900212-0061" num="35" wdcount="27"> Farouk Haider, vice-president of the militant Jammu-Kashmir Liberation Front that is leading the uprising, said in Islamabad after the Indian firing that ``the situation is very confusing''.</s>

<s docid="AP900212-0061" num="36" wdcount="9"> Thirty-one people were wounded in the shooting, Haider said.</s>

<s docid="AP900212-0061" num="37" wdcount="24"> Five were in critical condition in a hospital in Muzzafarabad, the capital of Pakistan-controlled Kashmir, he said, adding he knew of only one death.</s>

<s docid="AP900212-0061" num="38" wdcount="19"> The 40-year-old conflict over Kashmir flared Jan. 20 after a government crackdown and the arrest of 250 suspected militants.</s>

<s docid="AP900212-0061" num="39" wdcount="12"> Most of them were subsequently released, but the arrests sparked widespread violence.</s>

<s docid="AP900212-0061" num="40" wdcount="11"> At least 85 people have been killed since the crackdown began.</s>

<s docid="AP900212-0061" num="41" wdcount="14"> Most of the victims have been curfew-breaking protesters shot by security forces in Srinagar.</s>

<s docid="AP900212-0061" num="42" wdcount="21"> Srinagar, the summer capital of Jammu-Kashmir, has been the center of the secessionist movement that has turned violent in recent years.</s>

<s docid="AP900212-0061" num="43" wdcount="26"> The Jammu-Kashmir Liberation Front had earlier campaigned for union with Islamic Pakistan but has in recent years demanded independence and the status of a neutral country.</s>

<s docid="AP900212-0061" num="44" wdcount="23"> About 64 percent of Jammu-Kashmir's 6 million people are Moslems, making it the only Moslem majority state in predominantly Hindu India's 25 states.</s>

<s docid="AP900212-0061" num="45" wdcount="11"> Nationwide, Moslems make up 12 percent of India's 880 million population.</s>

<s docid="AP900212-0061" num="46" wdcount="5"> Hindus comprise 82 percent .</s>
</TEXT>
</DOC>
