<DOC>
<DOCNO>

<s docid="AP900406-0164" num="1" wdcount="1"> AP900406-0164</s>
</DOCNO>
<FILEID>

<s docid="AP900406-0164" num="2" wdcount="2"> AP-NR-04-06-90 2036EDT</s>
</FILEID>
<FIRST>

<s docid="AP900406-0164" num="3" wdcount="5"> u i AM-India-Kashmir 04-06 0286</s>
</FIRST>
<SECOND>

<s docid="AP900406-0164" num="4" wdcount="1"> AM-India-Kashmir,0295</s>
</SECOND>
<HEAD>

<s docid="AP900406-0164" num="5" wdcount="8"> Educator, Businessman Kidnapped in Kashmir, Six Militants Killed</s>
</HEAD>
<BYLINE>

<s docid="AP900406-0164" num="6" wdcount="3"> By QAISER MIRZA</s>
</BYLINE>
<BYLINE>

<s docid="AP900406-0164" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900406-0164" num="8" wdcount="3"> SRINAGAR, India (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900406-0164" num="9" wdcount="31"> Moslem extremists abducted a leading businessman and an educator Friday and threatened to kill them, a day after authorities killed six militants crossing into Pakistan for arms and training, police said.</s>

<s docid="AP900406-0164" num="10" wdcount="31"> Roads were blocked around Srinagar, where the hostages were seized, and soldiers tightened security around the Kashmir Valley, where the government launched a crackdown Jan. 20 on the Moslem separatist movement.</s>

<s docid="AP900406-0164" num="11" wdcount="35"> A telephone caller told a local reporter the abductors were also holding a third hostage and all three men would be killed within 24 hours of a Monday afternoon deadline for releasing three jailed militants.</s>

<s docid="AP900406-0164" num="12" wdcount="25"> The caller claimed to speak for the Students Liberation Front, a branch of the Jammu-Kashmir Liberation Front fighting for autonomy in the predominantly Moslem state.</s>

<s docid="AP900406-0164" num="13" wdcount="5"> India itself is overwhelmingly Hindu.</s>

<s docid="AP900406-0164" num="14" wdcount="33"> Police sources, who demanded anonymity, and the telephone caller both identified the new kidnap victims as Vice Chancellor Mushir ul-Haq of Kashmir University and L.M. Khela, general manager of Hindustan Machine Tools Co.</s>

<s docid="AP900406-0164" num="15" wdcount="17"> The caller said ul-Haq's private secretary also was being held hostage, but that could not be confirmed.</s>

<s docid="AP900406-0164" num="16" wdcount="17"> Moslem separatists had warned Indian government officials to leave Jammu-Kashmir state before April or ``face the consequences''.</s>

<s docid="AP900406-0164" num="17" wdcount="28"> Police said the border violence took place in Kupwara district, where at least 20 separatists tried to sneak into neighboring Pakistan to receive military training and buy weapons.</s>

<s docid="AP900406-0164" num="18" wdcount="4"> No details were available.</s>

<s docid="AP900406-0164" num="19" wdcount="17"> India says Pakistan trains and arms the militants in Kashmir, at the far northern tip of India.</s>

<s docid="AP900406-0164" num="20" wdcount="3"> Pakistan denies it.</s>

<s docid="AP900406-0164" num="21" wdcount="20"> India and Pakistan have fought two wars over the region since 1947, when both nations won independence from Britain .</s>
</TEXT>
</DOC>
