<DOC>
<DOCNO>

<s docid="AP900130-0010" num="1" wdcount="1"> AP900130-0010</s>
</DOCNO>
<FILEID>

<s docid="AP900130-0010" num="2" wdcount="2"> AP-NR-01-30-90 0051EST</s>
</FILEID>
<FIRST>

<s docid="AP900130-0010" num="3" wdcount="5"> r i PM-Kashmir 01-30 0789</s>
</FIRST>
<SECOND>

<s docid="AP900130-0010" num="4" wdcount="1"> PM-Kashmir,0818</s>
</SECOND>
<HEAD>

<s docid="AP900130-0010" num="5" wdcount="8"> Kashmir: A Tourist Paradise Becomes a War Zone</s>
</HEAD>
<NOTE>

<s docid="AP900130-0010" num="6" wdcount="18"> Eds: Also in Tuesday AMs report; In 10th graf, ``We are ''... Jagmohan uses only one name .</s>
</NOTE>
<BYLINE>

<s docid="AP900130-0010" num="7" wdcount="3"> By DILIP GANGULY</s>
</BYLINE>
<BYLINE>

<s docid="AP900130-0010" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900130-0010" num="9" wdcount="3"> SRINAGAR, India (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900130-0010" num="10" wdcount="28"> Exotic Kashmir, a tourist paradise of houseboat hotels and Mogul gardens from whose name the English made ``cashmere,'' has become a war zone of separatism and religious enmity.</s>

<s docid="AP900130-0010" num="11" wdcount="34"> Military jeeps carry senior government officials and civil servants around Srinagar in these dangerous days, as soldiers and paramilitary troopers try to stop a campaign of violence by Moslem separatists in the Kashmir Valley.</s>

<s docid="AP900130-0010" num="12" wdcount="9"> Intelligence officer M.K. Kaul commands one of the jeeps.</s>

<s docid="AP900130-0010" num="13" wdcount="29"> At the beginning of a trip through the city of 1 million people, he turned to the four soldiers in the jeep's rear seats and ordered: ``Check your weapons.</s>

<s docid="AP900130-0010" num="14" wdcount="4"> Be ready to fire''.</s>

<s docid="AP900130-0010" num="15" wdcount="13"> Kaul settled into the front seat, a 9mm pistol in his right hand.</s>

<s docid="AP900130-0010" num="16" wdcount="6"> ``These are bad days,'' he murmured.</s>

<s docid="AP900130-0010" num="17" wdcount="7"> ``These die-hard terrorists can attack from anywhere.</s>

<s docid="AP900130-0010" num="18" wdcount="11"> To his men, he said: ``Shoot them if you see them''.</s>

<s docid="AP900130-0010" num="19" wdcount="19"> On Monday, an around-the-clock curfew was lifted from 5 a.m. until noon and stores opened to crowds of customers.</s>

<s docid="AP900130-0010" num="20" wdcount="12"> Soldiers in sandbagged bunkers, armed with light machine guns, guarded main intersections.</s>

<s docid="AP900130-0010" num="21" wdcount="21"> A spokesman for the Jammu-Kashmir state government said the situation was peaceful and ``absolutely normal'' in Srinagar, the state's largest city.</s>

<s docid="AP900130-0010" num="22" wdcount="24"> At least 72 people have been killed since the crackdown began Jan. 20 in an effort to curb attacks on government officials and buildings.</s>

<s docid="AP900130-0010" num="23" wdcount="12"> Most of the dead have been Moslem militants shot by Indian troops.</s>

<s docid="AP900130-0010" num="24" wdcount="29"> ``We are neither fighting a war nor trying to suppress any popular movement,'' said Jagmohan, governor of Jammu-Kashmir, the only state in predominantly Hindu India with a Moslem majority.</s>

<s docid="AP900130-0010" num="25" wdcount="26"> ``We are fighting a handful of terrorists who are determined to create a law and order problem,'' said Jagmohan, a Hindu with a reputation for toughness.</s>

<s docid="AP900130-0010" num="26" wdcount="25"> Other officials in Kashmir say privately the situation is critical, perhaps the most serious threat India has faced in 42 years of independence from Britain.</s>

<s docid="AP900130-0010" num="27" wdcount="30"> ``It looks like everyone here has turned into a fundamentalist with firm belief that the day is not far off when they will become independent,'' a state police officer said.</s>

<s docid="AP900130-0010" num="28" wdcount="31"> Kashmir was a separate kingdom, ruled by a Hindu maharajah, when Britain relinquished colonial rule on Aug. 15, 1947, and the subcontinent was partitioned on religious lines into India and Pakistan.</s>

<s docid="AP900130-0010" num="29" wdcount="18"> The Hindu king opted to join India, not Pakistan, and the dispute over Kashmir has exacerbated relations since.</s>

<s docid="AP900130-0010" num="30" wdcount="11"> Pakistan took the western part of Kashmir and India the eastern.</s>

<s docid="AP900130-0010" num="31" wdcount="7"> Each accused the other of forcible occupation.</s>

<s docid="AP900130-0010" num="32" wdcount="12"> They have fought wars over Kashmir and the border question remains unresolved.</s>

<s docid="AP900130-0010" num="33" wdcount="15"> U.N. observers are stationed on the truce line and the two sides occasionally trade gunfire.</s>

<s docid="AP900130-0010" num="34" wdcount="32"> Officials will not say how many reinforcements have been sent to the Kashmir Valley since Jan. 20, but reports from various sources indicate 30,000-and 40,000 soldiers and paramilitary troops have been deployed.</s>

<s docid="AP900130-0010" num="35" wdcount="15"> It is the valley's heavily Moslem population that tilts the sectarian scale in Jammu-Kashmir state.</s>

<s docid="AP900130-0010" num="36" wdcount="15"> Of the state's nearly 6 million people, 64 percent are Moslems and 32 percent Hindus.</s>

<s docid="AP900130-0010" num="37" wdcount="8"> Most Hindus live in the southern Jammu area.</s>

<s docid="AP900130-0010" num="38" wdcount="4"> Srinagar has 150 mosques.</s>

<s docid="AP900130-0010" num="39" wdcount="20"> ``This is the best breeding ground for Moslem fundamentalism,'' said a federal official who helps coordinate the new security measures.</s>

<s docid="AP900130-0010" num="40" wdcount="25"> Nearly every mosque has a loudspeaker to summon the faithful to prayer _ and, more recently, to exhort listeners to defend their faith and Kashmir.</s>

<s docid="AP900130-0010" num="41" wdcount="34"> ``The residents are constantly bombarded with Islamic sermons and are reminded that fighting a `jihad' (Islamic holy war) is the most sacred duty of every Moslem,'' the federal official said, on condition of anonymity.</s>

<s docid="AP900130-0010" num="42" wdcount="36"> Electricity was cut off in the city Friday, which was both the Moslem sabbath and India's national Republic Day on India's Republic Day, but many mosque loudspeakers continued operating because militants connected them to car batteries.</s>

<s docid="AP900130-0010" num="43" wdcount="14"> Intelligence reports suggest the government has an advantage because the separatists are not united.</s>

<s docid="AP900130-0010" num="44" wdcount="20"> The most powerful group is the Jammu-Kashmir Liberation Front, but there are several others, including the Allah Tigers, Hezb-e-Mujahed Hezb-e-Islami.</s>

<s docid="AP900130-0010" num="45" wdcount="10"> India claims the fundamentalists get money and weapons from Pakistan.</s>

<s docid="AP900130-0010" num="46" wdcount="4"> The Pakistanis deny it.</s>

<s docid="AP900130-0010" num="47" wdcount="14"> Jagmohan, the governor, insists the main issue in Kashmir is economic development, not separatism.</s>

<s docid="AP900130-0010" num="48" wdcount="13"> ``The people do not want violence or the so-called independent Kashmir,'' he said.</s>

<s docid="AP900130-0010" num="49" wdcount="7"> ``The need of the hour is development.</s>

<s docid="AP900130-0010" num="50" wdcount="4"> Let more tourists come.</s>

<s docid="AP900130-0010" num="51" wdcount="5"> Let new schools be built.</s>

<s docid="AP900130-0010" num="52" wdcount="5"> Let new hospitals come up''.</s>

<s docid="AP900130-0010" num="53" wdcount="25"> As he spoke, military officers waited in the next room to discuss a new strategy to crush rebellion in what the tourist brochures call Paradise.</s>

<s docid="AP900130-0010" num="54" wdcount="9"> Right now, Paradise looks lost, at least temporarily .</s>
</TEXT>
</DOC>
