<DOC>
<DOCNO>

<s docid="AP900307-0146" num="1" wdcount="1"> AP900307-0146</s>
</DOCNO>
<FILEID>

<s docid="AP900307-0146" num="2" wdcount="2"> AP-NR-03-07-90 1738EST</s>
</FILEID>
<FIRST>

<s docid="AP900307-0146" num="3" wdcount="7"> u i AM-India 1stLd-Writethru a0609 03-07 0603</s>
</FIRST>
<SECOND>

<s docid="AP900307-0146" num="4" wdcount="4"> AM-India, 1st Ld-Writethru, a0609,0618</s>
</SECOND>
<HEAD>

<s docid="AP900307-0146" num="5" wdcount="6"> Moslems Ambush Truck Carrying Security Forces</s>
</HEAD>
<NOTE>

<s docid="AP900307-0146" num="6" wdcount="22"> Eds: INSERTS two grafs after 7th `At least'... to UPDATE with parties to send delegation to Kashmir; pickup graf 8 `Jagmohan said'....</s>

<s docid="AP900307-0146" num="7" wdcount="8"> One name for Gov. Jagmohan is cq .</s>
</NOTE>
<BYLINE>

<s docid="AP900307-0146" num="8" wdcount="3"> By DILIP GANGULY</s>
</BYLINE>
<BYLINE>

<s docid="AP900307-0146" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900307-0146" num="10" wdcount="3"> SRINAGAR, India (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900307-0146" num="11" wdcount="30"> Moslems blew up a truck carrying security forces Wednesday, killing three soldiers in the few hours the government relaxed a curfew designed to stop the Kashmiri separatist uprising, officials said.</s>

<s docid="AP900307-0146" num="12" wdcount="35"> In separate incidents, militants shot and killed a Moslem they said was a police informer and a Moslem died after he was caught in an exchange of fire between militants and security forces, officials said.</s>

<s docid="AP900307-0146" num="13" wdcount="25"> Also Wednesday, Moslem snipers fired on security forces in three parts of Srinagar during a five-hour relaxation of curfew, said Gov. Jagmohan of Jammu-Kashmir state.</s>

<s docid="AP900307-0146" num="14" wdcount="6"> There were no casualties, he said.</s>

<s docid="AP900307-0146" num="15" wdcount="26"> The curfew was relaxed from 5 a.m. to 10 a.m. to allow people in the city of 1 million to shop for food and other essentials.</s>

<s docid="AP900307-0146" num="16" wdcount="28"> An around-the-clock curfew was imposed Friday after security forces the day before shot and killed 49 Moslem demonstrators marching into Srinagar to take part in a pro-independence rally.</s>

<s docid="AP900307-0146" num="17" wdcount="18"> At least 1 million Moslems demonstrated to demand independence for the predominantly Moslem state; India is predominantly Hindu.</s>

<s docid="AP900307-0146" num="18" wdcount="13"> Srinagar, the summer capital of Jammu-Kashmir, is the center of the separatist movement.</s>

<s docid="AP900307-0146" num="19" wdcount="21"> At least 171 people have been killed in Kashmir since a government crackdown on the separatist movement began on Jan. 20.</s>

<s docid="AP900307-0146" num="20" wdcount="21"> Leading national parties decided Wednesday to send a ``high-powered delegation'' to Srinagar, according to the Press Trust of India news agency.</s>

<s docid="AP900307-0146" num="21" wdcount="13"> It did not name the members, but it said they would go Thursday.</s>

<s docid="AP900307-0146" num="22" wdcount="20"> The decision was taken at the end of a daylong multiparty meeting on Kashmir called by Prime Minister V.P. Singh.</s>

<s docid="AP900307-0146" num="23" wdcount="30"> A joint statement after the meeting said ``despite their ideological and political differences, (the parties) were one in defending the unity and integrity of the country,'' the news agency reported.</s>

<s docid="AP900307-0146" num="24" wdcount="23"> Jagmohan said the truck was driving around Srinagar distributing food to troops on street corners when it was blown up by Moslem militants.</s>

<s docid="AP900307-0146" num="25" wdcount="8"> He gave no further details of the attack.</s>

<s docid="AP900307-0146" num="26" wdcount="20"> The attacks came amid government claims that security forces arrested at least 12 leaders of the Moslem group Hezbul Mujahedeen.</s>

<s docid="AP900307-0146" num="27" wdcount="19"> Jagmohan said the militants, from Srinagar and the border towns of Baramulla and Kupwara, have been arrested since Sunday.</s>

<s docid="AP900307-0146" num="28" wdcount="11"> Hezbul Mujahedeen is one of 30 militant groups fighting for secession.</s>

<s docid="AP900307-0146" num="29" wdcount="14"> It is believed the second most powerful independence group after the Jammu-Kashmir Liberation Front.</s>

<s docid="AP900307-0146" num="30" wdcount="24"> ``We are going to hit hard at anti-national elements, there is no way they can get away with what they are doing,'' Jagmohan said.</s>

<s docid="AP900307-0146" num="31" wdcount="20"> ``It may take a month, six months, maybe a year, but ultimately these anti-national elments are going to be neutralized''.</s>

<s docid="AP900307-0146" num="32" wdcount="23"> Jagmohan, a Hindu, was appointed the state governor of Jammu-Kashmir on Jan. 18 in an attempt by the government to control the unrest.</s>

<s docid="AP900307-0146" num="33" wdcount="27"> Kashmir has been a problem for more than four decades following the 1947 partition of British colonial India into predominantly Moslem Pakistan and the mostly Hindu India.</s>

<s docid="AP900307-0146" num="34" wdcount="10"> Jammu-Kashmir, then a princely state, chose to merge with India.</s>

<s docid="AP900307-0146" num="35" wdcount="11"> Pakistan protested, claiming the territory because of its predominantly Moslem population.</s>

<s docid="AP900307-0146" num="36" wdcount="11"> The two countries have twice gone to war over the territory.</s>

<s docid="AP900307-0146" num="37" wdcount="16"> The Kashmir portion of Jammu-Kashmir is mostly Moslem, while the southern Jammu segment is predominantly Hindu.</s>

<s docid="AP900307-0146" num="38" wdcount="12"> Overall, about 65 percent of the state's 6 million people are Moslem.</s>

<s docid="AP900307-0146" num="39" wdcount="18"> Nationwide, Moslems make up 12 percent of India's 880 million people and Hindus account for 82 percent .</s>
</TEXT>
</DOC>
