<DOC>
<DOCNO>

<s docid="AP900220-0089" num="1" wdcount="1"> AP900220-0089</s>
</DOCNO>
<FILEID>

<s docid="AP900220-0089" num="2" wdcount="2"> AP-NR-02-20-90 1237EST</s>
</FILEID>
<FIRST>

<s docid="AP900220-0089" num="3" wdcount="5"> u i PM-Pakistan-India 02-20 0425</s>
</FIRST>
<SECOND>

<s docid="AP900220-0089" num="4" wdcount="1"> PM-Pakistan-India,0439</s>
</SECOND>
<HEAD>

<s docid="AP900220-0089" num="5" wdcount="6"> Indian and Pakistan Troops Exchange Fire</s>
</HEAD>
<BYLINE>

<s docid="AP900220-0089" num="6" wdcount="3"> By JOHN POMFRET</s>
</BYLINE>
<BYLINE>

<s docid="AP900220-0089" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900220-0089" num="8" wdcount="3"> MUZZAFFARABUD, Pakistan (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900220-0089" num="9" wdcount="30"> Pakistani and Indian troops exchanged fire for several hours today after a Pakistani soldier became the first military casualty on the troubled Kashmir border, officers and a western observer said.</s>

<s docid="AP900220-0089" num="10" wdcount="25"> The soldier was shot in the leg Sunday at a ceasefire line, several miles from the village of Chaukothi, officials said on condition of anonymity.</s>

<s docid="AP900220-0089" num="11" wdcount="21"> They said there were no reports of casualties from today's firefight at the line, which divides Kashmir between Pakistan and India.</s>

<s docid="AP900220-0089" num="12" wdcount="17"> The nations have twice gone to war over the Himalayan state, in 1948 and again in 1965.</s>

<s docid="AP900220-0089" num="13" wdcount="17"> The former princely state was divided between the two nations after British colonial rule ended in 1947.</s>

<s docid="AP900220-0089" num="14" wdcount="24"> Relations between the neighbors have become increasingly strained since Jan. 20 when Indian troops launched a military crackdown on Moslem separatists in turbulent Jammu-Kashmir.</s>

<s docid="AP900220-0089" num="15" wdcount="15"> The militants want India's only majority Moslem state to either become independent or join Pakistan.</s>

<s docid="AP900220-0089" num="16" wdcount="17"> Jammu-Kashmir is an aberration in India, where 82 percent of the country's 880 million people are Hindus.</s>

<s docid="AP900220-0089" num="17" wdcount="23"> The leaders of both countries have tried to soothe tempers in the dispute and have said another war over the region is unlikely.</s>

<s docid="AP900220-0089" num="18" wdcount="18"> However, Pakistani forces have now sealed off the border area at Chaukothi, forbidding civilians from entering the area.</s>

<s docid="AP900220-0089" num="19" wdcount="29"> The border crossing was the scene of a bloody confrontation on Feb. 11 between Indian troops and Pakistani students, who were marching in solidarity with activists in Indian-held Kashmir.</s>

<s docid="AP900220-0089" num="20" wdcount="17"> Indian troops killed three students and wounded several during that confrontation, a Pakistan defence ministry spokesman said.</s>

<s docid="AP900220-0089" num="21" wdcount="14"> The two armies also exchanged gunfire for about 30 minutes before calm was restored.</s>

<s docid="AP900220-0089" num="22" wdcount="27"> A Paksitan army captain, who said he witnessed the firefight, said unlike the occasional shootings in the past, Indian soldiers appeared to be aiming at Pakistani troops.</s>

<s docid="AP900220-0089" num="23" wdcount="16"> The western observer said Sunday's shooting of the Pakistan soldier appeared to back up that assertion.</s>

<s docid="AP900220-0089" num="24" wdcount="24"> In another sign of increased tensions, Pakistani and Indian officers are no longer accompanying United Nations' military observers as they pass through the borders.</s>

<s docid="AP900220-0089" num="25" wdcount="9"> ``It is not a normal situation,'' the officer said.</s>

<s docid="AP900220-0089" num="26" wdcount="5"> ``The border is extremely tense''.</s>

<s docid="AP900220-0089" num="27" wdcount="19"> Pakistan officials said they were taking steps to quell what one official called ``war fever'' on the Pakistan side.</s>

<s docid="AP900220-0089" num="28" wdcount="21"> ``We are trying to tie the people down,'' said Amir Alan Khan, a retired lieutenant colonel who heads Kashmir's civil defence.</s>

<s docid="AP900220-0089" num="29" wdcount="19"> He said hundreds of retired soldiers have approached him ``to ask for orders'' to fight the Indian army .</s>
</TEXT>
</DOC>
