<DOC>
<DOCNO>

<s docid="AP900121-0039" num="1" wdcount="1"> AP900121-0039</s>
</DOCNO>
<FILEID>

<s docid="AP900121-0039" num="2" wdcount="2"> AP-NR-01-21-90 1518EST</s>
</FILEID>
<FIRST>

<s docid="AP900121-0039" num="3" wdcount="5"> r i AM-India-Unrest 01-21 0627</s>
</FIRST>
<SECOND>

<s docid="AP900121-0039" num="4" wdcount="1"> AM-India-Unrest,0649</s>
</SECOND>
<HEAD>

<s docid="AP900121-0039" num="5" wdcount="6"> 21 Reported Killed in Kashmir Violence</s>
</HEAD>
<BYLINE>

<s docid="AP900121-0039" num="6" wdcount="3"> By ARUN JOSHI</s>
</BYLINE>
<BYLINE>

<s docid="AP900121-0039" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900121-0039" num="8" wdcount="3"> JAMMU, India (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900121-0039" num="9" wdcount="33"> Troops battled mobs of Moslem separatists in the Kashmir city of Srinagar over the weekend, and at least 21 people were killed and 100 wounded before the fighting subsided Sunday night, police said.</s>

<s docid="AP900121-0039" num="10" wdcount="24"> Fifteen demonstrators were shot and killed Sunday, while six were fatally wounded late Saturday night, according to Mohammad Nomani, inspector general of Srinagar police.</s>

<s docid="AP900121-0039" num="11" wdcount="16"> Militants defied a curfew and continued trading intermittent shots with government forces on Sunday, officials said.</s>

<s docid="AP900121-0039" num="12" wdcount="21"> Witnesses, speaking on condition of anonymity, said the death toll was at least 30, but that figure could not be confirmed.</s>

<s docid="AP900121-0039" num="13" wdcount="26"> Nomani, speaking by telephone from Srinagar, the summer capital of Jammu-Kashmir state, said the fighting tapered off late Sunday afternoon as heavy rains lashed the city.</s>

<s docid="AP900121-0039" num="14" wdcount="14"> But gunfire echoed through the deserted streets until evening, one resident said, requesting anonymity.</s>

<s docid="AP900121-0039" num="15" wdcount="10"> ``They (the troops) are shooting at anything moving,'' he said.</s>

<s docid="AP900121-0039" num="16" wdcount="15"> ``It is a disastrous situation out there,'' said Ramesh Kaul, a hotel receptionist in Srinagar.</s>

<s docid="AP900121-0039" num="17" wdcount="29"> At least 47 people have been killed in Jammu-Kashmir state since the beginning of the year in violence triggered by Moslem militants demanding independence or union with Islamic Pakistan.</s>

<s docid="AP900121-0039" num="18" wdcount="16"> The separatists, led by the Jammu-Kashmir Liberation Front, have often attacked government offices and police officials.</s>

<s docid="AP900121-0039" num="19" wdcount="24"> ``The situation is tense and dangerous,'' the state's chief secretary, Moosa Raza, said in Jammu, the state's winter capital 95 miles south of Srinagar.</s>

<s docid="AP900121-0039" num="20" wdcount="20"> Nomani said the police dispatched 25 cars with loudspeakers into the city, to appeal to people to obey the curfew.</s>

<s docid="AP900121-0039" num="21" wdcount="17"> The cars were escorted by heavily armed troops from the paramilitary Central Reserve Police Force, he said.</s>

<s docid="AP900121-0039" num="22" wdcount="22"> A 24-hour curfew was imposed Saturday in a bid to quell escalating violence and mass anti-India demonstrations in Srinagar and nearby towns.</s>

<s docid="AP900121-0039" num="23" wdcount="23"> But late Saturday, crowds defied curfew and surged into downtown Srinagar chanting ``Indian dogs go back''! and ``Long live Pakistan''! local reporters said.</s>

<s docid="AP900121-0039" num="24" wdcount="14"> They said the paramilitary troops opened fire, killing two people instantly and injuring 14.</s>

<s docid="AP900121-0039" num="25" wdcount="5"> Four of them died later.</s>

<s docid="AP900121-0039" num="26" wdcount="18"> As news of the shootings spread, thousands of Moslem men poured out of their homes, the reporters said.</s>

<s docid="AP900121-0039" num="27" wdcount="12"> They said protesters recited verses from the Koran, the Moslem holy book.</s>

<s docid="AP900121-0039" num="28" wdcount="24"> Some took up a chant urging ``mujahedeen,'' or Islamic holy warriors, to prepare for the final sacrifice in a showdown with India's Hindu-dominated government.</s>

<s docid="AP900121-0039" num="29" wdcount="21"> Jammu-Kashmir's former state chief minister, Farooq Abdullah, issued a statement accusing authorities of letting loose a ``reign of terror and repression''.</s>

<s docid="AP900121-0039" num="30" wdcount="24"> Abdullah's Moslem-dominated National Conference Party is closely aligned with the Congress Party of Rajiv Gandhi, the arch political foe of Prime Minister V.P. Singh.</s>

<s docid="AP900121-0039" num="31" wdcount="30"> Abdullah's government resigned Friday to protest the appointment of Singh's nominee as the state's new governor and imposition of governor's rule which amounts to tighter federal control over the state.</s>

<s docid="AP900121-0039" num="32" wdcount="32"> The curfew order was one of the first acts of the new governor, Jagmohan, a tough administrator who had cracked down on Kashmiri militants during an earlier stint as the state's governor.</s>

<s docid="AP900121-0039" num="33" wdcount="10"> Jagmohan, a Hindu who uses one name, took office Friday.</s>

<s docid="AP900121-0039" num="34" wdcount="11"> Parts of Kashmir region are claimed by both India and Pakistan.</s>

<s docid="AP900121-0039" num="35" wdcount="20"> The dispute started when the state was partitioned between the two countries when they gained independence from Britain in 1947.</s>

<s docid="AP900121-0039" num="36" wdcount="16"> Srinagar's 800,000 people are moslty Moslem, as is a majority of population in the Kashmir region.</s>

<s docid="AP900121-0039" num="37" wdcount="6"> The Jammu region is predominantly Hindu.</s>

<s docid="AP900121-0039" num="38" wdcount="15"> India has often accused Pakistan of aiding the Kashmiri militants, a charge Pakistan has denied.</s>

<s docid="AP900121-0039" num="39" wdcount="13"> Jammu-Kashmir is the only state with a Moslem majority in predominantly Hindu India.</s>

<s docid="AP900121-0039" num="40" wdcount="12"> Moslems make up 64 percent of the state population of 5 million.</s>

<s docid="AP900121-0039" num="41" wdcount="16"> Nationwide, Moslems comprise 12 percent of India's 880 million people, while Hindus comprise 82 percent .</s>
</TEXT>
</DOC>
