<DOC>
<DOCNO>

<s docid="AP900324-0081" num="1" wdcount="1"> AP900324-0081</s>
</DOCNO>
<FILEID>

<s docid="AP900324-0081" num="2" wdcount="2"> AP-NR-03-24-90 1408EST</s>
</FILEID>
<FIRST>

<s docid="AP900324-0081" num="3" wdcount="5"> r i AM-India-Kashmir 03-24 0350</s>
</FIRST>
<SECOND>

<s docid="AP900324-0081" num="4" wdcount="1"> AM-India-Kashmir,0364</s>
</SECOND>
<HEAD>

<s docid="AP900324-0081" num="5" wdcount="6"> Moslem Militants Kill Five, Kidnap One</s>
</HEAD>
<DATELINE>

<s docid="AP900324-0081" num="6" wdcount="3"> SRINAGAR, India (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900324-0081" num="7" wdcount="23"> Moslem militants killed five people who opposed their fight for independence from predominantly Hindu India and kidnapped a former legislator, officials said Saturday.</s>

<s docid="AP900324-0081" num="8" wdcount="28"> At least 195 people, mostly Moslem demonstrators, have been killed in the northern state of Jammu-Kashmir since Jan. 20 when the government launched a crackdown on the separatists.</s>

<s docid="AP900324-0081" num="9" wdcount="14"> State officials said four of the five people killed Friday and Saturday were Moslems.</s>

<s docid="AP900324-0081" num="10" wdcount="34"> They were identified as a deputy police superintendent; the 73-year-old local leader of the Communist Party of India; the grandson of another prominent Communist leader; and a man accused of being a police informer.</s>

<s docid="AP900324-0081" num="11" wdcount="14"> The fifth victim was a civilian, the sources added, speaking on condition of anonymity.</s>

<s docid="AP900324-0081" num="12" wdcount="9"> It was unclear if he was Hindu or Moslem.</s>

<s docid="AP900324-0081" num="13" wdcount="27"> The former state legislator, Mir Mustafa, was pulled out of his car at gunpoint Saturday near his home in Badgam, 12 miles west of Srinagar, officials said.</s>

<s docid="AP900324-0081" num="14" wdcount="14"> Srinagar has been a focal point of the fighting between government troops and separatists.</s>

<s docid="AP900324-0081" num="15" wdcount="25"> Family members and highly placed sources in the government of Jammu-Kashmir said no group has claimed responsibility for the abduction and no demands were issued.</s>

<s docid="AP900324-0081" num="16" wdcount="9"> Mustafa was an independent member of the state legislature.</s>

<s docid="AP900324-0081" num="17" wdcount="13"> The governing body was dissolved in January when the federal crackdown was ordered.</s>

<s docid="AP900324-0081" num="18" wdcount="31"> In December, Mustafa helped negotiate a prisoner exchange in which the kidnapped daughter of Home Minister Mufti Mohammad Saeed was swapped for five prominent members of the radical Jammu-Kashmir Liberation Front.</s>

<s docid="AP900324-0081" num="19" wdcount="29"> The front is one of several Moslem militant groups waging a campaign of bombings and assassinations to press demands for the independence of Kashmir, a part of Jammu-Kashmir state.</s>

<s docid="AP900324-0081" num="20" wdcount="8"> Jammu-Kashmir is the only Moslem-majority state in India.</s>

<s docid="AP900324-0081" num="21" wdcount="20"> The secession movement has been simmering since 1947, when the state of Kashmir was divided between India and Moslem Pakistan.</s>

<s docid="AP900324-0081" num="22" wdcount="10"> The eastern part of the state is governed by India.</s>

<s docid="AP900324-0081" num="23" wdcount="9"> The western slice of Kashmir is under Pakistan's control.</s>

<s docid="AP900324-0081" num="24" wdcount="21"> The two countries went to war twice over Kashmir, and their armies still face each other along the disputed frontier .</s>
</TEXT>
</DOC>
