<DOC>
<DOCNO>

<s docid="AP900625-0090" num="1" wdcount="1"> AP900625-0090</s>
</DOCNO>
<FILEID>

<s docid="AP900625-0090" num="2" wdcount="2"> AP-NR-06-25-90 1318EDT</s>
</FILEID>
<FIRST>

<s docid="AP900625-0090" num="3" wdcount="5"> r i AM-India-Kashmir 06-25 0227</s>
</FIRST>
<SECOND>

<s docid="AP900625-0090" num="4" wdcount="1"> AM-India-Kashmir,0232</s>
</SECOND>
<HEAD>

<s docid="AP900625-0090" num="5" wdcount="7"> Militants Kill Four of Family in Kashmir</s>
</HEAD>
<DATELINE>

<s docid="AP900625-0090" num="6" wdcount="3"> SRINAGAR, India (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900625-0090" num="7" wdcount="26"> The bodies of four Moslems were found in a Kashmir town Monday, five days after they were kidnapped by Moslem militants agitating for secession from India.</s>

<s docid="AP900625-0090" num="8" wdcount="31"> The bodies, which had bullet wounds, were found in the town of Sopore about 35 miles northwest of the Kashmir capital of Srinagar, said police officials speaking on condition of anonymity.</s>

<s docid="AP900625-0090" num="9" wdcount="23"> Anonymous callers to local newspapers and news agency offices said the four were killed by the Hezbul Mujahedeen because they were police informers.</s>

<s docid="AP900625-0090" num="10" wdcount="21"> The Hezbul Mujahedeen is one of more than a dozen Moslem organizations fighting for independence of the Kashmir valley from India.</s>

<s docid="AP900625-0090" num="11" wdcount="25"> Police officials also reported the death of one soldier in a militant ambush of an army convoy in the district of Baramulla, northwest of Srinagar.</s>

<s docid="AP900625-0090" num="12" wdcount="8"> At least three soldiers were injured, they said.</s>

<s docid="AP900625-0090" num="13" wdcount="23"> The deaths raise to 630 the number of people killed since security forces began a crackdown on the Moslem movement on Jan. 20.</s>

<s docid="AP900625-0090" num="14" wdcount="16"> The Kashmir valley, most of which falls in the Indian state of Jammu-Kashmir, is predominantly Moslem.</s>

<s docid="AP900625-0090" num="15" wdcount="10"> Jammu-Kashmir is the only Indian state with a Moslem majority.</s>

<s docid="AP900625-0090" num="16" wdcount="15"> Moslem militants earlier had demanded union with Pakistan, the Islamic nation on India's western border.</s>

<s docid="AP900625-0090" num="17" wdcount="16"> But, of late, they have been demanding independence and the status of a neutral nation .</s>
</TEXT>
</DOC>
