<DOC>
<DOCNO>

<s docid="AP891117-0248" num="1" wdcount="1"> AP891117-0248</s>
</DOCNO>
<FILEID>

<s docid="AP891117-0248" num="2" wdcount="2"> AP-NR-11-17-89 2145EST</s>
</FILEID>
<FIRST>

<s docid="AP891117-0248" num="3" wdcount="5"> r f AM-BeerAdvertising 11-17 0383</s>
</FIRST>
<SECOND>

<s docid="AP891117-0248" num="4" wdcount="2"> AM-Beer Advertising,0397</s>
</SECOND>
<HEAD>

<s docid="AP891117-0248" num="5" wdcount="9"> Miller, Anheuser-Busch Super Bowl Campaigns Tagged At $7 Million-Plus</s>
</HEAD>
<BYLINE>

<s docid="AP891117-0248" num="6" wdcount="3"> By RANDOLPH PICHT</s>
</BYLINE>
<BYLINE>

<s docid="AP891117-0248" num="7" wdcount="3"> AP Business Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP891117-0248" num="8" wdcount="3"> ST. LOUIS (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP891117-0248" num="9" wdcount="16"> The beer gridiron is going to be a busy and expensive place on television this January.</s>

<s docid="AP891117-0248" num="10" wdcount="38"> The nation's two largest brewers, Anheuser Busch Cos. Inc. and Miller Brewing Co., are gearing up to sell their beer with by staging mock football games in television commercials in conjunction with Super Bowl XXIV in New Orleans.</s>

<s docid="AP891117-0248" num="11" wdcount="18"> Executives from both companies say they're attempting to take advantage of the weeks of hype surrounding the game.</s>

<s docid="AP891117-0248" num="12" wdcount="21"> Both beermakers claim their packages are the largest Super Bowl promotions ever, with each planning to spend upwards of $7 million.</s>

<s docid="AP891117-0248" num="13" wdcount="38"> Anheuser Busch is staging a ``Bud Bowl II'' ad campaign that culminates during the Jan. 28 Super Bowl, with a game featuring animated teams of Budweiser and Bud Light beer bottles rattling around on a pint-sized football field.</s>

<s docid="AP891117-0248" num="14" wdcount="11"> The first such game was staged during the last Super Bowl.</s>

<s docid="AP891117-0248" num="15" wdcount="32"> ``We're starting a month earlier, we've added an extra promo spot and we're going to have a lot more display materials in the stores,'' said Tom Sharbaugh, group brand director for Budweiser.</s>

<s docid="AP891117-0248" num="16" wdcount="33"> Miller, based in Milwaukee, won't say exactly how much it is spending on its 12-week, pre-Super Bowl campaign centered on a football game between a ``Tastes Great'' team and a ``Less Filling'' squad.</s>

<s docid="AP891117-0248" num="17" wdcount="23"> Those teams will be made up of current and former National Football League players such as Bert Jones, L.C. Greenwood and Joe Klecko.</s>

<s docid="AP891117-0248" num="18" wdcount="19"> ``We're spending more than $7 million, I can tell you that,'' said Richard Burton, advertising manager for Lite beer.</s>

<s docid="AP891117-0248" num="19" wdcount="5"> ``We're talking about real-life talent''.</s>

<s docid="AP891117-0248" num="20" wdcount="26"> Miller's campaign culminates Jan. 14, two weeks before the Super Bowl, primarily because Anheuser Busch bought all the Super Bowl television spots allocated for beer advertising.</s>

<s docid="AP891117-0248" num="21" wdcount="7"> Miller's television commercials already have started airing.</s>

<s docid="AP891117-0248" num="22" wdcount="16"> Anheuser Busch will begin its ads this week with a spot featuring sports announcer Brent Musberger.</s>

<s docid="AP891117-0248" num="23" wdcount="7"> Both companies also have fan participation promotions.</s>

<s docid="AP891117-0248" num="24" wdcount="27"> Anheuser Busch expects to receive 400,000 to 500,000 scorecards from fans who are being asked to write down the score of the Bud Bowl after each quarter.</s>

<s docid="AP891117-0248" num="25" wdcount="11"> Fans who send in their scorecards will receive a commemorative pin.</s>

<s docid="AP891117-0248" num="26" wdcount="13"> Miller has a consumer sweepstakes offering expense-paid trips to the Super Bowl .</s>
</TEXT>
</DOC>
