<DOC>
<DOCNO>

<s docid="AP890122-0087" num="1" wdcount="1"> AP890122-0087</s>
</DOCNO>
<FILEID>

<s docid="AP890122-0087" num="2" wdcount="2"> AP-NR-01-22-89 2121EST</s>
</FILEID>
<FIRST>

<s docid="AP890122-0087" num="3" wdcount="5"> u a AM-SuperBowl-Newspage 01-22 0237</s>
</FIRST>
<SECOND>

<s docid="AP890122-0087" num="4" wdcount="2"> AM-Super Bowl-Newspage,0245</s>
</SECOND>
<HEAD>

<s docid="AP890122-0087" num="5" wdcount="7"> San Francisco Beats Cincinnati in Super Bowl</s>
</HEAD>
<DATELINE>

<s docid="AP890122-0087" num="6" wdcount="2"> MIAMI (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890122-0087" num="7" wdcount="24"> In a dramatic finish, the San Francisco 49ers football team won the Super Bowl on Sunday with a 20-16 victory over the Cincinnati Bengals.</s>

<s docid="AP890122-0087" num="8" wdcount="16"> Joe Montana's 10-yard touchdown pass to John Taylor with 34 seconds left provided the winning margin.</s>

<s docid="AP890122-0087" num="9" wdcount="26"> The victory was achieved through the brilliance of Montana and Jerry Rice, the wide receiver who caught 12 passes for 222 yards, both Super Bowl records.</s>

<s docid="AP890122-0087" num="10" wdcount="8"> Rice was named the game's most valuable player.</s>

<s docid="AP890122-0087" num="11" wdcount="27"> The winning score came at the end of a 92-yard drive, engineered by Montana, whose touchdown pass gave him a Super Bowl record with 357 yards passing.</s>

<s docid="AP890122-0087" num="12" wdcount="30"> It was the fifth straight win for a National Football Conference team, but by far the most dramatic _ the previous four had been by an average score of 41-14.</s>

<s docid="AP890122-0087" num="13" wdcount="12"> It also gave 49ers Coach Bill Walsh his third Super Bowl win.</s>

<s docid="AP890122-0087" num="14" wdcount="16"> The game was a defensive struggle in the first half, which ended in a 3-3 tie.</s>

<s docid="AP890122-0087" num="15" wdcount="22"> Two key players were injured in the first 14 plays, Cincinnati's All-Pro nose tackle Tim Krumrie and San Francisco's tackle Steve Wallace.</s>

<s docid="AP890122-0087" num="16" wdcount="24"> The first touchdown didn't come until 44 minutes into the 60-minute game, when Cincinnati's Stanford Jennings took a kickoff 93 yards for a score.</s>

<s docid="AP890122-0087" num="17" wdcount="19"> The game, before a crowd of 75,179 at Joe Robbie Stadium, went undisrupted by racial tensions in Miami .</s>
</TEXT>
</DOC>
