<DOC>
<DOCNO>

<s docid="AP890203-0164" num="1" wdcount="1"> AP890203-0164</s>
</DOCNO>
<FILEID>

<s docid="AP890203-0164" num="2" wdcount="2"> AP-NR-02-03-89 2112EST</s>
</FILEID>
<FIRST>

<s docid="AP890203-0164" num="3" wdcount="5"> r w AM-Bush-49ers 02-03 0325</s>
</FIRST>
<SECOND>

<s docid="AP890203-0164" num="4" wdcount="1"> AM-Bush-49ers,330</s>
</SECOND>
<HEAD>

<s docid="AP890203-0164" num="5" wdcount="4"> Bush Meets With 49ers</s>
</HEAD>
<DATELINE>

<s docid="AP890203-0164" num="6" wdcount="2"> WASHINGTON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890203-0164" num="7" wdcount="21"> President Bush congratulated the San Francisco 49ers on Friday and said they ``rewrote the record books'' with their Super Bowl victory.</s>

<s docid="AP890203-0164" num="8" wdcount="13"> In turn he was presented with two autographed balls and a jogging outfit.</s>

<s docid="AP890203-0164" num="9" wdcount="18"> ``Let me congratulate you also on your victory,'' quarterback Joe Montana told Bush at a East Room reception.</s>

<s docid="AP890203-0164" num="10" wdcount="29"> Montana said being invited to the White House ``means a lot to all of us'' and joked: ``Not very often do I get to see these guys in ties''.</s>

<s docid="AP890203-0164" num="11" wdcount="34"> Bush, surrounded by 49ers, told the team, ``With this, your third Super Bowl title in eight years, you rewrote the record books and raised the game of football to a new level of excellence''.</s>

<s docid="AP890203-0164" num="12" wdcount="31"> And, to Montana, who drove the team to the winning touchdown on a 92-yard drive late in the fourth quarter, Bush said: ``Joe, you once again showed your grace under pressure.</s>

<s docid="AP890203-0164" num="13" wdcount="10"> I guess we all wonder why it took so long''.</s>

<s docid="AP890203-0164" num="14" wdcount="21"> Bush was presented autographed balls by both Montana and wide receiver Jerry Rice, who won the game's Most Valuable Player award.</s>

<s docid="AP890203-0164" num="15" wdcount="17"> ``That's the real thing from the Super Bowl,'' Rice said of the ball he gave the president.</s>

<s docid="AP890203-0164" num="16" wdcount="22"> Bush joked that he heard, ``there is a new TV series coming out based on your Super Bowl performance _ Miami Rice.</s>

<s docid="AP890203-0164" num="17" wdcount="9"> Available in every city in the country except one.</s>

<s docid="AP890203-0164" num="18" wdcount="3"> Cininnnati, that is''.</s>

<s docid="AP890203-0164" num="19" wdcount="12"> The 49ers beat the Cincinnati Bengals, 20-16, two weeks ago in Miami.</s>

<s docid="AP890203-0164" num="20" wdcount="30"> Team owner Danny DeBartolo told Bush that he would be presented with a Super Bowl ring, size 11, ``because we want to make you an honorary member of our team''.</s>

<s docid="AP890203-0164" num="21" wdcount="35"> And outgoing coach Bill Walsh gave Bush a 49ers jogging outfit, but cautioned, ``I'm not sure we suggest running in the streets of Washington, D.C., in this suit....Remember the Redskin fans are all around us''.</s>

<s docid="AP890203-0164" num="22" wdcount="11"> Super Bowl winners are traditionally invited to the White House .</s>
</TEXT>
</DOC>
