<DOC>
<DOCNO>

<s docid="AP900130-0113" num="1" wdcount="1"> AP900130-0113</s>
</DOCNO>
<FILEID>

<s docid="AP900130-0113" num="2" wdcount="2"> AP-NR-01-30-90 1443EST</s>
</FILEID>
<FIRST>

<s docid="AP900130-0113" num="3" wdcount="7"> r a PM-SuperBowlRatings 2ndLd-Writethru a0577 01-30 0401</s>
</FIRST>
<SECOND>

<s docid="AP900130-0113" num="4" wdcount="8"> PM-Super Bowl Ratings, 2nd Ld - Writethru, a0577,0405</s>
</SECOND>
<HEAD>

<s docid="AP900130-0113" num="5" wdcount="7"> Super Bowl Was Lowest-Rated in 21 Years</s>
</HEAD>
<NOTE>

<s docid="AP900130-0113" num="6" wdcount="16"> Eds: INSERTS one graf after 7th graf pvs, `Only the '... with highest-rated Super Bowl .</s>
</NOTE>
<BYLINE>

<s docid="AP900130-0113" num="7" wdcount="3"> By RONALD BLUM</s>
</BYLINE>
<BYLINE>

<s docid="AP900130-0113" num="8" wdcount="3"> AP Sports Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900130-0113" num="9" wdcount="3"> NEW YORK (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900130-0113" num="10" wdcount="22"> The San Francisco 49ers' 55-10 rout of the Denver Broncos was the lowest-rated Super Bowl in 21 years and the third-lowest ever.</s>

<s docid="AP900130-0113" num="11" wdcount="43"> The game on CBS averaged a 39.0 rating and a 63 share, the lowest Super Bowl rating since 1969, when the New York Jets' 16-7 victory over Baltimore got a 36.0 on NBC for the worst rating ever, A.C. Nielsen Co. said today.</s>

<s docid="AP900130-0113" num="12" wdcount="14"> The rating is a percentage of the nation's televisions; each point represents 921,000 homes.</s>

<s docid="AP900130-0113" num="13" wdcount="12"> The share is the percentage of the televisions on at the time.</s>

<s docid="AP900130-0113" num="14" wdcount="35"> Despite the low rating, Sunday's game was seen by about 108.5 million people, making it the ninth most-watched TV show ever in the United States behind eight Super Bowls and the final episode of ``MASH''.</s>

<s docid="AP900130-0113" num="15" wdcount="17"> The higher viewership was made possible by the annual increase in the number of homes with television.</s>

<s docid="AP900130-0113" num="16" wdcount="25"> ``Given the expected blowout, the numbers are completely understandable and we're happy to have a 39,'' said Susan Kerr, director of programming for CBS Sports.</s>

<s docid="AP900130-0113" num="17" wdcount="8"> ``It's still a remarkable rating for prime time''.</s>

<s docid="AP900130-0113" num="18" wdcount="11"> The 49ers won by the biggest margin in Super Bowl history.</s>

<s docid="AP900130-0113" num="19" wdcount="21"> Only the 1969 and 1968 Super Bowls had lower ratings; Green Bay's 33-14 victory over Oakland in 1968 got a 36.8.</s>

<s docid="AP900130-0113" num="20" wdcount="7"> The first Super Bowl was in 1967.</s>

<s docid="AP900130-0113" num="21" wdcount="19"> The highest-rated Super Bowl was in 1982, when the 49ers' 26-21 victory over Cincinnati got a 49.1 on CBS.</s>

<s docid="AP900130-0113" num="22" wdcount="26"> Last year's San Francisco-Cincinnati Super Bowl, won by the 49ers 20-16, got a 43.5 rating and was seen in 39.3 million homes, according to Nielsen estimates.</s>

<s docid="AP900130-0113" num="23" wdcount="10"> This year's game was seen in about 35.9 million homes.</s>

<s docid="AP900130-0113" num="24" wdcount="34"> Viewership of the 5 p.m. game this year peaked at a 41.6 rating and a 69 share from 6 p.m. to 6:30 p.m., dropping off as it became clear that Denver would not rally.</s>

<s docid="AP900130-0113" num="25" wdcount="23"> The pregame show got a 39.0 rating and a 63 share and the postgame show got a 22.5 rating and a 35 share.</s>

<s docid="AP900130-0113" num="26" wdcount="14"> The musical ``Annie,'' which was on ABC opposite the game, got a 9.4 rating.</s>

<s docid="AP900130-0113" num="27" wdcount="19"> ``Life Goes On'' on NBC got a 6.0 rating and ``Love With a Twist'' on NBC a 7.6 .</s>
</TEXT>
</DOC>
