<DOC>
<DOCNO>

<s docid="AP900128-0063" num="1" wdcount="1"> AP900128-0063</s>
</DOCNO>
<FILEID>

<s docid="AP900128-0063" num="2" wdcount="2"> AP-NR-01-28-90 2236EST</s>
</FILEID>
<FIRST>

<s docid="AP900128-0063" num="3" wdcount="5"> u a AM-SuperBowl-Newspage 01-28 0265</s>
</FIRST>
<SECOND>

<s docid="AP900128-0063" num="4" wdcount="2"> AM-Super Bowl-Newspage,0277</s>
</SECOND>
<HEAD>

<s docid="AP900128-0063" num="5" wdcount="7"> San Francisco Routs Broncos in Super Bowl</s>
</HEAD>
<DATELINE>

<s docid="AP900128-0063" num="6" wdcount="3"> NEW ORLEANS (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900128-0063" num="7" wdcount="18"> The San Francisco 49ers routed the Denver Broncos 55-10 Sunday in the most lopsided Super Bowl victory ever.</s>

<s docid="AP900128-0063" num="8" wdcount="36"> The 49ers' win in the 24th Super Bowl made them the first repeat NFL champion in a decade and tied the Pittsburgh Steelers as a pinnacle of Super Bowl perfection with four wins in four tries.</s>

<s docid="AP900128-0063" num="9" wdcount="14"> San Francisco won the National Football League championship game in 1989, 1985 and 1982.</s>

<s docid="AP900128-0063" num="10" wdcount="16"> The Broncos, on the other hand, lost the last four Super Bowl games they have played.</s>

<s docid="AP900128-0063" num="11" wdcount="36"> San Francisco quarterback Joe Montana made five touchdown passes, three to Jerry Rice, breaking a Super Bowl record for touchdown passes on a day on which he also set a record with 13 straight pass completions.</s>

<s docid="AP900128-0063" num="12" wdcount="26"> He also set five Super Bowl career records, including his third Super Bowl Most Valuable Player award and San Francisco's point total was the most ever.</s>

<s docid="AP900128-0063" num="13" wdcount="10"> Montana left the game with nearly 11 minutes to play.</s>

<s docid="AP900128-0063" num="14" wdcount="12"> In four Super Bowls, he has thrown 11 touchdowns and no interceptions.</s>

<s docid="AP900128-0063" num="15" wdcount="18"> For Denver quarterback John Elway, it was a day of futility, ending with his third Super Bowl defeat.</s>

<s docid="AP900128-0063" num="16" wdcount="15"> He missed eight of his first 10 passes and was intercepted twice and fumbled once.</s>

<s docid="AP900128-0063" num="17" wdcount="6"> By halftime the score was 27-3.</s>

<s docid="AP900128-0063" num="18" wdcount="14"> With their third loss in four years, the Broncos have now been outscored 136-40.</s>

<s docid="AP900128-0063" num="19" wdcount="30"> San Francisco was boringly perfect, doing more than even the experts who made them favorites by nearly two touchdowns after a 14-2 season and a waltz through the playoffs .</s>
</TEXT>
</DOC>
