<DOC>
<DOCNO>

<s docid="LA013090-0161" num="1" wdcount="1"> LA013090-0161</s>
</DOCNO>
<DOCID>

<s docid="LA013090-0161" num="2" wdcount="1"> 169281</s>
</DOCID>
<DATE>
<P>

<s docid="LA013090-0161" num="3" wdcount="6"> January 30, 1990, Tuesday, P.M. Final</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA013090-0161" num="4" wdcount="10"> Calendar; Part P; Page 8; Column 5; Late Final Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA013090-0161" num="5" wdcount="2"> 339 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA013090-0161" num="6" wdcount="9"> SUPER BOWL TOPS ON TV BUT CBS STILL LAGGING</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA013090-0161" num="7" wdcount="6"> From Times Staff and Wire Reports</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA013090-0161" num="8" wdcount="2"> NEW YORK</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA013090-0161" num="9" wdcount="41"> Super Bowl XXIV was the most watched television event of the week, viewed by a whopping 63% of TV viewers, but not even Joe Montana could lift CBS out of the cellar in the ratings race, it was reported today .</s>
</P>
<P>

<s docid="LA013090-0161" num="10" wdcount="31"> CBS estimates that 109 million viewers saw all or part of the game, down only 2 million from last year despite the fact that this year's match was a blowout .</s>
</P>
<P>

<s docid="LA013090-0161" num="11" wdcount="43"> On the upside for CBS -- Super Bowl XXIV carried enough of its audience over to the debut of the new series, "Grand Slam," to provide a good audience sampling and give the action show a ranking of 15th for the night .</s>
</P>
<P>

<s docid="LA013090-0161" num="12" wdcount="25"> It was CBS' bad luck that the game was so predictably lopsided, which resulted in the lowest rating since Super Bowl III in 1969 .</s>
</P>
<P>

<s docid="LA013090-0161" num="13" wdcount="16"> Each rating point in 1990, however, represents many more households than it did two decades ago.</s>

<s docid="LA013090-0161" num="14" wdcount="13"> Technically, Super Bowl IV in 1970 out-rated Super Bowl XXIV, 39.4 to 39.0.</s>

<s docid="LA013090-0161" num="15" wdcount="25"> But last Sunday's game had almost twice as many viewers as the estimated 59.19 million who watched Kansas City beat Minnesota 20 years ago .</s>
</P>
<P>

<s docid="LA013090-0161" num="16" wdcount="27"> This also marks only the third time that the network airing the Super Bowl did not win the week -- NBC managed it in 1979 and 1981.</s>

<s docid="LA013090-0161" num="17" wdcount="24"> It also is only the second time the Super Bowl network was third for the week -- dating back to NBC in 1979 .</s>
</P>
<P>

<s docid="LA013090-0161" num="18" wdcount="13"> The Broncos were not to blame for all of CBS' troubles last week.</s>

<s docid="LA013090-0161" num="19" wdcount="11"> The network tried some stunting, most of which did not work.</s>

<s docid="LA013090-0161" num="20" wdcount="13"> On Monday it ran a popular theatrical movie, "Cocoon," which tied for 54th.</s>

<s docid="LA013090-0161" num="21" wdcount="18"> The big winner was the American Music Awards on ABC, which came in 10th for the week .</s>
</P>
<P>

<s docid="LA013090-0161" num="22" wdcount="3"> TOP 10 SHOWS</s>
</P>
<P>

<s docid="LA013090-0161" num="23" wdcount="16"> Here are the ratings for national prime-time television for Jan. 22-28, as compiled by the A.</s>

<s docid="LA013090-0161" num="24" wdcount="4"> C. Nielsen Co .</s>
</P>
<P>

<s docid="LA013090-0161" num="25" wdcount="3"> Program (Network): Rating</s>
</P>
<P>

<s docid="LA013090-0161" num="26" wdcount="6"> 1. Super Bowl XXIV (CBS): 39.0</s>
</P>
<P>

<s docid="LA013090-0161" num="27" wdcount="6"> 2. Super Bowl Postgame (CBS): 25.3</s>
</P>
<P>

<s docid="LA013090-0161" num="28" wdcount="6"> 3. The Cosby Show (NBC): 25.0</s>
</P>
<P>

<s docid="LA013090-0161" num="29" wdcount="4"> 4. Cheers (NBC): 25.0</s>
</P>
<P>

<s docid="LA013090-0161" num="30" wdcount="4"> 5. Roseanne (ABC): 24.5</s>
</P>
<P>

<s docid="LA013090-0161" num="31" wdcount="6"> 6. A Different World (NBC): 22.4</s>
</P>
<P>

<s docid="LA013090-0161" num="32" wdcount="6"> 7. The Golden Girls (NBC): 21.7</s>
</P>
<P>

<s docid="LA013090-0161" num="33" wdcount="5"> 8. Empty Nest (NBC): 20.5</s>
</P>
<P>

<s docid="LA013090-0161" num="34" wdcount="6"> 9. The Wonder Years (ABC): 20.4</s>
</P>
<P>

<s docid="LA013090-0161" num="35" wdcount="2"> 10. Amer.</s>

<s docid="LA013090-0161" num="36" wdcount="4"> Music Awards (ABC): 20.0</s>
</P>
</TEXT>
<TYPE>
<P>

<s docid="LA013090-0161" num="37" wdcount="1"> List</s>
</P>
</TYPE>
</DOC>
