<DOC>
<DOCNO>

<s docid="LA020890-0197" num="1" wdcount="1"> LA020890-0197</s>
</DOCNO>
<DOCID>

<s docid="LA020890-0197" num="2" wdcount="1"> 173561</s>
</DOCID>
<DATE>
<P>

<s docid="LA020890-0197" num="3" wdcount="6"> February 8, 1990, Thursday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA020890-0197" num="4" wdcount="9"> Sports; Part C; Page 11; Column 1; Sports Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA020890-0197" num="5" wdcount="2"> 466 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA020890-0197" num="6" wdcount="6"> ROSE BOWL BIDS FOR SUPER BOWL;</s>
</P>
<P>

<s docid="LA020890-0197" num="7" wdcount="8"> FOOTBALL: IN PROPOSAL FOR 1993 GAME, THE L.A.</s>

<s docid="LA020890-0197" num="8" wdcount="12"> SPORTS COUNCIL WILL OFFER INCENTIVES TO NFL, INCLUDING RENT-FREE STADIUM USE .</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA020890-0197" num="9" wdcount="6"> By VICKI TORRES, TIMES STAFF WRITER</s>
</P>
</BYLINE>
<TEXT>
<P>

<s docid="LA020890-0197" num="10" wdcount="35"> The Los Angeles Sports Council, in a bid to bring Super Bowl XXVII to the Rose Bowl in 1993, will offer the stadium to the National Football League rent-free in a proposal next Monday .</s>
</P>
<P>

<s docid="LA020890-0197" num="11" wdcount="34"> The Sports Council, which represents the Los Angeles-Orange County area in trying to bring major sports attractions here, also will offer the NFL all income from concessions and the sale of novelty items .</s>
</P>
<P>

<s docid="LA020890-0197" num="12" wdcount="13"> Competing against the Rose Bowl are San Diego, San Francisco and Phoenix .</s>
</P>
<P>

<s docid="LA020890-0197" num="13" wdcount="15"> Because the Rose Bowl has 102,083 seats, the council selected it as the prime venue.</s>

<s docid="LA020890-0197" num="14" wdcount="33"> Under a joint agreement, the Coliseum and Anaheim Stadium did not submit competing bids, but they would share in the revenues if Pasadena gets the game, said Ed Aghjayan, Pasadena's deputy city manager.</s>

<s docid="LA020890-0197" num="15" wdcount="27"> "The bulk of the revenue would go to the Rose Bowl, but the idea is that we would share with the Coliseum and Anaheim," Aghjayan said .</s>
</P>
<P>

<s docid="LA020890-0197" num="16" wdcount="8"> Details of the split are still being negotiated.</s>

<s docid="LA020890-0197" num="17" wdcount="21"> One plan calls for the Rose Bowl to receive 75% of the proceeds, with the two other facilities sharing 25% .</s>
</P>
<P>

<s docid="LA020890-0197" num="18" wdcount="34"> Pasadena earned $300,000 from the 1983 Super Bowl and $800,000 in 1987, the money coming from stadium rental fees, concession sales, admission taxes, charges for use of a hospitality tent compound and parking fees.</s>

<s docid="LA020890-0197" num="19" wdcount="23"> In addition, the city was allowed to buy 1,200 tickets at face value for local distribution by directors and other city officials .</s>
</P>
<P>

<s docid="LA020890-0197" num="20" wdcount="30"> But as bidding for the Super Bowl has become more competitive, the NFL has taken more of the income, Aghjayan said in a report to the city's Board of Directors.</s>

<s docid="LA020890-0197" num="21" wdcount="22"> In most parts of the country, the stadium is offered rent-free in exchange for the benefits to local economies, he said .</s>
</P>
<P>

<s docid="LA020890-0197" num="22" wdcount="25"> Under the proposal for the 1993 game, the city would give up most of the previous sources of revenue and allocate them to the NFL.</s>

<s docid="LA020890-0197" num="23" wdcount="19"> It also would provide 350,000 square feet of space for the league to build a hospitality tent compound .</s>
</P>
<P>

<s docid="LA020890-0197" num="24" wdcount="29"> The city would receive about $79,000 from seat taxes, $75,000 in hotel and sales taxes arising from the event and a share of about $55,000 in parking fees .</s>
</P>
<P>

<s docid="LA020890-0197" num="25" wdcount="7"> The board has approved the proposal .</s>
</P>
<P>

<s docid="LA020890-0197" num="26" wdcount="35"> The Rose Bowl, meanwhile, has proposed an $8.3-million project to renovate the press box and restructure about 1,000 seats for club seating, with an adjacent lounge, restaurant, hall of fame museum and gift shop .</s>
</P>
<P>

<s docid="LA020890-0197" num="27" wdcount="6"> SUPER BOWLS AT COLISEUM, ROSE BOWL</s>
</P>
<TABLE>
<ROWRULE>
</ROWRULE>
<TABLEROW>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="28" wdcount="2"> No .</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="29" wdcount="1"> Year</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="30" wdcount="1"> Site</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="31" wdcount="1"> Result</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
</TABLEROW>
<ROWRULE>
</ROWRULE>
<TABLEROW>
<CELLRULE>
</CELLRULE>
<TABLECELL>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>
</TABLECELL>
<CELLRULE>
</CELLRULE>
</TABLEROW>
<ROWRULE>
</ROWRULE>
<TABLEROW>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="32" wdcount="1"> I</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="33" wdcount="1"> 1967</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="34" wdcount="1"> Coliseum</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="35" wdcount="5"> Green Bay 35, K.C. 10</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
</TABLEROW>
<ROWRULE>
</ROWRULE>
<TABLEROW>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="36" wdcount="1"> VII</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="37" wdcount="1"> 1973</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="38" wdcount="1"> Coliseum</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="39" wdcount="4"> Miami 14, Washington 7</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
</TABLEROW>
<ROWRULE>
</ROWRULE>
<TABLEROW>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="40" wdcount="1"> XI</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="41" wdcount="1"> 1977</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="42" wdcount="2"> Rose Bowl</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="43" wdcount="4"> Raiders 32, Minnesota 14</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
</TABLEROW>
<ROWRULE>
</ROWRULE>
<TABLEROW>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="44" wdcount="1"> XIV</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="45" wdcount="1"> 1980</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="46" wdcount="2"> Rose Bowl</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="47" wdcount="4"> Pittsburgh 31, Rams 19</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
</TABLEROW>
<ROWRULE>
</ROWRULE>
<TABLEROW>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="48" wdcount="1"> XVII</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="49" wdcount="1"> 1983</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="50" wdcount="2"> Rose Bowl</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="51" wdcount="4"> Washington 27, Miami 17</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
</TABLEROW>
<ROWRULE>
</ROWRULE>
<TABLEROW>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="52" wdcount="1"> XXI</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="53" wdcount="1"> 1987</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="54" wdcount="2"> Rose Bowl</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="55" wdcount="5"> N.Y. Giants 39, Denver 20</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
</TABLEROW>
<ROWRULE>
</ROWRULE>
</TABLE>
<P>
</P>
<P>
</P>
<P>

<s docid="LA020890-0197" num="56" wdcount="3"> UPCOMING SUPER BOWLS</s>
</P>
<TABLE>
<ROWRULE>
</ROWRULE>
<TABLEROW>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="57" wdcount="2"> No .</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="58" wdcount="1"> Year</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="59" wdcount="1"> Site</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
</TABLEROW>
<ROWRULE>
</ROWRULE>
<TABLEROW>
<CELLRULE>
</CELLRULE>
<TABLECELL>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>
</TABLECELL>
<CELLRULE>
</CELLRULE>
</TABLEROW>
<ROWRULE>
</ROWRULE>
<TABLEROW>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="60" wdcount="1"> XXV</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="61" wdcount="1"> 1991</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="62" wdcount="2"> Tampa Bay</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
</TABLEROW>
<ROWRULE>
</ROWRULE>
<TABLEROW>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="63" wdcount="1"> XXVI</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="64" wdcount="1"> 1992</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
<TABLECELL>

<s docid="LA020890-0197" num="65" wdcount="1"> Minneapolis</s>
</TABLECELL>
<CELLRULE>
</CELLRULE>
</TABLEROW>
<ROWRULE>
</ROWRULE>
</TABLE>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA020890-0197" num="66" wdcount="11"> Table, SUPER BOWLS AT COLISEUM, ROSE BOWL; Table, UPCOMING SUPER BOWLS</s>
</P>
</GRAPHIC>
<TYPE>
<P>

<s docid="LA020890-0197" num="67" wdcount="1"> List</s>
</P>
</TYPE>
<SUBJECT>
<P>

<s docid="LA020890-0197" num="68" wdcount="18"> SUPER BOWL (FOOTBALL GAME); ROSE BOWL (STADIUM); LOS ANGELES SPORTS COUNCIL; NATIONAL FOOTBALL LEAGUE; PASADENA (CA) -- ATHLETICS</s>
</P>
</SUBJECT>
</DOC>
