<DOC>
<DOCNO>

<s docid="SJMN91-06025182" num="1" wdcount="1"> SJMN91-06025182</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06025182" num="2" wdcount="1"> 06025182</s>
</ACCESS>
<DESCRIPT>

<s docid="SJMN91-06025182" num="3" wdcount="5"> PROFESSIONAL; FOOTBALL; CHAMPIONSHIP; GAME; STATISTIC</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06025182" num="4" wdcount="12"> (box) AT STAKE: National Football League Championship for the Vince Lombardi Trophy.</s>

<s docid="SJMN91-06025182" num="5" wdcount="6"> (box) SITE: Tampa Stadium, Tampa, Fla.</s>

<s docid="SJMN91-06025182" num="6" wdcount="14"> This is the second time the game will be played at Tampa Stadium .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06025182" num="7" wdcount="2"> Special Section</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06025182" num="8" wdcount="5"> SUPER BOWL FACTS AND FIGURES</s>
</HEADLINE>
<MEMO>

<s docid="SJMN91-06025182" num="9" wdcount="6"> Super Bowl XXV: A Viewer's Guide</s>
</MEMO>
<TEXT>

<s docid="SJMN91-06025182" num="10" wdcount="4"> (box) SEATING CAPACITY: 74,315.</s>

<s docid="SJMN91-06025182" num="11" wdcount="7"> (box) KICKOFF: 3:18 p.m. Pacific Standard Time.</s>

<s docid="SJMN91-06025182" num="12" wdcount="10"> (box) PLAYERS SHARE: The winners will get $36,000 per man.</s>

<s docid="SJMN91-06025182" num="13" wdcount="7"> The losers will get $18,000 per man.</s>

<s docid="SJMN91-06025182" num="14" wdcount="20"> (box) SUDDEN DEATH: If the game is tied at regulation time 60 minutes, it will continue in sudden death overtime.</s>

<s docid="SJMN91-06025182" num="15" wdcount="12"> The team scoring first (by safety, field goal, or touchdown) will win.</s>

<s docid="SJMN91-06025182" num="16" wdcount="26"> At the end of regulation playing time, the referee will immediately toss a coin at midfield, in accordance with rules pertaining to the usual pregame toss.</s>

<s docid="SJMN91-06025182" num="17" wdcount="12"> The captain of AFC team (the visiting team) will call the toss.</s>

<s docid="SJMN91-06025182" num="18" wdcount="30"> Following a three-minute intermission after the end of the regular game, play will continue by 15-minute periods with a two-minute intermission between each such overtime period with no halftime intermission.</s>

<s docid="SJMN91-06025182" num="19" wdcount="20"> The teams will change goals between each period, there will be a two-minute warning at the end of each period.</s>

<s docid="SJMN91-06025182" num="20" wdcount="32"> (box) TROPHY: The winning team receives permanent possession of the Vince Lombardi Trophy, a sterling silver trophy created by Tiffany & Company and presented annually to the winner of the Super Bowl.</s>

<s docid="SJMN91-06025182" num="21" wdcount="24"> The trophy was named after the late coach Vince Lombardi of the two-time Super Bowl champion Green Bay Packers prior to Super Bowl V.</s>

<s docid="SJMN91-06025182" num="22" wdcount="20"> The trophy is a regulation silver football mounted in a kicking position on a pyramid-like stand of three concave sides.</s>

<s docid="SJMN91-06025182" num="23" wdcount="17"> The trophy stands 20 3/4 inches tall, weighs 6.7 pounds and is valued in excess of $10,000.</s>

<s docid="SJMN91-06025182" num="24" wdcount="18"> The words "Vince Lombardi" and "Super Bowl XXIV" are engraved on the base along with the NFL emblem.</s>

<s docid="SJMN91-06025182" num="25" wdcount="10"> (box) ATTENDANCE: To date, 1,953,690 have attended Super Bowl games.</s>

<s docid="SJMN91-06025182" num="26" wdcount="17"> The largest crowd was 103,985 at the 14th Super Bowl at the Rose Bowl in Pasadena .</s>
</TEXT>
<COUNTRY>

<s docid="SJMN91-06025182" num="27" wdcount="1"> USA</s>
</COUNTRY>
<EDITION>

<s docid="SJMN91-06025182" num="28" wdcount="2"> Morning Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06025182" num="29" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06025182" num="30" wdcount="4"> SAN JOSE MERCURY NEWS</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06025182" num="31" wdcount="1"> 910125</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06025182" num="32" wdcount="1"> Friday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06025182" num="33" wdcount="1"> January</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06025182" num="34" wdcount="1"> 26D</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06025182" num="35" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06025182" num="36" wdcount="1"> WEST</s>
</REGION>
<STATE>

<s docid="SJMN91-06025182" num="37" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06025182" num="38" wdcount="1"> 328</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06025182" num="39" wdcount="5"> Friday January 25, 1991 00025182,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06025182" num="40" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06025182" num="41" wdcount="1"> 1</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06025182" num="42" wdcount="1"> ENG</s>
</LANGUAGE>
</DOC>
