<DOC>
<DOCNO>

<s docid="WSJ870122-0100" num="1" wdcount="1"> WSJ870122-0100</s>
</DOCNO>
<HL>

<s docid="WSJ870122-0100" num="2" wdcount="19"> Your Money Matters: Business as Usual At Super Bowl -- Despite Tax Bill --- By Earl C. Gottschalk Jr.</s>

<s docid="WSJ870122-0100" num="3" wdcount="7"> Staff Reporter of The Wall Street Journal</s>
</HL>
<DD>

<s docid="WSJ870122-0100" num="4" wdcount="1"> 01/22/87</s>
</DD>
<SO>

<s docid="WSJ870122-0100" num="5" wdcount="4"> WALL STREET JOURNAL (J)</s>
</SO>
<IN>

<s docid="WSJ870122-0100" num="6" wdcount="1"> TAXES</s>
</IN>
<TEXT>

<s docid="WSJ870122-0100" num="7" wdcount="19"> Sports Illustrated is taking 300 advertisers to Super Bowl XXI in Pasadena, Calif., this weekend for an all-out bash.</s>

<s docid="WSJ870122-0100" num="8" wdcount="32"> Along with getting seats for Sunday's game, the guests will brunch at the chic Spago restaurant, take a private tour of Universal Studios and attend a wing-ding at the Century Plaza Hotel.</s>

<s docid="WSJ870122-0100" num="9" wdcount="23"> The magazine is just one of hundreds of businesses whose officials and customers will be among the 104,000 fans attending the Super Bowl.</s>

<s docid="WSJ870122-0100" num="10" wdcount="28"> And the companies show few signs of cutting back on their activities despite the new tax law's tighter restrictions on what can be claimed as a business-entertainment expense.</s>

<s docid="WSJ870122-0100" num="11" wdcount="46"> Still, the new rules do change things for a variety of Super Bowl entertaining -- from an executive sitting in a $1,500 seat on the 50-yard line to a businessman holding a Super Bowl party in his living room and hoping to write off the costs.</s>

<s docid="WSJ870122-0100" num="12" wdcount="31"> One big change under the new law limits business-entertainment deductions for tickets to sporting events like the Super Bowl: Only 80% of the face value of such tickets can be deducted.</s>

<s docid="WSJ870122-0100" num="13" wdcount="28"> If a company purchases a a 50-yard-line seat for $1,500 -- the going rate -- it can deduct only 80% of the ticket's $75 face value, or $60.</s>

<s docid="WSJ870122-0100" num="14" wdcount="34"> Even to get the 80% deduction, there still must be a "substantial and bona fide business discussion" before, during or after the game, says Julian Block, a tax specialist at Prentice-Hall Information Services Inc.</s>

<s docid="WSJ870122-0100" num="15" wdcount="19"> To take a client to a game as merely a good-will gesture is no longer enough, Mr. Block says.</s>

<s docid="WSJ870122-0100" num="16" wdcount="26"> And if a company wants to simply give clients tickets to the game, the business gift carries a total deduction of only $25 for each recipient.</s>

<s docid="WSJ870122-0100" num="17" wdcount="16"> The tougher IRS rule, however, hasn't slowed ticket demand; even end-zone seats are fetching $500 each.</s>

<s docid="WSJ870122-0100" num="18" wdcount="35"> "Even if it weren't tax deductible, it'd be worth it," says Tom Foley, chairman of Bibb Co., a Macon, Ga., maker of home furnishings and textile products that use the National Football League team logos.</s>

<s docid="WSJ870122-0100" num="19" wdcount="13"> Bibb is flying about 20 people -- mostly customers -- to the game.</s>

<s docid="WSJ870122-0100" num="20" wdcount="13"> "We get more earnings from the trip than the expense," says Mr. Foley.</s>

<s docid="WSJ870122-0100" num="21" wdcount="17"> Some companies say they are making adjustments or at least educating their executives about the new rules.</s>

<s docid="WSJ870122-0100" num="22" wdcount="31"> A spokesman for Adolph Coors & Co, the Golden, Colo., brewery, said its tax advisers instructed executives that "this can't be just a fun trip -- we have to discuss business".</s>

<s docid="WSJ870122-0100" num="23" wdcount="22"> Air fare and lodging are still 100% deductible, as long as there is a planned business meeting in addition to the game.</s>

<s docid="WSJ870122-0100" num="24" wdcount="11"> Meals are now 80% deductible as long as business is discussed.</s>

<s docid="WSJ870122-0100" num="25" wdcount="23"> Under the old law, meals were fully deductible and all a company had to do was show a business relationship with the guest.</s>

<s docid="WSJ870122-0100" num="26" wdcount="21"> Companies can get a 100% deduction for a pre-Super Bowl banquet, since the new tax law has a "banquet meeting exception".</s>

<s docid="WSJ870122-0100" num="27" wdcount="21"> Such meetings must have at least 40 persons, half of whom are away from home, and there must be a speaker.</s>

<s docid="WSJ870122-0100" num="28" wdcount="38"> Executives who bring clients over to the house to watch the Super Bowl on television also face new restrictions on deductions for food and liquor, says William J. Lipton, tax partner of the accounting firm Ernst & Whinney.</s>

<s docid="WSJ870122-0100" num="29" wdcount="24"> If a host wants to deduct 80% of the bill, he or she must talk business with all of the guests, Mr. Lipton says.</s>

<s docid="WSJ870122-0100" num="30" wdcount="10"> One safety measure: Make a business-oriented speech, Mr. Block suggests.</s>

<s docid="WSJ870122-0100" num="31" wdcount="15"> He also advises party hosts to keep a guest list and note their business connection.</s>

<s docid="WSJ870122-0100" num="32" wdcount="47"> That will be a big job for Barron Hilton, chairman of Hilton Hotels Corp., who along with Alex Spanos, owner of the San Diego Chargers, is holding a pre-Super Bowl brunch Sunday at the Beverly Hilton Hotel for 1,800 guests including business leaders, entertainment personalities and customers.</s>

<s docid="WSJ870122-0100" num="33" wdcount="25"> Allen Hermansen, a Hilton senior vice president, says the bash is tax deductible because "our sales people will be there and business will be discussed".</s>

<s docid="WSJ870122-0100" num="34" wdcount="10"> He admits, however, "We're not going to twist any arms.</s>

<s docid="WSJ870122-0100" num="35" wdcount="11"> We're there to say thank-you to those who've given us business".</s>

<s docid="WSJ870122-0100" num="36" wdcount="17"> An IRS spokesman says more agents will be assigned to corporate audits of business-entertainment expenses this year.</s>

<s docid="WSJ870122-0100" num="37" wdcount="18"> But IRS enforcement of the rules could be as difficult as blocking the New York Giants' Lawrence Taylor.</s>

<s docid="WSJ870122-0100" num="38" wdcount="31"> "As a practical matter, as long as people say they talked business at a Super Bowl party, how can the IRS dispute it"? says Vickie King, a Price Waterhouse tax official.</s>

<s docid="WSJ870122-0100" num="39" wdcount="15"> "The only people who will get into trouble are those who don't keep receipts" .</s>
</TEXT>
</DOC>
