<DOC>
<DOCNO>

<s docid="FBIS4-26392" num="1" wdcount="1"> FBIS4-26392</s>
</DOCNO>
<HT>

<s docid="FBIS4-26392" num="2" wdcount="1"> "drchi120_k_94007"</s>
</HT>
<HEADER>
<AU>

<s docid="FBIS4-26392" num="3" wdcount="1"> FBIS-CHI-94-120</s>
</AU>

<s docid="FBIS4-26392" num="4" wdcount="2"> Daily Report</s>
<DATE1>

<s docid="FBIS4-26392" num="5" wdcount="3"> 21 Jun 1994</s>
</DATE1>
</HEADER>
<F>

<s docid="FBIS4-26392" num="6" wdcount="2"> NATIONAL AFFAIRS</s>
</F>
<F>

<s docid="FBIS4-26392" num="7" wdcount="4"> Political \|[amp ]\| Social</s>
</F>
<H3>
<TI>

<s docid="FBIS4-26392" num="8" wdcount="4"> Water Level `Dropping Slowly'</s>
</TI>
</H3>
<HT>
<F>
<PHRASE>

<s docid="FBIS4-26392" num="9" wdcount="4"> Water Level `Dropping Slowly'</s>
</PHRASE>
</F>
</HT>
<F>

<s docid="FBIS4-26392" num="10" wdcount="12"> OW2106144594 Beijing XINHUA Domestic Service in Chinese 1020 GMT 21 Jun 94</s>
</F>
<F>

<s docid="FBIS4-26392" num="11" wdcount="1"> OW2106144594</s>
</F>
<F>

<s docid="FBIS4-26392" num="12" wdcount="4"> Beijing XINHUA Domestic Service</s>
</F>
<F>

<s docid="FBIS4-26392" num="13" wdcount="1"> Chinese</s>
</F>
<TEXT>

<s docid="FBIS4-26392" num="14" wdcount="70"> BFN [Text] Beijing, 21 Jun (XINHUA) -- According to the State Flood Control and Drought Relief Headquarters, after the largest or the second largest flood peaks since the liberation of China occurred a few days ago in the Xi Jiang, Bei Jiang, Xiang Jiang, and Gan Jiang rivers, water levels in these rivers are dropping slowly; however, high water levels will remain in these rivers for the next few days.</s>

<s docid="FBIS4-26392" num="15" wdcount="19"> Due to interaction of the Bei Jiang and Xi Jiang, the Zhujiang Delta will face a high water-level test.</s>

<s docid="FBIS4-26392" num="16" wdcount="29"> Heavy rainfall over a wide area since mid-June resulted in the largest flood waters since liberation of the country in the Xi Jiang, Bei Jiang, and Xiang Jiang rivers.</s>

<s docid="FBIS4-26392" num="17" wdcount="28"> The flood water in Guangdong's Xi Jiang crested in Gaoyao County on 20 June; the water level in Gaoyao's Xi Jiang dropped to 13.37 meters at 0600 today.</s>

<s docid="FBIS4-26392" num="18" wdcount="29"> A flood peak occured in Bei Jiang in Guangdong's Sanshui at 0400 on 20 June, raising the water level to 10.39 meters -- the largest flood level ever recorded.</s>

<s docid="FBIS4-26392" num="19" wdcount="10"> The water level droppped to 10.16 meters at 0600 today.</s>

<s docid="FBIS4-26392" num="20" wdcount="57"> Drops in water levels in Guangdong's Bei Jiang and Xi Jiang do not mean that Guangdong's flooding situations have eased, because flood waters in the Xi Jiang and Bei Jiang will remain at high levels for quite long a period and will enter the sea after the two flood waters jointly flow through the low-lying Zhujiang Delta.</s>

<s docid="FBIS4-26392" num="21" wdcount="14"> In particular, the sea tide may add to the flood waters on 25 June.</s>

<s docid="FBIS4-26392" num="22" wdcount="31"> With these factors combined, the Zhujiang Delta, which has a developed economy and a forest of factories, will face the most rigorous flood water test since the liberation of the country.</s>

<s docid="FBIS4-26392" num="23" wdcount="12"> The situation in the Xiang Jiang is also not an easy one.</s>

<s docid="FBIS4-26392" num="24" wdcount="28"> The flood peak passed Changsha on 19 June, but the water level at the Changsha Station was still at 25 meters at 0200 today [1800 GMT 20 June].</s>

<s docid="FBIS4-26392" num="25" wdcount="20"> Because the water level has remained high for a long period, several dangerous situations have occured along the river's dikes.</s>

<s docid="FBIS4-26392" num="26" wdcount="8"> Dike reinforcing work needs to be stepped up.</s>

<s docid="FBIS4-26392" num="27" wdcount="12"> The flood peak in Gan Jiang entered Boyang Lake on 20 June.</s>

<s docid="FBIS4-26392" num="28" wdcount="25"> However, due to continued rains over the last few days, the water level in the upper reaches west of Ganzhou has begun to rise again.</s>

<s docid="FBIS4-26392" num="29" wdcount="20"> At 0800 today, the water level at the Ganzhou Station was 100.95 meters, 3.45 meters above the warning level .</s>
</TEXT>
</DOC>
