<DOC>
<DOCNO>

<s docid="FBIS4-26516" num="1" wdcount="1"> FBIS4-26516</s>
</DOCNO>
<HT>

<s docid="FBIS4-26516" num="2" wdcount="1"> "drchi121_o_94002"</s>
</HT>
<HEADER>
<AU>

<s docid="FBIS4-26516" num="3" wdcount="1"> FBIS-CHI-94-121</s>
</AU>

<s docid="FBIS4-26516" num="4" wdcount="2"> Daily Report</s>
<DATE1>

<s docid="FBIS4-26516" num="5" wdcount="3"> 22 Jun 1994</s>
</DATE1>
</HEADER>
<F>

<s docid="FBIS4-26516" num="6" wdcount="2"> REGIONAL AFFAIRS</s>
</F>
<F>

<s docid="FBIS4-26516" num="7" wdcount="2"> East Region</s>
</F>
<H3>
<TI>

<s docid="FBIS4-26516" num="8" wdcount="5"> Fujian Governor Addresses Flood Teleconference</s>
</TI>
</H3>
<HT>
<F>
<PHRASE>

<s docid="FBIS4-26516" num="9" wdcount="5"> Fujian Governor Addresses Flood Teleconference</s>
</PHRASE>
</F>
</HT>
<H4>

<s docid="FBIS4-26516" num="10" wdcount="4"> Heavy Agricultural Losses Incurred</s>
</H4>
<F>

<s docid="FBIS4-26516" num="11" wdcount="12"> HK2306021994 Beijing ZHONGGUO XINWEN SHE in English 1328 GMT 22 Jun 94</s>
</F>
<F>

<s docid="FBIS4-26516" num="12" wdcount="1"> HK2306021994</s>
</F>
<F>

<s docid="FBIS4-26516" num="13" wdcount="4"> Beijing ZHONGGUO XINWEN SHE</s>
</F>
<F>

<s docid="FBIS4-26516" num="14" wdcount="1"> English</s>
</F>
<TEXT>

<s docid="FBIS4-26516" num="15" wdcount="25"> BFN [Text] Fuzhou, June 22 (CNS) -- Flood lasting for ten or more days in Fujian Province has brought about heavy losses in agriculture there.</s>

<s docid="FBIS4-26516" num="16" wdcount="58"> According to the latest information offered by the Provincial Agricultural Bureau, a total area of 2.465 million mu of crops have been hit by the flood and of which, 446 000 mu of crops will have no yield, 1.957 million mu of grain have been heavily hit and some 300 million kilogram grain are expected to be lost.</s>

<s docid="FBIS4-26516" num="17" wdcount="21"> Among nine cities and prefectures in Fujian, those seriously hit by the flood are Sanming, Nanping, Ningde, Fuzhou, Quanzhou and Putian.</s>

<s docid="FBIS4-26516" num="18" wdcount="10"> Of these, Sanming City is worst hit by the flood.</s>

<s docid="FBIS4-26516" num="19" wdcount="41"> In May, the city was hit by the heavy rainstorm and had big losses and now it suffers again from the flood with some 600 000 mu of crops damaged by flood and 200 million kilogram grain expected to be lost.</s>

<s docid="FBIS4-26516" num="20" wdcount="12"> Per capita possession of cultivated land in Fujian is only 0.05 mu.</s>

<s docid="FBIS4-26516" num="21" wdcount="13"> Even if in the normal years, grain output there is not self- sufficient.</s>

<s docid="FBIS4-26516" num="22" wdcount="11"> The consecutive flood has made agricultural production situation there more grim.</s>

<s docid="FBIS4-26516" num="23" wdcount="14"> Disaster-relief groups have been sent to the flood-stricken areas striving for minimizing losses .</s>
</TEXT>
</DOC>
