<DOC>
<DOCNO>

<s docid="FBIS4-26242" num="1" wdcount="1"> FBIS4-26242</s>
</DOCNO>
<HT>

<s docid="FBIS4-26242" num="2" wdcount="1"> "drchi119_p_94002"</s>
</HT>
<HEADER>
<AU>

<s docid="FBIS4-26242" num="3" wdcount="1"> FBIS-CHI-94-119</s>
</AU>

<s docid="FBIS4-26242" num="4" wdcount="2"> Daily Report</s>
<DATE1>

<s docid="FBIS4-26242" num="5" wdcount="3"> 19 Jun 1994</s>
</DATE1>
</HEADER>
<F>

<s docid="FBIS4-26242" num="6" wdcount="2"> Central-South Region</s>
</F>
<H3>
<TI>

<s docid="FBIS4-26242" num="7" wdcount="5"> Reportage On Provincial Flood Situation</s>
</TI>
</H3>
<HT>
<F>
<PHRASE>

<s docid="FBIS4-26242" num="8" wdcount="5"> Reportage On Provincial Flood Situation</s>
</PHRASE>
</F>
</HT>
<H4>

<s docid="FBIS4-26242" num="9" wdcount="4"> Flood Hits Hunan Capital</s>
</H4>
<F>

<s docid="FBIS4-26242" num="10" wdcount="10"> OW1906141294 Beijing XINHUA in English 1351 GMT 19 Jun 94</s>
</F>
<F>

<s docid="FBIS4-26242" num="11" wdcount="1"> OW1906141294</s>
</F>
<F>

<s docid="FBIS4-26242" num="12" wdcount="2"> Beijing XINHUA</s>
</F>
<F>

<s docid="FBIS4-26242" num="13" wdcount="1"> English</s>
</F>
<TEXT>

<s docid="FBIS4-26242" num="14" wdcount="37"> BFN [Text] Changsha, June 19 (XINHUA) -- This capital of central China's Hunan province has been hit by floods in the wake of a succession of rainstorms on the upper and middle reaches of the Xiangjiang River.</s>

<s docid="FBIS4-26242" num="15" wdcount="18"> The water level of the river, which flows through Changsha, is still rising sharply, according to local sources.</s>

<s docid="FBIS4-26242" num="16" wdcount="29"> By four o'clock this afternoon the level recorded at the Changsha monitoring station had risen to 38.93 m, some 0.56 m higher than the highest figure ever previously recorded.</s>

<s docid="FBIS4-26242" num="17" wdcount="21"> The flood has caused serious losses to people along both banks of the river, especially in Changsha, according to the sources.</s>

<s docid="FBIS4-26242" num="18" wdcount="21"> In the early hours of yesterday six villages and one fishing ground at Yulushan township were flooded when an embankment collapsed.</s>

<s docid="FBIS4-26242" num="19" wdcount="16"> Most of the 15,000 people affected by the flood there have been evacuated to safer places.</s>

<s docid="FBIS4-26242" num="20" wdcount="25"> By six o'clock yesterday afternoon 19 dykes in the Changsha area had collapsed, and a total of 128,000 urban and rural residents had been affected.</s>

<s docid="FBIS4-26242" num="21" wdcount="30"> A partial collapse of the grand Longwangang embankment at the Xihu fishing ground in the Wangyuehu district of Changsha has put the lives and property of 60,000 people in danger.</s>

<s docid="FBIS4-26242" num="22" wdcount="20"> But thanks to the concerted rescue efforts of 2,000 local cadres, residents and soldiers there was no loss of life.</s>

<s docid="FBIS4-26242" num="23" wdcount="31"> The city government of Changsha has asked residents within the endangered areas to relocate themselves and remove their property to safer places, in case of the occurrence of more serious flooding.</s>

<s docid="FBIS4-26242" num="24" wdcount="19"> By the early hours of this morning roads and surfaces of bridges in the Wangyuehu district had been inundated.</s>

<s docid="FBIS4-26242" num="25" wdcount="24"> The flood waters had also reached the boulevard along the Xiangjiang River, Xiahe Street and the western part of Zhongshan Street in Changsha proper.</s>

<s docid="FBIS4-26242" num="26" wdcount="17"> So far, more than 500,000 soldiers and local residents have moved in to help fight the floods.</s>

<s docid="FBIS4-26242" num="27" wdcount="40"> Meanwhile, the Changsha city committee of the Communist Party has held an emergency meeting, urging all departments and the people of the whole city to carry forward the spirit of continuous fighting and unite as one in battling the floods.</s>

<s docid="FBIS4-26242" num="28" wdcount="24"> Wang Maolin, secretary of the Hunan Provincial Party Committee, who is now in the province's southern city of Zhuzhou to direct anti-flood efforts there.</s>

<s docid="FBIS4-26242" num="29" wdcount="44"> In a telephone call to the Changsha city government, he called on local officials to adopt effective measures, ensure the safety of the lives and property of the residents of Changsha and make an overall success of the work to conquer the flood .</s>
</TEXT>
</DOC>
