<DOC>
<DOCNO>

<s docid="FBIS4-26769" num="1" wdcount="1"> FBIS4-26769</s>
</DOCNO>
<HT>

<s docid="FBIS4-26769" num="2" wdcount="1"> "drchi123_k_94007"</s>
</HT>
<HEADER>
<AU>

<s docid="FBIS4-26769" num="3" wdcount="1"> FBIS-CHI-94-123</s>
</AU>

<s docid="FBIS4-26769" num="4" wdcount="2"> Daily Report</s>
<DATE1>

<s docid="FBIS4-26769" num="5" wdcount="3"> 26 Jun 1994</s>
</DATE1>
</HEADER>
<F>

<s docid="FBIS4-26769" num="6" wdcount="2"> NATIONAL AFFAIRS</s>
</F>
<F>

<s docid="FBIS4-26769" num="7" wdcount="4"> Political \|[amp ]\| Social</s>
</F>
<H3>
<TI>

<s docid="FBIS4-26769" num="8" wdcount="7"> Wen Jiabao, Spokesman Comment on Flood Situation</s>
</TI>
</H3>
<HT>
<F>
<PHRASE>

<s docid="FBIS4-26769" num="9" wdcount="7"> Wen Jiabao, Spokesman Comment on Flood Situation</s>
</PHRASE>
</F>
</HT>
<F>

<s docid="FBIS4-26769" num="10" wdcount="10"> OW2606142694 Beijing XINHUA in English 1401 GMT 26 Jun 94</s>
</F>
<F>

<s docid="FBIS4-26769" num="11" wdcount="1"> OW2606142694</s>
</F>
<F>

<s docid="FBIS4-26769" num="12" wdcount="2"> Beijing XINHUA</s>
</F>
<F>

<s docid="FBIS4-26769" num="13" wdcount="1"> English</s>
</F>
<TEXT>

<s docid="FBIS4-26769" num="14" wdcount="42"> BFN [Text] Beijing, June 26 (XINHUA) -- Floods have all receded along Xijiang, Beijiang, Xiangjiang and Ganjiang except at a section of the Xijiang River in Wuzhou city, Guangxi, a spokesman from the State Flood Control and Drought Relief Headquarters announced today.</s>

<s docid="FBIS4-26769" num="15" wdcount="18"> The spokesman attributed the falling water level to the major water conservancy projects which help to mitigate losses.</s>

<s docid="FBIS4-26769" num="16" wdcount="27"> Meanwhile, he said, tension has been eased in the Pearl River delta as the latest tropical storm has been weakened after landing in Yangjiang city, Guangdong Province.</s>

<s docid="FBIS4-26769" num="17" wdcount="31"> Floods hit Guangdong, Guangxi, Hunan, Jiangxi, Fujiang and Zhejiang provinces following the first heavy rains and floods which typically hit China from the south to the north from June to August.</s>

<s docid="FBIS4-26769" num="18" wdcount="38"> Earlier reports said that successive torrential rainstorms in the Xijiang and Beijiang river valleys in early and mid-June resulted in a big flood, one of the most serious in 100 years, in Guangdong Province and caused heavy losses.</s>

<s docid="FBIS4-26769" num="19" wdcount="20"> Major flood monitoring stations on the two rivers recorded their highest water levels, all four meters above the warning level.</s>

<s docid="FBIS4-26769" num="20" wdcount="42"> In an urgent conference late yesterday, the Guangdong provincial government urged localities to help flood victims with food, shelter, clothing and medical care so that no one would die of hunger and no epidemic disease would break out in the flooded areas.</s>

<s docid="FBIS4-26769" num="21" wdcount="36"> The province has allocated 300 million kg of grain and 110 million yuan in cash along with over 10 million tons of such farm production supplies as chemical fertilizer and diesel oil to the flood-stricken areas.</s>

<s docid="FBIS4-26769" num="22" wdcount="23"> Meanwhile, 740 million yuan in loans and another 50 million yuan in donations have also been sent to flooded areas in Guangdong Province.</s>

<s docid="FBIS4-26769" num="23" wdcount="53"> While inspecting flood control and relief work in Jiangxi Province, through which the Ganjiang flows, Wen Jiabao, alternate member of the Political Bureau and member of the Secretariat of the CPC Central Committee, said the flooded areas should work hard to mitigate losses through their own efforts and with support from various departments.</s>

<s docid="FBIS4-26769" num="24" wdcount="33"> While inspecting Nanchang, the capital city of Jiangxi, and Fengcheng, Xingang, Jian and Taihe, on June 24-26, Wen said the key to mitigating economic losses is to resume production as soon as possible.</s>

<s docid="FBIS4-26769" num="25" wdcount="19"> The localities should waste no time in implementing various measures to resume production and rehabilitate their homeland, he said.</s>

<s docid="FBIS4-26769" num="26" wdcount="19"> As one of China's major bread baskets, Jiangxi is of key importance to China in agricultural production, Wen said.</s>

<s docid="FBIS4-26769" num="27" wdcount="12"> It has a direct bearing on the grain supply in south China.</s>

<s docid="FBIS4-26769" num="28" wdcount="11"> He urged the local governments to farmers resume agricultural production .</s>
</TEXT>
</DOC>
