<DOC>
<DOCNO>

<s docid="FBIS4-26604" num="1" wdcount="1"> FBIS4-26604</s>
</DOCNO>
<HT>

<s docid="FBIS4-26604" num="2" wdcount="1"> "drchi122_p_94001"</s>
</HT>
<HEADER>
<AU>

<s docid="FBIS4-26604" num="3" wdcount="1"> FBIS-CHI-94-122</s>
</AU>

<s docid="FBIS4-26604" num="4" wdcount="2"> Daily Report</s>
<DATE1>

<s docid="FBIS4-26604" num="5" wdcount="3"> 23 Jun 1994</s>
</DATE1>
</HEADER>
<F>

<s docid="FBIS4-26604" num="6" wdcount="2"> REGIONAL AFFAIRS</s>
</F>
<F>

<s docid="FBIS4-26604" num="7" wdcount="2"> Central-South Region</s>
</F>
<H3>
<TI>

<s docid="FBIS4-26604" num="8" wdcount="9"> Over 200 Dead, 11 Million Affected by Guangdong Flood</s>
</TI>
</H3>
<HT>
<F>
<PHRASE>

<s docid="FBIS4-26604" num="9" wdcount="9"> Over 200 Dead, 11 Million Affected by Guangdong Flood</s>
</PHRASE>
</F>
</HT>
<H4>

<s docid="FBIS4-26604" num="10" wdcount="4"> Highest `Peaks' Have Passed</s>
</H4>
<F>

<s docid="FBIS4-26604" num="11" wdcount="10"> OW2306150994 Beijing XINHUA in English 1448 GMT 23 Jun 94</s>
</F>
<F>

<s docid="FBIS4-26604" num="12" wdcount="1"> OW2306150994</s>
</F>
<F>

<s docid="FBIS4-26604" num="13" wdcount="2"> Beijing XINHUA</s>
</F>
<F>

<s docid="FBIS4-26604" num="14" wdcount="1"> English</s>
</F>
<TEXT>

<s docid="FBIS4-26604" num="15" wdcount="28"> BFN [Text] Guangzhou, June 23 (XINHUA) -- The highest flood peaks on the Xijiang and Beijiang Rivers have passed, said Zhu Senlin, governor of south China's Guangdong Province.</s>

<s docid="FBIS4-26604" num="16" wdcount="43"> While inspecting flood control and relief work in Qingyuan city on the Beijiang River yesterday, he attributed Guangdong's success in combating this flood -- almost the biggest in 100 years -- to concerted efforts by the armymen stationed in Guangdong and local residents.</s>

<s docid="FBIS4-26604" num="17" wdcount="22"> More than 200 people lost their lives in the natural disaster, which destroyed 189,000 rooms and ruined crops on 1.2 million hectares.</s>

<s docid="FBIS4-26604" num="18" wdcount="20"> The flood was caused by successive torrential rainstorms in the Xijiang and Beijiang River valleys in early and middle June.</s>

<s docid="FBIS4-26604" num="19" wdcount="20"> Major flood monitoring stations on the two rivers recorded their highest water levels, all four meters above the danger mark.</s>

<s docid="FBIS4-26604" num="20" wdcount="32"> Local governments at various levels in the province have paid close attention to flood control work, and leading government and communist party officials of different localities have gone to the flood-fighting front.</s>

<s docid="FBIS4-26604" num="21" wdcount="33"> No breaches of major embankments or reservoirs were reported despite the most serious flood in a hundred years, effectively protecting the safety of the provincial capital, Guangzhou, and the Pearl (Zhujiang) River Delta.</s>

<s docid="FBIS4-26604" num="22" wdcount="13"> But the losses caused by the flood were quite serious, said the governor.</s>

<s docid="FBIS4-26604" num="23" wdcount="37"> According to him, 11 million people in the province's nine cities and 55 counties were affected, and more than 200 people died in the natural disaster, with 189,000 rooms destroyed and 1.2 million hectares of crops ruined.</s>

<s docid="FBIS4-26604" num="24" wdcount="10"> The direct economic losses were set at 10.2 billion yuan.</s>

<s docid="FBIS4-26604" num="25" wdcount="43"> The governor warned that though the flood danger had receded, the determination to fight possible further floods could not slacken, as this is just the beginning: the main flood season, which usually begins in late July and early August, has not yet arrived.</s>

<s docid="FBIS4-26604" num="26" wdcount="44"> He urged local officials to be on constant alert against further possible floods and be meticulous about flood prevention and control measures, while doing their utmost to help flood victims, assisting them to resume production as soon as possible and maintaining social stability .</s>
</TEXT>
</DOC>
