<DOC>
<DOCNO>

<s docid="FBIS4-26327" num="1" wdcount="1"> FBIS4-26327</s>
</DOCNO>
<HT>

<s docid="FBIS4-26327" num="2" wdcount="1"> "drchi119_k_94004"</s>
</HT>
<HEADER>
<AU>

<s docid="FBIS4-26327" num="3" wdcount="1"> FBIS-CHI-94-119</s>
</AU>

<s docid="FBIS4-26327" num="4" wdcount="2"> Daily Report</s>
<DATE1>

<s docid="FBIS4-26327" num="5" wdcount="3"> 19 Jun 1994</s>
</DATE1>
</HEADER>
<F>

<s docid="FBIS4-26327" num="6" wdcount="2"> NATIONAL AFFAIRS</s>
</F>
<F>

<s docid="FBIS4-26327" num="7" wdcount="4"> Political \|[amp ]\| Social</s>
</F>
<H3>
<TI>

<s docid="FBIS4-26327" num="8" wdcount="8"> Jiang Zemin, Li Peng Express Concern Over Floods</s>
</TI>
</H3>
<HT>
<F>
<PHRASE>

<s docid="FBIS4-26327" num="9" wdcount="8"> Jiang Zemin, Li Peng Express Concern Over Floods</s>
</PHRASE>
</F>
</HT>
<F>

<s docid="FBIS4-26327" num="10" wdcount="12"> OW2106062894 Beijing XINHUA Domestic Service in Chinese 1629 GMT 19 Jun 94</s>
</F>
<F>

<s docid="FBIS4-26327" num="11" wdcount="1"> OW2106062894</s>
</F>
<F>

<s docid="FBIS4-26327" num="12" wdcount="4"> Beijing XINHUA Domestic Service</s>
</F>
<F>

<s docid="FBIS4-26327" num="13" wdcount="1"> Chinese</s>
</F>
<TEXT>

<s docid="FBIS4-26327" num="14" wdcount="42"> BFN [Text] Guangzhou, 19 Jun (XINHUA) -- Jiang Zemin, general secretary of the CPC Central Committee Political Bureau and chairman of the Central Military Commission, and Li Peng, premier of the State Council, are very much concerned about floods in Guangdong Province.</s>

<s docid="FBIS4-26327" num="15" wdcount="21"> Recently, they repeatedly inquired about the flood situation in the Zhu Jiang valley, particularly that of Bei Jiang and Xi Jiang.</s>

<s docid="FBIS4-26327" num="16" wdcount="51"> They expressed their deep concern for the people in the flood-hit areas, as well as extended their warm greetings to the vast number of cadres, officers, and men of the People's Liberation Army; armed police officers; and public security police who battle on the frontline against floods and provide disaster relief.</s>

<s docid="FBIS4-26327" num="17" wdcount="18"> Jiang Zemin and Li Peng gave important directives for current flood prevention and disaster relief tasks in Guangdong.</s>

<s docid="FBIS4-26327" num="18" wdcount="60"> They expressed the hope that under the leadership of the Guangdong provincial party committee and government, the Guangdong army and people would make concerted efforts in disaster relief; earnestly help flood victims solve their living problems; and go all out to battle floods to ensure the safety of the Bei Jiang dike, Guangzhou city, and the Zhu Jiang Delta .</s>
</TEXT>
</DOC>
