<DOC>
<DOCNO>

<s docid="FBIS4-26532" num="1" wdcount="1"> FBIS4-26532</s>
</DOCNO>
<HT>

<s docid="FBIS4-26532" num="2" wdcount="1"> "drchi121_p_94008"</s>
</HT>
<HEADER>
<AU>

<s docid="FBIS4-26532" num="3" wdcount="1"> FBIS-CHI-94-121</s>
</AU>

<s docid="FBIS4-26532" num="4" wdcount="2"> Daily Report</s>
<DATE1>

<s docid="FBIS4-26532" num="5" wdcount="3"> 22 Jun 1994</s>
</DATE1>
</HEADER>
<F>

<s docid="FBIS4-26532" num="6" wdcount="2"> Central-South Region</s>
</F>
<H3>
<TI>

<s docid="FBIS4-26532" num="7" wdcount="7"> Hunan Flood Control Work, Relief Efforts Underway</s>
</TI>
</H3>
<HT>
<F>
<PHRASE>

<s docid="FBIS4-26532" num="8" wdcount="7"> Hunan Flood Control Work, Relief Efforts Underway</s>
</PHRASE>
</F>
</HT>
<H4>

<s docid="FBIS4-26532" num="9" wdcount="4"> Wen Jiabao Inspects Area</s>
</H4>
<F>

<s docid="FBIS4-26532" num="10" wdcount="13"> HK2306093394 Changsha Hunan People's Radio Network in Mandarin 2300 GMT 22 Jun 94</s>
</F>
<F>

<s docid="FBIS4-26532" num="11" wdcount="1"> HK2306093394</s>
</F>
<F>

<s docid="FBIS4-26532" num="12" wdcount="5"> Changsha Hunan People's Radio Network</s>
</F>
<F>

<s docid="FBIS4-26532" num="13" wdcount="1"> Mandarin</s>
</F>
<TEXT>

<s docid="FBIS4-26532" num="14" wdcount="21"> BFN [Text] Comrade Wen Jiabao [member of CPC Central Committee Secretariat] and his party left Changsha for Zhuzhou and Xiangtan yesterday.</s>

<s docid="FBIS4-26532" num="15" wdcount="36"> He inspected the flooded areas, including Zhuzhou City's Xiawan dike, the Hexi New and High Technology Development Zone, and Linghuayuan and Xiangtan's Yangtianhu, Xingxiadi, Zhoujiangdi, and Shiwandalou, where rescue and relief work was in full swing.</s>

<s docid="FBIS4-26532" num="16" wdcount="24"> After listening to reports submitted by the two cities on their efforts to fight the flooding and do relief work, he issued important instructions.</s>

<s docid="FBIS4-26532" num="17" wdcount="31"> Comrade Wen Jiabao fully affirmed the initial victories that the two cities have scored in their flood fighting and relief work under the leadership of the provincial party committee and government.</s>

<s docid="FBIS4-26532" num="18" wdcount="50"> He said: In fighting floods and doing relief work, the broad masses of cadres and people in Zhuzhou and Xiangtan sacrificed their interests to rescue a large number of industrial and mining enterprises, the Beijing-Guangzhou Railway, the 107 National Highway, and cities and thus minimized the losses caused by floods.</s>

<s docid="FBIS4-26532" num="19" wdcount="19"> This fully shows that, with party leadership and the socialist system, we will be able to overcome all difficulties.</s>

<s docid="FBIS4-26532" num="20" wdcount="51"> Regarding the work in the next stage, he pointed out: We should continue to take flood fighting and relief tasks as the focus of our current work and simultaneously do a good job of reform, opening up to the outside world, stability, other fields of work, and industrial and agricultural production.</s>

<s docid="FBIS4-26532" num="21" wdcount="19"> He said: After the water recedes, we should firmly grasp the opportunity and repair the damaged dikes and embankments.</s>

<s docid="FBIS4-26532" num="22" wdcount="27"> As the highest flood season has not yet arrived, we should be prepared at any time to meet new flood peaks head-on rather than slacken our efforts.</s>

<s docid="FBIS4-26532" num="23" wdcount="36"> We should try every possible means to provide food, clothing, and shelter to flood victims, pay special attention to preventing and curing diseases, and concentrate efforts on the resumption of production and the reconstruction of homes.</s>

<s docid="FBIS4-26532" num="24" wdcount="20"> He particularly stressed: The current flooding has revealed problems in the construction of water conservancy facilities and urban flood control.</s>

<s docid="FBIS4-26532" num="25" wdcount="21"> In the past, inadequate consideration has been given to urban flood control and the coordination of urban and rural flood control.</s>

<s docid="FBIS4-26532" num="26" wdcount="14"> In the next step, we should earnestly draw a lesson from this negative experience.</s>

<s docid="FBIS4-26532" num="27" wdcount="76"> Governor Chen Bangzhu urged the party committees and governments of Zhuzhou and Xiangtan to convey Comrade Wen Jiabao's regards and instructions on behalf of the party Central Committee and the State Council for the broad masses of cadres and people to the party committees and governments at all levels as soon as possible, earnestly implement them, and effectively carry out the work of fighting floods, doing relief work, and helping oneself by engaging in production .</s>
</TEXT>
</DOC>
