<DOC>
<DOCNO>

<s docid="FBIS4-26245" num="1" wdcount="1"> FBIS4-26245</s>
</DOCNO>
<HT>

<s docid="FBIS4-26245" num="2" wdcount="1"> "drchi119_p_94005"</s>
</HT>
<HEADER>
<AU>

<s docid="FBIS4-26245" num="3" wdcount="1"> FBIS-CHI-94-119</s>
</AU>

<s docid="FBIS4-26245" num="4" wdcount="2"> Daily Report</s>
<DATE1>

<s docid="FBIS4-26245" num="5" wdcount="3"> 20 Jun 1994</s>
</DATE1>
</HEADER>
<F>

<s docid="FBIS4-26245" num="6" wdcount="2"> Central-South Region</s>
</F>
<H3>
<TI>

<s docid="FBIS4-26245" num="7" wdcount="5"> Reportage On Provincial Flood Situation</s>
</TI>
</H3>
<HT>
<F>
<PHRASE>

<s docid="FBIS4-26245" num="8" wdcount="5"> Reportage On Provincial Flood Situation</s>
</PHRASE>
</F>
</HT>
<H4>

<s docid="FBIS4-26245" num="9" wdcount="5"> Floods Continue in Guangdong, Hunan</s>
</H4>
<F>

<s docid="FBIS4-26245" num="10" wdcount="10"> OW2006171394 Beijing XINHUA in English 1503 GMT 20 Jun 94</s>
</F>
<F>

<s docid="FBIS4-26245" num="11" wdcount="1"> OW2006171394</s>
</F>
<F>

<s docid="FBIS4-26245" num="12" wdcount="2"> Beijing XINHUA</s>
</F>
<F>

<s docid="FBIS4-26245" num="13" wdcount="1"> English</s>
</F>
<TEXT>

<s docid="FBIS4-26245" num="14" wdcount="28"> BFN [Text] Beijing, June 20 (XINHUA) -- Floods continue to have serious effects in Guangdong, Hunan and Jiangxi Provinces and the Guangxi Zhuang Autonomous Region in southern China.</s>

<s docid="FBIS4-26245" num="15" wdcount="23"> Information from the State Flood Control and Drought Relief Headquarters revealed that the flood peak on the Xijiang River today reached Guangdong Province.</s>

<s docid="FBIS4-26245" num="16" wdcount="31"> By eight o'clock yesterday morning, a peak flood water level of 25.91 m [meters] was recorded at the flood monitoring station of Guangxi's Wuzhou city, 10.91 m above the danger level.</s>

<s docid="FBIS4-26245" num="17" wdcount="23"> Flood water has entered urban and suburban areas of Wuzhou city, and most of its transport and telecommunications with the outside were suspended.</s>

<s docid="FBIS4-26245" num="18" wdcount="20"> This city borders Guangdong and lies on the Xunjiang River, the name for the upper reaches of the Xijiang River.</s>

<s docid="FBIS4-26245" num="19" wdcount="25"> The speed of the flood-water was recorded as 46,200 cu [cubic] m per second, the most ferocious since the founding of New China in 1949.</s>

<s docid="FBIS4-26245" num="20" wdcount="43"> The flood peak on the Beijiang River in Guangdong Province passed through Qingyuan city by 23:00 hours last night, and the water level was recorded as 14.72 m, about 4.22 m above the danger mark; the speed was 17,400 cu m per second.</s>

<s docid="FBIS4-26245" num="21" wdcount="14"> Flood control work in the Pearl River (Zhujiang) Delta area is also very intense.</s>

<s docid="FBIS4-26245" num="22" wdcount="33"> The State Council, China's highest governing body, recently sent a joint working group formed by the Ministries of Water Resources, Construction and Civil Affairs to help fight floods in Guangxi and in Guangdong.</s>

<s docid="FBIS4-26245" num="23" wdcount="22"> At 11 o'clock on Saturday, the flood peak on the Xiangjiang River passed through Changsha city, capital of central China's Hunan Province.</s>

<s docid="FBIS4-26245" num="24" wdcount="18"> The water level recorded at the local monitoring station was 38.93 m, some 3.93 m above danger level.</s>

<s docid="FBIS4-26245" num="25" wdcount="12"> High flood water levels were also recorded at Hengyang and Xiangtan cities.</s>

<s docid="FBIS4-26245" num="26" wdcount="14"> About 118 towns of eight prefectures and cities along the Xiangjiang River were flooded.</s>

<s docid="FBIS4-26245" num="27" wdcount="21"> Flood water has also entered more than 20 streets and lanes of Changsha, and more than 300,000 city dwellers were affected.</s>

<s docid="FBIS4-26245" num="28" wdcount="15"> More than 400 factories and 5,000 shops were forced to stop production or stop business.</s>

<s docid="FBIS4-26245" num="29" wdcount="31"> More than half a million Armymen and local residents, under the leadership of the Hunan provincial party provincial committee and provincial people's government, are going all out to fight the flood.</s>

<s docid="FBIS4-26245" num="30" wdcount="16"> By 22:00 hours last night, the flood peak passed through Nanchang city, provincial capital of Jiangxi.</s>

<s docid="FBIS4-26245" num="31" wdcount="34"> Statistics from the local monitoring station show that the flood water level was 25.42 m, about 2.62 m above the danger mark, and the speed of the flood was 19,100 cu m per second.</s>

<s docid="FBIS4-26245" num="32" wdcount="21"> The Jiangxi provincial party committee and people's government are mobilizing local people and the troops stationed there to combat the floods.</s>

<s docid="FBIS4-26245" num="33" wdcount="22"> The State Flood Control and Drought Relief Headquarters has sent special teams of people to help fight floods in Hunan and Jiangxi.</s>

<s docid="FBIS4-26245" num="34" wdcount="22"> Meanwhile, drought is continuing to blight most areas of northern China and northeastern China, with about 15.3 million hectares of land affected.</s>

<s docid="FBIS4-26245" num="35" wdcount="29"> In the drought-stricken areas, 12 million people and 12 million head of livestock are short of drinking water, according to the State Flood Control and Drought Relief Headquarters .</s>
</TEXT>
</DOC>
