<DOC>
<DOCNO>

<s docid="FBIS4-26614" num="1" wdcount="1"> FBIS4-26614</s>
</DOCNO>
<HT>

<s docid="FBIS4-26614" num="2" wdcount="1"> "drchi122_p_94011"</s>
</HT>
<HEADER>
<AU>

<s docid="FBIS4-26614" num="3" wdcount="1"> FBIS-CHI-94-122</s>
</AU>

<s docid="FBIS4-26614" num="4" wdcount="2"> Daily Report</s>
<DATE1>

<s docid="FBIS4-26614" num="5" wdcount="3"> 20 Jun 1994</s>
</DATE1>
</HEADER>
<F>

<s docid="FBIS4-26614" num="6" wdcount="2"> REGIONAL AFFAIRS</s>
</F>
<F>

<s docid="FBIS4-26614" num="7" wdcount="2"> Central-South Region</s>
</F>
<H3>
<TI>

<s docid="FBIS4-26614" num="8" wdcount="6"> Hunan Governor Interviewed on Flood Situation</s>
</TI>
</H3>
<HT>
<F>
<PHRASE>

<s docid="FBIS4-26614" num="9" wdcount="6"> Hunan Governor Interviewed on Flood Situation</s>
</PHRASE>
</F>
</HT>
<F>

<s docid="FBIS4-26614" num="10" wdcount="13"> HK2306115194 Changsha Hunan People's Radio Network in Mandarin 2300 GMT 20 Jun 94</s>
</F>
<F>

<s docid="FBIS4-26614" num="11" wdcount="1"> HK2306115194</s>
</F>
<F>

<s docid="FBIS4-26614" num="12" wdcount="5"> Changsha Hunan People's Radio Network</s>
</F>
<F>

<s docid="FBIS4-26614" num="13" wdcount="1"> Mandarin</s>
</F>
<TEXT>

<s docid="FBIS4-26614" num="14" wdcount="25"> BFN [Text] The following is a recorded report filed by this station's reporter on the front lines of the province's battle against the flooding yesterday.</s>

<s docid="FBIS4-26614" num="15" wdcount="12"> [Begin recording] Dear audience, it is now almost noon on 20 June.</s>

<s docid="FBIS4-26614" num="16" wdcount="11"> I'm reporting in Changshanyuan at the eastern gate of Changsha City.</s>

<s docid="FBIS4-26614" num="17" wdcount="41"> This morning, Provincial Party Committee Secretary Wang Maolin, provincial Governor Chen Bangzhu, and some other provincial party and government leaders arrived here in Changshayuan, on the front line of the province's flood resistance effort, to direct the fight against the flooding.</s>

<s docid="FBIS4-26614" num="18" wdcount="23"> Governor Chen Bangzhu and vice Governor Zheng Peimin just arrived back in Changsha at about 0700 this morning after attending a Beijing meeting.</s>

<s docid="FBIS4-26614" num="19" wdcount="22"> As soon as they stepped out from the train, they set out for Changshayuan, the front line of the province's flood resistance.</s>

<s docid="FBIS4-26614" num="20" wdcount="9"> I interviewed Governor Chen Bangzhu here on the spot.</s>

<s docid="FBIS4-26614" num="21" wdcount="6"> [Reporter] How are you, Governor Chen?</s>

<s docid="FBIS4-26614" num="22" wdcount="11"> You have inspected some flood-stricken areas in Changsha City this morning.</s>

<s docid="FBIS4-26614" num="23" wdcount="12"> Will you please tell our audience something about the province's flood situation?</s>

<s docid="FBIS4-26614" num="24" wdcount="27"> [Governor] This year, Hunan has been hit by a flood of a severity unseen for the past 100 years in terms of both water level and quantity.</s>

<s docid="FBIS4-26614" num="25" wdcount="57"> Over the past few days, the broad masses of Army personnel and people across the province have been bravely fighting the flood and have been making concerted efforts to provide disaster relief to afflicted areas, with the result that some of the province's key dams have remained sound and economic losses have been reduced to a minimum.</s>

<s docid="FBIS4-26614" num="26" wdcount="35"> I would like to take this opportunity to extend my warm regards and thanks to the broad masses of Army personnel and people fighting in the front lines of the province's battle against the flood.</s>

<s docid="FBIS4-26614" num="27" wdcount="17"> At the moment, the province's flood situation remains very serious, because the water level is still high.</s>

<s docid="FBIS4-26614" num="28" wdcount="20"> According to weather forecasts and meteorological reports, the province is expecting more rain to fall over the next few days.</s>

<s docid="FBIS4-26614" num="29" wdcount="8"> We will definitely encounter more hardships and difficulties.</s>

<s docid="FBIS4-26614" num="30" wdcount="40"> Under the current circumstances, the broad masses of Army personnel and people across the province should further step up their work and devote more energy to flood prevention and disaster relief work, this being an overriding task at the moment.</s>

<s docid="FBIS4-26614" num="31" wdcount="63"> We are full of confidence that, under the leadership of the CPC Central Committee and the State Council, the broad masses of the Hunan Army personnel and people will be able to overcome the difficulties and hardships caused by natural calamities such as flooding, waterlogging, and so on and will win a complete victory in the on-going flood prevention and disaster relief struggle.</s>

<s docid="FBIS4-26614" num="32" wdcount="2"> [end recording]</s>
</TEXT>
</DOC>
