<DOC>
<DOCNO>

<s docid="FBIS4-26768" num="1" wdcount="1"> FBIS4-26768</s>
</DOCNO>
<HT>

<s docid="FBIS4-26768" num="2" wdcount="1"> "drchi123_k_94006"</s>
</HT>
<HEADER>
<AU>

<s docid="FBIS4-26768" num="3" wdcount="1"> FBIS-CHI-94-123</s>
</AU>

<s docid="FBIS4-26768" num="4" wdcount="2"> Daily Report</s>
<DATE1>

<s docid="FBIS4-26768" num="5" wdcount="3"> 24 Jun 1994</s>
</DATE1>
</HEADER>
<F>

<s docid="FBIS4-26768" num="6" wdcount="2"> NATIONAL AFFAIRS</s>
</F>
<F>

<s docid="FBIS4-26768" num="7" wdcount="4"> Political \|[amp ]\| Social</s>
</F>
<H3>
<TI>

<s docid="FBIS4-26768" num="8" wdcount="7"> Wen Jiabao Inspects Flood Situation in Jiangxi</s>
</TI>
</H3>
<HT>
<F>
<PHRASE>

<s docid="FBIS4-26768" num="9" wdcount="7"> Wen Jiabao Inspects Flood Situation in Jiangxi</s>
</PHRASE>
</F>
</HT>
<F>

<s docid="FBIS4-26768" num="10" wdcount="12"> OW2506172894 Beijing XINHUA Domestic Service in Chinese 1632 GMT 24 Jun 94</s>
</F>
<F>

<s docid="FBIS4-26768" num="11" wdcount="1"> OW2506172894</s>
</F>
<F>

<s docid="FBIS4-26768" num="12" wdcount="4"> Beijing XINHUA Domestic Service</s>
</F>
<F>

<s docid="FBIS4-26768" num="13" wdcount="1"> Chinese</s>
</F>
<TEXT>

<s docid="FBIS4-26768" num="14" wdcount="1"> BFN</s>
<F>

<s docid="FBIS4-26768" num="15" wdcount="10"> [By JIANGXI RIBAO reporter Zhang Wei (1728 3555) and XINHUA</s>
</F>

<s docid="FBIS4-26768" num="16" wdcount="62"> reporter Wu Huaguo (0702 5478 0948)] [Text] Nanchang, 24 Jun (XINHUA) -- A central work team led Wen Jiabao, alternate member of the CPC Central Committee Political Bureau and member of the CPC Central Committee Secretariat, arrived in Jiangxi from Hunan this morning to provide on-the-spot guideance for Jiangxi to conduct flood-fighting and relief work and to resume industrial and agricultural production.</s>

<s docid="FBIS4-26768" num="17" wdcount="61"> Immediately after disembarking from the plane, Wen Jiabao and his party -- accompanied by Mao Zhiyong, secretary of the Jiangxi Provincial Party Committee, and Governor Wu Guanzheng -- successively rushed to the Nanchang Bridge, the Leigongao construction work site along the Nanchang-Jiujiang Highway which is reserved for vehicles, Weidong Village under Changling Town in Xinjian County, and Houtian Township's Sanzhou Village.</s>

<s docid="FBIS4-26768" num="18" wdcount="33"> They inspected the flood situation along the Ganjiang River, visited the masses of flood victims, and extended greetings and appreciation to the servicemembers and civilians who have been performing rescue and emergency tasks.</s>

<s docid="FBIS4-26768" num="19" wdcount="30"> The same evening, Wen Jiabao and his party earnestly listened to reports by the Jiangxi Provincial Party Committee and government on Jiangxi's flood situation and its flood-fighting and relief work.</s>

<s docid="FBIS4-26768" num="20" wdcount="32"> Wen Jiabao highly commended Jiangxi's servicemembers and people for their spirit that stresses fostering unity and coordinated efforts, striving to help and rescue themselves, and continually fighting when encountering extraordinarily disastrous floods.</s>

<s docid="FBIS4-26768" num="21" wdcount="13"> He also fully affirmed Jiangxi's preliminary victories in its flood-fighting and relief work.</s>

<s docid="FBIS4-26768" num="22" wdcount="26"> Wen Jiabao pointed out: At present, the Ganjiang River's water-level is declining, but the Jiangxi Provincial Party Committee and government are still facing very arduous tasks.</s>

<s docid="FBIS4-26768" num="23" wdcount="46"> While continually and properly conducting flood-fighting and relief work along the Ganjiang River valleys, we should stress flood-prevention in the Poyang Lake area and should promptly organize the masses in the disaster-stricken areas to resume production so as to be self-reliant and to rebuild their homes.</s>

<s docid="FBIS4-26768" num="24" wdcount="6"> Jiangxi is a major agricultural province.</s>

<s docid="FBIS4-26768" num="25" wdcount="38"> We should take measures to promptly salvage the early-ripening rice, and should expand the planting of late-ripening rice and autumn grain as much as possible so as to attain a bumper harvest of grain for the whole year.</s>

<s docid="FBIS4-26768" num="26" wdcount="23"> While carrying out flood-fighting and relief work, we should also continually and properly handle various tasks concerning reform, stability, and development in Jiangxi.</s>

<s docid="FBIS4-26768" num="27" wdcount="30"> It has been learned that on 25 June Wen Jiabao and his party will visit other localities including Xingan, Fengcheng, and Jian where the flooding has been the most serious.</s>

<s docid="FBIS4-26768" num="28" wdcount="17"> They will further inspect the flood situation and extend sympathy and solicitude to flood victims there .</s>
</TEXT>
</DOC>
