<DOC>
<DOCNO>

<s docid="AP900425-0198" num="1" wdcount="1"> AP900425-0198</s>
</DOCNO>
<FILEID>

<s docid="AP900425-0198" num="2" wdcount="2"> AP-NR-04-25-90 2047EDT</s>
</FILEID>
<FIRST>

<s docid="AP900425-0198" num="3" wdcount="7"> r a AM-SpaceShuttle 3rdLd-Writethru a0742 04-25 0887</s>
</FIRST>
<SECOND>

<s docid="AP900425-0198" num="4" wdcount="5"> AM-Space Shuttle, 3rd Ld-Writethru, a0742,0912</s>
</SECOND>
<HEAD>

<s docid="AP900425-0198" num="5" wdcount="8"> Balky Telescope Released into Space, Starts 15-Year Voyage</s>
</HEAD>
<NOTE>

<s docid="AP900425-0198" num="6" wdcount="14"> Eds: Subs the 24th graf, ``Wojtalik said...,' to RESTORE first reference to Wojtalik .</s>
</NOTE>
<HEAD>

<s docid="AP900425-0198" num="7" wdcount="2"> LaserPhoto HTN1,6,9</s>
</HEAD>
<BYLINE>

<s docid="AP900425-0198" num="8" wdcount="3"> By MARCIA DUNN</s>
</BYLINE>
<BYLINE>

<s docid="AP900425-0198" num="9" wdcount="3"> AP Aerospace Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900425-0198" num="10" wdcount="4"> CAPE CANAVERAL, Fla. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900425-0198" num="11" wdcount="35"> After years of delay and a last-minute snag, the Hubble Space Telescope was freed from the shuttle Discovery on Wednesday and, glinting in the sunlight, drifted into orbit on its 15-year search for new worlds.</s>

<s docid="AP900425-0198" num="12" wdcount="27"> Mission specialist Steven Hawley released Hubble from the end of the shuttle's 50-foot-long mechanical arm after a delay in getting one of the telescope's solar wings unfurled.</s>

<s docid="AP900425-0198" num="13" wdcount="22"> ``The first of NASA's great observatories is now on station at 330 nautical miles above the Earth,'' Mission Control's Jeffrey Carr said.</s>

<s docid="AP900425-0198" num="14" wdcount="26"> ``The telescope really looked great as we flew away from it, and we sure hope it does good work,'' Discovery commander Loren J. Shriver said later.</s>

<s docid="AP900425-0198" num="15" wdcount="28"> The $1.5 billion telescope was released at 3:38 p.m. EDT as the shuttle entered its 20th orbit of Earth, nearly two hours and one orbit later than planned.</s>

<s docid="AP900425-0198" num="16" wdcount="5"> The shuttle then backed away.</s>

<s docid="AP900425-0198" num="17" wdcount="22"> ``Thank you very much for the ride,'' said Mike Harrington, director of orbital verifications at Goddard Space Flight Center in Greenbelt, Md.</s>

<s docid="AP900425-0198" num="18" wdcount="22"> Mission specialists Bruce McCandless and Kathryn Sullivan had been in the shuttle's airlock, ready to walk inspace to free the solar panel.</s>

<s docid="AP900425-0198" num="19" wdcount="5"> That proved to be unnecessary.</s>

<s docid="AP900425-0198" num="20" wdcount="18"> ``Close but no cigar, but better for the Hubble that it went the way it did,'' Sullivan said.</s>

<s docid="AP900425-0198" num="21" wdcount="15"> She and McCandless had trained for nearly five years to make such a rescue mission.</s>

<s docid="AP900425-0198" num="22" wdcount="27"> The first solar array unreeled from its mast at midday Wednesday as the shuttle passed 380 statute miles, or 330 nautical miles, above South America's eastern coast.</s>

<s docid="AP900425-0198" num="23" wdcount="16"> It started providing power to the telescope's batteries, which otherwise had only eight hours of charge.</s>

<s docid="AP900425-0198" num="24" wdcount="9"> Deployment of the starboard panel, however, was more troublesome.</s>

<s docid="AP900425-0198" num="25" wdcount="20"> It wouldn't budge when latches were first released, then moved about a fifth of its 39-foot length, and stopped again.</s>

<s docid="AP900425-0198" num="26" wdcount="10"> A third attempt rolled the panel out all the way.</s>

<s docid="AP900425-0198" num="27" wdcount="9"> ``Houston, we see motion,'' Commander Loren J. Shriver reported.</s>

<s docid="AP900425-0198" num="28" wdcount="32"> Hawley began the long process of releasing Hubble shortly after 7 a.m. EDT when he grasped it with Discovery's 50-foot-long mechanical arm and carefully hoisted the 12-ton telescope high above the shuttle.</s>

<s docid="AP900425-0198" num="29" wdcount="25"> Hubble was taken off shuttle electrical power just before it was lifted out of the cargo bay and was operating on its own nickel-hydrogen batteries.</s>

<s docid="AP900425-0198" num="30" wdcount="20"> ``At one day, seven minutes into the flight of Discovery, Hubble is now on its own internal power,'' Carr said.</s>

<s docid="AP900425-0198" num="31" wdcount="4"> ``The game has begun.</s>

<s docid="AP900425-0198" num="32" wdcount="4"> The race is on.</s>

<s docid="AP900425-0198" num="33" wdcount="4"> The clock is ticking''.</s>

<s docid="AP900425-0198" num="34" wdcount="19"> Worries that the telescope's instruments would be starved for electricity eased after the first solar panel was stretched out.</s>

<s docid="AP900425-0198" num="35" wdcount="28"> Television cameras aboard Discovery showed the first array as it was pulled from its reel slowly but steadily, the sun reflecting off the gold-colored panel and silvery telescope.</s>

<s docid="AP900425-0198" num="36" wdcount="16"> Discovery was 380 statute miles above Earth, 70 miles higher than any shuttle has ever flown.</s>

<s docid="AP900425-0198" num="37" wdcount="16"> The orbit was dictated by the need to put the telescope above the Earth's distorting atmosphere.</s>

<s docid="AP900425-0198" num="38" wdcount="8"> Discovery's five astronauts were awed by the view.</s>

<s docid="AP900425-0198" num="39" wdcount="31"> ``I'd like to pass on the quote of the day from the on-board astronomer something to the effect that the big marble sure looks far away today,'' Shriver said of Hawley.</s>

<s docid="AP900425-0198" num="40" wdcount="13"> Astronomers have waited seven years for Hubble to take its place in space.</s>

<s docid="AP900425-0198" num="41" wdcount="19"> The telescope originally was scheduled for launch in 1983, but technical problems and the Challenger explosion pushed it back.</s>

<s docid="AP900425-0198" num="42" wdcount="34"> The mission was delayed another two weeks when a faulty power unit on Discovery forced the National Aeronautics and Space Administration to halt the first launch attempt four minutes before April 10's scheduled liftoff.</s>

<s docid="AP900425-0198" num="43" wdcount="18"> On Tuesday, Discovery finally blasted into space, transporting Hubble out of this world and in search of others.</s>

<s docid="AP900425-0198" num="44" wdcount="18"> The telescope's 10-foot aperture door is to be opened Friday, exposing the finely polished 94.5-inch mirror to starlight.</s>

<s docid="AP900425-0198" num="45" wdcount="12"> Discovery was following Hubble in case the door does not open properly.</s>

<s docid="AP900425-0198" num="46" wdcount="16"> If a problem develops, McCandless and Sullivan will be prepared once again to walk in space.</s>

<s docid="AP900425-0198" num="47" wdcount="23"> Fred Wojtalik, Hubble project manager, said the telescope would be tested Thursday for its ability to maneuever before the aperture door is opened.</s>

<s docid="AP900425-0198" num="48" wdcount="25"> ``We want to be in full control so we don't ever endanger the Hubble by putting the aperture door close to the sunlight,'' he said.</s>

<s docid="AP900425-0198" num="49" wdcount="15"> The telescope cannot focus into the sun because of the sensitivity of its five instruments.</s>

<s docid="AP900425-0198" num="50" wdcount="15"> If all goes well, the crew will land Sunday at Edwards Air Force Base, Calif.</s>

<s docid="AP900425-0198" num="51" wdcount="23"> NASA expects to release its first image from the telescope _ of an open star cluster in the constellation Carina _ on Tuesday.</s>

<s docid="AP900425-0198" num="52" wdcount="8"> Data will follow in a month or two.</s>

<s docid="AP900425-0198" num="53" wdcount="29"> Astronomers hope to look back to almost the beginning of the time, studying stars and galaxies so distant their light has been traveling to Earth for 14 billion years.</s>

<s docid="AP900425-0198" num="54" wdcount="19"> They expect to determine precisely how and when the universe was formed, currently estimated at 15 billion years ago.</s>

<s docid="AP900425-0198" num="55" wdcount="22"> The telescope is named for the late American astronomer Edwin P. Hubble, who discovered during the 1920s that the universe was expanding.</s>

<s docid="AP900425-0198" num="56" wdcount="15"> He also was responsible for helping to form the Big Bang theory of creation .</s>
</TEXT>
</DOC>
