<DOC>
<DOCNO>

<s docid="AP900421-0075" num="1" wdcount="1"> AP900421-0075</s>
</DOCNO>
<FILEID>

<s docid="AP900421-0075" num="2" wdcount="2"> AP-NR-04-21-90 1625EDT</s>
</FILEID>
<FIRST>

<s docid="AP900421-0075" num="3" wdcount="7"> u a AM-SpaceShuttle 2ndLd-Writethru a0533 04-21 0809</s>
</FIRST>
<SECOND>

<s docid="AP900421-0075" num="4" wdcount="7"> AM-Space Shuttle, 2nd Ld - Writethru, a0533,0824</s>
</SECOND>
<HEAD>

<s docid="AP900421-0075" num="5" wdcount="7"> NASA, Scientists Eagerly Await Second Launch Attempt</s>
</HEAD>
<NOTE>

<s docid="AP900421-0075" num="6" wdcount="8"> Eds: SUBS 2nd graf to add launch time.</s>

<s docid="AP900421-0075" num="7" wdcount="6"> Picks up 3rd graf, `We are...'.</s>

<s docid="AP900421-0075" num="8" wdcount="5"> Should stand for AMs .</s>
</NOTE>
<BYLINE>

<s docid="AP900421-0075" num="9" wdcount="3"> By MARCIA DUNN</s>
</BYLINE>
<BYLINE>

<s docid="AP900421-0075" num="10" wdcount="3"> AP Aerospace Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900421-0075" num="11" wdcount="4"> CAPE CANAVERAL, Fla. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900421-0075" num="12" wdcount="35"> Two weeks after a failed launch attempt, an improved Discovery is ready to embark on one of the most momentous shuttle missions, hoisting the Hubble Space Telescope high enough to behold the threshold of time.</s>

<s docid="AP900421-0075" num="13" wdcount="14"> The countdown began Saturday afternoon for a launch set for 8:31 a.m. EDT Tuesday.</s>

<s docid="AP900421-0075" num="14" wdcount="21"> If the launch goes on schedule and all else goes well, the first picture from Hubble could be available next weekend.</s>

<s docid="AP900421-0075" num="15" wdcount="7"> ``We are as excited, maybe even more.</s>

<s docid="AP900421-0075" num="16" wdcount="25"> You can cut it with a knife, incredible,'' said Eric Chaisson, senior scientist at the Space Telescope Science Institute at Johns Hopkins University in Baltimore.</s>

<s docid="AP900421-0075" num="17" wdcount="29"> Nothing, at least scientifically, seems to have been lost as a result of the two-week wait, one of numerous delays plaguing the mission since its original 1983 launch date.</s>

<s docid="AP900421-0075" num="18" wdcount="14"> As Chaisson remarked last week: ``The universe has been around for 15 billion years.</s>

<s docid="AP900421-0075" num="19" wdcount="9"> A couple of weeks is not going to matter''.</s>

<s docid="AP900421-0075" num="20" wdcount="7"> ``The heavens look the same to me.</s>

<s docid="AP900421-0075" num="21" wdcount="7"> The secrets are the same,'' Chaisson said.</s>

<s docid="AP900421-0075" num="22" wdcount="14"> ``There's not a bit of difference,'' agreed Charles Pellerin Jr., NASA's director of astrophysics.</s>

<s docid="AP900421-0075" num="23" wdcount="15"> ``I think the main point is the Hubble Space Telescope still is in perfect condition''.</s>

<s docid="AP900421-0075" num="24" wdcount="21"> The $1.5 billion telescope, the most expensive unmanned spacecraft ever built, rests safely inside Discovery's payload bay awaiting the Tuesday launch.</s>

<s docid="AP900421-0075" num="25" wdcount="22"> If all goes well, Discovery will return to Edwards Air Force Base, Calif., on Sunday, April 29, with an empty payload bay.</s>

<s docid="AP900421-0075" num="26" wdcount="28"> NASA said it may release its first telescope image from Hubble _ of an open star cluster in the constellation Carina _ as early as that same day.</s>

<s docid="AP900421-0075" num="27" wdcount="29"> After the early test images are made and other preparatory work is done, Hubble is expected to start providing significant scientific data by satellite in a month or two.</s>

<s docid="AP900421-0075" num="28" wdcount="17"> The observatory is considered the greatest advance in astronomy since Galileo first used a telescope in 1609.</s>

<s docid="AP900421-0075" num="29" wdcount="22"> It also is considered by many at NASA to be the most important shuttle mission to date; it will be the 35th.</s>

<s docid="AP900421-0075" num="30" wdcount="21"> The telescope is named for the late astronomer Edwin P. Hubble, who discovered during the 1920s the universe constantly is expanding.</s>

<s docid="AP900421-0075" num="31" wdcount="20"> His work gave rise to the theory the universe was created by a tremendous explosion about 15 billion years ago.</s>

<s docid="AP900421-0075" num="32" wdcount="30"> From its perch far above Earth's obstructing atmosphere, the telescope will be able to discern objects 50 times fainter and with 10 times greater clarity than the best ground-based observatory.</s>

<s docid="AP900421-0075" num="33" wdcount="17"> Astronomers are counting on Hubble to unravel some of the mystery surrounding quasars, pulsars and black holes.</s>

<s docid="AP900421-0075" num="34" wdcount="40"> By studying stars and galaxies so distant their light has been traveling to Earth for 14 billion years, they hope to determine the precise origin of the universe and learn whether other solar systems _ and life forms _ exist.</s>

<s docid="AP900421-0075" num="35" wdcount="13"> ``If everything goes well, it's going to knock our socks off,'' Chaisson said.</s>

<s docid="AP900421-0075" num="36" wdcount="24"> NASA's sole attempt to launch Discovery was halted four minutes before liftoff April 10 when one of the shuttle's three auxiliary power units failed.</s>

<s docid="AP900421-0075" num="37" wdcount="23"> The 88-pound unit was replaced with a new one, the first time NASA ever had installed such a unit at the launch pad.</s>

<s docid="AP900421-0075" num="38" wdcount="22"> The procedure went so smoothly the space agency decided last week to advance the launch to Tuesday, a day earlier than planned.</s>

<s docid="AP900421-0075" num="39" wdcount="15"> Hubble's six nickel-hydrogen batteries were returned to the telescope Friday following 130 hours of recharging.</s>

<s docid="AP900421-0075" num="40" wdcount="33"> The batteries will power Hubble from the time it is disconnected from Discovery's power system until its energy-collecting solar panels are deployed 380 miles above Earth, the highest a shuttle has ever gone.</s>

<s docid="AP900421-0075" num="41" wdcount="24"> Astronaut Steven A. Hawley will use the shuttle's mechanical arm to lift the 24,250-pound telescope into space on the second day of the mission.</s>

<s docid="AP900421-0075" num="42" wdcount="19"> The telescope's aperture door will be opened on the next to allow the first starlight to strike the mirror.</s>

<s docid="AP900421-0075" num="43" wdcount="18"> Mission specialists Bruce McCandless II and Kathryn Sullivan, veteran spacewalkers, will leave the cabin to assist if necessary.</s>

<s docid="AP900421-0075" num="44" wdcount="24"> The shuttle will follow Hubble from 40 miles away in case a problem develops and the telescope must be retrieved and returned to Earth.</s>

<s docid="AP900421-0075" num="45" wdcount="21"> ``You can never eliminate those oddball quirks of fate or gremlins that may sneak up on any given day,'' Sullivan said.</s>

<s docid="AP900421-0075" num="46" wdcount="12"> ``But those are very remote potentials I really suspect we won't encounter''.</s>

<s docid="AP900421-0075" num="47" wdcount="29"> In addition to the $1.5 billion cost of the telescope, $500 million has been spent to stockpile spare parts, train astronauts and develop computer software to operate the instrument.</s>

<s docid="AP900421-0075" num="48" wdcount="24"> The European Space Agency contributed $250 million to the Hubble project and will get to use the telescope 15 percent of the time .</s>
</TEXT>
</DOC>
