<DOC>
<DOCNO>

<s docid="AP900424-0081" num="1" wdcount="1"> AP900424-0081</s>
</DOCNO>
<FILEID>

<s docid="AP900424-0081" num="2" wdcount="2"> AP-NR-04-24-90 1248EDT</s>
</FILEID>
<FIRST>

<s docid="AP900424-0081" num="3" wdcount="7"> r a AM-Shuttle-Astronomers 1stLd-Writethru a0577 04-24 0349</s>
</FIRST>
<SECOND>

<s docid="AP900424-0081" num="4" wdcount="6"> AM-Shuttle-Astronomers, 1st Ld - Writethru, a0577,330</s>
</SECOND>
<HEAD>

<s docid="AP900424-0081" num="5" wdcount="4"> With AM-Space Shuttle, Bjt</s>
</HEAD>
<HEAD>

<s docid="AP900424-0081" num="6" wdcount="7"> Astronomers Thrilled at Liftoff of Discovery, Telescope</s>
</HEAD>
<NOTE>

<s docid="AP900424-0081" num="7" wdcount="27"> Eds: Top 5 grafs recasts to separate partial quote in lead from full quote, pickup 4th pvs bgng ``Discovery's liftoff'' and deletes last 2 grafs original .</s>
</NOTE>
<BYLINE>

<s docid="AP900424-0081" num="8" wdcount="3"> By RON WORD</s>
</BYLINE>
<BYLINE>

<s docid="AP900424-0081" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900424-0081" num="10" wdcount="4"> CAPE CANAVERAL, Fla. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900424-0081" num="11" wdcount="26"> Jubilant astronomers saw decades of work take wing Tuesday as the Hubble Space Telescope was boosted high above Earth to launch ``a great adventure for mankind''.</s>

<s docid="AP900424-0081" num="12" wdcount="34"> Charles Robert O'Dell, a Rice University space physicist who has worked 19 years on Hubble, said seeing it hurled into orbit aboard the shuttle capped an experience that was ``comparable to raising a child.</s>

<s docid="AP900424-0081" num="13" wdcount="10"> I've been with the program since it was a concept.</s>

<s docid="AP900424-0081" num="14" wdcount="22"> ``There is nothing better than to see 19 years of my work and five of my friends thrust into orbit,'' he said.</s>

<s docid="AP900424-0081" num="15" wdcount="34"> Colin Norman, a physics and astronomy professor at Johns Hopkins University and academic affairs director of the Space Telescope Science Institute there, called the launch ``the perfect start to a great adventure for mankind.</s>

<s docid="AP900424-0081" num="16" wdcount="4"> ``It was incredibly beautiful.</s>

<s docid="AP900424-0081" num="17" wdcount="16"> The power of the launch was awesome and the telescope has an awesome power,'' Norman said.</s>

<s docid="AP900424-0081" num="18" wdcount="12"> Discovery's liftoff was especially gratifying since it ended seven years of delays.</s>

<s docid="AP900424-0081" num="19" wdcount="21"> The $1.5 billion telescope originally was scheduled for launch in 1983 but remained grounded by technical problems and the Challenger explosion.</s>

<s docid="AP900424-0081" num="20" wdcount="21"> Two weeks ago when hundreds of scientists crowded into the Kennedy Space Center, the launch was scrubbed four minutes before liftoff.</s>

<s docid="AP900424-0081" num="21" wdcount="14"> Only a few dozen of them returned Tuesday, but they were just as excited.</s>

<s docid="AP900424-0081" num="22" wdcount="8"> ``There were times when we were deeply depressed.</s>

<s docid="AP900424-0081" num="23" wdcount="24"> There were times when we were elated'' about Hubble's progress, said William H. Jeffreys, a University of Texas astronomer and Hubble's astrometry project leader.</s>

<s docid="AP900424-0081" num="24" wdcount="2"> Jeffreys said.</s>

<s docid="AP900424-0081" num="25" wdcount="12"> ``This is one of those times when we are thrilled beyond belief''.</s>

<s docid="AP900424-0081" num="26" wdcount="28"> Ed Weiler, NASA program scientist for Hubble, said watching the liftoff was ``a double whammy'' because ``it was my first shuttle launch and the launch of the HST.</s>

<s docid="AP900424-0081" num="27" wdcount="5"> It really gets to you.''</s>
</TEXT>
</DOC>
