<DOC>
<DOCNO>

<s docid="AP900425-0013" num="1" wdcount="1"> AP900425-0013</s>
</DOCNO>
<FILEID>

<s docid="AP900425-0013" num="2" wdcount="2"> AP-NR-04-25-90 0115EDT</s>
</FILEID>
<FIRST>

<s docid="AP900425-0013" num="3" wdcount="6"> r a PM-Gee-WhizTelescope Bjt 04-25 0651</s>
</FIRST>
<SECOND>

<s docid="AP900425-0013" num="4" wdcount="3"> PM-Gee-Whiz Telescope, Bjt,0667</s>
</SECOND>
<HEAD>

<s docid="AP900425-0013" num="5" wdcount="10"> Space Telescope Opening a Window on the Beginning of Time</s>
</HEAD>
<BYLINE>

<s docid="AP900425-0013" num="6" wdcount="4"> By HARRY F. ROSENTHAL</s>
</BYLINE>
<BYLINE>

<s docid="AP900425-0013" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900425-0013" num="8" wdcount="4"> CAPE CANAVERAL, Fla. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900425-0013" num="9" wdcount="17"> Already they're saying it's the biggest happening in astronomy since Galileo put his eye to a telescope.</s>

<s docid="AP900425-0013" num="10" wdcount="12"> So, step right up folks, and discover the wonders of the universe.</s>

<s docid="AP900425-0013" num="11" wdcount="5"> See how big it is.</s>

<s docid="AP900425-0013" num="12" wdcount="3"> Learn its age.</s>

<s docid="AP900425-0013" num="13" wdcount="16"> Look at light created 14 billion years ago and arriving at your eye only this instant.</s>

<s docid="AP900425-0013" num="14" wdcount="20"> Ride along to the beginning of everything, almost, to the Big Bang of 10 or 20 thousand million years ago.</s>

<s docid="AP900425-0013" num="15" wdcount="7"> See stars born and see them die.</s>

<s docid="AP900425-0013" num="16" wdcount="3"> Watch galaxies form.</s>

<s docid="AP900425-0013" num="17" wdcount="10"> Follow the flow of gas into the Milky Way's halo.</s>

<s docid="AP900425-0013" num="18" wdcount="37"> Peer deep into the universe, past so many stars in our own galaxy that it would take a person more than a lifetime to count, to a hundred billion other galaxies each with about 200 billion stars.</s>

<s docid="AP900425-0013" num="19" wdcount="35"> For scientists, and then the rest of us, all that becomes possible now that the space shuttle Discovery has carried the Hubble Space Telescope into the sky to see what no one has seen before.</s>

<s docid="AP900425-0013" num="20" wdcount="22"> The telescope, a silvery tube as long as a tanker truck, has an unmatched ability to detect and capture the faintest light.</s>

<s docid="AP900425-0013" num="21" wdcount="13"> Light, speeding along at 186,000 miles a second, is the messenger of creation.</s>

<s docid="AP900425-0013" num="22" wdcount="25"> Tracking the trail of light from today to the first moments contains all the information we will ever have about the creation of the universe.</s>

<s docid="AP900425-0013" num="23" wdcount="16"> The Hubble promises to give science an open window perhaps to the first echoes of creation.</s>

<s docid="AP900425-0013" num="24" wdcount="12"> This is a world-class event, even if astronomy is not your thing.</s>

<s docid="AP900425-0013" num="25" wdcount="34"> Superlatives? ``In the history of optical astronomy there have been two great leaps in the resolution of the universe: Galileo's telescope in the autumn of 1609, and the Hubble Space Telescope in April 1990''.</s>

<s docid="AP900425-0013" num="26" wdcount="15"> _ Eric J. Chaisson, a senior scientist at the Space Telescope Science Institute in Baltimore.</s>

<s docid="AP900425-0013" num="27" wdcount="2"> One more?</s>

<s docid="AP900425-0013" num="28" wdcount="13"> ``No one ever made anything that good,'' James Westphal, California Institute of Technology.</s>

<s docid="AP900425-0013" num="29" wdcount="23"> Another? Dr. Lennard Fisk, NASA's chief scientist, predicts that the Hubble telescope ``will literally be the dawn of a new era in astronomy''.</s>

<s docid="AP900425-0013" num="30" wdcount="7"> Eras rarely can be proclaimed in advance.</s>

<s docid="AP900425-0013" num="31" wdcount="13"> But the HST, named after Edwin Powell Hubble, holds that kind of promise.</s>

<s docid="AP900425-0013" num="32" wdcount="34"> Hubble was an astronomer in the first half of the century who concluded not only that distant galaxies are moving away from Earth but that the farther away they are, the faster they move.</s>

<s docid="AP900425-0013" num="33" wdcount="32"> The theory of an expanding universe supported the belief that the universe originated in a cosmic explosion and that all matter is still rushing from the site of that so-called Big Bang.</s>

<s docid="AP900425-0013" num="34" wdcount="25"> Astronomers think the Big Bang occurred 12 billion to 20 billion years ago and sent the entire universe flying out at incredible speed and heat.</s>

<s docid="AP900425-0013" num="35" wdcount="10"> Eventually matter cooled and condensed into galaxies, stars and planets.</s>

<s docid="AP900425-0013" num="36" wdcount="34"> There are bigger telescopes than the Hubble, but they are all on Earth and all subject to a major limitation _ the atmosphere _ which is fine for breathing but lousy for seeing through.</s>

<s docid="AP900425-0013" num="37" wdcount="20"> The problem of skywatching through layers of air has been likened to birdwatching from the bottom of a swimming pool.</s>

<s docid="AP900425-0013" num="38" wdcount="27"> The Voyager spacecraft, which sent back astonishing views of Earth's sister planets, had to travel 12 years to get close enough for pictures as they whizzed past.</s>

<s docid="AP900425-0013" num="39" wdcount="15"> With the Hubble, says scientist Edward Weiler, such pictures are possible any time we want.</s>

<s docid="AP900425-0013" num="40" wdcount="18"> The telescope is 42.5 by 14 feet and consists of a 94.5-inch primary mirror that gathers incoming light.</s>

<s docid="AP900425-0013" num="41" wdcount="23"> ``On a clear, dark night you can see a flashlight from two miles away,'' says Weiler, chief NASA scientist on the Hubble project.</s>

<s docid="AP900425-0013" num="42" wdcount="14"> ``With a 28-power telescope you can see it on the moon 250,000 miles away.</s>

<s docid="AP900425-0013" num="43" wdcount="12"> With the HST you could see a firefly in Australia from Washington.''</s>
</TEXT>
</DOC>
