<DOC>
<DOCNO>

<s docid="AP900425-0146" num="1" wdcount="1"> AP900425-0146</s>
</DOCNO>
<FILEID>

<s docid="AP900425-0146" num="2" wdcount="2"> AP-NR-04-25-90 1614EDT</s>
</FILEID>
<FIRST>

<s docid="AP900425-0146" num="3" wdcount="7"> u a PM-SpaceShuttle 15thLd-Writethru a0661-64 04-25 0772</s>
</FIRST>
<SECOND>

<s docid="AP900425-0146" num="4" wdcount="5"> PM-Space Shuttle, 15th Ld-Writethru, a0661-64,0789</s>
</SECOND>
<HEAD>

<s docid="AP900425-0146" num="5" wdcount="1"> URGENT</s>
</HEAD>
<HEAD>

<s docid="AP900425-0146" num="6" wdcount="3"> Space Telescope Deployed</s>
</HEAD>
<NOTE>

<s docid="AP900425-0146" num="7" wdcount="3"> Eds: Combines pvs.</s>

<s docid="AP900425-0146" num="8" wdcount="7"> Recasts lead to include equipment problem .</s>
</NOTE>
<HEAD>

<s docid="AP900425-0146" num="9" wdcount="2"> LaserPhoto HTN1</s>
</HEAD>
<BYLINE>

<s docid="AP900425-0146" num="10" wdcount="3"> By LAURA TOLLEY</s>
</BYLINE>
<BYLINE>

<s docid="AP900425-0146" num="11" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900425-0146" num="12" wdcount="4"> SPACE CENTER, Houston (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900425-0146" num="13" wdcount="26"> Discovery's astronauts overcame balky equipment to send the Hubble Space Telescope floating free from the shuttle today on a 15-year quest for secrets of the universe.</s>

<s docid="AP900425-0146" num="14" wdcount="29"> The $1.5 billion telescope began orbiting Earth every 97.3 minutes at an altitude of 380 miles _ high above the atmosphere, which has limited the view of ground-based telecopes.</s>

<s docid="AP900425-0146" num="15" wdcount="14"> ``Discovery, go for Hubble release,'' Mission Control told the crew at 3:37 p.m. EDT.</s>

<s docid="AP900425-0146" num="16" wdcount="14"> The event occurred a minute later as the shuttle slowly and carefully backed away.</s>

<s docid="AP900425-0146" num="17" wdcount="26"> The final hours before its release were a nightmare for ground controllers as they commanded the unfurling of two solar panels that power the telescope's instruments.</s>

<s docid="AP900425-0146" num="18" wdcount="13"> The starboard panel balked twice as it was being pulled from its reel.</s>

<s docid="AP900425-0146" num="19" wdcount="16"> Mission Control ordered space-walking astronauts to be ready to go out of the cabin to help.</s>

<s docid="AP900425-0146" num="20" wdcount="10"> But there was a third try and it was successful.</s>

<s docid="AP900425-0146" num="21" wdcount="22"> ``We have confirmation that the solar array wing on the starboard side has been deployed,'' the telescope control center in Maryland said.</s>

<s docid="AP900425-0146" num="22" wdcount="13"> ``So we have good news,'' said Dave Drachlis, of the Hubble control center.</s>

<s docid="AP900425-0146" num="23" wdcount="26"> The deployment of the two 39-foot panels allowed sun power to flow into the telescope's batteries, relieving worries that they would use up their eight-hour charge.</s>

<s docid="AP900425-0146" num="24" wdcount="36"> Before astronaut Steve Hawley was able to lift the 12-ton telescope from the cargo bay with the shuttle's mechanical arm, its instruments had to be disconnected from the shuttle's power and shifted over to the batteries.</s>

<s docid="AP900425-0146" num="25" wdcount="30"> ``Precisely one day after lifting off from Launch Pad 39B at Kennedy Space Center, the Hubble Space Telescope is ready to fly on its own,'' Mission Control's Jeffrey Carr said.</s>

<s docid="AP900425-0146" num="26" wdcount="4"> ``The game has begun.</s>

<s docid="AP900425-0146" num="27" wdcount="4"> The race is on.</s>

<s docid="AP900425-0146" num="28" wdcount="4"> The clock is ticking''.</s>

<s docid="AP900425-0146" num="29" wdcount="34"> Astronauts Kathryn Sullivan and Bruce McCandless put on spacesuits and entered an airlock in order to be ready to walk outside and pull out the array had mechanical deployment of the solar panels failed.</s>

<s docid="AP900425-0146" num="30" wdcount="28"> Cameras aboard Discovery showed the telescope, being held at the end of a 50-foot crane, reflecting sunlight from its silver surface and a turning Earth in the background.</s>

<s docid="AP900425-0146" num="31" wdcount="22"> Earlier this morning, Discovery commander Loren J. Shriver maneuvered the shuttle into its deployment position, with its nose pointed toward the sun.</s>

<s docid="AP900425-0146" num="32" wdcount="36"> That was to put the telescope's solar arrays, once unfurled, at the proper angle to quickly start collecting energy and protect the telescope's fixed star trackers while the instrument was being held above the payload bay.</s>

<s docid="AP900425-0146" num="33" wdcount="15"> Discovery is in orbit 380 miles above Earth, 70 miles higher than any previous shuttle.</s>

<s docid="AP900425-0146" num="34" wdcount="16"> The orbit was dictated by the need to put the telescope above the Earth's distorting atmosphere.</s>

<s docid="AP900425-0146" num="35" wdcount="36"> ``For those technically inclined this morning, I'd like to pass on the quote of the day from the on-board astronomer (Hawley), something to the effect that the big marble sure looks far away today,'' Shriver said.</s>

<s docid="AP900425-0146" num="36" wdcount="37"> The five astronauts' busy day began on a musical note early this morning as Mission Control played a song called ``Space is Our World,'' written by members of Discovery's training team and a Houston-area group, Private Numbers.</s>

<s docid="AP900425-0146" num="37" wdcount="32"> Controllers monitoring the telescope at Goddard Space Flight Center in Maryland said Tuesday that no problems had been detected so far aboard Hubble, the most expensive and complex unmanned spacecraft ever built.</s>

<s docid="AP900425-0146" num="38" wdcount="17"> ``Everything has just being going like clockwork,'' said Ron Schlagheck, shift director of orbital verifications at Goddard.</s>

<s docid="AP900425-0146" num="39" wdcount="5"> ``Everybody is in excellent spirits''.</s>

<s docid="AP900425-0146" num="40" wdcount="22"> The Hubble telescope, delayed by technical problems and the 1986 Challenger accident, has waited seven years to take its place in space.</s>

<s docid="AP900425-0146" num="41" wdcount="11"> It finally got a ride into orbit Tuesday morning aboard Discovery.</s>

<s docid="AP900425-0146" num="42" wdcount="21"> Hubble will allow astronomers to study stars and galaxies so distant their light has taken 14 billion years to reach Earth.</s>

<s docid="AP900425-0146" num="43" wdcount="37"> It is expected to provide clues to the age and size of the universe, and it may solve the mysteries of quasars, pulsars and black holes and even find stars with planets that could conceivably support life.</s>

<s docid="AP900425-0146" num="44" wdcount="20"> The 24,250-pound telescope is 43 feet long and 14 feet in diameter, about the size of a railroad tank car.</s>

<s docid="AP900425-0146" num="45" wdcount="20"> When it is in orbit, it will receive electrical power for its six scientific instruments from two winglike solar arrays.</s>

<s docid="AP900425-0146" num="46" wdcount="44"> It is named for the late astronomer Edwin P. Hubble, whose discovery during the 1920s that the universe is expanding gave rise to the Big Bang theory that the universe was created by a tremendous explosion 10 billion to 20 billion years ago .</s>
</TEXT>
</DOC>
