<DOC>
<DOCNO>

<s docid="AP900427-0146" num="1" wdcount="1"> AP900427-0146</s>
</DOCNO>
<FILEID>

<s docid="AP900427-0146" num="2" wdcount="2"> AP-NR-04-27-90 2041EDT</s>
</FILEID>
<FIRST>

<s docid="AP900427-0146" num="3" wdcount="7"> u a AM-SpaceShuttle 2ndLd-Writethru a0662 04-27 0970</s>
</FIRST>
<SECOND>

<s docid="AP900427-0146" num="4" wdcount="7"> AM-Space Shuttle, 2nd Ld - Writethru, a0662,0993</s>
</SECOND>
<HEAD>

<s docid="AP900427-0146" num="5" wdcount="11"> $1.5 Billion Eye in the Sky Opens; Astronauts Prepare for Return</s>
</HEAD>
<NOTE>

<s docid="AP900427-0146" num="6" wdcount="16"> Eds: LEADS with 20 grafs to UPDATE with details of communication problem, shuttle passing beneath telescope.</s>

<s docid="AP900427-0146" num="7" wdcount="8"> Pick up 18th graf pvs: `NASA said.. .</s>
</NOTE>
<HEAD>

<s docid="AP900427-0146" num="8" wdcount="2"> LaserPhotos HTN1,4</s>
</HEAD>
<BYLINE>

<s docid="AP900427-0146" num="9" wdcount="3"> By MARCIA DUNN</s>
</BYLINE>
<BYLINE>

<s docid="AP900427-0146" num="10" wdcount="3"> AP Aerospace Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900427-0146" num="11" wdcount="4"> CAPE CANAVERAL, Fla. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900427-0146" num="12" wdcount="32"> The Hubble Space Telescope orbited with its big eye open Friday after ground controllers overcame communications problems and lifted its lens cover, but its electronics were shut down due to a malfunction.</s>

<s docid="AP900427-0146" num="13" wdcount="19"> Those problems, however, were not the immediate concern of shuttle Discovery's astronauts, who prepared for Sunday's return to Earth.</s>

<s docid="AP900427-0146" num="14" wdcount="6"> ``You've been released from Hubble support.</s>

<s docid="AP900427-0146" num="15" wdcount="13"> It's on its own,'' Mission Control's Story Musgrave told the five crew members.</s>

<s docid="AP900427-0146" num="16" wdcount="9"> ``That's great news,'' replied Discovery commander Loren J. Shriver.</s>

<s docid="AP900427-0146" num="17" wdcount="9"> ``There are handshakes and smiles all around up here.</s>

<s docid="AP900427-0146" num="18" wdcount="15"> I'll bet it's just that way back down there, too,'' added mission specialist Steven Hawley.</s>

<s docid="AP900427-0146" num="19" wdcount="3"> ``Who's buying tonight''?</s>

<s docid="AP900427-0146" num="20" wdcount="9"> ``We'll buy when you all get back,'' Musgrave replied.</s>

<s docid="AP900427-0146" num="21" wdcount="11"> Flight director William Reeves said it was too early to cheer.</s>

<s docid="AP900427-0146" num="22" wdcount="13"> `We still have an important part of the mission to go,'' Reeves said.</s>

<s docid="AP900427-0146" num="23" wdcount="12"> ``We reserve our celebration until the crew is safely on the ground''.</s>

<s docid="AP900427-0146" num="24" wdcount="15"> Discovery is to land at 9:48 a.m. EDT Sunday at Edwards Air Force Base, Calif.</s>

<s docid="AP900427-0146" num="25" wdcount="31"> Landing would have been delayed a day if astronauts Bruce McCandless and Kathryn Sullivan had had to perform a space walk to crank open the telescope's lens cover, or aperture door.</s>

<s docid="AP900427-0146" num="26" wdcount="27"> The shuttle trailed 50 miles behind Hubble when the aperture door opened 380 miles above Earth, but passed 3.7 miles beneath the telescope later in the day.</s>

<s docid="AP900427-0146" num="27" wdcount="30"> The National Aeronautics and Space Administration had planned to release its first test image from the $1.5 billion telescope on Tuesday, showing an open star cluster in the constellation Carina.</s>

<s docid="AP900427-0146" num="28" wdcount="18"> But Steve Terry, director of orbital verifications, said that would be delayed by problems with Hubble's high-speed antennas.</s>

<s docid="AP900427-0146" num="29" wdcount="9"> Scientific data will follow in a month or two.</s>

<s docid="AP900427-0146" num="30" wdcount="32"> Hubble's 10-foot aluminum aperture door was opened to the heavens at 10:30 a.m. EDT, nearly four hours later than planned, exposing its finely polished 94.5-inch mirror to starlight for the first time.</s>

<s docid="AP900427-0146" num="31" wdcount="37"> Ground controllers sent a signal commanding the door to lift even though the telescope was in an automatic ``safe mode,'' with all motion stopped because of problems in linking its high-speed dish antennas with a relay satellite.</s>

<s docid="AP900427-0146" num="32" wdcount="23"> One of the two antennas apparently had swung too far, and the telescope shut down, said Jean Oliver, a Hubble deputy project manager.</s>

<s docid="AP900427-0146" num="33" wdcount="27"> If future movements of the antenna have to be limited to avoid the problem, it would have only slight impact on the telescope's observing time, Oliver said.</s>

<s docid="AP900427-0146" num="34" wdcount="15"> Terry said the opening of the aperture door could not have been delayed much longer.</s>

<s docid="AP900427-0146" num="35" wdcount="26"> ``There has to be a point where you say they have to go their way and we have to go ours,'' he said of the astronauts.</s>

<s docid="AP900427-0146" num="36" wdcount="19"> When the door opened, two of Hubble's four position-stabilizing gyroscopes stopped working; later, engineers got them back on line.</s>

<s docid="AP900427-0146" num="37" wdcount="21"> The motion of the lens cover knocked out the gyros, said Dave Drachlis of the Goddard Space Flight Center in Maryland.</s>

<s docid="AP900427-0146" num="38" wdcount="8"> That, too, kept it in the safe mode.</s>

<s docid="AP900427-0146" num="39" wdcount="17"> Oliver said it would be Saturday morning before the telescope is brought out of the safe mode.</s>

<s docid="AP900427-0146" num="40" wdcount="19"> It will take another day to get the instrument operating normally again, putting controllers at Goddard several days behind.</s>

<s docid="AP900427-0146" num="41" wdcount="38"> ``We're trying to be very deliberate and trying not to cut any corners and do anything fast because we feel there's a lot at risk here and we want to make sure we're doing it properly,'' Oliver said.</s>

<s docid="AP900427-0146" num="42" wdcount="21"> ``We've got a long future ahead of us, and we want to make sure it starts off on the right foot''.</s>

<s docid="AP900427-0146" num="43" wdcount="11"> NASA said the telescope was safe and in a stable position.</s>

<s docid="AP900427-0146" num="44" wdcount="23"> Tolerances for the telescope systems were set particularly narrow for the first operations and that was the cause of many malfunctions, Terry said.</s>

<s docid="AP900427-0146" num="45" wdcount="13"> In addition to that trouble, there were two communications outages totaling several hours.</s>

<s docid="AP900427-0146" num="46" wdcount="7"> ``We're cautious, and that's natural,'' Terry said.</s>

<s docid="AP900427-0146" num="47" wdcount="18"> ``We've got a very expensive spacecraft here and we don't want to do anything to jeopardize the usefulness.</s>

<s docid="AP900427-0146" num="48" wdcount="20"> ... We'll get to the point where we know exactly what the spacecraft will do and set the limits appropriately''.</s>

<s docid="AP900427-0146" num="49" wdcount="31"> Terry said Hubble is designed with safe modes so it can be ``the master of its own destiny'' in case contact with an orbiting communications system is lost for extended periods.</s>

<s docid="AP900427-0146" num="50" wdcount="17"> The telescope will share the system, known as Tracking and Data Relay Satellites, with other space craft.</s>

<s docid="AP900427-0146" num="51" wdcount="25"> Except for a tiny wedge opening, the lens cover had been closed and the telescope blind ever since Hubble was released by the astronauts Wednesday.</s>

<s docid="AP900427-0146" num="52" wdcount="32"> From its orbit high above Earth's distorting atmosphere, the telescope will enable astronomers over its 15-year working lifetime to look back 14 billion years and possibly determine the age of the universe.</s>

<s docid="AP900427-0146" num="53" wdcount="17"> The universe is believed to have been created about 15 billion years ago in a cosmic explosion.</s>

<s docid="AP900427-0146" num="54" wdcount="22"> The late astronomer Edwin P. Hubble, for whom the telescope is named, provided the basis for the Big Bang theory of creation.</s>

<s docid="AP900427-0146" num="55" wdcount="25"> He discovered during the 1920s that the universe is expanding and that the farther the galaxy is from Earth, the faster it is moving away.</s>

<s docid="AP900427-0146" num="56" wdcount="30"> In honor of the astronomer, Sullivan carried with her into space an eyepiece from the 100-inch telescope at California's Mount Wilson Observatory that Hubble used to make his pioneering observations.</s>

<s docid="AP900427-0146" num="57" wdcount="27"> ``It's a great pleasure to have something of such historical significance and something that so directly symbolizes Edwin Hubble's fundamental contributions to astronomy,'' she said Friday afternoon.</s>

<s docid="AP900427-0146" num="58" wdcount="13"> Once back on Earth, the eyepiece will be displayed at the observatory .</s>
</TEXT>
</DOC>
