<DOC>
<DOCNO>

<s docid="AP900426-0135" num="1" wdcount="1"> AP900426-0135</s>
</DOCNO>
<FILEID>

<s docid="AP900426-0135" num="2" wdcount="2"> AP-NR-04-26-90 1520EDT</s>
</FILEID>
<FIRST>

<s docid="AP900426-0135" num="3" wdcount="7"> u a PM-SpaceShuttle 5thLd-Writethru a0630 04-26 0996</s>
</FIRST>
<SECOND>

<s docid="AP900426-0135" num="4" wdcount="7"> PM-Space Shuttle, 5th Ld - Writethru, a0630,1023</s>
</SECOND>
<HEAD>

<s docid="AP900426-0135" num="5" wdcount="10"> Communications Outages Mar Hubble's First Day, But Problem Finally Solved</s>
</HEAD>
<HEAD>

<s docid="AP900426-0135" num="6" wdcount="3"> With PM-Hubble-Amateurs, Bjt</s>
</HEAD>
<NOTE>

<s docid="AP900426-0135" num="7" wdcount="10"> Eds: LEADS with 11 grafs to UPDATE with problem solved.</s>

<s docid="AP900426-0135" num="8" wdcount="8"> Picks up 13th graf pvs, `The telescope, embarking...'.</s>

<s docid="AP900426-0135" num="9" wdcount="13"> SUBS 21st graf, `Discovery and...', to delete now-redundant reference to Greenbelt, Md .</s>
</NOTE>
<BYLINE>

<s docid="AP900426-0135" num="10" wdcount="3"> By LAURA TOLLEY</s>
</BYLINE>
<BYLINE>

<s docid="AP900426-0135" num="11" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900426-0135" num="12" wdcount="4"> SPACE CENTER, Houston (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900426-0135" num="13" wdcount="34"> Ground controllers at the Goddard Space Flight Center finally made contact today with the two main antennas on the $1.5 billion Hubble Space Telescope after trying for more than six hours to lock on.</s>

<s docid="AP900426-0135" num="14" wdcount="23"> Applause erupted in the Hubble control center in Greenbelt, Md., as the glitch that marred Hubble's first full day in space was solved.</s>

<s docid="AP900426-0135" num="15" wdcount="24"> ``We have confirmation that we have achieved communication with the Tracking and Data Relay Satellite through the high-gain antenna system,'' said NASA's Dave Drachlis.</s>

<s docid="AP900426-0135" num="16" wdcount="36"> Engineers had said all along they believed the antennas were working all right and that the problem was in incorrectly pointing either the satellite or the TDRS, an orbiting communications satellite that acts as a switchboard.</s>

<s docid="AP900426-0135" num="17" wdcount="27"> In the successful attempt, they nearly doubled the width of the antennas' beams to take in more territory, from a sweep of 6.2 degrees to 10.8 degrees.</s>

<s docid="AP900426-0135" num="18" wdcount="23"> The telescope's low-gain antennas, which receive and transmit information at a much slower rate and can be used in emergencies, were working well.</s>

<s docid="AP900426-0135" num="19" wdcount="12"> Space shuttle Discovery was 46 miles away, available to remedy certain problems.</s>

<s docid="AP900426-0135" num="20" wdcount="14"> The outage was not a problem for which space walkers would have been summoned.</s>

<s docid="AP900426-0135" num="21" wdcount="19"> The five astronauts were otherwise busy making pictures of storms over Texas from their 380-mile-high perch, and doing experiments.</s>

<s docid="AP900426-0135" num="22" wdcount="27"> Steve Terry, director of a team calibrating various aspects of the telescope, said the first outage was caused by human error and was not a serious problem.</s>

<s docid="AP900426-0135" num="23" wdcount="17"> It began between 1 and 1:30 a.m. EDT and lasted 45 minutes to an hour, he said.</s>

<s docid="AP900426-0135" num="24" wdcount="23"> The second failure occurred at 6:44 a.m. when controllers attempted to send a signal to the telescope's two high-gain antennas through the TDRS.</s>

<s docid="AP900426-0135" num="25" wdcount="13"> ``This time it was a pointing problem,'' said Jim Elliott, a Goddard spokesman.</s>

<s docid="AP900426-0135" num="26" wdcount="14"> ``It's a new spacecraft and we think inexperience dealing with it was the cause''.</s>

<s docid="AP900426-0135" num="27" wdcount="31"> The telescope, embarking on a 15-year search for new worlds, was released from the shuttle's cargo bay Wednesday after a last-minute snag that almost sent two astronauts on an emergency spacewalk.</s>

<s docid="AP900426-0135" num="28" wdcount="19"> Mission Control awakened the crew early today with a loud rendition of the song ``Shout,'' a fraternity house favorite.</s>

<s docid="AP900426-0135" num="29" wdcount="3"> ``Good morning, Discovery.</s>

<s docid="AP900426-0135" num="30" wdcount="12"> I guess you're awake after that song,'' said Kathy Thornton, shuttle communicator.</s>

<s docid="AP900426-0135" num="31" wdcount="9"> ``There are a lot of happy people down here.</s>

<s docid="AP900426-0135" num="32" wdcount="16"> We saw a great deploy yesterday and Hubble had a good night while you were asleep''.</s>

<s docid="AP900426-0135" num="33" wdcount="12"> ``We appreciate the good words from everybody,'' replied Discovery Commander Loren Shriver.</s>

<s docid="AP900426-0135" num="34" wdcount="35"> After Wednesday's deployment, Shriver gently backed Discovery away from the telescope and put the shuttle through a series of maneuvers, the last one completed this morning, to ``park'' Discovery in orbit 46 miles behind Hubble.</s>

<s docid="AP900426-0135" num="35" wdcount="22"> ``The telescope really looked great as we flew away from it, and we sure hope it does good work,'' Shriver said Wednesday.</s>

<s docid="AP900426-0135" num="36" wdcount="18"> ``Well, it sure is now, Loren, and thanks for all the great work you've done,'' replied Mission Control.</s>

<s docid="AP900426-0135" num="37" wdcount="6"> ``Galileo is real proud of you''.</s>

<s docid="AP900426-0135" num="38" wdcount="31"> Scientists have hailed the Hubble _ NASA's most expensive unmanned spacecraft _ as the greatest advance in astronomy since Galileo raised a small telescope to his eyes nearly 400 years ago.</s>

<s docid="AP900426-0135" num="39" wdcount="27"> Discovery and its five astronauts will follow the telescope while controllers at the Goddard center make sure Hubble is operating properly, such as responding to directional commands.</s>

<s docid="AP900426-0135" num="40" wdcount="23"> The next milestone is Friday, when the telescope's 10-foot aperture door is to be opened, exposing the finely polished 94.5-inch mirror to starlight.</s>

<s docid="AP900426-0135" num="41" wdcount="21"> Then on Tuesday, NASA expects to release the first image from the telescope: an open star cluster in the constellation Carina.</s>

<s docid="AP900426-0135" num="42" wdcount="8"> Data will follow in a month or two.</s>

<s docid="AP900426-0135" num="43" wdcount="23"> If the aperture door doesn't open properly, Discovery could return to the telescope so two astronauts could perform a spacewalk to fix it.</s>

<s docid="AP900426-0135" num="44" wdcount="23"> Hubble project manager Fred Wojtalik said the telescope would be tested today for its ability to maneuver before the aperture door is opened.</s>

<s docid="AP900426-0135" num="45" wdcount="25"> ``We want to be in full control so we don't ever endanger the Hubble by putting the aperture door close to the sunlight,'' he said.</s>

<s docid="AP900426-0135" num="46" wdcount="9"> Too much light could damage the telescope's sensitive instruments.</s>

<s docid="AP900426-0135" num="47" wdcount="25"> On Wednesday, mission specialist Steve Hawley used the shuttle's 50-foot robot arm to gently grasp the 12-ton telescope and hoist it from the cargo bay.</s>

<s docid="AP900426-0135" num="48" wdcount="28"> One of the telescope's solar arrays unreeled from its mast as expected and started providing power to the telescope's batteries, which otherwise had only eight hours of charge.</s>

<s docid="AP900426-0135" num="49" wdcount="8"> But there was trouble with the second panel.</s>

<s docid="AP900426-0135" num="50" wdcount="21"> It wouldn't budge when the latches were released, and then moved about a fifth of its 39-foot length and stopped again.</s>

<s docid="AP900426-0135" num="51" wdcount="11"> The panel rolled all the way out on the third attempt.</s>

<s docid="AP900426-0135" num="52" wdcount="33"> By the final attempt, astronauts Bruce McCandless and Kathryn Sullivan were in their space suits in the airlock, 30 minutes away from taking tools in hand and going on an outer-space maintenance call.</s>

<s docid="AP900426-0135" num="53" wdcount="9"> Wojtalik said the cause of the problem is unknown.</s>

<s docid="AP900426-0135" num="54" wdcount="18"> The 8-hour procedure was performed 380 miles above Earth, 70 miles higher than any shuttle has ever flown.</s>

<s docid="AP900426-0135" num="55" wdcount="15"> The orbit was dictated by the need to put Hubble above the Earth's distorting atmosphere.</s>

<s docid="AP900426-0135" num="56" wdcount="32"> Astronomers hope to use the telescope to look back to almost the beginning of the time, studying stars and galaxies so distant their light has taken 14 billions years to reach Earth.</s>

<s docid="AP900426-0135" num="57" wdcount="18"> They hope to determine how and when the universe was formed, currently estimated at 15 billion years ago.</s>

<s docid="AP900426-0135" num="58" wdcount="19"> The telescope originally was scheduled for launch in 1983 but was delayed by technical problems and the Challenger accident.</s>

<s docid="AP900426-0135" num="59" wdcount="18"> Discovery, which blasted into orbit Tuesday, is scheduled to land Sunday at Edwards Air Force Base, Calif .</s>
</TEXT>
</DOC>
