<DOC>
<DOCNO>

<s docid="AP900427-0083" num="1" wdcount="1"> AP900427-0083</s>
</DOCNO>
<FILEID>

<s docid="AP900427-0083" num="2" wdcount="2"> AP-NR-04-27-90 1328EDT</s>
</FILEID>
<FIRST>

<s docid="AP900427-0083" num="3" wdcount="7"> u a PM-SpaceShuttle 7thLd-Writethru a0556 04-27 0927</s>
</FIRST>
<SECOND>

<s docid="AP900427-0083" num="4" wdcount="7"> PM-Space Shuttle, 7th Ld - Writethru, a0556,0949</s>
</SECOND>
<HEAD>

<s docid="AP900427-0083" num="5" wdcount="9"> Hubble Aperture Door Finally Opened After Morning Of Problems</s>
</HEAD>
<NOTE>

<s docid="AP900427-0083" num="6" wdcount="35"> Eds: LEADS with 8 grafs to CORRECT attribution of `great news' quote to Shriver sted Hawley, add new quote, and to UPDATE with problem blamed on jarring during door-opening; process under way to fix it.</s>

<s docid="AP900427-0083" num="7" wdcount="8"> Picks up 7th graf pvs, `Steve Terry...' .</s>
</NOTE>
<HEAD>

<s docid="AP900427-0083" num="8" wdcount="2"> LaserPhoto HTN1</s>
</HEAD>
<BYLINE>

<s docid="AP900427-0083" num="9" wdcount="3"> By LAURA TOLLEY</s>
</BYLINE>
<BYLINE>

<s docid="AP900427-0083" num="10" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900427-0083" num="11" wdcount="4"> SPACE CENTER, Houston (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900427-0083" num="12" wdcount="34"> The lens cover on the Hubble Space Telescope opened today after a morning of worrisome problems, and Mission Control told the Discovery astronauts they no longer are needed to rescue the $1.5 billion instrument.</s>

<s docid="AP900427-0083" num="13" wdcount="21"> ``You've been released from Hubble support; it's on its own,'' Mission Control told the astronauts when the aluminum aperture door opened.</s>

<s docid="AP900427-0083" num="14" wdcount="12"> ``Thank you, sir, that's great news,'' said Discovery Commander Loren J. Shriver.</s>

<s docid="AP900427-0083" num="15" wdcount="29"> ``There are handshakes and smiles all around up here,'' said Steve Hawley, who had been at the controls when the telescope was released into its own orbit on Wednesday.</s>

<s docid="AP900427-0083" num="16" wdcount="9"> ``I'll bet it's just that way down there, too''.</s>

<s docid="AP900427-0083" num="17" wdcount="19"> The successful opening of the lens cover paved the way for the astronauts to return to Earth on Sunday.</s>

<s docid="AP900427-0083" num="18" wdcount="19"> They had blasted into space Tuesday after a two-week delay and dispatched the telescope from its payload bay Wednesday.</s>

<s docid="AP900427-0083" num="19" wdcount="11"> ``The Hubble is open for business,'' Mission Control told the astronauts.</s>

<s docid="AP900427-0083" num="20" wdcount="7"> The telescope still was having problems, however.</s>

<s docid="AP900427-0083" num="21" wdcount="28"> When the door opened, two of its four position-stabilizing gyroscopes stopped working and the electronic system went into an automatic ``safe mode'' in which all motion is stopped.</s>

<s docid="AP900427-0083" num="22" wdcount="35"> The team at the Goddard Space Flight Center in Maryland, which guides the telescope, said the door-opening motion jarred the telescope more than had been expected and that the system reacted properly in shutting down.</s>

<s docid="AP900427-0083" num="23" wdcount="16"> By early afternoon, a step-by-step procedure was begun to bring the telescope's electronics back on line.</s>

<s docid="AP900427-0083" num="24" wdcount="30"> Steve Terry, a top Hubble engineering official, said tolerances for the telescope systems had been set particularly narrow for the first operations and that was the cause of many malfunctions.</s>

<s docid="AP900427-0083" num="25" wdcount="15"> In addition to the trouble this morning, there two communications outages Thursday totaling several hours.</s>

<s docid="AP900427-0083" num="26" wdcount="7"> ``We're cautious, and that's natural,'' he said.</s>

<s docid="AP900427-0083" num="27" wdcount="18"> ``We've got a very expensive spacecraft here and we don't want to do anything to jeopardize the usefulness.</s>

<s docid="AP900427-0083" num="28" wdcount="20"> ... We'll get to the point where we know exactly what the spacecraft will do and set the limits appropriately''.</s>

<s docid="AP900427-0083" num="29" wdcount="11"> NASA announced that ``at this time the telescope is safe, stable''.</s>

<s docid="AP900427-0083" num="30" wdcount="23"> The space shuttle Discovery, which carried the telescope to orbit, was 50 miles behind the telescope, ready to lend a hand if needed.</s>

<s docid="AP900427-0083" num="31" wdcount="22"> Later in the day, the ship was to do an engine firing that would set it on a preliminary path for home.</s>

<s docid="AP900427-0083" num="32" wdcount="11"> That path would take the Discovery two miles below the telescope.</s>

<s docid="AP900427-0083" num="33" wdcount="16"> The lens cover, a 10-foot diameter ``aperature door,'' covers the opening to the telescope's light shield.</s>

<s docid="AP900427-0083" num="34" wdcount="8"> When it is closed, the telescope is blind.</s>

<s docid="AP900427-0083" num="35" wdcount="29"> The lens cover had been closed _ except for a tiny wedge opening _ ever since the $1.5 billion telescope was dropped overboard by the Discovery crew on Wednesday.</s>

<s docid="AP900427-0083" num="36" wdcount="35"> Now that it is opened, starlight can strike the lens for the first time and it can go about its business of photographing and analyzing the universe in ways and with sensitivity never before possible.</s>

<s docid="AP900427-0083" num="37" wdcount="15"> The door is made from honeycombed aluminum sheets covered on the outside with solar-reflecting material.</s>

<s docid="AP900427-0083" num="38" wdcount="9"> The inside is painted black to absorb stray light.</s>

<s docid="AP900427-0083" num="39" wdcount="22"> If the door opening command had failed, the five Discovery astronauts who deployed Hubble were prepared to head back to the telescope.</s>

<s docid="AP900427-0083" num="40" wdcount="20"> Mission specialists Bruce McCandless and Kathryn Sullivan would have performed a space walk to open the door Saturday if necessary.</s>

<s docid="AP900427-0083" num="41" wdcount="24"> If it had been needed, the rescue would have delayed the landing, scheduled for Sunday at Edwards Air Force Base, Calif., by a day.</s>

<s docid="AP900427-0083" num="42" wdcount="18"> The astronauts were awakened at 2:30 a.m. EDT to the mellow sounds of the Beach Boys' song, ``Kokomo''.</s>

<s docid="AP900427-0083" num="43" wdcount="30"> ``For Max Q's keyboard, that's the way that song should really be done,'' Mission Control radioed to mission specialist Steve Hawley, a member of the all-astronaut band called Max Q.</s>

<s docid="AP900427-0083" num="44" wdcount="12"> ``Your next practice is Sunday evening in the gym, don't be late''.</s>

<s docid="AP900427-0083" num="45" wdcount="22"> Max Q is a NASA acronym for the point in the shuttle's ascent when the aerodynamic pressure is at its greatest point.</s>

<s docid="AP900427-0083" num="46" wdcount="11"> ``That sounds just like the way we do it,'' replied Hawley.</s>

<s docid="AP900427-0083" num="47" wdcount="11"> ``If you get us home by Sunday, I'll go to practice''.</s>

<s docid="AP900427-0083" num="48" wdcount="31"> In an orbit high enough to avoid Earth's distorting atmosphere, Hubble will allow astronomers to study stars and galaxies so distant their light has taken 14 billion years to reach Earth.</s>

<s docid="AP900427-0083" num="49" wdcount="20"> It is capable of detecting objects 50 times fainter and with 10 times greater clarity than the best ground-based observatory.</s>

<s docid="AP900427-0083" num="50" wdcount="18"> During its 15-year working lifetime, Hubble is expected to help determine the age and size of the universe.</s>

<s docid="AP900427-0083" num="51" wdcount="22"> It may solve the mysteries of quasars, pulsars and black holes and even find stars with planets that could conceivably support life.</s>

<s docid="AP900427-0083" num="52" wdcount="21"> On Tuesday, NASA plans to release its first test image from the telescope, an open star cluster in the constellation Carina.</s>

<s docid="AP900427-0083" num="53" wdcount="9"> Significant data will follow in a month or two.</s>

<s docid="AP900427-0083" num="54" wdcount="21"> The 12-ton, 43-foot-long telescope, about the size of a bus, is named for astronomer Edwin P. Hubble, who died in 1953.</s>

<s docid="AP900427-0083" num="55" wdcount="34"> The Missouri-born Hubble discovered during the 1920s that the universe is expanding, a finding that gave rise to the theory the universe was created about 15 billion years ago by a tremendous explosion .</s>
</TEXT>
</DOC>
