<DOC>
<DOCNO>

<s docid="AP900426-0185" num="1" wdcount="1"> AP900426-0185</s>
</DOCNO>
<FILEID>

<s docid="AP900426-0185" num="2" wdcount="2"> AP-NR-04-26-90 2024EDT</s>
</FILEID>
<FIRST>

<s docid="AP900426-0185" num="3" wdcount="7"> u a AM-SpaceShuttle 1stLd-Writethru a0667 04-26 0661</s>
</FIRST>
<SECOND>

<s docid="AP900426-0185" num="4" wdcount="5"> AM-Space Shuttle, 1st Ld-Writethru, a0667,0677</s>
</SECOND>
<HEAD>

<s docid="AP900426-0185" num="5" wdcount="7"> Telescope's Main Antennas Work on Second Try</s>
</HEAD>
<HEAD>

<s docid="AP900426-0185" num="6" wdcount="3"> With AM-Hubble-Gadgets, Bjt</s>
</HEAD>
<NOTE>

<s docid="AP900426-0185" num="7" wdcount="19"> Eds: INSERTS 2 grafs after 11th graf pvs, `There had been...,' to UPDATE with minor problem with stabilizing gyros.</s>

<s docid="AP900426-0185" num="8" wdcount="9"> Pick up 12th graf pvs, `Now we have.. .</s>
</NOTE>
<BYLINE>

<s docid="AP900426-0185" num="9" wdcount="3"> By MARCIA DUNN</s>
</BYLINE>
<BYLINE>

<s docid="AP900426-0185" num="10" wdcount="3"> AP Aerospace Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900426-0185" num="11" wdcount="4"> CAPE CANAVERAL, Fla. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900426-0185" num="12" wdcount="18"> Ground controllers cheered after re-establishing contact Thursday with the $1.5 billion Hubble Space Telescope through its main antennas.</s>

<s docid="AP900426-0185" num="13" wdcount="7"> An attempt six hours earlier had failed.</s>

<s docid="AP900426-0185" num="14" wdcount="20"> ``I'm pretty relieved, I must say,'' said Al Boggess, Hubble project scientist at Goddard Space Flight Center in Greenbelt, Md.</s>

<s docid="AP900426-0185" num="15" wdcount="17"> Applause erupted at Goddard's Space Telescope Operations Control Center when the high-speed contact was made Thursday afternoon.</s>

<s docid="AP900426-0185" num="16" wdcount="27"> Controllers sent information to the telescope about its location, and ``this basically improved the telescope's knowledge where it was, what its position was,'' said Goddard's Dave Drachlis.</s>

<s docid="AP900426-0185" num="17" wdcount="17"> They also widened the radio beam to cover a larger area around the two high-speed dish antennas.</s>

<s docid="AP900426-0185" num="18" wdcount="22"> ``We have confirmation that we have achieved communication with the Tracking and Data Relay Satellite through the high-gain antenna system,'' Drachlis reported.</s>

<s docid="AP900426-0185" num="19" wdcount="14"> The antennas are the primary communications links for relaying scientific information to the ground.</s>

<s docid="AP900426-0185" num="20" wdcount="15"> Controllers' lack of experience with the new satellite was part of the problem, Boggess said.</s>

<s docid="AP900426-0185" num="21" wdcount="13"> ``This probably won't be the last time we have a problem,'' he said.</s>

<s docid="AP900426-0185" num="22" wdcount="17"> ``We'll keep working at it until we have all these things that need to be done, done.</s>

<s docid="AP900426-0185" num="23" wdcount="4"> We'll get them right''.</s>

<s docid="AP900426-0185" num="24" wdcount="20"> The problem began Thursday morning when engineers tried pointing the two high-speed antennas toward two widely-separated TDRS satellites without success.</s>

<s docid="AP900426-0185" num="25" wdcount="17"> Two low-speed antennas were working fine, but Boggess said they would be ``excruciatingly slow'' for sending data.</s>

<s docid="AP900426-0185" num="26" wdcount="10"> There had been a communications outage with the telescope earlier.</s>

<s docid="AP900426-0185" num="27" wdcount="11"> It lasted only 45 minutes and was due to human error.</s>

<s docid="AP900426-0185" num="28" wdcount="32"> In addition, one of four ``rate gyros,'' wheels whose spin maintains the telescope in a stable position, was disconnected by an automatic system for a reason engineers were unable to explain immediately.</s>

<s docid="AP900426-0185" num="29" wdcount="13"> But it was restored later and the stability of the satellite was unaffected.</s>

<s docid="AP900426-0185" num="30" wdcount="27"> The problems won't delay the schedule for putting the telescope into use, said Jean Oliver, Hubble deputy project manager at Marshall Space Flight Center in Huntsville, Ala.</s>

<s docid="AP900426-0185" num="31" wdcount="38"> ``Now we have to do an analysis to make sure ourselves just what part of it worked and whether there are things we have to do differently in the future to make it continue to work,'' Boggess said.</s>

<s docid="AP900426-0185" num="32" wdcount="18"> ``Having done it once, we've got confidence we can do it and that means the mission can proceed''.</s>

<s docid="AP900426-0185" num="33" wdcount="25"> Space shuttle Discovery trailed 57 miles behind the telescope and was to stay nearby until the Hubble's aperture door was opened, set for Friday morning.</s>

<s docid="AP900426-0185" num="34" wdcount="31"> Its five astronauts spent the day doing experiments and taking pictures of storms over Texas and other views of Earth from 380 miles up, the highest a shuttle has ever flown.</s>

<s docid="AP900426-0185" num="35" wdcount="22"> When the door covering the telescope aperture is opened, starlight will strike the telescope's finely polished 94.5-inch mirror for the first time.</s>

<s docid="AP900426-0185" num="36" wdcount="27"> If signals fail to activate the 10-foot-wide aluminum aperture door, mission specialists Bruce McCandless and Kathryn Sullivan will go into open space and crank it open Saturday.</s>

<s docid="AP900426-0185" num="37" wdcount="13"> The shuttle is scheduled to land Sunday at Edwards Air Force Base, Calif.</s>

<s docid="AP900426-0185" num="38" wdcount="13"> The mission would be extended a day if the space walk became necessary.</s>

<s docid="AP900426-0185" num="39" wdcount="23"> On Tuesday, the National Aeronautics and Space Administration releases its first image from the telescope, an open star cluster in the constellation Carina.</s>

<s docid="AP900426-0185" num="40" wdcount="9"> Scientific data will follow in a month or two.</s>

<s docid="AP900426-0185" num="41" wdcount="21"> The 12-ton, 43-foot-long telescope, about the size of a bus, is named for astronomer Edwin P. Hubble, who died in 1953.</s>

<s docid="AP900426-0185" num="42" wdcount="33"> The Missouri-born Hubble discovered during the 1920s that the universe is expanding, a finding that gave rise to the theory the universe was created about 15 billion years ago by a tremendous explosion.</s>

<s docid="AP900426-0185" num="43" wdcount="13"> Astronomers expect to look back 14 billion years with the space telescope .</s>
</TEXT>
</DOC>
