<DOC>
<DOCNO>

<s docid="AP881110-0227" num="1" wdcount="1"> AP881110-0227</s>
</DOCNO>
<FILEID>

<s docid="AP881110-0227" num="2" wdcount="2"> AP-NR-11-10-88 2329EST</s>
</FILEID>
<FIRST>

<s docid="AP881110-0227" num="3" wdcount="5"> r a AM-Sakharov 11-10 0254</s>
</FIRST>
<SECOND>

<s docid="AP881110-0227" num="4" wdcount="1"> AM-Sakharov,0260</s>
</SECOND>
<HEAD>

<s docid="AP881110-0227" num="5" wdcount="5"> Sakharov Receives Human Rights Award</s>
</HEAD>
<DATELINE>

<s docid="AP881110-0227" num="6" wdcount="3"> NEW YORK (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP881110-0227" num="7" wdcount="27"> Andrei D. Sakharov, the father of the Soviet dissident movement, finally received a 1973 human rights award Thursday night during his first trip to New York City.</s>

<s docid="AP881110-0227" num="8" wdcount="28"> Sakharov received the Human Rights Award from the International League for Human Rights at a reception at the home of Ronald Lauder, the former U.S. ambassador to Austria.</s>

<s docid="AP881110-0227" num="9" wdcount="33"> The 67-year-old Nobel Peace Prize winner is on his first trip to the West, less than two years after Soviet leader Mikhail Gorbachev freed him from internal exile in the city of Gorky.</s>

<s docid="AP881110-0227" num="10" wdcount="19"> The human rights activist was banished in 1980 to the closed city for opposing the Soviet occupation of Afghanistan.</s>

<s docid="AP881110-0227" num="11" wdcount="23"> About 200 guests, including author Elie Wiesel, Brooklyn District Attorney Elizabeth Holtzman, designer Caroline Roehm and ABC television's Barbara Walters, attended the reception.</s>

<s docid="AP881110-0227" num="12" wdcount="7"> The ceremony was closed to the media.</s>

<s docid="AP881110-0227" num="13" wdcount="21"> Sakharov, wearing a blue beret and plaid scarf, made no statement as he left the reception and entered a waiting limousine.</s>

<s docid="AP881110-0227" num="14" wdcount="39"> Sakharov is the honorary president of the league, which has its headquarters in the United States and more than 40 affiliate groups around the world, including the Moscow Human Rights Committee, which Sakharov and his colleagues founded in 1971.</s>

<s docid="AP881110-0227" num="15" wdcount="46"> Sakharov arrived in the United States on Sunday to visit relatives and receive medical treatment before going to Washington for a White House visit and a board meeting of the International Foundation for the Survival and Development of Humanity, of which he is a director .</s>
</TEXT>
</DOC>
