<DOC>
<DOCNO>

<s docid="AP881109-0161" num="1" wdcount="1"> AP881109-0161</s>
</DOCNO>
<FILEID>

<s docid="AP881109-0161" num="2" wdcount="2"> AP-NR-11-09-88 1240EST</s>
</FILEID>
<FIRST>

<s docid="AP881109-0161" num="3" wdcount="5"> r i AM-Sakharov-Soviet 11-09 0309</s>
</FIRST>
<SECOND>

<s docid="AP881109-0161" num="4" wdcount="1"> AM-Sakharov-Soviet,0318</s>
</SECOND>
<HEAD>

<s docid="AP881109-0161" num="5" wdcount="7"> Sakharov's Trip Largely Ignored by Soviet Media</s>
</HEAD>
<DATELINE>

<s docid="AP881109-0161" num="6" wdcount="2"> MOSCOW (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP881109-0161" num="7" wdcount="33"> The visit by human rights activist Andrei D. Sakharov to the United States has gone virtually unreported by state media, with a radio broadcast saying only he had voiced opposition to the U.S.</s>

<s docid="AP881109-0161" num="8" wdcount="3"> ``Star Wars'' program.</s>

<s docid="AP881109-0161" num="9" wdcount="31"> That report from Radio Moscow, carried on its international-service news programs Tuesday, apparently was the only mention made by Soviet media of Sakharov's visit to the United States, which began Sunday.</s>

<s docid="AP881109-0161" num="10" wdcount="19"> Radio Moscow said Sakharov made the comments about the Reagan administration's space-based anti-missile program at a Boston news conference.</s>

<s docid="AP881109-0161" num="11" wdcount="32"> Sakharov, winner of the 1975 Nobel Peace Prize, is scheduled to spend two weeks visiting relatives in the United States, undergoing medical tests and promoting a new international organization he belongs to.</s>

<s docid="AP881109-0161" num="12" wdcount="32"> A celebrity in the West since he helped form the Soviet dissident movement of the 1970s, Sakharov spent nearly seven years in internal exile after criticizing the Kremlin's military drive into Afghanistan.</s>

<s docid="AP881109-0161" num="13" wdcount="13"> President Mikhail S. Gorbachev allowed him to return to Moscow in December 1986.</s>

<s docid="AP881109-0161" num="14" wdcount="35"> Some statements and articles by Sakharov have been printed in the Soviet media since then, including an article last week in a magazine that opposed some elements of Gorbachev's blueprint for political and electoral reforms.</s>

<s docid="AP881109-0161" num="15" wdcount="33"> Other activities by Sakharov have gone unreported here, including his delivery to Gorbachev of a list of 200 Soviets reportedly held in prison, labor camp or psychiatric hopsitals because of their political views.</s>

<s docid="AP881109-0161" num="16" wdcount="34"> The official Tass news agency reported Wednesday that the organization Sakharov belongs to _ the International Foundation for the Survival and Development of Humanity _ held its first session in Boston the previous day.</s>

<s docid="AP881109-0161" num="17" wdcount="32"> Tass made no mention of Sakharov in its three-paragragh report, but said the Soviet delegation to the meeting was headed by Yevgeny Velikhov, vice president of the Soviet Academy of Sciences .</s>
</TEXT>
</DOC>
