<DOC>
<DOCNO>

<s docid="AP880512-0096" num="1" wdcount="1"> AP880512-0096</s>
</DOCNO>
<FILEID>

<s docid="AP880512-0096" num="2" wdcount="2"> AP-NR-05-12-88 1042EDT</s>
</FILEID>
<FIRST>

<s docid="AP880512-0096" num="3" wdcount="5"> r i PM-Soviet-Sakharov 05-12 0416</s>
</FIRST>
<SECOND>

<s docid="AP880512-0096" num="4" wdcount="1"> PM-Soviet-Sakharov,0427</s>
</SECOND>
<HEAD>

<s docid="AP880512-0096" num="5" wdcount="10"> Moscow News Paints Sympathetic Portrait of the Sakharovs at Home</s>
</HEAD>
<DATELINE>

<s docid="AP880512-0096" num="6" wdcount="2"> MOSCOW (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880512-0096" num="7" wdcount="31"> A Soviet newspaper has painted a highly sympathetic portrait of Andrei D. Sakharov and Yelena Bonner, countering past attacks on the dissident couple once branded as traitors by the state-run media.</s>

<s docid="AP880512-0096" num="8" wdcount="33"> But the account in Moscow News only indirectly mentioned the nearly seven years Sakharov spent in forced internal exile for criticizing the Soviet drive into Afghanistan, indicating that topic is still too sensitive.</s>

<s docid="AP880512-0096" num="9" wdcount="40"> In its latest issue, the weekly devoted its entire back page to describing the home life of Sakharov, 66, the 1975 Nobel Peace Prize winner, and said the words most often heard in his seventh-floor Moscow apartment are ``help me''.</s>

<s docid="AP880512-0096" num="10" wdcount="35"> Sakharov's apartment on a major thoroughfare has been a mecca for Soviets seeking his aid since he and his wife were allowed to return from exile in the closed city of Gorky in December 1986.</s>

<s docid="AP880512-0096" num="11" wdcount="21"> Since then, Sakharov, who was one of the creators of his nation's hydrogen bomb, has vocally supported Soviet leader Mikhail S.</s>

<s docid="AP880512-0096" num="12" wdcount="22"> Gorbachev's reform campaign, but has called for the liberation of all political prisoners and more improvements in the field of human rights.</s>

<s docid="AP880512-0096" num="13" wdcount="29"> Past Soviet reports, published before Gorbachev became Soviet leader, accused Bonner of marrying Sakharov for his money and said the couple lived in ``oriental luxury'' amid ``scandals between spouses''.</s>

<s docid="AP880512-0096" num="14" wdcount="36"> Moscow News depicted the couple as living peacefully and frugally, eating cabbage, beet soup, potatoes, and other simple fare, and marveled that Sakharov, a member of the prestigious Academy of Sciences, always does the dishes himself.</s>

<s docid="AP880512-0096" num="15" wdcount="35"> While Sakharov was in exile in the closed city of Gorky, the author of a book that accused him of leading a luxurious and scandal-ridden existence came to ask for an interview, Moscow News said.</s>

<s docid="AP880512-0096" num="16" wdcount="28"> ``Sakharov put a copy of his book in front of him and proposed that he write an apology for all the lies that were published,'' the paper said.</s>

<s docid="AP880512-0096" num="17" wdcount="23"> It reported that when the unidentified author refused, Sakharov said, ``It's too bad that duels are abolished in our times,'' and slapped him.</s>

<s docid="AP880512-0096" num="18" wdcount="28"> Sakharov has been quoted numerous times by Soviet media since his return from exile, but the article in Moscow News was the longest devoted to him so far.</s>

<s docid="AP880512-0096" num="19" wdcount="22"> But most of the newspaper's circulation is among foreign tourists and readers abroad, so relatively few Soviets would see the Sakharov article.</s>

<s docid="AP880512-0096" num="20" wdcount="18"> As well as appearing in Russian, Moscow News also prints editions in English, French and other languages .</s>
</TEXT>
</DOC>
