<DOC>
<DOCNO>

<s docid="AP880512-0157" num="1" wdcount="1"> AP880512-0157</s>
</DOCNO>
<FILEID>

<s docid="AP880512-0157" num="2" wdcount="2"> AP-NR-05-12-88 1537EDT</s>
</FILEID>
<FIRST>

<s docid="AP880512-0157" num="3" wdcount="6"> u i AM-Soviet-Sakharov Bjt 05-12 0621</s>
</FIRST>
<SECOND>

<s docid="AP880512-0157" num="4" wdcount="2"> AM-Soviet-Sakharov, Bjt,0643</s>
</SECOND>
<HEAD>

<s docid="AP880512-0157" num="5" wdcount="8"> Weekly Prints Sympathetic Portrait of Sakharov, His Wife</s>
</HEAD>
<BYLINE>

<s docid="AP880512-0157" num="6" wdcount="3"> By JOHN-THOR DAHLBURG</s>
</BYLINE>
<BYLINE>

<s docid="AP880512-0157" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880512-0157" num="8" wdcount="2"> MOSCOW (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880512-0157" num="9" wdcount="27"> Soviet media once branded Andrei D. Sakharov a traitor, but a Moscow weekly has now provided a sympathetic portrait of the human rights activist and his wife.</s>

<s docid="AP880512-0157" num="10" wdcount="22"> This week's issue of the newspaper Moscow News said that Sakharov long ago understood the need for change in the Soviet Union.</s>

<s docid="AP880512-0157" num="11" wdcount="30"> The article makes a clear attempt to refute some of the past charges leveled at Sakharov and his wife, fellow dissident Yelena Bonner, by Soviet officials and the state-controlled media.</s>

<s docid="AP880512-0157" num="12" wdcount="16"> Moscow News also pointedly notes that the 1975 Nobel Peace Prize winner has praised Mikhail S.</s>

<s docid="AP880512-0157" num="13" wdcount="7"> Gorbachev's campaign for social and economic reform.</s>

<s docid="AP880512-0157" num="14" wdcount="36"> The 66-year-old Sakharov and his wife lead a frugal existence in their seventh-floor Moscow apartment, eating cabbage, beet soup, potatoes and other simple fare, and Sakharov insists on washing the dishes afterward himself, the paper said.</s>

<s docid="AP880512-0157" num="15" wdcount="24"> It said their two-room home was always filled with people seeking Sakharov's aid, and that the words most often heard there are: ``Help me''.</s>

<s docid="AP880512-0157" num="16" wdcount="9"> But Moscow News asked: ``Can he really do everything''?</s>

<s docid="AP880512-0157" num="17" wdcount="36"> Although the full-page article was the longest on Sakharov to date in the Soviet press, it made only indirect reference to the nearly seven years he spent in exile after criticizing the Kremlin's intervention in Afghanistan.</s>

<s docid="AP880512-0157" num="18" wdcount="32"> Sakharov, a brilliant physicist, was allowed to return to Moscow in December 1986 from his forced residence in the closed city of Gorky, where he was banished without trial in January 1980.</s>

<s docid="AP880512-0157" num="19" wdcount="29"> ``In effect, sometimes Sakharov bitterly jokes that he'd like to return to Gorky for a few months to be able to work alone on scientific work,'' Moscow News said.</s>

<s docid="AP880512-0157" num="20" wdcount="8"> ``Of course, concerning Gorky, that's a bitter joke''.</s>

<s docid="AP880512-0157" num="21" wdcount="29"> Since his return to Moscow, Sakharov has been a vocal supporter of Gorbachev's program for nationwide reforms that includes the policy of ``glasnost,'' or greater openness on selected topics.</s>

<s docid="AP880512-0157" num="22" wdcount="32"> ``He simply believes that something helped change the thoughts of the majority into state policy,'' Moscow News said.``He calls perestroika (restructuring) an enormous event for our country and for the entire world''.</s>

<s docid="AP880512-0157" num="23" wdcount="39"> However, Sakharov has insisted on speedier progress in improving the Soviet record on human rights, and during a Jan. 15 meeting in the Kremlin, he handed Gorbachev a list of 200 people he said were imprisoned for their views.</s>

<s docid="AP880512-0157" num="24" wdcount="22"> Moscow News noted that in 1975, in a tract titled ``Knowledge and the World,'' Sakharov set forth his views on Soviet affairs.</s>

<s docid="AP880512-0157" num="25" wdcount="10"> Those writings have not been published in the Soviet Union.</s>

<s docid="AP880512-0157" num="26" wdcount="23"> ``Now we can definitely see parallels between what he said then, and those ideas that we are putting forward today,'' Moscow News said.</s>

<s docid="AP880512-0157" num="27" wdcount="12"> Sakharov called for a ban on nuclear testing long before the Kremlin.</s>

<s docid="AP880512-0157" num="28" wdcount="33"> The human rights activist, one of the most prominent members of the dissident movement that reached its peak in the 1970s, sought openness in Soviet society years before ``glasnost'' became Communist Party policy.</s>

<s docid="AP880512-0157" num="29" wdcount="21"> Much of the Moscow News article seemed designed to undo harm caused to the Sakharovs by previous press campaigns against them.</s>

<s docid="AP880512-0157" num="30" wdcount="19"> It said one Soviet book accused the Sakharovs of living in ``oriental luxury'' and engaging in ``scandals between spouses''.</s>

<s docid="AP880512-0157" num="31" wdcount="35"> Moscow News said Sakharov was stubborn, unassuming, an undisputed member of his country's intelligentsia and a man with his own views on how to deal conscientiously with world affairs and the demands of this life.</s>

<s docid="AP880512-0157" num="32" wdcount="24"> His strong convictions even extend to his insistence that he do the dishes after meals, wrote the reporter who visited Sakharov at his apartment.</s>

<s docid="AP880512-0157" num="33" wdcount="13"> ``What is that, Andrei Dmitrievich, your hobby''? asked Moscow News correspondent Gennady Zhavoronkov.</s>

<s docid="AP880512-0157" num="34" wdcount="13"> ``Not all guests are able to wash the dishes conscientiously,'' Sakharov replied .</s>
</TEXT>
</DOC>
