<DOC>
<DOCNO>

<s docid="AP891217-0053" num="1" wdcount="1"> AP891217-0053</s>
</DOCNO>
<FILEID>

<s docid="AP891217-0053" num="2" wdcount="2"> AP-NR-12-17-89 1801EST</s>
</FILEID>
<FIRST>

<s docid="AP891217-0053" num="3" wdcount="7"> u i AM-Sakharov 3rdLd-Writethru a0748 12-17 1088</s>
</FIRST>
<SECOND>

<s docid="AP891217-0053" num="4" wdcount="4"> AM-Sakharov, 3rd Ld-Writethru, a0748,1116</s>
</SECOND>
<HEAD>

<s docid="AP891217-0053" num="5" wdcount="5"> Outpouring of Grief For Sakharov</s>
</HEAD>
<HEAD>

<s docid="AP891217-0053" num="6" wdcount="11"> Eds: LEADS with 3 grafs UPDATING estimate of people viewing body.</s>

<s docid="AP891217-0053" num="7" wdcount="8"> Picks up 4th graf, ``My God! .. .</s>
</HEAD>
<BYLINE>

<s docid="AP891217-0053" num="8" wdcount="3"> By ANDREW KATELL</s>
</BYLINE>
<BYLINE>

<s docid="AP891217-0053" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP891217-0053" num="10" wdcount="2"> MOSCOW (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP891217-0053" num="11" wdcount="35"> Mourners sobbed and shook their heads in disbelief Sunday as tens of thousands viewed the flower-draped body of Andrei D. Sakharov in a huge outpouring of grief for the man described as his country's conscience.</s>

<s docid="AP891217-0053" num="12" wdcount="36"> Crimean Tatars and Jewish refuseniks _ two of the groups Sakharov helped _ joined rank-and-file Communists, teachers and engineers in filing past the body of the physicist, Nobel Peace Prize winner, human rights advocate and legislator.</s>

<s docid="AP891217-0053" num="13" wdcount="19"> Based on official sources, an estimated 45,000 people filed through, and the flow of mourners continued into the night.</s>

<s docid="AP891217-0053" num="14" wdcount="29"> A friend of the family, speaking on condition of anonymity, said he heard estimates that 70,000 mourners viewed the body before it was returned to Sakharov's apartment at midnight.</s>

<s docid="AP891217-0053" num="15" wdcount="2"> ``My God!</s>

<s docid="AP891217-0053" num="16" wdcount="29"> Forgive us''! one elderly woman cried out as she saw Sakharov's body in an open coffin, sloping to the floor of the beige marble Youth Palace in central Moscow.</s>

<s docid="AP891217-0053" num="17" wdcount="11"> She apparently meant to apologize for not recognizing his contributions earlier.</s>

<s docid="AP891217-0053" num="18" wdcount="31"> A mound of red and white carnations grew steadily at Sakharov's feet, and a spotlight was focused on a portrait showing Sakharov with his hands over his mouth, deep in thought.</s>

<s docid="AP891217-0053" num="19" wdcount="6"> An organ and piano alternated dirges.</s>

<s docid="AP891217-0053" num="20" wdcount="35"> Sakharov died Thursday alone in his study at the age of 68, apparently of a heart attack, ending a three-decade fight against the jailing of innocent people, for free emigration, for disarmament and other causes.</s>

<s docid="AP891217-0053" num="21" wdcount="37"> Sunday was the first of two days of memorial ceremonies, and the outpouring was remarkable for a man who was once ostracized and committed to nearly seven years in internal exile in the remote city of Gorky.</s>

<s docid="AP891217-0053" num="22" wdcount="20"> There were signs of grief throughout this snowy capital of 9 million people, as though a government leader had died.</s>

<s docid="AP891217-0053" num="23" wdcount="28"> The huge line of mourners, sometimes four deep and heavily bundled against below-zero temperatures, stretched a mile from the palace and poured continuously out of a subway station.</s>

<s docid="AP891217-0053" num="24" wdcount="32"> So many people wanted to see Sakharov's body lying in state that authorities extended the viewing period by four hours and moved the coffin so two rows of mourners could file past.</s>

<s docid="AP891217-0053" num="25" wdcount="38"> Roald Z. Sagdeyev, a member of the official funeral commission, said about 3,000 people an hour were arriving initially, but the official news agency Tass said that rate doubled later, making for a total of 45,000 by nighttime.</s>

<s docid="AP891217-0053" num="26" wdcount="7"> Police lined the sidewalks where people waited.</s>

<s docid="AP891217-0053" num="27" wdcount="17"> Sakharov's widow Yelena Bonner, pleased authorities were not turning people away, praised them for being ``very democratic''.</s>

<s docid="AP891217-0053" num="28" wdcount="19"> In her first detailed public comments on her husband's death, Bonner said she hopes he will not be idolized.</s>

<s docid="AP891217-0053" num="29" wdcount="43"> ``I would not wish a living person _ he has lived an animated, happy life _ to be turned into an icon, an icon which could be used by various forces in their interests,'' Bonner said in an interview broadcast on Soviet TV.</s>

<s docid="AP891217-0053" num="30" wdcount="34"> She said, however, that she hopes Sakharov's writings, published abroad long ago, will become widely available in his homeland so there can be a conversation of ``the people of the future with Andrei Dmitrievich''.</s>

<s docid="AP891217-0053" num="31" wdcount="16"> Mourners carried small portraits of Sakharov and red and white carnations to place near his coffin.</s>

<s docid="AP891217-0053" num="32" wdcount="9"> One man, Sergei Kosykh, brought his 7-year-old daughter along.</s>

<s docid="AP891217-0053" num="33" wdcount="37"> ``My daughter, who is being brought up with the belief that there is nobody greater than (Soviet founder Vladimir) Lenin, I have brought her here today just to show her the person greater than Lenin,'' he said.</s>

<s docid="AP891217-0053" num="34" wdcount="12"> A middle-aged woman drew from Russian literature to reflect on Sakharov's contributions.</s>

<s docid="AP891217-0053" num="35" wdcount="40"> ``He was like the man from one of Maxim Gorky's tales who used his own bleeding and living heart as a torch to lead people to light and truth,'' said the woman, a teacher who declined to give her name.</s>

<s docid="AP891217-0053" num="36" wdcount="23"> ``Sakharov always was telling the truth and by doing so forced our leadership to do the same,'' said Boris Sorokin, a 50-year-old designer.</s>

<s docid="AP891217-0053" num="37" wdcount="14"> Unofficial shrines sprouted outside Sakharov's southeast Moscow apartment, where candles flickered alongside his portrait.</s>

<s docid="AP891217-0053" num="38" wdcount="24"> Outside the offices of the weekly newspaper Moscow News on Pushkin Square, a popular gathering place for political activists, portraits and flowers were displayed.</s>

<s docid="AP891217-0053" num="39" wdcount="20"> An entry in a notebook for mourners' comments outside Sakharov's apartment building declared, ``The conscience of the nation has died''.</s>

<s docid="AP891217-0053" num="40" wdcount="32"> Moscow News _ an organ of the official press, which had branded Sakharov an ``utterly ignorant person'' _ took the rare step Sunday of publishing a special edition devoted to the activist.</s>

<s docid="AP891217-0053" num="41" wdcount="48"> Four pages were filled with pictures of him, condolence telegrams from exiled writer Alexander Solzhenitsyn and President Bush and a text of Sakharov's last public remarks, a speech he delivered hours before his death in which he said the Soviet hierarchy was ``leading the country to a catastrophe''.</s>

<s docid="AP891217-0053" num="42" wdcount="22"> On Sunday night, Soviet TV's newscast ``Seven Days'' also paid tribute to Sakharov, leading the program with a 10-minute report on him.</s>

<s docid="AP891217-0053" num="43" wdcount="40"> The Communist Party daily Pravda published a poem by Yevgeny Yevtushenko that read in part: ``History's most peaceful rebel, in dying, did not come down from the cross, but left a horrifying hole in the moral fabric of the world''.</s>

<s docid="AP891217-0053" num="44" wdcount="12"> On Saturday, Pravda published what amounted to a public apology to Sakharov.</s>

<s docid="AP891217-0053" num="45" wdcount="31"> President Mikhail S. Gorbachev and other Soviet leaders said in an obituary that Sakharov had been the victim of ``gross injustices'' and praised him as a ``man of honesty and sincerity''.</s>

<s docid="AP891217-0053" num="46" wdcount="23"> Bonner, Sakharov's constant companion and fellow human rights activist, sat closest to the coffin, clutching a black handbag and periodically closing her eyes.</s>

<s docid="AP891217-0053" num="47" wdcount="20"> A son and daughter from his first marriage and son and daughter of Bonner also attended, along with four grandchildren.</s>

<s docid="AP891217-0053" num="48" wdcount="22"> Gorbachev was expected to pay his last respects Monday, when the funeral is planned, and on Sunday was represented by Yevgeny M.</s>

<s docid="AP891217-0053" num="49" wdcount="15"> Primakov, chairman of the funeral commission and a non-voting member of the country's ruling Politburo.</s>

<s docid="AP891217-0053" num="50" wdcount="42"> The foreign dignitaries expected to take part in Monday's ceremonies include Lech Walesa, head of Poland's Solidarity movement, who will be making his first trip to the Soviet Union, and former refuseniks Yosef Begun and Vladimir Slepak, who now live in Israel.</s>

<s docid="AP891217-0053" num="51" wdcount="25"> Israel's best known Soviet dissident, Natan Sharansky, was refused a visa when he applied for permission to travel to Moscow, said Sharansky's spokesman, Avraham Ben-Yaakov.</s>

<s docid="AP891217-0053" num="52" wdcount="16"> Begun and Slepak said they would lay a wreath on Sakharov's grave in Sharansky's name .</s>
</TEXT>
</DOC>
