<DOC>
<DOCNO>

<s docid="AP890320-0158" num="1" wdcount="1"> AP890320-0158</s>
</DOCNO>
<FILEID>

<s docid="AP890320-0158" num="2" wdcount="2"> AP-NR-03-20-89 1706EST</s>
</FILEID>
<FIRST>

<s docid="AP890320-0158" num="3" wdcount="7"> u i AM-Sakharov 1stLd-Writethru a0592 03-20 0452</s>
</FIRST>
<SECOND>

<s docid="AP890320-0158" num="4" wdcount="4"> AM-Sakharov, 1st Ld-Writethru, a0592,0463</s>
</SECOND>
<HEAD>

<s docid="AP890320-0158" num="5" wdcount="6"> Sakharov Challenges Science Academy Legislative Slate</s>
</HEAD>
<HEAD>

<s docid="AP890320-0158" num="6" wdcount="9"> Eds: LEADS throughout to UPDATE with Sakarov speech, details.</s>

<s docid="AP890320-0158" num="7" wdcount="3"> No pickup .</s>
</HEAD>
<DATELINE>

<s docid="AP890320-0158" num="8" wdcount="2"> MOSCOW (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890320-0158" num="9" wdcount="33"> Andrei D. Sakharov urged members of the Academy of Sciences on Monday to reject the leadership's list of candidates for the new Soviet legislature, which does not include the Nobel Peace Prize winner.</s>

<s docid="AP890320-0158" num="10" wdcount="37"> The 67-year-old nuclear physicist and human rights activist, who won the Nobel in 1975, said in a speech to the academy that many scientists objected to the slate for Sunday's election approved by the leadership in January.</s>

<s docid="AP890320-0158" num="11" wdcount="13"> Sakharov and several other well-known proponents of reform are missing from the list.</s>

<s docid="AP890320-0158" num="12" wdcount="29"> The official news agency Tass quoted him as saying, however, that scientists were upset ``not because Sakharov was not nominated, but because the role of scientific institutions was ignored''.</s>

<s docid="AP890320-0158" num="13" wdcount="25"> He called for reversal of what he called the anti-democratic decision, which produced a list of what critics describe as old-guard managers of scientific institutions.</s>

<s docid="AP890320-0158" num="14" wdcount="10"> A vote on the academy candidates is scheduled for Tuesday.</s>

<s docid="AP890320-0158" num="15" wdcount="33"> Sakharov was nominated from several geographic districts for a seat in the new 2,250-member Congress of People's Deputies, but he decided to refuse the nominations and fight for an Academy of Sciences seat.</s>

<s docid="AP890320-0158" num="16" wdcount="29"> Under an election law approved in December, 750 seats in the legislature are reserved for the Communist Party and its affiliates and for professional, social and trade union organizations.</s>

<s docid="AP890320-0158" num="17" wdcount="17"> The other 1,500 will be filled by representatives of the 15 Soviet republics and their electoral districts.</s>

<s docid="AP890320-0158" num="18" wdcount="32"> Those in the academy who support Sakharov hope to force a new round of nominations by mustering enough support to deny all nominees a majority, said Andrei Mironov, a former political prisoner.</s>

<s docid="AP890320-0158" num="19" wdcount="22"> That would force the academy to start over and produce a new list of nominees under terms of the new election law.</s>

<s docid="AP890320-0158" num="20" wdcount="16"> Twenty-five seats were allotted to the academy, but it gave five to affiliated societies and associations.</s>

<s docid="AP890320-0158" num="21" wdcount="14"> From 121 nominees, the academy leadership chose 23 candidates for the remaining 20 seats.</s>

<s docid="AP890320-0158" num="22" wdcount="14"> Although 60 research institutes nominated Sakharov, he was not chosen for the final slate.</s>

<s docid="AP890320-0158" num="23" wdcount="15"> The leadership's decision inspired widespread press criticism and a demonstration at the academy's Moscow headquarters.</s>

<s docid="AP890320-0158" num="24" wdcount="18"> Tass said 1,108 academicians, corresponding members and representatives of reseach institutes attended the three-day meeting that began Monday.</s>

<s docid="AP890320-0158" num="25" wdcount="36"> ``The first three days of this week may become the `hottest' spring days for Soviet scientists,'' it said, alluding to the leadership's rejection of such reformers as Sakharov, space scientist Roald Sagdeev and sociologist Tatyana Zaslavsakaya.</s>

<s docid="AP890320-0158" num="26" wdcount="12"> The agency acknowledged ``many scientists were unsatisfied'' with the slate of candidates.</s>

<s docid="AP890320-0158" num="27" wdcount="14"> Mironov said two other academicians also spoke on Monday in favor of new nominations.</s>

<s docid="AP890320-0158" num="28" wdcount="8"> No details of their remarks were available .</s>
</TEXT>
</DOC>
