<DOC>
<DOCNO>

<s docid="AP891216-0037" num="1" wdcount="1"> AP891216-0037</s>
</DOCNO>
<FILEID>

<s docid="AP891216-0037" num="2" wdcount="2"> AP-NR-12-16-89 0526EST</s>
</FILEID>
<FIRST>

<s docid="AP891216-0037" num="3" wdcount="5"> u i PM-Sakharov 12-16 0602</s>
</FIRST>
<SECOND>

<s docid="AP891216-0037" num="4" wdcount="1"> PM-Sakharov,0622</s>
</SECOND>
<HEAD>

<s docid="AP891216-0037" num="5" wdcount="10"> Kremlin Eulogizes Onetime Foe as `Man of Honesty and Sincerity'</s>
</HEAD>
<BYLINE>

<s docid="AP891216-0037" num="6" wdcount="4"> By MARK J. PORUBCANSKY</s>
</BYLINE>
<BYLINE>

<s docid="AP891216-0037" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP891216-0037" num="8" wdcount="2"> MOSCOW (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP891216-0037" num="9" wdcount="35"> In what amounted to a public apology, Mikhail S. Gorbachev and Soviet leaders today eulogized Andrei D. Sakharov as a ``man of honesty and sincerity'' who suffered great injustice at the hands of previous rulers.</s>

<s docid="AP891216-0037" num="10" wdcount="37"> An obituary signed by Gorbachev, five other members of the ruling Communist Party Politburo and 50 other leading officials and scholars was printed along with a picture of Sakharov on page 4 of the party daily Pravda.</s>

<s docid="AP891216-0037" num="11" wdcount="41"> Such obituaries are reserved for favored public figures and scientists, and Pravda emphasized the importance of the 1975 Nobel Peace Prize winner by printing a decree about the formation of a funeral commission in a black box on its front page.</s>

<s docid="AP891216-0037" num="12" wdcount="39"> Sakharov, 68, died Thursday night in his study, just hours after urging fellow members of the Congress of People's Deputies to create a formal opposition to the party in their drive to break its seven-decade strangehold on political power.</s>

<s docid="AP891216-0037" num="13" wdcount="18"> ``A distinguished scientist and public figure, a man of honesty and sincerity has passed away,'' the obituary said.</s>

<s docid="AP891216-0037" num="14" wdcount="14"> ``Everything that Andrei Dmitrievich did was dictated by his conscience, his deep humanitarian convictions''.</s>

<s docid="AP891216-0037" num="15" wdcount="22"> The obituary noted Sakharov was exiled in the industrial city of Gorky about 250 miles east of Moscow from 1980 to 1986.</s>

<s docid="AP891216-0037" num="16" wdcount="11"> ``Gross injustices were permitted in relation to A.D. Sakharov,'' it said.</s>

<s docid="AP891216-0037" num="17" wdcount="25"> It was signed by Gorbachev and fellow Politburo members Nikolai I. Ryzhkov, Vadim A. Medvedev, Lev N. Zaikov, Alexander N. Yakovlev and Vitaly I. Vorotnikov.</s>

<s docid="AP891216-0037" num="18" wdcount="22"> However, the signatures of several other Politburo members, including KGB chief Vladimir A. Kryuchkov and leading conservative Yegor K. Ligachev were missing.</s>

<s docid="AP891216-0037" num="19" wdcount="14"> Absence of their signatures could signify that the disagreed with part of the obituary.</s>

<s docid="AP891216-0037" num="20" wdcount="18"> Ligachev, interviewed by the Tass news agency on Friday, had said he disagreed with Sakharov but respected him.</s>

<s docid="AP891216-0037" num="21" wdcount="29"> It was Leonid I. Brezhnev, now blamed by Gorbachev for permitting stagnation and corruption to overcome the Soviet system, who exiled Sakharov for criticizing the Soviet intervention in Afghanistan.</s>

<s docid="AP891216-0037" num="22" wdcount="16"> Gorbachev called Sakharov in Gorky in December 1986 and told him he could return to Moscow.</s>

<s docid="AP891216-0037" num="23" wdcount="18"> The Soviet leader told reporters at the Congress of People's Deputies that Sakharov's death was a ``great loss''.</s>

<s docid="AP891216-0037" num="24" wdcount="14"> Even though the two often tangled at the Congress, Gorbachev said he respected Sakharov.</s>

<s docid="AP891216-0037" num="25" wdcount="13"> ``He was not some sort of political intriguer,'' the Soviet president said Friday.</s>

<s docid="AP891216-0037" num="26" wdcount="14"> Gorbachev said he would attend Sakharov's funeral Monday afternoon in southwest Moscow's Vostryakovskoye Cemetery.</s>

<s docid="AP891216-0037" num="27" wdcount="18"> Several hundred people gathered outside Sakharov's apartment building Friday evening, holding candles and wreathing his photograph in flowers.</s>

<s docid="AP891216-0037" num="28" wdcount="34"> Memorial services were scheduled Sunday at the city's main youth center, and on Monday at the Lebedev physics institute where Sakharov worked and the Academy of Sciences, of which he was a leading member.</s>

<s docid="AP891216-0037" num="29" wdcount="19"> The popular nighttime TV program ``Vzglad'' showed a brief interview with his widow, Yelena Bonner, discussing the funeral arrangements.</s>

<s docid="AP891216-0037" num="30" wdcount="37"> The obituary also praised Sakharov's vision as a scientist, which made him the youngest-ever member of the Academy of Sciences at age 32 and led to his inclusion in a group that developed the Soviet hydrogen bomb.</s>

<s docid="AP891216-0037" num="31" wdcount="15"> But it said that Sakharov realized the danger of the weapon he had helped create.</s>

<s docid="AP891216-0037" num="32" wdcount="37"> ``Working on the creation of weapons of mass destruction, A.D. Sakharov understood early the danger for humanity of their wide production and testing, and stubbornly placed before the government the question of limiting such tests,'' it said.</s>

<s docid="AP891216-0037" num="33" wdcount="11"> ``But at that time his appeals were not accepted,'' it said.</s>

<s docid="AP891216-0037" num="34" wdcount="8"> ``He kept these same positions in the future.''</s>
</TEXT>
</DOC>
