<DOC>
<DOCNO>

<s docid="LA012189-0060" num="1" wdcount="1"> LA012189-0060</s>
</DOCNO>
<DOCID>

<s docid="LA012189-0060" num="2" wdcount="1"> 8184</s>
</DOCID>
<DATE>
<P>

<s docid="LA012189-0060" num="3" wdcount="6"> January 21, 1989, Saturday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA012189-0060" num="4" wdcount="8"> Part 1; Page 5; Column 1; Foreign Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA012189-0060" num="5" wdcount="2"> 495 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA012189-0060" num="6" wdcount="6"> SOVIET PHYSICISTS SUPPORT SAKHAROV'S PARLIAMENT BID</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA012189-0060" num="7" wdcount="4"> From Times Wire Services</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA012189-0060" num="8" wdcount="1"> MOSCOW</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA012189-0060" num="9" wdcount="32"> In a major rebuff to the Soviet Union's scientific establishment, Soviet physicists Friday nominated Nobel laureate Andrei D. Sakharov to run as a candidate in nationwide parliamentary elections scheduled for March .</s>
</P>
<P>

<s docid="LA012189-0060" num="10" wdcount="36"> The overwhelming vote in favor of the 67-year-old human-rights advocate by his colleagues at Moscow's leading physics institute came only two days after his candidacy was rejected by the governing board of the Academy of Sciences.</s>

<s docid="LA012189-0060" num="11" wdcount="17"> The attempt to prevent Sakharov from running for a revamped Soviet Parliament has outraged Soviet intellectuals .</s>
</P>
<P>

<s docid="LA012189-0060" num="12" wdcount="34"> During a marathon session that ended late Wednesday, the governing board of the Academy of Sciences selected 23 scientists as candidates to fill 25 specially reserved seats in the new Congress of People's Deputies.</s>

<s docid="LA012189-0060" num="13" wdcount="22"> Sakharov and several other leading reformers, including the former director of the Soviet space institute, Roald Sagdeyev, failed to win nomination .</s>
</P>
<P>
</P>
<P>

<s docid="LA012189-0060" num="14" wdcount="2"> Sakharov Supported</s>
</P>
<P>

<s docid="LA012189-0060" num="15" wdcount="21"> During secret balloting Friday at the prestigious Lebedev Institute, the physicists supported Sakharov's candidacy by a vote of 1,543 to 22.</s>

<s docid="LA012189-0060" num="16" wdcount="31"> The outcome was more an expression of respect for Sakharov as a man who stuck by his principles during difficult times than a specific endorsement of all his political views .</s>
</P>
<P>

<s docid="LA012189-0060" num="17" wdcount="28"> Sakharov, however, used the occasion to outline his hopes for a multiparty system, public control over the KGB security police, and the convergence of communism and capitalism .</s>
</P>
<P>

<s docid="LA012189-0060" num="18" wdcount="30"> Although Sakharov has publicly expressed his support for President Mikhail S. Gorbachev, in recent months he seems to have become increasingly concerned about the slow and uneven pace of reform.</s>

<s docid="LA012189-0060" num="19" wdcount="19"> In a question-and-answer session with physicists, he described the political situation in the Soviet Union as "extremely complicated" .</s>
</P>
<P>
</P>
<P>

<s docid="LA012189-0060" num="20" wdcount="3"> 'Far From Delighted'</s>
</P>
<P>

<s docid="LA012189-0060" num="21" wdcount="20"> "I am far from being delighted about all the things that have happened in our country over the last year.</s>

<s docid="LA012189-0060" num="22" wdcount="15"> In many ways, our domestic policies have either been indecisive or incorrect," he said .</s>
</P>
<P>

<s docid="LA012189-0060" num="23" wdcount="28"> Sakharov, who acted as an unofficial Kremlin envoy to the troubled Transcaucasian region last month, said he was particularly dismayed by a government crackdown against leading Armenian nationalists.</s>

<s docid="LA012189-0060" num="24" wdcount="31"> He called for the release from prison of members of the outlawed Karabakh Committee, which has been campaigning for the secession of the largely Armenian-inhabited region of Nagorno-Karabakh from Azerbaijan .</s>
</P>
<P>

<s docid="LA012189-0060" num="25" wdcount="20"> The 1975 Nobel Peace Prize winner outlined a detailed political program which, if implemented, would totally transform the Soviet Union.</s>

<s docid="LA012189-0060" num="26" wdcount="10"> He called for total freedom of movement and association .</s>
</P>
<P>

<s docid="LA012189-0060" num="27" wdcount="32"> Although Sakharov has now been nominated as a candidate from the October electoral district of Moscow, it is by no means certain that his name will appear on the March 26 ballot.</s>

<s docid="LA012189-0060" num="28" wdcount="28"> Under the complicated voting procedures, it is still possible to strike down his candidacy during the so-called "pre-electoral campaign" if more than two candidates have been nominated .</s>
</P>
</TEXT>
<TYPE>
<P>

<s docid="LA012189-0060" num="29" wdcount="1"> Wire</s>
</P>
</TYPE>
<SUBJECT>
<P>

<s docid="LA012189-0060" num="30" wdcount="14"> SAKHAROV, ANDREI D; USSR -- ELECTIONS; USSR -- GOVERNMENT; GOVERNMENT REFORM; POLITICAL CANDIDATES; PHYSICISTS</s>
</P>
</SUBJECT>
</DOC>
