<DOC>
<DOCNO>

<s docid="LA051589-0055" num="1" wdcount="1"> LA051589-0055</s>
</DOCNO>
<DOCID>

<s docid="LA051589-0055" num="2" wdcount="1"> 57243</s>
</DOCID>
<DATE>
<P>

<s docid="LA051589-0055" num="3" wdcount="6"> May 15, 1989, Monday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA051589-0055" num="4" wdcount="8"> Part 1; Page 6; Column 2; Foreign Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA051589-0055" num="5" wdcount="2"> 282 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA051589-0055" num="6" wdcount="7"> SOVIET UNION NEAR ECONOMIC CATASTROPHE, SAKHAROV WARNS</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA051589-0055" num="7" wdcount="2"> From Reuters</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA051589-0055" num="8" wdcount="2"> MILAN, Italy</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA051589-0055" num="9" wdcount="32"> Soviet human rights activist Andrei D. Sakharov said Sunday that his country is on the brink of economic catastrophe because reforms of the old centralized system are too slow in arriving .</s>
</P>
<P>

<s docid="LA051589-0055" num="10" wdcount="39"> While praising the new course in world affairs taken by the Soviet Union, as demonstrated by its withdrawal from Afghanistan, Sakharov told the congress of the Italian Socialist Party that some aspects of internal affairs are "deeply disturbing" .</s>
</P>
<P>

<s docid="LA051589-0055" num="11" wdcount="13"> "We all know about the serious economic situation which can only get worse.</s>

<s docid="LA051589-0055" num="12" wdcount="15"> The budget deficit has reached astronomical proportions of more than 100 billion rubles ($160 billion).</s>

<s docid="LA051589-0055" num="13" wdcount="20"> Economic reforms are proceeding slower and slower and people are losing interest in them because they can't buy anything .</s>
</P>
<P>

<s docid="LA051589-0055" num="14" wdcount="11"> "The old centralized system is being dismantled, and that is right.</s>

<s docid="LA051589-0055" num="15" wdcount="13"> But the trouble is that it is not being replaced by anything new.</s>

<s docid="LA051589-0055" num="16" wdcount="15"> We can say that the country is on the brink of an economic catastrophe" .</s>
</P>
<P>

<s docid="LA051589-0055" num="17" wdcount="40"> Sakharov, who did not mention the name of President Mikhail S. Gorbachev, described as "anti-democratic" some measures taken to quell nationalist unrest, particularly the toxic gas believed to have been used against demonstrators in Soviet Georgia earlier this year .</s>
</P>
<P>

<s docid="LA051589-0055" num="18" wdcount="14"> The physicist also attacked new legislation on personal responsibility now under consideration in Moscow.</s>

<s docid="LA051589-0055" num="19" wdcount="10"> He said the laws could restrict freedom of speech .</s>
</P>
<P>

<s docid="LA051589-0055" num="20" wdcount="29"> Speaking in Russian without notes, he said the new laws were supposed to take the place of measures used against dissidents like himself in the 1970s and 1980s .</s>
</P>
<P>

<s docid="LA051589-0055" num="21" wdcount="27"> Sakharov was elected in April to the new Soviet Congress of People's Deputies, just two years after he was released from seven years of internal exile .</s>
</P>
</TEXT>
<TYPE>
<P>

<s docid="LA051589-0055" num="22" wdcount="1"> Wire</s>
</P>
</TYPE>
<SUBJECT>
<P>

<s docid="LA051589-0055" num="23" wdcount="13"> SAKHAROV, ANDREI D; USSR -- ECONOMY; ECONOMIC FORECASTS; GOVERNMENT REFORM; USSR -- LAWS</s>
</P>
</SUBJECT>
</DOC>
