<DOC>
<DOCNO>

<s docid="LA121589-0192" num="1" wdcount="1"> LA121589-0192</s>
</DOCNO>
<DOCID>

<s docid="LA121589-0192" num="2" wdcount="1"> 149194</s>
</DOCID>
<DATE>
<P>

<s docid="LA121589-0192" num="3" wdcount="6"> December 15, 1989, Friday, P.M. Final</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA121589-0192" num="4" wdcount="9"> Part P; Page 2; Column 3; Late Final Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA121589-0192" num="5" wdcount="2"> 445 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA121589-0192" num="6" wdcount="6"> SAKHAROV PRAISED AS CHAMPION OF FREEDOM</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA121589-0192" num="7" wdcount="4"> From Times Wire Services</s>
</P>
</BYLINE>
<TEXT>
<P>

<s docid="LA121589-0192" num="8" wdcount="38"> World leaders from President Bush to President Mikhail S. Gorbachev today praised Andrei D. Sakharov as a tremendous force for freedom who outlived his Soviet persecutors and saw the liberty he championed take root throughout Eastern Europe .</s>
</P>
<P>

<s docid="LA121589-0192" num="9" wdcount="19"> The 68-year-old scientist and human rights activist died Thursday of an apparent heart attack in his Moscow apartment .</s>
</P>
<P>

<s docid="LA121589-0192" num="10" wdcount="37"> The Soviet Congress stood for a minute of silence for their colleague, once considered a national hero for discovering the Soviet hydrogen bomb but later reviled by Kremlin leadership for his uncompromising stands for human freedom .</s>
</P>
<P>

<s docid="LA121589-0192" num="11" wdcount="20"> Gorbachev, who freed the physicist from seven years of internal exile, called Sakharov a "man of conviction and sincerity" .</s>
</P>
<P>

<s docid="LA121589-0192" num="12" wdcount="6"> "It's a great loss," Gorbachev said.</s>

<s docid="LA121589-0192" num="13" wdcount="18"> "He was a person who had his own ideas, his own convictions which he expressed openly and directly.</s>

<s docid="LA121589-0192" num="14" wdcount="15"> This doesn't mean I agreed with him, although on many things we did agree" .</s>
</P>
<P>

<s docid="LA121589-0192" num="15" wdcount="17"> One Soviet lawmaker called Sakharov a man "such as maybe appears once in a hundred years" .</s>
</P>
<P>

<s docid="LA121589-0192" num="16" wdcount="24"> Bush said that "all of us are diminished" and that Sakharov "embodied all of what is good and decent in the human spirit" .</s>
</P>
<P>

<s docid="LA121589-0192" num="17" wdcount="27"> Bush, in a message of condolence to Sakharov's widow, Yelena Bonner, said: "All of us who knew him will never forget his courage and devotion to freedom.</s>

<s docid="LA121589-0192" num="18" wdcount="24"> . . . Just as he truly enriched all of us with his life, all of us are diminished by his untimely death" .</s>
</P>
<P>

<s docid="LA121589-0192" num="19" wdcount="25"> Aase Lionaes, chairman of the Norwegian Nobel Committee that awarded Sakharov the Peace Prize in 1975, said he "fell in the struggle for democratic reforms.</s>

<s docid="LA121589-0192" num="20" wdcount="26"> His death represents a great loss, especially at a time with hopes of a positive development in the Soviet Union and in all Eastern Europe" .</s>
</P>
<P>

<s docid="LA121589-0192" num="21" wdcount="14"> Political leaders worldwide commended Sakharov as a man whose causes went beyond ideology .</s>
</P>
<P>

<s docid="LA121589-0192" num="22" wdcount="26"> Lech Walesa, a fellow Nobel Peace Prize laureate, said Sakharov's death was "a great loss for reform both in the Soviet Union and everywhere else" .</s>
</P>
<P>

<s docid="LA121589-0192" num="23" wdcount="12"> "He was just a remarkable person," said British Prime Minister Margaret Thatcher.</s>

<s docid="LA121589-0192" num="24" wdcount="26"> "He was one of those who would always say the truth must be found and was never afraid of stating that and letting everyone know" .</s>
</P>
<P>

<s docid="LA121589-0192" num="25" wdcount="23"> "It is just sad he will not be preeminent in the freer future of the Soviet Union," she told reporters in London .</s>
</P>
<P>

<s docid="LA121589-0192" num="26" wdcount="23"> In Strasbourg, France, the 518-member European Parliament unanimously paid tribute to Sakharov, whose name it had given to its Human Rights Prize .</s>
</P>
<P>

<s docid="LA121589-0192" num="27" wdcount="16"> In Brussels, the NATO foreign ministers hailed Sakharov as a pioneer who helped change Soviet society.</s>

<s docid="LA121589-0192" num="28" wdcount="21"> NATO Secretary General Manfred Woerner said, "The ministers expressed deeply felt sense of loss at the passing of Andrei Sakharov" .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA121589-0192" num="29" wdcount="18"> Photo, Mourning for Sakharov Muscovites gather outside the home of Andrei D. Sakharov to pay tribute to him.</s>

<s docid="LA121589-0192" num="30" wdcount="15"> The 68-year-old 1975 Nobel Peace Prize recipient and human rights activist died on Thursday. Tass</s>
</P>
</GRAPHIC>
<TYPE>
<P>

<s docid="LA121589-0192" num="31" wdcount="1"> Wire</s>
</P>
</TYPE>
</DOC>
