<DOC>
<DOCNO>

<s docid="AP900625-0036" num="1" wdcount="1"> AP900625-0036</s>
</DOCNO>
<FILEID>

<s docid="AP900625-0036" num="2" wdcount="2"> AP-NR-06-25-90 0333EDT</s>
</FILEID>
<FIRST>

<s docid="AP900625-0036" num="3" wdcount="5"> r i PM-Iran-Aid 06-25 0613</s>
</FIRST>
<SECOND>

<s docid="AP900625-0036" num="4" wdcount="1"> PM-Iran-Aid,0636</s>
</SECOND>
<HEAD>

<s docid="AP900625-0036" num="5" wdcount="8"> Tons of Relief Supplies Arriving, But Distribution Difficult</s>
</HEAD>
<HEAD>

<s docid="AP900625-0036" num="6" wdcount="3"> With PM-Iran-Quake, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP900625-0036" num="7" wdcount="3"> By NEIL MacFARQUHAR</s>
</BYLINE>
<BYLINE>

<s docid="AP900625-0036" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900625-0036" num="9" wdcount="3"> TEHRAN, Iran (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900625-0036" num="10" wdcount="32"> Planes loaded with food, medicine and tents are converging on earthquake-stricken Iran from around the world, among them the first private American relief mission to the country in more than a decade.</s>

<s docid="AP900625-0036" num="11" wdcount="15"> Authorities now are faced with the difficult task of getting supplies into the affected areas.</s>

<s docid="AP900625-0036" num="12" wdcount="20"> More than 60 aftershocks jolted the quake zone in northwestern Iran on Sunday, triggering landslides along one key relief route.</s>

<s docid="AP900625-0036" num="13" wdcount="18"> Tehran radio said Sunday that 68 relief aircraft had landed at Tehran's Mehrabad airport during a 24-hour period.</s>

<s docid="AP900625-0036" num="14" wdcount="14"> Among them was a plane carrying medicine and other supplies from the United States.</s>

<s docid="AP900625-0036" num="15" wdcount="9"> Another plane carrying U.S. government aid was due today.</s>

<s docid="AP900625-0036" num="16" wdcount="30"> The shipment that arrived Sunday was the first of its kind to be accepted by Iran since the hostage crisis of 1979-80, when 52 Americans were held at the U.S.</s>

<s docid="AP900625-0036" num="17" wdcount="3"> Embassy in Tehran.</s>

<s docid="AP900625-0036" num="18" wdcount="27"> Two countries that also have suffered devastating earthquakes in recent years, the Soviet Union and Mexico, were among those sending assistance to help victims of Thursday's quake.</s>

<s docid="AP900625-0036" num="19" wdcount="20"> Leaders of Iran's Arab neighbors, including Iraq, which waged an eight-year war with Iran, issued statements of sympathy and support.</s>

<s docid="AP900625-0036" num="20" wdcount="25"> Pope John Paul II called on the international community to help earthquake victims, asking for ``a real and generous demonstration of solidarity with our brothers.</s>

<s docid="AP900625-0036" num="21" wdcount="8"> Let us pray that their suffering is alleviated''.</s>

<s docid="AP900625-0036" num="22" wdcount="8"> The Vatican was among the many international donors.</s>

<s docid="AP900625-0036" num="23" wdcount="19"> Eleven planes from West Germany ferried in 145 tons of supplies plus a field hospital with two medical teams.</s>

<s docid="AP900625-0036" num="24" wdcount="5"> Nine flights arrived from Turkey.</s>

<s docid="AP900625-0036" num="25" wdcount="11"> The Spanish Red Cross sent medicines and food; India sent medicine.</s>

<s docid="AP900625-0036" num="26" wdcount="9"> The Austrian Red Cross shipped tents, blankets and medicine.</s>

<s docid="AP900625-0036" num="27" wdcount="27"> Bernard Kouchner, the French secretary of state for humanitarian action, arrived in Iran on Sunday to coordinate French assistance and evaluate future needs, Radio France Inter said.</s>

<s docid="AP900625-0036" num="28" wdcount="24"> The French government has sent a civil defense team of 195 people and 18 search dogs along with at least 24 tons of equipment.</s>

<s docid="AP900625-0036" num="29" wdcount="63"> The Saudi-based 46-member Organization of the Islamic Conference, an umbrella organization for the world's estimated one billion Moslems, issued an ``urgent appeal to the international community and especially Islamic countries and organizations to hasten with emergency aid for the Iranians ''... AmeriCares, a private U.S. relief organization based in New Canaan, Conn., flew in the 42 tons pounds of supplies that arrived Sunday.</s>

<s docid="AP900625-0036" num="30" wdcount="22"> ``To be on the ground here in Tehran is a very special feeeling for us,'' said Stephen M. Johnson, president of AmeriCares.</s>

<s docid="AP900625-0036" num="31" wdcount="5"> A spokeswoman for the U.S.</s>

<s docid="AP900625-0036" num="32" wdcount="26"> Agency for International Development said a Red Cross charter flight carrying $225,000 worth of supplies donated by the U.S. government would arrive in Tehran this morning.</s>

<s docid="AP900625-0036" num="33" wdcount="20"> Iran is believed to have influence with the Shiite Moslem extremists holding 16 Western hostages, including six Americans, in Lebanon.</s>

<s docid="AP900625-0036" num="34" wdcount="13"> The longest-held is Terry Anderson, chief Middle East correspondent of The Associated Press.</s>

<s docid="AP900625-0036" num="35" wdcount="6"> He was kidnapped March 16, 1985.</s>

<s docid="AP900625-0036" num="36" wdcount="14"> The Soviet Union sent in medical teams and supplies from Soviet republics bordering Iran.</s>

<s docid="AP900625-0036" num="37" wdcount="23"> More than 200 medical personnel arrived from the Soviet Union, which also sent medical supplies, trucks, trailers, ambulances, cranes, buses and water tankers.</s>

<s docid="AP900625-0036" num="38" wdcount="13"> The December 1988 earthquake in Soviet Armenia left at least 25,000 people dead.</s>

<s docid="AP900625-0036" num="39" wdcount="21"> Mexico, which lost at least 10,000 people in a 1985 earthquake, is sending food, medical supplies and blankets, officials said Sunday.</s>

<s docid="AP900625-0036" num="40" wdcount="23"> In Lebanon, the Iranian-backed Hezbollah, or Party of God, said its members were donating 10 percent of their salaries to help the victims.</s>

<s docid="AP900625-0036" num="41" wdcount="17"> That would amount to about $500,000, according to Hezbollah sources, who spoke on condition of anonymity .</s>
</TEXT>
</DOC>
