<DOC>
<DOCNO>

<s docid="AP900623-0022" num="1" wdcount="1"> AP900623-0022</s>
</DOCNO>
<FILEID>

<s docid="AP900623-0022" num="2" wdcount="2"> AP-NR-06-23-90 0233EDT</s>
</FILEID>
<FIRST>

<s docid="AP900623-0022" num="3" wdcount="5"> r w PM-Iran-Rally 06-23 0490</s>
</FIRST>
<SECOND>

<s docid="AP900623-0022" num="4" wdcount="1"> PM-Iran-Rally,460</s>
</SECOND>
<HEAD>

<s docid="AP900623-0022" num="5" wdcount="6"> Group Claims Iran Underreporting Earthquake Casualties</s>
</HEAD>
<HEAD>

<s docid="AP900623-0022" num="6" wdcount="2"> With PM-Iran-Quake</s>
</HEAD>
<HEAD>

<s docid="AP900623-0022" num="7" wdcount="5"> LaserPhoto WX21 of June 22</s>
</HEAD>
<BYLINE>

<s docid="AP900623-0022" num="8" wdcount="5"> By ROBERT NAYLOR JR .</s>
</BYLINE>
<BYLINE>

<s docid="AP900623-0022" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900623-0022" num="10" wdcount="2"> WASHINGTON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900623-0022" num="11" wdcount="31"> Iran is deliberately underreporting the number of casualties from Thursday's massive earthquake out of fear of a political backlash, leaders of a group seeking to overthrow the country's Islamic leadership say.</s>

<s docid="AP900623-0022" num="12" wdcount="19"> ``The regime is very much fearful of public outrage,'' said Shahin Gobadi, spokesman for the People's Mojahedin of Iran.</s>

<s docid="AP900623-0022" num="13" wdcount="8"> ``They're very much afraid of the political aftershocks''.</s>

<s docid="AP900623-0022" num="14" wdcount="26"> As Gobadi spoke Friday, members of the organization denounced Iran's government at a noisy rally held in a park across the street from the White House.</s>

<s docid="AP900623-0022" num="15" wdcount="17"> Northern Iran was stuck Thursday by an earthquake measuring between 7.3 and 7.7 on the Richter Scale.</s>

<s docid="AP900623-0022" num="16" wdcount="25"> Iran has told the United Nations that the death toll is at least 36,000, but Gobadi said his organization has received estimates closer to 100,000.</s>

<s docid="AP900623-0022" num="17" wdcount="25"> Gobadi said the country cannot properly assist earthquake victims because its treasury has been spent in a war with neighboring Iraq and against internal opposition.</s>

<s docid="AP900623-0022" num="18" wdcount="11"> ``They have been very late in assisting the people,'' he said.</s>

<s docid="AP900623-0022" num="19" wdcount="23"> Sympathy for the earthquake victims was a secondary issue for the chanting, flag-waving rally participants, who also carried signs criticizing their native country.</s>

<s docid="AP900623-0022" num="20" wdcount="21"> Planning for the event began three weeks before the earthquake, but part of the Friday's activities focused on Iran's stricken residents.</s>

<s docid="AP900623-0022" num="21" wdcount="21"> Gobadi said shoddy housing in which the government forced people to live was the cause for the widespread loss of life.</s>

<s docid="AP900623-0022" num="22" wdcount="10"> ``This regime has brought them nothing but devastation and misery.</s>

<s docid="AP900623-0022" num="23" wdcount="24"> This regime has devoted all of its resources to a senseless war with Iraq and to oppression of the people at home,'' he said.</s>

<s docid="AP900623-0022" num="24" wdcount="14"> A U.N.-sponsored cease-fire was declared last year after eight years of the Iran-Iraq war.</s>

<s docid="AP900623-0022" num="25" wdcount="23"> Iran's Islamic republic was established in 1979 after Shah Mohammad Reza Pahlavi was deposed by Ayatollah Ruhollah Khomeini and militants seized the U.S.</s>

<s docid="AP900623-0022" num="26" wdcount="7"> Embassy in Tehran, taking 66 Americans hostage.</s>

<s docid="AP900623-0022" num="27" wdcount="11"> The United States broke diplomatic relations with Iran in April 1980.</s>

<s docid="AP900623-0022" num="28" wdcount="20"> The shah died in exile in July 1980, U.S. hostages were freed six months later and Khomeini died last June.</s>

<s docid="AP900623-0022" num="29" wdcount="19"> Gobadi said his 25-year-old group had helped depose the shah but had no part in organizing the Islamic republic.</s>

<s docid="AP900623-0022" num="30" wdcount="19"> ``Even in this tragedy for which we grieve we cannot trust the regime in Iran,'' Rep. Mervyn Dymally, D-Calif.</s>

<s docid="AP900623-0022" num="31" wdcount="9"> , told an estimated 3,000 people attending the rally.</s>

<s docid="AP900623-0022" num="32" wdcount="28"> ``There were many, many victims before this tragedy and there are victims now whose needs need to be addressed by the people of the United States,'' he said.</s>

<s docid="AP900623-0022" num="33" wdcount="31"> Dymally, a member of the House Foreign Affairs Committee, praised President Bush's offer of humanitarian aid to Iran but said Bush must make sure the assistance is channeled through non-government groups.</s>

<s docid="AP900623-0022" num="34" wdcount="24"> The State Department said Friday that Iran was willing to accept earthquake relief from the American Red Cross and other U.S. humanitarian organizations .</s>
</TEXT>
</DOC>
