<DOC>
<DOCNO>

<s docid="AP900622-0025" num="1" wdcount="1"> AP900622-0025</s>
</DOCNO>
<FILEID>

<s docid="AP900622-0025" num="2" wdcount="2"> AP-NR-06-22-90 0329EDT</s>
</FILEID>
<FIRST>

<s docid="AP900622-0025" num="3" wdcount="5"> r i PM-IranQuake-Structures 06-22 0302</s>
</FIRST>
<SECOND>

<s docid="AP900622-0025" num="4" wdcount="2"> PM-Iran Quake-Structures,0312</s>
</SECOND>
<HEAD>

<s docid="AP900622-0025" num="5" wdcount="8"> Iran Earthquake Caught Victims Asleep in Fragile Homes</s>
</HEAD>
<HEAD>

<s docid="AP900622-0025" num="6" wdcount="3"> With PM-Iran-Quake, Bjt</s>
</HEAD>
<DATELINE>

<s docid="AP900622-0025" num="7" wdcount="3"> NEW YORK (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900622-0025" num="8" wdcount="17"> The earthquake that struck northern Iran brought reminders of another quake that devastated Soviet Armenia in 1988.</s>

<s docid="AP900622-0025" num="9" wdcount="16"> Like Thursday's earthquake in Iran, the Dec. 7, 1988, earthquake in Armenia killed about 25,000 people.</s>

<s docid="AP900622-0025" num="10" wdcount="10"> Most died in structures that collapsed when the quake hit.</s>

<s docid="AP900622-0025" num="11" wdcount="17"> ``It's very similar to what we had in Armenia,'' said Russ Needham, a geophysicist with the U.S.</s>

<s docid="AP900622-0025" num="12" wdcount="2"> Geological Survey.</s>

<s docid="AP900622-0025" num="13" wdcount="26"> The Armenian quake was measured at 6.9 on the Richter scale, but Thursday's earthquake shook the earth with a magnitude of 7.7 according to the U.S.</s>

<s docid="AP900622-0025" num="14" wdcount="2"> Geological Survey.</s>

<s docid="AP900622-0025" num="15" wdcount="25"> In the Iranian quake, the casualty count was pushed up by the fact that people were indoors and asleep at the time, just after midnight.</s>

<s docid="AP900622-0025" num="16" wdcount="18"> Many of the victims lived in fragile homes built of a ceramic-type brick or adobe that collapses easily.</s>

<s docid="AP900622-0025" num="17" wdcount="19"> In the Armenian quake, a Soviet parliamentary report later blamed the high number of fatalities on shoddily built buildings.</s>

<s docid="AP900622-0025" num="18" wdcount="22"> ``Most casualties from earthquakes are caused by something falling on top of you,'' said Needham in a telephone interview from Golden, Colo.</s>

<s docid="AP900622-0025" num="19" wdcount="34"> The quake struck an area of Iran where most of the buildings are built on a flood plain of loosely deposited soil that shifts in an earthquake and allows structures to collapse, Needham said.</s>

<s docid="AP900622-0025" num="20" wdcount="22"> The 7.7-magnitude quake was the largest ever recorded in that area, where two major plates of the earth's crust meet, he said.</s>

<s docid="AP900622-0025" num="21" wdcount="18"> ``Iran is in a very active seismic region,'' he said, and that there have been many smaller quakes.</s>

<s docid="AP900622-0025" num="22" wdcount="17"> Twelve earthquakes greater than magnitude 7 have occurred in Iran during the last 30 years, Needham said.</s>

<s docid="AP900622-0025" num="23" wdcount="19"> A quake of magnitude 7 is considered a major earthquake, capable of widespread, heavy damage in populated areas .</s>
</TEXT>
</DOC>
