<DOC>
<DOCNO>

<s docid="AP900626-0010" num="1" wdcount="1"> AP900626-0010</s>
</DOCNO>
<FILEID>

<s docid="AP900626-0010" num="2" wdcount="2"> AP-NR-06-26-90 0111EDT</s>
</FILEID>
<FIRST>

<s docid="AP900626-0010" num="3" wdcount="5"> r a PM-USAid-Iran 06-26 0657</s>
</FIRST>
<SECOND>

<s docid="AP900626-0010" num="4" wdcount="2"> PM-US Aid-Iran,0678</s>
</SECOND>
<HEAD>

<s docid="AP900626-0010" num="5" wdcount="9"> Contributions for Iranian Relief Light, Expected to Pick Up</s>
</HEAD>
<NOTE>

<s docid="AP900626-0010" num="6" wdcount="7"> Eds: Also in Tuesday AMs report .</s>
</NOTE>
<HEAD>

<s docid="AP900626-0010" num="7" wdcount="3"> With PM-Iran-Quake, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP900626-0010" num="8" wdcount="4"> By JANET L. CAPPIELLO</s>
</BYLINE>
<BYLINE>

<s docid="AP900626-0010" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<TEXT>

<s docid="AP900626-0010" num="10" wdcount="27"> Americans who rushed to donate money to help victims of the Armenian earthquake 18 months ago are responding more slowly to last week's killer earthquake in Iran.</s>

<s docid="AP900626-0010" num="11" wdcount="10"> But relief agencies said they expect contributions to pick up.</s>

<s docid="AP900626-0010" num="12" wdcount="21"> ``There's a hierarchy of responsiveness,'' said Dick Colenso, associate executive director of World Concern, a private relief agency based in Seattle.</s>

<s docid="AP900626-0010" num="13" wdcount="20"> ``Something happens in Europe, there's a very large response, Asia, a pretty good respons down to the Middle East ...</s>

<s docid="AP900626-0010" num="14" wdcount="6"> thee. When you get dynamics change''.</s>

<s docid="AP900626-0010" num="15" wdcount="15"> Colenso said, however, that contributions will ``surge upward'' as news spreads of the earthquake's destruction.</s>

<s docid="AP900626-0010" num="16" wdcount="2"> ``As ...</s>

<s docid="AP900626-0010" num="17" wdcount="18"> you get the disaster translated into the lives of individuals instead of mass numbers, people begin to respond.</s>

<s docid="AP900626-0010" num="18" wdcount="6"> They relate to that,'' he said.</s>

<s docid="AP900626-0010" num="19" wdcount="16"> At least 50,000 people were reported killed and 200,000 injured in the earthquake that struck Thursday.</s>

<s docid="AP900626-0010" num="20" wdcount="23"> AmeriCares, a private agency based in New Canaan, Conn., brought the first shipment of supplies from the United States into Iran on Sunday.</s>

<s docid="AP900626-0010" num="21" wdcount="27"> The shipment was the first of its kind to be accepted by Iran since the hostage crisis of 1979-80, when 52 Americans were held at the U.S.</s>

<s docid="AP900626-0010" num="22" wdcount="3"> Embassy in Tehran.</s>

<s docid="AP900626-0010" num="23" wdcount="7"> Iran is believede-scale structure in the universe.</s>

<s docid="AP900626-0010" num="24" wdcount="21"> AWARDS: National Award for Science and Technology, 1978; Chinese Academy of Sciences Award 1982; New York Academy of Sciences Award, 1988.</s>

<s docid="AP900626-0010" num="25" wdcount="13"> POLITICAL DISSENT: Fang became politically prominent during the pro-democracy student demonstrations of 1986-87.</s>

<s docid="AP900626-0010" num="26" wdcount="28"> His speeches to students at the University of Science and Technology in Hefei in central China, where he was vice president, helped incite the protests, party hard-liners said.</s>

<s docid="AP900626-0010" num="27" wdcount="18"> Fang was expelled from the Communist Party in 1957, when he said Marxist theory on physics was obsolete.</s>

<s docid="AP900626-0010" num="28" wdcount="10"> In 1987, he was fired from his Hefei university posts.</s>

<s docid="AP900626-0010" num="29" wdcount="22"> In between, in 1966, he was a victim of the Cultural Revolution purges and was sent to a communal farm for ``re-education''.</s>

<s docid="AP900626-0010" num="30" wdcount="21"> After the June 4, 1989, military crackdown on the democracy movement, Fang and Li obtained refuge in the U.S. Embassy .</s>
</TEXT>
</DOC>
