<DOC>
<DOCNO>

<s docid="AP900624-0011" num="1" wdcount="1"> AP900624-0011</s>
</DOCNO>
<FILEID>

<s docid="AP900624-0011" num="2" wdcount="2"> AP-NR-06-24-90 1145EDT</s>
</FILEID>
<FIRST>

<s docid="AP900624-0011" num="3" wdcount="5"> r i AM-Iran-US 06-24 0292</s>
</FIRST>
<SECOND>

<s docid="AP900624-0011" num="4" wdcount="1"> AM-Iran-US,0301</s>
</SECOND>
<HEAD>

<s docid="AP900624-0011" num="5" wdcount="9"> Radical Paper Blames U.S., In Part, For Quake Damage</s>
</HEAD>
<HEAD>

<s docid="AP900624-0011" num="6" wdcount="3"> With AM-Iran-Quake, Bjt</s>
</HEAD>
<DATELINE>

<s docid="AP900624-0011" num="7" wdcount="3"> TEHRAN, Iran (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900624-0011" num="8" wdcount="27"> An anti-American newspaper in Iran said Sunday the United States is partly to blame for the death of tens of thousands of people in last week's earthquake.</s>

<s docid="AP900624-0011" num="9" wdcount="31"> The ``criminal role of America in Iran's past became evident once again in the recent earthquake,'' the Jomhuri Islami said in an editorial reported by the official Islamic Republic News Agency.</s>

<s docid="AP900624-0011" num="10" wdcount="24"> ``Our people, even under the rubble, chant `Death to America' and pray to God to cut off the hands of the United States ...</s>

<s docid="AP900624-0011" num="11" wdcount="9"> even those hands stretched out to help,'' it said.</s>

<s docid="AP900624-0011" num="12" wdcount="39"> It argued that by ``plundering Iran's oil and other resources'' for 25 years, the United States had prevented the use of even a small part of the national wealth for urban development projects and ``advanced (anti-seismic) building construction systems''.</s>

<s docid="AP900624-0011" num="13" wdcount="27"> ``Even after its expulsion from Iran, the U.S. government by imposing economic sanctions and launching several other plots, halted the renovation of the country,'' the editorial added.</s>

<s docid="AP900624-0011" num="14" wdcount="21"> The newspaper was implying that with these actions the United States had blocked the diversion of funds to earthquake safety measures.</s>

<s docid="AP900624-0011" num="15" wdcount="27"> ``If the United States has real humanitarian objectives and intended to help the Iranian nation, it should do only one thing, stop hatching plots,'' the newspaper said.</s>

<s docid="AP900624-0011" num="16" wdcount="26"> It called on Iranians to reject relief offers by the United States and ``other governments whose hands are stained with the blood of the Iranian people''.</s>

<s docid="AP900624-0011" num="17" wdcount="16"> Iran, at odds with the United States since the 1979 seizure of hostages at the U.S.</s>

<s docid="AP900624-0011" num="18" wdcount="19"> Embassy in Tehran, has said it would welcome relief from the American Red Cross and other U.S. humanitarian groups.</s>

<s docid="AP900624-0011" num="19" wdcount="8"> The two nations have no diplomatic ties .</s>
</TEXT>
</DOC>
