<DOC>
<DOCNO>

<s docid="LA062590-0096" num="1" wdcount="1"> LA062590-0096</s>
</DOCNO>
<DOCID>

<s docid="LA062590-0096" num="2" wdcount="1"> 238671</s>
</DOCID>
<DATE>
<P>

<s docid="LA062590-0096" num="3" wdcount="7"> June 25, 1990, Monday, Orange County Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA062590-0096" num="4" wdcount="9"> Metro; Part B; Page 1; Column 6; Metro Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA062590-0096" num="5" wdcount="2"> 703 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA062590-0096" num="6" wdcount="6"> COUNTY'S IRANIANS OFFER AID IN QUAKE;</s>
</P>
<P>

<s docid="LA062590-0096" num="7" wdcount="23"> RESCUE: MONEY, MEDICINE AND MEANS OF SHELTER ARE BEING COLLECTED FOR THE THOUSANDS OF INJURED AND HOMELESS BY PROFESSIONAL AND COMMUNITY GROUPS .</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA062590-0096" num="8" wdcount="6"> By GEORGE FRANK, TIMES STAFF WRITER</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA062590-0096" num="9" wdcount="1"> IRVINE</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA062590-0096" num="10" wdcount="36"> Orange County's Iranian community launched an ambitious effort Sunday to collect half a million dollars in money, medicine, tents, blankets and sleeping bags for hundreds of thousands of injured and homeless people in earthquake-ravaged Iran .</s>
</P>
<P>

<s docid="LA062590-0096" num="11" wdcount="29"> Representatives of 11 Iranian professional and community groups manned tables near William R. Mason Regional Park, where contributors dropped off supplies, pledged other aid or made financial contributions .</s>
</P>
<P>

<s docid="LA062590-0096" num="12" wdcount="12"> Organizers said they hope to raise at least $500,000 in donations .</s>
</P>
<P>

<s docid="LA062590-0096" num="13" wdcount="12"> "We'll do this as long as it takes," said organizer Bijan Kian.</s>

<s docid="LA062590-0096" num="14" wdcount="8"> "We will be back here again next Sunday.</s>

<s docid="LA062590-0096" num="15" wdcount="18"> I have been in contact with a group that raised $150,000 (Saturday) by telephoning from home to home.</s>

<s docid="LA062590-0096" num="16" wdcount="7"> This is from their friends and relatives.</s>

<s docid="LA062590-0096" num="17" wdcount="9"> I'm sure we can double and triple that" .</s>
</P>
<P>

<s docid="LA062590-0096" num="18" wdcount="30"> The 50 organizers Sunday wore black armbands expressing their grief for those killed, injured and left homeless in what they described as that country's worst earthquake of the century .</s>
</P>
<P>

<s docid="LA062590-0096" num="19" wdcount="26"> In Iran, rescue efforts were hampered Sunday as the strongest aftershock yet jarred the already severely damaged rice-growing region of Rasht, 120 miles northwest of Tehran.</s>

<s docid="LA062590-0096" num="20" wdcount="31"> The new shock, with a magnitude of 5.7, toppled the few still-standing structures and caused mudslides that temporarily closed the road linking Rasht with other destruction zones in Zanjan province .</s>
</P>
<P>

<s docid="LA062590-0096" num="21" wdcount="17"> Estimates of the number killed in the devastating quake reached 50,000, with an additional 200,000 injured .</s>
</P>
<P>

<s docid="LA062590-0096" num="22" wdcount="22"> Army mountaineers climbed rugged mountains Sunday in an effort to rescue villagers trapped in remote hamlets in the ravaged northern provinces .</s>
</P>
<P>

<s docid="LA062590-0096" num="23" wdcount="15"> "They have no water or electricity," said Farrokh Shokooh, another organizer of the Sunday fund-raiser.</s>

<s docid="LA062590-0096" num="24" wdcount="14"> "Everything is made that much more difficult because it is the rainy season" .</s>
</P>
<P>

<s docid="LA062590-0096" num="25" wdcount="16"> Shokooh said the effort to help the earthquake victims was put together hastily Friday afternoon .</s>
</P>
<P>

<s docid="LA062590-0096" num="26" wdcount="24"> The group set up the collection point in front of William R. Mason Regional Park on property belonging to the City of Irvine .</s>
</P>
<P>

<s docid="LA062590-0096" num="27" wdcount="28"> Irvine Police Sgt. Tom Hume, who is in charge of policing special events held in the city, said the group failed to obtain a permit from the city.</s>

<s docid="LA062590-0096" num="28" wdcount="25"> But police accommodated the group, blocking off a bike lane on University Avenue so cars could pull in and unload supplies for the earthquake victims.</s>

<s docid="LA062590-0096" num="29" wdcount="13"> The supplies were put into a large truck parked along the road .</s>
</P>
<P>

<s docid="LA062590-0096" num="30" wdcount="15"> Hume said that two officers assigned to the event reported the crowd as small .</s>
</P>
<P>

<s docid="LA062590-0096" num="31" wdcount="28"> Organizer Genia Panahi, 40, of Newport Beach, said the 150 Iranian doctors practicing in Orange County responded to calls for medicine, surgical gloves, disposable needles and blood bags.</s>

<s docid="LA062590-0096" num="32" wdcount="12"> Organizers said between 60,000 and 80,000 Iranians live in Orange County .</s>
</P>
<P>

<s docid="LA062590-0096" num="33" wdcount="20"> "Medicine is in such a short supply over there," said Panahi, who along with her husband is a medical doctor.</s>

<s docid="LA062590-0096" num="34" wdcount="11"> "Doctors are being asked to donate needles, gloves and antibiotics" .</s>
</P>
<P>

<s docid="LA062590-0096" num="35" wdcount="24"> Her 17-year-old son, Homan, and his friend Sepehr Khonsari worked throughout the day Saturday collecting medical supplies from doctors' offices throughout the county .</s>
</P>
<P>

<s docid="LA062590-0096" num="36" wdcount="24"> The group -- the Orange County Committee for Iran Earthquake Relief -- has set up a special account at Capital Bank in Santa Ana.</s>

<s docid="LA062590-0096" num="37" wdcount="20"> Checks can be made out to the Iran Earthquake Fund and mailed to the bank at 400 N. Tustin Ave.</s>

<s docid="LA062590-0096" num="38" wdcount="17"> Blankets, tents and sleeping bags can be delivered to the Iranian Cultural Center at 8361 Westminster Blvd.</s>

<s docid="LA062590-0096" num="39" wdcount="6"> , Suite 220, in Westminster .</s>
</P>
<P>

<s docid="LA062590-0096" num="40" wdcount="23"> Kian said money sent to the special Capital Bank account will be turned over to the Red Cross for distribution in Iran .</s>
</P>
<P>

<s docid="LA062590-0096" num="41" wdcount="21"> Red Cross representative Sylvia Stewart said the Red Cross will accept only monetary contributions because shipping supplies there is very expensive.</s>

<s docid="LA062590-0096" num="42" wdcount="16"> She said sending money and allowing the supplies to be purchased there "helps stimulate the economy".</s>

<s docid="LA062590-0096" num="43" wdcount="18"> She said the donations are sent to the national Red Cross and then to the international organization .</s>
</P>
<P>

<s docid="LA062590-0096" num="44" wdcount="24"> The Iranian Student Assn. at California State Fullerton has set up a booth in Parking Lot C near State College Boulevard and Nutwood Avenue.</s>

<s docid="LA062590-0096" num="45" wdcount="20"> The donations will be forwarded to the Red Cross or they may be sent directly to the Red Cross, P.O.</s>

<s docid="LA062590-0096" num="46" wdcount="7"> Box 11364, Santa Ana, CA. 92711-1364 .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA062590-0096" num="47" wdcount="16"> Photo, Volunteer Behrooz Azarian, 37, of Santa Ana loads donations onto truck outside Mason Regional Park.</s>

<s docid="LA062590-0096" num="48" wdcount="6"> JOHN FUNG / Los Angeles Times</s>
</P>
</GRAPHIC>
<SUBJECT>
<P>

<s docid="LA062590-0096" num="49" wdcount="18"> EARTHQUAKES -- IRAN; IRAN -- RELIEF; DISASTERS -- IRAN; DISASTER RELIEF; IRANIANS -- ORANGE COUNTY; CONTRIBUTIONS; RELIEF ORGANIZATIONS</s>
</P>
</SUBJECT>
</DOC>
