<DOC>
<DOCNO>

<s docid="LA062290-0169" num="1" wdcount="1"> LA062290-0169</s>
</DOCNO>
<DOCID>

<s docid="LA062290-0169" num="2" wdcount="1"> 237434</s>
</DOCID>
<DATE>
<P>

<s docid="LA062290-0169" num="3" wdcount="6"> June 22, 1990, Friday, P.M. Final</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA062290-0169" num="4" wdcount="9"> Part P; Page 1; Column 1; Late Final Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA062290-0169" num="5" wdcount="2"> 503 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA062290-0169" num="6" wdcount="4"> IRAN ACCEPTS U.S. HELP;</s>
</P>
<P>

<s docid="LA062290-0169" num="7" wdcount="5"> EARTHQUAKE DEATH TOLL HITS 35,000</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA062290-0169" num="8" wdcount="4"> From Times Wire Services</s>
</P>
</BYLINE>
<TEXT>
<P>

<s docid="LA062290-0169" num="9" wdcount="37"> Iran said today that it would welcome relief offered by its bitter enemy, the United States, to help victims of the earthquake that has killed as many as 35,000 people, the State Department said in Washington .</s>
</P>
<P>

<s docid="LA062290-0169" num="10" wdcount="21"> The aid would be accepted through the American Red Cross and other U.S. humanitarian organizations, deputy spokesman Richard Boucher said .</s>
</P>
<P>

<s docid="LA062290-0169" num="11" wdcount="16"> "We want to be helpful without regard for our political differences with Iran," he said .</s>
</P>
<P>

<s docid="LA062290-0169" num="12" wdcount="19"> There have been only rare instances of U.S.-Iranian cooperation since the two countries broke diplomatic relations a decade ago.</s>

<s docid="LA062290-0169" num="13" wdcount="20"> The United States holds Iran partly responsible for the continued detention of American hostages by pro-Iranian groups in Lebanon .</s>
</P>
<P>

<s docid="LA062290-0169" num="14" wdcount="29"> Boucher said Iran told the U.S. government that private donor agencies should contact the Iranian Red Crescent, a humanitarian group that is the conduit for all outside assistance .</s>
</P>
<P>

<s docid="LA062290-0169" num="15" wdcount="16"> The U.S. government routinely channels humanitarian assistance through the Red Cross and other donor groups .</s>
</P>
<P>

<s docid="LA062290-0169" num="16" wdcount="22"> Boucher said the Iranian message to the United States presumably was delivered through a third party but added that he was uncertain.</s>

<s docid="LA062290-0169" num="17" wdcount="15"> Messages between the two countries normally are handled by the Swiss Embassy in Tehran .</s>
</P>
<P>

<s docid="LA062290-0169" num="18" wdcount="16"> Iranian authorities have told United Nations officials that about 35,000 people died in the earthquake .</s>
</P>
<P>

<s docid="LA062290-0169" num="19" wdcount="21"> Iran reportedly said it would accept aid from all countries -- including Iraq -- but excluded Israel and South Africa .</s>
</P>
<P>

<s docid="LA062290-0169" num="20" wdcount="30"> Rescuers in Iran today freed thousands of people from buildings flattened by the earthquake in northern Iran, which struck early Thursday and had a magnitude between 7.3 and 7.7 .</s>
</P>
<P>

<s docid="LA062290-0169" num="21" wdcount="24"> The Islamic Republic News Agency said 6,000 people were pulled from rubble and airlifted from the stricken Gilan and Zanjan provinces to hospitals .</s>
</P>
<P>

<s docid="LA062290-0169" num="22" wdcount="25"> Iranian television showed scenes of devastation, including the remains of an entire row of hillside village houses that collapsed and slid down the hill .</s>
</P>
<P>

<s docid="LA062290-0169" num="23" wdcount="11"> Rescuers scooped up rubble and used police dogs to find victims.</s>

<s docid="LA062290-0169" num="24" wdcount="22"> They gently fed water to one man who was trapped in a mass of stones and earth, only his head protruding .</s>
</P>
<P>

<s docid="LA062290-0169" num="25" wdcount="18"> The Iranian Red Crescent asked for help in providing shelter for 400,000 people left homeless by the earthquake.</s>

<s docid="LA062290-0169" num="26" wdcount="9"> Offers of help came from across the globe .</s>
</P>
<P>

<s docid="LA062290-0169" num="27" wdcount="31"> The death toll was higher than a quake that killed 25,000 people in nearby Soviet Armenia in December, 1988, and a quake in Iran in 1978 that also killed 25,000 .</s>
</P>
<P>

<s docid="LA062290-0169" num="28" wdcount="17"> In scenes shown on television, masked rescuers in white aprons pulled dust-covered bodies from under concrete slabs.</s>

<s docid="LA062290-0169" num="29" wdcount="11"> Corpses were laid on blocks of ice in open trucks .</s>
</P>
<P>

<s docid="LA062290-0169" num="30" wdcount="25"> The state-run television interviewed one middle-aged man from Roodbar, a mountainside village in Gilan province, who said he was sleeping when the temblor struck .</s>
</P>
<P>

<s docid="LA062290-0169" num="31" wdcount="6"> "It was so strong," he said.</s>

<s docid="LA062290-0169" num="32" wdcount="15"> "I was thrown several meters, I ended up by the olive trees," outside his home.</s>

<s docid="LA062290-0169" num="33" wdcount="7"> "Then a big boulder hit the house.</s>

<s docid="LA062290-0169" num="34" wdcount="3"> The house collapsed.</s>

<s docid="LA062290-0169" num="35" wdcount="8"> I lost all four of my children" .</s>
</P>
<P>

<s docid="LA062290-0169" num="36" wdcount="6"> * Photos of Iran's devastating earthquake.</s>

<s docid="LA062290-0169" num="37" wdcount="3"> See Back Page</s>
</P>
</TEXT>
<TYPE>
<P>

<s docid="LA062290-0169" num="38" wdcount="1"> Wire</s>
</P>
</TYPE>
</DOC>
