<DOC>
<DOCNO>

<s docid="LA062390-0068" num="1" wdcount="1"> LA062390-0068</s>
</DOCNO>
<DOCID>

<s docid="LA062390-0068" num="2" wdcount="1"> 237663</s>
</DOCID>
<DATE>
<P>

<s docid="LA062390-0068" num="3" wdcount="6"> June 23, 1990, Saturday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA062390-0068" num="4" wdcount="8"> Part A; Page 19; Column 1; Foreign Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA062390-0068" num="5" wdcount="2"> 867 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA062390-0068" num="6" wdcount="8"> U.S. PUTS RANCOR ASIDE, AIDS QUAKE RELIEF EFFORT;</s>
</P>
<P>

<s docid="LA062390-0068" num="7" wdcount="17"> ASSISTANCE: WASHINGTON GIVES $300,000 WORTH OF SUPPLIES TO THE AMERICAN RED CROSS FOR SHIPMENT TO IRAN .</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA062390-0068" num="8" wdcount="7"> By SAM FULWOOD III, TIMES STAFF WRITER</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA062390-0068" num="9" wdcount="1"> WASHINGTON</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA062390-0068" num="10" wdcount="29"> Setting aside years of animosity, the U.S. government joined with private humanitarian groups Friday to funnel medicine, tents, clothing, food and other relief materials to help earthquake-stricken Iran .</s>
</P>
<P>

<s docid="LA062390-0068" num="11" wdcount="41"> State Department officials said the government gave $300,000 worth of supplies to the American Red Cross for shipment to Iran -- including 1,000 hard hats, 1,000 pairs of leather gloves, 10,000 face masks, 2,940 wool blankets and about 500 tents .</s>
</P>
<P>

<s docid="LA062390-0068" num="12" wdcount="31"> The U.S. military, which often is used to ferry relief supplies to countries in need, stood ready to offer transport planes and logistics support for any U.S. aid requested by Iran.</s>

<s docid="LA062390-0068" num="13" wdcount="24"> However, a Pentagon official said it is unlikely that the State Department and the White House would authorize a military airlift of supplies .</s>
</P>
<P>

<s docid="LA062390-0068" num="14" wdcount="26"> "It's pretty clear that the Iranians don't want us, and there are so many alternatives, such as private charters, it really isn't necessary," the officials said.</s>

<s docid="LA062390-0068" num="15" wdcount="17"> "In a case like this, we would really be more of an irritant than a help" .</s>
</P>
<P>

<s docid="LA062390-0068" num="16" wdcount="22"> The quake, which rocked the northern region of Iran early Thursday, left nearly 29,000 dead, by official count, and about 400,000 homeless.</s>

<s docid="LA062390-0068" num="17" wdcount="13"> The death toll is expected to rise, however, as rescuers continue work .</s>
</P>
<P>

<s docid="LA062390-0068" num="18" wdcount="24"> Late Thursday, the Iranian Red Crescent appealed for help from the Red Cross and Red Crescent Society, a Geneva-based umbrella for international humanitarian organizations.</s>

<s docid="LA062390-0068" num="19" wdcount="16"> Iranian President Hashemi Rafsanjani, who toured the stricken region Friday, also appealed for international aid .</s>
</P>
<P>

<s docid="LA062390-0068" num="20" wdcount="42"> Pat Davis, a spokesman for the American Red Cross in Washington, said Friday that although the Red Crescent is highly organized and well equipped, the large number of dead and suffering people has forced the Iranian agency to solicit international assistance .</s>
</P>
<P>

<s docid="LA062390-0068" num="21" wdcount="44"> The American Red Cross responded by mobilizing its local offices to solicit money, informing its toll-free telephone operators to request earmarked donations for the earthquake victims and sending $50,000 in cash to the Red Crescent Society to be used to help needy Iranians .</s>
</P>
<P>

<s docid="LA062390-0068" num="22" wdcount="20"> Some Jewish relief organizations found themselves in an uncomfortable position because of Iran's hostility toward the United States and Israel.</s>

<s docid="LA062390-0068" num="23" wdcount="22"> Confronted with reports that Iran would not welcome assistance from Israel, the groups were uncertain whether they should offer any assistance .</s>
</P>
<P>

<s docid="LA062390-0068" num="24" wdcount="33"> Andy Griffel, executive director of American Jewish World Service, said directors of the assistance organization participated in a conference call Friday morning to debate whether to collect money for the Iranian victims .</s>
</P>
<P>

<s docid="LA062390-0068" num="25" wdcount="24"> After a spirited discussion, the group decided to help but to monitor the situation closely and to be prepared to change their decision .</s>
</P>
<P>

<s docid="LA062390-0068" num="26" wdcount="14"> "We're a humanitarian organization . . . without regard to political considerations," Griffel said.</s>

<s docid="LA062390-0068" num="27" wdcount="14"> "But if they are going politicize it, we will definitely reconsider our participation" .</s>
</P>
<P>

<s docid="LA062390-0068" num="28" wdcount="25"> Amir Zamani, a spokesman for the Iranian mission at the United Nations, welcomed the "many offers from many organizations" that his office has received .</s>
</P>
<P>

<s docid="LA062390-0068" num="29" wdcount="12"> "Iran needs assistance, and such organizations are welcome to send it" .</s>
</P>
<P>

<s docid="LA062390-0068" num="30" wdcount="25"> Acknowledging Iran's strained relations with many nations, Zamani said his country is attempting to ease the antagonism to deal with the disaster in the country.</s>

<s docid="LA062390-0068" num="31" wdcount="17"> As an example, he said "no formalities" will be required for relief planes flying into Iran .</s>
</P>
<P>

<s docid="LA062390-0068" num="32" wdcount="32"> He added, however, that aid shipments will be coordinated by the government and routed through Tehran because there are no other airports in the country that can accommodate large transport planes .</s>
</P>
<P>

<s docid="LA062390-0068" num="33" wdcount="13"> Meanwhile, other U.S. groups were rushing to supply Iran with emergency goods .</s>
</P>
<P>

<s docid="LA062390-0068" num="34" wdcount="36"> Dwain Schenck, a relief worker for AmeriCares Foundation, said the Connecticut-based relief group expects to send 80,000 pounds of medical supplies, two doctors, a nurse and about half a dozen relief workers to Iran today .</s>
</P>
<P>

<s docid="LA062390-0068" num="35" wdcount="13"> "We hope to be there about four days or so," he said .</s>
</P>
<P>

<s docid="LA062390-0068" num="36" wdcount="11"> Times staff writer Charles J. Hartley contributed to this report .</s>
</P>
<P>

<s docid="LA062390-0068" num="37" wdcount="4"> WHERE TO SEND AID</s>
</P>
<P>

<s docid="LA062390-0068" num="38" wdcount="12"> Here are some of the agencies accepting donations for Iranian earthquake victims:</s>
</P>
<P>

<s docid="LA062390-0068" num="39" wdcount="5"> Adventist Development and Relief Agency</s>
</P>
<P>

<s docid="LA062390-0068" num="40" wdcount="4"> 12501 Old Columbia Pike</s>
</P>
<P>

<s docid="LA062390-0068" num="41" wdcount="4"> Silver Spring, Md. 20904</s>
</P>
<P>

<s docid="LA062390-0068" num="42" wdcount="2"> (301) 680-6380</s>
</P>
<P>

<s docid="LA062390-0068" num="43" wdcount="4"> American Jewish World Service</s>
</P>
<P>

<s docid="LA062390-0068" num="44" wdcount="7"> 1290 Avenue of the Americas, 11th Floor</s>
</P>
<P>

<s docid="LA062390-0068" num="45" wdcount="4"> New York, N.Y. 10104</s>
</P>
<P>

<s docid="LA062390-0068" num="46" wdcount="3"> American Red Cross</s>
</P>
<P>

<s docid="LA062390-0068" num="47" wdcount="3"> Iran Earthquake Disaster</s>
</P>
<P>

<s docid="LA062390-0068" num="48" wdcount="3"> P.O. Box 37243</s>
</P>
<P>

<s docid="LA062390-0068" num="49" wdcount="3"> Washington, D.C. 20013</s>
</P>
<P>

<s docid="LA062390-0068" num="50" wdcount="2"> (800) 842-2200</s>
</P>
<P>

<s docid="LA062390-0068" num="51" wdcount="4"> American Red Cross (local)</s>
</P>
<P>

<s docid="LA062390-0068" num="52" wdcount="3"> 2700 Wilshire Blvd.,</s>
</P>
<P>

<s docid="LA062390-0068" num="53" wdcount="4"> Los Angeles, Calif. 90057</s>
</P>
<P>

<s docid="LA062390-0068" num="54" wdcount="1"> AmeriCares</s>
</P>
<P>

<s docid="LA062390-0068" num="55" wdcount="4"> 161 Cherry St .</s>
</P>
<P>

<s docid="LA062390-0068" num="56" wdcount="4"> New Canaan, Conn. 06840</s>
</P>
<P>

<s docid="LA062390-0068" num="57" wdcount="2"> (800) 486-HELP</s>
</P>
<P>

<s docid="LA062390-0068" num="58" wdcount="3"> Baptist World Alliance</s>
</P>
<P>

<s docid="LA062390-0068" num="59" wdcount="3"> Iran Earthquake Fund</s>
</P>
<P>

<s docid="LA062390-0068" num="60" wdcount="4"> 6733 Curran St .</s>
</P>
<P>

<s docid="LA062390-0068" num="61" wdcount="3"> McLean, Va. 22101</s>
</P>
<P>

<s docid="LA062390-0068" num="62" wdcount="3"> Direct Relief International</s>
</P>
<P>

<s docid="LA062390-0068" num="63" wdcount="6"> 2801-B De La Vina St .</s>
</P>
<P>

<s docid="LA062390-0068" num="64" wdcount="4"> Santa Barbara, Calif. 93105</s>
</P>
<P>

<s docid="LA062390-0068" num="65" wdcount="2"> (805) 687-3694</s>
</P>
<P>

<s docid="LA062390-0068" num="66" wdcount="3"> Bank Melli Iran</s>
</P>
<P>

<s docid="LA062390-0068" num="67" wdcount="4"> Iran Quake Relief Assistance</s>
</P>
<P>

<s docid="LA062390-0068" num="68" wdcount="3"> Account No. 5000</s>
</P>
<P>

<s docid="LA062390-0068" num="69" wdcount="4"> 628 Madison Ave .</s>
</P>
<P>

<s docid="LA062390-0068" num="70" wdcount="4"> New York, N.Y. 10022</s>
</P>
<P>

<s docid="LA062390-0068" num="71" wdcount="4"> Bank Melli Iran (local)</s>
</P>
<P>

<s docid="LA062390-0068" num="72" wdcount="4"> 818 Wilshire Blvd .</s>
</P>
<P>

<s docid="LA062390-0068" num="73" wdcount="4"> Los Angeles, Calif. 90017)</s>
</P>
<P>

<s docid="LA062390-0068" num="74" wdcount="3"> Lutheran World Relief</s>
</P>
<P>

<s docid="LA062390-0068" num="75" wdcount="4"> 390 Park Ave. S</s>
</P>
<P>

<s docid="LA062390-0068" num="76" wdcount="4"> New York, N.Y. 10016</s>
</P>
<P>

<s docid="LA062390-0068" num="77" wdcount="4"> U.S. Committee for UNICEF</s>
</P>
<P>

<s docid="LA062390-0068" num="78" wdcount="5"> 333 E. 38th St .</s>
</P>
<P>

<s docid="LA062390-0068" num="79" wdcount="4"> New York, N.Y. 10016</s>
</P>
<P>

<s docid="LA062390-0068" num="80" wdcount="2"> (212) 686-5522</s>
</P>
<P>

<s docid="LA062390-0068" num="81" wdcount="2"> World Concern</s>
</P>
<P>

<s docid="LA062390-0068" num="82" wdcount="3"> P.O. Box 33000</s>
</P>
<P>

<s docid="LA062390-0068" num="83" wdcount="3"> Seattle, Wash. 98133</s>
</P>
<P>

<s docid="LA062390-0068" num="84" wdcount="2"> World Vision</s>
</P>
<P>

<s docid="LA062390-0068" num="85" wdcount="4"> 919 W. Huntington Drive</s>
</P>
<P>

<s docid="LA062390-0068" num="86" wdcount="3"> Monrovia, Calif. 91016</s>
</P>
<P>

<s docid="LA062390-0068" num="87" wdcount="2"> (818) 357-7979</s>
</P>
</TEXT>
<TYPE>
<P>

<s docid="LA062390-0068" num="88" wdcount="1"> List</s>
</P>
</TYPE>
<SUBJECT>
<P>

<s docid="LA062390-0068" num="89" wdcount="24"> AMERICAN RED CROSS; RELIEF ORGANIZATIONS; UNITED STATES -- FOREIGN RELATIONS -- IRAN; CONTRIBUTIONS; EARTHQUAKES -- IRAN; DISASTERS -- IRAN; IRAN -- RELIEF; DISASTER RELIEF</s>
</P>
</SUBJECT>
</DOC>
