<DOC>
<DOCNO>

<s docid="LA062290-0134" num="1" wdcount="1"> LA062290-0134</s>
</DOCNO>
<DOCID>

<s docid="LA062290-0134" num="2" wdcount="1"> 237272</s>
</DOCID>
<DATE>
<P>

<s docid="LA062290-0134" num="3" wdcount="6"> June 22, 1990, Friday, Southland Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA062290-0134" num="4" wdcount="8"> Part A; Page 14; Column 1; Foreign Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA062290-0134" num="5" wdcount="2"> 419 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA062290-0134" num="6" wdcount="9"> IRANIAN MEDIA LOW KEY IN REPORTING ON KILLER QUAKE</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA062290-0134" num="7" wdcount="3"> From Associated Press</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA062290-0134" num="8" wdcount="2"> NICOSIA, Cyprus</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA062290-0134" num="9" wdcount="23"> Iranian news media reacted with little emotion Thursday to a killer earthquake that left an estimated 25,000 people dead in northern Iran .</s>
</P>
<P>

<s docid="LA062290-0134" num="10" wdcount="10"> The country has endured several massive tragedies in recent years.</s>

<s docid="LA062290-0134" num="11" wdcount="19"> An estimated 1 million Iranians were killed or wounded in the eight-year war with Iraq that ended in 1988.</s>

<s docid="LA062290-0134" num="12" wdcount="21"> And the Islamic revolution that in 1979 toppled the late Shah Mohammed Reza Pahlavi cost hundreds of thousands of lives .</s>
</P>
<P>

<s docid="LA062290-0134" num="13" wdcount="9"> And devastating quakes are not new to the country.</s>

<s docid="LA062290-0134" num="14" wdcount="11"> About 25,000 people died in eastern Iran in a 1978 earthquake.</s>

<s docid="LA062290-0134" num="15" wdcount="15"> Roughly the same number died in a December, 1988, quake in nearby Soviet Armenia .</s>
</P>
<P>

<s docid="LA062290-0134" num="16" wdcount="12"> The Iranian media, monitored from Nicosia, was quick to report Thursday's earthquake.</s>

<s docid="LA062290-0134" num="17" wdcount="21"> Within half an hour, the Islamic Republic News Agency reported that the tremor had been felt in Tehran, the capital .</s>
</P>
<P>

<s docid="LA062290-0134" num="18" wdcount="31"> But subsequent reports, some a few minutes apart, said the damage must have been principally to crops, with brief mentions that many casualties were feared in Zanjan and Gilan provinces .</s>
</P>
<P>

<s docid="LA062290-0134" num="19" wdcount="28"> The only detail reported for hours was that, when the quake hit, Tehran residents were either asleep or watching a World Cup soccer match between Brazil and Scotland.</s>

<s docid="LA062290-0134" num="20" wdcount="11"> The report said that many people fled into the streets .</s>
</P>
<P>

<s docid="LA062290-0134" num="21" wdcount="14"> In addition, the news agency's earliest reports dramatically underestimated the magnitude of the disaster.</s>

<s docid="LA062290-0134" num="22" wdcount="20"> While IRNA reported 10,000 dead late Thursday, the Iranian ambassador to the United Nations said 25,000 people had died .</s>
</P>
<P>

<s docid="LA062290-0134" num="23" wdcount="32"> Official radio was off the air when the earthquake struck, and although it came back on the air to report important news during the Iran-Iraq War, there was no such move Thursday.</s>

<s docid="LA062290-0134" num="24" wdcount="15"> Iranian radio first reported the earthquake on the main newscast 6 1/2 hours later .</s>
</P>
<P>

<s docid="LA062290-0134" num="25" wdcount="18"> The radio, like the agency, also kept listeners informed about the areas hit and the number of casualties.</s>

<s docid="LA062290-0134" num="26" wdcount="11"> But again, the reporting lacked color and description for hours .</s>
</P>
<P>

<s docid="LA062290-0134" num="27" wdcount="20"> The television's first shots from the stricken north were screened 12 hours after the quake with no comment from reporters.</s>

<s docid="LA062290-0134" num="28" wdcount="33"> When the scenes were replayed during newscasts, the anchors appeared unshaken by chilling clips such as one showing a stuffed toy and a small shoe lying in a street carpeted with debris .</s>
</P>
<P>

<s docid="LA062290-0134" num="29" wdcount="13"> Iranian President Hashemi Rafsanjani declared a three-day period of mourning for quake victims.</s>

<s docid="LA062290-0134" num="30" wdcount="29"> But the television showed cartoons and an educational program for children and ended its programming with live transmission of a World Cup soccer match between Egypt and England .</s>
</P>
</TEXT>
<TYPE>
<P>

<s docid="LA062290-0134" num="31" wdcount="1"> Wire</s>
</P>
</TYPE>
</DOC>
