<DOC>
<DOCNO>

<s docid="AP900802-0159" num="1" wdcount="1"> AP900802-0159</s>
</DOCNO>
<FILEID>

<s docid="AP900802-0159" num="2" wdcount="2"> AP-NR-08-02-90 1857EDT</s>
</FILEID>
<FIRST>

<s docid="AP900802-0159" num="3" wdcount="5"> u i AM-ArabLeague 08-02 0593</s>
</FIRST>
<SECOND>

<s docid="AP900802-0159" num="4" wdcount="2"> AM-Arab League,0615</s>
</SECOND>
<HEAD>

<s docid="AP900802-0159" num="5" wdcount="10"> Arab League Fails at Emergency Meeting to Condemn Iraq's Invasion</s>
</HEAD>
<HEAD>

<s docid="AP900802-0159" num="6" wdcount="3"> With AM-Iraq-Kuwait, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP900802-0159" num="7" wdcount="3"> By DALIA BALIGH</s>
</BYLINE>
<BYLINE>

<s docid="AP900802-0159" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900802-0159" num="9" wdcount="3"> CAIRO, Egypt (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900802-0159" num="10" wdcount="34"> An emergency Arab League Council failed to publicly condemn Iraq's invasion of Kuwait on Thursday and adjourned its meeting for 24 hours as Arab leaders held urgent consultations on how to handle the crisis.</s>

<s docid="AP900802-0159" num="11" wdcount="18"> Kuwait's Cabinet affairs minister, Abdel-Rahman el-Awadi told reporters he asked the 21-nation Arab League to condemn the attack.</s>

<s docid="AP900802-0159" num="12" wdcount="10"> He accused Iraq of using the ``laws of the jungle''.</s>

<s docid="AP900802-0159" num="13" wdcount="30"> President Hosni Mubarak and Jordan's King Hussein met in Alexandria and telephoned Iraqi President Saddam Hussein, President Bush, Saudi King Fahd and Yemeni President Ali Abdallah Saleh on the crisis.</s>

<s docid="AP900802-0159" num="14" wdcount="5"> Hussein later left for home.</s>

<s docid="AP900802-0159" num="15" wdcount="29"> Sources close to the Arab League Council said its members agreed to convene an emergency Arab summit but decided to leave the when and where up to Arab leaders.</s>

<s docid="AP900802-0159" num="16" wdcount="7"> The sources spoke on condition of anonymity.</s>

<s docid="AP900802-0159" num="17" wdcount="25"> The Council meeting of foreign ministers was convened in Cairo at Kuwaiti request hours after Iraqi military forces took over the small Persian Gulf state.</s>

<s docid="AP900802-0159" num="18" wdcount="6"> Some member nations sent lower-level representatives.</s>

<s docid="AP900802-0159" num="19" wdcount="29"> Following its evening session, attended by Saadoon Hamadi, a member of the Iraqi Revolutionary Council, Foreign Minister Esmat Abdel-Meguid of Egypt told reporters the Council would meet again Friday.</s>

<s docid="AP900802-0159" num="20" wdcount="16"> Saddam promised Mubarak two weeks ago that he would not invade Kuwait in their oil dispute.</s>

<s docid="AP900802-0159" num="21" wdcount="25"> At Thursday's closed session, Hamadi reiterated Iraq's claim its forces entered Kuwait at the request of a Kuwaiti revolutionary group that had overthrown the government.</s>

<s docid="AP900802-0159" num="22" wdcount="28"> A conference source said several Arab foreign ministers replied that ``they considered this to be an Iraqi invasion which is against all United Nations and Arab League conventions''.</s>

<s docid="AP900802-0159" num="23" wdcount="39"> So far, only Lebanon's prime minister and foreign minister, Salim Hoss, has joined Kuwait in Cairo in publicly condemning the invasion _ the first time in modern history one Arab country invaded another to take control of the government.</s>

<s docid="AP900802-0159" num="24" wdcount="17"> Hoss told reporters, ``We do not see any justification for what happened, whatever the arguments and pretexts''.</s>

<s docid="AP900802-0159" num="25" wdcount="17"> The invasion was denounced by the United States and other Western nations and by the Soviet Union.</s>

<s docid="AP900802-0159" num="26" wdcount="16"> The Arab League Council met early Thursday and then adjourned to await the arrival of Hamdoon.</s>

<s docid="AP900802-0159" num="27" wdcount="11"> Iraq's ambassador to Egypt, Nabil Najm, sat in until Hamdoon arrived.</s>

<s docid="AP900802-0159" num="28" wdcount="45"> ``The United Nation's Security Council has condemned the invasion and the issue is now being discussed within the framework of the Arab League and we hope that it will issue a condemnation within the hour and that Arabs stand against this invasion,'' Kuwait's Awadi said.</s>

<s docid="AP900802-0159" num="29" wdcount="17"> ``Arab leaders must take the initiative and stop this bloodshed and return things to their normal situation.</s>

<s docid="AP900802-0159" num="30" wdcount="9"> We also call on Iraq to withdraw its troops''.</s>

<s docid="AP900802-0159" num="31" wdcount="12"> Hamadi told reporters upon arrival, ``I see this meeting as unnecessary ...</s>

<s docid="AP900802-0159" num="32" wdcount="7"> There is no government presently in Kuwait.</s>

<s docid="AP900802-0159" num="33" wdcount="14"> There is a group which started the revolution and which will reveal itself shortly''.</s>

<s docid="AP900802-0159" num="34" wdcount="10"> His comments were carried by the Middle East News Agency.</s>

<s docid="AP900802-0159" num="35" wdcount="28"> MENA said Kuwait invoked the 1950 Arab joint defense pact and asked the Arab League Council to dispatch a joint Arab force to ``defend Kuwait against the invasion''.</s>

<s docid="AP900802-0159" num="36" wdcount="37"> In the event of military aggression against any League member, the pact all members, to ``take, individually and collectively, all steps available, including the use of armed force, to repel the aggression and restore security and peace''.</s>

<s docid="AP900802-0159" num="37" wdcount="15"> The ministers were in Cairo to attend the Organization of Islamic Conference's foreign ministers meeting.</s>

<s docid="AP900802-0159" num="38" wdcount="11"> All Arab League members also belong to the Islamic conference .</s>
</TEXT>
</DOC>
