<DOC>
<DOCNO>

<s docid="AP900804-0067" num="1" wdcount="1"> AP900804-0067</s>
</DOCNO>
<FILEID>

<s docid="AP900804-0067" num="2" wdcount="2"> AP-NR-08-04-90 1116EDT</s>
</FILEID>
<FIRST>

<s docid="AP900804-0067" num="3" wdcount="5"> r i AM-Iraq-Saudi 08-04 0540</s>
</FIRST>
<SECOND>

<s docid="AP900804-0067" num="4" wdcount="1"> AM-Iraq-Saudi,0555</s>
</SECOND>
<HEAD>

<s docid="AP900804-0067" num="5" wdcount="6"> Saudis Take No Steps Against Iraq</s>
</HEAD>
<HEAD>

<s docid="AP900804-0067" num="6" wdcount="3"> With AM-Iraq-Kuwait, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP900804-0067" num="7" wdcount="3"> By NICK LUDINGTON</s>
</BYLINE>
<BYLINE>

<s docid="AP900804-0067" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900804-0067" num="9" wdcount="3"> NICOSIA, Cyprus (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900804-0067" num="10" wdcount="22"> Saudi Arabia has been subdued in its reaction to Iraq's invasion of Kuwait, which places Iraqi forces near the oil-rich kingdom's border.</s>

<s docid="AP900804-0067" num="11" wdcount="35"> Oil executives said Saudi Arabia has not and will not take the most potent action possible against Iraq _ closing the pipeline that carries Iraqi oil for export across Saudi Arabia to the Red Sea.</s>

<s docid="AP900804-0067" num="12" wdcount="41"> The executives said the Saudis believe this would give Iraq's belligerent president, Saddam Hussein, an excuse to attack and occupy Saudi oil fields 150 miles south of Kuwait, giving Iraq control of more oil than any other country in the world.</s>

<s docid="AP900804-0067" num="13" wdcount="27"> The only direct Saudi statement since the invasion was made by an anonymous government spokesman through the official Saudi Press Agency the day after the Iraqi move.</s>

<s docid="AP900804-0067" num="14" wdcount="37"> The statement said Saudi Arabia was following the Kuwait situation ``with extreme concern'' and that King Fahd would be seeking to calm the situation and to find a solution ``in a manner ensuring the interests of all''.</s>

<s docid="AP900804-0067" num="15" wdcount="7"> The statement did not condemn the invasion.</s>

<s docid="AP900804-0067" num="16" wdcount="35"> The only tangible help Saudi Arabia gave the Kuwaiti government in the wake of the invasion was to shelter members of the ruling family, including the emir, Sheik Jaber al-Ahmed al-Sabah, and the crown prince.</s>

<s docid="AP900804-0067" num="17" wdcount="13"> Both nations are tightly run by royal families and have been close allies.</s>

<s docid="AP900804-0067" num="18" wdcount="25"> The Saudis also allowed the Kuwaiti royal family to briefly operate a radio, reportedly from a mobile van, in the area around the Saudi-Kuwait border.</s>

<s docid="AP900804-0067" num="19" wdcount="33"> But Friday the radio went off the air after a desperate call: ``The people of Kuwait appeal to you oh brethren, oh Arabs, oh beloved brothers, oh Moslems, rush, rush to their help''.</s>

<s docid="AP900804-0067" num="20" wdcount="39"> It was not known if the radio had been discovered by the Iraqis or shut down by the Saudis to avoid provoking Saddam at a time when fears were being expressed that he might invade Saudi Arabia as well.</s>

<s docid="AP900804-0067" num="21" wdcount="14"> Saudi Arabia borders Kuwait and Iraq's invasion forces were reportedly near the Saudi border.</s>

<s docid="AP900804-0067" num="22" wdcount="33"> The Saudis did condemned the invasion as part of a joint statement issued by the Gulf Cooperation Council, in which it is allied with Kuwait, the United Arab Emirates, Qatar, Oman and Bahrain.</s>

<s docid="AP900804-0067" num="23" wdcount="26"> The six states issued a statement saying, ``We strongly condemn and are very sorry for this attack that one Arab state took against another Arab state.</s>

<s docid="AP900804-0067" num="24" wdcount="9"> ... We do not recognize anything resulting from it''.</s>

<s docid="AP900804-0067" num="25" wdcount="21"> Iraq's 1-million-member armed forces is clearly too much for the joint 3,000-member Gulf Cooperation Council force or Saudi Arabia's 65,700-member army.</s>

<s docid="AP900804-0067" num="26" wdcount="27"> Saudi Arabia was also one of the 14 members of the 21-member Arab League that condemned the invasion in the same terms as the Gulf Cooperation Council.</s>

<s docid="AP900804-0067" num="27" wdcount="22"> The Arab League, with one-third of its members voting against the resolution or abstaining, was clearly unable to take any direct action.</s>

<s docid="AP900804-0067" num="28" wdcount="25"> Turkey has also refused to take action and has not commented about President Bush's suggestion that it cut off Iraq's oil pipeline to the Mediterranean.</s>

<s docid="AP900804-0067" num="29" wdcount="28"> Two parallel pipelines pump Iraqi crude oil to a terminal at Yumurtalik at the eastern corner of Turkey's Mediterranean coast and constitute Iraq's major oil export outlet .</s>
</TEXT>
</DOC>
