<DOC>
<DOCNO>

<s docid="AP900802-0092" num="1" wdcount="1"> AP900802-0092</s>
</DOCNO>
<FILEID>

<s docid="AP900802-0092" num="2" wdcount="2"> AP-NR-08-02-90 1102EDT</s>
</FILEID>
<FIRST>

<s docid="AP900802-0092" num="3" wdcount="7"> r i PM-UN-Iraq-Kuwait 3rdLd-Writethru a0584 08-02 0618</s>
</FIRST>
<SECOND>

<s docid="AP900802-0092" num="4" wdcount="4"> PM-UN-Iraq-Kuwait, 3rd Ld-Writethru, a0584,0636</s>
</SECOND>
<HEAD>

<s docid="AP900802-0092" num="5" wdcount="9"> U.N. Security Council Condemns Iraqi Invasion, Seeks Pullout, Talks</s>
</HEAD>
<NOTE>

<s docid="AP900802-0092" num="6" wdcount="11"> Eds: Leads with 5 grafs to UPDATE with British envoy's comment.</s>

<s docid="AP900802-0092" num="7" wdcount="6"> Pickup 5th graf pvs, ``The United..''</s>
</NOTE>
<HEAD>

<s docid="AP900802-0092" num="8" wdcount="3"> With PM-Iraq-Kuwait, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP900802-0092" num="9" wdcount="3"> By KATHY CHENAULT</s>
</BYLINE>
<BYLINE>

<s docid="AP900802-0092" num="10" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900802-0092" num="11" wdcount="3"> UNITED NATIONS (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900802-0092" num="12" wdcount="2"> The U.N.</s>

<s docid="AP900802-0092" num="13" wdcount="24"> Security Council today swiftly condemned Iraq's invasion of Kuwait, demanding an unconditional withdrawal of Iraqi troops and calling for immediate negotiations between the countries.</s>

<s docid="AP900802-0092" num="14" wdcount="24"> The Iraqi envoy said his country's troops would withdraw ``as soon as the situation is stable,'' perhaps within ``a few days or some weeks''.</s>

<s docid="AP900802-0092" num="15" wdcount="23"> The Security Council resolution was adopted 14-0 in an emergency session requested by the United States and Kuwait hours after today's pre-dawn invasion.</s>

<s docid="AP900802-0092" num="16" wdcount="9"> Neither Kuwait nor Iraq is on the 15-member council.</s>

<s docid="AP900802-0092" num="17" wdcount="18"> The representative of Yemen said he did not vote because he had not received instructions from his government.</s>

<s docid="AP900802-0092" num="18" wdcount="15"> Britain's U.N. envoy, Crispin Tickell, condemned the invasion as an ``ugly moment in world affairs''.</s>

<s docid="AP900802-0092" num="19" wdcount="6"> Kuwait is a former British colony.</s>

<s docid="AP900802-0092" num="20" wdcount="28"> ``The United States has made it clear that it will stand shoulder to shoulder with Kuwait in this time of crisis,'' U.S. Ambassador Thomas Pickering told the council.</s>

<s docid="AP900802-0092" num="21" wdcount="11"> ``It is our understanding that the present aggression was completely unprovoked''.</s>

<s docid="AP900802-0092" num="22" wdcount="22"> Baghdad radio claimed Iraq had come to the aid of ``revolutionary youth in Kuwait'' whom it said had toppled the Kuwaiti government.</s>

<s docid="AP900802-0092" num="23" wdcount="23"> Kuwait's ambassador to the United Nations, Mohammad Abulhasan, denied the invasion was in response to a call from help from a new government.</s>

<s docid="AP900802-0092" num="24" wdcount="15"> ``The pretext to invade an independent, sovereign state is a false, flimsy pretext,'' he said.</s>

<s docid="AP900802-0092" num="25" wdcount="26"> ``This kind of pretext, if it's not going to be deterred in a decisive manner and by this august assembly, all international relations will be threatened.</s>

<s docid="AP900802-0092" num="26" wdcount="9"> No country at all will be safe after this''.</s>

<s docid="AP900802-0092" num="27" wdcount="29"> A statement read by Sabah Talat Kadrat, Iraq's deputy permanant representative said Iraq's forces would withdraw when what it referred to as the ``free Kuwaiti interim government'' requested it.</s>

<s docid="AP900802-0092" num="28" wdcount="13"> The Iraqi statement was also reported by the Iraqi News Agency in Baghdad.</s>

<s docid="AP900802-0092" num="29" wdcount="16"> The Security Council resolution said the council supports all efforts for negotiations between Iraq and Kuwait.</s>

<s docid="AP900802-0092" num="30" wdcount="17"> It specifically endorsed mediation efforts by the Arab League, which met in emergency session in Cairo today.</s>

<s docid="AP900802-0092" num="31" wdcount="15"> The Iraqi invasion posed ``a breach of international peace and security,'' the Security Council said.</s>

<s docid="AP900802-0092" num="32" wdcount="16"> Kadrat said the events were related to an internal matter that was not the council's concern.</s>

<s docid="AP900802-0092" num="33" wdcount="24"> ``The Iraqi government firmly believes and states that Iraq is pursuing no goal or objective and wishes only cordial relations with Kuwait,'' said Kadrat.</s>

<s docid="AP900802-0092" num="34" wdcount="24"> ``Furthermore, it is the Kuwaitis themselves who will determine their own future and Iraqi forces will withdraw as soon as order has been restored''.</s>

<s docid="AP900802-0092" num="35" wdcount="15"> Members of the 15-member Security Council began gathering at the United Nations shortly after midnight.</s>

<s docid="AP900802-0092" num="36" wdcount="14"> Diplomats held more than three hours of private consultations before convening the formal meeting.</s>

<s docid="AP900802-0092" num="37" wdcount="22"> Kuwaiti spokesman Nasser Al-Sabeeh said before the formal meeting that Kuwait wants negotiations with Iraq to be mediated by the Arab League.</s>

<s docid="AP900802-0092" num="38" wdcount="12"> ``But if it's necessary, then we would seek U.N. mediation,'' he said.</s>

<s docid="AP900802-0092" num="39" wdcount="27"> Two weeks ago, President Saddam Hussein of Iraq threatened military action with Kuwait over its violation of OPEC oil production ceilings and a disputed border oil field.</s>

<s docid="AP900802-0092" num="40" wdcount="25"> Saddam also has accused some Persian Gulf nations of conspiring with the United States and Israel to weaken Iraq's economy and undermine its military buildup.</s>

<s docid="AP900802-0092" num="41" wdcount="18"> Today's resolution was sponsored by Canada, Colombia, Ivory Coast, Ethiopia, Finland, France, the United States, Britain and Malaysia.</s>

<s docid="AP900802-0092" num="42" wdcount="32"> The 15 members of the Security Council are China, Yemen, Romania, the Soviet Union, Cuba, Canada, Colombia, Ivory Coast, Ethiopia, Finland, France, the United States, the United Kingdom, Malaysia and Zaire .</s>
</TEXT>
</DOC>
