<DOC>
<DOCNO>

<s docid="AP900806-0095" num="1" wdcount="1"> AP900806-0095</s>
</DOCNO>
<FILEID>

<s docid="AP900806-0095" num="2" wdcount="2"> AP-NR-08-06-90 1619EDT</s>
</FILEID>
<FIRST>

<s docid="AP900806-0095" num="3" wdcount="7"> u i PM-UN-Iraq 4thLd-Writethru a0632 08-06 0479</s>
</FIRST>
<SECOND>

<s docid="AP900806-0095" num="4" wdcount="4"> PM-UN-Iraq, 4th Ld-Writethru, a0632,0489</s>
</SECOND>
<HEAD>

<s docid="AP900806-0095" num="5" wdcount="7"> U.N. Security Council Approves Sanctions Against Iraq</s>
</HEAD>
<NOTE>

<s docid="AP900806-0095" num="6" wdcount="12"> Eds: INSERTS 2 grafs after 3rd pvs to UPDATE with Bush reaction.</s>

<s docid="AP900806-0095" num="7" wdcount="17"> SUBS 6th pvs, `The sanctions'... with one graf to ADD that sanctions apply to all U.N. nations.</s>

<s docid="AP900806-0095" num="8" wdcount="5"> Pickup 7th pvs, `The vote...'</s>
</NOTE>
<BYLINE>

<s docid="AP900806-0095" num="9" wdcount="3"> By VICTORIA GRAHAM</s>
</BYLINE>
<BYLINE>

<s docid="AP900806-0095" num="10" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900806-0095" num="11" wdcount="3"> UNITED NATIONS (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900806-0095" num="12" wdcount="2"> The U.N.</s>

<s docid="AP900806-0095" num="13" wdcount="24"> Security Council today overwhelmingly approved sweeping trade and military sanctions against Iraq, including a ban on oil purchases, to punish Baghdad for invading Kuwait.</s>

<s docid="AP900806-0095" num="14" wdcount="25"> The vote was 13-0, with two abstentions by Cuba and Yemen on the 15-member council, which adopted the sanctions resolution proposed by the United States.</s>

<s docid="AP900806-0095" num="15" wdcount="18"> It said Iraq had launched an armed attack against Kuwait and usurped the authority of Kuwait's legitimate government.</s>

<s docid="AP900806-0095" num="16" wdcount="42"> The sanctions were intended to force Iraq to withdraw its troops from Kuwait and the resolution bans ``the import into their territories of all commodities and products originating in Iraq or Kuwait and exported there from after the date of this resolution''.</s>

<s docid="AP900806-0095" num="17" wdcount="20"> President Bush praised the decision and called for ``full and total implementation of these sanctions, ruling out nothing at all''.</s>

<s docid="AP900806-0095" num="18" wdcount="20"> He told reporters at the White House: ``The will of nations around the world will be to enforce these sanctions''.</s>

<s docid="AP900806-0095" num="19" wdcount="20"> It was the third time in its 45-year existence that the world body had voted sanctions against a member state.</s>

<s docid="AP900806-0095" num="20" wdcount="20"> The last time was 1967 when the Security Council voted similar, comprehensive sanctions against the white minority government of Rhodesia.</s>

<s docid="AP900806-0095" num="21" wdcount="10"> An arms embargo against South Africa still is in effect.</s>

<s docid="AP900806-0095" num="22" wdcount="19"> The sanctions are legally binding for all member nations, although past council resolutions have often been ignored or flouted.</s>

<s docid="AP900806-0095" num="23" wdcount="23"> The United Nations has no enforcement mechanism but later could call on members to take military action against Iraq or impose a blockade.</s>

<s docid="AP900806-0095" num="24" wdcount="22"> The vote followed similar sanctions imposed on Iraq by much of the West, including the United States, Japan and the European Community.</s>

<s docid="AP900806-0095" num="25" wdcount="13"> The Soviet Union and China said they would halt arms shipments to Iraq.</s>

<s docid="AP900806-0095" num="26" wdcount="29"> In a statement carried by the Iraqi News Agency on Sunday, the Iraqi-installed military government of Kuwait warned other nations not to take ``punishing measures'' against it or Iraq.</s>

<s docid="AP900806-0095" num="27" wdcount="15"> The provisional government said countries ``have to remember they have interests and citizens in Kuwait''.</s>

<s docid="AP900806-0095" num="28" wdcount="22"> The U.N. role in the Iraq-Kuwait crisis assumed increasing importance after divided Arab nations canceled a weekend emergency summit on the invasion.</s>

<s docid="AP900806-0095" num="29" wdcount="29"> In an emergency session just hours after Thursday's invasion, the Security Council condemned Iraq's invasion, demanded immediate and unconditional troop withdrawal, and called for negotiations between Iraq and Kuwait.</s>

<s docid="AP900806-0095" num="30" wdcount="11"> The council threatened to impose sanctions if Iraq did not comply.</s>

<s docid="AP900806-0095" num="31" wdcount="21"> The council includes the five permanent members with veto power _ the United States, Britain, China, France and the Soviet Union.</s>

<s docid="AP900806-0095" num="32" wdcount="18"> The 10 non-permanent members are: Canada, Colombia, Cuba, Ethiopia, Finland, Ivory Coast, Malaysia, Romania, Yemen and Zaire .</s>
</TEXT>
</DOC>
