<DOC>
<DOCNO>

<s docid="AP900731-0113" num="1" wdcount="1"> AP900731-0113</s>
</DOCNO>
<FILEID>

<s docid="AP900731-0113" num="2" wdcount="2"> AP-NR-07-31-90 1559EDT</s>
</FILEID>
<FIRST>

<s docid="AP900731-0113" num="3" wdcount="5"> r i AM-Iraq-Kuwait 07-31 0539</s>
</FIRST>
<SECOND>

<s docid="AP900731-0113" num="4" wdcount="1"> AM-Iraq-Kuwait,0558</s>
</SECOND>
<HEAD>

<s docid="AP900731-0113" num="5" wdcount="9"> 100,000 Troops Massed on Iraq-Kuwait Border as Talks Begin</s>
</HEAD>
<BYLINE>

<s docid="AP900731-0113" num="6" wdcount="3"> By ABDULLAH AL-SHEHRI</s>
</BYLINE>
<DATELINE>

<s docid="AP900731-0113" num="7" wdcount="4"> JIDDAH, Saudi Arabia (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900731-0113" num="8" wdcount="19"> Kuwaiti and Iraqi negotiators embraced warmly Tuesday as they began talks on their oil and border dispute, sources said.</s>

<s docid="AP900731-0113" num="9" wdcount="11"> Diplomats reported that Iraq had massed 100,000 troops on Kuwait's border.</s>

<s docid="AP900731-0113" num="10" wdcount="26"> Gulf-based diplomatic sources said the Iraqi force, triple the number earlier reported, included about 300 Soviet-made tanks, and dwarfed the entire Kuwaiti army of 20,000 troops.</s>

<s docid="AP900731-0113" num="11" wdcount="25"> The diplomats, who spoke on condition of anonymity, said the troops have been concentrated along the border since last week, when Iraq began threatening Kuwait.</s>

<s docid="AP900731-0113" num="12" wdcount="21"> Iraq accused the small Persian Gulf state of stealing oil from a disputed border region and forcing oil prices to drop.</s>

<s docid="AP900731-0113" num="13" wdcount="13"> The diplomats said the number of troops was at first difficult to determine.</s>

<s docid="AP900731-0113" num="14" wdcount="29"> The delegation leaders, Crown Prince and Prime Minister Sheik Saad al-Abdullah al-Sabah of Kuwait, and Izzat Ibrahim, deputy chairman of Iraq's Revolutionary Command Council, met privately for two hours.</s>

<s docid="AP900731-0113" num="15" wdcount="15"> There were no details on the negotiations, but sources said the meetings will continue Wednesday.</s>

<s docid="AP900731-0113" num="16" wdcount="29"> Diplomatic sources have said they expect Arab mediators to push the two sides to sign a treaty of non-belligerency to be followed by protracted negotiations on borders and compensation.</s>

<s docid="AP900731-0113" num="17" wdcount="38"> The Iraq-Kuwait crisis broke out on July 17 when Iraqi President Saddam Hussein accused Kuwait and the United Arab Emirates of driving down oil prices by exceeding quotas set for them by the Organization of Petroleum Exporting Countries.</s>

<s docid="AP900731-0113" num="18" wdcount="11"> Saddam said the move cost Iraq $14 billion in lost revenue.</s>

<s docid="AP900731-0113" num="19" wdcount="28"> Saddam also demanded compensation for the $2.4 billion in oil he claimed Kuwait pumped illegally from an oil field which straddles the unmarked border between the two countries.</s>

<s docid="AP900731-0113" num="20" wdcount="19"> Iraq also demanded that Kuwait forgive $15 billion in loans it extended to Baghdad during the eight-year Iran-Iraq war.</s>

<s docid="AP900731-0113" num="21" wdcount="7"> Iraq's tough talk appeared to have succeeded.</s>

<s docid="AP900731-0113" num="22" wdcount="17"> Kuwait and the U.A.E agreed to stick to their oil quotas at an OPEC meeting last week.</s>

<s docid="AP900731-0113" num="23" wdcount="22"> OPEC member states also agreed to a longstanding Iraqi demand to raised target crude oil prices from $18 to $21 a barrel.</s>

<s docid="AP900731-0113" num="24" wdcount="21"> Kuwaiti and Iraqi officials agreed to meet in Jiddah after intensive mediation efforts by King Fahd and Egyptian President Hosni Mubarak.</s>

<s docid="AP900731-0113" num="25" wdcount="20"> Kuwaiti leaders had insisted that Iraq pull back its troops before conciliation talks could began, but later dropped that demand.</s>

<s docid="AP900731-0113" num="26" wdcount="20"> Kuwaiti officials also asked that Iraq agree to demarcate the disputed border between the nations, a move Iraq has refused.</s>

<s docid="AP900731-0113" num="27" wdcount="31"> Iraq has historically laid claim to all of Kuwait and has long coveted the Kuwaiti islands of Bubiyan and Warba, which command access to Iraq's sole outlet into the Persian Gulf.</s>

<s docid="AP900731-0113" num="28" wdcount="17"> The mediators have succeeded in toning down a vitriolic campaign against Kuwait by the Iraqi state-run media.</s>

<s docid="AP900731-0113" num="29" wdcount="11"> On Tuesday, the Iraqi delegation left Baghdad without any public announcement.</s>

<s docid="AP900731-0113" num="30" wdcount="12"> The leading Al-Thawra daily newspaper called the Jiddah meeting ``an opportunity ...</s>

<s docid="AP900731-0113" num="31" wdcount="3"> for Kuwait ...</s>

<s docid="AP900731-0113" num="32" wdcount="9"> to perceive Iraq's demands and respond to its rights''.</s>

<s docid="AP900731-0113" num="33" wdcount="12"> In contrast, the Kuwaiti delegation left for Jiddah with fanfare and publicity.</s>

<s docid="AP900731-0113" num="34" wdcount="33"> The Kuwaiti papers said they hoped the Jiddah meeting was the start of ``a final just settlement'' of the differences between Iraq and Kuwait, in a manner ensuring the ``legitimate rights of each.''</s>
</TEXT>
</DOC>
