<DOC>
<DOCNO>

<s docid="AP900802-0164" num="1" wdcount="1"> AP900802-0164</s>
</DOCNO>
<FILEID>

<s docid="AP900802-0164" num="2" wdcount="2"> AP-NR-08-02-90 1937EDT</s>
</FILEID>
<FIRST>

<s docid="AP900802-0164" num="3" wdcount="5"> u i AM-KuwaitGovernment 08-02 0437</s>
</FIRST>
<SECOND>

<s docid="AP900802-0164" num="4" wdcount="2"> AM-Kuwait Government,0449</s>
</SECOND>
<HEAD>

<s docid="AP900802-0164" num="5" wdcount="7"> Kuwaiti `Free Government' Statements Indicate Iraqi Control</s>
</HEAD>
<HEAD>

<s docid="AP900802-0164" num="6" wdcount="3"> With AM-Iraq-Kuwait, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP900802-0164" num="7" wdcount="3"> By NEIL MacFARQUHAR</s>
</BYLINE>
<BYLINE>

<s docid="AP900802-0164" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900802-0164" num="9" wdcount="3"> NICOSIA, Cyprus (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900802-0164" num="10" wdcount="22"> Iraq says it invaded Kuwait at the request of a revolutionary organization there, but diplomats dismiss that rationale as a large-scale charade.</s>

<s docid="AP900802-0164" num="11" wdcount="24"> The diplomatic world has remained largely unconviced by the flood of statements issued from Iraq in the name of the Provisional Free Kuwait Government.</s>

<s docid="AP900802-0164" num="12" wdcount="15"> Britain's U.N. ambassador, Crispin Tickell, called the Iraqi action ``an invasion from the outside ...</s>

<s docid="AP900802-0164" num="13" wdcount="6"> a phony coup d'etat from within''.</s>

<s docid="AP900802-0164" num="14" wdcount="14"> He said the invasion had led to ``the purported establishment of a puppet government''.</s>

<s docid="AP900802-0164" num="15" wdcount="21"> In a rare display of solidarity, the United States and the Soviet Union called for Iraq to withdraw and imposed sanctions.</s>

<s docid="AP900802-0164" num="16" wdcount="2"> The U.N.</s>

<s docid="AP900802-0164" num="17" wdcount="8"> Security Council voted 14-0 to condemn the invasion.</s>

<s docid="AP900802-0164" num="18" wdcount="34"> But Iraq's deputy permanent U.N. representative, Sabah Talat Kadrat, said the Security Council should not be debating the issue, because the fall of the Kuwaiti Emir, Sheik Jaber Al-Ahmed Al-Sabah, was an internal matter.</s>

<s docid="AP900802-0164" num="19" wdcount="16"> The official Kuwait News Agency, monitored in Nicosia, did not issue a single story all day.</s>

<s docid="AP900802-0164" num="20" wdcount="9"> Its computer periodically sputtered out the phrase ``Line cut''.</s>

<s docid="AP900802-0164" num="21" wdcount="21"> On the other hand, state-run Iraqi News Agency from Baghdad came alive with a series of communiques from the ``provisional government''.</s>

<s docid="AP900802-0164" num="22" wdcount="5"> The members were not identified.</s>

<s docid="AP900802-0164" num="23" wdcount="30"> The first statement said the provisional government ``finds that one of its primordial obligations is to remedy the harm done by the deposed, corrupt government to our brothers in Iraq''.</s>

<s docid="AP900802-0164" num="24" wdcount="10"> Iraq has been feuding with Kuwait over a border dispute.</s>

<s docid="AP900802-0164" num="25" wdcount="32"> It has also accused Kuwait of violating its oil production quotas set by the Organization of Petroleum Exporting Countries, costing Iraq of much-needed revenues because oil is cheaper when supplies are higher.</s>

<s docid="AP900802-0164" num="26" wdcount="29"> The statement on the Iraqi News Agency said the border dispute would be settled with ``fraternity and Arab national interests,'' indicating Iraq would probably take the land it wants.</s>

<s docid="AP900802-0164" num="27" wdcount="28"> The statement also said the Al-Sabah family, which had ruled Kuwait for almost 250 years, was working in concert with Zionist and colonial powers to plot against Iraq.</s>

<s docid="AP900802-0164" num="28" wdcount="17"> That is the charge the Iraqi press leveled at Kuwait when tensions began to rise in mid-July.</s>

<s docid="AP900802-0164" num="29" wdcount="19"> ``Falsification of elections, authoritarianism, persecution of patriotic personalities have always been characteristics of the Al-Sabah family,'' the statement said.</s>

<s docid="AP900802-0164" num="30" wdcount="16"> Kuwait is one of the few Arab states that has experimented with a freely elected parliament.</s>

<s docid="AP900802-0164" num="31" wdcount="21"> A new National Council with 50 members voted into office and 25 appointed by the emir took office after June elections.</s>

<s docid="AP900802-0164" num="32" wdcount="15"> The communiques from the Iraqi News Agency said the National Council has been disbanded .</s>
</TEXT>
</DOC>
