<DOC>
<DOCNO>

<s docid="AP900806-0077" num="1" wdcount="1"> AP900806-0077</s>
</DOCNO>
<FILEID>

<s docid="AP900806-0077" num="2" wdcount="2"> AP-NR-08-06-90 1340EDT</s>
</FILEID>
<FIRST>

<s docid="AP900806-0077" num="3" wdcount="7"> u i PM-Iraq-Kuwait 4thLd-Writethru a0553 08-06 1162</s>
</FIRST>
<SECOND>

<s docid="AP900806-0077" num="4" wdcount="4"> PM-Iraq-Kuwait, 4th Ld-Writethru, a0553,1197</s>
</SECOND>
<HEAD>

<s docid="AP900806-0077" num="5" wdcount="8"> Iraq Prepares for Attack; Turkish Oil Pipeline Closed</s>
</HEAD>
<HEAD>

<s docid="AP900806-0077" num="6" wdcount="3"> LaserPhoto AMS2, BON1-2</s>
</HEAD>
<NOTE>

<s docid="AP900806-0077" num="7" wdcount="26"> Eds: INSERTS 2 grafs after 4th pvs, `Saudi Arabia'... to UPDATE with reports carrier battle group within striking distance of gulf, U.S. rapid deployment force dispatched.</s>

<s docid="AP900806-0077" num="8" wdcount="5"> Pickup 5th pvs, `In other...'</s>
</NOTE>
<BYLINE>

<s docid="AP900806-0077" num="9" wdcount="3"> By SALAH NASRAWI</s>
</BYLINE>
<BYLINE>

<s docid="AP900806-0077" num="10" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900806-0077" num="11" wdcount="3"> BAGHDAD, Iraq (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900806-0077" num="12" wdcount="30"> Ruling party members said today that the government, fearing a U.S. air attack, was distributing automatic weapons to tens of thousands of supporters and preparing to evacuate the Iraqi capital.</s>

<s docid="AP900806-0077" num="13" wdcount="28"> A boycott of Iraqi oil forced Baghdad today to close one of two pipelines in Turkey that were pumping the bulk of Iraq's exported oil, Turkish officials said.</s>

<s docid="AP900806-0077" num="14" wdcount="19"> A British official said Iraqi troops rounded up American and British visitors in Kuwait and taking them to Iraq.</s>

<s docid="AP900806-0077" num="15" wdcount="21"> The Foreign Office spokesman said most were passengers from a British Airways flight stranded in Kuwait since the Iraqi invasion Thursday.</s>

<s docid="AP900806-0077" num="16" wdcount="15"> ``There is no evidence that they are in any way in trouble,'' the official said.</s>

<s docid="AP900806-0077" num="17" wdcount="19"> Saudi Arabia was reported reinforcing its troops along the Kuwaiti border following concerns Iraq may try to invade it.</s>

<s docid="AP900806-0077" num="18" wdcount="34"> Pentagon sources said the USS Independence and its carrier battle group are now on station in the Arabian Sea, a position that would allow it to launch fighter planes into the Persian Gulf region.</s>

<s docid="AP900806-0077" num="19" wdcount="25"> Gulf-based diplomats said soldiers from the American rapid deployment force, formed to react to crises in the Middle East, had been dispatched to the area.</s>

<s docid="AP900806-0077" num="20" wdcount="26"> In other developments: _The new Kuwait government installed by Iraq hinted it might take hostages or seize property of nations that take punitive measures against Iraq.</s>

<s docid="AP900806-0077" num="21" wdcount="16"> _Iraqi President Saddam Hussein said the 100,000 soldiers who invaded Kuwait began to pull back Sunday.</s>

<s docid="AP900806-0077" num="22" wdcount="6"> President Bush said Iraq was lying.</s>

<s docid="AP900806-0077" num="23" wdcount="20"> _Oil prices jumped more than $3 a barrel on news Europe and Japan were joining the embargo of Iraqi oil.</s>

<s docid="AP900806-0077" num="24" wdcount="3"> Stocks slumped worldwide.</s>

<s docid="AP900806-0077" num="25" wdcount="15"> _Hospital officials said at least 300 Kuwaiti and Iraqi soldiers were killed during the invasion.</s>

<s docid="AP900806-0077" num="26" wdcount="12"> In London, Kuwaitis arriving on a special plane said 700 Kuwaitis died.</s>

<s docid="AP900806-0077" num="27" wdcount="16"> The embargo of Iraqi oil grew over the weekend to include Japan and the European Community.</s>

<s docid="AP900806-0077" num="28" wdcount="20"> Along with the United States, they bought more than half Iraq's exported oil, with most of it pumped through Turkey.</s>

<s docid="AP900806-0077" num="29" wdcount="37"> An official of the state-run Turkish pipeline company BOTAS said pumping stopped at one of the two Turkish pipelines at 5 p.m. Iraq reduced flow in the second, wider, pipeline to 70 percent of capacity, they said.</s>

<s docid="AP900806-0077" num="30" wdcount="6"> There was no comment from Iraq.</s>

<s docid="AP900806-0077" num="31" wdcount="23"> The two pipelines pump Iraqi crude from Kirkuk oil fields in northern Iraq to a terminal at the northeastern tip of the Mediterranean.</s>

<s docid="AP900806-0077" num="32" wdcount="18"> They carry 70 million tons of crude annually, providing the outlet for the major share of Iraqi exports.</s>

<s docid="AP900806-0077" num="33" wdcount="19"> The BOTAS official said all the countries participating in the embargo purchase their Iraqi crude from the Turkish outlet.</s>

<s docid="AP900806-0077" num="34" wdcount="17"> Iraq also exports oil through a Saudi Arabian pipeline and via tankers in the northern Persian Gulf.</s>

<s docid="AP900806-0077" num="35" wdcount="29"> A Foreign Office spokesman said today as saying a total of 366 people had been assembled by Iraqi troops in Kuwait, mostly passengers from a stranded British Airways flight.</s>

<s docid="AP900806-0077" num="36" wdcount="10"> They were being transported by bus to the Iraqi border.</s>

<s docid="AP900806-0077" num="37" wdcount="9"> Baghdad did not give any reason for its action.</s>

<s docid="AP900806-0077" num="38" wdcount="13"> Immediately after the invasion Thursday, 11 Americans were rounded up by Iraqi troops.</s>

<s docid="AP900806-0077" num="39" wdcount="6"> They turned up safe in Baghdad.</s>

<s docid="AP900806-0077" num="40" wdcount="8"> The new Iraqi-installed foreign minister of Kuwait, Lt.</s>

<s docid="AP900806-0077" num="41" wdcount="17"> Col. Walid Sa'oud Mohammed Abdullah, warned against further sanctions in a statement broadcast Sunday by Iraqi radio.</s>

<s docid="AP900806-0077" num="42" wdcount="27"> ``Countries that resort to punitive measures against the provisional free Kuwait government and fraternal Iraq should remember that they have interests and nationals in Kuwait,'' he said.</s>

<s docid="AP900806-0077" num="43" wdcount="23"> Iraqi soldiers invaded Kuwait after complaining that its violation of OPEC production quotas was driving down world crude prices, lowering Iraqi oil revenues.</s>

<s docid="AP900806-0077" num="44" wdcount="16"> Saddam also accused Kuwait of stealing oil from a field that includes land both sides claim.</s>

<s docid="AP900806-0077" num="45" wdcount="17"> The respected Middle East Economic Survey reported today that Kuwait's oil export facilities had been shut down.</s>

<s docid="AP900806-0077" num="46" wdcount="26"> It also said there was considerable doubt Saudi Arabia, with the world's largest oil reserves, would be willing to make up the potential world oil shortage.</s>

<s docid="AP900806-0077" num="47" wdcount="19"> Kuwait and Iraq together account for one-fifth of the 23.5 million barrels produced daily by the 13 OPEC nations.</s>

<s docid="AP900806-0077" num="48" wdcount="24"> Tensions remained high in the region; a U.S. official said in Washington that Iraqi troops massed on the Kuwaiti-Saudi border were apparently digging in.</s>

<s docid="AP900806-0077" num="49" wdcount="23"> An American technician at a secret Saudi Arabian base said the kingdom had sent 200 to 300 tanks toward its border with Kuwait.</s>

<s docid="AP900806-0077" num="50" wdcount="23"> Oil industry sources in Saudi Arabia reached by telephone from Bahrain said Saudi troops were entering the region of Khafji, near the border.</s>

<s docid="AP900806-0077" num="51" wdcount="13"> Residents reached by telephone reported intense air activity near the Saudi airport overnight.</s>

<s docid="AP900806-0077" num="52" wdcount="25"> The Washington Post reported today that Egypt was mobilizing some elements of its armed forces to assist Saudi Arabia in the event of an invasion.</s>

<s docid="AP900806-0077" num="53" wdcount="15"> U.S. officials said there was no indication Iraqi troops were preparing to invade Saudi Arabia.</s>

<s docid="AP900806-0077" num="54" wdcount="32"> But Bush sent Defense Secretary Dick Cheney to the kingdom to confer with its leaders, and the White House said Secretary of State James A. Baker would go this week to Turkey.</s>

<s docid="AP900806-0077" num="55" wdcount="35"> Saadi Mehdi Saleh, the Iraqi army commander, was quoted by the Al-Iraq newspaper as saying tens of thousands of volunteers had joined the army to defend what he called ``Iraq and the revolution in Kuwait''.</s>

<s docid="AP900806-0077" num="56" wdcount="20"> Americans, he was quoted as saying, ``should understand that the people of the great leader Saddam Hussein cannot be frightened''.</s>

<s docid="AP900806-0077" num="57" wdcount="25"> Local members of the ruling Baath party said preparations were under way to evacuate all of Baghdad's 4 million people to camps outside the city.</s>

<s docid="AP900806-0077" num="58" wdcount="7"> They were being told that the U.S.</s>

<s docid="AP900806-0077" num="59" wdcount="14"> Air Force might attack or that Israel might attack with chemical or nuclear weapons.</s>

<s docid="AP900806-0077" num="60" wdcount="23"> The party members also said the party had distributed guns, mainly AK-47 automatic rifles, to tens of thousands of people around the country.</s>

<s docid="AP900806-0077" num="61" wdcount="19"> State radio said Saddam had ordered the formation of 11 new Iraqi army divisions, expected to generate 100,000 troops.</s>

<s docid="AP900806-0077" num="62" wdcount="14"> The Arab world's most formidible military force is already estimated at 1 million men.</s>

<s docid="AP900806-0077" num="63" wdcount="32"> At a border checkpoint 30 miles south of the Iraqi port city of Basra, dozens of tanks, armored personnel carriers and trucks carrying hundreds of soldiers crossed back into Iraq on Sunday.</s>

<s docid="AP900806-0077" num="64" wdcount="17"> But thousands of Iraqi soldiers remained behind in Kuwait, controlling major government buildings, commerical centers and ports.</s>

<s docid="AP900806-0077" num="65" wdcount="13"> Diplomats in the region said a new Kuwaiti army fanned out through Kuwait.</s>

<s docid="AP900806-0077" num="66" wdcount="8"> The force comprises about 80,000 troops, mostly Iraqis.</s>

<s docid="AP900806-0077" num="67" wdcount="13"> The nine-member Kuwaiti military government, announced by Iraq on Saturday, remained a mystery.</s>

<s docid="AP900806-0077" num="68" wdcount="26"> No photographs of the named leaders have been shown and 12 reporters brought to Kuwait by the Ministry of Information could not locate any of them.</s>

<s docid="AP900806-0077" num="69" wdcount="19"> Kuwaiti diplomats said they were all Iraqis, including a son-in-law of Saddam, a charge official Iraqi media denied .</s>
</TEXT>
</DOC>
