<DOC>
<DOCNO>

<s docid="AP900804-0057" num="1" wdcount="1"> AP900804-0057</s>
</DOCNO>
<FILEID>

<s docid="AP900804-0057" num="2" wdcount="2"> AP-NR-08-04-90 0828EDT</s>
</FILEID>
<FIRST>

<s docid="AP900804-0057" num="3" wdcount="5"> r i PM-Kuwait-Saudi 08-04 0538</s>
</FIRST>
<SECOND>

<s docid="AP900804-0057" num="4" wdcount="1"> PM-Kuwait-Saudi,0552</s>
</SECOND>
<HEAD>

<s docid="AP900804-0057" num="5" wdcount="6"> Saudis Take No Steps Against Iraq</s>
</HEAD>
<HEAD>

<s docid="AP900804-0057" num="6" wdcount="3"> With PM-Iraq-Kuwait, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP900804-0057" num="7" wdcount="3"> By NICK LUDINGTON</s>
</BYLINE>
<BYLINE>

<s docid="AP900804-0057" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900804-0057" num="9" wdcount="3"> NICOSIA, Cyprus (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900804-0057" num="10" wdcount="18"> Saudi Arabia, an oil-rich ally of Kuwait, has been subdued in its reaction to Iraq's invasion of Kuwait.</s>

<s docid="AP900804-0057" num="11" wdcount="27"> The only direct Saudi statement since the invasion was made by an anonymous government spokesman through the official Saudi Press Agency the day after the Iraqi move.</s>

<s docid="AP900804-0057" num="12" wdcount="6"> It did not condemn Thursday's invasion.</s>

<s docid="AP900804-0057" num="13" wdcount="36"> It said Saudi Arabia was following the Kuwait situation ``with extreme concern'' and that King Fahd would be seeking to calm the situation and to find a solution ``in a manner ensuring the interests of all''.</s>

<s docid="AP900804-0057" num="14" wdcount="29"> The only tangible help Saudi Arabia gave the Kuwait government was to shelter members of the ruling family, including the emir, Sheik Jaber al-Ahmed al-Sabah, and his crown prince.</s>

<s docid="AP900804-0057" num="15" wdcount="8"> Both nations are tightly run by royal families.</s>

<s docid="AP900804-0057" num="16" wdcount="22"> The Saudis also allowed them briefly to operate a radio, reportedly from a mobile van in the area around the Saudi-Kuwait border.</s>

<s docid="AP900804-0057" num="17" wdcount="8"> It broadcast calls for resistance to the Iraqis.</s>

<s docid="AP900804-0057" num="18" wdcount="34"> But on Friday the radio went off the air after a desperate call: ``The people of Kuwait appeal to you oh brethren, oh Arabs, oh beloved brothers, oh Moslems, rush, rush to their help''.</s>

<s docid="AP900804-0057" num="19" wdcount="42"> It was not known if the radio had been discovered by the Iraqis or shut down by the Saudis to avoid provoking Iraqi President Saddam Hussein at a time when fears were being expressed that he might invade Saudi Arabia as well.</s>

<s docid="AP900804-0057" num="20" wdcount="35"> Oil executives said Saudi Arabia has not and will not take the most potent action possible against Iraq _ closing the pipeline that carries Iraqi oil for export across Saudi Arabia to the Red Sea.</s>

<s docid="AP900804-0057" num="21" wdcount="40"> The executives said the Saudis realize this would give the belligerent Saddam an excuse to attack and occupy the Saudi oil fields 150 miles south of Kuwait, giving Iraq control of more oil than any other country in the world.</s>

<s docid="AP900804-0057" num="22" wdcount="20"> Turkey also has refused to comment about President Bush's suggestion that Turkey cut off Iraq's oil pipeline to the Mediterranean.</s>

<s docid="AP900804-0057" num="23" wdcount="27"> Two parallel pipelines pump Iraqi crude oil to a terminal at Yumurtalik at the eastern corner of Turkey's Mediterranean coast and constitute Iraq's major oil export outlet.</s>

<s docid="AP900804-0057" num="24" wdcount="38"> The Saudis did condemn the invasion as part of a joint statement issued by the Gulf Cooperation Council, in which it is allied for economic and security cooperation with Kuwait, the United Arab Emirates, Qatar, Oman and Bahrain.</s>

<s docid="AP900804-0057" num="25" wdcount="26"> The six states issued a statement saying, ``We strongly condemn and are very sorry for this attack that one Arab state took against another Arab state.</s>

<s docid="AP900804-0057" num="26" wdcount="9"> ... We do not recognize anything resulting from it''.</s>

<s docid="AP900804-0057" num="27" wdcount="29"> Iraq's huge armed force is clearly too much for the joint 3,000-man Gulf Cooperation Council force, based at Hafr al-Baten in northeastern Saudi Arabia 65 miles south of Kuwait.</s>

<s docid="AP900804-0057" num="28" wdcount="13"> But there was no talk of specific action against Iraq by Kuwait's partners.</s>

<s docid="AP900804-0057" num="29" wdcount="27"> Saudi Arabia was also one of the 14 members of the 21-member Arab League that condemned the invasion in the same terms as the Gulf Cooperation Council.</s>

<s docid="AP900804-0057" num="30" wdcount="23"> The Arab League, with one-third of its members voting against the resolution or abstaining, was clearly unable to take any direct action .</s>
</TEXT>
</DOC>
