<DOC>
<DOCNO>

<s docid="AP900802-0180" num="1" wdcount="1"> AP900802-0180</s>
</DOCNO>
<FILEID>

<s docid="AP900802-0180" num="2" wdcount="2"> AP-NR-08-02-90 2246EDT</s>
</FILEID>
<FIRST>

<s docid="AP900802-0180" num="3" wdcount="5"> u i AM-Iraq-Kuwait-Glance 08-02 0302</s>
</FIRST>
<SECOND>

<s docid="AP900802-0180" num="4" wdcount="1"> AM-Iraq-Kuwait-Glance,0314</s>
</SECOND>
<HEAD>

<s docid="AP900802-0180" num="5" wdcount="7"> Basic Facts of Iraq's Invasion of Kuwait</s>
</HEAD>
<HEAD>

<s docid="AP900802-0180" num="6" wdcount="3"> With AM-Iraq-Kuwait, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP900802-0180" num="7" wdcount="4"> By The Associated Press</s>
</BYLINE>
<TEXT>

<s docid="AP900802-0180" num="8" wdcount="26"> THE INVASION: Iraq's troops, led by about 350 tanks, crossed the border at dawn Thursday, and seized the Kuwaiti palace and government buildings 40 miles away.</s>

<s docid="AP900802-0180" num="9" wdcount="9"> Early Friday, the invaders controlled Kuwait city, the capital.</s>

<s docid="AP900802-0180" num="10" wdcount="19"> The soldiers were also making sweeps through the southern oilfields, according to residents and Lloyds' insurance service in London.</s>

<s docid="AP900802-0180" num="11" wdcount="24"> Diplomatic sources estimate more than 200 Kuwaitis were killed or wounded, mainly from the Emiri Guard which bore the main brunt of the invasion.</s>

<s docid="AP900802-0180" num="12" wdcount="11"> Kuwait's Sheik Saad al-Abdullah al-Sabah fled to safety in Saudi Arabia.</s>

<s docid="AP900802-0180" num="13" wdcount="28"> THE FORCES: Iraq, a country of more than 17 million, has the Arab world's most battle-trained army, and had massed more than 100,000 soldiers on the Kuwaiti border.</s>

<s docid="AP900802-0180" num="14" wdcount="19"> Kuwait, an oil-rich city-state, has 1.9 million residents _ 60 percent foreigners _ and an army of 20,300 soldiers.</s>

<s docid="AP900802-0180" num="15" wdcount="23"> CAUSE OF CONFLICT: President Saddam Hussein of Iraq accused Kuwait of stealing oil from its territory and forcing down oil prices through overproduction.</s>

<s docid="AP900802-0180" num="16" wdcount="16"> Kuwait and U.N. diplomats dismissed Iraq's claim that it invaded at the request of Kuwaiti revolutionaries.</s>

<s docid="AP900802-0180" num="17" wdcount="3"> REACTION: The U.N.</s>

<s docid="AP900802-0180" num="18" wdcount="8"> Security Council voted 14-0 to condemn the invasion.</s>

<s docid="AP900802-0180" num="19" wdcount="7"> President Bush denounced it as ``naked agression''.</s>

<s docid="AP900802-0180" num="20" wdcount="16"> He froze Iraq's assets in the United States and blocked almost all Iraqi imports, including oil.</s>

<s docid="AP900802-0180" num="21" wdcount="19"> The order also froze Kuwait property under U.S. jurisdiction _ a move intended to keep Iraq from seizing it.</s>

<s docid="AP900802-0180" num="22" wdcount="12"> The Soviets also condemned the invasion and stopped arms sales to Iraq.</s>

<s docid="AP900802-0180" num="23" wdcount="12"> Kuwait's U.S. ambassador said the nation had asked for American military intervention.</s>

<s docid="AP900802-0180" num="24" wdcount="14"> A Pentagon source said a U.S. naval group was diverted toward the Persian Gulf.</s>

<s docid="AP900802-0180" num="25" wdcount="17"> Oil prices soared in frenzied trading amid fears the invasion would reduce the supply of oil .</s>
</TEXT>
</DOC>
