<DOC>
<DOCNO>

<s docid="LA080290-0233" num="1" wdcount="1"> LA080290-0233</s>
</DOCNO>
<DOCID>

<s docid="LA080290-0233" num="2" wdcount="1"> 256241</s>
</DOCID>
<DATE>
<P>

<s docid="LA080290-0233" num="3" wdcount="6"> August 2, 1990, Thursday, P.M. Final</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA080290-0233" num="4" wdcount="9"> Part P; Page 1; Column 5; Late Final Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA080290-0233" num="5" wdcount="2"> 537 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA080290-0233" num="6" wdcount="3"> IRAQ TRAMPLES KUWAIT;</s>
</P>
<P>

<s docid="LA080290-0233" num="7" wdcount="6"> TROOPS SEIZE CAPITAL, PALACE; EMIR FLEES;</s>
</P>
<P>

<s docid="LA080290-0233" num="8" wdcount="7"> 200 KUWAITIS SAID KILLED OR INJURED; U.S.</s>

<s docid="LA080290-0233" num="9" wdcount="2"> AID SOUGHT</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA080290-0233" num="10" wdcount="3"> From Associated Press</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA080290-0233" num="11" wdcount="1"> KUWAIT</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA080290-0233" num="12" wdcount="15"> Iraq's powerful army claimed victory today in its lightning invasion of this small, oil-rich kingdom.</s>

<s docid="LA080290-0233" num="13" wdcount="21"> Tank-led troops quickly seized the ruler's palace and government buildings, and the emir fled to Saudi Arabia, Kuwaiti officials said .</s>
</P>
<P>

<s docid="LA080290-0233" num="14" wdcount="22"> Kuwait's U.S. ambassador said the Iraqis occupied all government buildings in the capital and were moving south toward the country's oil facilities.</s>

<s docid="LA080290-0233" num="15" wdcount="7"> He appealed for U.S. military intervention .</s>
</P>
<P>

<s docid="LA080290-0233" num="16" wdcount="16"> "The Iraqis have occupied all of Kuwait"! a Kuwaiti government official shouted in a telephone interview.</s>

<s docid="LA080290-0233" num="17" wdcount="17"> Diplomatic sources in the Persian Gulf estimated that more than 200 Kuwaitis were killed or wounded .</s>
</P>
<P>

<s docid="LA080290-0233" num="18" wdcount="30"> The Iraqi government of President Saddam Hussein claimed that it invaded at the request of revolutionaries who had already staged a coup and established "the provisional government of free Kuwait".</s>

<s docid="LA080290-0233" num="19" wdcount="11"> Kuwait and U.N. diplomats labeled the coup report a farce .</s>
</P>
<P>

<s docid="LA080290-0233" num="20" wdcount="20"> Baghdad television said Iraq could withdraw its forces within days or weeks, depending on how quickly the situation stabilized .</s>
</P>
<P>

<s docid="LA080290-0233" num="21" wdcount="24"> The assault followed two weeks of tension between Kuwait and Iraq, caused by Iraqi accusations that Kuwait stole oil from a disputed border area.</s>

<s docid="LA080290-0233" num="22" wdcount="22"> Saddam also accused Kuwait of exceeding OPEC production quotas, thus driving down the price of oil, a major Iraqi revenue source .</s>
</P>
<P>

<s docid="LA080290-0233" num="23" wdcount="15"> In recent days, diplomats said Iraq had massed more than 100,000 troops at the border.</s>

<s docid="LA080290-0233" num="24" wdcount="8"> Kuwait's entire armed forces has 20,300 soldiers .</s>
</P>
<P>

<s docid="LA080290-0233" num="25" wdcount="21"> It was the first time in modern history that an Arab nation had invaded another and taken over its government .</s>
</P>
<P>

<s docid="LA080290-0233" num="26" wdcount="16"> Kuwait's army was no match for Iraq, battle-hardened after eight years of war with Iran .</s>
</P>
<P>

<s docid="LA080290-0233" num="27" wdcount="22"> Diplomats said about 350 Iraqi tanks wheeled into the capital a few hours after crossing the border 40 miles away at dawn.</s>

<s docid="LA080290-0233" num="28" wdcount="18"> Witnesses said the bombardment of ports and military airports by artillery and the air force was vicious .</s>
</P>
<P>

<s docid="LA080290-0233" num="29" wdcount="14"> The invaders surrounded the palace of Kuwait's ruler, Sheik Jabbar al Ahmed al Sabah.</s>

<s docid="LA080290-0233" num="30" wdcount="15"> Residents said the palace was seized after about two hours of heavy artillery barrages .</s>
</P>
<P>

<s docid="LA080290-0233" num="31" wdcount="22"> Diplomats said Sheik Fahd al Ahmed al Sabah, one of the emir's brothers, was killed while trying to defend the palace .</s>
</P>
<P>

<s docid="LA080290-0233" num="32" wdcount="16"> There were about 50 tanks around the palace and the neighboring American Embassy, residents said .</s>
</P>
<P>

<s docid="LA080290-0233" num="33" wdcount="12"> The al Sabah family has ruled the city-state for almost 250 years.</s>

<s docid="LA080290-0233" num="34" wdcount="12"> The Kuwaiti ambassador said the leaders were safe in Saudi Arabia .</s>
</P>
<P>

<s docid="LA080290-0233" num="35" wdcount="36"> Operating from an unknown location, al Ahmed's government responded to the formation of the provisional government by stating: "Kuwait is Kuwait to its people, led by the emir, Sheik Jabbar, and his Crown Prince Sheik Saad.</s>

<s docid="LA080290-0233" num="36" wdcount="7"> God preserve them from all harm" .</s>
</P>
<P>

<s docid="LA080290-0233" num="37" wdcount="30"> For its part, the provisional government announced through Baghdad's official Iraqi News Agency that it was dissolving Parliament and would hold "free and honest elections" at a future date .</s>
</P>
<P>

<s docid="LA080290-0233" num="38" wdcount="12"> Kuwait's land and sea borders were closed, as was the airport .</s>
</P>
<P>

<s docid="LA080290-0233" num="39" wdcount="7"> RELATED STORIES, PICTURES: Pages 2,3, BACK PAGE</s>
</P>
<P>
</P>
<P>

<s docid="LA080290-0233" num="40" wdcount="3"> Military Forces Compared:</s>
</P>
<P>

<s docid="LA080290-0233" num="41" wdcount="2"> Total Troops:</s>
</P>
<P>

<s docid="LA080290-0233" num="42" wdcount="2"> Iraq: 1,000,000</s>
</P>
<P>

<s docid="LA080290-0233" num="43" wdcount="2"> Kuwait: 20,300</s>
</P>
<P>

<s docid="LA080290-0233" num="44" wdcount="3"> Main Battle Tanks:</s>
</P>
<P>

<s docid="LA080290-0233" num="45" wdcount="2"> Iraq: 5,500</s>
</P>
<P>

<s docid="LA080290-0233" num="46" wdcount="2"> Kuwait: 275</s>
</P>
<P>

<s docid="LA080290-0233" num="47" wdcount="2"> Combat Aircraft:</s>
</P>
<P>

<s docid="LA080290-0233" num="48" wdcount="2"> Iraq: 513</s>
</P>
<P>

<s docid="LA080290-0233" num="49" wdcount="2"> Kuwait: 36</s>
</P>
<P>

<s docid="LA080290-0233" num="50" wdcount="1"> Ships:</s>
</P>
<P>

<s docid="LA080290-0233" num="51" wdcount="2"> Iraq: 51</s>
</P>
<P>

<s docid="LA080290-0233" num="52" wdcount="2"> Kuwait: 46</s>
</P>
<P>

<s docid="LA080290-0233" num="53" wdcount="6"> Source: International Institute for Strategic Studies</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA080290-0233" num="54" wdcount="30"> Map, IRAQI INVASION OF KUWAIT: Iraqi troops and tanks swept into Kuwait late Wednesday night and within hours had taken control of Kuwait City, the capital and only sizable town.</s>

<s docid="LA080290-0233" num="55" wdcount="5"> AP / Los Angeles Times</s>
</P>
</GRAPHIC>
<TYPE>
<P>

<s docid="LA080290-0233" num="56" wdcount="1"> Wire</s>
</P>
</TYPE>
</DOC>
