<DOC>
<DOCNO>

<s docid="WSJ900803-0023" num="1" wdcount="1"> WSJ900803-0023</s>
</DOCNO>
<DOCID>

<s docid="WSJ900803-0023" num="2" wdcount="2"> 900803-0023 .</s>
</DOCID>
<HL>

<s docid="WSJ900803-0023" num="3" wdcount="14"> The Iraqi Invasion of Kuwait: CIA Had Given Warning Of Iraq's Move on Kuwait</s>
</HL>
<DATE>

<s docid="WSJ900803-0023" num="4" wdcount="1"> 08/03/90</s>
</DATE>
<SO>

<s docid="WSJ900803-0023" num="5" wdcount="6"> WALL STREET JOURNAL (J), PAGE A5</s>
</SO>
<CO>

<s docid="WSJ900803-0023" num="6" wdcount="1"> MDEST</s>
</CO>
<GV>

<s docid="WSJ900803-0023" num="7" wdcount="5"> EXECUTIVE (EXE) FEDERAL GOVERNMENT (FDL)</s>
</GV>
<LP>

<s docid="WSJ900803-0023" num="8" wdcount="19"> WASHINGTON -- U.S. intelligence officials had been sounding alarms in recent days about a possible Iraqi invasion of Kuwait.</s>

<s docid="WSJ900803-0023" num="9" wdcount="36"> Emphasizing that the Central Intelligence Agency wasn't surprised by the Iraqi action, an agency spokesman said yesterday, "We provided policy makers with very useful and timely information on these events and we continue to do so."</s>
</LP>
<TEXT>

<s docid="WSJ900803-0023" num="10" wdcount="11"> Administration and congressional officials agree that the CIA did its job.</s>

<s docid="WSJ900803-0023" num="11" wdcount="39"> Since last week, President Bush had been warned by intelligence analysts that what originally looked like a military bluff was quickly turning into the kind of troop deployment that could be used to invade Kuwait or even Saudi Arabia.</s>

<s docid="WSJ900803-0023" num="12" wdcount="21"> Central Intelligence Agency Director William Webster even hand-delivered certain fresh details on the Iraqi buildup to National Security Adviser Brent Scowcroft.</s>

<s docid="WSJ900803-0023" num="13" wdcount="25"> Among the assessments he conveyed was a conclusion that, by this week, President Saddam Hussein's force would be capable of penetrating Kuwait or Saudi Arabia.</s>

<s docid="WSJ900803-0023" num="14" wdcount="13"> The agency lacked hard evidence of an intent to invade, intelligence officials say.</s>

<s docid="WSJ900803-0023" num="15" wdcount="35"> But as the buildup grew, the CIA became more alarmed, partly because Mr. Hussein is so unpredictable, and partly because, unlike many other Arab leaders, he has been known to carry out his threats .</s>
</TEXT>
</DOC>
