<DOC>
<DOCNO>

<s docid="AP890922-0049" num="1" wdcount="1"> AP890922-0049</s>
</DOCNO>
<FILEID>

<s docid="AP890922-0049" num="2" wdcount="2"> AP-NR-09-22-89 0413EDT</s>
</FILEID>
<FIRST>

<s docid="AP890922-0049" num="3" wdcount="7"> r a PM-Hugo-CharlestonHistory 1stLd-Writethru a0475 09-22 0361</s>
</FIRST>
<SECOND>

<s docid="AP890922-0049" num="4" wdcount="7"> PM-Hugo-Charleston History, 1st Ld - Writethru, a0475,0367</s>
</SECOND>
<HEAD>

<s docid="AP890922-0049" num="5" wdcount="10"> Hurricane Latest in String of Disasters to Hit Historic City</s>
</HEAD>
<HEAD>

<s docid="AP890922-0049" num="6" wdcount="3"> With PM-Hugo-Scene, Bjt</s>
</HEAD>
<HEAD>

<s docid="AP890922-0049" num="7" wdcount="19"> Eds: LEADS with 6 grafs to UPDATE with storm having hit; picks up 6th graf, `Charleston, a city ...'</s>
</HEAD>
<BYLINE>

<s docid="AP890922-0049" num="8" wdcount="3"> By BRUCE SMITH</s>
</BYLINE>
<BYLINE>

<s docid="AP890922-0049" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890922-0049" num="10" wdcount="3"> CHARLESTON, S.C. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890922-0049" num="11" wdcount="28"> This historic city has survived the ravages of earthquake, battle and storm in its storied 300-year-history, but it faced perhaps its greatest test of all in Hurricane Hugo.</s>

<s docid="AP890922-0049" num="12" wdcount="14"> The storm, packing winds of up to 135 mph, raged into Charleston Thursday night.</s>

<s docid="AP890922-0049" num="13" wdcount="49"> ``This is a dangerous, killer hurricane, the likes of which few people who have lived all their lives in Charleston have experienced,'' warned Mayor Joseph P. Riley Jr. Hugo was the first major hurricane to strike Charleston since Hurricane Gracie came ashore 70 miles to the south in 1959.</s>

<s docid="AP890922-0049" num="14" wdcount="12"> The seaside community has suffered through many disasters, both natural and man-made.</s>

<s docid="AP890922-0049" num="15" wdcount="29"> The worst in recent decades was in 1938 when a tornado tore through the city, killing 32 people, injuring hundreds and causing an estimated $2 million in property damage.</s>

<s docid="AP890922-0049" num="16" wdcount="20"> Charleston, a city of pastel-colored antebellum structures lining quaint streets and alleyways, is where the Civil War began in 1861.</s>

<s docid="AP890922-0049" num="17" wdcount="27"> The city has survived the shot and shell of two wars and any number of smaller hurricanes, politely referred to by Charlestonians of refinement as ``September gales''.</s>

<s docid="AP890922-0049" num="18" wdcount="33"> But the worst natural disaster to beset the city occurred on the hot night of Aug. 31, 1886, when the ground rumbled in what some folks thought was a prelude to Judgement Day.</s>

<s docid="AP890922-0049" num="19" wdcount="15"> The great Charleston earthquake was felt as far away as Chicago and New York City.</s>

<s docid="AP890922-0049" num="20" wdcount="30"> Measuring 7.7 on the Richter scale of ground motion, the earthquake claimed an estimated 110 lives, destroyed 102 buildings and tossed most of the city's 14,000 chimneys into the streets.</s>

<s docid="AP890922-0049" num="21" wdcount="23"> In recent years, the city has attracted millions of visitors annually who tour its historic buildings and visit its nearby fine sand beaches.</s>

<s docid="AP890922-0049" num="22" wdcount="17"> Charleston has received international acclaim as home to Spoleto Festival U.S.A., founded by composer Gian Carlo Menotti.</s>

<s docid="AP890922-0049" num="23" wdcount="14"> Organizers like to refer to Spoleto as the world's most comprehensive arts festival .</s>
</TEXT>
</DOC>
