<DOC>
<DOCNO>

<s docid="AP890928-0099" num="1" wdcount="1"> AP890928-0099</s>
</DOCNO>
<FILEID>

<s docid="AP890928-0099" num="2" wdcount="2"> AP-NR-09-28-89 1317EDT</s>
</FILEID>
<FIRST>

<s docid="AP890928-0099" num="3" wdcount="5"> r a AM-Hugo-OldDebt 09-28 0287</s>
</FIRST>
<SECOND>

<s docid="AP890928-0099" num="4" wdcount="2"> AM-Hugo-Old Debt,0294</s>
</SECOND>
<HEAD>

<s docid="AP890928-0099" num="5" wdcount="10"> City Sends Money To Charleston In Repayment Of 211-year-old Debt</s>
</HEAD>
<HEAD>

<s docid="AP890928-0099" num="6" wdcount="3"> With AM-Hugo Bjt</s>
</HEAD>
<DATELINE>

<s docid="AP890928-0099" num="7" wdcount="3"> KINGSTON, N.Y. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890928-0099" num="8" wdcount="22"> It's taken the devastation caused by Hurricane Hugo to stimulate repayment of a 211-year-old debt between two cities almost 1,000 miles apart.</s>

<s docid="AP890928-0099" num="9" wdcount="19"> As a way of repaying a kindness dating to 1778, Kingston is raising money to help Charleston, S.C., recover.</s>

<s docid="AP890928-0099" num="10" wdcount="28"> After Kingston, then New York's capital, was burned in October 1777 by the British, New York Gov. George Clinton received a letter from South Carolina Gov. Abraham Livingston.</s>

<s docid="AP890928-0099" num="11" wdcount="16"> The letter included nearly 1,000 New York pounds to help Kingston residents get through their crisis.</s>

<s docid="AP890928-0099" num="12" wdcount="41"> ``This money has been received for the charitable purpose of alleviating the distresses of the now-indigent inhabitants of the town of Kingston, who by the ravages of the enemy are reduced to poverty and want,'' Livingston wrote on March 31, 1778.</s>

<s docid="AP890928-0099" num="13" wdcount="15"> Kingston Historian Edwin Ford remembered the letter when Hurricane Hugo ravaged the Carolinas last week.</s>

<s docid="AP890928-0099" num="14" wdcount="13"> ``I figured they helped us, we should do something for them,'' Ford said.</s>

<s docid="AP890928-0099" num="15" wdcount="15"> On Wednesday, a local Red Cross chapter began collecting donations for victims of the hurricane.</s>

<s docid="AP890928-0099" num="16" wdcount="27"> ``A lot of people have been calling, asking to send donations down there,'' said Susan Lawlor, executive director of the Ulster County Chapter of the Red Cross.</s>

<s docid="AP890928-0099" num="17" wdcount="22"> On Tuesday, New York state sent two airplanes full of food, clothing and water to parts of the Caribbean ravaged by Hugo.</s>

<s docid="AP890928-0099" num="18" wdcount="23"> A New York National Guard C-5A cargo plane also left Tuesday to pick up equipment in Mississippi and take it to Puerto Rico.</s>

<s docid="AP890928-0099" num="19" wdcount="26"> Another cargo plane was scheduled to leave Stewart Air Force Base in Newburgh, taking 70 tons of food, water and other supplies to Puerto Rico .</s>
</TEXT>
</DOC>
