<DOC>
<DOCNO>

<s docid="AP890925-0054" num="1" wdcount="1"> AP890925-0054</s>
</DOCNO>
<FILEID>

<s docid="AP890925-0054" num="2" wdcount="2"> AP-NR-09-25-89 0631EDT</s>
</FILEID>
<FIRST>

<s docid="AP890925-0054" num="3" wdcount="5"> r a PM-Hugo-Readiness 09-25 0321</s>
</FIRST>
<SECOND>

<s docid="AP890925-0054" num="4" wdcount="1"> PM-Hugo-Readiness,0336</s>
</SECOND>
<HEAD>

<s docid="AP890925-0054" num="5" wdcount="8"> Loss Of Life Low Because People Were Prepared</s>
</HEAD>
<HEAD>

<s docid="AP890925-0054" num="6" wdcount="3"> With PM-Hugo Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP890925-0054" num="7" wdcount="3"> By BRUCE SMITH</s>
</BYLINE>
<BYLINE>

<s docid="AP890925-0054" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890925-0054" num="9" wdcount="3"> CHARLESTON, S.C. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890925-0054" num="10" wdcount="32"> Residents took forecasters at their word when they warned of Hurricane Hugo's fury, and the low number of deaths from the powerful storm can be credited to this healthy respect, authorities said.</s>

<s docid="AP890925-0054" num="11" wdcount="30"> The storm, which caused billions in damage, claimed 17 lives in South Carolina, and only two were in the Charleston area, which bore the brunt of Hugo's 135 mph winds.</s>

<s docid="AP890925-0054" num="12" wdcount="13"> ``We just feel very thankful about that,'' said Mayor Joseph P. Riley Jr.</s>

<s docid="AP890925-0054" num="13" wdcount="26"> ``Several thousands of people who were in the shelters and the tens of thousands of people who evacuated inland were potential victims of injury and death''.</s>

<s docid="AP890925-0054" num="14" wdcount="19"> Riley and other officials credited residents with monitoring the hurricane as it spun toward Charleston, and heeding evacuation warnings.</s>

<s docid="AP890925-0054" num="15" wdcount="21"> The last big storm to hit South Carolina was Hurricane David in 1979, which hit the coast after pounding southern Florida.</s>

<s docid="AP890925-0054" num="16" wdcount="20"> Since then several big storms have threatened but veered away, and officials were worried that Charlestonians wouldn't heed Hugo's warnings.</s>

<s docid="AP890925-0054" num="17" wdcount="16"> ``We've had so many close calls,'' said Gary Garnet, a meteorologist with the National Weather Service.</s>

<s docid="AP890925-0054" num="18" wdcount="9"> ``But this storm was very, very strong,'' he said.</s>

<s docid="AP890925-0054" num="19" wdcount="5"> ``This time they realized it''.</s>

<s docid="AP890925-0054" num="20" wdcount="20"> Glen Ellis, a Red Cross official, estimated that 18,000 residents in Charleston and the three surrounding counties headed for shelters.</s>

<s docid="AP890925-0054" num="21" wdcount="15"> Tens of thousands more got into their cars and headed up Interstate 26 toward Columbia.</s>

<s docid="AP890925-0054" num="22" wdcount="19"> Mayor John Bourne of North Charleston, where there apparently were no storm-related deaths, credited people for heeding the warnings.</s>

<s docid="AP890925-0054" num="23" wdcount="13"> ``It was bad, but it could have been a lot worse,'' he said.</s>

<s docid="AP890925-0054" num="24" wdcount="10"> ``You've just got to say nice things about the people''.</s>

<s docid="AP890925-0054" num="25" wdcount="20"> Meanwhile, Garnet had some good news for storm-weary Charlestonians: late Saturday the tropics were quiet with no other storms brewing.</s>

<s docid="AP890925-0054" num="26" wdcount="10"> ``There's nothing to worry about out there,'' he said .</s>
</TEXT>
</DOC>
