<DOC>
<DOCNO>

<s docid="AP890922-0007" num="1" wdcount="1"> AP890922-0007</s>
</DOCNO>
<FILEID>

<s docid="AP890922-0007" num="2" wdcount="2"> AP-NR-09-22-89 0022EDT</s>
</FILEID>
<FIRST>

<s docid="AP890922-0007" num="3" wdcount="7"> u a AM-Hugo 10thLd-Writethru a0404-5 09-22 0832</s>
</FIRST>
<SECOND>

<s docid="AP890922-0007" num="4" wdcount="6"> AM-Hugo, 10th Ld-Writethru, a0404-5, 2 Takes,0851</s>
</SECOND>
<HEAD>

<s docid="AP890922-0007" num="5" wdcount="1"> URGENT</s>
</HEAD>
<HEAD>

<s docid="AP890922-0007" num="6" wdcount="6"> Killer Storm Hits South Carolina Coast</s>
</HEAD>
<HEAD>

<s docid="AP890922-0007" num="7" wdcount="22"> Eds: LEADS with 17 grafs to UPDATE with eye passing just east of Charleston, 119 mph winds reported in city, other details.</s>

<s docid="AP890922-0007" num="8" wdcount="7"> Picks up 19th graf pvs, `Near its...'</s>
</HEAD>
<HEAD>

<s docid="AP890922-0007" num="9" wdcount="4"> LaserPhotos MH2, BEF1, LaserGraphic</s>
</HEAD>
<BYLINE>

<s docid="AP890922-0007" num="10" wdcount="3"> By BRUCE SMITH</s>
</BYLINE>
<BYLINE>

<s docid="AP890922-0007" num="11" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890922-0007" num="12" wdcount="3"> CHARLESTON, S.C. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890922-0007" num="13" wdcount="28"> Hurricane Hugo struck South Carolina with renewed fury Thursday after thousands of coastal residents in southeastern states grabbed what they could carry and fled inland on jammed highways.</s>

<s docid="AP890922-0007" num="14" wdcount="38"> ``This is a disaster staring us right in the eye,'' Mayor Joseph P. Riley Jr. said from his City Hall command post in Charleston, where the hurricane downed power lines, snapped trees and caused utility transformers to explode.</s>

<s docid="AP890922-0007" num="15" wdcount="28"> ``All we can do now is pray and hope all the precautions we have taken have been sufficient,'' Riley said as Hugo's eye bore in on the city.</s>

<s docid="AP890922-0007" num="16" wdcount="15"> ``I just hope and pray we can get through this without any loss of life''.</s>

<s docid="AP890922-0007" num="17" wdcount="9"> By midnight, 119 mph winds were reported in Charleston.</s>

<s docid="AP890922-0007" num="18" wdcount="25"> The roof cracked at City Hall, a 188-year-old brick building that has withstood several hurricanes, and torrents of water poured into the paneled council chamber.</s>

<s docid="AP890922-0007" num="19" wdcount="11"> Phone and electric service to the command post was knocked out.</s>

<s docid="AP890922-0007" num="20" wdcount="43"> Hurricane-force winds first hit the coast by 9:15 p.m. EDT, and about three hours later the eye of the storm passed over the Isle of Palms just east of Charleston, said Bob Sheets, director of the National Hurricane Center in Coral Gables, Fla.</s>

<s docid="AP890922-0007" num="21" wdcount="34"> The eye was about 10 miles across and top winds were still at 135 mph. Hugo was expected to turn gradually to the north, causing severe flooding as it moved up the East Coast.</s>

<s docid="AP890922-0007" num="22" wdcount="27"> The storm posed a 19 percent chance of hitting New York City and a 16 percent chance of hitting Boston before Sunday night, the hurricane center said.</s>

<s docid="AP890922-0007" num="23" wdcount="25"> As Hugo neared the coast, roads from Hilton Head to Myrtle Beach, 200 miles north, were nearly empty, as were the boarded-up resort towns themselves.</s>

<s docid="AP890922-0007" num="24" wdcount="13"> Power lines and trees were downed in some spots and water flooded roads.</s>

<s docid="AP890922-0007" num="25" wdcount="11"> Stop lights and neon lights were knocked out in Myrtle Beach.</s>

<s docid="AP890922-0007" num="26" wdcount="19"> ``One eyewitness said `It's like a light show,''' said Amy Garrison, a reporter at WKZQ AM-FM in Myrtle Beach.</s>

<s docid="AP890922-0007" num="27" wdcount="15"> In Charleston, the hurricane littered streets with tin roofs, palmetto fronds and chunks of bark.</s>

<s docid="AP890922-0007" num="28" wdcount="11"> Businesses were closed and classes at public schools and universities canceled.</s>

<s docid="AP890922-0007" num="29" wdcount="8"> Riley ordered residents of one-story homes to evacuate.</s>

<s docid="AP890922-0007" num="30" wdcount="24"> Hospitals stockpiled supplies, discharging any patients well enough to go and moving others to hospitals inland to make room for emergency patients, officials said.</s>

<s docid="AP890922-0007" num="31" wdcount="36"> About 12,000 people had checked into 83 shelters across the state as of Thursday evening, and more were expected, said Bennish Brown, a spokesman for the Emergency Operations Center in Columbia, 220 miles northwest of here.</s>

<s docid="AP890922-0007" num="32" wdcount="29"> ``We tried to close the doors but people are sneaking in side doors,'' said Elaine Skelton, a registered nurse working at the Conway High School shelter near Myrtle Beach.</s>

<s docid="AP890922-0007" num="33" wdcount="14"> ``We tried to post guards at the doors, but people were still coming in''.</s>

<s docid="AP890922-0007" num="34" wdcount="24"> American Red Cross relief efforts were buckling under the number of evacuees, said Brian Ruberry, a spokesman in Savannah, Ga., who appealed for help.</s>

<s docid="AP890922-0007" num="35" wdcount="17"> ``Right now the Red Cross is sheltering tens of thousands of people all along the Eastern seaboard.</s>

<s docid="AP890922-0007" num="36" wdcount="21"> This of course is at the same time that we're sheltering 25,000 people on Puerto Rico and the other Caribbean islands.</s>

<s docid="AP890922-0007" num="37" wdcount="6"> ``We're beginning to feel the squeeze.</s>

<s docid="AP890922-0007" num="38" wdcount="5"> Our resources are very tight.</s>

<s docid="AP890922-0007" num="39" wdcount="17"> Right now Hugo is shaping up to be one of our biggest relief operations of the decade''.</s>

<s docid="AP890922-0007" num="40" wdcount="19"> At midnight, the center of Hugo was near latitude 32.7 degrees north and longitude 79.9 degrees west, forecasters said.</s>

<s docid="AP890922-0007" num="41" wdcount="13"> The hurricane's speed had picked up to 22 mph from 20 mph earlier.</s>

<s docid="AP890922-0007" num="42" wdcount="24"> Near its center, Hugo's muscle reached winds of 135 mph, up from 125 mph earlier in the day and 105 mph the day before.</s>

<s docid="AP890922-0007" num="43" wdcount="20"> North and South Carolina can expect tornadoes linked to Hugo for the next two days, according to the hurricane center.</s>

<s docid="AP890922-0007" num="44" wdcount="20"> The coastal area could expect hurricane force winds for 10 to 12 hours once the eye comes ashore, officials said.</s>

<s docid="AP890922-0007" num="45" wdcount="14"> A hurricane warning was in effect between Fernandina Beach, Fla., and Oregon Inlet, N.C.</s>

<s docid="AP890922-0007" num="46" wdcount="28"> By late afternoon, Hugo was upgraded to a category 4 hurricane on the Saffir-Simpson scale of strength, the second mightiest category, which indicated it could cause extreme damage.</s>

<s docid="AP890922-0007" num="47" wdcount="23"> ``It strengthened more than we thought it would,'' Sheets said, adding that Hugo would cause severe flooding as it moved up the Appalachians.</s>

<s docid="AP890922-0007" num="48" wdcount="35"> The timing of the landfall was critical because of the storm's tidal surge, a dome of water 10 to 15 feet high that would feed a normal 5-foot high tide that peaks after 2 a.m.</s>

<s docid="AP890922-0007" num="49" wdcount="24"> ``On top of that will be waves,'' Sheets said earlier, and in many places on barrier islands ``the buildings will be swept clean off.''</s>
</TEXT>
<NOTE>

<s docid="AP890922-0007" num="50" wdcount="1"> MORE</s>
</NOTE>
</DOC>
