<DOC>
<DOCNO>

<s docid="AP890922-0119" num="1" wdcount="1"> AP890922-0119</s>
</DOCNO>
<FILEID>

<s docid="AP890922-0119" num="2" wdcount="2"> AP-NR-09-22-89 1300EDT</s>
</FILEID>
<FIRST>

<s docid="AP890922-0119" num="3" wdcount="5"> r a AM-Hugo-CityHall 09-22 0348</s>
</FIRST>
<SECOND>

<s docid="AP890922-0119" num="4" wdcount="2"> AM-Hugo-City Hall,0357</s>
</SECOND>
<HEAD>

<s docid="AP890922-0119" num="5" wdcount="8"> Officials Ride Out Storm In Historic City Hall</s>
</HEAD>
<HEAD>

<s docid="AP890922-0119" num="6" wdcount="3"> With AM-Hugo, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP890922-0119" num="7" wdcount="3"> By BRUCE SMITH</s>
</BYLINE>
<BYLINE>

<s docid="AP890922-0119" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890922-0119" num="9" wdcount="3"> CHARLESTON, S.C. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890922-0119" num="10" wdcount="23"> While Hurricane Hugo's 135 mph wind roared outside, Mayor Joseph P. Riley Jr. watched the fury it vented on his beloved, 300-year-old city.</s>

<s docid="AP890922-0119" num="11" wdcount="33"> Riley, city officials and a few reporters stayed in Charleston's historic City Hall through Thursday night as the area's worst hurricane in three decades pounded the coastal city where the Civil War began.</s>

<s docid="AP890922-0119" num="12" wdcount="11"> Late in the day, there was hope Hugo might spare Charleston.</s>

<s docid="AP890922-0119" num="13" wdcount="28"> But the storm gathered strength and speed as it spun straight toward this city, which had survived a number of near misses from great storms in recent years.</s>

<s docid="AP890922-0119" num="14" wdcount="22"> From the moment it became apparent Hugo might strike the Southeast coast, many Charlestonians conceded that, this time, their number was up.</s>

<s docid="AP890922-0119" num="15" wdcount="19"> As Hugo's wind howled outside the plywood boards protecting the windows, reporters wandered in and out of Riley's office.</s>

<s docid="AP890922-0119" num="16" wdcount="14"> On his desk several candles burned as insurance against the inevitable loss of power.</s>

<s docid="AP890922-0119" num="17" wdcount="29"> Later there was a sharp crack as a piece of the tin roof ripped off and water seeped down on the burnished wood tables in the City Council chamber.</s>

<s docid="AP890922-0119" num="18" wdcount="12"> Phone and electric service to the city command post was knocked out.</s>

<s docid="AP890922-0119" num="19" wdcount="13"> During it all, Riley kept in close contact with the National Weather Service.</s>

<s docid="AP890922-0119" num="20" wdcount="24"> As the eye of the storm passed, he took reporters onto the porch of the 188-year-old brick City Hall to look at the damage.</s>

<s docid="AP890922-0119" num="21" wdcount="27"> The initial view, sketched out in the glow of flashlights, was unsettling: The tin roof was tossed in the gutter, slate tiles were scattered on the ground.</s>

<s docid="AP890922-0119" num="22" wdcount="7"> Bricks, sticks and leaves littered the street.</s>

<s docid="AP890922-0119" num="23" wdcount="7"> ``This is the eye of the hurricane.</s>

<s docid="AP890922-0119" num="24" wdcount="15"> I've never been in one and I hope I'm never in one again,'' Riley said.</s>

<s docid="AP890922-0119" num="25" wdcount="6"> ``It's scarcely a late summer breeze''.</s>

<s docid="AP890922-0119" num="26" wdcount="27"> As the storm died before dawn, Riley was out on the streets again in a raincoat carrying a flashlight to get a better assessment of the damage.</s>

<s docid="AP890922-0119" num="27" wdcount="7"> ``Serious but fixable,'' the mayor concluded .</s>
</TEXT>
</DOC>
