<DOC>
<DOCNO>

<s docid="LA092789-0093" num="1" wdcount="1"> LA092789-0093</s>
</DOCNO>
<DOCID>

<s docid="LA092789-0093" num="2" wdcount="1"> 112961</s>
</DOCID>
<DATE>
<P>

<s docid="LA092789-0093" num="3" wdcount="6"> September 27, 1989, Wednesday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA092789-0093" num="4" wdcount="9"> Business; Part 4; Page 1; Column 5; Financial Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA092789-0093" num="5" wdcount="2"> 686 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA092789-0093" num="6" wdcount="8"> HURRICANE HUGO MAY BE MOST COSTLY STORM EVER;</s>
</P>
<P>

<s docid="LA092789-0093" num="7" wdcount="10"> 2 BIGGEST INSURERS IN CAROLINAS ESTIMATING LOSSES AT $600 MILLION</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA092789-0093" num="8" wdcount="6"> By LINDA WILLIAMS, Times Staff Writer</s>
</P>
</BYLINE>
<TEXT>
<P>

<s docid="LA092789-0093" num="9" wdcount="27"> The two dominant home and automobile insurers in the Carolinas said Tuesday that they expect to be hit with about $600 million in claims from Hurricane Hugo.</s>

<s docid="LA092789-0093" num="10" wdcount="18"> Such heavy losses suggest that the storm will be the most expensive ever for the insurance industry .</s>
</P>
<P>

<s docid="LA092789-0093" num="11" wdcount="27"> State Farm Insurance Co. expects claims as high as $400 million in South Carolina, where it insures one out of every five homes, spokesman Jerry Parsons said.</s>

<s docid="LA092789-0093" num="12" wdcount="24"> The Bloomington, Ill.-based company is also projecting an additional $100 million in claims from storm damage in North Carolina and Virginia, he said .</s>
</P>
<P>

<s docid="LA092789-0093" num="13" wdcount="39"> Additionally, Nationwide Insurance Co. said it expects claims close to $100 million, more than triple the $31 million that the company paid for damages caused by Hurricane Elena when it swept through Florida, Alabama and Mississippi in 1985 .</s>
</P>
<P>

<s docid="LA092789-0093" num="14" wdcount="23"> "Our previous all-time high was in 1983, when we paid $165 million in comparable claims for Hurricane Alicia, which struck Galveston and Houston.</s>

<s docid="LA092789-0093" num="15" wdcount="23"> There were a phenomenal number of claims from that storm, but there was not the severity of damage" as in Hugo, Parsons said.</s>

<s docid="LA092789-0093" num="16" wdcount="34"> Officials said property damage from Hugo escalated because the storm scored a direct hit on Charleston and then, instead of heading out to sea, veered northwest, hitting other population centers, including Charlotte, N.C .</s>
</P>
<P>
</P>
<P>

<s docid="LA092789-0093" num="17" wdcount="4"> Losses Still Being Tallied</s>
</P>
<P>

<s docid="LA092789-0093" num="18" wdcount="28"> Nationwide, based in Columbus, Ohio, is the biggest home and auto insurance in North Carolina, where damage was unexpectedly high, and is the third-largest insurer in South Carolina.</s>

<s docid="LA092789-0093" num="19" wdcount="12"> "We have so far received 16,000 claims," spokesman Bob Sohozich said .</s>
</P>
<P>

<s docid="LA092789-0093" num="20" wdcount="44"> Although claims adjusters are still tallying the losses, there is now little doubt that overall damage to insured property will far exceed the record $752.5 million in claims paid by the industry after Hurricane Frederic struck Mississippi and Alabama in 1979, Parsons said .</s>
</P>
<P>

<s docid="LA092789-0093" num="21" wdcount="17"> The Insurance Information Institute is expected to issue a report Thursday on overall insured losses from Hugo.</s>

<s docid="LA092789-0093" num="22" wdcount="29"> Although the losses are substantial, they are not expected to threaten the financial health of any individual company because reinsurers will pick up a significant portion of the costs.</s>

<s docid="LA092789-0093" num="23" wdcount="26"> For example, Nationwide said it would be responsible for up to $30 million in claims, while its reinsurers would cover up to $150 million in damages.</s>

<s docid="LA092789-0093" num="24" wdcount="32"> Reinsurers -- which share a portion of the risk on an insurance policy in exchange for part of the premium income -- typically spread their risk over many hundreds of companies .</s>
</P>
<P>

<s docid="LA092789-0093" num="25" wdcount="38"> Analysts said most of the claims will be borne by mutual insurance companies, which are owned by policyholders, but they noted that losses from Hurricane Hugo would also affect the short-term earnings of some publicly traded companies .</s>
</P>
<P>

<s docid="LA092789-0093" num="26" wdcount="26"> Continental Corp. said it expects to report a pretax charge of $50 million for the third quarter, reflecting its net exposure to damages from the storm.</s>

<s docid="LA092789-0093" num="27" wdcount="22"> The New York-based company had substantial business in Puerto Rico and the Virgin Islands, where Hugo first struck with devastating force .</s>
</P>
<P>
</P>
<P>

<s docid="LA092789-0093" num="28" wdcount="4"> Forecasts May Be Cut</s>
</P>
<P>

<s docid="LA092789-0093" num="29" wdcount="23"> The charge might push Continental into the red for the quarter, said Udayan Ghose, an analyst with Shearson Lehman Hutton in New York.</s>

<s docid="LA092789-0093" num="30" wdcount="14"> "If there is a profit, it will be a very small one," he said.</s>

<s docid="LA092789-0093" num="31" wdcount="14"> The charge will cut expected annual earnings by close to 25%, he added .</s>
</P>
<P>

<s docid="LA092789-0093" num="32" wdcount="37"> Ghose said Shearson may also cut its third-quarter and annual earnings projections for Cigna Corp., USF&G Corp. and Lincoln National Corp., which are expected to suffer hurricane-related losses equal to about 10% of expected full-year earnings .</s>
</P>
<P>

<s docid="LA092789-0093" num="33" wdcount="22"> Overall 1989 catastrophic losses for the industry now total about $1.6 billion, and analysts expect Hugo to make this year the costliest.</s>

<s docid="LA092789-0093" num="34" wdcount="27"> But "this could be a positive for the industry," Ghose said, explaining that the industry is in the middle of a price war because it is overcapitalized.</s>

<s docid="LA092789-0093" num="35" wdcount="30"> Billions of dollars in losses from Hugo and other catastrophes this year would have "a significant impact on excess capital," he said, causing insurance firms to raise prices shortly .</s>
</P>
<P>

<s docid="LA092789-0093" num="36" wdcount="12"> "That would be good for the companies and shareholders," he said .</s>
</P>
</TEXT>
<SUBJECT>
<P>

<s docid="LA092789-0093" num="37" wdcount="42"> HURRICANES; STORMS -- SOUTH CAROLINA; HOMEOWNERS INSURANCE; AUTOMOBILE INSURANCE; NATIONWIDE LIFE INSURANCE CO; CONTINENTAL CORP; DISASTERS; PROPERTY DAMAGE; INSURANCE CLAIMS; STORMS -- NORTH CAROLINA; STATE FARM FIRE & CASUALTY CO; STORMS -- PUERTO RICO; STORMS -- VIRGIN ISLANDS OF THE UNITED STATES</s>
</P>
</SUBJECT>
</DOC>
