<DOC>
<DOCNO>

<s docid="LA092189-0225" num="1" wdcount="1"> LA092189-0225</s>
</DOCNO>
<DOCID>

<s docid="LA092189-0225" num="2" wdcount="1"> 110563</s>
</DOCID>
<DATE>
<P>

<s docid="LA092189-0225" num="3" wdcount="6"> September 21, 1989, Thursday, P.M. Final</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA092189-0225" num="4" wdcount="9"> Part A; Page 1; Column 6; Late Final Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA092189-0225" num="5" wdcount="2"> 503 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA092189-0225" num="6" wdcount="9"> 150,000 TAKE OFF AS HUGO TAKES AIM AT GA.</s>

<s docid="LA092189-0225" num="7" wdcount="2"> , CAROLINA;</s>
</P>
<P>

<s docid="LA092189-0225" num="8" wdcount="8"> HURRICANE'S EDGE TO HIT AT 8 P.M .</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA092189-0225" num="9" wdcount="3"> From Associated Press</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA092189-0225" num="10" wdcount="3"> CHARLESTON, S.C .</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA092189-0225" num="11" wdcount="30"> Hurricane Hugo advanced faster and with renewed fury today on Georgia and South Carolina as 150,000 coastal residents grabbed what they could carry and fled inland on jammed highways .</s>
</P>
<P>

<s docid="LA092189-0225" num="12" wdcount="37"> "We're not going to take any chances," said Lamar Davis, a bartender on St. Simons Island off southern Georgia, who stole a last glance at the pounding surf before leaving with his wife and 4-year-old daughter .</s>
</P>
<P>

<s docid="LA092189-0225" num="13" wdcount="35"> The leading edge of Hugo, whose winds muscled up to 125 m.p.h. from 105 m.p.h. the day before, was most likely to hit between Savannah, Ga., and Charleston any time after 8 p.m., local time.</s>

<s docid="LA092189-0225" num="14" wdcount="15"> A hurricane warning was in effect between Fernandina Beach, Fla., and Oregon Inlet, N.C .</s>
</P>
<P>

<s docid="LA092189-0225" num="15" wdcount="15"> At 3 p.m., Hugo was 220 miles from Savannah and bearing down at 20 m.p.h.</s>

<s docid="LA092189-0225" num="16" wdcount="16"> It was expected to turn gradually to the north, according to the National Weather Service .</s>
</P>
<P>
</P>
<P>

<s docid="LA092189-0225" num="17" wdcount="3"> Tidal Surge Feared</s>
</P>
<P>

<s docid="LA092189-0225" num="18" wdcount="35"> The timing of the landfall was critical because of the storm's tidal surge, a dome of water 10 to 15 feet high that would feed a normal 5-foot tide that peaks after 2 a.m .</s>
</P>
<P>

<s docid="LA092189-0225" num="19" wdcount="42"> "On top of that will be waves, and so (on) . . . barrier islands (in) many places the buildings will be swept clean off of those islands," Bob Sheets, director of the National Hurricane Center, said from Coral Gables, Fla .</s>
</P>
<P>

<s docid="LA092189-0225" num="20" wdcount="16"> Evacuees queued up at gasoline stations and stripped store shelves of bottled water, bread and batteries.</s>

<s docid="LA092189-0225" num="21" wdcount="18"> Officials warned coastal dwellers not to linger because gale force winds and flash floods could block escape routes.</s>

<s docid="LA092189-0225" num="22" wdcount="9"> Five to 10 inches of rain is expected .</s>
</P>
<P>

<s docid="LA092189-0225" num="23" wdcount="15"> The Navy moved ships out of coastal harbors to ride out the storm at sea.</s>

<s docid="LA092189-0225" num="24" wdcount="12"> Army bases in coastal states moved helicopters inland or into shelters .</s>
</P>
<P>

<s docid="LA092189-0225" num="25" wdcount="28"> In South Carolina, which was in a state of emergency, Gov. Carroll Campbell dispatched 400 National Guardsmen to assist a mandatory evacuation of coastal barrier islands and shorefront.</s>

<s docid="LA092189-0225" num="26" wdcount="14"> About one-fifth of the state's 3.1 million residents live in eight coastal counties .</s>
</P>
<P>
</P>
<P>

<s docid="LA092189-0225" num="27" wdcount="3"> Resort Streets Deserted</s>
</P>
<P>

<s docid="LA092189-0225" num="28" wdcount="15"> By early afternoon, the wind-swept streets of the resort island of Hilton Head were deserted.</s>

<s docid="LA092189-0225" num="29" wdcount="11"> Store windows were fortified with boards and most homes were empty.</s>

<s docid="LA092189-0225" num="30" wdcount="7"> State troopers guarded the island's entrance .</s>
</P>
<P>

<s docid="LA092189-0225" num="31" wdcount="29"> "We brought our photo albums and our important papers," said Pat Bross, who had stopped for gas while heading from Hilton Head to Augusta, Ga., with her husband .</s>
</P>
<P>

<s docid="LA092189-0225" num="32" wdcount="26"> The Georgia Emergency Management Agency opened shelters and advised about 142,000 people -- more than 95,000 of them in Chatham County -- to leave their homes.</s>

<s docid="LA092189-0225" num="33" wdcount="13"> Gov. Joe Frank Harris declared a state of emergency in six counties .</s>
</P>
<P>

<s docid="LA092189-0225" num="34" wdcount="33"> The state's biggest shelters were opened at Georgia Southern College in Statesboro, with room for 15,500, and the Veterans Administration Medical Center in Dublin, where officials said nearly 19,000 could be housed .</s>
</P>
<P>

<s docid="LA092189-0225" num="35" wdcount="12"> Coastal school systems canceled classes for the rest of the week .</s>
</P>
<P>

<s docid="LA092189-0225" num="36" wdcount="25"> Hugo was upgraded to a Category 3 hurricane on the Saffir-Simpson scale of strength, indicating that it was powerful enough to cause extensive damage .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA092189-0225" num="37" wdcount="15"> Photo, Residents heading inland to flee hurricane are bumper to bumper leaving Charleston, S.C., today.</s>

<s docid="LA092189-0225" num="38" wdcount="2"> Associated Press</s>
</P>
</GRAPHIC>
<TYPE>
<P>

<s docid="LA092189-0225" num="39" wdcount="1"> Wire</s>
</P>
</TYPE>
</DOC>
