<DOC>
<DOCNO>

<s docid="WSJ890928-0084" num="1" wdcount="1"> WSJ890928-0084</s>
</DOCNO>
<DD>

<s docid="WSJ890928-0084" num="2" wdcount="2"> = 890928</s>
</DD>
<AN>

<s docid="WSJ890928-0084" num="3" wdcount="2"> 890928-0084 .</s>
</AN>
<HL>

<s docid="WSJ890928-0084" num="4" wdcount="22"> Several Insurers' Net @ To Be Cut in Quarter @ By Hurricane Hugo @ ---- @ A Wall Street Journal News Roundup</s>
</HL>
<DD>

<s docid="WSJ890928-0084" num="5" wdcount="1"> 09/28/89</s>
</DD>
<SO>

<s docid="WSJ890928-0084" num="6" wdcount="4"> WALL STREET JOURNAL (J)</s>
</SO>
<CO>

<s docid="WSJ890928-0084" num="7" wdcount="3"> AIG STPL CI</s>
</CO>
<IN>

<s docid="WSJ890928-0084" num="8" wdcount="2"> INSURANCE (INS)</s>
</IN>
<TEXT>

<s docid="WSJ890928-0084" num="9" wdcount="21"> Damage from Hurricane Hugo, which stormed through the Carolinas and the Caribbean last week, will reduce third-quarter earnings for several insurers.</s>

<s docid="WSJ890928-0084" num="10" wdcount="22"> New York-based American International Group Inc. expects net losses related to Hugo to reduce pretax earnings between $35 million and $45 million.</s>

<s docid="WSJ890928-0084" num="11" wdcount="29"> Analysts said AIG has told them that it must cover the first $35 million of losses and that its reinsurance agreements will cover the bulk of the remaining damages.</s>

<s docid="WSJ890928-0084" num="12" wdcount="17"> AIG insured property in Puerto Rico, the eastern Caribbean Islands and the coastal regions of the Carolinas.</s>

<s docid="WSJ890928-0084" num="13" wdcount="18"> St. Paul Cos., based in St. Paul, Minn, said the pretax cost of Hugo shouldn't exceed $50 million.</s>

<s docid="WSJ890928-0084" num="14" wdcount="18"> That amount takes into consideration what St. Paul expects to recover under its reinsurance contracts, the company said.</s>

<s docid="WSJ890928-0084" num="15" wdcount="15"> Philadelphia-based Cigna Corp. is expected to disclose Hugo's likely impact on its earnings sometime today.</s>

<s docid="WSJ890928-0084" num="16" wdcount="35"> Udayan Ghose, an insurance industry analyst at Shearson Lehman Hutton in New York, estimates that Cigna's third-quarter per-share earnings could be reduced by between 50 cents and 65 cents a share on an after-tax basis.</s>

<s docid="WSJ890928-0084" num="17" wdcount="16"> That would wipe out 35% to 40% of his $1.40-a-share earnings estimate for the third quarter.</s>

<s docid="WSJ890928-0084" num="18" wdcount="37"> State Farm Mutual Automobile Insurance Co. said its State Fire & Casualty Co. unit estimates claim payments from Hugo will exceed $400 million in South Carolina alone, far surpassing the company's record payout for a single disaster.</s>

<s docid="WSJ890928-0084" num="19" wdcount="18"> When damages in North Carolina and Virginia are added, the company said, the payments will exceed $500 million.</s>

<s docid="WSJ890928-0084" num="20" wdcount="27"> It said that is more than three times the previous record of $165 million set by Hurricane Alicia, which hit the Houston-Galveston, Texas, area in 1983 .</s>
</TEXT>
</DOC>
