<DOC>
<DOCNO>

<s docid="WSJ890927-0018" num="1" wdcount="1"> WSJ890927-0018</s>
</DOCNO>
<DD>

<s docid="WSJ890927-0018" num="2" wdcount="2"> = 890927</s>
</DD>
<AN>

<s docid="WSJ890927-0018" num="3" wdcount="2"> 890927-0018 .</s>
</AN>
<HL>

<s docid="WSJ890927-0018" num="4" wdcount="30"> Hugo to Be Costliest Storm for Insurers @ But No Early Rate Increase Is Expected @ ---- @ By Beatrice E. Garcia @ Staff Reporter of The Wall Street Journal</s>
</HL>
<DD>

<s docid="WSJ890927-0018" num="5" wdcount="1"> 09/27/89</s>
</DD>
<SO>

<s docid="WSJ890927-0018" num="6" wdcount="4"> WALL STREET JOURNAL (J)</s>
</SO>
<CO>

<s docid="WSJ890927-0018" num="7" wdcount="7"> CIC CI FG TIC AET CB NIEX</s>
</CO>
<IN>

<s docid="WSJ890927-0018" num="8" wdcount="2"> INSURANCE (INS)</s>
</IN>
<TEXT>

<s docid="WSJ890927-0018" num="9" wdcount="33"> Hurricane Hugo will go down in the record books as the costliest storm insurers have faced so far, but it won't cause property-casualty premium rates to rise immediately, analysts and company officials say.</s>

<s docid="WSJ890927-0018" num="10" wdcount="25"> The property claims service division of the American Insurance Service Group, a trade association, is expected to announce its estimate of total insured losses tomorrow.</s>

<s docid="WSJ890927-0018" num="11" wdcount="30"> "Hugo will be the biggest hurricane loss on record," said one official, far surpassing the $752.5 million insurers paid out after Frederick ripped through several Gulf Coast states in 1979.</s>

<s docid="WSJ890927-0018" num="12" wdcount="28"> The impact on premium rates could be minimal for now, analysts expect, because the biggest losses will be in the personal insurance area -- for homes and autos.</s>

<s docid="WSJ890927-0018" num="13" wdcount="23"> Most companies typically set aside funds from premiums they collect every year to cover claims they might have to pay in the future.</s>

<s docid="WSJ890927-0018" num="14" wdcount="22"> In the last three years, hurricane and storm seasons have been relatively mild, so insurers haven't had to dip into these funds.</s>

<s docid="WSJ890927-0018" num="15" wdcount="21"> And since Hugo also stormed through the Caribbean, foreign insurers are at risk for some of the damage on those islands.</s>

<s docid="WSJ890927-0018" num="16" wdcount="33"> Yet, some analysts believe Hugo's huge losses will make a dent in the industry's capital and crimp cash flow; that could make insurers less likely to slash premium rates further in coming months.</s>

<s docid="WSJ890927-0018" num="17" wdcount="7"> Rates have been falling since late 1986.</s>

<s docid="WSJ890927-0018" num="18" wdcount="18"> Udayan Ghose at Shearson Lehman Hutton Inc. believes these reasons might cause rates to edge higher by mid-1990.</s>

<s docid="WSJ890927-0018" num="19" wdcount="39"> For the time being, the losses from Hugo "will be substantial, but they won't be something the industry can't handle," said Charles L. Ruoff, director of strategic planning at Fred S. James & Co., a New York-based insurance broker.</s>

<s docid="WSJ890927-0018" num="20" wdcount="25"> For instance, State Farm Mutual Automobile Insurance Co. estimates it will pay claims totaling more than $400 million to homeowners and for some small businesses.</s>

<s docid="WSJ890927-0018" num="21" wdcount="25"> Nationwide Insurance Co., a mutual company based in Columbus, Ohio, said Hugo "is the single largest claims disaster" it has seen in its 63-year history.</s>

<s docid="WSJ890927-0018" num="22" wdcount="28"> The company, which is the largest home and auto insurer in North Carolina and No. 3 in South Carolina, has already received 16,000 claims from the stricken region.</s>

<s docid="WSJ890927-0018" num="23" wdcount="8"> Claims could total $100 million, a spokesman said.</s>

<s docid="WSJ890927-0018" num="24" wdcount="7"> For some insurers, Hugo was a double-whammy.</s>

<s docid="WSJ890927-0018" num="25" wdcount="42"> New York-based Continental Corp., which is a big insurer in Puerto Rico, the Virgin Islands and South Carolinas, said it will take a $50 million pretax charge against earnings this quarter, reflecting its net exposure to the damages caused by the hurricane.</s>

<s docid="WSJ890927-0018" num="26" wdcount="10"> "Hugo will be particularly costly to us," said John P.</s>

<s docid="WSJ890927-0018" num="27" wdcount="3"> Mascotte, Continental's chairman.</s>

<s docid="WSJ890927-0018" num="28" wdcount="41"> Philadelphia-based Cigna Corp., which has extensive domestic, foreign and reinsurance operations in the areas Hugo hit, and USF&G Corp. in Baltimore, a big insurer in the Carolina region, could also be forced to take one-time charges against third-quarter earnings, analysts said.</s>

<s docid="WSJ890927-0018" num="29" wdcount="17"> Some of USF&G's losses hit very close home -- its Charleston office was destroyed by the hurricane.</s>

<s docid="WSJ890927-0018" num="30" wdcount="36"> Both USF&G and Cigna declined to predict whether they would take a charge; USF&G said it would be responsible for the first $22.5 million of losses, and its reinsurance would cover the bulk of additional losses.</s>

<s docid="WSJ890927-0018" num="31" wdcount="25"> Hugo could have a marginal impact on third-quarter income at Travelers Corp., Aetna Life & Casualty Insurance Co. and Chubb Corp., according to industry analysts.</s>

<s docid="WSJ890927-0018" num="32" wdcount="43"> Mr. Ruoff at Fred S. James believes that even if losses from Hugo total as much as $5 billion, insurers won't feel enough "financial pain, such as not being able to pay shareholder dividends," to compel them to boost premium rates right away.</s>

<s docid="WSJ890927-0018" num="33" wdcount="33"> He explained that in the first six months of this year, net income for the industry declined slightly from 1988, but insurance companies were still earning an adequate rate of return on equity.</s>

<s docid="WSJ890927-0018" num="34" wdcount="19"> He also noted that the industry's aggregate net worth or policyholders' surplus, currently at $125 billion, is also plentiful.</s>

<s docid="WSJ890927-0018" num="35" wdcount="13"> Generally, insurers can book about $3 of premiums for every $1 of surplus.</s>

<s docid="WSJ890927-0018" num="36" wdcount="9"> Right now, premiums total about $200 billion, he said.</s>

<s docid="WSJ890927-0018" num="37" wdcount="21"> An official at Nationwide Insurance noted that the company has $1 of surplus for every $2 of insurance that it writes.</s>

<s docid="WSJ890927-0018" num="38" wdcount="23"> Insurers also buy protection for themselves through reinsurance by paying another company a portion of the premium to bear some of the losses.</s>

<s docid="WSJ890927-0018" num="39" wdcount="19"> Michael Lewis at Dean Witter Reynolds said losses from Hugo could be big enough to "temporarily" increase reinsurance rates.</s>

<s docid="WSJ890927-0018" num="40" wdcount="19"> Although reinsurance will limit the exposure of some companies, the losses they must still cover could hurt third-quarter results.</s>

<s docid="WSJ890927-0018" num="41" wdcount="43"> Niagara Exchange Corp., based in Buffalo, N.Y., said Monday it will report a loss from operations for the third quarter, and possibly for the year, because of the substantial losses that its Charleston Insurance Co. unit faces as a result of the hurricane.</s>

<s docid="WSJ890927-0018" num="42" wdcount="10"> State Farm, the nation's largest home insurer, doesn't buy reinsurance.</s>

<s docid="WSJ890927-0018" num="43" wdcount="15"> It believes its reserves are plentiful enough to absorb its losses, a spokesman said .</s>
</TEXT>
</DOC>
