<DOC>
<DOCNO>

<s docid="AP880217-0100" num="1" wdcount="1"> AP880217-0100</s>
</DOCNO>
<FILEID>

<s docid="AP880217-0100" num="2" wdcount="2"> AP-NR-02-17-88 1039EST</s>
</FILEID>
<FIRST>

<s docid="AP880217-0100" num="3" wdcount="5"> r a PM-Oscar-Vitals 02-17 0202</s>
</FIRST>
<SECOND>

<s docid="AP880217-0100" num="4" wdcount="1"> PM-Oscar-Vitals,0207</s>
</SECOND>
<HEAD>

<s docid="AP880217-0100" num="5" wdcount="6"> Statistics on Six Decades of Oscar</s>
</HEAD>
<HEAD>

<s docid="AP880217-0100" num="6" wdcount="4"> With PM-Oscar Nominations Bjt</s>
</HEAD>
<DATELINE>

<s docid="AP880217-0100" num="7" wdcount="3"> LOS ANGELES (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880217-0100" num="8" wdcount="23"> The motion picture industry's most coveted award, Oscar, was created 60 years ago and 1,816 of the statuettes have been produced so far.</s>

<s docid="AP880217-0100" num="9" wdcount="27"> Weighing 8 pounds and standing 13 inches tall, Oscar was created by Metro-Goldwyn-Mayer studios art director Cedric Gibbons, who went on to win 11 of the trophies.</s>

<s docid="AP880217-0100" num="10" wdcount="20"> Oscar, manufactured by the R.S. Owens Co., Chicago, is made of Britannia metal, copper plate, nickel plate and gold plate.</s>

<s docid="AP880217-0100" num="11" wdcount="19"> From 1942 to 1944, the trophy was made of plaster, but winners were later presented with the real thing.</s>

<s docid="AP880217-0100" num="12" wdcount="34"> According to the Academy of Motion Pictures Arts and Sciences, the only engraving mistake was in 1938 when the best actor trophy given to Spencer Tracy for ``Boy's Town'' read: ``Best Actor: Dick Tracy''.</s>

<s docid="AP880217-0100" num="13" wdcount="31"> The Academy holds all the rights on the statue and ``reserves the right to buy back an Oscar before someone takes it to a pawn shop,'' said Academy spokesman Bob Werden.</s>

<s docid="AP880217-0100" num="14" wdcount="9"> The most-nominated film was ``All About Eve'' in 1950.</s>

<s docid="AP880217-0100" num="15" wdcount="4"> It got 14 nominations.</s>

<s docid="AP880217-0100" num="16" wdcount="19"> ``Ben-Hur'' in 1959 was the most-awarded film with 11, and Walt Disney was the most-awarded person with 32 .</s>
</TEXT>
</DOC>
