<DOC>
<DOCNO>

<s docid="AP880328-0206" num="1" wdcount="1"> AP880328-0206</s>
</DOCNO>
<FILEID>

<s docid="AP880328-0206" num="2" wdcount="2"> AP-NR-03-28-88 1345EST</s>
</FILEID>
<FIRST>

<s docid="AP880328-0206" num="3" wdcount="6"> s e BC-APN--Oscars-Questions Adv10 03-28 0411</s>
</FIRST>
<SECOND>

<s docid="AP880328-0206" num="4" wdcount="3"> BC-APN--Oscars-Questions, Adv 10,0432</s>
</SECOND>
<NOTE>

<s docid="AP880328-0206" num="5" wdcount="1"> $adv10</s>
</NOTE>
<HEAD>

<s docid="AP880328-0206" num="6" wdcount="4"> AGENCIES AND RADIO OUT</s>
</HEAD>
<NOTE>

<s docid="AP880328-0206" num="7" wdcount="5"> For Release Sunday, April 10</s>
</NOTE>
<HEAD>

<s docid="AP880328-0206" num="8" wdcount="3"> From AP Newsfeatures</s>
</HEAD>
<HEAD>

<s docid="AP880328-0206" num="9" wdcount="2"> With BC-APN-Oscars</s>
</HEAD>
<TEXT>

<s docid="AP880328-0206" num="10" wdcount="32"> HOLLYWOOD (AP) _ Like all great contests, the annual Academy Awards ceremony has generated a wealth of statistics and trivia over its 60 years of existence, all carefully chronicled by Oscar historians.</s>

<s docid="AP880328-0206" num="11" wdcount="17"> Here, courtesy of the Academy of Motion Picture Arts and Sciences, are 20 questions about Oscar: 1.</s>

<s docid="AP880328-0206" num="12" wdcount="7"> What actress has received the most Oscars?</s>

<s docid="AP880328-0206" num="13" wdcount="3"> Katharine Hepburn, 4.</s>

<s docid="AP880328-0206" num="14" wdcount="11"> 2. What actor has received the most Oscars? Walter Brennan, 3.</s>

<s docid="AP880328-0206" num="15" wdcount="11"> 3. What director has received the most Oscars? John Ford, 4.</s>

<s docid="AP880328-0206" num="16" wdcount="7"> 4. Who is the most nominated actress?</s>

<s docid="AP880328-0206" num="17" wdcount="3"> Katharine Hepburn, 12.</s>

<s docid="AP880328-0206" num="18" wdcount="7"> 5. Who is the most nominated actor?</s>

<s docid="AP880328-0206" num="19" wdcount="3"> Laurence Olivier, 10.</s>

<s docid="AP880328-0206" num="20" wdcount="10"> 6. Who is the most nominated director? William Wyler, 12.</s>

<s docid="AP880328-0206" num="21" wdcount="14"> 7. How long was the longest Oscar ceremony? 3 hours, 45 minutes in 1985.</s>

<s docid="AP880328-0206" num="22" wdcount="8"> 8. What film has won the most Oscars?</s>

<s docid="AP880328-0206" num="23" wdcount="3"> ``Ben-Hur,'' 11, 1959.</s>

<s docid="AP880328-0206" num="24" wdcount="7"> 9. What was the most nominated picture?</s>

<s docid="AP880328-0206" num="25" wdcount="15"> ``Gone With The Wind,'' ``Mary Poppins'' and ``Who's Afraid of Virginia Woolf,'' each with 13.</s>

<s docid="AP880328-0206" num="26" wdcount="8"> 10. What studio has won the most Oscars?</s>

<s docid="AP880328-0206" num="27" wdcount="4"> MGM, with nearly 200.</s>

<s docid="AP880328-0206" num="28" wdcount="10"> 11. Who was the youngest performer to win an Oscar?</s>

<s docid="AP880328-0206" num="29" wdcount="8"> Tatum O'Neal, 10, supporting actress, ``Paper Moon,'' 1973.</s>

<s docid="AP880328-0206" num="30" wdcount="19"> 12. Who was the oldest performer ever to win an Oscar? Groucho Marx, 83, an honorary award in 1974.</s>

<s docid="AP880328-0206" num="31" wdcount="19"> George Burns is the oldest actor to win a performing Oscar, 80, for the ``The Sunshine Boys'' in 1976.</s>

<s docid="AP880328-0206" num="32" wdcount="11"> 13. What actor won a posthumous award? Peter Finch, ``Network,'' 1976.</s>

<s docid="AP880328-0206" num="33" wdcount="24"> 14. What father-son team won Oscars in the same picture? Walter Huston, supporting actor, and John Huston, director-writer, ``The Treasure of Sierra Madre,'' 1948.</s>

<s docid="AP880328-0206" num="34" wdcount="12"> 15. What actor was nominated in two categories for the same role?</s>

<s docid="AP880328-0206" num="35" wdcount="6"> Barry Fitzgerald, ``Going My Way,'' 1944.</s>

<s docid="AP880328-0206" num="36" wdcount="6"> He won in the supporting category.</s>

<s docid="AP880328-0206" num="37" wdcount="10"> 16. Who decapitated his Oscar while practicing golf swings indoors?</s>

<s docid="AP880328-0206" num="38" wdcount="2"> Barry Fitzgerald.</s>

<s docid="AP880328-0206" num="39" wdcount="11"> His 1944 supporting actor statuette was subsequently replaced by the Academy.</s>

<s docid="AP880328-0206" num="40" wdcount="13"> 17. What performers have refused their Oscars? George C. Scott and Marlon Brando.</s>

<s docid="AP880328-0206" num="41" wdcount="10"> 18. How many people view the Oscar ceremony on television?</s>

<s docid="AP880328-0206" num="42" wdcount="13"> Last year, the Oscarcast was seen by one billion people in 79 countries.</s>

<s docid="AP880328-0206" num="43" wdcount="15"> 19. Who holds the record for the fastest televised reading of the famed Academy rules?</s>

<s docid="AP880328-0206" num="44" wdcount="8"> Actor-comedian John (Federal Express) Moschitta, 25 seconds, 1983.</s>

<s docid="AP880328-0206" num="45" wdcount="12"> 20. What multiple Oscar winner has never appeared to collect her award?</s>

<s docid="AP880328-0206" num="46" wdcount="6"> Katharine Hepburn, all four times .</s>
</TEXT>
<NOTE>

<s docid="AP880328-0206" num="47" wdcount="6"> END ADV for Sunday, April 10</s>
</NOTE>
</DOC>
