<DOC>
<DOCNO>

<s docid="AP880325-0239" num="1" wdcount="1"> AP880325-0239</s>
</DOCNO>
<FILEID>

<s docid="AP880325-0239" num="2" wdcount="2"> AP-NR-03-25-88 0908EST</s>
</FILEID>
<FIRST>

<s docid="AP880325-0239" num="3" wdcount="6"> a e AM-APArts:Oscars-Overlooked Adv28 03-25 0704</s>
</FIRST>
<SECOND>

<s docid="AP880325-0239" num="4" wdcount="5"> AM-AP Arts: Oscars-Overlooked, Adv 28,0723</s>
</SECOND>
<NOTE>

<s docid="AP880325-0239" num="5" wdcount="1"> $Adv28</s>
</NOTE>
<NOTE>

<s docid="AP880325-0239" num="6" wdcount="8"> For Release Mon AMs, March 28 and Thereafter</s>
</NOTE>
<HEAD>

<s docid="AP880325-0239" num="7" wdcount="4"> Oscar Countdown: The Overlooked</s>
</HEAD>
<HEAD>

<s docid="AP880325-0239" num="8" wdcount="7"> Oscar Snubs The Best and The Brightest</s>
</HEAD>
<BYLINE>

<s docid="AP880325-0239" num="9" wdcount="3"> By BOB THOMAS</s>
</BYLINE>
<BYLINE>

<s docid="AP880325-0239" num="10" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880325-0239" num="11" wdcount="2"> HOLLYWOOD (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880325-0239" num="12" wdcount="16"> What do Charlie Chaplin, Greta Garbo, Cary Grant, Alfred Hitchcock and Steven Spielberg have in common?</s>

<s docid="AP880325-0239" num="13" wdcount="10"> They have never won Academy Awards for their individual achievements.</s>

<s docid="AP880325-0239" num="14" wdcount="17"> Such flagrant omissions are often cited by critics as evidence of the unfairness of Hollywood's highest prize.</s>

<s docid="AP880325-0239" num="15" wdcount="24"> Oscar's 60-year history is filled with examples of the film world's highest achievers being overlooked by the Academy of Motion Picture Arts and Sciences.</s>

<s docid="AP880325-0239" num="16" wdcount="32"> The latest casualties are directors James L. Brooks, whose movie ``Broadcast News'' was nominated though he wasn't, and Spielberg who was left out in the cold with his ``Empire of the Sun''.</s>

<s docid="AP880325-0239" num="17" wdcount="23"> Although ``Broadcast News'' won seven major nominations, including best picture and three acting categories, Brooks was strangely overlooked by the Academy's directing branch.</s>

<s docid="AP880325-0239" num="18" wdcount="40"> Since no movie has ever won a best picture Oscar without its director at least being nominated, the chances of the once-favored ``Broadcast News'' to be a big winner at the awards ceremony on April 11 have been significantly reduced.</s>

<s docid="AP880325-0239" num="19" wdcount="21"> Brooks did better in 1984 when his ``Terms of Endearment'' took the lion's share of Oscars, including best picture and director.</s>

<s docid="AP880325-0239" num="20" wdcount="18"> Spielberg's ``Empire of the Sun'' won six nominations this year, none of them major and none for director.</s>

<s docid="AP880325-0239" num="21" wdcount="15"> Two years ago, ``The Color Purple'' received 11 nominations but not for him as director.</s>

<s docid="AP880325-0239" num="22" wdcount="10"> The Directors Guild nevertheless named him best director that year.</s>

<s docid="AP880325-0239" num="23" wdcount="11"> ``I'm floored by this,'' Spielberg said upon receiving his DGA award.</s>

<s docid="AP880325-0239" num="24" wdcount="9"> ``This is the last thing I expected to happen.</s>

<s docid="AP880325-0239" num="25" wdcount="18"> ... If some of you are making a statement _ thank God _ I thank you for that''.</s>

<s docid="AP880325-0239" num="26" wdcount="4"> Why the Spielberg slight?</s>

<s docid="AP880325-0239" num="27" wdcount="37"> Some observers cite the fact that only 257 directors nominate for the Academy Awards, and many are veterans who might not look kindly on the young man whose films are the biggest moneymakers in history (``Jaws,'' ``E.T.</s>

<s docid="AP880325-0239" num="28" wdcount="6"> ,'' ``Raiders of the Lost Ark'').</s>

<s docid="AP880325-0239" num="29" wdcount="22"> The Academy appeared to make amends last year by presenting Spielberg with the Irving Thalberg award for ``consistently high quality of production''.</s>

<s docid="AP880325-0239" num="30" wdcount="16"> There was no mention of the fact that Spielberg is primarily a director, not a producer.</s>

<s docid="AP880325-0239" num="31" wdcount="16"> The Thalberg award has come in handy to acknowledge giants who were overlooked for individual awards.</s>

<s docid="AP880325-0239" num="32" wdcount="16"> The recipients have included Cecil B. DeMille, Stanley Kramer, Alfred Hitchcock, Ingmar Bergman and Mervyn Leroy.</s>

<s docid="AP880325-0239" num="33" wdcount="12"> The honorary award has also proved useful to salve the Academy's conscience.</s>

<s docid="AP880325-0239" num="34" wdcount="38"> Charlie Chaplin received one at the first Academy Awards for his creation of ``The Circus'' and again at the 44th awards for ``the incalculable effect he has had in making motion pictures the art form of this century''.</s>

<s docid="AP880325-0239" num="35" wdcount="26"> Douglas Fairbanks, Judy Garland, Noel Coward, Ernst Lubitsch, Fred Astaire, Gene Kelly, Harold Lloyd, Greta Garbo, Maurice Chevalier, Stan Laurel, Cary Grant, Lillian Gish, Edward G.</s>

<s docid="AP880325-0239" num="36" wdcount="15"> Robinson, Groucho Marx, Howard Hawks and Jean Renoir are others who have received honorary awards.</s>

<s docid="AP880325-0239" num="37" wdcount="13"> Cary Grant once remarked that he never expected to win an Academy Award.</s>

<s docid="AP880325-0239" num="38" wdcount="22"> ``I'd have to blacken my teeth first,'' he quipped, alluding to the Academy's fondness for actors who portray bums and downtrodden characters.</s>

<s docid="AP880325-0239" num="39" wdcount="23"> Alfred Hitchcock also had a lighthearted comment on why he failed to win an Oscar: ``I suppose it was a matter of carelessness''.</s>

<s docid="AP880325-0239" num="40" wdcount="18"> The overlooking of classic films and the industry's most talented filmmakers has provided historians with cause for dispute.</s>

<s docid="AP880325-0239" num="41" wdcount="51"> For example, ``Citizen Kane,'' which customarily places No. 1 on polls of the greatest American films, was nominated in 1941 for best picture (there were 10 nominees in those days), for Orson Welles' performance, direction and co-scripting with Herman Mankiewicz, Gregg Toland's camera work, plus art direction, sound, music and editing.</s>

<s docid="AP880325-0239" num="42" wdcount="10"> The only Oscar for ``Citizen Kane'' was for the script.</s>

<s docid="AP880325-0239" num="43" wdcount="9"> ``How Green Was My Valley'' was named best picture.</s>

<s docid="AP880325-0239" num="44" wdcount="27"> Billy Wilder's classic comedy, ``Some Like It Hot,'' failed to be nominated as best picture, as did Chaplin's ``Modern Times,'' Hawks' ``Red River'' and Woody Allen's ``Manhattan''.</s>

<s docid="AP880325-0239" num="45" wdcount="2"> Oh, well.</s>

<s docid="AP880325-0239" num="46" wdcount="5"> Oscar might use Joe E.</s>

<s docid="AP880325-0239" num="47" wdcount="10"> Brown's final line from ``Some Like It Hot'': ``Nobody's perfect.''</s>
</TEXT>
<NOTE>

<s docid="AP880325-0239" num="48" wdcount="7"> End Adv for Mon AMs, March 28</s>
</NOTE>
</DOC>
