<DOC>
<DOCNO>

<s docid="AP891110-0043" num="1" wdcount="1"> AP891110-0043</s>
</DOCNO>
<FILEID>

<s docid="AP891110-0043" num="2" wdcount="2"> AP-NR-11-10-89 0356EST</s>
</FILEID>
<FIRST>

<s docid="AP891110-0043" num="3" wdcount="5"> r a PM-OscarCopyright 11-10 0359</s>
</FIRST>
<SECOND>

<s docid="AP891110-0043" num="4" wdcount="2"> PM-Oscar Copyright,0368</s>
</SECOND>
<HEAD>

<s docid="AP891110-0043" num="5" wdcount="5"> Oscar Trophy Has No Copyright</s>
</HEAD>
<BYLINE>

<s docid="AP891110-0043" num="6" wdcount="3"> By JOHN HORN</s>
</BYLINE>
<BYLINE>

<s docid="AP891110-0043" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP891110-0043" num="8" wdcount="3"> LOS ANGELES (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP891110-0043" num="9" wdcount="22"> The Oscar statuette, one of the most recognizable images in the entertainment world, has no copyright protection, a federal judge has ruled.</s>

<s docid="AP891110-0043" num="10" wdcount="12"> The small Academy Award statue is part of the public domain, U.S.</s>

<s docid="AP891110-0043" num="11" wdcount="11"> District Court Judge Laughlin Waters said in a ruling released Thursday.</s>

<s docid="AP891110-0043" num="12" wdcount="28"> The decision was a setback for the Academy of Motion Picture Arts and Sciences, which had sued a Chicago-based manufacturer of an employee-incentive trophy similar to the Oscar.</s>

<s docid="AP891110-0043" num="13" wdcount="13"> Academy President Karl Malden said the ruling ``comes as a shock to me''.</s>

<s docid="AP891110-0043" num="14" wdcount="6"> The academy said it would appeal.</s>

<s docid="AP891110-0043" num="15" wdcount="26"> The academy claimed that the Star Award, the trophy look-alike made by Creative House Promotions, violated copyright laws, diluted the academy's trademark and represented unfair competition.</s>

<s docid="AP891110-0043" num="16" wdcount="24"> The Star Award depicted a naked, muscular male much like the Oscar, just two inches shorter and holding a star instead of a sword.</s>

<s docid="AP891110-0043" num="17" wdcount="21"> It had a gold finish similar to the Oscar, and stood on a circular gold cap mounted on a cylindrical base.</s>

<s docid="AP891110-0043" num="18" wdcount="46"> Although Waters acknowledged that the Creative House trophy is ``very similar'' to the Oscar, he rejected all of the academy's legal claims, saying that the statuette became part of the public domain prior to Jan. 1, 1978, the effective date of the Copyright Act of 1976.</s>

<s docid="AP891110-0043" num="19" wdcount="23"> The film industry's top award was distributed from the first ceremony in 1929 until about 1941 without the ``c'' mark indicating a copyright.</s>

<s docid="AP891110-0043" num="20" wdcount="36"> The judge ruled, too, that the Oscar not only was an honorary award but also was used to promote the film industry, and therefore did not have a ``limited purpose,'' as required by the copyright act.</s>

<s docid="AP891110-0043" num="21" wdcount="31"> The academy noted that the ruling applied only to the statuette and that the academy's trademark and service marks for the Oscar and the Academy Award names and symbols are unaffected.</s>

<s docid="AP891110-0043" num="22" wdcount="42"> ``We are surprised that the court would base its decision on events which occurred half a century ago, overlooking the meticulous fashion in which the Academy has protected the integrity of its institutional symbol for decades,'' Malden said in a statement .</s>
</TEXT>
</DOC>
