<DOC>
<DOCNO>

<s docid="AP890324-0014" num="1" wdcount="1"> AP890324-0014</s>
</DOCNO>
<FILEID>

<s docid="AP890324-0014" num="2" wdcount="2"> AP-NR-03-24-89 0733EST</s>
</FILEID>
<FIRST>

<s docid="AP890324-0014" num="3" wdcount="5"> r a PM-APArts:Oscar-Auction 03-24 0750</s>
</FIRST>
<SECOND>

<s docid="AP890324-0014" num="4" wdcount="3"> PM-AP Arts: Oscar-Auction,0768</s>
</SECOND>
<HEAD>

<s docid="AP890324-0014" num="5" wdcount="10"> As Commercialism Creeps In, Academy Fights To Save Oscar Integrity</s>
</HEAD>
<HEAD>

<s docid="AP890324-0014" num="6" wdcount="7"> Eds: Also in Friday AMs report .</s>
</HEAD>
<BYLINE>

<s docid="AP890324-0014" num="7" wdcount="3"> By JOHN HORN</s>
</BYLINE>
<BYLINE>

<s docid="AP890324-0014" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890324-0014" num="9" wdcount="3"> LOS ANGELES (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890324-0014" num="10" wdcount="16"> Free enterprise has collided with the Academy Awards, and everybody's trying to pick up the pieces.</s>

<s docid="AP890324-0014" num="11" wdcount="42"> With Oscar statuettes selling at auction for more than $10,000 and a Chicago trophy company casting alleged Academy Award clones, the National Academy of Motion Picture Arts and Sciences is scrambling to make sure Oscar's golden sheen isn't tarnished by Hollywood hucksterism.</s>

<s docid="AP890324-0014" num="12" wdcount="43"> ``If you know about an infringement and fail to object to it, you risk having your trademark become public domain,'' said Bruce Davis, the Academy's executive administrator, in explaining the lawsuits the organization has filed to protect its beloved hunk of electroplated pewter.</s>

<s docid="AP890324-0014" num="13" wdcount="47"> But despite the Academy's crusade against crass commercialism, this year's awards ceremony will feature a new merchandising wrinkle: Some 800 limousines delivering the most famous stars to the Oscar telecast will be equipped with door-mounted coolers jammed with Diet Coke, Coca-Cola Classic and other Coca-Cola Co. beverages.</s>

<s docid="AP890324-0014" num="14" wdcount="35"> When the limo doors swing open in front of the Shrine Auditorium and the celebrities tumble out, the Coke logo will be on display in front of an audience that includes millions around the world.</s>

<s docid="AP890324-0014" num="15" wdcount="12"> ``It seemed like a good marketing opportunity,'' said Coca-Cola spokesman Ira Gleser.</s>

<s docid="AP890324-0014" num="16" wdcount="20"> ``The Academy approached our local bottler in Los Angeles and said we're going to have a lot of thirsty people''.</s>

<s docid="AP890324-0014" num="17" wdcount="26"> But even as the Academy embraces this new intrusion of merchandising, it has lashed out at whatever else it considers a blemishing of the Oscar name.</s>

<s docid="AP890324-0014" num="18" wdcount="31"> When MGM-UA, the distributor of ``Rain Man,'' published newspaper advertisements touting the film's Oscar nominations before the nominations were even announced, the Academy issued a harsh statement condemning MGM-UA's promotional gamble.</s>

<s docid="AP890324-0014" num="19" wdcount="9"> After the ads appeared, ``Rain Man'' collected nine nominations.</s>

<s docid="AP890324-0014" num="20" wdcount="20"> ``We regard this as a serious matter, and we have communicated our concern,'' said Richard Kahn, president of the Academy.</s>

<s docid="AP890324-0014" num="21" wdcount="18"> For nearly 50 years, the Academy has maintained strict security around both the nominations and the award winners.</s>

<s docid="AP890324-0014" num="22" wdcount="12"> It also has envisoned the statuette itself as something of an icon.</s>

<s docid="AP890324-0014" num="23" wdcount="9"> So auctioning the Oscar has greatly distressed the Academy.</s>

<s docid="AP890324-0014" num="24" wdcount="59"> The Collector's Book Store, local sponsors of monthly entertainment memorabilia auctions, has sold off seven Oscars in the past year, including the best picture trophy for 1951's ``An American in Paris'' ($15,760), Marlon Brando's best actor prize for 1954's ``On the Waterfront'' ($13,000) and the black and white interior decoration Oscar for 1941's ``How Green Was My Valley'' ($17,715).</s>

<s docid="AP890324-0014" num="25" wdcount="21"> None were sold by the original recipients; heirs or friends who had later received the trophies put them on the block.</s>

<s docid="AP890324-0014" num="26" wdcount="44"> When Malcolm Willits, the book store's owner, announced that he would hold a February auction for the 1957 best-picture trophy for ``Around the World in 80 Days,'' the Academy said enough, initiating a court action that, for now, has blocked any future trophy sales.</s>

<s docid="AP890324-0014" num="27" wdcount="29"> The Academy insists that a contract signed by Oscar winners mandates that they will not sell the trophies without first offering them to the Academy for a nominal fee.</s>

<s docid="AP890324-0014" num="28" wdcount="29"> ``But now that the word is out that these awards are worth $10,000 to $50,000, people are reluctant to sell them back to the Academy for $10,'' Willits said.</s>

<s docid="AP890324-0014" num="29" wdcount="9"> ``The Academy has created something of great value here.</s>

<s docid="AP890324-0014" num="30" wdcount="15"> This is the most famous award in the world _ the most instantly recognizable award.</s>

<s docid="AP890324-0014" num="31" wdcount="19"> The Nobel Prize might be a greater honor, but people know more about what an Academy Award looks like.</s>

<s docid="AP890324-0014" num="32" wdcount="5"> ``And they're very limited, too.</s>

<s docid="AP890324-0014" num="33" wdcount="7"> There's not too many of them around.</s>

<s docid="AP890324-0014" num="34" wdcount="20"> ... Twenty years ago, you wouldn't have a movie poster in your living room unless you were a college student.</s>

<s docid="AP890324-0014" num="35" wdcount="22"> Now, you can go into Beverly Hills homes and there's a movie poster, and the darn thing's worth $10,000 or $20,000 dollars''.</s>

<s docid="AP890324-0014" num="36" wdcount="17"> When the Academy won a court order temporarily blocking future auctions, Willits decided to sell his store.</s>

<s docid="AP890324-0014" num="37" wdcount="7"> ``It seemed to be the final straw.</s>

<s docid="AP890324-0014" num="38" wdcount="6"> I don't like lawsuits,'' he said.</s>

<s docid="AP890324-0014" num="39" wdcount="10"> ``I'm getting older and I'd like to write movie scripts''.</s>

<s docid="AP890324-0014" num="40" wdcount="34"> Yet the Academy has lost its most recent attempt to save its trophy's integrity: A copyright infringement suit brought against the Houston International Film Festival was dismissed March 16 in a California federal court.</s>

<s docid="AP890324-0014" num="41" wdcount="22"> The Academy had claimed the Lone Star Statuette, designed and built by Chicago's Creative House Promotions, was ``practically identical'' to the Oscar.</s>

<s docid="AP890324-0014" num="42" wdcount="5"> The court found otherwise .</s>
</TEXT>
</DOC>
