<DOC>
<DOCNO>

<s docid="AP890323-0218" num="1" wdcount="1"> AP890323-0218</s>
</DOCNO>
<FILEID>

<s docid="AP890323-0218" num="2" wdcount="2"> AP-NR-03-23-89 1129EST</s>
</FILEID>
<FIRST>

<s docid="AP890323-0218" num="3" wdcount="6"> a e PM-APArts:Oscar-Voting Adv24 03-23 0889</s>
</FIRST>
<SECOND>

<s docid="AP890323-0218" num="4" wdcount="5"> PM-AP Arts: Oscar-Voting, Adv 24,0909</s>
</SECOND>
<HEAD>

<s docid="AP890323-0218" num="5" wdcount="2"> $Adv 24</s>
</HEAD>
<HEAD>

<s docid="AP890323-0218" num="6" wdcount="8"> For Release Fri PMs, March 24 and Thereafter</s>
</HEAD>
<HEAD>

<s docid="AP890323-0218" num="7" wdcount="10"> Oscar Ballot Comes Under Scrutiny As Some Allege Team Voting</s>
</HEAD>
<BYLINE>

<s docid="AP890323-0218" num="8" wdcount="3"> By JOHN HORN</s>
</BYLINE>
<BYLINE>

<s docid="AP890323-0218" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890323-0218" num="10" wdcount="2"> HOLLYWOOD (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890323-0218" num="11" wdcount="26"> Oscar selection has come under scrutiny as film studios go to new lengths to pull votes out of the Academy of Motion Picture Arts and Sciences.</s>

<s docid="AP890323-0218" num="12" wdcount="35"> And with the flood of Oscar vote enticements _ from free coffee mugs to complimentary buffet dinners _ Academy members are acknowledging that some Oscar voting is done by committee, in violation of the rules.</s>

<s docid="AP890323-0218" num="13" wdcount="24"> Secretaries, spouses and friends, several Academy members say, are marking ballots in what is supposed to be the entertainment industry's most esteemed awards competition.</s>

<s docid="AP890323-0218" num="14" wdcount="18"> ``It's like a local election of judges,'' said Academy member Harry Clein, who said he's witnessed team voting.</s>

<s docid="AP890323-0218" num="15" wdcount="10"> ``A lot of people don't know who the candidates are.</s>

<s docid="AP890323-0218" num="16" wdcount="15"> So they take a look at who's around them and see what the consensus is.</s>

<s docid="AP890323-0218" num="17" wdcount="8"> ``As far as elections go, it's not bad.</s>

<s docid="AP890323-0218" num="18" wdcount="9"> But I've never been through an election in Argentina''.</s>

<s docid="AP890323-0218" num="19" wdcount="30"> Dan Lyle, who oversees the Oscar balloting for the accounting firm Price, Waterhouse Inc., said that there is no guarantee that Academy members have actually filled out their own ballots.</s>

<s docid="AP890323-0218" num="20" wdcount="14"> ``All we know is that a properly numbered ballot has been returned,'' he said.</s>

<s docid="AP890323-0218" num="21" wdcount="12"> ``Members are on the honor system to fill out the ballot themselves''.</s>

<s docid="AP890323-0218" num="22" wdcount="29"> More than 4,600 members were given ballots this year for the 61st Annual Academy Awards, which will be telecast on March 29 from the Shrine Auditorium in Los Angeles.</s>

<s docid="AP890323-0218" num="23" wdcount="8"> Academy members vote on their area of specialty.</s>

<s docid="AP890323-0218" num="24" wdcount="18"> The Academy's actors branch, for example, is the only group to select nominees in the four acting categories.</s>

<s docid="AP890323-0218" num="25" wdcount="27"> Since the voting is done secretly _ members do not sign their ballots _ the ballot's authenticity is ensured solely by a numeric control number, Lyle said.</s>

<s docid="AP890323-0218" num="26" wdcount="28"> Ballots are invalidated only if there is more than one vote in a given category, and only the votes in that specific category are not tallied, he said.</s>

<s docid="AP890323-0218" num="27" wdcount="21"> Nominations for acting, directing, art direction and all specialized categories are handled by select branches and committees composed of Academy members.</s>

<s docid="AP890323-0218" num="28" wdcount="23"> All voting members of the Academy can participate in the best picture nominations and may vote for the final awards in all categories.</s>

<s docid="AP890323-0218" num="29" wdcount="26"> Winners for best documentary feature, best animated short film and best live-action short film are chosen by only those members who have seen all the nominees.</s>

<s docid="AP890323-0218" num="30" wdcount="15"> Academy constituent Julian Blaustein said that most of his colleagues take the voting very seriously.</s>

<s docid="AP890323-0218" num="31" wdcount="17"> ``I don't even vote (in a category) if I'm not familiar with the pictures in that category.</s>

<s docid="AP890323-0218" num="32" wdcount="18"> ... And I've never told someone to vote for a film, even when I've done some of them''.</s>

<s docid="AP890323-0218" num="33" wdcount="15"> Meanwhile, other Oscar voting rules are perhaps being broken, speculates veteran Academy member Millard Kaufman.</s>

<s docid="AP890323-0218" num="34" wdcount="41"> ``Although you're asked to vote in the nominations for five pictures, I think a lot of people figure out that they have a better chance if they just vote for their own picture and leave the other four blank,'' he said.</s>

<s docid="AP890323-0218" num="35" wdcount="31"> Given the tremendous impact both an Oscar nomination and an Oscar victory have on a film's fortunes, it's not entirely surprising that a certain degree of artifice might surround the Oscars.</s>

<s docid="AP890323-0218" num="36" wdcount="21"> ``The Last Emperor'' took in $18.9 million, close to half the film's gross, after it won last year's best picture trophy.</s>

<s docid="AP890323-0218" num="37" wdcount="19"> More than 70 percent of the revenues generated by 1986's best picture, ``Platoon,'' came after the film was nominated.</s>

<s docid="AP890323-0218" num="38" wdcount="13"> On average, a best picture award is worth about $20 million these days.</s>

<s docid="AP890323-0218" num="39" wdcount="15"> A $500,000 Oscar promotional campaign mounted by a studio, therefore, can be a good investment.</s>

<s docid="AP890323-0218" num="40" wdcount="30"> In the case of this year's awards, a flurry of Academy-oriented newspaper advertisements, banquets, complimentary gifts and photo mailings tied to five late releases appears to have been remarkably successful.</s>

<s docid="AP890323-0218" num="41" wdcount="36"> This year, all best picture nominees and the large majority of top acting nominees came from movies released in December: ``The Accidental Tourist,'' ``Dangerous Liaisons,'' ``Rain Man'' and ``Working Girl'' were all released after Dec. 16.</s>

<s docid="AP890323-0218" num="42" wdcount="27"> While these five movies might be good, the nearly complete exclusion of films from the rest of the year has highlighted the studios' mastery of Oscar marketing.</s>

<s docid="AP890323-0218" num="43" wdcount="21"> ``I think the Academy Awards are crap,'' said Terry Gilliam, director of ``Brazil'' and the current ``The Adventures of Baron Munchausen''.</s>

<s docid="AP890323-0218" num="44" wdcount="10"> ``It's about selling films is all it's about,'' he said.</s>

<s docid="AP890323-0218" num="45" wdcount="8"> ``It's one more way of flogging some films.</s>

<s docid="AP890323-0218" num="46" wdcount="16"> When `Brazil' got nominated (in 1986), they asked me to be a member of the Academy.</s>

<s docid="AP890323-0218" num="47" wdcount="4"> And I wouldn't join.</s>

<s docid="AP890323-0218" num="48" wdcount="12"> I just don't want to be a part of that at all''.</s>

<s docid="AP890323-0218" num="49" wdcount="21"> And at least one prominent Academy member, director Carl Reiner, says that the manipulation of Oscar voters has reached new depths.</s>

<s docid="AP890323-0218" num="50" wdcount="30"> Reiner said that Universal Studios' all-out effort to bag votes for Sigourney Weaver, a best actress nominee for ``Gorillas in the Mist,'' could lead him to vote against the film.</s>

<s docid="AP890323-0218" num="51" wdcount="27"> ``I have in my house more color reproductions of Sigourney Weaver and a beautiful gorilla than I need,'' Reiner said of promotional material sent to his home.</s>

<s docid="AP890323-0218" num="52" wdcount="10"> ``We've got to tell the Academy to stop this advertising.</s>

<s docid="AP890323-0218" num="53" wdcount="9"> I'm getting turned off on the pictures I like.''</s>
</TEXT>
<NOTE>

<s docid="AP890323-0218" num="54" wdcount="6"> End Adv PM Fri March 24</s>
</NOTE>
</DOC>
