<DOC>
<DOCNO>

<s docid="AP890330-0123" num="1" wdcount="1"> AP890330-0123</s>
</DOCNO>
<FILEID>

<s docid="AP890330-0123" num="2" wdcount="2"> AP-NR-03-30-89 2032EST</s>
</FILEID>
<FIRST>

<s docid="AP890330-0123" num="3" wdcount="5"> r a AM-Oscar-Perspective 03-30 0417</s>
</FIRST>
<SECOND>

<s docid="AP890330-0123" num="4" wdcount="1"> AM-Oscar-Perspective,0447</s>
</SECOND>
<HEAD>

<s docid="AP890330-0123" num="5" wdcount="10"> 61st Oscars: Way Too Much, And Some New Award Categories</s>
</HEAD>
<BYLINE>

<s docid="AP890330-0123" num="6" wdcount="3"> By BOB THOMAS</s>
</BYLINE>
<BYLINE>

<s docid="AP890330-0123" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890330-0123" num="8" wdcount="3"> LOS ANGELES (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890330-0123" num="9" wdcount="18"> Spencer Tracy's acting technique was simply ``less is better,'' and that helped make him the screen's greatest actor.</s>

<s docid="AP890330-0123" num="10" wdcount="12"> The Tracy credo is recommended to future producers of Academy Award shows.</s>

<s docid="AP890330-0123" num="11" wdcount="14"> Wednesday night's orgy of self-congratulation was dazzling, glamorous and all those familiar Hollywood adjectives.</s>

<s docid="AP890330-0123" num="12" wdcount="3"> Also too much.</s>

<s docid="AP890330-0123" num="13" wdcount="5"> Too many endless production numbers.</s>

<s docid="AP890330-0123" num="14" wdcount="6"> Too much forced conversation between couples.</s>

<s docid="AP890330-0123" num="15" wdcount="10"> Too many awards with meaning lost to the general public.</s>

<s docid="AP890330-0123" num="16" wdcount="23"> The use of ``couples, co-stars, compadres and companions,'' as presenters for the 61st Academy Awards at the Shrine Auditorium was clever but wearing.</s>

<s docid="AP890330-0123" num="17" wdcount="27"> The best Oscar shows have been emceed by Will Rogers, Bob Hope, Johnny Carson and other funnymen who provided continuity as well as a leavening of pomposity.</s>

<s docid="AP890330-0123" num="18" wdcount="22"> The brightest moments of the 61st Awards came from Billy Crystal, Robin Williams and Bob Hope, but they were all too brief.</s>

<s docid="AP890330-0123" num="19" wdcount="17"> Tom Selleck remarked that Douglas Fairbanks Sr. handed out the first awards in 1929 in five minutes.</s>

<s docid="AP890330-0123" num="20" wdcount="23"> The present awards could be staged in two hours instead of the 3 hours and 15 minutes they took Wednesday night on ABC-TV.</s>

<s docid="AP890330-0123" num="21" wdcount="7"> But the show will never be shorter.</s>

<s docid="AP890330-0123" num="22" wdcount="14"> Reason: The time is needed to sell all those 30-second adds at $375,000 per.</s>

<s docid="AP890330-0123" num="23" wdcount="20"> Since the Academy Awards are a night of superlatives here are a few more: The most heartfelt acceptance: Dustin Hoffman.</s>

<s docid="AP890330-0123" num="24" wdcount="6"> The most intelligent acceptance: Jodie Foster.</s>

<s docid="AP890330-0123" num="25" wdcount="7"> Warmest reception: Lucille Ball and Bob Hope.</s>

<s docid="AP890330-0123" num="26" wdcount="5"> Best looking legs: Cyd Charisse.</s>

<s docid="AP890330-0123" num="27" wdcount="5"> Second-best looking legs: Martin Short.</s>

<s docid="AP890330-0123" num="28" wdcount="13"> Worst desecration of an icon: Snow White portrayed as a whining would-be starlet.</s>

<s docid="AP890330-0123" num="29" wdcount="11"> Best comedy routine: Billy Crystal imitating Yul Brynner as Babe Ruth.</s>

<s docid="AP890330-0123" num="30" wdcount="13"> Best walk-on music: ``The Second Time Around'' for Melanie Griffith and Don Johnson.</s>

<s docid="AP890330-0123" num="31" wdcount="6"> Least promising rock singer: Rob Lowe.</s>

<s docid="AP890330-0123" num="32" wdcount="15"> Most overworked butt of jokes: Vice President Dan Quayle by Crystal, Hope and Williams (twice).</s>

<s docid="AP890330-0123" num="33" wdcount="5"> Most prevalent fashion: Strapless gowns.</s>

<s docid="AP890330-0123" num="34" wdcount="7"> Seemingly endless number: ``Oscar Winners of Tomorrow''.</s>

<s docid="AP890330-0123" num="35" wdcount="9"> Most relentless double entendre: Bo Derek and Dudley Moore.</s>

<s docid="AP890330-0123" num="36" wdcount="11"> Most questionable taste: Kurt Russell's ``proposal'' of marriage to Goldie Hawn.</s>

<s docid="AP890330-0123" num="37" wdcount="9"> Most mentioned agent: Michael Ovitz of Creative Artists Agency.</s>

<s docid="AP890330-0123" num="38" wdcount="9"> Most recurrent dance routine: The Rockettes-like line of kickers.</s>

<s docid="AP890330-0123" num="39" wdcount="11"> Best exchange of banter: Sean Connery, Michael Caine and Roger Moore.</s>

<s docid="AP890330-0123" num="40" wdcount="10"> Most welcomed elimination: Singing of the nominees for best song.</s>

<s docid="AP890330-0123" num="41" wdcount="12"> Most stunning beauty: Michelle Pfeiffer Worst reader of Teleprompter: Walter Matthau .</s>
</TEXT>
<TEXT>

<s docid="AP890330-0123" num="42" wdcount="10"> Editors: Wednesday's ceremony was Bob Thomas' 45th Academy Awards .</s>
</TEXT>
</DOC>
