<DOC>
<DOCNO>

<s docid="AP900220-0065" num="1" wdcount="1"> AP900220-0065</s>
</DOCNO>
<FILEID>

<s docid="AP900220-0065" num="2" wdcount="2"> AP-NR-02-20-90 1033EST</s>
</FILEID>
<FIRST>

<s docid="AP900220-0065" num="3" wdcount="5"> r a PM-People-SpikeLee 02-20 0218</s>
</FIRST>
<SECOND>

<s docid="AP900220-0065" num="4" wdcount="2"> PM-People-Spike Lee,0223</s>
</SECOND>
<HEAD>

<s docid="AP900220-0065" num="5" wdcount="11"> Director Spike Lee Has Pointed Remarks in Talk at Syracuse University</s>
</HEAD>
<DATELINE>

<s docid="AP900220-0065" num="6" wdcount="3"> SYRACUSE, N.Y. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900220-0065" num="7" wdcount="30"> Spike Lee may have been wearing a Georgetown University cap and sweatshirt, but he got a far warmer reception from Syracuse University students than he did from Academy Award voters.</s>

<s docid="AP900220-0065" num="8" wdcount="28"> In a lecture and question-and-answer session Monday, Lee shrugged off the academy's icy treatment of his latest movie, ``Do the Right Thing,'' and blamed it on generational politics.</s>

<s docid="AP900220-0065" num="9" wdcount="23"> The 1989 film, widely hailed by critics, received only two Academy Award nominations, and isn't being considered for best picture or best director.</s>

<s docid="AP900220-0065" num="10" wdcount="12"> The academy's membership consists mainly of ``old people,'' the 32-year-old Lee said.</s>

<s docid="AP900220-0065" num="11" wdcount="24"> He said they were ``a lot more comfortable with the black chauffeur in `Driving Miss Daisy''' than with the angry characters in his film.</s>

<s docid="AP900220-0065" num="12" wdcount="13"> ``I still feel we made the best film of the year,'' he said.</s>

<s docid="AP900220-0065" num="13" wdcount="17"> Asked if racism might have been involved in the academy nominations, Lee replied, ``Racism's involved in everything''.</s>

<s docid="AP900220-0065" num="14" wdcount="14"> Despite the cap and sweatshirt, Syracuse students welcomed him as one of their own.</s>

<s docid="AP900220-0065" num="15" wdcount="31"> ``He's an African-American, one of the first ones to make it (as a producer and director), and he's addressing the issues and concerns affecting our community,'' Syracuse senior Deron Harris said.</s>

<s docid="AP900220-0065" num="16" wdcount="7"> ``That's why we're so proud of him.''</s>
</TEXT>
</DOC>
