<DOC>
<DOCNO>

<s docid="LA033189-0114" num="1" wdcount="1"> LA033189-0114</s>
</DOCNO>
<DOCID>

<s docid="LA033189-0114" num="2" wdcount="1"> 38062</s>
</DOCID>
<DATE>
<P>

<s docid="LA033189-0114" num="3" wdcount="6"> March 31, 1989, Friday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA033189-0114" num="4" wdcount="9"> Metro; Part 2; Page 1; Column 3; Metro Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA033189-0114" num="5" wdcount="2"> 553 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA033189-0114" num="6" wdcount="9"> DISNEY SUES OVER USE OF SNOW WHITE AT OSCARS</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA033189-0114" num="7" wdcount="7"> By NINA J. EASTON, Times Staff Writer</s>
</P>
</BYLINE>
<TEXT>
<P>

<s docid="LA033189-0114" num="8" wdcount="20"> Who would have thought that Snow White, of all people, would become the source of Oscar night's only major glitch?</s>
</P>
<P>

<s docid="LA033189-0114" num="9" wdcount="33"> The Walt Disney Co. filed suit in Los Angeles federal court Thursday against the Academy of Motion Picture Arts and Sciences, charging copyright infringement of its Snow White character and unfair competition .</s>
</P>
<P>

<s docid="LA033189-0114" num="10" wdcount="22"> The famous fairy tale character, portrayed by singer-dancer Eileen Bowman, opened Wednesday night's Academy Awards ceremonies with an elaborate, 10-minute song-and-dance routine.</s>

<s docid="LA033189-0114" num="11" wdcount="16"> But Disney contends that the character was used on the show without the company's permission .</s>
</P>
<P>

<s docid="LA033189-0114" num="12" wdcount="27"> "We have great respect for the academy and for all that it does," Frank Wells, Disney's president and chief operating officer, said Thursday in a prepared statement.</s>

<s docid="LA033189-0114" num="13" wdcount="30"> "We were therefore greatly surprised and dismayed when we viewed last evening's Academy Awards ceremonies to see that our Snow White character had been used extensively without our permission" .</s>
</P>
<P>

<s docid="LA033189-0114" num="14" wdcount="32"> Wells said the suit was filed only after the company asked the academy to publicly apologize for its unauthorized use of the character, which debuted in a 1937 full-length cartoon film .</s>
</P>
<P>

<s docid="LA033189-0114" num="15" wdcount="20"> "If such a statement had been agreed to by the academy," Wells said, "we would have considered the matter ended.</s>

<s docid="LA033189-0114" num="16" wdcount="15"> For its own reasons, however, the academy unfortunately did not accede to our request" .</s>
</P>
<P>

<s docid="LA033189-0114" num="17" wdcount="31"> Disney spokesman Erwin Okun did not provide any details of Thursday's negotiations with academy officials over an apology, except to say that the academy's offer "was not to our satisfaction" .</s>
</P>
<P>

<s docid="LA033189-0114" num="18" wdcount="18"> Bruce Davis, the academy's executive administrator, declined comment, saying top officials needed time to assess the suit .</s>
</P>
<P>

<s docid="LA033189-0114" num="19" wdcount="22"> "We haven't gotten any official notification of this," Davis said, adding that he learned of the legal action from a reporter .</s>
</P>
<P>

<s docid="LA033189-0114" num="20" wdcount="24"> Ironically, the academy is extremely protective of the Oscar name and statuette copyrights and is quick to object to the image's unauthorized use .</s>
</P>
<P>
</P>
<P>

<s docid="LA033189-0114" num="21" wdcount="3"> Number Kept Secret</s>
</P>
<P>

<s docid="LA033189-0114" num="22" wdcount="25"> Alan Carr, who produced the Oscar show, had ordered that the details of the opening number be kept secret until Wednesday night's ABC telecast .</s>
</P>
<P>

<s docid="LA033189-0114" num="23" wdcount="17"> But in its suit, Disney says a company representative learned of the plans early in the week.</s>

<s docid="LA033189-0114" num="24" wdcount="16"> The company claims that the academy refused to respond to its inquiries until Wednesday afternoon .</s>
</P>
<P>

<s docid="LA033189-0114" num="25" wdcount="41"> At that point, the Disney statement said, the academy, "through a legal representative, denied to Disney that the Academy Award program contained any material deleterious to the interests of Disney, without revealing the academy's intention to feature Disney's Snow White" .</s>
</P>
<P>

<s docid="LA033189-0114" num="26" wdcount="9"> Carr could not be reached for comment Thursday .</s>
</P>
<P>

<s docid="LA033189-0114" num="27" wdcount="35"> The Snow White character -- as portrayed Wednesday night by Bowman -- was created by Steve Silver, who for 15 years has used the character in the San Francisco musical revue "Beach Blanket Babylon" .</s>
</P>
<P>

<s docid="LA033189-0114" num="28" wdcount="20"> Disney files dozens of suits a year against individuals and companies that copy its characters, particularly in consumer products .</s>
</P>
<P>

<s docid="LA033189-0114" num="29" wdcount="8"> "We sue all the time," Okun said .</s>
</P>
<P>

<s docid="LA033189-0114" num="30" wdcount="26"> But Okun said the company, which won four Oscars Wednesday night, has never sued Silver over his use of the Snow White character in that production.</s>

<s docid="LA033189-0114" num="31" wdcount="13"> The spokesman, however, did not preclude the possibility of a future lawsuit .</s>
</P>
<P>

<s docid="LA033189-0114" num="32" wdcount="16"> "We look at these characters as the heart and soul of the company," Okun explained .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA033189-0114" num="33" wdcount="9"> Photo, Eileen Bowman, portraying Snow White, works crowd, below,.</s>

<s docid="LA033189-0114" num="34" wdcount="15"> . . Photo, . . . and dances with Rob Lowe in Academy Awards' opening.</s>

<s docid="LA033189-0114" num="35" wdcount="6"> RANDY LEFFINGWELL / Los Angeles Times</s>
</P>
</GRAPHIC>
<SUBJECT>
<P>

<s docid="LA033189-0114" num="36" wdcount="22"> SNOW WHITE; CARR, ALAN; BOWMAN, EILEEN; WALT DISNEY CO; ACADEMY OF MOTION PICTURE ARTS AND SCIENCES; ACADEMY AWARDS; SUITS; COPYRIGHT; CARTOON CHARACTERS</s>
</P>
</SUBJECT>
</DOC>
