<DOC>
<DOCNO>

<s docid="LA033089-0190" num="1" wdcount="1"> LA033089-0190</s>
</DOCNO>
<DOCID>

<s docid="LA033089-0190" num="2" wdcount="1"> 37693</s>
</DOCID>
<DATE>
<P>

<s docid="LA033089-0190" num="3" wdcount="6"> March 30, 1989, Thursday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA033089-0190" num="4" wdcount="9"> Calendar; Part 6; Page 1; Column 2; Entertainment Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA033089-0190" num="5" wdcount="2"> 570 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA033089-0190" num="6" wdcount="7"> SOMETHING FOR EVERYONE . . . ALMOST;</s>
</P>
<P>

<s docid="LA033089-0190" num="7" wdcount="9"> ACADEMY VOTERS SURVEY THE FIELD, AND SPREAD THE WEALTH</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA033089-0190" num="8" wdcount="6"> By JACK MATHEWS, Times Staff Writer</s>
</P>
</BYLINE>
<TEXT>
<P>

<s docid="LA033089-0190" num="9" wdcount="37"> Well, it did turn out to be "Rain Man's" evening, but not until the last few minutes, and if there was a message in Wednesday night's Academy Awards results, it's that parity has returned to Hollywood .</s>
</P>
<P>

<s docid="LA033089-0190" num="10" wdcount="18"> For two-thirds of the show, the academy voters seemed determined to give an award to every film nominated.</s>

<s docid="LA033089-0190" num="11" wdcount="19"> As it was, 10 different movies split 17 awards, the most winners for one year in this decade .</s>
</P>
<P>

<s docid="LA033089-0190" num="12" wdcount="12"> The major awards made the forecasters look smart and the academy predictable.</s>

<s docid="LA033089-0190" num="13" wdcount="31"> "Rain Man" did win the grand prize (and three other big ones) and "Mississippi Burning," with just one Oscar for cinematography, did get punished for its highly publicized historical muddling .</s>
</P>
<P>

<s docid="LA033089-0190" num="14" wdcount="33"> But gone, for a refreshing change, was the slate voting that has turned many recent Academy Awards shows into one-note evenings that kept some deserving people out of the Oscar resale market .</s>
</P>
<P>

<s docid="LA033089-0190" num="15" wdcount="45"> "Rain Man," its director Barry Levinson, Hoffman and the screenwriters (the two of several who worked on it) may have fulfilled their roles as favorites, but there were no sure things elsewhere, and people looking for early patterns had to throw away the form .</s>
</P>
<P>

<s docid="LA033089-0190" num="16" wdcount="20"> The final score shows "Rain Man" with four Oscars and "Dangerous Liaisons" and "Who Framed Roger Rabbit" with three each.</s>

<s docid="LA033089-0190" num="17" wdcount="11"> But there were seven other films with one award each .</s>
</P>
<P>

<s docid="LA033089-0190" num="18" wdcount="39"> Whether the spread represents a change in voting habits, or an absence of a film to rally around, it made for a great show and in some cases, the awards helped right some wrongs in the nominations process .</s>
</P>
<P>

<s docid="LA033089-0190" num="19" wdcount="36"> That "Who Framed Roger Rabbit" won three of the six awards for which it was nominated may save the academy some embarrassment for neglecting the one 1988 film sure to be regarded as a classic .</s>
</P>
<P>

<s docid="LA033089-0190" num="20" wdcount="19"> The good news for observers of voter psychology were the awards given to films that were not box-office hits.</s>

<s docid="LA033089-0190" num="21" wdcount="32"> The voters tend to favor those films that are both of substance and commercially successful (thus: "Rain Man"), and whether they even bother to see the other nominees is often questioned .</s>
</P>
<P>

<s docid="LA033089-0190" num="22" wdcount="37"> This year, several winners came from films that failed to ring up big numbers at the box office: Jodie Foster as best actress from "The Accused," Geena Davis as best supporting actress from "The Accidental Tourist" .</s>
</P>
<P>

<s docid="LA033089-0190" num="23" wdcount="29"> More surprising were the awards given to "Bird" and "The Milagro Beanfield War," films that divided critics and sent moviegoers off to the video store looking for alternatives .</s>
</P>
<P>

<s docid="LA033089-0190" num="24" wdcount="37"> Both films were flawed, but the sound editing done for "Bird," which seamlessly blended old jazz recordings with fresh studio cuts done by contemporary musicians, was brilliant and deserved the award its four-man sound team won .</s>
</P>
<P>

<s docid="LA033089-0190" num="25" wdcount="24"> David Grusin's Oscar for scoring "The Milagro Beanfield War" overcame even bigger odds, winning over popular John Williams' score for "The Accidental Tourist" .</s>
</P>
<P>

<s docid="LA033089-0190" num="26" wdcount="33"> The selective mood of the voters is a reflection of the kind of year the film industry had, and whether the spread is a quirk, one can hope it suggests a trend .</s>
</P>
<P>

<s docid="LA033089-0190" num="27" wdcount="14"> The 1988 slate of films was, on total, a marked improvement over recent years.</s>

<s docid="LA033089-0190" num="28" wdcount="24"> The industry is still adjusting to its changing -- its older and more demanding audience -- and that means a wider variety of films.</s>

<s docid="LA033089-0190" num="29" wdcount="21"> Nominees this year represented as wide a range of material as any in years, and they produced more winning films .</s>
</P>
<P>

<s docid="LA033089-0190" num="30" wdcount="17"> The events last night played hell with the office pool, but it made for a better show.</s>

<s docid="LA033089-0190" num="31" wdcount="8"> Maybe it's the start of something new .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA033089-0190" num="32" wdcount="8"> Photo, Barry Levinson, a triumph for "Rain Man".</s>

<s docid="LA033089-0190" num="33" wdcount="19"> RANDY LEFFINGWELL / Los Angeles Times; Photo, Geena Davis takes an Oscar home for performance in "The Accidental Tourist".</s>

<s docid="LA033089-0190" num="34" wdcount="9"> Photo, Kevin Kline holds his Oscar for best-supporting actor.</s>

<s docid="LA033089-0190" num="35" wdcount="6"> JAYNE KAMIN-ONCEA / Los Angeles Times</s>
</P>
</GRAPHIC>
<SUBJECT>
<P>

<s docid="LA033089-0190" num="36" wdcount="22"> ACADEMY AWARDS; 1988 (YEAR); MOTION PICTURES; HONORS; RAIN MAN (MOTION PICTURE); HOFFMAN, DUSTIN; FOSTER, JODIE; LEVINSON, BARRY; KLINE, KEVIN; DAVIS, GEENA; AWARDS</s>
</P>
</SUBJECT>
</DOC>
