<DOC>
<DOCNO>

<s docid="AP900625-0153" num="1" wdcount="1"> AP900625-0153</s>
</DOCNO>
<FILEID>

<s docid="AP900625-0153" num="2" wdcount="2"> AP-NR-06-25-90 2129EDT</s>
</FILEID>
<FIRST>

<s docid="AP900625-0153" num="3" wdcount="5"> r i AM-Quake-List 06-25 0139</s>
</FIRST>
<SECOND>

<s docid="AP900625-0153" num="4" wdcount="1"> AM-Quake-List,0150</s>
</SECOND>
<HEAD>

<s docid="AP900625-0153" num="5" wdcount="6"> Five Decades of Major Earthquakes Worldwide</s>
</HEAD>
<HEAD>

<s docid="AP900625-0153" num="6" wdcount="3"> With AM-Iran-Quake, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP900625-0153" num="7" wdcount="4"> By The Associated Press</s>
</BYLINE>
<TEXT>

<s docid="AP900625-0153" num="8" wdcount="19"> The estimated 50,000 dead in the Iran earthquake make it the world's fourth deadliest quake in the past half-century.</s>

<s docid="AP900625-0153" num="9" wdcount="13"> Here is a list of the major quakes of the past 50 years.</s>

<s docid="AP900625-0153" num="10" wdcount="14"> The location is followed by the Richter scale magnitude and the number of dead.</s>

<s docid="AP900625-0153" num="11" wdcount="14"> Iran, June 21, 1990, 7.3 to 7.7 on the Richter scale, 50,000 dead (estimated).</s>

<s docid="AP900625-0153" num="12" wdcount="7"> Soviet Armenia, Dec. 7, 1988, 6.9, 25,000.</s>

<s docid="AP900625-0153" num="13" wdcount="6"> Iran, Sept. 16, 1978, 7.7, 25,000.</s>

<s docid="AP900625-0153" num="14" wdcount="9"> China, July 28, 1976, 8.2, 200,000 officially, 800,000 unofficially.</s>

<s docid="AP900625-0153" num="15" wdcount="6"> Guatemala, Feb. 4, 1976, 7.5, 22,778.</s>

<s docid="AP900625-0153" num="16" wdcount="6"> Peru, May 31, 1970, 7.7, 66,794.</s>

<s docid="AP900625-0153" num="17" wdcount="6"> Iran, Aug. 31, 1968, 7.4, 12,000.</s>

<s docid="AP900625-0153" num="18" wdcount="6"> Iran, Sept. 1, 1962, 7.1, 12,230.</s>

<s docid="AP900625-0153" num="19" wdcount="6"> Morocco, Feb. 29, 1960, 5.8, 12,000.</s>

<s docid="AP900625-0153" num="20" wdcount="11"> Soviet Turkmenia, Oct. 5, 1948, (no Richter reading available), 110,000 .</s>
</TEXT>
</DOC>
