<DOC>
<DOCNO>

<s docid="AP900621-0186" num="1" wdcount="1"> AP900621-0186</s>
</DOCNO>
<FILEID>

<s docid="AP900621-0186" num="2" wdcount="2"> AP-NR-06-21-90 1947EDT</s>
</FILEID>
<FIRST>

<s docid="AP900621-0186" num="3" wdcount="5"> u a AM-US-IranQuake-Structures 06-21 0325</s>
</FIRST>
<SECOND>

<s docid="AP900621-0186" num="4" wdcount="2"> AM-US-Iran Quake-Structures,0336</s>
</SECOND>
<HEAD>

<s docid="AP900621-0186" num="5" wdcount="8"> Iran Earthquake Caught Victims Asleep in Fragile Homes</s>
</HEAD>
<HEAD>

<s docid="AP900621-0186" num="6" wdcount="3"> With AM-Iran-Quake, Bjt</s>
</HEAD>
<DATELINE>

<s docid="AP900621-0186" num="7" wdcount="3"> NEW YORK (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900621-0186" num="8" wdcount="28"> The earthquake that devastated Iran early Thursday took tens of thousands of lives because people were asleep in fragile homes built on flood plains, an earthquake expert said.</s>

<s docid="AP900621-0186" num="9" wdcount="21"> ``Most casualties from earthquakes are caused by something falling on top of you,'' said Russ Needham, a geophysist with the U.S.</s>

<s docid="AP900621-0186" num="10" wdcount="9"> Geological Survey that monitors ground motion around the world.</s>

<s docid="AP900621-0186" num="11" wdcount="27"> The quake hit at 12:30 a.m. in Iran, when most of the people were in their homes, Needham said Thursday in a telephone interview from Golden, Colo.</s>

<s docid="AP900621-0186" num="12" wdcount="31"> At least 25,000 people died and thousands were injured in the quake, which demolished scores of villages and buried thousands of people in the rubble of their homes, Iranian officials said.</s>

<s docid="AP900621-0186" num="13" wdcount="18"> Needham said most structures in that area are built of a ceramic-type brick or adobe that collapses easily.</s>

<s docid="AP900621-0186" num="14" wdcount="22"> ``It's very similar to what we had in Armenia,'' he said of the Dec. 7, 1988, earthquake that killed about 25,000 people.</s>

<s docid="AP900621-0186" num="15" wdcount="15"> A Soviet parliamentary report later blamed the high number of fatalities on shoddily built buildings.</s>

<s docid="AP900621-0186" num="16" wdcount="22"> The Armenian quake was measured at 6.9 on the Richter scale, but Thursday's earthquake shook the earth with a magnitude of 7.7.</s>

<s docid="AP900621-0186" num="17" wdcount="38"> The shock wave traveled through the mountainous section of coastal Iran where most of the buildings are built on a flood plain of loosely deposited soil that shifts in an earthquake and allows structures to collapse, he said.</s>

<s docid="AP900621-0186" num="18" wdcount="22"> The 7.7-magnitude quake was the largest ever recorded in that area, where two major plates of the earth's crust meet, Needhams said.</s>

<s docid="AP900621-0186" num="19" wdcount="18"> ``Iran is in a very active seismic region,'' he said, and that there have been many smaller quakes.</s>

<s docid="AP900621-0186" num="20" wdcount="17"> Twelve earthquakes greater than magnitude 7 have occurred in Iran during the last 30 years, Needhams said.</s>

<s docid="AP900621-0186" num="21" wdcount="19"> A quake of magnitude 7 is considered a major earthquake, capable of widespread, heavy damage in populated areas .</s>
</TEXT>
</DOC>
