<DOC>
<DOCNO>

<s docid="AP900623-0119" num="1" wdcount="1"> AP900623-0119</s>
</DOCNO>
<FILEID>

<s docid="AP900623-0119" num="2" wdcount="2"> AP-NR-06-23-90 1829EDT</s>
</FILEID>
<FIRST>

<s docid="AP900623-0119" num="3" wdcount="5"> u i AM-Iran-Aid 06-23 0665</s>
</FIRST>
<SECOND>

<s docid="AP900623-0119" num="4" wdcount="1"> AM-Iran-Aid,0691</s>
</SECOND>
<HEAD>

<s docid="AP900623-0119" num="5" wdcount="7"> Friendly, Hostile Countries Send Aid To Iran</s>
</HEAD>
<HEAD>

<s docid="AP900623-0119" num="6" wdcount="3"> With AM-Iran Quake,Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP900623-0119" num="7" wdcount="3"> By JOHN WRIGHT</s>
</BYLINE>
<BYLINE>

<s docid="AP900623-0119" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<TEXT>

<s docid="AP900623-0119" num="9" wdcount="27"> Countries worldwide, both friendly and hostile to Tehran's Islamic government, sent supplies, medical personnel and condolences to Iran, where about 40,000 people have died in an earthquake.</s>

<s docid="AP900623-0119" num="10" wdcount="21"> Iran's deadliest earthquake since 1976 jolted the northern part of the country Thursday, devastating towns and injuring at least 100,000 people.</s>

<s docid="AP900623-0119" num="11" wdcount="16"> The United States sent a message of condolence and expressed its willingness to provide humanitarian aid.</s>

<s docid="AP900623-0119" num="12" wdcount="20"> Iran, which has had no diplomatic ties with the United States since the 1979 seizure of hostages at the U.S.</s>

<s docid="AP900623-0119" num="13" wdcount="18"> Embassy in Tehran, said it would welcome relief from the American Red Cross and other U.S. humanitarian groups.</s>

<s docid="AP900623-0119" num="14" wdcount="21"> Moderate Arab countries with which Iran has had prickly relations _ Egypt, Saudi Arabia and Jordan _ also offered their support.</s>

<s docid="AP900623-0119" num="15" wdcount="23"> An official statement distributed late Friday by the Saudi Press Agency said the kingdom followed with ``deep sorrow'' the news of the tragedy.</s>

<s docid="AP900623-0119" num="16" wdcount="6"> ``The kingdom of Saudi Arabia ...</s>

<s docid="AP900623-0119" num="17" wdcount="34"> declares its readiness to help in extending assistance to those harmed by the tragedy, wishing to help ease the pain of the afflicted from among the sons of the Iranian Moslem nation,'' it said.</s>

<s docid="AP900623-0119" num="18" wdcount="16"> Jordan announced Saturday it was sending medical aid to Iran, but details were not immediately clear.</s>

<s docid="AP900623-0119" num="19" wdcount="32"> King Hussein sent condolences to Iranian President Hashemi Rafsanjani on Friday in what is believed to be the first direct contact between Jordanian and Iranian heads of state in almost a decade.</s>

<s docid="AP900623-0119" num="20" wdcount="30"> Jordan backed Iraq in the eight-year Iran-Iraq war, which ended with a cease-fire in August 1988, and at one point sent hundreds of Jordanian volunteers to fight alongside Iraqi soldiers.</s>

<s docid="AP900623-0119" num="21" wdcount="14"> Egypt was sending two military planes with supplies, the Middle East News Agency reported.</s>

<s docid="AP900623-0119" num="22" wdcount="25"> President Hosni Mubarak offered the aid ``in the framework of Egypt's concern to provide help for brothers and friends, especially at times of natural disasters''.</s>

<s docid="AP900623-0119" num="23" wdcount="22"> The official Soviet news agency Tass reported that a professional lifesaving team from the Armenian capital of Yerevan flew Saturday to Iran.</s>

<s docid="AP900623-0119" num="24" wdcount="15"> The team gained experience in the devastating 1988 earthquake in Armenia that killed 25,000 people.</s>

<s docid="AP900623-0119" num="25" wdcount="33"> Thousands of residents in the predominantly Moslem Soviet republic of Azerbaijan, which borders Iran, donated tons of flour, rice and tea, and contributed more than $500,000 to a special earthquake fund, Tass said.</s>

<s docid="AP900623-0119" num="26" wdcount="18"> The Italian Red Cross sent a plane to Iran Saturday with relief supplies, including tents, blankets and medicine.</s>

<s docid="AP900623-0119" num="27" wdcount="37"> In Paris, the French government, which already has sent a 200-member civil defense team _ including rescuers, medical personnel and search dogs _ said Saturday it would send an entire mobile hospital unit if Iran wanted it.</s>

<s docid="AP900623-0119" num="28" wdcount="20"> In West Germany, the Foreign Ministry said that it was sending tents, blankets, hospital equipment and cooking equipment to Iran.</s>

<s docid="AP900623-0119" num="29" wdcount="21"> Eight tons was being shipped Saturday and the government has chartered a jumbo jet to transport 100 tons of equipment Monday.</s>

<s docid="AP900623-0119" num="30" wdcount="20"> At the Vatican, Pope John Paul II sent aid to earthquake victims and a message of condolence to Iranian leaders.</s>

<s docid="AP900623-0119" num="31" wdcount="29"> The Vatican said in a statement that the donation of an unspecified amount was to ``provide for the most immediate needs of the population hurt by this huge earthquake''.</s>

<s docid="AP900623-0119" num="32" wdcount="30"> John Paul also sent a telegram to the papal nuncio, or diplomatic representative, in Tehran saying the pope ``is praying fervently for the wounded and the families of the victims''.</s>

<s docid="AP900623-0119" num="33" wdcount="17"> The Indian government said it would donate medicine, blankets and other relief supplies worth more than $500,000.</s>

<s docid="AP900623-0119" num="34" wdcount="16"> China's Red Cross said it was sending $106,000 worth of relief supplies, state-run television said Saturday.</s>

<s docid="AP900623-0119" num="35" wdcount="31"> The Polish government was sending 5 tons of powdered milk, a ton of bed sheets, a ton of medicine and 3 tons of blankets and clothing, according to Polish media reports.</s>

<s docid="AP900623-0119" num="36" wdcount="9"> Malaysia was providing more than $90,000 in relief aid.</s>

<s docid="AP900623-0119" num="37" wdcount="26"> Foreign Ministry Secretary-General Ahmad Kamil Jaafar told reporters Saturday the money would be used to buy medicine, food, powdered milk, tents and other essential items .</s>
</TEXT>
</DOC>
