<DOC>
<DOCNO>

<s docid="LA062490-0172" num="1" wdcount="1"> LA062490-0172</s>
</DOCNO>
<DOCID>

<s docid="LA062490-0172" num="2" wdcount="1"> 238224</s>
</DOCID>
<DATE>
<P>

<s docid="LA062490-0172" num="3" wdcount="6"> June 24, 1990, Sunday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA062490-0172" num="4" wdcount="8"> Part A; Page 17; Column 1; Foreign Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA062490-0172" num="5" wdcount="2"> 467 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA062490-0172" num="6" wdcount="7"> SOVIET TRUCKS CARRY QUAKE AID TO IRAN;</s>
</P>
<P>

<s docid="LA062490-0172" num="7" wdcount="7"> NEIGHBORS: GORBACHEV SENDS CONDOLENCES, RESCUE CREWS, SUPPLIES.</s>

<s docid="LA062490-0172" num="8" wdcount="6"> AZERBAIJAN DECLARES DAY OF MOURNING .</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA062490-0172" num="9" wdcount="4"> From Times Wire Services</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA062490-0172" num="10" wdcount="1"> MOSCOW</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA062490-0172" num="11" wdcount="26"> Trucks carried aid into earthquake-stricken Iran on Saturday from Soviet Azerbaijan, which observed a day of mourning for victims, the official Tass news agency said .</s>
</P>
<P>

<s docid="LA062490-0172" num="12" wdcount="25"> President Mikhail S. Gorbachev sent his condolences to the Iranian leadership, and the Soviet Red Cross dispatched a plane carrying rescue workers and aid .</s>
</P>
<P>

<s docid="LA062490-0172" num="13" wdcount="28"> In his message to Iranian President Hashemi Rafsanjani, Gorbachev expressed his "deep condolences to the families and friends of those who lost their lives in the earthquake" .</s>
</P>
<P>

<s docid="LA062490-0172" num="14" wdcount="35"> A report by Tass from the Azerbaijan capital of Baku said an official day of mourning was declared in the mainly Muslim republic and that black ribbons hung from public buildings in the city .</s>
</P>
<P>

<s docid="LA062490-0172" num="15" wdcount="27"> A column of trucks carrying 100 doctors, 10,000 tons of food, clothing and equipment such as welding gear left the town of Nakhicheva near the border .</s>
</P>
<P>

<s docid="LA062490-0172" num="16" wdcount="31"> Tass said people in Azerbaijan, many of whom are Shiite Muslims who feel a kinship with people of their faith in Iran, poured money into a public fund for earthquake victims.</s>

<s docid="LA062490-0172" num="17" wdcount="7"> Other volunteers donated blood, it said .</s>
</P>
<P>

<s docid="LA062490-0172" num="18" wdcount="19"> A Soviet Red Cross official said a plane left Moscow carrying relief aid, nine doctors and rescue workers .</s>
</P>
<P>

<s docid="LA062490-0172" num="19" wdcount="16"> In December, 1988, a powerful earthquake killed 25,000 people in Soviet Armenia, which borders Azerbaijan .</s>
</P>
<P>

<s docid="LA062490-0172" num="20" wdcount="16"> Also on Saturday, aid continued to pour into Iran from other parts of the world .</s>
</P>
<P>

<s docid="LA062490-0172" num="21" wdcount="17"> A 205-member French relief team arrived Friday night, according to Iran's official Islamic Republic News Agency (IRNA).</s>

<s docid="LA062490-0172" num="22" wdcount="20"> West Germany said it was sending 200 tents and 3,200 blankets, to be followed by 100 tons of similar supplies.</s>

<s docid="LA062490-0172" num="23" wdcount="13"> Jordan and Kuwait also said they are sending planeloads of relief aid .</s>
</P>
<P>

<s docid="LA062490-0172" num="24" wdcount="32"> The European Community has granted $1.2 million in emergency aid, and Japan is reportedly sending between $500,000 and $1 million in cash as well as a 22-member medical and rescue squad .</s>
</P>
<P>

<s docid="LA062490-0172" num="25" wdcount="26"> The United States on Friday sent $300,000 worth of relief supplies through the American Red Cross and is planning more aid, State Department officials said .</s>
</P>
<P>

<s docid="LA062490-0172" num="26" wdcount="25"> Pope John Paul II was "very saddened" by the earthquake and has donated personal funds to help victims of the disaster, the Vatican said .</s>
</P>
<P>

<s docid="LA062490-0172" num="27" wdcount="28"> Spokesman Joaquin Navarro did not specify the amount, but in the past the Pope has sent as much as $100,000 for disaster relief from his personal funds .</s>
</P>
<P>

<s docid="LA062490-0172" num="28" wdcount="23"> Other assistance reportedly was due from Holland, Turkey, Greece, Pakistan, Belgium, Finland, India, Bangladesh, Yugoslavia, Sri Lanka, Kuwait and several other nations .</s>
</P>
<P>

<s docid="LA062490-0172" num="29" wdcount="17"> Iranian officials have said they would welcome aid from all countries except Israel and South Africa .</s>
</P>
<P>

<s docid="LA062490-0172" num="30" wdcount="18"> However, Egyptian officials in Cairo said Iran rejected an Egyptian offer to send a planeload of medical supplies.</s>

<s docid="LA062490-0172" num="31" wdcount="17"> A source at the Foreign Ministry said Iran rejected the supplies, saying it needed heavy equipment .</s>
</P>
</TEXT>
<TYPE>
<P>

<s docid="LA062490-0172" num="32" wdcount="1"> Wire</s>
</P>
</TYPE>
<SUBJECT>
<P>

<s docid="LA062490-0172" num="33" wdcount="22"> EARTHQUAKES -- RELIEF; IRAN -- RELIEF; DISASTERS -- RELIEF; RELIEF ORGANIZATIONS; DISASTER RELIEF; GORBACHEV, MIKHAIL S; IRAN -- FOREIGN RELATIONS -- USSR</s>
</P>
</SUBJECT>
</DOC>
