<DOC>
<DOCNO>

<s docid="LA062390-0001" num="1" wdcount="1"> LA062390-0001</s>
</DOCNO>
<DOCID>

<s docid="LA062390-0001" num="2" wdcount="1"> 237494</s>
</DOCID>
<DATE>
<P>

<s docid="LA062390-0001" num="3" wdcount="8"> June 23, 1990, Saturday, San Diego County Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA062390-0001" num="4" wdcount="8"> Part A; Page 1; Column 6; Metro Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA062390-0001" num="5" wdcount="2"> 630 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA062390-0001" num="6" wdcount="7"> SAN DIEGANS AWAIT WORD ON IRAN RELATIVES</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA062390-0001" num="7" wdcount="7"> By LINDA ROACH MONROE, TIMES STAFF WRITER</s>
</P>
</BYLINE>
<TEXT>
<P>

<s docid="LA062390-0001" num="8" wdcount="34"> Shortly after 2 p.m. Wednesday, San Diego resident Mohammad Nyakoui got a call from his wife, who is spending the summer in the Caspian Sea coastal city of Rasht, Iran, with her family .</s>
</P>
<P>

<s docid="LA062390-0001" num="9" wdcount="19"> "I asked her what she was doing, and she said she was watching the World Cup," Nyakoui recalls .</s>
</P>
<P>

<s docid="LA062390-0001" num="10" wdcount="24"> About 15 minutes after she hung up, Rasht and other cities in Iran's northern region were rocked by an earthquake that killed thousands .</s>
</P>
<P>

<s docid="LA062390-0001" num="11" wdcount="17"> Back home in San Diego, it was several hours before Nyakoui even heard news of the quake.</s>

<s docid="LA062390-0001" num="12" wdcount="22"> When he did, some quick time-zone arithmetic showed that he had talked to his wife just minutes before the quake happened .</s>
</P>
<P>

<s docid="LA062390-0001" num="13" wdcount="6"> "I was very worried," Nyakoui said.</s>

<s docid="LA062390-0001" num="14" wdcount="22"> "I tried through the Red Cross to call Iran, but they told us they couldn't do anything before 48 hours passed" .</s>
</P>
<P>

<s docid="LA062390-0001" num="15" wdcount="45"> One of about 25,000 San Diego Iranians in the same anxious state, Nyakoui was luckier than most: His wife managed to call him a second time that day, about eight hours after the quake, to tell him she and their two children were safe .</s>
</P>
<P>

<s docid="LA062390-0001" num="16" wdcount="12"> Phone lines remained jammed Friday, other Iranian-Americans in San Diego said .</s>
</P>
<P>

<s docid="LA062390-0001" num="17" wdcount="5"> "There's a sense of panic.</s>

<s docid="LA062390-0001" num="18" wdcount="19"> It's just impossible to get through," said Houshang Ghashghai, who teaches political science at San Diego State University .</s>
</P>
<P>

<s docid="LA062390-0001" num="19" wdcount="20"> Already though, some of the worried immigrants were turning their fear into action by mobilizing relief efforts for Iran .</s>
</P>
<P>

<s docid="LA062390-0001" num="20" wdcount="30"> Hamid Biglari, a theoretical physicist at UC San Diego, was among those who organized a local group to gather contributions for the United Nations Fund for the Iran Earthquake .</s>
</P>
<P>

<s docid="LA062390-0001" num="21" wdcount="10"> The group has set up two offices and phone lines.</s>

<s docid="LA062390-0001" num="22" wdcount="17"> They are collecting medicine, food and a variety of living supplies, including blankets, light clothing and flashlights.</s>

<s docid="LA062390-0001" num="23" wdcount="12"> The supplies will be transported by the United Nations, Biglari said .</s>
</P>
<P>

<s docid="LA062390-0001" num="24" wdcount="30"> Another group gathering medical supplies is Southwest Medical Teams, an organization whose last major international effort was sending volunteers and medical supplies to Armenia after the 1988 quake there .</s>
</P>
<P>

<s docid="LA062390-0001" num="25" wdcount="16"> Southwest Medical Teams won't be sending any volunteers this time, said director Barry La Forgia .</s>
</P>
<P>

<s docid="LA062390-0001" num="26" wdcount="8"> "That's at the advice of the State Department.</s>

<s docid="LA062390-0001" num="27" wdcount="21"> They couldn't ensure our safety over there, and we don't want to endanger any of our volunteers," La Forgia said .</s>
</P>
<P>

<s docid="LA062390-0001" num="28" wdcount="4"> WHERE TO SEND AID</s>
</P>
<P>

<s docid="LA062390-0001" num="29" wdcount="14"> Donations for Iranian earthquake relief are being taken in San Diego by two groups:</s>
</P>
<P>

<s docid="LA062390-0001" num="30" wdcount="40"> United Nations Fund for the Iran Earthquake (467-1120 or 456-4000) -- Collecting antibiotic and analgesic drugs, collapsible plastic water containers, plastic sheeting, 220-volt portable generators of less than 10 kilowatts, tents, blankets, dry food, light clothing, flashlights and lighting equipment.</s>

<s docid="LA062390-0001" num="31" wdcount="25"> Bring items or mail checks to 4540 Kearny Villa Road, Suite 214, San Diego 92123; or to 7509 Girard Ave., Suite A, La Jolla 92037.</s>

<s docid="LA062390-0001" num="32" wdcount="8"> Checks should be made out to the U.N.</s>

<s docid="LA062390-0001" num="33" wdcount="6"> Fund for the Iran Earthquake .</s>
</P>
<P>

<s docid="LA062390-0001" num="34" wdcount="23"> Southwest Medical Teams (284-7979) -- Through Thursday, collecting sutures, surgical gloves, antibiotics, analgesics (including aspirin), vitamins, ophthalmic solutions and empty blood collection bags.</s>

<s docid="LA062390-0001" num="35" wdcount="6"> Shipment will be sent July 2.</s>

<s docid="LA062390-0001" num="36" wdcount="13"> Cash donations will be used to pay to fly the supplies to Iran.</s>

<s docid="LA062390-0001" num="37" wdcount="23"> Mail checks to 3547 Camino del Rio South, Suite C, San Diego 92108, noting that donation is for Iranian Earthquake Relief Fund .</s>
</P>
<P>

<s docid="LA062390-0001" num="38" wdcount="8"> Other agencies accepting donations for Iranian earthquake victims:</s>
</P>
<P>

<s docid="LA062390-0001" num="39" wdcount="5"> Adventist Development and Relief Agency</s>
</P>
<P>

<s docid="LA062390-0001" num="40" wdcount="4"> 12501 Old Columbia Pike</s>
</P>
<P>

<s docid="LA062390-0001" num="41" wdcount="4"> Silver Spring, Md. 20904</s>
</P>
<P>

<s docid="LA062390-0001" num="42" wdcount="2"> (301) 680-6380</s>
</P>
<P>

<s docid="LA062390-0001" num="43" wdcount="3"> American Red Cross</s>
</P>
<P>

<s docid="LA062390-0001" num="44" wdcount="3"> Iran Earthquake Disaster</s>
</P>
<P>

<s docid="LA062390-0001" num="45" wdcount="3"> P.O. Box 37243</s>
</P>
<P>

<s docid="LA062390-0001" num="46" wdcount="3"> Washington, D.C. 20013</s>
</P>
<P>

<s docid="LA062390-0001" num="47" wdcount="2"> (800) 842-2200</s>
</P>
<P>

<s docid="LA062390-0001" num="48" wdcount="3"> Bank Melli Iran</s>
</P>
<P>

<s docid="LA062390-0001" num="49" wdcount="4"> Iran Quake Relief Assistance</s>
</P>
<P>

<s docid="LA062390-0001" num="50" wdcount="3"> Account No. 5000</s>
</P>
<P>

<s docid="LA062390-0001" num="51" wdcount="4"> 628 Madison Ave .</s>
</P>
<P>

<s docid="LA062390-0001" num="52" wdcount="4"> New York, N.Y. 10022</s>
</P>
<P>

<s docid="LA062390-0001" num="53" wdcount="4"> U.S. Committee for UNICEF</s>
</P>
<P>

<s docid="LA062390-0001" num="54" wdcount="5"> 333 E. 38th St .</s>
</P>
<P>

<s docid="LA062390-0001" num="55" wdcount="4"> New York, N.Y. 10016</s>
</P>
<P>

<s docid="LA062390-0001" num="56" wdcount="2"> (212) 686-5522</s>
</P>
</TEXT>
</DOC>
