<DOC>
<DOCNO>

<s docid="LA062690-0155" num="1" wdcount="1"> LA062690-0155</s>
</DOCNO>
<DOCID>

<s docid="LA062690-0155" num="2" wdcount="1"> 239212</s>
</DOCID>
<DATE>
<P>

<s docid="LA062690-0155" num="3" wdcount="6"> June 26, 1990, Tuesday, P.M. Final</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA062690-0155" num="4" wdcount="9"> Part P; Page 2; Column 1; Late Final Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA062690-0155" num="5" wdcount="2"> 212 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA062690-0155" num="6" wdcount="1"> WORLD;</s>
</P>
<P>

<s docid="LA062690-0155" num="7" wdcount="9"> RUSHDIE DONATES QUAKE AID; IRAN SAYS HE'S STILL DOOMED</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA062690-0155" num="8" wdcount="5"> By FROM TIMES WIRE SERVICES</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA062690-0155" num="9" wdcount="1"> LONDON</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA062690-0155" num="10" wdcount="24"> Writer Salman Rushdie, who has been sentenced to die by Iranian zealots, has donated $8,600 to victims of last week's devastating earthquake in Iran.</s>

<s docid="LA062690-0155" num="11" wdcount="9"> Iran said today his death order still stands .</s>
</P>
<P>

<s docid="LA062690-0155" num="12" wdcount="32"> Rushdie donated the money to the Independent Iranian Earthquake Appeal, organized by the Independent newspaper to help survivors of the earthquake that Iranian officials said left at least 50,000 people dead .</s>
</P>
<P>

<s docid="LA062690-0155" num="13" wdcount="38"> "I wanted to join the Independent and the hostage families and many other people in their appeal for contributions toward the needs of the Iranian earthquake victims," Rushdie said in a message delivered from his hiding place .</s>
</P>
<P>

<s docid="LA062690-0155" num="14" wdcount="25"> "It's quite clear that at the moment, we should be thinking only of the humanitarian issue, which transcends all other discussion," said Rushdie, 42 .</s>
</P>
<P>

<s docid="LA062690-0155" num="15" wdcount="36"> The Indian-born writer has been out of public view since Feb. 14, 1989, when the late Ayatollah Ruhollah Khomeini sentenced him to death for writing "The Satanic Verses," a novel many Muslims regard as blasphemous .</s>
</P>
<P>

<s docid="LA062690-0155" num="16" wdcount="36"> "The foreign media seems to think that by publishing news of aid from Salman Rushdie to earthquake victims, we will compromise on Rushdie's fatwa (edict)," Ayatollah Sadeq Khalkhali, known as the "Hanging Judge," said in Tehran.</s>

<s docid="LA062690-0155" num="17" wdcount="6"> He indicated they would not .</s>
</P>
</TEXT>
<TYPE>
<P>

<s docid="LA062690-0155" num="18" wdcount="2"> Brief; Wire</s>
</P>
</TYPE>
</DOC>
