<DOC>
<DOCNO>

<s docid="AP880808-0039" num="1" wdcount="1"> AP880808-0039</s>
</DOCNO>
<FILEID>

<s docid="AP880808-0039" num="2" wdcount="2"> AP-NR-08-08-88 0617EDT</s>
</FILEID>
<FIRST>

<s docid="AP880808-0039" num="3" wdcount="7"> u i PM-India-Ferry 1stLd-Writethru a0470 08-08 0753</s>
</FIRST>
<SECOND>

<s docid="AP880808-0039" num="4" wdcount="6"> PM-India-Ferry, 1st Ld - Writethru, a0470,0778</s>
</SECOND>
<HEAD>

<s docid="AP880808-0039" num="5" wdcount="8"> Currents Hamper Recovery; Official Blames Overcrowding, Safety Violations</s>
</HEAD>
<NOTE>

<s docid="AP880808-0039" num="6" wdcount="23"> Eds: LEADS with 23 grafs to UPDATE with official citing overcrowding and safety violations as cause of accident, families criticizing government, witness account.</s>

<s docid="AP880808-0039" num="7" wdcount="8"> Picks up 13th graf pvs `It was ...'</s>
</NOTE>
<BYLINE>

<s docid="AP880808-0039" num="8" wdcount="3"> By DILIP GANGULY</s>
</BYLINE>
<BYLINE>

<s docid="AP880808-0039" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880808-0039" num="10" wdcount="3"> KATIHAR, India (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880808-0039" num="11" wdcount="24"> Overcrowding and safety violations caused an aging ferry to capsize in the Ganges River, killing as many as 400 people, a government report said.</s>

<s docid="AP880808-0039" num="12" wdcount="10"> The ferry accident was said to be India's worst ever.</s>

<s docid="AP880808-0039" num="13" wdcount="14"> Strong currents hampered efforts today to pull the two-decker from the rising monsoon-swollen river.</s>

<s docid="AP880808-0039" num="14" wdcount="6"> Hundreds of relatives stood by watching.</s>

<s docid="AP880808-0039" num="15" wdcount="30"> A senior government official, discussing the confidential report on condition of anonymity, said authorities believed at least 300 people on the lower deck died when the ferry overturned Saturday morning.</s>

<s docid="AP880808-0039" num="16" wdcount="10"> About 200 people were on the upper deck, he said.</s>

<s docid="AP880808-0039" num="17" wdcount="13"> Authorities believe about 100 people swam to safety or were rescued by villagers.</s>

<s docid="AP880808-0039" num="18" wdcount="20"> Only about a dozen bodies have been found, and most of the missing were believed trapped inside the 35-year-old ferry.</s>

<s docid="AP880808-0039" num="19" wdcount="4"> ``It was badly overcrowded.</s>

<s docid="AP880808-0039" num="20" wdcount="13"> The situation was made more dangerous by wheat bags loaded on the ferry.</s>

<s docid="AP880808-0039" num="21" wdcount="22"> Many lives could have been saved if the ferry had carried water safety equipment such as life jackets,'' said the senior official.</s>

<s docid="AP880808-0039" num="22" wdcount="14"> Survivors said they protested when 150 bags of wheat were loaded onto the ferry.</s>

<s docid="AP880808-0039" num="23" wdcount="19"> The steam-powered vessel started wavering soon after it left the banks and capsized about 100 yards from the shore.</s>

<s docid="AP880808-0039" num="24" wdcount="29"> Navy divers attempted to reach the submerged boat today, but the river was too muddy and its current too swift, said H.S. Pathak, head of the eight-member diving team.</s>

<s docid="AP880808-0039" num="25" wdcount="21"> ``We are trying our best, but because of the current, we are not able to go near the launch,'' Pathak said.</s>

<s docid="AP880808-0039" num="26" wdcount="5"> ``The water is too muddy.</s>

<s docid="AP880808-0039" num="27" wdcount="13"> We can't see anything, so we just have to feel by our hands''.</s>

<s docid="AP880808-0039" num="28" wdcount="17"> Authorities said the water was still rising and the submerged boat was sinking in the river bed.</s>

<s docid="AP880808-0039" num="29" wdcount="10"> The water depth was estimated at 12 to 30 feet.</s>

<s docid="AP880808-0039" num="30" wdcount="16"> Katihar Commissioner Madan Mohan Singh estimated the boat was resting in about six feet of sand.</s>

<s docid="AP880808-0039" num="31" wdcount="7"> ``We are planning to break the ferry.</s>

<s docid="AP880808-0039" num="32" wdcount="13"> Only then will we be able to get the bodies out,'' Singh said.</s>

<s docid="AP880808-0039" num="33" wdcount="16"> Katihar District Police Chief P.S. Natarajah said chances of finding any survivors were ``very, very dim''.</s>

<s docid="AP880808-0039" num="34" wdcount="24"> He said the death toll may never be known because some bodies probably were carried downstream 30 to 60 miles by the surging water.</s>

<s docid="AP880808-0039" num="35" wdcount="16"> The ferry was designed to carry about 160 people, but was was always overcrowded, he said.</s>

<s docid="AP880808-0039" num="36" wdcount="16"> Jetty workers, who spoke on condition of anonymity, said 535 tickets were sold for the trip.</s>

<s docid="AP880808-0039" num="37" wdcount="23"> Katihar Police Inspector N. Kumar said about 2,000 relatives and residents were waiting along the rain-swollen river for the bodies to be recovered.</s>

<s docid="AP880808-0039" num="38" wdcount="12"> ``Police are trying to control the crowds and console them,'' he said.</s>

<s docid="AP880808-0039" num="39" wdcount="13"> Family members railed against authorities as numerous officials arrived to review recovery efforts.</s>

<s docid="AP880808-0039" num="40" wdcount="5"> ``Give back our family members.</s>

<s docid="AP880808-0039" num="41" wdcount="7"> We don't want (government) ministers,'' they shouted.</s>

<s docid="AP880808-0039" num="42" wdcount="4"> One survivor, Chadrasekhar D.</s>

<s docid="AP880808-0039" num="43" wdcount="14"> Tiwary, said he was standing on the ferry's upper deck when it started wavering.</s>

<s docid="AP880808-0039" num="44" wdcount="12"> ``As soon as the ferry tilted, I knew we were going down.</s>

<s docid="AP880808-0039" num="45" wdcount="7"> I saw three women crying for help.</s>

<s docid="AP880808-0039" num="46" wdcount="7"> They probably drowned,'' the 50-year-old farmer said.</s>

<s docid="AP880808-0039" num="47" wdcount="13"> Ram Prasad Yadaw's wife and four other family members vanished in the accident.</s>

<s docid="AP880808-0039" num="48" wdcount="7"> ``The women and children suffered the worst.</s>

<s docid="AP880808-0039" num="49" wdcount="10"> They had to sit on the lower deck,'' he said.</s>

<s docid="AP880808-0039" num="50" wdcount="7"> ``I am sure my wife is dead''.</s>

<s docid="AP880808-0039" num="51" wdcount="16"> It was the worst boat accident ever in India, according to the United News of India.</s>

<s docid="AP880808-0039" num="52" wdcount="19"> At least 150 people died on July 5, 1970, when a boat capsized in Krishna River in eastern India.</s>

<s docid="AP880808-0039" num="53" wdcount="16"> The Navy divers came from New Delhi, the Indian capital about 650 miles west of Katihar.</s>

<s docid="AP880808-0039" num="54" wdcount="14"> Mangan Chand, a police officer, said only one body surfaced near the ferry Sunday.</s>

<s docid="AP880808-0039" num="55" wdcount="12"> Ten to 12 bodies were found Saturday, according to Bihar state officials.</s>

<s docid="AP880808-0039" num="56" wdcount="10"> Chand said his father and uncle were aboard the ferry.</s>

<s docid="AP880808-0039" num="57" wdcount="17"> He said he was waiting for the bodies so he could cremate them according to Hindu rites.</s>

<s docid="AP880808-0039" num="58" wdcount="24"> The boat trip is normally used by Hindu pilgrims going across the river to worship at a shrine of Lord Shiva in Deoghar town.</s>

<s docid="AP880808-0039" num="59" wdcount="10"> Lord Shiva is the destroyer diety in the Hindu trinity.</s>

<s docid="AP880808-0039" num="60" wdcount="16"> Boat accidents are common during the annual monsoon rains when major rivers overflow their banks .</s>
</TEXT>
</DOC>
