<DOC>
<DOCNO>

<s docid="AP881218-0007" num="1" wdcount="1"> AP881218-0007</s>
</DOCNO>
<FILEID>

<s docid="AP881218-0007" num="2" wdcount="2"> AP-NR-12-18-88 0020EST</s>
</FILEID>
<FIRST>

<s docid="AP881218-0007" num="3" wdcount="5"> u i AM-FerrySinks 12-18 0248</s>
</FIRST>
<SECOND>

<s docid="AP881218-0007" num="4" wdcount="2"> AM-Ferry Sinks,0252</s>
</SECOND>
<HEAD>

<s docid="AP881218-0007" num="5" wdcount="11"> Overloaded Boat Sinks in South China, 55 Die and Seven Missing</s>
</HEAD>
<DATELINE>

<s docid="AP881218-0007" num="6" wdcount="3"> HONG KONG (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP881218-0007" num="7" wdcount="32"> An overloaded ferry taking schoolchildren on a field trip capsized and sank in southern China, killing 55 people and leaving seven missing, the China News Service said in a dispatch seen Sunday.</s>

<s docid="AP881218-0007" num="8" wdcount="26"> The 183 passengers and four crew members ``enormously exceeded'' the ferry's capacity and the ship capsized Wednesday before it had sailed 200 yards, the report said.</s>

<s docid="AP881218-0007" num="9" wdcount="13"> It did not say how many people the boat was designed to hold.</s>

<s docid="AP881218-0007" num="10" wdcount="19"> It said that by Friday, 125 survivors had been rescued, 55 bodies were found and seven people were missing.</s>

<s docid="AP881218-0007" num="11" wdcount="9"> The accident occurred off Hainan island, the report said.</s>

<s docid="AP881218-0007" num="12" wdcount="34"> The news service said the passengers were 183 students and teachers from a high school and primary school in Qiongzhong County, who were going to take the ferry to visit a hydroelectric power station.</s>

<s docid="AP881218-0007" num="13" wdcount="22"> On September 22, another overloaded ferry sank in the Guangxi Zhuang Autonomous Region bordering Vietnam, leaving 61 people dead and one missing.</s>

<s docid="AP881218-0007" num="14" wdcount="33"> The Ministry of Communications, which is responsible for inland water navigation, announced in August it had begun an investigation into the safety of China's river vessels to determine if standards should be tightened.</s>

<s docid="AP881218-0007" num="15" wdcount="42"> The move followed the July 21 capsizing of a ferry on the Min River in Southwestern Sichuan province in which 133 people died, and the July 25 sinking of a passenger boat on the Yangtze River in which 71 people drowned .</s>
</TEXT>
</DOC>
