<DOC>
<DOCNO>

<s docid="AP881027-0051" num="1" wdcount="1"> AP881027-0051</s>
</DOCNO>
<FILEID>

<s docid="AP881027-0051" num="2" wdcount="2"> AP-NR-10-27-88 0246EDT</s>
</FILEID>
<FIRST>

<s docid="AP881027-0051" num="3" wdcount="5"> r i PM-Bangladesh 10-27 0339</s>
</FIRST>
<SECOND>

<s docid="AP881027-0051" num="4" wdcount="1"> PM-Bangladesh,0348</s>
</SECOND>
<HEAD>

<s docid="AP881027-0051" num="5" wdcount="10"> 100 Feared Drowned In Ferry Sinking, Pirates Attack Second Boat</s>
</HEAD>
<BYLINE>

<s docid="AP881027-0051" num="6" wdcount="3"> By FARID HOSSAIN</s>
</BYLINE>
<BYLINE>

<s docid="AP881027-0051" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP881027-0051" num="8" wdcount="3"> DHAKA, Bangladesh (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP881027-0051" num="9" wdcount="22"> More than 100 people were feared drowned after an overcrowded ferry sank at a river junction in southern Bangladesh, police said today.</s>

<s docid="AP881027-0051" num="10" wdcount="32"> Fifteen bodies were recovered and 94 people were reported missing in the sinking Wednesday night where the Ilisha and Tetulia rivers meet and join the Meghna, police and a district administrator said.</s>

<s docid="AP881027-0051" num="11" wdcount="13"> Another ferry was attacked by river pirates near Chandpur late Tuesday, police said.</s>

<s docid="AP881027-0051" num="12" wdcount="17"> Six passengers, including a pregnant woman, were thrown overboard and have not been found, Chandpur police said.</s>

<s docid="AP881027-0051" num="13" wdcount="25"> About 200 passengers were wounded when the pirates fired rifles and hurled homemade bombs before making off with about $83,000 in local currency, police said.</s>

<s docid="AP881027-0051" num="14" wdcount="17"> The ferry that sank was carrying more than double its authorized capacity of 100 passengers, police said.</s>

<s docid="AP881027-0051" num="15" wdcount="24"> They said about 100 people on the ferry's roof swam to safety but most of those in the hull were unable to save themselves.</s>

<s docid="AP881027-0051" num="16" wdcount="26"> The ferry was traveling from Mehendiganj to the island town of Bhola, about 68 miles southeast of Dhaka, when it sank in 22 feet of water.</s>

<s docid="AP881027-0051" num="17" wdcount="25"> Police said six bodies were found in the hull of the ferry, the M.L. Sonali, and nine others were found more than a mile downstream.</s>

<s docid="AP881027-0051" num="18" wdcount="24"> Two independent newspapers in Dhaka, Ittefaq and Sangbad, quoted survivors as saying the ferry went out of control while trying to negotiate a turn.</s>

<s docid="AP881027-0051" num="19" wdcount="16"> The pirate attack on the second ferry, the M.V. Sagar, also occurred on the Meghna River.</s>

<s docid="AP881027-0051" num="20" wdcount="23"> The Sagar was en route from Dhaka to Barisal when about 50 pirates launched their attack near Chandpur, 34 miles southeast of Dhaka.</s>

<s docid="AP881027-0051" num="21" wdcount="29"> The pirates, who had boarded the ferry as passengers, opened fire and exploded bombs shortly before midnight Tuesday as people were bedding down for the night, Chandpur police said.</s>

<s docid="AP881027-0051" num="22" wdcount="9"> The attackers escaped in waiting boats, the police added.</s>

<s docid="AP881027-0051" num="23" wdcount="15"> They said 44 of the injured passengers were hospitalized, including four in critical condition .</s>
</TEXT>
</DOC>
