<DOC>
<DOCNO>

<s docid="AP890103-0029" num="1" wdcount="1"> AP890103-0029</s>
</DOCNO>
<FILEID>

<s docid="AP890103-0029" num="2" wdcount="2"> AP-NR-01-03-89 0136EST</s>
</FILEID>
<FIRST>

<s docid="AP890103-0029" num="3" wdcount="5"> r i PM-Guatemala-Ferry 01-03 0365</s>
</FIRST>
<SECOND>

<s docid="AP890103-0029" num="4" wdcount="1"> PM-Guatemala-Ferry,0376</s>
</SECOND>
<HEAD>

<s docid="AP890103-0029" num="5" wdcount="9"> Captain Charged in Ferry Sinking that Left 67 Dead</s>
</HEAD>
<BYLINE>

<s docid="AP890103-0029" num="6" wdcount="4"> By DOUGLAS GRANT MINE</s>
</BYLINE>
<BYLINE>

<s docid="AP890103-0029" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890103-0029" num="8" wdcount="3"> GUATEMALA CITY (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890103-0029" num="9" wdcount="22"> Authorities charged a 22-year-old ferry captain with negligent homicide after the boat, overcrowded with New Year's travelers, sank off the Caribbean coast.</s>

<s docid="AP890103-0029" num="10" wdcount="7"> Sixty-seven people drowned and 14 were missing.</s>

<s docid="AP890103-0029" num="11" wdcount="22"> Officials said 46 people survived the sinking of the ferry Justo Rufino Barrios II in Amatique Bay on Guatemala's east coast Sunday.</s>

<s docid="AP890103-0029" num="12" wdcount="35"> Juan Pablo Ezquibel was arrested after authorities determined that about 120 people were aboard the 30-ton ferry, which was authorized to carry 90, said Capt. Anibal Giron Arreola, second-in-command at the Puerto Barrios naval base.</s>

<s docid="AP890103-0029" num="13" wdcount="37"> He said by telephone that the ferry ran out of fuel midway on a 16-mile run across the bay from Livingston to Puerto Barrios and sank after a naval patrol boat tried to tow it to port.</s>

<s docid="AP890103-0029" num="14" wdcount="44"> Officials had yet to determine the exact cause of the sinking, but Giron Arreola said the ferry captain was slow to respond to requests by the skipper of the naval patrol boat to take control of the ferry's wheel once it was under tow.</s>

<s docid="AP890103-0029" num="15" wdcount="15"> He said the patrol boat captain believed the ferry's rudder was unmanned while under tow.</s>

<s docid="AP890103-0029" num="16" wdcount="18"> Esquibel radioed that he had taken the wheel just as the boat began to capsize, Giron Arreola said.</s>

<s docid="AP890103-0029" num="17" wdcount="23"> Giron Arreola also said that passengers ran to one side of the ferry while it was under tow just before the ferry sank.</s>

<s docid="AP890103-0029" num="18" wdcount="24"> ``It appears the boat rode a wave and that as it was leaning the people ran to one side out of fear,'' he said.</s>

<s docid="AP890103-0029" num="19" wdcount="16"> Although seas were only 1-to-1 feet, passengers were not used to traveling by sea, he said.</s>

<s docid="AP890103-0029" num="20" wdcount="7"> No Americans were on board, he said.</s>

<s docid="AP890103-0029" num="21" wdcount="8"> A morgue official said 13 bodies were identified.</s>

<s docid="AP890103-0029" num="22" wdcount="14"> Navy patrol boats, fishing vessels and other private craft searched for the missing Monday.</s>

<s docid="AP890103-0029" num="23" wdcount="16"> Puerto Barrios, 187 miles northeast of Guatemala City, the capital, is Guatemala's main east coast port.</s>

<s docid="AP890103-0029" num="24" wdcount="15"> There are no roads to Livingston and most travel along the coast is by boat.</s>

<s docid="AP890103-0029" num="25" wdcount="20"> The Rufino Barrios Maritime Transport firm owns the ferry and operates two other ferries along the Livingston-Puerto Barrios route .</s>
</TEXT>
</DOC>
