<DOC>
<DOCNO>

<s docid="AP890102-0076" num="1" wdcount="1"> AP890102-0076</s>
</DOCNO>
<FILEID>

<s docid="AP890102-0076" num="2" wdcount="2"> AP-NR-01-02-89 1334EST</s>
</FILEID>
<FIRST>

<s docid="AP890102-0076" num="3" wdcount="7"> u i PM-Guatemala-Shipwreck 1stLd-Writethru a0527 01-02 0278</s>
</FIRST>
<SECOND>

<s docid="AP890102-0076" num="4" wdcount="4"> PM-Guatemala-Shipwreck, 1st Ld-Writethru, a0527,0285</s>
</SECOND>
<HEAD>

<s docid="AP890102-0076" num="5" wdcount="1"> URGENT</s>
</HEAD>
<HEAD>

<s docid="AP890102-0076" num="6" wdcount="7"> Guatemalan Ferry Sinks; 59 Dead, Six Missing</s>
</HEAD>
<HEAD>

<s docid="AP890102-0076" num="7" wdcount="9"> Eds: Updates with name of Spanish victim, other details.</s>

<s docid="AP890102-0076" num="8" wdcount="5"> CORRECTS spelling to Puerto Barrios.</s>

<s docid="AP890102-0076" num="9" wdcount="2"> No pickup.</s>

<s docid="AP890102-0076" num="10" wdcount="3"> Adds byline .</s>
</HEAD>
<BYLINE>

<s docid="AP890102-0076" num="11" wdcount="3"> By ALFONSO ANZUETO</s>
</BYLINE>
<BYLINE>

<s docid="AP890102-0076" num="12" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890102-0076" num="13" wdcount="3"> GUATEMALA CITY (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890102-0076" num="14" wdcount="27"> A passenger ferry sank off the Caribbean coast while being towed to port, and 59 people drowned and six are missing, authorities and news reports said today.</s>

<s docid="AP890102-0076" num="15" wdcount="25"> Capt. Anibal Giron Arreola, a spokesman at the Puerto Barrios naval base, said the ferry Justo Rufino Barrios II sank Sunday afternoon in Amatique Bay.</s>

<s docid="AP890102-0076" num="16" wdcount="8"> He said by telephone that 59 people died.</s>

<s docid="AP890102-0076" num="17" wdcount="37"> Juan Jose Gaytan, a reporter at Radio Portena in Puerto Barrios, said the Justo Rufineo Barrios II ran out of fuel midway on a regular 16-mile run from the town Livingston, across the bay, to Puerto Barrios.</s>

<s docid="AP890102-0076" num="18" wdcount="13"> Gaytan said the boat sank while it was being towed by a tugboat.</s>

<s docid="AP890102-0076" num="19" wdcount="21"> The Spanish Embassy in Guatemala City confirmed the sinking and said a 40-year-old Spanish citizen, Vicente Daudi, was among the dead.</s>

<s docid="AP890102-0076" num="20" wdcount="19"> The embassy reported his wife, Rosa Maria Arnal, and a son survived the shipwreck, but two daughters were missing.</s>

<s docid="AP890102-0076" num="21" wdcount="17"> Daudi was working with a Spanish technical aid and economic development mission in Guatemala, the embassy said.</s>

<s docid="AP890102-0076" num="22" wdcount="13"> An official at the Puerto Barrios morgue said 13 bodies have been identified.</s>

<s docid="AP890102-0076" num="23" wdcount="11"> Besides Daudi, the nationalities of the victims were not immediately known.</s>

<s docid="AP890102-0076" num="24" wdcount="20"> Gaytan said navy patrol boats, fishing vessels and private craft have been searching the bay for survivors and recovering bodies.</s>

<s docid="AP890102-0076" num="25" wdcount="10"> He said he had no other details on the shipwreck.</s>

<s docid="AP890102-0076" num="26" wdcount="15"> Puerto Barrios, 187 miles northeast of the capital, is Guatemala's principal east coast port .</s>
</TEXT>
</DOC>
