<DOC>
<DOCNO>

<s docid="AP901222-0078" num="1" wdcount="1"> AP901222-0078</s>
</DOCNO>
<FILEID>

<s docid="AP901222-0078" num="2" wdcount="2"> AP-NY-12-22-90 1313EST</s>
</FILEID>
<FIRST>

<s docid="AP901222-0078" num="3" wdcount="5"> u i AM-Gulf-Survivors 12-22 0545</s>
</FIRST>
<SECOND>

<s docid="AP901222-0078" num="4" wdcount="1"> AM-Gulf-Survivors,0720</s>
</SECOND>
<HEAD>

<s docid="AP901222-0078" num="5" wdcount="5"> American Sailors Recount Harrowing Escape</s>
</HEAD>
<HEAD>

<s docid="AP901222-0078" num="6" wdcount="4"> With AM-Gulf Capsize, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP901222-0078" num="7" wdcount="3"> By MARCUS ELIASON</s>
</BYLINE>
<BYLINE>

<s docid="AP901222-0078" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP901222-0078" num="9" wdcount="3"> HAIFA, Israel (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP901222-0078" num="10" wdcount="28"> Chief Petty Officer Lance Vickery recalls waves tumbling into the stern of the bobbing ferry headed back to the USS Saratoga and joking, ``Whoa, looks like we're flooding''.</s>

<s docid="AP901222-0078" num="11" wdcount="22"> Only minutes later, his words came true, turning a simple ride back from Christmas shore leave into a harrowing fight to survive.</s>

<s docid="AP901222-0078" num="12" wdcount="22"> The Israeli ferry Tuvia capsized shortly after midnight on Saturday, throwing more than 100 men into the cold waters of Haifa Bay.</s>

<s docid="AP901222-0078" num="13" wdcount="9"> At least 19 sailors drowned, and scores were injured.</s>

<s docid="AP901222-0078" num="14" wdcount="11"> The sailors were part of the multinational force arrayed against Iraq.</s>

<s docid="AP901222-0078" num="15" wdcount="12"> Vickery, 33, was among four American sailors interviewed at Haifa's Rambam Hospital.</s>

<s docid="AP901222-0078" num="16" wdcount="14"> He is from Jacksonville, Fla., is not far from Mayport, the Saragota's home port.</s>

<s docid="AP901222-0078" num="17" wdcount="28"> Three of the sailors said the boat had been taking on water over the stern in heavy seas, then capsized when it was hit by a big wave.</s>

<s docid="AP901222-0078" num="18" wdcount="15"> Vickery said the fatal wave came about a minute after he had cracked his joke.</s>

<s docid="AP901222-0078" num="19" wdcount="13"> ``All of a sudden, I saw water just come flying in,'' he said.</s>

<s docid="AP901222-0078" num="20" wdcount="12"> ``And it was maybe two seconds, and the boat rolled right over''.</s>

<s docid="AP901222-0078" num="21" wdcount="21"> The 13-year veteran sailor found himself trapped in the ferry's cabin, frantically struggling to find a window as the ship sank.</s>

<s docid="AP901222-0078" num="22" wdcount="10"> ``I started breathing in water and almost died,'' Vickery said.</s>

<s docid="AP901222-0078" num="23" wdcount="18"> ``If I had been under the water maybe another 30 seconds, I wouldn't be lying here right now.</s>

<s docid="AP901222-0078" num="24" wdcount="10"> I'd be in one of those body bags out there''.</s>

<s docid="AP901222-0078" num="25" wdcount="18"> When he made his way to the surface he found ``guys floating everywhere, screaming and yelling like chaos''.</s>

<s docid="AP901222-0078" num="26" wdcount="23"> Despite his own predicament, he grabbed a struggling fellow sailor by the collar and dragged him toward a floating, plastic foam life ring.</s>

<s docid="AP901222-0078" num="27" wdcount="11"> One rescue boat, already overloaded, passed by and threw life preservers.</s>

<s docid="AP901222-0078" num="28" wdcount="11"> In what ``seemed like an hour,'' another boat came, also full.</s>

<s docid="AP901222-0078" num="29" wdcount="28"> ``So they just dragged us through the water back to the Saratoga, and I was a real happy person to see those guys snatching me up,'' he said.</s>

<s docid="AP901222-0078" num="30" wdcount="42"> As Vickery was being treated for bleeding lungs caused by water inhalation, his hospital roommate, Seaman Michael Benjamin, 19, of San Antonio, Texas, was recovering from a neck injury suffered when a rescue boat hit him while he was in the water.</s>

<s docid="AP901222-0078" num="31" wdcount="24"> Both were wearing blue hospital pajamas and, when they walked to the visiting room's balcony could see the Saratoga anchored outside the Haifa harbor.</s>

<s docid="AP901222-0078" num="32" wdcount="20"> Benjamin, who has been in the navy for just a year, said the ferry had been jostled in heavy seas.</s>

<s docid="AP901222-0078" num="33" wdcount="27"> ``As we were going on the waves, I just noticed one that was bigger than normal and then another one that was bigger than normal,'' he said.</s>

<s docid="AP901222-0078" num="34" wdcount="14"> ``The next thing I know, all I saw coming in was water,'' he said.</s>

<s docid="AP901222-0078" num="35" wdcount="22"> Benjamin said he dove from the ferry, then had to swim frantically to get away from the suction of the sinking boat.</s>

<s docid="AP901222-0078" num="36" wdcount="18"> Clinging to a foam plastic float, he was passed by one rescue boat and hit by a second.</s>

<s docid="AP901222-0078" num="37" wdcount="27"> ``I looked around and I see this big hull coming at me and we were all yelling, but I guess the ship didn't see us,'' he said.</s>

<s docid="AP901222-0078" num="38" wdcount="16"> ``I was trying to get out of the way, but I got hit by the ship''.</s>

<s docid="AP901222-0078" num="39" wdcount="23"> Dazed, Benjamin stripped off his jacket, shirt and shoes and kept treading water until he found a piece of driftwood to cling to.</s>

<s docid="AP901222-0078" num="40" wdcount="5"> ``I was scared,'' he admitted.</s>

<s docid="AP901222-0078" num="41" wdcount="11"> ``I was having a hard time staying up in the water''.</s>

<s docid="AP901222-0078" num="42" wdcount="16"> A rescue ship picked him up, he estimated, about a half hour to 45 minutes later.</s>

<s docid="AP901222-0078" num="43" wdcount="26"> Two other men interviewed at Rambam Hospital identified themselves as Technician John Richards, 31, of Twin Lake, Mich., and Airman Lamont Jones, 20, of Claremont, Va.</s>

<s docid="AP901222-0078" num="44" wdcount="8"> Both were breathing with difficulty despite gas masks.</s>

<s docid="AP901222-0078" num="45" wdcount="14"> Richards recalled seeing a large wave and feeling the ship heeling to one side.</s>

<s docid="AP901222-0078" num="46" wdcount="23"> ``All I can remember thinking is, `Oh my God, it's sinking,' and then I was scrambling for my life,'' he said faintly .</s>
</TEXT>
</DOC>
