<DOC>
<DOCNO>

<s docid="SJMN91-06351209" num="1" wdcount="1"> SJMN91-06351209</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06351209" num="2" wdcount="1"> 06351209</s>
</ACCESS>
<CAPTION>

<s docid="SJMN91-06351209" num="3" wdcount="42"> Photo, Map; PHOTO: Associated Press; An Egyptian pulled from sunken ferry Sunday in stormy Red Sea makes his way to a rescue vehicle (color); MAP: Associated Press; (Red Sea showing the Port of origin and the port where the barge sank) (color)</s>
</CAPTION>
<DESCRIPT>

<s docid="SJMN91-06351209" num="4" wdcount="8"> BOAT; DISASTER; MULTIPLE; DEATH; EGYPT; MISSING; PERSON; HUNT</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06351209" num="5" wdcount="31"> The engineer of a ferry that sank off this Red Sea port, leaving more than 400 people missing, today denied accusations of widespread negligence on the part of the ship's crew.</s>

<s docid="SJMN91-06351209" num="6" wdcount="31"> Mahmoud Moharram, engineer of the Salem Express, acknowledged misconduct by some crew members but said the survival of only about 10 of the 71-member crew indicated negligence was not widespread .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06351209" num="7" wdcount="1"> Front</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06351209" num="8" wdcount="12"> EGYPTIAN FERRY SINKS -- 462 LOST SURVIVORS SAY CREW MEMBERS ABANDONED THEM</s>
</HEADLINE>
<TEXT>

<s docid="SJMN91-06351209" num="9" wdcount="29"> Investigators were looking into complaints from some survivors that the crew abandoned the ferry without helping passengers and that some crew members pushed aside passengers to get to lifeboats.</s>

<s docid="SJMN91-06351209" num="10" wdcount="10"> Moharram said he helped 17 passengers put on life jackets.</s>

<s docid="SJMN91-06351209" num="11" wdcount="18"> He said the ferry sank quickly Saturday night after being tossed into a coral reef by stormy seas.</s>

<s docid="SJMN91-06351209" num="12" wdcount="19"> Moharram said the coral cut a hole in the ship's side, and water also entered through the boarding doors.</s>

<s docid="SJMN91-06351209" num="13" wdcount="15"> Only seven bodies have been recovered since the ferry went down, leaving 462 people missing.</s>

<s docid="SJMN91-06351209" num="14" wdcount="14"> Today, the deputy security chief for Egypt's ports said searchers have not given up.</s>

<s docid="SJMN91-06351209" num="15" wdcount="10"> "We are looking for both survivors and bodies," said Brig.</s>

<s docid="SJMN91-06351209" num="16" wdcount="3"> Gen. Abdel-Karim el-Gazzar.</s>

<s docid="SJMN91-06351209" num="17" wdcount="17"> "We haven't lost all hope that there may be some survivors, although the odds are against it.</s>

<s docid="SJMN91-06351209" num="18" wdcount="33"> But you never can tell."; Survivors said that after the ferry hit the reef, crew members herded them to one side of the listing boat, then pushed passengers aside to get to lifeboats.</s>

<s docid="SJMN91-06351209" num="19" wdcount="15"> "They went off in a boat," passenger Abdel-A'ati Hassan, 31, said from his hospital bed.</s>

<s docid="SJMN91-06351209" num="20" wdcount="21"> "They left us with women and kids, who died."; Hassan said the ship sank within 15 minutes of hitting the reef.</s>

<s docid="SJMN91-06351209" num="21" wdcount="12"> During that time, he said, he saw no crew members helping passengers.</s>

<s docid="SJMN91-06351209" num="22" wdcount="9"> "The crew told us to stand on one side.</s>

<s docid="SJMN91-06351209" num="23" wdcount="16"> They wore life preservers and left us and even pushed us aside to escape," he said.</s>

<s docid="SJMN91-06351209" num="24" wdcount="21"> "They could have had time to help."; Many survivors spent hours in shark-infested waters or in lifeboats before being picked up.</s>

<s docid="SJMN91-06351209" num="25" wdcount="15"> Egypt's director of port security, Hassan al-Aghouri, said the rescue was delayed by the storm.</s>

<s docid="SJMN91-06351209" num="26" wdcount="15"> At Safaga Central Hospital, Mustafa Ahmed, 38, said he pulled 13 people into a lifeboat.</s>

<s docid="SJMN91-06351209" num="27" wdcount="17"> "I found a rope and clung to it, and then I found a capsized lifeboat," Ahmed said.</s>

<s docid="SJMN91-06351209" num="28" wdcount="16"> "I managed to get 13 people who were around me in the sea onto the boat.</s>

<s docid="SJMN91-06351209" num="29" wdcount="34"> We waited until a ship rescued us at around noon."; Prime Minister Atef Sidki, who traveled to Safaga, said many passengers may have been on lifeboats driven far from the wreckage by strong winds.</s>

<s docid="SJMN91-06351209" num="30" wdcount="14"> However, many bodies were expected to be found in the hull of the ferry.</s>

<s docid="SJMN91-06351209" num="31" wdcount="6"> Efforts to lift it began today.</s>

<s docid="SJMN91-06351209" num="32" wdcount="20"> U.S. Navy helicopter crews reported "lots of wreckage including life preservers, rafts and floating material" where the ferry went down.</s>

<s docid="SJMN91-06351209" num="33" wdcount="22"> They said the 1,105-ton ferry lay on its starboard -- or right-hand -- side, with its port side protruding from the water.</s>

<s docid="SJMN91-06351209" num="34" wdcount="24"> Lt. Gen. Salah Halaby, chief of staff of Egypt's armed forces, said 30 Egyptian navy divers were searching for victims or, less likely, survivors.</s>

<s docid="SJMN91-06351209" num="35" wdcount="18"> The Salem Express sank after a trip from Jiddah, Saudi Arabia, to Safaga, 290 miles south of Cairo.</s>

<s docid="SJMN91-06351209" num="36" wdcount="31"> Many passengers -- all but 10 of the 649 people aboard were Egyptians -- were Muslims returning from pilgrimages to Mecca, and others were coming home after working in Saudi Arabia.</s>

<s docid="SJMN91-06351209" num="37" wdcount="27"> Ahmed Gamal Sobhi, Safaga's city council chairman, said four bodies were recovered by Egyptian vessels and helicopters by nightfall, and bad weather stopped the search Sunday .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06351209" num="38" wdcount="2"> Associated Press</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06351209" num="39" wdcount="1"> USA</s>
</COUNTRY>
<CITY>

<s docid="SJMN91-06351209" num="40" wdcount="2"> Safaga, Egypt</s>
</CITY>
<EDITION>

<s docid="SJMN91-06351209" num="41" wdcount="2"> Stock Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06351209" num="42" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06351209" num="43" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06351209" num="44" wdcount="1"> 911216</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06351209" num="45" wdcount="1"> Monday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06351209" num="46" wdcount="1"> December</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06351209" num="47" wdcount="1"> 1A</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06351209" num="48" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06351209" num="49" wdcount="1"> WEST</s>
</REGION>
<FEATURE>

<s docid="SJMN91-06351209" num="50" wdcount="2"> PHOTO; MAP</s>
</FEATURE>
<STATE>

<s docid="SJMN91-06351209" num="51" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06351209" num="52" wdcount="1"> 627</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06351209" num="53" wdcount="5"> Monday, December 16, 1991 00351209,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06351209" num="54" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06351209" num="55" wdcount="1"> 1</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06351209" num="56" wdcount="2"> ENG FRONT</s>
</LANGUAGE>
</DOC>
