<DOC>
<DOCNO>

<s docid="SJMN91-06064099" num="1" wdcount="1"> SJMN91-06064099</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06064099" num="2" wdcount="1"> 06064099</s>
</ACCESS>
<DESCRIPT>

<s docid="SJMN91-06064099" num="3" wdcount="6"> AFRICA; BOAT; ACCIDENT; RESULT; MULTIPLE; DEATH</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06064099" num="4" wdcount="21"> A boat carrying hundreds of Somali refugees struck a reef off Kenya and sank, killing more than 130 people, newspapers reported.</s>

<s docid="SJMN91-06064099" num="5" wdcount="23"> The accident involving a vessel ferrying about 600 people occurred Friday near Malindi, a tourist resort about 400 miles southeast of Nairobi .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06064099" num="6" wdcount="1"> Front</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06064099" num="7" wdcount="7"> SOMALI REFUGEE BOAT SINKS; 130 ARE KILLED</s>
</HEADLINE>
<TEXT>

<s docid="SJMN91-06064099" num="8" wdcount="11"> First accounts of the accident were reported Sunday in Kenyan newspapers.</s>

<s docid="SJMN91-06064099" num="9" wdcount="21"> Two English-language dailies said the accident occurred one mile off the coast, but a third said it was six miles away.</s>

<s docid="SJMN91-06064099" num="10" wdcount="30"> Police, navy divers, tourists and local residents had recovered about 130 bodies by Saturday afternoon, but 50 victims were believed still trapped in the sunken vessel, according to the newspapers.</s>

<s docid="SJMN91-06064099" num="11" wdcount="11"> Confirmation from local authorities of the accounts was not immediately available.</s>

<s docid="SJMN91-06064099" num="12" wdcount="22"> The boat with the refugees had set sail from the Somali town of Kismayo, 250 miles north of Malindi, on Feb. 26.</s>

<s docid="SJMN91-06064099" num="13" wdcount="28"> It was one of a stream of vessels that brought thousands of Somalis seeking refuge to Kenya since rebels overthrew Somalian President Mohamed Siad Barre in late January.</s>

<s docid="SJMN91-06064099" num="14" wdcount="16"> The victory followed a month of heavy fighting in Mogadishu, capital of the East African nation.</s>

<s docid="SJMN91-06064099" num="15" wdcount="24"> The fighting appears largely to have stopped since the rebel United Somali Congress established an interim government, but refugees continue to arrive in Kenya.</s>

<s docid="SJMN91-06064099" num="16" wdcount="24"> Abdi Mohammed Ali, a survivor, was quoted as telling the Standard newspaper that most of those who drowned were on the ship's lower deck.</s>

<s docid="SJMN91-06064099" num="17" wdcount="27"> First word of the accident came when two survivors staggered into the Jambo Club tourist hotel, manager Barney Ngare was quoted as saying by the Sunday Nation.</s>

<s docid="SJMN91-06064099" num="18" wdcount="32"> The hotel sent a small boat to help save those still on the sinking vessel, but rescue workers had to cut the lifeline when too many people grabbed hold, according to Ngare.</s>

<s docid="SJMN91-06064099" num="19" wdcount="17"> Another boat sent by the hotel ferried 15 people at a time to shore, said the Nation.</s>

<s docid="SJMN91-06064099" num="20" wdcount="18"> Eleven Somalis drowned when a boat capsized off Kenya near Lamu, north of Malindi, on Feb. 1 .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06064099" num="21" wdcount="2"> Associated Press</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06064099" num="22" wdcount="1"> USA</s>
</COUNTRY>
<CITY>

<s docid="SJMN91-06064099" num="23" wdcount="2"> Nairobi, Kenya</s>
</CITY>
<EDITION>

<s docid="SJMN91-06064099" num="24" wdcount="2"> Morning Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06064099" num="25" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06064099" num="26" wdcount="4"> SAN JOSE MERCURY NEWS</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06064099" num="27" wdcount="1"> 910304</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06064099" num="28" wdcount="1"> Monday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06064099" num="29" wdcount="1"> March</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06064099" num="30" wdcount="1"> 3A</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06064099" num="31" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06064099" num="32" wdcount="1"> WEST</s>
</REGION>
<STATE>

<s docid="SJMN91-06064099" num="33" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06064099" num="34" wdcount="1"> 324</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06064099" num="35" wdcount="5"> Monday March 4, 1991 00064099,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06064099" num="36" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06064099" num="37" wdcount="1"> 1</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06064099" num="38" wdcount="1"> ENG</s>
</LANGUAGE>
</DOC>
