<DOC>
<DOCNO>

<s docid="SJMN91-06351097" num="1" wdcount="1"> SJMN91-06351097</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06351097" num="2" wdcount="1"> 06351097</s>
</ACCESS>
<CAPTION>

<s docid="SJMN91-06351097" num="3" wdcount="42"> Photo, Map; PHOTO: Associated Press; An Egyptian pulled from sunken ferry Sunday in stormy Red Sea makes his way to a rescue vehicle (color); MAP: Associated Press; (Red Sea showing the Port of origin and the port where the barge sank) (color)</s>
</CAPTION>
<DESCRIPT>

<s docid="SJMN91-06351097" num="4" wdcount="8"> BOAT; DISASTER; MULTIPLE; DEATH; EGYPT; MISSING; PERSON; HUNT</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06351097" num="5" wdcount="1"> U.S.</s>

<s docid="SJMN91-06351097" num="6" wdcount="31"> Navy aircraft joined the search today for survivors of the ferry sinking that left 471 people missing in shark-infested Red Sea waters but found nothing but empty life rafts and debris.</s>

<s docid="SJMN91-06351097" num="7" wdcount="30"> Investigators, meanwhile, were looking into complaints from some of the 178 survivors that the crew of the Salem Express abandoned ship without helping them into lifeboats or flotation gear .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06351097" num="8" wdcount="1"> Front</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06351097" num="9" wdcount="7"> EGYPTIAN FERRY SINKS -- 471 LOST U.S.</s>

<s docid="SJMN91-06351097" num="10" wdcount="6"> AIRCRAFT JOIN THE SEARCH FOR SURVIVORS</s>
</HEADLINE>
<TEXT>

<s docid="SJMN91-06351097" num="11" wdcount="13"> They also want to know why the ferry strayed outside standard navigational channels.</s>

<s docid="SJMN91-06351097" num="12" wdcount="24"> The 1,105-ton ship went down Saturday night about six miles off the Egyptian coast after ramming into a coral reef in stormy 10-foot seas.</s>

<s docid="SJMN91-06351097" num="13" wdcount="10"> "We are looking for both survivors and bodies," said Brig.</s>

<s docid="SJMN91-06351097" num="14" wdcount="8"> Abdel-Karim el-Gazzar, Egypt's deputy chief of port security.</s>

<s docid="SJMN91-06351097" num="15" wdcount="42"> "We haven't lost all hope that there may be some survivors, although the odds are against it."; Prime Minister Atef Sidki, who traveled to Safaga, said many passengers may have been on lifeboats driven far from the wreck scene by strong winds.</s>

<s docid="SJMN91-06351097" num="16" wdcount="28"> Ahmed Gamal Sobhi, Safaga's city council chairman, said only four bodies were recovered by Egyptian vessels and helicopters and the time nightfall and bad weather stopped Sunday's search.</s>

<s docid="SJMN91-06351097" num="17" wdcount="10"> The weather improved today as two helicopters from the U.S.</s>

<s docid="SJMN91-06351097" num="18" wdcount="27"> Navy frigate Aubrey Fitch, which joined in the rescue effort on Sunday night, and a Navy P-3 submarine-chaser aircraft made their first daylight search runs, said Lt.</s>

<s docid="SJMN91-06351097" num="19" wdcount="7"> Cmdr. Rudolph Brewington, a Pentagon duty officer.</s>

<s docid="SJMN91-06351097" num="20" wdcount="20"> "They've observed lots of wreckage, empty life rafts, an oil slick but no additional bodies and no survivors," he said.</s>

<s docid="SJMN91-06351097" num="21" wdcount="35"> Survivors said that after the ship struck the reef, crew members herded them to one side of the listing boat to keep it from heeling over, then pushed passengers aside to get to the lifeboats.</s>

<s docid="SJMN91-06351097" num="22" wdcount="17"> "They went off in a boat," passenger Abdel-A'ati Hassan, 31, said from his hospital bed in Safaga.</s>

<s docid="SJMN91-06351097" num="23" wdcount="32"> "They left us with women and kids, who died."; The Salem Express was near the end of a 36-hour trip from Jiddah, Saudi Arabia, to Safaga, about 290 miles south of Cairo.</s>

<s docid="SJMN91-06351097" num="24" wdcount="26"> Many of the passengers were Muslims returning from off-season pilgrimages to Mecca and others were returning to Egypt after stints as guest workers in Saudi Arabia.</s>

<s docid="SJMN91-06351097" num="25" wdcount="21"> Outside the harbor, scores of relatives of passengers squatted on a sidewalk or huddled in taxis, awaiting word about their kin.</s>

<s docid="SJMN91-06351097" num="26" wdcount="28"> Hassan Al-Aghouri, Egypt's chief of port security, said the Egyptian-registered ferry inexplicably left standard navigational channels and investigators were seeking to question surviving crew about the course change.</s>

<s docid="SJMN91-06351097" num="27" wdcount="14"> The investigation also will try to determine whether the ferry was carrying enough lifeboats.</s>

<s docid="SJMN91-06351097" num="28" wdcount="23"> Al-Ahram, a leading Cairo newspaper, said in an unattributed report today that the vessel left the charted navigation channel to take a shortcut.</s>

<s docid="SJMN91-06351097" num="29" wdcount="17"> It said naval authorities warned the skipper back on course to avoid the area's abundant coral reefs.</s>

<s docid="SJMN91-06351097" num="30" wdcount="12"> But strong winds sent the boat out of control, the newspaper said.</s>

<s docid="SJMN91-06351097" num="31" wdcount="19"> The boat's first mate, Mahmoud Soleiman Rizake, said a "terrible explosion" from the collision awoke him in his cabin.</s>

<s docid="SJMN91-06351097" num="32" wdcount="27"> "Water flooded the ship in 10 minutes, causing it to sink," he said, adding that he jumped overboard and swam until a rescue boat picked him up.</s>

<s docid="SJMN91-06351097" num="33" wdcount="26"> The temperature of the water was not immediately known, but the air temperature was about 50 degrees and many of the survivors were treated for exposure.</s>

<s docid="SJMN91-06351097" num="34" wdcount="8"> At least 118 of the survivors were hospitalized.</s>

<s docid="SJMN91-06351097" num="35" wdcount="16"> El-Gazzar, the deputy port security chief, said all but 10 of the passengers were Egyptians .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06351097" num="36" wdcount="2"> Associated Press</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06351097" num="37" wdcount="1"> USA</s>
</COUNTRY>
<CITY>

<s docid="SJMN91-06351097" num="38" wdcount="2"> Safaga, Egypt</s>
</CITY>
<EDITION>

<s docid="SJMN91-06351097" num="39" wdcount="1"> Street</s>
</EDITION>
<CODE>

<s docid="SJMN91-06351097" num="40" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06351097" num="41" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06351097" num="42" wdcount="1"> 911216</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06351097" num="43" wdcount="1"> Monday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06351097" num="44" wdcount="1"> December</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06351097" num="45" wdcount="1"> 1A</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06351097" num="46" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06351097" num="47" wdcount="1"> WEST</s>
</REGION>
<FEATURE>

<s docid="SJMN91-06351097" num="48" wdcount="2"> PHOTO; MAP</s>
</FEATURE>
<STATE>

<s docid="SJMN91-06351097" num="49" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06351097" num="50" wdcount="1"> 626</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06351097" num="51" wdcount="5"> Monday, December 16, 1991 00351097,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06351097" num="52" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06351097" num="53" wdcount="1"> 1</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06351097" num="54" wdcount="2"> ENG FRONT</s>
</LANGUAGE>
</DOC>
