<DOC>
<DOCNO>

<s docid="AP880821-0010" num="1" wdcount="1"> AP880821-0010</s>
</DOCNO>
<FILEID>

<s docid="AP880821-0010" num="2" wdcount="2"> AP-NR-08-21-88 0835EDT</s>
</FILEID>
<FIRST>

<s docid="AP880821-0010" num="3" wdcount="7"> u i BC-India-NepalQuake 1stLd-Writethru a0626 08-21 0698</s>
</FIRST>
<SECOND>

<s docid="AP880821-0010" num="4" wdcount="5"> BC-India-Nepal Quake, 1st Ld-Writethru, a0626,0711</s>
</SECOND>
<HEAD>

<s docid="AP880821-0010" num="5" wdcount="10"> Quake Along India-Nepal Border Reportedly Leaves More Than 200 Dead</s>
</HEAD>
<NOTE>

<s docid="AP880821-0010" num="6" wdcount="11"> Eds: New thruout to UPDATE with more deaths in Nepal, U.S.</s>

<s docid="AP880821-0010" num="7" wdcount="6"> Geological Survey reading, details and quotes.</s>

<s docid="AP880821-0010" num="8" wdcount="3"> No Pickup .</s>
</NOTE>
<DATELINE>

<s docid="AP880821-0010" num="9" wdcount="4"> NEW DELHI, India (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880821-0010" num="10" wdcount="31"> A strong earthquake triggered landslides and destroyed houses in the mountainous India-Nepal border region early Sunday, killing at least 237 people and injuring more than 1,500, officials and news reports said.</s>

<s docid="AP880821-0010" num="11" wdcount="14"> Seismologists said it was the deadliest earthquake to strike the Himalayan region since 1950.</s>

<s docid="AP880821-0010" num="12" wdcount="18"> More than 100 people died when the quake rumbled through the eastern Indian state of Bihar, officials said.</s>

<s docid="AP880821-0010" num="13" wdcount="10"> In Nepal, authorities said at least 137 people were dead.</s>

<s docid="AP880821-0010" num="14" wdcount="21"> Officials in both countries predicted the death toll would rise after they received reports from remote areas which were hit harder.</s>

<s docid="AP880821-0010" num="15" wdcount="11"> ``The tolls have come in only from urban areas,'' said V.K.</s>

<s docid="AP880821-0010" num="16" wdcount="7"> Sharma, deputy secretary in the Bihar government.</s>

<s docid="AP880821-0010" num="17" wdcount="23"> The temblor also jolted parts of northern Bangladesh and the capital of Dhaka, but there were no immediate reports of casualties or damage.</s>

<s docid="AP880821-0010" num="18" wdcount="26"> Witnesses said windows and doors rattled, buildings cracked and people roused from their sleep ran screaming from their homes as objects tumbled from shelves and tables.</s>

<s docid="AP880821-0010" num="19" wdcount="17"> ``My bed rattled, then it began swinging,'' said R.N. Rudra, a resident of Patna, the Bihar capital.</s>

<s docid="AP880821-0010" num="20" wdcount="11"> ``My dogs began barking and I rushed out of the house''.</s>

<s docid="AP880821-0010" num="21" wdcount="33"> At least 1,000 people were injured when the quake triggered landslides and house collapses in Bihar and the surrounding states of Uttar Pradesh, West Bengal and Orissa, all heavily populated, largely agricultural areas.</s>

<s docid="AP880821-0010" num="22" wdcount="22"> The quake also was felt in Sikkim and Tripura, located in the Himalayan foothills, the Press Trust of India news agency said.</s>

<s docid="AP880821-0010" num="23" wdcount="25"> In Nepal, a Foreign Ministry official, Shailendra Kumar Upadhyaya, said more than 500 people were injured and thousands of houses collapsed from the quake's impact.</s>

<s docid="AP880821-0010" num="24" wdcount="36"> ``Most of them (were) buried alive under collapsed houses,'' said Indra Shrestha, a social worker involved in the rescue operation in Dharan Bazar, a township of about 100,000 people about 18 miles from the Indian border.</s>

<s docid="AP880821-0010" num="25" wdcount="23"> Shrestha said rescue operations were being hampered by the monsoon rains, which hit the subcontinent in late June and usually last through September.</s>

<s docid="AP880821-0010" num="26" wdcount="10"> Both countries were rushing emergency medical teams to the area.</s>

<s docid="AP880821-0010" num="27" wdcount="11"> The Red Cross of Nepal issued urgent appeals for blood donations.</s>

<s docid="AP880821-0010" num="28" wdcount="16"> In India's Bihar state, communications with Darbhanga, which appeared to be the worst-hit area, were disrupted.</s>

<s docid="AP880821-0010" num="29" wdcount="18"> The Press Trust of India said a school hostel in the town collapsed, killing at least 17 children.</s>

<s docid="AP880821-0010" num="30" wdcount="10"> It said more bodies were feared buried under the debris.</s>

<s docid="AP880821-0010" num="31" wdcount="23"> The quake damaged most of the houses in Darbhanga, the news agency said, quoting P.K. Patnaik, the top civil administrator in the district.</s>

<s docid="AP880821-0010" num="32" wdcount="13"> Deaths were also reported in the neighboring towns of Munger, Keoti and Narpatnagar.</s>

<s docid="AP880821-0010" num="33" wdcount="16"> The tremor also was felt in the eastern city of Calcutta, Press Trust of India said.</s>

<s docid="AP880821-0010" num="34" wdcount="21"> There were no immediate reports of casualties but residents were quoted as saying windows of several homes vibrated and doors rattled.</s>

<s docid="AP880821-0010" num="35" wdcount="13"> The Seismological Observatory in New Delhi said the quake hit at 4:40 a.m.</s>

<s docid="AP880821-0010" num="36" wdcount="24"> (7:10 p.m. EDT Saturday) and was centered 40 to 50 miles northeast of the town of Darbhanga in Bihar state, along the India-Nepal border.</s>

<s docid="AP880821-0010" num="37" wdcount="13"> Observatory Director H.N. Srivastava said the quake measured 6.5 on the Richter scale.</s>

<s docid="AP880821-0010" num="38" wdcount="15"> Srivastava said the quake lasted about one minute and aftershocks continued for about an hour.</s>

<s docid="AP880821-0010" num="39" wdcount="7"> Seismologists warned aftershocks could continue for days.</s>

<s docid="AP880821-0010" num="40" wdcount="2"> The U.S.</s>

<s docid="AP880821-0010" num="41" wdcount="22"> Geological Survey said its initial seismograph readings placed the center of the quake 100 miles southeast of Katmandu, the capital of Nepal.</s>

<s docid="AP880821-0010" num="42" wdcount="19"> Geological Survey monitors in Golden, Colo., recorded the earthquake at a preliminary magnitude of 6.7 on the Richter scale.</s>

<s docid="AP880821-0010" num="43" wdcount="20"> The Richter scale gauges the energy released by an earthquake as measured by the ground motion recorded on a seismograph.</s>

<s docid="AP880821-0010" num="44" wdcount="11"> A quake of magnitude 6 is capable of causing severe damage.</s>

<s docid="AP880821-0010" num="45" wdcount="7"> Earthquakes are common in the Himalayan region.</s>

<s docid="AP880821-0010" num="46" wdcount="18"> On Aug. 6 a quake of magnitude 7.3 shook the states of Assam, Manipur, West Bengal and Bihar.</s>

<s docid="AP880821-0010" num="47" wdcount="4"> Four people were killed.</s>

<s docid="AP880821-0010" num="48" wdcount="17"> India's worst earthquake was in 1950, when at least 30,000 people were killed in Assam state .</s>
</TEXT>
</DOC>
