<DOC>
<DOCNO>

<s docid="AP880826-0161" num="1" wdcount="1"> AP880826-0161</s>
</DOCNO>
<FILEID>

<s docid="AP880826-0161" num="2" wdcount="2"> AP-NR-08-26-88 1605EDT</s>
</FILEID>
<FIRST>

<s docid="AP880826-0161" num="3" wdcount="5"> r i AM-Earthquake 08-26 0541</s>
</FIRST>
<SECOND>

<s docid="AP880826-0161" num="4" wdcount="1"> AM-Earthquake,0557</s>
</SECOND>
<HEAD>

<s docid="AP880826-0161" num="5" wdcount="9"> Death Toll Rises to 981, Legislator Beaten to Death</s>
</HEAD>
<BYLINE>

<s docid="AP880826-0161" num="6" wdcount="3"> By EARLEEN FISHER</s>
</BYLINE>
<BYLINE>

<s docid="AP880826-0161" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880826-0161" num="8" wdcount="3"> BHAKTAPUR, Nepal (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880826-0161" num="9" wdcount="25"> An earthquake that devastated parts of Nepal and India earlier this week has killed more than 980 people, officials from the two countries said Friday.</s>

<s docid="AP880826-0161" num="10" wdcount="32"> Mourners paraded through the streets of this medieval town, calling for revenge after a former legislator was beaten to death by political rivals while he was distributing relief supplies to earthquake victims.</s>

<s docid="AP880826-0161" num="11" wdcount="31"> ``Hang the murderers,'' scores of young men chanted as they marched in front of a jeep bearing the battered body of Karna Hyanju, once a sympathizer of the now-outlawed Communist Party.</s>

<s docid="AP880826-0161" num="12" wdcount="24"> Witnesses said Hyanju was beaten with umbrellas and sticks late Thursday afternoon, then dragged through the streets for nearly two hours before police intervened.</s>

<s docid="AP880826-0161" num="13" wdcount="14"> He died Friday at the Bir hospital in Katmandu, 7 miles west of Bhaktapur.</s>

<s docid="AP880826-0161" num="14" wdcount="46"> Uttam Dhaubanjar, a 28-year-old bank employee and neighbor of the dead man, said Hyanju had been handing out blankets, milk and other food in Bhaktapur when he was accosted by a group of men who accused him of giving relief supplies only to his own supporters.</s>

<s docid="AP880826-0161" num="15" wdcount="27"> Reports of damage and devastation continued to arrive from remote parts of Nepal on Friday, and the Home Affairs Ministry updated its confirmed death toll to 704.</s>

<s docid="AP880826-0161" num="16" wdcount="8"> In India, the official count rose to 277.</s>

<s docid="AP880826-0161" num="17" wdcount="17"> But survivors, the news media and opposition politicians say the toll could be as high as 1,500.</s>

<s docid="AP880826-0161" num="18" wdcount="23"> Sunday's earthquake registered 6.5 on the Richter scale, which records energy released by a tremor according to ground motion measured by a seismograph.</s>

<s docid="AP880826-0161" num="19" wdcount="16"> A reading of 6 indicates the possibility of severe damage, while 7 signifies a major quake.</s>

<s docid="AP880826-0161" num="20" wdcount="17"> Dhaubanjar said he saw about 40 people rounded up by police Thursday night after Hyanju's beating death.</s>

<s docid="AP880826-0161" num="21" wdcount="13"> He said many belonged to the same Communist faction that Hyanju once supported.</s>

<s docid="AP880826-0161" num="22" wdcount="8"> ``People started beating him with umbrellas,'' Dhaubanjar said.</s>

<s docid="AP880826-0161" num="23" wdcount="14"> ``There were a lot of scratches on his body, and a lot of blood.</s>

<s docid="AP880826-0161" num="24" wdcount="7"> It looked like one ear was missing.</s>

<s docid="AP880826-0161" num="25" wdcount="24"> Then they made a necklace of their shoes (by tying the laces together), put it around his neck and pulled him through the streets''.</s>

<s docid="AP880826-0161" num="26" wdcount="36"> As Hyanju's body was taken through the winding streets of Bhaktapur, a 12th-century town of ancient Hindu temples, thousands of the town's 50,000 people jammed streets, temple steps and the balconies of brick and mud houses.</s>

<s docid="AP880826-0161" num="27" wdcount="37"> Pashupati Rana, one of several Cabinet ministers who marched in the funeral procession, said several people were arrested in the killing, including the mayor, the deputy mayor and a member of the Rashtriya Panchayat, or non-partisan assembly.</s>

<s docid="AP880826-0161" num="28" wdcount="15"> Rana, who is minister of local development and legislative, affairs, called Hyanju's death ``political murder''.</s>

<s docid="AP880826-0161" num="29" wdcount="23"> Hyanju served in the Panchayat from 1981 until 1986 when he lost the backing of the Communists in Bhaktapur, traditionally a leftist stronghold.</s>

<s docid="AP880826-0161" num="30" wdcount="38"> The Panchayat, whose members are elected on non-party lines, was created after the late king Mahendra abolished the old Parliament and all political parties in 1960, saying a Western-style parliamentary system was not suited to his mountain kingdom.</s>

<s docid="AP880826-0161" num="31" wdcount="25"> Dhaubanjar and a group of young men who gathered around him said Hyanju was perceived as a government supporter despite his previous communist leanings .</s>
</TEXT>
</DOC>
