<DOC>
<DOCNO>

<s docid="AP880825-0147" num="1" wdcount="1"> AP880825-0147</s>
</DOCNO>
<FILEID>

<s docid="AP880825-0147" num="2" wdcount="2"> AP-NR-08-25-88 1722EDT</s>
</FILEID>
<FIRST>

<s docid="AP880825-0147" num="3" wdcount="5"> r a AM-NepalQuake-Volunteers 08-25 0238</s>
</FIRST>
<SECOND>

<s docid="AP880825-0147" num="4" wdcount="2"> AM-Nepal Quake-Volunteers,0243</s>
</SECOND>
<HEAD>

<s docid="AP880825-0147" num="5" wdcount="10"> Parents of Peace Corps Worker Find Out Son Is Safe</s>
</HEAD>
<DATELINE>

<s docid="AP880825-0147" num="6" wdcount="4"> IOWA CITY, Iowa (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880825-0147" num="7" wdcount="35"> The parents of a Peace Corps worker learned Thursday that their son, a volunteer in Nepal, was safe following an earthquake last weekend that killed at least 750 people in that country and neighboring India.</s>

<s docid="AP880825-0147" num="8" wdcount="35"> ``They called this morning, that's the first we had heard about anything since the quake,'' said Arthur Giaquinta, whose 24-year-old son, Peter, lives in a village 10 miles north of the hard-hit Dharan Bazar township.</s>

<s docid="AP880825-0147" num="9" wdcount="18"> Jim Flanigan, a Peace Corps spokesman in Washington, said Peter Giaquinta was ``fine as far as we know''.</s>

<s docid="AP880825-0147" num="10" wdcount="22"> In Boston, the brother of Peace Corps volunteer Bettyjean Bouffard, 27, said Thursday she called her relatives to say she was safe.</s>

<s docid="AP880825-0147" num="11" wdcount="16"> The call, said Dave Bouffard, was the first news the family had had of her safety.</s>

<s docid="AP880825-0147" num="12" wdcount="21"> ``We're ecstatic,'' he said, adding that his sister had been living with a Nepalese family five miles from the earthquake epicenter.</s>

<s docid="AP880825-0147" num="13" wdcount="20"> Flanigan said the Peace Corps has been able to track down all but three of the 157 volunteers in Nepal.</s>

<s docid="AP880825-0147" num="14" wdcount="10"> There are no Peace Corps members in India, he said.</s>

<s docid="AP880825-0147" num="15" wdcount="18"> The three, he said, are from Michigan, Wisconsin and the Philadelphia area; he declined to release their names.</s>

<s docid="AP880825-0147" num="16" wdcount="11"> ``We have a problem with roads out, monsoon rains,'' Flanigan said.</s>

<s docid="AP880825-0147" num="17" wdcount="13"> ``In the best of times, reaching some of these volunteers is several days.''</s>
</TEXT>
</DOC>
