<DOC>
<DOCNO>

<s docid="AP880821-0008" num="1" wdcount="1"> AP880821-0008</s>
</DOCNO>
<FILEID>

<s docid="AP880821-0008" num="2" wdcount="2"> AP-NR-08-21-88 0234EDT</s>
</FILEID>
<FIRST>

<s docid="AP880821-0008" num="3" wdcount="7"> u i AM-India-Quake 3rdLd-Writethru a0623 08-21 0428</s>
</FIRST>
<SECOND>

<s docid="AP880821-0008" num="4" wdcount="4"> AM-India-Quake, 3rd Ld-Writethru, a0623,0440</s>
</SECOND>
<HEAD>

<s docid="AP880821-0008" num="5" wdcount="11"> 100 Feared Dead In Earthquake That Hits Nepal And Eastern India</s>
</HEAD>
<NOTE>

<s docid="AP880821-0008" num="6" wdcount="17"> Eds: Leads with 5 grafs to UPDATE with Indian officials measuring quake at 6.5 on Richter scale.</s>

<s docid="AP880821-0008" num="7" wdcount="18"> Pickup 5th graf pvs ``Press Trust...''; SUBS final graf ``A quake''... with one graf to ADD background .</s>
</NOTE>
<DATELINE>

<s docid="AP880821-0008" num="8" wdcount="3"> KATMANDU, Nepal (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880821-0008" num="9" wdcount="22"> A strong earthquake hit the Himalayan kingdom of Nepal and parts of eastern India on Sunday morning, triggering landslides and collapsing buildings.</s>

<s docid="AP880821-0008" num="10" wdcount="8"> First reports said 100 people may have died.</s>

<s docid="AP880821-0008" num="11" wdcount="11"> Nepal's Department of Geology said the earthquake struck at 4:54 a.m.</s>

<s docid="AP880821-0008" num="12" wdcount="11"> (7:09 p.m. EDT Saturday) and measured 5.7 on the Richter scale.</s>

<s docid="AP880821-0008" num="13" wdcount="23"> The department said the quake was centered near Udayapur, a town near the Indian-Nepalese border and 100 miles southeast of Katmandu, Nepal's capital.</s>

<s docid="AP880821-0008" num="14" wdcount="8"> Officials said the temblor lasted about 40 seconds.</s>

<s docid="AP880821-0008" num="15" wdcount="15"> In New Delhi, the Seismologoical Observatory said the quake measured 6.5 on the Richter scale.</s>

<s docid="AP880821-0008" num="16" wdcount="25"> The state-run Radio Nepal said at least 27 people were killed in the towns of Bhaktapur and Dharan when they were buried by collapsing houses.</s>

<s docid="AP880821-0008" num="17" wdcount="32"> Press Trust of India news agency said that in addition to 100 feared dead in India and Nepal, 1,000 people were injured in the Indian states of Bihar, Sikkim and West Bengal.</s>

<s docid="AP880821-0008" num="18" wdcount="19"> A Nepalese journalist in Dharan, 130 miles southeast of Katmandu, said by telephone that ``20 people have already died.</s>

<s docid="AP880821-0008" num="19" wdcount="18"> A large number of injured were being taken to local hospitals and a rescue operation is under way.</s>

<s docid="AP880821-0008" num="20" wdcount="20"> Men of the Royal Nepal Army, police, social workers and other local inhabitants are taking part in the rescue operation''.</s>

<s docid="AP880821-0008" num="21" wdcount="15"> The journalist added that ``90 percent of the house of Vijapur area of Dharan collapsed''.</s>

<s docid="AP880821-0008" num="22" wdcount="20"> Police reported seven people died in Bhaktapur, an ancient town seven miles east of Katmandu, while 20 others suffered injuries.</s>

<s docid="AP880821-0008" num="23" wdcount="22"> The quake was also felt in the Indian capital of New Delhi and Calcutta, but there was no report of any casualties.</s>

<s docid="AP880821-0008" num="24" wdcount="20"> One hard-hit Indian city was Dharbhanga in Bihar state, where 14 children were believed killed when their school hostel collapsed.</s>

<s docid="AP880821-0008" num="25" wdcount="13"> Dharbhanga, with a population of 200,000, is 550 miles east of New Delhi.</s>

<s docid="AP880821-0008" num="26" wdcount="16"> Several homes in the residential areas of Dharbhanga have collapsed, killing an unspecified number of people.</s>

<s docid="AP880821-0008" num="27" wdcount="21"> The Richter scale is a gauge of energy released by an earthquake, as measured by ground motion recorded on a seismograph.</s>

<s docid="AP880821-0008" num="28" wdcount="13"> Every increase of one number means the ground motion is 10 times greater.</s>

<s docid="AP880821-0008" num="29" wdcount="21"> A quake of magnitude 5 can cause considerable damage in populated areas while one measuring 6 can cause severe damage .</s>
</TEXT>
</DOC>
