<DOC>
<DOCNO>

<s docid="AP880822-0075" num="1" wdcount="1"> AP880822-0075</s>
</DOCNO>
<FILEID>

<s docid="AP880822-0075" num="2" wdcount="2"> AP-NR-08-22-88 1059EDT</s>
</FILEID>
<FIRST>

<s docid="AP880822-0075" num="3" wdcount="7"> u i PM-Earthquake 3rdLd-Writethru a0493 08-22 0766</s>
</FIRST>
<SECOND>

<s docid="AP880822-0075" num="4" wdcount="6"> PM-Earthquake, 3rd Ld - Writethru, a0493,0787</s>
</SECOND>
<HEAD>

<s docid="AP880822-0075" num="5" wdcount="3"> Precede NEW DELHI</s>
</HEAD>
<HEAD>

<s docid="AP880822-0075" num="6" wdcount="6"> One-Third Of Nepal Devastated By Quake</s>
</HEAD>
<NOTE>

<s docid="AP880822-0075" num="7" wdcount="11"> Eds: LEADS with 16 grafs to UPDATE with details on Nepal.</s>

<s docid="AP880822-0075" num="8" wdcount="6"> Pick up 12th pvs, Prime Minister.</s>

<s docid="AP880822-0075" num="9" wdcount="3"> Changes byline .</s>
</NOTE>
<BYLINE>

<s docid="AP880822-0075" num="10" wdcount="3"> By EARLEEN FISHER</s>
</BYLINE>
<BYLINE>

<s docid="AP880822-0075" num="11" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880822-0075" num="12" wdcount="3"> KATMANDU, Nepal (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880822-0075" num="13" wdcount="29"> Rescuers searched through debris today for victims of an earthquake that ravaged one-third of this country's territory and parts of India, killing at least 650 people and injuring thousands.</s>

<s docid="AP880822-0075" num="14" wdcount="29"> The death toll was expected to climb from Sunday's pre-dawn quake on the India-Nepal border, which triggered landslides and floods and was the mountainous region's deadliest in 38 years.</s>

<s docid="AP880822-0075" num="15" wdcount="36"> Officials in both countries said they had yet to receive reports from the remote Himalayan areas hardest hit by the temblor, which knocked out power and communications and was said to injure at least 3,000 people.</s>

<s docid="AP880822-0075" num="16" wdcount="23"> Niranjan Thapa, Nepal's minister of state for home affairs, told a news conference at least 450 were dead and up to 1,000 injured.</s>

<s docid="AP880822-0075" num="17" wdcount="8"> He said officials expected the numbers to climb.</s>

<s docid="AP880822-0075" num="18" wdcount="19"> Indian officials reported at least 200 people dead and more than 2,000 injured, most by debris from collapsing buildings.</s>

<s docid="AP880822-0075" num="19" wdcount="14"> The quake, centered almost on the India-Nepal border, registered 6.5 on the Richter scale.</s>

<s docid="AP880822-0075" num="20" wdcount="31"> Indian television today showed the devastation in the Indian state of Bihar: crumbled buildings, makeshift morgues lined with rows of bodies wrapped in white shrouds, damaged hospital wards packed with survivors.</s>

<s docid="AP880822-0075" num="21" wdcount="22"> Medical teams in India carried medicine and other supplies to overcrowded hospitals and the army was deployed to help search for victims.</s>

<s docid="AP880822-0075" num="22" wdcount="18"> But the monsoons, which hit the subcontinent in late June and usually last through September, hampered relief operations.</s>

<s docid="AP880822-0075" num="23" wdcount="19"> Nepal's Thapa told a news conference that ``the rains have been a great hindrance in carrying out rescue works.</s>

<s docid="AP880822-0075" num="24" wdcount="10"> Access to some areas of this mountain country is impossible''.</s>

<s docid="AP880822-0075" num="25" wdcount="11"> He said 21 of the kingdom's 75 districts suffered extensive damage.</s>

<s docid="AP880822-0075" num="26" wdcount="20"> The hardest hit appeared to be Dharan, a sparsely populated border region where Thapa said at least 131 people died.</s>

<s docid="AP880822-0075" num="27" wdcount="15"> Bir Bahadur Shahi, secretary of the home affairs ministry, flew to eastern Nepal on Sunday.</s>

<s docid="AP880822-0075" num="28" wdcount="13"> He said 50,000 to 60,000 houses were destroyed in the Dharan district alone.</s>

<s docid="AP880822-0075" num="29" wdcount="29"> ``Ninety percent of the remaining houses are cracked,'' Shahi said, adding that most of the damage was to modern houses of stone and older houses from mud and bricks.</s>

<s docid="AP880822-0075" num="30" wdcount="7"> Wooden houses were not affected, he said.</s>

<s docid="AP880822-0075" num="31" wdcount="25"> Many people were given shelter in schools, guesthouses and public buildings, ``but most of the people do not want to leave their homes,'' Shahi said.</s>

<s docid="AP880822-0075" num="32" wdcount="16"> He said water supplies were still adequate and there were no reports of disease breaking out.</s>

<s docid="AP880822-0075" num="33" wdcount="15"> Prime Minister Rajiv Gandhi flew to Bihar to tour some of the hardest hit areas.</s>

<s docid="AP880822-0075" num="34" wdcount="16"> The government said it would release a detailed report after he returned to the capital tonight.</s>

<s docid="AP880822-0075" num="35" wdcount="20"> Prime Minister Marich Man Singh Shrestha of Nepal visited some of the victims at Bir Hospital in his capital, Katmandu.</s>

<s docid="AP880822-0075" num="36" wdcount="19"> The quake roused people from their sleep in Bihar and nine other Indian states and central and eastern Nepal.</s>

<s docid="AP880822-0075" num="37" wdcount="12"> It lasted about a minute and aftershocks continued for about an hour.</s>

<s docid="AP880822-0075" num="38" wdcount="26"> Rail tracks sank into the soggy ground and bridges over rising rivers cracked, paralyzing train service and road travel in many parts of the devastated areas.</s>

<s docid="AP880822-0075" num="39" wdcount="12"> Parts of northern Bangladesh and the capital, Dhaka, also felt the tremor.</s>

<s docid="AP880822-0075" num="40" wdcount="17"> There were reports that 50 people were injured, most by jumping from their houses during the quake.</s>

<s docid="AP880822-0075" num="41" wdcount="27"> Witnesses in Darbhanga, an Indian city of 800,000 about 45 miles south of the epicenter, said the only warnings were hissing sounds, rattling doors and cracking windows.</s>

<s docid="AP880822-0075" num="42" wdcount="15"> Women began blowing conch shells, following an ancient tradition believed to appease the weather gods.</s>

<s docid="AP880822-0075" num="43" wdcount="20"> More than 25,000 houses were flattened in Darbhanga, as well as the districts of Munger and Madhubani, Indian officials said.</s>

<s docid="AP880822-0075" num="44" wdcount="14"> In Madhubani, the Bhootahi Balan River jumped its banks and flooded nearly 50 villages.</s>

<s docid="AP880822-0075" num="45" wdcount="22"> Officials said at least 45 people died, but it was not known whether the deaths were due to floods or collapsing houses.</s>

<s docid="AP880822-0075" num="46" wdcount="12"> It was the worst quake to strike the region in 38 years.</s>

<s docid="AP880822-0075" num="47" wdcount="16"> A temblor rumbled through the Indian state of Assam on the India-China border in August 1950.</s>

<s docid="AP880822-0075" num="48" wdcount="17"> Official accounts said more than 1,500 people died, but seismologists said their records showed 30,000 were killed.</s>

<s docid="AP880822-0075" num="49" wdcount="21"> The Richter scale is a gauge of energy released by an earthquake, as measured by ground motion recorded on a seismograph.</s>

<s docid="AP880822-0075" num="50" wdcount="13"> Every increase of one number means the ground motion is 10 times greater.</s>

<s docid="AP880822-0075" num="51" wdcount="13"> A quake of magnitude 6 can cause severe damage in populated areas .</s>
</TEXT>
</DOC>
