<DOC>
<DOCNO>

<s docid="AP880823-0059" num="1" wdcount="1"> AP880823-0059</s>
</DOCNO>
<FILEID>

<s docid="AP880823-0059" num="2" wdcount="2"> AP-NR-08-23-88 0705EDT</s>
</FILEID>
<FIRST>

<s docid="AP880823-0059" num="3" wdcount="7"> u i PM-Earthquake 1stLd-Writethru a0496 08-23 0697</s>
</FIRST>
<SECOND>

<s docid="AP880823-0059" num="4" wdcount="6"> PM-Earthquake, 1st Ld - Writethru, a0496,0715</s>
</SECOND>
<HEAD>

<s docid="AP880823-0059" num="5" wdcount="5"> Rescuers Cope With Rains, Aftershocks</s>
</HEAD>
<NOTE>

<s docid="AP880823-0059" num="6" wdcount="11"> Eds: LEADS with 3 grafs to UPDATE with higher death toll.</s>

<s docid="AP880823-0059" num="7" wdcount="8"> PickS up 4th graf pvs `Officials in ...'</s>
</NOTE>
<BYLINE>

<s docid="AP880823-0059" num="8" wdcount="3"> By RAJU GOPALKRISHNAN</s>
</BYLINE>
<BYLINE>

<s docid="AP880823-0059" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880823-0059" num="10" wdcount="3"> BIRATNAGAR, Nepal (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880823-0059" num="11" wdcount="31"> Rescue workers coped with aftershocks and heavy rain today in an effort to reach remote regions of the Himalayas to help victims of an earthquake whose official death toll neared 700.</s>

<s docid="AP880823-0059" num="12" wdcount="18"> Rumors predicting another large quake sent thousands of panic-stricken people fleeing from their homes in India and Nepal.</s>

<s docid="AP880823-0059" num="13" wdcount="24"> Sunday's pre-dawn quake registered 6.5 on the Richter scale and claimed at least 497 lives in Nepal and 200 in India, government officials said.</s>

<s docid="AP880823-0059" num="14" wdcount="24"> Officials in both countries said they expected the death toll to climb when reports arrived from regions difficult to reach even in good weather.</s>

<s docid="AP880823-0059" num="15" wdcount="15"> The quake injured at least 2,000 people in India and 1,000 in Nepal, officials said.</s>

<s docid="AP880823-0059" num="16" wdcount="46"> In Biratnagar, a city near the Indian border 150 miles east of the Nepalese capital Katmandu, residents poured into the streets before dawn today as men ran from houses to house, shouting that a message came from Katmandu that a new quake was expected before dawn.</s>

<s docid="AP880823-0059" num="17" wdcount="13"> Police in the city of 300,000 people said they received no such message.</s>

<s docid="AP880823-0059" num="18" wdcount="23"> ``I have tried to tell them they are making a mistake, but no one will listen to me,'' said Dabal Singh, an inspector.</s>

<s docid="AP880823-0059" num="19" wdcount="15"> Anonymous telephone calls with similar rumors roused hundreds of people in Katmandu, also before dawn.</s>

<s docid="AP880823-0059" num="20" wdcount="18"> Sunday's quake was felt in the capital, but no deaths or serious damage were reported in the city.</s>

<s docid="AP880823-0059" num="21" wdcount="24"> In Patna, India, thousands of people huddled in the rain in open courtyards Monday as rumors swept the city that another quake was imminent.</s>

<s docid="AP880823-0059" num="22" wdcount="13"> Patna is the capital of Bihar state, the worst hit area in India.</s>

<s docid="AP880823-0059" num="23" wdcount="25"> A quake registering 5.1 on the Richter scale shook eastern Nepal late Monday afternoon, but there were no immediate reports of new casualties or damage.</s>

<s docid="AP880823-0059" num="24" wdcount="9"> In general, however, the intensity of aftershocks has lessened.</s>

<s docid="AP880823-0059" num="25" wdcount="25"> ``Compared to the ones on Sunday and Monday, they have been declining,'' Madhav Prasad Pandy, senior seismologist at Nepal's Department of Geology, said in Katmandu.</s>

<s docid="AP880823-0059" num="26" wdcount="15"> He said most aftershocks had declined to a reading of 1 on the Richter scale.</s>

<s docid="AP880823-0059" num="27" wdcount="15"> Rain continued in quake-affected areas, hampering access on muddy roads already cracked by the quake.</s>

<s docid="AP880823-0059" num="28" wdcount="7"> Landslides blocked many roads to devastated areas.</s>

<s docid="AP880823-0059" num="29" wdcount="18"> Railroad tracks sank into the mud, and the quake also cracked bridges over rivers swollen by the monsoon.</s>

<s docid="AP880823-0059" num="30" wdcount="21"> In India, the area with the greatest damage and casualties was just south of the border in Bihar, India's poorest state.</s>

<s docid="AP880823-0059" num="31" wdcount="14"> News reports said 400 people died in Bihar state, double the Indian government's count.</s>

<s docid="AP880823-0059" num="32" wdcount="28"> Bihar officials said the reports were exaggerated, while opposition politicians in the state accused the government of suppressing information and claimed the death toll was close to 1,500.</s>

<s docid="AP880823-0059" num="33" wdcount="23"> Tremors flattened more than 25,000 houses in India, officials said, and the Bhoothai Balan River flooded nearly 50 villages in the Madhubani district.</s>

<s docid="AP880823-0059" num="34" wdcount="17"> Indian army soldiers helped with relief efforts, and the navy and air force were put on alert.</s>

<s docid="AP880823-0059" num="35" wdcount="14"> Nepalese soldiers, police and volunteers joined forces in the kingdom's remote mountains and valleys.</s>

<s docid="AP880823-0059" num="36" wdcount="26"> Niranjan Thapa of the Home Minstry reported extensive damage in 21 of Nepal's 75 districts and at least four affected districts reported 50 or more deaths.</s>

<s docid="AP880823-0059" num="37" wdcount="15"> Officials distributed 88-pound bags of rice to families in this kingdom of 17 million people.</s>

<s docid="AP880823-0059" num="38" wdcount="22"> Government officials said many offers of assistance had come from abroad, but no decision had been made about whether to accept them.</s>

<s docid="AP880823-0059" num="39" wdcount="2"> A U.S.</s>

<s docid="AP880823-0059" num="40" wdcount="17"> Embassy official said the embassy had offered $25,000 in immediate aid but had not received a response.</s>

<s docid="AP880823-0059" num="41" wdcount="26"> The quake was the worst in the region since a temblor in India's eastern state of Assam killed 1,500 people in 1950, according to official accounts.</s>

<s docid="AP880823-0059" num="42" wdcount="12"> Seismologists said their records showed a death toll of at least 30,000.</s>

<s docid="AP880823-0059" num="43" wdcount="19"> The Richter scale measures ground motion as recorded on seismographs and each number represents aa tenflod increaase in intensity.</s>

<s docid="AP880823-0059" num="44" wdcount="22"> A quake of 6 on the scale is capable of causing severe damage, while one measuring 5 can cause considerable damage .</s>
</TEXT>
</DOC>
