<DOC>
<DOCNO>

<s docid="AP880824-0050" num="1" wdcount="1"> AP880824-0050</s>
</DOCNO>
<FILEID>

<s docid="AP880824-0050" num="2" wdcount="2"> AP-NR-08-24-88 0448EDT</s>
</FILEID>
<FIRST>

<s docid="AP880824-0050" num="3" wdcount="5"> r i PM-Earthquake 08-24 0531</s>
</FIRST>
<SECOND>

<s docid="AP880824-0050" num="4" wdcount="1"> PM-Earthquake,0549</s>
</SECOND>
<HEAD>

<s docid="AP880824-0050" num="5" wdcount="6"> Death Toll at 749 In Quake</s>
</HEAD>
<BYLINE>

<s docid="AP880824-0050" num="6" wdcount="3"> By RAJU GOPALAKRISHNAN</s>
</BYLINE>
<BYLINE>

<s docid="AP880824-0050" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880824-0050" num="8" wdcount="3"> DHARAN, Nepal (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880824-0050" num="9" wdcount="27"> Police bulldozed unstable brick and mud houses today while those left homeless by an earthquake that killed at least 749 people sought shelter and awaited government aid.</s>

<s docid="AP880824-0050" num="10" wdcount="24"> Casualty reports continued to trickle in from remote parts of this Himalayan mountain kingdom as relief workers fanned out through the foothills and valleys.</s>

<s docid="AP880824-0050" num="11" wdcount="8"> Sunday's pre-dawn quake struck near the India-Nepal border.</s>

<s docid="AP880824-0050" num="12" wdcount="11"> Some roads were flooded by heavy rains that followed the quake.</s>

<s docid="AP880824-0050" num="13" wdcount="15"> Others had cracks three feet deep or were blocked by boulders the size of houses.</s>

<s docid="AP880824-0050" num="14" wdcount="17"> At least 549 people were killed in Nepal, said Tek Bahadur Thapa of the Home Affairs Ministry.</s>

<s docid="AP880824-0050" num="15" wdcount="4"> Dharan was hardest hit.</s>

<s docid="AP880824-0050" num="16" wdcount="11"> At least 131 bodies were found in the city of 100,000.</s>

<s docid="AP880824-0050" num="17" wdcount="42"> Indian officials have maintained since Monday that the death toll in their country was 200 or less, but the figure was questioned by opposition politicians, survivors and the local media, including the Times of India, a newspaper that generally supports the government.</s>

<s docid="AP880824-0050" num="18" wdcount="12"> They put the India death count at anywhere from 400 to 1,500.</s>

<s docid="AP880824-0050" num="19" wdcount="10"> Indian officials said 200 people were injured in the quake.</s>

<s docid="AP880824-0050" num="20" wdcount="12"> Nepalese officials listed 752 injured, down from their earlier estimate of 1,000.</s>

<s docid="AP880824-0050" num="21" wdcount="41"> In Bhaktapur, a city of 50,000 where seven people died in the quake, 63-year-old Nhuchhe Raj Sakya said his five-story brick and mud house had nearly fallen down but that he and his family of 10 were still living in it.</s>

<s docid="AP880824-0050" num="22" wdcount="8"> ``What else can we do''? the goldsmith said.</s>

<s docid="AP880824-0050" num="23" wdcount="4"> ``We have no tent.</s>

<s docid="AP880824-0050" num="24" wdcount="6"> How can I leave my place''?</s>

<s docid="AP880824-0050" num="25" wdcount="22"> Prime Minister Marich Man Singh Shrestha visited Dharan on Tuesday and surveyed heaps of bricks that were once three-story and five-story houses.</s>

<s docid="AP880824-0050" num="26" wdcount="15"> ``This is the biggest calamity to strike Nepal,'' Shrestha said as he toured the town.</s>

<s docid="AP880824-0050" num="27" wdcount="18"> Dharan, 105 miles southeast of Katmandu, sits on a rolling plain at the base of a steep hill.</s>

<s docid="AP880824-0050" num="28" wdcount="25"> Most of the victims died in their houses, which were made of bricks held together by mud that had loosened during the seasonal monsoon rains.</s>

<s docid="AP880824-0050" num="29" wdcount="17"> Police Inspector G. Adhikari said bulldozers have demolished more than 50 houses deemed too dangerous for habitation.</s>

<s docid="AP880824-0050" num="30" wdcount="20"> ``We will continue to demolish houses until we are satisfied (the ones remaining) are safe to live in,'' he said.</s>

<s docid="AP880824-0050" num="31" wdcount="22"> Adhikari said local officials had not yet heard from the government on compensation or new housing for people whose homes were demolished.</s>

<s docid="AP880824-0050" num="32" wdcount="19"> Most of the homeless have moved in with neighbors or found shelter in tents erected on the soggy earth.</s>

<s docid="AP880824-0050" num="33" wdcount="46"> The earthquake, which struck when most people were still asleep, registered 6.5 on the Richter scale and was the deadliest quake in the region since 1950, when a temblor in the east Indian state of Assam killed 1,500 by official count and 30,000 by seismologists' accounts.</s>

<s docid="AP880824-0050" num="34" wdcount="30"> Aftershocks have persisted since Sunday's quake, and rumors of an impending new quake sent thousands of people fleeing into the streets in panic before dawn Tuesday in Katmandu and Dharan.</s>

<s docid="AP880824-0050" num="35" wdcount="13"> The rumors started with anonymous telephone calls and spread by word of mouth.</s>

<s docid="AP880824-0050" num="36" wdcount="14"> In Dharan, men ran from houses to houses rousing people from their sleep .</s>
</TEXT>
</DOC>
