<DOC>
<DOCNO>

<s docid="AP880823-0127" num="1" wdcount="1"> AP880823-0127</s>
</DOCNO>
<FILEID>

<s docid="AP880823-0127" num="2" wdcount="2"> AP-NR-08-23-88 1531EDT</s>
</FILEID>
<FIRST>

<s docid="AP880823-0127" num="3" wdcount="6"> u i AM-Earthquake Bjt 08-23 0769</s>
</FIRST>
<SECOND>

<s docid="AP880823-0127" num="4" wdcount="2"> AM-Earthquake, Bjt,0791</s>
</SECOND>
<HEAD>

<s docid="AP880823-0127" num="5" wdcount="9"> Unsafe Buildings Bulldozed as Recovery From Killer Quake Continues</s>
</HEAD>
<BYLINE>

<s docid="AP880823-0127" num="6" wdcount="3"> By RAJU GOPALKRISHNAN</s>
</BYLINE>
<BYLINE>

<s docid="AP880823-0127" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880823-0127" num="8" wdcount="3"> DHARAN, Nepal (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880823-0127" num="9" wdcount="27"> Police bulldozed teetering houses Tuesday to keep people from returning to homes left unsafe by an earthquake that killed at least 731 people in India and Nepal.</s>

<s docid="AP880823-0127" num="10" wdcount="24"> Officials in both countries expected the death toll to rise as relief workers reached remote towns that have been inaccessible since Sunday's devastating quake.</s>

<s docid="AP880823-0127" num="11" wdcount="30"> Some roads were flooded by heavy rains that continued Tuesday, while others had 3-foot-deep cracks or were blocked by boulders the size of houses in the Himalayan mountains and valleys.</s>

<s docid="AP880823-0127" num="12" wdcount="19"> At least 531 people were killed in Nepal, said Tek Bahadur Thapa, additional secretary in the Home Affairs Ministry.</s>

<s docid="AP880823-0127" num="13" wdcount="25"> Prime Minister Marich Man Singh Shrestha visited Dharan, one of the hardest-hit towns, and surveyed heaps of bricks that were once three-story and five-story houses.</s>

<s docid="AP880823-0127" num="14" wdcount="15"> ``This is the biggest calamity to strike Nepal,'' Shrestha said as he toured the town.</s>

<s docid="AP880823-0127" num="15" wdcount="31"> India reported an official death toll of 200, but the figure was disputed by news media and opposition politicians who put the Indian death count at anywhere from 400 to 1,500.</s>

<s docid="AP880823-0127" num="16" wdcount="18"> In Darbhanga, India on Tuesday, worshipers offered sweets, milk and coconuts to appease the Hindu god of destruction.</s>

<s docid="AP880823-0127" num="17" wdcount="34"> Women dressed in colorful saris gathered at countryside temples in the quake-ravaged areas of eastern Bihar state to pray and present their offerings to Lord Shiva, the god of destruction in the Hindu trinity.</s>

<s docid="AP880823-0127" num="18" wdcount="16"> ``If God is pleased, nothing will happen,'' said one woman, who refused to give her name.</s>

<s docid="AP880823-0127" num="19" wdcount="20"> The earthquake, which struck shortly before daybreak Sunday when most people were still asleep, registered 6.5 on the Richter scale.</s>

<s docid="AP880823-0127" num="20" wdcount="30"> It was the deadliest quake in the region since 1950 when a temblor in the east Indian state of Assam killed 1,500 by official count and 30,000 by seismologists' accounts.</s>

<s docid="AP880823-0127" num="21" wdcount="18"> Dharan, 105 miles southeast of Katmandu, sits on a rolling plain at the base of a steep hill.</s>

<s docid="AP880823-0127" num="22" wdcount="12"> At least 131 bodies have been found in the town of 100,000.</s>

<s docid="AP880823-0127" num="23" wdcount="25"> Most of the victims died in their houses, which were made of bricks held together by mud that had loosened during the seasonal monsoon rains.</s>

<s docid="AP880823-0127" num="24" wdcount="17"> Police Inspector G. Adhikari said bulldozers have demolished more than 50 houses deemed too dangerous for habitation.</s>

<s docid="AP880823-0127" num="25" wdcount="20"> ``We will continue to demolish houses until we are satisfied (the ones remaining) are safe to live in,'' he said.</s>

<s docid="AP880823-0127" num="26" wdcount="16"> British soldiers from a nearby Gurkha recruiting center pitched in with cranes to aid the demolition.</s>

<s docid="AP880823-0127" num="27" wdcount="24"> Dharan is in the heart of regional famed for fierce Gurkha fighters who have served in the British army for more than 150 years.</s>

<s docid="AP880823-0127" num="28" wdcount="22"> Adhikari said local officials had not yet heard from the government on compensation or new housing for people whose homes were demolished.</s>

<s docid="AP880823-0127" num="29" wdcount="19"> Most of the homeless have moved in with neighbors of found shelter in tents erected on the soggy earth.</s>

<s docid="AP880823-0127" num="30" wdcount="15"> The hardest hit areas in India were in Bihar state just across the Nepalese border.</s>

<s docid="AP880823-0127" num="31" wdcount="14"> Rescuers in army helicopters searched for survivors in Bihar's Darbhanga, Madhubani and Mungar districts.</s>

<s docid="AP880823-0127" num="32" wdcount="23"> Other helicopters ferried medicine, rice, cooking oil, clothes and tents to police trapped in the most remote regions of Bihar, India's poorest state.</s>

<s docid="AP880823-0127" num="33" wdcount="18"> Heavy rains, overflowing rivers and submerged bridges and roads hampered attempts by 1,000 Indian soldiers to provide assistance.</s>

<s docid="AP880823-0127" num="34" wdcount="23"> In Nepal, 88-pound bags of rice were being distributed to families affected by the quake, but officials were unable to give any figures.</s>

<s docid="AP880823-0127" num="35" wdcount="37"> International agencies operating in Nepal were gearing up to contribute supplies or assistance but have not yet heard from the government on what was wanted, according to several foreign relief workers who spoke on condition of anonymity.</s>

<s docid="AP880823-0127" num="36" wdcount="20"> Shrestha said the mountain kingdom had not sought foreign aid because ``we are still assessing the magnitude of the tragedy''.</s>

<s docid="AP880823-0127" num="37" wdcount="12"> Some supplies, medicine and health workers arrived in eastern Nepal on Tuesday.</s>

<s docid="AP880823-0127" num="38" wdcount="10"> Donors included UNICEF and the government of Japan and Britain.</s>

<s docid="AP880823-0127" num="39" wdcount="8"> Nepal is one of the world's poorest countries.</s>

<s docid="AP880823-0127" num="40" wdcount="19"> Two-third of the children under age of 5 suffer from malnutrition and life expectancy is 52, according to UNICEF.</s>

<s docid="AP880823-0127" num="41" wdcount="29"> A nation of 17 million, Nepal has one doctor for every 22,650 people, compared with 5,000 people per doctor in India and 780 per doctor in the United States.</s>

<s docid="AP880823-0127" num="42" wdcount="30"> Aftershocks have persisted since Sunday's earthquake, and rumors of an impending new quake sent thousands of people fleeing into the streets in panic before dawn Tuesday in Katmandu and Dharan.</s>

<s docid="AP880823-0127" num="43" wdcount="13"> The rumors started with anonymous telephone calls and spread by word of mouth.</s>

<s docid="AP880823-0127" num="44" wdcount="14"> In Dharan, men ran from houses to houses rousing people from their sleep .</s>
</TEXT>
</DOC>
