<DOC>
<DOCNO>

<s docid="AP880824-0139" num="1" wdcount="1"> AP880824-0139</s>
</DOCNO>
<FILEID>

<s docid="AP880824-0139" num="2" wdcount="2"> AP-NR-08-24-88 1425EDT</s>
</FILEID>
<FIRST>

<s docid="AP880824-0139" num="3" wdcount="5"> r i AM-Earthquake 08-24 0625</s>
</FIRST>
<SECOND>

<s docid="AP880824-0139" num="4" wdcount="1"> AM-Earthquake,0646</s>
</SECOND>
<HEAD>

<s docid="AP880824-0139" num="5" wdcount="10"> Earthquake Death Toll Rises As Rescue Teams Reach Remote Areas</s>
</HEAD>
<BYLINE>

<s docid="AP880824-0139" num="6" wdcount="3"> By RAJU GOPALKRISHNANA</s>
</BYLINE>
<BYLINE>

<s docid="AP880824-0139" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880824-0139" num="8" wdcount="3"> KATMANDU, Nepal (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880824-0139" num="9" wdcount="32"> The death toll from the Himalayan earthquake topped 750 on Wednesday as rescue workers hampered by monsoon rains, aftershocks and washed out roads reached remote areas of Nepal and found more bodies.</s>

<s docid="AP880824-0139" num="10" wdcount="36"> In eastern India, which also was devastated by the quake, cracks were found in the embankments of six rivers in Bihar state, and officials said floods could pose the next threat to the 10 million people.</s>

<s docid="AP880824-0139" num="11" wdcount="6"> ``It may be the second coming.</s>

<s docid="AP880824-0139" num="12" wdcount="34"> All the rivers are in full spate, and if the embankments breach, we are in for serious problems,'' said Puranman Mittal, the relief commissioner in Bihar state, which suffered the most damage in India.</s>

<s docid="AP880824-0139" num="13" wdcount="17"> Bihar residents ran screaming through the streets on Wednesday when a mild tremor rumbled through the area.</s>

<s docid="AP880824-0139" num="14" wdcount="15"> No casualties or damage was reported, witnesses and the Seismological Observatory in New Delhi said.</s>

<s docid="AP880824-0139" num="15" wdcount="21"> Residents in Dharan, the worst-hit area of Nepal, also raced from their homes Wednesday during two aftershocks, officials in Katmandu said.</s>

<s docid="AP880824-0139" num="16" wdcount="15"> No further damage was reported in the city, where 100 houses collapsed during the quake.</s>

<s docid="AP880824-0139" num="17" wdcount="21"> Rescue workers demolished 50 homes in Dharan on Wednesday that were severely damaged in the temblor, police inspector G. Adhikari said.</s>

<s docid="AP880824-0139" num="18" wdcount="21"> ``We will continue to demolish houses until we are satisfied (the ones remaining) are to safe to live in,'' he said.</s>

<s docid="AP880824-0139" num="19" wdcount="25"> ``This is the biggest calamity to strike Nepal,'' Prime Minister Marich Man Singh Shrestha, said Tuesday after a tour of devastated areas in his nation.</s>

<s docid="AP880824-0139" num="20" wdcount="22"> At least 758 people died and 950 were injured in both countries Sunday when the earthquake jolted the mountainous India-Nepal border region.</s>

<s docid="AP880824-0139" num="21" wdcount="26"> It was the deadliest quake to strike the subcontinent since 1950, when, by official count, 1,500 people were killed in the eastern Indian state of Assam.</s>

<s docid="AP880824-0139" num="22" wdcount="14"> Indian officials said Wednesday that at least 196 died in India in Sunday's disaster.</s>

<s docid="AP880824-0139" num="23" wdcount="24"> Officials in Nepal said at least 562 people were killed in Nepal, including 31 people whose bodies were found in remote areas on Wednesday.</s>

<s docid="AP880824-0139" num="24" wdcount="32"> In India's Bihar state, officials said the water had reached dangerous levels and was still rising in six rivers: the Ganges, the Ghagara, the Burigandak, the Bagmati, the Koshi and the Mahananada.</s>

<s docid="AP880824-0139" num="25" wdcount="26"> To make matters worse, survey teams found cracks in the embankments of the six rivers, which are swollen by monsoon rains that began in late June.</s>

<s docid="AP880824-0139" num="26" wdcount="17"> Engineers tried to strengthen the weakened embankments with cement, and helicopters made aerial surveys watching for ruptures.</s>

<s docid="AP880824-0139" num="27" wdcount="23"> As survivors in both countries began rebuilding homes damaged or destroyed by the quake, medicine, food and financial aid began arriving from abroad.</s>

<s docid="AP880824-0139" num="28" wdcount="8"> Elroy J. Carlson, an official at the U.S.</s>

<s docid="AP880824-0139" num="29" wdcount="11"> Embassy in Katmandu, said the United State offered $25,000 in aid.</s>

<s docid="AP880824-0139" num="30" wdcount="18"> In New Delhi, U.S. Ambassador John Gunther Dean presented the government with a similar amount for Indian victims.</s>

<s docid="AP880824-0139" num="31" wdcount="19"> Michael Hamilton, an official at the British Embassy in Katmandu, said three medical teams had been sent to Dharan.</s>

<s docid="AP880824-0139" num="32" wdcount="12"> ``The teams are carrying two truckloads of blood and medicine,'' Hamilton said.</s>

<s docid="AP880824-0139" num="33" wdcount="17"> The British army also runs a military hospital in Dharan, where at least 100 people were admitted.</s>

<s docid="AP880824-0139" num="34" wdcount="16"> The government hospital in Dharan treated hundreds of people injured when brick and wood houses collapsed.</s>

<s docid="AP880824-0139" num="35" wdcount="21"> U.N. agencies and the Red Cross also sent medical teams to Nepal, and the government began distributing 90-pound bags of rice.</s>

<s docid="AP880824-0139" num="36" wdcount="24"> The relief efforts were hampered in both countries by heavy rains which cut off communications and road links to several of the affected areas.</s>

<s docid="AP880824-0139" num="37" wdcount="17"> ``The earthquake hit a wide area, and it is a big job to reach the remote villages.</s>

<s docid="AP880824-0139" num="38" wdcount="13"> But we are trying,'' said Mittal, the relief official in Bihar state .</s>
</TEXT>
</DOC>
