<DOC>
<DOCNO>

<s docid="AP900623-0009" num="1" wdcount="1"> AP900623-0009</s>
</DOCNO>
<FILEID>

<s docid="AP900623-0009" num="2" wdcount="2"> AP-NR-06-23-90 0148EDT</s>
</FILEID>
<FIRST>

<s docid="AP900623-0009" num="3" wdcount="5"> r i PM-CheckpointCharlie 06-23 0786</s>
</FIRST>
<SECOND>

<s docid="AP900623-0009" num="4" wdcount="2"> PM-Checkpoint Charlie,0816</s>
</SECOND>
<HEAD>

<s docid="AP900623-0009" num="5" wdcount="6"> Famed Border Crossing Consigned to History</s>
</HEAD>
<NOTE>

<s docid="AP900623-0009" num="6" wdcount="7"> Eds: Also in Saturday AMs report .</s>
</NOTE>
<HEAD>

<s docid="AP900623-0009" num="7" wdcount="2"> LaserPhotos FRA4,BER1,BER5</s>
</HEAD>
<BYLINE>

<s docid="AP900623-0009" num="8" wdcount="3"> By MARK FRITZ</s>
</BYLINE>
<BYLINE>

<s docid="AP900623-0009" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900623-0009" num="10" wdcount="3"> WEST BERLIN (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900623-0009" num="11" wdcount="12"> Maik Polster was a stern-faced member of the East German secret police.</s>

<s docid="AP900623-0009" num="12" wdcount="7"> Patrick Gainey took pictures for the U.S.</s>

<s docid="AP900623-0009" num="13" wdcount="14"> Army. Andreas Bratke was an East German who wanted to be a West German.</s>

<s docid="AP900623-0009" num="14" wdcount="12"> Illa Wobig saw eight people just like him die on her street.</s>

<s docid="AP900623-0009" num="15" wdcount="44"> What they all had in common was a little white shack on the west side of the Berlin Wall, a guardhouse with a funny name that stood as a chilling symbol of the tensions that divided a street, a city, a nation, the world.</s>

<s docid="AP900623-0009" num="16" wdcount="35"> Checkpoint Charlie, the famed Allied border crossing on the west side of the Berlin Wall, was lifted into the sky by a giant crane Friday, placed gently onto a flatbed truck and consigned to history.</s>

<s docid="AP900623-0009" num="17" wdcount="27"> It was emptied, locked and taken away in an elaborate ceremony attended by six foreign ministers, a brace of generals, a brass brand and hundreds of reporters.</s>

<s docid="AP900623-0009" num="18" wdcount="6"> ``Sir, dismiss your detachment''! French Maj.</s>

<s docid="AP900623-0009" num="19" wdcount="19"> Gen. Francois Lann barked to a young American officer, who crisply led away the last contingent of military police.</s>

<s docid="AP900623-0009" num="20" wdcount="24"> The public was not invited to the ceremony on Friedrich Street, the avenue blocked by Checkpoint Charlie and its once-feared East German counterpart nearby.</s>

<s docid="AP900623-0009" num="21" wdcount="15"> Illa Wobig raised six children in a fourth-floor apartment just 20 yards from Checkpoint Charlie.</s>

<s docid="AP900623-0009" num="22" wdcount="15"> They saw it from their window for 24 years, and they saw it disappear Friday.</s>

<s docid="AP900623-0009" num="23" wdcount="12"> ``I saw eight people shot to death on that street,'' said Mrs.</s>

<s docid="AP900623-0009" num="24" wdcount="2"> Wobig, 55.</s>

<s docid="AP900623-0009" num="25" wdcount="13"> ``I saw an East German officer try to go under a guard rail.</s>

<s docid="AP900623-0009" num="26" wdcount="6"> He was shot in the neck''.</s>

<s docid="AP900623-0009" num="27" wdcount="9"> She said she saw at least 20 successful escapes.</s>

<s docid="AP900623-0009" num="28" wdcount="15"> ``Some were in cars and some came through a tunnel across the street,'' she said.</s>

<s docid="AP900623-0009" num="29" wdcount="10"> ``Some would walk very slowly, look around and just run''.</s>

<s docid="AP900623-0009" num="30" wdcount="20"> She is not sure if one of the people she saw was Andreas Bratke, a 23-year-old East Berlin construction worker.</s>

<s docid="AP900623-0009" num="31" wdcount="20"> Tunnels, balloons, customized vehicles and other elaborate methods were used to flee past the Berlin Wall by desperate East Germans.</s>

<s docid="AP900623-0009" num="32" wdcount="3"> Bratke just ran.</s>

<s docid="AP900623-0009" num="33" wdcount="9"> ``I ran as fast as I could,'' he said.</s>

<s docid="AP900623-0009" num="34" wdcount="5"> ``I still cannot believe it''.</s>

<s docid="AP900623-0009" num="35" wdcount="8"> Bratke is now a West Berlin engineering student.</s>

<s docid="AP900623-0009" num="36" wdcount="8"> He was taking his certification examinations this week.</s>

<s docid="AP900623-0009" num="37" wdcount="26"> Eight months after Bratke made his bold escape, Sgt. Patrick Gainey was coming back from a party when he saw a huge commotion near Checkpoint Charlie.</s>

<s docid="AP900623-0009" num="38" wdcount="19"> ``This guy had driven a cement truck with his girlfriend and baby through the checkpoint,'' said Gainey, a U.S.</s>

<s docid="AP900623-0009" num="39" wdcount="2"> Army photographer.</s>

<s docid="AP900623-0009" num="40" wdcount="12"> ``He drove a half-mile into the west side just to make sure.</s>

<s docid="AP900623-0009" num="41" wdcount="11"> When he stopped, he asked if he was in West Berlin''.</s>

<s docid="AP900623-0009" num="42" wdcount="14"> The escapee was Hans-Joachim Pofahl, who made the crossing through a hail of bullets.</s>

<s docid="AP900623-0009" num="43" wdcount="13"> East Germany's border guards were as feared as members of the secret police.</s>

<s docid="AP900623-0009" num="44" wdcount="12"> According to guard Maik Polster, they were members of the secret police.</s>

<s docid="AP900623-0009" num="45" wdcount="28"> ``I was with the state security,'' said Polster, 23, as he genially waved tourists through the East German checkpoint that is expected to follow Checkpoint Charlie into oblivion.</s>

<s docid="AP900623-0009" num="46" wdcount="11"> ``We had to maintain a certain level of appearance,'' he said.</s>

<s docid="AP900623-0009" num="47" wdcount="4"> ``No smiling, no joking.</s>

<s docid="AP900623-0009" num="48" wdcount="6"> We had to watch for everything''.</s>

<s docid="AP900623-0009" num="49" wdcount="16"> The stone-faced scrutiny of the East German border guards helped give Checkpoint Charlie its chilling cachet.</s>

<s docid="AP900623-0009" num="50" wdcount="10"> The checkpoint went up with the Berlin Wall in 1961.</s>

<s docid="AP900623-0009" num="51" wdcount="22"> With the wall being dismantled daily in anticipation of German unification, U.S. officials decided to remove Checkpoint Charlie with a grand flourish.</s>

<s docid="AP900623-0009" num="52" wdcount="26"> Secretary of State James A. Baker III, Soviet Foreign Minister Eduard Shevardnadze and their counterparts from France, Britain and the two Germanys presided over the ceremony.</s>

<s docid="AP900623-0009" num="53" wdcount="19"> While the Berlin Wall is coming down, temporary barricades were put up to keep the public from the ceremony.</s>

<s docid="AP900623-0009" num="54" wdcount="11"> Several hundred craned their necks to watch from a half-block away.</s>

<s docid="AP900623-0009" num="55" wdcount="28"> Eilli Wiechies, 60, watched the pageantry from his wheelchair on the sidewalk in front of his apartment house, one of the few regular people allowed on the grounds.</s>

<s docid="AP900623-0009" num="56" wdcount="17"> ``Finally, Germans can cross,'' he said, bitter that the Allied border crossing was reserved only for non-Germans.</s>

<s docid="AP900623-0009" num="57" wdcount="2"> A U.S.</s>

<s docid="AP900623-0009" num="58" wdcount="31"> Army band played ``That is the Berlin Atmosphere,'' a stirring old song about the old Berlin, as the white checkpoint building was lifted to within 30 feet of Mrs. Wobig's window.</s>

<s docid="AP900623-0009" num="59" wdcount="12"> A sign saying ``What a pity, Checkpoint Charlie,'' hung from her sill.</s>

<s docid="AP900623-0009" num="60" wdcount="11"> ``I saw Kennedy, Reagan and Carter give speeches here,'' she said.</s>

<s docid="AP900623-0009" num="61" wdcount="8"> ``I saw a James Bond movie filmed here.</s>

<s docid="AP900623-0009" num="62" wdcount="11"> This is wonderful for history, but it is sad for me.</s>

<s docid="AP900623-0009" num="63" wdcount="6"> It was part of my home.''</s>
</TEXT>
</DOC>
