<DOC>
<DOCNO>

<s docid="AP900621-0192" num="1" wdcount="1"> AP900621-0192</s>
</DOCNO>
<FILEID>

<s docid="AP900621-0192" num="2" wdcount="2"> AP-NR-06-21-90 2028EDT</s>
</FILEID>
<FIRST>

<s docid="AP900621-0192" num="3" wdcount="5"> u i AM-CheckpointCharlie 06-21 0323</s>
</FIRST>
<SECOND>

<s docid="AP900621-0192" num="4" wdcount="2"> AM-Checkpoint Charlie,0330</s>
</SECOND>
<HEAD>

<s docid="AP900621-0192" num="5" wdcount="8"> Famed Allied Border Crossing Ready for Removal Friday</s>
</HEAD>
<BYLINE>

<s docid="AP900621-0192" num="6" wdcount="3"> By MARK FRITZ</s>
</BYLINE>
<BYLINE>

<s docid="AP900621-0192" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900621-0192" num="8" wdcount="3"> EAST BERLIN (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900621-0192" num="9" wdcount="17"> Checkpoint Charlie, the famed Allied border crossing by the Berlin Wall, was to be hauled away Friday.</s>

<s docid="AP900621-0192" num="10" wdcount="26"> U.S. Army Sgt. Lorn Walsh late Thursday stood sentry for the last time by the little white shack, rendered unnecessary by the thaw in East-West relations.</s>

<s docid="AP900621-0192" num="11" wdcount="11"> ``This is a nice way to end my military service ...</s>

<s docid="AP900621-0192" num="12" wdcount="27"> to be here when they take it down,'' said Walsh, 23, a military police officer who leaves the army in six weeks to study for the priesthood.</s>

<s docid="AP900621-0192" num="13" wdcount="37"> A huge crane hung over the small house in the middle of the narrow street that leads to East Berlin, where a sign in English, German, Russian and French says: ``You are now leaving the American sector''.</s>

<s docid="AP900621-0192" num="14" wdcount="33"> Secretary of State James A. Baker III, Soviet Foreign Minister Eduard Shevardnadze and their colleagues from France, Britain and the two Germanys were to preside over a ceremony marking the checkpoint's removal Friday.</s>

<s docid="AP900621-0192" num="15" wdcount="28"> The envoys from the German states and the four World War II Allies that divided them were in East Berlin to discuss the international aspects of German unification.</s>

<s docid="AP900621-0192" num="16" wdcount="26"> Since East Germany overthrew its Communist government last fall and the German borders were opened, Checkpoint Charlie has become as superfluous as the crumbling Berlin Wall.</s>

<s docid="AP900621-0192" num="17" wdcount="21"> With huge sections of the Berlin Wall being ripped down daily, U.S. officials decided two weeks ago to remove Checkpoint Charlie.</s>

<s docid="AP900621-0192" num="18" wdcount="34"> The border crossing was the scene of stirring escapes and heartbreaking captures as East Germans tried flee to the West, breaking through East German control stations just 20 yards away from the Allied checkpoint.</s>

<s docid="AP900621-0192" num="19" wdcount="21"> East Germans once manned their side of the checkpoint with emotionless effiency, closely scrutinizing travel documents and creating a palpable tension.</s>

<s docid="AP900621-0192" num="20" wdcount="21"> Thursday night, they merely waved Westerners through their side of the checkpoint, although some tourists demanded their documents be checked .</s>
</TEXT>
</DOC>
