<DOC>
<DOCNO>

<s docid="AP900622-0087" num="1" wdcount="1"> AP900622-0087</s>
</DOCNO>
<FILEID>

<s docid="AP900622-0087" num="2" wdcount="2"> AP-NR-06-22-90 1236EDT</s>
</FILEID>
<FIRST>

<s docid="AP900622-0087" num="3" wdcount="6"> u i PM-Germany-Soviet 4thLd-Writethru 06-22 0576</s>
</FIRST>
<SECOND>

<s docid="AP900622-0087" num="4" wdcount="3"> PM-Germany-Soviet, 4th Ld-Writethru,a0539,0590</s>
</SECOND>
<HEAD>

<s docid="AP900622-0087" num="5" wdcount="9"> Soviets Say Germany Can Join NATO AFter Five Years</s>
</HEAD>
<NOTE>

<s docid="AP900622-0087" num="6" wdcount="22"> Eds: LEADS thruout to UPDATE with Soviets saying united Germany can join NATO after five years, US rejecting proposal, details and background.</s>

<s docid="AP900622-0087" num="7" wdcount="3"> No pickup .</s>
</NOTE>
<BYLINE>

<s docid="AP900622-0087" num="8" wdcount="4"> By DEBORAH G. SEWARD</s>
</BYLINE>
<BYLINE>

<s docid="AP900622-0087" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900622-0087" num="10" wdcount="3"> EAST BERLIN (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900622-0087" num="11" wdcount="28"> The Soviet Union said today that a united Germany can join NATO after a five-year transition period during which all Soviet and U.S. troops would leave the country.</s>

<s docid="AP900622-0087" num="12" wdcount="10"> The United States rejected the proposal, a U.S. official said.</s>

<s docid="AP900622-0087" num="13" wdcount="24"> The proposal was outlined by Soviet Foreign Minister Eduard Shevardnadze during international talks in East Berlin on the strategic future of a united Germany.</s>

<s docid="AP900622-0087" num="14" wdcount="31"> The remarks, a copy of which were obtained by The Associated Press, indicates that a united Germany would be free to join the Western NATO alliance after a five-year transitional period.</s>

<s docid="AP900622-0087" num="15" wdcount="26"> But in exchange, Western and Soviet troops would pull out of the country and Germany's own military strength would be sharply reduced, according to the proposal.</s>

<s docid="AP900622-0087" num="16" wdcount="9"> Shevardnadze made the proposal as he met with U.S.</s>

<s docid="AP900622-0087" num="17" wdcount="18"> Secretary of State James A. Baker III and their counterparts from Britain, France and the two German states.</s>

<s docid="AP900622-0087" num="18" wdcount="20"> ``I am underwhelmed,'' Baker said when asked about the Soviet proposal while posing for pictures with the other foreign ministers.</s>

<s docid="AP900622-0087" num="19" wdcount="22"> A U.S. official, speaking on condition of anonymity, said U.S. officials objected to the five-year time limit before Germany could join NATO.</s>

<s docid="AP900622-0087" num="20" wdcount="11"> The official said the other Western ministers expressed the same reservations.</s>

<s docid="AP900622-0087" num="21" wdcount="25"> The United States wants a united Germany to be a member of the North Atlantic Treaty Organization and the Soviet Union has been staunchly opposed.</s>

<s docid="AP900622-0087" num="22" wdcount="19"> West Germany now is a mainstay of NATO and East Germany is a member of the Soviet-led Warsaw Pact.</s>

<s docid="AP900622-0087" num="23" wdcount="31"> Shevardnadze said the Soviet proposal seeks to limit the strength of the German armed forces and ``to revamp their structure to make sure that they are rendered incapable for offensive operations''.</s>

<s docid="AP900622-0087" num="24" wdcount="11"> It said those reductions could be undertaken over a three-year period.</s>

<s docid="AP900622-0087" num="25" wdcount="13"> Germany also would be prevented from producing or deploying chemmical or nuclear weapons.</s>

<s docid="AP900622-0087" num="26" wdcount="29"> It also said that within six months of unification, all Western troops should leave West Berlin, which remains technically under military occupation by the United States, France and Britian.</s>

<s docid="AP900622-0087" num="27" wdcount="37"> The four nations would reduce their military forces in the country during a three-year period following unification first by 50 percent, then ``bring them down to a level of token contingents, or completely withdraw them from Germany''.</s>

<s docid="AP900622-0087" num="28" wdcount="29"> There are about 380,000 Soviet troops in East Germany, while a quarter-million U.S. troops are stationed in West Germany along with tens of thousands of British and French soldiers.</s>

<s docid="AP900622-0087" num="29" wdcount="29"> Previously, the Soviets had said their troops would stay in what is now East Germany for several years, but had left unclear the exact plans for pulling them out.</s>

<s docid="AP900622-0087" num="30" wdcount="32"> Shevardnadze, speaking earlier at a ceremony for the removal of the Western Allies' Checkpoint Charlie, said he wanted the Big Four Powers' troops out of ``greater Berlin'' within six months after unification.</s>

<s docid="AP900622-0087" num="31" wdcount="28"> The proposal, as translated into English by the Soviets and distributed to the news media, apparently would also include the Kremlin's soldiers stationed just outside the city proper.</s>

<s docid="AP900622-0087" num="32" wdcount="15"> The United States, France and Great Britain have an estimated 12,000 troops in West Berlin.</s>

<s docid="AP900622-0087" num="33" wdcount="31"> An official reached by telephone in the office of the military attache at the Soviet embassy in East Berlin said there were no Soviet troops stationed in the city proper .</s>
</TEXT>
</DOC>
