<DOC>
<DOCNO>

<s docid="AP900622-0080" num="1" wdcount="1"> AP900622-0080</s>
</DOCNO>
<FILEID>

<s docid="AP900622-0080" num="2" wdcount="2"> AP-NR-06-22-90 1133EDT</s>
</FILEID>
<FIRST>

<s docid="AP900622-0080" num="3" wdcount="7"> u i PM-CheckpointCharlie 4thLd-Writethru a0527 06-22 0653</s>
</FIRST>
<SECOND>

<s docid="AP900622-0080" num="4" wdcount="5"> PM-Checkpoint Charlie, 4th Ld-Writethru, a0527,0669</s>
</SECOND>
<HEAD>

<s docid="AP900622-0080" num="5" wdcount="9"> Famous Allied Checkpoint Dividing East And West Berlin Removed</s>
</HEAD>
<NOTE>

<s docid="AP900622-0080" num="6" wdcount="14"> Eds: To UPDATE with details about Shevardnadze proposal, SUB 8th graf pvs, `But the'...</s>

<s docid="AP900622-0080" num="7" wdcount="5"> Pickup 9th pvs, `Berlin has...'</s>
</NOTE>
<BYLINE>

<s docid="AP900622-0080" num="8" wdcount="3"> By MARK FRITZ</s>
</BYLINE>
<BYLINE>

<s docid="AP900622-0080" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900622-0080" num="10" wdcount="3"> WEST BERLIN (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900622-0080" num="11" wdcount="25"> Soldiers from three nations locked the doors of Checkpoint Charlie today and a crane whisked away the Cold War relic that symbolized a divided world.</s>

<s docid="AP900622-0080" num="12" wdcount="2"> A U.S.</s>

<s docid="AP900622-0080" num="13" wdcount="33"> Army band played a stirring song about old Berlin as the rectangular white sentry station, a place East Germans died trying to reach, was hoisted onto a truck for its passage into history.</s>

<s docid="AP900622-0080" num="14" wdcount="30"> The famed Allied checkpoint by the Berlin Wall was closed with an elaborate ceremony that brought together the top diplomats from the Germanys and the four World War II Allies.</s>

<s docid="AP900622-0080" num="15" wdcount="10"> ``For 29 years Checkpoint Charlie embodied the Cold War,'' U.S.</s>

<s docid="AP900622-0080" num="16" wdcount="19"> Secretary of State James A. Baker III told a crowd of invited guests and journalists on Berlin's Friedrich Street.</s>

<s docid="AP900622-0080" num="17" wdcount="22"> ``And now, 29 years after it was built, we meet here today to dismantle it and to bury the conflicts it created''.</s>

<s docid="AP900622-0080" num="18" wdcount="29"> Baker, Soviet Foreign Minister Eduard Shevardnadze and the foreign ministers from France, Britain and the two Germanys each heralded the end of the checkpoint as a symbol of change.</s>

<s docid="AP900622-0080" num="19" wdcount="31"> Shevardnadze called for the removal of Berlin's status as an Allied-controlled city and the withdrawal of troops within six months after the two German states unify, which could come in December.</s>

<s docid="AP900622-0080" num="20" wdcount="28"> The proposal, as translated into English by the Soviets and distributed later to news media, apparently would also include the Kremlin's soldiers stationed just outside the city proper.</s>

<s docid="AP900622-0080" num="21" wdcount="15"> The United States, France and Great Britain have an estimated 12,000 troops in West Berlin.</s>

<s docid="AP900622-0080" num="22" wdcount="20"> Berlin has been split into Soviet, U.S., British and France sectors and West Berlin remains technically separate from West Germany.</s>

<s docid="AP900622-0080" num="23" wdcount="26"> The German and Allied foreign ministers are meeting in East Berlin to discuss the status of the city and a united Germany's role in world affairs.</s>

<s docid="AP900622-0080" num="24" wdcount="21"> All borders are to be opened between the Berlins and the Germanys by July 2, when the nations merge their economies.</s>

<s docid="AP900622-0080" num="25" wdcount="26"> Large sections of the Berlin Wall are being dismantled daily, and U.S. officials decided to time the removal of Checkpoint Charlie with the foreign ministers' meeting.</s>

<s docid="AP900622-0080" num="26" wdcount="26"> A color guard of French, British and American soldiers strode to the building and locked the doors leading to each Allied nation's compartment in the checkpoint.</s>

<s docid="AP900622-0080" num="27" wdcount="12"> The giant crane then lifted the box-like building high into the air.</s>

<s docid="AP900622-0080" num="28" wdcount="15"> U.S. Army spokesman Sgt. Ed McCarthy said he believes it is destined for a museum.</s>

<s docid="AP900622-0080" num="29" wdcount="27"> Checkpoint Charlie stood just 20 yards from an East German checkpoint and was the only place between the Berlins that could be crossed on foot by non-Germans.</s>

<s docid="AP900622-0080" num="30" wdcount="29"> The ceremony was closed to the public but not to the residents of the buildings that line Friedrich Street, which had been divided by the Berlin Wall since 1961.</s>

<s docid="AP900622-0080" num="31" wdcount="25"> Illa Wobig leaned out her window and watched the ceremony unfold just 20 yards below the fourth-floor apartment where she has lived for 24 years.</s>

<s docid="AP900622-0080" num="32" wdcount="12"> ``I saw eight people shot to death on that street,'' she said.</s>

<s docid="AP900622-0080" num="33" wdcount="13"> ``I saw an East German officer try to go under a guard rail.</s>

<s docid="AP900622-0080" num="34" wdcount="6"> He was shot in the neck''.</s>

<s docid="AP900622-0080" num="35" wdcount="16"> She said she also saw at least 20 successful escapes, by tunnel, car and on foot.</s>

<s docid="AP900622-0080" num="36" wdcount="11"> ``I saw Kennedy, Reagan and Carter give speeches here,'' she said.</s>

<s docid="AP900622-0080" num="37" wdcount="8"> ``I saw a James Bond movie filmed here.</s>

<s docid="AP900622-0080" num="38" wdcount="11"> This is wonderful for history but it is sad for me.</s>

<s docid="AP900622-0080" num="39" wdcount="6"> It was part of my home''.</s>

<s docid="AP900622-0080" num="40" wdcount="30"> East German construction worker Andreas Bratke was working near the wall in January 1986 when he suddenly bolted through the East German checkpoint, down Friedrich Street and through Checkpoint Charlie.</s>

<s docid="AP900622-0080" num="41" wdcount="15"> ``I ran as fast as I could,'' he said from his home in West Berlin.</s>

<s docid="AP900622-0080" num="42" wdcount="9"> ``Checkpoint Charlie is a very important place to me.''</s>
</TEXT>
</DOC>
