<DOC>
<DOCNO>

<s docid="LA062290-0172" num="1" wdcount="1"> LA062290-0172</s>
</DOCNO>
<DOCID>

<s docid="LA062290-0172" num="2" wdcount="1"> 237443</s>
</DOCID>
<DATE>
<P>

<s docid="LA062290-0172" num="3" wdcount="6"> June 22, 1990, Friday, P.M. Final</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA062290-0172" num="4" wdcount="9"> Part P; Page 2; Column 3; Late Final Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA062290-0172" num="5" wdcount="2"> 364 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA062290-0172" num="6" wdcount="8"> CHECKPOINT CHARLIE COMES IN FROM COLD WAR ERA</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA062290-0172" num="7" wdcount="2"> From Reuters</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA062290-0172" num="8" wdcount="2"> WEST BERLIN</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA062290-0172" num="9" wdcount="18"> Checkpoint Charlie, the Berlin Wall border post that symbolized the Cold War, was hoisted into history today .</s>
</P>
<P>

<s docid="LA062290-0172" num="10" wdcount="43"> As a brass band played and foreign ministers of the four World War II allies watched, a crane lifted the prefabricated hut with its American, British and French flags and placed it on a flatbed truck to be taken to a museum .</s>
</P>
<P>

<s docid="LA062290-0172" num="11" wdcount="35"> Checkpoint Charlie went up in 1961 in the middle of the Friedrichstrasse boulevard after Communist East Germany erected the Berlin Wall to choke off a flood of refugees to the enclave of West Berlin .</s>
</P>
<P>

<s docid="LA062290-0172" num="12" wdcount="30"> "The checkpoint symbolized our conviction as allies that Berlin should remain one city and travel within it should be free," British Foreign Secretary Douglas Hurd said in a speech .</s>
</P>
<P>

<s docid="LA062290-0172" num="13" wdcount="19"> "We always hoped that one day Checkpoint Charlie would no longer be needed, and now that day has arrived.</s>

<s docid="LA062290-0172" num="14" wdcount="14"> At long last, we are bringing Charlie in from the cold," he added .</s>
</P>
<P>

<s docid="LA062290-0172" num="15" wdcount="29"> Soviet Foreign Minister Eduard A. Shevardnadze attended the ceremony in a gesture of reconciliation with the Western members of the wartime alliance: Britain, France and the United States .</s>
</P>
<P>

<s docid="LA062290-0172" num="16" wdcount="29"> Shevardnadze, the first Soviet foreign minister to visit West Berlin, noted that the checkpoint was vanishing on the 49th anniversary of the Nazi invasion of the Soviet Union .</s>
</P>
<P>

<s docid="LA062290-0172" num="17" wdcount="27"> "The closing of this checkpoint offers further proof of a turn for the better in the international arena, for overcoming the legacy of confrontation," he said .</s>
</P>
<P>

<s docid="LA062290-0172" num="18" wdcount="17"> Foreign ministers Hans-Dietrich Genscher of West Germany and Markus Meckel of East Germany also attended the ceremony.</s>

<s docid="LA062290-0172" num="19" wdcount="22"> Genscher thanked Moscow for reform policies that had ended "a time of trouble" in Berlin and opened the door to unity .</s>
</P>
<P>

<s docid="LA062290-0172" num="20" wdcount="37"> Hundreds of excited Berliners leaned from balconies and windows today to cheer Charlie's exit, snapping pictures and clapping in rhythm with the band as the crane pried the hut from its moorings and swung it away .</s>
</P>
<P>

<s docid="LA062290-0172" num="21" wdcount="33"> Former West German Chancellor Willy Brandt, who emotionally challenged the building of the wall as mayor of West Berlin in the early 1960s, was in the front row of an invited audience .</s>
</P>
<P>

<s docid="LA062290-0172" num="22" wdcount="16"> Afterward, souvenir hunters ran up and snatched cobblestones that had served as Checkpoint Charlie's foundation .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA062290-0172" num="23" wdcount="25"> Photo, Landmark building at Checkpoint Charlie is removed today by a crane in a ceremony attended by representatives of the West and the East. Reuters</s>
</P>
</GRAPHIC>
<TYPE>
<P>

<s docid="LA062290-0172" num="24" wdcount="1"> Wire</s>
</P>
</TYPE>
</DOC>
