<DOC>
<DOCNO>

<s docid="AP881113-0007" num="1" wdcount="1"> AP881113-0007</s>
</DOCNO>
<FILEID>

<s docid="AP881113-0007" num="2" wdcount="2"> AP-NR-11-13-88 0112EST</s>
</FILEID>
<FIRST>

<s docid="AP881113-0007" num="3" wdcount="5"> u i AM-Mandela 11-13 0235</s>
</FIRST>
<SECOND>

<s docid="AP881113-0007" num="4" wdcount="1"> AM-Mandela,0245</s>
</SECOND>
<HEAD>

<s docid="AP881113-0007" num="5" wdcount="10"> African National Congress Official Says Mandela May Be Released Tuesday</s>
</HEAD>
<DATELINE>

<s docid="AP881113-0007" num="6" wdcount="2"> TORONTO (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP881113-0007" num="7" wdcount="24"> A representative of the African National Congress said Saturday the South African government may release black nationalist leader Nelson Mandela as early as Tuesday.</s>

<s docid="AP881113-0007" num="8" wdcount="38"> ``There are very strong rumors in South Africa today that on Nov. 15 Nelson Mandela will be released,'' said Yusef Saloojee, chief representative in Canada for the ANC, which is fighting to end white-minority rule in South Africa.</s>

<s docid="AP881113-0007" num="9" wdcount="25"> Mandela the 70-year-old leader of the ANC jailed 27 years ago, was sentenced to life in prison for conspiring to overthrow the South African government.</s>

<s docid="AP881113-0007" num="10" wdcount="14"> He was transferred from prison to a hospital in August for treatment of tuberculosis.</s>

<s docid="AP881113-0007" num="11" wdcount="26"> Since then, it has been widely rumored Mandela will be released by Christmas in a move to win strong international support for the South African government.</s>

<s docid="AP881113-0007" num="12" wdcount="29"> ``It will be a victory for the people of South Africa and indeed a victory for the whole of Africa,'' Saloojee told an audience at the University of Toronto.</s>

<s docid="AP881113-0007" num="13" wdcount="30"> A South African government source last week indicated recent rumors of Mandela's impending release were orchestrated by members of the anti-apartheid movement to pressure the government into taking some action.</s>

<s docid="AP881113-0007" num="14" wdcount="24"> And a prominent anti-apatheid activist in South Africa said there has been ``no indication (Mandela) would be released today or in the near future''.</s>

<s docid="AP881113-0007" num="15" wdcount="9"> Apartheid is South Africa's policy of racial separation .</s>
</TEXT>
</DOC>
