<DOC>
<DOCNO>

<s docid="AP880508-0070" num="1" wdcount="1"> AP880508-0070</s>
</DOCNO>
<FILEID>

<s docid="AP880508-0070" num="2" wdcount="2"> AP-NR-05-08-88 1910EDT</s>
</FILEID>
<FIRST>

<s docid="AP880508-0070" num="3" wdcount="5"> r a AM-MandelaDegree 05-08 0374</s>
</FIRST>
<SECOND>

<s docid="AP880508-0070" num="4" wdcount="2"> AM-Mandela Degree,0385</s>
</SECOND>
<HEAD>

<s docid="AP880508-0070" num="5" wdcount="7"> Wrangle Over Honorary Degree For Nelson Mandela</s>
</HEAD>
<DATELINE>

<s docid="AP880508-0070" num="6" wdcount="2"> BOSTON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880508-0070" num="7" wdcount="31"> A 3-year campaign that has succeeded in getting Northeastern University to award an honorary degree to jailed South African nationalist leader Nelson Mandela has raised objections from some faculty and students.</s>

<s docid="AP880508-0070" num="8" wdcount="37"> Northeastern announced plans to award the degree honoring Mandela on May 13, ending a long effort by students seeking to change a university policy barring honorary degrees for anyone who could not be present at the ceremony.</s>

<s docid="AP880508-0070" num="9" wdcount="23"> The degree is to be accepted by South African Archbishop Desmond Tutu, who is scheduled to be in Boston for a benefit dinner.</s>

<s docid="AP880508-0070" num="10" wdcount="14"> Law students last September began a campaign of demonstrations and vigils on the campus.</s>

<s docid="AP880508-0070" num="11" wdcount="17"> They hung a banner from the second floor of the law library that said: ``Honor Nelson Mandela''.</s>

<s docid="AP880508-0070" num="12" wdcount="15"> Before he was imprisoned, said third-year law student Sarah Ottinger, ``Nelson Mandela was an ...</s>

<s docid="AP880508-0070" num="13" wdcount="8"> attorney and an activist who worked against apartheid.</s>

<s docid="AP880508-0070" num="14" wdcount="8"> That's the message we wanted conveyed to students''.</s>

<s docid="AP880508-0070" num="15" wdcount="27"> South Africa's white-minority government says it will free Mandela only if he renounces the use of violence by forces seeking political power for blacks in the country.</s>

<s docid="AP880508-0070" num="16" wdcount="24"> Some faculty members and students, including many blacks, have criticized the administration's plan for the event, saying no effort was made to include them.</s>

<s docid="AP880508-0070" num="17" wdcount="22"> ``I don't even know what office is sponsoring it,'' said Keith Motley, dean and director of the African-American Institute, a student group.</s>

<s docid="AP880508-0070" num="18" wdcount="15"> ``We got a memo from the administration saying they need six ushers, but that's it.</s>

<s docid="AP880508-0070" num="19" wdcount="12"> ``You'd think at least we'd be clued in to what's going on''.</s>

<s docid="AP880508-0070" num="20" wdcount="17"> ``This started out as something noble, something we've tried to have done for three years,'' said Ottinger.</s>

<s docid="AP880508-0070" num="21" wdcount="9"> ``We are very, very sorry it happened this way.</s>

<s docid="AP880508-0070" num="22" wdcount="8"> It wasn't meant to turn out like this''.</s>

<s docid="AP880508-0070" num="23" wdcount="12"> The trustees decided in January that Mandela should get the honorary degree.</s>

<s docid="AP880508-0070" num="24" wdcount="13"> Students set up a committee to contact Mandela's family to get their approval.</s>

<s docid="AP880508-0070" num="25" wdcount="33"> University spokesman Paul Jones said letters were sent to Mandela's wife, Winnie, and his two daughters: Zenani, a student at Boston University, and Makaziwe, a student at the University of Massachusetts at Boston.</s>

<s docid="AP880508-0070" num="26" wdcount="16"> However, Northeastern still has not received approval from the Mandela family, The Boston Globe reported .</s>
</TEXT>
</DOC>
