<DOC>
<DOCNO>

<s docid="AP890717-0149" num="1" wdcount="1"> AP890717-0149</s>
</DOCNO>
<FILEID>

<s docid="AP890717-0149" num="2" wdcount="2"> AP-NR-07-17-89 2000EST</s>
</FILEID>
<FIRST>

<s docid="AP890717-0149" num="3" wdcount="7"> r i AM-Mandela 1stLd-Writethru a0672 07-17 0698</s>
</FIRST>
<SECOND>

<s docid="AP890717-0149" num="4" wdcount="4"> AM-Mandela, 1st Ld-Writethru, a0672,0714</s>
</SECOND>
<HEAD>

<s docid="AP890717-0149" num="5" wdcount="5"> Family Gathering for Prisoner's Birthday</s>
</HEAD>
<HEAD>

<s docid="AP890717-0149" num="6" wdcount="12"> Eds: LEADS throughout to UPDATE with comments from wife and daughter, details.</s>

<s docid="AP890717-0149" num="7" wdcount="3"> No pickup .</s>
</HEAD>
<BYLINE>

<s docid="AP890717-0149" num="8" wdcount="3"> By SAHM VENTER</s>
</BYLINE>
<BYLINE>

<s docid="AP890717-0149" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890717-0149" num="10" wdcount="5"> CAPE TOWN, South Africa (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890717-0149" num="11" wdcount="32"> The largest family group to visit black leader Nelson Mandela since he was jailed 27 years ago gathered in Cape Town for a meeting Tuesday with the prisoner on his 71st birthday.</s>

<s docid="AP890717-0149" num="12" wdcount="24"> His wife, Winnie Mandela, arrived Monday night and indicated she did not expect Mandela, leader of the African National Congress, would be freed soon.</s>

<s docid="AP890717-0149" num="13" wdcount="22"> She said that opinion came from her husband, who she visited last week after Mandela's July 5 meeting with President P.W. Botha.</s>

<s docid="AP890717-0149" num="14" wdcount="11"> That meeting sparked speculation that Mandela would be freed this year.</s>

<s docid="AP890717-0149" num="15" wdcount="18"> He is serving a life term after being convicted of sabotage and plotting to overthrow the white-dominated government.</s>

<s docid="AP890717-0149" num="16" wdcount="27"> Mrs. Mandela, referring to her earlier visit with her husband, told reporters: ``He said from that meeting with P.W. Botha we musn't construe as indicating his release.</s>

<s docid="AP890717-0149" num="17" wdcount="5"> ``His release wasn't even there.</s>

<s docid="AP890717-0149" num="18" wdcount="10"> In fact it was not on the agenda at all''.</s>

<s docid="AP890717-0149" num="19" wdcount="18"> Mrs. Mandela, dressed in black as an expression of mourning, spoke with reporters at the D.F. Malan Airport.</s>

<s docid="AP890717-0149" num="20" wdcount="35"> She said the family normally spent Mandela's birthday at home, fasting and praying, but members would visit him this year on his birthday ``because he has invited us to come and share it with him''.</s>

<s docid="AP890717-0149" num="21" wdcount="29"> The family said 14 relatives, including children from both of Mandela's marriages, would go to Mandela's house at the Victor Verster prison farm in Paarl, north of Cape Town.</s>

<s docid="AP890717-0149" num="22" wdcount="20"> In addition to Mrs. Mandela the group will include three of Mandela's children, one daughter-in-law, eight grandhildren and a great-grandson.</s>

<s docid="AP890717-0149" num="23" wdcount="29"> Mrs. Mandela showed reporters a huge cardboard birthday card in the black, green and yellow colors of the outlawed African National Congress, the largest guerrilla group fighting the government.</s>

<s docid="AP890717-0149" num="24" wdcount="14"> She said the card was made by members of the National Union of Mineworkers.</s>

<s docid="AP890717-0149" num="25" wdcount="21"> ``It is very nice but it is also at the same time very sad,'' she said of the planned birthday celebration.</s>

<s docid="AP890717-0149" num="26" wdcount="7"> ``After all, he is not at home''.</s>

<s docid="AP890717-0149" num="27" wdcount="38"> Mandela was allowed to meet last Friday with five other ANC members convicted with him in 1964 of trying to overthrow the government and still imprisoned in Cape Town, according to Dullah Omar, a family friend and attorney.</s>

<s docid="AP890717-0149" num="28" wdcount="24"> Mandela has been in prison since 1962 when he was sentenced to five years for leaving the country illegally and organizing an illegal strike.</s>

<s docid="AP890717-0149" num="29" wdcount="10"> He was given a life sentence following the 1964 conviction.</s>

<s docid="AP890717-0149" num="30" wdcount="29"> Omar said Tuesday's family gathering ``will be an occasion with a strong theme of sadness because after the reunion they will leave Mr. Mandela to resume his lonely life''.</s>

<s docid="AP890717-0149" num="31" wdcount="19"> Mandela's oldest grandson, Mandla, 14, arrived Monday evening from Swaziland where he is a student at a private school.</s>

<s docid="AP890717-0149" num="32" wdcount="35"> Mandla is the son of Makgatho Mandela, the prisoner's eldest son by his first marriage to Evelyn Ntoko Mase, who lives in the black township of Soweto and was not expected to join the reunion.</s>

<s docid="AP890717-0149" num="33" wdcount="18"> Makgatho Mandela came to Cape Town with his wife, Zondi, his daughter Indaba and 4-year-old Thembela, Mandela's great-grandson.</s>

<s docid="AP890717-0149" num="34" wdcount="7"> Thembela is the grandson of Tembikile Mandela.</s>

<s docid="AP890717-0149" num="35" wdcount="17"> Tembikile, Mandela's son by his marriage to Evelyn Ntoko Mase, died in an automobile accident in 1970.</s>

<s docid="AP890717-0149" num="36" wdcount="21"> Evelyn Ntoko Mase, the cousin of ANC leader Walter Sisulu who has been imprisoned with Mandela, married Nelson Mandela in 1944.</s>

<s docid="AP890717-0149" num="37" wdcount="4"> They had four children.</s>

<s docid="AP890717-0149" num="38" wdcount="30"> One of their daughters, Makaziwe Mandela-Amuah, arrived with her three children from the United States, where she is studying for a doctoral degree in anthropology at Amherst College in Massachusetts.</s>

<s docid="AP890717-0149" num="39" wdcount="35"> She said, ``He (Nelson Mandela) believes that education is the key to all doors and he would like to see all of his children get an education; in fact all of the black children ...</s>

<s docid="AP890717-0149" num="40" wdcount="29"> because you cannot claim to want to rule the country and be the leaders of the future if you have people who are untrained and don't have any skills''.</s>

<s docid="AP890717-0149" num="41" wdcount="23"> Mrs. Mandela-Amuah said of her father's possible release, ``I always firmly believe that you can't predict what the South African government will do.''</s>
</TEXT>
</DOC>
