<DOC>
<DOCNO>

<s docid="AP890118-0100" num="1" wdcount="1"> AP890118-0100</s>
</DOCNO>
<FILEID>

<s docid="AP890118-0100" num="2" wdcount="2"> AP-NR-01-18-89 1050EST</s>
</FILEID>
<FIRST>

<s docid="AP890118-0100" num="3" wdcount="5"> r i PM-Mandela 01-18 0243</s>
</FIRST>
<SECOND>

<s docid="AP890118-0100" num="4" wdcount="1"> PM-Mandela,0251</s>
</SECOND>
<HEAD>

<s docid="AP890118-0100" num="5" wdcount="6"> Imprisoned Colleagues Visited Mandela Before Christmas</s>
</HEAD>
<DATELINE>

<s docid="AP890118-0100" num="6" wdcount="4"> JOHANNESBURG, South Africa (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890118-0100" num="7" wdcount="28"> Four imprisoned African National Congress leaders, convicted in 1964 with Nelson Mandela, were allowed to visit their ANC colleague at his isolated prison house, an activist said today.</s>

<s docid="AP890118-0100" num="8" wdcount="39"> The four men, all held at Pollsmoor Prison in Cape Town, were taken to nearby Victor Verster Prison on Dec. 23 and spent about six hours with Mandela, said Dullah Omar, an activist and family friend of the Mandelas.</s>

<s docid="AP890118-0100" num="9" wdcount="24"> Mandela was moved to the suburban-style home on the prison grounds Dec. 7 after recovering from tuberculosis at a private clinic in Cape Town.</s>

<s docid="AP890118-0100" num="10" wdcount="22"> Mandela's wife, Winnie, said after visiting her husband last month that he is being held ``practically in solitary confinement'' at the house.</s>

<s docid="AP890118-0100" num="11" wdcount="16"> The four men who visited Mandela are Walter Sisulu, Andrew Mhlangeni, Raymond Mhlaba and Ahmed Kathrada.</s>

<s docid="AP890118-0100" num="12" wdcount="16"> The men were convicted along with Mandela and three others at the same trial in 1964.</s>

<s docid="AP890118-0100" num="13" wdcount="21"> All were given life sentences for their activities with the ANC, the main guerrilla group attempting to overthrow the white-led government.</s>

<s docid="AP890118-0100" num="14" wdcount="28"> ``All of them _ except Sisulu _ had not seen Nelson since 1986, and they were very excited at being able to spend time with him,'' Omar said.</s>

<s docid="AP890118-0100" num="15" wdcount="25"> Of the three co-defendants not at the Dec. 23 gathering, two have been released and one remains at the Robben Island Prison near Cape Town.</s>

<s docid="AP890118-0100" num="16" wdcount="11"> The Prisons Service declined to confirm or deny the visit .</s>
</TEXT>
</DOC>
