<DOC>
<DOCNO>

<s docid="AP901006-0037" num="1" wdcount="1"> AP901006-0037</s>
</DOCNO>
<FILEID>

<s docid="AP901006-0037" num="2" wdcount="2"> AP-NY-10-06-90 0721EDT</s>
</FILEID>
<FIRST>

<s docid="AP901006-0037" num="3" wdcount="7"> r i PM-SAfrica-Mandela 2ndLd-Writethru a0452 10-06 0384</s>
</FIRST>
<SECOND>

<s docid="AP901006-0037" num="4" wdcount="4"> PM-SAfrica-Mandela, 2nd Ld-Writethru, a0452,0452</s>
</SECOND>
<HEAD>

<s docid="AP901006-0037" num="5" wdcount="10"> Baby Killed in Attack on Home of Relatives of Mandela</s>
</HEAD>
<NOTE>

<s docid="AP901006-0037" num="6" wdcount="11"> Eds: LEADS thruout with details on attack, background; no pickup .</s>
</NOTE>
<BYLINE>

<s docid="AP901006-0037" num="7" wdcount="3"> By TOM COHEN</s>
</BYLINE>
<BYLINE>

<s docid="AP901006-0037" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP901006-0037" num="9" wdcount="4"> JOHANNESBURG, South Africa (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP901006-0037" num="10" wdcount="27"> Unidentified assailants hurled a grenade and fired shots today at the home of relatives of Nelson Mandela, killing a baby girl and injuring her parents, police said.</s>

<s docid="AP901006-0037" num="11" wdcount="17"> African National Congress officials said the dead child and her parents were distant cousins of Nelson Mandela.</s>

<s docid="AP901006-0037" num="12" wdcount="14"> They denied South African police and press reports that the child was Mandela's great-granddaughter.</s>

<s docid="AP901006-0037" num="13" wdcount="12"> Police said they did not know who was responsible for the attack.</s>

<s docid="AP901006-0037" num="14" wdcount="5"> No group took immediate responsibility.</s>

<s docid="AP901006-0037" num="15" wdcount="22"> Police Lt. Govindesamy Mariemuthoo said the attack occurred before dawn at the home of Monde Mandela in the black township of Soweto.</s>

<s docid="AP901006-0037" num="16" wdcount="17"> The blast badly damaged part of the house, knocking holes in the wall and causing extensive damage.</s>

<s docid="AP901006-0037" num="17" wdcount="13"> The police officer said a baby girl was killed and her parents injured.</s>

<s docid="AP901006-0037" num="18" wdcount="8"> He gave no other detail on the victims.</s>

<s docid="AP901006-0037" num="19" wdcount="14"> He said the room in which the injured couple had been sleeping was destroyed.</s>

<s docid="AP901006-0037" num="20" wdcount="21"> ANC officials said the dead child was the great niece of Mandela's father, making her a distant cousin of Nelson Mandela.</s>

<s docid="AP901006-0037" num="21" wdcount="11"> The dead girl's father, Monde Mandela, runs a small grocery shop.</s>

<s docid="AP901006-0037" num="22" wdcount="13"> The ANC officials said Nelson Mandela was close to the Monde Mandela family.</s>

<s docid="AP901006-0037" num="23" wdcount="23"> An ANC statement said, ``The ANC notes the curious coincidence of an attack on a man bearing the Mandela name at this time''.</s>

<s docid="AP901006-0037" num="24" wdcount="30"> Given the distant connection between Mandela and the family, police said they did not know if the attack was deliberate or just a random attack linked to the general violence.</s>

<s docid="AP901006-0037" num="25" wdcount="14"> Mandela was reportedly attending a political meeting in the eastern province of Natal today.</s>

<s docid="AP901006-0037" num="26" wdcount="22"> Soweto and other black townships around Johannesburg have been hit by black factional fighting that has killed about 800 people since August.</s>

<s docid="AP901006-0037" num="27" wdcount="15"> The fighting has pitted followers of the ANC against Zulus of the conservative Inkatha group.</s>

<s docid="AP901006-0037" num="28" wdcount="24"> Mandela has repeatedly accused security forces of manipulating the violence to derail government efforts to end apartheid and share power with the black majority.</s>

<s docid="AP901006-0037" num="29" wdcount="6"> The police have denied Mandela's charges.</s>

<s docid="AP901006-0037" num="30" wdcount="16"> Mandela was released in February after 27 years in jail for opposing the white minority government.</s>

<s docid="AP901006-0037" num="31" wdcount="20"> He is closely guarded by ANC operatives, and there have been reports of threats on his life in recent months.</s>

<s docid="AP901006-0037" num="32" wdcount="30"> Mandela and other ANC leaders have been negotiating with President F.W. de Klerk to pave the way for full-scale talks on ending apartheid, the South African system of racial separation.</s>

<s docid="AP901006-0037" num="33" wdcount="9"> De Klerk has promised to end white-minority rule .</s>
</TEXT>
</DOC>
