<DOC>
<DOCNO>

<s docid="AP900620-0133" num="1" wdcount="1"> AP900620-0133</s>
</DOCNO>
<FILEID>

<s docid="AP900620-0133" num="2" wdcount="2"> AP-NR-06-20-90 2157EDT</s>
</FILEID>
<FIRST>

<s docid="AP900620-0133" num="3" wdcount="5"> r a AM-Mandela-Officials 06-20 0276</s>
</FIRST>
<SECOND>

<s docid="AP900620-0133" num="4" wdcount="1"> AM-Mandela-Officials,0286</s>
</SECOND>
<HEAD>

<s docid="AP900620-0133" num="5" wdcount="5"> Mandela Arrival Brings Praise, Encouragement</s>
</HEAD>
<HEAD>

<s docid="AP900620-0133" num="6" wdcount="3"> With AM-Mandela, Bjt</s>
</HEAD>
<DATELINE>

<s docid="AP900620-0133" num="7" wdcount="3"> NEW YORK (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900620-0133" num="8" wdcount="21"> The arrival Wednesday of African National Congress leader Nelson Mandela prompted an outpouring of praise and encouragement from politicians and supporters.</s>

<s docid="AP900620-0133" num="9" wdcount="5"> A sampling of their comments:</s>
</TEXT>
<TEXT>

<s docid="AP900620-0133" num="10" wdcount="14"> The Rev. Jesse Jackson: ``The presence of Nelson Mandela generates hope around the world.</s>

<s docid="AP900620-0133" num="11" wdcount="18"> He emerged from the prison unbroken, unbowed and without bitterness, and he continues to struggle for human rights.</s>

<s docid="AP900620-0133" num="12" wdcount="17"> Just as the walls came down in Berlin, they should come down in South Africa as well.''</s>
</TEXT>
<TEXT>

<s docid="AP900620-0133" num="13" wdcount="7"> Mayor David Dinkins: ``Our honored guest ...</s>

<s docid="AP900620-0133" num="14" wdcount="10"> is a George Washington, a Bolivar, a King, a Herzl.</s>

<s docid="AP900620-0133" num="15" wdcount="20"> He is like a modern-day Moses leading the people of South Africa from enslavement at the hands of the pharaohs.</s>

<s docid="AP900620-0133" num="16" wdcount="13"> He and his people have endured their walk through the desert of deprivation.</s>

<s docid="AP900620-0133" num="17" wdcount="6"> And now, his path is clear.</s>

<s docid="AP900620-0133" num="18" wdcount="5"> He will not be deterred.</s>

<s docid="AP900620-0133" num="19" wdcount="14"> He and his people have suffered their way into the leadership of South Africa.''</s>
</TEXT>
<TEXT>

<s docid="AP900620-0133" num="20" wdcount="20"> Former tennis star Arthur Ashe: ``For me, one of my fondest dreams and hopes is to see Nelson Mandela free.</s>

<s docid="AP900620-0133" num="21" wdcount="7"> I never thought I'd see the day.</s>

<s docid="AP900620-0133" num="22" wdcount="12"> I feel humbled by being part of his welcome to our country.</s>

<s docid="AP900620-0133" num="23" wdcount="12"> He will do more good here than he will ever, ever know.''</s>
</TEXT>
<TEXT>

<s docid="AP900620-0133" num="24" wdcount="17"> New York Gov. Mario Cuomo: ``Today we are celebrating Nelson Mandela and honoring his commitment to mankind.</s>

<s docid="AP900620-0133" num="25" wdcount="20"> This government ought to continue to support the needs of South Africa with its speeches, its prayers and its money.''</s>
</TEXT>
<TEXT>

<s docid="AP900620-0133" num="26" wdcount="18"> New Jersey Gov. Jim Florio: ``Today is a restatement of our commitment that all people are created equal.''</s>
</TEXT>
</DOC>
