<DOC>
<DOCNO>

<s docid="AP900609-0040" num="1" wdcount="1"> AP900609-0040</s>
</DOCNO>
<FILEID>

<s docid="AP900609-0040" num="2" wdcount="2"> AP-NR-06-09-90 0733EST</s>
</FILEID>
<FIRST>

<s docid="AP900609-0040" num="3" wdcount="5"> r a PM-MandelaVisit 06-09 0263</s>
</FIRST>
<SECOND>

<s docid="AP900609-0040" num="4" wdcount="2"> PM-Mandela Visit,0271</s>
</SECOND>
<HEAD>

<s docid="AP900609-0040" num="5" wdcount="9"> NYC Mayor Warns Jewish Groups Not To Protest Visit</s>
</HEAD>
<DATELINE>

<s docid="AP900609-0040" num="6" wdcount="3"> NEW YORK (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900609-0040" num="7" wdcount="31"> Mayor David Dinkins warned Jewish groups against protesting the visit of anti-apartheid leader Nelson Mandela to New York City, saying the protests might insult the black community, a newspaper said today.</s>

<s docid="AP900609-0040" num="8" wdcount="23"> The mayor also asked members of the ``organized Jewish community'' to dissuade more radical groups from disrupting the visit, the Daily News said.</s>

<s docid="AP900609-0040" num="9" wdcount="17"> Mandela, leader of the African National Congress, will visit eight cities from June 20 to July 1.</s>

<s docid="AP900609-0040" num="10" wdcount="25"> ``There is a danger of many people who hold Nelson Mandela in very, very high esteem taking great umbrage'' at any public protest, Dinkins said.</s>

<s docid="AP900609-0040" num="11" wdcount="35"> ``I think it's sad and unfortunate and tactically very, very unwise, because this man is an international symbol of freedom and especially so seen by persons of color,'' Dinkins told the newspaper in an interview.</s>

<s docid="AP900609-0040" num="12" wdcount="13"> Leaders of several Jewish-American organizations plan to meet Mandela on Sunday in Geneva.</s>

<s docid="AP900609-0040" num="13" wdcount="13"> The organizations want the South African leader to clarify his position on Israel.</s>

<s docid="AP900609-0040" num="14" wdcount="26"> Mandela has embraced Yasser Arafat, chairman of the Palestine Liberation Organization, in public and has compared the struggle of Palestinians to that of black South Africans.</s>

<s docid="AP900609-0040" num="15" wdcount="31"> Rabbi Abraham Weiss of the Hebrew Institute announced his Coalition of Concern will hold a protest at Mandela's public welcome in New York because of the anti-apartheid leader's ``unbending anti-Israel stance''.</s>

<s docid="AP900609-0040" num="16" wdcount="33"> City councilman Noach Dear and state assemblyman Dov Hikind said if Mandela does not make a strong statement in support of Israel, they would take out ads in newspapers and hold demonstrations .</s>
</TEXT>
</DOC>
