<DOC>
<DOCNO>

<s docid="LA021190-0181" num="1" wdcount="1"> LA021190-0181</s>
</DOCNO>
<DOCID>

<s docid="LA021190-0181" num="2" wdcount="1"> 175004</s>
</DOCID>
<DATE>
<P>

<s docid="LA021190-0181" num="3" wdcount="6"> February 11, 1990, Sunday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA021190-0181" num="4" wdcount="8"> Part A; Page 14; Column 5; Foreign Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA021190-0181" num="5" wdcount="2"> 450 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA021190-0181" num="6" wdcount="3"> ONE MAN'S STRUGGLE</s>
</P>
</HEADLINE>
<TEXT>
<P>

<s docid="LA021190-0181" num="7" wdcount="15"> From behind bars, Nelson Mandela has dominated the fight for black rights in South Africa.</s>

<s docid="LA021190-0181" num="8" wdcount="12"> The following are some of the key events in his life .</s>
</P>
<P>

<s docid="LA021190-0181" num="9" wdcount="1"> 1944</s>
</P>
<P>

<s docid="LA021190-0181" num="10" wdcount="17"> Mandela joins the African National Congress at age 26, later becoming president of the group's Youth League.</s>

<s docid="LA021190-0181" num="11" wdcount="12"> In a short time, the ANC becomes the force behind black protests.</s>

<s docid="LA021190-0181" num="12" wdcount="25"> When the National Party comes to power in 1948, the ANC begins planning a campaign of civil disobedience to fight the party's apartheid policy .</s>
</P>
<P>

<s docid="LA021190-0181" num="13" wdcount="2"> June, 1952</s>
</P>
<P>

<s docid="LA021190-0181" num="14" wdcount="16"> Mandela is named leader of the campaign and breaks curfew as the first act of defiance.</s>

<s docid="LA021190-0181" num="15" wdcount="12"> In December, he is arrested and charged under Suppression of Communism Act.</s>

<s docid="LA021190-0181" num="16" wdcount="15"> He gets a suspended sentence and is barred from attending meetings or leaving Johannesburg .</s>
</P>
<P>

<s docid="LA021190-0181" num="17" wdcount="2"> December, 1956</s>
</P>
<P>

<s docid="LA021190-0181" num="18" wdcount="21"> A campaign of civil disobedience by the ANC results in Mandela being detained along with 155 others and charged with treason.</s>

<s docid="LA021190-0181" num="19" wdcount="10"> The trial, which lasts until 1961, ends in acquittal .</s>
</P>
<P>

<s docid="LA021190-0181" num="20" wdcount="2"> March, 1960</s>
</P>
<P>

<s docid="LA021190-0181" num="21" wdcount="21"> Sixty-nine black protesters are killed by police in Sharpeville; a state of emergency is declared and the ANC is outlawed .</s>
</P>
<P>

<s docid="LA021190-0181" num="22" wdcount="2"> January, 1962</s>
</P>
<P>

<s docid="LA021190-0181" num="23" wdcount="14"> Attends Pan-African Freedom Movement Conference in Ethiopia; travels to London to meet with leftists.</s>

<s docid="LA021190-0181" num="24" wdcount="17"> In August he is charged with incitement and leaving the country illegally; gets five-year jail term .</s>
</P>
<P>

<s docid="LA021190-0181" num="25" wdcount="2"> July, 1963</s>
</P>
<P>

<s docid="LA021190-0181" num="26" wdcount="13"> With Mandela in jail, police raid ANC offices, seizing documents outlining guerrilla campaign.</s>

<s docid="LA021190-0181" num="27" wdcount="14"> Mandela, seven others are charged with sabotage and conspiracy to overthrow the government .</s>
</P>
<P>

<s docid="LA021190-0181" num="28" wdcount="2"> April-June, 1964</s>
</P>
<P>

<s docid="LA021190-0181" num="29" wdcount="11"> Mandela and seven others are sentenced to life in prison .</s>
</P>
<P>

<s docid="LA021190-0181" num="30" wdcount="2"> May, 1984</s>
</P>
<P>

<s docid="LA021190-0181" num="31" wdcount="14"> Mandela is allowed a visit with his wife -- the first since 1962 .</s>
</P>
<P>

<s docid="LA021190-0181" num="32" wdcount="2"> January, 1985</s>
</P>
<P>

<s docid="LA021190-0181" num="33" wdcount="30"> President Pieter W. Botha offers to free Mandela if he renounces violence; Mandela refuses until the government takes steps to dismantle apartheid and grants full political rights to blacks .</s>
</P>
<P>

<s docid="LA021190-0181" num="34" wdcount="2"> July, 1988</s>
</P>
<P>

<s docid="LA021190-0181" num="35" wdcount="3"> Mandela turns 70.</s>

<s docid="LA021190-0181" num="36" wdcount="10"> A rock concert in London is held in his honor.</s>

<s docid="LA021190-0181" num="37" wdcount="8"> But South Africa bans all local celebrations .</s>
</P>
<P>

<s docid="LA021190-0181" num="38" wdcount="2"> August, 1988</s>
</P>
<P>

<s docid="LA021190-0181" num="39" wdcount="9"> Mandela contracts tuberculosis and is transferred to a hospital.</s>

<s docid="LA021190-0181" num="40" wdcount="23"> Three months later he is taken to a prison farm in Paarl and placed in a house usually reserved for prison employees .</s>
</P>
<P>

<s docid="LA021190-0181" num="41" wdcount="2"> July, 1989</s>
</P>
<P>

<s docid="LA021190-0181" num="42" wdcount="10"> Mandela meets with outgoing president Botha at the presidential mansion.</s>

<s docid="LA021190-0181" num="43" wdcount="17"> One week later, Mandela is allowed to make his first officially sanctioned public statement since his conviction.</s>

<s docid="LA021190-0181" num="44" wdcount="13"> His statement makes clear his position has not changed in 28 years .</s>
</P>
<P>

<s docid="LA021190-0181" num="45" wdcount="2"> December, 1989</s>
</P>
<P>

<s docid="LA021190-0181" num="46" wdcount="12"> President Frederik W. de Klerk meets Mandela for the first time .</s>
</P>
<P>

<s docid="LA021190-0181" num="47" wdcount="2"> February, 1990</s>
</P>
<P>

<s docid="LA021190-0181" num="48" wdcount="11"> De Klerk lifts ANC ban and says Mandela will be released.</s>

<s docid="LA021190-0181" num="49" wdcount="15"> On Feb. 11, the nation's best-known black leader becomes a free man at last .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA021190-0181" num="50" wdcount="4"> Photo, Mandela in 1958.</s>

<s docid="LA021190-0181" num="51" wdcount="8"> Photo, A pro-Mandela protest earlier this month .</s>
</P>
</GRAPHIC>
<TYPE>
<P>

<s docid="LA021190-0181" num="52" wdcount="2"> Sidebar; Chronology</s>
</P>
</TYPE>
<SUBJECT>
<P>

<s docid="LA021190-0181" num="53" wdcount="33"> MANDELA, NELSON R; POLITICAL PRISONERS -- SOUTH AFRICA; PRISONER RELEASES; APARTHEID; BLACKS -- SOUTH AFRICA; RACIAL RELATIONS -- SOUTH AFRICA; SOUTH AFRICA -- GOVERNMENT; GOVERNMENT REFORM; AFRICAN NATIONAL CONGRESS; DE KLERK, FREDERIK W</s>
</P>
</SUBJECT>
</DOC>
