<DOC>
<DOCNO>

<s docid="LA021190-0179" num="1" wdcount="1"> LA021190-0179</s>
</DOCNO>
<DOCID>

<s docid="LA021190-0179" num="2" wdcount="1"> 175002</s>
</DOCID>
<DATE>
<P>

<s docid="LA021190-0179" num="3" wdcount="6"> February 11, 1990, Sunday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA021190-0179" num="4" wdcount="8"> Part A; Page 13; Column 1; Foreign Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA021190-0179" num="5" wdcount="2"> 602 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA021190-0179" num="6" wdcount="6"> WORLD LEADERS REJOICE AT MANDELA NEWS</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA021190-0179" num="7" wdcount="3"> From Associated Press</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA021190-0179" num="8" wdcount="1"> LONDON</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA021190-0179" num="9" wdcount="10"> World leaders welcomed South Africa's announcement Saturday of Nelson R.</s>

<s docid="LA021190-0179" num="10" wdcount="21"> Mandela's impending release from prison, and international rejoicing began to build for an event so long awaited by so many .</s>
</P>
<P>

<s docid="LA021190-0179" num="11" wdcount="27"> Britain said it is time to resume contacts with internationally isolated South Africa, but anti-apartheid campaigners warned against any reduction of pressure on the white-led government .</s>
</P>
<P>

<s docid="LA021190-0179" num="12" wdcount="31"> President Bush praised South African President Frederik W. de Klerk for "bold and imaginative leadership," and the Canadian government expressed delight at the announcement that Mandela would be released today .</s>
</P>
<P>

<s docid="LA021190-0179" num="13" wdcount="34"> In Lusaka, Zambian President Kenneth D. Kaunda, whose country has been a refuge for the exiled leadership of Mandela's African National Congress, said his first reaction was to kneel down and thank God .</s>
</P>
<P>

<s docid="LA021190-0179" num="14" wdcount="26"> "Really, we must believe in the leadership of the people of South Africa to put their heads together and build on these developments," Kaunda said .</s>
</P>
<P>

<s docid="LA021190-0179" num="15" wdcount="36"> Hours after the announcement of Mandela's release date, the ANC's leadership announced from its headquarters in Lusaka, Zambia: "We welcome Nelson Mandela back from all those years of imprisonment into our midst with great joy" .</s>
</P>
<P>

<s docid="LA021190-0179" num="16" wdcount="36"> "Ireland rejoices that Nelson Mandela is free at last," said Charles Haughey, Irish prime minister and current president of the European Community, which has been using economic sanctions to pressure Pretoria to give up apartheid .</s>
</P>
<P>

<s docid="LA021190-0179" num="17" wdcount="20"> "By his indomitable courage he has demonstrated once again that the human spirit can never be vanquished," Haughey said .</s>
</P>
<P>

<s docid="LA021190-0179" num="18" wdcount="38"> Egyptian President Hosni Mubarak, current chairman of the Organization of African Unity, sent Mandela a message of congratulation, praising the "sacrifices of the great people of South Africa" and assuring him of Egyptian solidarity with his cause .</s>
</P>
<P>

<s docid="LA021190-0179" num="19" wdcount="35"> In the Soviet Union, Moscow Radio broadcast news of the announcement, then added: "Nelson Mandela has become the world's most famous political prisoner, put in jail for the struggle against apartheid in South Africa" .</s>
</P>
<P>

<s docid="LA021190-0179" num="20" wdcount="11"> Amsterdam's central Leidseplein square was temporarily rechristened Nelson Mandela Square .</s>
</P>
<P>

<s docid="LA021190-0179" num="21" wdcount="26"> In London, a jubilant crowd of about 120, some waving pictures of Mandela, celebrated in the pouring rain outside South Africa House in Trafalgar Square .</s>
</P>
<P>

<s docid="LA021190-0179" num="22" wdcount="31"> In a statement released by her 10 Downing St. office, Prime Minister Margaret Thatcher said, "We believe that the steps President de Klerk has taken merit a positive, practical response" .</s>
</P>
<P>

<s docid="LA021190-0179" num="23" wdcount="41"> "We believe it no longer makes sense to discourage new investment in South Africa -- a restraint which in our case in any event has been voluntary -- and we shall be discussing this with our EC partners," she said .</s>
</P>
<P>

<s docid="LA021190-0179" num="24" wdcount="23"> In 1986, the European Community banned imports of South African iron, steel and Kruggerand gold coins, and barred new investment in the country.</s>

<s docid="LA021190-0179" num="25" wdcount="9"> It had already frozen scientific and cultural relations .</s>
</P>
<P>

<s docid="LA021190-0179" num="26" wdcount="31"> Britain regards the iron, steel and coin embargoes as mandatory, but not the investment ban, and has already announced that it is no longer observing the scientific and cultural embargo .</s>
</P>
<P>

<s docid="LA021190-0179" num="27" wdcount="35"> In London, Bob Hughes, chairman of the Anti-Apartheid Movement, said he was delighted at the news, which he called "a tremendous victory for the people of South Africa and for the international sanctions campaign" .</s>
</P>
<P>

<s docid="LA021190-0179" num="28" wdcount="34"> Commonwealth Secretary General Shridath Ramphal said Mandela's safety must be guaranteed by the South African government and that until change there becomes irreversible, the Commonwealth will sustain its pressure for the end of apartheid.</s>

<s docid="LA021190-0179" num="29" wdcount="16"> "It is not yet time to demobilize the international support for apartheid's victims," he said .</s>
</P>
</TEXT>
<TYPE>
<P>

<s docid="LA021190-0179" num="30" wdcount="1"> Wire</s>
</P>
</TYPE>
<SUBJECT>
<P>

<s docid="LA021190-0179" num="31" wdcount="55"> GOVERNMENT OFFICIALS; LEADERSHIP; CELEBRATIONS; ENGLAND -- FOREIGN RELATIONS -- SOUTH AFRICA; EGYPT -- FOREIGN RELATIONS -- SOUTH AFRICA; SOUTH AFRICA -- FOREIGN RELATIONS -- USSR; SOUTH AFRICA -- FOREIGN RELATIONS -- ZAMBIA; MANDELA, NELSON R; POLITICAL PRISONERS -- SOUTH AFRICA; PRISONER RELEASES; APARTHEID; RACIAL RELATIONS -- SOUTH AFRICA; SOUTH AFRICA -- GOVERNMENT; AFRICAN NATIONAL CONGRESS</s>
</P>
</SUBJECT>
</DOC>
