<DOC>
<DOCNO>

<s docid="SJMN91-06145218" num="1" wdcount="1"> SJMN91-06145218</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06145218" num="2" wdcount="1"> 06145218</s>
</ACCESS>
<CAPTION>

<s docid="SJMN91-06145218" num="3" wdcount="3"> Photo; PHOTO: Mandela</s>
</CAPTION>
<DESCRIPT>

<s docid="SJMN91-06145218" num="4" wdcount="4"> SOUTH-AFRICA; WEAPON; BAN; OPINION</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06145218" num="5" wdcount="15"> THE PHOTOGRAPHER caught Winnie Mandela as she left the court after her conviction for kidnapping.</s>

<s docid="SJMN91-06145218" num="6" wdcount="13"> She was smiling exuberantly, as if she had just won a great victory.</s>

<s docid="SJMN91-06145218" num="7" wdcount="11"> Behind her was Nelson Mandela, eyes downcast, looking stricken and exhausted.</s>

<s docid="SJMN91-06145218" num="8" wdcount="19"> That remarkable, terrible picture spoke volumes about the drama of South Africa today, the human factors and the politics.</s>

<s docid="SJMN91-06145218" num="9" wdcount="16"> Most of all, it reminded us of the unimaginable burdens borne by one 72-year-old man .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06145218" num="10" wdcount="1"> Editorial</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06145218" num="11" wdcount="7"> S. AFRICA'S NEXT STEP: BAN WEAPONS, NEGOTIATE</s>
</HEADLINE>
<MEMO>

<s docid="SJMN91-06145218" num="12" wdcount="10"> Commentary Anthony Lewis is a New York Times columnist .</s>
</MEMO>
<TEXT>

<s docid="SJMN91-06145218" num="13" wdcount="28"> In the 15 months since he walked free from prison, Nelson Mandela has played the chief role in talks with President F.W. de Klerk and the white government.</s>

<s docid="SJMN91-06145218" num="14" wdcount="15"> He has presided over an African National Congress divided and not yet organized for politics.</s>

<s docid="SJMN91-06145218" num="15" wdcount="17"> He has spent his moral capital trying, unsuccessfully, to end the murderous conflict between black political factions.</s>

<s docid="SJMN91-06145218" num="16" wdcount="13"> Now Mandela is confronted with his wife's conviction for a brutal criminal offense.</s>

<s docid="SJMN91-06145218" num="17" wdcount="6"> He has loyally defended her innocence.</s>

<s docid="SJMN91-06145218" num="18" wdcount="10"> He has seemed to hear no voice to the contrary.</s>

<s docid="SJMN91-06145218" num="19" wdcount="5"> But events have caught up.</s>

<s docid="SJMN91-06145218" num="20" wdcount="26"> The radicals in the ANC may well use the trial and conviction of Mrs. Mandela to arouse members against Nelson Mandela's policy of peace and negotiation.</s>

<s docid="SJMN91-06145218" num="21" wdcount="30"> There are rumors that at a national conference next month the radicals will try to move such older leaders as Mandela and Walter Sisulu aside to a nominal senior role.</s>

<s docid="SJMN91-06145218" num="22" wdcount="25"> It is a gloomy picture: an elderly man bearing the hopes of peace in South Africa beset by problems, personal trauma on top of political.</s>

<s docid="SJMN91-06145218" num="23" wdcount="21"> But I think it would be wrong to conclude that the South African drama is necessarily heading toward a tragic end.</s>

<s docid="SJMN91-06145218" num="24" wdcount="27"> One reason for a degree of optimism is the way South Africans on all sides, most of them, have dealt with Winnie Mandela's trial: calmly and fairly.</s>

<s docid="SJMN91-06145218" num="25" wdcount="12"> During the years of white supremacy the law has been viciously misused.</s>

<s docid="SJMN91-06145218" num="26" wdcount="17"> But from all one can tell, this trial was handled professionally by the judge, Justice Michael Stegmann.</s>

<s docid="SJMN91-06145218" num="27" wdcount="12"> The reaction to the verdict and six-year prison sentence was also mild.</s>

<s docid="SJMN91-06145218" num="28" wdcount="11"> Surprisingly few supporters gathered outside the court to cheer Mrs. Mandela.</s>

<s docid="SJMN91-06145218" num="29" wdcount="18"> The ANC issued a detached statement saying that the last word had not been spoken in the case.</s>

<s docid="SJMN91-06145218" num="30" wdcount="44"> Archbishop Desmond Tutu said "the movement is larger than any individual."; A more fundamental reason for hope is that F.W. de Klerk and Nelson Mandela -- and those for whom they speak -- have a common interest in creating a new, non-racial South Africa.</s>

<s docid="SJMN91-06145218" num="31" wdcount="4"> They need each other.</s>

<s docid="SJMN91-06145218" num="32" wdcount="15"> Without their agreement, there can be no solution, no outcome that leaves a viable country.</s>

<s docid="SJMN91-06145218" num="33" wdcount="6"> The next step is formal negotiations.</s>

<s docid="SJMN91-06145218" num="34" wdcount="35"> They can come only when the government takes further steps to meet the reasonable ANC demand for action against violence -- in particular, a ban on the carrying of so-called "cultural" weapons such as spears.</s>

<s docid="SJMN91-06145218" num="35" wdcount="16"> How can the government look away when 1,000 Zulus carrying spears and machetes slaughter township residents?</s>

<s docid="SJMN91-06145218" num="36" wdcount="6"> The time factor is crucial now.</s>

<s docid="SJMN91-06145218" num="37" wdcount="22"> Negotiations must start soon if the moderate center of the public, black and white, is to retain hope for a peaceful solution.</s>

<s docid="SJMN91-06145218" num="38" wdcount="8"> World and time press on Nelson Mandela .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06145218" num="39" wdcount="2"> ANTHONY LEWIS</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06145218" num="40" wdcount="1"> USA</s>
</COUNTRY>
<EDITION>

<s docid="SJMN91-06145218" num="41" wdcount="2"> Morning Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06145218" num="42" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06145218" num="43" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06145218" num="44" wdcount="1"> 910524</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06145218" num="45" wdcount="1"> Friday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06145218" num="46" wdcount="1"> May</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06145218" num="47" wdcount="1"> 7B</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06145218" num="48" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06145218" num="49" wdcount="1"> WEST</s>
</REGION>
<FEATURE>

<s docid="SJMN91-06145218" num="50" wdcount="1"> PHOTO</s>
</FEATURE>
<STATE>

<s docid="SJMN91-06145218" num="51" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06145218" num="52" wdcount="1"> 534</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06145218" num="53" wdcount="5"> Friday May 24, 1991 00145218,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06145218" num="54" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06145218" num="55" wdcount="1"> 1</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06145218" num="56" wdcount="1"> ENG</s>
</LANGUAGE>
</DOC>
