<DOC>
<DOCNO>

<s docid="AP880228-0013" num="1" wdcount="1"> AP880228-0013</s>
</DOCNO>
<FILEID>

<s docid="AP880228-0013" num="2" wdcount="2"> AP-NR-02-28-88 0009EST</s>
</FILEID>
<FIRST>

<s docid="AP880228-0013" num="3" wdcount="5"> u i AM-OlympicsNewspage 02-28 0387</s>
</FIRST>
<SECOND>

<s docid="AP880228-0013" num="4" wdcount="2"> AM-Olympics Newspage,0398</s>
</SECOND>
<HEAD>

<s docid="AP880228-0013" num="5" wdcount="8"> Debi Thomas A Disappointing Third In Figure Skating</s>
</HEAD>
<DATELINE>

<s docid="AP880228-0013" num="6" wdcount="3"> CALGARY, Alberta (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880228-0013" num="7" wdcount="35"> Debi Thomas' dream of Olympic gold turned into disappointment Saturday as East Germany's Katarina Witt won her second straight Olympic championship and Canadian Elizabeth Manley took home the silver before a crowd of cheering countrymen.</s>

<s docid="AP880228-0013" num="8" wdcount="2"> ``It's over.</s>

<s docid="AP880228-0013" num="9" wdcount="14"> Back to school,'' said Thomas, who won the bronze medal despite three faulty landings.</s>

<s docid="AP880228-0013" num="10" wdcount="7"> ``I'm not going to make any excuses.</s>

<s docid="AP880228-0013" num="11" wdcount="7"> I was really skating well this week.</s>

<s docid="AP880228-0013" num="12" wdcount="7"> It wasn't supposed to happen, I guess.</s>

<s docid="AP880228-0013" num="13" wdcount="3"> But I tried''.</s>

<s docid="AP880228-0013" num="14" wdcount="30"> While the top two skaters in the world staged a shootout to music from Bizet's ``Carmen,'' Manley was so sensational in the freestyle that she finished first with seven judges.</s>

<s docid="AP880228-0013" num="15" wdcount="27"> Combined with a fourth in the compulsory figures and a third-place finish in the short program earlier in the week, the performance put Manley in second place.</s>

<s docid="AP880228-0013" num="16" wdcount="24"> Witt, a three-time world champion from East Germany, became the first repeat singles champion since Dick Button took Olympic gold in 1948 and '52.</s>

<s docid="AP880228-0013" num="17" wdcount="19"> Sonja Henie of Norway was the only woman to do it before Witt, winning in 1928, 1932 and 1936.</s>

<s docid="AP880228-0013" num="18" wdcount="30"> Thomas, of San Jose, Calif., the first black to win a U.S. figure skating crown and the 1986 world champion, skated poorly Saturday after doing well earlier in the Games.</s>

<s docid="AP880228-0013" num="19" wdcount="12"> By contrast, Manley had the sellout crowd at the Olympic Saddledome enraptured.</s>

<s docid="AP880228-0013" num="20" wdcount="16"> They cheered, hooted and stamped their feet when she finished hitting every element of her program.</s>

<s docid="AP880228-0013" num="21" wdcount="7"> Jill Trenary of Minnetonka, Minn., finished fourth.</s>

<s docid="AP880228-0013" num="22" wdcount="15"> She was fifth heading into the long program, worth 50 percent of the overall score.</s>

<s docid="AP880228-0013" num="23" wdcount="13"> Thomas' bronze was the third figure skating medal here for the United States.</s>

<s docid="AP880228-0013" num="24" wdcount="18"> Brian Boitano won the men's crown, and a bronze in pairs went to Jill Watson and Peter Oppegard.</s>

<s docid="AP880228-0013" num="25" wdcount="21"> In addition to the three figure skating medals, the U.S. team had three speed-skating medals: one each gold, silver and bronze.</s>

<s docid="AP880228-0013" num="26" wdcount="22"> Speed skater Bonnie Blair, America's only double medalist, tried again Saturday in the 1,500 meters but finished fourth, well off the pace.</s>

<s docid="AP880228-0013" num="27" wdcount="14"> She won the gold in the 500 and the bronze in the 1,000 meters.</s>

<s docid="AP880228-0013" num="28" wdcount="29"> As the Olympics winded up its next-to-last day, the Soviet Union had 27 medals, including 11 golds, while East Germany in second place had 22, including nine golds .</s>
</TEXT>
</DOC>
