<DOC>
<DOCNO>

<s docid="AP881003-0066" num="1" wdcount="1"> AP881003-0066</s>
</DOCNO>
<FILEID>

<s docid="AP881003-0066" num="2" wdcount="2"> AP-NR-10-03-88 0522EDT</s>
</FILEID>
<FIRST>

<s docid="AP881003-0066" num="3" wdcount="6"> u i PM-OlympicsWrap Bjt 10-03 0722</s>
</FIRST>
<SECOND>

<s docid="AP881003-0066" num="4" wdcount="3"> PM-Olympics Wrap, Bjt,0740</s>
</SECOND>
<HEAD>

<s docid="AP881003-0066" num="5" wdcount="12"> Fans, Athletes Take Away Memories, Medals As Summer Olympics End In Seoul</s>
</HEAD>
<NOTE>

<s docid="AP881003-0066" num="6" wdcount="7"> Eds: RETRANSMITTING a0501 to restore logo .</s>
</NOTE>
<BYLINE>

<s docid="AP881003-0066" num="7" wdcount="3"> By STEVE WILSTEIN</s>
</BYLINE>
<BYLINE>

<s docid="AP881003-0066" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP881003-0066" num="9" wdcount="4"> SEOUL, South Korea (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP881003-0066" num="10" wdcount="34"> The Summer Olympics will be remembered for moments of glory like that enjoyed by U.S. diver Greg Louganis and the startling moment of disgrace when the gold was stripped from Canadian sprinter Ben Johnson.</s>

<s docid="AP881003-0066" num="11" wdcount="27"> The Soviet Union won the first U.S.-Soviet Olympic medal contest since 1976, getting 55 gold medals to 37 for East Germany and 36 for the United States.</s>

<s docid="AP881003-0066" num="12" wdcount="12"> Host South Korea rose to fourth in the world with 12 golds.</s>

<s docid="AP881003-0066" num="13" wdcount="32"> The fear of terrorism and massive civil unrest prompted extraordinary security, but neither bogey materialized as nearly 10,000 athletes from 160 countries tested their mettle in 16 days of competition ended Sunday.</s>

<s docid="AP881003-0066" num="14" wdcount="46"> As always, there were shining moments of glory, from an opening ceremony with exotic dancers and parachutists to a closing with hugs and tears, fireworks and dances, and the mascots of Seoul and Barcelona, the site of the 1992 Games, floating together into the starry night.</s>

<s docid="AP881003-0066" num="15" wdcount="15"> Louganis claimed his second pair of gold medals after hitting his head on a springboard.</s>

<s docid="AP881003-0066" num="16" wdcount="25"> He said he talked with his coach about quitting the Olympics after hitting the board and opening a cut that needed five stitches to close.</s>

<s docid="AP881003-0066" num="17" wdcount="16"> ``We walked and discussed all the things we had gone through to get there,'' he said.</s>

<s docid="AP881003-0066" num="18" wdcount="10"> ``I decided to stay in, and I'm glad I did''.</s>

<s docid="AP881003-0066" num="19" wdcount="13"> Louganis said Sunday he is retiring from diving to begin an acting career.</s>

<s docid="AP881003-0066" num="20" wdcount="42"> What had been the highest moment of the Games _ Ben Johnson rocketing to victory over U.S. great Carl Lewis in a 100-meter dash world record _ led to the deepest pain when the Canadian was caught cheating with muscle-building anabolic steroids.</s>

<s docid="AP881003-0066" num="21" wdcount="34"> Twenty years from now, when most of the records set in Seoul are broken, the impact of Johnson's disgrace will still be felt if athletes and trainers heed the events here and end doping.</s>

<s docid="AP881003-0066" num="22" wdcount="29"> ``There have been high points and some low points, and the most important low point was Ben Johnson,'' Juan Antonio Samaranch, president of the International Olympic Committee, said today.</s>

<s docid="AP881003-0066" num="23" wdcount="5"> ``That was indeed a blow''.</s>

<s docid="AP881003-0066" num="24" wdcount="27"> But catching Johnson and expelling him and nine other athletes with positive drug tests was an indication that ``we have won the battle against doping,'' Samaranch said.</s>

<s docid="AP881003-0066" num="25" wdcount="27"> Sports officials from the United States and the Soviet Union on Sunday announced Sunday they would join forces to work towards the elimination of drugs from sport.</s>

<s docid="AP881003-0066" num="26" wdcount="31"> A statement issued by the U.S. and Soviet Olympic committees said the groups would investigate using the exchange of testing teams, lab results and technical data; education programs; and uniform penalties.</s>

<s docid="AP881003-0066" num="27" wdcount="18"> For the United States, a serious problem at the Seoul Games was a rising tide of anti-American sentiment.</s>

<s docid="AP881003-0066" num="28" wdcount="35"> It was exacerbated by NBC's coverage, which the Koreans saw as anti-Korean and insensitive to local culture; the arrest of several American athletes; and the perceived rudeness of the U.S. team at the opening ceremony.</s>

<s docid="AP881003-0066" num="29" wdcount="26"> The Soviets, meanwhile, cultivated friendship by bringing in the Bolshoi Ballet, the Moscow Philharmonic, films, a photo exhibit and copies of the Communist Party newspaper Pravda.</s>

<s docid="AP881003-0066" num="30" wdcount="30"> The announcement of an unprecedented sports exchange program between South Korea and the Soviet Union and the arrival of the first Soviet diplomats since World War II also warmed relations.</s>

<s docid="AP881003-0066" num="31" wdcount="21"> Soviet athletes, as they did in Calgary, Canada, during the Winter Games, made a special effort to meet with local people.</s>

<s docid="AP881003-0066" num="32" wdcount="6"> American athletes tended to isolate themselves.</s>

<s docid="AP881003-0066" num="33" wdcount="34"> All those differences became apparent at the sporting events, where Koreans often cheered louder for the Soviets or East Germans than they did for Americans, despite a close 40-year relationship with the United States.</s>

<s docid="AP881003-0066" num="34" wdcount="33"> Still, there were Louganis and other Americans to unabashedly cheer for _ like sisters-in-law Florence Griffith Joyner and Jackie Joyner-Kersee, who led an assault on the track and field record books, and Louganis.</s>

<s docid="AP881003-0066" num="35" wdcount="19"> Griffith Joyner won golds in the 100, the 200 and the 400-meter relay, and silver in the 1,600-meter relay.</s>

<s docid="AP881003-0066" num="36" wdcount="15"> She set a world record in the 200 and an Olympic record in the 100.</s>

<s docid="AP881003-0066" num="37" wdcount="27"> Joyner-Kersee won two golds, taking the heptathlon with a world record 7,291 points and the long jump with an Olympic mark of 24 feet, 3 inches .</s>
</TEXT>
</DOC>
