<DOC>
<DOCNO>

<s docid="AP880929-0042" num="1" wdcount="1"> AP880929-0042</s>
</DOCNO>
<FILEID>

<s docid="AP880929-0042" num="2" wdcount="2"> AP-NR-09-29-88 0336EDT</s>
</FILEID>
<FIRST>

<s docid="AP880929-0042" num="3" wdcount="5"> u i BC-Olympics-Newspage 09-29 0241</s>
</FIRST>
<SECOND>

<s docid="AP880929-0042" num="4" wdcount="1"> BC-Olympics-Newspage,0248</s>
</SECOND>
<HEAD>

<s docid="AP880929-0042" num="5" wdcount="6"> Flo Jo Sets Two World Records</s>
</HEAD>
<NOTE>

<s docid="AP880929-0042" num="6" wdcount="6"> Eds: No PMs separate planned .</s>
</NOTE>
<HEAD>

<s docid="AP880929-0042" num="7" wdcount="2"> LaserPhoto OLY178</s>
</HEAD>
<DATELINE>

<s docid="AP880929-0042" num="8" wdcount="4"> SEOUL, South Korea (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880929-0042" num="9" wdcount="20"> Florence Griffith Joyner twice smashed a world record Thursday as she blazed to a gold medal in the 200-meter sprint.</s>

<s docid="AP880929-0042" num="10" wdcount="22"> She also stayed on target to become the second woman to win four track and field gold medals in a single Olympics.</s>

<s docid="AP880929-0042" num="11" wdcount="25"> Griffith Joyner dashed to her second gold in 21.34 seconds, shattering the world mark she had set just 90 minutes earlier in her semifinal heat.</s>

<s docid="AP880929-0042" num="12" wdcount="26"> In that race, she ran 21.56, eclipsing the 9-year-old mark of 21.71 set in 1979 by Marita Koch of East Germany and equaled three times since.</s>

<s docid="AP880929-0042" num="13" wdcount="14"> In her 200 quarterfinal heat Wednesday, Griffith Joyner ran an Olympic record 21.76 seconds.</s>

<s docid="AP880929-0042" num="14" wdcount="28"> Griffith Joyner, who set an Olympic record Sunday in winning the 100 meters, had a big lead Thursday as she turned the curve for the final 100 meters.</s>

<s docid="AP880929-0042" num="15" wdcount="5"> She glided to the wire.</s>

<s docid="AP880929-0042" num="16" wdcount="9"> ``I know I can run much faster,'' she said.</s>

<s docid="AP880929-0042" num="17" wdcount="4"> ``I felt very relaxed.</s>

<s docid="AP880929-0042" num="18" wdcount="3"> That's the key''.</s>

<s docid="AP880929-0042" num="19" wdcount="21"> Griffith Joyner, 28, is scheduled to run in the 400-meter relay Saturday and may compete in the 1,600-meter relay that day.</s>

<s docid="AP880929-0042" num="20" wdcount="44"> Noted for her long, painted fingernails and racy, colorful bodysuits, Griffith Joyner of Los Angeles has a chance to match the 1984 quadruple gold medal performance of U.S. sprinter and long jumper Carl Lewis, and by Fanny Blankers-Koen of the Netherlands in 1948 .</s>
</TEXT>
</DOC>
