<DOC>
<DOCNO>

<s docid="AP881002-0048" num="1" wdcount="1"> AP881002-0048</s>
</DOCNO>
<FILEID>

<s docid="AP881002-0048" num="2" wdcount="2"> AP-NR-10-02-88 1459EDT</s>
</FILEID>
<FIRST>

<s docid="AP881002-0048" num="3" wdcount="6"> u a AM-OlympicsWrap Bjt 10-02 0815</s>
</FIRST>
<SECOND>

<s docid="AP881002-0048" num="4" wdcount="3"> AM-Olympics Wrap, Bjt,0839</s>
</SECOND>
<HEAD>

<s docid="AP881002-0048" num="5" wdcount="10"> Olympics Conclude Peacefully, With Many Heroes And A Few Sorrows</s>
</HEAD>
<HEAD>

<s docid="AP881002-0048" num="6" wdcount="8"> LaserPhotos OLY152, 154, 179, 180, 181, LaserColor OLY162</s>
</HEAD>
<BYLINE>

<s docid="AP881002-0048" num="7" wdcount="4"> By The Associated Press</s>
</BYLINE>
<DATELINE>

<s docid="AP881002-0048" num="8" wdcount="4"> SEOUL, South Korea (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP881002-0048" num="9" wdcount="28"> The 1988 Summer Olympics, kept free of terrorism but tainted by drug scandals, closed Sunday with the pealing of a medieval bell to symbolize the sorrow of parting.</s>

<s docid="AP881002-0048" num="10" wdcount="7"> The United States finished third in medals.</s>

<s docid="AP881002-0048" num="11" wdcount="36"> The 1,000-year-old, 72-ton Emille Bell, which according to Korean legend has the saddest tone of any in the world, tolled farewell to the more than 9,000 athletes from 160 nations who participated in the 24th Olympiad.</s>

<s docid="AP881002-0048" num="12" wdcount="22"> The 16-day event, conducted under extraordinary security, wrapped up with the Soviet Union winning the lion's share of the 237 medals events.</s>

<s docid="AP881002-0048" num="13" wdcount="20"> The Soviets took home 132 medals, including 55 gold, the most ever in a Summer Olympics without a major-power boycott.</s>

<s docid="AP881002-0048" num="14" wdcount="17"> East Germany had 102 medals and 37 gold, and the United States 94 medals and 36 gold.</s>

<s docid="AP881002-0048" num="15" wdcount="38"> Many felt that the United States was robbed of a second-place tie for golds when judges awarded a bout to a South Korean boxer over American Roy Jones in the 156-pound event on the final day of competition.</s>

<s docid="AP881002-0048" num="16" wdcount="37"> Because of boycotts in 1980 and 1984, the Games were the first meeting between the Soviet Union and the United States since 1976 in Montreal, and matchups between the two nations provided some of the Games' highlights.</s>

<s docid="AP881002-0048" num="17" wdcount="24"> The U.S. men's volleyball team beat the Soviets to defend its 1984 Olympic championship, providing consolation for America's upset in the men's basketball quarterfinals.</s>

<s docid="AP881002-0048" num="18" wdcount="12"> America also defeated the Soviets in women's basketball and men's water polo.</s>

<s docid="AP881002-0048" num="19" wdcount="14"> At least 1 billion people watched the Olympics via a 115-nation, worldwide TV hookup.</s>

<s docid="AP881002-0048" num="20" wdcount="22"> The Seoul Games had the greatest number of athletes (9,633), the most countries, the most gold medals and the most venues (34).</s>

<s docid="AP881002-0048" num="21" wdcount="22"> Communist North Korea, which demanded a role in the Games, boycotted them, but the only sports power to follow suit was Cuba.</s>

<s docid="AP881002-0048" num="22" wdcount="25"> Among the highlights: _Greg Louganis won the Olympic Spirit Award as top American athlete Sunday for winning gold medals in platform and 3-meter springboard diving.</s>

<s docid="AP881002-0048" num="23" wdcount="17"> He accomplished the same feat in 1980 and became the first man to sweep the events twice.</s>

<s docid="AP881002-0048" num="24" wdcount="29"> The 28-year-old Louganis, who hit his head on the board in the preliminaries and received five stitches, announced his retirement from diving and said he wanted to pursue acting.</s>

<s docid="AP881002-0048" num="25" wdcount="19"> _Sisters-in-law Florence Griffith Joyner and Jackie Joyner-Kersee led an American assault on the record books in track and field.</s>

<s docid="AP881002-0048" num="26" wdcount="19"> Griffith Joyner won golds in the 100, the 200 and the 400-meter relay, and silver in the 1,600-meter relay.</s>

<s docid="AP881002-0048" num="27" wdcount="15"> She set a world record in the 200 and an Olympic record in the 100.</s>

<s docid="AP881002-0048" num="28" wdcount="26"> Joyner-Kersee won two golds, taking the heptathlon with a world record 7,291 points and the long jump with an Olympic mark of 24 feet, 3 inches.</s>

<s docid="AP881002-0048" num="29" wdcount="10"> _Kristin Otto of East Germany won six golds in swimming.</s>

<s docid="AP881002-0048" num="30" wdcount="22"> American swimmer Matt Biondi won seven medals, five gold, while Janet Evans earned three golds in the pool for the United States.</s>

<s docid="AP881002-0048" num="31" wdcount="15"> _Daniela Silivas of Romania dominated women's gymnastics, winning three golds, two silvers and a bronze.</s>

<s docid="AP881002-0048" num="32" wdcount="35"> _West German Steffi Graf completed tennis's first Golden Slam, winning the gold medal as well as all four Grand Slam tournaments _ Wimbledon and the U.S., French and Australian Opens _ in a calendar year.</s>

<s docid="AP881002-0048" num="33" wdcount="6"> There were low moments as well.</s>

<s docid="AP881002-0048" num="34" wdcount="40"> Canadian sprinter Ben Johnson, the most prominent of 10 athletes who tested positive for drugs, was stripped of his gold medal in the 100 meters and title of world's fastest man, and flew home in disgrace, his career in jeopardy.</s>

<s docid="AP881002-0048" num="35" wdcount="7"> He was accused of using muscle-building steroids.</s>

<s docid="AP881002-0048" num="36" wdcount="35"> Four other medals _ two Bulgarian weightlifting golds, a Hungarian weightlifing silver and a British judo bronze _ also were stripped for drugs, and five non-medalists tested positive for substances ranging from caffeine to diuretics.</s>

<s docid="AP881002-0048" num="37" wdcount="29"> Early in the Games, five people connected to the Korean boxing team were suspended for attacking a New Zealand referee after a Korean lost a decision to a Bulgarian.</s>

<s docid="AP881002-0048" num="38" wdcount="14"> Another Korean boxer staged a 67-minute sit-in in the ring to protest his loss.</s>

<s docid="AP881002-0048" num="39" wdcount="27"> Anthony Hembrick, a U.S. boxer expected to win a gold, never got to fight; his coach misread the schedule and he missed the bus to the arena.</s>

<s docid="AP881002-0048" num="40" wdcount="22"> Two gold medal-winning U.S. swimmers were arrested for carrying a stone lion's head out of a hotel bar, but charges were dropped.</s>

<s docid="AP881002-0048" num="41" wdcount="13"> American runner Johnny Gray kicked a taxicab in an argument with its driver.</s>

<s docid="AP881002-0048" num="42" wdcount="5"> He was arrested and released.</s>

<s docid="AP881002-0048" num="43" wdcount="30"> Security measures against the possibility of terrorism were extraordinary, including metal detectors, numerous checkpoints and ID cards, but except for scattered protests by student radicals, the Games proceeded without incident.</s>

<s docid="AP881002-0048" num="44" wdcount="25"> At the closing ceremonies, before the great torch was extinguished, Korea passed the Olympic flag to representatives from Barcelona, site of the 1992 Games .</s>
</TEXT>
</DOC>
