<DOC>
<DOCNO>

<s docid="AP880228-0097" num="1" wdcount="1"> AP880228-0097</s>
</DOCNO>
<FILEID>

<s docid="AP880228-0097" num="2" wdcount="2"> AP-NR-02-28-88 2231EST</s>
</FILEID>
<FIRST>

<s docid="AP880228-0097" num="3" wdcount="5"> r i AM-OlympicsNewspage 02-28 0368</s>
</FIRST>
<SECOND>

<s docid="AP880228-0097" num="4" wdcount="2"> AM-Olympics Newspage,0376</s>
</SECOND>
<HEAD>

<s docid="AP880228-0097" num="5" wdcount="6"> America's Showing Worst In 52 Years</s>
</HEAD>
<DATELINE>

<s docid="AP880228-0097" num="6" wdcount="3"> CALGARY, Alberta (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880228-0097" num="7" wdcount="43"> Time ran out for the U.S. athletes when the Winter Olympics ended Sunday, with a team headed by Brent Rushlaw a tick away from a U.S. bobsled medal and Dutch speed skater Yvonne van Gennip a triple gold medalist with time to spare.</s>

<s docid="AP880228-0097" num="8" wdcount="16"> The best America could do was six medals, its worst Winter Games showing in 52 years.</s>

<s docid="AP880228-0097" num="9" wdcount="20"> Two of the six were gold medals, won by Brian Boitano in figure skating and Bonnie Blair in speed skating.</s>

<s docid="AP880228-0097" num="10" wdcount="14"> Blair also won a bronze in speed skating, making her America's only double winner.</s>

<s docid="AP880228-0097" num="11" wdcount="17"> The Olympics wrapped up Sunday evening with a rousing closing ceremony before 60,000 people in McMahon Stadium.</s>

<s docid="AP880228-0097" num="12" wdcount="36"> The 250 figure skaters who performed included past and present medal winners as well as young skaters from Albertville, France, site of the 1992 Winter Games, and Seoul, South Korea, site of this year's summer Games.</s>

<s docid="AP880228-0097" num="13" wdcount="25"> Athletes marched in carrying miniature Olympic torches, and banners reading ``Until We Meet Again'' in eight languages were draped along the top of the stands.</s>

<s docid="AP880228-0097" num="14" wdcount="28"> Earlier Sunday, Rushlaw and his three team members missed winning the first U.S. bobsled medal in 32 years when they was beaten by .02 seconds for the bronze.</s>

<s docid="AP880228-0097" num="15" wdcount="22"> Van Gennip took more than six seconds off her own world record in the 5,000 meters to win her third gold medal.</s>

<s docid="AP880228-0097" num="16" wdcount="7"> American Mary Docter was 22.87 seconds behind.</s>

<s docid="AP880228-0097" num="17" wdcount="7"> East Germans finished 2-3 in the race.</s>

<s docid="AP880228-0097" num="18" wdcount="16"> Finland won the hockey silver medal, handing the Soviets their first loss of the Games, 2-1.</s>

<s docid="AP880228-0097" num="19" wdcount="17"> The Soviets clinched the gold medal Friday night, and America finished seventh for the second straight time.</s>

<s docid="AP880228-0097" num="20" wdcount="13"> In 1936, America won just four medals, but only 51 were available then.</s>

<s docid="AP880228-0097" num="21" wdcount="7"> This time, 138 medals were handed out.</s>

<s docid="AP880228-0097" num="22" wdcount="23"> The Soviets finished first in both number of gold medals, with 11, and total medals, with 29, a record for the Winter Olympics.</s>

<s docid="AP880228-0097" num="23" wdcount="23"> East Germany's athletes won nine golds, 25 overall; while Switzerland's team came in third in both gold medals, five, and overall medals, 15.</s>

<s docid="AP880228-0097" num="24" wdcount="21"> Four other teams also bested the United States in terms of overall medals: Austria, West Germany, Finland and the Netherlands .</s>
</TEXT>
</DOC>
