<DOC>
<DOCNO>

<s docid="AP900328-0128" num="1" wdcount="1"> AP900328-0128</s>
</DOCNO>
<FILEID>

<s docid="AP900328-0128" num="2" wdcount="2"> AP-NR-03-28-90 1820EST</s>
</FILEID>
<FIRST>

<s docid="AP900328-0128" num="3" wdcount="7"> u w AM-Bush-JesseOwens 1stLd-Writethru a0603 03-28 0477</s>
</FIRST>
<SECOND>

<s docid="AP900328-0128" num="4" wdcount="5"> AM-Bush-Jesse Owens, 1st Ld-Writethru, a0603,470</s>
</SECOND>
<NOTE>

<s docid="AP900328-0128" num="5" wdcount="18"> Eds: INSERTS 2 grafs after pvs 3rd graf bgng ``This Saturday ''... to add Bush's banquet remarks .</s>
</NOTE>
<BYLINE>

<s docid="AP900328-0128" num="6" wdcount="3"> By CHRISTOPHER CONNELL</s>
</BYLINE>
<BYLINE>

<s docid="AP900328-0128" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900328-0128" num="8" wdcount="2"> WASHINGTON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900328-0128" num="9" wdcount="34"> The late Jesse Owens, whose performance at the 1936 Olympics put the lie to Hitler's boasts of racial superiority, picked up a fifth gold medal Wednesday for ``humanitarian contributions in the race of life''.</s>

<s docid="AP900328-0128" num="10" wdcount="30"> President Bush presented the Congressional Gold Medal to his widow, Ruth Owens, in a ceremony at the White House also attended by three daughters and teammates of the track legend.</s>

<s docid="AP900328-0128" num="11" wdcount="12"> This Saturday marks the 10th anniversary of Owens' death at age 66.</s>

<s docid="AP900328-0128" num="12" wdcount="28"> The president later hailed Owens's multiple gold medals in the Berlin games ``a victory for humanity'' in prepared remarks to a banquet sponsored by the U.S. Olympic Committee.</s>

<s docid="AP900328-0128" num="13" wdcount="27"> ``The Olympics, like democracy, are a kind of dialogue _ a way that nations can converse in the language of friendly competition, not deadly conflict,'' Bush said.</s>

<s docid="AP900328-0128" num="14" wdcount="19"> Bush called Owens, who was black, an ``Olympic hero and an American hero every day of his life ...</s>

<s docid="AP900328-0128" num="15" wdcount="7"> born with the gift of burning speed''.</s>

<s docid="AP900328-0128" num="16" wdcount="32"> ``He was always the fastest,'' said Bush, recalling the afternoon in May 1935 when the Ohio State runner broke three world records and tied a fourth in the space of 45 minutes.</s>

<s docid="AP900328-0128" num="17" wdcount="9"> ``Talk about a guy in a hurry,'' Bush laughed.</s>

<s docid="AP900328-0128" num="18" wdcount="6"> ``He was the epitome of that''.</s>

<s docid="AP900328-0128" num="19" wdcount="24"> At the 1936 Olympic Games in Berlin, Owens captured four gold medals _ in the broad jump, 100-meter dash, 200-meter dash and 400-meter relay.</s>

<s docid="AP900328-0128" num="20" wdcount="26"> ``The Berlin Games were to be the showcase of Hitler's theories on the superiority of the master race until this 23-year-old kid'' showed up, Bush said.</s>

<s docid="AP900328-0128" num="21" wdcount="6"> ``It was an unrivaled athletic triumph.</s>

<s docid="AP900328-0128" num="22" wdcount="12"> But more than that, it really was a triumph for all humanity''.</s>

<s docid="AP900328-0128" num="23" wdcount="30"> Bush, borrowing a phrase from Ruth Owens, said it was not those athletic feats but ``his humanitarian contributions in the race of life'' that earned Owens the Congressional Gold Medal.</s>

<s docid="AP900328-0128" num="24" wdcount="17"> Owens devoted himself to working with youth and serving as ``a special ambassador for sports,'' said Bush.</s>

<s docid="AP900328-0128" num="25" wdcount="34"> He said the athlete's legacy lives on through the Jesse Owens Games, a playground Olympics; the Jesse Owens International Trophy for amateur athletes and the Jesse Owens Foundation, which awards scholarships to needy youth.</s>

<s docid="AP900328-0128" num="26" wdcount="17"> ``Despite the many honors, his greatest satisfaction came from his work with youth,'' said Mrs. Owens, 74.</s>

<s docid="AP900328-0128" num="27" wdcount="45"> Attending the ceremony along with Owens' family were former Olympians Mal Whitfield, Harrison Dillard and Herb Douglass; former teammates John Chavers, Samuel Devine and Chester Thomas, and two Ohio Democrats, Sen. Howard Metzenbaum and Rep. Louis Stokes, who spearheaded the drive to strike the medal.</s>

<s docid="AP900328-0128" num="28" wdcount="15"> The silver-haired Mrs. Owens, standing outside the White House afterwards, called the event ``absolutely beautiful''.</s>

<s docid="AP900328-0128" num="29" wdcount="14"> She added: ``I'm sure with the sun shining straight down, Jesse's watching us, too.''</s>
</TEXT>
</DOC>
