<DOC>
<DOCNO>

<s docid="FT923-8765" num="1" wdcount="1"> FT923-8765</s>
</DOCNO>
<PROFILE>

<s docid="FT923-8765" num="2" wdcount="1"> _AN-CHLBKAEXFT</s>
</PROFILE>
<DATE>

<s docid="FT923-8765" num="3" wdcount="1"> 920808</s>
</DATE>
<HEADLINE>

<s docid="FT923-8765" num="4" wdcount="17"> FT 08 AUG 92 / The Barcelona Olympics: Minnows vs big spenders - Tonight's athletics relay finals</s>
</HEADLINE>
<BYLINE>

<s docid="FT923-8765" num="5" wdcount="3"> By PETER BERLIN</s>
</BYLINE>
<TEXT>

<s docid="FT923-8765" num="6" wdcount="16"> TONIGHT in the big stadium in Barcelona the athletics is dominated by the four relay finals.</s>

<s docid="FT923-8765" num="7" wdcount="6"> Tonight it is nation versus nation.</s>

<s docid="FT923-8765" num="8" wdcount="36"> What the relays demonstrate more clearly than any other athletics event is that at the Olympics the race has traditionally gone to affluent countries - or to those, rather, that choose to lavish resources on athletes.</s>

<s docid="FT923-8765" num="9" wdcount="35"> The US has comfortably won the most relay medals, followed by Britain, the former Soviet Union, the former West Germany (not even counting the six won before 1939), the former East Germany, France and Canada.</s>

<s docid="FT923-8765" num="10" wdcount="22"> Britain alone have won more relay medals (23) than all the Caribbean islands (nine) and Africa (four, including one for South Africa).</s>

<s docid="FT923-8765" num="11" wdcount="20"> The Dutch, with one, have more relay medals than all the nations of Asia (nil) and South America (nil) combined.</s>

<s docid="FT923-8765" num="12" wdcount="25"> The Cuban women's 100 metres relay teams of 1968 and 1972 are the only women from outside the developed world to have won relay medals.</s>

<s docid="FT923-8765" num="13" wdcount="27"> With a little luck - with their nerve-stretching hand-overs the relays always require a little luck - the developing countries will continue the gentle redistribution of medals.</s>

<s docid="FT923-8765" num="14" wdcount="17"> But although they have talent, few can match the strength in depth of the traditional relay powers.</s>

<s docid="FT923-8765" num="15" wdcount="13"> The US 4x400m squad has been weakened by the injury to Danny Everett.</s>

<s docid="FT923-8765" num="16" wdcount="14"> Even so they rested Steve Lewis, the 400m silver medallist, in last night's semi-finals.</s>

<s docid="FT923-8765" num="17" wdcount="25"> In the 4x100m heats James Jett replaced Carl Lewis but Lewis ran impressively in last night's semi-final and tonight will pursue his eighth Olympic gold.</s>

<s docid="FT923-8765" num="18" wdcount="38"> One thing that became clear on Thursday, when Lewis won his seventh gold with victory in the long jump, was that while winning at the Olympics may bring other athletes excitement or relief, Lewis simply adores the experience.</s>

<s docid="FT923-8765" num="19" wdcount="48"> When Voula Patoulidou, looking up at the giant video screen after the women's 100m hurdle final, suddenly realised, to her astonishment, that she had won a gold medal, she went delightfully and utterly potty, as did the other 25 Greeks in the stadium, including Queen Sofia of Spain.</s>

<s docid="FT923-8765" num="20" wdcount="19"> Lewis, on the other hand, seemed unsurprised when Mike Powell was unable to overhaul him in the long jump.</s>

<s docid="FT923-8765" num="21" wdcount="28"> Even though the long jump had not finished and even though 5,000m runners were trudging through a semi-final, Lewis began at once an extremely hammy lap-and-a-half of honour.</s>

<s docid="FT923-8765" num="22" wdcount="7"> He tried to orchestrate a Mexican wave.</s>

<s docid="FT923-8765" num="23" wdcount="16"> This is a man who derives immense pleasure from winning in front of a packed house.</s>

<s docid="FT923-8765" num="24" wdcount="7"> Lewis will be difficult to suppress tonight.</s>

<s docid="FT923-8765" num="25" wdcount="13"> Noureddine Morcelli of Algeria will be hard to beat in the men's 1,500m.</s>

<s docid="FT923-8765" num="26" wdcount="25"> Morcelli is one of five Africans in the final striving to increase their continent's tally of just three Olympic medals (all Kenyan) in this event.</s>

<s docid="FT923-8765" num="27" wdcount="21"> Even here there is a US connection: Morcelli attended Riverside Community College in California, to hone his running on good tracks.</s>

<s docid="FT923-8765" num="28" wdcount="18"> On Thursday night, Morcelli cruised through his heat in first place after the gentlest push on the accelerator.</s>

<s docid="FT923-8765" num="29" wdcount="25"> The Moroccan Rachid Al-Basir followed him down the straight, a respectful step behind, looming over his fellow Arab and glancing anxiously round like a bodyguard.</s>

<s docid="FT923-8765" num="30" wdcount="11"> Morcelli has not been beaten in the 1,500m since 1990 .</s>
</TEXT>
<PUB>

<s docid="FT923-8765" num="31" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT923-8765" num="32" wdcount="3"> London Page IX</s>
</PAGE>
</DOC>
