<DOC>
<DOCNO>

<s docid="LA040790-0121" num="1" wdcount="1"> LA040790-0121</s>
</DOCNO>
<DOCID>

<s docid="LA040790-0121" num="2" wdcount="1"> 201051</s>
</DOCID>
<DATE>
<P>

<s docid="LA040790-0121" num="3" wdcount="6"> April 7, 1990, Saturday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA040790-0121" num="4" wdcount="9"> Sports; Part C; Page 16; Column 1; Sports Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA040790-0121" num="5" wdcount="2"> 409 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA040790-0121" num="6" wdcount="6"> SHOOTER BAKES SETS RECORD, WINS GOLD</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA040790-0121" num="7" wdcount="6"> By ELLIOTT ALMOND, TIMES STAFF WRITER</s>
</P>
</BYLINE>
<TEXT>
<P>

<s docid="LA040790-0121" num="8" wdcount="15"> Someday, Milan Bakes of Czechoslovakia might find himself the toast of Pilsen, his hometown .</s>
</P>
<P>

<s docid="LA040790-0121" num="9" wdcount="14"> As one of the world's finest small-bore free-rifle shooters, he is coming close .</s>
</P>
<P>

<s docid="LA040790-0121" num="10" wdcount="39"> Bakes, 27, set a world record in the kneeling portion of the three-position rifle competition Friday en route to a gold medal at the 1990 World Cup USA Olympic-style shooting tournament at Petersen's Prado Tiro Ranges in Chino .</s>
</P>
<P>

<s docid="LA040790-0121" num="11" wdcount="23"> By scoring 396 of a possible 400 points, Bakes broke the record set last week in Mexico City by Yugoslavia's Rajmond Debevec .</s>
</P>
<P>

<s docid="LA040790-0121" num="12" wdcount="15"> The event includes 120 total shots in three positions -- prone, standing and kneeling .</s>
</P>
<P>

<s docid="LA040790-0121" num="13" wdcount="14"> Bakes once held the record for standing, too, but that was four years ago.</s>

<s docid="LA040790-0121" num="14" wdcount="28"> He has yet to hold the prone record, but his 397 in that discipline helped him take a big lead in one of three medal events Friday .</s>
</P>
<P>

<s docid="LA040790-0121" num="15" wdcount="12"> Counting the 10-shot shoot-off, Bakes finished with 1,275.9 points out of 1,309.</s>

<s docid="LA040790-0121" num="16" wdcount="10"> Jean Pierre Amat of France was second with 1,271.9 .</s>
</P>
<P>

<s docid="LA040790-0121" num="17" wdcount="21"> Bakes, a lieutenant in the Czech army, said he was confident after his kneeling performance that he would do well .</s>
</P>
<P>

<s docid="LA040790-0121" num="18" wdcount="25"> In the day's closest competition, Francoise Decharne of Moulin, France, won the women's air rifle competition with a total of 496.4 of a possible 509.</s>

<s docid="LA040790-0121" num="19" wdcount="14"> Soon Young Jin of South Korea was second and Deena Wigger of Murray, Ky.</s>

<s docid="LA040790-0121" num="20" wdcount="4"> , was third .</s>
</P>
<P>

<s docid="LA040790-0121" num="21" wdcount="22"> Wigger was second after the regular competition ended, but fell 0.7 of a point behind Jin in a 10-shot final round .</s>
</P>
<P>

<s docid="LA040790-0121" num="22" wdcount="14"> All international events have added the final round to increase television and spectator interest.</s>

<s docid="LA040790-0121" num="23" wdcount="20"> The top eight shooters in pistol, rifle and air events qualify, whereas the top six advance in shotgun events .</s>
</P>
<P>

<s docid="LA040790-0121" num="24" wdcount="38"> In women's air pistol, Jasna Sekaric of Yugoslavia won her second gold of the four-day event with a total of 490.8. Hyun Joo Bang of South Korea was second and Margit Stein of West Germany was third .</s>
</P>
<P>

<s docid="LA040790-0121" num="25" wdcount="12"> Sekaric, 24, held a nine-point lead going into the final round .</s>
</P>
<P>

<s docid="LA040790-0121" num="26" wdcount="8"> "My final was not so good," she said.</s>

<s docid="LA040790-0121" num="27" wdcount="7"> "I had too big of a lead.</s>

<s docid="LA040790-0121" num="28" wdcount="12"> I usually shoot better in these finals when I am pressed" .</s>
</P>
<P>

<s docid="LA040790-0121" num="29" wdcount="24"> Despite her lapse, she still won by 8.4 points over Bang, perhaps the most appropriately named competitor in this tournament featuring 46 countries .</s>
</P>
<P>

<s docid="LA040790-0121" num="30" wdcount="15"> Sekaric, a secretary at a shooting club, said she has been competing for 10 years.</s>

<s docid="LA040790-0121" num="31" wdcount="11"> She won gold and bronze medals at the Seoul Olympics .</s>
</P>
<P>

<s docid="LA040790-0121" num="32" wdcount="15"> Bang, also 24, and a Seoul bank accountant, did not fare so well in 1988.</s>

<s docid="LA040790-0121" num="33" wdcount="7"> Friday was her best international performance .</s>
</P>
</TEXT>
<TYPE>
<P>

<s docid="LA040790-0121" num="34" wdcount="2"> Game Story</s>
</P>
</TYPE>
<SUBJECT>
<P>

<s docid="LA040790-0121" num="35" wdcount="9"> SHOOTING (SPORT); SPORTS RECORDS; CZECHOSLOVAKIA -- ATHLETICS; BAKES, MILAN</s>
</P>
</SUBJECT>
</DOC>
