<DOC>
<DOCNO>

<s docid="LA082889-0067" num="1" wdcount="1"> LA082889-0067</s>
</DOCNO>
<DOCID>

<s docid="LA082889-0067" num="2" wdcount="1"> 100353</s>
</DOCID>
<DATE>
<P>

<s docid="LA082889-0067" num="3" wdcount="6"> August 28, 1989, Monday, Southland Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA082889-0067" num="4" wdcount="9"> Sports; Part 3; Page 4; Column 1; Sports Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA082889-0067" num="5" wdcount="2"> 559 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA082889-0067" num="6" wdcount="3"> WORLD UNIVERSITY GAMES;</s>
</P>
<P>

<s docid="LA082889-0067" num="7" wdcount="8"> JOHNSON RUNS DOWN DECATHLON GOLD IN FINAL EVENT</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA082889-0067" num="8" wdcount="3"> From Associated Press</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA082889-0067" num="9" wdcount="3"> DUISBURG, West Germany</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA082889-0067" num="10" wdcount="22"> Dave Johnson of the United States clinched the decathlon gold medal in the final event at the World University Games Sunday .</s>
</P>
<P>

<s docid="LA082889-0067" num="11" wdcount="23"> Johnson trailed Mikhail Medved of the Soviet Union by 11 points before the 1,500-meter race, the final event of the two-day competition .</s>
</P>
<P>

<s docid="LA082889-0067" num="12" wdcount="14"> "It's the hardest I've ever worked in my life," said Johnson, of Montclair, Calif.</s>

<s docid="LA082889-0067" num="13" wdcount="5"> "I was scared to death.</s>

<s docid="LA082889-0067" num="14" wdcount="15"> I knew I had to run at my best or even better to win" .</s>
</P>
<P>

<s docid="LA082889-0067" num="15" wdcount="12"> Johnson posted a time of 4 minutes 32.72 seconds in the 1,500.</s>

<s docid="LA082889-0067" num="16" wdcount="16"> That gave him 727 points for a winning total of 8,216, 154 more than Medved .</s>
</P>
<P>

<s docid="LA082889-0067" num="17" wdcount="23"> The Soviet had a time of 4:59.60 in the race, worth 562 points, and ended up second with a total of 8,062 .</s>
</P>
<P>

<s docid="LA082889-0067" num="18" wdcount="11"> Johnson leads the world decathlon rankings this year with 8,549 points.</s>

<s docid="LA082889-0067" num="19" wdcount="21"> "I always go out to give 100%, but the weather conditions stopped me from having a better score," he said .</s>
</P>
<P>

<s docid="LA082889-0067" num="20" wdcount="12"> Sheldon Blockburger of the U.S. was third going into the last event.</s>

<s docid="LA082889-0067" num="21" wdcount="18"> But he was overtaken by Dezso Szabo of Hungary and had to settle for fourth place at 7,906.</s>

<s docid="LA082889-0067" num="22" wdcount="7"> Szabo clinched the bronze with 8,031 .</s>
</P>
<P>

<s docid="LA082889-0067" num="23" wdcount="31"> "I felt good going into the race, but my legs just gave out," said Blockburger, who had the slowest 1,500 time and earned only 569 points in the final event .</s>
</P>
<P>

<s docid="LA082889-0067" num="24" wdcount="30"> Olympic steeplechase champion Julius Kariuki of Kenya, running the distance for the first time this year, won the men's 10,000-meter race, while the Romanian team earned six gold medals .</s>
</P>
<P>

<s docid="LA082889-0067" num="25" wdcount="33"> Four of Romania's golds came in rowing and two in track and field, one of them from Olympic champion Paula Ivan, who set a meet record in winning the women's 3,000-meter race .</s>
</P>
<P>

<s docid="LA082889-0067" num="26" wdcount="21"> Reggie Davis won the gold and Kevin Henderson took the bronze for the U.S. in the men's 400-meter intermediate hurdles .</s>
</P>
<P>

<s docid="LA082889-0067" num="27" wdcount="12"> Davis, of Tallahassee, Fla., breezed home in the hurdles in 49.74 seconds.</s>

<s docid="LA082889-0067" num="28" wdcount="21"> Vladimir Budko of the Soviet Union was a distant second in 50.30, with Henderson, of Auburn, Ala., third in 50.57 .</s>
</P>
<P>

<s docid="LA082889-0067" num="29" wdcount="15"> "I had some problems recently with disqualifications, but this time it was OK," Davis said.</s>

<s docid="LA082889-0067" num="30" wdcount="15"> "I wanted this title and a meet record, but the weather spoiled my chances" .</s>
</P>
<P>

<s docid="LA082889-0067" num="31" wdcount="32"> Kariuki, who won the gold medal at the 1988 Seoul Games in the 3,000-meter steeplechase, beat out Zeki Oeztuerk of Turkey to win the 10,000 in the slow time of 28:35.46 .</s>
</P>
<P>

<s docid="LA082889-0067" num="32" wdcount="12"> "I ran to win and didn't worry about the time," Kariuki said.</s>

<s docid="LA082889-0067" num="33" wdcount="18"> "I'm in good condition and it's not a problem to run either the steeplechase or the 10,000" .</s>
</P>
<P>

<s docid="LA082889-0067" num="34" wdcount="29"> Ivan, the Olympic 1,500-meter champion and silver medalist at 3,000 meters, won the gold in the 3,000 in 8:44.09, bettering her meet record of 8:53.61 set in 1987 .</s>
</P>
<P>

<s docid="LA082889-0067" num="35" wdcount="26"> Ana Quirot of Cuba cruised to victory in the women's 400 meters in a slow 50.73, ahead of Jearl Miles of the U.S. at 52.41 .</s>
</P>
<P>

<s docid="LA082889-0067" num="36" wdcount="17"> Quirot posted a meet record of 50.01 in Saturday's heats, fastest in the world this year .</s>
</P>
<P>

<s docid="LA082889-0067" num="37" wdcount="17"> Miles, of Jacksonville, Fla., said she tried to conserve her strength for the final 200 meters .</s>
</P>
<P>

<s docid="LA082889-0067" num="38" wdcount="25"> "I tried not to waste too much energy on the backstretch and concentrated on giving a big burst on the home stretch," she said .</s>
</P>
<P>

<s docid="LA082889-0067" num="39" wdcount="15"> Jaime Jefferson of Cuba won the men's long jump at 26 feet, 2 1/4 inches.</s>

<s docid="LA082889-0067" num="40" wdcount="22"> Vladimir Ratoushkov of the Soviet Union was second at 26-1 1/2, followed by Llewellyn Starks of the U.S. at 25-11 1/2 .</s>
</P>
<P>

<s docid="LA082889-0067" num="41" wdcount="18"> Galina Astafei of Romania, the world junior champion, upset Silvia Costa of Cuba in the women's high jump.</s>

<s docid="LA082889-0067" num="42" wdcount="11"> Both cleared 6-3 1/4 but Astafei won on fewer misses .</s>
</P>
</TEXT>
<TYPE>
<P>

<s docid="LA082889-0067" num="43" wdcount="3"> Game Story; Wire</s>
</P>
</TYPE>
</DOC>
