<DOC>
<DOCNO>

<s docid="AP891111-0064" num="1" wdcount="1"> AP891111-0064</s>
</DOCNO>
<FILEID>

<s docid="AP891111-0064" num="2" wdcount="2"> AP-NR-11-11-89 1140EST</s>
</FILEID>
<FIRST>

<s docid="AP891111-0064" num="3" wdcount="6"> u w AM-GermanReunification Bjt 11-11 0725</s>
</FIRST>
<SECOND>

<s docid="AP891111-0064" num="4" wdcount="3"> AM-German Reunification, Bjt,700</s>
</SECOND>
<HEAD>

<s docid="AP891111-0064" num="5" wdcount="7"> East German Changes Spark Interest in Reunification</s>
</HEAD>
<BYLINE>

<s docid="AP891111-0064" num="6" wdcount="3"> By GEORGE GEDDA</s>
</BYLINE>
<BYLINE>

<s docid="AP891111-0064" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP891111-0064" num="8" wdcount="2"> WASHINGTON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP891111-0064" num="9" wdcount="35"> The concept of a reunified Germany enjoys support from the United States and other countries but some analysts believe the consequences of a political and economic German superstate could have an unsettling effect throughout Europe.</s>

<s docid="AP891111-0064" num="10" wdcount="32"> The lifting of travel restrictions by East Germany on Thursday has breathed new life into the idea of a single German state, drawing expressions of support from the Bush administration and others.</s>

<s docid="AP891111-0064" num="11" wdcount="36"> But Soviet affairs expert William Hyland says that despite these assertions, a reunified Germany is ``really terrifying to most of the countries involved, to the West Germans, to the United States, Soviet Union, Poland and Czechoslovakia.</s>

<s docid="AP891111-0064" num="12" wdcount="34"> ``No one really wants German unity except the East German people, and they turn out to be the decisive factor,'' says Hyland, a one-time top aide to former Secretary of State Henry A. Kissinger.</s>

<s docid="AP891111-0064" num="13" wdcount="40"> It was just 2 months ago when ceremonies were held commemorating the 50th anniversary of the start of World War II, a time when a unified Germany initiated what was to become the slaughter of more than 50 million people.</s>

<s docid="AP891111-0064" num="14" wdcount="27"> While a recurrence of that nightmare seems remote at best under any scenario, an undivided Germany could become the unchallenged economic and political force on the continent.</s>

<s docid="AP891111-0064" num="15" wdcount="19"> The official U.S. policy on the reunification question was outlined last Thursday by State Department deputy spokesman Richard Boucher.</s>

<s docid="AP891111-0064" num="16" wdcount="38"> ``Reunification has been supported by NATO and by the United States for 40 years, and our strongly held view is that reunification or reconciliation between the peoples of Germany must take place in peace and freedom,'' he said.</s>

<s docid="AP891111-0064" num="17" wdcount="27"> As former National Security adviser Zbigniew Brzezinski sees it, the reunification issue will become ``very, very active'' if a freely elected government takes power in East Germany.</s>

<s docid="AP891111-0064" num="18" wdcount="16"> That possibility has been mentioned by East German leaders as part of the ongoing reform process.</s>

<s docid="AP891111-0064" num="19" wdcount="29"> Brzezinski asks: ``How do we arrange for the unification of Germany, so that it doesn't become destabilizing, so it isn't a threat to Germany's neighbors _ France, Poland, Czechoslovakia?</s>

<s docid="AP891111-0064" num="20" wdcount="12"> ``These are the issues we really have to very hard think about.</s>

<s docid="AP891111-0064" num="21" wdcount="14"> We have to think of a new structure between NATO and the Warsaw Pact.</s>

<s docid="AP891111-0064" num="22" wdcount="5"> That is our new agenda''.</s>

<s docid="AP891111-0064" num="23" wdcount="33"> Theodore Sorenson, a top aide to President John F. Kennedy when the Berlin Wall was built in 1961, says he hopes a reunited Germany will be forged as part of a reunited Europe.</s>

<s docid="AP891111-0064" num="24" wdcount="19"> Reunification, Sorenson says, ``will pose problems, because we couldn't afford to have a reunited Germany outside the Western Alliance.</s>

<s docid="AP891111-0064" num="25" wdcount="16"> The Soviet Union couldn't afford to have a reunited Germany as part of the Western Alliance.</s>

<s docid="AP891111-0064" num="26" wdcount="20"> ``That's why I hope it will be a reunited Europe within which the reunited Germany can take place,'' Sorenson says.</s>

<s docid="AP891111-0064" num="27" wdcount="16"> Bernard Rogers, a former commander of allied forces in Europe, does not think reunification is inevitable.</s>

<s docid="AP891111-0064" num="28" wdcount="9"> Some form of federation, he believes, is more likely.</s>

<s docid="AP891111-0064" num="29" wdcount="28"> Rogers notes that Soviet President Mikhail Gorbachev has said the nations of eastern Europe can do what they want so long as they stay in the Warsaw Pact.</s>

<s docid="AP891111-0064" num="30" wdcount="35"> ``If East Germany stays in the Warsaw Pact, NATO, with the best of its ability, would try to prevent full reunification; maybe a confederation between the two Germanys, but not a full reunification,'' Rogers says.</s>

<s docid="AP891111-0064" num="31" wdcount="18"> Senate Majority Leader George Mitchell, D-Maine, points out that German reunification is a sensitive question for the Soviets.</s>

<s docid="AP891111-0064" num="32" wdcount="17"> ``Soviet policy is based upon preventing a reunified, economically strong and certainly militarily strong Germany,'' Mitchell says.</s>

<s docid="AP891111-0064" num="33" wdcount="26"> ``There must be some serious apprehension in the Soviet Union today, because the events of the last couple of days certainly has made reunification more likely''.</s>

<s docid="AP891111-0064" num="34" wdcount="30"> The Bush administration says it does not foresee the dismantling of NATO under any circumstances but, according to Hyland, the reunification of Germany could mean the demise of the alliance.</s>

<s docid="AP891111-0064" num="35" wdcount="25"> ``It may also mean the end of Western European unity, because both have been based on a divided Germany and a divided Europe,'' Hyland says.</s>

<s docid="AP891111-0064" num="36" wdcount="26"> ``If that comes to an end and 80 million Germans are united in a confederation or a single state, it changes the entire map of Europe.</s>

<s docid="AP891111-0064" num="37" wdcount="17"> ``It changes all of the geopolitics and, in effect, ends the period we've been in since ...</s>

<s docid="AP891111-0064" num="38" wdcount="5"> the beginning of the war.''</s>
</TEXT>
</DOC>
