<DOC>
<DOCNO>

<s docid="AP891202-0154" num="1" wdcount="1"> AP891202-0154</s>
</DOCNO>
<FILEID>

<s docid="AP891202-0154" num="2" wdcount="2"> AP-NR-12-02-89 0241EST</s>
</FILEID>
<FIRST>

<s docid="AP891202-0154" num="3" wdcount="5"> r i AM-Germany-NATO 12-02 0378</s>
</FIRST>
<SECOND>

<s docid="AP891202-0154" num="4" wdcount="1"> AM-Germany-NATO,0384</s>
</SECOND>
<HEAD>

<s docid="AP891202-0154" num="5" wdcount="10"> West German Leader Tries to Reassure U.S. Senators on NATO</s>
</HEAD>
<HEAD>

<s docid="AP891202-0154" num="6" wdcount="3"> With AM-East Germany</s>
</HEAD>
<BYLINE>

<s docid="AP891202-0154" num="7" wdcount="3"> By TERRENCE PETTY</s>
</BYLINE>
<BYLINE>

<s docid="AP891202-0154" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP891202-0154" num="9" wdcount="4"> BONN, West Germany (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP891202-0154" num="10" wdcount="32"> Chancellor Helmut Kohl assured visiting U.S. senators on the eve of a superpower summit that West Germany will not forsake NATO to reunite with East Germany, one of the senators said Friday.</s>

<s docid="AP891202-0154" num="11" wdcount="28"> ``He strongly affirmed under no circumstances would a reunified Germany be neutral,'' Sen. Richard G. Lugar, head of the American delegation, said of the Friday meeting with Kohl.</s>

<s docid="AP891202-0154" num="12" wdcount="26"> Asked whether he thought the West Germans were committed to staying in the NATO military alliance of Western nations, the Indiana Republican said: ``Without any reservations''.</s>

<s docid="AP891202-0154" num="13" wdcount="23"> There is growing discussion in West Germany about German reunification as a result of sweeping social and political reforms underway in East Germany.</s>

<s docid="AP891202-0154" num="14" wdcount="25"> There has been speculation that West Germany might someday be tempted to agree to neutrality if the Kremlin stipulates it as the price for reunification.</s>

<s docid="AP891202-0154" num="15" wdcount="14"> Kohl on Tuesday unveiled a 10-point proposal with German reunification as its ultimate goal.</s>

<s docid="AP891202-0154" num="16" wdcount="27"> But the Soviets, who suffered millions of deaths fighting a unified Germany in World War II, have said the idea of German reunification is ``dangerous and unrealistic''.</s>

<s docid="AP891202-0154" num="17" wdcount="18"> President Bush and Soviet President Mikhail S. Gorbachev are to begin a shipboard summit off Malta on Saturday.</s>

<s docid="AP891202-0154" num="18" wdcount="24"> The dramatic events in East Germany and whirlwind reforms elsewhere in the East bloc are likely to be a main topic of their talks.</s>

<s docid="AP891202-0154" num="19" wdcount="11"> Lugar came to Bonn with eight other members of the U.S.</s>

<s docid="AP891202-0154" num="20" wdcount="5"> Senate's arms control observer group.</s>

<s docid="AP891202-0154" num="21" wdcount="25"> He said the purpose of the trip was to ``visit with the Germans on their judgments about all of these procedures that are going on''.</s>

<s docid="AP891202-0154" num="22" wdcount="15"> U.S. Ambassador Vernon A. Walters joined the senators for their 75-minute closed-door talks with Kohl.</s>

<s docid="AP891202-0154" num="23" wdcount="17"> The senators also met with Foreign Minister Hans-Dietrich Genscher and Defense Minister Gerhard Stoltenberg during the day.</s>

<s docid="AP891202-0154" num="24" wdcount="35"> Lugar said Kohl told the Americans that reunification would be a ``procedure that depends on many events in Germany and Europe'' and that the Soviet Union and the United States have a role to play.</s>

<s docid="AP891202-0154" num="25" wdcount="26"> Lugar said of Kohl's proposals, ``There is much to work with there with regard to the future of Germany and the future of the (NATO) alliance.''</s>
</TEXT>
</DOC>
