<DOC>
<DOCNO>

<s docid="AP891207-0158" num="1" wdcount="1"> AP891207-0158</s>
</DOCNO>
<FILEID>

<s docid="AP891207-0158" num="2" wdcount="2"> AP-NR-12-07-89 2156EST</s>
</FILEID>
<FIRST>

<s docid="AP891207-0158" num="3" wdcount="5"> r i AM-Poland-Germany 12-07 0419</s>
</FIRST>
<SECOND>

<s docid="AP891207-0158" num="4" wdcount="1"> AM-Poland-Germany,0433</s>
</SECOND>
<HEAD>

<s docid="AP891207-0158" num="5" wdcount="8"> Poland Says Any German Reunification Must Be Gradual</s>
</HEAD>
<BYLINE>

<s docid="AP891207-0158" num="6" wdcount="3"> By JOHN DANISZEWSKI</s>
</BYLINE>
<BYLINE>

<s docid="AP891207-0158" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP891207-0158" num="8" wdcount="3"> WARSAW, Poland (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP891207-0158" num="9" wdcount="25"> The government on Thursday allowed for the possibility of a reunified Germany, but said such a state must be formed gradually and respect Poland's borders.</s>

<s docid="AP891207-0158" num="10" wdcount="31"> In the Solidarity government's first definitive statement on the issue, Foreign Minister Krzysztof Skubiszewski told Parliament the two German states could be joined as part of the process of uniting Europe.</s>

<s docid="AP891207-0158" num="11" wdcount="12"> He said German reunification ``cannot go ahead'' of the reunification of Europe.</s>

<s docid="AP891207-0158" num="12" wdcount="15"> ``A reunited Germany will not be created tomorrow or the day after tomorrow,'' Skubiszewski said.</s>

<s docid="AP891207-0158" num="13" wdcount="17"> ``Fears and concerns appearing every now and then, including in Poland, are unjustified, although alertness is recommended''.</s>

<s docid="AP891207-0158" num="14" wdcount="32"> Asked about German reunification at a news conference in Gdansk, Solidarity labor leader Lech Walesa said he prefers ``no political changes in Europe, but there should be all kinds of economic integrations''.</s>

<s docid="AP891207-0158" num="15" wdcount="15"> Western European countries have agreed to form an economic union by the end of 1992.</s>

<s docid="AP891207-0158" num="16" wdcount="36"> Sweeping democratic reforms have taken hold in East Germany in the past several weeks under the pressure of mass protests, spurring talk of reuniting the two German states divided at the end of World War II.</s>

<s docid="AP891207-0158" num="17" wdcount="15"> West Germany has proposed a plan for greater unity, but East German leaders reject reunification.</s>

<s docid="AP891207-0158" num="18" wdcount="28"> The specter of a powerful, reunited Germany has troubed many Poles, especially the older ones who recall the 1939 Nazi invasion of Poland that began World War II.</s>

<s docid="AP891207-0158" num="19" wdcount="16"> A reported surge in anti-Polish sentiment in East Germany in recent weeks has heightened Polish anxieties.</s>

<s docid="AP891207-0158" num="20" wdcount="25"> Skubiszewski's speech seemed designed to reassure Poles that the government does not see unification in the near future and will insist on Poland's current borders.</s>

<s docid="AP891207-0158" num="21" wdcount="31"> Skubiszewski faulted West German Chancellor Helmut Kohl's program for gradual German reunification, offered last week, for not making clear that reunification would respect the existing border between Poland and East Germany.</s>

<s docid="AP891207-0158" num="22" wdcount="27"> Some right-wing West German politicians have called for recovering the 40,000 square miles of territory that Germany lost to Poland at the end of World War II.</s>

<s docid="AP891207-0158" num="23" wdcount="8"> The territory is about one-third of present-day Poland.</s>

<s docid="AP891207-0158" num="24" wdcount="27"> East Germany and West Germany each separately has recognized the border, but there has been no official assurance that a reunified Germany would also acknowledge the border.</s>

<s docid="AP891207-0158" num="25" wdcount="13"> ``One can only unite within established borders and without territorial arguments,'' said Skubiszewski.</s>

<s docid="AP891207-0158" num="26" wdcount="26"> He also said German reunification is unlikely as long as West Germany belongs to NATO and East Germany to the Soviet-led Warsaw Pact military alliance .</s>
</TEXT>
</DOC>
