<DOC>
<DOCNO>

<s docid="AP891212-0062" num="1" wdcount="1"> AP891212-0062</s>
</DOCNO>
<FILEID>

<s docid="AP891212-0062" num="2" wdcount="2"> AP-NR-12-12-89 1148EST</s>
</FILEID>
<FIRST>

<s docid="AP891212-0062" num="3" wdcount="6"> u i PM-EastGermany 2ndLd-Writethru 12-12 0648</s>
</FIRST>
<SECOND>

<s docid="AP891212-0062" num="4" wdcount="4"> PM-East Germany, 2nd Ld-Writethru,a0502,0663</s>
</SECOND>
<HEAD>

<s docid="AP891212-0062" num="5" wdcount="8"> Party Admits Socialism Failed; Reunification Splits Democracy Movement</s>
</HEAD>
<HEAD>

<s docid="AP891212-0062" num="6" wdcount="16"> Eds: SUBS 3rd graf `Also today'... with 1 graf to UPDATE with Baker meeting with Modrow.</s>

<s docid="AP891212-0062" num="7" wdcount="5"> Pickup 4th graf `In another...'</s>
</HEAD>
<HEAD>

<s docid="AP891212-0062" num="8" wdcount="2"> LaserPhoto LEI2</s>
</HEAD>
<BYLINE>

<s docid="AP891212-0062" num="9" wdcount="3"> By TONY CZUCZKA</s>
</BYLINE>
<BYLINE>

<s docid="AP891212-0062" num="10" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP891212-0062" num="11" wdcount="4"> LEIPZIG, East Germany (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP891212-0062" num="12" wdcount="23"> The Communist Party today admitted that East Germany's socialist system has failed, and expressed support for a type of partnership with West Germany.</s>

<s docid="AP891212-0062" num="13" wdcount="24"> The statement in the Communist Party newspaper Neues Deutschland was one of the bluntest official assessments to date of the country's increasingly troubled situation.</s>

<s docid="AP891212-0062" num="14" wdcount="19"> It came a day after shouting matches broke out over German reunification during pro-democracy protests in Leipzig and Dresden.</s>

<s docid="AP891212-0062" num="15" wdcount="15"> Also today, Secretary of State James A. Baker III urged caution on the reunification issue.</s>

<s docid="AP891212-0062" num="16" wdcount="19"> He visited the Berlin Wall and met with West German Chancellor Helmut Kohl and East German Premier Hans Modrow.</s>

<s docid="AP891212-0062" num="17" wdcount="28"> In another development, the largest opposition movement, New Forum, announced it will take part as a political party in the country's first free elections, scheduled for May 6.</s>

<s docid="AP891212-0062" num="18" wdcount="40"> Neues Deutschland, in proposing a new party platform, said ``socialism has definitely failed as a social system in our country'' and acknowledged that the ``popular revolutionary movement'' of the past weeks had led to the scrapping of the old system.</s>

<s docid="AP891212-0062" num="19" wdcount="17"> The paper repeated the Communists' promise to work for a new ``democratic socialism'' within a multi-party system.</s>

<s docid="AP891212-0062" num="20" wdcount="32"> During the past few weeks, both Germanys have increased business and cultural ties but have debated what labels to use for closer relations, since the East Berlin government rejects calls for reunification.</s>

<s docid="AP891212-0062" num="21" wdcount="19"> Neues Deutschland urged a ``qualified partnership of both German states'' but rejected any suggestions of resolving the ``German question''.</s>

<s docid="AP891212-0062" num="22" wdcount="42"> During Monday's demonstrations that drew more than 200,000 protesters, the largest of them the now-weekly rally in the southern city of Leipzig, speakers warned that the reunification issue could fracture the popular movement that has forced the ruling Communists into swift retreat.</s>

<s docid="AP891212-0062" num="23" wdcount="15"> One sign said ``Germany United Fatherland,'' using a phrase from the West German national anthem.</s>

<s docid="AP891212-0062" num="24" wdcount="17"> Others, opposing reunification, urged ``No Fourth Reich'' and no transformation of East Germany into West Germany's ``plantation''.</s>

<s docid="AP891212-0062" num="25" wdcount="24"> ADN said 40,000 people demonstrated for reunification in Karl-Marx-Stadt, while several thousand people split into pro- and anti-reunification groups at a rally in Dresden.</s>

<s docid="AP891212-0062" num="26" wdcount="13"> Smaller rallies were also reported by ADN in Schwerin, Potsdam, Neubrandenburg and Halle.</s>

<s docid="AP891212-0062" num="27" wdcount="13"> The agency did not say if reunification played a role in those protests.</s>

<s docid="AP891212-0062" num="28" wdcount="35"> The rallies came shortly after the four victorious World War II Allies met in West Berlin to discuss the latest developments in East Germany and Berlin _ the divided city that they still technically administer.</s>

<s docid="AP891212-0062" num="29" wdcount="29"> The meeting brought together officials of the United States, France and Britain with Soviet officials, who have increasingly expressed concern over calls in both Germanys to reunite the country.</s>

<s docid="AP891212-0062" num="30" wdcount="15"> Kohl has advocated a confederation of the two Germanys, to be followed by eventual reunification.</s>

<s docid="AP891212-0062" num="31" wdcount="25"> But he stressed to reporters on Monday that ``the goal of our policies is not to create an overpowering Germany in the middle of Europe''.</s>

<s docid="AP891212-0062" num="32" wdcount="23"> The West German leader advocates a reunified Germany that would respect the security needs _ and borders _ of the rest of Europe.</s>

<s docid="AP891212-0062" num="33" wdcount="25"> Soviet President Mikhail S. Gorbachev, during a Central Committee in Moscow on Saturday, urged the West not to try to influence developments in East Germany.</s>

<s docid="AP891212-0062" num="34" wdcount="19"> East Germany is a front line of defense for the Soviets, who have nearly 400,000 troops in the country.</s>

<s docid="AP891212-0062" num="35" wdcount="21"> ADN said Gorbachev would meet soon with Gregor Gysi, a reformer who was chosen East German Communist Party chief on Saturday.</s>

<s docid="AP891212-0062" num="36" wdcount="11"> Gysi's rise followed the ouster of two sets of Communist leaders.</s>

<s docid="AP891212-0062" num="37" wdcount="38"> Since East Germans began agitating for an end to Communist domination two months ago, public pressure has forced the opening of the Berlin Wall and pushed the Communists to promise free elections and relinquish their political monopoly .</s>
</TEXT>
</DOC>
