<DOC>
<DOCNO>

<s docid="AP890925-0009" num="1" wdcount="1"> AP890925-0009</s>
</DOCNO>
<FILEID>

<s docid="AP890925-0009" num="2" wdcount="2"> AP-NR-09-25-89 0037EDT</s>
</FILEID>
<FIRST>

<s docid="AP890925-0009" num="3" wdcount="5"> r i PM-OneGermany 09-25 1121</s>
</FIRST>
<SECOND>

<s docid="AP890925-0009" num="4" wdcount="2"> PM-One Germany,1155</s>
</SECOND>
<HEAD>

<s docid="AP890925-0009" num="5" wdcount="9"> German Reunification Again Under Discussion as Changes Sweep Europe</s>
</HEAD>
<HEAD>

<s docid="AP890925-0009" num="6" wdcount="7"> Eds: Also in Monday AMs report .</s>
</HEAD>
<HEAD>

<s docid="AP890925-0009" num="7" wdcount="3"> An AP Extra</s>
</HEAD>
<BYLINE>

<s docid="AP890925-0009" num="8" wdcount="3"> By KEVIN COSTELLOE</s>
</BYLINE>
<BYLINE>

<s docid="AP890925-0009" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890925-0009" num="10" wdcount="4"> FRANKFURT, West Germany (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890925-0009" num="11" wdcount="23"> Three decades ago, a West German politician said German reunification was a ``sleeping lioness'' that would awake one day with a mighty roar.</s>

<s docid="AP890925-0009" num="12" wdcount="23"> Now, there is growing speculation the awakening may be at hand to create a giant political and economic machine that could dominate Europe.</s>

<s docid="AP890925-0009" num="13" wdcount="24"> ``Reunification is coming closer, but I can't say whether it will take 10, 15 or 20 years,'' says West German conservative lawmaker Eduard Lintner.</s>

<s docid="AP890925-0009" num="14" wdcount="18"> ``We have the impression that things are much more concrete than we could have imagined five years ago''.</s>

<s docid="AP890925-0009" num="15" wdcount="27"> The daily sight of thousands of refugees fleeing East German leader Erich Honecker's hard-line Communist rule for the capitalist West has revived international interest in the debate.</s>

<s docid="AP890925-0009" num="16" wdcount="35"> Once dismissed as a nostalgic daydream, the idea of German reunification has gotten a public nod from President Bush and something short of a categorical ``no'' from President Mikhail S. Gorbachev of the Soviet Union.</s>

<s docid="AP890925-0009" num="17" wdcount="8"> The idea makes East German leaders virtually apopletic.</s>

<s docid="AP890925-0009" num="18" wdcount="43"> ``If there were a free choice under the present circumstances in the German Democratic Republic (East Germany), certainly 80 percent to 90 percent would vote for national reunification with the Federal Republic of Germany,'' added the 44-year-old Lintner in an Associated Press interview.</s>

<s docid="AP890925-0009" num="19" wdcount="43"> The West German constitution calls for a united Germany, but it has not been a paramount concern of the West Germans in the years since the ruins of Nazi Germany were divided into East and West at the end of World War II.</s>

<s docid="AP890925-0009" num="20" wdcount="16"> Full national reunification would completey rework the postwar European order mapped out by the conquering Allies.</s>

<s docid="AP890925-0009" num="21" wdcount="18"> It is a prospect that creates unease in Britain and France, and in Poland in the East bloc.</s>

<s docid="AP890925-0009" num="22" wdcount="28"> London's prestigious Sunday Times on Sept. 10 mapped out a possible scenario that includes massive troop reductions in Europe, Honecker's death and further Westernization of Poland and Hungary.</s>

<s docid="AP890925-0009" num="23" wdcount="23"> ``Moscow unilaterally abolishes the Warsaw Pact after guarantees from Poland and Hungary they will not join other alliances,'' the Times' futuristic view continued.</s>

<s docid="AP890925-0009" num="24" wdcount="19"> ``West Germany withdraws from NATO; and a referendum in both East and West Germany votes for reunification and neutrality''.</s>

<s docid="AP890925-0009" num="25" wdcount="31"> That sort of talk is being heard more and more as Moscow loosens its hold on the East bloc and countries like the Soviet Union, Poland and Hungary explore democratic reforms.</s>

<s docid="AP890925-0009" num="26" wdcount="23"> The implications of pulling down the Berlin Wall and other barriers to link the two German states are enormous and, for many, ominous.</s>

<s docid="AP890925-0009" num="27" wdcount="44"> As much of Western Europe heads towards its own unification in 1992, the economic center of gravity would be shifted even further to the German side with a powerhouse of nearly 80 million people _ 61.1 million West Germans and 16.6 million East Germans.</s>

<s docid="AP890925-0009" num="28" wdcount="24"> West Germany is already Europe's largest exporting nation, and despite its many flaws East Germany's economy is the envy of many Soviet bloc neighbors.</s>

<s docid="AP890925-0009" num="29" wdcount="24"> A unified Germany could become the political focal point of a continent already in flux, as democratic movements sweep parts of the Soviet bloc.</s>

<s docid="AP890925-0009" num="30" wdcount="22"> Older generations recall eerie echoes of Nazi dictator Adolf Hitler's boasting that he had brought about ``the unity of the German nation''.</s>

<s docid="AP890925-0009" num="31" wdcount="36"> Eva Kulesza, head of research for the Soviet Union and Eastern Europe at the French Institute of International Relations, says she believes that ``as far as public opinion there is new sort of mistrust toward Germany.</s>

<s docid="AP890925-0009" num="32" wdcount="11"> ``This new fear of Germany is linked to German economic trends.</s>

<s docid="AP890925-0009" num="33" wdcount="11"> Germany is much stronger, much more dynamic than France,'' she added.</s>

<s docid="AP890925-0009" num="34" wdcount="28"> Since West Germany and East Germany are at the front lines of two competing alliances, any signs for eventual reunification would have to come from Washington and Moscow.</s>

<s docid="AP890925-0009" num="35" wdcount="20"> During a news conference last week in Montana, Bush said that reunification is a ``matter for the Germans to decide''.</s>

<s docid="AP890925-0009" num="36" wdcount="25"> But he added: ``If that (reunification) was worked out between the Germanys, I do not think we should view that as bad for Western interests''.</s>

<s docid="AP890925-0009" num="37" wdcount="27"> For his part, Gorbachev evaded the issue during a news conference in Bonn in June, saying only, ``the situation in Europe today was determined by historical realities''.</s>

<s docid="AP890925-0009" num="38" wdcount="13"> Outside Germany, political leaders and commentators have been sharply divided on the issue.</s>

<s docid="AP890925-0009" num="39" wdcount="26"> ``In thinking about the German Question, we ought not to be governed by old prejudices and out-of-date assumptions,'' wrote commentator Peter Jenkins in London's The Independent.</s>

<s docid="AP890925-0009" num="40" wdcount="39"> ``The Cold War was conducted in the name of freedom and, today, if the coming of freedom to East Germany brings a desire for unity which finds its echo in the Federal Republic, we ought not to be opposed''.</s>

<s docid="AP890925-0009" num="41" wdcount="36"> Willy Brandt, the Social Democrat who sought greater ties to the East as chancellor in the 1970s, said German unity doesn't necessarily mean a single state although he called reunification a ``hypothesis that cannot be excluded''.</s>

<s docid="AP890925-0009" num="42" wdcount="25"> As talk grows in the West, the positions against reunification almost seem to harden in East Germany, as people leave the country in near-record numbers.</s>

<s docid="AP890925-0009" num="43" wdcount="24"> More than 100,000 East Germans are expected to resettle in West Germany this year, leaving a gaping hole in the Communist nation's work force.</s>

<s docid="AP890925-0009" num="44" wdcount="21"> Little is likely to change in East Germany as long as the 77-year-old Honecker and his aging comrades stay in power.</s>

<s docid="AP890925-0009" num="45" wdcount="19"> During a September 1987 visit to Bonn, Honecker called respect for Europe's present borders a basic condition of peace.</s>

<s docid="AP890925-0009" num="46" wdcount="19"> ``Socialism and capitalism can't be any more united than fire and water,'' Honecker added on the issue of reunification.</s>

<s docid="AP890925-0009" num="47" wdcount="20"> There are virtually no indications that Honecker's successors will be inclined to democratic reforms, let alone joining the capitalist West.</s>

<s docid="AP890925-0009" num="48" wdcount="30"> The calls for reunification have already found a sympathetic ear among some leaders of the Polish Solidarity movement, in the country that suffered some of the Nazis' most brutal savagery.</s>

<s docid="AP890925-0009" num="49" wdcount="33"> ``After all, the abnormal situation of the German nation overshadows the whole of Polish-German relations,'' member of Parliament Adam Michnik wrote on Monday in the pro-Solidarity daily newspaper Gazeta Wyborcza, which he edits.</s>

<s docid="AP890925-0009" num="50" wdcount="31"> The renewed talk of reunification is recalling the nearly prophetic words of Reinhold Maier, a prominent West German state governor who later went on to head the centrist Free Democratic Party.</s>

<s docid="AP890925-0009" num="51" wdcount="10"> ``Reunification is resting in our midst like a sleeping lioness.</s>

<s docid="AP890925-0009" num="52" wdcount="19"> Tired and weak, indecisive people in West Germany are trying not to disturb her sleep,'' Maier predicted in 1955.</s>

<s docid="AP890925-0009" num="53" wdcount="16"> ``The lioness will one day wake up, blink, snap her her tail and start to roar''.</s>

<s docid="AP890925-0009" num="54" wdcount="33"> Still, many in both East and West still agree with the 1967 quip by Nobel Prize-winning French author Francois Mauriac: ``I love Germany so much, I'm delighted that there are two of them.''</s>
</TEXT>
</DOC>
