<DOC>
<DOCNO>

<s docid="AP900131-0068" num="1" wdcount="1"> AP900131-0068</s>
</DOCNO>
<FILEID>

<s docid="AP900131-0068" num="2" wdcount="2"> AP-NR-01-31-90 0930EST</s>
</FILEID>
<FIRST>

<s docid="AP900131-0068" num="3" wdcount="5"> r i PM-EastGermany 01-31 0584</s>
</FIRST>
<SECOND>

<s docid="AP900131-0068" num="4" wdcount="2"> PM-East Germany,0602</s>
</SECOND>
<HEAD>

<s docid="AP900131-0068" num="5" wdcount="7"> West Germans Praise Gorbachev's Comments on Reunification</s>
</HEAD>
<BYLINE>

<s docid="AP900131-0068" num="6" wdcount="3"> By TERRENCE PETTY</s>
</BYLINE>
<BYLINE>

<s docid="AP900131-0068" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900131-0068" num="8" wdcount="3"> EAST BERLIN (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900131-0068" num="9" wdcount="29"> West German officials and media today praised Soviet President Mikhail S. Gorbachev for softening his view on German reunification and said it could give hope to disheartened East Germans.</s>

<s docid="AP900131-0068" num="10" wdcount="33"> Disgraced former Communist Party leader Erich Honecker was released from prison Tuesday night after justice officials determined he was too frail to withstand the rigors of imprisonment while awaiting trial on treason charges.</s>

<s docid="AP900131-0068" num="11" wdcount="29"> Gorbachev said Tuesday in Moscow that he believed one Germany was likely in the future, but he added that Germans ``should not decide this important question on the streets''.</s>

<s docid="AP900131-0068" num="12" wdcount="15"> He referred to the growing number of demonstrations in East Germany in support of reunification.</s>

<s docid="AP900131-0068" num="13" wdcount="25"> Gorbachev's statement was his most tolerant yet on the subject of a single Germany, which has been opposed by Communists for more than 40 years.</s>

<s docid="AP900131-0068" num="14" wdcount="12"> East German Communists on Tuesday endorsed for reunification for the first time.</s>

<s docid="AP900131-0068" num="15" wdcount="24"> In West Germany, Foreign Minister Hans-Dietrich Genscher told West German Radio that Gorbachev had ``correctly analyzed'' the situation and again shown his political skill.</s>

<s docid="AP900131-0068" num="16" wdcount="29"> West German officials and media praised Gorbachev's view as ``realistic'' and described it as an important sign of hope for East Germans who have lost faith in their government.</s>

<s docid="AP900131-0068" num="17" wdcount="28"> Communist leaders launched their uphill campaign for March 18 parliamentary elections with a news conference to unveil their ``European concept'' that aims for a united and demilitarized Europe.</s>

<s docid="AP900131-0068" num="18" wdcount="23"> Party ideologist Peter Brie said the Communists support ``the togetherness of the German nation,'' and urged a thoughtful and measured approach to reunification.</s>

<s docid="AP900131-0068" num="19" wdcount="22"> In an interview with the West German Bild newspaper, party leader Gregor Gysi complained that the reunification drive is moving too quickly.</s>

<s docid="AP900131-0068" num="20" wdcount="14"> Asked if the Communists oppose reunification, Gysi told the newspaper: ``No, not at all.</s>

<s docid="AP900131-0068" num="21" wdcount="7"> This process cannot be stopped any more.</s>

<s docid="AP900131-0068" num="22" wdcount="18"> But it is irresponsible to do things in such a way now as if it were possible tomorrow''.</s>

<s docid="AP900131-0068" num="23" wdcount="20"> The reunification issue promises to dominate the election campaign that will seat a new leadership in less than seven weeks.</s>

<s docid="AP900131-0068" num="24" wdcount="28"> Increasing numbers of East Germans have demonstrated for union with wealthy and prosperous West Germany as their own economy tumbles and an exodus of skilled workers continues unchecked.</s>

<s docid="AP900131-0068" num="25" wdcount="19"> More than 340,000 people fled East Germany last year, having lost hope that their spartan living conditions would improve.</s>

<s docid="AP900131-0068" num="26" wdcount="14"> The devastating flight has included as many as 2,500 people daily since Jan. 1.</s>

<s docid="AP900131-0068" num="27" wdcount="36"> The Communists are widely distrusted because of corruption scandals that have surfaced since the peaceful pro-democracy revolt last fall, and because they carry the blame for leading East Germany into its current economic and political crises.</s>

<s docid="AP900131-0068" num="28" wdcount="31"> The man most blamed for the country's problems, Honecker, was set free after an East Berlin court rejected a request that he be kept in prison until his trial in March.</s>

<s docid="AP900131-0068" num="29" wdcount="4"> He was jailed Monday.</s>

<s docid="AP900131-0068" num="30" wdcount="28"> The court decided that ``despite the severity of the charges against Honecker, the state of the accused's health does not permit imprisonment,'' the official ADN news agency reported.</s>

<s docid="AP900131-0068" num="31" wdcount="15"> A spokesman for Chief Prosecutor Hans-Juergen Joseph promised that the investigation against Honecker would proceed.</s>

<s docid="AP900131-0068" num="32" wdcount="14"> ADN said the court acted on advice from two doctors who examined Honecker independently.</s>

<s docid="AP900131-0068" num="33" wdcount="13"> Honecker, 77, underwent surgery on Jan. 8 to remove a malignant kidney tumor.</s>

<s docid="AP900131-0068" num="34" wdcount="13"> Honecker was ousted from the leadership on Oct. 18, after massive pro-democracy demonstrations.</s>

<s docid="AP900131-0068" num="35" wdcount="21"> He was expelled from the Communist Party in December and has since been accused of treason and abusing his power .</s>
</TEXT>
</DOC>
