<DOC>
<DOCNO>

<s docid="AP900214-0157" num="1" wdcount="1"> AP900214-0157</s>
</DOCNO>
<FILEID>

<s docid="AP900214-0157" num="2" wdcount="2"> AP-NR-02-14-90 1927EST</s>
</FILEID>
<FIRST>

<s docid="AP900214-0157" num="3" wdcount="5"> r w AM-Germany-Holocaust 02-14 0385</s>
</FIRST>
<SECOND>

<s docid="AP900214-0157" num="4" wdcount="1"> AM-Germany-Holocaust,360</s>
</SECOND>
<HEAD>

<s docid="AP900214-0157" num="5" wdcount="8"> Jewish Leader Seeks to Discuss Reunification with Germans</s>
</HEAD>
<HEAD>

<s docid="AP900214-0157" num="6" wdcount="5"> With AM-The German Question, Bjt</s>
</HEAD>
<DATELINE>

<s docid="AP900214-0157" num="7" wdcount="2"> WASHINGTON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900214-0157" num="8" wdcount="35"> The chairman of the Simon Wisenthal Center has asked to meet with the leaders of West and East Germany to discuss ``the great fear that German reunification brings to the community of victims of Nazism''.</s>

<s docid="AP900214-0157" num="9" wdcount="37"> ``I must tell you I am not among those in the cheering section applauding the rush towards German reunification,'' Rabbi Marvin Hier wrote Chancellor Helmut Kohl of West Germany and Prime Minister Hans Modrow of East Germany.</s>

<s docid="AP900214-0157" num="10" wdcount="18"> ``However, if that is the inevitable course, let us at least place on record our concerns,'' he said.</s>

<s docid="AP900214-0157" num="11" wdcount="29"> Hier is the founder of the center, headquartered in Los Angeles, which seeks to keep alive the memory of the Nazi persecution of Jews in Germany and Nazi-conquered lands.</s>

<s docid="AP900214-0157" num="12" wdcount="23"> In nearly identical letters, he asked to meet with Kohl during his forthcoming trip to Washington and with Modrow in Germany next month.</s>

<s docid="AP900214-0157" num="13" wdcount="10"> The letters were made available Wednsday to The Associated Press.</s>

<s docid="AP900214-0157" num="14" wdcount="23"> ``You are undoubtedly aware,'' he wrote both leaders, ``of the great fear that German reunification brings to the community of victims of Nazism''.</s>

<s docid="AP900214-0157" num="15" wdcount="31"> ``It is not an irrational fear of the kind that one explains away as the nightmares of victims who remain locked into their past and lose all perspective of present reality.</s>

<s docid="AP900214-0157" num="16" wdcount="30"> ``The fears are real because those who bear the scars of the last `unified Germany' do not see their concerns being addressed in the current reunification discussions betwen world leaders''.</s>

<s docid="AP900214-0157" num="17" wdcount="8"> Hier listed 10 points he wanted to raise.</s>

<s docid="AP900214-0157" num="18" wdcount="123"> Among them were a program to teach German schoolchildren about the annhilation of the Jews; the creation of an agency to monitor and prosecute hate groups; the continuation of the ``special relationship'' now existing between West Germany and Israel; the convening of a 1992 conference of world leaders on the 50th anniversary of the conference at which ``the final solution'' was developed; the establisment of a German commission to protect Holocaust sites; the banning of terrorist organizations that ``have enjoyed respectablity in East Germany;'' a cultural exchange program between German and Jewish organizations; German television and radio programs on the reconciliation; restitution payments to the families and victims of Nazism, and a German commitment to revitalize former synagogues in East German territory .</s>
</TEXT>
</DOC>
