<DOC>
<DOCNO>

<s docid="AP900130-0202" num="1" wdcount="1"> AP900130-0202</s>
</DOCNO>
<FILEID>

<s docid="AP900130-0202" num="2" wdcount="2"> AP-NR-01-30-90 2203EST</s>
</FILEID>
<FIRST>

<s docid="AP900130-0202" num="3" wdcount="7"> u i AM-Soviet-Germany 1stLd-Writethru a0634 01-30 0637</s>
</FIRST>
<SECOND>

<s docid="AP900130-0202" num="4" wdcount="4"> AM-Soviet-Germany, 1st Ld-Writethru, a0634,0655</s>
</SECOND>
<HEAD>

<s docid="AP900130-0202" num="5" wdcount="7"> Gorbachev Leaves Door Open to German Reunification</s>
</HEAD>
<NOTE>

<s docid="AP900130-0202" num="6" wdcount="10"> Eds: INSERT 3 grafs after 17th graf, According to ...</s>

<s docid="AP900130-0202" num="7" wdcount="4"> UPDATING with Lambsdorff remarks.</s>

<s docid="AP900130-0202" num="8" wdcount="6"> Picks up 18th, `Modrow invited.. .</s>
</NOTE>
<HEAD>

<s docid="AP900130-0202" num="9" wdcount="4"> With AM-East Germany, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP900130-0202" num="10" wdcount="3"> By ANDREW KATELL</s>
</BYLINE>
<BYLINE>

<s docid="AP900130-0202" num="11" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900130-0202" num="12" wdcount="2"> MOSCOW (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900130-0202" num="13" wdcount="22"> President Mikhail S. Gorbachev met Tuesday with East German Premier Hans Modrow and appeared to be more open toward eventual German reunification.</s>

<s docid="AP900130-0202" num="14" wdcount="33"> Modrow told reporters after the meeting that Gorbachev ``did not rule out such a prospect in the future, and at the same time did not venture to set some time limits for that''.</s>

<s docid="AP900130-0202" num="15" wdcount="20"> Earlier, the Kremlin chief said any such decisions must include the four Allied powers and take into account European opinions.</s>

<s docid="AP900130-0202" num="16" wdcount="36"> ``The development of events in the world, in East Germany, in the Soviet Union demand deep consideration and an analytical approach to deciding this problem,'' he said in remarks reported by the official news agency Tass.</s>

<s docid="AP900130-0202" num="17" wdcount="12"> ``Time itself is acting on this process, giving it dynamism,'' Gorbachev said.</s>

<s docid="AP900130-0202" num="18" wdcount="14"> ``We have to act responsibly and not decide this important question on the streets''.</s>

<s docid="AP900130-0202" num="19" wdcount="19"> Tass said Gorbachev emphasized that talks about restructuring relations between the two Germanys must involve ``all directly interested governments''.</s>

<s docid="AP900130-0202" num="20" wdcount="31"> Asked by an East German correspondent about his attitude toward reunification, Gorbachev said the question was not unexpected and that ``no one can cast doubt'' on the reasonableness of asking it.</s>

<s docid="AP900130-0202" num="21" wdcount="17"> However, the English-language Tass translation indicated Gorbachev could have meant there were no doubts about reunification itself.</s>

<s docid="AP900130-0202" num="22" wdcount="14"> Gorbachev's position was similar to that adopted by Communists in East Berlin on Tuesday.</s>

<s docid="AP900130-0202" num="23" wdcount="27"> For the first time, the Communists acknowledged German unity as a long-term goal but said it must be imbedded in the process of overcoming Europe's overall divisions.</s>

<s docid="AP900130-0202" num="24" wdcount="30"> The Soviet Union traditionally has strongly opposed any talk of German reunification, but Gorbachev has softened that position in adopting a policy that has allowed radical reform in Eastern Europe.</s>

<s docid="AP900130-0202" num="25" wdcount="14"> Soviets say the question of German reunification is to be decided in the future.</s>

<s docid="AP900130-0202" num="26" wdcount="36"> Gorbachev, in comments to reporters after meeting French President Francois Mitterrand in Kiev in December, reiterated his view that the existence of two German states is a fact based on the outcome of World War II.</s>

<s docid="AP900130-0202" num="27" wdcount="20"> But he added, ``The present situation is the result of specific historical events, a specific historical process on this continent.</s>

<s docid="AP900130-0202" num="28" wdcount="9"> So, history should decide the future of this continent''.</s>

<s docid="AP900130-0202" num="29" wdcount="9"> ``I don't think it is a topical question today.</s>

<s docid="AP900130-0202" num="30" wdcount="24"> A different approach may create a situation that would complicate the entire European process, including the relations between the two German states,'' Gorbachev said.</s>

<s docid="AP900130-0202" num="31" wdcount="15"> Modrow said the two Germanys could work toward confederation in phases with no time limit.</s>

<s docid="AP900130-0202" num="32" wdcount="22"> He said he agreed with Gorbachev that reunification must be decided not only by East and West Germany, but all of Europe.</s>

<s docid="AP900130-0202" num="33" wdcount="41"> According to Tass, the Soviet leader said any action on reunification must not infringe on the interests of either East or West Germany, the four Allied powers: France, Britain, the United States or the Soviet Union, or anyone else in Europe.</s>

<s docid="AP900130-0202" num="34" wdcount="31"> Count Otto Lambsdorff, head of West Germany's Free Democratic Party, a partner in the governing coalition, said Tuesday in London that Gorbachev has adopted ``a more positive attitude'' toward German reunification.</s>

<s docid="AP900130-0202" num="35" wdcount="27"> In a TV interview on Britain's Channel 4, he also urged ``economic union'' within 18 months as a prelude to full union of West and East Germany.</s>

<s docid="AP900130-0202" num="36" wdcount="18"> Lambsdorff said that because of East Germany's political instability it had only two choices _ unification or chaos.</s>

<s docid="AP900130-0202" num="37" wdcount="17"> Modrow invited Gorbachev and Premier Nikolai I. Ryzhkov to visit East Germany and they accepted, Tass reported.</s>

<s docid="AP900130-0202" num="38" wdcount="6"> Modrow arrived in Moscow late Monday.</s>

<s docid="AP900130-0202" num="39" wdcount="29"> A Communist, he has moved forward the country's first free elections from May to March 18 and brought the opposition into a coalition that will govern until then .</s>
</TEXT>
</DOC>
