<DOC>
<DOCNO>

<s docid="AP900215-0013" num="1" wdcount="1"> AP900215-0013</s>
</DOCNO>
<FILEID>

<s docid="AP900215-0013" num="2" wdcount="2"> AP-NR-02-15-90 0229EST</s>
</FILEID>
<FIRST>

<s docid="AP900215-0013" num="3" wdcount="6"> r w PM-TheGermanQuestion Bjt 02-15 0800</s>
</FIRST>
<SECOND>

<s docid="AP900215-0013" num="4" wdcount="4"> PM-The German Question, Bjt,790</s>
</SECOND>
<HEAD>

<s docid="AP900215-0013" num="5" wdcount="10"> A Single Germany: No Fear of Jackboots, But Worries Nonetheless</s>
</HEAD>
<BYLINE>

<s docid="AP900215-0013" num="6" wdcount="3"> By MIKE FEINSILBER</s>
</BYLINE>
<BYLINE>

<s docid="AP900215-0013" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900215-0013" num="8" wdcount="2"> WASHINGTON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900215-0013" num="9" wdcount="37"> Historians say the world need not fear that German jackboots will echo again on European pavements, but some still see the rush toward German reunification as a setback _ a step away from the integration of Europe.</s>

<s docid="AP900215-0013" num="10" wdcount="24"> For the most part, the historians say an East Germany collapsing into chaos represents a greater threat to stability than a united German state.</s>

<s docid="AP900215-0013" num="11" wdcount="33"> ``The West Germans are moving ahead not out of nationalistic fervor, but a perceived need to deal with a crisis,'' said Henry Ashby Turner of Yale, author of ``The Two Germanies Since 1945''.</s>

<s docid="AP900215-0013" num="12" wdcount="12"> ``There is no such a thing as indelible national character,'' Turner said.</s>

<s docid="AP900215-0013" num="13" wdcount="33"> ``I don't think there is any chance that the young men of Germany are going to slip out of their Adidas running shoes and pull on jackboots and start running around saying, `Heil''!</s>

<s docid="AP900215-0013" num="14" wdcount="48"> He was one of several experts in German history discussing the implications of reunification following the decision Tuesday by the four World War II allies _ the United States, Britain, France and the Soviet Union _ to accept the reunification of a Germany they divided 45 years ago.</s>

<s docid="AP900215-0013" num="15" wdcount="54"> University of Chicago historian Michael Geyer, a native of Germany, said he feared the creation of a ``strong, sovereign nation in the center of Europe'' could reverse a more important development _ the 40-year drive toward an integrated Europe in which industries, banks, trade unions and even government ministries have been collaborating across borders.</s>

<s docid="AP900215-0013" num="16" wdcount="8"> ``The East German state is collapsing,'' said Geyer.</s>

<s docid="AP900215-0013" num="17" wdcount="7"> ``So something has to happen very dramatically.</s>

<s docid="AP900215-0013" num="18" wdcount="12"> But they have a choice _ the Europeans and Germans and Americans.</s>

<s docid="AP900215-0013" num="19" wdcount="23"> Do they want to opt for the European card or for the German card? I think they are opting for the German card''.</s>

<s docid="AP900215-0013" num="20" wdcount="16"> ``I hear these days very little about what Gorbachev called `the house of Europe,''' he said.</s>

<s docid="AP900215-0013" num="21" wdcount="21"> The result of a dominant ``uncomfortably strong'' German state, Geyer added, could be a setback to the diminishment of national borders.</s>

<s docid="AP900215-0013" num="22" wdcount="20"> It could also mean, he said, that American troops might have to stay in Europe as a counterweight to Germany.</s>

<s docid="AP900215-0013" num="23" wdcount="28"> ``If I had my druthers reunifications would have happened after 1992, after the integration of the West German economy into the economy of Western Europe,'' said Charles J.</s>

<s docid="AP900215-0013" num="24" wdcount="8"> Herber of George Washington University, expressing similar concern.</s>

<s docid="AP900215-0013" num="25" wdcount="12"> ``Then there would have been fewer chances for German adventurers,'' he said.</s>

<s docid="AP900215-0013" num="26" wdcount="26"> West Germans were aware of their European neighbors' misgivings, said Richard Breitman of American University, and so they presented reunification within the context of European integration.</s>

<s docid="AP900215-0013" num="27" wdcount="13"> They wanted to avoid arousing fear of a united Germany again dominating Europe.</s>

<s docid="AP900215-0013" num="28" wdcount="16"> ``Even if the history did not exist, there would be fears of that kind,'' he said.</s>

<s docid="AP900215-0013" num="29" wdcount="14"> ``We're dealing not just with rational calculation but a whole host of emotional memories''.</s>

<s docid="AP900215-0013" num="30" wdcount="36"> For all that, Breitman said, ``One Germany is not only inevitable, but given the successful record of West Germany over the last 40 years, my feeling is it is better than having a regime in chaos''.</s>

<s docid="AP900215-0013" num="31" wdcount="20"> ``The only alternative to reunification,'' added Turner, is an East Germany in ruins, ``a basket case, a Bangladesh of Europe''.</s>

<s docid="AP900215-0013" num="32" wdcount="10"> He said Germans have ``no significant interest in territorial revisions.</s>

<s docid="AP900215-0013" num="33" wdcount="4"> Those misgivings are misplaced''.</s>

<s docid="AP900215-0013" num="34" wdcount="24"> Gerhard Weinberg of the University of North Carolina, considered a leading historian of the Nazi era, cautioned that reunification, if mishandled, could prove explosive.</s>

<s docid="AP900215-0013" num="35" wdcount="35"> While the people of West Europe have gotten over nationalistic distrusts, East Europeans, living in closed societies, have not, he said, and fear of Germany is a reality in East Europe and Russia, he said.</s>

<s docid="AP900215-0013" num="36" wdcount="35"> ``I don't think the Germans are heading for Moscow again, but we have to give people _ and the Germans have to give people _ time to think this through and get used to it.</s>

<s docid="AP900215-0013" num="37" wdcount="25"> ... Mishandled, reunification could scare one or the other of the participants into starting something and scare others and goodness knows where it would end''.</s>

<s docid="AP900215-0013" num="38" wdcount="34"> Gordon Craig, emeritus professor at Stanford, said the division of Germany has been the basis of a peace settlement ``which worked pretty well'' but was ``abnormal and sooner or later had to be corrected''.</s>

<s docid="AP900215-0013" num="39" wdcount="24"> German reunification, said Craig, gives the world the chance to build a new international system, one that ``will prevent the use of international violence''.</s>

<s docid="AP900215-0013" num="40" wdcount="63"> He added, ``We have to be careful that we don't fall back into the kind of system that existed before the Second World War, a Europe filled with nations that were suffering various grievances, rivalries, disputed frontiers, driven by what they considered to be legitimate reasons but pitted against each other _ the sort of things that gave rise to Hitler in 1933.''</s>
</TEXT>
</DOC>
