<DOC>
<DOCNO>

<s docid="AP900321-0057" num="1" wdcount="1"> AP900321-0057</s>
</DOCNO>
<FILEID>

<s docid="AP900321-0057" num="2" wdcount="2"> AP-NR-03-21-90 0648EST</s>
</FILEID>
<FIRST>

<s docid="AP900321-0057" num="3" wdcount="5"> r a PM-Jews-Reunification 03-21 0347</s>
</FIRST>
<SECOND>

<s docid="AP900321-0057" num="4" wdcount="1"> PM-Jews-Reunification,0356</s>
</SECOND>
<HEAD>

<s docid="AP900321-0057" num="5" wdcount="9"> Jewish Leaders To Meet in Berlin on German Reunification</s>
</HEAD>
<BYLINE>

<s docid="AP900321-0057" num="6" wdcount="3"> By CATHERINE CROCKER</s>
</BYLINE>
<BYLINE>

<s docid="AP900321-0057" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900321-0057" num="8" wdcount="3"> NEW YORK (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900321-0057" num="9" wdcount="30"> The Berlin villa where the Nazi leadership met to implement the ``final solution'' against Europe's Jewish population will be the site of a World Jewish Congress conference on German reunification.</s>

<s docid="AP900321-0057" num="10" wdcount="20"> The New York-based organization announced Tuesday that the meeting is scheduled for May 8, the 45th anniversary of V-E Day.</s>

<s docid="AP900321-0057" num="11" wdcount="19"> ``The world is expecting a Jewish statement on reunification,'' said Edgar Bronfman, the president of the World Jewish Congress.</s>

<s docid="AP900321-0057" num="12" wdcount="35"> ``I think that the place where they decided on the `final solution' is the right place to have such a meeting, and the anniversary of the victory in Europe seems to be the right day''.</s>

<s docid="AP900321-0057" num="13" wdcount="40"> Some 100 members of the World Jewish Congress from about 70 countries will attend the conference at the villa in Wannsee, Berlin, where on Jan. 20, 1942, high German government and party officials adopted a plan to exterminate the Jews.</s>

<s docid="AP900321-0057" num="14" wdcount="19"> ``Jews have a right to state a moral position on German reunification and we will make a moral statement.</s>

<s docid="AP900321-0057" num="15" wdcount="18"> And part of that moral statement is to see that it (the Holocaust) doesn't happen again,'' Bronfman said.</s>

<s docid="AP900321-0057" num="16" wdcount="29"> In the long run, he said, a united Germany can be ``a very positive thing'' for Europe, but certain precautions must be taken to prevent a repeat of history.</s>

<s docid="AP900321-0057" num="17" wdcount="20"> For example, Germany's borders ``must be sealed in cement,'' and the country should not be allowed nuclear weapons, he said.</s>

<s docid="AP900321-0057" num="18" wdcount="16"> Bronfman said he does not fear a resurgence of anti-Semitism once the two Germanys are united.</s>

<s docid="AP900321-0057" num="19" wdcount="12"> In fact, he said, reunification might cause a decline in anti-Jewish feelings.</s>

<s docid="AP900321-0057" num="20" wdcount="21"> ``Now that reunification is about to be a fact, they won't be blaming the Jews'' for a divided Germany, Bronfman explained.</s>

<s docid="AP900321-0057" num="21" wdcount="18"> The conference will convene May 6 and a formal declaration on German reunification will be issued May 8.</s>

<s docid="AP900321-0057" num="22" wdcount="29"> It will be the first meeting ever held on German soil by the World Jewish Congress, which was founded in 1936 in response to Hitler's threats against Jews .</s>
</TEXT>
</DOC>
