<DOC>
<DOCNO>

<s docid="AP900210-0106" num="1" wdcount="1"> AP900210-0106</s>
</DOCNO>
<FILEID>

<s docid="AP900210-0106" num="2" wdcount="2"> AP-NR-02-10-90 1607EST</s>
</FILEID>
<FIRST>

<s docid="AP900210-0106" num="3" wdcount="5"> r i AM-EastGermany 02-10 0419</s>
</FIRST>
<SECOND>

<s docid="AP900210-0106" num="4" wdcount="2"> AM-East Germany,0434</s>
</SECOND>
<HEAD>

<s docid="AP900210-0106" num="5" wdcount="4"> Thousands Demonstrate for Unification</s>
</HEAD>
<HEAD>

<s docid="AP900210-0106" num="6" wdcount="3"> With AM-Germany-Soviet, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP900210-0106" num="7" wdcount="3"> By NESHA STARCEVIC</s>
</BYLINE>
<BYLINE>

<s docid="AP900210-0106" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900210-0106" num="9" wdcount="3"> WEST BERLIN (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900210-0106" num="10" wdcount="23"> About 20,000 East Germans, many carrying West German flags, demonstrated Saturday for speedy German reunification, the official East German news agency ADN said.</s>

<s docid="AP900210-0106" num="11" wdcount="34"> As the demonstrators rallied in the southern city of Plauen, West German Chancellor Helmut Kohl said in Moscow that Soviet President Mikhail S. Gorbachev had given him an unequivocal promise to respect German reunification.</s>

<s docid="AP900210-0106" num="12" wdcount="9"> Kohl declared it a ``very good day for Germany''.</s>

<s docid="AP900210-0106" num="13" wdcount="38"> Kohl and Foreign Minister Hans-Dietrich Genscher also disclosed that they expect a reunification plan with agreement of the World War II Allies to be ready before the end of the year for presentation to a pan-European summit meeting.</s>

<s docid="AP900210-0106" num="14" wdcount="26"> Calls for German reunification have increased since the ouster of the hard-line Communist leadership and the opening of East Germany's borders during the fall pro-democracy movement.</s>

<s docid="AP900210-0106" num="15" wdcount="26"> Despite reforms, nearly 2,000 East Germans, most of them skilled workers, continue to leave their homeland daily, crippling an economy already troubled by strikes and absenteeism.</s>

<s docid="AP900210-0106" num="16" wdcount="31"> Earlier Saturday, West German Finance Minister Theo Waigel said the East German economy was in a ``sorrowful state'' and urged the East German government to release details on its financial situation.</s>

<s docid="AP900210-0106" num="17" wdcount="20"> Waigel's comments came after a day after a high-ranking official in Bonn warned that East Germany is rapidly approaching insolvency.</s>

<s docid="AP900210-0106" num="18" wdcount="12"> ``Things are escalating,'' Waigel said in an interview with West Berlin radio.</s>

<s docid="AP900210-0106" num="19" wdcount="7"> ``The economy is in a sorrowful state.</s>

<s docid="AP900210-0106" num="20" wdcount="5"> The political authority is crumbling''.</s>

<s docid="AP900210-0106" num="21" wdcount="14"> He said the Bonn government believes East Germany's foreign debt stands at $18 billion.</s>

<s docid="AP900210-0106" num="22" wdcount="30"> ``If the situation has changed, the East German government must say so,'' said Waigel, a conservative who has been pushing for establishment of a common currency for the two states.</s>

<s docid="AP900210-0106" num="23" wdcount="28"> Also Saturday, more than 100 East Germans protested in front of the Soviet Embassy in East Berlin against the stationing of Soviet helicopters in their country, ADN said.</s>

<s docid="AP900210-0106" num="24" wdcount="16"> ADN said the demonstrators held signs saying ``Gorbi, what about disarmament''? and ``Tanks out, helicopters in''?</s>

<s docid="AP900210-0106" num="25" wdcount="36"> The protesters, from the East German town of Prenzlau, claimed the Soviets had backed out of disarmament plans by replacing a tank unit that had been stationed at a military base there with helicopters, ADN reported.</s>

<s docid="AP900210-0106" num="26" wdcount="29"> According to ADN, the demonstrators, who came from church and citizens' groups as well as from the town council, issued a statement calling for civilian use of the base.</s>

<s docid="AP900210-0106" num="27" wdcount="14"> Prenzlau, a town of 22,000, is located about 50 miles north of Berlin .</s>
</TEXT>
</DOC>
