<DOC>
<DOCNO>

<s docid="FT923-6509" num="1" wdcount="1"> FT923-6509</s>
</DOCNO>
<PROFILE>

<s docid="FT923-6509" num="2" wdcount="1"> _AN-CHZBBACDFT</s>
</PROFILE>
<DATE>

<s docid="FT923-6509" num="3" wdcount="1"> 920824</s>
</DATE>
<HEADLINE>

<s docid="FT923-6509" num="4" wdcount="13"> FT 24 AUG 92 / Letter: The Bundesbank is led to the dock</s>
</HEADLINE>
<BYLINE>

<s docid="FT923-6509" num="5" wdcount="4"> From Mr HOWARD FLIGHT</s>
</BYLINE>
<TEXT>

<s docid="FT923-6509" num="6" wdcount="33"> Sir, The argument for an independent central bank is that it should be free of party political interference, not that it should conduct monetary policy without regard to national, regional or global interests.</s>

<s docid="FT923-6509" num="7" wdcount="22"> Whatever policy the Kohl government followed over reunification, it was bound to unleash a large federal deficit and inflationary pressures in Germany.</s>

<s docid="FT923-6509" num="8" wdcount="50"> As the western German population is now aware, German reunification needs a strong, growing west German economy to finance the subsidisation of eastern Germans' living standards until there is a sustained upswing in the east - even if at the cost of higher German inflation than the Bundesbank would wish.</s>

<s docid="FT923-6509" num="9" wdcount="16"> In Europe as a whole, very high real interest rates threaten to turn recession into depression.</s>

<s docid="FT923-6509" num="10" wdcount="27"> The governments of Europe have been remarkably patient with the Bundesbank, although it is threatening nearly 10 years of European effort for greater economic and political integration.</s>

<s docid="FT923-6509" num="11" wdcount="13"> Surely there must be compromise of some economic habits to achieve the latter?</s>

<s docid="FT923-6509" num="12" wdcount="32"> It is ironic that, just when German reunification presented a short-term reason for Germany to shift its anti-inflationary economic and monetary priorities, accommodating European convergence, Bundesbank intransigence is threatening the EMU commitment.</s>

<s docid="FT923-6509" num="13" wdcount="9"> Beyond Europe, the dominant economic forces are strongly disinflationary.</s>

<s docid="FT923-6509" num="14" wdcount="21"> But Germany is the one economy which, for reasons of reunification, could afford a more relaxed stand on the inflationary front.</s>

<s docid="FT923-6509" num="15" wdcount="20"> Yet Mr Otmar Issing, the Bundesbank's chief economist, advises there are no grounds for a cut in Germany's interest rates.</s>

<s docid="FT923-6509" num="16" wdcount="9"> This, despite the unreliability of German money supply data.</s>

<s docid="FT923-6509" num="17" wdcount="37"> The German government might point out to the Bundesbank that monetary targets might be achievable only at the cost of many more than 3m unemployed in Germany, of the destruction of the EMU programme and global depression.</s>

<s docid="FT923-6509" num="18" wdcount="15"> A DM exchange rate adjustment within the ERM is not the answer to the problems.</s>

<s docid="FT923-6509" num="19" wdcount="8"> We need a prolonged low-interest-rate German reunification boom.</s>

<s docid="FT923-6509" num="20" wdcount="19"> The European currency bloc is overvalued against the dollar and yen as a result of Bundesbank interest rate policies.</s>

<s docid="FT923-6509" num="21" wdcount="5"> And this is aggravating recession.</s>

<s docid="FT923-6509" num="22" wdcount="25"> A future European-wide central bank must clearly - like the US Federal Reserve - be more accountable in the broader European political and economic interest.</s>

<s docid="FT923-6509" num="23" wdcount="34"> The governments and central banks of Europe and the G7 block - including the Kohl administration - should pressurise the Bundesbank, and be prepared to consider constitutional changes if necessary, to halt this idiocy.</s>

<s docid="FT923-6509" num="24" wdcount="19"> Howard Flight, managing director, Guinness Flight Global Asset Management, Lighterman's Court, 5 Gainsford Street, Tower Bridge, London SE1 2NE</s>
</TEXT>
<PUB>

<s docid="FT923-6509" num="25" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT923-6509" num="26" wdcount="3"> London Page 11</s>
</PAGE>
</DOC>
