<DOC>
<DOCNO>

<s docid="LA021290-0043" num="1" wdcount="1"> LA021290-0043</s>
</DOCNO>
<DOCID>

<s docid="LA021290-0043" num="2" wdcount="1"> 175174</s>
</DOCID>
<DATE>
<P>

<s docid="LA021290-0043" num="3" wdcount="6"> February 12, 1990, Monday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA021290-0043" num="4" wdcount="8"> Part A; Page 5; Column 1; Foreign Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA021290-0043" num="5" wdcount="2"> 461 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA021290-0043" num="6" wdcount="8"> 'WAY IS FREE' FOR GERMAN REUNIFICATION, KOHL SAYS</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA021290-0043" num="7" wdcount="6"> By WILLIAM TUOHY, TIMES STAFF WRITER</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA021290-0043" num="8" wdcount="1"> BONN</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA021290-0043" num="9" wdcount="23"> West German Chancellor Helmut Kohl declared on his return from Moscow on Sunday that "the way is now free" for German reunification .</s>
</P>
<P>

<s docid="LA021290-0043" num="10" wdcount="36"> His meeting with Soviet President Mikhail S. Gorbachev convinced him, he told West German radio, that the two German states should "enter into negotiations as quickly as possible" after the March 18 East German election .</s>
</P>
<P>

<s docid="LA021290-0043" num="11" wdcount="37"> Kohl will meet with East German Prime Minister Hans Modrow on Tuesday and Wednesday in Bonn to discuss immediate steps in economic cooperation, including monetary union, to prevent the collapse of the faltering East German economy .</s>
</P>
<P>

<s docid="LA021290-0043" num="12" wdcount="11"> "Political and economic union go hand in hand," Kohl said .</s>
</P>
<P>

<s docid="LA021290-0043" num="13" wdcount="35"> He said that immediate steps must be taken on the economic front to "stop the hemorrhage of East Germans to the Federal Republic and keep them in their heimat," or home, in East Germany .</s>
</P>
<P>

<s docid="LA021290-0043" num="14" wdcount="45"> Kohl said that his talks with Gorbachev -- who told him that reunification is a matter for the Germans themselves to decide -- could lead to an "economic breakthrough" in East Germany, which in turn could provide a "push forward" for all of Europe .</s>
</P>
<P>

<s docid="LA021290-0043" num="15" wdcount="29"> Asked how soon the two Germanys could merge, Kohl declared that the March election has to come first, and "then I think it will all go very quickly" .</s>
</P>
<P>

<s docid="LA021290-0043" num="16" wdcount="19"> The chancellor said that almost all of the political parties and opposition groups in East Germany now support reunification.</s>

<s docid="LA021290-0043" num="17" wdcount="17"> And after the election, he said, "they will want to put their programs into practice quickly" .</s>
</P>
<P>

<s docid="LA021290-0043" num="18" wdcount="31"> Gorbachev inquired about plans by West German politicians to campaign in East Germany, Kohl said, adding that the Soviet leader did not appear to be upset about such political activity .</s>
</P>
<P>

<s docid="LA021290-0043" num="19" wdcount="34"> West Germany's Social Democratic Party is expected to campaign heavily in East Germany in support of a fledging branch of the party that has taken a surprisingly strong lead in public opinion polls .</s>
</P>
<P>

<s docid="LA021290-0043" num="20" wdcount="25"> Major members of the party, including former Chancellor Willy Brandt, are scheduled to appear at rallies on behalf of the East German Social Democrats .</s>
</P>
<P>

<s docid="LA021290-0043" num="21" wdcount="28"> With the surge of the East German Social Democrats, political analysts are pointing to the strange role they could play in the ultimate political fate of Kohl .</s>
</P>
<P>

<s docid="LA021290-0043" num="22" wdcount="43"> Ever since reunification became a blazing issue, Kohl's standing in West German opinion polls has risen, and if the national elections, now scheduled for December, were held today, he would have a good chance of leading his Christian Democratic Union to victory .</s>
</P>
<P>

<s docid="LA021290-0043" num="23" wdcount="56"> But if the two Germanys are fused before the West Germany election in December, the growing number of Social Democratic voters in what today is East Germany -- who would presumably be allowed to vote in December -- could easily tip the balance away from the Christian Democrats, pushing Kohl out of the government leadership .</s>
</P>
</TEXT>
<SUBJECT>
<P>

<s docid="LA021290-0043" num="24" wdcount="21"> KOHL, HELMUT; REUNIFICATION; EAST GERMANY -- FOREIGN RELATIONS -- WEST GERMANY; USSR -- FOREIGN RELATIONS -- WEST GERMANY; GORBACHEV, MIKHAIL S</s>
</P>
</SUBJECT>
</DOC>
