<DOC>
<DOCNO>

<s docid="WSJ890922-0113" num="1" wdcount="1"> WSJ890922-0113</s>
</DOCNO>
<DD>

<s docid="WSJ890922-0113" num="2" wdcount="2"> = 890922</s>
</DD>
<AN>

<s docid="WSJ890922-0113" num="3" wdcount="2"> 890922-0113 .</s>
</AN>
<HL>

<s docid="WSJ890922-0113" num="4" wdcount="26"> East German Exodus Sparks Discussion @ On the Possibility of Reuniting Germany @ ---- @ By Terence Roth @ Staff Reporter of The Wall Street Journal</s>
</HL>
<DD>

<s docid="WSJ890922-0113" num="5" wdcount="1"> 09/22/89</s>
</DD>
<SO>

<s docid="WSJ890922-0113" num="6" wdcount="4"> WALL STREET JOURNAL (J)</s>
</SO>
<CO>

<s docid="WSJ890922-0113" num="7" wdcount="2"> EUROP FREST</s>
</CO>
<DATELINE>

<s docid="WSJ890922-0113" num="8" wdcount="3"> FRANKFURT, West Germany</s>
</DATELINE>
<TEXT>

<s docid="WSJ890922-0113" num="9" wdcount="30"> The mass emigration of thousands of disaffected East Germans has rekindled reunification talk in West Germany, where some legislators plan to begin exploring the possiblity of reuniting the two Germanys.</s>

<s docid="WSJ890922-0113" num="10" wdcount="10"> No one is predicting a date for a possible reunification.</s>

<s docid="WSJ890922-0113" num="11" wdcount="25"> Proponents acknowledge the risks of assuming too much of East Bloc reform trends, and most hedge their thoughts with careful references to Washington and Moscow.</s>

<s docid="WSJ890922-0113" num="12" wdcount="19"> Yet growing signs of ferment in East Germany have given Chancellor Helmut Kohl's government reason to consider the possibilities.</s>

<s docid="WSJ890922-0113" num="13" wdcount="29"> Eduard Lintner, parliamentary speaker on German affairs for the joint Christian Democrat and Christrian Socialist caucus in the Bundestag, said his committee has placed reunification on its October agenda.</s>

<s docid="WSJ890922-0113" num="14" wdcount="27"> He said the sessions, which will include government officials and outside experts, hopefully can devise reunification models to discuss with West Germany's Western allies, particularly the U.S.</s>

<s docid="WSJ890922-0113" num="15" wdcount="20"> "It has become clear to the world that the Communist system in East Germany is in trouble," Mr. Lintner said.</s>

<s docid="WSJ890922-0113" num="16" wdcount="39"> "The time has come for us to show our allies, but also reform-minded people in the East, that German reunification is no longer just a theory but a subject requiring a serious appraisal of how it could come about".</s>

<s docid="WSJ890922-0113" num="17" wdcount="10"> "There are still a number of imponderables," Mr. Linter conceded.</s>

<s docid="WSJ890922-0113" num="18" wdcount="19"> "For instance, we want the federal government to approach our allies and get their thoughts on the reunification topic".</s>

<s docid="WSJ890922-0113" num="19" wdcount="24"> The U.S. ambassador to Bonn, Vernon A. Walters, earlier this month reaffirmed Washington's policy of supporting a German reunification based on free, democratic elections.</s>

<s docid="WSJ890922-0113" num="20" wdcount="17"> But Mr. Walters caused a stir by predicting that reunion could occur in the relatively near future.</s>

<s docid="WSJ890922-0113" num="21" wdcount="29"> Emerging opposition to uncompromising Communist rule in East Germany has raised questions on how long East Berlin's leaders can resist the democratic reforms sweeping through neighboring East Bloc countries.</s>

<s docid="WSJ890922-0113" num="22" wdcount="15"> Reforms in Poland, Hungary and even the Soviet Union have magnified East Germany's Stalinist controls.</s>

<s docid="WSJ890922-0113" num="23" wdcount="35"> Fledgling protest groups, and the influential Protestant church, have begun pressing for reforms in East Germany which, if allowed to include free elections, could eventually lead to a reunited Germany, according to some Western experts.</s>

<s docid="WSJ890922-0113" num="24" wdcount="35"> Dorothee Wilms, Bonn's cabinet minister for inter-German affairs, said in an interview in the newspaper Welt am Sonntag that recent polls show that between 85% and 90% of all West Germans favor a reunifed Germany.</s>

<s docid="WSJ890922-0113" num="25" wdcount="26"> "The desire for reunification, a feeling of togetherness, a sense of nationhood -- all this has strongly increased in recent years," Ms. Wilms told the newspaper.</s>

<s docid="WSJ890922-0113" num="26" wdcount="31"> "The recent escape movement from the DDR makes especially clear that people of both German states want to live free amongst themselves," she said, but cautioned that reunification cannot occur overnight.</s>

<s docid="WSJ890922-0113" num="27" wdcount="12"> The first step, she added, "is the reform process in the DDR".</s>

<s docid="WSJ890922-0113" num="28" wdcount="24"> Most West German governments since 1949 have paid only lip service to the reunification goal set down in the preamble of West Germany's constitution.</s>

<s docid="WSJ890922-0113" num="29" wdcount="11"> Political realities have prevented the topic from becoming a serious issue.</s>

<s docid="WSJ890922-0113" num="30" wdcount="12"> Analysts say that four decades of different systems would make reunification difficult.</s>

<s docid="WSJ890922-0113" num="31" wdcount="17"> Further, many West German workers worry that a mass influx of East Germans could threaten their jobs.</s>

<s docid="WSJ890922-0113" num="32" wdcount="23"> Thousands of East Germans have emigrated to West Germany over the Austro-Hungarian border since Budapest ignored East Berlin's protests and opened its border.</s>

<s docid="WSJ890922-0113" num="33" wdcount="31"> Close to 80,000 East German refugees have arrived in West Germany so far this year, either legally or by escaping, and a total of more than 100,000 are expected by December.</s>

<s docid="WSJ890922-0113" num="34" wdcount="31"> The Soviets have joined East Berlin in criticizing Bonn for welcoming the East German refugees, and chided Hungary for violating an emigration treaty with East Germany by allowing them to leave.</s>

<s docid="WSJ890922-0113" num="35" wdcount="29"> Moscow, which has tolerated reforms elsewhere in the East Bloc, is said to be concerned by conditions in East Germany, perhaps the most important of its Warsaw Pact satellites.</s>

<s docid="WSJ890922-0113" num="36" wdcount="27"> Unconfirmed West German intelligence reports appearing in the West German media said Moscow fears a growing dissident movement and mass demonstrations in East Germany by next year.</s>

<s docid="WSJ890922-0113" num="37" wdcount="28"> Soviet President Mikhail Gorbachev accepted an invitation to attend East Germany's 40th anniversary celebration, providing an opportunity for serious discussions with Erich Honecker, East Berlin's ailing party leader.</s>

<s docid="WSJ890922-0113" num="38" wdcount="22"> East Germany's Communist leadership, commented the newspaper Frankfurter Allgemeine Zeitung, "has no illusions as to why Gorbachev is honoring their 40th anniversary.</s>

<s docid="WSJ890922-0113" num="39" wdcount="11"> He certainly will not say 'well done, keep it up'" .</s>
</TEXT>
</DOC>
