<DOC>
<DOCNO>

<s docid="AP890615-0263" num="1" wdcount="1"> AP890615-0263</s>
</DOCNO>
<FILEID>

<s docid="AP890615-0263" num="2" wdcount="2"> AP-NR-06-15-89 1342EST</s>
</FILEID>
<FIRST>

<s docid="AP890615-0263" num="3" wdcount="5"> r f BC-Walton 06-15 0226</s>
</FIRST>
<SECOND>

<s docid="AP890615-0263" num="4" wdcount="1"> BC-Walton,0234</s>
</SECOND>
<HEAD>

<s docid="AP890615-0263" num="5" wdcount="7"> Wal-Mart Founder Pitches in at Check-Out Counter</s>
</HEAD>
<DATELINE>

<s docid="AP890615-0263" num="6" wdcount="5"> FORT WALTON BEACH, Fla. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890615-0263" num="7" wdcount="27"> Wal-Mart founder Sam Walton pitched in to help check-out clerks at his store in this Florida Panhandle city when an electronic glitch shut down the cash registers.</s>

<s docid="AP890615-0263" num="8" wdcount="34"> The 71-year-old Walton, considered to be one of the world's richest people, grabbed a note pad Tuesday evening and started hand-writing merchandise prices for customers so their bills could be tallied on calculators quickly.</s>

<s docid="AP890615-0263" num="9" wdcount="15"> ``People began recognizing him and coming up and greeting him,'' said store manager Paul Sively.</s>

<s docid="AP890615-0263" num="10" wdcount="10"> ``He shook their hands and talked to everyone he could.</s>

<s docid="AP890615-0263" num="11" wdcount="17"> The registers were out for about 45 minutes, and I don't think we had one customer complain''.</s>

<s docid="AP890615-0263" num="12" wdcount="28"> Walton, known for his down-home style, made a surprise visit to the store that later Tuesday staged a concert by country singer Jana Jea in its parking lot.</s>

<s docid="AP890615-0263" num="13" wdcount="21"> Walton often attends promotional events for his Arkansas-based chain, and Sively said he had suspected the boss might make an appearance.</s>

<s docid="AP890615-0263" num="14" wdcount="8"> Walton continued talking with customers during the concert.</s>

<s docid="AP890615-0263" num="15" wdcount="18"> He also joined the singer on stage to sing a duet and led customers in the Wal-Mart cheer.</s>

<s docid="AP890615-0263" num="16" wdcount="23"> ``He was up there saying, `Give me a W, give me an A,' and the customers went right along with him,'' Sively said.</s>

<s docid="AP890615-0263" num="17" wdcount="9"> ``He even got down to do a cheerleader's squiggle.''</s>
</TEXT>
</DOC>
