<DOC>
<DOCNO>

<s docid="AP890323-0234" num="1" wdcount="1"> AP890323-0234</s>
</DOCNO>
<FILEID>

<s docid="AP890323-0234" num="2" wdcount="2"> AP-NR-03-23-89 1347EST</s>
</FILEID>
<FIRST>

<s docid="AP890323-0234" num="3" wdcount="6"> s a BC-Wal-Mart-WaltonProfile Adv26 03-23 0677</s>
</FIRST>
<SECOND>

<s docid="AP890323-0234" num="4" wdcount="4"> BC-Wal-Mart-Walton Profile, Adv 26,0700</s>
</SECOND>
<HEAD>

<s docid="AP890323-0234" num="5" wdcount="1"> $Adv26</s>
</HEAD>
<HEAD>

<s docid="AP890323-0234" num="6" wdcount="7"> For Release Sunday, March 26, and Thereafter</s>
</HEAD>
<HEAD>

<s docid="AP890323-0234" num="7" wdcount="6"> Retail Empire Built By Bargain-Preaching Entrepreneur</s>
</HEAD>
<HEAD>

<s docid="AP890323-0234" num="8" wdcount="5"> Eds: Also on financial wire</s>
</HEAD>
<BYLINE>

<s docid="AP890323-0234" num="9" wdcount="3"> By MARYBETH NIBLEY</s>
</BYLINE>
<BYLINE>

<s docid="AP890323-0234" num="10" wdcount="3"> AP Business Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890323-0234" num="11" wdcount="4"> DE SOTO, Texas (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890323-0234" num="12" wdcount="30"> The store manager of the Wal-Mart in this community on the outskirts of Dallas tells a story that gives an insight into the man considered responsible for a retailing phenomenon.</s>

<s docid="AP890323-0234" num="13" wdcount="49"> Manager Don Bost remembers one day last summer when a secretary telephoned from Wal-Mart Stores Inc.'s corporate headquarters in Bentonville, Ark. Chairman Sam Walton was about to land at a nearby airport and the secretary asked if someone could fetch him and bring him to the De Soto store.</s>

<s docid="AP890323-0234" num="14" wdcount="17"> Paying unexpected calls on stores is one way Walton has kept in close touch with everyday goings-on.</s>

<s docid="AP890323-0234" num="15" wdcount="22"> His example is followed by other Wal-Mart executives and most make a point of spending a lot of time in the field.</s>

<s docid="AP890323-0234" num="16" wdcount="23"> Says Ed Nagy, district manager for 9 stores in the Dallas metropolitan area, ``It's not like `Uh-oh, someone's coming,' because they're always out''.</s>

<s docid="AP890323-0234" num="17" wdcount="11"> By all accounts, Sam Walton's personality permeates operations throughout the company.</s>

<s docid="AP890323-0234" num="18" wdcount="28"> Everyone, from Wal-Mart President and Chief Operating Officer David Glass down to an hourly store worker, can readily quote the gospel according to Sam, as he is called.</s>

<s docid="AP890323-0234" num="19" wdcount="15"> To paraphrase Sam's primary rules of retailing, ``Rule No.1 is the customer is always right.</s>

<s docid="AP890323-0234" num="20" wdcount="13"> Rule No.2 says just in case the customer's wrong, revert to rule No.1''.</s>

<s docid="AP890323-0234" num="21" wdcount="20"> If the principles sound old-fashioned and homespun, they are because that's the way Sam is, people who know him say.</s>

<s docid="AP890323-0234" num="22" wdcount="23"> He shuns the limelight that his company's success has shed on him and has decided to refuse almost all press requests for interviews.</s>

<s docid="AP890323-0234" num="23" wdcount="10"> He's happy to chat with folks in his stores, though.</s>

<s docid="AP890323-0234" num="24" wdcount="12"> He also regularly reminds Wal-Mart ``associates'' that hospitality to customers is crucial.</s>

<s docid="AP890323-0234" num="25" wdcount="13"> He preaches it in person or via high-tech satellite hookup with his stores.</s>

<s docid="AP890323-0234" num="26" wdcount="27"> Wal-Mart employees became known as associates under a company effort to prove it cared about employees, partly to thwart a union organizing effort in the late 1960s.</s>

<s docid="AP890323-0234" num="27" wdcount="13"> One of the most sensitive subjects for Walton is the fortune he's amassed.</s>

<s docid="AP890323-0234" num="28" wdcount="22"> A close associate says Sam would ``probably give anything'' not to be named on Fortune magazine's list of the country's wealthiest people.</s>

<s docid="AP890323-0234" num="29" wdcount="17"> The magazine has estimated that his immediate family's stake in Wal-Mart stock is worth about $6.8 billion.</s>

<s docid="AP890323-0234" num="30" wdcount="20"> ``Sam Walton is more interested in his backhand than he is in his bank account,'' says Don Shinkle, Wal-Mart spokesman.</s>

<s docid="AP890323-0234" num="31" wdcount="8"> Samuel Moore Walton turns 71 on March 29.</s>

<s docid="AP890323-0234" num="32" wdcount="6"> He was born in Kingfisher, Okla.</s>

<s docid="AP890323-0234" num="33" wdcount="11"> , and grew up as the son of a farm-mortgage banker.</s>

<s docid="AP890323-0234" num="34" wdcount="26"> He graduated from the University of Missouri with an economics degree in 1940 and joined J.C. Penney Co. as a management trainee in Des Moines, Iowa.</s>

<s docid="AP890323-0234" num="35" wdcount="24"> After serving three years in the Army, he went to Arkansas and opened a Ben Franklin five-and-dime store, eventually becoming the company's biggest franchisee.</s>

<s docid="AP890323-0234" num="36" wdcount="25"> The seeds of the Wal-Mart empire were sown when Sam and his brother James L., or Bud, opened the first Wal-Mart Discount City in 1962.</s>

<s docid="AP890323-0234" num="37" wdcount="14"> The rest will probably earn an entry in the history of U.S. retail trade.</s>

<s docid="AP890323-0234" num="38" wdcount="11"> Bud is a senior vice president and board member of Wal-Mart.</s>

<s docid="AP890323-0234" num="39" wdcount="20"> Three of the four grown children Sam and his wife Helen had are involved with the company in various capacities.</s>

<s docid="AP890323-0234" num="40" wdcount="28"> Sam hasn't slowed much, enjoying hunting and tennis as much as ever, and is said not to suffer after effects from a bout with leukemia, now in remission.</s>

<s docid="AP890323-0234" num="41" wdcount="15"> He spends less time in the office since handing over most responsiblities to David Glass.</s>

<s docid="AP890323-0234" num="42" wdcount="7"> Sam is still chairman of the board.</s>

<s docid="AP890323-0234" num="43" wdcount="11"> Glass doesn't hesitate when asked if Wal-Mart can flourish without Sam.</s>

<s docid="AP890323-0234" num="44" wdcount="13"> The answer is an emphatic yes because, he says, ``We have great people''.</s>

<s docid="AP890323-0234" num="45" wdcount="9"> The Walton family will always be involved, he adds.</s>

<s docid="AP890323-0234" num="46" wdcount="14"> Commenting on the future, Glass says: ``We'll be judged on what we produce today.</s>

<s docid="AP890323-0234" num="47" wdcount="9"> Tomorrow, what we've done in the past won't matter.''</s>
</TEXT>
<NOTE>

<s docid="AP890323-0234" num="48" wdcount="6"> End Adv for Sunday, March 26</s>
</NOTE>
</DOC>
