<DOC>
<DOCNO>

<s docid="AP890711-0223" num="1" wdcount="1"> AP890711-0223</s>
</DOCNO>
<FILEID>

<s docid="AP890711-0223" num="2" wdcount="2"> AP-NR-07-11-89 0217EST</s>
</FILEID>
<FIRST>

<s docid="AP890711-0223" num="3" wdcount="6"> r f PM-World'sRichest-Walton Bjt 07-11 0505</s>
</FIRST>
<SECOND>

<s docid="AP890711-0223" num="4" wdcount="3"> PM-World's Richest-Walton, Bjt,0521</s>
</SECOND>
<HEAD>

<s docid="AP890711-0223" num="5" wdcount="6"> Wealthy Wal-Mart Founder Just Another Neighbor</s>
</HEAD>
<BYLINE>

<s docid="AP890711-0223" num="6" wdcount="4"> By JENNIFER M. FULFORD</s>
</BYLINE>
<BYLINE>

<s docid="AP890711-0223" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890711-0223" num="8" wdcount="4"> LITTLE ROCK, Ark. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890711-0223" num="9" wdcount="31"> He's ranked as the richest man in the nation by a leading business magazine, but to folks in Bentonville, a town of about 8,700 people, Sam Walton is just another neighbor.</s>

<s docid="AP890711-0223" num="10" wdcount="18"> ``He's just a part of the community,'' said Curt Loyd, executive director of the Bentonville Chamber of Commerce.</s>

<s docid="AP890711-0223" num="11" wdcount="4"> ``He's a neat person.</s>

<s docid="AP890711-0223" num="12" wdcount="10"> He calls Bentonville home, and that is special to us''.</s>

<s docid="AP890711-0223" num="13" wdcount="30"> Walton, who prefers bird-hunting, tennis and opening new Wal-Mart stores to trumpeting his personal financial holdings, is again shunning publicity about his third consecutive ranking among the world's top billionaires.</s>

<s docid="AP890711-0223" num="14" wdcount="23"> According to Forbes magazine's July 24 edition, the Walton family's estimated worth is $8.7 billion, up from its 1988 estimate of $6.5 billion.</s>

<s docid="AP890711-0223" num="15" wdcount="28"> ``He is unavailable,'' said Wal-Mart spokesman Don Shinkle of the silver-haired founder of the nation's third-largest retail chain, based in Bentonville, about 150 miles northwest of Little Rock.</s>

<s docid="AP890711-0223" num="16" wdcount="18"> Shinkle said he received about 10 calls from reporters Monday morning, when the Forbes list appeared in newspapers.</s>

<s docid="AP890711-0223" num="17" wdcount="16"> Shinkle said news coverage about Walton ``usually sets off a press frenzy'' for comments from him.</s>

<s docid="AP890711-0223" num="18" wdcount="7"> But the 71-year-old businessman declined to comment.</s>

<s docid="AP890711-0223" num="19" wdcount="25"> ``He feels any attention to Sam Walton is to the individual and he prefers attention to Sam Walton (the founder of) the company,'' Shinkle said.</s>

<s docid="AP890711-0223" num="20" wdcount="8"> ``He very seldom schedules interviews about his feelings.</s>

<s docid="AP890711-0223" num="21" wdcount="12"> It just puts him in a position he doesn't want to be''.</s>

<s docid="AP890711-0223" num="22" wdcount="9"> But Walton occasionally offers peeks that reveal personal modesty.</s>

<s docid="AP890711-0223" num="23" wdcount="37"> Just after the 1987 stock market crash, in which Walton's family-owned chunk of Wal-Mart stock lost millions in value, he quipped in response to questions at a news conference on another topic that it was only paper.</s>

<s docid="AP890711-0223" num="24" wdcount="5"> Walton then changed the subject.</s>

<s docid="AP890711-0223" num="25" wdcount="14"> Walton was first listed by Forbes as the nation's richest man in October 1985.</s>

<s docid="AP890711-0223" num="26" wdcount="11"> Three years ago, Forbes also began listing the world's wealthiest people.</s>

<s docid="AP890711-0223" num="27" wdcount="11"> Walton made that listing as the richest American every year since.</s>

<s docid="AP890711-0223" num="28" wdcount="9"> This year he ranks third, behind two Japanese businessmen.</s>

<s docid="AP890711-0223" num="29" wdcount="30"> Shinkle said Walton stays busy visiting many of the more than 1,400 stores operated by the company he started as a single five-and-dime at Rogers more than two decades ago.</s>

<s docid="AP890711-0223" num="30" wdcount="15"> He is out of the office up to four days a week, the spokesman said.</s>

<s docid="AP890711-0223" num="31" wdcount="23"> ``He spends most of his time talking to associates and customers,'' Shinkle said, ``and he always comes back with many ideas from them''.</s>

<s docid="AP890711-0223" num="32" wdcount="9"> Wal-Mart calls its sales help associates instead of employees.</s>

<s docid="AP890711-0223" num="33" wdcount="29"> When Walton first made the Forbes list of richest Americans, recalled Little Rock investment banker Warren Simpson, calls came in from all over about the billionaire from the Ozarks.</s>

<s docid="AP890711-0223" num="34" wdcount="17"> ``They wanted to know about the stock and the company,'' said Simpson, who works for Stephens Inc.</s>

<s docid="AP890711-0223" num="35" wdcount="14"> ``You'd think that he'd be living in New York or LA, not Bentonville, Arkansas.</s>

<s docid="AP890711-0223" num="36" wdcount="6"> But now people just accept it.</s>

<s docid="AP890711-0223" num="37" wdcount="14"> ``When it comes out now, it's just, `Yeah, he's still there,''' Simpson said .</s>
</TEXT>
</DOC>
