<DOC>
<DOCNO>

<s docid="AP900507-0207" num="1" wdcount="1"> AP900507-0207</s>
</DOCNO>
<FILEID>

<s docid="AP900507-0207" num="2" wdcount="2"> AP-NR-05-07-90 0731EDT</s>
</FILEID>
<FIRST>

<s docid="AP900507-0207" num="3" wdcount="5"> r f PM-Wal-MartCenter 05-07 0636</s>
</FIRST>
<SECOND>

<s docid="AP900507-0207" num="4" wdcount="2"> PM-Wal-Mart Center,0655</s>
</SECOND>
<HEAD>

<s docid="AP900507-0207" num="5" wdcount="6"> Center Puts Wal-Mart History on Display</s>
</HEAD>
<DATELINE>

<s docid="AP900507-0207" num="6" wdcount="3"> BENTONVILLE, Ark. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900507-0207" num="7" wdcount="26"> Forty years after Sam Walton first hung out his shingle, Walton's 5&10 will reopen to show how a little rural storekeeper built a discount retail empire.</s>

<s docid="AP900507-0207" num="8" wdcount="25"> Wal-Mart Stores Inc.'s Visitors Center opens Wednesday in the same building on the downtown square where Walton first opened for business on May 9, 1950.</s>

<s docid="AP900507-0207" num="9" wdcount="16"> The center chronicles the rise of the nation's fastest-growing discount chain, using displays and audio-video presentations.</s>

<s docid="AP900507-0207" num="10" wdcount="17"> It concentrates on how the free enterprise system works and how Wal-Mart thrived when similar companies didn't.</s>

<s docid="AP900507-0207" num="11" wdcount="23"> The window displays date back to the store's opening, with Simplicity patterns and Johnson's Glo-Coat, a box of Dreft and some Ivory Snow.</s>

<s docid="AP900507-0207" num="12" wdcount="11"> Inside, an electronic map details the company's 1,500-plus store chain today.</s>

<s docid="AP900507-0207" num="13" wdcount="37"> Also on display at the center is the hula skirt that Sam Walton donned for his ``dance on Wall Street,'' which he performed after challenging the company to reach a record 8 percent pre-tax profit in 1984.</s>

<s docid="AP900507-0207" num="14" wdcount="7"> The goal was accomplished and he danced.</s>

<s docid="AP900507-0207" num="15" wdcount="22"> The old and the modern together reflect the corporate culture of the nation's biggest discount retailer behind K mart Corp. of Detroit.</s>

<s docid="AP900507-0207" num="16" wdcount="13"> Walton and his brother, Bud, opened the first Wal-Mart Discount City in 1962.</s>

<s docid="AP900507-0207" num="17" wdcount="22"> Both will be on hand for the opening, along with a sprinkling of other dignitaries, including Gov. Bill Clinton, the dedication speaker.</s>

<s docid="AP900507-0207" num="18" wdcount="29"> Aside from the other displays and presentations, the center also has a replica of Sam Walton's original office at the store, including many fixtures he used 40 years ago.</s>

<s docid="AP900507-0207" num="19" wdcount="19"> Also on display is a photograph of young Sam Walton, a fat-faced baby born in Oklahoma in the 1920s.</s>

<s docid="AP900507-0207" num="20" wdcount="24"> Typical of the Wal-Mart outlook, Dust Bowl Oklahoma is termed ``a place to grow and to dream'' in a video on the Walton family.</s>

<s docid="AP900507-0207" num="21" wdcount="20"> After a stint with J.C. Penney Co. and the Army, he opened a Ben Franklin store in Newport in 1945.</s>

<s docid="AP900507-0207" num="22" wdcount="11"> He lost the lease on that one, and relocated to Bentonville.</s>

<s docid="AP900507-0207" num="23" wdcount="6"> That's where the story took off.</s>

<s docid="AP900507-0207" num="24" wdcount="22"> Sam Walton convinced Bob Bogle, then a public health officer, to take over management of his Bentonville Ben Franklin store in 1955.</s>

<s docid="AP900507-0207" num="25" wdcount="37"> Walton ``said he wanted to put in about a dozen stores'' and needed someone to tend the shop in Bentonville while he and his brother built a chain of Ben Franklins, Bogle said in a recent interview.</s>

<s docid="AP900507-0207" num="26" wdcount="13"> That's when Bogle found himself in Walton's ``learn as you go'' training program.</s>

<s docid="AP900507-0207" num="27" wdcount="18"> ``I got home at 10 o'clock that night after scrubbing and waxing the floor with Sam,'' Bogle said.</s>

<s docid="AP900507-0207" num="28" wdcount="8"> Inauspicious first impressions are part of the story.</s>

<s docid="AP900507-0207" num="29" wdcount="33"> In one video, David Glass, who succeeded Sam Walton as chief executive of Wal-Mart in 1988, recalled his impressions after attending the opening of the second Wal-Mart Discount City at Harrison in 1964.</s>

<s docid="AP900507-0207" num="30" wdcount="9"> The first store, at Rogers, opened two years earlier.</s>

<s docid="AP900507-0207" num="31" wdcount="30"> ``I thought to myself this is absolutely the worst discount store, or retail store, I have ever seen,'' said Glass, who was president of a drugstore chain at the time.</s>

<s docid="AP900507-0207" num="32" wdcount="36"> And Wal-Mart Vice Chairman Donald Soderquist recalls that when Walton took his idea of putting discount stores in rural areas to Ben Franklin headquarters in Chicago, officials there ``just really didn't see a future in it''.</s>

<s docid="AP900507-0207" num="33" wdcount="52"> Don Shinkle, Wal-Mart's director of corporate and public affairs, attributed Wal-Mart's success to its ``associates'' _ the term for employees first coined in 1972 to stress that all Wal-Mart employees are partners in the company _ and to Sam Walton's leadership and knack for hiring the ``right person at the right time''.</s>

<s docid="AP900507-0207" num="34" wdcount="17"> At the start of 1990, Wal-Mart owned 1,402 stores, employed 272,000 and listed sales of $25.8 billion.</s>

<s docid="AP900507-0207" num="35" wdcount="20"> Sam's Wholesale Club closed out the year with 123 units and Wal-Mart announced plans to enter the California market .</s>
</TEXT>
</DOC>
