<DOC>
<DOCNO>

<s docid="FT922-14265" num="1" wdcount="1"> FT922-14265</s>
</DOCNO>
<PROFILE>

<s docid="FT922-14265" num="2" wdcount="1"> _AN-CDGBIAF1FT</s>
</PROFILE>
<DATE>

<s docid="FT922-14265" num="3" wdcount="1"> 920407</s>
</DATE>
<HEADLINE>

<s docid="FT922-14265" num="4" wdcount="15"> FT 07 APR 92 / International Company News: Founder most important retailer of his generation</s>
</HEADLINE>
<BYLINE>

<s docid="FT922-14265" num="5" wdcount="3"> By MARTIN DICKSON</s>
</BYLINE>
<TEXT>

<s docid="FT922-14265" num="6" wdcount="11"> SAM WALTON was arguably the most important retailer of his generation.</s>

<s docid="FT922-14265" num="7" wdcount="33"> The son of an Oklahoma real-estate broker, he opened the first general store in what was to become the Wal-Mart chain in Bentonville, in the backwaters of Arkansas, in 1950, writes Martin Dickson.</s>

<s docid="FT922-14265" num="8" wdcount="28"> By 1991 the chain's sales had risen to nearly Dollars 44bn, making it the world's largest retailer in terms of revenues, and the Walton family probably America's richest.</s>

<s docid="FT922-14265" num="9" wdcount="15"> Wal-Mart now operates in 43 US states, selling goods ranging from detergents to golf clubs.</s>

<s docid="FT922-14265" num="10" wdcount="16"> The chain's success stemmed both from Mr Walton's personality and willingness to challenge accepted retailing orthodoxy.</s>

<s docid="FT922-14265" num="11" wdcount="41"> He was a frugal, modest man who worked extremely long hours from a spartan room in his Bentonville headquarters but delighted in getting out of the office to tour stores and meet customers and staff, whom he insisted on calling 'associates'.</s>

<s docid="FT922-14265" num="12" wdcount="21"> He would deliver pep-talks to employees extolling the virtues of thrift and customer satisfaction, long before these became fashionable management buzz-words.</s>

<s docid="FT922-14265" num="13" wdcount="26"> Employee satisfaction - an idea which is only now gaining wider acceptance in US service industries - was also a vital ingredient in the Walton philosophy.</s>

<s docid="FT922-14265" num="14" wdcount="27"> He buoyed staff morale with cheer-leading sessions, bonus payments for good performance and profit-sharing plans which allowed some employees of very modest means to retire relatively wealthy.</s>

<s docid="FT922-14265" num="15" wdcount="28"> Eight years ago, when Wal-Mart's profits were better than expected, he kept a promise to staff by dressing in a grass-skirt to dance the hula on Wall Street.</s>

<s docid="FT922-14265" num="16" wdcount="29"> Also essential to Wal-Mart's growth was its pioneering of high volume, cut-price retailing throughout the year, rather than the periodic sales which rivals relied on to generate customer loyalty.</s>

<s docid="FT922-14265" num="17" wdcount="6"> 'Low prices always' became Wal-Mart's motto.</s>

<s docid="FT922-14265" num="18" wdcount="24"> Mr Walton also disproved the conventional wisdom that large discount stores could not operate successfully in the small, rural towns of the US south.</s>

<s docid="FT922-14265" num="19" wdcount="44"> It was precisely such locations which became the bedrock of the business, though in the process Wal-Mart put out of business hundreds of small main street stores, prompting bitter resistance in some towns which Mr Walton tended to blunt with generous charitable donations .</s>
</TEXT>
<PUB>

<s docid="FT922-14265" num="20" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT922-14265" num="21" wdcount="3"> London Page 26</s>
</PAGE>
</DOC>
