<DOC>
<DOCNO>

<s docid="FT923-5068" num="1" wdcount="1"> FT923-5068</s>
</DOCNO>
<PROFILE>

<s docid="FT923-5068" num="2" wdcount="1"> _AN-CIEAPABTFT</s>
</PROFILE>
<DATE>

<s docid="FT923-5068" num="3" wdcount="1"> 920903</s>
</DATE>
<HEADLINE>

<s docid="FT923-5068" num="4" wdcount="14"> FT 03 SEP 92 / Book Review: Good ol' boy who made a bundle</s>
</HEADLINE>
<BYLINE>

<s docid="FT923-5068" num="5" wdcount="3"> By NIKKI TAIT</s>
</BYLINE>
<TEXT>

<s docid="FT923-5068" num="6" wdcount="27"> MADE IN AMERICA: MY STORY By Sam Walton Doubleday, Dollars 22.50. 269 pages Being an American folk hero is a tricky assignment, as Ross Perot found out.</s>

<s docid="FT923-5068" num="7" wdcount="19"> The problem is that the great American public likes its boot-strap entrepreneurs to be very rich and very upright.</s>

<s docid="FT923-5068" num="8" wdcount="17"> In a country where business practices are not overly genteel, this is a tough combination to achieve.</s>

<s docid="FT923-5068" num="9" wdcount="11"> A vast media circus, meanwhile, is quick to expose any flaws.</s>

<s docid="FT923-5068" num="10" wdcount="23"> Sam Walton, founder of the Wal-Mart chain of discount supermarkets who died of cancer in April, negotiated these pitfalls much better than most.</s>

<s docid="FT923-5068" num="11" wdcount="29"> When, in 1985, Forbes magazine declared him America's richest entrepreneur, the paparazzi descended on the obscure corner of Arkansas, mainly occupied by chicken farmers, where Walton made his home.</s>

<s docid="FT923-5068" num="12" wdcount="28"> What they found was a happily married, much-liked billionaire who enjoyed quail hunting, breakfasted at the local Holiday Inn, and drove a battered pick-up truck, minus two hub-caps.</s>

<s docid="FT923-5068" num="13" wdcount="4"> Folksy was an understatement.</s>

<s docid="FT923-5068" num="14" wdcount="30"> Since then, some aspects of Wal-Mart's business - its anti-union policies, the impact of its Dollars 40bn annual sales on hundreds of Mom-and-Pop shops -have been subject to critical scrutiny.</s>

<s docid="FT923-5068" num="15" wdcount="14"> So, to an extent, have the less wholesome adventures of the four Walton children.</s>

<s docid="FT923-5068" num="16" wdcount="13"> But no one has ever been able to make Sam himself look bad.</s>

<s docid="FT923-5068" num="17" wdcount="12"> The worst that has been said is that he was rather dull.</s>

<s docid="FT923-5068" num="18" wdcount="8"> Walton is not about to dash anyone's illusions.</s>

<s docid="FT923-5068" num="19" wdcount="19"> Readers will either find his autobiography lashed with 'good ol'' common-sense and a lot of harmless, if charming, anecdotes.</s>

<s docid="FT923-5068" num="20" wdcount="8"> Or they will find it dreary and downbeat.</s>

<s docid="FT923-5068" num="21" wdcount="36"> Walton makes no excuses: 'I realise this may sound boring to most you,' he writes at one stage, 'but one of my best items ever was a mattress pad called a Bedmate . . . '.</s>

<s docid="FT923-5068" num="22" wdcount="9"> A few snippets are more revealing about the character.</s>

<s docid="FT923-5068" num="23" wdcount="27"> There cannot be many billionaires who admit that they 'never learned handwriting too well' - and have the guts to include a photograph which demonstrates the point.</s>

<s docid="FT923-5068" num="24" wdcount="13"> Meanwhile, the competitive energy which Sam Walton applied to his business is inescapable.</s>

<s docid="FT923-5068" num="25" wdcount="36"> In one of many contributions from friends and family, Don Soderquist, Wal-Mart's chief operating officer, tells of finding Sam one Saturday morning on his hand and knees at the local Kmart store, analysing his rival's stock.</s>

<s docid="FT923-5068" num="26" wdcount="30"> And his wife, in a casual aside, notes that when the couple was on holiday in Italy their luggage vanished while her husband was off on a similar scouting mission.</s>

<s docid="FT923-5068" num="27" wdcount="17"> But it is David Glass, Wal-Mart's current chief executive, who perhaps captures the entrepreneurial Walton spirit best.</s>

<s docid="FT923-5068" num="28" wdcount="29"> Explaining the annual contest in which Wal-Mart executives choose one 'volume producing item' to promote, he recalls the time Sam (who usually won) selected minnow buckets for carrying bait.</s>

<s docid="FT923-5068" num="29" wdcount="8"> Glass was more happily teamed with apple juice.</s>

<s docid="FT923-5068" num="30" wdcount="36"> 'So I would go down to the stores, and get them to take that minnow bucket . . . put ice in it, ice down the juice and give away samples out of his minnow bucket.</s>

<s docid="FT923-5068" num="31" wdcount="13"> I particularly did it in stores I knew (Sam) was going to visit.</s>

<s docid="FT923-5068" num="32" wdcount="17"> It drove him crazy, and he got off that minnow bucket pretty quick . . . '.</s>

<s docid="FT923-5068" num="33" wdcount="15"> But the reader can't help feeling that the cosy yarns tell only half the truth.</s>

<s docid="FT923-5068" num="34" wdcount="31"> Sam Walton was a salesman to the core, and seems to have packaged himself with all the skill that he once applied to selling a gooey southern sweet called Moon Pies.</s>

<s docid="FT923-5068" num="35" wdcount="12"> For the most part, this makes for an engaging, if one-dimensional, portrait.</s>

<s docid="FT923-5068" num="36" wdcount="4"> Occasionally, it just grates.</s>

<s docid="FT923-5068" num="37" wdcount="28"> 'I had bought a bank in Bentonville, for about about Dollars 300,000,' Walton remarks, for example, 'just a little old bank with only about Dollars 3.5m in deposits.</s>

<s docid="FT923-5068" num="38" wdcount="10"> But it helped me learn a lot about financing things'.</s>

<s docid="FT923-5068" num="39" wdcount="9"> Oh, come on Sam, is that the whole story?</s>

<s docid="FT923-5068" num="40" wdcount="31"> The real truth, one suspects, comes right at the end of the book - when Walton admits that 'if I hadn't gotten sick, I doubt I would have written this book'.</s>

<s docid="FT923-5068" num="41" wdcount="35"> Given the pleadings of publishers - Doubleday paid about Dollars 4m for the manuscript - and a rather natural desire to have a final say, he can hardly be blamed for agreeing to write it.</s>

<s docid="FT923-5068" num="42" wdcount="14"> But these are unlikely to be circumstances which make for the most critical self-analysis.</s>

<s docid="FT923-5068" num="43" wdcount="18"> At the end of the day, Sam Walton's heritage is in the shopping malls, not the bookstores .</s>
</TEXT>
<PUB>

<s docid="FT923-5068" num="44" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT923-5068" num="45" wdcount="3"> London Page 18</s>
</PAGE>
</DOC>
