<DOC>
<DOCNO>

<s docid="FT944-12170" num="1" wdcount="1"> FT944-12170</s>
</DOCNO>
<PROFILE>

<s docid="FT944-12170" num="2" wdcount="1"> _AN-EKBD9AGPFT</s>
</PROFILE>
<DATE>

<s docid="FT944-12170" num="3" wdcount="1"> 941102</s>
</DATE>
<HEADLINE>

<s docid="FT944-12170" num="4" wdcount="32"> FT 02 NOV 94 / FT Review of Business Books (10): Few better qualified - What is most startling about Wal-Mart is the speed of its growth / Sam Walton's American dream</s>
</HEADLINE>
<BYLINE>

<s docid="FT944-12170" num="5" wdcount="3"> By NEIL BUCKLEY</s>
</BYLINE>
<TEXT>

<s docid="FT944-12170" num="6" wdcount="47"> 'WAL-MART: A HISTORY OF SAM WALTON'S RETAIL PHENOMENON' by Sandra S. Vance and Roy V. Scott Twayne Publishers, New York, Dollars 14.95 240 pages Many people might be said to be the personification of the American Dream; few are better qualified for that title than Sam Walton.</s>

<s docid="FT944-12170" num="7" wdcount="22"> Walton is a character it would be difficult to invent, an all-American boy who became one of the world's most successful businessmen.</s>

<s docid="FT944-12170" num="8" wdcount="36"> The church-going son of a farmer born in 1918 near Kingfisher, Oklahoma, he founded a store chain which made him America's richest man, and which, shortly before his death in 1992, became the world's biggest retailer.</s>

<s docid="FT944-12170" num="9" wdcount="35"> His company, Wal-Mart, made sales of Dollars 55bn last year, and after Walton's death Fortune magazine reported that his wife and four children held between them the second-largest fortune in the world - Dollars 23.5bn.</s>

<s docid="FT944-12170" num="10" wdcount="12"> What is most startling about Wal-Mart is the speed of its growth.</s>

<s docid="FT944-12170" num="11" wdcount="28"> Although Walton built up a small chain of Ben Franklin variety store franchises from 1945, it was not until 1962 that he opened his first Wal-Mart discount store.</s>

<s docid="FT944-12170" num="12" wdcount="38"> At the time of its incorporation in 1971, Wal-Mart had only 38 outlets with sales of Dollars 44m - not enough to earn a place in trade journal Discount Merchandiser's list of the 71 biggest US discount retailers.</s>

<s docid="FT944-12170" num="13" wdcount="19"> Ten years later, with 330 stores and Dollars 1.6bn sales, it was only the 33rd-biggest retailer in the US.</s>

<s docid="FT944-12170" num="14" wdcount="23"> Its turnover was only 9 per cent of that of Sears Roebuck, the biggest, and 11 per cent of K mart, the second-biggest.</s>

<s docid="FT944-12170" num="15" wdcount="9"> Within another 10 years, Wal-Mart had overtaken them both.</s>

<s docid="FT944-12170" num="16" wdcount="18"> Apart from Walton's autobiography completed shortly before his death, however, published material about the company is curiously scarce.</s>

<s docid="FT944-12170" num="17" wdcount="32"> This book attempts to fill the gap, to provide a 'scholarly account' of the rise of Wal-Mart, setting it in the wider context of US retailing, and explaining how it was achieved.</s>

<s docid="FT944-12170" num="18" wdcount="15"> One strength the authors identify is Wal-Mart's ability to copy and adapt from other retailers.</s>

<s docid="FT944-12170" num="19" wdcount="7"> Sam Walton did not invent discount retailing.</s>

<s docid="FT944-12170" num="20" wdcount="39"> Rather, he realised the threat discounting posed to his own variety store business and studied in depth many of the US's leading discounters of the early 1960s, including Ann and Hope, E J Korvette, Spartan's, Fed-Mart, and K mart.</s>

<s docid="FT944-12170" num="21" wdcount="40"> Walton learned from them all, but was unique in taking his discount stores into small towns of a few thousand people, where shoppers used to travelling long distances were delighted to have a cut-price store nearby selling everything they needed.</s>

<s docid="FT944-12170" num="22" wdcount="7"> Another strength is Wal-Mart's openness to technology.</s>

<s docid="FT944-12170" num="23" wdcount="36"> As early as the 1950s, Walton realised he was wasting too much time travelling and bought a small aircraft to pilot between stores himself - something he continued to do to the end of his life.</s>

<s docid="FT944-12170" num="24" wdcount="44"> Sometimes, Walton was more reluctant to invest in technology, and had to be persuaded by colleagues to introduce computers, and scanning at check-outs - long before most retailers had recognised their importance - and to invest Dollars 20m in an internal satellite communications system.</s>

<s docid="FT944-12170" num="25" wdcount="15"> This technology helped Wal-Mart build one of the most efficient distribution systems of any retailer.</s>

<s docid="FT944-12170" num="26" wdcount="21"> But perhaps the most fundamental reason for its success, the book suggests, has been Wal-Mart's streamlined and highly responsive management structure.</s>

<s docid="FT944-12170" num="27" wdcount="43"> Regional vice-presidents based at group headquarters in Bentonville, Arkansas, rather than in costly regional offices, are despatched every Monday by aircraft to their regions, spend the week visiting stores, working with staff and managers, and return for a day-long merchandising meeting every Friday.</s>

<s docid="FT944-12170" num="28" wdcount="25"> They discuss results, problems and suggestions from the week at a 7.30am meeting on Saturdays and immediately afterwards call district managers to relate the results.</s>

<s docid="FT944-12170" num="29" wdcount="29"> District managers hold a conference call with their store managers, and before the day is out, the contents of the meeting have been communicated to all store department heads.</s>

<s docid="FT944-12170" num="30" wdcount="28"> The system means employees can make suggestions to vice-presidents one week and, if the idea is accepted by the Saturday meeting, see its implementation begin the following week.</s>

<s docid="FT944-12170" num="31" wdcount="9"> Even the world's most successful retailer makes mistakes, however.</s>

<s docid="FT944-12170" num="32" wdcount="40"> One was Walton's decision to stand down from the chairman and chief executive's role in 1974 in favour of Ronald Mayer, only to return to both roles in 1976 after finding he was incapable of letting go of the reins.</s>

<s docid="FT944-12170" num="33" wdcount="14"> Another was Wal-Mart's short-lived Hypermart format, which proved too big even for gigantist America.</s>

<s docid="FT944-12170" num="34" wdcount="26"> Then there was Walton's rash promise to do a 'hula dance' on Wall Street if Wal-Mart achieved an 8 per cent pre-tax profit margin in 1984.</s>

<s docid="FT944-12170" num="35" wdcount="5"> It did, and he did.</s>

<s docid="FT944-12170" num="36" wdcount="22"> The book also covers well the debate over whether Wal-Mart's impact on the economies of small US towns was positive or negative.</s>

<s docid="FT944-12170" num="37" wdcount="23"> If there are criticisms, these are that this 'scholarly account' never quite captures the sheer excitement of working in the world's fastest-growing retailer.</s>

<s docid="FT944-12170" num="38" wdcount="27"> Moreover, it makes little attempt to predict whether Wal-Mart can continue its growth, and conquer the rest of the world in the way it conquered the US.</s>

<s docid="FT944-12170" num="39" wdcount="19"> But this is a well-researched and accessible account of one man's success in building his own American dream .</s>
</TEXT>
<XX>

<s docid="FT944-12170" num="40" wdcount="1"> Countries:-</s>
</XX>
<CN>

<s docid="FT944-12170" num="41" wdcount="6"> USZ United States of America .</s>
</CN>
<XX>

<s docid="FT944-12170" num="42" wdcount="1"> Industries:-</s>
</XX>
<IN>

<s docid="FT944-12170" num="43" wdcount="4"> P2731 Book Publishing .</s>
</IN>
<XX>

<s docid="FT944-12170" num="44" wdcount="1"> Types:-</s>
</XX>
<TP>

<s docid="FT944-12170" num="45" wdcount="6"> TECH Products & Product use .</s>
</TP>
<PUB>

<s docid="FT944-12170" num="46" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT944-12170" num="47" wdcount="3"> London Page VIII</s>
</PAGE>
</DOC>
