<DOC>
<DOCNO>

<s docid="AP880913-0070" num="1" wdcount="1"> AP880913-0070</s>
</DOCNO>
<FILEID>

<s docid="AP880913-0070" num="2" wdcount="2"> AP-NR-09-13-88 0857EDT</s>
</FILEID>
<FIRST>

<s docid="AP880913-0070" num="3" wdcount="7"> u i PM-Netherlands-FerrySinking 3rdLd-Writethru a0537 09-13 0255</s>
</FIRST>
<SECOND>

<s docid="AP880913-0070" num="4" wdcount="5"> PM-Netherlands-Ferry Sinking, 3rd Ld-Writethru, a0537,0260</s>
</SECOND>
<HEAD>

<s docid="AP880913-0070" num="5" wdcount="4"> Ship Sinks, Crew Rescued</s>
</HEAD>
<NOTE>

<s docid="AP880913-0070" num="6" wdcount="7"> Eds: UPDATES with crew rescued; identifies ship</s>
</NOTE>
<DATELINE>

<s docid="AP880913-0070" num="7" wdcount="3"> AMSTERDAM, Netherlands (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880913-0070" num="8" wdcount="32"> A freighter carrying a cargo of beer sank in the North Sea today off the Dutch coast and all nine crew members were rescued from life rafts, a coast guard spokesman said.</s>

<s docid="AP880913-0070" num="9" wdcount="20"> The ship sank at about 12:45 p.m. in high winds, some 28 nautical miles north of the island of Ameland.</s>

<s docid="AP880913-0070" num="10" wdcount="28"> It was not immediately clear what had caused the sinking 29 miles off the Dutch island of Ameland, according to the coast guard spokesman, who was not identified.</s>

<s docid="AP880913-0070" num="11" wdcount="6"> There were no casualties, he said.</s>

<s docid="AP880913-0070" num="12" wdcount="30"> The coast guard official, who spoke in a Dutch radio interview, identified the ship involved as the Finnish-registered freighter Ra and said it had been carrying a cargo of beer.</s>

<s docid="AP880913-0070" num="13" wdcount="9"> He did not give the ship's origin or destination.</s>

<s docid="AP880913-0070" num="14" wdcount="14"> The nine crew members boarded two life rafts after the sinking in high winds.</s>

<s docid="AP880913-0070" num="15" wdcount="26"> They were taken ashore by a West German helicopter from the island of Borkum, about 30 miles from the site of the sinking, the official said.</s>

<s docid="AP880913-0070" num="16" wdcount="13"> A Dutch navy aircraft and two life boats also rushed to the scene.</s>

<s docid="AP880913-0070" num="17" wdcount="30"> Earlier reports had said that the ship was a passenger ferry, possibly one of the Dutch ships plying the frequent ferry lanes between the coastal islands and the Dutch mainland.</s>

<s docid="AP880913-0070" num="18" wdcount="26"> Freight shipping in the area is also heavy because of its vicinity to the ports of Delfzijl in the Netherlands and Emden in West Germany .</s>
</TEXT>
</DOC>
