<DOC>
<DOCNO>

<s docid="AP880521-0088" num="1" wdcount="1"> AP880521-0088</s>
</DOCNO>
<FILEID>

<s docid="AP880521-0088" num="2" wdcount="2"> AP-NR-05-21-88 1053EDT</s>
</FILEID>
<FIRST>

<s docid="AP880521-0088" num="3" wdcount="5"> r i AM-Shipwreck 05-21 0528</s>
</FIRST>
<SECOND>

<s docid="AP880521-0088" num="4" wdcount="1"> AM-Shipwreck,0546</s>
</SECOND>
<HEAD>

<s docid="AP880521-0088" num="5" wdcount="7"> Historic Turkish Wreck Located Off Greek Island</s>
</HEAD>
<BYLINE>

<s docid="AP880521-0088" num="6" wdcount="3"> By KERIN HOPE</s>
</BYLINE>
<BYLINE>

<s docid="AP880521-0088" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880521-0088" num="8" wdcount="3"> ATHENS, Greece (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880521-0088" num="9" wdcount="25"> Greek divers have plunged 162 feet beneath the Aegean Sea and back into history, finding a treasure-laden Turkish warship sunk by Greek revolutionaries in 1822.</s>

<s docid="AP880521-0088" num="10" wdcount="40"> The remains of the wooden sailing ship were found near the island of Chios in the eastern Aegean at a point where historical accounts place the sinking of the Ottoman ship, according to Peter Nicolaides, a diver and salvage expert.</s>

<s docid="AP880521-0088" num="11" wdcount="27"> The Bourloti Seimaz _ or ``Explosives Invincible'' _ was set afire and sunk by Greek Admiral Constantine Kanaris in revenge for Turkish killing and looting on Chios.</s>

<s docid="AP880521-0088" num="12" wdcount="27"> Thousands of islanders died in the Turkish raids, which shocked other nations and swung Western European countries behind the Greek struggle for independence from the Ottoman Empire.</s>

<s docid="AP880521-0088" num="13" wdcount="5"> Greece won independence in 1830.</s>

<s docid="AP880521-0088" num="14" wdcount="17"> The French painter Eugene Delacroix produced a famous picture, ``The Massacre of Chios,'' based on the raids.</s>

<s docid="AP880521-0088" num="15" wdcount="31"> ``It's an incredible discovery, straight out of the history book we used to read in school about the War of Independence,'' Nicolaides said in an interview Friday with The Associated Press.</s>

<s docid="AP880521-0088" num="16" wdcount="28"> Nicolaides, who heard about the wreck while teaching an underwater archaeology course to local divers last winter, started querying fishermen about where their nets snagged on seabed obstacles.</s>

<s docid="AP880521-0088" num="17" wdcount="9"> He pinpointed the wreck on May 3, he said.</s>

<s docid="AP880521-0088" num="18" wdcount="35"> ``When I dived, I found ships' timbers sticking out of the muddy seabed and dozens of objects _ Islamic cooking pots, cannon balls, a candlestick, even a chalice from a Greek Orthodox church,'' he said.</s>

<s docid="AP880521-0088" num="19" wdcount="9"> ``The ship was obviously crammed with loot from Chios.</s>

<s docid="AP880521-0088" num="20" wdcount="13"> I think there may be gold and silver items as well,'' he said.</s>

<s docid="AP880521-0088" num="21" wdcount="11"> ``I also saw what I recognized as human bones,'' he added.</s>

<s docid="AP880521-0088" num="22" wdcount="14"> He said the wreckage indicated the vessel was at least 100 feet in length.</s>

<s docid="AP880521-0088" num="23" wdcount="30"> According to historians, more than 1,000 people _ including 400 Greek captives _ were aboard the ship when Kanaris staged his attack in the early hours of June 7, 1822.</s>

<s docid="AP880521-0088" num="24" wdcount="16"> The Greek admiral sailed from the nearby island of Psara, towing a boat stuffed with explosives.</s>

<s docid="AP880521-0088" num="25" wdcount="19"> Its pointed bow was rammed into the mouth of a cannon on the Bourloti Seimaz and a fuse lit.</s>

<s docid="AP880521-0088" num="26" wdcount="15"> The Ottoman commander, Admiral Kara Ali, was killed in the blast that split the ship.</s>

<s docid="AP880521-0088" num="27" wdcount="7"> Kanaris and his crew of Greeks escaped.</s>

<s docid="AP880521-0088" num="28" wdcount="25"> ``This is a very significant, very emotive find, coming from this particular period of history,'' said George Papathanassopoulos, the Culture Ministry's adviser on marine archaeology.</s>

<s docid="AP880521-0088" num="29" wdcount="35"> Papathanassopoulos said the 162-foot water depth at the site will make investigation difficult since underwater archaeology rarely is attempted at depths over 113 feet, but he said, ``This is a ship that must be explored''.</s>

<s docid="AP880521-0088" num="30" wdcount="22"> Nicolaides said he hoped it would be possible to tap American and Turkish expertise to excavate the wreck as an international project.</s>

<s docid="AP880521-0088" num="31" wdcount="29"> American experts from the Institute of Nautical Archaeology at Texas A & M University, working in cooperation with Turkish divers, have pioneered underwater excavation off the Turkish Aegean coast.</s>

<s docid="AP880521-0088" num="32" wdcount="20"> Greek marine archaeologists focus on locating and surveying historic wrecks scattered around the Aegean and rarely carry out excavations .</s>
</TEXT>
</DOC>
