<DOC>
<DOCNO>

<s docid="AP890622-0157" num="1" wdcount="1"> AP890622-0157</s>
</DOCNO>
<FILEID>

<s docid="AP890622-0157" num="2" wdcount="2"> AP-NR-06-22-89 1542EST</s>
</FILEID>
<FIRST>

<s docid="AP890622-0157" num="3" wdcount="6"> u w AM-Bismarck Bjt 06-22 0717</s>
</FIRST>
<SECOND>

<s docid="AP890622-0157" num="4" wdcount="2"> AM-Bismarck, Bjt,700</s>
</SECOND>
<HEAD>

<s docid="AP890622-0157" num="5" wdcount="12"> Nazis Scuttled the Ship, Discover Says; He Leaves Its Fate to Germans</s>
</HEAD>
<HEAD>

<s docid="AP890622-0157" num="6" wdcount="1"> Laserphotos</s>
</HEAD>
<BYLINE>

<s docid="AP890622-0157" num="7" wdcount="3"> By MIKE FEINSILBER</s>
</BYLINE>
<BYLINE>

<s docid="AP890622-0157" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890622-0157" num="9" wdcount="2"> WASHINGTON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890622-0157" num="10" wdcount="39"> A deep-sea inspection of the Bismarck suggests that the most powerful battleship in Adolf Hitler's navy was scuttled by its own crew rather than sunk by the British in a celebrated battle, underwater explorer Robert D. Ballard said Thursday.</s>

<s docid="AP890622-0157" num="11" wdcount="22"> During a 90-minute news conference, Ballard described how he his ocean-crawling robot located the Bismarck ``sitting upright and proud'' two weeks ago.</s>

<s docid="AP890622-0157" num="12" wdcount="25"> Then the American oceanographer, whose father was of British background and whose mother was of German heritage, addressed himself to the German people in German.</s>

<s docid="AP890622-0157" num="13" wdcount="16"> ``I am an underwater explorer, not a treasure hunter,'' he said, translating himself back into English.</s>

<s docid="AP890622-0157" num="14" wdcount="5"> ``We found no human remains.</s>

<s docid="AP890622-0157" num="15" wdcount="6"> We touched nothing and took nothing.</s>

<s docid="AP890622-0157" num="16" wdcount="14"> ... The future of the Bismarck is in the hands of the German people''.</s>

<s docid="AP890622-0157" num="17" wdcount="31"> He said he will disclose its exact location only to Germany so Germans themselves can decide whether to try to raise the ship, which sank after a battle May 27, 1941.</s>

<s docid="AP890622-0157" num="18" wdcount="38"> Ballard, a senior scientist at the Woods Hole Oceanographic Institution in Massachusetts, said structural evidence satisfied him that the Germans scuttled the battleship rather than trying to surrender or allowing her to be sent down by British fire.</s>

<s docid="AP890622-0157" num="19" wdcount="15"> ``Only scuttled ships tend to make it to the bottom in one piece,'' Ballard said.</s>

<s docid="AP890622-0157" num="20" wdcount="11"> ``It appears the crew opened it up along its entire length.</s>

<s docid="AP890622-0157" num="21" wdcount="7"> It was clearly flooded, stem to stern''.</s>

<s docid="AP890622-0157" num="22" wdcount="13"> ``Maybe the Germans didn't want it taken as a war prize,'' he added.</s>

<s docid="AP890622-0157" num="23" wdcount="32"> It is known that two years earlier, Hitler ordered the German pocket battleship Graf Spee scuttled after it was cornered in the neutral port of Montevideo, Uruguay, and attacked by British ships.</s>

<s docid="AP890622-0157" num="24" wdcount="18"> Hitler apparently wanted to keep the British from learning the secrets of the Graf Spee's construction and weapons.</s>

<s docid="AP890622-0157" num="25" wdcount="41"> In the 1941 battle, the Bismarck's main guns were quickly knocked out and the attacking British ships were out of range of her secondary guns, Ballard said, so its was helpless and taking hundreds of hits _ its sinking clearly inevitable.</s>

<s docid="AP890622-0157" num="26" wdcount="15"> Rendered unsteerable by torpedoes dropped by tiny fabric-covered British biplanes, it was unable to escape.</s>

<s docid="AP890622-0157" num="27" wdcount="38"> Asked if the German commander couldn't have surrendered by ceasing fire, Ballard said ``in the fuzz of battle'' in fierce seas it would have been unlikely that the British would have recognized that the Germans were giving up.</s>

<s docid="AP890622-0157" num="28" wdcount="19"> Again, he speculated, perhaps the Germans did not want the ship's technologically advanced equipment to fall into British hands.</s>

<s docid="AP890622-0157" num="29" wdcount="20"> The Bismarck was found by Ballard in more than 15,000 feet of water about 600 miles west of Brest, France.</s>

<s docid="AP890622-0157" num="30" wdcount="11"> He said it was in remarkably good shape, ``elegant, well preserved''.</s>

<s docid="AP890622-0157" num="31" wdcount="28"> Before the battle, British Prime Minister Winston Churchill had left convoys unprotected and thrown all his capital ships in pursuit with a ringing three-word command: ``Sink the Bismarck''!</s>

<s docid="AP890622-0157" num="32" wdcount="9"> Of the Bismarck's 2,200-man crew, only about 115 survived.</s>

<s docid="AP890622-0157" num="33" wdcount="27"> British ships picked up 110 survivors but left with hundreds of German sailors still in the icy waters after spotting what might have been a German U-boat.</s>

<s docid="AP890622-0157" num="34" wdcount="8"> German vessels later rescued only five more survivors.</s>

<s docid="AP890622-0157" num="35" wdcount="11"> The story has been recounted in books, songs and a movie.</s>

<s docid="AP890622-0157" num="36" wdcount="16"> The sinking occurred only eight days after the Bismarck left Gdynia, Poland, for her first operation.</s>

<s docid="AP890622-0157" num="37" wdcount="33"> If unstopped, it could have posed a critical threat to convoys of merchant shipping and undercut British morale at a time when England stood virtually alone against combined German sea and air power.</s>

<s docid="AP890622-0157" num="38" wdcount="40"> The British sent the warship Hood after the Bismarck but within five days of going to sea the Bismarck had sunk the Hood in a three-minute engagement, with the loss of all but three of the vessel's crew of 1,419.</s>

<s docid="AP890622-0157" num="39" wdcount="30"> The Hood was a symbol of British sea power, and its loss stunned the British public and the war government and made sinking the Bismarck a mission of crucial importance.</s>

<s docid="AP890622-0157" num="40" wdcount="16"> Ballard said under laws of the sea, the Bismarck remains the property of the German people.</s>

<s docid="AP890622-0157" num="41" wdcount="38"> The sunken battleship was discovered and photographed by the same remote-controlled robot that Ballard used four years ago to find the wreck of the Titanic, the British passenger liner that sank in 1912 after striking an iceberg .</s>
</TEXT>
</DOC>
