<DOC>
<DOCNO>

<s docid="AP890125-0099" num="1" wdcount="1"> AP890125-0099</s>
</DOCNO>
<FILEID>

<s docid="AP890125-0099" num="2" wdcount="2"> AP-NR-01-25-89 1104EST</s>
</FILEID>
<FIRST>

<s docid="AP890125-0099" num="3" wdcount="5"> r i PM-Austria 01-25 0357</s>
</FIRST>
<SECOND>

<s docid="AP890125-0099" num="4" wdcount="1"> PM-Austria,0368</s>
</SECOND>
<HEAD>

<s docid="AP890125-0099" num="5" wdcount="5"> Parliamentary President Resigns Under Pressure</s>
</HEAD>
<DATELINE>

<s docid="AP890125-0099" num="6" wdcount="3"> VIENNA, Austria (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890125-0099" num="7" wdcount="31"> Leopold Gratz, the president of Parliament and one of the most powerful politicians in the Socialist Party, resigned today over a scandal surrounding the mysterious sinking of ship 12 years ago.</s>

<s docid="AP890125-0099" num="8" wdcount="32"> Gratz, 59, is the second senior Socialist official to step down because of his alleged involvement in the so-called ``Lucona'' scandal, the subject of a widely publicized investigation by a parliamentary committee.</s>

<s docid="AP890125-0099" num="9" wdcount="40"> Interior Minister Karl Blecha, like Gratz a onetime protege of former Chancellor Bruno Kreisky, resigned Jan.19. Blecha and Gratz have denied wrongdoing or aiding Udo Proksch, the prime suspect in the sinking of the ship Lucona in the Indian Ocean.</s>

<s docid="AP890125-0099" num="10" wdcount="3"> Six sailors died.</s>

<s docid="AP890125-0099" num="11" wdcount="19"> The Lucona's cargo was officially described by Proksch as for a uranium processing plant and insured for $16 million.</s>

<s docid="AP890125-0099" num="12" wdcount="25"> The insurance company has never paid, claiming the cargo was only scrap metal and alleging the vessel was intentionally sunk to collect the insurance money.</s>

<s docid="AP890125-0099" num="13" wdcount="26"> Proksch, wanted by Austrian justice on suspicion of murder and insurance fraud, has been variously described to be living in Syria, the Philippines and Latin America.</s>

<s docid="AP890125-0099" num="14" wdcount="22"> In several interviews, Gratz described himself as a close friend of Proksch, but when Proksch fled to escape prosecution, Gratz criticized him.</s>

<s docid="AP890125-0099" num="15" wdcount="25"> Gratz told Parliament today he would give up his seat in February, hence his post as president, one of the most prestigious posts in Austria.</s>

<s docid="AP890125-0099" num="16" wdcount="15"> ``My decision is a personal one and it is politically motivated,'' Gratz told the house.</s>

<s docid="AP890125-0099" num="17" wdcount="52"> ``If it becomes impossible for the president to effectively take a stand on significant issues or to speak up on problems of parliamentarism because everybody is only interested in his context in a single other topic, then he cannot serve the National Council (parliament) in such a way as is his duty''.</s>

<s docid="AP890125-0099" num="18" wdcount="29"> In past newspaper stories, Gratz was accused of providing fabricated evidence from abroad to help Proksch in his claim that the controversial shipment was for a uranium processing plant.</s>

<s docid="AP890125-0099" num="19" wdcount="15"> Gratz, who denied the allegations, was also accused of helping Proksch in several other ways.</s>

<s docid="AP890125-0099" num="20" wdcount="12"> Like Blecha, Gratz is to appear before the parliamentary investigation committee .</s>
</TEXT>
</DOC>
