<DOC>
<DOCNO>

<s docid="AP890820-0068" num="1" wdcount="1"> AP890820-0068</s>
</DOCNO>
<FILEID>

<s docid="AP890820-0068" num="2" wdcount="2"> AP-NR-08-20-89 2232EDT</s>
</FILEID>
<FIRST>

<s docid="AP890820-0068" num="3" wdcount="7"> r a AM-CoupleAdrift 2ndLd-Writethru a0754 08-20 0443</s>
</FIRST>
<SECOND>

<s docid="AP890820-0068" num="4" wdcount="7"> AM-Couple Adrift, 2nd Ld - Writethru, a0754,0450</s>
</SECOND>
<HEAD>

<s docid="AP890820-0068" num="5" wdcount="13"> Couple Says They Survived More Than Two Months At Sea After Whale Attack</s>
</HEAD>
<HEAD>

<s docid="AP890820-0068" num="6" wdcount="30"> Eds: INSERTS 1 graf after 5th graf, ```They were...,' to UPDATE with last known radio contact; SUBS 3rd graf to clarify that couple said they lost 50 pounds each .</s>
</HEAD>
<DATELINE>

<s docid="AP890820-0068" num="7" wdcount="3"> ALAMEDA, Calif. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890820-0068" num="8" wdcount="31"> A Florida couple said their pleasure boat was sunk by whales off Costa Rica and they survived 66 days at sea by eating raw fish and drinking purified water, the U.S.</s>

<s docid="AP890820-0068" num="9" wdcount="4"> Coast Guard reported Sunday.</s>

<s docid="AP890820-0068" num="10" wdcount="34"> William Butler, 60, and Simone Butler, 52, of Miami, were ``weak but recovering'' at a hospital in Golfito, Costa Rica, after being rescued by a Costa Rican Coast Guard ship Saturday afternoon, said U.S.</s>

<s docid="AP890820-0068" num="11" wdcount="7"> Coast Guard Chief Petty Officer Egbert Vallecillo.</s>

<s docid="AP890820-0068" num="12" wdcount="24"> The survivors told authorities they lost about 50 pounds each from the ordeal, said Vallecillo, who spoke to the couple by telephone early Sunday.</s>

<s docid="AP890820-0068" num="13" wdcount="2"> The U.S.</s>

<s docid="AP890820-0068" num="14" wdcount="14"> Coast Guard's Pacific Command is headquartered in Alameda, 10 miles east of San Francisco.</s>

<s docid="AP890820-0068" num="15" wdcount="28"> William Butler told Coast Guard officials their 40-foot pleasure boat Sibonay was attacked and sunk by ``several'' whales on June 15 about 1,200 miles southwest of Costa Rica.</s>

<s docid="AP890820-0068" num="16" wdcount="9"> ``They were large, according to Mr. Butler,'' Vallecillo said.</s>

<s docid="AP890820-0068" num="17" wdcount="7"> ``But he didn't know how many whales''.</s>

<s docid="AP890820-0068" num="18" wdcount="21"> The couple's last radio contact was June 13, when they talked to their daughter in Miami, the Coast Guard spokesman said.</s>

<s docid="AP890820-0068" num="19" wdcount="26"> Vallecillo said he'd heard of boats running into marine mammals when there's poor visibility, but isn't sure if there are any recorded cases of whale aggression.</s>

<s docid="AP890820-0068" num="20" wdcount="12"> ``This happened in the early morning hours'' with good visibility, he said.</s>

<s docid="AP890820-0068" num="21" wdcount="7"> ``This is the first (case) I've documented''.</s>

<s docid="AP890820-0068" num="22" wdcount="33"> As the boat was sinking, the couple said, they grabbed fishing rods and a salt-water purifier and and got into a rubber lifeboat, where they remained for the next two months, Vallecillo said.</s>

<s docid="AP890820-0068" num="23" wdcount="34"> As the lifeboat drifted slowly eastward over two months, the Butlers said, they caught between 400 and 500 pounds of fish and survived multiple shark attacks by sealing punctures with a raft repair kit.</s>

<s docid="AP890820-0068" num="24" wdcount="3"> Butler told U.S.</s>

<s docid="AP890820-0068" num="25" wdcount="18"> Coast Guard officials that several times the couple spotted merchant ships but were unable to flag them down.</s>

<s docid="AP890820-0068" num="26" wdcount="25"> On Saturday, a Coast Guard ship making its ``fisheries'' patrol about 30 miles off the coast of Golfito spotted the raft and rescued the couple.</s>

<s docid="AP890820-0068" num="27" wdcount="18"> They were sailing from Coral Gables, Fla., near Miami, to Honolulu, where they planned to vacation, Vallecillo said.</s>

<s docid="AP890820-0068" num="28" wdcount="7"> Butler is an experienced sailor, he said.</s>

<s docid="AP890820-0068" num="29" wdcount="25"> Their daughter, Sally Smith, and son, Bill Butler, were flying to Costa Rica on Sunday evening to be reunited with their parents, Vallecillo said .</s>
</TEXT>
</DOC>
