<DOC>
<DOCNO>

<s docid="AP890613-0125" num="1" wdcount="1"> AP890613-0125</s>
</DOCNO>
<FILEID>

<s docid="AP890613-0125" num="2" wdcount="2"> AP-NR-06-13-89 1552EST</s>
</FILEID>
<FIRST>

<s docid="AP890613-0125" num="3" wdcount="5"> r a AM-Hitler'sYacht 06-13 0454</s>
</FIRST>
<SECOND>

<s docid="AP890613-0125" num="4" wdcount="2"> AM-Hitler's Yacht,0470</s>
</SECOND>
<HEAD>

<s docid="AP890613-0125" num="5" wdcount="9"> Hitler Yacht Sunk in Wrong Spot, Must Be Moved</s>
</HEAD>
<DATELINE>

<s docid="AP890613-0125" num="6" wdcount="4"> MIAMI BEACH, Fla. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890613-0125" num="7" wdcount="34"> A yacht built for Adolf Hitler and sunk with great fanfare to commemorate the ``Voyage of the Damned'' was mistakenly dropped on a delicate coral reef in a shallow shipping lane, officials said Tuesday.</s>

<s docid="AP890613-0125" num="8" wdcount="13"> ``They're going to have to move it,'' said Coast Guard spokeswoman Veronica Cady.</s>

<s docid="AP890613-0125" num="9" wdcount="22"> The 85-foot Ostwind yacht was supposed to become an artificial reef in 250 feet of water about two miles off the coast.</s>

<s docid="AP890613-0125" num="10" wdcount="10"> It was sunk June 4, 50 years after the U.S.</s>

<s docid="AP890613-0125" num="11" wdcount="21"> Coast Guard turned away the SS St. Louis as its more than 900 Jewish passengers were seeking refuge from the Holocaust.</s>

<s docid="AP890613-0125" num="12" wdcount="30"> The sinking site was supposed to be near where the Coast Guard intercepted the St. Louis, whose passengers also were turned away by Cuba and forced to return to Europe.</s>

<s docid="AP890613-0125" num="13" wdcount="10"> Most of the passengers later died in Nazi concentration camps.</s>

<s docid="AP890613-0125" num="14" wdcount="29"> For unexplained reasons, the Ostwind was pushed off a barge about a mile north of the site, and is resting in 25 feet of water on a living reef.</s>

<s docid="AP890613-0125" num="15" wdcount="12"> ``It was truly an incredible, incredible historic event, and suddenly _ boom!</s>

<s docid="AP890613-0125" num="16" wdcount="18"> _ somebody made a mistake,'' said Mayor Abe Resnick, a Holocaust survivor and a sponsor of the event.</s>

<s docid="AP890613-0125" num="17" wdcount="17"> Federal and Dade County officials who allowed Resnick to sink the boat are upset about the result.</s>

<s docid="AP890613-0125" num="18" wdcount="14"> ``They didn't even come close,'' complained Susan Markely, an administrator with Dade's environmental department.</s>

<s docid="AP890613-0125" num="19" wdcount="21"> Coast Guard Lt. Al Crespo said the yacht is balanced on a delicate living reef, threatening damage to coral and sponges.</s>

<s docid="AP890613-0125" num="20" wdcount="28"> It's also close to an anchoring spot for freighters and other vessels heading to the port of Miami and has been marked with a flashing buoy, he said.</s>

<s docid="AP890613-0125" num="21" wdcount="17"> ``It's close enough that if a ship swings on its anchor, it could hit it,'' Crespo said.</s>

<s docid="AP890613-0125" num="22" wdcount="18"> The Army Corps of Engineers said the Ostwind must be moved or cut to pieces by June 22.</s>

<s docid="AP890613-0125" num="23" wdcount="11"> If it's not, the government will remove it and bill Resnick.</s>

<s docid="AP890613-0125" num="24" wdcount="21"> Resnick blames the mistake on A.M. Daly Jr., captain of the tug that towed the yacht to where it was sunk.</s>

<s docid="AP890613-0125" num="25" wdcount="21"> Daly, however, said Chris Cadley, captain of a passenger boat that accompanied him, had agreed to lead him to the site.</s>

<s docid="AP890613-0125" num="26" wdcount="13"> Cadley denied that, saying he only agreed to meet Daly off the coast.</s>

<s docid="AP890613-0125" num="27" wdcount="7"> Resnick said someone will have to pay.</s>

<s docid="AP890613-0125" num="28" wdcount="19"> ``I think's that's going to end up being decided by attorneys,'' said Ben Mostkoff, the county's artificial reef director.</s>

<s docid="AP890613-0125" num="29" wdcount="12"> The Ostwind was built at Hitler's direction, although he rarely used it.</s>

<s docid="AP890613-0125" num="30" wdcount="19"> After World War II, the badly decayed boat wound up in the hands of a Jacksonville marina owner .</s>
</TEXT>
</DOC>
