<DOC>
<DOCNO>

<s docid="AP890201-0043" num="1" wdcount="1"> AP890201-0043</s>
</DOCNO>
<FILEID>

<s docid="AP890201-0043" num="2" wdcount="2"> AP-NR-02-01-89 0207EST</s>
</FILEID>
<FIRST>

<s docid="AP890201-0043" num="3" wdcount="7"> u i AM-US-AntarcticRescue 3rdLd-Writethru a0435 02-01 0500</s>
</FIRST>
<SECOND>

<s docid="AP890201-0043" num="4" wdcount="7"> AM-US-Antarctic Rescue, 3rd Ld - Writethru, a0435,0512</s>
</SECOND>
<HEAD>

<s docid="AP890201-0043" num="5" wdcount="1"> URGENT</s>
</HEAD>
<HEAD>

<s docid="AP890201-0043" num="6" wdcount="5"> Argentine Ship Sinks Off Antarctica</s>
</HEAD>
<HEAD>

<s docid="AP890201-0043" num="7" wdcount="3"> Eds: REORGANIZES throughout</s>
</HEAD>
<DATELINE>

<s docid="AP890201-0043" num="8" wdcount="4"> BUENOS AIRES, Argentina (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890201-0043" num="9" wdcount="34"> An Argentine supply ship that ran aground off Antarctica sank Tuesday in heavy seas and high winds, the government said, and there was concern oil in its hold could leak and damage the environment.</s>

<s docid="AP890201-0043" num="10" wdcount="12"> The sinking of the 400-foot Bahia Paraiso followed warnings from the U.S.</s>

<s docid="AP890201-0043" num="11" wdcount="24"> National Science Foundation that the unspoiled Antarctic could face ecological disaster if the 250,000 gallons of diesel fuel aboard the ship were to spill.</s>

<s docid="AP890201-0043" num="12" wdcount="7"> No injuries were reported in the sinking.</s>

<s docid="AP890201-0043" num="13" wdcount="24"> Tourists aboard and the crew had been evacuated from the vessel, which was 600 miles south of Cape Horn, the tip of South America.</s>

<s docid="AP890201-0043" num="14" wdcount="9"> Salvage efforts had been hampered by 50 mph winds.</s>

<s docid="AP890201-0043" num="15" wdcount="19"> The double-hulled oceanographic ship sank at about 10 p.m., the government news agency Telam said, citing a navy communique.</s>

<s docid="AP890201-0043" num="16" wdcount="18"> Telam did not say whether the ship broke up or if diesel oil spilled when it went down.</s>

<s docid="AP890201-0043" num="17" wdcount="14"> The depth of the water in which the ship sank was not immediately known.</s>

<s docid="AP890201-0043" num="18" wdcount="38"> The ship had been carrying supplies including jet fuel, gasoline and canisters of compressed gases to the Argentine Esperanza station near the tip of the Antarctic Peninsula, the National Science Foundation said in a statement released in Washington.</s>

<s docid="AP890201-0043" num="19" wdcount="22"> The ship ran aground Saturday about two miles from Palmer Station, a U.S. research facility on the Antarctic Peninsula, the continent's tip.</s>

<s docid="AP890201-0043" num="20" wdcount="24"> It sustained a 35-foot-long gash in its hull, and some of the 250,000 gallons of diesel fuel began leaking, washing ashore near Palmer station.</s>

<s docid="AP890201-0043" num="21" wdcount="35"> The fuel killed some krill, a tiny shrimp-like creature that is a vital part of the Antarctic food chain, and has affected penguins, sea gulls and giant petrel birds, the National Science Foundation statement said.</s>

<s docid="AP890201-0043" num="22" wdcount="17"> There were no immediate details about the extent of damage to the wildlife in the pristine surroundings.</s>

<s docid="AP890201-0043" num="23" wdcount="22"> Agency spokesman Jack Renerie said Tuesday before the ship sank that the leak, which was threatening penguins and other wildlife, had stopped.</s>

<s docid="AP890201-0043" num="24" wdcount="20"> ``Scientists are concerned that some research search projects may already have been affected by the leak,'' a foundation statement said.</s>

<s docid="AP890201-0043" num="25" wdcount="13"> It said two Argentine salvage vessels were expected to arrive Thursday or Friday.</s>

<s docid="AP890201-0043" num="26" wdcount="9"> Before the sinking, Argentine officials had discounted a spill.</s>

<s docid="AP890201-0043" num="27" wdcount="28"> Telam quoted Argentine navy sources as saying: ``The fuel it carried, both for itself and the Antarctic stations, was in steel drums so a spill is practically impossible''.</s>

<s docid="AP890201-0043" num="28" wdcount="27"> The 316 people aboard the ship when it ran aground, including 82 passengers and 234 crew members, were rescued by power boats and taken to Palmer Station.</s>

<s docid="AP890201-0043" num="29" wdcount="28"> The passengers and most of the crew were taken by cruise ship to the South Shetland Islands, from which they were airlifted to the South American mainland Sunday.</s>

<s docid="AP890201-0043" num="30" wdcount="9"> But 104 crewmen remain at the station, said Renerie.</s>

<s docid="AP890201-0043" num="31" wdcount="25"> Because the station is equipped for only 40 people, food has been rationed to two meals a day, a National Science Foundation statement said .</s>
</TEXT>
</DOC>
