<DOC>
<DOCNO>

<s docid="AP890417-0189" num="1" wdcount="1"> AP890417-0189</s>
</DOCNO>
<FILEID>

<s docid="AP890417-0189" num="2" wdcount="2"> AP-NR-04-17-89 1941EST</s>
</FILEID>
<FIRST>

<s docid="AP890417-0189" num="3" wdcount="7"> u a AM-FounderingShip 1stLd-Writethru a0729 04-17 0379</s>
</FIRST>
<SECOND>

<s docid="AP890417-0189" num="4" wdcount="5"> AM-Foundering Ship, 1st Ld-Writethru, a0729,0389</s>
</SECOND>
<HEAD>

<s docid="AP890417-0189" num="5" wdcount="7"> Two Missing After Cargo Ship Apparently Sinks</s>
</HEAD>
<HEAD>

<s docid="AP890417-0189" num="6" wdcount="16"> Eds: UPDATES throughout with two sailors missing, details on sinking, rescue, ship, other details; no pickup.</s>

<s docid="AP890417-0189" num="7" wdcount="11"> Clarifies that survivors were found on lifeboat, sted life raft .</s>
</HEAD>
<BYLINE>

<s docid="AP890417-0189" num="8" wdcount="3"> By JOHN DIAMOND</s>
</BYLINE>
<BYLINE>

<s docid="AP890417-0189" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890417-0189" num="10" wdcount="2"> BOSTON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890417-0189" num="11" wdcount="25"> Two sailors were missing Monday evening after a 652-foot freighter en route from Greece apparently sank in rough seas 400 miles southeast of Cape Cod.</s>

<s docid="AP890417-0189" num="12" wdcount="5"> Twenty-three crew members were rescued.</s>

<s docid="AP890417-0189" num="13" wdcount="31"> The 23 sailors from the Star of Alexandria were found on a lifeboat and picked up by the merchant ship Ravenscraig, Coast Guard Petty Officer Randy Midgett said in New York.</s>

<s docid="AP890417-0189" num="14" wdcount="12"> ``They're all in good shape, some minor cuts and scrapes,'' Midgett said.</s>

<s docid="AP890417-0189" num="15" wdcount="35"> The two missing sailors were believed to be on a life raft, which was the object of a hunt Monday evening by the 950-foot Ravenscraig and five Navy and Coast Guard search planes, officials said.</s>

<s docid="AP890417-0189" num="16" wdcount="15"> The Ravenscraig's crew spotted a second life raft, but it turned out to be empty.</s>

<s docid="AP890417-0189" num="17" wdcount="11"> The cause of the sinking was not immediately known, officials said.</s>

<s docid="AP890417-0189" num="18" wdcount="36"> The Star of Alexandria had been en route from Athens, Greece, to New York with a load of cement when it began taking on water in 12-foot seas and winds up to 35 mph, Midgett said.</s>

<s docid="AP890417-0189" num="19" wdcount="32"> The first mayday call went out at 9:05 a.m. A Coast Guard jet from the air station on Cape Cod and a C-130 plane from Elizabeth City, N.C., converged on the ship.</s>

<s docid="AP890417-0189" num="20" wdcount="6"> The lifeboat was spotted around noon.</s>

<s docid="AP890417-0189" num="21" wdcount="28"> The C-130 was able to drop a radio into the water near the boat carrying the 23 crew members and they were able to establish communications, Midgett said.</s>

<s docid="AP890417-0189" num="22" wdcount="10"> About four hours later, they were rescued by the Ravenscraig.</s>

<s docid="AP890417-0189" num="23" wdcount="17"> The Star of Alexandria was not spotted, and was presumed to be sinking or sunk, Midgett said.</s>

<s docid="AP890417-0189" num="24" wdcount="12"> Visibility in the rough seas was five to eight miles Monday afternoon.</s>

<s docid="AP890417-0189" num="25" wdcount="13"> The Star of Alexandria was built in 1966, and was registered in England.</s>

<s docid="AP890417-0189" num="26" wdcount="24"> It was designed to carry bulk freight, and was owned by Caribene Investments Ltd. of Gibraltar, according to Bureau Veritas, a Paris-based shipping registry.</s>

<s docid="AP890417-0189" num="27" wdcount="19"> The Ravenscraig had been bound for England, but its destination after its rescue mission was not immediately known .</s>
</TEXT>
</DOC>
