<DOC>
<DOCNO>

<s docid="FBIS4-57796" num="1" wdcount="1"> FBIS4-57796</s>
</DOCNO>
<HT>

<s docid="FBIS4-57796" num="2" wdcount="1"> "drlat101_k_94003"</s>
</HT>
<HEADER>
<AU>

<s docid="FBIS4-57796" num="3" wdcount="1"> FBIS-LAT-94-101</s>
</AU>

<s docid="FBIS4-57796" num="4" wdcount="2"> Daily Report</s>
<DATE1>

<s docid="FBIS4-57796" num="5" wdcount="3"> 23 May 1994</s>
</DATE1>
</HEADER>
<F>

<s docid="FBIS4-57796" num="6" wdcount="2"> SOUTH AMERICA</s>
</F>
<F>

<s docid="FBIS4-57796" num="7" wdcount="1"> Argentina</s>
</F>
<H3>
<TI>

<s docid="FBIS4-57796" num="8" wdcount="9"> Navy Says Fishing Boat `Sunk by Its Own Crew'</s>
</TI>
</H3>
<HT>
<F>
<PHRASE>

<s docid="FBIS4-57796" num="9" wdcount="9"> Navy Says Fishing Boat `Sunk by Its Own Crew'</s>
</PHRASE>
</F>
</HT>
<F>

<s docid="FBIS4-57796" num="10" wdcount="12"> PY2405133394 Buenos Aires NOTICIAS ARGENTINAS in Spanish 0113 GMT 23 May 94</s>
</F>
<F>

<s docid="FBIS4-57796" num="11" wdcount="1"> PY2405133394</s>
</F>
<F>

<s docid="FBIS4-57796" num="12" wdcount="4"> Buenos Aires NOTICIAS ARGENTINAS</s>
</F>
<F>

<s docid="FBIS4-57796" num="13" wdcount="1"> Spanish</s>
</F>
<TEXT>

<s docid="FBIS4-57796" num="14" wdcount="48"> BFN [Text] Buenos Aires, 23 May (NA) -- Today, the Foreign Ministry said that control operations carried out by the corvette Spiro against a Korean-flagged [as received] ship fishing illegally in Argentine waters were carried out "in accordance with international law and in coordination with the Foreign Ministry".</s>

<s docid="FBIS4-57796" num="15" wdcount="27"> The Foreign Ministry thus approved the intervention by the Argentine corvette when it discovered the Korean ship Chin Yuan Hsing violating Argentine jurisdictional waters on 21 May.</s>

<s docid="FBIS4-57796" num="16" wdcount="28"> The Argentine Navy reported today that the corvette Spiro stayed near the Korean ship "given the adverse weather conditions, and fulfilling its responsibilities of sea search and rescue".</s>

<s docid="FBIS4-57796" num="17" wdcount="26"> The Korean ship, which had been fishing illegally in Argentine waters, was sunk by its own crew after failing to answer to the Argentine ship's warnings.</s>

<s docid="FBIS4-57796" num="18" wdcount="23"> The crew was transferred to the Chin Chuan Hsing, which was sailing nearby and approached to rescue the crew of the sinking ship.</s>

<s docid="FBIS4-57796" num="19" wdcount="30"> The Navy reported that around 15 nautical miles off the coast of Malvinas and "in accordance with bilateral agreements with Great Britain, the Spiro transferred assistance responsibility to British authorities".</s>

<s docid="FBIS4-57796" num="20" wdcount="22"> The Foreign Ministry said "an understanding with the UK for operations in cases of uninterrupted persecution of illegally fishing ships was implemented".</s>

<s docid="FBIS4-57796" num="21" wdcount="43"> The Foreign Ministry also said the policy "is in accordance with the growing international opinion currently giving priority to the preservation, regulation, and the sustainable use of marine live resources and the effective punishment of violators of national laws on the matter" .</s>
</TEXT>
</DOC>
