<DOC>
<DOCNO>

<s docid="FT943-178" num="1" wdcount="1"> FT943-178</s>
</DOCNO>
<PROFILE>

<s docid="FT943-178" num="2" wdcount="1"> _AN-EI3DUAD5FT</s>
</PROFILE>
<DATE>

<s docid="FT943-178" num="3" wdcount="1"> 940930</s>
</DATE>
<HEADLINE>

<s docid="FT943-178" num="4" wdcount="11"> FT 30 SEP 94 / Leading Article: Defying the cruel sea</s>
</HEADLINE>
<TEXT>

<s docid="FT943-178" num="5" wdcount="7"> Ferries are among the safest vessels afloat.</s>

<s docid="FT943-178" num="6" wdcount="30"> But, as the tragic sinking of the Estonia with the loss of more than 800 lives demonstrates, when they do go down the toll in human life can be high.</s>

<s docid="FT943-178" num="7" wdcount="21"> As ferries increase in size, so the numbers on board at risk from mechanical failure or a crew error go up.</s>

<s docid="FT943-178" num="8" wdcount="46"> The move to roll-on roll-off ferries with vehicle decks which run the entire length of the vessel has increased the risk that, once the sea penetrates the hold through the bow doors or a gash in the ship's side, it can lead to the vessel capsizing.</s>

<s docid="FT943-178" num="9" wdcount="25"> The United Nations International Maritime Organisation (IMO) and its members, the ship-owning nations, have devoted much thought over the past two decades to ship safety.</s>

<s docid="FT943-178" num="10" wdcount="15"> But the sinking of the Estonia should lead to a new review of ferry safety.</s>

<s docid="FT943-178" num="11" wdcount="29"> Particularly worrying are the eyewitness reports which suggest that water penetrated the bow doors in a manner reminiscent of the sinking of the Herald of Free Enterprise in 1987.</s>

<s docid="FT943-178" num="12" wdcount="21"> Unlike the Herald, the Estonia appears to have had its doors closed, but ro-ros are undoubtedly very vulnerable to water penetration.</s>

<s docid="FT943-178" num="13" wdcount="11"> Any review of ferry safety should focus on three main issues.</s>

<s docid="FT943-178" num="14" wdcount="9"> First the subject of ferry design should be reconsidered.</s>

<s docid="FT943-178" num="15" wdcount="23"> Additional stability could be provided by the addition of sponsons, stabilising bulges which project from the ship's side just above the water line.</s>

<s docid="FT943-178" num="16" wdcount="23"> Greater resistance to an influx of water could be obtained by installing moveable barriers or bulkheads to break up the large car decks.</s>

<s docid="FT943-178" num="17" wdcount="21"> These proposals were looked at by the British government in the wake of the sinking of the Herald of Free Enterprise.</s>

<s docid="FT943-178" num="18" wdcount="34"> It calculated that it would cost between Pounds 70m and Pounds 85m to improve standards on the 57 vessels in the UK ferry fleet, with a further Pounds 22m in extra annual running costs.</s>

<s docid="FT943-178" num="19" wdcount="26"> Higher costs would inevitably lead to higher fares - unwelcome to ferry operators when, on the short cross-Channel routes, they face competition from the Channel tunnel.</s>

<s docid="FT943-178" num="20" wdcount="21"> But the difficulty of pushing through fare rises would be nothing like as damaging to the ferry companies as another disaster.</s>

<s docid="FT943-178" num="21" wdcount="17"> Second, the IMO and national governments must look closely at how to improve enforcement of existing regulations.</s>

<s docid="FT943-178" num="22" wdcount="24"> The IMO has been trying to move enforcement up its agenda, but it depends on the good will and professionalism of governments and shipowners.</s>

<s docid="FT943-178" num="23" wdcount="19"> Third, the IMO should be given support by national governments in its campaign, launched yesterday, to improve crew training.</s>

<s docid="FT943-178" num="24" wdcount="16"> Much of the regulation in recent years has concentrated on improving the ship and its equipment.</s>

<s docid="FT943-178" num="25" wdcount="16"> Above all, if new regulation does turn out to be necessary, it must be introduced speedily.</s>

<s docid="FT943-178" num="26" wdcount="18"> As things stand, it can take years before changes are ratified by enough governments to give them force.</s>

<s docid="FT943-178" num="27" wdcount="21"> The European Union, which Sweden and Finland are getting ready to join, could take a lead in speeding up the process.</s>

<s docid="FT943-178" num="28" wdcount="13"> Ship safety is not, of course, just an issue for the ferry sector.</s>

<s docid="FT943-178" num="29" wdcount="11"> Five (small) ferries were lost last year, according to Lloyd's Register.</s>

<s docid="FT943-178" num="30" wdcount="20"> But this figure pales into insignificance compared with the 96 general cargo ships and 12 tankers which also went down.</s>

<s docid="FT943-178" num="31" wdcount="19"> When a cargo vessel with a third-world crew goes down in a distant ocean, very little attention is paid.</s>

<s docid="FT943-178" num="32" wdcount="39"> If the loss of a relatively modern passenger vessel in European waters can make shipping safety a higher priority for governments and the public, this will be some small compensation for the loss of life from the Estonia .</s>
</TEXT>
<XX>

<s docid="FT943-178" num="33" wdcount="1"> Countries:-</s>
</XX>
<CN>

<s docid="FT943-178" num="34" wdcount="4"> EEZ Estonia, East Europe.</s>

<s docid="FT943-178" num="35" wdcount="5"> GBZ United Kingdom, EC .</s>
</CN>
<XX>

<s docid="FT943-178" num="36" wdcount="1"> Industries:-</s>
</XX>
<IN>

<s docid="FT943-178" num="37" wdcount="5"> P9621 Regulation, Administration of Transportation.</s>

<s docid="FT943-178" num="38" wdcount="3"> P4482 Ferries .</s>
</IN>
<XX>

<s docid="FT943-178" num="39" wdcount="1"> Types:-</s>
</XX>
<TP>

<s docid="FT943-178" num="40" wdcount="4"> CMMT Comment & Analysis.</s>

<s docid="FT943-178" num="41" wdcount="5"> TECH Safety & Standards .</s>
</TP>
<PUB>

<s docid="FT943-178" num="42" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT943-178" num="43" wdcount="3"> London Page 19</s>
</PAGE>
</DOC>
