<DOC>
<DOCNO>

<s docid="AP880729-0155" num="1" wdcount="1"> AP880729-0155</s>
</DOCNO>
<FILEID>

<s docid="AP880729-0155" num="2" wdcount="2"> AP-NR-07-29-88 1643EDT</s>
</FILEID>
<FIRST>

<s docid="AP880729-0155" num="3" wdcount="5"> r i AM-Soviet-Ethnic 07-29 0593</s>
</FIRST>
<SECOND>

<s docid="AP880729-0155" num="4" wdcount="1"> AM-Soviet-Ethnic,0607</s>
</SECOND>
<HEAD>

<s docid="AP880729-0155" num="5" wdcount="9"> Gorbachev Proposes Tougher Legislation to Punish Promoters of Nationalism</s>
</HEAD>
<BYLINE>

<s docid="AP880729-0155" num="6" wdcount="3"> By JOHN-THOR DAHLBURG</s>
</BYLINE>
<BYLINE>

<s docid="AP880729-0155" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880729-0155" num="8" wdcount="2"> MOSCOW (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880729-0155" num="9" wdcount="25"> Mikhail S. Gorbachev on Friday proposed tougher legislation to punish Soviets who seek to kindle ethnic unrest, saying ``nationalist passions'' benefit opponents of his reforms.</s>

<s docid="AP880729-0155" num="10" wdcount="35"> The Soviet leader told a meeting of the Communist Party leadership that inter-ethnic relations were worsening in some regions of the country, due in part to ``active resistance put up to perestroika by corrupt groups''.</s>

<s docid="AP880729-0155" num="11" wdcount="12"> ``Perestroika,'' or restructuring, is Gorbachev's program for widespread economic and social change.</s>

<s docid="AP880729-0155" num="12" wdcount="31"> State-run media also indicated Friday that a crackdown had begun on people in Armenia who continue to agitate for annexation of a mostly Armenian enclave in the neighboring republic of Azerbaijan.</s>

<s docid="AP880729-0155" num="13" wdcount="24"> The six-month conflict between the two republics over control of the Nagorno-Karabakh district has led to mass rallies, strikes and ethnic violence since February.</s>

<s docid="AP880729-0155" num="14" wdcount="12"> The Supreme Soviet Presidium, the government's top executive body, intervened July 18.</s>

<s docid="AP880729-0155" num="15" wdcount="18"> It rejected any change in Nagorno-Karabakh's status but called for measures to develop the region's economy and culture.</s>

<s docid="AP880729-0155" num="16" wdcount="24"> The conflict over Nagorno-Karabakh is one of the most rancorous domestic disputes faced by Gorbachev since he became Communist Party chief in March 1985.</s>

<s docid="AP880729-0155" num="17" wdcount="24"> He indicated Friday he wants to defuse tensions between ethnic groups, but also to punish those who transform the tensions into a political crisis.</s>

<s docid="AP880729-0155" num="18" wdcount="14"> Gorbachev spoke before a plenary meeting of the Central Committee, the party's policy-making body.</s>

<s docid="AP880729-0155" num="19" wdcount="13"> A summary of his remarks was distributed by the official Tass news agency.</s>

<s docid="AP880729-0155" num="20" wdcount="22"> Gorbachev outlined the reasons for a ``current aggravation'' of tensions between ethnic groups in some regions of the Soviet Union, Tass said.</s>

<s docid="AP880729-0155" num="21" wdcount="42"> Among the causes, Gorbachev listed ``a lack of concern for many years for the specific requirements of peoples and ethnic groups, inadequate control by the masses over the activities of executive personnel, and active resistance put up to perestroika by corrupt groups''.</s>

<s docid="AP880729-0155" num="22" wdcount="24"> Tass said that after Gorbachev noted that ``nationalist passions benefit all anti-perestroika forces,'' he suggested increasing accountability in Soviet laws for kindling ethnic strife.</s>

<s docid="AP880729-0155" num="23" wdcount="8"> Tass did not give details of Gorbachev's suggestion.</s>

<s docid="AP880729-0155" num="24" wdcount="23"> At the July 18 Presidium meeting, the Soviet leader accused corrupt conservatives who oppose his reforms of hiding behind the Nagorno-Karabakh annexation drive.</s>

<s docid="AP880729-0155" num="25" wdcount="33"> Gorbachev said the grounds for tougher legislation come directly from Article 36 of the 1977 Soviet Constitution, which says the law can punish ``any advocacy of racial or national exclusiveness, hostility or contempt''.</s>

<s docid="AP880729-0155" num="26" wdcount="50"> Tass said Gorbachev made other proposals on how to resolve ethnic tensions, including an increase in power for each of the country's 15 republics, a law on ``equal use'' of the more than 100 languages spoken in the Soviet Union and some economic autonomy for the country's republics and regions.</s>

<s docid="AP880729-0155" num="27" wdcount="29"> In particular, the Baltic republics of Lithuania, Latvia and Estonia, forcibly incorporated into the Soviet Union in 1940, have demanded more say in their own economic and government affairs.</s>

<s docid="AP880729-0155" num="28" wdcount="36"> The labor newspaper Trud said 44 people in Yerevan, Armenia's capital, will face criminal charges following an incident in which activists seeking the annexation of Nagorno-Karabakh attached slogans to their cars and drove around the city.</s>

<s docid="AP880729-0155" num="29" wdcount="26"> The paper did not give the date or size of the mobile demonstration, but said 155 drivers have had their licenses revoked and 310 were fined.</s>

<s docid="AP880729-0155" num="30" wdcount="23"> In its July 18th decision, the Presidium also ordered local law enforcement agencies to ensure order was restored in the Caucasus Mountain region.</s>

<s docid="AP880729-0155" num="31" wdcount="25"> Tass reported Friday that the situation was stabilizing in Armenia, but said that at the ``urging of instigators,'' some strikes and protests were continuing .</s>
</TEXT>
</DOC>
