<DOC>
<DOCNO>

<s docid="AP891213-0164" num="1" wdcount="1"> AP891213-0164</s>
</DOCNO>
<FILEID>

<s docid="AP891213-0164" num="2" wdcount="2"> AP-NR-12-13-89 1711EST</s>
</FILEID>
<FIRST>

<s docid="AP891213-0164" num="3" wdcount="5"> u i AM-Soviet-Germans 12-13 0536</s>
</FIRST>
<SECOND>

<s docid="AP891213-0164" num="4" wdcount="1"> AM-Soviet-Germans,0549</s>
</SECOND>
<HEAD>

<s docid="AP891213-0164" num="5" wdcount="10"> German, Crimean Tatars to Get Own Soviet Regions _ Eventually</s>
</HEAD>
<BYLINE>

<s docid="AP891213-0164" num="6" wdcount="3"> By CAREY GOLDBERG</s>
</BYLINE>
<BYLINE>

<s docid="AP891213-0164" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP891213-0164" num="8" wdcount="2"> MOSCOW (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP891213-0164" num="9" wdcount="32"> The government has decided to give ethnic Germans and Crimean Tatars who were expelled from their homelands by Josef Stalin their own autonomous regions but it will take years, Tass reported Wednesday.</s>

<s docid="AP891213-0164" num="10" wdcount="5"> ``The ice has been broken.</s>

<s docid="AP891213-0164" num="11" wdcount="5"> A start has been made.</s>

<s docid="AP891213-0164" num="12" wdcount="25"> We're working on creating such autonomy,'' said Rafik Nishanov, chairman of a chamber of the Soviet legislature, in remarks carried by the official news agency.</s>

<s docid="AP891213-0164" num="13" wdcount="19"> However, he said, the nuts and bolts of how to create the regions still had to be worked out.</s>

<s docid="AP891213-0164" num="14" wdcount="7"> ``For example, a 10-year program on resettlement.</s>

<s docid="AP891213-0164" num="15" wdcount="13"> People can't just be expelled from the area for others to move in''.</s>

<s docid="AP891213-0164" num="16" wdcount="43"> The Tatars of the Crimea and the ethnic Germans who lived on the Volga River were forcibly resettled during World War II, when Josef Stalin kicked peoples out of their homelands on the grounds they could not be trusted to occupy strategic areas.</s>

<s docid="AP891213-0164" num="17" wdcount="40"> The Tatars and Germans, among others, long have been agitating to return from Siberia and Central Asia to their traditional lands, and last month the Supreme Soviet legislature declared that all peoples exiled under Stalin should be considered politically rehabilitated.</s>

<s docid="AP891213-0164" num="18" wdcount="27"> But other people now occupy the lands and houses that belonged to the exiles, and re-establishing their dominion in their home regions will not be so simple.</s>

<s docid="AP891213-0164" num="19" wdcount="34"> The Supreme Soviet took the basic decision that the two autonmous regions should be created on Nov. 28 but kept it quiet, apparently fearing explosive reactions from the populations now living in the regions.</s>

<s docid="AP891213-0164" num="20" wdcount="27"> It was also a potentially dangerous precedent: The Soviet Union is a patchwork of well over 100 ethnic groups, and many of them have outstanding territorial claims.</s>

<s docid="AP891213-0164" num="21" wdcount="16"> Trouble already has been reported between ethnic Germans and Russians in several cities on the Volga.</s>

<s docid="AP891213-0164" num="22" wdcount="24"> Residents of the Saratov and Volgograd regions have protested the prospect of seeing many of the nation's estimated 2 million Germans descending on them.</s>

<s docid="AP891213-0164" num="23" wdcount="18"> Ethnographers estimate there are some 500,000 Crimean Tatars in the Soviet Union, and another 1 million in Turkey.</s>

<s docid="AP891213-0164" num="24" wdcount="25"> Their protests near the Kremlin in 1987 demanding to be allowed to return to their homeland were among the first tests of President Mikhail S.</s>

<s docid="AP891213-0164" num="25" wdcount="5"> Gorbachev's promises of greater democracy.</s>

<s docid="AP891213-0164" num="26" wdcount="20"> Several thousand Tatars have been filtering back to the Crimea each year despite the lack of wholesale permission to return.</s>

<s docid="AP891213-0164" num="27" wdcount="42"> A wave of some 100,000 ethnic Germans emigrated to West Germany this year, but many would probably stay if they could be assured of their own republic, said Irina Ostroukh, a researcher at the Soviet Institute of Ethnography who studies ethnic Germans.</s>

<s docid="AP891213-0164" num="28" wdcount="29"> The Nov. 28 plan approved by the Supreme Soviet recommended excluding from the German region areas where resistance to German resettlement was strongest in order to avoid ethnic conflicts.</s>

<s docid="AP891213-0164" num="29" wdcount="27"> The explosive conflict between Armenians and Azerbaijanis over the Nagorno-Karabakh region has led to 200 deaths and hundreds of thousands of refugees in the last two years.</s>

<s docid="AP891213-0164" num="30" wdcount="8"> Both sides claim control over the mountainous enclave.</s>

<s docid="AP891213-0164" num="31" wdcount="24"> The Supreme Soviet charged the government with creating a commmission to determine how to create the regions for the Germans and Crimean Tatars .</s>
</TEXT>
</DOC>
