<DOC>
<DOCNO>

<s docid="AP900613-0195" num="1" wdcount="1"> AP900613-0195</s>
</DOCNO>
<FILEID>

<s docid="AP900613-0195" num="2" wdcount="2"> AP-NR-06-13-90 2337EDT</s>
</FILEID>
<FIRST>

<s docid="AP900613-0195" num="3" wdcount="5"> r i AM-Soviet-Unrest 06-13 0268</s>
</FIRST>
<SECOND>

<s docid="AP900613-0195" num="4" wdcount="1"> AM-Soviet-Unrest,0275</s>
</SECOND>
<HEAD>

<s docid="AP900613-0195" num="5" wdcount="7"> Soviets Say 148 Died in Kirghizia Unrest</s>
</HEAD>
<DATELINE>

<s docid="AP900613-0195" num="6" wdcount="2"> MOSCOW (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900613-0195" num="7" wdcount="24"> Ethnic violence killed 148 people and wounded 885 this month in the Central Asian republic of Kirghizia, the official news agency Tass said Wednesday.</s>

<s docid="AP900613-0195" num="8" wdcount="24"> Tass said 748 of the injured had to be hospitalized and said a search was continuing for a police officer who vanished June 7.</s>

<s docid="AP900613-0195" num="9" wdcount="36"> No new outbreaks were reported in the region near the border city of Osh in western Kirghizia, where clashes arising from a land dispute began on June 2 between ethnic Kirghiz and Uzbeks, both Sunni Moslems.</s>

<s docid="AP900613-0195" num="10" wdcount="15"> The argument involves allocation of land in a densly populated region where housing is scarce.</s>

<s docid="AP900613-0195" num="11" wdcount="16"> It was the latest in a series of bloody civil conflicts to trouble President Mikhail S.</s>

<s docid="AP900613-0195" num="12" wdcount="2"> Gorbachev's government.</s>

<s docid="AP900613-0195" num="13" wdcount="34"> Maj. Gen. Alexander Grienko, chief of the Interior Ministry's Political Department, said that in two years of civil strife _ mainly ethnic clashes _ in the Soviet Union, about 24,000 people have been arrested.</s>

<s docid="AP900613-0195" num="14" wdcount="26"> He said in Moscow on Tuesday that ministry troops had to be used in 13 regions of the Soviet Union because of such outbreaks, Tass said.</s>

<s docid="AP900613-0195" num="15" wdcount="16"> Grienko said 16 ministry soldiers were killed, four were reported missing and more than 1,000 wounded.</s>

<s docid="AP900613-0195" num="16" wdcount="9"> Tass did not quote Grienko on how civilians casualties.</s>

<s docid="AP900613-0195" num="17" wdcount="29"> The general was quoted as saying these conflicts ``were often accompanied by riots and pogroms, arson and massacre of innocent people, (and) complete or partial destabilization of the situation''.</s>

<s docid="AP900613-0195" num="18" wdcount="25"> Besides unrest this month in Kirghizia and Uzbekistan, ethnic violence also has been reported in recent years in Georgia, Armenia, Azerbaijan, Kazakhstan and Tadzhikistan .</s>
</TEXT>
</DOC>
