<DOC>
<DOCNO>

<s docid="AP901230-0022" num="1" wdcount="1"> AP901230-0022</s>
</DOCNO>
<FILEID>

<s docid="AP901230-0022" num="2" wdcount="2"> AP-NY-12-30-90 1601EST</s>
</FILEID>
<FIRST>

<s docid="AP901230-0022" num="3" wdcount="5"> u i AM-Soviet-Moldavia 12-30 0420</s>
</FIRST>
<SECOND>

<s docid="AP901230-0022" num="4" wdcount="1"> AM-Soviet-Moldavia,0468</s>
</SECOND>
<HEAD>

<s docid="AP901230-0022" num="5" wdcount="6"> Moldavian Parliament Agrees to Gorbachev's Measures</s>
</HEAD>
<DATELINE>

<s docid="AP901230-0022" num="6" wdcount="2"> MOSCOW (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP901230-0022" num="7" wdcount="31"> Moldavia, acting to defuse one of the Soviet Union's most explosive ethnic conflicts, agreed Sunday to comply with a Kremlin order to reconsider its law making Moldavian the republic's official language.</s>

<s docid="AP901230-0022" num="8" wdcount="24"> The republic's parliament acted in response to a decree issued on Dec. 22 by President Mikhail S. Gorbachev, the official news agency Tass reported.</s>

<s docid="AP901230-0022" num="9" wdcount="29"> Gorbachev also gave the republic 10 days to dissolve a new national guard and to come up with measures guaranteeing equal rights for all ethnic groups within its borders.</s>

<s docid="AP901230-0022" num="10" wdcount="23"> Tass said the Moldavan parliament agreed to disband the nationalguard and to revise a law that Gorbachev said restricted the rights of minorities.</s>

<s docid="AP901230-0022" num="11" wdcount="22"> Ethnic tension has gripped Moldavia, a largely agricultural republic bordering Romania, during its push for independence from the Soviet Union this year.</s>

<s docid="AP901230-0022" num="12" wdcount="15"> The unrest turned violent last month, when government troops clashed with activists, leaving four dead.</s>

<s docid="AP901230-0022" num="13" wdcount="27"> Gorbachev said the conflicts had reached ``critical levels,'' and he put part of the blame on the Moldavian Supreme Soviet for enacting laws that discriminate against minorities.</s>

<s docid="AP901230-0022" num="14" wdcount="17"> Alarmed by rising Moldavian nationalism, two of the republic's minority groups have begun their own separatist movements.</s>

<s docid="AP901230-0022" num="15" wdcount="16"> The Gagauz, a group of about 150,000 Turkish Christians, declared a new republic in southern Moldavia.</s>

<s docid="AP901230-0022" num="16" wdcount="24"> In the eastern part of Moldavia, more than 300,000 ethnic Russians and Ukrainians have joined in declaring a new republic along the Dneister River.</s>

<s docid="AP901230-0022" num="17" wdcount="7"> All three groups claim discrimination by Moldavians.</s>

<s docid="AP901230-0022" num="18" wdcount="31"> In particular, they resent a new law making Moldavian the official language and requiring people in dozens of jobs ranging from doctors to hairdressers to pass Moldavian language tests by 1995.</s>

<s docid="AP901230-0022" num="19" wdcount="12"> Tass did not say how the Moldavian parliament would modify the law.</s>

<s docid="AP901230-0022" num="20" wdcount="16"> Moldavian is identical to Romanian except for the Cyrillic script Josef Stalin imposed on the republic.</s>

<s docid="AP901230-0022" num="21" wdcount="9"> It is spoken by two-thirds of the republic's residents.</s>

<s docid="AP901230-0022" num="22" wdcount="23"> Soviet hard-liners want Gorbachev to impose a state of emergency and presidential rule in troubled zones throughout the ethnically and geographically diverse country.</s>

<s docid="AP901230-0022" num="23" wdcount="30"> Gorbachev said the declaration of the Gagauz and Dniester republics was illegal under the Soviet and Moldavian constitutions, as were elections to form legislatures and any actions by those bodies.</s>

<s docid="AP901230-0022" num="24" wdcount="13"> The Moldavian legislature has also voted to declare the elections null and void.</s>

<s docid="AP901230-0022" num="25" wdcount="37"> After residents of the Gagauz region began holding local elections in late October, the Moldavian legislature clamped a two-month state of emergency on the region, restricting movement in and out of the area and banning public rallies.</s>

<s docid="AP901230-0022" num="26" wdcount="24"> Volunteer brigades of college-age Moldavians, who then flocked to the region to try to stop the separatist movement, were ordered dissolved by Gorbachev's decree.</s>

<s docid="AP901230-0022" num="27" wdcount="13"> The volunteers were organized by nationalist groups, including the Moldavian People's Front .</s>
</TEXT>
</DOC>
