<DOC>
<DOCNO>

<s docid="FBIS4-62505" num="1" wdcount="1"> FBIS4-62505</s>
</DOCNO>
<HT>

<s docid="FBIS4-62505" num="2" wdcount="1"> "drsov095_m_94006"</s>
</HT>
<HEADER>
<AU>

<s docid="FBIS4-62505" num="3" wdcount="1"> FBIS-SOV-94-095</s>
</AU>

<s docid="FBIS4-62505" num="4" wdcount="2"> Daily Report</s>
<DATE1>

<s docid="FBIS4-62505" num="5" wdcount="3"> 16 May 1994</s>
</DATE1>
</HEADER>
<F>

<s docid="FBIS4-62505" num="6" wdcount="1"> Tajikistan</s>
</F>
<H3>
<TI>

<s docid="FBIS4-62505" num="7" wdcount="7"> Communist Leader Calls for `Renovated' Soviet Union</s>
</TI>
</H3>
<HT>
<F>
<PHRASE>

<s docid="FBIS4-62505" num="8" wdcount="7"> Communist Leader Calls for `Renovated' Soviet Union</s>
</PHRASE>
</F>
</HT>
<F>

<s docid="FBIS4-62505" num="9" wdcount="10"> LD1605201494 Moscow ITAR-TASS in English 1916 GMT 16 May 94</s>
</F>
<F>

<s docid="FBIS4-62505" num="10" wdcount="1"> LD1605201494</s>
</F>
<F>

<s docid="FBIS4-62505" num="11" wdcount="2"> Moscow ITAR-TASS</s>
</F>
<F>

<s docid="FBIS4-62505" num="12" wdcount="1"> English</s>
</F>
<TEXT>

<s docid="FBIS4-62505" num="13" wdcount="1"> BFN</s>
<F>

<s docid="FBIS4-62505" num="14" wdcount="6"> [Report by ITAR-TASS correspondent Galina Gridnyova]</s>
</F>

<s docid="FBIS4-62505" num="15" wdcount="45"> [Text] Dushanbe 16 May TASS -- The Tajik Communist Party has called for the restoration of a renovated Soviet Union in the form of a federation as the only means to ensure the development of the political, economic, and spiritual potential of former Soviet republics.</s>

<s docid="FBIS4-62505" num="16" wdcount="35"> Tajik communists' leader Shodiy Shabdolov told ITAR-TASS on Monday [16 May]that the disintegration of the Soviet Union and the parade of sovereignty that followed it have led to economic and political chaos in all republics.</s>

<s docid="FBIS4-62505" num="17" wdcount="31"> Radical market reforms "imposed by quasi- democrats" and "wild privatisation" have enriched a small group of nouveau riches and plunged the rest of the population in poverty and hunger, he said.</s>

<s docid="FBIS4-62505" num="18" wdcount="19"> The mass drive for sovereignty was accompanied by armed inter-ethnic conflicts in many ex-Soviet republics and outburst of nationalism.</s>

<s docid="FBIS4-62505" num="19" wdcount="5"> Tajikistan was hit most hard.</s>

<s docid="FBIS4-62505" num="20" wdcount="16"> The civil war in the Republic claimed the lives of more than 100,000 people, Shabdolov said.</s>

<s docid="FBIS4-62505" num="21" wdcount="19"> He noted that the majority of the population support Tajik communists' call for the restoration of the Soviet Union.</s>

<s docid="FBIS4-62505" num="22" wdcount="34"> Over one million people, about two-thirds of the adult population, signed appeals "for unity, brotherhood and friendship of the peoples of the USSR" adopted by numerous conferences and meetings held all across the Republic.</s>

<s docid="FBIS4-62505" num="23" wdcount="19"> Supporters of the restoration of a renovated union held a founding congress of their movement in Dushanbe on Saturday.</s>

<s docid="FBIS4-62505" num="24" wdcount="28"> Apart from the communist party, the founders of the new movement include Tajik trade unions, the Union of Tajik Women, organisations of veterans and ethnic and cultural associations.</s>

<s docid="FBIS4-62505" num="25" wdcount="17"> "We are confident that our movement is growing so strong that it cannot be stopped," Shabdolov said.</s>

<s docid="FBIS4-62505" num="26" wdcount="17"> He stressed that it will act within the framework of the law and use only constitutional methods.</s>

<s docid="FBIS4-62505" num="27" wdcount="11"> "We are against barricades and use of force," he said .</s>
</TEXT>
</DOC>
