<DOC>
<DOCNO>

<s docid="FBIS4-40244" num="1" wdcount="1"> FBIS4-40244</s>
</DOCNO>
<HT>

<s docid="FBIS4-40244" num="2" wdcount="1"> "drsov115_u_94001"</s>
</HT>
<HEADER>
<AU>

<s docid="FBIS4-40244" num="3" wdcount="1"> FBIS-SOV-94-115</s>
</AU>

<s docid="FBIS4-40244" num="4" wdcount="2"> Daily Report</s>
<DATE1>

<s docid="FBIS4-40244" num="5" wdcount="3"> 14 Jun 1994</s>
</DATE1>
</HEADER>
<F>

<s docid="FBIS4-40244" num="6" wdcount="1"> Latvia</s>
</F>
<H3>
<TI>

<s docid="FBIS4-40244" num="7" wdcount="7"> Alksnis Warns of Ethnic Cleansing in Latvia</s>
</TI>
</H3>
<HT>
<F>
<PHRASE>

<s docid="FBIS4-40244" num="8" wdcount="7"> Alksnis Warns of Ethnic Cleansing in Latvia</s>
</PHRASE>
</F>
</HT>
<F>

<s docid="FBIS4-40244" num="9" wdcount="10"> LD1406163794 Moscow NTV in Russian 1500 GMT 14 Jun 94</s>
</F>
<F>

<s docid="FBIS4-40244" num="10" wdcount="1"> LD1406163794</s>
</F>
<F>

<s docid="FBIS4-40244" num="11" wdcount="2"> Moscow NTV</s>
</F>
<F>

<s docid="FBIS4-40244" num="12" wdcount="1"> Russian</s>
</F>
<TEXT>

<s docid="FBIS4-40244" num="13" wdcount="15"> BFN [Text] Viktor Alksnis, former USSR Supreme Soviet deputy, today reminded us of his existence.</s>

<s docid="FBIS4-40244" num="14" wdcount="33"> [Correspondent Irina Zaytseva] Viktor Alksnis, born 1950, Latvian, former deputy of the Supreme Soviet of the former USSR, soldier, resigned from the Army in order to fight for the restoration of the USSR.</s>

<s docid="FBIS4-40244" num="15" wdcount="18"> During the October events he left the White House with a head wound and was taken to hospital.</s>

<s docid="FBIS4-40244" num="16" wdcount="15"> After a long interval Viktor Alksnis held a news conference today in the Slavjanskaya Hotel.</s>

<s docid="FBIS4-40244" num="17" wdcount="48"> He began it with a short statement, the essence of which comes down to the fact that the adoption of the Latvian citizenship law violates not only human rights, but creates the conditions for a conflict similar, in his opinion, to the ones in Yugoslavia and the Caucasus.</s>

<s docid="FBIS4-40244" num="18" wdcount="16"> It was not only the Latvian Government Alksnis accused of this, but also the United States.</s>

<s docid="FBIS4-40244" num="19" wdcount="27"> According to him, during the latest visit to the United States by [Latvian President] Guntis Ulmanis, sanction was obtained for the adoption of the aforementioned discriminatory law.</s>

<s docid="FBIS4-40244" num="20" wdcount="21"> [Begin Alksnis recording] And thus carte blanche was given for mild ethnic cleansing of the Russian speaking population of the republic.</s>

<s docid="FBIS4-40244" num="21" wdcount="23"> [end recording] [Zaytseva] Apart from that, Alksnis added, according to information received from reliable sources, certain circles in Moscow want conflict in Latvia.</s>

<s docid="FBIS4-40244" num="22" wdcount="49"> [Begin Alksnis recording] A certain scenario exists to drive a so-called security corridor along the route Daugavpils-Yekabpils-Riga where stringent ethnic cleansing of the Latvian population will take place in reply to the mild ethnic cleansing of the Russian population in order to bring so-called independent Latvia to its knees.</s>

<s docid="FBIS4-40244" num="23" wdcount="15"> [end recording] [Zaytseva] Journalists asked for more precise information about what Alksnis called reliable sources.</s>

<s docid="FBIS4-40244" num="24" wdcount="11"> [Begin Alksnis recording] You understand that I cannot name these sources.</s>

<s docid="FBIS4-40244" num="25" wdcount="9"> But I can say that they are fairly authoritative.</s>

<s docid="FBIS4-40244" num="26" wdcount="25"> [end recording] [Zaytseva] Asked what he intends to do, Alksnis said his opportunities are unfortunately limited, and that is why he is appealing to journalists.</s>

<s docid="FBIS4-40244" num="27" wdcount="30"> In his opinion, only joint efforts can bring this information to the attention of world public opinion, point out the seriousness of this issue, and avoid the coming tragedy .</s>
</TEXT>
</DOC>
