<DOC>
<DOCNO>

<s docid="FT921-4937" num="1" wdcount="1"> FT921-4937</s>
</DOCNO>
<PROFILE>

<s docid="FT921-4937" num="2" wdcount="1"> _AN-CCFAOADQFT</s>
</PROFILE>
<DATE>

<s docid="FT921-4937" num="3" wdcount="1"> 920306</s>
</DATE>
<HEADLINE>

<s docid="FT921-4937" num="4" wdcount="9"> FT 06 MAR 92 / Shooting threatens Moldova peace</s>
</HEADLINE>
<BYLINE>

<s docid="FT921-4937" num="5" wdcount="3"> By JOHN LLOYD</s>
</BYLINE>
<DATELINE>

<s docid="FT921-4937" num="6" wdcount="1"> MOSCOW</s>
</DATELINE>
<TEXT>

<s docid="FT921-4937" num="7" wdcount="30"> A CEASEFIRE in Moldova was threatened yesterday when a truck driver transporting militiamen was shot dead by machinegun fire in the self-proclaimed Trans Dnestr republic, home of the Russian-speaking minority.</s>

<s docid="FT921-4937" num="8" wdcount="33"> The shooting came shortly after the ceasefire came into effect between the Moldovan authorities, dominated by ethnic Romanians, and the minority based in the republic on the east bank of the river Dnestr.</s>

<s docid="FT921-4937" num="9" wdcount="13"> At least nine people have been killed in clashes over the past week.</s>

<s docid="FT921-4937" num="10" wdcount="20"> As in the more severe conflict in Nagorno-Karabakh, the underlying tensions are growing and neither side believes it is losing.</s>

<s docid="FT921-4937" num="11" wdcount="24"> In other respects, however, the conflicts are quite different and illustrate the complexity of conflict with which the former Soviet Union is now faced.</s>

<s docid="FT921-4937" num="12" wdcount="27"> The Trans Dnestr conflict stems directly from the breakup of the Soviet Union while Nagorno-Karabakh has been a source of tension between Azeris and Armenians for centuries.</s>

<s docid="FT921-4937" num="13" wdcount="12"> Moldova (formerly Moldavia) was finally taken under full Soviet control in 1944.</s>

<s docid="FT921-4937" num="14" wdcount="32"> The Soviet leadership sought to stifle any attempts to preserve its former links with Romania - calling Moldovan a separate language from Romanian, and constructing a separate history for the Moldovan people.</s>

<s docid="FT921-4937" num="15" wdcount="27"> Industry was largely situated on the left bank of the Dnestr, in the sliver of the republic next to Ukraine, and largely staffed by Russians and Ukrainians.</s>

<s docid="FT921-4937" num="16" wdcount="19"> Ukrainians and Russians together represent some 27 per cent of the population, with Moldovans accounting for 64 per cent.</s>

<s docid="FT921-4937" num="17" wdcount="14"> The little republic (4.5m people) was slow to respond to the stirrings of reform.</s>

<s docid="FT921-4937" num="18" wdcount="42"> When it did, in 1989, a language movement quickly put the hardline Communist Party on the defensive and it lost power in 1990 to the present nationalist government, headed by President Mircea Snegur, the former secretary of the Moldovan Party's central committee.</s>

<s docid="FT921-4937" num="19" wdcount="60"> From the beginning of the nationalist movement, it was clear that the Russian and, to a lesser extent, the Ukrainian minorities would be hostile, reacting to laws establishing Moldovan as the official language and to calls for renewed union with Romania with strikes and demonstrations, and, finally last year, proclaiming Trans Dnestr independent under a Russian president, Mr Igor Smirnov.</s>

<s docid="FT921-4937" num="20" wdcount="32"> During the August coup last year, the Moldovan government stoutly rejected it and the Trans Dnestr authorities welcomed it, siding with the Soviet army in its brief efforts to impose military rule.</s>

<s docid="FT921-4937" num="21" wdcount="8"> Thereafter, the two sides have gathered military forces.</s>

<s docid="FT921-4937" num="22" wdcount="22"> The Trans Dnestr side has been augmented by Cossacks from nearby areas returning to their traditional role as defenders of Russia's borders.</s>

<s docid="FT921-4937" num="23" wdcount="32"> The daily Izvestia reported yesterday that the Cossacks appear to have appointed themselves mercenaries for the Russians (they are paid from Rbs2,000 to Rbs5,000 a week by the Trans Dnestr authorities) .</s>
</TEXT>
<PUB>

<s docid="FT921-4937" num="24" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT921-4937" num="25" wdcount="3"> London Page 2</s>
</PAGE>
</DOC>
