<DOC>
<DOCNO>

<s docid="FT923-13244" num="1" wdcount="1"> FT923-13244</s>
</DOCNO>
<PROFILE>

<s docid="FT923-13244" num="2" wdcount="1"> _AN-CGOA1AAPFT</s>
</PROFILE>
<DATE>

<s docid="FT923-13244" num="3" wdcount="1"> 920715</s>
</DATE>
<HEADLINE>

<s docid="FT923-13244" num="4" wdcount="10"> FT 15 JUL 92 / Peace-keepers sent into South Ossetia</s>
</HEADLINE>
<BYLINE>

<s docid="FT923-13244" num="5" wdcount="2"> By REUTER</s>
</BYLINE>
<DATELINE>

<s docid="FT923-13244" num="6" wdcount="1"> MOSCOW</s>
</DATELINE>
<TEXT>

<s docid="FT923-13244" num="7" wdcount="35"> RUSSIA and Georgia yesterday deployed 'blue helmet' troops to stop ethnic fighting in the disputed region of South Ossetia in the first peace-keeping operation since the collapse of the Soviet Union, Reuter reports from Moscow.</s>

<s docid="FT923-13244" num="8" wdcount="33"> Reports from the remote Transcaucasian region said hundreds of heavily armed Russian troops from the 104th paratroop battalion moved into a 7km-wide security zone separating rebel South Ossetia from the rest of Georgia.</s>

<s docid="FT923-13244" num="9" wdcount="25"> Georgian national guards occupied similar positions on their side of the border and pulled out all their men from the South Ossetian capital of Tskhinvali.</s>

<s docid="FT923-13244" num="10" wdcount="23"> But Itar-Tass news agency said gunfire overnight near the city killed four civilians and injured two others, underscoring the difficulties facing the operation.</s>

<s docid="FT923-13244" num="11" wdcount="32"> The mission was the first peace-keeping attempt anywhere in the former Soviet Union, whose disintegration last year has prompted waves of bloodletting in ethnic flashpoints from the Romanian to the Afghan borders.</s>

<s docid="FT923-13244" num="12" wdcount="24"> Reports from the former Soviet republic of Moldova said several people had been killed overnight in fresh ceasefire violations between government forces and separatists.</s>

<s docid="FT923-13244" num="13" wdcount="30"> In the Transcaucasian republic of Armenia, Radio Russia said five civilians had died overnight in Azerbaijani shelling, the latest victims of a four-year undeclared war which has killed 2,000 people.</s>

<s docid="FT923-13244" num="14" wdcount="32"> Russia and Georgia were cautiously optimistic that Ossetia could be the first region of the former Soviet Union where armed conflict could be resolved with the help of 'political measures and actions'.</s>

<s docid="FT923-13244" num="15" wdcount="21"> South Ossetia is part of Georgia but wants to unite with neighbouring North Ossetia, which was assigned to Russia by Stalin.</s>

<s docid="FT923-13244" num="16" wdcount="12"> Hundreds have been killed since 1990 in fighting between Georgians and Ossetians.</s>

<s docid="FT923-13244" num="17" wdcount="16"> The peace-keepers have been issued with UN-style light-blue helmet bands and matching chevrons on their sleeves.</s>

<s docid="FT923-13244" num="18" wdcount="26"> They will be joined later by a multi-ethnic force - Russians, Ukrainians, Ossetians and other mountain peoples - under the nominal command of North Ossetian leaders.</s>

<s docid="FT923-13244" num="19" wdcount="19"> The peace-keepers' mission is to form a physical barrier between the two sides, opening the way to future talks.</s>

<s docid="FT923-13244" num="20" wdcount="32"> The greatest threat is expected to come from hundreds of armed fighters on both sides, operating independently in a dozen or so bands outside the control of either Russian or Georgian authorities.</s>

<s docid="FT923-13244" num="21" wdcount="22"> Interfax news agency said Russia's Vice-President Alexander Rutskoi, at present on a visit to Moldova, proposed a similar peace-keeping operation there .</s>
</TEXT>
<PUB>

<s docid="FT923-13244" num="22" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT923-13244" num="23" wdcount="3"> London Page 4</s>
</PAGE>
</DOC>
