<DOC>
<DOCNO>

<s docid="FT921-5959" num="1" wdcount="1"> FT921-5959</s>
</DOCNO>
<PROFILE>

<s docid="FT921-5959" num="2" wdcount="1"> _AN-CCAAAAEOFT</s>
</PROFILE>
<DATE>

<s docid="FT921-5959" num="3" wdcount="1"> 920229</s>
</DATE>
<HEADLINE>

<s docid="FT921-5959" num="4" wdcount="12"> FT 29 FEB 92 / Troops to pull out of Nagorno Karabakh</s>
</HEADLINE>
<BYLINE>

<s docid="FT921-5959" num="5" wdcount="5"> By LEYLA BOULTON and Agencies</s>
</BYLINE>
<DATELINE>

<s docid="FT921-5959" num="6" wdcount="1"> MOSCOW</s>
</DATELINE>
<TEXT>

<s docid="FT921-5959" num="7" wdcount="30"> TROOPS OF the former Soviet Union were ordered to pull out from the Armenian enclave of Nagorno-Karabakh yesterday after they were fired on during clashes between Azeri and Armenian militants.</s>

<s docid="FT921-5959" num="8" wdcount="28"> Marshal Yevgeny Shaposhnikov, the Commonwealth of Independent States' defence minister, announced the decision as fighting worsened in the disputed territory in spite of efforts to secure a truce.</s>

<s docid="FT921-5959" num="9" wdcount="11"> The enclave is administered by Azerbaijan but largely populated by Armenians.</s>

<s docid="FT921-5959" num="10" wdcount="31"> The order for the pull-out of the 366th motorised regiment follows the deaths earlier this week of a handful of soldiers caught in the fighting between Armenian guerrillas and Azerbaijani forces.</s>

<s docid="FT921-5959" num="11" wdcount="13"> Fighting flared again yesterday in the capital Stepanakert, where the regiment is based.</s>

<s docid="FT921-5959" num="12" wdcount="13"> Azerbaijani and Armenian officials claimed their civilian targets were under particularly vicious attack.</s>

<s docid="FT921-5959" num="13" wdcount="29"> Marshal Shaposhnikov, who is also commander-in-chief, has long warned that he would withdraw troops rather than allow them to become targets of ethnic conflicts in the former Soviet Union.</s>

<s docid="FT921-5959" num="14" wdcount="8"> No dates have been given for the withdrawal.</s>

<s docid="FT921-5959" num="15" wdcount="11"> Troops under fire along the Armenian-Azerbaijani border will also be withdrawn.</s>

<s docid="FT921-5959" num="16" wdcount="24"> Commanders of the Trans-Caucasus military district, which encompasses Georgia as well as Armenia and Azerbaijan, have been ordered to rebuff attacks on military installations.</s>

<s docid="FT921-5959" num="17" wdcount="27"> Azeri and Armenian officials say sophisticated weapons, including combat helicopters, tanks and armoured personnel carriers, are being used by guerrillas on both sides in the four-year-old conflict.</s>

<s docid="FT921-5959" num="18" wdcount="32"> Armenian militants attacked the last Azeri stronghold in Nagorno-Karabakh yesterday, according to Azerbaijan's interior ministry, which said residents of the town of Shusha fled as helicopter gunships swooped down from snow-covered mountains.</s>

<s docid="FT921-5959" num="19" wdcount="17"> Armenians in the enclave want unification with Armenia, but Azerbaijan will not give up any territory .</s>
</TEXT>
<PUB>

<s docid="FT921-5959" num="20" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT921-5959" num="21" wdcount="3"> London Page 2</s>
</PAGE>
</DOC>
