<DOC>
<DOCNO>

<s docid="FT924-10185" num="1" wdcount="1"> FT924-10185</s>
</DOCNO>
<PROFILE>

<s docid="FT924-10185" num="2" wdcount="1"> _AN-CKBCIAAQFT</s>
</PROFILE>
<DATE>

<s docid="FT924-10185" num="3" wdcount="1"> 921102</s>
</DATE>
<HEADLINE>

<s docid="FT924-10185" num="4" wdcount="15"> FT 02 NOV 92 / Russia sends troops to Caucasus to back North Ossetian regime</s>
</HEADLINE>
<BYLINE>

<s docid="FT924-10185" num="5" wdcount="3"> By STEVE LEVINE</s>
</BYLINE>
<DATELINE>

<s docid="FT924-10185" num="6" wdcount="1"> MOSCOW</s>
</DATELINE>
<TEXT>

<s docid="FT924-10185" num="7" wdcount="33"> RUSSIA flew 3,000 special forces to halt ethnic fighting in the troubled Caucasus mountains at the weekend, its second troop deployment in a week to support a beleaguered government in its former empire.</s>

<s docid="FT924-10185" num="8" wdcount="26"> Russian President Boris Yeltsin sent Spetsnaz commandos and elite police to Vladikavkaz, capital of the Russian autonomous republic of North Ossetia, 1,100 miles south of Moscow.</s>

<s docid="FT924-10185" num="9" wdcount="25"> The troops were sent to halt fighting between Ossetians and a regional ethnic group, the Ingush, who officials claimed were setting fire to Ossetian-owned homes.</s>

<s docid="FT924-10185" num="10" wdcount="18"> Scores were reported killed and injured in street fighting between Ossetians and Ingush in the past several days.</s>

<s docid="FT924-10185" num="11" wdcount="18"> Ingush rebels were reported yesterday to have taken hostage 80 Russian interior ministry soldiers based in the region.</s>

<s docid="FT924-10185" num="12" wdcount="36"> A local official said the soldiers were seized on Friday in the Dzhermen settlement, located near the regional capital, Vladikavkaz, and populated mostly by Ingushis, Mr Felix Gutnov, spokesman for the North Ossetian interior ministry, said.</s>

<s docid="FT924-10185" num="13" wdcount="29"> The Ingush, who declared an independent state in June, are demanding the return of lands that Russian leader Josef Stalin expropriated in 1944 and declared part of North Ossetia.</s>

<s docid="FT924-10185" num="14" wdcount="18"> Mr Yeltsin and Russian Prime Minister Yegor Gaidar held emergency meetings on the crisis on Saturday and yesterday.</s>

<s docid="FT924-10185" num="15" wdcount="19"> At the same time, the North Ossetian government said it would distribute Russian army-supplied automatic weapons to civilian volunteers.</s>

<s docid="FT924-10185" num="16" wdcount="30"> 'The Russian authorities are strong enough to make all those violating the law respect it,' Russian Deputy Prime Minister Georgy Khizha, Mr Yeltsin's specialist on the Caucasus, told Russian television.</s>

<s docid="FT924-10185" num="17" wdcount="20"> The Russian action mirrored recent developments in the former Soviet republic of Tajikistan, where Russian troops have also been deployed.</s>

<s docid="FT924-10185" num="18" wdcount="25"> The Central Asian nation, which has yet to form its own army since the Soviet Union collapsed last December, has also distributed weapons to civilians.</s>

<s docid="FT924-10185" num="19" wdcount="20"> On October 26-27 Russian soldiers played a crucial role in crushing a coup attempt in the Tajik capital of Dushanbe.</s>

<s docid="FT924-10185" num="20" wdcount="20"> The Caucasus mountains, which stretch from southern Russia to the borders of Turkey and Iran, are engulfed by several conflicts.</s>

<s docid="FT924-10185" num="21" wdcount="17"> Among them are Georgia's war with Abkhazian separatists, and Azerbaijan's conflict with ethnic Armenians in Nagorno-Karabakh .</s>
</TEXT>
<PUB>

<s docid="FT924-10185" num="22" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT924-10185" num="23" wdcount="3"> London Page 3</s>
</PAGE>
</DOC>
