<DOC>
<DOCNO>

<s docid="FT934-2439" num="1" wdcount="1"> FT934-2439</s>
</DOCNO>
<PROFILE>

<s docid="FT934-2439" num="2" wdcount="1"> _AN-DLND1ADUFT</s>
</PROFILE>
<DATE>

<s docid="FT934-2439" num="3" wdcount="1"> 931214</s>
</DATE>
<HEADLINE>

<s docid="FT934-2439" num="4" wdcount="13"> FT 14 DEC 93 / Challenge of peacekeeping: A possible framework for co-operation</s>
</HEADLINE>
<BYLINE>

<s docid="FT934-2439" num="5" wdcount="6"> By DOUGLAS HURD and ANDREI KOZYREV</s>
</BYLINE>
<TEXT>

<s docid="FT934-2439" num="6" wdcount="35"> The international community is starting to look beyond the conflict in the former Yugoslavia, and is becoming increasingly aware of the true magnitude and seriousness of ethnic and political conflicts in the former Soviet Union.</s>

<s docid="FT934-2439" num="7" wdcount="7"> The problem is indeed a pressing one.</s>

<s docid="FT934-2439" num="8" wdcount="21"> The disputes in the Transcaucasus, central Asia, and elsewhere in the former Soviet Union are causing great suffering for those involved.</s>

<s docid="FT934-2439" num="9" wdcount="19"> They are a source of legitimate concern to the Russians, who are worried by clashes close to their borders.</s>

<s docid="FT934-2439" num="10" wdcount="39"> They are concerned too about the safety of ethnic Russians living in those countries where there are conflicts, and about the economic and social consequences of refugees fleeing to Russia (whose potential number is estimated at more than 2m).</s>

<s docid="FT934-2439" num="11" wdcount="17"> They believe that the problems in some of the former Soviet republics are either ignored or misunderstood.</s>

<s docid="FT934-2439" num="12" wdcount="15"> The Russians fear that if they do nothing, the conflicts will worsen and probably spread.</s>

<s docid="FT934-2439" num="13" wdcount="17"> They argue that they have a legitimate concern in trying to resolve conflicts that threaten their security.</s>

<s docid="FT934-2439" num="14" wdcount="32"> They ask why, when the international community is engaged in peacemaking and peacekeeping in many of the world's trouble spots, similar efforts should not be undertaken in the hot spots near them.</s>

<s docid="FT934-2439" num="15" wdcount="29"> Equally, these disputes are of legitimate concern to Britain, its western partners and the whole international community, both for humanitarian reasons and because such flashpoints risk provoking regional instability.</s>

<s docid="FT934-2439" num="16" wdcount="23"> If uncontrolled, they pose a variety of threats to European security, including increased traffic in drugs and arms as well as international terrorism.</s>

<s docid="FT934-2439" num="17" wdcount="27"> Crises in Russia's newly independent neighbours may also complicate Russia's relations with the west: unless they are carefully handled, they risk prejudicing the emerging relationship between us.</s>

<s docid="FT934-2439" num="18" wdcount="8"> The west is sometimes suspicious of Moscow's attitude.</s>

<s docid="FT934-2439" num="19" wdcount="21"> There are no differences about the need to resolve these conflicts: but there are differences over how to go about it.</s>

<s docid="FT934-2439" num="20" wdcount="21"> The British government will not underwrite Russian involvement unless it is sure that peacekeeping troops will not turn into occupying forces.</s>

<s docid="FT934-2439" num="21" wdcount="30"> Nor are countries that secured their independence when the Soviet Union was dissolved keen that the west should concede to Moscow the same role it played in the Soviet empire.</s>

<s docid="FT934-2439" num="22" wdcount="8"> They fear that this would compromise their sovereignty.</s>

<s docid="FT934-2439" num="23" wdcount="22"> When they are willing for Russian troops to play a peacekeeping role, they want there to be some form of international monitoring.</s>

<s docid="FT934-2439" num="24" wdcount="35"> This has meant that, even though the west lacks the resources to engage directly in those trouble spots, it has been wary of appearing to endorse Russian involvement instead, in case it had imperial tendencies.</s>

<s docid="FT934-2439" num="25" wdcount="30"> If we are to fashion a joint approach by Russia and its western partners to the problem of peacekeeping in the former Soviet Union, we must address all these concerns.</s>

<s docid="FT934-2439" num="26" wdcount="11"> Clearly Russia has an important role to play in this area.</s>

<s docid="FT934-2439" num="27" wdcount="39"> If the Russians want international recognition and more active support from the international community, the west in turn needs guarantees that Russia will not regard recognition of its involvement as giving it carte blanche in the former Soviet Union.</s>

<s docid="FT934-2439" num="28" wdcount="16"> Peace-keeping in the former Soviet Union, as indeed peacekeeping elsewhere, must comply with internationally recognised principles.</s>

<s docid="FT934-2439" num="29" wdcount="12"> It needs to be looked at on a case by case basis.</s>

<s docid="FT934-2439" num="30" wdcount="12"> Respect for the sovereignty of the newly independent countries must remain paramount.</s>

<s docid="FT934-2439" num="31" wdcount="75"> We agreed that the principles underlying Russian, CIS or international peacekeeping operations would need to include: strict respect for the sovereignty of the countries involved; an invitation from the government concerned and the consent of the parties to the conflict; commitment to a parallel political peace process; a clear mandate setting out the role of the peacekeeping forces (which should whenever possible be multinational in character); and an exit strategy for the peacekeeping forces deployed.</s>

<s docid="FT934-2439" num="32" wdcount="32"> These principles should help stimulate a dialogue and political settlement between the parties to the conflict, focus attention and, where possible, resources on the settlement of conflicts in the former Soviet Union.</s>

<s docid="FT934-2439" num="33" wdcount="8"> All this will help enhance Russian peacekeeping practices.</s>

<s docid="FT934-2439" num="34" wdcount="41"> Although the Conference for Security and Co-operation in Europe and the UN lack the resources to put large numbers of peacekeepers on the ground themselves, they may be able to suggest measures to enhance transparency and to monitor the peace process.</s>

<s docid="FT934-2439" num="35" wdcount="22"> Extending co-operation within the North Atlantic Co-operation Council, and also co-operation between Russia and Nato, might help improve training for Russian peacekeepers.</s>

<s docid="FT934-2439" num="36" wdcount="10"> This is an area we shall need to explore further.</s>

<s docid="FT934-2439" num="37" wdcount="11"> We also need to put much more emphasis on preventive diplomacy.</s>

<s docid="FT934-2439" num="38" wdcount="27"> One of the ways in which we can help prevent conflicts is to strengthen the democratic institutions in the newly independent countries of the former Soviet Union.</s>

<s docid="FT934-2439" num="39" wdcount="30"> The CSCE and other international institutions can play an important role here, drawing the newly independent countries into a more active dialogue on ways of promoting democratic values and principles.</s>

<s docid="FT934-2439" num="40" wdcount="24"> We discussed ways of strengthening the CSCE's role, including the role of the High Commissioner for National Minorities, at the recent Rome ministerial meeting.</s>

<s docid="FT934-2439" num="41" wdcount="16"> We must try to find ways of managing and resolving tensions before they erupt into conflict.</s>

<s docid="FT934-2439" num="42" wdcount="9"> It will not be easy, but we must try.</s>

<s docid="FT934-2439" num="43" wdcount="22"> Potentially explosive cocktails of ethnic and political animosities could spread the fire of intolerance all too easily to other countries and regions.</s>

<s docid="FT934-2439" num="44" wdcount="12"> We need to deal with it together in the spirit of partnership.</s>

<s docid="FT934-2439" num="45" wdcount="8"> And we need to deal with it urgently.</s>

<s docid="FT934-2439" num="46" wdcount="26"> Our security is indivisible and we must ensure it by vigorous and imaginative efforts aimed at promoting peace for all as well as rights for all.</s>

<s docid="FT934-2439" num="47" wdcount="10"> The authors are UK foreign secretary and Russian foreign minister</s>
</TEXT>
<XX>

<s docid="FT934-2439" num="48" wdcount="1"> Countries:-</s>
</XX>
<CN>

<s docid="FT934-2439" num="49" wdcount="5"> RUZ Russia, East Europe .</s>
</CN>
<XX>

<s docid="FT934-2439" num="50" wdcount="1"> Industries:-</s>
</XX>
<IN>

<s docid="FT934-2439" num="51" wdcount="3"> P9721 International Affairs.</s>

<s docid="FT934-2439" num="52" wdcount="5"> P9199 General Government, NEC .</s>
</IN>
<XX>

<s docid="FT934-2439" num="53" wdcount="1"> Types:-</s>
</XX>
<TP>

<s docid="FT934-2439" num="54" wdcount="5"> CMMT Comment & Analysis .</s>
</TP>
<PUB>

<s docid="FT934-2439" num="55" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT934-2439" num="56" wdcount="3"> London Page 16</s>
</PAGE>
</DOC>
