<DOC>
<DOCNO>

<s docid="LA070289-0167" num="1" wdcount="1"> LA070289-0167</s>
</DOCNO>
<DOCID>

<s docid="LA070289-0167" num="2" wdcount="1"> 77533</s>
</DOCID>
<DATE>
<P>

<s docid="LA070289-0167" num="3" wdcount="6"> July 2, 1989, Sunday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA070289-0167" num="4" wdcount="8"> Part 1; Page 1; Column 6; Foreign Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA070289-0167" num="5" wdcount="2"> 1294 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA070289-0167" num="6" wdcount="8"> GORBACHEV SAYS ETHNIC STRIFE IS THREAT TO UNITY</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA070289-0167" num="7" wdcount="6"> By MICHAEL PARKS, Times Staff Writer</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA070289-0167" num="8" wdcount="1"> MOSCOW</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA070289-0167" num="9" wdcount="35"> Soviet President Mikhail S. Gorbachev warned the nation Saturday night that the country's growing ethnic strife is endangering its unity as a state as well as threatening his program of political and economic reforms .</s>
</P>
<P>

<s docid="LA070289-0167" num="10" wdcount="44"> Appealing for calm and for the cool consideration of grievances after weeks of continuing unrest in scattered areas of the country, Gorbachev made clear the leadership's fear that the nation is heading into a political maelstrom that could tear the Soviet Union apart .</s>
</P>
<P>

<s docid="LA070289-0167" num="11" wdcount="32"> As president, Gorbachev said, it is his "duty to warn you about the mounting danger of worsening inter-ethnic relations and the consequences for society, for every family and for every person" .</s>
</P>
<P>

<s docid="LA070289-0167" num="12" wdcount="25"> "The fate of perestroika and the unity of our state is at stake," he declared in a sober, 20-minute address broadcast on radio and television.</s>

<s docid="LA070289-0167" num="13" wdcount="28"> "Irresponsible slogans, political instigation, setting one national group against another, the domination of some ethnic groups by others -- this could lead to disaster for us all .</s>
</P>
<P>

<s docid="LA070289-0167" num="14" wdcount="33"> "The living and the succeeding generations will curse those who pushed the nation on this course and those who failed to caution it against the dangers involved in time to prevent madness" .</s>
</P>
<P>

<s docid="LA070289-0167" num="15" wdcount="69"> With serious ethnic clashes in Soviet Central Asia over the past month, with troops needed to maintain the peace in the southern republics of Armenia, Azerbaijan and Georgia and with nationalism growing stronger in the Baltic republics of Estonia, Latvia and Lithuania, Gorbachev is struggling to hold the Soviet Union together as a state while he pushes broad reforms that he believes will resolve most of the grievances .</s>
</P>
<P>

<s docid="LA070289-0167" num="16" wdcount="30"> Even as he spoke, Soviet officials reported new violence in the south -- this time between Georgians and Azerbaijanis inside the Georgian republic but in an area with many Azerbaijanis.</s>

<s docid="LA070289-0167" num="17" wdcount="34"> Roving gangs, armed with hunting rifles, gasoline bombs and other weapons, had clashed in three towns south of the capital of Tbilisi last week, leaving one man dead and 22 people seriously wounded .</s>
</P>
<P>

<s docid="LA070289-0167" num="18" wdcount="45"> Although limited so far in scope, some of the ethnic conflicts could grow to the point where various regions of the country would be thrown into virtual civil war, Gorbachev suggested, and some national republics could find themselves in violent disputes with their neighbors .</s>
</P>
<P>

<s docid="LA070289-0167" num="19" wdcount="40"> Those who encourage the unrest are "playing with fire," Gorbachev said, warning that the government will use its full powers and take "the most decisive measures" against those provoking the clashes, organizing attacks on minority groups or urging secession .</s>
</P>
<P>

<s docid="LA070289-0167" num="20" wdcount="58"> Nearly 300 people have been killed in communal clashes and related political disturbances over the past two years; tens of thousands of people have had to flee their homes, including 40,000 last month alone, to seek refuge from the violence, and nearly 25,000 special troops are now deployed in various parts of the country to maintain order .</s>
</P>
<P>

<s docid="LA070289-0167" num="21" wdcount="35"> "There will be no pulling of our punches in relation to those who have taken the criminal path," Gorbachev said, warning of stern measures against those engaged in communal violence or in political agitation .</s>
</P>
<P>
</P>
<P>

<s docid="LA070289-0167" num="22" wdcount="3"> Political Energy Drained</s>
</P>
<P>

<s docid="LA070289-0167" num="23" wdcount="60"> The ethnic strife, much of it rooted in past Soviet policies of domination by ethnic Russians or in the forced deportation of hundreds of thousands of people during the Stalinist era, has increasingly drained the political energy necessary to push through major reforms and has provided conservative critics of reform with a potent argument against faster and broader change .</s>
</P>
<P>

<s docid="LA070289-0167" num="24" wdcount="45"> For Gorbachev, the spread of the unrest has forced the humiliating admission that the Soviet Union, a superpower in world terms, cannot ensure the domestic tranquility that is a first priority for any government -- nor can it protect its own minorities against pogroms .</s>
</P>
<P>

<s docid="LA070289-0167" num="25" wdcount="30"> If the strife here continued and grew, he asked, "What kind of example shall we set for others while calling on the whole of mankind to build a nonviolent world"?</s>
</P>
<P>

<s docid="LA070289-0167" num="26" wdcount="41"> Of equal gravity for Gorbachev in domestic political terms has been the growth of not only nationalism but the appearance of secessionist groups in the Baltic republics and in Armenia, Georgia and Moldavia, a Soviet republic on the Romanian border .</s>
</P>
<P>

<s docid="LA070289-0167" num="27" wdcount="33"> The whole issue is believed to have been the subject of a high-level Communist Party conference here late last week, and Gorbachev's unusual television address underscores the threat posed by the conflicts .</s>
</P>
<P>

<s docid="LA070289-0167" num="28" wdcount="38"> Gorbachev acknowledged that ethnic relations are "wound in a tight knot of contradictions" because of previous Soviet policies, particularly the effort to pull the country's 100-plus ethnic groups into a new "Soviet nationality" with a unified culture .</s>
</P>
<P>

<s docid="LA070289-0167" num="29" wdcount="22"> This policy had, in fact, collided head on with growing ethnic awareness throughout the country and made the problems even worse .</s>
</P>
<P>

<s docid="LA070289-0167" num="30" wdcount="27"> Past economic policies, including the "stagnation" in many regions under the regime of the late President Leonid I. Brezhnev, had also made the problems more acute .</s>
</P>
<P>

<s docid="LA070289-0167" num="31" wdcount="49"> "We are also reaping today the results of lawlessness in preceding decades -- the deportation of whole peoples from their lands and the burying in oblivion of the national interests of small ethnic groups," Gorbachev said, alluding to actions carried out decades ago by the dictator Josef Stalin .</s>
</P>
<P>

<s docid="LA070289-0167" num="32" wdcount="52"> "Such excesses resulted in indifference to ethnic interests, to many outstanding social and economic problems in constituent republics and autonomous regions, deformities in the development of the languages and cultures of the country's different peoples, the deteriorating demographic situation and many other negative consequences that ultimately provoked tension in inter-ethnic relations" .</s>
</P>
<P>

<s docid="LA070289-0167" num="33" wdcount="61"> Although these questions will be dealt with during a special meeting of the Communist Party's policy-making Central Committee in late July and then debated again by the Congress of People's Deputies, the country's new national assembly, Gorbachev apparently felt that he could not wait for those debates, and he set out his own broad guidelines for dealing with the crisis .</s>
</P>
<P>
</P>
<P>

<s docid="LA070289-0167" num="34" wdcount="3"> Right of Equality</s>
</P>
<P>

<s docid="LA070289-0167" num="35" wdcount="34"> "Everyone, regardless of his nationality, should feel an equal citizen in any part of the country and have a possibility to exercise all the rights guaranteed by the Soviet Union's constitution," he said .</s>
</P>
<P>

<s docid="LA070289-0167" num="36" wdcount="44"> The refusal to recognize the basic principle of equality had led to attacks on minority groups in several parts of the country, Gorbachev said, alluding to the particularly vicious assaults on Mesketian Turks in Uzbekistan last month in which about 100 people died .</s>
</P>
<P>

<s docid="LA070289-0167" num="37" wdcount="53"> The Soviet leader outlined an approach that would seek to increase the feeling of various ethnic groups that they are "at home in their own land" and could preserve and develop their own cultures, languages and social traditions, with the Soviet Union evolving politically to be much more of a federal system .</s>
</P>
<P>

<s docid="LA070289-0167" num="38" wdcount="19"> But he said that minority communities also need to be protected so that there is a balance of rights.</s>

<s docid="LA070289-0167" num="39" wdcount="15"> "We have lived and will continue to live in a multi-ethnic community," he observed .</s>
</P>
<P>

<s docid="LA070289-0167" num="40" wdcount="30"> Gorbachev said that "profound transformations in the Soviet federation" are clearly essential, promising further political reforms to make it a real federation and not just one in name only .</s>
</P>
<P>
</P>
<P>

<s docid="LA070289-0167" num="41" wdcount="2"> Demands Rejected</s>
</P>
<P>

<s docid="LA070289-0167" num="42" wdcount="38"> But he declared at the same time his firm opposition to near-total independence demanded by some nationalists, particularly in Estonia, Latvia and Lithuania, and to the calls by others for the redrawing of the borders of ethnic territories.</s>

<s docid="LA070289-0167" num="43" wdcount="12"> The Soviet Union's ethnic groups have "a common destiny," Gorbachev said .</s>
</P>
<P>

<s docid="LA070289-0167" num="44" wdcount="39"> "In quest of the better, one should not embark on the path of destroying what has been built and abandoning what has already been given by the federation and what can be multiplied within its framework," he said .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA070289-0167" num="45" wdcount="8"> Map, AREAS OF ETHNIC STRIFE, Los Angeles Times</s>
</P>
</GRAPHIC>
<SUBJECT>
<P>

<s docid="LA070289-0167" num="46" wdcount="14"> GORBACHEV, MIKHAIL S; SPEECHES; ETHNIC GROUPS; DEMONSTRATIONS -- USSR; RACIAL RELATIONS -- USSR; NATIONALISM</s>
</P>
</SUBJECT>
</DOC>
