<DOC>
<DOCNO>

<s docid="AP881115-0113" num="1" wdcount="1"> AP881115-0113</s>
</DOCNO>
<FILEID>

<s docid="AP881115-0113" num="2" wdcount="2"> AP-NR-11-15-88 1338EST</s>
</FILEID>
<FIRST>

<s docid="AP881115-0113" num="3" wdcount="6"> u w AM-Heart-Balloon Bjt 11-15 0657</s>
</FIRST>
<SECOND>

<s docid="AP881115-0113" num="4" wdcount="2"> AM-Heart-Balloon, Bjt,640</s>
</SECOND>
<HEAD>

<s docid="AP881115-0113" num="5" wdcount="9"> Study Says Emergency Heart Procedure Unnecessary After Heart Attacks</s>
</HEAD>
<BYLINE>

<s docid="AP881115-0113" num="6" wdcount="4"> By DANIEL Q. HANEY</s>
</BYLINE>
<BYLINE>

<s docid="AP881115-0113" num="7" wdcount="3"> AP Science Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP881115-0113" num="8" wdcount="2"> WASHINGTON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP881115-0113" num="9" wdcount="36"> The expensive practice of using balloon catheters to force open heart arteries immediately after heart attacks, now routinely done at many large hospitals, is unnecessary and should be abandoned, according to a major study released Tuesday.</s>

<s docid="AP881115-0113" num="10" wdcount="27"> The study found that if heart attack victims quickly receive clot-dissolving drugs, they usually don't need the extra step of the common balloon procedure, known as angioplasty.</s>

<s docid="AP881115-0113" num="11" wdcount="27"> Some experts said the results are good news, because they mean that most heart attack patients can be treated in community hospitals, where angioplasty is not available.</s>

<s docid="AP881115-0113" num="12" wdcount="8"> The study also has an important financial message.</s>

<s docid="AP881115-0113" num="13" wdcount="23"> Its authors estimated that if angioplasty was widely adopted after heart attacks, it could raise the nation's annual medical bills by $704 million.</s>

<s docid="AP881115-0113" num="14" wdcount="15"> ``This trial has settled one of the most important questions in modern-day cardiology,'' commented Dr.</s>

<s docid="AP881115-0113" num="15" wdcount="9"> J. Ward Kennedy of the University of Washington, Seattle.</s>

<s docid="AP881115-0113" num="16" wdcount="26"> The study is phase 2 of the Thrombolysis in Miocardial Infarction Trial, or TIMI-II, directed by Dr. Eugene Braunwald of Brigham and Women's Hospital in Boston.</s>

<s docid="AP881115-0113" num="17" wdcount="29"> The first phase of the study showed that giving people a clot-dissolving drug called tissue plasminogen activator, or TPA, immediately after heart attacks dramatically improved their chances of survival.</s>

<s docid="AP881115-0113" num="18" wdcount="34"> The latest study, presented at the annual meeting of the American Heart Association, was intended to see whether people did better still if doctors tried to clear away any remaining blockages after giving TPA.</s>

<s docid="AP881115-0113" num="19" wdcount="32"> At 50 hospitals across the United States, doctors randomly assigned 1,636 patients to get angioplasty within two days of their heart attacks if tests showed there was any chance they might benefit.</s>

<s docid="AP881115-0113" num="20" wdcount="21"> Sixty percent of them actually underwent the procedure, which temporarily inflates balloons in dangerously narrowed heart arteries to squeeze them open.</s>

<s docid="AP881115-0113" num="21" wdcount="8"> A comparison group of 1,626 also got TPA.</s>

<s docid="AP881115-0113" num="22" wdcount="20"> But they were not considered for angioplasty unless they had lingering heart pain or abnormal exercise tests during their recovery.</s>

<s docid="AP881115-0113" num="23" wdcount="28"> After 42 days, 11 percent of those in the angioplasty group had died or suffered further heart attacks, as did 10 percent of those in the comparison group.</s>

<s docid="AP881115-0113" num="24" wdcount="11"> A year after the treatment, there was no difference in survival.</s>

<s docid="AP881115-0113" num="25" wdcount="9"> About 93 percent of both groups were still alive.</s>

<s docid="AP881115-0113" num="26" wdcount="13"> ``There does not appear to be any additional benefit from angioplasty,'' Braunwald said.</s>

<s docid="AP881115-0113" num="27" wdcount="26"> Dr. Thomas J. Ryan of Boston University Medical Center commented, ``We have the answer in this trial to a very important question of health care delivery''.</s>

<s docid="AP881115-0113" num="28" wdcount="24"> While small hospitals can give clot-dissolving drugs to heart attack patients, most of them do not have the sophisticated labs where angioplasty is performed.</s>

<s docid="AP881115-0113" num="29" wdcount="32"> If the study had found that immediate angioplasty improves survival, it would have meant that many more angioplasty labs would need to be established and more doctors trained to give the procedure.</s>

<s docid="AP881115-0113" num="30" wdcount="12"> ``The watch word is watchful waiting'' to see if patients need angioplasty.</s>

<s docid="AP881115-0113" num="31" wdcount="35"> ``This ultimately makes it possible for patients to be treated in community hospitals and be transfered to terciary care centers if angioplasty is needed,'' said Dr. Howard Morgan, immediate past president of the heart association.</s>

<s docid="AP881115-0113" num="32" wdcount="14"> Heart attacks occur when a clot blocks an artery that feeds the heart muscle.</s>

<s docid="AP881115-0113" num="33" wdcount="16"> The purpose of TPA and similar drugs is to dissolve these clots before the muscle dies.</s>

<s docid="AP881115-0113" num="34" wdcount="19"> To be effective, the drugs must be given within about four hours of the start of heart attack symptoms.</s>

<s docid="AP881115-0113" num="35" wdcount="19"> Experts say that only about 20 percent of heart attack victims are considered to be candidates for the drugs.</s>

<s docid="AP881115-0113" num="36" wdcount="11"> Many people delay going to the hospital until permanent damage occurs.</s>

<s docid="AP881115-0113" num="37" wdcount="18"> In others, the treatment may be considered too dangerous because of recent surgery or a history of strokes.</s>

<s docid="AP881115-0113" num="38" wdcount="19"> Balloon angioplasty is also widely used to treat people with clogged heart arteries who have not suffered heart attacks.</s>

<s docid="AP881115-0113" num="39" wdcount="14"> The latest study did not question the usefulness of this kind of angioplasty .</s>
</TEXT>
</DOC>
