<DOC>
<DOCNO>

<s docid="AP880428-0041" num="1" wdcount="1"> AP880428-0041</s>
</DOCNO>
<FILEID>

<s docid="AP880428-0041" num="2" wdcount="2"> AP-NR-04-28-88 0425EDT</s>
</FILEID>
<FIRST>

<s docid="AP880428-0041" num="3" wdcount="5"> r a PM-HeartAttack 04-28 0509</s>
</FIRST>
<SECOND>

<s docid="AP880428-0041" num="4" wdcount="2"> PM-Heart Attack,0523</s>
</SECOND>
<HEAD>

<s docid="AP880428-0041" num="5" wdcount="10"> Study: Three-Day Hospital Stays Enough for Some Heart Attack Victims</s>
</HEAD>
<BYLINE>

<s docid="AP880428-0041" num="6" wdcount="4"> By DANIEL Q. HANEY</s>
</BYLINE>
<BYLINE>

<s docid="AP880428-0041" num="7" wdcount="3"> AP Science Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880428-0041" num="8" wdcount="2"> BOSTON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880428-0041" num="9" wdcount="36"> New treatments that stop a heart attack in its tracks may help victims to get out of the hospital more quickly than ever before, perhaps even three days after their attacks, a study published today concludes.</s>

<s docid="AP880428-0041" num="10" wdcount="21"> Doctors from the University of Michigan Medical Center studied the effects of sending a few carefully selected heart patients home early.</s>

<s docid="AP880428-0041" num="11" wdcount="20"> They found that these people had no unusual complications, got back to work sooner and had substantially lower medical bills.</s>

<s docid="AP880428-0041" num="12" wdcount="14"> ``It was an extraordinarily safe strategy,'' said Dr. Eric J. Topol, the study's director.</s>

<s docid="AP880428-0041" num="13" wdcount="8"> ``There were no problems with any serious events''.</s>

<s docid="AP880428-0041" num="14" wdcount="21"> Topol said the early discharges were made possible by two recent medical advances _ tissue plasminogen activator, or TPA, and angioplasty.</s>

<s docid="AP880428-0041" num="15" wdcount="18"> When given quickly after a heart attack, TPA can dissolve clots in the heart's arteries and minimize damage.</s>

<s docid="AP880428-0041" num="16" wdcount="14"> Angioplasty can produce similar results by opening up the clogged arteries with tiny balloons.</s>

<s docid="AP880428-0041" num="17" wdcount="23"> The report represents the latest in a steady three-decade trend of sending heart attack patients home from the hospital after ever shorter stays.</s>

<s docid="AP880428-0041" num="18" wdcount="21"> However, the study in the New England Journal of Medicine said more research is needed before the findings are widely adopted.</s>

<s docid="AP880428-0041" num="19" wdcount="20"> In the 1950s, doctors often recommended that patients stay in bed for one to two months after a heart attack.</s>

<s docid="AP880428-0041" num="20" wdcount="20"> When President Dwight D. Eisenhower suffered an uncomplicated heart attack in 1955, he spent seven weeks recovering in the hospital.</s>

<s docid="AP880428-0041" num="21" wdcount="11"> However, doctors learned that long inactivity did more harm than good.</s>

<s docid="AP880428-0041" num="22" wdcount="11"> Patients got out of shape, developed blood clots and became demoralized.</s>

<s docid="AP880428-0041" num="23" wdcount="17"> In the 1960s, the stay was shortened to three weeks and in the 1970s to two weeks.</s>

<s docid="AP880428-0041" num="24" wdcount="12"> Now, doctors typically keep heart attack patients hospitalized seven to 10 days.</s>

<s docid="AP880428-0041" num="25" wdcount="24"> In their paper, the doctors determined that 80 of the 507 heart attack patients studied were healthy enough to be considered for early discharge.</s>

<s docid="AP880428-0041" num="26" wdcount="12"> None of them had irregular heart beats, chest pain or heart failure.</s>

<s docid="AP880428-0041" num="27" wdcount="9"> Treadmill tests showed no signs of heart attack damage.</s>

<s docid="AP880428-0041" num="28" wdcount="16"> Forty patients were sent home after three days, while the rest stayed seven to 10 days.</s>

<s docid="AP880428-0041" num="29" wdcount="19"> After six months of followup, none had died, and the number of medical problems in both groups was similar.</s>

<s docid="AP880428-0041" num="30" wdcount="31"> However, people in the early discharge group were able to return to work about two weeks sooner than the others, and their medical bills were significantly lower _ $12,546 versus $17,868.</s>

<s docid="AP880428-0041" num="31" wdcount="26"> The researchers estimated that if 15 percent of all heart attack patients were discharged after three days, the annual saving would be at least $280 million.</s>

<s docid="AP880428-0041" num="32" wdcount="32"> In an accompanying editorial, Dr. Gregory D. Curfman, a deputy editor of the journal, cautioned that the study was not large enough to spot complications that might result from reducing hospital stays.</s>

<s docid="AP880428-0041" num="33" wdcount="30"> ``This single study,'' he wrote, ``is not sufficient to justify sweeping changes in current management practices for all patients who may at first appear to have uncomplicated'' heart attacks .</s>
</TEXT>
</DOC>
