<DOC>
<DOCNO>

<s docid="AP880818-0088" num="1" wdcount="1"> AP880818-0088</s>
</DOCNO>
<FILEID>

<s docid="AP880818-0088" num="2" wdcount="2"> AP-NR-08-18-88 0901EDT</s>
</FILEID>
<FIRST>

<s docid="AP880818-0088" num="3" wdcount="5"> r a PM-HeartDrug 08-18 0533</s>
</FIRST>
<SECOND>

<s docid="AP880818-0088" num="4" wdcount="2"> PM-Heart Drug,0548</s>
</SECOND>
<HEAD>

<s docid="AP880818-0088" num="5" wdcount="8"> Heart Attack Drug Not Always Helpful, Researcher Says</s>
</HEAD>
<BYLINE>

<s docid="AP880818-0088" num="6" wdcount="3"> By RANDOLPH PICHT</s>
</BYLINE>
<BYLINE>

<s docid="AP880818-0088" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880818-0088" num="8" wdcount="3"> ROCHESTER, N.Y. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880818-0088" num="9" wdcount="39"> A drug used to treat patients complaining of chest pain also could help prevent recurring heart attacks in four out of five heart patients, according to a study published in today's edition of the New England Journal of Medicine.</s>

<s docid="AP880818-0088" num="10" wdcount="25"> Surprisingly, however, the study found that the drug, diltiazem, increases the chance of a subsequent heart attack in patients whose hearts pump abnormally, experts said.</s>

<s docid="AP880818-0088" num="11" wdcount="24"> Even so, the results may trigger an increase in the use of the drug, which is now primarily used to treat angina, doctors said.</s>

<s docid="AP880818-0088" num="12" wdcount="43"> The drug was tested in 38 hospitals in the United States and Canada on patients who had recently suffered a heart attack, said Dr. Arthur Moss, a clinical professor of medicine at the University of Rochester and the principal investigator for the study.</s>

<s docid="AP880818-0088" num="13" wdcount="25"> The results suggest the drug may be quite effective in decreasing the likelihood of a second heart attack in the majority of patients, Moss said.</s>

<s docid="AP880818-0088" num="14" wdcount="28"> But the study also surprisingly suggests that patients who suffer pulmonary congestion should not be given diltiazem because the drug increases the chance of a subsequent heart attack.</s>

<s docid="AP880818-0088" num="15" wdcount="14"> ``We now know when to prescribe this drug and when not to,'' Moss said.</s>

<s docid="AP880818-0088" num="16" wdcount="7"> ``That's what this study was all about''.</s>

<s docid="AP880818-0088" num="17" wdcount="20"> Diltiazem is a calcium entry blocker, the newest class of drugs to be introduced in the fight against heart disease.</s>

<s docid="AP880818-0088" num="18" wdcount="12"> Nitrates and beta blockers are the other types commonly prescribed by doctors.</s>

<s docid="AP880818-0088" num="19" wdcount="20"> The study involved 2,466 heart attack patients, who were given either 240 milligrams of diltiazem a day or a placebo.</s>

<s docid="AP880818-0088" num="20" wdcount="14"> Patients were recruited from 1983 to 1986 and followed for 12 to 52 months.</s>

<s docid="AP880818-0088" num="21" wdcount="17"> Overall, the drug only decreased additional heart attacks 11 percent, which was not statistically significant, Moss said.</s>

<s docid="AP880818-0088" num="22" wdcount="35"> But in patients who had normal or near-normal heart pump function _ 1,909 patients or 80 percent of the total group _ diltiazem decreased the chance of another heart attack by 25 percent, Moss said.</s>

<s docid="AP880818-0088" num="23" wdcount="25"> In patients whose hearts had pumping problems, the drug not only didn't help, but it increased the chance of a heart attack by 25 percent.</s>

<s docid="AP880818-0088" num="24" wdcount="33"> Dr. John Schroeder, a cardiologist and professor at Stanford University, said he was surprised that the drug increased the chance of heart attack in any group and that overall results were not higher.</s>

<s docid="AP880818-0088" num="25" wdcount="20"> ``But the bottom line is that this is the first study to show that diltiazem can be effective,'' Schroeder said.</s>

<s docid="AP880818-0088" num="26" wdcount="19"> ``I think it will mean that more patients will be routinely put on this drug on a long-term basis''.</s>

<s docid="AP880818-0088" num="27" wdcount="30"> Dr. George Beller, a cardiologist and professor at the University of Virginia, said he was also somewhat surprised about the increase in heart attacks in the group suffering pulmonary congestion.</s>

<s docid="AP880818-0088" num="28" wdcount="14"> ``This is one of the first reports that seems to identify that,'' he said.</s>

<s docid="AP880818-0088" num="29" wdcount="30"> Diltiazem and two other calcium entry blockers were introduced in the past decade, Beller said, and research into how effective they are in various applications is in its early stages.</s>

<s docid="AP880818-0088" num="30" wdcount="18"> Nitrates have been used for more than 50 years, and beta blockers were developed in the 1960s .</s>
</TEXT>
</DOC>
