<DOC>
<DOCNO>

<s docid="AP880829-0222" num="1" wdcount="1"> AP880829-0222</s>
</DOCNO>
<FILEID>

<s docid="AP880829-0222" num="2" wdcount="2"> AP-NR-08-29-88 0905EDT</s>
</FILEID>
<FIRST>

<s docid="AP880829-0222" num="3" wdcount="5"> a a BC-SPE--HealthCare:Heart 08-29 0843</s>
</FIRST>
<SECOND>

<s docid="AP880829-0222" num="4" wdcount="3"> BC-SPE--Health Care: Heart,0869</s>
</SECOND>
<HEAD>

<s docid="AP880829-0222" num="5" wdcount="2"> BC-SPECIAL EDITION</s>
</HEAD>
<HEAD>

<s docid="AP880829-0222" num="6" wdcount="3"> Health Care: Heart</s>
</HEAD>
<HEAD>

<s docid="AP880829-0222" num="7" wdcount="3"> LaserPhotos NY700, NY701</s>
</HEAD>
<BYLINE>

<s docid="AP880829-0222" num="8" wdcount="3"> By PAUL RAEBURN</s>
</BYLINE>
<BYLINE>

<s docid="AP880829-0222" num="9" wdcount="3"> AP Science Editor</s>
</BYLINE>
<DATELINE>

<s docid="AP880829-0222" num="10" wdcount="3"> NEW YORK (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880829-0222" num="11" wdcount="19"> Aspirin sales jumped 41 percent for a few weeks earlier this year, not because of a rash of headaches.</s>

<s docid="AP880829-0222" num="12" wdcount="25"> A study of more than 22,000 male doctors had shown that taking a single aspirin every other day could cut heart attack risk in half.</s>

<s docid="AP880829-0222" num="13" wdcount="31"> The study was one of a series of recent reports showing for the first time that doctors are able not only to treat heart attacks _ but also to prevent them.</s>

<s docid="AP880829-0222" num="14" wdcount="34"> In the most recent report, doctors found that one aspirin tablet and a single dose of a clot-dissolving drug given within 24 hours can dramatically cut the risk of a second fatal heart attack.</s>

<s docid="AP880829-0222" num="15" wdcount="22"> Without the treatment, patients had a 13 percent chance of dying from a second heart attack within five weeks, the researchers found.</s>

<s docid="AP880829-0222" num="16" wdcount="9"> With the treatment, the figure dropped to 8 percent.</s>

<s docid="AP880829-0222" num="17" wdcount="26"> ``The real discovery is that treatment for patients is going to reduce in-hospital mortality substantially,'' says Richard Peto of Oxford University, one of the study's authors.</s>

<s docid="AP880829-0222" num="18" wdcount="11"> Heart disease is the nation's leading cause of death, by far.</s>

<s docid="AP880829-0222" num="19" wdcount="16"> The National Center for Health Statistics reports that 762,820 Americans died of heart disease in 1987.</s>

<s docid="AP880829-0222" num="20" wdcount="22"> To put it another way: Of the 2,127,000 American who died that year, more than one in three died of heart disease.</s>

<s docid="AP880829-0222" num="21" wdcount="13"> (This does not include those who died of blood-vessel diseases, such as strokes).</s>

<s docid="AP880829-0222" num="22" wdcount="21"> The drugs most responsible for the recent success in preventing heart attacks are the new clot-dissolvers and that old standby, aspirin.</s>

<s docid="AP880829-0222" num="23" wdcount="21"> The usual cause of heart attacks is a blockage of the coronary arteries, which supply the heart muscle with oxygen-rich blood.</s>

<s docid="AP880829-0222" num="24" wdcount="12"> The blockage arises from the buildup of fats, cholesterol and clotted blood.</s>

<s docid="AP880829-0222" num="25" wdcount="8"> Clot-dissolvers break up clots, thus restoring blood flow.</s>

<s docid="AP880829-0222" num="26" wdcount="17"> Aspirin interferes with aspects of the clotting process, helping to prevent clot formation in the first place.</s>

<s docid="AP880829-0222" num="27" wdcount="24"> The limited sales of the clot-dissolving drugs in the United States show that many doctors are still not using them, despite their proven success.</s>

<s docid="AP880829-0222" num="28" wdcount="6"> But that is beginning to change.</s>

<s docid="AP880829-0222" num="29" wdcount="34"> Some doctors predict that in the not-too-distant future these drugs will be judged so safe that they will be administered routinely by paramedics in ambulances before suspected heart attack victims even reach the hospital.</s>

<s docid="AP880829-0222" num="30" wdcount="43"> ``We have to know how to respond quickly, and we have to have the courage to use these drugs in the absence of definitive diagnosis,'' says Dr. Burton Sobel of Washington University in St. Louis, a pioneer in the testing of the clot-dissolvers.</s>

<s docid="AP880829-0222" num="31" wdcount="20"> ``The most important thing we can do is teach patients in advance about the value of early treatment,'' he says.</s>

<s docid="AP880829-0222" num="32" wdcount="30"> While most public attention has focused on this new ability to prevent heart attacks, researchers have also made important progress in speeding the recovery of patients who survive heart attacks.</s>

<s docid="AP880829-0222" num="33" wdcount="28"> Researchers at the University of Michigan recently determined that some heart attack victims can be released from the hospital as soon as three days after their heart attacks.</s>

<s docid="AP880829-0222" num="34" wdcount="16"> Most heart attacks victims are kept in the hospital for at least seven to 10 days.</s>

<s docid="AP880829-0222" num="35" wdcount="20"> The patients given early discharge were able to return to work two weeks sooner than others in the study group.</s>

<s docid="AP880829-0222" num="36" wdcount="12"> After six months, not one death was recorded in the early-discharge group.</s>

<s docid="AP880829-0222" num="37" wdcount="18"> The researchers concluded that perhaps 15 percent of heart attacks victims could be safely discharged after three days.</s>

<s docid="AP880829-0222" num="38" wdcount="42"> In July, Stanford University doctors found that workers who went back to their jobs about seven weeks after their heart attacks did at least as well as workers who went back after a more typical convalescence of about 10 or 11 weeks.</s>

<s docid="AP880829-0222" num="39" wdcount="28"> All of these advances come at a time when public health experts are increasingly emphasizing the role of good health and good nutrition in lowering heart disease risk.</s>

<s docid="AP880829-0222" num="40" wdcount="30"> Early next year, the American Heart Association seal of approval will begin appearing on foods that are low in fat and cholesterol and therefore can help reduce heart disease risk.</s>

<s docid="AP880829-0222" num="41" wdcount="34"> U.S. Surgeon General C. Everett Koop in July issued his first report on nutrition, calling on Americans to lower their consumption of fats and to eat more vegetables, fruits, fish, poultry and whole grains.</s>

<s docid="AP880829-0222" num="42" wdcount="23"> The report has been likened to the first Surgeon Generals report on smoking, issued in 1964, which focused public attention on smoking's hazards.</s>

<s docid="AP880829-0222" num="43" wdcount="21"> Koop's recommendations largely echo those of the American Heart Association, but they should help carry the message to many more people.</s>

<s docid="AP880829-0222" num="44" wdcount="28"> Progress in research on heart disease is making clear that the heart attack is no longer a mysterious killer that strikes without warning and cannot be defended against.</s>

<s docid="AP880829-0222" num="45" wdcount="22"> Much can be done to prevent heart attacks, great improvements are being made in treatments, and recovery is faster than ever before.</s>

<s docid="AP880829-0222" num="46" wdcount="20"> The use of a clot-dissolver and aspirin could, alone, save 25,000 lives a year in the United States, doctors say.</s>

<s docid="AP880829-0222" num="47" wdcount="14"> ``These results,'' says Dr. Peter Sleight of Oxford University, ``will change medical practice worldwide.''</s>
</TEXT>
</DOC>
