<DOC>
<DOCNO>

<s docid="AP890115-0014" num="1" wdcount="1"> AP890115-0014</s>
</DOCNO>
<FILEID>

<s docid="AP890115-0014" num="2" wdcount="2"> AP-NR-01-15-89 1239EST</s>
</FILEID>
<FIRST>

<s docid="AP890115-0014" num="3" wdcount="6"> r a AM-Heart Bjt 01-15 0652</s>
</FIRST>
<SECOND>

<s docid="AP890115-0014" num="4" wdcount="2"> AM-Heart, Bjt,0672</s>
</SECOND>
<HEAD>

<s docid="AP890115-0014" num="5" wdcount="10"> Heart Disease Death Rate Drops Dramatically But Still Biggest Killer</s>
</HEAD>
<HEAD>

<s docid="AP890115-0014" num="6" wdcount="7"> Eds: For release at 5 p.m. EST</s>
</HEAD>
<BYLINE>

<s docid="AP890115-0014" num="7" wdcount="4"> By DANIEL Q. HANEY</s>
</BYLINE>
<BYLINE>

<s docid="AP890115-0014" num="8" wdcount="3"> AP Science Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890115-0014" num="9" wdcount="3"> MONTEREY, Calif. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890115-0014" num="10" wdcount="35"> Deaths from heart and blood vessel disease dropped 24 percent over the past decade, but it remains by far the nation's biggest killer, taking a life every 32 seconds, the American Heart Association said Sunday.</s>

<s docid="AP890115-0014" num="11" wdcount="24"> ``The good news is that we continue to see an improvement in the death rate from the biggest killer of our population,'' said Dr.</s>

<s docid="AP890115-0014" num="12" wdcount="14"> Bernadine Healy of the Cleveland Clinic Foundation, who is president of the heart association.</s>

<s docid="AP890115-0014" num="13" wdcount="12"> ``Those trends are dramatic and don't seem to be reversing,'' she said.</s>

<s docid="AP890115-0014" num="14" wdcount="24"> ``The bad news is that heart disease is still killing almost 1 million Americans a year, and we've got a long way to go''.</s>

<s docid="AP890115-0014" num="15" wdcount="12"> The association released the statistics at its annual forum for science writers.</s>

<s docid="AP890115-0014" num="16" wdcount="24"> Experts attribute the decline in death rates to a combination of healthier living habits, including fewer cigarettes and better food, and improved medical treatment.</s>

<s docid="AP890115-0014" num="17" wdcount="28"> ``The public ought to appreciate the progress that has been made in heart disease over the past 20 years,'' said Dr. Myron L. Weisfeldt of Johns Hopkins University.</s>

<s docid="AP890115-0014" num="18" wdcount="3"> ``It's almost unbelievable.</s>

<s docid="AP890115-0014" num="19" wdcount="15"> There is almost no form of heart disease that we can't approach without meaningful treatment''.</s>

<s docid="AP890115-0014" num="20" wdcount="29"> However, Weisfeldt, who is president-elect of the heart association, also cautioned that much work remains, both in improving care and encouraging people to take better care of their health.</s>

<s docid="AP890115-0014" num="21" wdcount="40"> ``I believe we can prevent at least 50 percent of the ischemic heart disease in the United States by the year 2000 if we stop smoking, get cholesterol treated if it's above 220, and identify and treat hypertension,'' he said.</s>

<s docid="AP890115-0014" num="22" wdcount="13"> Ischemic heart disease is the clogging of blood vessels that feed the heart.</s>

<s docid="AP890115-0014" num="23" wdcount="11"> It underlies most heart attacks, the single most lethal heart ailment.</s>

<s docid="AP890115-0014" num="24" wdcount="35"> Association figures indicated that in 1986 _ the most recent year for which there are statistics _ an estimated 978,500 Americans died from heart attacks, strokes and other diseases of the heart and blood vessels.</s>

<s docid="AP890115-0014" num="25" wdcount="8"> Cancer, the No. 2 killer, took 466,000 lives.</s>

<s docid="AP890115-0014" num="26" wdcount="16"> Between 1976 and 1986, the death rate from all forms of cardiovascular disease fell 24 percent.</s>

<s docid="AP890115-0014" num="27" wdcount="12"> It declined 28 percent for heart attacks and 40 percent for strokes.</s>

<s docid="AP890115-0014" num="28" wdcount="26"> The association's figures show that more than one in four Americans suffers some form of cardiovascular disease, and almost half of those eventually die from it.</s>

<s docid="AP890115-0014" num="29" wdcount="15"> About 60 percent of the heart attack deaths occur before the victim reaches the hospital.</s>

<s docid="AP890115-0014" num="30" wdcount="21"> Studies show that about half of all heart attack victims wait more than two hours before getting to an emergency room.</s>

<s docid="AP890115-0014" num="31" wdcount="26"> Weisfeldt said a major health goal is getting people to go to the hospital within three or four hours of the first sign of heart attacks.</s>

<s docid="AP890115-0014" num="32" wdcount="22"> During this period, there is still time to give them drugs to dissolve the blood clots that are causing their heart attacks.</s>

<s docid="AP890115-0014" num="33" wdcount="12"> This treatment can save lives and reduce the disability of heart attacks.</s>

<s docid="AP890115-0014" num="34" wdcount="40"> Other major goals, he said, include finding ways to improve the effectiveness of angioplasty, a technique that uses balloons to open clogged heart arteries, and finding surgical and medical techniques to identify and protect people at risk of cardiac arrest.</s>

<s docid="AP890115-0014" num="35" wdcount="19"> The heart association estimates that cardiovascular disease will cost $88.2 billion this year in medical expenses and lost wages.</s>

<s docid="AP890115-0014" num="36" wdcount="21"> Among other statistics released by the association: _The most common cardiovascular disease is high blood pressure, which affects 60 million Americans.</s>

<s docid="AP890115-0014" num="37" wdcount="16"> _About 200,000 of the deaths from cardiovascular disease each year occur in people under age 65.</s>

<s docid="AP890115-0014" num="38" wdcount="15"> _There were 1,418 heart transplants in 1987, almost nine times as many as in 1983.</s>

<s docid="AP890115-0014" num="39" wdcount="14"> _About 2.5 million Americans have angina, the chest pain resulting from clogged heart arteries.</s>

<s docid="AP890115-0014" num="40" wdcount="6"> About 300,000 new cases occur annually.</s>

<s docid="AP890115-0014" num="41" wdcount="13"> _As many as 1.5 million Americans will have heart attacks this year .</s>
</TEXT>
</DOC>
