<DOC>
<DOCNO>

<s docid="AP901003-0006" num="1" wdcount="1"> AP901003-0006</s>
</DOCNO>
<FILEID>

<s docid="AP901003-0006" num="2" wdcount="2"> AP-NY-10-03-90 2350EDT</s>
</FILEID>
<FIRST>

<s docid="AP901003-0006" num="3" wdcount="5"> r a PM-Cholesterol 10-03 0408</s>
</FIRST>
<SECOND>

<s docid="AP901003-0006" num="4" wdcount="1"> PM-Cholesterol,0460</s>
</SECOND>
<HEAD>

<s docid="AP901003-0006" num="5" wdcount="5"> Study: Cholesterol-Lowering Surgery Saves Lives</s>
</HEAD>
<BYLINE>

<s docid="AP901003-0006" num="6" wdcount="4"> By DANIEL Q. HANEY</s>
</BYLINE>
<BYLINE>

<s docid="AP901003-0006" num="7" wdcount="3"> AP Science Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP901003-0006" num="8" wdcount="2"> BOSTON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP901003-0006" num="9" wdcount="26"> An intestinal operation to lower the cholesterol of heart attack patients reduced their risk for another heart attack or death from heart disease, researchers said today.</s>

<s docid="AP901003-0006" num="10" wdcount="19"> The surgery, called a partial ileal bypass, has one significant drawback: It causes chronic diarrhea that persists for years.</s>

<s docid="AP901003-0006" num="11" wdcount="18"> In the operation, doctors change the route of the small intestine so about one-third of it is bypassed.</s>

<s docid="AP901003-0006" num="12" wdcount="12"> This reduces the amount of cholesterol that is absorbed into the bloodstream.</s>

<s docid="AP901003-0006" num="13" wdcount="15"> The $52 million, 17-year study was conducted on people who had already suffered heart attacks.</s>

<s docid="AP901003-0006" num="14" wdcount="21"> The approach lengthened the lives of people who had very mild heart attacks but not those with more severe heart damage.</s>

<s docid="AP901003-0006" num="15" wdcount="24"> During an average of 10 years of follow up, the death rate among surgery patients who had sustained minimal heart damage was 24 percent.</s>

<s docid="AP901003-0006" num="16" wdcount="12"> In a comparison group without the intestinal surgery, it was 39 percent.</s>

<s docid="AP901003-0006" num="17" wdcount="27"> Dr. Henry Buchwald of the University of Minnesota, who directed the study, said the surgery should be considered along with cholesterol-lowering drugs as a possible standard treatment.</s>

<s docid="AP901003-0006" num="18" wdcount="20"> ``It has a role in the management of patients with high cholesterol who have had a heart attack,'' Buchwald said.</s>

<s docid="AP901003-0006" num="19" wdcount="23"> ``It is eminently logical to extend all cholesterol-lowering therapy, including this, to patients with high cholesterol who have not had a heart attack''.</s>

<s docid="AP901003-0006" num="20" wdcount="19"> Besides diarrhea, those who undergo the surgery are somewhat more prone to have kidney stones, gallstones and intestinal obstructions.</s>

<s docid="AP901003-0006" num="21" wdcount="22"> The study was conducted in Minneapolis, Los Angeles, Philadelphia and Little Rock, Ark., and published in today's New England Journal of Medicine.</s>

<s docid="AP901003-0006" num="22" wdcount="22"> Despite wide acceptance of cholesterol lowering, doubts remain about whether it actually helps people live longer if they already have healthy hearts.</s>

<s docid="AP901003-0006" num="23" wdcount="24"> Although the latest study was conducted exclusively on people who had suffered heart attacks, Buchwald said he believes the research should settle that question.</s>

<s docid="AP901003-0006" num="24" wdcount="17"> ``It offers the strongest justification for marked lipid (cholesterol) ineervention that has ever been offered,'' Buchwald said.</s>

<s docid="AP901003-0006" num="25" wdcount="21"> ``It is a very powerful study and should, except for certain people who will never be satisfied, end the cholesterol controversy''.</s>

<s docid="AP901003-0006" num="26" wdcount="25"> In the study, 421 people who recovered from heart attacks underwent the surgery, while a comparison group of 417 people were treated with diet alone.</s>

<s docid="AP901003-0006" num="27" wdcount="12"> At the start of the study, their average cholesterol levels were 251.</s>

<s docid="AP901003-0006" num="28" wdcount="7"> The surgery lowered people's cholesterol 23 percent.</s>

<s docid="AP901003-0006" num="29" wdcount="26"> The overall risk of dying from heart disease or suffering another non-fatal heart attack was reduced 35 percent among the surgical patients with the healthiest hearts.</s>

<s docid="AP901003-0006" num="30" wdcount="19"> The surgical patients also required less than half as many coronary bypass operations because of clogged heart arteries .</s>
</TEXT>
</DOC>
