<DOC>
<DOCNO>

<s docid="AP900705-0149" num="1" wdcount="1"> AP900705-0149</s>
</DOCNO>
<FILEID>

<s docid="AP900705-0149" num="2" wdcount="2"> AP-NR-07-05-90 2142EDT</s>
</FILEID>
<FIRST>

<s docid="AP900705-0149" num="3" wdcount="5"> r w AM-HeartSaver 07-05 0417</s>
</FIRST>
<SECOND>

<s docid="AP900705-0149" num="4" wdcount="2"> AM-Heart Saver,410</s>
</SECOND>
<HEAD>

<s docid="AP900705-0149" num="5" wdcount="10"> Growth Factor Protects Heart Following Attack, Study In Rats Shows</s>
</HEAD>
<BYLINE>

<s docid="AP900705-0149" num="6" wdcount="3"> By PAUL RECER</s>
</BYLINE>
<BYLINE>

<s docid="AP900705-0149" num="7" wdcount="3"> AP Science Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900705-0149" num="8" wdcount="2"> WASHINGTON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900705-0149" num="9" wdcount="31"> A natural substance called transforming growth factor beta appears to be able to limit damage to cardiac cells following a heart attack, according to a study published in the journal Science.</s>

<s docid="AP900705-0149" num="10" wdcount="43"> In a study at the Jefferson Medical College in Philadelphia, a group of laboratory rats induced to have heart attacks suffered 50 percent less cell damage after injections of transforming growth factor beta than did rats that did not receive the TGF beta.</s>

<s docid="AP900705-0149" num="11" wdcount="26"> ``TGF beta is a growth factor that opposes some of the bad guys following a heart attack,'' said Dr. Allan M. Lefer, a professor at Jefferson.</s>

<s docid="AP900705-0149" num="12" wdcount="19"> Lefer said his research team simulated heart attacks in 24 rats by partially blocking key arteries in their hearts.</s>

<s docid="AP900705-0149" num="13" wdcount="10"> In 12 of the rats, the researchers injected a placebo.</s>

<s docid="AP900705-0149" num="14" wdcount="10"> In the other 12, they injected transforming growth factor beta.</s>

<s docid="AP900705-0149" num="15" wdcount="18"> For those who received the TGF beta, said Lefer, ``the damage from the attack was much less severe.</s>

<s docid="AP900705-0149" num="16" wdcount="13"> There was about 50 percent less injury with TGF beta than without it''.</s>

<s docid="AP900705-0149" num="17" wdcount="22"> The extent of heart cell damage was determined by measuring the amount of creatine kinase in the heart tissue following an attack.</s>

<s docid="AP900705-0149" num="18" wdcount="20"> Hearts damaged when the blood supply is interrupted, as in a heart attack, tend to lose creatine kinase, said Lefer.</s>

<s docid="AP900705-0149" num="19" wdcount="17"> Thus, by measuring for the loss of this substance, researchers could determine the amount of heart damage.</s>

<s docid="AP900705-0149" num="20" wdcount="29"> Lefer said the TGF beta seems to block the action of other substances, such as tumor necrosis factor, that can cause blood vessels to narrow following a heart attack.</s>

<s docid="AP900705-0149" num="21" wdcount="18"> Narrowed blood vessels carry less oxygen-rich blood to cells and this causes additional injury following a heart attack.</s>

<s docid="AP900705-0149" num="22" wdcount="29"> TGF beta is normally present in heart cells, but the study published in Science said that it is missing from rat heart cells damaged by a simulated heart attack.</s>

<s docid="AP900705-0149" num="23" wdcount="25"> Though TGF beta is produced naturally in the body, Lefer said his research team used a substance produced artificially by Genentech, a California biotechnology firm.</s>

<s docid="AP900705-0149" num="24" wdcount="31"> Lefer said his team is now conducting additional studies with TGF beta and that any experimental treatment of human heart attack victims with the substance is at least a year away.</s>

<s docid="AP900705-0149" num="25" wdcount="16"> Jefferson Medical College, where the study was done, is part of Thomas Jefferson University in Philadelphia.</s>

<s docid="AP900705-0149" num="26" wdcount="18"> Science, which published the study, is the journal of the American Association for the Advancement of Science .</s>
</TEXT>
</DOC>
