<DOC>
<DOCNO>

<s docid="AP900322-0112" num="1" wdcount="1"> AP900322-0112</s>
</DOCNO>
<FILEID>

<s docid="AP900322-0112" num="2" wdcount="2"> AP-NR-03-22-90 1532EST</s>
</FILEID>
<FIRST>

<s docid="AP900322-0112" num="3" wdcount="7"> r a AM-HeartAttack 1stLd-Writethru a0636 03-22 0614</s>
</FIRST>
<SECOND>

<s docid="AP900322-0112" num="4" wdcount="7"> AM-Heart Attack, 1st Ld - Writethru, a0636,0623</s>
</SECOND>
<HEAD>

<s docid="AP900322-0112" num="5" wdcount="9"> Study Finds Drug Lowers Death Risk After Heart Attack</s>
</HEAD>
<NOTE>

<s docid="AP900322-0112" num="6" wdcount="15"> Eds: CORRECTS spelling to Verapimil sted verapimil in grafs 2, 5, 9, 10 and 11</s>
</NOTE>
<BYLINE>

<s docid="AP900322-0112" num="7" wdcount="4"> By DANIEL Q. HANEY</s>
</BYLINE>
<BYLINE>

<s docid="AP900322-0112" num="8" wdcount="3"> AP Science Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900322-0112" num="9" wdcount="3"> NEW ORLEANS (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900322-0112" num="10" wdcount="33"> A drug that eases the heart's workload can cut the risk of new cardiac attacks and death by 20 percent in people recovering from heart attacks, according to a major study released Thursday.</s>

<s docid="AP900322-0112" num="11" wdcount="26"> The study, conducted in Denmark, found that the drug Verapamil, known as a calcium channel blocker, was effective for the 1 years after a heart attack.</s>

<s docid="AP900322-0112" num="12" wdcount="15"> Calcium blockers are among several classes of medicines commonly prescribed to relieve high blood pressure.</s>

<s docid="AP900322-0112" num="13" wdcount="32"> ``This is the first trial that indicates that a calcium blocker may be beneficial after an acute myocardial infarction,'' or heart attack, said Dr. Carl J. Pepine of the University of Florida.</s>

<s docid="AP900322-0112" num="14" wdcount="26"> Several other studies of calcium blockers, including one large U.S. study published last year, failed to find any benefit from using the medicines after heart attacks.</s>

<s docid="AP900322-0112" num="15" wdcount="27"> According to the Danish study, Verapamil is about as effective as another variety of blood pressure medicines known as beta blockers at protecting people after heart attacks.</s>

<s docid="AP900322-0112" num="16" wdcount="23"> While calcium blockers may not replace beta blockers after heart attacks, the researchers said these drugs still should have a role in treatment.</s>

<s docid="AP900322-0112" num="17" wdcount="8"> ``We feel it is important to have alternatives.</s>

<s docid="AP900322-0112" num="18" wdcount="23"> Many patients do not tolerate beta blockers,'' said Dr. Kresten Mellemgaard of Central County Hospital in Hillerod, Denmark, a co-author of the study.</s>

<s docid="AP900322-0112" num="19" wdcount="12"> Beta blockers are generally not recommended for people with asthma and emphysema.</s>

<s docid="AP900322-0112" num="20" wdcount="18"> This means the drugs often cannot be given to cigarette smokers, who are frequent victims of heart attacks.</s>

<s docid="AP900322-0112" num="21" wdcount="24"> In the study, conducted at 20 community hospitals, doctors compared 897 patients who got Verapamil after heart attacks with 878 people who took placebos.</s>

<s docid="AP900322-0112" num="22" wdcount="27"> After 18 months of followup, there were 146 deaths or recurring heart attacks among the Verapamil patients, compared with 180 in people who got the dummy medication.</s>

<s docid="AP900322-0112" num="23" wdcount="14"> ``We wanted to see if an effect would be observed with Verapamil,'' said Dr.</s>

<s docid="AP900322-0112" num="24" wdcount="7"> Forgen Fischer Hansen of Copenhagen Municipal Hospital.</s>

<s docid="AP900322-0112" num="25" wdcount="32"> ``If it had an effect, it should be seen in the first 12 to 18 months, because there is a big increase in mortality in myocardial infarction in this period,'' he said.</s>

<s docid="AP900322-0112" num="26" wdcount="4"> ``Then it levels off.</s>

<s docid="AP900322-0112" num="27" wdcount="4"> That's what we demonstrated.</s>

<s docid="AP900322-0112" num="28" wdcount="2"> It worked''.</s>

<s docid="AP900322-0112" num="29" wdcount="35"> The researchers believe that by reducing the amount of work needed by the heart to sustain circulation, calcium blockers lowered the chances of ischemia, episodes in which the heart's own muscle is deprived of oxygen.</s>

<s docid="AP900322-0112" num="30" wdcount="19"> They said they were unsure why earlier studies failed to show any benefit from calcium blockers after heart attacks.</s>

<s docid="AP900322-0112" num="31" wdcount="14"> However, they noted that some studies enrolled patients who were also taking beta blockers.</s>

<s docid="AP900322-0112" num="32" wdcount="10"> And this might have obscured any benefits from calcium blockers.</s>

<s docid="AP900322-0112" num="33" wdcount="13"> The results were presented at a meeting of the American College of Cardiology.</s>

<s docid="AP900322-0112" num="34" wdcount="8"> Among other research described at the meeting: _Dr.</s>

<s docid="AP900322-0112" num="35" wdcount="40"> James H. Chesebro of the Mayo Clinic said a five-year study found that aspirin does not stop the continued buildup of existing blockages in the arteries feeding the heart, although it may modestly protect against the development of new deposits.</s>

<s docid="AP900322-0112" num="36" wdcount="16"> However, like other studies, this one found that aspirin signficantly cut the risk of heart attacks.</s>

<s docid="AP900322-0112" num="37" wdcount="27"> _Dr. Eugene Braunwald of Harvard Medical School said the next phase of a large study of clot-dissolving drugs will see what effect they have in unstable angina.</s>

<s docid="AP900322-0112" num="38" wdcount="19"> This is a condition in which people suffer spontaneous chest pain that is not triggered by work or stress.</s>

<s docid="AP900322-0112" num="39" wdcount="13"> Until now, the drugs have been used only to treat heart attacks .</s>
</TEXT>
</DOC>
