<DOC>
<DOCNO>

<s docid="WSJ880603-0129" num="1" wdcount="1"> WSJ880603-0129</s>
</DOCNO>
<HL>

<s docid="WSJ880603-0129" num="2" wdcount="11"> FDA Urges Caution On the Use of Aspirin Against Heart Attack</s>
</HL>
<SO>
</SO>
<IN>

<s docid="WSJ880603-0129" num="3" wdcount="1"> PHA</s>
</IN>
<G>

<s docid="WSJ880603-0129" num="4" wdcount="1"> FDA</s>
</G>
<DATELINE>

<s docid="WSJ880603-0129" num="5" wdcount="2"> CHICAGO (AP)</s>
</DATELINE>
<TEXT>

<s docid="WSJ880603-0129" num="6" wdcount="25"> Doctors should be cautious in prescribing aspirin as a preventer of heart attacks until more research supports its value, the Food and Drug Administration said.</s>

<s docid="WSJ880603-0129" num="7" wdcount="33"> Taking aspirin to prevent heart attacks may increase some people's chances of dying of other things, especially hemorrhagic strokes, the agency said in a commentary in today's Journal of the American Medical Association.</s>

<s docid="WSJ880603-0129" num="8" wdcount="23"> The FDA persuaded aspirin makers in March to refrain from promoting aspirin as a preventer of first heart attacks, at least for now.</s>

<s docid="WSJ880603-0129" num="9" wdcount="35"> A study published in January indicated an aspirin every other day reduced the risk of nonfatal, first heart attacks 47% in 11,000 male doctors over five years, compared with 11,000 who took a non-aspirin substitute.</s>

<s docid="WSJ880603-0129" num="10" wdcount="16"> Aspirin tends to promote bleeding by reducing the ability of blood platelets to help form clots.</s>

<s docid="WSJ880603-0129" num="11" wdcount="19"> Heart attacks usually occur when clots form in the arteries nourishing the heart and choke off its blood supply.</s>

<s docid="WSJ880603-0129" num="12" wdcount="34"> But aspirin may increase health risks for people who already have clotting problems, or for those who have high blood pressure, which puts them at increased risk for hemorrhagic strokes, the FDA commentary said.</s>

<s docid="WSJ880603-0129" num="13" wdcount="24"> Strokes are the result of brain damage caused by bleeding in the brain or by blood clots; hemorrhagic strokes are those caused by bleeding.</s>

<s docid="WSJ880603-0129" num="14" wdcount="30"> The FDA commentary pointed to 10 hemorrhagic strokes recorded among the 11,000 subjects taking aspirin in the recent study, compared with two such strokes among 11,000 subjects taking the substitute.</s>

<s docid="WSJ880603-0129" num="15" wdcount="20"> Overall death rates for the two groups were the same, though the aspirin group's nonfatal heart-attack rate was much lower.</s>

<s docid="WSJ880603-0129" num="16" wdcount="16"> There were 104 nonfatal heart attacks among the aspirin users and 189 in the comparison group.</s>

<s docid="WSJ880603-0129" num="17" wdcount="32"> "Physicians, will, for a time, be forced to make their professional judgments about aspirin use on the basis of incomplete information," said the FDA commentary, co-written by agency Director Dr. Frank E.</s>

<s docid="WSJ880603-0129" num="18" wdcount="20"> Young. "We agree with them completely," said Dr. Julie Buring, a Harvard University researcher who participated in the aspirin study.</s>

<s docid="WSJ880603-0129" num="19" wdcount="27"> She added in a telephone interview yesterday that an extension of the study is under way, and researchers expect to report to the FDA in late fall.</s>

<s docid="WSJ880603-0129" num="20" wdcount="38"> The commentary noted a British study, also released in January, of 5,000 male physicians that found that aspirin failed to protect against heart attacks, and that it was associated with a 2 1/2-fold increase in disabling strokes .</s>
</TEXT>
</DOC>
