<DOC>
<DOCNO>

<s docid="WSJ910418-0105" num="1" wdcount="1"> WSJ910418-0105</s>
</DOCNO>
<DOCID>

<s docid="WSJ910418-0105" num="2" wdcount="2"> 910418-0105 .</s>
</DOCID>
<HL>

<s docid="WSJ910418-0105" num="3" wdcount="21"> Health: Test Identifies Patients at Risk Of Heart Attack ---- By Jerry E. Bishop Staff Reporter of The Wall Street Journal</s>
</HL>
<DATE>

<s docid="WSJ910418-0105" num="4" wdcount="1"> 04/18/91</s>
</DATE>
<SO>

<s docid="WSJ910418-0105" num="5" wdcount="6"> WALL STREET JOURNAL (J), PAGE B1</s>
</SO>
<CO>

<s docid="WSJ910418-0105" num="6" wdcount="2"> BMY MRK</s>
</CO>
<MS>

<s docid="WSJ910418-0105" num="7" wdcount="5"> CONSUMER NON-CYCLICAL (NCY) TECHNOLOGY (TEC)</s>
</MS>
<IN>

<s docid="WSJ910418-0105" num="8" wdcount="10"> DRUG MANUFACTURERS (DRG) MEDICAL AND BIOTECHNOLOGY, GENETIC RESEARCH, PROSTHETICS (MTC)</s>
</IN>
<RE>

<s docid="WSJ910418-0105" num="9" wdcount="6"> NEW JERSEY (NJ) NEW YORK (NY)</s>
</RE>
<LP>

<s docid="WSJ910418-0105" num="10" wdcount="31"> NEW YORK -- An experiment with more than 1,700 high blood pressure patients showed that a blood and urine test can pinpoint those patients most likely to have a heart attack.</s>

<s docid="WSJ910418-0105" num="11" wdcount="30"> The experiment suggests that doctors could test their patients with mild to moderate high blood pressure to determine how intensively they should be treated to prevent heart attacks, researchers said.</s>

<s docid="WSJ910418-0105" num="12" wdcount="26"> The experiment indicated that the test can spot those patients with extremely low risk of heart attack as well as those with a high risk .</s>
</LP>
<TEXT>

<s docid="WSJ910418-0105" num="13" wdcount="29"> The experiment also hinted that the blood and urine test, which measures the activity of a blood protein called renin, might suggest a new "risk factor" for heart attacks.</s>

<s docid="WSJ910418-0105" num="14" wdcount="35"> About half of the 1.5 million Americans who suffer a heart attack each year don't have the known risk factors for heart disease, such as high cholesterol levels, cigarette smoking, obesity and high blood pressure.</s>

<s docid="WSJ910418-0105" num="15" wdcount="16"> It is unknown what distinguishes these seemingly healthy people from those who don't suffer heart attacks.</s>

<s docid="WSJ910418-0105" num="16" wdcount="37"> The blood and urine test is already being done in many commercial laboratories but for medical conditions other than heart attack risk, said John H. Laragh of the Cardiovascular Center at Cornell University and New York Hospital.</s>

<s docid="WSJ910418-0105" num="17" wdcount="21"> "In our hands, it cost about $40 and in other labs it may cost the patient $40 to $80," he said.</s>

<s docid="WSJ910418-0105" num="18" wdcount="20"> Dr. Laragh pioneered the research underlying use of the test, which was developed by his wife, biochemist Jean E. Sealey.</s>

<s docid="WSJ910418-0105" num="19" wdcount="12"> The test, which isn't patented, is available in kit form to laboratories.</s>

<s docid="WSJ910418-0105" num="20" wdcount="23"> The blood portion of the test determines whether the kidneys are releasing renin into the blood stream and how active the chemical is.</s>

<s docid="WSJ910418-0105" num="21" wdcount="18"> The release of renin is the first step in a rapid chemical chain reaction that raises blood pressure.</s>

<s docid="WSJ910418-0105" num="22" wdcount="14"> The urine portion of the test tells how much salt is in the bloodstream.</s>

<s docid="WSJ910418-0105" num="23" wdcount="11"> A high concentration of salt in the blood also raises pressure.</s>

<s docid="WSJ910418-0105" num="24" wdcount="35"> The test is based on the fact that if the salt concentration in the blood rises, tending to boost blood pressure, the activity of the renin normally drops to offset the effect of the salt.</s>

<s docid="WSJ910418-0105" num="25" wdcount="31"> The new experiment was designed to test a theory put forth by Dr. Laragh and his colleagues that the activity of the renin in the blood foretells a possible heart attack.</s>

<s docid="WSJ910418-0105" num="26" wdcount="11"> The theory has provoked sometimes furious controversy for almost 20 years.</s>

<s docid="WSJ910418-0105" num="27" wdcount="35"> The Cornell cardiologist has argued that in many people with high blood pressure the activity of the renin in the blood is much higher than is warranted by the amount of salt in the blood.</s>

<s docid="WSJ910418-0105" num="28" wdcount="13"> Such "high renin" people are at a high risk of a heart attack.</s>

<s docid="WSJ910418-0105" num="29" wdcount="30"> On the other hand, in other patients with high blood pressure, the activity of the renin is much lower than is warranted by the degree of salt in the blood.</s>

<s docid="WSJ910418-0105" num="30" wdcount="16"> These "low renin" people are at a low risk of heart attack, Dr. Laragh has maintained.</s>

<s docid="WSJ910418-0105" num="31" wdcount="28"> In the experiment, blood and urine samples were obtained at New York City offices and factories from 1,717 workers found to have mild to moderate high blood pressure.</s>

<s docid="WSJ910418-0105" num="32" wdcount="40"> The patients' high blood pressure was initially discovered in a screening program carried out by Michael H. Alderman and his colleagues at Albert Einstein College of Medicine, who operate a work-site blood pressure control program in cooperation with local unions.</s>

<s docid="WSJ910418-0105" num="33" wdcount="3"> In 1981, Dr.</s>

<s docid="WSJ910418-0105" num="34" wdcount="15"> Laragh's group began testing the renin activity in blood and urine samples collected by Dr.</s>

<s docid="WSJ910418-0105" num="35" wdcount="2"> Alderman's team.</s>

<s docid="WSJ910418-0105" num="36" wdcount="17"> They kept track of the workers for more than eight years to see which had heart attacks.</s>

<s docid="WSJ910418-0105" num="37" wdcount="16"> The results, published in this week's New England Journal of Medicine, lend strong support to Dr.</s>

<s docid="WSJ910418-0105" num="38" wdcount="2"> Laragh's theory.</s>

<s docid="WSJ910418-0105" num="39" wdcount="9"> Only 12% of the patients had high renin "profiles".</s>

<s docid="WSJ910418-0105" num="40" wdcount="27"> But the seven heart attacks in this small group constituted the highest incidence of heart attacks among the patients, 13 heart attacks per 1,000 person-years of observation.</s>

<s docid="WSJ910418-0105" num="41" wdcount="53"> The incidence in the high renin patients was more than double the incidence in those with a normal renin profile -- 5.3 heart attacks per 1,000 person-years -- and more than triple that of the patients with a low renin profile, 3.3 per 1,000 person-years, Drs. Alderman, Laragh and their respective colleagues reported.</s>

<s docid="WSJ910418-0105" num="42" wdcount="26"> Regardless of how the statisticians broke down the patients into various groups, those with high renin profiles almost invariably had the highest incidence of heart attacks.</s>

<s docid="WSJ910418-0105" num="43" wdcount="30"> Smokers had more heart attacks than nonsmokers, but the incidence of attacks in smokers with high renin profiles was more than six times that in smokers with low renin profiles.</s>

<s docid="WSJ910418-0105" num="44" wdcount="23"> "But the real dynamite is in the patients who didn't have any of the usual risk factors," Dr. Laragh said in an interview.</s>

<s docid="WSJ910418-0105" num="45" wdcount="41"> Among patients who had normal blood cholesterol level and were free of diabetes, "those with high renin profiles were seven times more likely to have a myocardial infarction {heart attack} than those with normal or low renin profiles," the researchers wrote.</s>

<s docid="WSJ910418-0105" num="46" wdcount="23"> There were no heart attacks among the 240 patients with low renin profiles who had no risk factors other than high blood pressure.</s>

<s docid="WSJ910418-0105" num="47" wdcount="25"> To Dr. Laragh, this suggests that a high renin profile might signal a high risk of heart attack even for people without high blood pressure.</s>

<s docid="WSJ910418-0105" num="48" wdcount="15"> "We think everybody should have this simple and accurate test," he said in the interview.</s>

<s docid="WSJ910418-0105" num="49" wdcount="7"> "It's a new window into heart disease".</s>

<s docid="WSJ910418-0105" num="50" wdcount="38"> In an accompanying editorial, Victor J. Dzau of Stanford University medical school said the study shows that the renin profile test is "potentially useful" in identifying high blood pressure patients who are at risk of a heart attack.</s>

<s docid="WSJ910418-0105" num="51" wdcount="17"> But, he wrote, "a larger, population-based study will be important in confirming the results of this paper".</s>

<s docid="WSJ910418-0105" num="52" wdcount="11"> The experiment has implications for drug makers as well as patients.</s>

<s docid="WSJ910418-0105" num="53" wdcount="24"> Apparently by coincidence, Abbott Laboratories announced on Tuesday that is developing a high blood pressure drug that works by inhibiting the activity of renin.</s>

<s docid="WSJ910418-0105" num="54" wdcount="13"> Other major drug makers are thought to also be working on renin inhibitors.</s>

<s docid="WSJ910418-0105" num="55" wdcount="12"> The experiment hints these drugs might also protect patients from heart attacks.</s>

<s docid="WSJ910418-0105" num="56" wdcount="41"> A big-selling class of high blood pressure drugs, including Bristol-Myers Squibb Corp.'s Capoten and Merck & Co.'s Vasotec, are known as ACE inhibitors because they work by stopping renin in the blood from being converted to a second chemical called angiotensin.</s>

<s docid="WSJ910418-0105" num="57" wdcount="23"> Studies are under way to see if these ACE inhibitors protect patients against heart attacks as well as lower their blood pressure .</s>
</TEXT>
</DOC>
