<DOC>
<DOCNO>

<s docid="AP900424-0048" num="1" wdcount="1"> AP900424-0048</s>
</DOCNO>
<FILEID>

<s docid="AP900424-0048" num="2" wdcount="2"> AP-NR-04-24-90 0636EDT</s>
</FILEID>
<FIRST>

<s docid="AP900424-0048" num="3" wdcount="7"> u a PM-SpaceShuttle 4thLd-Writethru a0484 04-24 0727</s>
</FIRST>
<SECOND>

<s docid="AP900424-0048" num="4" wdcount="7"> PM-Space Shuttle, 4th Ld - Writethru, a0484,730</s>
</SECOND>
<HEAD>

<s docid="AP900424-0048" num="5" wdcount="7"> Discovery Readied for Launch With Space Telescope</s>
</HEAD>
<NOTE>

<s docid="AP900424-0048" num="6" wdcount="36"> Eds: Top 4 grafs with all astronauts aboard, pickup 5th bgng ``The $1.5 billion,'' inserts new graf after 8th bgng ``Columbia, which'' to include that Hubble has been delayed since 1983; minor editing changes below .</s>
</NOTE>
<HEAD>

<s docid="AP900424-0048" num="7" wdcount="2"> LaserPhoto covering</s>
</HEAD>
<BYLINE>

<s docid="AP900424-0048" num="8" wdcount="3"> By MARCIA DUNN</s>
</BYLINE>
<BYLINE>

<s docid="AP900424-0048" num="9" wdcount="3"> AP Aerospace Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900424-0048" num="10" wdcount="4"> CAPE CANAVERAL, Fla. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900424-0048" num="11" wdcount="32"> Five astronauts boarded Discovery today for a second try at sending the Hubble Space Telescope into orbit to scan the outermost reaches of the universe for clues to the beginning of time.</s>

<s docid="AP900424-0048" num="12" wdcount="25"> ``Astronomers are starting to tingle again in anticipation of what the Hubble will be able to accomplish,'' said Lennard Fisk, head of NASA science activities.</s>

<s docid="AP900424-0048" num="13" wdcount="27"> Air Force forecasters said there was a 90 percent chance the weather would be favorable for launching the shuttle at the scheduled time of 8:31 a.m. EDT.</s>

<s docid="AP900424-0048" num="14" wdcount="22"> More than a half million gallons of liquid hydrogen and liquid oxygen were pumped into the space ship's fuel tanks after midnight.</s>

<s docid="AP900424-0048" num="15" wdcount="22"> The astronauts, wearing bright orange flight suits, climbed into the crew cabin just as dawn was breaking over the Kennedy Space Center.</s>

<s docid="AP900424-0048" num="16" wdcount="30"> The $1.5 billion telescope, NASA's costliest cargo, will give astronomers ``a new set of eyes and ears that we don't have,'' said William Lenoir, head of NASA's space flight program.</s>

<s docid="AP900424-0048" num="17" wdcount="7"> ``It's going to change our perspective altogether.</s>

<s docid="AP900424-0048" num="18" wdcount="19"> I can't say what we're going to learn, but I'll be astounded if we don't learn many new things''.</s>

<s docid="AP900424-0048" num="19" wdcount="31"> Discovery was aiming for an altitude of 380 miles, the highest a shuttle has ever gone, so the telescope can be placed in its proper orbit far above Earth's distorting atmosphere.</s>

<s docid="AP900424-0048" num="20" wdcount="6"> It is the 35th shuttle mission.</s>

<s docid="AP900424-0048" num="21" wdcount="39"> Columbia, which journeys into space next month with the Astro observatory, sat on a launch pad 1.6 miles from Discovery, only the second time both pads have been occupied; the first was in 1986 just before the Challenger explosion.</s>

<s docid="AP900424-0048" num="22" wdcount="20"> Hubble has been waiting to take its place in space since 1983, delayed by technical problems and the Challenger accident.</s>

<s docid="AP900424-0048" num="23" wdcount="24"> The latest postponement occurred April 10, when Discovery's launch was scrubbed four minutes before liftoff because of a faulty power unit on the shuttle.</s>

<s docid="AP900424-0048" num="24" wdcount="25"> The mood at the Kennedy Space Center was considerably less festive than during the first launch attempt, when hundreds of astronomers gathered with their families.</s>

<s docid="AP900424-0048" num="25" wdcount="22"> The day after launch, mission specialist Steven A. Hawley will use the shuttle's mechanical arm to lift the 24,250-pound telescope into space.</s>

<s docid="AP900424-0048" num="26" wdcount="14"> Veteran spacewalkers Bruce McCandless II and Kathryn Sullivan will assist if a problem develops.</s>

<s docid="AP900424-0048" num="27" wdcount="26"> Discovery will follow Hubble from 40 miles away for two days until after its lens cap is opened, exposing the finely polished 94.5-inch mirror to starlight.</s>

<s docid="AP900424-0048" num="28" wdcount="18"> Hubble is not expected to start providing scientific data by satellite for a month or more after liftoff.</s>

<s docid="AP900424-0048" num="29" wdcount="23"> However, NASA said it will release its first image _ an open star cluster in the constellation Carina _ a week after launch.</s>

<s docid="AP900424-0048" num="30" wdcount="26"> In addition to the $1.5 billion cost of Hubble, $500 million has been spent on spare parts, astronaut training and computer software to operate the instrument.</s>

<s docid="AP900424-0048" num="31" wdcount="14"> The European Space Agency contributed $250 million for 15 percent of the viewing time.</s>

<s docid="AP900424-0048" num="32" wdcount="17"> NASA estimates it will cost $200 million a year to operate and maintain the telescope in space.</s>

<s docid="AP900424-0048" num="33" wdcount="23"> During its 15-year working lifetime, the telescope will provide astronomers with 10 times better resolution and 25 times more sensitivity than ground-based observatories.</s>

<s docid="AP900424-0048" num="34" wdcount="25"> As a result, they will be able to study stars and galaxies so distant their light has been traveling toward Earth for 14 billion years.</s>

<s docid="AP900424-0048" num="35" wdcount="27"> Astronomers hope to learn whether the universe was created 15 billion years ago as believed and uncover some of the mystery surrounding galaxies, black holes and quasars.</s>

<s docid="AP900424-0048" num="36" wdcount="15"> Hubble also is expected to shed light on how and when the universe might end.</s>

<s docid="AP900424-0048" num="37" wdcount="21"> The telescope is named for the late astronomer Edwin P. Hubble, who discovered during the 1920s that the universe is expanding.</s>

<s docid="AP900424-0048" num="38" wdcount="18"> His work gave rise to the Big Bang theory that the universe was created by a tremendous explosion.</s>

<s docid="AP900424-0048" num="39" wdcount="20"> In addition to Hubble, Discovery carries a human skull filled with sensors to measure the space radiation that astronauts receive.</s>

<s docid="AP900424-0048" num="40" wdcount="8"> It is the skull's third trip into space.</s>

<s docid="AP900424-0048" num="41" wdcount="18"> The shuttle is to end its five-day mission with a landing at Edwards Air Force Base, Calif .</s>
</TEXT>
</DOC>
