<DOC>
<DOCNO>

<s docid="AP900424-0096" num="1" wdcount="1"> AP900424-0096</s>
</DOCNO>
<FILEID>

<s docid="AP900424-0096" num="2" wdcount="2"> AP-NR-04-24-90 1402EDT</s>
</FILEID>
<FIRST>

<s docid="AP900424-0096" num="3" wdcount="6"> u a AM-SpaceShuttle Bjt 04-24 0848</s>
</FIRST>
<SECOND>

<s docid="AP900424-0096" num="4" wdcount="3"> AM-Space Shuttle, Bjt,870</s>
</SECOND>
<HEAD>

<s docid="AP900424-0096" num="5" wdcount="8"> Hubble Out of this World _ At Last</s>
</HEAD>
<NOTE>

<s docid="AP900424-0096" num="6" wdcount="2"> With LaserPhotos</s>
</NOTE>
<BYLINE>

<s docid="AP900424-0096" num="7" wdcount="4"> By HARRY F. ROSENTHAL</s>
</BYLINE>
<BYLINE>

<s docid="AP900424-0096" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900424-0096" num="9" wdcount="4"> CAPE CANAVERAL, Fla. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900424-0096" num="10" wdcount="33"> Seven years late, the Hubble Space Telescope is where it belongs, out of this world and in search of others so distant that they may have been formed at the beginning of time.</s>

<s docid="AP900424-0096" num="11" wdcount="25"> Less than five hours after it rode into space aboard the shuttle Discovery on Tuesday, the $1.5 billion telescope sent its first test radio signal.</s>

<s docid="AP900424-0096" num="12" wdcount="14"> At the sign of life, applause and cheers erupted in Mission Control in Houston.</s>

<s docid="AP900424-0096" num="13" wdcount="16"> ``As near as we can tell, everything looks perfect,'' said astronaut Steve Hawley from the shuttle.</s>

<s docid="AP900424-0096" num="14" wdcount="17"> Hawley's job on Wednesday will be to drop the telescope overboard for a 15-year stay in space.</s>

<s docid="AP900424-0096" num="15" wdcount="32"> Discovery, trailing an arc of white smoke into a brilliant blue sky, carried the silver-colored telescope to an orbit 380 miles above Earth _ higher by 70 miles than any previous shuttle.</s>

<s docid="AP900424-0096" num="16" wdcount="23"> There the Hubble will stay to search for yet-unseen wonders of creation with instruments that can look 14 billion years backward in time.</s>

<s docid="AP900424-0096" num="17" wdcount="5"> ``Our window on the universe''!</s>

<s docid="AP900424-0096" num="18" wdcount="15"> NASA launch commentator George Diller exulted as the Discovery rose off its seaside launch pad.</s>

<s docid="AP900424-0096" num="19" wdcount="28"> ``It's a beautiful day to have Hubble Space Telescope in orbit instead of here on Earth like it's been for so many years,'' said NASA administrator Richard Truly.</s>

<s docid="AP900424-0096" num="20" wdcount="7"> ``Hubble's in its element and I'm delighted''.</s>

<s docid="AP900424-0096" num="21" wdcount="19"> The telescope was supposed to be launched in 1983, but technical problems and the Challenger accident delayed its deployment.</s>

<s docid="AP900424-0096" num="22" wdcount="26"> It suffered a further delay two weeks ago when the countdown was stopped at the four-minutes-to-go point because of a faulty hydraulic unit on the shuttle.</s>

<s docid="AP900424-0096" num="23" wdcount="18"> While it remained on Earth, the telescope cost $7 million a month to exercise and keep in readiness.</s>

<s docid="AP900424-0096" num="24" wdcount="22"> In its first day in space, that checkout and testing continued remotely under control of the Goddard Space Flight Center in Maryland.</s>

<s docid="AP900424-0096" num="25" wdcount="36"> On hand to watch the Discovery launching was a contingent of scientists who have hailed the Hubble as the greatest advance in astronomy since Galileo raised a small telescope to his eyes nearly 400 years ago.</s>

<s docid="AP900424-0096" num="26" wdcount="22"> Truly referred to the early-day astronomer when he was asked about the long delays in getting the telescope to its working station.</s>

<s docid="AP900424-0096" num="27" wdcount="26"> ``Somebody the other day said, `Who remembers the day that Galileo picked up his telescope to look at the stars'''? said Truly, a former shuttle astronaut.</s>

<s docid="AP900424-0096" num="28" wdcount="15"> ``It doesn't matter what day we launch Hubble, it matters that we do it right''.</s>

<s docid="AP900424-0096" num="29" wdcount="19"> The telescope is 43 feet long and 14 feet in diameter, about the size of a railroad tank car.</s>

<s docid="AP900424-0096" num="30" wdcount="25"> When it flies free, it will receive electrical power for its six scientific instruments from two wing-like solar arrays that extend outward on each side.</s>

<s docid="AP900424-0096" num="31" wdcount="30"> It is named after the late astronomer Edwin P. Hubble, who theorized that the universe was expanding and that the farther away a galaxy is, the faster it is traveling.</s>

<s docid="AP900424-0096" num="32" wdcount="24"> That gave support to the theory that a massive explosion _ the Big Bang _ created the universe 10 to 20 billion years ago.</s>

<s docid="AP900424-0096" num="33" wdcount="18"> The Hubble is expected to help provide the answer to two major questions: How old is the universe?</s>

<s docid="AP900424-0096" num="34" wdcount="4"> How big is it?</s>

<s docid="AP900424-0096" num="35" wdcount="14"> The telescope has two mirrors, one 94.5 inches in diameter, the other 12 inches.</s>

<s docid="AP900424-0096" num="36" wdcount="14"> Two of the instruments are cameras, two are spectrometers and one is a photometer.</s>

<s docid="AP900424-0096" num="37" wdcount="17"> In addition, the fine pointing system acts as a sixth instrument by providing precise measurement of distances.</s>

<s docid="AP900424-0096" num="38" wdcount="38"> On Wednesday, Hawley is to grapple the 12-ton telescope with the shuttle's mechanical arm, lift it out of the cargo bay, point it, and _ after a long checkout _ drop it overboard to orbit on its own.</s>

<s docid="AP900424-0096" num="39" wdcount="12"> In the cargo bay, the telescope receives electrical power from the shuttle.</s>

<s docid="AP900424-0096" num="40" wdcount="30"> But the juice is cut when the instrument is lifted out and it will depend on internal batteries until the solar panels are extended to receive light from the sun.</s>

<s docid="AP900424-0096" num="41" wdcount="35"> Should the solar panels not deploy, mission specialists Bruce McCandless and Kathryn Sullivan will be standing by, partially dressed in space suits, ready to go into the open cargo bay to unfurl the arrays manually.</s>

<s docid="AP900424-0096" num="42" wdcount="7"> Discovery's launch was not without its problems.</s>

<s docid="AP900424-0096" num="43" wdcount="27"> With 31 seconds left in the countdown, the computer that runs the final moments before liftoff refused to close a fuel valve and stopped the launch process.</s>

<s docid="AP900424-0096" num="44" wdcount="17"> The problem was overcome and the shuttle lifted off at 8:34 a.m. EDT, about three minutes late.</s>

<s docid="AP900424-0096" num="45" wdcount="18"> The shuttle is scheduled to land Sunday at 9:49 a.m. EDT at Edwards Air Force Base in California.</s>

<s docid="AP900424-0096" num="46" wdcount="21"> ``On the way uphill,'' as Commander Loren J. Shriver put it, the shuttle's windshield was splattered with ``several flecks of things''.</s>

<s docid="AP900424-0096" num="47" wdcount="27"> He said the windshield was streaked by the debris and that it also was smeared when the spent booster rockets fell off during the climb to orbit.</s>

<s docid="AP900424-0096" num="48" wdcount="20"> The astronauts also had problems with their UHF radio circuit, and one of the ship's small rear thrusters was inoperative.</s>

<s docid="AP900424-0096" num="49" wdcount="6"> Neither problem was considered serious .</s>
</TEXT>
</DOC>
