<DOC>
<DOCNO>

<s docid="AP900428-0050" num="1" wdcount="1"> AP900428-0050</s>
</DOCNO>
<FILEID>

<s docid="AP900428-0050" num="2" wdcount="2"> AP-NR-04-28-90 1018EDT</s>
</FILEID>
<FIRST>

<s docid="AP900428-0050" num="3" wdcount="7"> u a PM-SpaceShuttle 1stLd-Writethru a0444 04-28 1012</s>
</FIRST>
<SECOND>

<s docid="AP900428-0050" num="4" wdcount="7"> PM-Space Shuttle, 1st Ld - Writethru, a0444,1034</s>
</SECOND>
<HEAD>

<s docid="AP900428-0050" num="5" wdcount="9"> Space Telescope Resumes Operations; Shuttle Crew Prepares for Landing</s>
</HEAD>
<NOTE>

<s docid="AP900428-0050" num="6" wdcount="33"> Eds: LEADS with 12 grafs to UPDATE with quote from news conference, telescope's instruments still on hold, other detail from briefing; and to CORRECT spelling of Olivier sted Oliver in 6-7th grafs pvs.</s>

<s docid="AP900428-0050" num="7" wdcount="9"> Picks up 8th graf pvs, `The telescope problems...' .</s>
</NOTE>
<BYLINE>

<s docid="AP900428-0050" num="8" wdcount="5"> LaserPhoto HTN1 ^By LAURA TOLLEY</s>
</BYLINE>
<BYLINE>

<s docid="AP900428-0050" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900428-0050" num="10" wdcount="4"> SPACE CENTER, Houston (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900428-0050" num="11" wdcount="34"> The Hubble Space Telescope was awakened from its self-induced sleep today but it was still without the use of its high-speed antennas, and its science instruments were on hold, unable to begin any observations.</s>

<s docid="AP900428-0050" num="12" wdcount="19"> ``We are out of the `safe-mode' right now,'' said Steve Terry, a supervisor of the engineers controlling the telescope.</s>

<s docid="AP900428-0050" num="13" wdcount="22"> He said the telescope was running on a ``normal control-all mode,'' where its own computers and sensors guide where it is pointing.</s>

<s docid="AP900428-0050" num="14" wdcount="26"> Discovery's astronauts, meanwhile, packed their gear for a return to Earth Sunday, made some last-minute observations of Earth and talked with ground-based reporters about their flight.</s>

<s docid="AP900428-0050" num="15" wdcount="35"> Pilot Charles Bolden said he was especially upbeat about the widespread public awareness of the telescope, which is expected eventually to look back 14 billion light years _ nearly to the birth of the universe.</s>

<s docid="AP900428-0050" num="16" wdcount="19"> ``It's hard to go somewhere and find someone who has never heard of the Hubble Space Telescope,'' said Bolden.</s>

<s docid="AP900428-0050" num="17" wdcount="7"> ``It makes little kids' eyes light up.</s>

<s docid="AP900428-0050" num="18" wdcount="15"> It makes little kids want to learn how to add and subtract and study science''.</s>

<s docid="AP900428-0050" num="19" wdcount="33"> The telescope's big eye has remained open, but Hubble had been in a ``safe mode'' with all motion stopped because of earlier problems in linking the high-speed dish antennas with a relay satellite.</s>

<s docid="AP900428-0050" num="20" wdcount="13"> The antennas are the primary links for relaying scientific data to the ground.</s>

<s docid="AP900428-0050" num="21" wdcount="39"> Terry said that even in the safe mode, one of the tape recorders in the telescope reads telemetry signals from all its systems and that these would be played to Earth and analyzed when the antennas are working properly.</s>

<s docid="AP900428-0050" num="22" wdcount="12"> ``We expect to use that data to investigate what happened,'' he said.</s>

<s docid="AP900428-0050" num="23" wdcount="33"> Engineers are able to send commands to the telescope via its secondary antennas but the communications system is not useful for scientific data, which must be transmitted at a high rate of speed.</s>

<s docid="AP900428-0050" num="24" wdcount="16"> ``We're putting the scientific instruments in a hold mode, in effect a standby mode,'' he said.</s>

<s docid="AP900428-0050" num="25" wdcount="42"> Shortly after 6 a.m. EDT, controllers at the Goddard Space Flight Center in Greenbelt, Md., completed a series of commands that took the telescope out of its safe mode and then began to run a 12-hour computer program to monitor Hubble's health.</s>

<s docid="AP900428-0050" num="26" wdcount="32"> It will take another day before the $1.5 billion telescope is operating the way it was supposed to at this point in the startup process, said Hubble deputy project manager Jean Olivier.</s>

<s docid="AP900428-0050" num="27" wdcount="18"> ``We're backing up to a very deliberate and slow and careful approach to these problems,'' Olivier said Friday.</s>

<s docid="AP900428-0050" num="28" wdcount="9"> ``This is not the time to do anything dumb''.</s>

<s docid="AP900428-0050" num="29" wdcount="26"> The telescope problems have put the flight center several days behind, but the five astronauts who deployed it earlier this week were sticking to their schedule.</s>

<s docid="AP900428-0050" num="30" wdcount="25"> Landing is scheduled for 9:48 a.m. EDT Sunday at Edwards Air Force Base, Calif., but flight controllers were keeping a close watch on the weather.</s>

<s docid="AP900428-0050" num="31" wdcount="14"> Winds were predicted to be about 20 mph with gusts up to 29 mph.</s>

<s docid="AP900428-0050" num="32" wdcount="11"> Mission rules dictate that headwinds cannot exceed 29 mph at touchdown.</s>

<s docid="AP900428-0050" num="33" wdcount="17"> The shuttle carries enough supplies to stay in orbit three days beyond Sunday if necessary, NASA said.</s>

<s docid="AP900428-0050" num="34" wdcount="17"> Mission Control awakened the crew members at about 1:30 a.m. EDT today by playing the song, ``Cosmos''.</s>

<s docid="AP900428-0050" num="35" wdcount="14"> ``Thanks for the wake-up music, it's pretty appropriate for today,'' said Commander Loren Shriver.</s>

<s docid="AP900428-0050" num="36" wdcount="22"> ``The song was selected in honor of Hubble Space Telescope, which is now open for business,'' said Mission Control commentator James Hartsfield.</s>

<s docid="AP900428-0050" num="37" wdcount="17"> The astronauts were to finish up their experiments and photography today and pack for the trip home.</s>

<s docid="AP900428-0050" num="38" wdcount="17"> They also planned to hold a news conference from space with reporters at the Johnson Space Center.</s>

<s docid="AP900428-0050" num="39" wdcount="28"> Shriver and pilot Charles Bolden were to run through a series of tests to make certain the shuttle's computers and control jets were ready for return to Earth.</s>

<s docid="AP900428-0050" num="40" wdcount="23"> The crew deployed Hubble on Wednesday but they had stayed close to the telescope in case there was trouble opening the aperture door.</s>

<s docid="AP900428-0050" num="41" wdcount="25"> Mission specialists Bruce McCandless and Kathryn Sullivan were prepared to perform a space walk today to crank it open in orbit 380 miles above Earth.</s>

<s docid="AP900428-0050" num="42" wdcount="24"> But that proved unnecessary when the door was opened Friday morning, exposing the telescope's finely polished 94.5-inch eye to starlight for the first time.</s>

<s docid="AP900428-0050" num="43" wdcount="20"> Two of Hubble's four position-stabilizing gyroscopes stopped working when the door opened, but engineers later got them back on line.</s>

<s docid="AP900428-0050" num="44" wdcount="27"> The gyroscopes were knocked out by the motion and that, too, kept the telescope in the safe mode, said Dave Drachlis, director of orbital verifications at Goddard.</s>

<s docid="AP900428-0050" num="45" wdcount="21"> A colleague, Steve Terry, said Hubble's systems were set at conservative limits for the first operations and that caused many malfunctions.</s>

<s docid="AP900428-0050" num="46" wdcount="9"> There also were two communications outages totaling several hours.</s>

<s docid="AP900428-0050" num="47" wdcount="31"> Hubble is designed with safe modes so it can be ``the master of its own destiny'' in case contact with an orbiting communications system is lost for extended periods, Terry said.</s>

<s docid="AP900428-0050" num="48" wdcount="23"> NASA had planned to release its first test image from the telescope on Tuesday, showing an open star cluster in the constellation Carina.</s>

<s docid="AP900428-0050" num="49" wdcount="12"> But Terry said that would be delayed because of the antenna problems.</s>

<s docid="AP900428-0050" num="50" wdcount="9"> Scientific data will follow in a month or two.</s>

<s docid="AP900428-0050" num="51" wdcount="32"> The telescope, named for the late astronomer Edwin P. Hubble, will enable astronomers over its 15-year working lifetime to look back 14 billion years and possibly determine the age of the universe.</s>

<s docid="AP900428-0050" num="52" wdcount="17"> The universe is believed to have been created about 15 billion years ago in a cosmic explosion.</s>

<s docid="AP900428-0050" num="53" wdcount="10"> Hubble provided the basis for the big-bang theory of creation.</s>

<s docid="AP900428-0050" num="54" wdcount="26"> He discovered during the 1920s that the universe is expanding and that the farther the galaxy is from Earth, the faster it is moving away .</s>
</TEXT>
</DOC>
