<DOC>
<DOCNO>

<s docid="AP900422-0032" num="1" wdcount="1"> AP900422-0032</s>
</DOCNO>
<FILEID>

<s docid="AP900422-0032" num="2" wdcount="2"> AP-NR-04-22-90 1415EDT</s>
</FILEID>
<FIRST>

<s docid="AP900422-0032" num="3" wdcount="5"> r a AM-SpaceShuttle 04-22 0560</s>
</FIRST>
<SECOND>

<s docid="AP900422-0032" num="4" wdcount="2"> AM-Space Shuttle,0577</s>
</SECOND>
<HEAD>

<s docid="AP900422-0032" num="5" wdcount="6"> Discovery's Astronauts Back for Second Try</s>
</HEAD>
<BYLINE>

<s docid="AP900422-0032" num="6" wdcount="3"> By MARCIA DUNN</s>
</BYLINE>
<BYLINE>

<s docid="AP900422-0032" num="7" wdcount="3"> AP Aerospace Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900422-0032" num="8" wdcount="4"> CAPE CANAVERAL, Fla. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900422-0032" num="9" wdcount="26"> Discovery's five astronauts returned Sunday for a second attempt to launch the shuttle with NASA's most valuable and celebrated payload, the $1.5 billion Hubble Space Telescope.</s>

<s docid="AP900422-0032" num="10" wdcount="11"> Discovery is scheduled to lift off at 8:31 a.m. EDT Tuesday.</s>

<s docid="AP900422-0032" num="11" wdcount="22"> ``We feel very confident that things are going to go well this time,'' said Discovery's commander, Air Force Col. Loren J. Shriver.</s>

<s docid="AP900422-0032" num="12" wdcount="19"> ``We're going to come out OK on Tuesday morning and, if not, we'll just keep trying until we do.</s>

<s docid="AP900422-0032" num="13" wdcount="11"> That's kind of the name of the game here,'' Shriver said.</s>

<s docid="AP900422-0032" num="14" wdcount="22"> NASA test director Mike Leinbach said Sunday that the countdown was proceeding smoothly and the shuttle appeared to be in perfect condition.</s>

<s docid="AP900422-0032" num="15" wdcount="7"> The countdown got under way Saturday afternoon.</s>

<s docid="AP900422-0032" num="16" wdcount="18"> A faulty power unit forced the first launch attempt to be scrubbed four minutes before liftoff April 10.</s>

<s docid="AP900422-0032" num="17" wdcount="14"> The unit was replaced with a new one, which tests showed to be fine.</s>

<s docid="AP900422-0032" num="18" wdcount="12"> ``Hopefully, we'll get the shuttle off the pad this time,'' Leinbach said.</s>

<s docid="AP900422-0032" num="19" wdcount="28"> A 70 percent chance of favorable weather was expected at launch time, with low clouds being the main concern, said the Air Force's Ed Priselac, shuttle weather officer.</s>

<s docid="AP900422-0032" num="20" wdcount="17"> A weak cold front from the north was expected to pass through the area by Monday night.</s>

<s docid="AP900422-0032" num="21" wdcount="11"> The outlook is considerably better for Wednesday and Thursday, Priselac said.</s>

<s docid="AP900422-0032" num="22" wdcount="27"> As Discovery's astronauts arrived from Johnson Space Center in Houston early Sunday afternoon, the shuttle Columbia was being transported to a launch pad 1.6 miles from Discovery.</s>

<s docid="AP900422-0032" num="23" wdcount="18"> It is only the second time both shuttle launch pads at Kennedy Space Center have been occupied simultaneously.</s>

<s docid="AP900422-0032" num="24" wdcount="15"> The first time was in January 1986; 16 days after Columbia lifted off, Challenger exploded.</s>

<s docid="AP900422-0032" num="25" wdcount="22"> Columbia commander Vance Brand said he does not believe the National Aeronautics and Space Administration is moving too fast with his shuttle.</s>

<s docid="AP900422-0032" num="26" wdcount="26"> NASA expects to launch Columbia with an astronomical observatory called Astro no earlier than May 16, one week later than planned because of Discovery's two-week delay.</s>

<s docid="AP900422-0032" num="27" wdcount="16"> ``In some cases, it could be a problem'' having shuttles on both launch pads, Brand said.</s>

<s docid="AP900422-0032" num="28" wdcount="7"> ``In this particular case, everything's fitting together''.</s>

<s docid="AP900422-0032" num="29" wdcount="10"> NASA has until Saturday to get Discovery off the ground.</s>

<s docid="AP900422-0032" num="30" wdcount="17"> After that, all launch attempts must be halted for eight days so Hubble's batteries can be recharged.</s>

<s docid="AP900422-0032" num="31" wdcount="27"> The six nickel-hydrogen batteries will power Hubble from the time it is disconnected from Discovery's electrical system until its two energy-collecting solar panels take over in space.</s>

<s docid="AP900422-0032" num="32" wdcount="21"> Discovery's payload bay was sealed late Saturday night, drastically reducing the risk of contamination to the telescope's finely polished 94.5-inch mirror.</s>

<s docid="AP900422-0032" num="33" wdcount="31"> Discovery will aim for an altitude of 380 miles, the highest a shuttle has ever gone, so the telescope can be placed in its proper orbit far above Earth's distorting atmosphere.</s>

<s docid="AP900422-0032" num="34" wdcount="26"> During Hubble's 15-year journey through space, astronomers expect to look back to nearly the beginning of time and solve some of the universe's most perplexing mysteries.</s>

<s docid="AP900422-0032" num="35" wdcount="16"> Astro will measure ultraviolet radiation undetected by Hubble and thus provide additional targets for the telescope.</s>

<s docid="AP900422-0032" num="36" wdcount="25"> The $100 million observatory also will focus during Columbia's nine-day mission on Comet Austin, believed to be on its first trip through the solar system.</s>

<s docid="AP900422-0032" num="37" wdcount="18"> Both Hubble and Astro were scheduled for launch in 1986, but were delayed by the Challenger accident .</s>
</TEXT>
</DOC>
