<DOC>
<DOCNO>

<s docid="AP900428-0022" num="1" wdcount="1"> AP900428-0022</s>
</DOCNO>
<FILEID>

<s docid="AP900428-0022" num="2" wdcount="2"> AP-NR-04-28-90 0307EDT</s>
</FILEID>
<FIRST>

<s docid="AP900428-0022" num="3" wdcount="5"> r a PM-Shuttle-Eyepiece 04-28 0396</s>
</FIRST>
<SECOND>

<s docid="AP900428-0022" num="4" wdcount="1"> PM-Shuttle-Eyepiece,0408</s>
</SECOND>
<HEAD>

<s docid="AP900428-0022" num="5" wdcount="11"> Telescope Eyepiece Used by Edwin Hubble is Riding on the Shuttle</s>
</HEAD>
<HEAD>

<s docid="AP900428-0022" num="6" wdcount="4"> With PM-Space Shuttle, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP900428-0022" num="7" wdcount="3"> By LEE SIEGEL</s>
</BYLINE>
<BYLINE>

<s docid="AP900428-0022" num="8" wdcount="3"> AP Science Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900428-0022" num="9" wdcount="3"> PASADENA, Calif. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900428-0022" num="10" wdcount="33"> The shuttle that put the Hubble Space Telescope into orbit also carries an instrument used in the 1920s by astronomer Edwin Hubble: the eyepiece from what once was the world's most powerful telescope.</s>

<s docid="AP900428-0022" num="11" wdcount="37"> ``It's a great pleasure to have something of such historical significance and something that so directly symbolizes Edwin Hubble's fundamental contributions to astronomy,'' astronaut Kathy Sullivan said Friday as she circled the Earth in space shuttle Discovery.</s>

<s docid="AP900428-0022" num="12" wdcount="16"> The eyepiece from the Mount Wilson Observatory's 100-inch Hooker Telescope was carried into orbit by Sullivan.</s>

<s docid="AP900428-0022" num="13" wdcount="17"> After she brings the eyepiece back to Earth, it will be placed on display at the observatory.</s>

<s docid="AP900428-0022" num="14" wdcount="24"> ``It's basically a symbolic gesture from the past of astronomy to the future of astronomy,'' said Lyn McAfee, spokeswoman for the Mount Wilson Institute.</s>

<s docid="AP900428-0022" num="15" wdcount="15"> The Pasadena-based group runs the observatory, located in the San Gabriel Mountains outside Los Angeles.</s>

<s docid="AP900428-0022" num="16" wdcount="26"> ``The discoveries made by Hubble on the 100-inch telescope at Mount Wilson gave us a giant leap forward in our understanding of the universe,'' McAfee said.</s>

<s docid="AP900428-0022" num="17" wdcount="11"> ``We believe the Hubble Space Telescope will do the same thing''.</s>

<s docid="AP900428-0022" num="18" wdcount="33"> The Hooker Telescope was the world's most powerful telescope from its construction in 1918 until 1948, when the 200-inch Hale Telescope was placed in operation at Mount Palomar Observatory northeast of San Diego.</s>

<s docid="AP900428-0022" num="19" wdcount="25"> Using the Hooker Telescope, Hubble was the first to determine the distance to a galaxy outside the Milky Way, the institute said in a statement.</s>

<s docid="AP900428-0022" num="20" wdcount="24"> ``This crucial discovery provided the first definite proof that other galaxies existed far beyond the confines of our own local galaxy,'' the institute said.</s>

<s docid="AP900428-0022" num="21" wdcount="34"> During the 1920s and 1930s, Hubble and an assistant used the Hooker telescope to take thousands of photographs of faint galaxies, showing that most of them were moving away from each other very quickly.</s>

<s docid="AP900428-0022" num="22" wdcount="21"> ``This provided observational evidence for the concept, suggested by Einstein's Theory of Relativity, that the universe is expanding,'' the institute said.</s>

<s docid="AP900428-0022" num="23" wdcount="23"> Hubble's work helped convince scientists the universe was created in a giant explosion, called the ``big bang,'' an estimated 15 billion years ago.</s>

<s docid="AP900428-0022" num="24" wdcount="20"> The Hooker Telescope was mothballed in 1985 by the Carnegie Institution, former operator of the observatory, in a money-saving move.</s>

<s docid="AP900428-0022" num="25" wdcount="10"> The institute hopes to obtain funds to reopen it .</s>
</TEXT>
</DOC>
