<DOC>
<DOCNO>

<s docid="LA042590-0152" num="1" wdcount="1"> LA042590-0152</s>
</DOCNO>
<DOCID>

<s docid="LA042590-0152" num="2" wdcount="1"> 209563</s>
</DOCID>
<DATE>
<P>

<s docid="LA042590-0152" num="3" wdcount="6"> April 25, 1990, Wednesday, P.M. Final</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA042590-0152" num="4" wdcount="9"> Part P; Page 1; Column 6; Late Final Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA042590-0152" num="5" wdcount="2"> 504 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA042590-0152" num="6" wdcount="2"> TELESCOPE LAUNCHED;</s>
</P>
<P>

<s docid="LA042590-0152" num="7" wdcount="6"> FREED SOLAR PANEL AVERTS SPACE WALK</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA042590-0152" num="8" wdcount="4"> From Times Wire Services</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA042590-0152" num="9" wdcount="4"> CAPE CANAVERAL, Fla .</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA042590-0152" num="10" wdcount="31"> The Discovery astronauts triumphantly launched the $1.5-billion Hubble Space Telescope one orbit late today after last-ditch commands from Earth freed a stuck solar panel, narrowly averting a daring emergency spacewalk .</s>
</P>
<P>

<s docid="LA042590-0152" num="11" wdcount="28"> The telescope began orbiting Earth every 97.3 minutes at an altitude of 380 miles -- high above the atmosphere, which has limited the view of ground-based telescopes .</s>
</P>
<P>

<s docid="LA042590-0152" num="12" wdcount="14"> "Discovery, go for Hubble release," Mission Control told the crew at 12:37 p.m. PDT.</s>

<s docid="LA042590-0152" num="13" wdcount="31"> The event occurred a minute later as the shuttle slowly and carefully backed away as the telescope, glinting in the sunlight, drifted off on its 15-year search for new worlds .</s>
</P>
<P>

<s docid="LA042590-0152" num="14" wdcount="27"> The final hours before its release were a nightmare for ground controllers as they commanded the unfurling of two solar panels that power the telescope's instruments .</s>
</P>
<P>

<s docid="LA042590-0152" num="15" wdcount="13"> The starboard panel balked twice as it was being pulled from its reel.</s>

<s docid="LA042590-0152" num="16" wdcount="16"> Mission Control ordered spacewalking astronauts to be ready to go out of the cabin to help.</s>

<s docid="LA042590-0152" num="17" wdcount="11"> But there was a third try, and it was successful .</s>
</P>
<P>

<s docid="LA042590-0152" num="18" wdcount="23"> "We have confirmation that the solar array wing on the starboard side has been deployed," the telescope control center in Maryland said .</s>
</P>
<P>

<s docid="LA042590-0152" num="19" wdcount="14"> "So we have good news," said Dave Drachlis of the Hubble control center .</s>
</P>
<P>

<s docid="LA042590-0152" num="20" wdcount="27"> The deployment of the two 39-foot panels allowed sun power to flow into the telescope's batteries, relieving worries that they would use up their eight-hour charge .</s>
</P>
<P>

<s docid="LA042590-0152" num="21" wdcount="38"> Before astronaut Steve Hawley was able to lift the 12 1/2-ton telescope from the cargo bay with the shuttle's mechanical arm, its instruments had to be disconnected from the shuttle's power and shifted over to the batteries .</s>
</P>
<P>

<s docid="LA042590-0152" num="22" wdcount="38"> Astronauts Kathryn Sullivan and Bruce McCandless had put on spacesuits and entered an air lock in order to be ready to walk outside and pull out the array in case mechanical deployment of the solar panels failed .</s>
</P>
<P>

<s docid="LA042590-0152" num="23" wdcount="21"> The first solar array unreeled from its mast at midday as the shuttle passed 380 miles above South America's eastern coast.</s>

<s docid="LA042590-0152" num="24" wdcount="17"> It started providing power to the telescope's batteries, which otherwise had only eight hours of charge .</s>
</P>
<P>

<s docid="LA042590-0152" num="25" wdcount="9"> Deployment of the starboard panel, however, was more troublesome.</s>

<s docid="LA042590-0152" num="26" wdcount="21"> It refused to budge when latches were first released, then moved about a fifth of its 39-foot length and stopped again.</s>

<s docid="LA042590-0152" num="27" wdcount="11"> A third attempt rolled the panel out all the way .</s>
</P>
<P>

<s docid="LA042590-0152" num="28" wdcount="10"> "Houston, we see motion," Commander Loren J. Shriver reported .</s>
</P>
<P>

<s docid="LA042590-0152" num="29" wdcount="35"> Hawley began the long process of releasing Hubble shortly after 4 a.m. PDT when he grasped the Hubble with Discovery's 50-foot-long mechanical arm and carefully hoisted the 12 1/2-ton telescope high above the shuttle .</s>
</P>
<P>

<s docid="LA042590-0152" num="30" wdcount="15"> Discovery was 380 miles above Earth, 70 miles higher than any shuttle has ever flown.</s>

<s docid="LA042590-0152" num="31" wdcount="17"> The orbit was dictated by the need to put the telescope above the Earth's distorting atmosphere .</s>
</P>
<P>

<s docid="LA042590-0152" num="32" wdcount="9"> Discovery's five astronauts were awed by the view .</s>
</P>
<P>

<s docid="LA042590-0152" num="33" wdcount="34"> "I'd like to pass on the quote of the day from the on-board astronomer -- something to the effect that the big marble (Earth) sure looks far away today," Shriver said of Hawley .</s>
</P>
</TEXT>
<TYPE>
<P>

<s docid="LA042590-0152" num="34" wdcount="1"> Wire</s>
</P>
</TYPE>
</DOC>
