<DOC>
<DOCNO>

<s docid="LA042590-0135" num="1" wdcount="1"> LA042590-0135</s>
</DOCNO>
<DOCID>

<s docid="LA042590-0135" num="2" wdcount="1"> 209452</s>
</DOCID>
<DATE>
<P>

<s docid="LA042590-0135" num="3" wdcount="6"> April 25, 1990, Wednesday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA042590-0135" num="4" wdcount="8"> Part A; Page 1; Column 5; National Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA042590-0135" num="5" wdcount="2"> 911 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA042590-0135" num="6" wdcount="7"> POWERFUL TELESCOPE SOARS INTO SPACE ABOARD SHUTTLE</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA042590-0135" num="7" wdcount="6"> By LEE DYE, TIMES SCIENCE WRITER</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA042590-0135" num="8" wdcount="5"> KENNEDY SPACE CENTER, Fla .</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA042590-0135" num="9" wdcount="29"> The space shuttle Discovery brought a thundering end to years of frustration when it blasted off Tuesday to extend human vision to the very edge of the universe .</s>
</P>
<P>

<s docid="LA042590-0135" num="10" wdcount="46"> The Discovery roared to a record high orbit of 381 miles, where its crew today will ever-so-carefully deploy the Hubble Space Telescope, billed as the finest optical instrument ever created, a $1.5-billion scope that is half a billion times more powerful than the human eye .</s>
</P>
<P>

<s docid="LA042590-0135" num="11" wdcount="30"> Seven years behind schedule, the telescope will be deployed by astronaut Steven Hawley, an astronomer, on a day that many scientists were beginning to doubt they would ever see .</s>
</P>
<P>

<s docid="LA042590-0135" num="12" wdcount="25"> "It's been long and frustrating," conceded Edward Weiler, program scientist for the National Aeronautics and Space Administration, who was visibly shaken by the launch .</s>
</P>
<P>

<s docid="LA042590-0135" num="13" wdcount="10"> "Every astronomer," he said softly, "should take today off" .</s>
</P>
<P>

<s docid="LA042590-0135" num="14" wdcount="21"> The launch marked the beginning of an era -- some say a revolution -- in the exploration of the universe .</s>
</P>
<P>

<s docid="LA042590-0135" num="15" wdcount="23"> "After 12 years," astronomer Eric Chaisson of the Space Telescope Science Institute said with a sigh, "it has finally left the Earth" .</s>
</P>
<P>

<s docid="LA042590-0135" num="16" wdcount="26"> High above the haze of the Earth's atmosphere, the Hubble is expected to produce images 10 times sharper than even the largest telescopes on Earth today.</s>

<s docid="LA042590-0135" num="17" wdcount="18"> The telescope will not get down to serious science until it completes a seven-month checkout and engineering period.</s>

<s docid="LA042590-0135" num="18" wdcount="17"> Then scientists will begin studying some of the dimmest and most distant objects in the universe .</s>
</P>
<P>

<s docid="LA042590-0135" num="19" wdcount="19"> After the deployment, engineers at the Goddard Space Flight Center will begin the tedious process of activating the telescope.</s>

<s docid="LA042590-0135" num="20" wdcount="31"> Although scientific images that should tell much about the origin and evolution of the universe will not be released for several months, there will be a few teasers early on .</s>
</P>
<P>

<s docid="LA042590-0135" num="21" wdcount="39"> In about seven days the Hubble should snap its first picture -- what astronomers call "first light" for the telescope -- but it will be primarily an engineering exercise and the image is not expected to amount to much.</s>

<s docid="LA042590-0135" num="22" wdcount="30"> The image, of a cluster of stars in the southern sky, will be taken during the beginning of the focusing phase, so it may not even be in focus .</s>
</P>
<P>

<s docid="LA042590-0135" num="23" wdcount="9"> But it will still represent a historic moment .</s>
</P>
<P>

<s docid="LA042590-0135" num="24" wdcount="24"> "The stars may be so out of focus they look like doughnuts," said Caltech's James Westphal, principal scientist for the telescope's wide field camera.</s>

<s docid="LA042590-0135" num="25" wdcount="11"> "But however it comes out, it's going to be great" .</s>
</P>
<P>

<s docid="LA042590-0135" num="26" wdcount="23"> It will mark the moment when humans freed themselves from the fuzzy view from Earth and looked to the heavens with absolute clarity.</s>

<s docid="LA042590-0135" num="27" wdcount="21"> There will be other space telescopes in the years ahead, but there will never be another moment quite like this .</s>
</P>
<P>

<s docid="LA042590-0135" num="28" wdcount="40"> "Every bit of 12 years was worth it," Weiler said moments after Discovery lifted off on a sunny day, pierced a fleecy white cloud and emerged on the other side like a spacecraft on a journey to the future .</s>
</P>
<P>

<s docid="LA042590-0135" num="29" wdcount="16"> Sadly, some who have worked so hard for so long were forced to miss the launch.</s>

<s docid="LA042590-0135" num="30" wdcount="35"> They were here two weeks ago, but when the launch was delayed because of a hydraulic problem they returned to their homes, and many agencies had not budgeted for two trips to Cape Canaveral .</s>
</P>
<P>

<s docid="LA042590-0135" num="31" wdcount="20"> Weiler estimated that only about one-third of the people who were here April 10 made it back for Tuesday's launch.</s>

<s docid="LA042590-0135" num="32" wdcount="22"> Among the missing were most of the families who had accompanied scientists in hopes of seeing this little bit of history .</s>
</P>
<P>

<s docid="LA042590-0135" num="33" wdcount="26"> There was only one small snag in the otherwise perfect launch when a valve failed to close automatically, halting the countdown at 31 seconds before launch.</s>

<s docid="LA042590-0135" num="34" wdcount="23"> The valve was ordered by computer to correct its position, and it did so, clearing the way for the countdown to resume .</s>
</P>
<P>

<s docid="LA042590-0135" num="35" wdcount="7"> That delayed the launch about four minutes.</s>

<s docid="LA042590-0135" num="36" wdcount="23"> But at 5:34 a.m. PDT, with Air Force Col. Loren J. Shriver, 45, sitting in the commander's seat, the shuttle lifted off .</s>
</P>
<P>

<s docid="LA042590-0135" num="37" wdcount="11"> All five members of the crew are veterans of previous flights.</s>

<s docid="LA042590-0135" num="38" wdcount="24"> This is the second flight for Charles F. Bolden Jr., 43, the pilot, and mission specialists Bruce McCandless, 52, and Kathryn D. Sullivan, 38.</s>

<s docid="LA042590-0135" num="39" wdcount="9"> It is the third flight for Hawley, 38 .</s>
</P>
<P>

<s docid="LA042590-0135" num="40" wdcount="23"> Sullivan and McCandless will be partially suited for a spacewalk today just in case anything goes wrong during the deployment of the telescope.</s>

<s docid="LA042590-0135" num="41" wdcount="23"> The most anxious moments will come as Hawley gently lifts the 25,000-pound instrument out of its tight quarters in the cargo bay .</s>
</P>
<P>

<s docid="LA042590-0135" num="42" wdcount="19"> He will do that with the shuttle's robotic arm, which he tested in the first hours of the flight.</s>

<s docid="LA042590-0135" num="43" wdcount="31"> The arm, however, tends to drift slightly, so he will have his hands full keeping the telescope from banging into the sides of the payload bay as he lifts it .</s>
</P>
<P>

<s docid="LA042590-0135" num="44" wdcount="14"> Engineers will not breathe freely until the telescope's two giant solar arrays are unfurled.</s>

<s docid="LA042590-0135" num="45" wdcount="47"> The solar arrays keep the telescope's high-tech batteries charged, and if they are not fully deployed within six hours after the telescope is lifted out of the cargo bay, the batteries will have discharged to the point that some instruments in the telescope could be damaged .</s>
</P>
<P>

<s docid="LA042590-0135" num="46" wdcount="19"> So Sullivan and McCandless will be ready to step outside and manually unfurl the solar arrays if necessary .</s>
</P>
<P>

<s docid="LA042590-0135" num="47" wdcount="27"> After the telescope is released and functioning on its own, the Discovery will back off about 40 miles and shepherd the scope around Earth for two days.</s>

<s docid="LA042590-0135" num="48" wdcount="27"> If anything goes wrong during that period, the shuttle can rendezvous with the telescope and McCandless and Sullivan can go out and work on the problem .</s>
</P>
<P>

<s docid="LA042590-0135" num="49" wdcount="19"> If there are no problems, Discovery will land at 6:49 a.m. PDT Sunday at Edwards Air Force Base .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA042590-0135" num="50" wdcount="32"> Photo, Heading for spacecraft on morning of launch is shuttle Discovery crew, from left: Bruce McCandless, pilot Charles F. Bolden Jr., Kathryn D. Sullivan, Steven Hawley and flight commander Loren J. Shriver.</s>

<s docid="LA042590-0135" num="51" wdcount="14"> Agence France-Presse; Photo, (Southland Edition) Discovery blasts off with the Hubble Space Telescope aboard.</s>

<s docid="LA042590-0135" num="52" wdcount="2"> Agence France-Presse</s>
</P>
</GRAPHIC>
<SUBJECT>
<P>

<s docid="LA042590-0135" num="53" wdcount="17"> HUBBLE SPACE TELESCOPE; SPACE EXPLORATION; SPACE PROGRAMS -- UNITED STATES; SPACE SHUTTLE; DISCOVERY (SPACE SHUTTLE); TELESCOPES; ASTRONOMY</s>
</P>
</SUBJECT>
</DOC>
