<DOC>
<DOCNO>

<s docid="LA042290-0160" num="1" wdcount="1"> LA042290-0160</s>
</DOCNO>
<DOCID>

<s docid="LA042290-0160" num="2" wdcount="1"> 208054</s>
</DOCID>
<DATE>
<P>

<s docid="LA042290-0160" num="3" wdcount="6"> April 22, 1990, Sunday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA042290-0160" num="4" wdcount="8"> Part A; Page 4; Column 1; National Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA042290-0160" num="5" wdcount="2"> 253 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA042290-0160" num="6" wdcount="7"> SHUTTLE COUNTDOWN RESUMES FOR HUBBLE TELESCOPE MISSION</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA042290-0160" num="7" wdcount="5"> By from United Press International</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA042290-0160" num="8" wdcount="5"> KENNEDY SPACE CENTER, Fla .</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA042290-0160" num="9" wdcount="22"> Countdown clocks resumed ticking Saturday for the shuttle Discovery's delayed launch Tuesday to boost the $1.5-billion Hubble Space Telescope into orbit .</s>
</P>
<P>

<s docid="LA042290-0160" num="10" wdcount="18"> Engineers also readied the shuttle Columbia for rollout to its launch pad today for a May flight .</s>
</P>
<P>

<s docid="LA042290-0160" num="11" wdcount="10"> Discovery's carefully scripted countdown began on time at 3 p.m.</s>

<s docid="LA042290-0160" num="12" wdcount="34"> The ship's five-member crew is set to blast off at 5:31 a.m. PDT Tuesday, 14 days after the flight was grounded just four minutes before takeoff by a faulty hydraulic power steering unit .</s>
</P>
<P>

<s docid="LA042290-0160" num="13" wdcount="9"> "We're off and running," NASA spokesman George Diller said.</s>

<s docid="LA042290-0160" num="14" wdcount="8"> "We're still 80% go for launch weather-wise" .</s>
</P>
<P>

<s docid="LA042290-0160" num="15" wdcount="19"> With Discovery's launch processing on track, engineers worked to ready Columbia for its May 16 Spacelab astronomy mission .</s>
</P>
<P>

<s docid="LA042290-0160" num="16" wdcount="32"> The National Aeronautics and Space Administration has not had two shuttles on the launch pad since Columbia took off Jan. 12, 1986, with Challenger poised on a pad 1.7 miles away .</s>
</P>
<P>

<s docid="LA042290-0160" num="17" wdcount="15"> Columbia's 3.5-mile trip to the firing stand was set to begin at 8 a.m. today.</s>

<s docid="LA042290-0160" num="18" wdcount="25"> Five hours later, Discovery's five-member crew was scheduled to fly in from the Johnson Space Center in Houston to make final preparations for launch .</s>
</P>
<P>

<s docid="LA042290-0160" num="19" wdcount="29"> Commander Loren J. Shriver, 45; co-pilot Charles F. Bolden, 43; Steven A. Hawley, 38; Bruce McCandless, 52, and Kathryn D. Sullivan, 38, plan to launch the telescope Wednesday .</s>
</P>
<P>

<s docid="LA042290-0160" num="20" wdcount="26"> Discovery's replacement auxiliary power unit was successfully test fired Wednesday and the battery charging for the telescope was completed Thursday, one day ahead of schedule .</s>
</P>
</TEXT>
<TYPE>
<P>

<s docid="LA042290-0160" num="21" wdcount="1"> Wire</s>
</P>
</TYPE>
<SUBJECT>
<P>

<s docid="LA042290-0160" num="22" wdcount="14"> DISCOVERY (SPACE SHUTTLE); SPACE SHUTTLE; SCHEDULES; HUBBLE SPACE TELESCOPE; SPACE PROGRAMS -- UNITED STATES</s>
</P>
</SUBJECT>
</DOC>
