<DOC>
<DOCNO>

<s docid="AP880817-0124" num="1" wdcount="1"> AP880817-0124</s>
</DOCNO>
<FILEID>

<s docid="AP880817-0124" num="2" wdcount="2"> AP-NR-08-17-88 1201EDT</s>
</FILEID>
<FIRST>

<s docid="AP880817-0124" num="3" wdcount="7"> u i PM-Poland 3rdLd-Writethru a0563 08-17 0782</s>
</FIRST>
<SECOND>

<s docid="AP880817-0124" num="4" wdcount="4"> PM-Poland, 3rd Ld-Writethru, a0563,0807</s>
</SECOND>
<HEAD>

<s docid="AP880817-0124" num="5" wdcount="9"> Port Workers, Coal Miners Join Strike To Legalize Solidarity</s>
</HEAD>
<NOTE>

<s docid="AP880817-0124" num="6" wdcount="11"> Eds: LEADS with four grafs to UPDATE with strike at port.</s>

<s docid="AP880817-0124" num="7" wdcount="6"> Pick up 3rd pvs, `Andrzej Andrzejczak...'</s>
</NOTE>
<BYLINE>

<s docid="AP880817-0124" num="8" wdcount="4"> By DEBORAH G. SEWARD</s>
</BYLINE>
<BYLINE>

<s docid="AP880817-0124" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880817-0124" num="10" wdcount="3"> JASTRZEBIE, Poland (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880817-0124" num="11" wdcount="22"> Port workers in Szczecin and southwestern coal miners today declared sympathy strikes with miners demanding the legalization of Solidarity, opposition activists said.</s>

<s docid="AP880817-0124" num="12" wdcount="38"> In support of an estimated 3,000 colleagues striking for a second day at the July Manifesto mine in Jastrzebie, workers at the nearby Morcinek mine refused today to take up their tools and launched their own occupation strike.</s>

<s docid="AP880817-0124" num="13" wdcount="30"> Port workers occupied the docks in Szezecin, about 250 miles northwest of Warsaw, and set up a 15-member strike committee, said Jan Kostecki, a leader of the independent union federation.</s>

<s docid="AP880817-0124" num="14" wdcount="11"> A local prosecutor immediately declared the strike illegal, Solidarity officials said.</s>

<s docid="AP880817-0124" num="15" wdcount="22"> Andrzej Andrzejczak, head of the Morcinek mine strike committee, said: ``We support all of the demands of the July Manifesto mine workers''.</s>

<s docid="AP880817-0124" num="16" wdcount="32"> The mine is about 12 miles south of July Manifesto, where strikers were demanding legalization of the outlawed independent labor federation, pay raises and reinstatement of workers fired for trade union activites.</s>

<s docid="AP880817-0124" num="17" wdcount="23"> Police ringing July Manifesto, one of Poland's largest coal mines, today turned away area residents who tried to bring food to the strikers.</s>

<s docid="AP880817-0124" num="18" wdcount="25"> Andrzejczak said the Morcinek miners broke off talks with management when they were refused access to loudspeakers and contact with the strikers at July Manifesto.</s>

<s docid="AP880817-0124" num="19" wdcount="19"> He said miners erected a large Polish flag atop the administration building and were blocking the complex's main entrance.</s>

<s docid="AP880817-0124" num="20" wdcount="10"> It was not immediately known how many workers were involved.</s>

<s docid="AP880817-0124" num="21" wdcount="23"> The second strike came as Solidarity strike committee members met with management and representatives of the Industry Ministry at the July Manifesto colliery.</s>

<s docid="AP880817-0124" num="22" wdcount="18"> Adam Kowalczyk, a regional Solidarity leader, said more workers were joining colleagues inside by leaping over police barricades.</s>

<s docid="AP880817-0124" num="23" wdcount="33"> The strike committee issued a communique today saying the workers would not end their stoppage until their demands are met and charged: ``The mine management is trying to end the strike by hunger''.</s>

<s docid="AP880817-0124" num="24" wdcount="12"> Police surrounded the mine after workers put down their tools on Tuesday.</s>

<s docid="AP880817-0124" num="25" wdcount="12"> Witnesses said about 600 officers were outside and about 3,000 strikers inside.</s>

<s docid="AP880817-0124" num="26" wdcount="21"> The strikes mark the eighth anniversary of the birth of the Solidarity, which Communist authorities crushed in a 1981 military crackdown.</s>

<s docid="AP880817-0124" num="27" wdcount="22"> Miners leaving July Manifesto this morning said wage demands were based on hardships caused by Poland's worsening economy, including 60 percent inflation.</s>

<s docid="AP880817-0124" num="28" wdcount="10"> ``The economy is in ruins,'' one told The Associated Press.</s>

<s docid="AP880817-0124" num="29" wdcount="11"> ``Miners cannot live on their salaries because of recent price hikes''.</s>

<s docid="AP880817-0124" num="30" wdcount="22"> Miners earn nearly twice the average national salary and receive extra benefits because of the vital role they play in the economy.</s>

<s docid="AP880817-0124" num="31" wdcount="16"> Poland is the world's fourth largest exporter of coal, and coal is the nation's leading export.</s>

<s docid="AP880817-0124" num="32" wdcount="23"> July Manifesto, a hotbed of labor activism during the strike wave that spawned Solidarity, is one of five coal mines in the region.</s>

<s docid="AP880817-0124" num="33" wdcount="33"> Solidarity adviser Jacek Kuron said there were no reports of violence and police made no attempt to move into the mine, which is 280 miles southwest of Warsaw and employs about 9,000 workers.</s>

<s docid="AP880817-0124" num="34" wdcount="15"> The state-run PAP news agency, in a dispatch late Tuesday, said the strike was illegal.</s>

<s docid="AP880817-0124" num="35" wdcount="16"> PAP said the miners were warned that ``they may be held responsible for their illegal actions''.</s>

<s docid="AP880817-0124" num="36" wdcount="10"> The July Manifesto mine is in Silesia, Poland's industrial heartland.</s>

<s docid="AP880817-0124" num="37" wdcount="29"> Eight years ago, a wave of mine strikes in Silesia ended with the signing at July Manifesto of the last of three agreements that established Solidarity across the nation.</s>

<s docid="AP880817-0124" num="38" wdcount="6"> The pact also won work-free weekends.</s>

<s docid="AP880817-0124" num="39" wdcount="17"> Solidarity leaders said the strike began Tuesday when overnight shift workers refused to take up their tools.</s>

<s docid="AP880817-0124" num="40" wdcount="12"> They were joined by workers arriving for the morning shift, Kuron said.</s>

<s docid="AP880817-0124" num="41" wdcount="19"> Kuron said mine management then locked out members of the afternoon shift to prevent them from joining the strike.</s>

<s docid="AP880817-0124" num="42" wdcount="21"> Solidarity spokesmen said workers at the nearby Borynia mine staged a brief sympathy rally but went back to work Tuesday afternoon.</s>

<s docid="AP880817-0124" num="43" wdcount="22"> Also Tuesday, security officials briefly detained 10 Solidarity activists at the Rudna copper mine near the city of Wroclaw in lower Silesia.</s>

<s docid="AP880817-0124" num="44" wdcount="19"> That mine has also been the scene of unrest in recent months, where workers have demanded improved safety conditions.</s>

<s docid="AP880817-0124" num="45" wdcount="34"> Five strikes in Poland from April 25 to May 10, and brief stoppages or strike threats in 25 more work places, constituted the worst labor unrest in the country since the 1981 martial-law crackdown.</s>

<s docid="AP880817-0124" num="46" wdcount="16"> One of the stoppages, at a steel mill near Krakow, was broken up by security forces.</s>

<s docid="AP880817-0124" num="47" wdcount="16"> The workers in those strikes also demanded the legalization of Solidarity, along with wage increases .</s>
</TEXT>
</DOC>
