<DOC>
<DOCNO>

<s docid="AP880816-0135" num="1" wdcount="1"> AP880816-0135</s>
</DOCNO>
<FILEID>

<s docid="AP880816-0135" num="2" wdcount="2"> AP-NR-08-16-88 1042EDT</s>
</FILEID>
<FIRST>

<s docid="AP880816-0135" num="3" wdcount="5"> r i PM-Poland-Mine 08-16 0285</s>
</FIRST>
<SECOND>

<s docid="AP880816-0135" num="4" wdcount="1"> PM-Poland-Mine,0298</s>
</SECOND>
<HEAD>

<s docid="AP880816-0135" num="5" wdcount="6"> Miners Strike On Anniversary Of Solidarity</s>
</HEAD>
<BYLINE>

<s docid="AP880816-0135" num="6" wdcount="4"> By GIRARD C. STEICHEN</s>
</BYLINE>
<BYLINE>

<s docid="AP880816-0135" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880816-0135" num="8" wdcount="3"> WARSAW, Poland (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880816-0135" num="9" wdcount="29"> More than 4,000 workers at a coal mine in the southern city of Jastrzebie went on strike today to demand legalization of Solidarity and higher wages, a spokeswoman said.</s>

<s docid="AP880816-0135" num="10" wdcount="23"> The strike in Jastrzebie, about 275 miles southwest of Warsaw, comes on the eighth anniversary of the founding of the outlawed trade federation.</s>

<s docid="AP880816-0135" num="11" wdcount="32"> Solidarity spokeswoman Katarzyna Ketrzynska said workers on the overnight shift at the Manifest Lipcowy mine stayed outside the mine shaft all night and were joined by workers arriving for the morning shift.</s>

<s docid="AP880816-0135" num="12" wdcount="24"> She said security officers blocked miners on the afternoon shift, which starts at 2 p.m., from entering the grounds to join the striking miners.</s>

<s docid="AP880816-0135" num="13" wdcount="9"> The strike began at noon today, according to Katrzynska.</s>

<s docid="AP880816-0135" num="14" wdcount="18"> She said the miners are demanding the legalization of Solidarity and reinstatement of workers fired for union activities.</s>

<s docid="AP880816-0135" num="15" wdcount="26"> The workers are also calling for higher wages and better working conditions, and are requesting two lawyers and two economists to assist them in the negotiations.</s>

<s docid="AP880816-0135" num="16" wdcount="15"> Manifest Lipcowy is the second mine in the industrial region of Silesia to experience unrest.</s>

<s docid="AP880816-0135" num="17" wdcount="29"> Workers at the Rudna copper mine near the city of Wroclaw staged a protest rally Monday to demand improved safety conditions and the return of Solidarity activists to work.</s>

<s docid="AP880816-0135" num="18" wdcount="9"> Three members of Solidarity were barred Saturday from working.</s>

<s docid="AP880816-0135" num="19" wdcount="20"> Solidarity was crushed in 1981, when the government imposed martial law, and was banned nearly a year later by parliament.</s>

<s docid="AP880816-0135" num="20" wdcount="32"> On Aug. 16, 1980, workers at factories around the northern port of Gdansk joined striking shipyard workers to form Solidarity, the first and only independent trade federation in the Soviet bloc .</s>
</TEXT>
</DOC>
