<DOC>
<DOCNO>

<s docid="AP890616-0230" num="1" wdcount="1"> AP890616-0230</s>
</DOCNO>
<FILEID>

<s docid="AP890616-0230" num="2" wdcount="2"> AP-NR-06-16-89 1418EST</s>
</FILEID>
<FIRST>

<s docid="AP890616-0230" num="3" wdcount="7"> u f PM-CoalStrike 3rdLd-Writethru f0134 06-16 0665</s>
</FIRST>
<SECOND>

<s docid="AP890616-0230" num="4" wdcount="5"> PM-Coal Strike, 3rd Ld-Writethru, f0134,0682</s>
</SECOND>
<HEAD>

<s docid="AP890616-0230" num="5" wdcount="6"> Sympathy Strikes Spread to Other States</s>
</HEAD>
<HEAD>

<s docid="AP890616-0230" num="6" wdcount="26"> Eds: SUBS 3rd graf, One United...', with 2 grafs to CORRECT that Pittston, not union members, dropped out of the Bituminous Coal Operators Association, add background.</s>

<s docid="AP890616-0230" num="7" wdcount="8"> Picks up 4th graf pvs, `UMW officials...' .</s>
</HEAD>
<BYLINE>

<s docid="AP890616-0230" num="8" wdcount="3"> By MARK PAXTON</s>
</BYLINE>
<BYLINE>

<s docid="AP890616-0230" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890616-0230" num="10" wdcount="3"> CHARLESTON, W.Va. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890616-0230" num="11" wdcount="36"> More than 10,000 coal miners in four states were off the job today to express sympathy for miners in Virginia and West Virginia who have waged a bitter strike since April against the Pittston Coal Group.</s>

<s docid="AP890616-0230" num="12" wdcount="18"> Miners in Pennsylvania and Kentucky today became the third and fourth states to report walkouts at coal companies.</s>

<s docid="AP890616-0230" num="13" wdcount="14"> The sympathy strikes began Monday in West Virginia and spread to Indiana late Thursday.</s>

<s docid="AP890616-0230" num="14" wdcount="38"> One United Mine Workers representative said today that the Indiana walkout was prompted by Thursday night's telecast of CBS' ``48 Hours,'' which focused on the Pittston strike, in which 1,600 miners have been off the job since April.</s>

<s docid="AP890616-0230" num="15" wdcount="30"> Pittston dropped out of the Bituminous Coal Operators Association to negotiate with the union independently, and the two sides have failed to reach an agreement despite 16 months of negotiations.</s>

<s docid="AP890616-0230" num="16" wdcount="14"> UMW officials gave conflicting indications of whether they are responsible for the wildcat strike.</s>

<s docid="AP890616-0230" num="17" wdcount="46"> Some said they are asking union members to return to work, but Tommy Buchanan, international executive board member in UMW District 20 in Birmingham, Ala., said today the final decision on whether 5,000 Alabama miners will join the strike will be with union President Richard Trumka.</s>

<s docid="AP890616-0230" num="18" wdcount="5"> ``It might be two days.</s>

<s docid="AP890616-0230" num="19" wdcount="5"> It might be a week.</s>

<s docid="AP890616-0230" num="20" wdcount="13"> It will start whenever it comes down from the union president,'' Buchanan said.</s>

<s docid="AP890616-0230" num="21" wdcount="17"> Union spokesman Joe Corcoran was not in his office and has not returned phone calls this week.</s>

<s docid="AP890616-0230" num="22" wdcount="22"> The head of the coal industry bargaining unit said he had no plans to confer with the Pittston on the wildcat strikes.</s>

<s docid="AP890616-0230" num="23" wdcount="52"> ``I would no more try to tell someone else how to run their company than I would expect someone else to try to tell me how to run my company,'' said Robert H. Quenon, president of Peabody Holding Co., the nation's largest coal producer, and chairman of the Bituminous Coal Operators Association.</s>

<s docid="AP890616-0230" num="24" wdcount="23"> Quenon flew to Charleston from St. Louis on Thursday to meet with reporters and express Peabody's and the association's concerns about the walkout.</s>

<s docid="AP890616-0230" num="25" wdcount="15"> An estimated 2,300 United Mine Workers members stayed away from their jobs today in Pennsylvania.</s>

<s docid="AP890616-0230" num="26" wdcount="29"> Most worked for Rochester & Pittsburgh Coal Co. operations in central Pennsylvania, where 1,600 miners failed to report for work at midnight Thursday, said company spokesman Hank Waneck said.</s>

<s docid="AP890616-0230" num="27" wdcount="12"> About 290 miners at Peabody's Camp No. 1 mine in Morganfield, Ky.</s>

<s docid="AP890616-0230" num="28" wdcount="11"> , didn't report for work today, said company spokesman Tom Clarke.</s>

<s docid="AP890616-0230" num="29" wdcount="16"> At least 270 miners were off the job at two mines in Indiana today, spokesmen said.</s>

<s docid="AP890616-0230" num="30" wdcount="18"> Mark Arnold, a spokesman for UMW District 11 in Terre Haute, attributed the action to the CBS show.</s>

<s docid="AP890616-0230" num="31" wdcount="22"> ``When the miners saw that last night, that kind of set them off to where they decided to walk out,'' he said.</s>

<s docid="AP890616-0230" num="32" wdcount="13"> About one-third of West Virginia's 24,000 miners were reported off the job today.</s>

<s docid="AP890616-0230" num="33" wdcount="19"> Some 600 miners in Wise County, Va., who walked out earlier in the week returned to work this morning.</s>

<s docid="AP890616-0230" num="34" wdcount="26"> The coal companies contend the walkouts at companies other than Pittston violate a no-strike clause in the 1988 national contract the union signed with the association.</s>

<s docid="AP890616-0230" num="35" wdcount="8"> Pittston did not take part in that agreement.</s>

<s docid="AP890616-0230" num="36" wdcount="22"> Union officials have not returned phone calls this week, but in the past they have said they have not authorized the walkout.</s>

<s docid="AP890616-0230" num="37" wdcount="25"> ``I think the union leadership ought to exercise its leadership role and do what they can to lead the miners back to work,'' Quenon said.</s>

<s docid="AP890616-0230" num="38" wdcount="6"> ``That's why we have a union.</s>

<s docid="AP890616-0230" num="39" wdcount="28"> That's why we have an agreement with the union _ to set out the terms and conditions under which we will have labor to run our coal mines.</s>

<s docid="AP890616-0230" num="40" wdcount="7"> ``And we expect that to be honored.''</s>
</TEXT>
</DOC>
