<DOC>
<DOCNO>

<s docid="AP891103-0200" num="1" wdcount="1"> AP891103-0200</s>
</DOCNO>
<FILEID>

<s docid="AP891103-0200" num="2" wdcount="2"> AP-NR-11-03-89 2007EST</s>
</FILEID>
<FIRST>

<s docid="AP891103-0200" num="3" wdcount="5"> u i AM-Soviet-Strikes 11-03 0338</s>
</FIRST>
<SECOND>

<s docid="AP891103-0200" num="4" wdcount="1"> AM-Soviet-Strikes,0351</s>
</SECOND>
<HEAD>

<s docid="AP891103-0200" num="5" wdcount="5"> Soviet Miners Block Coal Shipments</s>
</HEAD>
<DATELINE>

<s docid="AP891103-0200" num="6" wdcount="2"> MOSCOW (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP891103-0200" num="7" wdcount="24"> Thousands of miners in the northern Vorkuta region are expanding their strike and some are blocking coal shipments, the Soviet news media reported Friday.</s>

<s docid="AP891103-0200" num="8" wdcount="14"> The miners are demanding the government fulfill promises of improved living and job conditions.</s>

<s docid="AP891103-0200" num="9" wdcount="16"> Soviet officials have said the strikes could force fuel rationing during the Soviet Union's severe winter.</s>

<s docid="AP891103-0200" num="10" wdcount="30"> Premier Nikolai I. Ryzhkov introduced a bill in parliament that would increase pension benefits by about 40 percent and upgrade benefits for coal miners, the official Tass news agency reported.</s>

<s docid="AP891103-0200" num="11" wdcount="46"> The Komsomolskaya Pravda youth newspaper, in an article giving a sympathetic view of the workers condition's in the Arctic Cirle coal-mining districts, said many miners do not see daylight for months because of their underground work and the sun dips below the horizon in the winter.</s>

<s docid="AP891103-0200" num="12" wdcount="20"> A regional court in Vorkuta ruled that the latest round of strikes is illegal but did not impose any penalties.</s>

<s docid="AP891103-0200" num="13" wdcount="9"> The miners's unions said the decision will be appealed.</s>

<s docid="AP891103-0200" num="14" wdcount="34"> Coal miners in the northern region and the Ukraine struck for two weeks this summer but returned to work in July after parliament passed a resolution promising reforms, including improved social and economic conditions.</s>

<s docid="AP891103-0200" num="15" wdcount="10"> The miners say the government has renedged on its promises.</s>

<s docid="AP891103-0200" num="16" wdcount="36"> The news media gave these accounts of the latest strikes: Workers at the Vorgashor mine in the Arctic Circle, the largest mine in the Vorkuta region, continued their strike for an eighth day, according to Tass.</s>

<s docid="AP891103-0200" num="17" wdcount="32"> Komsomolskaya Pravda said night-shift workers walked out at three mines in Vorkuta and at another one the miners were still working but were preventing the coal from being shipped outside the region.</s>

<s docid="AP891103-0200" num="18" wdcount="17"> In the Ukraine's Donetsk Coal Basin, the nation's major coal-producing area, miner representatives were discussing another strike.</s>

<s docid="AP891103-0200" num="19" wdcount="13"> Tens of thousands of miners walked off the job for two hours Wednesday.</s>

<s docid="AP891103-0200" num="20" wdcount="27"> Tass said that in Donetsk the miners gathered in front of the House of Unions to demand that the government set a deadline for implementing reforms .</s>
</TEXT>
</DOC>
