<DOC>
<DOCNO>

<s docid="AP890721-0091" num="1" wdcount="1"> AP890721-0091</s>
</DOCNO>
<FILEID>

<s docid="AP890721-0091" num="2" wdcount="2"> AP-NR-07-21-89 1239EDT</s>
</FILEID>
<FIRST>

<s docid="AP890721-0091" num="3" wdcount="7"> u i PM-Soviet-Strikes 2ndLd-Writethru a0510 07-21 0777</s>
</FIRST>
<SECOND>

<s docid="AP890721-0091" num="4" wdcount="4"> PM-Soviet-Strikes, 2nd Ld-Writethru, a0510,0802</s>
</SECOND>
<HEAD>

<s docid="AP890721-0091" num="5" wdcount="8"> Siberian Miners Agree to Return, But Strikes Spread</s>
</HEAD>
<HEAD>

<s docid="AP890721-0091" num="6" wdcount="20"> Eds: Leads with 20 grafs to UPDATE with coal official giving details of Donetsk strikes, other details on regional strikes.</s>

<s docid="AP890721-0091" num="7" wdcount="6"> Pickup 19th pvs, `Tass today.. .</s>
</HEAD>
<HEAD>

<s docid="AP890721-0091" num="8" wdcount="2"> LaserPhoto NY4</s>
</HEAD>
<BYLINE>

<s docid="AP890721-0091" num="9" wdcount="3"> By BRYAN BRUMLEY</s>
</BYLINE>
<BYLINE>

<s docid="AP890721-0091" num="10" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890721-0091" num="11" wdcount="3"> PROKOPYEVSK, U.S.S.R. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890721-0091" num="12" wdcount="31"> Coal miners in Siberia ended their strike today after exacting promises of better food, housing and working conditions, but the wave of unrest they launched continued in other key coal regions.</s>

<s docid="AP890721-0091" num="13" wdcount="36"> Some of the 150,000 miners who went on strike last week in Siberia's Kuznetsk coal basin region returned to work Thursday, and the rest went back today, strike leaders and the official Tass news agency said.</s>

<s docid="AP890721-0091" num="14" wdcount="6"> Despite announcements that President Mikhail S.</s>

<s docid="AP890721-0091" num="15" wdcount="25"> Gorbachev's sweeping concessions _ including granting miners greater control over their industry _ apply nationwide, hundreds of thousands of miners stayed off the job elsewhere.</s>

<s docid="AP890721-0091" num="16" wdcount="31"> In the largest coal region, the Donetsk Coal Basin of the Ukraine, more than 300,000 miners were on strike, the deputy minister of the coal industry, Alexander P. Fisun, told Izvestia.</s>

<s docid="AP890721-0091" num="17" wdcount="32"> In the Karaganda region of the southern republic of Kazakhstan, the Soviet Union's third-biggest coal-producing area, all 26 mines were at a standstill, and miners made more than 70 demands, Izvestia said.</s>

<s docid="AP890721-0091" num="18" wdcount="22"> Strikes were also reported in the Pechora Coal Basin in the Russian republic, and Chervonograd in the western Ukraine, official media said.</s>

<s docid="AP890721-0091" num="19" wdcount="11"> The labor unrest is the Soviet Union's worst in six decades.</s>

<s docid="AP890721-0091" num="20" wdcount="29"> Gorbachev has expressed sympathy for the strikers and placed much of the blame for the miners' deteriorating working and living conditions on leaders of the officially sanctioned trade unions.</s>

<s docid="AP890721-0091" num="21" wdcount="25"> Still, he and other Communist leaders have warned that if the strikes don't end quickly, coal shortages will shut down much of the country's industry.</s>

<s docid="AP890721-0091" num="22" wdcount="19"> On Wednesday, the Kuznetsk strike committee and members of a high-level government commission signed an agreement meeting many demands.</s>

<s docid="AP890721-0091" num="23" wdcount="33"> The workers were promised higher wages, increased deliveries of meat, sugar, soap, clothes, furniture and other consumer goods, more housing construction and _ most important _ a greater voice in running their industry.</s>

<s docid="AP890721-0091" num="24" wdcount="48"> ``It's a victory over the system that we've had in the Soviet Union for the last 70 years, a system in which we work hard but get little in return,'' said Pyotr A. Menayev, an engineer at the Taldinski Severny open pit mine on the outskirts of Prokopyevsk.</s>

<s docid="AP890721-0091" num="25" wdcount="20"> Strike committee member Vyacheslav G. Akulov stressed that the miners had agreed to ``interrupt the strike, not to end it''.</s>

<s docid="AP890721-0091" num="26" wdcount="24"> He said the miners would hold the government to its word: ``If the government doesn't keep its promises, we will go back on strike''.</s>

<s docid="AP890721-0091" num="27" wdcount="31"> The 26-member strike committee met today with a half-dozen representatives to the national parliament and called for municipal elections to be advanced from the spring to the first half of November.</s>

<s docid="AP890721-0091" num="28" wdcount="22"> The last local elections in Kuznetsk were held two years ago, before Gorbachev's reforms made elections more democratic by offering multiple candidates.</s>

<s docid="AP890721-0091" num="29" wdcount="14"> The strike wave began 11 days ago in Kuznetsk, the country's second-largest coal field.</s>

<s docid="AP890721-0091" num="30" wdcount="25"> Tass said late Thursday that strikes had ended at six mines in the Donetsk region but that most mines in the area remained on strike.</s>

<s docid="AP890721-0091" num="31" wdcount="27"> Miners at three shafts in Chervonograd, near the Polish border, joined the walkout Thursday night, said Anatoly M. Dotsenko, a spokesman for the Ukrainian Helsinki Watch Group.</s>

<s docid="AP890721-0091" num="32" wdcount="9"> The coal industry employs more than 1 million workers.</s>

<s docid="AP890721-0091" num="33" wdcount="23"> Tass today quoted Coal Minister Mikhail I. Shchadov as saying the government agreed to make all Soviet coal operations economically and legally independent.</s>

<s docid="AP890721-0091" num="34" wdcount="19"> He said authorities had agreed to additional payments for night and evening shifts and to give workers Sundays off.</s>

<s docid="AP890721-0091" num="35" wdcount="42"> Beginning Aug. 1, mines and other industries in the ``coal mining complex'' will gain the right to sell for negotiated prices in the USSR and abroad products which they make over and above the state plan,'' Tass quoted the agreement as stipulating.</s>

<s docid="AP890721-0091" num="36" wdcount="16"> It said local managers will be able to raise coal prices to reflect actual production costs.</s>

<s docid="AP890721-0091" num="37" wdcount="32"> Gorbachev is trying to end the longtime Soviet practice of setting prices for goods that bear no relation to their free-market value and encourage and end to central control of the economy.</s>

<s docid="AP890721-0091" num="38" wdcount="14"> Akulov said that beginning Jan. 1, the Kuznetzk coal basin will become economically autonomous.</s>

<s docid="AP890721-0091" num="39" wdcount="28"> ``The Coal Mining Ministry will continue to run the mines, but the miners will have a much greater say setting production levels and allocating the profits,'' he said.</s>

<s docid="AP890721-0091" num="40" wdcount="14"> ``Our politics have gotten freer under perestroika,'' Akulov said of Gorbachev's economic reform program.</s>

<s docid="AP890721-0091" num="41" wdcount="7"> ``But our living conditions have not improved''.</s>

<s docid="AP890721-0091" num="42" wdcount="12"> Until Gorbachev rose to power in 1985, strikes were not tolerated .</s>
</TEXT>
</DOC>
