<DOC>
<DOCNO>

<s docid="AP890719-0248" num="1" wdcount="1"> AP890719-0248</s>
</DOCNO>
<FILEID>

<s docid="AP890719-0248" num="2" wdcount="2"> AP-NR-07-19-89 0907EST</s>
</FILEID>
<FIRST>

<s docid="AP890719-0248" num="3" wdcount="7"> u f PM-Soviet-Strikes 1stLd-Writethru f0038 07-19 0775</s>
</FIRST>
<SECOND>

<s docid="AP890719-0248" num="4" wdcount="4"> PM-Soviet-Strikes, 1st Ld-Writethru, f0038,0800</s>
</SECOND>
<HEAD>

<s docid="AP890719-0248" num="5" wdcount="6"> Gorbachev Says Strikes Threaten to Spread</s>
</HEAD>
<HEAD>

<s docid="AP890719-0248" num="6" wdcount="17"> Eds: New thruout to ADD details of concessions offered in Prokopyevsk; CORRECTS spelling of Prokopyevsk and Kuznetsk.</s>

<s docid="AP890719-0248" num="7" wdcount="3"> No pickup .</s>
</HEAD>
<BYLINE>

<s docid="AP890719-0248" num="8" wdcount="3"> By CAREY GOLDBERG</s>
</BYLINE>
<BYLINE>

<s docid="AP890719-0248" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890719-0248" num="10" wdcount="2"> MOSCOW (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890719-0248" num="11" wdcount="32"> President Mikhail S. Gorbachev said today that thousands of striking coal miners and other workers are urging railway employees to join the work stoppage and that the unrest threatens his economic reforms.</s>

<s docid="AP890719-0248" num="12" wdcount="20"> Strikes have shut down more than 200 mines and factories in the country's two top coal-producing regions, official reports said.</s>

<s docid="AP890719-0248" num="13" wdcount="20"> In a report to the Supreme Soviet, Gorbachev said they have resulted in a 1 million-ton drop in coal production.</s>

<s docid="AP890719-0248" num="14" wdcount="24"> Following Gorbachev to the podium, legislator Anatoly Saunin said each lost work day cost millions of rubles that might otherwise help improve living conditions.</s>

<s docid="AP890719-0248" num="15" wdcount="14"> ``You mustn't hold a knife to the throat'' of the government, he told strikers.</s>

<s docid="AP890719-0248" num="16" wdcount="28"> Saunin, from the Donetsk region of the Ukraine, the country's top coal region, said the number of striking mines there increased from 20 on Tuesday to 58 today.</s>

<s docid="AP890719-0248" num="17" wdcount="30"> ``Now there are reports of calls to railroad workers to join the strike as of Aug. 1,'' Gorbachev said during the parliamentary session, which was broadcast on television and radio.</s>

<s docid="AP890719-0248" num="18" wdcount="29"> ``Such a development of events poses a threat to the implementation of plans projected by the policy of perestroika,'' he said, referring to his efforts to restructure the economy.</s>

<s docid="AP890719-0248" num="19" wdcount="12"> Miners began walking out July 11 in Siberia's Kuznetsk Basin coal region.</s>

<s docid="AP890719-0248" num="20" wdcount="9"> Workers in other industries in the region soon followed.</s>

<s docid="AP890719-0248" num="21" wdcount="13"> On Saturday, miners in the Donetsk coal basin began walking off the job.</s>

<s docid="AP890719-0248" num="22" wdcount="19"> The miners are demanding more local control over their industry as well as higher wages and better living conditions.</s>

<s docid="AP890719-0248" num="23" wdcount="33"> Gorbachev said he and Premier Nikolai I. Ryzhkov sent a telegram to miners in the Ukraine assuring them that any concessions granted to Siberian miners would apply to other mining regions as well.</s>

<s docid="AP890719-0248" num="24" wdcount="17"> He blamed some of the miners' discontent on ``anti-socialist'' elements but said he understood their basic demands.</s>

<s docid="AP890719-0248" num="25" wdcount="39"> Government negotiations with strike committees have resolved most of the miners' demands, including those on pensions and overtime, but some longer-term questions will take up to a month to settle, and the miners are refusing any delay, he said.</s>

<s docid="AP890719-0248" num="26" wdcount="14"> Central authorities have so far balked at granting miners more control over their industry.</s>

<s docid="AP890719-0248" num="27" wdcount="35"> If the strike spreads to other sectors of the economy, ``We may have to take such extreme measures that it will hurt what we've been doing,'' Gorbachev said, without specifying what steps he would take.</s>

<s docid="AP890719-0248" num="28" wdcount="22"> He said the lost coal production could not be recovered by increasing the mines' output because they already work at full capacity.</s>

<s docid="AP890719-0248" num="29" wdcount="26"> Recent reports have put the total number of strikers in the Donetsk and Kuznetsk regions at more than 112,000, but the number appeared to be rising.</s>

<s docid="AP890719-0248" num="30" wdcount="18"> Because of disrupted coal deliveries, the strike threatened ``a catastrophe'' at metallurgical and electrical power plants, Tass said.</s>

<s docid="AP890719-0248" num="31" wdcount="30"> The Politburo sent to Kuznetsk Nikolai N. Slyunkov, a member of the ruling Communist Party body who worked several years in the tractor-building industry and has spoken about labor discipline.</s>

<s docid="AP890719-0248" num="32" wdcount="25"> He held marathon meetings with strikers Monday night and Tuesday and addressed 30,000 people in the main square of Prokopyevsk, 2,100 miles east of Moscow.</s>

<s docid="AP890719-0248" num="33" wdcount="30"> Miners in the Donetsk Basin are demanding a 40 percent wage increase for night work, improved living conditions, a fixed day off and retirement after 20 years of underground work.</s>

<s docid="AP890719-0248" num="34" wdcount="12"> They also demand that the Coal Mining Ministry trim its managerial staff.</s>

<s docid="AP890719-0248" num="35" wdcount="21"> Tass carried a report Tuesday denying that the Soviet Union's third major coal region, Karaganda in Kazakhstan, also was on strike.</s>

<s docid="AP890719-0248" num="36" wdcount="20"> A proposed law on ending strikes and other labor conflicts is being rushed through the Supreme Soviet legislature, Tass said.</s>

<s docid="AP890719-0248" num="37" wdcount="34"> A spokesman for the strike committee in Prokopyevsk, Valery Legachev, said Tuesday that Slyunkov ``promised to increase the area's regular food supplies by 20 to 30 percent, as well as soap and washing powder''.</s>

<s docid="AP890719-0248" num="38" wdcount="30"> Izvestia, the government newspaper, reported Tuesday that Slyunkov promised higher pay for night work, longer vacations and a doubling of the wholesale price of coal to pay for the benefits.</s>

<s docid="AP890719-0248" num="39" wdcount="25"> The strikes are believed to be the nation's worst since the 1920s, when the country was gripped in revolution, civil war and a power struggle.</s>

<s docid="AP890719-0248" num="40" wdcount="16"> Records from that period are sketchy, but fighting was widespread and industrial production was severely disrupted.</s>

<s docid="AP890719-0248" num="41" wdcount="19"> Until Gorbachev came to power in 1985, the official media did not report job actions in the Soviet Union.</s>

<s docid="AP890719-0248" num="42" wdcount="20"> Underground reports described strikes that were of much shorter and not as widespread as those in Kuznetsk and Donetsk .</s>
</TEXT>
</DOC>
