<DOC>
<DOCNO>

<s docid="FBIS4-42027" num="1" wdcount="1"> FBIS4-42027</s>
</DOCNO>
<HT>

<s docid="FBIS4-42027" num="2" wdcount="1"> "drsov126_f_94009"</s>
</HT>
<HEADER>
<AU>

<s docid="FBIS4-42027" num="3" wdcount="1"> FBIS-SOV-94-126</s>
</AU>

<s docid="FBIS4-42027" num="4" wdcount="2"> Daily Report</s>
<DATE1>

<s docid="FBIS4-42027" num="5" wdcount="3"> 29 Jun 1994</s>
</DATE1>
</HEADER>
<F>

<s docid="FBIS4-42027" num="6" wdcount="2"> National Affairs</s>
</F>
<H3>
<TI>

<s docid="FBIS4-42027" num="7" wdcount="6"> Mine Strikes Seen Directed Against Kravchuk</s>
</TI>
</H3>
<HT>
<F>
<PHRASE>

<s docid="FBIS4-42027" num="8" wdcount="6"> Mine Strikes Seen Directed Against Kravchuk</s>
</PHRASE>
</F>
</HT>
<F>

<s docid="FBIS4-42027" num="9" wdcount="10"> LD2906171094 Kiev UNIAN in Ukrainian 1330 GMT 29 Jun 94</s>
</F>
<F>

<s docid="FBIS4-42027" num="10" wdcount="1"> LD2906171094</s>
</F>
<F>

<s docid="FBIS4-42027" num="11" wdcount="2"> Kiev UNIAN</s>
</F>
<F>

<s docid="FBIS4-42027" num="12" wdcount="1"> Ukrainian</s>
</F>
<TEXT>

<s docid="FBIS4-42027" num="13" wdcount="38"> BFN [Text] Donetsk Oblast [no date as received] -- As UNIAN reported, miners at the "Ordzhonikidzevuhillya" coal production association and the "Yenakiyevo" and "Poltava" pits went on strike in Yenakiyevo on 27 June, demanding payment of wage arrears.</s>

<s docid="FBIS4-42027" num="14" wdcount="9"> The strike continued at these mines on 28 June.</s>

<s docid="FBIS4-42027" num="15" wdcount="18"> Some of the miners at the Karl Marx, "Chernovonyy Zhovten," "Chervonyy Profinter," and "Yunkom" pits joined the strike.</s>

<s docid="FBIS4-42027" num="16" wdcount="12"> A total of 1,200 of the association's 2,248 workers are on strike.</s>

<s docid="FBIS4-42027" num="17" wdcount="34"> A rally consisting of 350 miners was held on 28 June near the town council building where demands were made to pay the wages and dismiss the director general of the "Ordzhonikidzevuhillya" production association.</s>

<s docid="FBIS4-42027" num="18" wdcount="44"> A strike committee consisting of 12 persons was elected (one of the members is a former Komsomol leader and former USSR people's deputy Viktor Honcharov) and it was decided to continue the strike until the demands that had been raised have been completely fulfilled.</s>

<s docid="FBIS4-42027" num="19" wdcount="38"> On 28 June, 118 of 258 workers on the second shift at the "PivdennoDonbass" mine of the "Donetskvuhillya" production association in the town of Ugledar refused to start work for the same reasons -- delay in paying wages.</s>

<s docid="FBIS4-42027" num="20" wdcount="22"> After a meeting with the mine's director, who promised to pay the arrears, the miners on the third shift returned to work.</s>

<s docid="FBIS4-42027" num="21" wdcount="28"> On 27 June, all miners on the fourth shift at the "Karbomid" and "Pervomaysk" mines in Pervomaysk, Lugansk oblast, refused to start work (142 and 157 miners respectively).</s>

<s docid="FBIS4-42027" num="22" wdcount="40"> In the opinion of the mine's representatives, who wished not to be identified, the strike has a clear political hue -- to attempt to compromise the existing authorities and, particularly, President Leonid Kravchuk before the second round of presidential elections.</s>

<s docid="FBIS4-42027" num="23" wdcount="21"> According to some reports, among the leaders of the striking pits there are members of the Kuchma-Hrynyov Interregional Bloc of Reforms.</s>

<s docid="FBIS4-42027" num="24" wdcount="60"> As Kostyantyn Fesenko, chairman of the coal industry workers trade union, informed a UNIAN correspondent, Viktor Yushchenko, the chairman of the National Bank of Ukraine, in a telephone conversation on 29 June, gave assurances that the money for the miners' wages as well as subsidies for the following month would be found and forwarded in the next few days .</s>
</TEXT>
</DOC>
