<DOC>
<DOCNO>

<s docid="FT923-12122" num="1" wdcount="1"> FT923-12122</s>
</DOCNO>
<PROFILE>

<s docid="FT923-12122" num="2" wdcount="1"> _AN-CGUANACNFT</s>
</PROFILE>
<DATE>

<s docid="FT923-12122" num="3" wdcount="1"> 920721</s>
</DATE>
<HEADLINE>

<s docid="FT923-12122" num="4" wdcount="14"> FT 21 JUL 92 / Commodities and Agriculture: Poland's copper combine hit by strike</s>
</HEADLINE>
<BYLINE>

<s docid="FT923-12122" num="5" wdcount="3"> By CHRISTOPHER BOBINSKI</s>
</BYLINE>
<DATELINE>

<s docid="FT923-12122" num="6" wdcount="1"> WARSAW</s>
</DATELINE>
<TEXT>

<s docid="FT923-12122" num="7" wdcount="34"> WORKERS AT KGHM, Poland's copper producing combine went on strike yesterday as coal mining unions staged token stoppages in a third of the country's pits in a major challenge to the government's economic policies.</s>

<s docid="FT923-12122" num="8" wdcount="39"> The strike at KGHM in Lubin, western Poland, where mining unions representing some 40,0000 workers have been demanding a 30 per cent wage increase, came despite a management offer at the weekend to increase wages by 20 per cent.</s>

<s docid="FT923-12122" num="9" wdcount="24"> Further increases could only come if the government eased prohibitive wage control taxes, thus providing a powerful precedent for wage demands by other groups.</s>

<s docid="FT923-12122" num="10" wdcount="43"> Meanwhile coal mining unions are also demanding wage increases as well as a clear restructuring strategy for their industry after last week's scattered stoppages in some 15 of Poland's 71 pits wrung promises of wage rises that cash strapped managements can ill afford.</s>

<s docid="FT923-12122" num="11" wdcount="33"> In contrast to the copper industry, which continues to show a profit, coal mining is running at a loss with subsidies stopped in March as the government moved to control the budget deficit.</s>

<s docid="FT923-12122" num="12" wdcount="26"> The industry is experiencing a coal glut with pit head, power station and export stocks amounting to some 12m tonnes, the equivalent of a month's output.</s>

<s docid="FT923-12122" num="13" wdcount="19"> This has led to temporary lay-offs, which have hit miners' incomes and led to the present bout of unrest.</s>

<s docid="FT923-12122" num="14" wdcount="26"> Polish mines produced 69.7m tonnes of coal in the first half of the year or 1.5 per cent less than in the same period last year.</s>

<s docid="FT923-12122" num="15" wdcount="25"> Meanwhile KGHM produced 197,000 tonnes of refined copper in the same period or 3.9 per cent more than in the first half of 1991 .</s>
</TEXT>
<PUB>

<s docid="FT923-12122" num="16" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT923-12122" num="17" wdcount="3"> London Page 24</s>
</PAGE>
</DOC>
