<DOC>
<DOCNO>

<s docid="FT933-9536" num="1" wdcount="1"> FT933-9536</s>
</DOCNO>
<PROFILE>

<s docid="FT933-9536" num="2" wdcount="1"> _AN-DHJCNAFWFT</s>
</PROFILE>
<DATE>

<s docid="FT933-9536" num="3" wdcount="1"> 930809</s>
</DATE>
<HEADLINE>

<s docid="FT933-9536" num="4" wdcount="11"> FT 09 AUG 93 / Romanian coal miners flex their muscles</s>
</HEADLINE>
<BYLINE>

<s docid="FT933-9536" num="5" wdcount="3"> By VIRGINIA MARSH</s>
</BYLINE>
<DATELINE>

<s docid="FT933-9536" num="6" wdcount="1"> BUCHAREST</s>
</DATELINE>
<TEXT>

<s docid="FT933-9536" num="7" wdcount="28"> COALMINERS from Romania's Jiu Valley, who spearheaded violent anti-reform rampages through Bucharest in 1990 and 1991, are once again out on strike, pressing the government for higher wages.</s>

<s docid="FT933-9536" num="8" wdcount="12"> But so far the government, unlike its predecessors, has not caved in.</s>

<s docid="FT933-9536" num="9" wdcount="18"> It has instead begun legal action to have the strike, which today entered its second week, declared illegal.</s>

<s docid="FT933-9536" num="10" wdcount="5"> The miners' position seems untenable.</s>

<s docid="FT933-9536" num="11" wdcount="24"> Romanians appear solidly opposed to the strike, angered by the miners' demands for an average wage of the equivalent of Dollars 290 a month.</s>

<s docid="FT933-9536" num="12" wdcount="7"> Most workers earn less than Dollars 80.</s>

<s docid="FT933-9536" num="13" wdcount="20"> Workers in the same trade union confederation as the miners have ignored appeals by their leaders to strike in solidarity.</s>

<s docid="FT933-9536" num="14" wdcount="28"> The Ministry of Industry argues that the 6m tonnes of pit coal produced each year in the Jiu Valley's 13 mines is not a vital source of energy.</s>

<s docid="FT933-9536" num="15" wdcount="32"> The region's coal supplies two nearby power stations but these plants, which together account for only 4 per cent of the country's electricity capacity, could also be run using lignite and gas.</s>

<s docid="FT933-9536" num="16" wdcount="18"> The ministry further argues that the miners are in danger of pricing their coal out of the market.</s>

<s docid="FT933-9536" num="17" wdcount="18"> According to the ministry, if the miners' pay demands were met, the cost of their coal would double.</s>

<s docid="FT933-9536" num="18" wdcount="13"> Even at present prices, Ukrainian coal is being imported to the Romanian market.</s>

<s docid="FT933-9536" num="19" wdcount="9"> The strike seems motivated by a number of factors.</s>

<s docid="FT933-9536" num="20" wdcount="24"> The rank and file have come out because they want more money to compensate for the difficult conditions in which they live and work.</s>

<s docid="FT933-9536" num="21" wdcount="28"> They are also following the call of their charismatic leader, Mr Miron Cosma, the man who led them on protests to Bucharest and secured their earlier wage increases.</s>

<s docid="FT933-9536" num="22" wdcount="26"> Mr Cosma's motive for calling the strike - for which, surprisingly, he has the support of RAH, the state-owned coal mining company - are less obvious.</s>

<s docid="FT933-9536" num="23" wdcount="24"> The ministries of industry and finance are conducting investigations into charges of fraud and embezzlement by Mr Cosma and several senior RAH company officials.</s>

<s docid="FT933-9536" num="24" wdcount="14"> The company's chief accountant and budget director have already been fired, following earlier investigations.</s>

<s docid="FT933-9536" num="25" wdcount="17"> Ministry of Industry officials argue the strike could be an attempt to divert attention from the investigations.</s>

<s docid="FT933-9536" num="26" wdcount="5"> Mr Cosma, however, appears confident.</s>

<s docid="FT933-9536" num="27" wdcount="13"> One of his bargaining tools is the threat, albeit veiled, of fresh violence.</s>

<s docid="FT933-9536" num="28" wdcount="30"> In response to the question as to whether he intends to lead his men, who appear to support him whole-heartedly, to Bucharest again, he says: 'With miners, anything is possible'.</s>

<s docid="FT933-9536" num="29" wdcount="7"> But he is also making political threats.</s>

<s docid="FT933-9536" num="30" wdcount="31"> In recent months, Mr Cosma has claimed he has evidence that senior government officials, including President Ion Iliescu, called miners to Bucharest as part of plans to consolidate their own power.</s>

<s docid="FT933-9536" num="31" wdcount="13"> Mr Cosma appears increasingly willing to talk if his demands are not met.</s>

<s docid="FT933-9536" num="32" wdcount="23"> It remains to be seen whether those involved in the incidents of 1990 and 1991 now feel confident enough to ignore him .</s>
</TEXT>
<XX>

<s docid="FT933-9536" num="33" wdcount="1"> Countries:-</s>
</XX>
<CN>

<s docid="FT933-9536" num="34" wdcount="5"> ROZ Romania, East Europe .</s>
</CN>
<XX>

<s docid="FT933-9536" num="35" wdcount="1"> Industries:-</s>
</XX>
<IN>

<s docid="FT933-9536" num="36" wdcount="3"> P1222 Bituminous Coal-Underground.</s>

<s docid="FT933-9536" num="37" wdcount="5"> P1221 Bituminous Coal and Lignite-Surface.</s>

<s docid="FT933-9536" num="38" wdcount="4"> P8631 Labor Organizations .</s>
</IN>
<XX>

<s docid="FT933-9536" num="39" wdcount="1"> Types:-</s>
</XX>
<TP>

<s docid="FT933-9536" num="40" wdcount="3"> PEOP Labour .</s>
</TP>
<PUB>

<s docid="FT933-9536" num="41" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT933-9536" num="42" wdcount="3"> International Page 3</s>
</PAGE>
</DOC>
