<DOC>
<DOCNO>

<s docid="SJMN91-06069108" num="1" wdcount="1"> SJMN91-06069108</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06069108" num="2" wdcount="1"> 06069108</s>
</ACCESS>
<DESCRIPT>

<s docid="SJMN91-06069108" num="3" wdcount="3"> USSR; LABOR; STRIKE</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06069108" num="4" wdcount="37"> A one-day strike by coal miners in Kazakhstan and the Ukraine has grown into a nationwide walkout involving up to 100,000 miners demanding President Mikhail Gorbachev surrender power to the restive republics, a union leader said Friday.</s>

<s docid="SJMN91-06069108" num="5" wdcount="8"> "The government doesn't want to negotiate with us.</s>

<s docid="SJMN91-06069108" num="6" wdcount="28"> They understand that we're not like the phony unions they had before," said Pavel Shushpanov, chairman of the executive committee of the 5-month-old Independent Union of Miners .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06069108" num="7" wdcount="1"> Front</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06069108" num="8" wdcount="7"> SOVIET STRIKE SPREADS; MINERS STEP UP DEMANDS</s>
</HEADLINE>
<TEXT>

<s docid="SJMN91-06069108" num="9" wdcount="38"> Most of the country's 1.2 million coal miners are still working, but output in some key regions has been halved, saddling Gorbachev with a substantial labor and fuel problem even as he struggles to revive the Soviet economy.</s>

<s docid="SJMN91-06069108" num="10" wdcount="11"> The strike is the new union's first major test of strength.</s>

<s docid="SJMN91-06069108" num="11" wdcount="33"> It began March 1 as a warning action in the Karaganda coal field of Kazakhstan and the Krasnoarmeisk area of the Ukraine but gradually spread to all of the country's major coal regions.</s>

<s docid="SJMN91-06069108" num="12" wdcount="17"> The strikers are seeking wage increases of at least 100 percent, better working conditions and earlier retirement.</s>

<s docid="SJMN91-06069108" num="13" wdcount="25"> They claim the government has not kept promises it made to raise miners' living standards as settlement of a nationwide coal strike in July 1989.</s>

<s docid="SJMN91-06069108" num="14" wdcount="13"> The 1989 strike, which involved more than 500,000 miners, made only economic demands.</s>

<s docid="SJMN91-06069108" num="15" wdcount="12"> This time, Shushpanov said, the miners also want three major political concessions.</s>

<s docid="SJMN91-06069108" num="16" wdcount="12"> First, he said, they want "real sovereignty" for the 15 Soviet republics.</s>

<s docid="SJMN91-06069108" num="17" wdcount="26"> They are unhappy with Gorbachev's proposed Union Treaty, which would leave the central government in control of the economy, defense, foreign policy and communications, he said.</s>

<s docid="SJMN91-06069108" num="18" wdcount="19"> Second, the union is demanding more power for Gorbachev's Federation Council, which includes the presidents of all the republics.</s>

<s docid="SJMN91-06069108" num="19" wdcount="29"> Finally, the union wants a "law on property" that would define what belongs to the government and allow private ownership of land and industry, including some mines, he said.</s>

<s docid="SJMN91-06069108" num="20" wdcount="36"> According to the state news agency Tass, the strike has spread to the Donetsk coal basin of the Ukraine, the Vorkuta and Inta regions of northern Russia, and the Kuznetsk coal basin of western Siberia .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06069108" num="21" wdcount="2"> Associated Press</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06069108" num="22" wdcount="1"> USA</s>
</COUNTRY>
<CITY>

<s docid="SJMN91-06069108" num="23" wdcount="1"> Moscow</s>
</CITY>
<EDITION>

<s docid="SJMN91-06069108" num="24" wdcount="2"> Morning Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06069108" num="25" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06069108" num="26" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06069108" num="27" wdcount="1"> 910309</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06069108" num="28" wdcount="1"> Saturday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06069108" num="29" wdcount="1"> March</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06069108" num="30" wdcount="1"> 16A</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06069108" num="31" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06069108" num="32" wdcount="1"> WEST</s>
</REGION>
<STATE>

<s docid="SJMN91-06069108" num="33" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06069108" num="34" wdcount="1"> 345</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06069108" num="35" wdcount="5"> Saturday March 9, 1991 00069108,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06069108" num="36" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06069108" num="37" wdcount="1"> 1</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06069108" num="38" wdcount="1"> ENG</s>
</LANGUAGE>
</DOC>
