<DOC>
<DOCNO>

<s docid="WSJ870804-0095" num="1" wdcount="1"> WSJ870804-0095</s>
</DOCNO>
<HL>

<s docid="WSJ870804-0095" num="2" wdcount="28"> Black Miners In South Africa Set Strike Date --- Gold and Coal Workers Seek Better Pay and Benefits; Firms Build Stockpiles --- A Wall Street Journal News Roundup</s>
</HL>
<DD>

<s docid="WSJ870804-0095" num="3" wdcount="1"> 08/04/87</s>
</DD>
<SO>

<s docid="WSJ870804-0095" num="4" wdcount="4"> WALL STREET JOURNAL (J)</s>
</SO>
<IN>

<s docid="WSJ870804-0095" num="5" wdcount="18"> AFRIC ANGLY LABOR PRECIOUS METALS, STONES, GOLD, SILVER (PCS) COMMODITY NEWS, FARM PRODUCTS (CMD) MINING, METALS (NON-PRECIOUS) (MIN)</s>
</IN>
<TEXT>

<s docid="WSJ870804-0095" num="6" wdcount="49"> The National Union of Mineworkers said an estimated 200,000 black gold and coal miners in South Africa will begin a strike Sunday night for higher wages and better working conditions, in what it said would be the largest job action ever to affect the mining industry in that nation.</s>

<s docid="WSJ870804-0095" num="7" wdcount="27"> The strike initially would cover more than half of South Africa's gold mines and about one-fifth of its coal mines, said Cyril Ramaphosa, the union's general secretary.</s>

<s docid="WSJ870804-0095" num="8" wdcount="24"> If workers in mines not included in current negotiations join in sympathy strikes, a total of 300,000 miners could be on strike, he said.</s>

<s docid="WSJ870804-0095" num="9" wdcount="13"> Gold and coal account for more than half of South Africa's foreign-currency earnings.</s>

<s docid="WSJ870804-0095" num="10" wdcount="33"> The union's announcement produced little immediate reaction on South African financial markets, where analysts said a strike had been expected and probably wouldn't have much impact unless it lasted more than a month.</s>

<s docid="WSJ870804-0095" num="11" wdcount="15"> Mine owners reportedly have been building stockpiles for several weeks in anticipation of a strike.</s>

<s docid="WSJ870804-0095" num="12" wdcount="25"> Mining companies' shares rose along with the price of gold, but the metal's rise came mainly in reaction to increased tensions in the Persian Gulf.</s>

<s docid="WSJ870804-0095" num="13" wdcount="7"> The South African rand was slightly firmer.</s>

<s docid="WSJ870804-0095" num="14" wdcount="28"> Mr. Ramaphosa said the union is demanding a 30%, across-the-board wage increase for black miners, who the union says earn an average of 225 rand ($109) a month.</s>

<s docid="WSJ870804-0095" num="15" wdcount="20"> The Chamber of Mines, which represents the nation's six biggest mining houses, says black miners earn about twice that much.</s>

<s docid="WSJ870804-0095" num="16" wdcount="11"> It implemented wage increases ranging from 15% to 23.4% last month.</s>

<s docid="WSJ870804-0095" num="17" wdcount="32"> Anglo American Corp., the huge South African mining house, warned against a strike, saying miners had received a good wage increase in July and wouldn't gain further raises by a job action.</s>

<s docid="WSJ870804-0095" num="18" wdcount="36"> But "at this stage it seems the strike seems inevitable," said Mr. Ramaphosa, who added that there hadn't been any negotiations with management since a strike ballot received "overwhelming support" during the week of July 12.</s>

<s docid="WSJ870804-0095" num="19" wdcount="25"> He also warned of possible confrontations with police, saying: "We have issued instructions to our members that if they are attacked they should defend themselves".</s>

<s docid="WSJ870804-0095" num="20" wdcount="15"> Miners' strikes in recent years have featured clashes with police, leaving dozens of people dead.</s>

<s docid="WSJ870804-0095" num="21" wdcount="21"> "The total mines that will be affected are 28 gold mines around the country and 18 collieries," the union official said.</s>

<s docid="WSJ870804-0095" num="22" wdcount="36"> "Our union is at the same time in dispute with a number of other companies, where strike action could take place at any time, should the various mine managements refuse to accede to our members' demands".</s>

<s docid="WSJ870804-0095" num="23" wdcount="16"> He said such other companies included De Beers Consolidated Mines Ltd., the world's largest diamond miner.</s>

<s docid="WSJ870804-0095" num="24" wdcount="21"> In addition to the general wage increase, Mr. Ramaphosa said the union is demanding pay for black miners doing dangerous work.</s>

<s docid="WSJ870804-0095" num="25" wdcount="26"> The black miners also are asking for 30 days' leave each year, and a paid holiday on June 16, the anniversary of the 1976 Soweto riots.</s>

<s docid="WSJ870804-0095" num="26" wdcount="14"> They also want an increase in death benefits to five years from two .</s>
</TEXT>
</DOC>
