<DOC>
<DOCNO>

<s docid="AP881106-0062" num="1" wdcount="1"> AP881106-0062</s>
</DOCNO>
<FILEID>

<s docid="AP881106-0062" num="2" wdcount="2"> AP-NR-11-06-88 1737EST</s>
</FILEID>
<FIRST>

<s docid="AP881106-0062" num="3" wdcount="6"> u a AM-NYMarathon Bjt 11-06 0516</s>
</FIRST>
<SECOND>

<s docid="AP881106-0062" num="4" wdcount="3"> AM-NY Marathon, Bjt,0532</s>
</SECOND>
<HEAD>

<s docid="AP881106-0062" num="5" wdcount="12"> Sun Shines on Crowds in Manhattan for the New York City Marathon</s>
</HEAD>
<HEAD>

<s docid="AP881106-0062" num="6" wdcount="9"> LaserPhotos NY12, NY16, NY19, NY20, NY23, LaserGraphics NY24, NY27</s>
</HEAD>
<BYLINE>

<s docid="AP881106-0062" num="7" wdcount="4"> By GEORGE P. BAYLISS</s>
</BYLINE>
<BYLINE>

<s docid="AP881106-0062" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP881106-0062" num="9" wdcount="3"> NEW YORK (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP881106-0062" num="10" wdcount="33"> Television watchers of the 19th annual New York City Marathon followed the step-by-step progress Sunday of the leaders, but many spectators on the course scanned the thousands of runners for a familar face.</s>

<s docid="AP881106-0062" num="11" wdcount="36"> The winner in the field of 23,478 _ largest ever for a marathon _ was Steve Jones of Wales, who finished in 2 hours, 8 minutes and 20 seconds, only seven seconds off the course record.</s>

<s docid="AP881106-0062" num="12" wdcount="15"> Grete Waitz of Norway won the women's division for a record ninth time in 2:28:07.</s>

<s docid="AP881106-0062" num="13" wdcount="14"> Marybeth Torpe was hoping another runner would run fast _ her boyfriend Tony Giannelli.</s>

<s docid="AP881106-0062" num="14" wdcount="31"> She and several others had staked out the corner table at a restaurant on First Avenue to get a good view of the runners as they romped off the Queensboro Bridge.</s>

<s docid="AP881106-0062" num="15" wdcount="13"> Their hopes on seeing Giannelli depended on how fast the Yonkers native ran.</s>

<s docid="AP881106-0062" num="16" wdcount="8"> ``We have to leave this table by 12:30.</s>

<s docid="AP881106-0062" num="17" wdcount="12"> The manager's kicking us out,'' said one of Giannelli's friends, Pete Koogan.</s>

<s docid="AP881106-0062" num="18" wdcount="8"> Torpe was eager for Giannelli to finish, too.</s>

<s docid="AP881106-0062" num="19" wdcount="20"> ``I'm going to ask him to marry me today,'' she said, holding up the rose she planned to give him.</s>

<s docid="AP881106-0062" num="20" wdcount="18"> Crowds cheered for the those in the lead packs and the also-rans on the warm, sunny autumn day.</s>

<s docid="AP881106-0062" num="21" wdcount="7"> Lynne Avery, a sophomore at Morristown (N.J).</s>

<s docid="AP881106-0062" num="22" wdcount="20"> High School, waited on First Avenue near 60th Street hoping to catch a glimpse of her English teacher, Robert Paciorkowski.</s>

<s docid="AP881106-0062" num="23" wdcount="10"> But she was not taking any chances on missing him.</s>

<s docid="AP881106-0062" num="24" wdcount="27"> ``Mr. Paciorkowski told us if he saw a television camera, he'd wave to us,'' Avery said _ as she held a small portable television in her hand.</s>

<s docid="AP881106-0062" num="25" wdcount="25"> All along the marathon route, volunteers handed drinks to runners, but Rick Fairlamb of Glen Rock, N.J., had prepared a special elixir of carrot juice.</s>

<s docid="AP881106-0062" num="26" wdcount="26"> He handed them out to the 50 or so runners in the ``Natural Living'' running club who passed his table at 61st Street and First Avenue.</s>

<s docid="AP881106-0062" num="27" wdcount="16"> ``Last night I went into Brooklyn and got 500 pounds of carrots from a food co-op.</s>

<s docid="AP881106-0062" num="28" wdcount="10"> We juiced them starting at 5 this morning,'' he said.</s>

<s docid="AP881106-0062" num="29" wdcount="21"> In Central Park, Richard Borrego stood on the railing with a bullhorn, waiting for his favorites in the race to pass.</s>

<s docid="AP881106-0062" num="30" wdcount="7"> He didn't have any trouble finding them.</s>

<s docid="AP881106-0062" num="31" wdcount="14"> ``I'm cheering for Grete and Steve Jones,'' Mr. Borrego said, referring to the winners.</s>

<s docid="AP881106-0062" num="32" wdcount="8"> ``They're both so courteous, full of good sportsmanship.</s>

<s docid="AP881106-0062" num="33" wdcount="5"> They always help other runners.</s>

<s docid="AP881106-0062" num="34" wdcount="7"> They never knock other runners,'' Borrego said.</s>

<s docid="AP881106-0062" num="35" wdcount="7"> ``And that's the way it should be''.</s>

<s docid="AP881106-0062" num="36" wdcount="31"> In Washington, D.C., more than 13,000 people from 23 countries and 49 states ran the Marine Corps Marathon, which offers no prize money and prides itself on being the ``people's race''.</s>

<s docid="AP881106-0062" num="37" wdcount="31"> Jim Hage, a lawyer from Lanham, Md., who had never won a major marathon, pulled away from two-time champion Brad Ingram in the last half mile to win in 2:21:58 .</s>
</TEXT>
</DOC>
