<DOC>
<DOCNO>

<s docid="FT923-8766" num="1" wdcount="1"> FT923-8766</s>
</DOCNO>
<PROFILE>

<s docid="FT923-8766" num="2" wdcount="1"> _AN-CHLBKAEWFT</s>
</PROFILE>
<DATE>

<s docid="FT923-8766" num="3" wdcount="1"> 920808</s>
</DATE>
<HEADLINE>

<s docid="FT923-8766" num="4" wdcount="27"> FT 08 AUG 92 / The Barcelona Olympics: Marathon a 'sell-out to commercialism' - Tomorrow's runners face daunting heat and a wicked finish, just for TV ratings</s>
</HEADLINE>
<BYLINE>

<s docid="FT923-8766" num="5" wdcount="3"> By NICHOLAS WOODSWORTH</s>
</BYLINE>
<TEXT>

<s docid="FT923-8766" num="6" wdcount="23"> TOMORROW evening, just before the Olympic closing ceremony, the last and one of the most prestigious events of the Games will be held.</s>

<s docid="FT923-8766" num="7" wdcount="8"> It is also without doubt the most gruelling.</s>

<s docid="FT923-8766" num="8" wdcount="29"> Run in high heat, high humidity, high pollution levels and over an extraordinary course, the Barcelona Olympic men's marathon will prove one of the most physically demanding ever run.</s>

<s docid="FT923-8766" num="9" wdcount="8"> There are lots of figures to show why.</s>

<s docid="FT923-8766" num="10" wdcount="23"> It is estimated that when the race begins in Mataro, a seaside town north of Barcelona, the temperature will be an already-uncomfortable 25`C.</s>

<s docid="FT923-8766" num="11" wdcount="23"> Towards the marathon's end, however, radiant heat thrown off by buildings could be subjecting the runners to a temperature of up to 30`C.</s>

<s docid="FT923-8766" num="12" wdcount="16"> More debilitating still, relative humidity in Barcelona in August rises as high as 80 per cent.</s>

<s docid="FT923-8766" num="13" wdcount="16"> With more than 10 kilometres still to go, most of the course is an upward run.</s>

<s docid="FT923-8766" num="14" wdcount="49"> The last 4.6km, which take the runners 60m higher still to the Olympic stadium at the top of the hill of Montjuic, has an average gradient of more than 4.5 per cent, and includes some sections of 7 per cent, equivalent in skiing terms to a steep 'red' run.</s>

<s docid="FT923-8766" num="15" wdcount="16"> But we do not need figures to convince us of the extraordinary difficulty of tomorrow's race.</s>

<s docid="FT923-8766" num="16" wdcount="29"> Last Saturday, in the Olympic stadium, I watched the final moments and aftermath of the women's marathon, begun at the same time of day and run in similar conditions.</s>

<s docid="FT923-8766" num="17" wdcount="20"> Never in any event voluntarily entered into, sporting or otherwise, have I seen such signs of physical and mental distress.</s>

<s docid="FT923-8766" num="18" wdcount="35"> The race was won by the Unified Team's Valentina Yegorova in 2 hours 32 minutes, a time considerably slower than that achieved by women on less demanding Olympic marathon courses in Los Angeles and Seoul.</s>

<s docid="FT923-8766" num="19" wdcount="38"> After her nearest competitor, Japan's Yuko Arimori, came in eight seconds later, they had the energy - between bouts of grimacing and lowering their heads to their knees - to embrace each other and smile for the cameras.</s>

<s docid="FT923-8766" num="20" wdcount="20"> It was a different story in the 'mixed zone,' the area under the stadium where athletes recover after their events.</s>

<s docid="FT923-8766" num="21" wdcount="38"> As runner after runner stumbled and limped into the room - several were brought in senseless on stretchers - the scene seemed to be populated by exhausted boat people rescued after weeks of exposure and deprivation at sea.</s>

<s docid="FT923-8766" num="22" wdcount="29"> As a photographer calmly shot off a roll of film a foot from her face, Manuela Machado of Mexico and another runner stood vomiting violently into a potted palm.</s>

<s docid="FT923-8766" num="23" wdcount="22"> Several competitors lay prone and gasping on the ground as water was poured over them; others stood hunched over, grasping their abdomens.</s>

<s docid="FT923-8766" num="24" wdcount="15"> If anyone moved at all, it was with agonised faces and the slowest of hobbles.</s>

<s docid="FT923-8766" num="25" wdcount="21"> These are not the sort of scenes likely to promote enthusiasm for marathon running or for the ideals of Olympic competition.</s>

<s docid="FT923-8766" num="26" wdcount="17"> Chris Brasher, organiser of the London marathon, was on hand to witness the suffering, and was incensed.</s>

<s docid="FT923-8766" num="27" wdcount="19"> Male marathon runners will face the same kind of problems with heat, humidity, and an over-demanding terrain, he said.</s>

<s docid="FT923-8766" num="28" wdcount="34"> In his opinion, gearing the marathon to prime-time TV viewing and having the event end at the top of a hill for the sake of stadium spectators was unjustified and a 'sell-out to commercialism.</s>

<s docid="FT923-8766" num="29" wdcount="46"> 'To put on the marathon in the late afternoon, rather than first thing in the morning (the normal practice), and then to make them run 4km up a hill is just criminal in my opinion,' said Brasher, a former Olympic gold medal athlete and noted sportswriter.</s>

<s docid="FT923-8766" num="30" wdcount="27"> I spoke to Britain's Steve Brace, winner of the Paris marathon in 1989 and 1990, the Berlin marathon last year and a competitor in the Barcelona event.</s>

<s docid="FT923-8766" num="31" wdcount="28"> He agrees that the run will be highly demanding, and while he regards Olympic marathon running as a pinnacle of his career, he is cautious about tomorrow's slog.</s>

<s docid="FT923-8766" num="32" wdcount="16"> Like almost all the athletes running tomorrow, Brace is a professional runner who specialises in marathons.</s>

<s docid="FT923-8766" num="33" wdcount="9"> He takes an objective, long-term view of his profession.</s>

<s docid="FT923-8766" num="34" wdcount="21"> As an income-earner, marathon running is an activity with liabilities and limitations, and requires business management as well as physical ability.</s>

<s docid="FT923-8766" num="35" wdcount="26"> The winner of the London marathon earns a tidy Dollars 50,000 and the New York, Boston and Japanese runs are all in the same prize-winning category.</s>

<s docid="FT923-8766" num="36" wdcount="22"> But these and less financially-rewarding events are physically debilitating, and can only be won if a competitor is in top physical shape.</s>

<s docid="FT923-8766" num="37" wdcount="17"> With their careers and financial prospects in mind, top-level runners normally only run two marathons a year.</s>

<s docid="FT923-8766" num="38" wdcount="22"> As Brace says, when you have only two pay-days out of 365, you choose, plan and train for them with great care.</s>

<s docid="FT923-8766" num="39" wdcount="5"> Brace trains extremely carefully indeed.</s>

<s docid="FT923-8766" num="40" wdcount="9"> 'Running a marathon is the easy part,' he says.</s>

<s docid="FT923-8766" num="41" wdcount="12"> 'The hard part is the lead-up to achieving the performance level required'.</s>

<s docid="FT923-8766" num="42" wdcount="18"> He starts training three months before an event by running 80 miles a week and then building progressively.</s>

<s docid="FT923-8766" num="43" wdcount="11"> For the last six weeks he runs 120 miles a week.</s>

<s docid="FT923-8766" num="44" wdcount="11"> Normally he would hope that such a routine brings a pay-off.</s>

<s docid="FT923-8766" num="45" wdcount="16"> But the Olympic marathon is an exception: the only top-level marathon that carries no prize money.</s>

<s docid="FT923-8766" num="46" wdcount="23"> Brace says that in spite of the prestige and possible financial spin-offs involved, 'it does not necessarily make sense to run to win'.</s>

<s docid="FT923-8766" num="47" wdcount="33"> Given the highly demanding nature of the course and their desire to preserve physical condition for races that do bring in money, he says, many runners will give less than their best effort.</s>

<s docid="FT923-8766" num="48" wdcount="11"> Nonetheless, there are plenty whose considerations stretch beyond the purely financial.</s>

<s docid="FT923-8766" num="49" wdcount="16"> Italian Gelindo Bordin, who came first in the 1988 Seoul Olympic marathon, is a strong contender.</s>

<s docid="FT923-8766" num="50" wdcount="10"> So is Djibouti's Ahmed Salah, who came third in Seoul.</s>

<s docid="FT923-8766" num="51" wdcount="13"> Ibrahim Hussein of Kenya and Hiromi Taniguchi of Japan are also possible winners.</s>

<s docid="FT923-8766" num="52" wdcount="18"> None of them, though, will make a molehill out of the steep and formidable ascent of Montjuic .</s>
</TEXT>
<PUB>

<s docid="FT923-8766" num="53" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT923-8766" num="54" wdcount="3"> London Page IX</s>
</PAGE>
</DOC>
