<DOC>
<DOCNO>

<s docid="LA030290-0075" num="1" wdcount="1"> LA030290-0075</s>
</DOCNO>
<DOCID>

<s docid="LA030290-0075" num="2" wdcount="1"> 183603</s>
</DOCID>
<DATE>
<P>

<s docid="LA030290-0075" num="3" wdcount="6"> March 2, 1990, Friday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA030290-0075" num="4" wdcount="9"> Sports; Part C; Page 1; Column 4; Sports Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA030290-0075" num="5" wdcount="2"> 704 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA030290-0075" num="6" wdcount="5"> HUMAN BILLBOARDS RUN IN MARATHON</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA030290-0075" num="7" wdcount="6"> By JULIE CART, TIMES STAFF WRITER</s>
</P>
</BYLINE>
<TEXT>
<P>

<s docid="LA030290-0075" num="8" wdcount="30"> Try to think of Sunday's Los Angeles Marathon less as a "happening," which it surely is; or a world-class athletic event, which it may become but is not now .</s>
</P>
<P>

<s docid="LA030290-0075" num="9" wdcount="21"> Look at it more as a moving advertising opportunity, human billboards running 26.2 miles through the city on live television .</s>
</P>
<P>

<s docid="LA030290-0075" num="10" wdcount="23"> With that kind of exposure to a potential 12 million Southern Californians, it's no wonder that in only five years the L. A.</s>

<s docid="LA030290-0075" num="11" wdcount="15"> Marathon has become the best-marketed, slickest, most modern and sponsor-driven of the world's major marathons.</s>

<s docid="LA030290-0075" num="12" wdcount="10"> It may not be an overstatement that the L. A.</s>

<s docid="LA030290-0075" num="13" wdcount="13"> Marathon is one of the country's best-marketed sports events of any kind .</s>
</P>
<P>

<s docid="LA030290-0075" num="14" wdcount="14"> Depending on your point of view, this may or may not be good news.</s>

<s docid="LA030290-0075" num="15" wdcount="32"> Massive marketing campaigns and major sponsors lining up for a seat on the money wagon do not make L. A. an elite race, give it prestige or attract the world's best runners.</s>

<s docid="LA030290-0075" num="16" wdcount="13"> However, they do generate a tremendous amount of money for all concerned .</s>
</P>
<P>

<s docid="LA030290-0075" num="17" wdcount="43"> And that may yet transform this race, if -- as marathon President Bill Burke said this week -- the total purse of $202,520 is increased by $100,000 next year and significantly more money is added for appearance fees to lure top athletes .</s>
</P>
<P>

<s docid="LA030290-0075" num="18" wdcount="7"> The lineup of commercial support is impressive.</s>

<s docid="LA030290-0075" num="19" wdcount="46"> The race has Mercedes-Benz of North America as its presenting sponsor, making it one of 10 companies that have not only paid the race organizers to be called sponsors, but have also put more money into the race either outright or by providing products and services.</s>

<s docid="LA030290-0075" num="20" wdcount="11"> Mercedes provides automobiles for the top male and female finishers .</s>
</P>
<P>

<s docid="LA030290-0075" num="21" wdcount="10"> The Times is one of the race's more generous sponsors.</s>

<s docid="LA030290-0075" num="22" wdcount="22"> According to Will Kern, director of Times special events, this year's marathon has received almost $500,000 worth of donated advertising space .</s>
</P>
<P>

<s docid="LA030290-0075" num="23" wdcount="19"> For this, the newspaper has received more than $50,000 in contributions to the Times Fund charity, Kern said .</s>
</P>
<P>

<s docid="LA030290-0075" num="24" wdcount="29"> In addition, the marathon sells its name to licensees and suppliers, who donate everything from fruit and water to the official salted snack and the official hair-growth product .</s>
</P>
<P>

<s docid="LA030290-0075" num="25" wdcount="16"> The race's marketing-oriented philosophy can be traced to Burke and marathon Vice President Marie Patrick .</s>
</P>
<P>

<s docid="LA030290-0075" num="26" wdcount="20"> "It was because of our backgrounds in business," said Patrick, who came to the marathon from sports marketing in tennis.</s>

<s docid="LA030290-0075" num="27" wdcount="6"> "We're not runners, never have been.</s>

<s docid="LA030290-0075" num="28" wdcount="12"> We knew that you have to have big dollars in the beginning.</s>

<s docid="LA030290-0075" num="29" wdcount="12"> From there you can move forward to be a major event" .</s>
</P>
<P>

<s docid="LA030290-0075" num="30" wdcount="12"> Burke and Patrick have formed a persuasive and successful recruiting team .</s>
</P>
<P>

<s docid="LA030290-0075" num="31" wdcount="11"> According to Mary Reiling, national event manager for AT&T, the L.A.</s>

<s docid="LA030290-0075" num="32" wdcount="8"> Marathon's "sponsor-friendly" approach is a big incentive .</s>
</P>
<P>

<s docid="LA030290-0075" num="33" wdcount="27"> "I've worked a lot of events with a lot of different promoters, but they are by far the most creative group I've ever seen," she said .</s>
</P>
<P>

<s docid="LA030290-0075" num="34" wdcount="27"> Mercedes-Benz, which also sponsors marathons in New York and San Francisco, likes the fact that the race gives them a foothold in their No. 1 market .</s>
</P>
<P>

<s docid="LA030290-0075" num="35" wdcount="20"> "The whole marketing approach of Bill Burke is great for sponsors," said Linda Paulmeno, manager of press relations for Mercedes-Benz.</s>

<s docid="LA030290-0075" num="36" wdcount="7"> "The whole race is very marketing-oriented" .</s>
</P>
<P>

<s docid="LA030290-0075" num="37" wdcount="18"> The race depends on sponsors for the bulk of its operating budget, which supports a year-round full-time staff.</s>

<s docid="LA030290-0075" num="38" wdcount="15"> Patrick said the cost to sponsors varies from "the mid-six-figure range to over $1 million".</s>

<s docid="LA030290-0075" num="39" wdcount="12"> The fees depend on the services and products offered by a firm.</s>

<s docid="LA030290-0075" num="40" wdcount="4"> Trade-outs are common .</s>
</P>
<P>

<s docid="LA030290-0075" num="41" wdcount="30"> The marathon receives several hundred thousand dollars from KCOP (Channel 13) for the television rights, and the race has also been sold to cable and will be covered by radio.</s>

<s docid="LA030290-0075" num="42" wdcount="8"> The sponsors also work together for mutual benefit.</s>

<s docid="LA030290-0075" num="43" wdcount="29"> For example, AT&T is buying commercial time on Channel 13's broadcast, and Channel 13 is providing updates on the AT&T Friendship Cup, an international race within the race .</s>
</P>
<P>

<s docid="LA030290-0075" num="44" wdcount="17"> In fact, television makes the race more attractive to sponsors, who figure to multiply their exposure .</s>
</P>
<P>

<s docid="LA030290-0075" num="45" wdcount="21"> Richard Lipeles, president of PacifiCare Health Systems, said sponsorship in the race helps separate his company in a congested health-care market.</s>

<s docid="LA030290-0075" num="46" wdcount="8"> Also, the company provides headbands to all runners.</s>

<s docid="LA030290-0075" num="47" wdcount="16"> "Certainly, we'd love it if every runner wore our headband during the race," he said .</s>
</P>
</TEXT>
<SUBJECT>
<P>

<s docid="LA030290-0075" num="48" wdcount="19"> RUNNING; ADVERTISING; TELEVISION BROADCASTS; LOS ANGELES MARATHON; MARATHONS; SPONSORS; MARKETING; LOS ANGELES TIMES; MERCEDES BENZ OF NORTH AMERICA INC</s>
</P>
</SUBJECT>
</DOC>
