<DOC>
<DOCNO>

<s docid="LA121090-0095" num="1" wdcount="1"> LA121090-0095</s>
</DOCNO>
<DOCID>

<s docid="LA121090-0095" num="2" wdcount="1"> 320384</s>
</DOCID>
<DATE>
<P>

<s docid="LA121090-0095" num="3" wdcount="8"> December 10, 1990, Monday, San Diego County Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA121090-0095" num="4" wdcount="9"> Sports; Part C; Page 1; Column 5; Sports Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA121090-0095" num="5" wdcount="2"> 977 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA121090-0095" num="6" wdcount="5"> THEY ARE NOVICES NO MORE;</s>
</P>
<P>

<s docid="LA121090-0095" num="7" wdcount="17"> SAN DIEGO MARATHON: MARTINEZ, SMITH, RELATIVELY NEW TO LONG-DISTANCE RUNNING, CHRISTEN A NEW COURSE WITH VICTORIES .</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA121090-0095" num="8" wdcount="7"> By KIM Q. BERKSHIRE, TIMES STAFF WRITER</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA121090-0095" num="9" wdcount="1"> OCEANSIDE</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA121090-0095" num="10" wdcount="17"> Their common ground pretty much ended when the miles of asphalt to the finish line did .</s>
</P>
<P>

<s docid="LA121090-0095" num="11" wdcount="45"> By the time most people were starting their first cup of coffee Sunday morning, Benjamin Paredez Martinez of Ecatepec, Mexico, and Kathy Smith of Newport Beach were crowned winners in the San Diego Marathon at the Oceanside pier, efforts than earned them $2,000 apiece .</s>
</P>
<P>

<s docid="LA121090-0095" num="12" wdcount="25"> The runs set records on the new North County course, but the times, even helped by warm breezes and clear, 74-degree conditions, were hardly blistering.</s>

<s docid="LA121090-0095" num="13" wdcount="19"> Martinez, 29, finished in 2 hours 19 minutes 3 seconds, 36 seconds faster than Doug Kurtis of Northville, Mich.</s>

<s docid="LA121090-0095" num="14" wdcount="14"> Smith's 2:43:05 seemed days quicker than the 2:52:12 posted by Escondido's Mindy Ireland .</s>
</P>
<P>

<s docid="LA121090-0095" num="15" wdcount="18"> In years past, the marathon's mystery often has been who the leader was, not how he got there.</s>

<s docid="LA121090-0095" num="16" wdcount="27"> Runners, often from Mexico, would register late, and race officials were at their wits end when the media screamed to know the identity of the leader .</s>
</P>
<P>

<s docid="LA121090-0095" num="17" wdcount="14"> This year, officials made sure there were no mystery men out on the course.</s>

<s docid="LA121090-0095" num="18" wdcount="36"> They knew who Martinez was, but no one was sure how he was able to practically appear out of nowhere to take the lead from Alfredo Rosas of San Pedro going into the 25-mile mark .</s>
</P>
<P>

<s docid="LA121090-0095" num="19" wdcount="9"> What Martinez did, was start out slow and deliberate.</s>

<s docid="LA121090-0095" num="20" wdcount="13"> Through an interpreter, Martinez said he started out running 5:15 or 5:20 miles.</s>

<s docid="LA121090-0095" num="21" wdcount="22"> Rosas and a pack of as many as eight came out at a pace seven to 10 seconds quicker per mile .</s>
</P>
<P>

<s docid="LA121090-0095" num="22" wdcount="21"> "I knew it would kill them, that they would never keep it up," said Martinez, who won with a 5:18-mile pace.</s>

<s docid="LA121090-0095" num="23" wdcount="11"> "I had to have patience and run from the back" .</s>
</P>
<P>

<s docid="LA121090-0095" num="24" wdcount="26"> After the 14-mile mark, the pack has already thinned to just Rosas, Danny Bustos, Doug Kurtis and Ernesto Gutierrez, who ran single file for a time.</s>

<s docid="LA121090-0095" num="25" wdcount="25"> Martinez and Martin Rodriguez Rivera held back, but Martinez soon heard a little voice that told him to move or be removed from contention .</s>
</P>
<P>

<s docid="LA121090-0095" num="26" wdcount="13"> "The first 10-15 miles, I could have been in 1,000th place," Martinez said.</s>

<s docid="LA121090-0095" num="27" wdcount="3"> "I didn't care.</s>

<s docid="LA121090-0095" num="28" wdcount="5"> Then I got worried" .</s>
</P>
<P>

<s docid="LA121090-0095" num="29" wdcount="8"> Martinez left Rivera, and started on the chase.</s>

<s docid="LA121090-0095" num="30" wdcount="29"> Since Martinez hadn't been seen earlier, it originally was thought the figure gainly ground slowly but methodically from Mile 21 to Mile 24 was San Diego's Henry Chio .</s>
</P>
<P>

<s docid="LA121090-0095" num="31" wdcount="29"> Wrong. Martinez' late kick caught Rosas, who had broken away on his own for a three-mile lead at Mile 21, cramped and been surprised at the 23-mile mark .</s>
</P>
<P>

<s docid="LA121090-0095" num="32" wdcount="16"> "I tied up, there was nothing I could do," said Rosas, who was third in 2:19.49.</s>

<s docid="LA121090-0095" num="33" wdcount="12"> "As he started closing, that's when my legs really started getting sore.</s>

<s docid="LA121090-0095" num="34" wdcount="17"> I tried to just hang on, to hang in there, but he shot ahead of me" .</s>
</P>
<P>

<s docid="LA121090-0095" num="35" wdcount="35"> Before Martinez took the lead for good -- a uphill surge at Mile 25 -- it appeared Rosas was hearing footsteps and was looking over his shoulder to see who was gaining on him .</s>
</P>
<P>

<s docid="LA121090-0095" num="36" wdcount="4"> Not so, said Rosas.</s>

<s docid="LA121090-0095" num="37" wdcount="15"> "The police on the bikes were telling me how close he was," he said .</s>
</P>
<P>

<s docid="LA121090-0095" num="38" wdcount="16"> It was the second marathon in two weeks that Kurtis, 38, has run, and almost won.</s>

<s docid="LA121090-0095" num="39" wdcount="16"> The Bangkok Marathon in November was his 13th of the year, his 112th to date .</s>
</P>
<P>

<s docid="LA121090-0095" num="40" wdcount="41"> The only recurring theme in Martinez' and Smith's backgrounds -- other than the 26.2 miles they ran -- was that they are novices at long-distance running, this was their first victory at this distance and that they are both teachers .</s>
</P>
<P>

<s docid="LA121090-0095" num="41" wdcount="19"> Martinez is a world-class biathlete who finished third at the World Duathlon Championship two weeks ago near Palm Springs.</s>

<s docid="LA121090-0095" num="42" wdcount="8"> He has run only two marathons before Sunday.</s>

<s docid="LA121090-0095" num="43" wdcount="14"> He teaches physical education in his hometown, 10-15 miles outside of Mexico City .</s>
</P>
<P>

<s docid="LA121090-0095" num="44" wdcount="17"> Smith, 24, was a 5,000- and 10,000-meter specialist at Stanford but is now focusing on longer distances.</s>

<s docid="LA121090-0095" num="45" wdcount="13"> She is a fourth- through sixth-grade teacher at College Park in Irvine .</s>
</P>
<P>

<s docid="LA121090-0095" num="46" wdcount="40"> She was holding class with reporters long before Ireland, 39, was carried into a room for mandatory drug testing -- the United States Olympic Committee Drug Testing Program randomly selected this race to administer tests to the top finishers .</s>
</P>
<P>

<s docid="LA121090-0095" num="47" wdcount="32"> "My goal was to come out here, be as low-key as possible and try to qualify for the trials," said Smith, who finished fourth last year and ran a personal-best time Sunday.</s>

<s docid="LA121090-0095" num="48" wdcount="12"> She met and beat the Olympic Trials qualifying standard of 2:45 .</s>
</P>
<P>

<s docid="LA121090-0095" num="49" wdcount="27"> Smith said she and Ireland ran together -- they even chatted -- through the 20-mile mark, until Smith got her feet working faster than her mouth .</s>
</P>
<P>

<s docid="LA121090-0095" num="50" wdcount="20"> Having run with Ireland last year in the San Diego Marathon, Smith knew a little of Ireland's racing style .</s>
</P>
<P>

<s docid="LA121090-0095" num="51" wdcount="12"> "She's really tough in the latter part of a race," Smith said.</s>

<s docid="LA121090-0095" num="52" wdcount="17"> "I wanted to hang back with her, so then she could carry me through the latter part.</s>

<s docid="LA121090-0095" num="53" wdcount="8"> She hung in pretty well with me" .</s>
</P>
<P>

<s docid="LA121090-0095" num="54" wdcount="24"> Smith earlier this year ran the Long Beach Marathon, where she finished seventh but has been concentrating on this distance for just a year.</s>

<s docid="LA121090-0095" num="55" wdcount="7"> She is getting smarter about it .</s>
</P>
<P>

<s docid="LA121090-0095" num="56" wdcount="11"> "Last year I led from Miles 13 to 22," Smith said.</s>

<s docid="LA121090-0095" num="57" wdcount="8"> "This year's it's just a matter of maturity.</s>

<s docid="LA121090-0095" num="58" wdcount="8"> And the hills were positive for me" .</s>
</P>
<P>

<s docid="LA121090-0095" num="59" wdcount="18"> Martinez said entered this event because he knew the field was weak and his chances were good .</s>
</P>
<P>

<s docid="LA121090-0095" num="60" wdcount="17"> "I knew Rosas and Kurtis were good, but it was a relatively weak field," he said .</s>
</P>
<P>

<s docid="LA121090-0095" num="61" wdcount="38"> But weak field or not, the 4,000-plus runners who participated in the event seemed to relish the experience, as all the problems the marathon has had to deal with faded as each runner crossed the finish line .</s>
</P>
<P>

<s docid="LA121090-0095" num="62" wdcount="18"> "It's a beautiful course, and this was a great marathon," one runner told race director Lynn Flanagan .</s>
</P>
<P>

<s docid="LA121090-0095" num="63" wdcount="13"> "I can't believe it went off so well," said another to a volunteer.</s>

<s docid="LA121090-0095" num="64" wdcount="13"> "You'd never know anything had happened that was at all an inconvenience" .</s>
</P>
<P>

<s docid="LA121090-0095" num="65" wdcount="24"> DeAnna Sodoma of Escondido won her first marathon wheelchair race in 2:17:52; Saul Mendoza Hernandez of Mexico won the men's division in 1:57:50 .</s>
</P>
<P>

<s docid="LA121090-0095" num="66" wdcount="22"> James Sheremeta of San Diego won the men's half marathon in 1:08:59; Jeanne Lassee-Johnson was the women's half winner in 1:16:15 .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA121090-0095" num="67" wdcount="20"> Photo, COLOR, (A1) Off and Running: It was crowded at the start of the San Diego Marathon in Oceanside Sunday.</s>

<s docid="LA121090-0095" num="68" wdcount="13"> Benjamin Paredez Martinez of Mexico and Kathy Smith of Newport Beach were winners.</s>

<s docid="LA121090-0095" num="69" wdcount="20"> DAVID McNEW / Los Angeles Times; Photo, Benjamin Paradez Martinez is the surprise winner of the 1990 San Diego Marathon.</s>

<s docid="LA121090-0095" num="70" wdcount="6"> DAVID MCNEW / Los Angeles Times</s>
</P>
</GRAPHIC>
<TYPE>
<P>

<s docid="LA121090-0095" num="71" wdcount="2"> Game Story</s>
</P>
</TYPE>
</DOC>
