<DOC>
<DOCNO>

<s docid="SJMN91-06312120" num="1" wdcount="1"> SJMN91-06312120</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06312120" num="2" wdcount="1"> 06312120</s>
</ACCESS>
<DESCRIPT>

<s docid="SJMN91-06312120" num="3" wdcount="3"> RUNNING; RACING; GUIDELINE</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06312120" num="4" wdcount="9"> TO MOST PEOPLE, marathons and vacations are mutually exclusive.</s>

<s docid="SJMN91-06312120" num="5" wdcount="31"> Vacation, according to Webster, means "freedom from any activity; rest; respite."; A marathon, says the same source, is "a footrace of 26 miles, 385 yards, run over an open course" .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06312120" num="6" wdcount="1"> Venture</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06312120" num="7" wdcount="1"> VACATION?</s>

<s docid="SJMN91-06312120" num="8" wdcount="4"> HOW 'BOUT A MARATHON?</s>
</HEADLINE>
<MEMO>

<s docid="SJMN91-06312120" num="9" wdcount="6"> Venture -- Celebrating the Active Life</s>
</MEMO>
<TEXT>

<s docid="SJMN91-06312120" num="10" wdcount="16"> But a unique subset has formed: people who like to do both at the same time.</s>

<s docid="SJMN91-06312120" num="11" wdcount="12"> And to help these folks along, companies arrange tours for marathon vacations.</s>

<s docid="SJMN91-06312120" num="12" wdcount="2"> The result?</s>

<s docid="SJMN91-06312120" num="13" wdcount="10"> Bangkok in November, London in April and Stockholm in May.</s>

<s docid="SJMN91-06312120" num="14" wdcount="25"> "Skiers have mountain ranges, tennis players have resorts, why can't a runner take a marathon vacation"? said Thorn Gilligan, president of Marathon Tours in Boston.</s>

<s docid="SJMN91-06312120" num="15" wdcount="13"> "A runner should be able to enjoy a closed city for a day.</s>

<s docid="SJMN91-06312120" num="16" wdcount="26"> It's a celebration for the sport as much as a competition."; Gilligan took 5,500 people last year on 20 tours to countries from Bermuda to Moscow.</s>

<s docid="SJMN91-06312120" num="17" wdcount="20"> In addition to air fare and hotel, runners are guaranteed spots in restricted entry races such as the London Marathon.</s>

<s docid="SJMN91-06312120" num="18" wdcount="5"> Qualifying times are not required.</s>

<s docid="SJMN91-06312120" num="19" wdcount="17"> London, the most popular European city to visit, holds the world's largest marathon (April 12 next year).</s>

<s docid="SJMN91-06312120" num="20" wdcount="3"> Berlin's race (Sept.</s>

<s docid="SJMN91-06312120" num="21" wdcount="10"> 27, 1992) has grown with the demise of the wall.</s>

<s docid="SJMN91-06312120" num="22" wdcount="38"> "Most marathons take you through cities, so you get a chance to see things you'd never see on a sightseeing bus," said Fred Lebow, president of the New York Roadrunner's Club and director of the New York Marathon.</s>

<s docid="SJMN91-06312120" num="23" wdcount="15"> Lebow has run in 32 marathons, including London, Paris, Rome, Stockholm, Iceland, Seoul and Vienna.</s>

<s docid="SJMN91-06312120" num="24" wdcount="12"> "The most exciting thing is the start of the race," he said.</s>

<s docid="SJMN91-06312120" num="25" wdcount="31"> "Each city has something unique."; The cities are different, but most marathons include a carbo-loading pasta party the night before, medical exams, a post-race celebration, commemorative T-shirts and awards to finishers.</s>

<s docid="SJMN91-06312120" num="26" wdcount="8"> Entry fees vary; Brussels is $16, Venice $40.</s>

<s docid="SJMN91-06312120" num="27" wdcount="9"> Marathon Tours includes the entry price in the package.</s>

<s docid="SJMN91-06312120" num="28" wdcount="11"> Going to Bermuda, for example, costs approximately $900 from San Francisco.</s>

<s docid="SJMN91-06312120" num="29" wdcount="36"> The price includes round-trip air fare, four days and three nights at the Grotto Bay Beach hotel (per person, based on double occupancy), full breakfasts and dinners, a welcome cocktail party and post-race parties and discounts.</s>

<s docid="SJMN91-06312120" num="30" wdcount="21"> England has similar organizations: Sports Tours International and Keith Prowse, a company that specializes in British theater, sports and concert tours.</s>

<s docid="SJMN91-06312120" num="31" wdcount="20"> But it isn't necessary to run 26.2 miles to go on a running vacation, especially if it's a family trip.</s>

<s docid="SJMN91-06312120" num="32" wdcount="17"> Some marathons, like Portland's, include additional races: a five-mile run, a five-mile walk and a kids run.</s>

<s docid="SJMN91-06312120" num="33" wdcount="9"> Tel Aviv has a half-marathon and a fun run.</s>

<s docid="SJMN91-06312120" num="34" wdcount="10"> Budapest offers a half-marathon and a mini-marathon along the Danube.</s>

<s docid="SJMN91-06312120" num="35" wdcount="11"> There are also trips that incorporate running into the sightseeing schedule.</s>

<s docid="SJMN91-06312120" num="36" wdcount="21"> Running coach Pat Savage and Hal Higdon, a senior writer for Runner's World, are taking a group to Ireland in June.</s>

<s docid="SJMN91-06312120" num="37" wdcount="22"> The eight-day trip will leave from Chicago and will include sightseeing, guided runs and a fun run from Malahide Castle to Swords.</s>

<s docid="SJMN91-06312120" num="38" wdcount="12"> "On a running vacation you plan something around running everyday," Higdon said.</s>

<s docid="SJMN91-06312120" num="39" wdcount="19"> "We know the unique scenic routes and put together special runs."; Some runs are intriguing because of current events.</s>

<s docid="SJMN91-06312120" num="40" wdcount="16"> The Tel Aviv Marathon course went past houses hit by Scud missiles during the Gulf War.</s>

<s docid="SJMN91-06312120" num="41" wdcount="8"> The Belgrade Marathon was held despite Yugoslavia's turmoil.</s>

<s docid="SJMN91-06312120" num="42" wdcount="17"> The Munich course is the same as the 1972 Olympic route and finishes in the same stadium.</s>

<s docid="SJMN91-06312120" num="43" wdcount="27"> Running 26 miles just to see a city definitely isn't for everyone, but at the very least, it's a way to kill two birds with one stone.</s>

<s docid="SJMN91-06312120" num="44" wdcount="17"> In the recent Chicago Marathon, a German man ran with a camera, snapping photos every few miles.</s>

<s docid="SJMN91-06312120" num="45" wdcount="27"> IF YOU'RE INTERESTED; If you're interested in combining a vacation and marathon, here are some firms to contact:; (box) Marathon Tours, 108 Main St., Charlestown, Mass. 02129.</s>

<s docid="SJMN91-06312120" num="46" wdcount="2"> (617) 242-7845.</s>

<s docid="SJMN91-06312120" num="47" wdcount="11"> (box) Roadrunner Tours, 2815 Lake Shore Dr., Michigan City, Ind. 46360.</s>

<s docid="SJMN91-06312120" num="48" wdcount="2"> (219) 879-0133.</s>

<s docid="SJMN91-06312120" num="49" wdcount="6"> (box) Keith Prowse, based in England.</s>

<s docid="SJMN91-06312120" num="50" wdcount="2"> (8OO) 6MY-TOUR.</s>

<s docid="SJMN91-06312120" num="51" wdcount="7"> (box) Sports Tours International, 91 Walkdon Rd.</s>

<s docid="SJMN91-06312120" num="52" wdcount="8"> , Walkdon, Worslay, Manchester M28 5DQ, United Kingdom.</s>

<s docid="SJMN91-06312120" num="53" wdcount="3"> (061) 703-8161 .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06312120" num="54" wdcount="5"> JULIE DEARDORFF, Special to Venture</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06312120" num="55" wdcount="1"> USA</s>
</COUNTRY>
<EDITION>

<s docid="SJMN91-06312120" num="56" wdcount="2"> Morning Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06312120" num="57" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06312120" num="58" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06312120" num="59" wdcount="1"> 911107</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06312120" num="60" wdcount="1"> Thursday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06312120" num="61" wdcount="1"> November</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06312120" num="62" wdcount="1"> 7G</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06312120" num="63" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06312120" num="64" wdcount="1"> WEST</s>
</REGION>
<STATE>

<s docid="SJMN91-06312120" num="65" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06312120" num="66" wdcount="1"> 691</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06312120" num="67" wdcount="5"> Thursday, November 7, 1991 00312120,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06312120" num="68" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06312120" num="69" wdcount="1"> 1</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06312120" num="70" wdcount="1"> ENG</s>
</LANGUAGE>
</DOC>
