<DOC>
<DOCNO>

<s docid="SJMN91-06105230" num="1" wdcount="1"> SJMN91-06105230</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06105230" num="2" wdcount="1"> 06105230</s>
</ACCESS>
<DESCRIPT>

<s docid="SJMN91-06105230" num="3" wdcount="5"> ROAD; RACING; CHAMPIONSHIP; BOSTON; FORECAST</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06105230" num="4" wdcount="3"> Suicide or sense?</s>

<s docid="SJMN91-06105230" num="5" wdcount="11"> The answer may decide the men's winner of Monday's Boston Marathon.</s>

<s docid="SJMN91-06105230" num="6" wdcount="9"> For the women, the story line is more personal.</s>

<s docid="SJMN91-06105230" num="7" wdcount="35"> Can Ingrid Kristiansen and Joan Benoit Samuelson, the two fastest women's marathoners in history, return to their past glory after having their second babies or is a wave of runners ready to sweep past them?</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06105230" num="8" wdcount="1"> Sports</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06105230" num="9" wdcount="10"> EARLY SPEED MAY TURN BOSTON MARATHON INTO RACE OF ATTRITION</s>
</HEADLINE>
<TEXT>

<s docid="SJMN91-06105230" num="10" wdcount="16"> And for the sentimentalists, there will be 83-year-old Johnny Kelley starting in his 60th Boston Marathon.</s>

<s docid="SJMN91-06105230" num="11" wdcount="12"> There have only been 35 editions of this race run without him.</s>

<s docid="SJMN91-06105230" num="12" wdcount="11"> The last three Boston marathons have turned into reckless speed duels.</s>

<s docid="SJMN91-06105230" num="13" wdcount="20"> They have produced five of the top 10 times and eight of the top 15 in the race's storied history.</s>

<s docid="SJMN91-06105230" num="14" wdcount="24"> They also have resulted in a race of attrition, with many of the early speedsters burning out completely or faltering in the late stages.</s>

<s docid="SJMN91-06105230" num="15" wdcount="32"> Along the historic route that begins in Hopkinton, west of Boston, and ends in Copley Square in the Back Bay section of the city, checkpoint records have fallen at an alarming rate.</s>

<s docid="SJMN91-06105230" num="16" wdcount="26"> For example, all 11 checkpoint records were shattered through the first 20 miles last year, either by Simon Robert Naali or Juma Ikangaa, both of Tanzania.</s>

<s docid="SJMN91-06105230" num="17" wdcount="2"> Neither won.</s>

<s docid="SJMN91-06105230" num="18" wdcount="19"> The winner was 1988 Olympic champion Gelindo Bordin, who outsmarted the early pacesetters by running a patient, calculating race.</s>

<s docid="SJMN91-06105230" num="19" wdcount="47"> Running alone about 200 meters behind a pack of six Africans, Bordin passed them all by 21 miles and went on to win in 2 hours, 8 minutes, 19 seconds, the second-fastest time in the race's history, behind only the 2:07:51 by Rob de Castella in 1986.</s>

<s docid="SJMN91-06105230" num="20" wdcount="7"> Ikangaa finished a distant second in 2:09:52.</s>

<s docid="SJMN91-06105230" num="21" wdcount="9"> It was his third consecutive runner-up finish in Boston.</s>

<s docid="SJMN91-06105230" num="22" wdcount="10"> Ikangaa is back again, along with several other formidable Africans.</s>

<s docid="SJMN91-06105230" num="23" wdcount="63"> They include Ibrahim Hussein of Kenya, the 1988 winner in 2:08:43, the third-fastest time in Boston and one second ahead of Ikangaa; Abebe Mekonnen of Ethiopia, the 1989 champion in 2:09:06, Boston's eighth-best time; Douglas Wakiihuri of Kenya, the 1987 world champion and 1988 Olympic silver medalist who is making his Boston debut; and Naali, the third-place finisher in the 1990 Commonwealth Games.</s>

<s docid="SJMN91-06105230" num="24" wdcount="63"> Among those chasing them will be John Treacy, the 1984 Olympic silver medalist and the third-place finisher in Boston in 1988 and 1989; Geoff Smith, the Boston winner in 1984-85; Ed Eyestone, the top-ranked U.S. marathoner; Salvador Garcia, the runner-up to Wakiihuri in last year's New York City Marathon; and Rolando Vera, who finished third in his marathon debut in Boston in 1990.</s>

<s docid="SJMN91-06105230" num="25" wdcount="10"> The women's division also is filled with many respectable entrants.</s>

<s docid="SJMN91-06105230" num="26" wdcount="42"> Foremost among them are Kristiansen, the 35-year-old Norwegian who holds the world record of 2:21:06 and won in Boston in 1986 and 1989, and Samuelson, 33, the U.S.-record holder at 2:21:21, 1984 Olympic gold medalist and Boston champion in 1979 and 1983.</s>

<s docid="SJMN91-06105230" num="27" wdcount="11"> Challenging them will be Uta Pippig, Wanda Panfil and Kim Jones.</s>

<s docid="SJMN91-06105230" num="28" wdcount="11"> Pippig finished second in Boston last year in a career-best 2:28:03.</s>

<s docid="SJMN91-06105230" num="29" wdcount="20"> Panfil won the London Marathon in 2:26:31, her personal best, and won the New York City Marathon in 1990 .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06105230" num="30" wdcount="2"> Associated Press</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06105230" num="31" wdcount="1"> USA</s>
</COUNTRY>
<CITY>

<s docid="SJMN91-06105230" num="32" wdcount="1"> Boston</s>
</CITY>
<EDITION>

<s docid="SJMN91-06105230" num="33" wdcount="2"> Morning Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06105230" num="34" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06105230" num="35" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06105230" num="36" wdcount="1"> 910414</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06105230" num="37" wdcount="1"> Sunday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06105230" num="38" wdcount="1"> April</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06105230" num="39" wdcount="1"> 16D</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06105230" num="40" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06105230" num="41" wdcount="1"> WEST</s>
</REGION>
<STATE>

<s docid="SJMN91-06105230" num="42" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06105230" num="43" wdcount="1"> 527</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06105230" num="44" wdcount="5"> Sunday April 14, 1991 00105230,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06105230" num="45" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06105230" num="46" wdcount="1"> 1</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06105230" num="47" wdcount="1"> ENG</s>
</LANGUAGE>
</DOC>
