<DOC>
<DOCNO>

<s docid="SJMN91-06171237" num="1" wdcount="1"> SJMN91-06171237</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06171237" num="2" wdcount="1"> 06171237</s>
</ACCESS>
<DESCRIPT>

<s docid="SJMN91-06171237" num="3" wdcount="6"> RUNNING; RACING; CHAMPIONSHIP; NAME; LIST; SAN-FRANCISCO</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06171237" num="4" wdcount="31"> The women's field for Sunday's San Francisco Marathon appears mighty impressive to race President Rich Nichols, who didn't have to do much coaxing to get the highly ranked women to enter.</s>

<s docid="SJMN91-06171237" num="5" wdcount="15"> "This year's women's field is interesting because most of the competitors called us," said Nichols.</s>

<s docid="SJMN91-06171237" num="6" wdcount="14"> "We didn't have to do the calling like we normally would have to" .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06171237" num="7" wdcount="1"> Sports</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06171237" num="8" wdcount="12"> ELITE FIELD ENHANCES MARATHON TOP WOMEN EAGER TO RUN IN S.F. EVENT</s>
</HEADLINE>
<TEXT>

<s docid="SJMN91-06171237" num="9" wdcount="14"> The Olympic trials, scheduled for January, have made Nichols' job much easier this year.</s>

<s docid="SJMN91-06171237" num="10" wdcount="22"> Most top-ranked U.S. women are looking for any summer-time marathon in which to run and the San Francisco version offers excellent conditions.</s>

<s docid="SJMN91-06171237" num="11" wdcount="9"> The hills of San Francisco make this marathon challenging.</s>

<s docid="SJMN91-06171237" num="12" wdcount="16"> The weather, however, makes it one of the few enticing races held from June to September.</s>

<s docid="SJMN91-06171237" num="13" wdcount="11"> Early morning temperatures range in the low 50s in late June.</s>

<s docid="SJMN91-06171237" num="14" wdcount="21"> "This is the only place in the world where you can have a marathon in the middle of summer," Nichols said.</s>

<s docid="SJMN91-06171237" num="15" wdcount="13"> Defending champ back; Last year's winner, Janis Klecker of Minnetonka, Minn., is entered.</s>

<s docid="SJMN91-06171237" num="16" wdcount="38"> The field also boasts Janine Aiello of Albuquerque, N.M. Michelle Bush-Cuke of Berrien Springs, Mich. Christine Gibbons of Elmwood, N.J. Lesley Lahane of Chestnut Hills, Mass. Julie Shea-Graw of Raleigh, N.C., and Jane Welzel of Fort Collins, Colo.</s>

<s docid="SJMN91-06171237" num="17" wdcount="11"> All seven women have run marathons under the 2-hour, 40-minute barrier.</s>

<s docid="SJMN91-06171237" num="18" wdcount="9"> Klecker turned in a 2:39:52 on the 26.2-mile course.</s>

<s docid="SJMN91-06171237" num="19" wdcount="27"> Welzel is the 1990 national champion, Gibbons has won 26 marathons, Lahane is a former cross-country national champion and Aiello twice has finished second in San Francisco.</s>

<s docid="SJMN91-06171237" num="20" wdcount="31"> A test for Shea-Graw; Shea-Graw, 32, finished third in the 1981 New York City Marathon and was consistently ranked among the top five American runners throughout most of the early '80s.</s>

<s docid="SJMN91-06171237" num="21" wdcount="21"> She was the top qualifier for the 1980 Olympics team that missed the Moscow Summer Games because of a U.S. boycott.</s>

<s docid="SJMN91-06171237" num="22" wdcount="21"> This will be Shea-Graw's first race outside of North Carolina since 1986, when she took time off to have a child.</s>

<s docid="SJMN91-06171237" num="23" wdcount="7"> "I've run some local races," Shea-Graw said.</s>

<s docid="SJMN91-06171237" num="24" wdcount="9"> "This is going to be a test for me.</s>

<s docid="SJMN91-06171237" num="25" wdcount="27"> If it goes well, then I'll up the ante and give my training the time that is needed to become competitive again."; Shea-Graw's best time is 2:30:11.</s>

<s docid="SJMN91-06171237" num="26" wdcount="13"> "I had some major injuries and wanted to have a child," Shea-Graw said.</s>

<s docid="SJMN91-06171237" num="27" wdcount="11"> "But now it's time to get on with my career" .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06171237" num="28" wdcount="6"> PEDRO GOMEZ, Mercury News Staff Writer</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06171237" num="29" wdcount="1"> USA</s>
</COUNTRY>
<EDITION>

<s docid="SJMN91-06171237" num="30" wdcount="2"> Morning Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06171237" num="31" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06171237" num="32" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06171237" num="33" wdcount="1"> 910619</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06171237" num="34" wdcount="1"> Wednesday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06171237" num="35" wdcount="1"> June</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06171237" num="36" wdcount="1"> 8F</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06171237" num="37" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06171237" num="38" wdcount="1"> WEST</s>
</REGION>
<STATE>

<s docid="SJMN91-06171237" num="39" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06171237" num="40" wdcount="1"> 403</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06171237" num="41" wdcount="5"> Wednesday June 19, 1991 00171237,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06171237" num="42" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06171237" num="43" wdcount="1"> 1</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06171237" num="44" wdcount="1"> ENG</s>
</LANGUAGE>
</DOC>
