<DOC>
<DOCNO>

<s docid="WSJ870220-0106" num="1" wdcount="1"> WSJ870220-0106</s>
</DOCNO>
<HL>

<s docid="WSJ870220-0106" num="2" wdcount="26"> Los Angeles Tries to Make Its Marathon Both a Civil Festival and a Profit Center --- By Frederick Rose Staff Reporter of The Wall Street Journal</s>
</HL>
<DD>

<s docid="WSJ870220-0106" num="3" wdcount="1"> 02/20/87</s>
</DD>
<SO>

<s docid="WSJ870220-0106" num="4" wdcount="4"> WALL STREET JOURNAL (J)</s>
</SO>
<IN>

<s docid="WSJ870220-0106" num="5" wdcount="3"> MARKETING, ADVERTISING (MKT)</s>
</IN>
<DATELINE>

<s docid="WSJ870220-0106" num="6" wdcount="2"> LOS ANGELES</s>
</DATELINE>
<TEXT>

<s docid="WSJ870220-0106" num="7" wdcount="23"> A crowd the size of a small city will squeeze past a starting line here March 1 to run 26 miles, 385 yards.</s>

<s docid="WSJ870220-0106" num="8" wdcount="17"> And cheering every step of that distance will be more than a dozen corporate sponsors and licensees.</s>

<s docid="WSJ870220-0106" num="9" wdcount="22"> Makers of cars, soda pop, sportswear, copiers, computers -- even a hospital -- have tagged their names to the Los Angeles Marathon.</s>

<s docid="WSJ870220-0106" num="10" wdcount="20"> In the promoter's words, this run is "a marketing event on legs," reflecting marathoning's growing importance in upscale product promotions.</s>

<s docid="WSJ870220-0106" num="11" wdcount="7"> Runners, it seems, are a well-heeled lot.</s>

<s docid="WSJ870220-0106" num="12" wdcount="18"> A study by Mercedes-Benz found that 42% of family heads making $40,000 a year or more jog regularly.</s>

<s docid="WSJ870220-0106" num="13" wdcount="11"> Of potential buyers showing up at Mercedes dealers, 47% are joggers.</s>

<s docid="WSJ870220-0106" num="14" wdcount="30"> With those numbers in mind, the car maker has become a sponsor of three marathons -- in New York, Boston and Los Angeles -- as well as other running races.</s>

<s docid="WSJ870220-0106" num="15" wdcount="8"> Marathons have had corporate backing for some time.</s>

<s docid="WSJ870220-0106" num="16" wdcount="15"> But Los Angeles is ahead of the pack in making distance running a commercial spectacle.</s>

<s docid="WSJ870220-0106" num="17" wdcount="45"> The city that invented the corporate-sponsored Olympics has created a marathon unlike others -- artfully dressed as an Olympic-type amateur race, but built from the ground up to make money for the closely held company that controls it -- as well as for the city.</s>

<s docid="WSJ870220-0106" num="18" wdcount="19"> "I took air and made an event," says William Burke, the founder and president of Los Angeles Marathon Inc.</s>

<s docid="WSJ870220-0106" num="19" wdcount="26"> For a man whose running days ended with his high school track team, Mr. Burke is turning a lot of heads in the world of marathoning.</s>

<s docid="WSJ870220-0106" num="20" wdcount="33"> Last year, its first time out, the Los Angeles race attracted nearly 11,000 runners -- four times the number forecast and enough to make it the third -- largest race in the U.S.</s>

<s docid="WSJ870220-0106" num="21" wdcount="23"> The event also pulled in about $4 million in cash and services from its sponsors, leaving the organizers with $370,000 in red ink.</s>

<s docid="WSJ870220-0106" num="22" wdcount="23"> This year, Mr. Burke and his partner, Marie Patrick, expect to gross about $5 million in cash and services and to break even.</s>

<s docid="WSJ870220-0106" num="23" wdcount="8"> Next year, they say, a profit is possible.</s>

<s docid="WSJ870220-0106" num="24" wdcount="8"> More than 18,000 runners are expected this year.</s>

<s docid="WSJ870220-0106" num="25" wdcount="33"> An audience of perhaps a million and a half or more will line the route, drawn in part by advertisements on 75 million Coca-Cola cans and 2,500 billboards around the Los Angeles area.</s>

<s docid="WSJ870220-0106" num="26" wdcount="17"> Marketing experts say the festive atmosphere of big crowds in the streets makes marathons attractive to sponsors.</s>

<s docid="WSJ870220-0106" num="27" wdcount="33"> For the cost of a 30-second ad on the Super Bowl, a company can sponsor a marathon and "take over a city," says Lesa Ukman, editor of Special Events Reports, a Chicago-based newsletter.</s>

<s docid="WSJ870220-0106" num="28" wdcount="18"> The Los Angeles organizers and sponsors have perhaps done more than their counterparts elsewhere to publicize the event.</s>

<s docid="WSJ870220-0106" num="29" wdcount="28"> Los Angelenos are seeing plugs for the race on millions of grocery bags, milk cartons and loaves of bread, in addition to soda cans, billboards and other sources.</s>

<s docid="WSJ870220-0106" num="30" wdcount="8"> The venerable New York Marathon is taking note.</s>

<s docid="WSJ870220-0106" num="31" wdcount="25"> The New York Road Runners Club, organizer of the race, stopped promoting the event some years ago because it had all the runners it wanted.</s>

<s docid="WSJ870220-0106" num="32" wdcount="21"> Now, Fred Lebow, the group's president, says he is encouraging sponsors to promote the race as the Los Angeles sponsors do.</s>

<s docid="WSJ870220-0106" num="33" wdcount="7"> The promotion in Los Angeles is unabashed.</s>

<s docid="WSJ870220-0106" num="34" wdcount="23"> "We tell people that if they're looking for a new way to crack the Los Angeles market, this is it," says Mr. Burke.</s>

<s docid="WSJ870220-0106" num="35" wdcount="40"> The pitch has attracted the likes of Coca-Cola Bottling Co. of Los Angeles; Vons Cos., a large supermarket chain; the Los Angeles Times; the Sears Savings Bank unit of Sears, Roebuck & Co. Eastman Kodak Co., and Tandem Computers Inc.</s>

<s docid="WSJ870220-0106" num="36" wdcount="10"> One supporter is Ellesse USA, a sportswear and shoe producer.</s>

<s docid="WSJ870220-0106" num="37" wdcount="49"> A $50,000 fee enables the company to use the marathon's name in its ads; Ellesse will spend an additional $100,000 dressing race personnel in T-shirts and warm-up suits, showing its clothes at the marathon's public "Expo" of sponsors' wares, and posting a dozen big street banners along the course.</s>

<s docid="WSJ870220-0106" num="38" wdcount="21"> The company has rented more than 500 billboards at a cut-rate price of $120,000 from Patrick Media Group, a marathon sponsor.</s>

<s docid="WSJ870220-0106" num="39" wdcount="6"> The discount, about 50%, was important.</s>

<s docid="WSJ870220-0106" num="40" wdcount="15"> "We couldn't have bought that kind of exposure normally," says Susan Cialone, Ellesse's advertising director.</s>

<s docid="WSJ870220-0106" num="41" wdcount="15"> Ellesse, which also sponsors the New York run, finds the West Coast event more freewheeling.</s>

<s docid="WSJ870220-0106" num="42" wdcount="11"> "They have let us do whatever we want," says Ms. Cialone.</s>

<s docid="WSJ870220-0106" num="43" wdcount="22"> For instance, product banners along the route -- almost impossible to arrange in New York -- are a snap in Los Angeles.</s>

<s docid="WSJ870220-0106" num="44" wdcount="10"> The city, in fact, is a partner in the race.</s>

<s docid="WSJ870220-0106" num="45" wdcount="18"> After competitive bidding, it awarded an eight-year contract to Los Angeles Marathon Inc. to put on the race.</s>

<s docid="WSJ870220-0106" num="46" wdcount="25"> The exclusive franchise calls for the race organizers this year to pay a minimum $60,000 fee or 4% of gross cash receipts to the city.</s>

<s docid="WSJ870220-0106" num="47" wdcount="16"> The organizers also will pay the cost of city services for the marathon, estimated at $100,000.</s>

<s docid="WSJ870220-0106" num="48" wdcount="24"> The race sponsors and city officials are trading freely on the good will generated by Los Angeles's role as host of the 1984 Olympics.</s>

<s docid="WSJ870220-0106" num="49" wdcount="11"> The logo of the marathon is a shield with laurel wreath.</s>

<s docid="WSJ870220-0106" num="50" wdcount="14"> Some posters show the Los Angeles Coliseum with its torch and giant Olympic symbol.</s>

<s docid="WSJ870220-0106" num="51" wdcount="10"> "The World Returns to Los Angeles," proclaims one Mercedes-Benz ad.</s>

<s docid="WSJ870220-0106" num="52" wdcount="21"> Race directors are called "commissioners," a term borrowed from the 1984 Olympic organization, in which Mr. Burke was commissioner of tennis.</s>

<s docid="WSJ870220-0106" num="53" wdcount="18"> And like the Olympics, Los Angeles Marathon Inc., portraying the race as a civic celebration, thrives on volunteers.</s>

<s docid="WSJ870220-0106" num="54" wdcount="14"> Some 7,500 people will work for free to monitor the course on race day.</s>

<s docid="WSJ870220-0106" num="55" wdcount="10"> And two-thirds of the race's office staff work without pay.</s>

<s docid="WSJ870220-0106" num="56" wdcount="13"> "I couldn't buy this," Mr. Burke says, gesturing around the crowded race headquarters.</s>

<s docid="WSJ870220-0106" num="57" wdcount="5"> Not everyone works for free.</s>

<s docid="WSJ870220-0106" num="58" wdcount="10"> Big-name runners, for instance, want to be paid a lot.</s>

<s docid="WSJ870220-0106" num="59" wdcount="7"> And here, the organizers have pinched pennies.</s>

<s docid="WSJ870220-0106" num="60" wdcount="27"> While some runners will be paid to appear, this year's field, like last year's, lacks some of the superstars who race in Boston, New York and London.</s>

<s docid="WSJ870220-0106" num="61" wdcount="19"> Grete Waitz, one of the best woman marathoners, wanted $100,000 to appear in Los Angeles; she was turned down.</s>

<s docid="WSJ870220-0106" num="62" wdcount="38"> Mr. Burke says the Australian runner Rob de Castella made it known through his agent that he wouldn't run any marathons in the spring but, for $25,000, he'd be happy to say the Los Angeles event was tempting.</s>

<s docid="WSJ870220-0106" num="63" wdcount="8"> Mr. Burke says he slammed down the phone.</s>

<s docid="WSJ870220-0106" num="64" wdcount="20"> "We won't spend extraordinary amounts of money on any single runner to the detriment of the other runners," he says.</s>

<s docid="WSJ870220-0106" num="65" wdcount="8"> Mr. de Castella's agent denies the story entirely.</s>

<s docid="WSJ870220-0106" num="66" wdcount="14"> What Los Angeles lacks in superstars, it plans to make up for in numbers.</s>

<s docid="WSJ870220-0106" num="67" wdcount="15"> This year's race may challenge New York and London as the largest marathon ever run.</s>

<s docid="WSJ870220-0106" num="68" wdcount="9"> Some 20,500 started the New York race last year.</s>

<s docid="WSJ870220-0106" num="69" wdcount="18"> Mr. Lebow, organizer of the New York event, says next year's Los Angeles Marathon will surpass that number.</s>

<s docid="WSJ870220-0106" num="70" wdcount="9"> For one sponsor, this may be a mixed blessing.</s>

<s docid="WSJ870220-0106" num="71" wdcount="21"> Orthopaedic Hospital, a not-for-profit institution whose sponsorship is part of a publicity campaign, provides emergency care stations along the marathon route.</s>

<s docid="WSJ870220-0106" num="72" wdcount="9"> Last year, one of every 20 runners needed aid.</s>

<s docid="WSJ870220-0106" num="73" wdcount="14"> Along with sprains, strains and blisters came more serious cases of exhaustion and hypothermia.</s>

<s docid="WSJ870220-0106" num="74" wdcount="12"> A spokeswoman says: "We advised 250 people to quit the race" .</s>
</TEXT>
</DOC>
