<DOC>
<DOCNO>

<s docid="WSJ910326-0090" num="1" wdcount="1"> WSJ910326-0090</s>
</DOCNO>
<DOCID>

<s docid="WSJ910326-0090" num="2" wdcount="2"> 910326-0090 .</s>
</DOCID>
<HL>

<s docid="WSJ910326-0090" num="3" wdcount="40"> He Paints Still Lifes But John Kelley, 83, Is Still on the Move --- He Lives for Boston Marathon Which He'll Be in April 15, Running His 60th Race ---- By Joseph Pereira Staff Reporter of The Wall Street Journal</s>
</HL>
<DATE>

<s docid="WSJ910326-0090" num="4" wdcount="1"> 03/26/91</s>
</DATE>
<SO>

<s docid="WSJ910326-0090" num="5" wdcount="6"> WALL STREET JOURNAL (J), PAGE A1</s>
</SO>
<IN>

<s docid="WSJ910326-0090" num="6" wdcount="11"> RECREATION, ENTERTAINMENT, TOYS, MOVIES, PHOTOGRAPHY, SPORTS (REC) ENTERTAINMENT AND LEISURE (ENT)</s>
</IN>
<LP>

<s docid="WSJ910326-0090" num="7" wdcount="21"> EAST DENNIS, Mass. -- It's 5:30 a.m., an icy rain is falling from an indigo sky, and there's a stiff northeaster.</s>

<s docid="WSJ910326-0090" num="8" wdcount="15"> This Cape Cod country road is deserted, but for the sweaty silhouette of John Kelley.</s>

<s docid="WSJ910326-0090" num="9" wdcount="43"> Bounding up a hill in his thin green Windbreaker, with sand from the beach blowing into his face, Mr. Kelley shouts over the howling gale: "This isn't too bad, you know," he says, though the wind chill factor is about 20 below .</s>
</LP>
<TEXT>

<s docid="WSJ910326-0090" num="10" wdcount="14"> Mr. Kelley is in training for the Boston Marathon -- his 60th Boston Marathon.</s>

<s docid="WSJ910326-0090" num="11" wdcount="31"> And even at the age of 83, he probably will finish ahead of a large number of the 13,000 runners expected to compete -- officially or unofficially -- on April 15.</s>

<s docid="WSJ910326-0090" num="12" wdcount="17"> Bill Rodgers, a four-time Boston Marathon winner who plans to run again this year, marvels at Mr.</s>

<s docid="WSJ910326-0090" num="13" wdcount="13"> Kelley: "It's incomprehensible that a man his age is doing what he's doing.</s>

<s docid="WSJ910326-0090" num="14" wdcount="7"> I'm struggling at the age of 43.</s>

<s docid="WSJ910326-0090" num="15" wdcount="6"> . . . This isn't golf".</s>

<s docid="WSJ910326-0090" num="16" wdcount="17"> Even the thought of running a course of 26 miles and 385 yards leaves some of Mr.</s>

<s docid="WSJ910326-0090" num="17" wdcount="5"> Kelley's rivals of yesteryear gasping.</s>

<s docid="WSJ910326-0090" num="18" wdcount="22"> "Aghast is more like it," says Leslie Pawson, 86, a three-time Boston champion who ran against Mr. Kelley half a century ago.</s>

<s docid="WSJ910326-0090" num="19" wdcount="6"> "My doctor says: `No running, whatsoever'.</s>

<s docid="WSJ910326-0090" num="20" wdcount="10"> I can't even remember when I ran my last marathon".</s>

<s docid="WSJ910326-0090" num="21" wdcount="18"> John Adelbert Kelley is a throwback to a time when marathoners did it for glory and cab fare.</s>

<s docid="WSJ910326-0090" num="22" wdcount="33"> A two-time winner in Boston (1935 and 1945) and runner-up seven times, Mr. Kelley is to be the oldest competitor in the race this year -- as he has been for 15 years.</s>

<s docid="WSJ910326-0090" num="23" wdcount="19"> Mr. Kelley is such an institution that Hopkinton, Mass., where the race begins, has made him an honorary citizen.</s>

<s docid="WSJ910326-0090" num="24" wdcount="11"> ("That means I don't have to pay taxes there," he jokes).</s>

<s docid="WSJ910326-0090" num="25" wdcount="29"> Two state troopers will run alongside the 5-foot-6, 130-pound Mr. Kelley into Boston so he won't be trampled by "groupies," as he calls them, clamoring to shake his hand.</s>

<s docid="WSJ910326-0090" num="26" wdcount="22"> Last year, five Japanese runners were waved away by the bodyguards, as they sidled up to the old celebrity during the race.</s>

<s docid="WSJ910326-0090" num="27" wdcount="17"> Recalls Suni Tomomitsu, one of the runners: "At first we thought, `Oh, wow, he's like Mafia man'.</s>

<s docid="WSJ910326-0090" num="28" wdcount="10"> Then we said, `Oh no, this is nice Johnny Kelley'.</s>

<s docid="WSJ910326-0090" num="29" wdcount="5"> In Japan, he is awesome".</s>

<s docid="WSJ910326-0090" num="30" wdcount="20"> Though he isn't the oldest person ever to enter the Boston Marathon, Mr. Kelley is the oldest to run it.</s>

<s docid="WSJ910326-0090" num="31" wdcount="17"> Peter Foley, who was born in 1859, was a regular until he was well into his 80s.</s>

<s docid="WSJ910326-0090" num="32" wdcount="5"> But he walked the course.</s>

<s docid="WSJ910326-0090" num="33" wdcount="22"> Starting at dawn (six hours before the official noon start), Mr. Foley would eventually saunter across the finish line in the moonlight.</s>

<s docid="WSJ910326-0090" num="34" wdcount="41"> Of course, Mr. Kelley -- not to be confused with the other John Kelley, who won the Boston Marathon in 1957 -- isn't the runner he was in 1935 when he won the race, in 2 hours, 32 minutes, 7 seconds.</s>

<s docid="WSJ910326-0090" num="35" wdcount="13"> His best time ever was in 1945: 2 hours, 30 minutes, 40 seconds.</s>

<s docid="WSJ910326-0090" num="36" wdcount="9"> Last year he finished in 5 hours, 5 minutes.</s>

<s docid="WSJ910326-0090" num="37" wdcount="7"> He hopes to do better in 1991.</s>

<s docid="WSJ910326-0090" num="38" wdcount="9"> "That's not a prediction, just a goal," he says.</s>

<s docid="WSJ910326-0090" num="39" wdcount="32"> When John Kelley first toed the line in 1928, George Bush wasn't yet in kindergarten, Joe DiMaggio was an unknown and Nike was the winged goddess of victory, not a running shoe.</s>

<s docid="WSJ910326-0090" num="40" wdcount="24"> In those days, Mr. Kelley recalls, he ran in black leather high-jumping shoes that he cut open at the toes with a razor blade.</s>

<s docid="WSJ910326-0090" num="41" wdcount="18"> "I would have loved to run with the worst pair of sneakers on the market today," he says.</s>

<s docid="WSJ910326-0090" num="42" wdcount="10"> Back then, the sport didn't have much of a following.</s>

<s docid="WSJ910326-0090" num="43" wdcount="24"> Today, of course, the Boston Marathon is a big deal, covered by TV from start to finish and offering $402,000 altogether in prize money.</s>

<s docid="WSJ910326-0090" num="44" wdcount="10"> "The winners get a medal and $55,000," says Mr. Kelley.</s>

<s docid="WSJ910326-0090" num="45" wdcount="7"> "I got a medal and beef stew.</s>

<s docid="WSJ910326-0090" num="46" wdcount="5"> God bless them," he adds.</s>

<s docid="WSJ910326-0090" num="47" wdcount="3"> "They deserve it".</s>

<s docid="WSJ910326-0090" num="48" wdcount="9"> The rosy-cheeked, supple Mr. Kelley is a medical wonder.</s>

<s docid="WSJ910326-0090" num="49" wdcount="19"> Each year, he visits the Cooper Clinic at the Aerobics Center in Dallas for a battery of endurance tests.</s>

<s docid="WSJ910326-0090" num="50" wdcount="17"> "Physiologically, whatever that means, I got all A's," Mr. Kelley reports of his checkup four months ago.</s>

<s docid="WSJ910326-0090" num="51" wdcount="37"> "What that means," explains Kenneth Cooper, the physician who wrote "Aerobics" and several sequels and is now at work on a book on elderly athletes, "is that Johnny has the body of a man 23 years younger.</s>

<s docid="WSJ910326-0090" num="52" wdcount="11"> He's going to be one of the stars of my book".</s>

<s docid="WSJ910326-0090" num="53" wdcount="19"> Mr. Kelley's resting pulse rate -- 60 beats a minute -- is well below the average person's 72 beats.</s>

<s docid="WSJ910326-0090" num="54" wdcount="2"> (That's good).</s>

<s docid="WSJ910326-0090" num="55" wdcount="17"> On the stress test the clinic gives, Mr. Kelley holds the endurance record for his age group.</s>

<s docid="WSJ910326-0090" num="56" wdcount="25"> A mechanic for Boston Edison Co. before he retired in 1972, Mr. Kelley started running in the evenings after work more than six decades ago.</s>

<s docid="WSJ910326-0090" num="57" wdcount="10"> His only purpose was to relax and have some fun.</s>

<s docid="WSJ910326-0090" num="58" wdcount="14"> "All day long, I did what my boss told me to do," he recalls.</s>

<s docid="WSJ910326-0090" num="59" wdcount="9"> "But when I ran at night, I felt free.</s>

<s docid="WSJ910326-0090" num="60" wdcount="6"> I ran till I was exhausted".</s>

<s docid="WSJ910326-0090" num="61" wdcount="15"> In 1928, when he was 21, he entered his first Boston Marathon but didn't finish.</s>

<s docid="WSJ910326-0090" num="62" wdcount="10"> He dropped out three-quarters of the way through the race.</s>

<s docid="WSJ910326-0090" num="63" wdcount="13"> Then, in 1933, he finished 37th in a field of about 200 runners.</s>

<s docid="WSJ910326-0090" num="64" wdcount="14"> In all the years since, he has missed the race just once, in 1967.</s>

<s docid="WSJ910326-0090" num="65" wdcount="14"> (He has competed, all told, in 112 marathons, including the 1936 and 1948 Olympics.</s>

<s docid="WSJ910326-0090" num="66" wdcount="39"> Mr. Kelley well knows the jagged course from Hopkinton to downtown Boston: The first challenge comes five miles into the race, where a set of little hills can get a psyched runner to waste energy charging up the slopes.</s>

<s docid="WSJ910326-0090" num="67" wdcount="21"> A mile and a half later, there's new reason to beware: The smells of Cavanaugh's Bakery can set off hunger pangs.</s>

<s docid="WSJ910326-0090" num="68" wdcount="9"> An Exxon station in Wellesley marks the halfway point.</s>

<s docid="WSJ910326-0090" num="69" wdcount="13"> A steep descent into Newton Lower Falls can jar a tired runner's bones.</s>

<s docid="WSJ910326-0090" num="70" wdcount="18"> Then, at the end of a long column of oak and maple trees, is Heartbreak Hill, his nemesis.</s>

<s docid="WSJ910326-0090" num="71" wdcount="9"> It cost him at least two victories, he says.</s>

<s docid="WSJ910326-0090" num="72" wdcount="13"> And finally there's the Haunted Mile, a stretch where many runners have collapsed.</s>

<s docid="WSJ910326-0090" num="73" wdcount="13"> Boston's skyline, 2 1/2 miles in the distance, can seem so far away.</s>

<s docid="WSJ910326-0090" num="74" wdcount="13"> Though still going strong, Mr. Kelley acknowledges the marathon gets tougher each year.</s>

<s docid="WSJ910326-0090" num="75" wdcount="5"> To compensate, he trains harder.</s>

<s docid="WSJ910326-0090" num="76" wdcount="12"> He used to start preparing in earnest at the end of January.</s>

<s docid="WSJ910326-0090" num="77" wdcount="38"> "In recent years, I've been in training 12 months a year," he says, though the serious stuff -- a daily one-hour run, sprints on the track and long, 2 1/2-hour runs every other week -- begins in December.</s>

<s docid="WSJ910326-0090" num="78" wdcount="29"> (He doesn't count the miles he puts in, as many long-distance runners obsessively do, but he says he wouldn't object to an estimate of about 50 miles a week).</s>

<s docid="WSJ910326-0090" num="79" wdcount="21"> Mr. Kelley always trains at 5 a.m., and alone: "It's a quiet time, no traffic; the air is fresh and sweet".</s>

<s docid="WSJ910326-0090" num="80" wdcount="3"> His routes vary.</s>

<s docid="WSJ910326-0090" num="81" wdcount="10"> In January, he prefers the frozen sands of the beach.</s>

<s docid="WSJ910326-0090" num="82" wdcount="26"> With the approach of spring, he takes to the alder and scrub-pine hills and bluffs where the sun can be seen rising over Cape Cod Bay.</s>

<s docid="WSJ910326-0090" num="83" wdcount="26"> After his morning run, he spends a couple of hours painting (still lifes and Cape Cod scenes), a hobby he took up about 25 years ago.</s>

<s docid="WSJ910326-0090" num="84" wdcount="16"> Unlike many runners, Mr. Kelley doesn't bother with stretching exercises before he runs in the morning.</s>

<s docid="WSJ910326-0090" num="85" wdcount="26"> "This is my warm up: I empty the dishwasher, I set up the coffeepot, but I don't plug it in. I set up the breakfast table.</s>

<s docid="WSJ910326-0090" num="86" wdcount="12"> Then I check the outside temperature to see what clothes to wear".</s>

<s docid="WSJ910326-0090" num="87" wdcount="27"> He and his wife, Laura, live in a two-bedroom ranch-style house here in East Dennis, with more than 350 trophies, medals and sweat-stained marathon numbers scattered about.</s>

<s docid="WSJ910326-0090" num="88" wdcount="26"> He isn't particular about brands of shoes ("I wear them all") or what he eats ("I never eat broccoli, but I love steak and ice cream").</s>

<s docid="WSJ910326-0090" num="89" wdcount="13"> Mr. Kelley aims to run till he is at least 100 years old.</s>

<s docid="WSJ910326-0090" num="90" wdcount="13"> "He's a strange man," says Laura Kelley, in awe of her husband's vigor.</s>

<s docid="WSJ910326-0090" num="91" wdcount="22"> The 82-year-old Mrs. Kelley adds, "I just try to stay in his shadow, but I have a hard time even doing that".</s>

<s docid="WSJ910326-0090" num="92" wdcount="19"> In a rare moment of reflection, Mr. Kelley explains what makes him tick: "I paint because I like it.</s>

<s docid="WSJ910326-0090" num="93" wdcount="6"> I run because I like it.</s>

<s docid="WSJ910326-0090" num="94" wdcount="16"> If for some reason I don't finish the marathon, I don't owe an apology to anyone.</s>

<s docid="WSJ910326-0090" num="95" wdcount="19"> But I'll tell you, the Boston Marathon -- with all those people waving -- is better than my birthday."</s>
</TEXT>
</DOC>
