<DOC>
<DOCNO>

<s docid="SJMN91-06237020" num="1" wdcount="1"> SJMN91-06237020</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06237020" num="2" wdcount="1"> 06237020</s>
</ACCESS>
<CAPTION>

<s docid="SJMN91-06237020" num="3" wdcount="40"> Photos (3); PHOTO: Associated Press; Yeltsin joins other members of the Russian republic's parliament in applauding Gorbachev's safe return; PHOTO: Associated Press; Gorbachev shrugs at a question from a member of the Russian legislature during a special session Friday (color).</s>

<s docid="SJMN91-06237020" num="4" wdcount="24"> PHOTO: Associated Press; Yeltsin urges Gorbachev to read aloud the minutes of a Cabinet meeting that showed the depth of the disloyalty (color) .</s>
</CAPTION>
<DESCRIPT>

<s docid="SJMN91-06237020" num="5" wdcount="6"> USSR; GOVERNMENT; END; POLITICS; ORGANIZATION; CHANGE</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06237020" num="6" wdcount="37"> With the old order of Bolshevik power and ideology in ruins, Soviet leader Mikhail Gorbachev demanded the resignation Friday of his entire government and Russian President Boris Yeltsin shut down Communist Party organizations throughout the vast republic.</s>

<s docid="SJMN91-06237020" num="7" wdcount="12"> Ministers appointed only Thursday by Gorbachev were fired and replaced Friday .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06237020" num="8" wdcount="1"> Front</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06237020" num="9" wdcount="46"> A DAY OF SWIFT DEVELOPMENTS IN USSR -- HARD-LINERS PURGED FROM TOP POSITIONS / YELTSIN SUSPENDS COMMUNIST PARTY / CRITICISM OF GORBACHEV MOUNTS / FOREIGN MINISTER BESSMERTNYKH FIRED / COMMUNIST PARTY BANNED FROM KGB YELTSIN FLEXES NEW MUSCLE IN KREMLIN HOUSECLEANING RUSSIAN LEADER KEEPS GORBACHEV HUMBLED</s>
</HEADLINE>
<MEMO>

<s docid="SJMN91-06237020" num="10" wdcount="16"> The Coup's Aftermath; See also related stories on pages 1A and 10-13A of this section .</s>
</MEMO>
<TEXT>

<s docid="SJMN91-06237020" num="11" wdcount="35"> Yeltsin, the triumphant leader of the resistance against this week's military coup, has drastically tipped the balance of power here, showing himself to be at least the political equal, if not the master, of Gorbachev.</s>

<s docid="SJMN91-06237020" num="12" wdcount="39"> In a symbol of the new order, the Russian tricolor, the banner of the anti-coup resistance, flew over the gates of the Kremlin alongside the red Soviet flag for the first time since the rise of the Bolshevik state.</s>

<s docid="SJMN91-06237020" num="13" wdcount="49"> In a joint appearance with Gorbachev in the Russian parliament, broadcast live on Soviet television, Yeltsin made it clear that the Soviet president can maintain a semblance of authority only if he agrees to share power and intensify the march toward a democratic political system and a market economy.</s>

<s docid="SJMN91-06237020" num="14" wdcount="12"> "And now for a bit of relaxation," Yeltsin said, interrupting Gorbachev's speech.</s>

<s docid="SJMN91-06237020" num="15" wdcount="37"> "Let me sign a decree suspending the activity of the Russian Communist Party."; Gorbachev, who has insisted the party is still capable of reform, stammered a bit and then said, "Boris Nikolayevich, Boris Nikolayevich . . ".</s>

<s docid="SJMN91-06237020" num="16" wdcount="10"> With an expression that was half-smile, half-sneer, Yeltsin broke in.</s>

<s docid="SJMN91-06237020" num="17" wdcount="15"> "It's been signed," he said definitively, and the deputies broke out in cheering and applause.</s>

<s docid="SJMN91-06237020" num="18" wdcount="13"> Gorbachev struggled to explain his own position, but he seemed at a loss.</s>

<s docid="SJMN91-06237020" num="19" wdcount="44"> Yeltsin, who clearly relished his emotional and political control of the parliament session, also played a critical role in selecting the new heads of the KGB, the Defense Ministry and the Interior Ministry police, which until now have been bastions of opposition to reform.</s>

<s docid="SJMN91-06237020" num="20" wdcount="21"> Flouting protocol, Yeltsin was the first to announce the appointments while speaking at a mass rally Friday morning outside KGB headquarters.</s>

<s docid="SJMN91-06237020" num="21" wdcount="34"> New appointees; Former Interior Minister Vadim Bakatin will head the KGB, Gen. Yevgeny Shaposhnikov, the air force chief, becomes defense minister and former Russian Interior Minister Victor Barannikov will be the union's interior minister.</s>

<s docid="SJMN91-06237020" num="22" wdcount="24"> All three men took a clear stand against the coup and are expected to move quickly to reform the key institutions they now head.</s>

<s docid="SJMN91-06237020" num="23" wdcount="8"> Gorbachev also fired Alexander Bessmertnykh as foreign minister.</s>

<s docid="SJMN91-06237020" num="24" wdcount="89"> Although Bessmertnykh said he had refused to go along with the coup leaders, Gorbachev said he had information that his top diplomat had been "maneuvering, or at least did not take a firm stand."; Bessmertnykh reacted with "bitterness," according to the Tass news agency, and claimed that he had refused to join the conservative uprising, even though coup leader and former KGB chief Vladimir Kryuchkov had told him, "We need a liberal among us."; In both Moscow and Leningrad, city officials ordered police to seal off Communist Party headquarters.</s>

<s docid="SJMN91-06237020" num="25" wdcount="27"> Moscow Mayor Gavril Popov said investigators had to make a thorough search of party buildings and documents to determine the scope of the coup and its participants.</s>

<s docid="SJMN91-06237020" num="26" wdcount="28"> Across the country, Communist Party leaders who opposed the coup quit their party posts, and some who supported it, such as Latvian party leader Alfred Rubiks, were arrested.</s>

<s docid="SJMN91-06237020" num="27" wdcount="22"> The leader of the Russian Orthodox Church, Patriarch Alexei II, said the coup meant the end of communist ideology in the country.</s>

<s docid="SJMN91-06237020" num="28" wdcount="6"> "God has saved Russia," he declared.</s>

<s docid="SJMN91-06237020" num="29" wdcount="52"> As Gorbachev struggled during the 90-minute session of the Russian parliament, he called for "maturity and balance" in judging the conspirators and said, "Let's not have a witch hunt."; Greeted by protesters; From the moment that protesters outside the Russian parliament building greeted the arrival of Gorbachev's limousine with shouts of "Resign!</s>

<s docid="SJMN91-06237020" num="30" wdcount="26"> Resign"! it was clear that the Soviet president was not about to get a warm homecoming from those who played a key role in rescuing him.</s>

<s docid="SJMN91-06237020" num="31" wdcount="13"> The Russian deputies -- and Yeltsin especially -- were alternately sarcastic and aggressive.</s>

<s docid="SJMN91-06237020" num="32" wdcount="20"> When Gorbachev had trouble at one point explaining one development in the coup, Yeltsin broke in like an exasperated schoolmaster.</s>

<s docid="SJMN91-06237020" num="33" wdcount="7"> "Sometimes Mikhail Sergeyevich forgets things," he said.</s>

<s docid="SJMN91-06237020" num="34" wdcount="22"> Yeltsin also seemed eager to impress on Gorbachev just how thoroughly he had been betrayed by his own ministers and presumed allies.</s>

<s docid="SJMN91-06237020" num="35" wdcount="50"> He handed Gorbachev the minutes of a closed Council of Ministers meeting held last Monday during which all of the more than 20 ministers present -- with one or two exceptions -- supported the coup and the State Committee for the State of Emergency set up by the putsch leaders.</s>

<s docid="SJMN91-06237020" num="36" wdcount="15"> "I haven't read this yet," said Gorbachev in an attempt to put off the matter.</s>

<s docid="SJMN91-06237020" num="37" wdcount="4"> "Go ahead," Yeltsin insisted.</s>

<s docid="SJMN91-06237020" num="38" wdcount="32"> "Read it now."; And Gorbachev did, reeling off the names of all of the ministers who had for so long mouthed the slogans of reform and then stabbed him in the back.</s>

<s docid="SJMN91-06237020" num="39" wdcount="17"> "This whole government has got to resign," Gorbachev said with a degree of despair in his voice.</s>

<s docid="SJMN91-06237020" num="40" wdcount="31"> "I must say this has been a great drama for me, a severe trial."; Retribution for Yeltsin; Yeltsin seemed to take extraordinary relish in this Shakespearean drama of betrayal and retribution.</s>

<s docid="SJMN91-06237020" num="41" wdcount="25"> It had been Gorbachev who ordered Yeltsin out of a hospital bed in 1987 to face a vengeful meeting of the Moscow Communist Party Committee.</s>

<s docid="SJMN91-06237020" num="42" wdcount="24"> At that session, one speaker after another attacked Yeltsin for "political immaturity" and other sins for daring to criticize the party and its Politburo.</s>

<s docid="SJMN91-06237020" num="43" wdcount="23"> And it was Gorbachev in 1990 who came to the Russian parliament to call on deputies to vote against Yeltsin as their chairman.</s>

<s docid="SJMN91-06237020" num="44" wdcount="49"> Although this seemingly endless political saga of two reformers who can only struggle to find a common language seemed at an end this spring when they began negotiations on a new Union Treaty, it is clear that their relationship will likely remain the great floating opera of Soviet politics.</s>

<s docid="SJMN91-06237020" num="45" wdcount="16"> Gorbachev said he and Yeltsin had also agreed to assume each other's duties in an emergency.</s>

<s docid="SJMN91-06237020" num="46" wdcount="30"> "If one or another gets in the situation when he cannot even give orders, like what happened now, his rights and responsibilities are automatically taken by the other," Gorbachev said.</s>

<s docid="SJMN91-06237020" num="47" wdcount="19"> It appeared that the move would have to be temporary and could be made permanent only with legislative consent.</s>

<s docid="SJMN91-06237020" num="48" wdcount="8"> Soviet law makes the vice president the next-in-line.</s>

<s docid="SJMN91-06237020" num="49" wdcount="13"> Gennady Yanayev invoked that law in the coup while declaring Gorbachev physically incapacitated.</s>

<s docid="SJMN91-06237020" num="50" wdcount="10"> The conspirators themselves are now in jail and facing interrogation.</s>

<s docid="SJMN91-06237020" num="51" wdcount="44"> Gorbachev said the leaders of the junta "tried to turn us all into chopped meat" and they should be prosecuted without "hesitation or forgiveness."; Soviet Prime Minister Valetin Pavlov has been arrested for helping to lead the coup, Soviet and Russian television reported today.</s>

<s docid="SJMN91-06237020" num="52" wdcount="28"> Pavlov was one of the eight officials in the committee that ousted Gorbachev from power, but he was reportedly taken ill on Sunday night when the coup began.</s>

<s docid="SJMN91-06237020" num="53" wdcount="14"> He has been under police guard in a hospital since Gorbachev regained power Wednesday.</s>

<s docid="SJMN91-06237020" num="54" wdcount="14"> Speculation of guilt also turned on another key figure in the old Gorbachev government.</s>

<s docid="SJMN91-06237020" num="55" wdcount="24"> According to Yeltsin, Supreme Soviet Chairman Anatoly Lukyanov has been ousted for taking part in the coup, but that has not been confirmed .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06237020" num="56" wdcount="4"> DAVID REMNICK, Washington Post</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06237020" num="57" wdcount="1"> USA</s>
</COUNTRY>
<CITY>

<s docid="SJMN91-06237020" num="58" wdcount="1"> Moscow</s>
</CITY>
<EDITION>

<s docid="SJMN91-06237020" num="59" wdcount="2"> Morning Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06237020" num="60" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06237020" num="61" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06237020" num="62" wdcount="1"> 910824</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06237020" num="63" wdcount="1"> Saturday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06237020" num="64" wdcount="1"> August</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06237020" num="65" wdcount="1"> 1A</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06237020" num="66" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06237020" num="67" wdcount="1"> WEST</s>
</REGION>
<FEATURE>

<s docid="SJMN91-06237020" num="68" wdcount="1"> PHOTO</s>
</FEATURE>
<STATE>

<s docid="SJMN91-06237020" num="69" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06237020" num="70" wdcount="1"> 1,271</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06237020" num="71" wdcount="5"> Saturday, August 24, 1991 00237020,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06237020" num="72" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06237020" num="73" wdcount="1"> 0</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06237020" num="74" wdcount="2"> ENG FRONT</s>
</LANGUAGE>
</DOC>
