<DOC>
<DOCNO>

<s docid="SJMN91-06234209" num="1" wdcount="1"> SJMN91-06234209</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06234209" num="2" wdcount="1"> 06234209</s>
</ACCESS>
<CAPTION>

<s docid="SJMN91-06234209" num="3" wdcount="71"> Photos (4); PHOTO: Michael Rondou -- Mercury News; A Soviet army lieutenant colonel waves white flag of surrender as he walks ahead of coup protesters today (color); PHOTO: Associated Press; Yeltsin led the coup resistance (color); PHOTO: Associated Press; Thousands huddle under umbrellas today as they listen to Yeltsin tell Russian parliament of coup leaders' failure; PHOTO: Associated Press; Tank convoy on outskirts of Moscow withdrew today after the coup failed</s>
</CAPTION>
<DESCRIPT>

<s docid="SJMN91-06234209" num="4" wdcount="7"> USSR; GOVERNMENT; CHANGE; ATTEMPT; END; PRESIDENT; MOSCOW</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06234209" num="5" wdcount="27"> Soviet President Mikhail Gorbachev was prepared to head back to Moscow today to reclaim power after the hard-line coup against him collapsed and its leaders reportedly fled.</s>

<s docid="SJMN91-06234209" num="6" wdcount="25"> Outside the Russian parliament, which served as the headquarters for resistance led by Boris Yeltsin, rejoicing crowds cheered and waved flags as the coup ended.</s>

<s docid="SJMN91-06234209" num="7" wdcount="12"> Soldiers, their withdrawing tanks strewed with flowers, waved at television cameras .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06234209" num="8" wdcount="1"> Front</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06234209" num="9" wdcount="9"> GORBACHEV BACK; COUP COLLAPSES JUBILANT MOSCOW AWAITS HIS RETURN</s>
</HEADLINE>
<MEMO>

<s docid="SJMN91-06234209" num="10" wdcount="14"> SOVIET UPHEAVAL; See also related articles on pages 1A, 12A-16A of this section .</s>
</MEMO>
<TEXT>

<s docid="SJMN91-06234209" num="11" wdcount="35"> Gorbachev was set to board a plane in the Crimea, where he was vacationing at the time of Monday's coup, for the two-hour flight to Moscow, said a deputy to Russian Defense Minister Konstantin Kobets.</s>

<s docid="SJMN91-06234209" num="12" wdcount="13"> Earlier reports that the plane had already taken off were incorrect, officials said.</s>

<s docid="SJMN91-06234209" num="13" wdcount="31"> The Soviet leader, in a statement for radio and television, said he was fully in command of the situation and that the coup leaders would bear "full responsibility" for their actions.</s>

<s docid="SJMN91-06234209" num="14" wdcount="75"> In the United States, President Bush hailed Gorbachev's return to power and said the coup leaders had "underestimated the power of the people, underestimated what a taste of freedom and democracy brings."; The three-day coup, one of the most tumultuous developments in recent Soviet history, unraveled in a series of swift and dramatic developments today:; (check) Tanks and armored personnel carriers moved away from the Russian parliament, scene of the worst violence of the coup.</s>

<s docid="SJMN91-06234209" num="15" wdcount="12"> A 2 1/2-milelong column of tanks and trucks headed out of Moscow.</s>

<s docid="SJMN91-06234209" num="16" wdcount="10"> (check) The leaders of the national legislature demanded Gorbachev's reinstatement.</s>

<s docid="SJMN91-06234209" num="17" wdcount="9"> The full legislature nullified the coup leaders' emergency decrees.</s>

<s docid="SJMN91-06234209" num="18" wdcount="5"> (check) Press restrictions were lifted.</s>

<s docid="SJMN91-06234209" num="19" wdcount="28"> "I'm sorry, comrades, but I'm very excited"! said a Soviet TV announcer, grinning broadly after he was allowed for the first time to criticize the coup leaders' actions.</s>

<s docid="SJMN91-06234209" num="20" wdcount="14"> (check) The Communist Party, apparently seeking to salvage its own image, denounced the takeover.</s>

<s docid="SJMN91-06234209" num="21" wdcount="24"> (check) In the secessionist Baltic republics, which had borne the brunt of the post-coup crackdown, some Soviet troops began returning to their permanent bases.</s>

<s docid="SJMN91-06234209" num="22" wdcount="13"> Latvia joined neighbor Estonia today in declaring immediate independence from the Soviet Union.</s>

<s docid="SJMN91-06234209" num="23" wdcount="41"> The coup's failure could deal a fatal blow to organized, high-level efforts to thwart reform drives in the Soviet Union by Gorbachev and Yeltsin and significantly alter the balance of power that has characterized Soviet power for the six-year Gorbachev era.</s>

<s docid="SJMN91-06234209" num="24" wdcount="11"> The country's future course depends, however, on who remains in power.</s>

<s docid="SJMN91-06234209" num="25" wdcount="16"> Although Yeltsin supported Gorbachev during the coup, the two men maintain different approaches to Soviet reforms.</s>

<s docid="SJMN91-06234209" num="26" wdcount="78"> Yeltsin addressed the Russian parliament today and said the Soviet Union had just "gone through a most tragic moment in its history, and perhaps the most tragic moment."; Gorbachev's foreign minister, Alexander Bessmertnykh, who had dropped out of sight during the coup, reappeared today and called the takeover a page in Soviet history that "has got to be turned."; The national legislature invalidated all decrees made by the coup leaders, national lawmaker Yuri Karyakin told the Russian legislature.</s>

<s docid="SJMN91-06234209" num="27" wdcount="11"> Karyakin said the legislature's executive council demanded Gorbachev's return to power.</s>

<s docid="SJMN91-06234209" num="28" wdcount="13"> With the coup's demise, the Communist Party moved to salvage its own credibility.</s>

<s docid="SJMN91-06234209" num="29" wdcount="20"> It called the takeover unconstitutional and demanded a meeting with Gorbachev, the party chief, the official news agency Tass said.</s>

<s docid="SJMN91-06234209" num="30" wdcount="9"> The party renounced any connection with the coup leaders.</s>

<s docid="SJMN91-06234209" num="31" wdcount="25"> Thousands of people had kept up their vigil at the Russian parliament building after overnight clashes with Soviet troops that left at least four dead.</s>

<s docid="SJMN91-06234209" num="32" wdcount="14"> They cheered when the announcement of the coup committee's departure came over a loudspeaker.</s>

<s docid="SJMN91-06234209" num="33" wdcount="29"> "This shows the strength of our democracy," said Leonid Abramtsov, who was marching with a band of teen-agers waving the red, white and sky-blue flag of the Russian republic.</s>

<s docid="SJMN91-06234209" num="34" wdcount="37"> The plane reportedly carrying the coup leaders was said to be headed to the city of Bishkek, formerly called Frunze, the capital of Kirgizia, 2,100 miles southeast of Moscow, according to Radio Russia, which speaks for Yeltsin.</s>

<s docid="SJMN91-06234209" num="35" wdcount="13"> It was not immediately known why the coup leaders would travel to Kirgizia.</s>

<s docid="SJMN91-06234209" num="36" wdcount="26"> But sources at the airport told the Associated Press that only KGB chief Vladimir Kryuchkov was on a plane, and it was headed to the Crimea.</s>

<s docid="SJMN91-06234209" num="37" wdcount="12"> He reportedly was accompanied by Communist Party No. 2 leader Vladimir Ivashko.</s>

<s docid="SJMN91-06234209" num="38" wdcount="23"> The republic-run Russian Information Agency said Vice President Gennady Yanayev, the nominal head of the coup committee, was still in his Kremlin office.</s>

<s docid="SJMN91-06234209" num="39" wdcount="14"> The report could not be independently confirmed, and the discrepancies could not be clarified.</s>

<s docid="SJMN91-06234209" num="40" wdcount="34"> Despite the force brought to bear by the coup leaders, they were unable to dislodge Yeltsin from the Russian parliament, where he rallied the opposition, to enforce the curfew, or prevent large demonstrations nationwide.</s>

<s docid="SJMN91-06234209" num="41" wdcount="21"> The state of emergency was declared after hard-line elements in the military and Communist Party ousted Gorbachev, declaring he was ill.</s>

<s docid="SJMN91-06234209" num="42" wdcount="22"> The junta had seemed unable to cope with tens of thousands of people who erected barricades around Yeltsin's stronghold in the parliament.</s>

<s docid="SJMN91-06234209" num="43" wdcount="22"> There were also huge anti-coup demonstrations in Moscow, Leningrad, Kishiniev and other cities, as well as strikes by coal miners in Siberia.</s>

<s docid="SJMN91-06234209" num="44" wdcount="19"> Early today, before the coup fell apart, columns of tanks and armored personnel carriers had moved around central Moscow.</s>

<s docid="SJMN91-06234209" num="45" wdcount="22"> One patrol of the armored vehicles was trapped by furious demonstrators just after midnight as it tried to break through a barricade.</s>

<s docid="SJMN91-06234209" num="46" wdcount="26"> Two people were confirmed shot or crushed to death as the vehicles tried to fight their way through, and witnesses said a third person was killed.</s>

<s docid="SJMN91-06234209" num="47" wdcount="26"> A Russian republic official, Col. Viktor Samailov, told the independent news agency Interfax that four people were shot or crushed to death in the clash .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06234209" num="48" wdcount="2"> Associated Press</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06234209" num="49" wdcount="1"> USA</s>
</COUNTRY>
<CITY>

<s docid="SJMN91-06234209" num="50" wdcount="1"> Moscow</s>
</CITY>
<EDITION>

<s docid="SJMN91-06234209" num="51" wdcount="2"> Stock Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06234209" num="52" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06234209" num="53" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06234209" num="54" wdcount="1"> 910821</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06234209" num="55" wdcount="1"> Wednesday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06234209" num="56" wdcount="1"> August</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06234209" num="57" wdcount="1"> 1A</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06234209" num="58" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06234209" num="59" wdcount="1"> WEST</s>
</REGION>
<FEATURE>

<s docid="SJMN91-06234209" num="60" wdcount="1"> PHOTO</s>
</FEATURE>
<STATE>

<s docid="SJMN91-06234209" num="61" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06234209" num="62" wdcount="1"> 1,011</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06234209" num="63" wdcount="5"> Wednesday, August 21, 1991 00234209,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06234209" num="64" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06234209" num="65" wdcount="1"> 0</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06234209" num="66" wdcount="2"> ENG FRONT</s>
</LANGUAGE>
</DOC>
