<DOC>
<DOCNO>

<s docid="SJMN91-06235179" num="1" wdcount="1"> SJMN91-06235179</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06235179" num="2" wdcount="1"> 06235179</s>
</ACCESS>
<CAPTION>

<s docid="SJMN91-06235179" num="3" wdcount="6"> Drawing; DRAWING: Mercury News; (Soviet Time)</s>
</CAPTION>
<DESCRIPT>

<s docid="SJMN91-06235179" num="4" wdcount="7"> USSR; GOVERNMENT; CHANGE; ATTEMPT; US; RESEARCH; ANALYSIS</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06235179" num="5" wdcount="59"> A week before the Soviet coup, U.S. intelligence officials warned the White House of "a real possibility" that hard-liners in the KGB or the Soviet military might act to block the scheduled signing of the new Union Treaty, senior government officials said Wednesday, but they acknowledged they knew too little about such plans to enable President Bush to act.</s>

<s docid="SJMN91-06235179" num="6" wdcount="21"> The treaty, which reduces Moscow's centralized control and strengthens powers of the Soviet Union's 15 republics, is anathema to Soviet conservatives.</s>

<s docid="SJMN91-06235179" num="7" wdcount="28"> And U.S. analysts monitoring Soviet troop movements concluded six months to a year ago that right-wing officials had started embryonic plans for a coup, the officials said .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06235179" num="8" wdcount="1"> Front</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06235179" num="9" wdcount="1"> U.S.</s>

<s docid="SJMN91-06235179" num="10" wdcount="8"> INTELLIGENCE TOLD BUSH OF SIGNS OF IMPENDING COUP</s>
</HEADLINE>
<MEMO>

<s docid="SJMN91-06235179" num="11" wdcount="3"> THE COUP'S AFTERMATH</s>
</MEMO>
<TEXT>

<s docid="SJMN91-06235179" num="12" wdcount="32"> As soon as the hard-liners made their move Sunday night -- two days before Gorbachev was to sign the treaty -- it was obvious the coup was doomed to failure, they said.</s>

<s docid="SJMN91-06235179" num="13" wdcount="30"> One result of the bungled coup is that Soviet President Mikhail Gorbachev -- even though reinstated as head of state -- "could be irrelevant" to what happens next, analysts said.</s>

<s docid="SJMN91-06235179" num="14" wdcount="17"> Even before Gorbachev returned to Moscow, they predicted his future would be limited to a figurehead role.</s>

<s docid="SJMN91-06235179" num="15" wdcount="8"> "He lost by being peripheral to what happened.</s>

<s docid="SJMN91-06235179" num="16" wdcount="16"> No one really came to Gorbachev's assistance as leader of the country," one U.S. official said.</s>

<s docid="SJMN91-06235179" num="17" wdcount="34"> Instead, opposition to the coup was based on "the illegality of the principle" of usurping power and widespread fear that if Gorbachev could be "rolled up," then other democratically elected leaders could be, too.</s>

<s docid="SJMN91-06235179" num="18" wdcount="53"> In the aftermath of the coup, analysts also predicted that:; (check) Major constraints on Soviet cooperation with the West, such as the military's disaffection with Gorbachev's support of Bush's strategy during the Persian Gulf war, will now be greatly weakened or removed, although "a benign" Soviet Union cannot be assumed in every case.</s>

<s docid="SJMN91-06235179" num="19" wdcount="50"> (check) The coup's abrupt end opened the way for faster democratic reforms, but it will not now "create Jeffersonian democracy -- or maybe ever."; (check) The Communist Party is "dead" and will no longer be a political force, although most of the country's bureaucrats are current or former party members.</s>

<s docid="SJMN91-06235179" num="20" wdcount="15"> (check) Gorbachev is likely to abandon the party and move more aggressively toward reform .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06235179" num="21" wdcount="3"> Los Angeles Times</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06235179" num="22" wdcount="1"> USA</s>
</COUNTRY>
<CITY>

<s docid="SJMN91-06235179" num="23" wdcount="1"> WASHINGTON</s>
</CITY>
<EDITION>

<s docid="SJMN91-06235179" num="24" wdcount="2"> Morning Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06235179" num="25" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06235179" num="26" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06235179" num="27" wdcount="1"> 910822</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06235179" num="28" wdcount="1"> Thursday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06235179" num="29" wdcount="1"> August</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06235179" num="30" wdcount="1"> 16A</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06235179" num="31" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06235179" num="32" wdcount="1"> WEST</s>
</REGION>
<FEATURE>

<s docid="SJMN91-06235179" num="33" wdcount="1"> DRAWING</s>
</FEATURE>
<STATE>

<s docid="SJMN91-06235179" num="34" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06235179" num="35" wdcount="1"> 368</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06235179" num="36" wdcount="5"> Thursday, August 22, 1991 00235179,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06235179" num="37" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06235179" num="38" wdcount="1"> 1</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06235179" num="39" wdcount="1"> ENG</s>
</LANGUAGE>
</DOC>
