<DOC>
<DOCNO>

<s docid="SJMN91-06235097" num="1" wdcount="1"> SJMN91-06235097</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06235097" num="2" wdcount="1"> 06235097</s>
</ACCESS>
<CAPTION>

<s docid="SJMN91-06235097" num="3" wdcount="27"> Photos (4); PHOTO: Associated Press; BACK IN ACTION -- Mikhail Gorbachev, in his first public address since defeat of the coup, speaks live on Soviet television today.</s>

<s docid="SJMN91-06235097" num="4" wdcount="10"> This is a TV image transmitted by a U.S. network.</s>

<s docid="SJMN91-06235097" num="5" wdcount="32"> PHOTO: (Yeltsin) (Color); PHOTO: (Gorbachev) (Color); PHOTO: Michael Rondou -- Mercury News; A happy man in Moscow today embraces and whispers to a tank officer whose crews sided with coup opponents (Color)</s>
</CAPTION>
<DESCRIPT>

<s docid="SJMN91-06235097" num="6" wdcount="7"> USSR; LEADER; OPPOSE; GOVERNMENT; ASSAULT; MEETING; MOSCOW</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06235097" num="7" wdcount="35"> President Mikhail Gorbachev today furiously denounced the "crude and crafty" plotters who briefly overthrew him but said the failed power grab by hard-liners could prove to be an "enormous opportunity" to further his democratic reforms.</s>

<s docid="SJMN91-06235097" num="8" wdcount="36"> Gorbachev, moving to tighten his newly regained grip on power and punish the coup leaders, declared at a news conference that the Soviet Union had survived "the most difficult trial" of his six-year-old reform movement .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06235097" num="9" wdcount="1"> Front</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06235097" num="10" wdcount="18"> THE VICTOR GORBACHEV MOVES AGAINST FOES AND THE HERO YELTSIN LEADS RED SQUARE RALLY PLOTTERS DENOUNCED AS 'CRUDE'</s>
</HEADLINE>
<MEMO>

<s docid="SJMN91-06235097" num="11" wdcount="19"> The coup's aftermath; See also related article on page 1A, 16A, 17A, 18A, 19A, 20A of this section .</s>
</MEMO>
<TEXT>

<s docid="SJMN91-06235097" num="12" wdcount="49"> At the news conference -- Gorbachev's first since the coup against him collapsed on Wednesday -- the 60-year-old leader condemned the takeover as being against "the people, against democracy."; Earlier, he told reporters he would have killed himself rather than submit to any forced arrangement with the coup leaders.</s>

<s docid="SJMN91-06235097" num="13" wdcount="10"> "I said I wouldn't make any deals," he said then.</s>

<s docid="SJMN91-06235097" num="14" wdcount="20"> "Otherwise, I would have had to commit suicide."; Gorbachev detailed his purge of coup leaders, including Defense Minister Dmitri Yazov.</s>

<s docid="SJMN91-06235097" num="15" wdcount="48"> He named a new acting KGB chief, interior minister and defense minister, and said he would do everything to "drive out the reactionary forces from the Communist Party."; Gorbachev pledged cooperation with Russian republic President Boris Yeltsin but said he had no plans to leave the Communist Party.</s>

<s docid="SJMN91-06235097" num="16" wdcount="7"> "I am convinced that socialism is correct.</s>

<s docid="SJMN91-06235097" num="17" wdcount="55"> I am an adherent of socialism."; When asked if Yeltsin now had more power than he did, Gorbachev said, "We have been bound together by the situation."; Looking and sounding angry, he described the plotters as "primitive and crude and crafty" and scoffed at their announcement that he had stepped aside because he was ill.</s>

<s docid="SJMN91-06235097" num="18" wdcount="10"> "Their hands were shaking the whole time," he said derisively.</s>

<s docid="SJMN91-06235097" num="19" wdcount="23"> Despite his display of anger, the Soviet president said the failure of the coup could ultimately help ensure the continuation of his reforms.</s>

<s docid="SJMN91-06235097" num="20" wdcount="11"> "We have to see this as an enormous opportunity," he said.</s>

<s docid="SJMN91-06235097" num="21" wdcount="31"> At his news conference, Gorbachev made a point of publicly praising Yeltsin, whose folk-hero stature was enhanced during the coup as he rallied hundreds of thousands of his supporters to resist.</s>

<s docid="SJMN91-06235097" num="22" wdcount="24"> Before dawn today, Gorbachev flew back to Moscow from the Crimea, where he had been confined to his summer home during his brief ouster.</s>

<s docid="SJMN91-06235097" num="23" wdcount="32"> The Soviet president, who was reported to have slept for a few hours in his dacha outside Moscow after returning from the Crimea, arrived at Moscow's Vnukovo Airport unannounced, under heavy security.</s>

<s docid="SJMN91-06235097" num="24" wdcount="14"> He looked somewhat disheveled, clad in a windbreaker and a shirt with open collar.</s>

<s docid="SJMN91-06235097" num="25" wdcount="20"> Appearing on Soviet television after his arrival, Gorbachev looked haggard and unshaven, with deep lines around his eyes and mouth.</s>

<s docid="SJMN91-06235097" num="26" wdcount="23"> Later, at his news conference, he at first spoke haltingly, but then appeared to recover his composure and spoke in a forceful voice.</s>

<s docid="SJMN91-06235097" num="27" wdcount="41"> Gorbachev said his captors cut off all communication and that his only source of news during the coup had been from foreign broadcasts, including the BBC and Voice of America, received on a makeshift radio set up by his personal guards.</s>

<s docid="SJMN91-06235097" num="28" wdcount="12"> "This has been a very difficult, an extremely difficult lesson for me.</s>

<s docid="SJMN91-06235097" num="29" wdcount="10"> It's my, you might say, my drama," he told reporters.</s>

<s docid="SJMN91-06235097" num="30" wdcount="9"> "Everything was done to weaken me psychologically," Gorbachev said.</s>

<s docid="SJMN91-06235097" num="31" wdcount="3"> "It was hard.</s>

<s docid="SJMN91-06235097" num="32" wdcount="29"> It is hard to say it now, but that's how it was."; He said that early on in the coup, he tried to find out who was behind it.</s>

<s docid="SJMN91-06235097" num="33" wdcount="13"> "I picked up one of the telephones I have and it wasn't working.</s>

<s docid="SJMN91-06235097" num="34" wdcount="18"> I picked up a second, a third, a fourth . . . everything was cut off," he said.</s>

<s docid="SJMN91-06235097" num="35" wdcount="31"> "Every day, morning and night, I demanded . . . that my communication be restored and that an airplane be brought immediately so I could be returned to Moscow," he said.</s>

<s docid="SJMN91-06235097" num="36" wdcount="11"> He was being held at his vacation home in the Crimea.</s>

<s docid="SJMN91-06235097" num="37" wdcount="9"> Gorbachev said the coup leaders demanded that he resign.</s>

<s docid="SJMN91-06235097" num="38" wdcount="12"> "I said, 'You will never live that long (to see me resign)'.</s>

<s docid="SJMN91-06235097" num="39" wdcount="19"> "; He called the crisis "one of the most difficult trials of the entire history" of his six-year rule.</s>

<s docid="SJMN91-06235097" num="40" wdcount="12"> Gorbachev said his 32-man personal guard stayed with him throughout the coup.</s>

<s docid="SJMN91-06235097" num="41" wdcount="37"> The 60-year-old president said the crisis had been difficult for his family, especially his wife, Raisa, who "took it very hard."; "Best of all, my granddaughter Anastasia didn't understand anything that was going on," Gorbachev told reporters.</s>

<s docid="SJMN91-06235097" num="42" wdcount="12"> "She wanted to go to the beach; that's all that concerned her.</s>

<s docid="SJMN91-06235097" num="43" wdcount="43"> But the guards wouldn't let her go to the beach; they were concerned something would happen."; When it became clear the coup was failing, Gorbachev said he prepared himself and his family for the possibility that they would be killed by the conspirators.</s>

<s docid="SJMN91-06235097" num="44" wdcount="14"> "You know that it appeared as though they might have done something to me.</s>

<s docid="SJMN91-06235097" num="45" wdcount="28"> They might have killed me and my whole family and made it look as if . . . they were acting in the name" of the acting president.</s>

<s docid="SJMN91-06235097" num="46" wdcount="10"> "These people might have done almost anything," he said .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06235097" num="47" wdcount="2"> Associated Press</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06235097" num="48" wdcount="1"> USA</s>
</COUNTRY>
<CITY>

<s docid="SJMN91-06235097" num="49" wdcount="1"> Moscow</s>
</CITY>
<EDITION>

<s docid="SJMN91-06235097" num="50" wdcount="2"> Stock Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06235097" num="51" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06235097" num="52" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06235097" num="53" wdcount="1"> 910822</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06235097" num="54" wdcount="1"> Thursday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06235097" num="55" wdcount="1"> August</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06235097" num="56" wdcount="1"> 1A</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06235097" num="57" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06235097" num="58" wdcount="1"> WEST</s>
</REGION>
<FEATURE>

<s docid="SJMN91-06235097" num="59" wdcount="1"> PHOTO</s>
</FEATURE>
<STATE>

<s docid="SJMN91-06235097" num="60" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06235097" num="61" wdcount="1"> 912</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06235097" num="62" wdcount="5"> Thursday, August 22, 1991 00235097,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06235097" num="63" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06235097" num="64" wdcount="1"> 1</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06235097" num="65" wdcount="2"> ENG FRONT</s>
</LANGUAGE>
</DOC>
