<DOC>
<DOCNO>

<s docid="SJMN91-06234048" num="1" wdcount="1"> SJMN91-06234048</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06234048" num="2" wdcount="1"> 06234048</s>
</ACCESS>
<DESCRIPT>

<s docid="SJMN91-06234048" num="3" wdcount="4"> USSR; GOVERNMENT; CHANGE; ANALYSIS</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06234048" num="4" wdcount="35"> The camera pans across the ornate furnishings of President Mikhail Gorbachev's Kremlin office, then moves in for a tight shot of three men hunched over a coffee table, conferring in the low voices of conspirators.</s>

<s docid="SJMN91-06234048" num="5" wdcount="21"> "Then it's agreed," Gorbachev says, sitting back and raising his eyes to the portrait of Lenin hanging on the opposite wall.</s>

<s docid="SJMN91-06234048" num="6" wdcount="4"> "It's the only way".</s>

<s docid="SJMN91-06234048" num="7" wdcount="7"> The two others nod in assent .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06234048" num="8" wdcount="1"> Front</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06234048" num="9" wdcount="4"> WHO'S REALLY BEHIND COUP?</s>

<s docid="SJMN91-06234048" num="10" wdcount="3"> CONSPIRACY THEORIES ABOUND</s>
</HEADLINE>
<MEMO>

<s docid="SJMN91-06234048" num="11" wdcount="19"> The Fall of Gorbachev; See also related article on page 1A, 14A, 15A, & 16A of this section .</s>
</MEMO>
<TEXT>

<s docid="SJMN91-06234048" num="12" wdcount="18"> Cut to a row of dour Communists in ill-fitting gray suits announcing Gorbachev's illness and a palace coup.</s>

<s docid="SJMN91-06234048" num="13" wdcount="17"> The camera zooms in on the impassive faces of the two men last seen in Gorbachev's office.</s>

<s docid="SJMN91-06234048" num="14" wdcount="5"> What is going on here?</s>

<s docid="SJMN91-06234048" num="15" wdcount="12"> OK, it's a hackneyed device that would only work in the movies.</s>

<s docid="SJMN91-06234048" num="16" wdcount="17"> But then, this week's events in the Soviet Union have all the makings of a spy thriller.</s>

<s docid="SJMN91-06234048" num="17" wdcount="42"> Kremlinologists who dabble in conspiracy theories are working overtime, though they insist that their darkest imaginings be clearly labeled "pure speculation."; "Once you have a palace coup, the possibilities are endless," said Robert Conquest, a senior research fellow at the Hoover Institution.</s>

<s docid="SJMN91-06234048" num="18" wdcount="34"> "Russian politics are full of very strange things."; For all we know, Conquest joked, Gorbachev could be injected with drugs to change his personality or KGB scientists could produce a body-double to impersonate him.</s>

<s docid="SJMN91-06234048" num="19" wdcount="9"> "His friends would know, but would you or I"?</s>

<s docid="SJMN91-06234048" num="20" wdcount="2"> Conquest said.</s>

<s docid="SJMN91-06234048" num="21" wdcount="27"> "That would be going a bit far."; A more intriguing scenario has Gorbachev conspiring with the coup plotters to engineer a transformation of the Soviet political landscape.</s>

<s docid="SJMN91-06234048" num="22" wdcount="37"> The thinking goes like this:; With his popularity at rock bottom, Gorbachev, a lifelong creature of the KGB, hatches a false coup in order to step out of the way while hard-liners and liberals battle each other.</s>

<s docid="SJMN91-06234048" num="23" wdcount="17"> The coup falls apart and Gorbachev triumphantly returns with a level of legitimacy he never enjoyed before.</s>

<s docid="SJMN91-06234048" num="24" wdcount="30"> The theory could explain the apparent bungling of the coup plotters, said author Joseph Finder, whose 1991 novel, "The Moscow Club," foreshadowed many of the elements of the current crisis.</s>

<s docid="SJMN91-06234048" num="25" wdcount="26"> Finder, who said he did not subscribe to the scenario, nonetheless pointed out that tanks did not begin to roll until hours after Gorbachev's supposed arrest.</s>

<s docid="SJMN91-06234048" num="26" wdcount="12"> Russian President Boris Yeltsin was not arrested, and Leningrad was left alone.</s>

<s docid="SJMN91-06234048" num="27" wdcount="11"> Speculation was not unique to Kremlin watchers in the United States.</s>

<s docid="SJMN91-06234048" num="28" wdcount="40"> Theorizing was rampant in the streets of Moscow on Tuesday, said San Francisco businesswoman Kimberly Getto, who sent a long fax detailing speculation, fueled by the fact that many of the tanks encircling the Russian parliament building had no ammunition.</s>

<s docid="SJMN91-06234048" num="29" wdcount="9"> Gorbachev did not want bloodshed, according to the theory.</s>

<s docid="SJMN91-06234048" num="30" wdcount="22"> The Democratic Reform Movement, headed by former Foreign Minister Eduard Shevardnadze, Gorbachev's longtime ally, floated the same possibility in a statement Monday.</s>

<s docid="SJMN91-06234048" num="31" wdcount="36"> "It's highly implausible, but not to be excluded, that Gorbachev himself agreed to a withdrawal, thinking he'd show them they still needed him," said Norman Naimark, director of Stanford's Center for Russian and East European Studies.</s>

<s docid="SJMN91-06234048" num="32" wdcount="9"> "The degree of connivance is difficult to gauge" .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06234048" num="33" wdcount="6"> DAVID BANK, Mercury News Staff Writer</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06234048" num="34" wdcount="1"> USA</s>
</COUNTRY>
<EDITION>

<s docid="SJMN91-06234048" num="35" wdcount="2"> Morning Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06234048" num="36" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06234048" num="37" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06234048" num="38" wdcount="1"> 910821</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06234048" num="39" wdcount="1"> Wednesday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06234048" num="40" wdcount="1"> August</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06234048" num="41" wdcount="1"> 14A</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06234048" num="42" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06234048" num="43" wdcount="1"> WEST</s>
</REGION>
<STATE>

<s docid="SJMN91-06234048" num="44" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06234048" num="45" wdcount="1"> 518</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06234048" num="46" wdcount="5"> Wednesday, August 21, 1991 00234048,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06234048" num="47" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06234048" num="48" wdcount="1"> 1</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06234048" num="49" wdcount="1"> ENG</s>
</LANGUAGE>
</DOC>
