<DOC>
<DOCNO>

<s docid="SJMN91-06238185" num="1" wdcount="1"> SJMN91-06238185</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06238185" num="2" wdcount="1"> 06238185</s>
</ACCESS>
<DESCRIPT>

<s docid="SJMN91-06238185" num="3" wdcount="7"> OPINION; USSR; PRESIDENT; GOVERNMENT; POLITICS; CHANGE; REVIEW</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06238185" num="4" wdcount="33"> IT IS the stuff of a Byzantine Cold War novel, enticing enough to grab the attention of even the most benign conspiracy theorist: Did Mikhail Gorbachev orchestrate the coup that almost overthrew him?</s>

<s docid="SJMN91-06238185" num="5" wdcount="15"> The blueprint for imposing a state of emergency was drawn by Gorbachev himself last winter.</s>

<s docid="SJMN91-06238185" num="6" wdcount="17"> He pushed through the legislation that included suspension of political activity and of freedom of the press.</s>

<s docid="SJMN91-06238185" num="7" wdcount="19"> He hand-picked the heads of the coercive institutions and other key officials who took part in the coup .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06238185" num="8" wdcount="1"> Perspective</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06238185" num="9" wdcount="7"> WAS GORBACHEV THE MASTERMIND BEHIND THE COUP?</s>
</HEADLINE>
<MEMO>

<s docid="SJMN91-06238185" num="10" wdcount="20"> A Perspective Special Section; Eugene B. Rumer, a specialist in Soviet affairs, wrote this article for the Los Angeles Times.</s>

<s docid="SJMN91-06238185" num="11" wdcount="6"> Times reporter Cathleen Decker contributed .</s>
</MEMO>
<TEXT>

<s docid="SJMN91-06238185" num="12" wdcount="13"> Gorbachev chose to ignore warnings about the right's impending attempt to seize power.</s>

<s docid="SJMN91-06238185" num="13" wdcount="15"> Some warnings came from Gorbachev's liberal advisers, such as Alexander Yakovlev, shortly before the coup.</s>

<s docid="SJMN91-06238185" num="14" wdcount="10"> But, incredibly, the clearest signals came from the hard-liners themselves.</s>

<s docid="SJMN91-06238185" num="15" wdcount="43"> A leading conservative journalist, Alexander Prokhanov, known as the "nightingale of the General Staff," published a transcript of his conversation with the head of the General Staff Academy, the commander-in-chief of the Soviet Navy and Gorbachev's deputy at the Defense Council, Oleg Baklanov.</s>

<s docid="SJMN91-06238185" num="16" wdcount="26"> With remarkable candor, Baklanov called for a military takeover as an appropriate step to avert reforms that would result in a fundamental transformation of the union.</s>

<s docid="SJMN91-06238185" num="17" wdcount="14"> Needless to say, Baklanov delivered on that warning and joined the Gang of Eight.</s>

<s docid="SJMN91-06238185" num="18" wdcount="4"> Gorbachev ignored these warnings.</s>

<s docid="SJMN91-06238185" num="19" wdcount="28"> To some -- an admitted minority -- the thought of a Gorbachev conspiracy is comfortably within the range of the traditional Soviet art of deception known as maskirovka.</s>

<s docid="SJMN91-06238185" num="20" wdcount="26"> And to laymen, something that odd could make sense in a country where illness can mean anything from the flu to a precipitous fall from power.</s>

<s docid="SJMN91-06238185" num="21" wdcount="31"> The most volatile fuel for the conspiracy theory came directly from Gorbachev himself, in his Thursday news conference in which he described his three days under house arrest in the Crimea.</s>

<s docid="SJMN91-06238185" num="22" wdcount="29"> Among the questions: If Gorbachev's 32 armed guards remained loyal to him throughout, why was there no conflict with the opposition delegation that notified the president of the coup?</s>

<s docid="SJMN91-06238185" num="23" wdcount="15"> Why didn't the coup leaders incapacitate Gorbachev's guards, or at least separate them from him?</s>

<s docid="SJMN91-06238185" num="24" wdcount="40"> If Gorbachev's contact with the outside world was limited to intercepting Western radio outlets on an ancient shortwave radio, how was he able to describe the news conference given by the collaborators, down to his view of their trembling hands?</s>

<s docid="SJMN91-06238185" num="25" wdcount="28"> It is highly unlikely that the hard-liners had been set up or ordered by Gorbachev to launch a hopeless coup attempt in order to improve his political standing.</s>

<s docid="SJMN91-06238185" num="26" wdcount="16"> Such a scenario would require an unprecedented degree of selfless commitment to Gorbachev on their part.</s>

<s docid="SJMN91-06238185" num="27" wdcount="60"> A more plausible scenario is that Gorbachev was initially a full member of the conspiracy, which, with his participation, could have clung to the fig leaf of constitutionality and would have thwarted the new Union Treaty, to have been signed last Tuesday, which provided for transfer of key levers of power from the federal presidency to the leaders of republics.</s>

<s docid="SJMN91-06238185" num="28" wdcount="42"> It is possible that, unwilling to take a huge risk and openly side with the hard-liners at the start of the coup, Gorbachev had decided to become ill and wait out the initial phase under virtually self-imposed confinement in his summer residence.</s>

<s docid="SJMN91-06238185" num="29" wdcount="19"> Gorbachev did reveal, however, that two important officials had visited him in Crimea at the outset of the coup.</s>

<s docid="SJMN91-06238185" num="30" wdcount="34"> One was head of the KGB department responsible for the security of Soviet leaders; the other was V. Boldin, Gorbachev's closest aide, by the president's own admission a man of absolute loyalty to him.</s>

<s docid="SJMN91-06238185" num="31" wdcount="43"> One can't help but wonder whether these two visitors came to deliver an ultimatum to Gorbachev and put him under arrest in the event of his non-compliance, or to deliver important documents from fellow junta members at the outset of their joint enterprise.</s>

<s docid="SJMN91-06238185" num="32" wdcount="36"> Conspiracy theorists grope for motives -- Gorbachev wanted to ferret out disloyal elements in his government, to make himself a hero and to delay the scheduled signing of a treaty that would have lessened his powers.</s>

<s docid="SJMN91-06238185" num="33" wdcount="9"> But there is virtually unanimous agreement on one point.</s>

<s docid="SJMN91-06238185" num="34" wdcount="23"> Gorbachev put into power the very hard-liners who fronted the coup and kept them in power despite their vocal mutterings about him .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06238185" num="35" wdcount="3"> EUGENE B. RUMER</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06238185" num="36" wdcount="1"> USA</s>
</COUNTRY>
<EDITION>

<s docid="SJMN91-06238185" num="37" wdcount="2"> Morning Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06238185" num="38" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06238185" num="39" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06238185" num="40" wdcount="1"> 910825</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06238185" num="41" wdcount="1"> Sunday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06238185" num="42" wdcount="1"> August</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06238185" num="43" wdcount="1"> 10C</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06238185" num="44" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06238185" num="45" wdcount="1"> WEST</s>
</REGION>
<STATE>

<s docid="SJMN91-06238185" num="46" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06238185" num="47" wdcount="1"> 717</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06238185" num="48" wdcount="5"> Sunday, August 25, 1991 00238185,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06238185" num="49" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06238185" num="50" wdcount="1"> 1</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06238185" num="51" wdcount="1"> ENG</s>
</LANGUAGE>
</DOC>
