<DOC>
<DOCNO>

<s docid="SJMN91-06236241" num="1" wdcount="1"> SJMN91-06236241</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06236241" num="2" wdcount="1"> 06236241</s>
</ACCESS>
<DESCRIPT>

<s docid="SJMN91-06236241" num="3" wdcount="5"> USSR; GOVERNMENT; END; POLITICS; CHANGE</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06236241" num="4" wdcount="31"> Mikhail Gorbachev and Boris Yeltsin today pressed ahead with a sweeping purge of coup supporters, and the Communist Party suffered a series of stunning blows for not opposing the coup plotters.</s>

<s docid="SJMN91-06236241" num="5" wdcount="25"> Gorbachev threw out his foreign minister, Alexander Bessmertnykh, and the Communist Party was banned from the KGB, which for decades helped enforce Communist rule .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06236241" num="6" wdcount="1"> Front</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06236241" num="7" wdcount="32"> THE HEADS BEGIN TO ROLL KGB STRIPPED OF ITS POWER TO ENFORCE PARTY'S DOCTRINE FOREIGN AIDE BESSMERTNYKH IS FIRED FOR REMAINING SILENT COUP PLOTTERS DID HAVE PLAN TO ARREST AND ISOLATE YELTSIN</s>
</HEADLINE>
<MEMO>

<s docid="SJMN91-06236241" num="8" wdcount="16"> The Coup's Aftermath; See also related stories on pages 1A and 18-19A of this section .</s>
</MEMO>
<TEXT>

<s docid="SJMN91-06236241" num="9" wdcount="18"> Gorbachev told an audience at the Russian parliament that the government would prosecute those responsible for the takeover.</s>

<s docid="SJMN91-06236241" num="10" wdcount="7"> "They wanted to turn us into meat.</s>

<s docid="SJMN91-06236241" num="11" wdcount="18"> They wanted to annihilate us, and for that they must bear the severe responsibility," the Soviet president said.</s>

<s docid="SJMN91-06236241" num="12" wdcount="12"> He accused the Communist Party Central Committee of panicking during the coup.</s>

<s docid="SJMN91-06236241" num="13" wdcount="11"> "There are people who lost their heads, all sense of responsibility.</s>

<s docid="SJMN91-06236241" num="14" wdcount="6"> You could even call them traitors!</s>

<s docid="SJMN91-06236241" num="15" wdcount="33"> Traitors!"; Gorbachev and Yeltsin, the Russian Federation leader who saved Gorbachev, met today for the first time since the coup collapsed to discuss the takeover and deal with officials who backed the putsch.</s>

<s docid="SJMN91-06236241" num="16" wdcount="15"> Gorbachev named a series of well-known reformers to the posts of those who were fired.</s>

<s docid="SJMN91-06236241" num="17" wdcount="19"> In his speech, Gorbachev praised "the outstanding role" of Yeltsin, his sometimes adversary, in halting the hard-line Communist coup.</s>

<s docid="SJMN91-06236241" num="18" wdcount="48"> Yeltsin has been a strong foe of Communist Party influence in the country; Gorbachev, however, warned in his speech against "any kind of anti-Communist hysteria."; Yeltsin commented frequently during Gorbachev's speech, and Gorbachev deferred to him several times on details of what happened while Gorbachev was in detention.</s>

<s docid="SJMN91-06236241" num="19" wdcount="22"> His opening comments drew a standing ovation from the lawmakers in the parliament, where Yeltsin had led the opposition to the coup.</s>

<s docid="SJMN91-06236241" num="20" wdcount="19"> Gorbachev also told the Russian Federation parliamentarians that the leaders of the hard-line coup had sought to arrest Yeltsin.</s>

<s docid="SJMN91-06236241" num="21" wdcount="28"> "The president of Russia, Yeltsin . . . was to be arrested, that is how I understood it," Gorbachev said, adding the coup plotters intended to isolate Yeltsin.</s>

<s docid="SJMN91-06236241" num="22" wdcount="37"> As the face of the Soviet government continued to change in the aftermath of the 63-hour coup, hundreds of angry citizens marched toward Communist Party headquarters in Moscow intent on proving the party was behind the coup.</s>

<s docid="SJMN91-06236241" num="23" wdcount="18"> Yeltsin, who led the nationwide coup resistance, today nationalized the hundreds of printing plants in the Russian republic.</s>

<s docid="SJMN91-06236241" num="24" wdcount="28"> He suspended the publication of six Communist Party newspapers and ordered new chiefs for the official Novosti and Tass news services, charging that they had supported the takeover.</s>

<s docid="SJMN91-06236241" num="25" wdcount="12"> It was unclear whether he had the authority to order the firings.</s>

<s docid="SJMN91-06236241" num="26" wdcount="33"> The actions by Yeltsin, who quit the party last summer, came amid a growing wave of anger at the Communist Party, six of whose top party officials were arrested for instigating the coup.</s>

<s docid="SJMN91-06236241" num="27" wdcount="25"> In a major blow to the crumbling party, the acting head of the KGB today banned Communist Party activity in the security service, Tass said.</s>

<s docid="SJMN91-06236241" num="28" wdcount="24"> A KGB directive also banned any other political parties in the KGB, for decades used by Communist regimes to intimidate dissidents and anti-Communist activists.</s>

<s docid="SJMN91-06236241" num="29" wdcount="35"> As Gorbachev and Yeltsin met, a crowd of about 1,000 people headed toward the Communist Party headquarters in Moscow, saying they wanted to capture and preserve records that might prove the party supported the coup.</s>

<s docid="SJMN91-06236241" num="30" wdcount="41"> Calls for retribution have sounded since the 3-day-old coup collapsed Wednesday, with Gorbachev beginning a purge of coup plotters and thousands of cheering demonstrators toppling a statue outside the Moscow headquarters of the KGB, whose former leader backed the ouster attempt.</s>

<s docid="SJMN91-06236241" num="31" wdcount="17"> Bessmertnykh is out; The firing of Foreign Minister Bessmertnykh followed criticism of his silence during the coup.</s>

<s docid="SJMN91-06236241" num="32" wdcount="16"> Bessmertnykh, 57, was the latest official to step down or be removed after the failed takeover.</s>

<s docid="SJMN91-06236241" num="33" wdcount="32"> In in his speech to the Russian Federation parliament, Gorbachev said of Bessmertnykh "this morning I got information that at least he was trying to maneuver or worse" during the coup attempt.</s>

<s docid="SJMN91-06236241" num="34" wdcount="20"> He was not seen publicly after the coup began, and he didn't re-emerge until the coup leadership began to collapse.</s>

<s docid="SJMN91-06236241" num="35" wdcount="10"> Bessmertnykh said he had been ill and unable to act.</s>

<s docid="SJMN91-06236241" num="36" wdcount="19"> Also dismissed was Soviet parliamentary speaker Anatoly Lukyanov, whom Yeltsin had named as the chief ideologue of the plotters.</s>

<s docid="SJMN91-06236241" num="37" wdcount="24"> Yeltsin, who stature rose with his resistance in the coup, said earlier that he would insist that proven reformers be installed in top jobs.</s>

<s docid="SJMN91-06236241" num="38" wdcount="29"> Gorbachev told the legislators that he did not want now to name all those appointed to replace the hard-liners, but Yeltsin said that Gorbachev had agreed to appointing Maj.</s>

<s docid="SJMN91-06236241" num="39" wdcount="7"> Gen. Constantine Kovets head of the army.</s>

<s docid="SJMN91-06236241" num="40" wdcount="10"> Kovets was in charge of defense for the Russian republic.</s>

<s docid="SJMN91-06236241" num="41" wdcount="27"> Six newspapers suspended; The six newspapers suspended by Yeltsin, all based in the Russian republic, are Pravda, Sovietskaya Rossiya, Glasnost, Rabochaya Tribuna, Moskovskaya Pravda and Leninskoe Znamya.</s>

<s docid="SJMN91-06236241" num="42" wdcount="16"> It was unclear whether he had the authority to fire the chiefs at Tass and Novosti.</s>

<s docid="SJMN91-06236241" num="43" wdcount="5"> He also ordered Novosti nationalized.</s>

<s docid="SJMN91-06236241" num="44" wdcount="22"> In other developments:; (check) Gorbachev said he would meet today with leaders of the nine republics who support the new Union Treaty.</s>

<s docid="SJMN91-06236241" num="45" wdcount="25"> The treaty, whose signing was put off by the coup, had angered hard-liners who objected to its provisions ceding more Kremlin power to the republics.</s>

<s docid="SJMN91-06236241" num="46" wdcount="14"> Gorbachev also was to make a late-afternoon visit to the Russian parliament, Tass reported.</s>

<s docid="SJMN91-06236241" num="47" wdcount="29"> (check) Kirghiz President Askar Akaev said the republic of Kirghizia would take control of the headquarters of the Kirghiz wing of the Communist Party and the local Lenin Museum.</s>

<s docid="SJMN91-06236241" num="48" wdcount="7"> Akaev said the party would be compensated.</s>

<s docid="SJMN91-06236241" num="49" wdcount="25"> (check) Only one of the eight top leaders of the coup remained at large early today -- Oleg Baklanov, deputy of the state Defense Committee.</s>

<s docid="SJMN91-06236241" num="50" wdcount="31"> Coup leader kills himself; One of the coup leaders, Interior Minister Boris Pugo, committed suicide Thursday by shooting himself in the head as he was about to be arrested, officials said.</s>

<s docid="SJMN91-06236241" num="51" wdcount="5"> He was replaced by Lt.</s>

<s docid="SJMN91-06236241" num="52" wdcount="4"> Gen. Vasily P. Trushin.</s>

<s docid="SJMN91-06236241" num="53" wdcount="19"> Defense Minister Dmitri Yazov was arrested and replaced by Gen. Mikhail Moiseyev, the chief of the Soviet general staff.</s>

<s docid="SJMN91-06236241" num="54" wdcount="11"> Leonid V. Shebarshin was named to replace KGB Chief Vladimir Kryuchkov.</s>

<s docid="SJMN91-06236241" num="55" wdcount="13"> Gorbachev's chief of staff, Valery I. Boldin, was replaced by Grigory Revenko .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06236241" num="56" wdcount="2"> Associated Press</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06236241" num="57" wdcount="1"> USA</s>
</COUNTRY>
<CITY>

<s docid="SJMN91-06236241" num="58" wdcount="1"> Moscow</s>
</CITY>
<EDITION>

<s docid="SJMN91-06236241" num="59" wdcount="1"> Street</s>
</EDITION>
<CODE>

<s docid="SJMN91-06236241" num="60" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06236241" num="61" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06236241" num="62" wdcount="1"> 910823</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06236241" num="63" wdcount="1"> Friday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06236241" num="64" wdcount="1"> August</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06236241" num="65" wdcount="1"> 1A</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06236241" num="66" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06236241" num="67" wdcount="1"> WEST</s>
</REGION>
<STATE>

<s docid="SJMN91-06236241" num="68" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06236241" num="69" wdcount="1"> 1,027</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06236241" num="70" wdcount="5"> Friday, August 23, 1991 00236241,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06236241" num="71" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06236241" num="72" wdcount="1"> 0</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06236241" num="73" wdcount="2"> ENG FRONT</s>
</LANGUAGE>
</DOC>
