<DOC>
<DOCNO>

<s docid="SJMN91-06235187" num="1" wdcount="1"> SJMN91-06235187</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06235187" num="2" wdcount="1"> 06235187</s>
</ACCESS>
<CAPTION>

<s docid="SJMN91-06235187" num="3" wdcount="38"> Photo; PHOTO: Associated Press; GOODBYE -- Valentin Pavlov, Gennady Yanayev, Anatoly Lukyanov and Vladimir Ivashko, soon to be among the "coup people," bid farewell in July to Mikhail Gorbachev as he departs for the London economic summit .</s>
</CAPTION>
<DESCRIPT>

<s docid="SJMN91-06235187" num="4" wdcount="6"> USSR; GOVERNMENT; CHANGE; ATTEMPT; POLITICS; ANALYSIS</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06235187" num="5" wdcount="15"> Nothing so important has happened in Soviet politics since 1917, when the Bolsheviks seized power.</s>

<s docid="SJMN91-06235187" num="6" wdcount="14"> In Moscow on Wednesday, the system the Bolsheviks and Joseph Stalin created finally collapsed.</s>

<s docid="SJMN91-06235187" num="7" wdcount="5"> A new historical epoch began.</s>

<s docid="SJMN91-06235187" num="8" wdcount="27"> Soviets had an experience comparable to those that transformed the outlooks of Poles, Hungarians, Czechs and Slovaks in 1989, when they learned they could finally be free.</s>

<s docid="SJMN91-06235187" num="9" wdcount="16"> Soviets' courage in resisting this putsch announced the arrival of a nation capable of self-governance .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06235187" num="10" wdcount="1"> Front</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06235187" num="11" wdcount="8"> DEFIANT SOVIETS HAVE WON POWER TO RULE THEMSELVES</s>
</HEADLINE>
<MEMO>

<s docid="SJMN91-06235187" num="12" wdcount="1"> Analysis</s>
</MEMO>
<TEXT>

<s docid="SJMN91-06235187" num="13" wdcount="14"> The "coup people," as President Bush dubbed them, could not have miscalculated more profoundly.</s>

<s docid="SJMN91-06235187" num="14" wdcount="26"> They thought the issue was Mikhail Gorbachev, and apparently believed that by neutralizing Gorbachev and threatening everyone else, they could quickly take charge of the country.</s>

<s docid="SJMN91-06235187" num="15" wdcount="32"> But the people of the Soviet Union apparently concluded that the real issue was not Gorbachev himself, but the new political culture of freedom and even democracy that his reforms had created.</s>

<s docid="SJMN91-06235187" num="16" wdcount="18"> For the first time in their thousand-year history, Russians asserted their independence from autocracy, and the autocrats fell.</s>

<s docid="SJMN91-06235187" num="17" wdcount="11"> There will be much to sort out in the months ahead.</s>

<s docid="SJMN91-06235187" num="18" wdcount="17"> But almost certainly the failure of the counterrevolution will accelerate the democratic revolution it tried to choke.</s>

<s docid="SJMN91-06235187" num="19" wdcount="21"> That revolution will alter the country, creating a new, decentralized and probably smaller Soviet Union much more quickly than anyone anticipated.</s>

<s docid="SJMN91-06235187" num="20" wdcount="10"> Gorbachev's own standing also will be transformed by these events.</s>

<s docid="SJMN91-06235187" num="21" wdcount="33"> It seems unlikely that he can escape the consequences of his own past miscalculations -- especially the miscalculation that led him to embrace the very men who led this putsch against his rule.</s>

<s docid="SJMN91-06235187" num="22" wdcount="35"> Gorbachev was the most resourceful and creative political leader of the late 20th century, but this week he was trumped by Boris Yeltsin, who will now rightly be seen as the man who saved him.</s>

<s docid="SJMN91-06235187" num="23" wdcount="7"> Yeltsin had two talents that Gorbachev lacked.</s>

<s docid="SJMN91-06235187" num="24" wdcount="39"> One was the ability to stay close to the Russian people as their world was transformed by Gorbachev's revolution -- hence his thumping victory in this spring's first presidential election in Russia and Gorbachev's abysmal standing in the polls.</s>

<s docid="SJMN91-06235187" num="25" wdcount="24"> Yeltsin's second talent was his eagerness to challenge the apparatus of the Soviet Communist Party, the world from which both he and Gorbachev emerged.</s>

<s docid="SJMN91-06235187" num="26" wdcount="8"> Gorbachev could never shuck his party apparatchik's skin.</s>

<s docid="SJMN91-06235187" num="27" wdcount="31"> Instead of reaching out to new ideas and new people as Yeltsin has, he surrounded himself with traditional Communist Party officials and worried about the impact of new schemes and ideas.</s>

<s docid="SJMN91-06235187" num="28" wdcount="45"> Gorbachev thought Vladimir Kryuchkov of the KGB, Boris Pugo of the Ministry of Interior, Dmitri Yazov of the Red Army and Gennady Yanayev of the Communist Party were necessary bedfellows whose presence in his entourage could protect him from conservative forces that hated his reforms.</s>

<s docid="SJMN91-06235187" num="29" wdcount="8"> Instead, they turned out to be mortal enemies.</s>

<s docid="SJMN91-06235187" num="30" wdcount="14"> If they had been only personal enemies, Gorbachev might have been undone by them.</s>

<s docid="SJMN91-06235187" num="31" wdcount="51"> But when they closed the new, liberal news media and reverted to the Stalinist tradition of the big lie, the members of the State Emergency Committee threatened not just Gorbachev but also the new Soviet Union -- a society that offered its citizens an unprecedented opportunity for dignity, self-reliance and freedom.</s>

<s docid="SJMN91-06235187" num="32" wdcount="19"> For years, Soviets and Western Kremlinologists had debated whether the changes that created this new Soviet Union were irreversible.</s>

<s docid="SJMN91-06235187" num="33" wdcount="7"> Tuesday, it became clear that they were.</s>

<s docid="SJMN91-06235187" num="34" wdcount="13"> Of course, Gorbachev initiated those changes, and history will credit him for that.</s>

<s docid="SJMN91-06235187" num="35" wdcount="23"> He also refused to acquiesce to the state of emergency that those responsible for the coup apparently asked him to endorse last weekend.</s>

<s docid="SJMN91-06235187" num="36" wdcount="40"> It is intriguing in assessing the coup's failure that men trained as thugs by some of the most violent and mean-spirited institutions created by any state could not, in their moment of truth, behave like thugs and kill their compatriots.</s>

<s docid="SJMN91-06235187" num="37" wdcount="34"> They left Gorbachev alive and Yeltsin at large; they let the Western media report their coup as it unfolded; and they allowed foreign radio stations to broadcast news of it back into the country.</s>

<s docid="SJMN91-06235187" num="38" wdcount="20"> Even their own news media, under strict control, conveyed the fact that there was widespread resistance to their attempted coup.</s>

<s docid="SJMN91-06235187" num="39" wdcount="22"> By Tuesday night, the Emergency Committee was in a confrontation with the political legitimacy of Yeltsin, and this proved an unequal contest.</s>

<s docid="SJMN91-06235187" num="40" wdcount="40"> As Gorbachev had previously discovered in his negotiations with Yeltsin over a new union treaty, the legitimacy provided by the 50 million votes that Yeltsin received in the elections for president of the Russian federation was a formidable political force.</s>

<s docid="SJMN91-06235187" num="41" wdcount="22"> At first blush, the botching of the coup was surprising -- couldn't the vaunted KGB and its allies run an efficient putsch?</s>

<s docid="SJMN91-06235187" num="42" wdcount="20"> But these were representatives of the political class that turned one of the world's richest nations into a basket case.</s>

<s docid="SJMN91-06235187" num="43" wdcount="37"> Perhaps their coup should be seen as a desperate and forlorn effort to deny a truth that proved undeniable -- that the Stalinist system had failed so utterly there was simply no way to redeem it .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06235187" num="44" wdcount="5"> ROBERT G. KAISER, Washington Post</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06235187" num="45" wdcount="1"> USA</s>
</COUNTRY>
<EDITION>

<s docid="SJMN91-06235187" num="46" wdcount="2"> Morning Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06235187" num="47" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06235187" num="48" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06235187" num="49" wdcount="1"> 910822</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06235187" num="50" wdcount="1"> Thursday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06235187" num="51" wdcount="1"> August</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06235187" num="52" wdcount="1"> 1A</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06235187" num="53" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06235187" num="54" wdcount="1"> WEST</s>
</REGION>
<FEATURE>

<s docid="SJMN91-06235187" num="55" wdcount="1"> PHOTO</s>
</FEATURE>
<STATE>

<s docid="SJMN91-06235187" num="56" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06235187" num="57" wdcount="1"> 852</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06235187" num="58" wdcount="5"> Thursday, August 22, 1991 00235187,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06235187" num="59" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06235187" num="60" wdcount="1"> 1</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06235187" num="61" wdcount="2"> ENG FRONT</s>
</LANGUAGE>
</DOC>
