<DOC>
<DOCNO>

<s docid="SJMN91-06236235" num="1" wdcount="1"> SJMN91-06236235</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06236235" num="2" wdcount="1"> 06236235</s>
</ACCESS>
<CAPTION>

<s docid="SJMN91-06236235" num="3" wdcount="26"> Photos (2); PHOTO: Bessmertnykh; PHOTO: Associated Press; NAMING NAMES -- Gorbachev holds notes given him by Yeltsin today at a special session of the Russian parliament.</s>

<s docid="SJMN91-06236235" num="4" wdcount="20"> The notes were taken at a cabinet meeting Monday and indicate the stand of each minister toward the coup .</s>
</CAPTION>
<DESCRIPT>

<s docid="SJMN91-06236235" num="5" wdcount="5"> USSR; CHANGE; POLITICS; GOVERNMENT; END</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06236235" num="6" wdcount="40"> Mikhail Gorbachev and Boris Yeltsin launched a sweeping purge today that dealt a series of stunning blows to the Communist Party power structure, including the ouster of top officials, the sealing of party headquarters and the curtailing of party activities.</s>

<s docid="SJMN91-06236235" num="7" wdcount="27"> Yeltsin appeared today to be acting at least as an equal with Gorbachev, and the two clearly agreed on the replacement of old-guard officials by new reformers.</s>

<s docid="SJMN91-06236235" num="8" wdcount="26"> In fact, the two leaders reached an agreement that permits each man to assume the other's duties in an emergency, such as another coup attempt .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06236235" num="9" wdcount="1"> Front</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06236235" num="10" wdcount="28"> HEADS BEGIN TO ROLL GORBACHEV AND YELTSIN JOINTLY REPLACE TOP OFFICIALS COMMUNIST PARTY BUILDING SEALED AND PHONE SERVICE CUT POLITICAL ACTIVITY BANNED IN KGB, ARMY AND POLICE UNITS</s>
</HEADLINE>
<MEMO>

<s docid="SJMN91-06236235" num="11" wdcount="16"> The Coup's Aftermath; See also related stories on pages 1A and 18-19A of this section .</s>
</MEMO>
<TEXT>

<s docid="SJMN91-06236235" num="12" wdcount="21"> Gorbachev threw out his foreign minister, Alexander Bessmertnykh, and his acting defense minister, and named a new head of the KGB.</s>

<s docid="SJMN91-06236235" num="13" wdcount="11"> And Yeltsin, with Gorbachev's blessing, fired the heads of state-owned media.</s>

<s docid="SJMN91-06236235" num="14" wdcount="24"> The Moscow City Council, meanwhile, ordered all Communist Party buildings in the capital sealed and all telephone service to party and KGB buildings cut.</s>

<s docid="SJMN91-06236235" num="15" wdcount="30"> About 2,000 protesters blockaded the Communist Party headquarters in Moscow, declaring they were trying to prevent the removal of documents that might contain evidence linking party members to the coup.</s>

<s docid="SJMN91-06236235" num="16" wdcount="49"> Some of the demonstrators chanted, "Down with the Communist Party!"; Yeltsin, who had led the nationwide resistance to the coup, announced a ban on Communist Party activities in the Russian republic, the army, police units of the Interior Ministry and the KGB, which for decades helped enforce Communist rule.</s>

<s docid="SJMN91-06236235" num="17" wdcount="21"> Some of the many new decrees issued by Yeltsin went beyond the official bounds of his power as Russian Federation president.</s>

<s docid="SJMN91-06236235" num="18" wdcount="23"> In his speech before the Russian parliament, Gorbachev was compelled to affirm as legitimate the decrees issued by Yeltsin during the three-day coup.</s>

<s docid="SJMN91-06236235" num="19" wdcount="33"> It wasn't clear whether the Soviet president had intended to back Yeltsin's latest decrees, and he balked at proposals by Russian deputies to outlaw the Communist Party, saying it would divide the nation.</s>

<s docid="SJMN91-06236235" num="20" wdcount="14"> Gorbachev told the deputies that the government would prosecute those responsible for the takeover.</s>

<s docid="SJMN91-06236235" num="21" wdcount="7"> "They wanted to turn us into meat.</s>

<s docid="SJMN91-06236235" num="22" wdcount="18"> They wanted to annihilate us, and for that they must bear the severe responsibility," the Soviet president said.</s>

<s docid="SJMN91-06236235" num="23" wdcount="12"> He accused the Communist Party Central Committee of panicking during the coup.</s>

<s docid="SJMN91-06236235" num="24" wdcount="11"> "There are people who lost their heads, all sense of responsibility.</s>

<s docid="SJMN91-06236235" num="25" wdcount="6"> You could even call them traitors!</s>

<s docid="SJMN91-06236235" num="26" wdcount="32"> Traitors!"; At one point during the session, Gorbachev dramatically held up what he said were the minutes of a secret Cabinet meeting during the coup that revealed who backed the emergency decrees.</s>

<s docid="SJMN91-06236235" num="27" wdcount="16"> He said many of them "hemmed and hawed," but most voted in support of the takeover.</s>

<s docid="SJMN91-06236235" num="28" wdcount="15"> Today's meeting displayed unprecedented openness in which deputies repeatedly interrupted Gorbachev and argued with him.</s>

<s docid="SJMN91-06236235" num="29" wdcount="16"> Gorbachev drew applause from deputies when he announced that the party's headquarters in Moscow was sealed.</s>

<s docid="SJMN91-06236235" num="30" wdcount="26"> The meeting of Gorbachev and Yeltsin was the first since the coup collapsed to discuss the takeover and to deal with officials who backed the putsch.</s>

<s docid="SJMN91-06236235" num="31" wdcount="19"> In his speech, Gorbachev praised "the outstanding role" of Yeltsin, his sometimes adversary, in halting the hard-line Communist coup.</s>

<s docid="SJMN91-06236235" num="32" wdcount="46"> Yeltsin has been a strong foe of Communist Party influence in the country; Gorbachev, however, warned in his speech against "any kind of anti-Communist hysteria."; Yeltsin often commented during Gorbachev's speech, and Gorbachev deferred to him several times on details of what happened during Gorbachev's detention.</s>

<s docid="SJMN91-06236235" num="33" wdcount="17"> Standing ovation; The Soviet president's opening comments drew a standing ovation from the lawmakers in the parliament.</s>

<s docid="SJMN91-06236235" num="34" wdcount="25"> Yeltsin led the opposition to the coup from the parliament building, where supporters rallied to build barricades and form a human shield against expected attacks.</s>

<s docid="SJMN91-06236235" num="35" wdcount="15"> The coup plotters never dared mount a frontal assault on Yeltsin's headquarters during the standoff.</s>

<s docid="SJMN91-06236235" num="36" wdcount="37"> As the face of the Soviet government continued to change in the aftermath of the failed coup, hundreds of angry residents marched toward Communist Party headquarters in Moscow intent on proving the party was behind the coup.</s>

<s docid="SJMN91-06236235" num="37" wdcount="28"> In other developments:; (check) Only one of the eight top leaders of the coup remained at large early today -- Oleg Baklanov, deputy of the state Defense Committee.</s>

<s docid="SJMN91-06236235" num="38" wdcount="31"> (check) In Kirghizia, Kirghiz President Askar Akaev said the republic would take control of the headquarters of the Kirghiz wing of the Communist Party, as well as the local Lenin Museum.</s>

<s docid="SJMN91-06236235" num="39" wdcount="7"> Akaev said the party would be compensated.</s>

<s docid="SJMN91-06236235" num="40" wdcount="16"> Publication suspended; In Moscow, Yeltsin today nationalized the hundreds of printing plants in the Russian republic.</s>

<s docid="SJMN91-06236235" num="41" wdcount="27"> He suspended the publication of six Communist Party newspapers and ordered new chiefs for the official Novosti and Tass news services, charging they had supported the takeover.</s>

<s docid="SJMN91-06236235" num="42" wdcount="33"> The actions by Yeltsin, who quit the party last summer, came amid a growing wave of anger at the Communist Party, six of whose top party officials were arrested for instigating the coup.</s>

<s docid="SJMN91-06236235" num="43" wdcount="28"> In a major blow to the crumbling party, the acting head of the KGB today affirmed Yeltsin's ban on Communist Party activity in the security service, Tass said.</s>

<s docid="SJMN91-06236235" num="44" wdcount="24"> A KGB directive also banned any other political parties in the KGB, for decades used by Communist regimes to intimidate dissidents and anti-Communist activists.</s>

<s docid="SJMN91-06236235" num="45" wdcount="14"> Bold protests; The firing of Bessmertnykh followed criticism of his silence during the coup.</s>

<s docid="SJMN91-06236235" num="46" wdcount="16"> Bessmertnykh, 57, was the latest official to step down or be removed after the failed takeover.</s>

<s docid="SJMN91-06236235" num="47" wdcount="20"> He was not seen publicly after the coup began, and he didn't re-emerge until the coup leadership began to collapse.</s>

<s docid="SJMN91-06236235" num="48" wdcount="10"> Bessmertnykh said he had been ill and unable to act.</s>

<s docid="SJMN91-06236235" num="49" wdcount="22"> The arrest of the former KGB chief and other Communist Party hard-liners inspired tens of thousands of demonstrators to undreamed-of daring Thursday.</s>

<s docid="SJMN91-06236235" num="50" wdcount="26"> They expressed their anger and disgust with the organizations responsible for killing millions of Soviet citizens and now caught conspiring to return to their old dictatorship.</s>

<s docid="SJMN91-06236235" num="51" wdcount="12"> At KGB headquarters on Dzerzhinsky Street, thousands shook fists and shouted, "Executioners"!</s>

<s docid="SJMN91-06236235" num="52" wdcount="19"> They smeared "Down with the KGB"! and a swastika on the front of the building in white paint .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06236235" num="53" wdcount="2"> Associated Press</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06236235" num="54" wdcount="1"> USA</s>
</COUNTRY>
<CITY>

<s docid="SJMN91-06236235" num="55" wdcount="1"> Moscow</s>
</CITY>
<EDITION>

<s docid="SJMN91-06236235" num="56" wdcount="2"> Stock Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06236235" num="57" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06236235" num="58" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06236235" num="59" wdcount="1"> 910823</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06236235" num="60" wdcount="1"> Friday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06236235" num="61" wdcount="1"> August</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06236235" num="62" wdcount="1"> 1A</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06236235" num="63" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06236235" num="64" wdcount="1"> WEST</s>
</REGION>
<FEATURE>

<s docid="SJMN91-06236235" num="65" wdcount="1"> PHOTO</s>
</FEATURE>
<STATE>

<s docid="SJMN91-06236235" num="66" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06236235" num="67" wdcount="1"> 1,036</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06236235" num="68" wdcount="5"> Friday, August 23, 1991 00236235,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06236235" num="69" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06236235" num="70" wdcount="1"> 0</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06236235" num="71" wdcount="2"> ENG FRONT</s>
</LANGUAGE>
</DOC>
