<DOC>
<DOCNO>

<s docid="AP880625-0142" num="1" wdcount="1"> AP880625-0142</s>
</DOCNO>
<FILEID>

<s docid="AP880625-0142" num="2" wdcount="2"> AP-NR-06-25-88 1555EDT</s>
</FILEID>
<FIRST>

<s docid="AP880625-0142" num="3" wdcount="5"> r i AM-Philippines-Marcos 06-25 0374</s>
</FIRST>
<SECOND>

<s docid="AP880625-0142" num="4" wdcount="1"> AM-Philippines-Marcos,0387</s>
</SECOND>
<HEAD>

<s docid="AP880625-0142" num="5" wdcount="9"> Aquino Reported Ready to Let Marcos Return For Trial</s>
</HEAD>
<DATELINE>

<s docid="AP880625-0142" num="6" wdcount="3"> MANILA, Philippines (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880625-0142" num="7" wdcount="31"> President Corazon Aquino has agreed to allow Ferdinand Marcos to return to the Philippines so that the government can try him on charges of stealing billions of dollars, newspapers said Saturday.</s>

<s docid="AP880625-0142" num="8" wdcount="33"> The Manila Bulletin and The Manila Chronicle quoted Mrs. Aquino's press secretary, Teodoro Benigno, as saying that Mrs. Aquino made the assurance to two Swiss lawyers before she visited Switzerland earlier this month.</s>

<s docid="AP880625-0142" num="9" wdcount="25"> The reports did not say when criminal charges against Marcos, Aquino's ousted predecessor, will be filed or when Mrs. Aquino will allow him to return.</s>

<s docid="AP880625-0142" num="10" wdcount="13"> Mrs. Aquino has refused to allow Marcos into the Philippines, citing security reasons.</s>

<s docid="AP880625-0142" num="11" wdcount="6"> Marcos lives in exile in Hawaii.</s>

<s docid="AP880625-0142" num="12" wdcount="25"> Mrs. Aquino's government has said it will file criminal charges against Marcos, whom it has accused of stealing up to $10 billion in government funds.</s>

<s docid="AP880625-0142" num="13" wdcount="18"> But the government has not done so because of Mrs. Aquino's refusal to let Marcos enter the country.</s>

<s docid="AP880625-0142" num="14" wdcount="8"> Philippine law does not allow trial in absentia.</s>

<s docid="AP880625-0142" num="15" wdcount="20"> Swiss lawyers are helping the Philippine government trace money that Marcos and his family allegedly placed in Swiss bank accounts.</s>

<s docid="AP880625-0142" num="16" wdcount="23"> Marcos has been living in Hawaii since he was toppled by the civilian-military revolt that swept Mrs. Aquino to power in February 1986.</s>

<s docid="AP880625-0142" num="17" wdcount="34"> The Swiss government has frozen the assets of Marcos and his associates and has not released information on them to the Philippine government because of legal challenges posed by Marcos' lawyers and Swiss banks.</s>

<s docid="AP880625-0142" num="18" wdcount="32"> The unidentified Swiss lawyers said the information will not be turned over ``unless and until there is an assurance that formal charges will be filed against him,'' Benigno was quoted as saying.</s>

<s docid="AP880625-0142" num="19" wdcount="15"> Swiss law allows the lifting of banking secrecy laws only in case of criminal prosecution.</s>

<s docid="AP880625-0142" num="20" wdcount="33"> Mrs. Aquino has said she would allow Marcos to return now only if he and his family swore allegiance to her government and returned the money he allegedly stole during his 20-year rule.</s>

<s docid="AP880625-0142" num="21" wdcount="25"> She said later she would abide by any court decision if Marcos' lawyers in the Philippines raised the matter of his return to the courts.</s>

<s docid="AP880625-0142" num="22" wdcount="17"> Benigno was quoted as saying that Mrs. Aquino ``has to accept the possibility of Marcos returning home.''</s>
</TEXT>
</DOC>
