<DOC>
<DOCNO>

<s docid="AP890519-0060" num="1" wdcount="1"> AP890519-0060</s>
</DOCNO>
<FILEID>

<s docid="AP890519-0060" num="2" wdcount="2"> AP-NR-05-19-89 0707EST</s>
</FILEID>
<FIRST>

<s docid="AP890519-0060" num="3" wdcount="6"> u i PM-Philippines-Marcos 2ndLd-Writethru 05-19 0533</s>
</FIRST>
<SECOND>

<s docid="AP890519-0060" num="4" wdcount="3"> PM-Philippines-Marcos, 2nd Ld-Writethru,a0478,0546</s>
</SECOND>
<HEAD>

<s docid="AP890519-0060" num="5" wdcount="10"> Mrs. Aquino Reaffirms Ban on Marcos, Imelda Makes Radio Appeal</s>
</HEAD>
<HEAD>

<s docid="AP890519-0060" num="6" wdcount="13"> Eds: LEADS with 8 grafs to UPDATE with Imelda Marcos making appeal, details.</s>

<s docid="AP890519-0060" num="7" wdcount="8"> Picks up graf 5 pvs, `I regret ...'</s>
</HEAD>
<HEAD>

<s docid="AP890519-0060" num="8" wdcount="2"> With PM-Marcos</s>
</HEAD>
<DATELINE>

<s docid="AP890519-0060" num="9" wdcount="3"> MANILA, Philippines (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890519-0060" num="10" wdcount="31"> President Corazon Aquino said today she will not allow Ferdinand Marcos to come home to die and her government will not permit the ousted president to be buried on Philippine soil.</s>

<s docid="AP890519-0060" num="11" wdcount="19"> Marcos' wife Imelda appealed today to Mrs. Aquino to ``open her heart'' and allow the former president to return.</s>

<s docid="AP890519-0060" num="12" wdcount="22"> Marcos' lawyer also asked the Philippine Supreme Court to order the return, pledging the ousted leader would cooperate with the Aquino administration.</s>

<s docid="AP890519-0060" num="13" wdcount="16"> Marcos was reported in critical condition today in a Honolulu hospital after undergoing emergency kidney surgery.</s>

<s docid="AP890519-0060" num="14" wdcount="16"> Hospital officials said the 71-year-old former Philippine leader was suffering from renal, cardiac and pulmonary failure.</s>

<s docid="AP890519-0060" num="15" wdcount="29"> In Honolulu, Marcos aide Arturo Aruiza said Imelda had left the hospital to make a final appeal to Mrs. Aquino to allow her husband to die in his homeland.</s>

<s docid="AP890519-0060" num="16" wdcount="15"> Mrs. Aquino's daughter, Maria Elena Cruz, said the president had received no calls from Mrs.</s>

<s docid="AP890519-0060" num="17" wdcount="2"> Marcos. Mrs.</s>

<s docid="AP890519-0060" num="18" wdcount="6"> Cruz serves as her mother's secretary.</s>

<s docid="AP890519-0060" num="19" wdcount="46"> In a statement broadcast today by the pro-Marcos radio station DZEC, Imelda said she was trying to contact the presidential office ``to make a last appeal to Madam Corazon Aquino to open her heart and let Ferdinand come home because he is in very serious condition.</s>

<s docid="AP890519-0060" num="20" wdcount="13"> ``This is for reconciliation, this is what's best for the country,'' Imelda said.</s>

<s docid="AP890519-0060" num="21" wdcount="14"> ``I'd like to ask our people to pray that Marcos may continue to live''.</s>

<s docid="AP890519-0060" num="22" wdcount="26"> Mrs. Aquino told reporters earlier that she was sorry to hear that Marcos' condition had deteriorated ``and I pray that he will be able to recover''.</s>

<s docid="AP890519-0060" num="23" wdcount="5"> ``I regret to inform Mrs.</s>

<s docid="AP890519-0060" num="24" wdcount="23"> Marcos, if indeed she is asking me for reconsideration, because as I have said in the past, much as I agree that Mr.</s>

<s docid="AP890519-0060" num="25" wdcount="21"> Marcos has his rights, I still have to consider also the rights and interests of millions of Filipinos,'' Mrs. Aquino said.</s>

<s docid="AP890519-0060" num="26" wdcount="32"> ``I have already said in the past that we will not allow his remains to be brought back here, and we have already taken plans to avoid any untoward incidents,'' she added.</s>

<s docid="AP890519-0060" num="27" wdcount="19"> Mrs. Aquino succeeded Marcos after the 1986 uprising that toppled his administration and forced him into exile in Hawaii.</s>

<s docid="AP890519-0060" num="28" wdcount="15"> Today, the Manila Stock Exchange's composite index fell to 1,084.53 from Thursday's close of 1,102.97.</s>

<s docid="AP890519-0060" num="29" wdcount="13"> Traders said rumors of Marcos' death triggered a selling wave shortly before noon.</s>

<s docid="AP890519-0060" num="30" wdcount="8"> In Honolulu, Marcos aide Arturo Aruiza said Mrs.</s>

<s docid="AP890519-0060" num="31" wdcount="17"> Marcos planned to make one last appeal to Mrs. Aquino to allow her husband to return home.</s>

<s docid="AP890519-0060" num="32" wdcount="29"> Rafael Ileto, Mrs. Aquino's national security advisor, said granting such a request was still an option but, ``I doubt very much that it will be one of the solutions''.</s>

<s docid="AP890519-0060" num="33" wdcount="29"> Ileto, who met with Mrs. Aquino for a half-hour today, said Marcos no longer posed a threat to the nation but his followers ``can cause disruptions of normal functions''.</s>

<s docid="AP890519-0060" num="34" wdcount="26"> Ileto, a retired vice chief of staff and former Defense Minister, said the 160,000-member armed forces was capable of quelling any unrest by Marcos supporters .</s>
</TEXT>
</DOC>
