<DOC>
<DOCNO>

<s docid="AP890710-0170" num="1" wdcount="1"> AP890710-0170</s>
</DOCNO>
<FILEID>

<s docid="AP890710-0170" num="2" wdcount="2"> AP-NR-07-10-89 2059EST</s>
</FILEID>
<FIRST>

<s docid="AP890710-0170" num="3" wdcount="5"> r i AM-Germany-Aquino 07-10 0338</s>
</FIRST>
<SECOND>

<s docid="AP890710-0170" num="4" wdcount="1"> AM-Germany-Aquino,0347</s>
</SECOND>
<HEAD>

<s docid="AP890710-0170" num="5" wdcount="8"> Aquino Asks for Economic Aid for the Philippines</s>
</HEAD>
<DATELINE>

<s docid="AP890710-0170" num="6" wdcount="4"> BONN, West Germany (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890710-0170" num="7" wdcount="20"> President Corazon Aquino of the Philippines on Monday asked government and industrial leaders to expand economic ties with her nation.</s>

<s docid="AP890710-0170" num="8" wdcount="27"> Mrs. Aquino, on the first stop of her weeklong three-nation European tour, met with West German President Richard von Weizsaecker, Foreign Minister Hans-Dietrich Genscher and other officials.</s>

<s docid="AP890710-0170" num="9" wdcount="31"> Mrs. Aquino, comparing the task of strengthening the heavily indebted Philippine economy to the recovery of West Germany after World War II, asked that Germany share its experience with her homeland.</s>

<s docid="AP890710-0170" num="10" wdcount="39"> ``We have tried by sound fiscal policies not to buy recovery at the price of inflation, nor debt relief at the price of national honor,'' she said in a speech to the West German Chamber of Industry and Trade.</s>

<s docid="AP890710-0170" num="11" wdcount="28"> ``We have paid as careful attention to the consequences of runaway inflation and devaluation as Germany in the light of her own experiences between the wars,'' she said.</s>

<s docid="AP890710-0170" num="12" wdcount="35"> Mrs. Aquino said the Philippines' debt was projected to increase to $29 billion by year's end but that much was money that ``was in fact stolen by the previous government'' of ousted dictator Ferdinand Marcos.</s>

<s docid="AP890710-0170" num="13" wdcount="33"> She said that since her government took over in 1986, the country's growth rate of minus 10 percent under Marcos in 1985 had improved to a rate of plus 6.7 percent by 1988.</s>

<s docid="AP890710-0170" num="14" wdcount="23"> ``What we need to complete the equation are two elements essential to the German recovery _ debt relief and investments,'' Mrs. Aquino said.</s>

<s docid="AP890710-0170" num="15" wdcount="23"> During a state banquet in the evening, Weizsaecker told Mrs. Aquino her visit would further strengthen relations between West Germany and the Philippines.</s>

<s docid="AP890710-0170" num="16" wdcount="36"> Weizsaecker said the Philippines have had good results in trade with West Germany, and assured Mrs. Aquino that the barrier-free market the European Economic Community plans for 1992 will not lock out trade with other countries.</s>

<s docid="AP890710-0170" num="17" wdcount="21"> Mrs. Aquino, who arrived in West Germany on Sunday, will meet with Chancellor Helmut Kohl on Tuesday before departing for Paris.</s>

<s docid="AP890710-0170" num="18" wdcount="7"> She also is to visit Belgium .</s>
</TEXT>
</DOC>
