<DOC>
<DOCNO>

<s docid="AP890519-0117" num="1" wdcount="1"> AP890519-0117</s>
</DOCNO>
<FILEID>

<s docid="AP890519-0117" num="2" wdcount="2"> AP-NR-05-19-89 1438EST</s>
</FILEID>
<FIRST>

<s docid="AP890519-0117" num="3" wdcount="6"> u i AM-Philippines-Marcos Bjt 05-19 0584</s>
</FIRST>
<SECOND>

<s docid="AP890519-0117" num="4" wdcount="2"> AM-Philippines-Marcos, Bjt,0600</s>
</SECOND>
<HEAD>

<s docid="AP890519-0117" num="5" wdcount="11"> Aquino Refuses Imelda's `Last' Appeal for Marcos to Die at Home</s>
</HEAD>
<HEAD>

<s docid="AP890519-0117" num="6" wdcount="2"> LaserPhoto HU1</s>
</HEAD>
<BYLINE>

<s docid="AP890519-0117" num="7" wdcount="4"> By ROBERT H. REID</s>
</BYLINE>
<BYLINE>

<s docid="AP890519-0117" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890519-0117" num="9" wdcount="3"> MANILA, Philippines (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890519-0117" num="10" wdcount="33"> President Corazon Aquino on Friday refused to allow Ferdinand Marcos to return home to die and said her government won't permit him to be buried here despite ``a last appeal'' from his wife.</s>

<s docid="AP890519-0117" num="11" wdcount="16"> The 71-year-old Marcos was in critical condition Friday in a Honolulu hospital after emergency kidney surgery.</s>

<s docid="AP890519-0117" num="12" wdcount="14"> Hospital officials said the ousted leader was suffering from renal, cardiac and pulmonary failure.</s>

<s docid="AP890519-0117" num="13" wdcount="30"> Marcos' wife, Imelda, broadcast an appeal Friday to Mrs. Aquino to allow her husband to die in his homeland, and his supporters threatened mass protests if the request is rejected.</s>

<s docid="AP890519-0117" num="14" wdcount="29"> But Mrs. Aquino refused to withdraw her ban on Marcos, and the Philippine Supreme Court rejected a petition from the former president's lawyer, Juan David, to order the return.</s>

<s docid="AP890519-0117" num="15" wdcount="22"> Marcos has lived in Hawaii since he was ousted three years ago in a popular uprising that propelled Mrs. Aquino to power.</s>

<s docid="AP890519-0117" num="16" wdcount="13"> ``I would like first of all to convey to the family of Mr.</s>

<s docid="AP890519-0117" num="17" wdcount="18"> Marcos that I do pray that he will still recover from this latest critical illness,'' Mrs. Aquino said.</s>

<s docid="AP890519-0117" num="18" wdcount="15"> ``I regret very much it is not possible for us to allow him to return''.</s>

<s docid="AP890519-0117" num="19" wdcount="31"> She said she has ``said in the past that we will not allow his remains to be brought back here, and we have already taken plans to avoid any untoward incidents''.</s>

<s docid="AP890519-0117" num="20" wdcount="17"> Mrs. Aquino, whose government has survived six coup attempts, has cited national security in refusing previous requests.</s>

<s docid="AP890519-0117" num="21" wdcount="10"> In a statement broadcast by a pro-Marcos radio station, Mrs.</s>

<s docid="AP890519-0117" num="22" wdcount="18"> Marcos said she has tried to telephone Mrs. Aquino from Hawaii but was told the president was busy.</s>

<s docid="AP890519-0117" num="23" wdcount="17"> Maria Elena Cruz, Mrs. Aquino's daughter and personal secretary, said the president received no calls from Mrs.</s>

<s docid="AP890519-0117" num="24" wdcount="2"> Marcos. Mrs.</s>

<s docid="AP890519-0117" num="25" wdcount="34"> Marcos said she was trying to contact the president ``to make a last appeal to Madame Corazon Aquino to open her heart and let Ferdinand come home because he is in very serious condition''.</s>

<s docid="AP890519-0117" num="26" wdcount="36"> ``My countrymen, I am appealing to each and every one of you to pray that, hopefully, Mrs. Aquino will know that bringing home Marcos will bring true reconciliation, true peace and unity for our country,'' Mrs.</s>

<s docid="AP890519-0117" num="27" wdcount="2"> Marcos said.</s>

<s docid="AP890519-0117" num="28" wdcount="7"> ``This is what's best for the country''.</s>

<s docid="AP890519-0117" num="29" wdcount="10"> Mrs. Aquino had said earlier: ``I regret to inform Mrs.</s>

<s docid="AP890519-0117" num="30" wdcount="23"> Marcos, if indeed she is asking me for reconsideration, because as I have said in the past, much as I agree that Mr.</s>

<s docid="AP890519-0117" num="31" wdcount="18"> Marcos has his rights, I still have to consider also the rights and interests of millions of Filipinos''.</s>

<s docid="AP890519-0117" num="32" wdcount="7"> When told of Mrs. Aquino's statement, Mrs.</s>

<s docid="AP890519-0117" num="33" wdcount="15"> Marcos said ``We are aware, but I am a believer and I am an optimist.</s>

<s docid="AP890519-0117" num="34" wdcount="5"> I know miracles can happen''.</s>

<s docid="AP890519-0117" num="35" wdcount="14"> Marcos supporters, meanwhile, announced they would hold rallies Saturday to pray for his recovery.</s>

<s docid="AP890519-0117" num="36" wdcount="12"> Pro-Marcos leaders warned the former president's death in exile would trigger demonstrations.</s>

<s docid="AP890519-0117" num="37" wdcount="14"> ``We expect tactical alliances in this nationwide mass action,'' said pro-Marcos lawyer Oliver Lozano.</s>

<s docid="AP890519-0117" num="38" wdcount="14"> ``We refer to the tactical alliances of the military, labor sector and student sector''.</s>

<s docid="AP890519-0117" num="39" wdcount="31"> But the chief of staff, Gen. Renato de Villa, said the armed forces would accept Mrs. Aquino's decision and was prepared to block any attempts by the opposition to foment trouble.</s>

<s docid="AP890519-0117" num="40" wdcount="20"> ``We will do everything in our power to see to it that law and order prevail,'' de Villa told reporters.</s>

<s docid="AP890519-0117" num="41" wdcount="9"> ``We will follow any decision by the executive branch.''</s>
</TEXT>
</DOC>
