<DOC>
<DOCNO>

<s docid="AP900408-0059" num="1" wdcount="1"> AP900408-0059</s>
</DOCNO>
<FILEID>

<s docid="AP900408-0059" num="2" wdcount="2"> AP-NR-04-08-90 2117EDT</s>
</FILEID>
<FIRST>

<s docid="AP900408-0059" num="3" wdcount="7"> u i AM-Philippines-Reform 1stLd-Writethru a0691 04-08 0763</s>
</FIRST>
<SECOND>

<s docid="AP900408-0059" num="4" wdcount="4"> AM-Philippines-Reform, 1st Ld-Writethru, a0691,0785</s>
</SECOND>
<HEAD>

<s docid="AP900408-0059" num="5" wdcount="8"> Controversy Raises Doubts About Commitment To Land Reform</s>
</HEAD>
<HEAD>

<s docid="AP900408-0059" num="6" wdcount="4"> An AP News Analysis</s>
</HEAD>
<NOTE>

<s docid="AP900408-0059" num="7" wdcount="23"> Eds: SUBS one graf for 12th graf `Lawmakers on'... to CORRECT to Commission on Appointments, sted on Appoints; pickup graf 13 `Despite the...'</s>
</NOTE>
<BYLINE>

<s docid="AP900408-0059" num="8" wdcount="4"> By ROBERT H. REID</s>
</BYLINE>
<BYLINE>

<s docid="AP900408-0059" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900408-0059" num="10" wdcount="3"> MANILA, Philippines (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900408-0059" num="11" wdcount="28"> The resignation of the land reform secretary raises doubts about President Corazon Aquino's commitment to agrarian reform and dramatizes conflicts in a government criticized for lack of vision.</s>

<s docid="AP900408-0059" num="12" wdcount="25"> The controversy climaxed Thursday with the resignation of Secretary-designate Florencio Abad, 35, whose nomination was opposed by the pro-Aquino Struggle of the Democratic Filipino Party.</s>

<s docid="AP900408-0059" num="13" wdcount="31"> Handling of the controversy highlighted all the inconsistencies for which Mrs. Aquino has been criticized: lack of clear priorities; tactical blundering; and the strong influence of her relatives over national policy.</s>

<s docid="AP900408-0059" num="14" wdcount="41"> It also reinforced the suspicion among liberals that for all her rhetoric, Mrs. Aquino does not share the deep commitment to social change which they expected when she took power in the 1986 ``people power'' uprising against the late Ferdinand Marcos.</s>

<s docid="AP900408-0059" num="15" wdcount="18"> ``The sincerity of Corazon Aquino is being seriously questioned,'' wrote columnist Ninez Cacho-Olivares in the Philippine Daily Inquirer.</s>

<s docid="AP900408-0059" num="16" wdcount="10"> Land reform, ``the centerpiece program of her administration, is dead''.</s>

<s docid="AP900408-0059" num="17" wdcount="27"> Abad's troubles began in February when he tried unsuccessfully to block the lease of government land in Cavite province to Japan's Marubeni Corp., for an industrial park.</s>

<s docid="AP900408-0059" num="18" wdcount="27"> Although the deal was approved by the National Development Corp., Abad, a former congressman, said the land should be distributed to peasants under the agrarian reform program.</s>

<s docid="AP900408-0059" num="19" wdcount="22"> The Department of Trade and Industry said the Marubeni deal was crucial to attracting much-needed foreign investment for the government's industrialization program.</s>

<s docid="AP900408-0059" num="20" wdcount="32"> But the Department of Agrarian Reform said if the Cavite land was exempted, hundreds of landlords would try to have their property declared as a potential industrial site to avoid losing title.</s>

<s docid="AP900408-0059" num="21" wdcount="20"> The presidential staff finally worked out a compromise under which farmers would be offered either land or a cash settlement.</s>

<s docid="AP900408-0059" num="22" wdcount="12"> Abad reluctantly agreed to the formula under repeated orders from Mrs. Aquino.</s>

<s docid="AP900408-0059" num="23" wdcount="23"> Abad's firm stand, however, alarmed landowners in Congress, who floated rumors in the press that the Agrarian Reform Department was riddled with Communists.</s>

<s docid="AP900408-0059" num="24" wdcount="27"> Lawmakers on the Commission on Appointments who belong to the pro-Aquino Struggle of the Democratic Filipino Party blocked Abad's confirmation through eight hearings until he finally resigned.</s>

<s docid="AP900408-0059" num="25" wdcount="13"> Despite the party's ``victory,'' poltical damage to it and Mrs. Aquino was considerable.</s>

<s docid="AP900408-0059" num="26" wdcount="31"> The Manila press transformed Abad into a folk hero, depicting him as the champion of the farmer against political barons of the Struggle of the Democratic Filipino Party, dubbed ``Landlord-Dominated Party''.</s>

<s docid="AP900408-0059" num="27" wdcount="6"> ``Worry not about Abad's destiny, Mrs.</s>

<s docid="AP900408-0059" num="28" wdcount="9"> President,'' wrote columnist Carol Arguillas in The Manila Chronicle.</s>

<s docid="AP900408-0059" num="29" wdcount="13"> ``Worry about yours and how you blew the last chance'' for liberal support.</s>

<s docid="AP900408-0059" num="30" wdcount="14"> Mrs. Aquino pledged publicly to work for Abad's confirmation, but her lobbying appeared ineffectual.</s>

<s docid="AP900408-0059" num="31" wdcount="20"> Abad's strongest opponents included politicians who consistently support Mrs. Aquino, leading to speculation she was not disappointed when he departed.</s>

<s docid="AP900408-0059" num="32" wdcount="16"> Abad's opponents included her younger brother, Rep. Jose ``Peping'' Cojuangco, who wields considerable influence in government.</s>

<s docid="AP900408-0059" num="33" wdcount="18"> ``There is no way Cory Aquino will challenge Peping,'' said one Western diplomat, speaking on condition of anonymity.</s>

<s docid="AP900408-0059" num="34" wdcount="7"> Mrs. Aquino comes from a landlord family.</s>

<s docid="AP900408-0059" num="35" wdcount="16"> She and her brothers and sisters are partners in a 14,500-acre sugar plantation in Tarlac province.</s>

<s docid="AP900408-0059" num="36" wdcount="19"> Rather than break up the estate, they used a legal option and created a ``profit-sharing'' plan for the tenants.</s>

<s docid="AP900408-0059" num="37" wdcount="24"> The Abad controversy was the latest in a series of blows to the agrarian reform program, once touted as the ``centerpiece'' of the administration.</s>

<s docid="AP900408-0059" num="38" wdcount="20"> Last year, Agrarian Reform Secretary Philip Juico resigned after disclosures that his department paid vastly inflated sums for marginal land.</s>

<s docid="AP900408-0059" num="39" wdcount="27"> His successor, Miriam Defensor Santiago, was repeatedly rejected by the Commission on Appointments, only to be reappointed until Mrs. Aquino replaced her with Abad on Dec. 31.</s>

<s docid="AP900408-0059" num="40" wdcount="7"> No reason for the change was given.</s>

<s docid="AP900408-0059" num="41" wdcount="21"> But Mrs. Santiago claims she did not display sufficient public loyalty to Mrs. Aquino during a coup attempt in early December.</s>

<s docid="AP900408-0059" num="42" wdcount="23"> Agrarian reform was widely seen as a means for breaking the power of landlord families and uplifting the livelihood of millions of peasants.</s>

<s docid="AP900408-0059" num="43" wdcount="13"> The program was advertised as essential in curbing the 21-year-old rural-based Marxist insurgency.</s>

<s docid="AP900408-0059" num="44" wdcount="14"> Mrs. Aquino proclaimed a land reform program in 1987 but left details to Congress.</s>

<s docid="AP900408-0059" num="45" wdcount="20"> The final bill contained so many pro-landlord loopholes that several of its original sponsors, including Abad, voted against it .</s>
</TEXT>
<NOTE>

<s docid="AP900408-0059" num="46" wdcount="2"> EDITOR'S NOTE</s>
</NOTE>
<TEXT>

<s docid="AP900408-0059" num="47" wdcount="15"> Robert H. Reid has been the AP bureau chief in Manila since September 1986 .</s>
</TEXT>
</DOC>
