<DOC>
<DOCNO>

<s docid="AP900829-0044" num="1" wdcount="1"> AP900829-0044</s>
</DOCNO>
<FILEID>

<s docid="AP900829-0044" num="2" wdcount="2"> AP-NR-08-29-90 0838EST</s>
</FILEID>
<FIRST>

<s docid="AP900829-0044" num="3" wdcount="5"> r i PM-Philippines 08-29 0338</s>
</FIRST>
<SECOND>

<s docid="AP900829-0044" num="4" wdcount="1"> PM-Philippines,0348</s>
</SECOND>
<HEAD>

<s docid="AP900829-0044" num="5" wdcount="10"> Aquino Calls for Peace Talks With Communist Rebels, Rebellious Troops</s>
</HEAD>
<BYLINE>

<s docid="AP900829-0044" num="6" wdcount="3"> By EILEEN GUERRERO</s>
</BYLINE>
<BYLINE>

<s docid="AP900829-0044" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900829-0044" num="8" wdcount="3"> MANILA, Philippines (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900829-0044" num="9" wdcount="27"> President Corazon Aquino today reversed a long-held policy and said she was willing to negotiate cease-fires with Communist guerrillas and former soldiers who have staged coup attempts.</s>

<s docid="AP900829-0044" num="10" wdcount="19"> Mrs. Aquino also invited the opposition to join the talks, including her most outspoken critic, Sen. Juan Ponce Enrile.</s>

<s docid="AP900829-0044" num="11" wdcount="8"> Manila has been rocked by almost daily explosions.</s>

<s docid="AP900829-0044" num="12" wdcount="28"> Although no one has claimed responsibility for the blasts, the government has blamed them on former soldiers who have repeatedly tried to toppled Mrs. Aquino in coup attempts.</s>

<s docid="AP900829-0044" num="13" wdcount="14"> The Communist rebels have been waging a 21-year rebellion to establish a Marxist state.</s>

<s docid="AP900829-0044" num="14" wdcount="9"> The last cease-fire with them collapsed in early 1987.</s>

<s docid="AP900829-0044" num="15" wdcount="30"> Sen. Wigberto Tanada called for a truce between the government and the Communist rebels after a major earthquake in the Philippines on July 16, but Mrs. Aquino rejected the proposal.</s>

<s docid="AP900829-0044" num="16" wdcount="29"> On Tuesday, a pro-Aquino senator, Orlando Mercado, urged Mrs. Aquino to put aside differences with her political foes and begin to discuss the nation's security problems and economic woes.</s>

<s docid="AP900829-0044" num="17" wdcount="27"> Enrile said he was willing to reconcile with Mrs. Aquino, who fired him as defense minister after he was implicated in a coup attempt in November 1986.</s>

<s docid="AP900829-0044" num="18" wdcount="25"> Mrs. Aquino said in a statement today that Mercado and Enrile are welcome to join discussions now being held by a committee of Cabinet members.</s>

<s docid="AP900829-0044" num="19" wdcount="28"> Defense Secretary Fidel Ramos has adamantly refused any cease-fire with the Communist guerrillas since November 1986 when the Aquino government negotiated with the rebels during a 60-day truce.</s>

<s docid="AP900829-0044" num="20" wdcount="18"> Ramos, a member of the Cabinet committee, has been credited with crushing six coup attempts against Mrs. Aquino.</s>

<s docid="AP900829-0044" num="21" wdcount="25"> Communists have accused him of whipping up threats of another coup attempt against Mrs. Aquino so that the civilian leadership would become indebted to him.</s>

<s docid="AP900829-0044" num="22" wdcount="5"> Ramos has denied all allegations.</s>

<s docid="AP900829-0044" num="23" wdcount="24"> The last cease-fire with the rebels collapsed in January 1987 after troops fired on farmers demonstrating outside Mrs. Aquino's office for land reform .</s>
</TEXT>
</DOC>
