<DOC>
<DOCNO>

<s docid="LA052089-0075" num="1" wdcount="1"> LA052089-0075</s>
</DOCNO>
<DOCID>

<s docid="LA052089-0075" num="2" wdcount="1"> 59513</s>
</DOCID>
<DATE>
<P>

<s docid="LA052089-0075" num="3" wdcount="6"> May 20, 1989, Saturday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA052089-0075" num="4" wdcount="8"> Part 1; Page 5; Column 2; Foreign Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA052089-0075" num="5" wdcount="2"> 573 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA052089-0075" num="6" wdcount="9"> AQUINO RULES OUT RETURN OF MARCOS, EVEN FOR BURIAL</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA052089-0075" num="7" wdcount="3"> By CHARLES P.</s>

<s docid="LA052089-0075" num="8" wdcount="4"> WALLACE, Times Staff Writer</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA052089-0075" num="9" wdcount="1"> MANILA</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA052089-0075" num="10" wdcount="17"> President Corazon Aquino said Friday that for security reasons she would not permit deposed President Ferdinand E.</s>

<s docid="LA052089-0075" num="11" wdcount="8"> Marcos to be buried in the Philippines .</s>
</P>
<P>

<s docid="LA052089-0075" num="12" wdcount="22"> Marcos was reported to be in "very critical condition" in Honolulu, where he has lived in exile since his ouster in 1986.</s>

<s docid="LA052089-0075" num="13" wdcount="15"> Hospital officials there said that he rallied slightly Friday but remained in extremely critical condition.</s>

<s docid="LA052089-0075" num="14" wdcount="18"> The 71-year-old former president has been suffering from heart, lung and kidney disorders as well as pneumonia .</s>
</P>
<P>

<s docid="LA052089-0075" num="15" wdcount="31"> His frail body attached to a respirator and a hemodialysis blood-cleansing machine, Marcos is unconscious most of the time but occasionally shows faint signs of life, doctors in Hawaii said .</s>
</P>
<P>

<s docid="LA052089-0075" num="16" wdcount="22"> Medical sources said that he is being treated with antibiotics and heart medication but that he could die at "any time" .</s>
</P>
<P>

<s docid="LA052089-0075" num="17" wdcount="9"> Radio stations here broadcast hourly reports on Marcos' condition.</s>

<s docid="LA052089-0075" num="18" wdcount="26"> Philippine officials were asked repeatedly whether the Aquino government's refusal to allow Marcos to return to the country would remain in effect after his death .</s>
</P>
<P>

<s docid="LA052089-0075" num="19" wdcount="30"> One radio station broadcast an interview with Marcos' wife, Imelda, at the St. Francis Medical Center in Honolulu, where she was said to be maintaining a vigil at his bedside.</s>

<s docid="LA052089-0075" num="20" wdcount="20"> She was quoted as appealing to Aquino to "open her heart" and allow Marcos to return to the Philippines .</s>
</P>
<P>

<s docid="LA052089-0075" num="21" wdcount="17"> Aquino said she would not alter her position but that she had prayed for Marcos' recovery .</s>
</P>
<P>

<s docid="LA052089-0075" num="22" wdcount="5"> "I regret to inform Mrs.</s>

<s docid="LA052089-0075" num="23" wdcount="9"> Marcos that as much as I agree that Mr.</s>

<s docid="LA052089-0075" num="24" wdcount="27"> Marcos has his rights, I still have to consider also the rights and the interests of millions of Filipinos," Aquino told reporters at the presidential palace .</s>
</P>
<P>

<s docid="LA052089-0075" num="25" wdcount="33"> "I have said . . . in the past that we will not allow his remains to be brought back here, and we have already taken plans to avoid any untoward incident" .</s>
</P>
<P>

<s docid="LA052089-0075" num="26" wdcount="28"> Nonetheless, Marcos supporters announced that they will march through the capital today to support the former president's demand that he be allowed to die in the Philippines .</s>
</P>
<P>

<s docid="LA052089-0075" num="27" wdcount="25"> Despite charges that Marcos and his inner circle looted the government treasury of billions of dollars, the former president still has a significant following here.</s>

<s docid="LA052089-0075" num="28" wdcount="11"> In the Philippines, personal loyalty is considered a sacred debt .</s>
</P>
<P>
</P>
<P>

<s docid="LA052089-0075" num="29" wdcount="2"> Attempted Coups</s>
</P>
<P>

<s docid="LA052089-0075" num="30" wdcount="20"> Government officials have accused Marcos supporters of taking part in at least two attempted coups against the Aquino government .</s>
</P>
<P>

<s docid="LA052089-0075" num="31" wdcount="23"> Aquino evidently is concerned that even after death, the return of Marcos' remains could spark violence or galvanize opposition to her government .</s>
</P>
<P>

<s docid="LA052089-0075" num="32" wdcount="30"> Aquino's national security adviser, Rafael Ileto, told reporters Friday that the Philippine army is prepared for any emergency that might be provoked by the death of the former president .</s>
</P>
<P>

<s docid="LA052089-0075" num="33" wdcount="23"> He was quoted as saying that while Marcos is no longer a threat to the government, his supporters "can still cause disruption" .</s>
</P>
<P>

<s docid="LA052089-0075" num="34" wdcount="24"> Marcos' mother, Josefa, died a year ago, but because Marcos has been barred from this country, the family refuses to have her remains interred.</s>

<s docid="LA052089-0075" num="35" wdcount="20"> A newspaper advertisement published on the first anniversary of her death May 4 said, "funeral arrangements will be announced" .</s>
</P>
<P>

<s docid="LA052089-0075" num="36" wdcount="23"> Marcos and his wife have been indicted by a federal grand jury in the United States on charges of racketeering, fraud and extortion.</s>

<s docid="LA052089-0075" num="37" wdcount="16"> Marcos has been excused from appearing in court up to now because of his failing health.</s>

<s docid="LA052089-0075" num="38" wdcount="9"> Imelda Marcos is free on $5 million bail .</s>
</P>
<P>

<s docid="LA052089-0075" num="39" wdcount="12"> Times staff writer Ron Harris, in Honolulu, contributed to this story .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA052089-0075" num="40" wdcount="14"> Photo, Imelda Marcos at Honolulu hospital where her husband, Ferdinand, is clinging to life.</s>

<s docid="LA052089-0075" num="41" wdcount="2"> Associated Press</s>
</P>
</GRAPHIC>
<SUBJECT>
<P>

<s docid="LA052089-0075" num="42" wdcount="13"> AQUINO, CORAZON; MARCOS, IMELDA; MARCOS, FERDINAND E; EXILES -- PHILIPPINES; HEADS OF STATE</s>
</P>
</SUBJECT>
</DOC>
