<DOC>
<DOCNO>

<s docid="LA101390-0087" num="1" wdcount="1"> LA101390-0087</s>
</DOCNO>
<DOCID>

<s docid="LA101390-0087" num="2" wdcount="1"> 291853</s>
</DOCID>
<DATE>
<P>

<s docid="LA101390-0087" num="3" wdcount="6"> October 13, 1990, Saturday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA101390-0087" num="4" wdcount="8"> Part A; Page 3; Column 1; Foreign Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA101390-0087" num="5" wdcount="2"> 632 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA101390-0087" num="6" wdcount="4"> PHILIPPINES / COUP MANIA;</s>
</P>
<P>

<s docid="LA101390-0087" num="7" wdcount="6"> REVOLT IS OVER, BUT DANGER REMAINS</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA101390-0087" num="8" wdcount="6"> By BOB DROGIN, TIMES STAFF WRITER</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA101390-0087" num="9" wdcount="1"> MANILA</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA101390-0087" num="10" wdcount="31"> The quick collapse of a bizarre military revolt on the Philippines' second-largest island leaves President Corazon Aquino's beleaguered government with a muddied victory at best and clear danger signs ahead .</s>
</P>
<P>

<s docid="LA101390-0087" num="11" wdcount="42"> Analysts here say Aquino's immediate use of small bombers and artillery to end a pocket rebellion led by renegade army Col. Alexander Noble on the north coast of Mindanao helps counter oft-heard criticism that her four-year-old government is indecisive and inept .</s>
</P>
<P>

<s docid="LA101390-0087" num="12" wdcount="35"> And despite widespread fears that the Oct. 4-6 uprising would quickly spread to military garrisons on other islands and become a major threat to Aquino, leaders of the rightist military underground failed to move .</s>
</P>
<P>

<s docid="LA101390-0087" num="13" wdcount="13"> "It was the coup attempt that didn't catch fire," one Western diplomat said.</s>

<s docid="LA101390-0087" num="14" wdcount="9"> "It sort of fizzled before anything could happen" .</s>
</P>
<P>

<s docid="LA101390-0087" num="15" wdcount="14"> But he and other diplomats see little benefit for Aquino's battered image overseas .</s>
</P>
<P>

<s docid="LA101390-0087" num="16" wdcount="12"> "The international consequence is people saying, 'Yet another revolt in the Philippines'.</s>

<s docid="LA101390-0087" num="17" wdcount="10"> It's like she's under a perpetual onslaught," he said .</s>
</P>
<P>

<s docid="LA101390-0087" num="18" wdcount="61"> Moreover, questions linger as to how Noble and about 350 rebel troops so easily evaded a much-publicized military manhunt to drive 140 miles from their mountain sanctuary, pass unhindered through at least 10 military checkpoints and seize two military camps, including the command post of the general who had been ordered to capture him -- all without firing a shot .</s>
</P>
<P>

<s docid="LA101390-0087" num="19" wdcount="27"> Noble, once chief of staff of Aquino's own security detail, quickly linked up with Reuben Canoy, a local politician who heads the so-called Mindanao Independence Movement .</s>
</P>
<P>

<s docid="LA101390-0087" num="20" wdcount="29"> The resource-rich island has spawned secession groups since the 16th Century -- though Canoy's is the first to print fake passports and currency based on crude counterfeits of U.S.</s>

<s docid="LA101390-0087" num="21" wdcount="3"> $5 bills .</s>
</P>
<P>

<s docid="LA101390-0087" num="22" wdcount="12"> "The whole thing was kind of a farce," one Asian diplomat said.</s>

<s docid="LA101390-0087" num="23" wdcount="5"> "Only in the Philippines" .</s>
</P>
<P>

<s docid="LA101390-0087" num="24" wdcount="43"> Noble, best known for his long goatee and red stocking cap, quickly surrendered with most of his motley army of soldiers and Higaonon tribal militiamen after two World War II-vintage T-28 planes, called Tora Toras here, bombed and strafed one of the camps.</s>

<s docid="LA101390-0087" num="25" wdcount="13"> One plane later crashed and the pilot drowned, the revolt's only fatality .</s>
</P>
<P>

<s docid="LA101390-0087" num="26" wdcount="17"> Aquino has now survived two major coup attempts and half a dozen assorted and aborted military mutinies.</s>

<s docid="LA101390-0087" num="27" wdcount="23"> Most ended in embarrassing standoffs or dragged on for days, as top military leaders hedged on ordering troops to fire on other soldiers.</s>

<s docid="LA101390-0087" num="28" wdcount="16"> In one case, mutineers were ordered to do push-ups and attend Bible class as punishment .</s>
</P>
<P>

<s docid="LA101390-0087" num="29" wdcount="22"> "This time was a different government response altogether, which Noble clearly had underestimated," said University of the Philippines political scientist Alex Magno.</s>

<s docid="LA101390-0087" num="30" wdcount="11"> "He expected another standoff and hoped for other camps to defect.</s>

<s docid="LA101390-0087" num="31" wdcount="5"> He got bombed instead" .</s>
</P>
<P>

<s docid="LA101390-0087" num="32" wdcount="20"> After the revolt, the government toughened its anti-coup law, boosting the maximum penalty from 12 years to life in prison.</s>

<s docid="LA101390-0087" num="33" wdcount="18"> Aquino's spokesman, Tomas Gomez III, urged other rebel leaders to take "the honorable way out" -- suicide .</s>
</P>
<P>

<s docid="LA101390-0087" num="34" wdcount="35"> Ironically, Noble made his move on the day a presidential fact-finding board issued a long-awaited 609-page report on the causes of last December's coup attempt in Manila, which left more than 100 people dead .</s>
</P>
<P>

<s docid="LA101390-0087" num="35" wdcount="32"> After 332 witnesses, 226 sworn statements and 4,100 documents, the so-called Davide Commission concluded that coup attempts are likely to continue -- but unlikely to succeed -- for the indefinite future .</s>
</P>
<P>

<s docid="LA101390-0087" num="36" wdcount="28"> Commission member Delfin Lazaro estimated that 70 officers involved in last December's coup attempt, which came closest to toppling Aquino, are still at large and still plotting .</s>
</P>
<P>

<s docid="LA101390-0087" num="37" wdcount="20"> "It's going to be very difficult for them to get the critical mass to launch a successful coup," he said.</s>

<s docid="LA101390-0087" num="38" wdcount="4"> "But they'll keep trying.</s>

<s docid="LA101390-0087" num="39" wdcount="5"> What else can they do"?</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA101390-0087" num="40" wdcount="9"> Photo, Renegade army Col. Alexander Noble after his surrender.</s>

<s docid="LA101390-0087" num="41" wdcount="15"> He led the latest in a long string of attempts to bring down Corazon Aquino.</s>

<s docid="LA101390-0087" num="42" wdcount="2"> Agence France-Presse</s>
</P>
</GRAPHIC>
<SUBJECT>
<P>

<s docid="LA101390-0087" num="43" wdcount="15"> PHILIPPINES -- REVOLTS; PHILIPPINES -- GOVERNMENT; PHILIPPINES -- ARMED FORCES; AQUINO, CORAZON; GUERRILLAS -- PHILIPPINES</s>
</P>
</SUBJECT>
</DOC>
