<DOC>
<DOCNO>

<s docid="LA120389-0170" num="1" wdcount="1"> LA120389-0170</s>
</DOCNO>
<DOCID>

<s docid="LA120389-0170" num="2" wdcount="1"> 143394</s>
</DOCID>
<DATE>
<P>

<s docid="LA120389-0170" num="3" wdcount="6"> December 3, 1989, Sunday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA120389-0170" num="4" wdcount="8"> Part A; Page 17; Column 1; Foreign Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA120389-0170" num="5" wdcount="2"> 518 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA120389-0170" num="6" wdcount="7"> REBELS 'HAVE RIGHT' TO ACT, LAUREL SAYS;</s>
</P>
<P>

<s docid="LA120389-0170" num="7" wdcount="10"> PHILIPPINES: CORAZON AQUINO'S VICE PRESIDENT REFUSES TO CONDEMN THE INSURRECTION.</s>

<s docid="LA120389-0170" num="8" wdcount="11"> AND HE PREDICTS THAT IT MAY LEAD TO CIVIL WAR .</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA120389-0170" num="9" wdcount="6"> By BOB DROGIN, TIMES STAFF WRITER</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA120389-0170" num="10" wdcount="2"> HONG KONG</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA120389-0170" num="11" wdcount="33"> Philippine Vice President and opposition leader Salvador H. Laurel declined Saturday night to condemn the armed insurrection in his country and said the rebels "have the right" to try to seize power .</s>
</P>
<P>

<s docid="LA120389-0170" num="12" wdcount="18"> Laurel also said that the rebels will not surrender to President Corazon Aquino's forces, as she has demanded.</s>

<s docid="LA120389-0170" num="13" wdcount="22"> He predicted that the fighting may turn to civil war if reported rebel reinforcements arrive from Cebu, Mindanao and other islands .</s>
</P>
<P>

<s docid="LA120389-0170" num="14" wdcount="20"> "I don't think this is going to end right away," he said in a suite in the Peninsula Hotel here.</s>

<s docid="LA120389-0170" num="15" wdcount="14"> "I think it's going to be a long, protracted thing, even civil war" .</s>
</P>
<P>

<s docid="LA120389-0170" num="16" wdcount="19"> Although he grinned broadly and laughed often during the interview, Laurel denied that he was "cheering" for the rebels.</s>

<s docid="LA120389-0170" num="17" wdcount="15"> He refused, however, to condemn their use of violence against a constitutionally elected government .</s>
</P>
<P>

<s docid="LA120389-0170" num="18" wdcount="12"> "I don't want to prejudge their goals or objectives," he said .</s>
</P>
<P>

<s docid="LA120389-0170" num="19" wdcount="14"> "Everybody should try to win with a ballot rather than a bullet," he added.</s>

<s docid="LA120389-0170" num="20" wdcount="11"> "But democracy does not preclude that as a last resort" .</s>
</P>
<P>

<s docid="LA120389-0170" num="21" wdcount="26"> Laurel, who is known as Doy, broke with Aquino shortly after they took office in 1986 following a popular uprising that toppled former President Ferdinand E.</s>

<s docid="LA120389-0170" num="22" wdcount="19"> Marcos. Since then, Laurel has criticized Aquino frequently in his role as head of the opposition Nacionalista Party .</s>
</P>
<P>

<s docid="LA120389-0170" num="23" wdcount="13"> Laurel said he was in London early Friday when the Philippine fighting began.</s>

<s docid="LA120389-0170" num="24" wdcount="31"> He flew to Hong Kong but was stranded here with scores of journalists because the Philippines' two international airports, in Manila and Cebu, have been closed since the fighting began .</s>
</P>
<P>

<s docid="LA120389-0170" num="25" wdcount="24"> Laurel said 18 Nacionalista leaders were meeting at the Intercontinental Hotel in Manila late Saturday despite the presence of rebel holdouts in the hotel.</s>

<s docid="LA120389-0170" num="26" wdcount="17"> He called the group his party's "junta," but said they have no ties to the rebels .</s>
</P>
<P>

<s docid="LA120389-0170" num="27" wdcount="15"> Laurel criticized Aquino for asking the United States to help bolster her beleaguered forces Friday.</s>

<s docid="LA120389-0170" num="28" wdcount="23"> U.S. officials have said F-4 Phantom jets flew over rebel aircraft to keep them grounded but did not drop bombs or fire .</s>
</P>
<P>

<s docid="LA120389-0170" num="29" wdcount="33"> But Laurel said the U.S. fighter-bombers destroyed a Philippine air force fuel dump and other facilities at Sangley Point and fired rockets that killed civilians near Camp Aguinaldo, the armed forces headquarters .</s>
</P>
<P>

<s docid="LA120389-0170" num="30" wdcount="38"> Laurel added that Aquino now is "completely beholden" to the United States just as exploratory talks on renegotiating leases for Clark Air Base and Subic Bay Naval Base, the two largest U.S. military facilities abroad, are beginning .</s>
</P>
<P>

<s docid="LA120389-0170" num="31" wdcount="20"> Laurel's companion, Homobono Adaza, a former member of Parliament under Marcos and a Nacionalista member, also defended the rebels .</s>
</P>
<P>

<s docid="LA120389-0170" num="32" wdcount="7"> "These are the reformist elements," he said.</s>

<s docid="LA120389-0170" num="33" wdcount="8"> "They are trying to reform the government" .</s>
</P>
<P>

<s docid="LA120389-0170" num="34" wdcount="23"> Laurel said the coup occurred because Aquino "failed to unite the nation" or the armed forces, leading to divided loyalties and fragmentation .</s>
</P>
<P>

<s docid="LA120389-0170" num="35" wdcount="21"> He said she also failed to enforce the law "against graft and corruption" and had failed to deliver critical services .</s>
</P>
<P>

<s docid="LA120389-0170" num="36" wdcount="6"> "There's a power shortage," he said.</s>

<s docid="LA120389-0170" num="37" wdcount="3"> "A rice shortage.</s>

<s docid="LA120389-0170" num="38" wdcount="3"> A transport crisis.</s>

<s docid="LA120389-0170" num="39" wdcount="5"> The people are fed up.</s>

<s docid="LA120389-0170" num="40" wdcount="6"> They're worse off than ever" .</s>
</P>
</TEXT>
<SUBJECT>
<P>

<s docid="LA120389-0170" num="41" wdcount="20"> LAUREL, SALVADOR; AQUINO, CORAZON; PHILIPPINES -- REVOLTS; PHILIPPINES -- GOVERNMENT; GUERRILLAS -- PHILIPPINES; UNITED STATES -- MILITARY AID -- PHILIPPINES</s>
</P>
</SUBJECT>
</DOC>
