<DOC>
<DOCNO>

<s docid="LA120189-0122" num="1" wdcount="1"> LA120189-0122</s>
</DOCNO>
<DOCID>

<s docid="LA120189-0122" num="2" wdcount="1"> 142393</s>
</DOCID>
<DATE>
<P>

<s docid="LA120189-0122" num="3" wdcount="6"> December 1, 1989, Friday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA120189-0122" num="4" wdcount="9"> Metro; Part B; Page 3; Column 1; Metro Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA120189-0122" num="5" wdcount="2"> 392 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA120189-0122" num="6" wdcount="7"> AQUINO ALLIES, FOES IN CONFRONTATION AT CONSULATE</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA120189-0122" num="7" wdcount="6"> By HECTOR TOBAR, TIMES STAFF WRITER</s>
</P>
</BYLINE>
<TEXT>
<P>

<s docid="LA120189-0122" num="8" wdcount="38"> As a military coup attempt unfolded in their homeland 7,000 miles away, supporters of the rebellious soldiers engaged in a shouting match Thursday night with supporters of President Corazon Aquino at the Philippine Consulate in Los Angeles .</s>
</P>
<P>

<s docid="LA120189-0122" num="9" wdcount="34"> About 30 members of the Filipino-American Movement for a Better Philippines held a candlelight vigil outside the consulate on Wilshire Boulevard to express sympathy with the coup led by officers linked to renegade Lt.</s>

<s docid="LA120189-0122" num="10" wdcount="4"> Col. Gregorio Honasan .</s>
</P>
<P>

<s docid="LA120189-0122" num="11" wdcount="18"> "We are calling for Mrs. Aquino to step down immediately," said Milo Castelo, 45, a Los Angeles attorney.</s>

<s docid="LA120189-0122" num="12" wdcount="15"> He said the Aquino government is "inept and incompetent" and guilty of "rampant corruption" .</s>
</P>
<P>

<s docid="LA120189-0122" num="13" wdcount="42"> Castelo and a handful of the protesters then entered the office building and took the elevator to the 12th-floor consulate, where a coalition of four Filipino groups in Los Angeles that support the Aquino government had just completed a press conference .</s>
</P>
<P>

<s docid="LA120189-0122" num="14" wdcount="26"> Half a dozen television news crews watched as the anti-government protesters confronted the acting consul general for the Philippines in Los Angeles, Willy C. Gaa .</s>
</P>
<P>

<s docid="LA120189-0122" num="15" wdcount="21"> "We are in sympathy with the coup in the Philippines"! announced Eli Swing, 49, a Los Angeles real estate agent .</s>
</P>
<P>

<s docid="LA120189-0122" num="16" wdcount="10"> The consul general remained silent, glaring at the protesters .</s>
</P>
<P>

<s docid="LA120189-0122" num="17" wdcount="15"> But Danny Lamila, a representative of the Philippines Liberal Party, loudly defended the government .</s>
</P>
<P>

<s docid="LA120189-0122" num="18" wdcount="9"> "These people staging the coup are criminals," Lamila yelled.</s>

<s docid="LA120189-0122" num="19" wdcount="5"> "They are fugitives from justice"!</s>
</P>
<P>

<s docid="LA120189-0122" num="20" wdcount="14"> After a few minutes, the 20 Aquino supporters in the room began chanting "Cory!</s>

<s docid="LA120189-0122" num="21" wdcount="14"> Cory"! The anti-government protesters then left the consular offices and order was restored .</s>
</P>
<P>

<s docid="LA120189-0122" num="22" wdcount="29"> Greg Santillas of the Campaign for Democracy and Independence said he believes that most of the estimated 350,000 Filipinos living in Los Angeles County oppose the military coup .</s>
</P>
<P>

<s docid="LA120189-0122" num="23" wdcount="15"> "We're here not only to support the president, but also the democratic institutions," he said.</s>

<s docid="LA120189-0122" num="24" wdcount="12"> "The military is a dangerous leftover from the dictatorship (of Ferdinand Marcos).</s>

<s docid="LA120189-0122" num="25" wdcount="13"> We don't want the government to be a hostage to the military" .</s>
</P>
<P>

<s docid="LA120189-0122" num="26" wdcount="22"> Also present at the press conference was Andrea Aquino, 50, the niece of assassinated Marcos opponent Benigno Aquino, Cory Aquino's husband .</s>
</P>
<P>

<s docid="LA120189-0122" num="27" wdcount="11"> "I support democracy and the government against the coup," she said.</s>

<s docid="LA120189-0122" num="28" wdcount="10"> "I think it's about time these renegades are punished" .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA120189-0122" num="29" wdcount="15"> Photo, Aquino foe Rosita Labello shouts at Danny Lamila, a representative of the Liberal Party.</s>

<s docid="LA120189-0122" num="30" wdcount="8"> In middle is Willy Gaa, acting consul general.</s>

<s docid="LA120189-0122" num="31" wdcount="15"> Photo, About 30 protesters stand vigil outside the Philippine Consulate in support of rebel officers.</s>

<s docid="LA120189-0122" num="32" wdcount="6"> ROBERT DURRELL / Los Angeles Times</s>
</P>
</GRAPHIC>
<SUBJECT>
<P>

<s docid="LA120189-0122" num="33" wdcount="24"> AQUINO, CORAZON; FILIPINO AMERICAN MOVEMENT FOR A BETTER PHILIPPINES; PHILIPPINES -- REVOLTS; PHILIPPINES -- ARMED FORCES; FILIPINOS -- LOS ANGELES; DEMONSTRATIONS -- LOS ANGELES</s>
</P>
</SUBJECT>
</DOC>
