<DOC>
<DOCNO>

<s docid="AP901127-0119" num="1" wdcount="1"> AP901127-0119</s>
</DOCNO>
<FILEID>

<s docid="AP901127-0119" num="2" wdcount="2"> AP-NY-11-27-90 1759EST</s>
</FILEID>
<FIRST>

<s docid="AP901127-0119" num="3" wdcount="7"> u i AM-Britain-Politics 1stLd-Writethru a0638 11-27 0755</s>
</FIRST>
<SECOND>

<s docid="AP901127-0119" num="4" wdcount="4"> AM-Britain-Politics, 1st Ld-Writethru, a0638,0931</s>
</SECOND>
<HEAD>

<s docid="AP901127-0119" num="5" wdcount="9"> John Major to Become British Prime Minister Succeeding Thatcher</s>
</HEAD>
<NOTE>

<s docid="AP901127-0119" num="6" wdcount="26"> Eds: LEADS with 19 grafs to CORRECT time element 4th graf `Major, the' to Tuesday night sted Thursday, ADDS background on rapid development of leadership challenge.</s>

<s docid="AP901127-0119" num="7" wdcount="7"> Picks up graf 15 pvs, `Hurd said...'</s>
</NOTE>
<HEAD>

<s docid="AP901127-0119" num="8" wdcount="2"> LaserPhotos LON1,3,4,14</s>
</HEAD>
<BYLINE>

<s docid="AP901127-0119" num="9" wdcount="3"> By MAUREEN JOHNSON</s>
</BYLINE>
<BYLINE>

<s docid="AP901127-0119" num="10" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP901127-0119" num="11" wdcount="2"> LONDON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP901127-0119" num="12" wdcount="27"> John Major, endorsed by Margaret Thatcher as the politician closest to her heart, was elected by the Conservative Party Tuesday night to succeed her as prime minister.</s>

<s docid="AP901127-0119" num="13" wdcount="35"> Major, 47, fell two votes short of winning a majority in voting among the 372 Coservative Party members of Parliament, but his two opponents quickly conceded defeat and the party confirmed Major as the winner.</s>

<s docid="AP901127-0119" num="14" wdcount="29"> Mrs. Thatcher, ending 11 years in power, intended to submit her resignation to Queen Elizabeth II on Wednesday morning, and Major would then be called to lead the government.</s>

<s docid="AP901127-0119" num="15" wdcount="25"> Major, the chancellor of the exchequer, emerged from his official residence at 11 Downing St. Tuesday night smiling and holding hands with his wife, Norma.</s>

<s docid="AP901127-0119" num="16" wdcount="17"> Inside, Mrs. Thatcher, who came next door from the prime minister's 10 Downing Street residence, embraced Major.</s>

<s docid="AP901127-0119" num="17" wdcount="22"> ``I am thrilled and delighted that John Major is to succeed me,'' the ``Iron Lady'' said in a statement released by aides.</s>

<s docid="AP901127-0119" num="18" wdcount="34"> ``It is a very exciting thing to become leader of the Conservative Party, and particularly exciting, I think, to follow one of the most remarkable leaders the Conservative Party has ever had,'' Major said.</s>

<s docid="AP901127-0119" num="19" wdcount="8"> ``Our job now I think is quite clear.</s>

<s docid="AP901127-0119" num="20" wdcount="30"> We are going to unite totally and absolutely, and we're going to win the next general election,'' said Major, who will be the youngest British prime minister in this century.</s>

<s docid="AP901127-0119" num="21" wdcount="9"> Major received 185 votes, two short of a majority.</s>

<s docid="AP901127-0119" num="22" wdcount="14"> Former Defense Secretary Michael Heseltine received 131 and Foreign Secretary Douglas Hurd had 56.</s>

<s docid="AP901127-0119" num="23" wdcount="12"> Hurd and Heseltine conceded within minutes, and party officials declared Major elected.</s>

<s docid="AP901127-0119" num="24" wdcount="31"> The party had been torn by the sudden and unexpected leadership challenge by Heseltine, who last week stopped Mrs. Thatcher short of victory in the first round of the leadership race.</s>

<s docid="AP901127-0119" num="25" wdcount="24"> Mrs. Thatcher had not wanted to leave office, but she decided to resign last week after she was unable to put down Heseltine's challenge.</s>

<s docid="AP901127-0119" num="26" wdcount="13"> She said she resigned to let someone from the Cabinet stand against Heseltine.</s>

<s docid="AP901127-0119" num="27" wdcount="24"> Major and Foreign Secretary Douglas Hurd both joined the race, but before the vote her aides spread the word that she was backing Major.</s>

<s docid="AP901127-0119" num="28" wdcount="30"> The son of a circus performer and at one time a welfare recipient, Major personifies the values of self-reliance and hard work that Mrs. Thatcher had preached to the nation.</s>

<s docid="AP901127-0119" num="29" wdcount="27"> His election climaxed a month of British politics-turned-upside down, and the Western world's longest-serving head of government was driven from office by a revolt in party ranks.</s>

<s docid="AP901127-0119" num="30" wdcount="38"> Heading a government that was trailing the opposition Labor Party in the polls and suffering a losing streak in local Parliamentary elections, Mrs. Thatcher lost control of events after her deputy, Sir Geoffrey Howe, resigned on Nov. 1.</s>

<s docid="AP901127-0119" num="31" wdcount="34"> Howe, the fourth Cabinet member to resign because of disputes over policy toward the European Community, shocked the House of Commons on Nov. 13 by calling Mrs. Thatcher a threat to Britain's vital interests.</s>

<s docid="AP901127-0119" num="32" wdcount="9"> The next day, Heseltine announced he would challenge her.</s>

<s docid="AP901127-0119" num="33" wdcount="27"> Six days later, with Mrs. Thatcher at a 34-nation summit in Paris officially ending the Cold War, Heseltine polled enough votes to deny her re-election as leader.</s>

<s docid="AP901127-0119" num="34" wdcount="16"> Two days later, she decided to resign after party leaders told her she could not win.</s>

<s docid="AP901127-0119" num="35" wdcount="14"> Heseltine, 57, said Major's election ``lays the basis for the unity of our party''.</s>

<s docid="AP901127-0119" num="36" wdcount="17"> Hurd said the party needed to unite, and ``John Major is the right leader for this task''.</s>

<s docid="AP901127-0119" num="37" wdcount="11"> Opposition leaders derided Major's election as ``Thatcherism with a different face''.</s>

<s docid="AP901127-0119" num="38" wdcount="12"> The Conservatives' main rivals, the socialist Labor Party, demanded a general election.</s>

<s docid="AP901127-0119" num="39" wdcount="25"> ``John Major is a Thatcherette - that is how he sought election and that is how he got elected,'' said Labor Party leader Neil Kinnock.</s>

<s docid="AP901127-0119" num="40" wdcount="19"> ``It means that the policies that brought the poll tax, recession, heavy mortgages and rising unemployment will go on''.</s>

<s docid="AP901127-0119" num="41" wdcount="32"> During his five-day campaign, Major had aaid he would review the ``poll tax,'' an unpopular local tax brought in by Mrs. Thatcher, but he gave no other hints of differing with her.</s>

<s docid="AP901127-0119" num="42" wdcount="33"> While adopting a gentler tone on the contentious issue of Britain's involvement in Europe, he shares her opposition to a single European currency and shares her belief in tight restraint on government spending.</s>

<s docid="AP901127-0119" num="43" wdcount="14"> However, he insisted over the weekend, ``I am not running as `Son of Thatcher'.</s>

<s docid="AP901127-0119" num="44" wdcount="13"> I am running as myself, with my own priorities and my own programs''.</s>

<s docid="AP901127-0119" num="45" wdcount="19"> Major's victory ended a patient, four-year campaign by Heseltine to promote himself as a future leader of the party.</s>

<s docid="AP901127-0119" num="46" wdcount="9"> ``Tomorrow always dawns,'' he said, smiling after conceding defeat.</s>

<s docid="AP901127-0119" num="47" wdcount="19"> Major was elected to Parliament in 1979, was appointed foreign secretary and then chancellor of the exchequer last year.</s>

<s docid="AP901127-0119" num="48" wdcount="8"> He moved up quickly in the leadership race.</s>

<s docid="AP901127-0119" num="49" wdcount="26"> By the weekend, opinion polls showed that Major was nearly as highly regarded by the public as was Heseltine, who has been prominent for a decade.</s>

<s docid="AP901127-0119" num="50" wdcount="26"> Major attracted support from figures on the right wing of the Conservative Party, although his friends insisted Major's own views were more liberal than many supposed.</s>

<s docid="AP901127-0119" num="51" wdcount="14"> He described himself as conservative on economic issues but liberal on social issues .</s>
</TEXT>
</DOC>
