<DOC>
<DOCNO>

<s docid="FBIS4-24776" num="1" wdcount="1"> FBIS4-24776</s>
</DOCNO>
<HT>

<s docid="FBIS4-24776" num="2" wdcount="1"> "drchi106_h_94002"</s>
</HT>
<HEADER>
<AU>

<s docid="FBIS4-24776" num="3" wdcount="1"> FBIS-CHI-94-106</s>
</AU>

<s docid="FBIS4-24776" num="4" wdcount="2"> Daily Report</s>
<DATE1>

<s docid="FBIS4-24776" num="5" wdcount="3"> 7 May 1994</s>
</DATE1>
</HEADER>
<F>

<s docid="FBIS4-24776" num="6" wdcount="2"> West Europe</s>
</F>
<H3>
<TI>

<s docid="FBIS4-24776" num="7" wdcount="7"> Editorial Views Future of UK Prime Minister</s>
</TI>
</H3>
<HT>
<F>
<PHRASE>

<s docid="FBIS4-24776" num="8" wdcount="7"> Editorial Views Future of UK Prime Minister</s>
</PHRASE>
</F>
</HT>
<F>

<s docid="FBIS4-24776" num="9" wdcount="13"> HK0805015794 Hong Kong WEN WEI PO in Chinese 7 May 94 p A2</s>
</F>
<F>

<s docid="FBIS4-24776" num="10" wdcount="1"> HK0805015794</s>
</F>
<F>

<s docid="FBIS4-24776" num="11" wdcount="5"> Hong Kong WEN WEI PO</s>
</F>
<F>

<s docid="FBIS4-24776" num="12" wdcount="1"> Chinese</s>
</F>
<TEXT>

<s docid="FBIS4-24776" num="13" wdcount="1"> BFN</s>
<F>

<s docid="FBIS4-24776" num="14" wdcount="8"> [Editorial: "There Are Signs of Conservative Party Changing</s>
</F>

<s docid="FBIS4-24776" num="15" wdcount="26"> Its Leader"] [Text] In local government elections across Britain yesterday, the Conservatives suffered their worst defeat ever, losing control of 17 regional councils and 444 seats.</s>

<s docid="FBIS4-24776" num="16" wdcount="23"> As the ruling party, the Tories took just 27 percent of the vote, two percentage points lower than their rating in the polls.</s>

<s docid="FBIS4-24776" num="17" wdcount="25"> The results of the local elections showed that the Tories were reduced to the third party nationally, behind the Liberal Democrats and the Labour Party.</s>

<s docid="FBIS4-24776" num="18" wdcount="23"> The Labour Party controls 90 local councils, whereas the Conservatives only control 13, with a sharp contrast in strength between the two sides.</s>

<s docid="FBIS4-24776" num="19" wdcount="10"> The Liberal Democrats had a net gain of 378 seats.</s>

<s docid="FBIS4-24776" num="20" wdcount="19"> Even some former Conservative members of parliament announced publicly to reporters that they would vote for the Liberal Democrats.</s>

<s docid="FBIS4-24776" num="21" wdcount="34"> Of course, this was a measure taken by Tories under circumstances of an inevitable defeat to reduce losses by encouraging constituents, who resent the Tories, to vote for the Liberal Democrats rather than Labour.</s>

<s docid="FBIS4-24776" num="22" wdcount="12"> In the deep sorrow of defeat, some Conservatives are secretly feeling happy.</s>

<s docid="FBIS4-24776" num="23" wdcount="24"> They resent John Major's leadership, and would most willingly link Major's incompetence and lack of vision with the bitter defeat in the local elections.</s>

<s docid="FBIS4-24776" num="24" wdcount="28"> Even before all of the results were known, some Tories openly announced their determination to challenge John Major's position and remove him from office as early as possible.</s>

<s docid="FBIS4-24776" num="25" wdcount="29"> The right-winger Michael Portillo added salt to the wound by starting a dispute over the European issue, and highlighted John Major's image as a loser who fails to command.</s>

<s docid="FBIS4-24776" num="26" wdcount="29"> Obviously, all of these actions were long planned and are aimed at making John Major suffer an even greater defeat in the European Parliament elections scheduled for 9 June.</s>

<s docid="FBIS4-24776" num="27" wdcount="13"> Before 9 June, nobody will officially challenge for the position of party leader.</s>

<s docid="FBIS4-24776" num="28" wdcount="13"> But he who is in office must suffer the pain of electoral defeat.</s>

<s docid="FBIS4-24776" num="29" wdcount="24"> After 9 June, John Major will have to answer for all of the disasters, and it is time to use him as a scapegoat.</s>

<s docid="FBIS4-24776" num="30" wdcount="48"> John Major is someone who was propped up by Mrs. Thatcher, who supported appointing the mediocre John Major as her successor when she was utterly isolated so that one day she would be able to pull strings from behind the scenes and continue to pursue the Thatcher line.</s>

<s docid="FBIS4-24776" num="31" wdcount="23"> Nevertheless, people around John Major seriously pushed him to betray Thatcher's doctrine, while pursuing entirely new "leftist" policies and affecting John Major's moves.</s>

<s docid="FBIS4-24776" num="32" wdcount="15"> For a very long period, right-wingers and left-wingers argued over many domestic and world issues.</s>

<s docid="FBIS4-24776" num="33" wdcount="24"> John Major has always been weak and powerless, and vacillates to the left and to the right resulting in his own "crisis of honor".</s>

<s docid="FBIS4-24776" num="34" wdcount="30"> On the European issue, he stressed the imperative of maintaining the sovereignty, cultural traditions, and life-style of each country of the future European Union, while reflecting the islanders' mind set.</s>

<s docid="FBIS4-24776" num="35" wdcount="25"> On the one hand, he expressed the will to join the European family; on the other, he made one big stride closer to the right.</s>

<s docid="FBIS4-24776" num="36" wdcount="22"> While great skill is needed to have one's bread buttered on both sides, John Major has been relatively stupid in such circumstance.</s>

<s docid="FBIS4-24776" num="37" wdcount="29"> When expounding on such concepts, he set out a campaign to "return to basic values," with an emphasis on citizen self-discipline, taking social responsibility and obligations, and being upright.</s>

<s docid="FBIS4-24776" num="38" wdcount="25"> However, one scandal surfaced after another in his cabinet; consequently, British citizens saw how bombastic Major could be and how he failed to know himself.</s>

<s docid="FBIS4-24776" num="39" wdcount="7"> The scandals caused Major's reputation to collapse.</s>

<s docid="FBIS4-24776" num="40" wdcount="38"> For a long time, John Major has failed to resolve the economic crisis and has seriously jeopardized the interests of British people, who have become poorer with each passing day and suffer from a high rate of unemployment.</s>

<s docid="FBIS4-24776" num="41" wdcount="32"> At this critical juncture, John Major went back on promises made during the election campaign by increasing value-added tax on domestic fuel; as a result, things became even harder for the poor.</s>

<s docid="FBIS4-24776" num="42" wdcount="15"> He promised to reduce public expenditure, but on the contrary, it rose by 45.5 percent.</s>

<s docid="FBIS4-24776" num="43" wdcount="21"> [as published] John Major has become an expert in making "empty promises," while constituents continue to scorn this dishonest prime minister.</s>

<s docid="FBIS4-24776" num="44" wdcount="13"> Many Conservatives believe that John Major is driven by a gambler's mind set.</s>

<s docid="FBIS4-24776" num="45" wdcount="26"> At a time when his reputation was waning, he wanted to start an offensive in the arena of difficult world issues, regardless of British national strength.</s>

<s docid="FBIS4-24776" num="46" wdcount="36"> This being the case, he wanted to try his luck in Bosnia, as well as policy toward China; however, he was helpless in dealing with domestic economic issues which would only lead Britain to an impasse.</s>

<s docid="FBIS4-24776" num="47" wdcount="28"> It will be difficult for John Major to lead the Tories in the next general election; therefore, news spread earlier this year that John Major would be replaced.</s>

<s docid="FBIS4-24776" num="48" wdcount="15"> The setback which has resulted from defeats in the local elections is heavier than expected.</s>

<s docid="FBIS4-24776" num="49" wdcount="19"> To accelerate a leadership reshuffle, Conservatives have spread the opinion that "John Major is not up to his office".</s>

<s docid="FBIS4-24776" num="50" wdcount="20"> However, if politicians from various factions compete for office by taking a laissez-faire attitude, the Tory unity will be jeopardized.</s>

<s docid="FBIS4-24776" num="51" wdcount="24"> This being the case, a planned transfer of power, especially the reorganization of the cabinet and the replacement of the party chairman, is necessary.</s>

<s docid="FBIS4-24776" num="52" wdcount="19"> When the new party chairman is elected, the question of who will replace John Major will be settled too.</s>

<s docid="FBIS4-24776" num="53" wdcount="19"> Word has spread that John Major wants Chris Patten to become Conservative Party chairman; however, this proposal was rejected.</s>

<s docid="FBIS4-24776" num="54" wdcount="33"> That should have been a party secret; making public such an inside story would only provide evidence of political reality, namely, many Conservatives did not agree to Chris Patten contending for this position.</s>

<s docid="FBIS4-24776" num="55" wdcount="26"> There are no grounds to allow a politician who has lost a previous electoral campaign to canvass votes in the next one under unfavorable electoral circumstances.</s>

<s docid="FBIS4-24776" num="56" wdcount="20"> That would only aggravate the Tory's poor image as a party which enjoys little public support and has few talents.</s>

<s docid="FBIS4-24776" num="57" wdcount="34"> In actual fact, should John Major set out such a line in appointing people, that would only give more evidence of his poor ability, insight, and lack of judgment, as well as his self-knowledge.</s>

<s docid="FBIS4-24776" num="58" wdcount="24"> Now, it is just a matter of time until he leaves office; but nobody will let him make arrangements for the transfer of power.</s>

<s docid="FBIS4-24776" num="59" wdcount="22"> Work to seek a new leader will be conducted by veteran Tories; how can John Major be qualified for such a task?</s>
</TEXT>
</DOC>
