<DOC>
<DOCNO>

<s docid="FBIS3-1707" num="1" wdcount="1"> FBIS3-1707</s>
</DOCNO>
<HT>

<s docid="FBIS3-1707" num="2" wdcount="1"> "drchi040_a_94025"</s>
</HT>
<HEADER>
<AU>

<s docid="FBIS3-1707" num="3" wdcount="1"> FBIS-CHI-94-040</s>
</AU>

<s docid="FBIS3-1707" num="4" wdcount="3"> Document Type:Daily Report</s>
<DATE1>

<s docid="FBIS3-1707" num="5" wdcount="3"> 1 March 1994</s>
</DATE1>
</HEADER>
<F>

<s docid="FBIS3-1707" num="6" wdcount="2"> INTERNATIONAL AFFAIRS</s>
</F>
<F>

<s docid="FBIS3-1707" num="7" wdcount="1"> General</s>
</F>
<H3>
<TI>

<s docid="FBIS3-1707" num="8" wdcount="7"> President Clinton, John Major Emphasize `Special Relationship'</s>
</TI>
</H3>
<F>

<s docid="FBIS3-1707" num="9" wdcount="10"> OW0103084694 Beijing XINHUA in English 0807 GMT 1 Mar 94</s>
</F>
<F>

<s docid="FBIS3-1707" num="10" wdcount="1"> OW0103084694</s>
</F>
<F>

<s docid="FBIS3-1707" num="11" wdcount="2"> Beijing XINHUA</s>
</F>
<TEXT>

<s docid="FBIS3-1707" num="12" wdcount="1"> Language:</s>
<F>

<s docid="FBIS3-1707" num="13" wdcount="1"> English</s>
</F>

<s docid="FBIS3-1707" num="14" wdcount="9"> Article Type:BFN [Text] Washington, February 28 (XINHUA) -- U.S.</s>

<s docid="FBIS3-1707" num="15" wdcount="19"> President Bill Clinton, trying to brush aside recent differences with London, today stressed Washington's special transatlantic relationship with Britain.</s>

<s docid="FBIS3-1707" num="16" wdcount="52"> Welcoming British Prime Minister John Major in Pittsburgh, where major's grandfather and father once lived, Clinton said at the airport, "We're working together today to respond to the terrible tragedy in Bosnia to try to bring an end to the killing and to bring peace and to keep that conflict from spreading".</s>

<s docid="FBIS3-1707" num="17" wdcount="25"> For his part, Major said, pressure would be increased for the peace that every sensitive person wishes to see in that war-torn and troubled land.</s>

<s docid="FBIS3-1707" num="18" wdcount="32"> On Russia, Major said "A Russia that's a good neighbor to the United States and West would be one of the finest things that this generation could hand down to the next".</s>

<s docid="FBIS3-1707" num="19" wdcount="13"> Clinton will then share his Air Force One back to the nation's capital.</s>

<s docid="FBIS3-1707" num="20" wdcount="23"> Major will spend a night at the White House, the first foreign head of state to have this honor since Clinton became President.</s>

<s docid="FBIS3-1707" num="21" wdcount="26"> On Tuesday [1 March], the two leaders will begin their discussions on a wide range of issues including Russia, Bosnia, Northern Ireland and the world trade.</s>

<s docid="FBIS3-1707" num="22" wdcount="15"> The two will also discuss Northern Ireland and "what to do with NATO," Clinton said.</s>

<s docid="FBIS3-1707" num="23" wdcount="24"> Clinton and major will meet again in June in Europe during the commemoration of the 50th anniversary of D-Day of the second world war.</s>

<s docid="FBIS3-1707" num="24" wdcount="19"> Major said Clinton would visit Britain, and perhaps the Oxford University, Clinton's alma mater, during the June visit .</s>
</TEXT>
</DOC>
