<DOC>
<DOCNO>

<s docid="FBIS4-18298" num="1" wdcount="1"> FBIS4-18298</s>
</DOCNO>
<HT>

<s docid="FBIS4-18298" num="2" wdcount="1"> "drweu064__a94008"</s>
</HT>
<HEADER>
<AU>

<s docid="FBIS4-18298" num="3" wdcount="1"> FBIS-WEU-94-064-A</s>
</AU>

<s docid="FBIS4-18298" num="4" wdcount="2"> Daily Report</s>
<DATE1>

<s docid="FBIS4-18298" num="5" wdcount="3"> 4 Apr 1994</s>
</DATE1>
</HEADER>
<F>

<s docid="FBIS4-18298" num="6" wdcount="1"> ANNEX</s>
</F>
<F>

<s docid="FBIS4-18298" num="7" wdcount="2"> United Kingdom</s>
</F>
<H3>
<TI>

<s docid="FBIS4-18298" num="8" wdcount="6"> Ministers Support Major Following Resignation Call</s>
</TI>
</H3>
<HT>
<F>
<PHRASE>

<s docid="FBIS4-18298" num="9" wdcount="6"> Ministers Support Major Following Resignation Call</s>
</PHRASE>
</F>
</HT>
<F>

<s docid="FBIS4-18298" num="10" wdcount="14"> PM0404080294 London THE INDEPENDENT in English 4 Apr 94 p 1--FOR OFFICIAL USE ONLY</s>
</F>
<F>

<s docid="FBIS4-18298" num="11" wdcount="1"> PM0404080294</s>
</F>
<F>

<s docid="FBIS4-18298" num="12" wdcount="3"> London THE INDEPENDENT</s>
</F>
<F>

<s docid="FBIS4-18298" num="13" wdcount="1"> English</s>
</F>
<TEXT>

<s docid="FBIS4-18298" num="14" wdcount="1"> BFN</s>
<F>

<s docid="FBIS4-18298" num="15" wdcount="9"> [Colin Brown article: "Cabinet Allies Close Ranks But Bring</s>
</F>

<s docid="FBIS4-18298" num="16" wdcount="22"> Scant Relief to Major"] [Text] Cabinet ministers rallied behind John Major yesterday by insisting there would be no leadership election this autumn.</s>

<s docid="FBIS4-18298" num="17" wdcount="20"> But the concerted show of support failed to dispel doubts among Tory MPs about his chances of staying in office.</s>

<s docid="FBIS4-18298" num="18" wdcount="29"> Right-wing MPs confirmed the findings in an INDEPENDENT ON SUNDAY/NOP [National Opinion Poll] poll that Michael Heseltine was the favourite to replace Mr Major, if he is forced out.</s>

<s docid="FBIS4-18298" num="19" wdcount="18"> But they are calculating that Michael Portillo will run hard to secure Eurosceptic policies from the eventual winner.</s>

<s docid="FBIS4-18298" num="20" wdcount="39"> Some of Mr Major's closest allies were seething with anger at Mr Heseltine and Kenneth Clarke, the Chancellor, for "posturing" before the damaging retreat last week by the Prime Minister over Britain's veto powers in the enlarged European Union.</s>

<s docid="FBIS4-18298" num="21" wdcount="12"> "Why were Clarke and Heseltine trying to sound more Portilloesque than Portillo?</s>

<s docid="FBIS4-18298" num="22" wdcount="8"> The answer's pretty obvious," said one Cabinet minister.</s>

<s docid="FBIS4-18298" num="23" wdcount="37"> The leadership is hoping that over the Easter recess the Conservative constituencies will urge their MPs to stop the damaging in-fighting which they believe is overshadowing the Government's fightback on the economy, law and order and education.</s>

<s docid="FBIS4-18298" num="24" wdcount="17"> That message was reinforced by three Cabinet ministers who broke their Easter Sundays to support Mr Major.</s>

<s docid="FBIS4-18298" num="25" wdcount="17"> John Patten, the Secretary of State for Education, said: "He is a man of very great resilience.</s>

<s docid="FBIS4-18298" num="26" wdcount="6"> It must be tough for him.</s>

<s docid="FBIS4-18298" num="27" wdcount="11"> No one likes the level of criticism he has been getting.</s>

<s docid="FBIS4-18298" num="28" wdcount="20"> But he will be carrying on a 20- to 30-year programme begun in 1979 through to the next general election".</s>

<s docid="FBIS4-18298" num="29" wdcount="14"> Michael Howard, the Home Secretary, said: "There is no prospect of any leadership contest.</s>

<s docid="FBIS4-18298" num="30" wdcount="15"> John Major is going to lead the Conservative Party successfully into the next general election".</s>

<s docid="FBIS4-18298" num="31" wdcount="21"> He dismissed one poll of 100 MPs which showed that 41 of them believed there would be a change of leadership.</s>

<s docid="FBIS4-18298" num="32" wdcount="30"> Lord Wakeham, Leader of the House of Lords, used a letter to his former constituency of Colchester South to issue a general call to Tories for loyalty to Mr Major.</s>

<s docid="FBIS4-18298" num="33" wdcount="37"> "Our support for him should not only be loyalty to a proven winner, but also backing for a man who has ideas, ambitions and ability to take Britain to success in the 21st century," Lord Wakeham said.</s>

<s docid="FBIS4-18298" num="34" wdcount="12"> Their calls were described as "ritualistic" by one leading right-wing Tory MP.</s>

<s docid="FBIS4-18298" num="35" wdcount="7"> "John Major has done himself great damage.</s>

<s docid="FBIS4-18298" num="36" wdcount="8"> There will not be a coup next week.</s>

<s docid="FBIS4-18298" num="37" wdcount="13"> It will depend on how we do in the local and European elections.</s>

<s docid="FBIS4-18298" num="38" wdcount="10"> But there will be a stalking horse candidate this autumn.</s>

<s docid="FBIS4-18298" num="39" wdcount="7"> There's little doubt about that," he said.</s>

<s docid="FBIS4-18298" num="40" wdcount="20"> However, Tory right wingers said last night that they would support Mr Major because there was no credible right-wing candidate.</s>

<s docid="FBIS4-18298" num="41" wdcount="16"> Mr Portillo, 40, was too young and they still regarded Mr Heseltine as an interventionist left-winger.</s>

<s docid="FBIS4-18298" num="42" wdcount="26"> If a challenge does take place, they will press Mr Portillo to stand to secure key commitments, including no British entry into a single European currency.</s>

<s docid="FBIS4-18298" num="43" wdcount="28"> Three of the Tory MPs who have been rumoured as possible stalking horses -- Teresa Gorman, Tony Marlow and Sir Richard Body -- appeared to rule themselves out.</s>

<s docid="FBIS4-18298" num="44" wdcount="18"> The odds against Mr Major surviving have shortened from evens to 11/10 against over the past 24 hours.</s>

<s docid="FBIS4-18298" num="45" wdcount="23"> The Prime Minister told journalists at his Huntingdon Conservative Club at the weekend that he would not be forced out by the speculation.</s>

<s docid="FBIS4-18298" num="46" wdcount="9"> "It hasn't stopped me in the past two years.</s>

<s docid="FBIS4-18298" num="47" wdcount="8"> It isn't going to stop me now" .</s>
</TEXT>
</DOC>
