<DOC>
<DOCNO>

<s docid="FT933-10917" num="1" wdcount="1"> FT933-10917</s>
</DOCNO>
<PROFILE>

<s docid="FT933-10917" num="2" wdcount="1"> _AN-DHAABAE8FT</s>
</PROFILE>
<DATE>

<s docid="FT933-10917" num="3" wdcount="1"> 930731</s>
</DATE>
<HEADLINE>

<s docid="FT933-10917" num="4" wdcount="12"> FT 31 JUL 93 / Hawks & Handsaws: A few blunt words</s>
</HEADLINE>
<BYLINE>

<s docid="FT933-10917" num="5" wdcount="3"> By MICHAEL THOMPSON-NOEL</s>
</BYLINE>
<TEXT>

<s docid="FT933-10917" num="6" wdcount="24"> THE revelation that John Major is capable of candid, blunt and salty language when talking off-the- record to friendly journalists has surprised some people.</s>

<s docid="FT933-10917" num="7" wdcount="44"> It has even been suggested that the recording of the prime minister's conversation with Michael Brunson, ITN's political editor, in which Major used a variety of four-, six- and eight-letter words to communicate his lack of fondness for certain colleagues, may do him good.</s>

<s docid="FT933-10917" num="8" wdcount="14"> With luck, it is reckoned, Major's image as a leaden-tongued wimp may undergo correction.</s>

<s docid="FT933-10917" num="9" wdcount="2"> What piffle.</s>

<s docid="FT933-10917" num="10" wdcount="37"> Major is a gonner, especially after this week's revolt of the wooden-tops in the Christchurch by-election, where a Conservative majority of 23,015 at last year's general election was converted into a 16,427 majority for the Liberal Democrats.</s>

<s docid="FT933-10917" num="11" wdcount="18"> Fifteen months too late, the voters of Christchurch rounded on the Tories with a malignant and squeaky fury.</s>

<s docid="FT933-10917" num="12" wdcount="22"> In reality, all politicians, not just Major, are far more candid and salty when chatting in private than when speaking in public.</s>

<s docid="FT933-10917" num="13" wdcount="18"> In public, they have to be careful of what they say, so their utterances achieve a horrible mattness.</s>

<s docid="FT933-10917" num="14" wdcount="5"> But in private they relax.</s>

<s docid="FT933-10917" num="15" wdcount="3"> Their syntax disappears.</s>

<s docid="FT933-10917" num="16" wdcount="4"> Their words become nonsensical.</s>

<s docid="FT933-10917" num="17" wdcount="6"> They swear and joke and shout.</s>

<s docid="FT933-10917" num="18" wdcount="5"> It really is a spectacle.</s>

<s docid="FT933-10917" num="19" wdcount="15"> To show you what I mean, I spoke yesterday to John Major and John Smith.</s>

<s docid="FT933-10917" num="20" wdcount="15"> Smith, a Scot, is leader of the Labour Party, though not many people know that.</s>

<s docid="FT933-10917" num="21" wdcount="23"> In the aftermath of Christchurch, where Labour lost its deposit, I wanted to provoke the two Johns into a spot of real soul-searching.</s>

<s docid="FT933-10917" num="22" wdcount="8"> To guarantee them privacy, I used a signal-scrambler.</s>

<s docid="FT933-10917" num="23" wdcount="5"> No one could have eavesdropped.</s>

<s docid="FT933-10917" num="24" wdcount="6"> Their responses were true to form.</s>

<s docid="FT933-10917" num="25" wdcount="42"> But I have left out the swear-words because the new Financial Times Style Guide states that 'the gratuitous use of expletives or obscenities is discouraged . . . Four-letter expletives will usually be confined to infrequent use in the review (Arts) pages'.</s>

<s docid="FT933-10917" num="26" wdcount="16"> I can live with that, though why the artsy-fartsies should receive any dispensation is a puzzle.</s>

<s docid="FT933-10917" num="27" wdcount="4"> First, I tackled Major.</s>

<s docid="FT933-10917" num="28" wdcount="31"> I said: 'Did you read, John, what Olivier Blanchard, Rudiger Dornbusch, Stanley Fischer, Franco Modigliani, Paul A Samuelson and Robert Solow wrote, in just one article, in the FT this week?</s>

<s docid="FT933-10917" num="29" wdcount="11"> They were describing Europe's lunatic monetary policies and exchange rate arrangements.</s>

<s docid="FT933-10917" num="30" wdcount="6"> They did not pull their punches.</s>

<s docid="FT933-10917" num="31" wdcount="5"> I bet you went chalk-white.</s>

<s docid="FT933-10917" num="32" wdcount="7"> 'So why not walk the plank, John?</s>

<s docid="FT933-10917" num="33" wdcount="14"> You are the most unpopular prime minister since the start of the fourth century.</s>

<s docid="FT933-10917" num="34" wdcount="4"> Why invite more punishment?</s>

<s docid="FT933-10917" num="35" wdcount="16"> Unfairly or not, you are drawing the blame for all life's unpleasantnesses, let alone the cock-ups'.</s>

<s docid="FT933-10917" num="36" wdcount="7"> 'Are you sure'? the prime minister replied.</s>

<s docid="FT933-10917" num="37" wdcount="43"> 'I mean . . . how did it come about, Michael . . . like, Christchurch, y'know - load of . . . let me put it to you - the economy, of course . . . I mean, wimpy guy like me.</s>

<s docid="FT933-10917" num="38" wdcount="11"> But I'm not giving in like that, like . . '.</s>

<s docid="FT933-10917" num="39" wdcount="5"> On and on it went.</s>

<s docid="FT933-10917" num="40" wdcount="5"> Then I rang John Smith.</s>

<s docid="FT933-10917" num="41" wdcount="41"> I told him I had been impressed with his interview with Andrew Marr in The Independent on Thursday, in which he sharpened up his promise to introduce meaty political reforms (if he ever gets elected), including a referendum on proportional representation.</s>

<s docid="FT933-10917" num="42" wdcount="10"> I said: 'You are starting to raise your game, John.</s>

<s docid="FT933-10917" num="43" wdcount="40"> Many people will have agreed with your assertion that democracy in Britain is decaying, and that the Tories must be roasted for their arrogance, incompetence, complacency and sharp practices - especially their 'centralisation of power and the elimination of opposition'.</s>

<s docid="FT933-10917" num="44" wdcount="13"> But some of your critics still accuse you, John, of laziness and ineffectualness.</s>

<s docid="FT933-10917" num="45" wdcount="6"> What do you say to that'?</s>

<s docid="FT933-10917" num="46" wdcount="8"> 'Away, ye thowless jad,' shouted the Labour leader.</s>

<s docid="FT933-10917" num="47" wdcount="14"> 'Gie me o'wit an' sense a life, behint a kist to lie an' sklent.</s>

<s docid="FT933-10917" num="48" wdcount="26"> Our Stibble-rig was Rab M'Graen, a clever, sturdy fellow, but then he was sae fley'd by his showther gae a keek, an' tumbl'd wi' a wintle.</s>

<s docid="FT933-10917" num="49" wdcount="52"> Likewise with political and constitutional reform, Michael, for by the L - - d, tho' I should beg wi'lyart pow, I'll laugh, an' sing, an' shake my leg, as lang's I dow]' After that, I thought of telephoning Wing-Commander Paddy Ashdown, leader of the Liberal Democrats, to solicit his views on Christchurch.</s>

<s docid="FT933-10917" num="50" wdcount="7"> But I couldn't raise the energy .</s>
</TEXT>
<XX>

<s docid="FT933-10917" num="51" wdcount="1"> Countries:-</s>
</XX>
<CN>

<s docid="FT933-10917" num="52" wdcount="5"> GBZ United Kingdom, EC .</s>
</CN>
<XX>

<s docid="FT933-10917" num="53" wdcount="1"> Industries:-</s>
</XX>
<IN>

<s docid="FT933-10917" num="54" wdcount="4"> P9111 Executive Offices .</s>
</IN>
<XX>

<s docid="FT933-10917" num="55" wdcount="1"> Types:-</s>
</XX>
<TP>

<s docid="FT933-10917" num="56" wdcount="3"> PEOP People .</s>
</TP>
<PUB>

<s docid="FT933-10917" num="57" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT933-10917" num="58" wdcount="3"> London Page XX</s>
</PAGE>
</DOC>
