<DOC>
<DOCNO>

<s docid="FT942-6613" num="1" wdcount="1"> FT942-6613</s>
</DOCNO>
<PROFILE>

<s docid="FT942-6613" num="2" wdcount="1"> _AN-EE2AAAF1FT</s>
</PROFILE>
<DATE>

<s docid="FT942-6613" num="3" wdcount="1"> 940528</s>
</DATE>
<HEADLINE>

<s docid="FT942-6613" num="4" wdcount="19"> FT 28 MAY 94 / Major additions and omissions: Dominic Lawson on a prime minister who has invented himself</s>
</HEADLINE>
<BYLINE>

<s docid="FT942-6613" num="5" wdcount="3"> By DOMINIC LAWSON</s>
</BYLINE>
<TEXT>

<s docid="FT942-6613" num="6" wdcount="28"> Last year a biography of Mrs Norma Major - or, if we are being old-fashioned, Mrs John Major - claimed that the Majors' favourite film was Being There.</s>

<s docid="FT942-6613" num="7" wdcount="6"> I entirely concur with their choice.</s>

<s docid="FT942-6613" num="8" wdcount="44"> In case you did not see that marvellous film, this, in essence, was the plot: a man no one knows anything about, a gardener called Chauncey, rises without trace to become, by the end of the film, a serious candidate for the US presidency.</s>

<s docid="FT942-6613" num="9" wdcount="27"> Chauncey, played by Peter Sellers, utters only mundane sentiments in a halting monotone but this convinces the Republican party's power brokers that he is a sure-fire winner.</s>

<s docid="FT942-6613" num="10" wdcount="12"> In Chauncey's bromides everyone seems to hear what they want to believe.</s>

<s docid="FT942-6613" num="11" wdcount="5"> He has a deadly innocence.</s>

<s docid="FT942-6613" num="12" wdcount="7"> No wonder the Majors liked this film.</s>

<s docid="FT942-6613" num="13" wdcount="20"> John Major must, at some level, have appreciated the similarity between his own, strangely intangible, rise and that of Chauncey's.</s>

<s docid="FT942-6613" num="14" wdcount="12"> If he did not see the similarity, that is still more revealing.</s>

<s docid="FT942-6613" num="15" wdcount="14"> Do not protest that the urban John Major could not identify with a gardener.</s>

<s docid="FT942-6613" num="16" wdcount="21"> In an interview with Farmers Weekly, a few days ago, Major disclosed an unknown fact: his father was once a farmer.</s>

<s docid="FT942-6613" num="17" wdcount="15"> Farmers Weekly, you see, had asked Major how he had 'such obvious empathy with agriculture'.</s>

<s docid="FT942-6613" num="18" wdcount="8"> (Well, it was obvious to Farmers Weekly, anyway).</s>

<s docid="FT942-6613" num="19" wdcount="5"> And Major replied: 'It's simple.</s>

<s docid="FT942-6613" num="20" wdcount="5"> My father was a farmer.</s>

<s docid="FT942-6613" num="21" wdcount="9"> He lived on a small farm somewhere in Shropshire'.</s>

<s docid="FT942-6613" num="22" wdcount="27"> Francis Wheen of The Guardian, a keen student of Major's mysterious past, immediately rang 10 Downing Street, which claimed that Major's father farmed near Bromsgrove in 1910.</s>

<s docid="FT942-6613" num="23" wdcount="27"> As Wheen pointed out, Major was an unresponsive minus 33 years old at that time, and - a minor point this - Bromsgrove is not in Shropshire.</s>

<s docid="FT942-6613" num="24" wdcount="11"> This, of course, does not mean that Major made everything up.</s>

<s docid="FT942-6613" num="25" wdcount="6"> Family folklore is a peculiar thing.</s>

<s docid="FT942-6613" num="26" wdcount="34"> Yet when I heard about this, my mind immediately went back to an incident a few months ago, when Major visited Pittsburgh, centre of the US steel industry, as part of his American tour.</s>

<s docid="FT942-6613" num="27" wdcount="20"> I recall that he made a great hit by recounting that his father had been a steelworker in the city.</s>

<s docid="FT942-6613" num="28" wdcount="18"> A farmer for Farmers Weekly, a Pittsburgh steelworker for the American audience . . . a pattern emerges.</s>

<s docid="FT942-6613" num="29" wdcount="16"> Major's father, and therefore by extension John Major himself, can be all things to all people.</s>

<s docid="FT942-6613" num="30" wdcount="17"> If John Major were a different sort of politician, this would be a point barely worth making.</s>

<s docid="FT942-6613" num="31" wdcount="15"> But it does seem all of a piece with Major's approach to wider political issues.</s>

<s docid="FT942-6613" num="32" wdcount="26"> On the one hand he will appeal to the pro-Europeans in his own party by claiming to want Britain to be at the heart of Europe.</s>

<s docid="FT942-6613" num="33" wdcount="24"> On the other he is free with insulting references to the European Commission, whenever it is necessary to appeal to an audience of Euro-sceptics.</s>

<s docid="FT942-6613" num="34" wdcount="37"> There are those who will argue that this merely means that Major is a typical democratic politician, that one who wants to become prime minister in a democracy must recognise many constituencies of interest, not just one.</s>

<s docid="FT942-6613" num="35" wdcount="12"> But that has not been true of Major's most recent Conservative predecessors.</s>

<s docid="FT942-6613" num="36" wdcount="24"> Margaret Thatcher was notoriously dogmatic, even in public, and so too was Edward Heath, even though he always pretended to be a 'consensus politician'.</s>

<s docid="FT942-6613" num="37" wdcount="26"> No, Major's technique is very much his own invention, very much a reflection of his own particular character, itself a product of his unsettled family background.</s>

<s docid="FT942-6613" num="38" wdcount="24"> His father, Tom Major-Ball, was an itinerant figure, moving from place to place, trying his hand at any number of occupations, including the circus.</s>

<s docid="FT942-6613" num="39" wdcount="19"> No wonder the young John Major learned the skill of fitting in with prevailing circumstances, no matter how fluctuating.</s>

<s docid="FT942-6613" num="40" wdcount="18"> The only problem is the old one: you cannot fool all of the people all of the time.</s>

<s docid="FT942-6613" num="41" wdcount="4"> Except in the movies.</s>

<s docid="FT942-6613" num="42" wdcount="7"> Dominic Lawson is editor of The Spectator</s>
</TEXT>
<XX>

<s docid="FT942-6613" num="43" wdcount="1"> Countries:-</s>
</XX>
<CN>

<s docid="FT942-6613" num="44" wdcount="5"> GBZ United Kingdom, EC .</s>
</CN>
<XX>

<s docid="FT942-6613" num="45" wdcount="1"> Industries:-</s>
</XX>
<IN>

<s docid="FT942-6613" num="46" wdcount="5"> P9199 General Government, NEC .</s>
</IN>
<XX>

<s docid="FT942-6613" num="47" wdcount="1"> Types:-</s>
</XX>
<TP>

<s docid="FT942-6613" num="48" wdcount="3"> PEOP People .</s>
</TP>
<PUB>

<s docid="FT942-6613" num="49" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT942-6613" num="50" wdcount="3"> London Page XXII</s>
</PAGE>
</DOC>
