<DOC>
<DOCNO>

<s docid="LA112890-0036" num="1" wdcount="1"> LA112890-0036</s>
</DOCNO>
<DOCID>

<s docid="LA112890-0036" num="2" wdcount="1"> 314382</s>
</DOCID>
<DATE>
<P>

<s docid="LA112890-0036" num="3" wdcount="6"> November 28, 1990, Wednesday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA112890-0036" num="4" wdcount="8"> Part A; Page 1; Column 5; Foreign Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA112890-0036" num="5" wdcount="2"> 1595 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA112890-0036" num="6" wdcount="9"> JOHN MAJOR, 47, A THATCHER PROTEGE, WILL LEAD BRITAIN;</s>
</P>
<P>

<s docid="LA112890-0036" num="7" wdcount="8"> POLITICS: HE WILL BE CENTURY'S YOUNGEST PRIME MINISTER.</s>

<s docid="LA112890-0036" num="8" wdcount="6"> CONSERVATIVES' CHOICE ENSURES PARTY UNITY .</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA112890-0036" num="9" wdcount="6"> By WILLIAM TUOHY, TIMES STAFF WRITER</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA112890-0036" num="10" wdcount="1"> LONDON</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA112890-0036" num="11" wdcount="30"> John Major, the 47-year-old chancellor of the exchequer who rose out of one of London's toughest neighborhoods and the unemployment line, was selected Tuesday as Britain's next prime minister .</s>
</P>
<P>

<s docid="LA112890-0036" num="12" wdcount="30"> Major, whose father was once a circus trapeze artist, was elected leader of the Conservative Party to replace Margaret Thatcher, whose sudden resignation under pressure last week surprised the nation.</s>

<s docid="LA112890-0036" num="13" wdcount="21"> Thatcher formally presents her resignation today to Queen Elizabeth II, who will then ask Major to form a new government .</s>
</P>
<P>

<s docid="LA112890-0036" num="14" wdcount="32"> The Conservatives' choice of Major, a Thatcher protege, came after a battle pitting him against two other contenders for the party leadership, former Defense Secretary Michael Heseltine and Foreign Secretary Douglas Hurd.</s>

<s docid="LA112890-0036" num="15" wdcount="23"> The three-way race took shape last week when Thatcher, stunned by Heseltine's strong showing in the first-round voting for party leader, resigned .</s>
</P>
<P>

<s docid="LA112890-0036" num="16" wdcount="33"> In the secret, second-round balloting among the 372 Tory members of the House of Commons on Tuesday, Major got 185 votes -- two shy of the total he needed for an outright victory.</s>

<s docid="LA112890-0036" num="17" wdcount="32"> But as party members began preparing themselves for a Thursday runoff between Major and Heseltine, the runner-up, both Heseltine, with 131 votes, and Hurd, with 56, threw their support to Major .</s>
</P>
<P>

<s docid="LA112890-0036" num="18" wdcount="20"> Thatcher said she was "thrilled" by Major's victory, adding that he was her personal favorite among the three contenders .</s>
</P>
<P>

<s docid="LA112890-0036" num="19" wdcount="13"> Major becomes Britain's 18th prime minister and the youngest in this century .</s>
</P>
<P>

<s docid="LA112890-0036" num="20" wdcount="27"> His election ensures the unity of the fractured Conservative Party, which now has become the favorite to defeat the opposition Labor Party in the next general election.</s>

<s docid="LA112890-0036" num="21" wdcount="10"> Before Thatcher's resignation, the polls had been favoring Labor .</s>
</P>
<P>

<s docid="LA112890-0036" num="22" wdcount="37"> Appearing outside his official residence at No. 11 Downing St., next to the prime minister's, Major declared Tuesday evening, "We are going to unite totally and absolutely, and we are going to win the next election" .</s>
</P>
<P>

<s docid="LA112890-0036" num="23" wdcount="35"> "It is a very exciting thing to become leader of the Conservative Party, and particularly exciting, I think, to follow one of the most remarkable leaders the Conservative Party has ever had," Major said .</s>
</P>
<P>

<s docid="LA112890-0036" num="24" wdcount="13"> He complimented his rivals for a campaign based on "substance, not personality" .</s>
</P>
<P>

<s docid="LA112890-0036" num="25" wdcount="39"> When the results of Tuesday's vote were announced about 6:20 p.m., both Heseltine and Hurd said that they would vote for Major in the scheduled third runoff ballot on Thursday and advised their supporters to do the same .</s>
</P>
<P>

<s docid="LA112890-0036" num="26" wdcount="22"> Party leaders, however, waived the third ballot -- which was expected to be unanimous -- and Major was declared party leader .</s>
</P>
<P>

<s docid="LA112890-0036" num="27" wdcount="19"> After his appointment by the queen today, he is expected to name his Cabinet in a few days .</s>
</P>
<P>

<s docid="LA112890-0036" num="28" wdcount="22"> President Bush, en route to Washington after a visit to Mexico, telephoned Major from aboard Air Force One to congratulate him .</s>
</P>
<P>

<s docid="LA112890-0036" num="29" wdcount="26"> "The President said he looked forward to working with Major and to maintaining the special relationship" with Britain, said White House Press Secretary Marlin Fitzwater .</s>
</P>
<P>

<s docid="LA112890-0036" num="30" wdcount="12"> In Washington, the State and Defense departments also welcomed the news .</s>
</P>
<P>

<s docid="LA112890-0036" num="31" wdcount="22"> "We're very glad that it's all settled, and that it was able to be settled so quickly," a State Department official said.</s>

<s docid="LA112890-0036" num="32" wdcount="11"> "We know John Major and expect to work well with him.</s>

<s docid="LA112890-0036" num="33" wdcount="9"> We don't expect any change in U.S.-U.K. relations" .</s>
</P>
<P>

<s docid="LA112890-0036" num="34" wdcount="13"> After Major's election, Thatcher declared that she wanted everyone "to rally behind him".</s>

<s docid="LA112890-0036" num="35" wdcount="36"> The prime minister had picked Major from among "backbenchers" -- those who are not party leaders -- as someone to watch several years ago and regarded him, aides said, as "a man of the people" .</s>
</P>
<P>

<s docid="LA112890-0036" num="36" wdcount="17"> With her support, he rose swiftly through the Department of Social Security and then the Treasury .</s>
</P>
<P>

<s docid="LA112890-0036" num="37" wdcount="16"> Thatcher will remain a member of the House of Commons, representing the Finchley section of London.</s>

<s docid="LA112890-0036" num="38" wdcount="24"> She and her husband, Denis, will move out of 10 Downing St. today to their house in the South London community of Dulwich .</s>
</P>
<P>

<s docid="LA112890-0036" num="39" wdcount="29"> Thatcher may accept a peerage in the House of Lords as a hereditary countess, friends said, since earldoms (the male equivalent) are the traditional award to former prime ministers.</s>

<s docid="LA112890-0036" num="40" wdcount="11"> That tradition was not followed by recent Labor prime ministers .</s>
</P>
<P>

<s docid="LA112890-0036" num="41" wdcount="24"> Major is a high school dropout who made his name in banking before winning a seat in the House of Commons in 1979 .</s>
</P>
<P>

<s docid="LA112890-0036" num="42" wdcount="44"> He has few enemies and is regarded as a leader who can unify the party and, associates said Tuesday night, lead the Tories to victory in the next election, which must be held within 18 months, at a time of the party's choosing .</s>
</P>
<P>

<s docid="LA112890-0036" num="43" wdcount="41"> He is not expected to introduce any major new policies but will take a more sympathetic view toward Britain's role in the European Community and has promised to review the controversial community charge, the so-called poll tax introduced by Thatcher .</s>
</P>
<P>

<s docid="LA112890-0036" num="44" wdcount="27"> Labor Party leader Neil Kinnock, who likely will face Major in the next national election, immediately labeled him "more of the same" in the Thatcher mold .</s>
</P>
<P>

<s docid="LA112890-0036" num="45" wdcount="15"> The Labor Party had expected to defeat an unpopular Thatcher in the next election .</s>
</P>
<P>

<s docid="LA112890-0036" num="46" wdcount="16"> Jack Cunningham, Labor's campaign coordinator, argued that Major's victory was that of the "Thatcher candidate" .</s>
</P>
<P>

<s docid="LA112890-0036" num="47" wdcount="22"> Cunningham pointed out that 187 members of Major's own party, a majority in the House of Commons, voted against him Tuesday .</s>
</P>
<P>

<s docid="LA112890-0036" num="48" wdcount="7"> That in a sense was true .</s>
</P>
<P>

<s docid="LA112890-0036" num="49" wdcount="27"> With 185 votes in the three-way race, Major did not gain as many as the 202 votes Thatcher won Nov. 20, when Heseltine was her sole opponent.</s>

<s docid="LA112890-0036" num="50" wdcount="37"> That vote -- while she was in Paris attending the summit meeting of the Conference on Security and Cooperation in Europe -- forced her into a runoff with Heseltine and ultimately cost her the party leadership .</s>
</P>
<P>

<s docid="LA112890-0036" num="51" wdcount="21"> But in that vote, under the party's complicated rules, she needed a majority plus 15% and she fell four votes short.</s>

<s docid="LA112890-0036" num="52" wdcount="13"> In Tuesday's ballot, only a simple majority was needed to win outright .</s>
</P>
<P>

<s docid="LA112890-0036" num="53" wdcount="38"> The prime minister's downfall came after she had run into a stretch of unpopularity -- partly through her authoritarian manner, partly because of inflation and high interest rates and partly because of her unpopular new "poll tax" .</s>
</P>
<P>

<s docid="LA112890-0036" num="54" wdcount="38"> She also appeared to take an anti-European attitude toward her 11 partners in the European Community, which caused her long-serving Cabinet colleague and deputy prime minister, Geoffrey Howe, to resign and deliver a witheringly critical resignation speech .</s>
</P>
<P>

<s docid="LA112890-0036" num="55" wdcount="37"> That speech led Heseltine, who had walked out of the Cabinet in 1984 in a dispute over how to aid of a defense contractor, to challenge Thatcher for the leadership in that first ballot last Tuesday .</s>
</P>
<P>

<s docid="LA112890-0036" num="56" wdcount="15"> The prime minister's failure to gain the necessary majority forced her to reassess her position.</s>

<s docid="LA112890-0036" num="57" wdcount="39"> Her closest advisers reported that her support in the House of Commons was eroding, friends said, so she decided to resign rather than risk the humiliation of a defeat at the hands of one of her own colleagues .</s>
</P>
<P>

<s docid="LA112890-0036" num="58" wdcount="21"> At that point, on Thursday morning, both Major and Hurd, loyal members of her Cabinet, entered the race against Heseltine .</s>
</P>
<P>

<s docid="LA112890-0036" num="59" wdcount="30"> Many Tories in Parliament were angry at Heseltine for his role in bringing down Thatcher, who had won three national elections during her 15 years as Conservative Party leader .</s>
</P>
<P>

<s docid="LA112890-0036" num="60" wdcount="13"> Her 11 1/2-year tenure as prime minister was the longest in this century.</s>

<s docid="LA112890-0036" num="61" wdcount="24"> Her confrontational style of leadership won her many admirers at home and abroad -- and many enemies, here and in the European Community .</s>
</P>
<P>

<s docid="LA112890-0036" num="62" wdcount="28"> During the past few days, Major picked up strength among his colleagues, as opinion polls showed him to be the next most popular Tory after Heseltine nationwide .</s>
</P>
<P>

<s docid="LA112890-0036" num="63" wdcount="16"> On Monday, Thatcher let it be known that she personally preferred Major to succeed her .</s>
</P>
<P>

<s docid="LA112890-0036" num="64" wdcount="26"> Some commentators feared that Thatcher's revelation of her choice might harm Major -- with her comment Tuesday morning that she would make a "good back-seat driver".</s>

<s docid="LA112890-0036" num="65" wdcount="5"> Labor members called Major "Mrs.</s>

<s docid="LA112890-0036" num="66" wdcount="3"> Thatcher's poodle" .</s>
</P>
<P>

<s docid="LA112890-0036" num="67" wdcount="25"> But Major was the clear-cut victor in the balloting, held from 11 a.m. to 6 p.m. Tuesday in a House of Commons committee room .</s>
</P>
<P>

<s docid="LA112890-0036" num="68" wdcount="17"> After the results were announced, Heseltine declared that the election had been fought "without rancor and bitterness".</s>

<s docid="LA112890-0036" num="69" wdcount="30"> To "lay the basis for unity," he said, he would ask his supporters to vote for Major in the expected third ballot on Thursday, as he himself would do .</s>
</P>
<P>

<s docid="LA112890-0036" num="70" wdcount="7"> Soon afterward, Hurd did the same .</s>
</P>
<P>

<s docid="LA112890-0036" num="71" wdcount="38"> A third ballot seemed certain until Cranley Onslow, who heads the Conservative Party organization called the 1922 Committee, which supervised the party election, announced that another ballot would not be necessary and declared Major the party leader .</s>
</P>
<P>

<s docid="LA112890-0036" num="72" wdcount="26"> It was not immediately clear whether Hurd and Heseltine would join Major's Cabinet, though Major's aides indicated they would be offered roles in the government .</s>
</P>
<P>

<s docid="LA112890-0036" num="73" wdcount="33"> Conservative Party members of all hues were elated by the result and by the fact that the short campaign was conducted in the most gentlemanly fashion, with no blood on the floor .</s>
</P>
<P>

<s docid="LA112890-0036" num="74" wdcount="25"> The Labor Party, almost overnight, went from being the strong favorite in the next election to second place behind a Tory party led by Major.</s>

<s docid="LA112890-0036" num="75" wdcount="15"> Recent opinion polls had suggested that any new leader would greatly enhance Tory popularity .</s>
</P>
<P>

<s docid="LA112890-0036" num="76" wdcount="26"> Labor's Cunningham declared that the Conservatives' lead was "a temporary blip" and promised "to fight an election as soon as he (Major) names a date" .</s>
</P>
<P>
</P>
<P>

<s docid="LA112890-0036" num="77" wdcount="3"> TORY ELECTION RESULTS</s>
</P>
<P>

<s docid="LA112890-0036" num="78" wdcount="23"> Despite being two votes short of a majority, John Major was elected leader of the ruling Conservative Party after his challengers conceded defeat.</s>

<s docid="LA112890-0036" num="79" wdcount="12"> He will bwcome prime minister when formally confirmed by the Queen .</s>
</P>
<P>

<s docid="LA112890-0036" num="80" wdcount="3"> John Major: 185</s>
</P>
<P>

<s docid="LA112890-0036" num="81" wdcount="3"> Michael Heseltine: 131</s>
</P>
<P>

<s docid="LA112890-0036" num="82" wdcount="3"> Douglas Hurd: 56</s>
</P>
<P>

<s docid="LA112890-0036" num="83" wdcount="5"> 187 votes needed to win</s>
</P>
<P>

<s docid="LA112890-0036" num="84" wdcount="10"> The Conservative Party holds 372 seats in the 650-seat Parliament</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA112890-0036" num="85" wdcount="19"> Photo, COLOR, British Chancellor of Exchequer John Major, with wife Norma, waves from his home at 11 Downing St.</s>

<s docid="LA112890-0036" num="86" wdcount="16"> Major, just elected leader of Conservative Party, will move next door as he becomes prime minister.</s>

<s docid="LA112890-0036" num="87" wdcount="8"> Reuters; Chart, TORY ELECTION RESULTS, AP/Los Angeles Times</s>
</P>
</GRAPHIC>
<TYPE>
<P>

<s docid="LA112890-0036" num="88" wdcount="1"> Infobox</s>
</P>
</TYPE>
<SUBJECT>
<P>

<s docid="LA112890-0036" num="89" wdcount="18"> ENGLAND -- POLITICS; CONSERVATIVE PARTY (ENGLAND); LEADERSHIP; POLITICAL CANDIDATES; POLLS; HESELTINE, MICHAEL; HURD, DOUGLAS; MAJOR, JOHN; THATCHER, MARGARET</s>
</P>
</SUBJECT>
</DOC>
