<DOC>
<DOCNO>

<s docid="LA112790-0154" num="1" wdcount="1"> LA112790-0154</s>
</DOCNO>
<DOCID>

<s docid="LA112790-0154" num="2" wdcount="1"> 314232</s>
</DOCID>
<DATE>
<P>

<s docid="LA112790-0154" num="3" wdcount="6"> November 27, 1990, Tuesday, P.M. Final</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA112790-0154" num="4" wdcount="9"> Part P; Page 1; Column 5; Late Final Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA112790-0154" num="5" wdcount="2"> 512 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA112790-0154" num="6" wdcount="3"> THATCHER HEIR ELECTED;</s>
</P>
<P>

<s docid="LA112790-0154" num="7" wdcount="9"> TREASURY CHIEF JOHN MAJOR TO BE NEXT PRIME MINISTER</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA112790-0154" num="8" wdcount="4"> From Times Wire Services</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA112790-0154" num="9" wdcount="1"> LONDON</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA112790-0154" num="10" wdcount="30"> John Major, who was endorsed by Prime Minister Margaret Thatcher as her successor and heir, was elected today as leader of the Conservative Party and will become prime minister .</s>
</P>
<P>

<s docid="LA112790-0154" num="11" wdcount="22"> Major fell two votes short of the needed majority, but his opponents conceded defeat and Conservative Party officials declared him elected .</s>
</P>
<P>

<s docid="LA112790-0154" num="12" wdcount="5"> Aides said Thatcher is "thrilled".</s>

<s docid="LA112790-0154" num="13" wdcount="22"> Major, 47, her chancellor of the Exchequer, is the youngest person to be elected Britain's prime minister since the 19th Century .</s>
</P>
<P>

<s docid="LA112790-0154" num="14" wdcount="35"> "It is a very exciting thing to become leader of the Conservative Party, and particularly exciting, I think, to follow one of the most remarkable leaders the Conservative Party has ever had," Major said .</s>
</P>
<P>

<s docid="LA112790-0154" num="15" wdcount="10"> He called Thatcher "a very great prime minister indeed" .</s>
</P>
<P>

<s docid="LA112790-0154" num="16" wdcount="12"> Thatcher has made no public comment on what she will do next.</s>

<s docid="LA112790-0154" num="17" wdcount="23"> She could continue to represent Finchley in the House of Commons, enter the House of Lords, write her memoirs or enter business .</s>
</P>
<P>

<s docid="LA112790-0154" num="18" wdcount="8"> "Our job now I think is quite clear.</s>

<s docid="LA112790-0154" num="19" wdcount="30"> We are going to unite totally and absolutely and we're going to win the next general election," said Major, who emerged smiling from his residence at 11 Downing St .</s>
</P>
<P>

<s docid="LA112790-0154" num="20" wdcount="31"> Major won 185 votes, former Defense Secretary Michael Heseltine had 131 votes and Foreign Secretary Douglas Hurd had 56 votes in a secret ballot election among Tory members of Parliament .</s>
</P>
<P>

<s docid="LA112790-0154" num="21" wdcount="37"> "I congratulate John Major and thank him for a first-class campaign, fought without rancor or bitterness, which I believe lays the basis for the unity of our party," Heseltine said moments after the vote was announced .</s>
</P>
<P>

<s docid="LA112790-0154" num="22" wdcount="5"> Hurd also quickly conceded .</s>
</P>
<P>

<s docid="LA112790-0154" num="23" wdcount="27"> Within minutes, Cranley Onslow, chairman of the Conservative Party committee that supervised the election, announced that another ballot was not required and that Major was elected .</s>
</P>
<P>

<s docid="LA112790-0154" num="24" wdcount="25"> Thatcher left her residence at 10 Downing Street to congratulate Major, who as chancellor of the Exchequer is her next-door neighbor at No. 11 .</s>
</P>
<P>

<s docid="LA112790-0154" num="25" wdcount="30"> Queen Elizabeth II will send for Major and ask him to form a Cabinet after Thatcher has handed in her seals of office at Buckingham Palace on Wednesday morning .</s>
</P>
<P>

<s docid="LA112790-0154" num="26" wdcount="20"> Major was elected to Parliament in 1979, was appointed foreign secretary and then chancellor of the Exchequer last year .</s>
</P>
<P>

<s docid="LA112790-0154" num="27" wdcount="29"> He attracted support from prominent figures on the right wing of the Conservative Party, although his friends insisted that Major's own views are more liberal than many supposed .</s>
</P>
<P>

<s docid="LA112790-0154" num="28" wdcount="14"> He described himself as conservative on economic issues but liberal on social issues .</s>
</P>
<P>

<s docid="LA112790-0154" num="29" wdcount="9"> Major epitomized the self-reliant, hard-working achiever whom Thatcher encouraged.</s>

<s docid="LA112790-0154" num="30" wdcount="27"> Born March 29, 1943, the son of a circus performer, he left school at 16 and was a laborer and at one time a welfare recipient .</s>
</P>
<P>

<s docid="LA112790-0154" num="31" wdcount="21"> Major became a banker and a Conservative Party activist and was elected to Parliament in the first Thatcher victory of 1979.</s>

<s docid="LA112790-0154" num="32" wdcount="22"> He was appointed to a junior ministerial post in 1985, then to the No. 2 position at the Exchequer in 1987 .</s>
</P>
<P>

<s docid="LA112790-0154" num="33" wdcount="25"> He emerged as a possible heir-apparent when Thatcher appointed him foreign secretary in July, 1989, and then chancellor of the Exchequer three months later .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA112790-0154" num="34" wdcount="12"> Photo, Margaret Thatcher talks in Parliament for last time as prime minister.</s>

<s docid="LA112790-0154" num="35" wdcount="11"> Reuters; Photo, John Major waves to supporters before Conservative Party voting.</s>

<s docid="LA112790-0154" num="36" wdcount="2"> Associated Press</s>
</P>
</GRAPHIC>
<TYPE>
<P>

<s docid="LA112790-0154" num="37" wdcount="1"> Wire</s>
</P>
</TYPE>
</DOC>
