<DOC>
<DOCNO>

<s docid="LA122190-0149" num="1" wdcount="1"> LA122190-0149</s>
</DOCNO>
<DOCID>

<s docid="LA122190-0149" num="2" wdcount="1"> 325991</s>
</DOCID>
<DATE>
<P>

<s docid="LA122190-0149" num="3" wdcount="6"> December 21, 1990, Friday, P.M. Final</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA122190-0149" num="4" wdcount="9"> Part P; Page 1; Column 4; Late Final Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA122190-0149" num="5" wdcount="2"> 288 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA122190-0149" num="6" wdcount="8"> BRITISH PRIME MINISTER TAKES HARD LINE ON IRAQ</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA122190-0149" num="7" wdcount="3"> From Associated Press</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA122190-0149" num="8" wdcount="1"> WASHINGTON</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA122190-0149" num="9" wdcount="30"> British Prime Minister John Major said today that Iraqi troops will have to be "forcibly removed" from Kuwait if President Saddam Hussein does not agree to withdraw them peacefully .</s>
</P>
<P>

<s docid="LA122190-0149" num="10" wdcount="34"> Major, just as unyielding in talking about Hussein as was his predecessor, Margaret Thatcher, rejected the notion that a partial Iraqi pullback from Kuwait would help bring about a solution to the crisis .</s>
</P>
<P>

<s docid="LA122190-0149" num="11" wdcount="25"> "A complete withdrawal is necessary, a partial withdrawal won't do," Major said in a display of solidarity with U.S. policy on the Persian Gulf .</s>
</P>
<P>

<s docid="LA122190-0149" num="12" wdcount="37"> On the gulf issue at least, Major's remarks augured well for his talks with President Bush late in the day at Camp David, the Maryland presidential retreat where the two leaders were planning an overnight stay .</s>
</P>
<P>

<s docid="LA122190-0149" num="13" wdcount="33"> Major, who arrived here Thursday night for a 40-hour visit, wasted no time in going on a rhetorical offensive against Hussein, using a succession of four television interviews aired shortly after dawn .</s>
</P>
<P>

<s docid="LA122190-0149" num="14" wdcount="37"> "If he stays in Kuwait, in a country which essentially at the moment is rather like a prison camp, a country that he's dismantling day after day, then he will have to be forcibly removed," Major said.</s>

<s docid="LA122190-0149" num="15" wdcount="20"> "I hope it won't come to that -- everyone hopes it won't come to that -- but it could" .</s>
</P>
<P>

<s docid="LA122190-0149" num="16" wdcount="29"> At the same time, Major demonstrated the kinder, gentler face he has brought to British politics since his accession, showing none of the abrasiveness that was a Thatcher hallmark.</s>

<s docid="LA122190-0149" num="17" wdcount="12"> In contrast to Thatcher, he was polite to reporters questioning him .</s>
</P>
<P>

<s docid="LA122190-0149" num="18" wdcount="15"> Comparing Major and Thatcher, one U.S. official said, "The biggest change is personal style" .</s>
</P>
<P>

<s docid="LA122190-0149" num="19" wdcount="17"> Consistent with the U.S. view on the gulf, Major said: "There is nothing whatsoever to negotiate about".</s>

<s docid="LA122190-0149" num="20" wdcount="7"> Hussein, he said, "has to go" .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA122190-0149" num="21" wdcount="18"> Photo, Major meeting -- British Prime Minister John Major, right, meets Secretary of State James A. Baker III.</s>

<s docid="LA122190-0149" num="22" wdcount="2"> Associated Press</s>
</P>
</GRAPHIC>
<TYPE>
<P>

<s docid="LA122190-0149" num="23" wdcount="1"> Wire</s>
</P>
</TYPE>
</DOC>
