<DOC>
<DOCNO>

<s docid="AP891106-0072" num="1" wdcount="1"> AP891106-0072</s>
</DOCNO>
<FILEID>

<s docid="AP891106-0072" num="2" wdcount="2"> AP-NR-11-06-89 1050EST</s>
</FILEID>
<FIRST>

<s docid="AP891106-0072" num="3" wdcount="5"> r i PM-Britain-Politics 11-06 0624</s>
</FIRST>
<SECOND>

<s docid="AP891106-0072" num="4" wdcount="1"> PM-Britain-Politics,0643</s>
</SECOND>
<HEAD>

<s docid="AP891106-0072" num="5" wdcount="8"> Thatcher Says She'll Step Down After Next Election</s>
</HEAD>
<BYLINE>

<s docid="AP891106-0072" num="6" wdcount="3"> By LESLIE SHEPHERD</s>
</BYLINE>
<BYLINE>

<s docid="AP891106-0072" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP891106-0072" num="8" wdcount="2"> LONDON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP891106-0072" num="9" wdcount="33"> Prime Minister Margaret Thatcher has weakened her position and kicked off the race to succeed her by saying she plans to step down after winning another term, opposition leaders and political observers said.</s>

<s docid="AP891106-0072" num="10" wdcount="20"> A pro-Thatcher newspaper today said she had merely stated the obvious and that her statements were no ``cause for astonishment''.</s>

<s docid="AP891106-0072" num="11" wdcount="35"> Mrs. Thatcher told The Sunday Correspondent in an interview published Sunday that she hoped to lead her Conservative Party to a fourth successive election but said it was unlikely she would try for a fifth.</s>

<s docid="AP891106-0072" num="12" wdcount="19"> ``I think people would think it was time for someone else to carry the torch,'' she told the newspaper.</s>

<s docid="AP891106-0072" num="13" wdcount="10"> The Sunday Times of London said in a commentary: ``Mrs.</s>

<s docid="AP891106-0072" num="14" wdcount="6"> Thatcher has committed a colossal blunder''.</s>

<s docid="AP891106-0072" num="15" wdcount="22"> ``She has given the riders for the Tory succession their starting orders years in advance of the actual race,'' the newspaper said.</s>

<s docid="AP891106-0072" num="16" wdcount="22"> The next election must be held by the summer of 1992, but it is expected Mrs. Thatcher will call it in 1991.</s>

<s docid="AP891106-0072" num="17" wdcount="23"> Mrs. Thatcher, who turned 64 last month, has never previously made it clear in public when she plans to retire as party leader.</s>

<s docid="AP891106-0072" num="18" wdcount="30"> She was elected in 1979, the first female prime minister in Europe, and won re-election in 1983 and in 1987, when she said she planned to ``go on and on''.</s>

<s docid="AP891106-0072" num="19" wdcount="26"> Earlier this year, Mrs. Thatcher overtook Liberal Lord Asquith's 1908-1916 tenure as prime minister to become Britain's longest continuously serving prime minister of the 20th century.</s>

<s docid="AP891106-0072" num="20" wdcount="41"> Mrs. Thatcher's popularity is the lowest of any prime minister since opinion polls began in Britain 50 years ago, and senior colleagues have publicly admonished her to change her leadership style following the surprise resignation of her treasury chief, Nigel Lawson.</s>

<s docid="AP891106-0072" num="21" wdcount="20"> Lord Callaghan, former Labor prime minister whom Mrs. Thatcher defeated in 1979, said her comments had ``considerably weakened her position''.</s>

<s docid="AP891106-0072" num="22" wdcount="32"> If her party wins the next election, it is expected Mrs. Thatcher would step down before her term ends to allow her successor to choose a time to call a new election.</s>

<s docid="AP891106-0072" num="23" wdcount="22"> ``My guess is that the Tory party will want someone as leader who could take them through the next Parliament,'' Callaghan said.</s>

<s docid="AP891106-0072" num="24" wdcount="41"> If Mrs. Thatcher resigns while in office, her successor elected by the party automatically becomes prime minister with approval of Queen Elizabeth II, but convention dictates that he or she seek a mandate in a general election as soon as possible.</s>

<s docid="AP891106-0072" num="25" wdcount="10"> The Sunday Times speculated she would step down by 1994.</s>

<s docid="AP891106-0072" num="26" wdcount="30"> Mrs. Thatcher would celebrate her 69th birthday that year and her husband, Denis, will be 79 and ``his age may have been a factor in her decision,'' the newspaper said.</s>

<s docid="AP891106-0072" num="27" wdcount="32"> The newspaper predicted the opposition Labor Party will try to promote leader Neil Kinnock as ``the occupant-in-waiting of 10 Downing St., who is ready, able and willing to complete a full term''.</s>

<s docid="AP891106-0072" num="28" wdcount="3"> Kinnock called Mrs.</s>

<s docid="AP891106-0072" num="29" wdcount="10"> Thatcher's comments ``the interview of someone preparing herself for quitting.</s>

<s docid="AP891106-0072" num="30" wdcount="10"> Mentally, Margaret Thatcher is preparing herself for packing her bags''.</s>

<s docid="AP891106-0072" num="31" wdcount="25"> In an editorial today, the pro-Thatcher Daily Telegraph said Mrs. Thatcher was merely stating the obvious by indicating she would not seek a fifth term.</s>

<s docid="AP891106-0072" num="32" wdcount="21"> ``Even were she not to fight a fifth election, Mrs. Thatcher could yet enjoy seven more years in charge,'' it said.</s>

<s docid="AP891106-0072" num="33" wdcount="16"> ``By then she would be in her 70s, and her devoted husband a decade older ...</s>

<s docid="AP891106-0072" num="34" wdcount="20"> Nonetheless, what other politician would be expected to entertain an inquiry about his or her intentions in seven years time?</s>

<s docid="AP891106-0072" num="35" wdcount="25"> And can it really be a cause for astonishment that Mrs. Thatcher is unwilling to commit herself to political activity in her mid-70s and beyond?''</s>
</TEXT>
</DOC>
