<DOC>
<DOCNO>

<s docid="AP901122-0100" num="1" wdcount="1"> AP901122-0100</s>
</DOCNO>
<FILEID>

<s docid="AP901122-0100" num="2" wdcount="2"> AP-NY-11-22-90 1650EST</s>
</FILEID>
<FIRST>

<s docid="AP901122-0100" num="3" wdcount="7"> u i AM-Thatcher-Reaction 1stLd-Writethru a0572 11-22 0800</s>
</FIRST>
<SECOND>

<s docid="AP901122-0100" num="4" wdcount="4"> AM-Thatcher-Reaction, 1st Ld-Writethru, a0572,0940</s>
</SECOND>
<HEAD>

<s docid="AP901122-0100" num="5" wdcount="6"> Foreign Leaders Pay Tribute To Mrs.</s>

<s docid="AP901122-0100" num="6" wdcount="2"> Thatcher's Courage</s>
</HEAD>
<NOTE>

<s docid="AP901122-0100" num="7" wdcount="19"> Eds: LEADS with 22 grafs to UPDATE with praise from foes, comments from South Africa, Japan, Soviet Union, other.</s>

<s docid="AP901122-0100" num="8" wdcount="6"> Picks up 16th graf, `Dutch Prime...'</s>
</NOTE>
<HEAD>

<s docid="AP901122-0100" num="9" wdcount="3"> With AM-Britain-Politics, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP901122-0100" num="10" wdcount="3"> By AUDREY WOODS</s>
</BYLINE>
<BYLINE>

<s docid="AP901122-0100" num="11" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP901122-0100" num="12" wdcount="2"> LONDON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP901122-0100" num="13" wdcount="18"> Prime Minister Margaret Thatcher's international admirers praised her courage and achievements Thursday after she announced she would resign.</s>

<s docid="AP901122-0100" num="14" wdcount="11"> Even her foes tempered scorn with praise for a formidable adversary.</s>

<s docid="AP901122-0100" num="15" wdcount="7"> Said President Bush, ``I will miss her''.</s>

<s docid="AP901122-0100" num="16" wdcount="21"> He called her ``an outstanding ally of the United States,'' adding, ``You always knew where she was and what she believed''.</s>

<s docid="AP901122-0100" num="17" wdcount="31"> Vitaly Ignatenko, spokesman for Soviet President Mikhail Gorbachev, told the independent Interfax news agency: ``Political, economic and cultural ties between our countries have become of greater importance'' in the Thatcher era.</s>

<s docid="AP901122-0100" num="18" wdcount="3"> ``Our relations ...</s>

<s docid="AP901122-0100" num="19" wdcount="6"> were marked by constructivism and dialogue''.</s>

<s docid="AP901122-0100" num="20" wdcount="15"> The reluctance Mrs. Thatcher showed toward increasing European unity was the source of most criticism.</s>

<s docid="AP901122-0100" num="21" wdcount="18"> But in a joyful and unambiguous response, Iraq saw the Persian Gulf crisis as cause of her downfall.</s>

<s docid="AP901122-0100" num="22" wdcount="21"> Bitterness was undisguised in the comment from Argentina's Nicanor Costa Mendez, foreign minister during his country's 1982 Falklands War with Britain.</s>

<s docid="AP901122-0100" num="23" wdcount="10"> ``I can't say that it makes me sad,'' he said.</s>

<s docid="AP901122-0100" num="24" wdcount="34"> ``I believe that the extreme positions - unnecessarily extreme, unjustifiably extreme - of the prime minister were one of the causes of the war, and one of the biggest impediments to achieve agreement after''.</s>

<s docid="AP901122-0100" num="25" wdcount="18"> Socialist President Mario Soares of Portugal singled out ``her systematic opposition to the advances of the European Community''.</s>

<s docid="AP901122-0100" num="26" wdcount="33"> ``During her long mandate,'' he said, ``the preoccupations of social justice receded many times before purely development objectives, causing a climate of discontent in British public opinion to which Mrs. Thatcher appeared insensitive''.</s>

<s docid="AP901122-0100" num="27" wdcount="35"> But Soares also lauded the British prime minister as a ``determined politician (who) took courageous positions on critical occasions in international life and without doubt marked an era in the contemporary history of her country''.</s>

<s docid="AP901122-0100" num="28" wdcount="24"> German Finance Minister Theo Waigel noted, ``Despite her critical position on some questions of European integration, she accomplished a great deal for European politics''.</s>

<s docid="AP901122-0100" num="29" wdcount="29"> A neutral letter from Socialist President Francois Mitterrand of France told Mrs. Thatcher she had ``marked an important moment in the history of your country and that of Europe''.</s>

<s docid="AP901122-0100" num="30" wdcount="21"> Iraqi government spokesman Naji al-Hadithi said growing opposition to her hard line against Iraq over its invasion of Kuwait ``buried Mrs.</s>

<s docid="AP901122-0100" num="31" wdcount="19"> Thatcher'' just as the 1956 crisis over Britain's attack on the Suez Canal ruined former Prime Minister Anthony Eden.</s>

<s docid="AP901122-0100" num="32" wdcount="8"> Britain stepped in after Egypt nationalized the canal.</s>

<s docid="AP901122-0100" num="33" wdcount="35"> On Thursday, Britain announced it was nearly doubling its troops deployed in the gulf as part of the multinational force arrayed against Iraq, sending 14,000 more soldiers to join the 16,000 already in the region.</s>

<s docid="AP901122-0100" num="34" wdcount="25"> South African President F.W. de Klerk praised Mrs. Thatcher, who opposed sanctions on South Africa, for standing up to world pressure and standing by Pretoria.</s>

<s docid="AP901122-0100" num="35" wdcount="16"> ``She had faith in South Africa's ability to solve its problems in a democratic way ...</s>

<s docid="AP901122-0100" num="36" wdcount="9"> She had the courage of her convictions,'' he said.</s>

<s docid="AP901122-0100" num="37" wdcount="36"> Prime Minister Yitzhak Shamir of Israel saidafter hearing of her resignation that Israel ``feels a moment of sorrow because we all know this special personality, Mrs. Thatcher, who did many things and was an outstanding leader''.</s>

<s docid="AP901122-0100" num="38" wdcount="37"> Prime Minister Toshiki Kaifu of Japan said the British prime minister ``is a rare leader of firm convictions who was invigorated the United Kingdom and I feel great regret that she has withdrawn from the front line''.</s>

<s docid="AP901122-0100" num="39" wdcount="25"> Belgium's prime minister, Wilfried Martens, applauded ``the determining role she played during more than 10 years in her own country and on the international scene''.</s>

<s docid="AP901122-0100" num="40" wdcount="30"> Said Prime Minister Bob Hawke of Australia, ``Even those like myself who have been at odds with Margaret Thatcher on particular issues have admired her courage and tenacity of purpose.</s>

<s docid="AP901122-0100" num="41" wdcount="22"> ``Whatever the forces arrayed against her, she was always prepared to pursue with the utmost vigor those positions in which she believed''.</s>

<s docid="AP901122-0100" num="42" wdcount="45"> Dutch Prime Minister Ruud Lubbers said, ``In the many years that she placed such an important stamp on the policies of the United Kingdom, Mrs. Thatcher has shown that she does not avoid making difficult decisions that she deems to be in the nation's interest.</s>

<s docid="AP901122-0100" num="43" wdcount="9"> This, too, is such a decision which deserves respect''.</s>

<s docid="AP901122-0100" num="44" wdcount="15"> Former French President Valery Giscard d'Estaing, now a legislator in the European Parliament, said Mrs.</s>

<s docid="AP901122-0100" num="45" wdcount="8"> Thatcher's decision to quit was ``dignified and courageous''.</s>

<s docid="AP901122-0100" num="46" wdcount="19"> ``Margaret Thatcher will be seen with Winston Churchill as the greatest British prime minister of the last 50 years.</s>

<s docid="AP901122-0100" num="47" wdcount="8"> The curtain has fallen on the Iron Lady.</s>

<s docid="AP901122-0100" num="48" wdcount="4"> She deserves our congratulations''.</s>

<s docid="AP901122-0100" num="49" wdcount="7"> Even European Commission President Jacques Delors, Mrs.</s>

<s docid="AP901122-0100" num="50" wdcount="14"> Thatcher's archenemy in Europe, spoke of his ``high esteem'' for her, despite their differences.</s>

<s docid="AP901122-0100" num="51" wdcount="29"> Alfred Dregger, parliamentary leader of Germany's governing Christian Democratic Union, said Mrs. Thatcher played a major role in securing Western solidarity in the ``historical conflict for freedom and democracy.</s>

<s docid="AP901122-0100" num="52" wdcount="5"> We thank her for that''.</s>

<s docid="AP901122-0100" num="53" wdcount="12"> Former President Reagan spoke with great warmth of his closest foreign ally.</s>

<s docid="AP901122-0100" num="54" wdcount="14"> ``Margaret Thatcher's resoluteness played a key role in ending the Cold War,'' he said.</s>

<s docid="AP901122-0100" num="55" wdcount="13"> ``She stood up to the Soviets and let them know she meant business.</s>

<s docid="AP901122-0100" num="56" wdcount="42"> Her deep and abiding dedication to the principles of liberty and democracy served as an inspiration to oppressed peoples everywhere who knew that Margaret Thatcher would never waver in her belief that all men and women are entitled to live in freedom.''</s>
</TEXT>
</DOC>
