<DOC>
<DOCNO>

<s docid="AP901126-0053" num="1" wdcount="1"> AP901126-0053</s>
</DOCNO>
<FILEID>

<s docid="AP901126-0053" num="2" wdcount="2"> AP-NY-11-26-90 1059EST</s>
</FILEID>
<FIRST>

<s docid="AP901126-0053" num="3" wdcount="7"> r i PM-Thatcher-Women 1stLd-Writethru a0421 11-26 0568</s>
</FIRST>
<SECOND>

<s docid="AP901126-0053" num="4" wdcount="4"> PM-Thatcher-Women, 1st Ld-Writethru, a0421,0687</s>
</SECOND>
<HEAD>

<s docid="AP901126-0053" num="5" wdcount="10"> British Women Say Thatcher Set Good Example But Little Else</s>
</HEAD>
<NOTE>

<s docid="AP901126-0053" num="6" wdcount="15"> Eds: SUBS penultimate graf to restore dropped first name and reference to Ms. Hawkins .</s>
</NOTE>
<BYLINE>

<s docid="AP901126-0053" num="7" wdcount="3"> By JESSICA BALDWIN</s>
</BYLINE>
<BYLINE>

<s docid="AP901126-0053" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP901126-0053" num="9" wdcount="2"> LONDON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP901126-0053" num="10" wdcount="26"> Margaret Thatcher set the example of what a woman could achieve in British society, but her critics say she did little else to help women along.</s>

<s docid="AP901126-0053" num="11" wdcount="12"> For some, it was enough that her political career reached the heights.</s>

<s docid="AP901126-0053" num="12" wdcount="17"> One woman wrote to The Independent newspaper last week that her 7-year-old daughter wondered what title Mrs.</s>

<s docid="AP901126-0053" num="13" wdcount="15"> Thatcher's successor would hold, since ``he couldn't be called prime minister, that's a girl's name''.</s>

<s docid="AP901126-0053" num="14" wdcount="21"> Emma Nicholson, a Conservative Party lawmaker, said it was once unthinkable that a woman would ever be a British prime minister.</s>

<s docid="AP901126-0053" num="15" wdcount="14"> ``She has broken the mold once and forever,'' Ms. Nicholson said in an interview.</s>

<s docid="AP901126-0053" num="16" wdcount="21"> Mrs. Thatcher, who trained as a chemist before studying law, said she viewed herself as prime minister, not as a woman.</s>

<s docid="AP901126-0053" num="17" wdcount="17"> She believed the battle for women's rights had been largely won and was no believer in feminism.</s>

<s docid="AP901126-0053" num="18" wdcount="10"> ``What has it ever done for me''? she once asked.</s>

<s docid="AP901126-0053" num="19" wdcount="23"> Mrs. Thatcher, who stepped down on Thursday, urged women to get involved in politics, but did little to pull them up the ladder.</s>

<s docid="AP901126-0053" num="20" wdcount="35"> Several female lawmakers were appointed to junior executive posts in various ministries, but the only woman to serve in a Thatcher Cabinet was Baroness Young, leader of the House of Lords from 1981 to 1983.</s>

<s docid="AP901126-0053" num="21" wdcount="27"> ``The truth is that although Mrs. Thatcher is a woman, she doesn't believe in the advancement of women,'' Clare Short, a Labor Party lawmaker, said last month.</s>

<s docid="AP901126-0053" num="22" wdcount="23"> Edwina Currie, a former junior health minister, said any other prime minister would have had several women in and out of the Cabinet.</s>

<s docid="AP901126-0053" num="23" wdcount="18"> ``It's Margaret's fault that the only people standing (to succeed her) wear trousers,'' Mrs. Currie said last week.</s>

<s docid="AP901126-0053" num="24" wdcount="24"> Trree men are vying to succeed her as Conservative Party leader and thus prime minister in a vote by party lawmakers set for Tuesday.</s>

<s docid="AP901126-0053" num="25" wdcount="24"> Traditional male attitudes remain strong in Britain, from the upper-crust, all-male clubs of London to the topless women pictured daily in the tabloid press.</s>

<s docid="AP901126-0053" num="26" wdcount="16"> Women are paid less than men and are poorly represented in management jobs and in Parliament.</s>

<s docid="AP901126-0053" num="27" wdcount="13"> However, campaigners for women rights say there are encouraging signs at the grassroots.</s>

<s docid="AP901126-0053" num="28" wdcount="23"> ``The critical mass of women have entered middle management in government and business,'' said Lesley Abdela, a founding member of the 300 Group.</s>

<s docid="AP901126-0053" num="29" wdcount="19"> The group seeks equal representation for women in the 650-seat House of Commons, which now has 43 female members.</s>

<s docid="AP901126-0053" num="30" wdcount="23"> Women represented 43 percent of the British labor force in 1988, compared with 40 percent in 1979 when Mrs. Thatcher became prime minister.</s>

<s docid="AP901126-0053" num="31" wdcount="13"> Britain has a higher proportion of working women than other European Community countries.</s>

<s docid="AP901126-0053" num="32" wdcount="36"> Though Mrs. Thatcher never made a priority of women's issues, she did introduce some helpful legislation: tax concessions for workplace nurseries; independent taxation for married women; and legislation to compel absent fathers to pay child benefits.</s>

<s docid="AP901126-0053" num="33" wdcount="17"> But as prime minister, she angered feminists by often emphasizing women's traditional roles of homemakers and care-givers.</s>

<s docid="AP901126-0053" num="34" wdcount="23"> Angela Rumbold, the Conservative Party's minister for women's issues, contends that an ``enormous amount'' has been done for women during the Thatcher years.</s>

<s docid="AP901126-0053" num="35" wdcount="24"> ``I'm not sure what she could have gone beyond promoting people who were there just because they were women,'' she said in an interview.</s>

<s docid="AP901126-0053" num="36" wdcount="6"> ``Margaret Thatcher is a great meritocrat.</s>

<s docid="AP901126-0053" num="37" wdcount="10"> She believes in getting people to succeed on their merits''.</s>

<s docid="AP901126-0053" num="38" wdcount="20"> Jo Hawkins of the 300 Group, which is seeking equal numbers of women in the House of Commons, believes Mrs.</s>

<s docid="AP901126-0053" num="39" wdcount="16"> Thatcher's extraordinary abilities made it difficult for her to understand the needs of the average woman.</s>

<s docid="AP901126-0053" num="40" wdcount="22"> ``She would say that anybody can do it, just stick to your principles and get up and do it,'' Ms. Hawkins said.</s>

<s docid="AP901126-0053" num="41" wdcount="21"> ``I think because of her character, her personality and her amazing self-confidence, she isn't aware of how the normal person struggles.''</s>
</TEXT>
</DOC>
