<DOC>
<DOCNO>

<s docid="AP901123-0062" num="1" wdcount="1"> AP901123-0062</s>
</DOCNO>
<FILEID>

<s docid="AP901123-0062" num="2" wdcount="2"> AP-NY-11-23-90 1138EST</s>
</FILEID>
<FIRST>

<s docid="AP901123-0062" num="3" wdcount="7"> r a PM-Reagan-Thatcher 1stLd-Writethru a0442 11-23 0443</s>
</FIRST>
<SECOND>

<s docid="AP901123-0062" num="4" wdcount="6"> PM-Reagan-Thatcher, 1st Ld - Writethru, a0442,0515</s>
</SECOND>
<HEAD>

<s docid="AP901123-0062" num="5" wdcount="12"> Reagan Heaps Praise on Thatcher as She Heads Off Into Political Sunset</s>
</HEAD>
<NOTE>

<s docid="AP901123-0062" num="6" wdcount="13"> Eds: Rewrites throughout to restore courtesy title on second reference to Mrs. Thatcher.</s>

<s docid="AP901123-0062" num="7" wdcount="3"> No pickup .</s>
</NOTE>
<HEAD>

<s docid="AP901123-0062" num="8" wdcount="4"> With PM-Britain Politics, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP901123-0062" num="9" wdcount="4"> By ROSE ANA BERBEO</s>
</BYLINE>
<BYLINE>

<s docid="AP901123-0062" num="10" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP901123-0062" num="11" wdcount="3"> LOS ANGELES (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP901123-0062" num="12" wdcount="31"> Former President Reagan thanked British Prime Minister Margaret Thatcher for backing him up when other allies backed down, heaping praise on his political soulmate as she heads off into the sunset.</s>

<s docid="AP901123-0062" num="13" wdcount="26"> ``Margaret Thatcher was a completely reliable ally and partner of the greatest personal integrity,'' Reagan said in a statement after Mrs. Thatcher announced her impending retirement.</s>

<s docid="AP901123-0062" num="14" wdcount="17"> ``I could always count on her wise counsel, her firm support, and her loyal friendship,'' Reagan said.</s>

<s docid="AP901123-0062" num="15" wdcount="20"> Mrs. Thatcher on Thursday succumbed to the challenge mounted by Michael Heseltine, who resigned as her defense minister in 1986.</s>

<s docid="AP901123-0062" num="16" wdcount="24"> Reagan and the prime minister dubbed the Iron Lady formed a formidable duo in the 1980s and made no secret of their mutual regard.</s>

<s docid="AP901123-0062" num="17" wdcount="14"> They often stood side-by-side at international gatherings and called each other Ronnie and Margaret.</s>

<s docid="AP901123-0062" num="18" wdcount="40"> Two years ago, as they met for the final time before Reagan left office, the president said he was leaving the White House with ``considerable satisfaction in the knowledge that Margaret Thatcher will still reside at No. 10 Downing Street''.</s>

<s docid="AP901123-0062" num="19" wdcount="35"> Reagan, who spent Thanksgiving with friends at his Bel-Air home, called her resignation in the face of strong opposition a ``selfless and courageous decision in what she believes is the best interests of her country''.</s>

<s docid="AP901123-0062" num="20" wdcount="9"> The former chief executive was always grateful to Mrs.</s>

<s docid="AP901123-0062" num="21" wdcount="14"> Thatcher's support of his conservative approach to foreign affairs during his own eight-year tenure.</s>

<s docid="AP901123-0062" num="22" wdcount="31"> In 1986, when the U.S. bombing of Libya was criticized by world powers, Mrs. Thatcher was the only ally who supported Reagan and allowed the bombers to fly from British bases.</s>

<s docid="AP901123-0062" num="23" wdcount="18"> When Britain fought Argentina for the Falkland Islands, the United States was forced to choose between two allies.</s>

<s docid="AP901123-0062" num="24" wdcount="5"> Reagan sided with Mrs. Thatcher.</s>

<s docid="AP901123-0062" num="25" wdcount="25"> She also encouraged Reagan's nurturing of the huge Pentagon buildup, and backed U.S. efforts to install medium-range missiles in Europe, despite opposition from NATO allies.</s>

<s docid="AP901123-0062" num="26" wdcount="27"> Both leaders adopted a hard line toward the Soviet Union, but were quick to warm up to Soviet President Mikhail S. Gorbachev as the Cold War thawed.</s>

<s docid="AP901123-0062" num="27" wdcount="3"> Reagan credited Mrs.</s>

<s docid="AP901123-0062" num="28" wdcount="19"> Thatcher's ``resoluteness'' for playing a key role in ending the tensions between the Western democracies and the Eastern Block.</s>

<s docid="AP901123-0062" num="29" wdcount="15"> ``She stood up to the Soviets and let them know she meant business,'' he said.</s>

<s docid="AP901123-0062" num="30" wdcount="11"> Both were ardent advocates of the free market and private enterprise.</s>

<s docid="AP901123-0062" num="31" wdcount="19"> While the United States became mired in debt in the era of Reaganomics, the British economy thrived on Mrs.</s>

<s docid="AP901123-0062" num="32" wdcount="8"> Thatcher's radical policies during her nearly 12-year rule.</s>

<s docid="AP901123-0062" num="33" wdcount="16"> Average earnings were up by nearly one-third and more Britons owned their homes during her tenor.</s>

<s docid="AP901123-0062" num="34" wdcount="28"> Like Reagan, however, Mrs. Thatcher was accused by liberals of widening the gap between the rich and poor in her country, and both clashed with organized labor .</s>
</TEXT>
</DOC>
