<DOC>
<DOCNO>

<s docid="AP901123-0002" num="1" wdcount="1"> AP901123-0002</s>
</DOCNO>
<FILEID>

<s docid="AP901123-0002" num="2" wdcount="2"> AP-NY-11-23-90 0009EST</s>
</FILEID>
<FIRST>

<s docid="AP901123-0002" num="3" wdcount="5"> r i PM-Britain-US 11-23 0605</s>
</FIRST>
<SECOND>

<s docid="AP901123-0002" num="4" wdcount="1"> PM-Britain-US,0748</s>
</SECOND>
<HEAD>

<s docid="AP901123-0002" num="5" wdcount="8"> With Thatcher's Demise, US Loses Its Staunchest Ally</s>
</HEAD>
<NOTE>

<s docid="AP901123-0002" num="6" wdcount="7"> Eds: Also in Friday AMs report .</s>
</NOTE>
<HEAD>

<s docid="AP901123-0002" num="7" wdcount="4"> An AP News Analysis</s>
</HEAD>
<BYLINE>

<s docid="AP901123-0002" num="8" wdcount="3"> By TERENCE HUNT</s>
</BYLINE>
<BYLINE>

<s docid="AP901123-0002" num="9" wdcount="4"> AP White House Correspondent</s>
</BYLINE>
<DATELINE>

<s docid="AP901123-0002" num="10" wdcount="3"> CAIRO, Egypt (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP901123-0002" num="11" wdcount="29"> For almost a decade, Margaret Thatcher was regarded at the White House as America's best friend, the trusted ally whose strong views reinforced the conservative tone of administration policies.</s>

<s docid="AP901123-0002" num="12" wdcount="19"> Among Western allies, she was alone at Ronald Reagan's side in 1986 in supporting the U.S. bombing of Libya.</s>

<s docid="AP901123-0002" num="13" wdcount="18"> In the Persian Gulf crisis, she boldly joined with George Bush in sending troops to the Middle East.</s>

<s docid="AP901123-0002" num="14" wdcount="19"> ``You always know where she was and what she believed,'' Bush said upon hearing of her decision to resign.</s>

<s docid="AP901123-0002" num="15" wdcount="13"> ``She has always been an outstanding ally of the United States,'' he said.</s>

<s docid="AP901123-0002" num="16" wdcount="4"> ``I will miss her''.</s>

<s docid="AP901123-0002" num="17" wdcount="27"> There were many doubters around the world when Reagan arrived in Washington with an economic program of free-market capitalism that seemed out of step with the times.</s>

<s docid="AP901123-0002" num="18" wdcount="15"> Mrs. Thatcher wasn't one of the skeptics; she was advocating a similar program at home.</s>

<s docid="AP901123-0002" num="19" wdcount="7"> They shared rocky relations with organized labor.</s>

<s docid="AP901123-0002" num="20" wdcount="14"> Reagan successfully fired the nation's air traffic controllers, dealing a devastating blow to labor.</s>

<s docid="AP901123-0002" num="21" wdcount="5"> She, too, smashed restive unions.</s>

<s docid="AP901123-0002" num="22" wdcount="17"> On foreign policy, she frequently was more right wing than Reagan - certainly more so than Bush.</s>

<s docid="AP901123-0002" num="23" wdcount="14"> Reagan never made any secret of his special affection for the British prime minister.</s>

<s docid="AP901123-0002" num="24" wdcount="11"> They were ideological soulmates and called each other Ronnie and Margaret.</s>

<s docid="AP901123-0002" num="25" wdcount="9"> At international gatherings, they usually were side by side.</s>

<s docid="AP901123-0002" num="26" wdcount="40"> Two years ago as they met for the final time before Reagan left office, the president said he was leaving the White House with ``considerable satisfaction in the knowledge that Margaret Thatcher will still reside at No. 10 Downing Street''.</s>

<s docid="AP901123-0002" num="27" wdcount="21"> She later wrote him a ``Dear Ron'' letter in which she praised him as ``a great president, one of the greatest''.</s>

<s docid="AP901123-0002" num="28" wdcount="10"> Like Reagan, she was deeply suspicious of the Soviet Union.</s>

<s docid="AP901123-0002" num="29" wdcount="32"> Together they advocated a hard line toward Moscow and championed military readiness - even though she was the first to recognize Mikhail S. Gorbachev as a leader she could do business with.</s>

<s docid="AP901123-0002" num="30" wdcount="17"> Mrs. Thatcher encouraged the huge Pentagon buildup that Reagan nurtured under the theme of peace through strength.</s>

<s docid="AP901123-0002" num="31" wdcount="27"> She was a big backer of U.S. efforts to install medium-range missiles in Europe and always seemed cautious - perhaps reluctant - when it came to disarmament.</s>

<s docid="AP901123-0002" num="32" wdcount="23"> When Argentina and Britain clashed militarily over the Falkland Islands, the United States was forced to make a painful choice between two allies.</s>

<s docid="AP901123-0002" num="33" wdcount="4"> Ronnie sided with Margaret.</s>

<s docid="AP901123-0002" num="34" wdcount="12"> Washington's special relationship with London seemed to slip when Reagan left power.</s>

<s docid="AP901123-0002" num="35" wdcount="27"> Bush and Mrs. Thatcher disagreed publicly last year over her government's decision to deport Vietnamese and Cambodian ``boat people'' who were fleeing their countries to Hong Kong.</s>

<s docid="AP901123-0002" num="36" wdcount="12"> Bush, a veteran of world politics, knew many leaders around the globe.</s>

<s docid="AP901123-0002" num="37" wdcount="11"> Mrs. Thatcher suddenly seemed to be just one of the gang.</s>

<s docid="AP901123-0002" num="38" wdcount="21"> The Berlin Wall was collapsing and it appeared as if Bush found German Chancellor Helmut Kohl more interesting than Mrs. Thatcher.</s>

<s docid="AP901123-0002" num="39" wdcount="23"> She was merely one in a parade of foreign dignitaries who got the prized invitation to visit Bush at Camp David this year.</s>

<s docid="AP901123-0002" num="40" wdcount="21"> Nevertheless, Bush said he expected the ``special relationship'' between the United States and Great Britain to remain on a ``steady keel''.</s>

<s docid="AP901123-0002" num="41" wdcount="8"> Mrs. Thatcher did her part, demonstrating her loyalty.</s>

<s docid="AP901123-0002" num="42" wdcount="27"> For awhile she and Bush were seemingly alone in their suspicions of Gorbachev's unilateral cutbacks in troops and arms in Europe, and appeared uncertain how to respond.</s>

<s docid="AP901123-0002" num="43" wdcount="13"> Under intense pressure from Congress, Bush began to warm to the Soviet leader.</s>

<s docid="AP901123-0002" num="44" wdcount="7"> Now they seem almost best of friends.</s>

<s docid="AP901123-0002" num="45" wdcount="26"> On the Persian Gulf, Bush said he would not rule out possible military force, and ordered a huge buildup of troops to make his threat credible.</s>

<s docid="AP901123-0002" num="46" wdcount="5"> Mrs. Thatcher, characteristically, was tougher.</s>

<s docid="AP901123-0002" num="47" wdcount="22"> She said that unless Saddam Hussein got out of Kuwait soon, the West would have to use military force to dislodge him.</s>

<s docid="AP901123-0002" num="48" wdcount="18"> She called Saddam ``a loser,'' and the state-controlled Iraqi news agency replied that she was an ``old hag''.</s>

<s docid="AP901123-0002" num="49" wdcount="4"> Now, she is leaving.</s>

<s docid="AP901123-0002" num="50" wdcount="19"> No one suspects that Britain's new leadership - whoever it is - will take a soft line toward Iraq.</s>

<s docid="AP901123-0002" num="51" wdcount="25"> Yet, if the going gets tough, it might have been comforting for Bush to be able to hear the tough old line from Thatcher .</s>
</TEXT>
</DOC>
