<DOC>
<DOCNO>

<s docid="LA040689-0198" num="1" wdcount="1"> LA040689-0198</s>
</DOCNO>
<DOCID>

<s docid="LA040689-0198" num="2" wdcount="1"> 40693</s>
</DOCID>
<DATE>
<P>

<s docid="LA040689-0198" num="3" wdcount="6"> April 6, 1989, Thursday, P.M. Final</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA040689-0198" num="4" wdcount="9"> Part A; Page 2; Column 3; Late Final Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA040689-0198" num="5" wdcount="2"> 310 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA040689-0198" num="6" wdcount="5"> GORBACHEV, THATCHER TALK 4 HOURS;</s>
</P>
<P>

<s docid="LA040689-0198" num="7" wdcount="10"> SESSION COVERS WIDE RANGE OF SUBJECTS; THEY 'LOVE TO ARGUE'</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA040689-0198" num="8" wdcount="3"> From Associated Press</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA040689-0198" num="9" wdcount="1"> LONDON</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA040689-0198" num="10" wdcount="34"> Soviet President Mikhail S. Gorbachev and Prime Minister Margaret Thatcher today argued passionately during a four-hour meeting that covered subjects ranging from disarmament to reports of Soviet bomber sales to Libya, officials said .</s>
</P>
<P>

<s docid="LA040689-0198" num="11" wdcount="29"> Reopening a European peace offensive that was disrupted by the Armenian earthquake, Gorbachev had "extremely frank exchanges, animated, warm, passionate and solemn," said a Thatcher spokesman, requesting anonymity .</s>
</P>
<P>

<s docid="LA040689-0198" num="12" wdcount="30"> Gorbachev also hit the streets of London, stopping his motorcade to shake hands with about 20 people in a crowd of several hundred who cheered him outside Westminster Abbey .</s>
</P>
<P>

<s docid="LA040689-0198" num="13" wdcount="16"> The Thatcher spokesman said the Soviet leader and the staunchly anti-Communist prime minister "love arguing" .</s>
</P>
<P>

<s docid="LA040689-0198" num="14" wdcount="19"> Emerging from her 10 Downing St. residence into the icy rain with Gorbachev at her side, Thatcher told reporters:</s>
</P>
<P>

<s docid="LA040689-0198" num="15" wdcount="24"> "The talks have been very deep, very wide ranging and very friendly, and as always we got to grips with the real issues" .</s>
</P>
<P>

<s docid="LA040689-0198" num="16" wdcount="27"> The spokesman said Thatcher asked Gorbachev about a report from Washington that Moscow sold up to 15 long-range fighter-bombers to Libya, which Britain accuses of sponsoring terrorism.</s>

<s docid="LA040689-0198" num="17" wdcount="7"> Gorbachev did not respond, he said .</s>
</P>
<P>

<s docid="LA040689-0198" num="18" wdcount="32"> Although the two leaders could make no progress on the bomber issue, the spokesman said the Soviet and British foreign ministers, meeting separately, would most likely discuss the matter at length .</s>
</P>
<P>

<s docid="LA040689-0198" num="19" wdcount="23"> He said Thatcher also accused the Soviets of having been "not as frank as they should be" about their chemical weapons arsenal .</s>
</P>
<P>

<s docid="LA040689-0198" num="20" wdcount="19"> He quoted Gorbachev as replying: "If you aren't fully satisfied, then quite clearly we have to have more exchanges.</s>

<s docid="LA040689-0198" num="21" wdcount="11"> We have got to try better to convince each other" .</s>
</P>
<P>

<s docid="LA040689-0198" num="22" wdcount="14"> Another area of disagreement was Gorbachev's goal of eliminating all nuclear weapons from Europe.</s>

<s docid="LA040689-0198" num="23" wdcount="10"> Thatcher believes the deterrence of nuclear weapons prevents war .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA040689-0198" num="24" wdcount="14"> Photo, Soviet leader Mikhail Gorbachev checks his watch as Prime Minister Margaret Thatcher speaks.</s>

<s docid="LA040689-0198" num="25" wdcount="2"> Associated Press</s>
</P>
</GRAPHIC>
<TYPE>
<P>

<s docid="LA040689-0198" num="26" wdcount="1"> Wire</s>
</P>
</TYPE>
</DOC>
