<DOC>
<DOCNO>

<s docid="LA112190-0001" num="1" wdcount="1"> LA112190-0001</s>
</DOCNO>
<DOCID>

<s docid="LA112190-0001" num="2" wdcount="1"> 311051</s>
</DOCID>
<DATE>
<P>

<s docid="LA112190-0001" num="3" wdcount="6"> November 21, 1990, Wednesday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA112190-0001" num="4" wdcount="10"> Metro; Part B; Page 6; Column 3; Editorial Writers Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA112190-0001" num="5" wdcount="2"> 339 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA112190-0001" num="6" wdcount="5"> THERE'LL ALWAYS BE AN ENGLAND;</s>
</P>
<P>

<s docid="LA112190-0001" num="7" wdcount="8"> BUT MARGARET THATCHER WON'T ALWAYS BE PRIME MINISTER</s>
</P>
</HEADLINE>
<TEXT>
<P>

<s docid="LA112190-0001" num="8" wdcount="19"> Embattled Margaret Thatcher remains leader of Britain's Conservative Party, and so the country's prime minister -- but only barely.</s>

<s docid="LA112190-0001" num="9" wdcount="28"> She has survived a vote of confidence taken by her party colleagues in the House of Commons, winning 204 votes against 152 for former defense minister Michael Heseltine.</s>

<s docid="LA112190-0001" num="10" wdcount="25"> But under Tory party rules, that margin, representing something less than a ringing endorsement, forces Thatcher to face a second round of voting on Tuesday.</s>

<s docid="LA112190-0001" num="11" wdcount="27"> Other candidates could choose to stand against her, perhaps diluting the opposition vote and letting her claim the simple majority she needs to stay as party head.</s>

<s docid="LA112190-0001" num="12" wdcount="7"> But her reelection is hardly assured .</s>
</P>
<P>

<s docid="LA112190-0001" num="13" wdcount="19"> Polls show the Tories would do better in the next national elections with someone other than Thatcher leading them.</s>

<s docid="LA112190-0001" num="14" wdcount="17"> But elections don't have to be called until mid-1992; Thatcher's public standing could conceivably increase by then.</s>

<s docid="LA112190-0001" num="15" wdcount="11"> Thatcher has served as PM longer than anyone in this century.</s>

<s docid="LA112190-0001" num="16" wdcount="49"> She led her party to victory in three elections, steered it through the war with Argentina to reclaim the Falklands, faced down the miners union in a long strike, moved -- often drastically -- to reverse Britain's economic decline and won a prominent place on the world stage .</s>
</P>
<P>

<s docid="LA112190-0001" num="17" wdcount="10"> But 11 1/2 years in office is a long time.</s>

<s docid="LA112190-0001" num="18" wdcount="34"> Memory and feelings being what they are, it is the mistakes and irritations of this long tenure that are more likely to be immediately recalled, while its achievements are left to history to salute.</s>

<s docid="LA112190-0001" num="19" wdcount="19"> Thatcher is seen as having become increasingly autocratic at home and a somewhat tiresome scold within the European Community.</s>

<s docid="LA112190-0001" num="20" wdcount="30"> Her government is deeply identified with high interest rates, inflation and a flat tax on every adult (in place of the property tax) that is generally regarded as hugely unfair.</s>

<s docid="LA112190-0001" num="21" wdcount="35"> Ultimately, in the cold calculus of politics, the question that will most decisively sway Conservative MPs is whether they are more likely to win the next election with Thatcher at their head or someone else.</s>

<s docid="LA112190-0001" num="22" wdcount="7"> Next week will bring the answer .</s>
</P>
</TEXT>
<TYPE>
<P>

<s docid="LA112190-0001" num="23" wdcount="1"> Editorial</s>
</P>
</TYPE>
</DOC>
