<DOC>
<DOCNO>

<s docid="LA112390-0008" num="1" wdcount="1"> LA112390-0008</s>
</DOCNO>
<DOCID>

<s docid="LA112390-0008" num="2" wdcount="1"> 312054</s>
</DOCID>
<DATE>
<P>

<s docid="LA112390-0008" num="3" wdcount="6"> November 23, 1990, Friday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA112390-0008" num="4" wdcount="9"> Metro; Part B; Page 5; Column 4; Op-Ed Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA112390-0008" num="5" wdcount="2"> 857 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA112390-0008" num="6" wdcount="8"> THE ROMANCE IS OVER; THE ANGLO PARTNERSHIP PALES;</s>
</P>
<P>

<s docid="LA112390-0008" num="7" wdcount="19"> THATCHER: SHE WAS A SYMBIOTIC ALLY TO REAGAN AND THEN BUSH; SHE SIMPLY LOST HER OWN PARTY'S ALLEGIANCE .</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA112390-0008" num="8" wdcount="18"> By PETER STOTHARD, Peter Stothard is the U.S. editor, based in Washington, of the Times of London .</s>
</P>
</BYLINE>
<TEXT>
<P>

<s docid="LA112390-0008" num="9" wdcount="16"> President Bush lost an irreplaceable pin supporting his mission in the Persian Gulf on Thanksgiving Day.</s>

<s docid="LA112390-0008" num="10" wdcount="25"> He heard the news of Margaret Thatcher's resignation as he celebrated the holiday in the Saudi desert -- and it clearly came as a shock.</s>

<s docid="LA112390-0008" num="11" wdcount="10"> In the State Department, too, it came as a shock.</s>

<s docid="LA112390-0008" num="12" wdcount="22"> Americans who had come to take Thatcher for granted during her 11 years of power were not prepared for her passing .</s>
</P>
<P>

<s docid="LA112390-0008" num="13" wdcount="24"> Thatcher had told the world that she would fight to a second ballot after her narrow failure to retain the premiership outright on Tuesday.</s>

<s docid="LA112390-0008" num="14" wdcount="11"> The feeling everywhere was that Thatcher always stuck to her word.</s>

<s docid="LA112390-0008" num="15" wdcount="3"> So no problem.</s>

<s docid="LA112390-0008" num="16" wdcount="4"> Pass the turkey .</s>
</P>
<P>

<s docid="LA112390-0008" num="17" wdcount="37"> Thatcher's friends all over the world had reckoned without the British Conservative Party, which had looked at the opinion polls, the bad economic news and an unpopular new tax and smelled a loss at the next election.</s>

<s docid="LA112390-0008" num="18" wdcount="32"> They had reckoned without the hatred for the flamboyant Michael Heseltine among the middle-ranking party figures who risked losing their jobs and future prospects if the unpredictable "Tarzan" came to power .</s>
</P>
<P>

<s docid="LA112390-0008" num="19" wdcount="52"> It was an extraordinary scene in the palace of Westminster on Wednesday night as one by one her own Cabinet members trooped sheepishly into Thatcher's office and told her, in their chosen code, that they "couldn't support her over the weekend" in the second round of secret balloting on the party's leadership.</s>

<s docid="LA112390-0008" num="20" wdcount="14"> Therefore, if Heseltine was to be beaten, it had to be by someone else.</s>

<s docid="LA112390-0008" num="21" wdcount="20"> After "sleeping on it," as one of her closest advisers put it, Thatcher reluctantly concluded that she had to go.</s>

<s docid="LA112390-0008" num="22" wdcount="37"> Thus did the toughest fighter for shared British and American values since Winston Churchill become the first prime minister to be forced out of office by the Conservative Party since the failed war leader Neville Chamberlain .</s>
</P>
<P>

<s docid="LA112390-0008" num="23" wdcount="14"> When George Bush recovered from his Thanksgiving surprise, he was generous in his praise.</s>

<s docid="LA112390-0008" num="24" wdcount="9"> Two years ago, his words would have rung hollow.</s>

<s docid="LA112390-0008" num="25" wdcount="12"> The President began his term in office without much trust in her.</s>

<s docid="LA112390-0008" num="26" wdcount="20"> He had seen the influence she exerted over Ronald Reagan and was keen to be seen as his own man.</s>

<s docid="LA112390-0008" num="27" wdcount="33"> He had heard her doubts over the pace of German reunification and the integration of Europe, and had been persuaded by his advisers that she stood against the United States' best interests .</s>
</P>
<P>

<s docid="LA112390-0008" num="28" wdcount="4"> Gradually, however, that changed.</s>

<s docid="LA112390-0008" num="29" wdcount="14"> At the beginning of the Persian Gulf crisis, the President deliberately sought Thatcher's analysis.</s>

<s docid="LA112390-0008" num="30" wdcount="29"> It was her assessment of the threat to international security posed by Iraqi aggression that, according to British and American sources, set the moral framework for Operation Desert Shield.</s>

<s docid="LA112390-0008" num="31" wdcount="33"> The pivotal moment was when she fielded press questions about Iraq on Bush's behalf in the Colorado mountain garden of the U.S. ambassador to Britain, Henry Catto; that marked the public turning point.</s>

<s docid="LA112390-0008" num="32" wdcount="10"> She was able to articulate what Bush sensed was right.</s>

<s docid="LA112390-0008" num="33" wdcount="20"> And he was able to defer to her without embarrassment, seeming almost gentlemanly in allowing her to go first .</s>
</P>
<P>

<s docid="LA112390-0008" num="34" wdcount="15"> Bush is unlikely to reach such a rapport with any of her three potential successors.</s>

<s docid="LA112390-0008" num="35" wdcount="17"> Heseltine is an exceptionally powerful orator, but it hard to see that helping the tongue-tied American President.</s>

<s docid="LA112390-0008" num="36" wdcount="18"> Douglas Hurd, the urbane foreign secretary, is an English James Baker; the President already has a James Baker.</s>

<s docid="LA112390-0008" num="37" wdcount="21"> John Major, the chancellor of the Exchequer and Thatcher's own choice to succeed her, may have views very close to Bush's.</s>

<s docid="LA112390-0008" num="38" wdcount="22"> But he is mild-mannered, slightly clumsy and, although widely liked and admired by his friends, is almost wholly without international experience .</s>
</P>
<P>

<s docid="LA112390-0008" num="39" wdcount="9"> The issue is no longer the Anglo-American "special relationship".</s>

<s docid="LA112390-0008" num="40" wdcount="19"> It is Margaret Thatcher and Ronald Reagan who will go down in history as Washington and London's "last romantics".</s>

<s docid="LA112390-0008" num="41" wdcount="45"> They were the ones who would each ditch their closest friends in order to support the other: Reagan when overruling Jeane Kirkpatrick's objections to the Falklands campaign, and Thatcher when blocking her own right wing's protests at the U.S. bombing of Libya from British bases.</s>

<s docid="LA112390-0008" num="42" wdcount="26"> They shared the conviction that communism could be rolled back -- and she helped persuade him that Mikhail Gorbachev was a man who could be trusted.</s>

<s docid="LA112390-0008" num="43" wdcount="25"> The powerful enunciation of that belief -- and its eventual vindication -- may be the last great achievement of the special postwar Anglo-American alliance .</s>
</P>
<P>

<s docid="LA112390-0008" num="44" wdcount="23"> George Bush and Margaret Thatcher had something more simple in common, a pragmatic relationship of mutual respect and support that benefited both .</s>
</P>
<P>

<s docid="LA112390-0008" num="45" wdcount="13"> British policy toward Iraq will not change suddenly under a new prime minister.</s>

<s docid="LA112390-0008" num="46" wdcount="17"> The doubling of the size of the British gulf force on Thursday attempted emphatically to prove that.</s>

<s docid="LA112390-0008" num="47" wdcount="18"> But as time goes by, Britain's allies will find that many certainties have passed along with Margaret Thatcher.</s>

<s docid="LA112390-0008" num="48" wdcount="22"> If seductive deals emerge to save the face and the atomic-weapon factories of Saddam Hussein, her steadfastness will be sorely missed .</s>
</P>
<P>

<s docid="LA112390-0008" num="49" wdcount="28"> And if Europe becomes more inward-looking and protectionist, blame those who booted out the prime minister whose final words to her Cabinet were, "It's a funny old world".</s>

<s docid="LA112390-0008" num="50" wdcount="8"> Her memoirs deserve a more dignified title .</s>
</P>
</TEXT>
<TYPE>
<P>

<s docid="LA112390-0008" num="51" wdcount="1"> Opinion</s>
</P>
</TYPE>
</DOC>
