<DOC>
<DOCNO>

<s docid="LA112090-0165" num="1" wdcount="1"> LA112090-0165</s>
</DOCNO>
<DOCID>

<s docid="LA112090-0165" num="2" wdcount="1"> 311032</s>
</DOCID>
<DATE>
<P>

<s docid="LA112090-0165" num="3" wdcount="6"> November 20, 1990, Tuesday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA112090-0165" num="4" wdcount="10"> World Report; Part H; Page 2; Column 1; Foreign Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA112090-0165" num="5" wdcount="2"> 1094 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA112090-0165" num="6" wdcount="2"> THE PRESS;</s>
</P>
<P>

<s docid="LA112090-0165" num="7" wdcount="7"> TORIES' TORMENT: WHAT TO DO WITH THATCHER?</s>
</P>
</HEADLINE>
<TEXT>
<P>

<s docid="LA112090-0165" num="8" wdcount="25"> Flamboyant former Defense Minister Michael Heseltine's challenge to Prime Minister Margaret Thatcher for leadership of the Conservative Party has caused a political sensation in Britain.</s>

<s docid="LA112090-0165" num="9" wdcount="54"> A crucial first vote of Tory Members of Parliament (MPs) is scheduled for today, and if Heseltine should wrest control of the party from Thatcher -- the longest-serving British head of government in modern times -- she would also have to give up the prime minister's job that she has held since 1979 .</s>
</P>
<P>

<s docid="LA112090-0165" num="10" wdcount="13"> Here's a sampling of editorial comment on the contest that has stirred Britain:</s>
</P>
<P>

<s docid="LA112090-0165" num="11" wdcount="9"> "The Thatcher era in British politics is almost over.</s>

<s docid="LA112090-0165" num="12" wdcount="14"> . . . It is more likely than not that she is finished altogether.</s>

<s docid="LA112090-0165" num="13" wdcount="11"> The coup de grace may not be delivered at this moment.</s>

<s docid="LA112090-0165" num="14" wdcount="12"> The nature of the era that comes afterward is far from clear.</s>

<s docid="LA112090-0165" num="15" wdcount="23"> But as a political force, she is condemned at best to an unrelenting rear-guard action which will end sometime in a humiliating abyss.</s>

<s docid="LA112090-0165" num="16" wdcount="3"> . . .</s>
</P>
<P>

<s docid="LA112090-0165" num="17" wdcount="40"> "The party may sullenly support her now, but they will ask the question again in the spring, knowing that if they do not do so the country will ask the same question even more pitilessly when the general election comes.</s>

<s docid="LA112090-0165" num="18" wdcount="3"> . . .</s>
</P>
<P>

<s docid="LA112090-0165" num="19" wdcount="8"> "An alternative, however, stares her in the face.</s>

<s docid="LA112090-0165" num="20" wdcount="36"> . . . It is to acknowledge that an era has passed, and preserve its achievements by standing down, releasing her lieutenants and urging her party, in the interests of a vanished unity, to support Mr.</s>

<s docid="LA112090-0165" num="21" wdcount="5"> (Foreign Minister Douglas) Hurd" .</s>
</P>
<P>

<s docid="LA112090-0165" num="22" wdcount="8"> -- Thatcher biographer Hugo Young in The Guardian</s>
</P>
<P>

<s docid="LA112090-0165" num="23" wdcount="16"> "The contest for the leadership of the Conservative party . . . should not be occurring.</s>

<s docid="LA112090-0165" num="24" wdcount="3"> . . .</s>
</P>
<P>

<s docid="LA112090-0165" num="25" wdcount="17"> "It would be foolish to deny that, today, the prime minister is politically beleaguered as never before.</s>

<s docid="LA112090-0165" num="26" wdcount="50"> . . . But the task of the Conservative party, in the year and more that remains before the next general election, must be to rally to enable Mrs. Thatcher to rebuild her personal position, and give her the confidence and support to win the fourth term she deserves" .</s>
</P>
<P>

<s docid="LA112090-0165" num="27" wdcount="4"> -- The Daily Telegraph</s>
</P>
<P>

<s docid="LA112090-0165" num="28" wdcount="24"> "Who could have guessed . . . from watching the prime minister answer questions in the Commons that she was fighting for her life?</s>

<s docid="LA112090-0165" num="29" wdcount="8"> She was as brisk and well-briefed as ever.</s>

<s docid="LA112090-0165" num="30" wdcount="3"> . . .</s>
</P>
<P>

<s docid="LA112090-0165" num="31" wdcount="5"> "Bloodied Margaret Thatcher may be.</s>

<s docid="LA112090-0165" num="32" wdcount="7"> Bowed she most certainly is not" .</s>
</P>
<P>

<s docid="LA112090-0165" num="33" wdcount="3"> -- Daily Mail</s>
</P>
<P>

<s docid="LA112090-0165" num="34" wdcount="18"> "British Conservative MPs must be prepared to reject Mrs. Thatcher when they vote in the party's leadership election.</s>

<s docid="LA112090-0165" num="35" wdcount="35"> . . . It is no longer in the interests of the United Kingdom, which are now inextricably linked with the development of a strong and united Europe, for her to remain in office .</s>
</P>
<P>

<s docid="LA112090-0165" num="36" wdcount="9"> "The European derives no satisfaction from reaching this conclusion.</s>

<s docid="LA112090-0165" num="37" wdcount="33"> Apart from her domestic achievements in reviving the British economy in the 1980s, Mrs. Thatcher has contributed much more to the development of the European Community than she is often given credit for.</s>

<s docid="LA112090-0165" num="38" wdcount="3"> . . .</s>
</P>
<P>

<s docid="LA112090-0165" num="39" wdcount="26"> "But The European believes that her nightmare vision of Europe, of ill-intentioned people trying to destroy democracy, is not shared by most of the British people.</s>

<s docid="LA112090-0165" num="40" wdcount="13"> They reject her view that pooling of sovereignty is no different from surrender.</s>

<s docid="LA112090-0165" num="41" wdcount="3"> . . .</s>
</P>
<P>

<s docid="LA112090-0165" num="42" wdcount="7"> "The Conservative Party faces a stark choice.</s>

<s docid="LA112090-0165" num="43" wdcount="24"> Either it will reelect Mrs. Thatcher and see the United Kingdom slip into isolation as it is left behind the rest of the Community.</s>

<s docid="LA112090-0165" num="44" wdcount="22"> Or it can choose a new leader who is prepared to participate genuinely in the argument about economic and political union" .</s>
</P>
<P>

<s docid="LA112090-0165" num="45" wdcount="3"> -- The European</s>
</P>
<P>
</P>
<P>

<s docid="LA112090-0165" num="46" wdcount="23"> "A prime minister in total command for 11 years could not be unseated, and cherished policies abandoned, without an explosion within the party.</s>

<s docid="LA112090-0165" num="47" wdcount="13"> It would take a Solomon to heal the divisions and prevent civil war.</s>

<s docid="LA112090-0165" num="48" wdcount="10"> Frankly, we cannot see Mr. Heseltine in that role .</s>
</P>
<P>

<s docid="LA112090-0165" num="49" wdcount="16"> "The Sun also deeply questions his ability to be a successful or even adequate prime minister.</s>

<s docid="LA112090-0165" num="50" wdcount="27"> . . . This is the man who for the past five years has professed loyalty to the government and yet has been its most divisive force.</s>

<s docid="LA112090-0165" num="51" wdcount="14"> We discern just one constant loyalty -- and that is to Michael Heseltine" .</s>
</P>
<P>

<s docid="LA112090-0165" num="52" wdcount="3"> -- The Sun</s>
</P>
<P>

<s docid="LA112090-0165" num="53" wdcount="25"> "Mrs. Thatcher deserves better than to be dismissed in the shoddy and demeaning manner some Tory MPs are minded to have in store for her.</s>

<s docid="LA112090-0165" num="54" wdcount="21"> To be defeated by the people in a general election, as was Winston Churchill in 1945, that was an honorable rejection.</s>

<s docid="LA112090-0165" num="55" wdcount="31"> To be brought down by a vote of censure in the House of Commons, as was Neville Chamberlain in 1940 -- even that was a constitutionally respectable form of political demise.</s>

<s docid="LA112090-0165" num="56" wdcount="23"> But what they are proposing to do to Mrs. Thatcher, unquestionably the greatest peacetime prime minister of this century, is quite simply unworthy.</s>

<s docid="LA112090-0165" num="57" wdcount="17"> Her fate could be sealed, if her opponents have their way, behind closed doors in smoke-filled rooms.</s>

<s docid="LA112090-0165" num="58" wdcount="24"> . . . Persons of quality were always accorded the dignity of execution by ax or firing squad, rather than the humiliation of hanging.</s>

<s docid="LA112090-0165" num="59" wdcount="22"> These plotters would like to dispatch Mrs. Thatcher, who almost single-handedly has won three elections, by the political equivalent of the rope.</s>

<s docid="LA112090-0165" num="60" wdcount="3"> . . .</s>
</P>
<P>

<s docid="LA112090-0165" num="61" wdcount="7"> "You can find Heseltines wherever you go.</s>

<s docid="LA112090-0165" num="62" wdcount="7"> But there is only one Mrs. Thatcher.</s>

<s docid="LA112090-0165" num="63" wdcount="3"> Handle with care.</s>

<s docid="LA112090-0165" num="64" wdcount="6"> This valuable object is irreplaceable" .</s>
</P>
<P>

<s docid="LA112090-0165" num="65" wdcount="4"> -- The Sunday Telegraph</s>
</P>
<P>

<s docid="LA112090-0165" num="66" wdcount="27"> "This newspaper has long maintained that the best result in the next general election would be for Margaret Thatcher to lead the Tories to a fourth victory.</s>

<s docid="LA112090-0165" num="67" wdcount="11"> Sadly, the course of events has conspired to make that unlikely.</s>

<s docid="LA112090-0165" num="68" wdcount="3"> . . .</s>
</P>
<P>

<s docid="LA112090-0165" num="69" wdcount="22"> "The British have never liked Margaret Thatcher; but as long as she delivered the goods they respected her, and voted for her.</s>

<s docid="LA112090-0165" num="70" wdcount="16"> When her government fails (as it has recently), that lack of affection turns to growing resentment.</s>

<s docid="LA112090-0165" num="71" wdcount="25"> For reasons that are probably unfair and undeserved, Mrs. Thatcher is now a victim of that strongest public mood of all: time for a change.</s>

<s docid="LA112090-0165" num="72" wdcount="3"> . . .</s>
</P>
<P>

<s docid="LA112090-0165" num="73" wdcount="22"> "Mrs. Thatcher is right to feel bitter that a prime minister with her track record and prestige can be so easily challenged.</s>

<s docid="LA112090-0165" num="74" wdcount="36"> If she goes, the manner of her ousting will leave much to be desired; no other party could so lightly dispose of its leader in government, this side of an election, largely for reasons of unpopularity.</s>

<s docid="LA112090-0165" num="75" wdcount="25"> But the Tories have a nose for survival in power unmatched by any other party in the democratic world, and politics is an unforgiving business.</s>

<s docid="LA112090-0165" num="76" wdcount="26"> The issue before Tory MPs . . . is not the reelection of Margaret Thatcher, it is the defeat of (opposition Labor Party leader) Neil Kinnock.</s>

<s docid="LA112090-0165" num="77" wdcount="16"> That requires saying a reluctant goodby to Mrs. Thatcher, and the endorsement of Michael Heseltine" .</s>
</P>
<P>

<s docid="LA112090-0165" num="78" wdcount="4"> -- The Sunday Times</s>
</P>
</TEXT>
<SUBJECT>
<P>

<s docid="LA112090-0165" num="79" wdcount="14"> NEWSPAPERS -- ENGLAND; ENGLAND -- POLITICS; THATCHER, MARGARET; HESELTINE, MICHAEL; CONSERVATIVE PARTY (ENGLAND); LEADERSHIP</s>
</P>
</SUBJECT>
</DOC>
