<DOC>
<DOCNO>

<s docid="LA120890-0055" num="1" wdcount="1"> LA120890-0055</s>
</DOCNO>
<DOCID>

<s docid="LA120890-0055" num="2" wdcount="1"> 319341</s>
</DOCID>
<DATE>
<P>

<s docid="LA120890-0055" num="3" wdcount="6"> December 8, 1990, Saturday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA120890-0055" num="4" wdcount="8"> Part A; Page 16; Column 1; Foreign Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA120890-0055" num="5" wdcount="2"> 434 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA120890-0055" num="6" wdcount="10"> IT'S NOW 'LADY THATCHER,' BUT SHE'LL STICK WITH 'MRS' .</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA120890-0055" num="7" wdcount="6"> By WILLIAM TUOHY, TIMES STAFF WRITER</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA120890-0055" num="8" wdcount="1"> LONDON</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA120890-0055" num="9" wdcount="28"> Queen Elizabeth II awarded former Prime Minister Margaret Thatcher the coveted Order of Merit on Friday and made her husband a baronet, which is a hereditary knighthood .</s>
</P>
<P>

<s docid="LA120890-0055" num="10" wdcount="32"> From now on Denis Thatcher will be formally addressed as Sir Denis and his wife as Lady Thatcher, although she insisted Friday she wished to be known simply as "Mrs. Thatcher" .</s>
</P>
<P>

<s docid="LA120890-0055" num="11" wdcount="30"> "I have done pretty well out of being Mrs. Thatcher," said the former prime minister, who resigned Nov. 22 during a fight for the leadership of the Conservative Party .</s>
</P>
<P>

<s docid="LA120890-0055" num="12" wdcount="42"> Palace insiders said Friday that one reason for the quick award of the Order of Merit, restricted to only 24 eminent men and women, was the queen's desire to demonstrate that there is no animosity between Britain's two most prominent women .</s>
</P>
<P>

<s docid="LA120890-0055" num="13" wdcount="23"> In the past, Buckingham Palace sources and journalists assigned to the royal court have said that the two did not get along .</s>
</P>
<P>

<s docid="LA120890-0055" num="14" wdcount="30"> "This puts (to rest) rumors that the queen and Mrs. Thatcher didn't like each other," said Harold Brooks-Baker, director of Burke's Peerage and an authority on the royal family .</s>
</P>
<P>

<s docid="LA120890-0055" num="15" wdcount="48"> As a member of the Order of Merit, created in 1902, Thatcher joins such luminaries in the world of arts, science and politics as philosopher Isiah Berlin, historian Veronica Wedgwood, writer Graham Greene, violinist Yehudi Menuhin and artist Sidney Noland, as well as honorary member Mother Teresa .</s>
</P>
<P>

<s docid="LA120890-0055" num="16" wdcount="19"> Deceased recipients include Prime Minister Winston Churchill, Gen. Dwight D. Eisenhower, missionary Albert Schweitzer and actor Lawrence Olivier .</s>
</P>
<P>

<s docid="LA120890-0055" num="17" wdcount="32"> Contrary to some reports, the OM, as it is popularly called, does not precede all other British royal honors but ranks behind the Order of the Garter, which dates from 1348 .</s>
</P>
<P>

<s docid="LA120890-0055" num="18" wdcount="12"> Thatcher said she was "deeply honored and moved" by the award .</s>
</P>
<P>

<s docid="LA120890-0055" num="19" wdcount="38"> At the same time, the queen gave a baronetcy to Thatcher's husband Denis, the subject of fictional letters from No. 10 Downing Street invented by the satirical magazine Private Eye about life as the prime minister's consort .</s>
</P>
<P>

<s docid="LA120890-0055" num="20" wdcount="4"> Baronets date from 1611.</s>

<s docid="LA120890-0055" num="21" wdcount="27"> Sir Denis' title passes upon his death to his son, Mark, who is married to an American, and will eventually pass to Mark Thatcher's son, Michael .</s>
</P>
<P>

<s docid="LA120890-0055" num="22" wdcount="24"> With an OM, Thatcher can continue to serve in the House of Commons as the member from the North London constituency of Finchley .</s>
</P>
<P>

<s docid="LA120890-0055" num="23" wdcount="22"> Burke's Brooks-Baker believes that Thatcher eventually should be made a hereditary countess, which in Britain is the female equivalent of an earl.</s>

<s docid="LA120890-0055" num="24" wdcount="25"> Traditionally, retiring prime ministers of Britain were granted earldoms, although Churchill, for one, refused a peerage, preferring to remain in the House of Commons .</s>
</P>
</TEXT>
<SUBJECT>
<P>

<s docid="LA120890-0055" num="25" wdcount="8"> THATCHER, MARGARET; THATCHER, DENIS; HONORS; ENGLAND -- POLITICS</s>
</P>
</SUBJECT>
</DOC>
