<DOC>
<DOCNO>

<s docid="AP891116-0191" num="1" wdcount="1"> AP891116-0191</s>
</DOCNO>
<FILEID>

<s docid="AP891116-0191" num="2" wdcount="2"> AP-NR-11-16-89 2029EST</s>
</FILEID>
<FIRST>

<s docid="AP891116-0191" num="3" wdcount="7"> u a AM-Storms-Glance 1stLd-Writethru a0771 11-16 0704</s>
</FIRST>
<SECOND>

<s docid="AP891116-0191" num="4" wdcount="4"> AM-Storms-Glance, 1st Ld-Writethru, a0771,0717</s>
</SECOND>
<HEAD>

<s docid="AP891116-0191" num="5" wdcount="4"> With AM-Southern Tornadoes, Bjt</s>
</HEAD>
<HEAD>

<s docid="AP891116-0191" num="6" wdcount="27"> Eds: INSERTS items on Illinois and Ohio, changes death toll to 27 to reflect Illinois death, SUBS West Virginia item to CORRECT location of Jefferson County .</s>
</HEAD>
<BYLINE>

<s docid="AP891116-0191" num="7" wdcount="4"> By The Associated Press</s>
</BYLINE>
<TEXT>

<s docid="AP891116-0191" num="8" wdcount="28"> Here is a state-by-state look at the tornadoes and severe thunderstorms that have killed at least 27 people, injured more than 500 and left hundreds homeless since Wednesday:</s>
</TEXT>
<TEXT>

<s docid="AP891116-0191" num="9" wdcount="21"> _Alabama: Seventeen people were killed in Huntsville on Wednesday when a tornado touched down just before rush hour, causing major damage.</s>

<s docid="AP891116-0191" num="10" wdcount="12"> There were 463 injuries and about 1,000 people left homeless, authorities said.</s>

<s docid="AP891116-0191" num="11" wdcount="14"> Three people were injured in an earlier tornado in Clay County in eastern Alabama.</s>

<s docid="AP891116-0191" num="12" wdcount="23"> _District of Columbia: Heavy thunderstorms packing 50-60 mph winds swept through the Washington area during the Thursday morning rush hour, flooding some streets.</s>

<s docid="AP891116-0191" num="13" wdcount="10"> About 10,000 customers lost power, mostly in the Maryland suburbs.</s>

<s docid="AP891116-0191" num="14" wdcount="4"> No injuries were reported.</s>

<s docid="AP891116-0191" num="15" wdcount="35"> _Georgia: 19 people were injured, four critically, and at least 200 people were evacuated Wednesday after a tornado struck two mobile home parks and an interstate highway near Palmetto, about 25 miles southeast of Atlanta.</s>

<s docid="AP891116-0191" num="16" wdcount="20"> _Illinois: Strong winds Wednesday morning destroyed about 15 homes and killed one woman in St. Clair County in southwestern Illinois.</s>

<s docid="AP891116-0191" num="17" wdcount="9"> Damage was estimated at $3 million to $5 million.</s>

<s docid="AP891116-0191" num="18" wdcount="14"> _Indiana: A tornado was spotted Wednesday afternoon around Richmond, close to the Ohio border.</s>

<s docid="AP891116-0191" num="19" wdcount="14"> It ripped the top off a silo and tipped a semi-trailer into a ditch.</s>

<s docid="AP891116-0191" num="20" wdcount="5"> The driver was slightly injured.</s>

<s docid="AP891116-0191" num="21" wdcount="18"> _Kentucky: The storm Wednesday left at least 28 people injured; damage was estimated at $2.5 million or more.</s>

<s docid="AP891116-0191" num="22" wdcount="22"> A storm believed to have been a tornado cut a mile-long swath of destruction through the town of Flaherty in Meade County.</s>

<s docid="AP891116-0191" num="23" wdcount="11"> Damage was also reported in Bullitt, LaRue, Hardin and Pendleton counties.</s>

<s docid="AP891116-0191" num="24" wdcount="32"> _Maryland, Delaware: Heavy winds on Thursday leveled a church building in Kent County, Md., lifted roofs from buildings in Baltimore and cut power to tens of thousands of utility customers, authorities said.</s>

<s docid="AP891116-0191" num="25" wdcount="12"> Reports of tornado damage came from Kent County, Md., and Hockessin, Del.</s>

<s docid="AP891116-0191" num="26" wdcount="11"> National Weather Service officials were unable to immediately confirm the reports.</s>

<s docid="AP891116-0191" num="27" wdcount="4"> No injuries were reported.</s>

<s docid="AP891116-0191" num="28" wdcount="25"> _Mississippi: Scattered damage and power outages were reported Wednesday after radar showed tornadoes in Neshoba and Kemper counties in the east-central portion of the state.</s>

<s docid="AP891116-0191" num="29" wdcount="4"> No injuries were reported.</s>

<s docid="AP891116-0191" num="30" wdcount="22"> _New Jersey: High winds and tornadoes were blamed for one death, at least four injuries and widespread damage and power outages Thursday.</s>

<s docid="AP891116-0191" num="31" wdcount="18"> A tornado touched down in Piscataway shortly after noon, collapsing on house and damaging 10 to 12 others.</s>

<s docid="AP891116-0191" num="32" wdcount="6"> One person suffered a minor injury.</s>

<s docid="AP891116-0191" num="33" wdcount="27"> A bridge connecting Elizabeth with New York City was closed after two tractor trailers overturned in heavy winds; one truck driver died and a passenger was injured.</s>

<s docid="AP891116-0191" num="34" wdcount="8"> Two minor injuries were reported in Bergen County.</s>

<s docid="AP891116-0191" num="35" wdcount="35"> _New York: A severe thunderstorm Thursday sent a tree crashing through an elementary school roof in Newburgh, about 60 miles north of New York City, killing at least seven children and injuring 18, authorities said.</s>

<s docid="AP891116-0191" num="36" wdcount="22"> In New York City, a woman was killed by a 12-foot steel beam that apparently had blown off her apartment's water tower.</s>

<s docid="AP891116-0191" num="37" wdcount="10"> Tornadoes were reported in Peekskill, just north of the city.</s>

<s docid="AP891116-0191" num="38" wdcount="18"> _North Carolina: A pair of tornadoes were reported Wednesday in Henderson County, where a vacant house was destroyed.</s>

<s docid="AP891116-0191" num="39" wdcount="4"> No injuries were reported.</s>

<s docid="AP891116-0191" num="40" wdcount="29"> _Ohio: High winds described by local authorities as a tornado hopscotched across north-central Ohio on Wednesday, ripping roofs off barns and houses, destroying farm sheds and damaging trailer homes.</s>

<s docid="AP891116-0191" num="41" wdcount="17"> One man was hospitalized from a lightning strike and a woman was slightly injured by flying debris.</s>

<s docid="AP891116-0191" num="42" wdcount="22"> _Pennsylvania: High winds and funnel clouds ripped off roofs and downed trees in eastern Pennslyvania on Thursday, shattering windows in Philadelphia skyscrapers.</s>

<s docid="AP891116-0191" num="43" wdcount="15"> No serious injuries were reported, but at least 75,000 customers in southeastern Pennsylvania lost power.</s>

<s docid="AP891116-0191" num="44" wdcount="14"> _South Carolina: A tornado Wednesday downed power lines and damaged 20 houses near Greenwood.</s>

<s docid="AP891116-0191" num="45" wdcount="4"> No injuries were reported.</s>

<s docid="AP891116-0191" num="46" wdcount="33"> _West Virginia: High winds knocked over trees, ripped roofs off houses and toppled a trailer early Thursday in Jefferson County, just west of Frederick, Md., injuring four members of one family, two seriously.</s>

<s docid="AP891116-0191" num="47" wdcount="12"> The National Weather Service said the storm probably was a tornado .</s>
</TEXT>
</DOC>
