<DOC>
<DOCNO>

<s docid="AP891116-0198" num="1" wdcount="1"> AP891116-0198</s>
</DOCNO>
<FILEID>

<s docid="AP891116-0198" num="2" wdcount="2"> AP-NR-11-16-89 2218EST</s>
</FILEID>
<FIRST>

<s docid="AP891116-0198" num="3" wdcount="7"> u a AM-SouthernTornadoes 3rdLd-Writethru a0813 11-16 1138</s>
</FIRST>
<SECOND>

<s docid="AP891116-0198" num="4" wdcount="5"> AM-Southern Tornadoes, 3rd Ld-Writethru, a0813,1167</s>
</SECOND>
<HEAD>

<s docid="AP891116-0198" num="5" wdcount="9"> Huntsville Picks Up Pieces One Day After Killer Tornado</s>
</HEAD>
<HEAD>

<s docid="AP891116-0198" num="6" wdcount="22"> Eds: Fixes paragraphing in 1st 2 grafs; SUBS 2nd graf to raise reference to Illinois death; SUBS grafs 10-13, `The cafeteria ...</s>

<s docid="AP891116-0198" num="7" wdcount="33"> Hughes said' with 6 grafs to UPDATE with up to 125 children in school, dead ages 7 to 8, four injured critically, power outages in Connecticut; picks up 14th graf, `Tornadoes were ...'</s>
</HEAD>
<HEAD>

<s docid="AP891116-0198" num="8" wdcount="5"> LaserPhotos HUN1,2,3,5,10,13, MFD1, LaserColor HUN10</s>
</HEAD>
<BYLINE>

<s docid="AP891116-0198" num="9" wdcount="3"> By PAUL NEWBERRY</s>
</BYLINE>
<BYLINE>

<s docid="AP891116-0198" num="10" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<TEXT>

<s docid="AP891116-0198" num="11" wdcount="28"> A violent storm that spun tornadoes across the South and Midwest blew north Thursday, knocking a cafeteria wall down on top of lunching schoolchildren in upstate New York.</s>

<s docid="AP891116-0198" num="12" wdcount="11"> The two-day toll was at least 27 dead and hundreds injured.</s>

<s docid="AP891116-0198" num="13" wdcount="25"> The cafeteria cave-in claimed the lives of seven children near Newburgh, N.Y., and deaths also were reported in New York City, New Jersey and Illinois.</s>

<s docid="AP891116-0198" num="14" wdcount="27"> Seventeen people died Wednesday in Huntsville, Ala., when a tornado packing 250 mph winds struck virtually without warning, laying waste to a wide swath of the city.</s>

<s docid="AP891116-0198" num="15" wdcount="14"> The storm churned around a collision of record warm air and extremely cold air.</s>

<s docid="AP891116-0198" num="16" wdcount="8"> The result was tornadoes and unusually severe thunderstorms.</s>

<s docid="AP891116-0198" num="17" wdcount="24"> By far the worst damage was in Huntsville, where an estimated 1,000 people were left homeless and National Guardsmen stood watch against looting Thursday.</s>

<s docid="AP891116-0198" num="18" wdcount="17"> No bodies were believed left in the rubble, but portions of the city resembled a bombing target.</s>

<s docid="AP891116-0198" num="19" wdcount="10"> A shopping center and clusters of apartment buildings were leveled.</s>

<s docid="AP891116-0198" num="20" wdcount="6"> Cars were piled atop each other.</s>

<s docid="AP891116-0198" num="21" wdcount="7"> Utility poles had been snapped like twigs.</s>

<s docid="AP891116-0198" num="22" wdcount="26"> The National Weather Service said the tornado path had covered between eight and 10 miles and that its wind speeds were as high as 250 mph.</s>

<s docid="AP891116-0198" num="23" wdcount="24"> ``It's like taking six to 10 city blocks and putting them in a blender and putting it on liquefy,'' said rescue worker Bob Caraway.</s>

<s docid="AP891116-0198" num="24" wdcount="29"> As the storm moved north on Thursday, it knocked over trees and ripped the the roofs off houses in West Virginia, injuring four members of one family, two seriously.</s>

<s docid="AP891116-0198" num="25" wdcount="44"> The storm also caused flooding in Washington, D.C., blew the windows out of skyscrapers in Philadelphia and destroyed a house in Piscataway, N.J. A truck driver died when his tractor-trailer overturned in high winds on a bridge connecting Elizabeth, N.J., and New York City.</s>

<s docid="AP891116-0198" num="26" wdcount="18"> A New York City woman died after being hit by a steel beam blown off a water tower.</s>

<s docid="AP891116-0198" num="27" wdcount="26"> In Wyckoff, N.J., high winds knocked a power line onto a gas line, sparking a fire that forced the evacuation of 20 homes, according to police.</s>

<s docid="AP891116-0198" num="28" wdcount="4"> No houses were burned.</s>

<s docid="AP891116-0198" num="29" wdcount="37"> The cafeteria collapse occurred at the East Coldenham Elementary School in Newburgh at about 12:30 p.m., when from 113 to 125 students in first, second and third grades were eating lunch, said Newburgh police Chief John Kulisek.</s>

<s docid="AP891116-0198" num="30" wdcount="31"> State Police and survivors said they believed the school was hit by a tornado, but the National Weather Service said it could not confirm that until investigators went to the scene.</s>

<s docid="AP891116-0198" num="31" wdcount="21"> The center section of a cinder-block and glass wall fell in on the cafeteria, showering the pupils with glass and concrete.</s>

<s docid="AP891116-0198" num="32" wdcount="20"> ``You are talking about huge concrete blocks that fell on top of the kids,'' state police Lt. Robert Hughes said.</s>

<s docid="AP891116-0198" num="33" wdcount="17"> Seven children ages 7 and 8 were killed and 18 others were injured, four critically, officials said.</s>

<s docid="AP891116-0198" num="34" wdcount="26"> In eastern Connecticut, more than 75,000 Northeast Utilities customers lost power in the afternoon, and 18,000 remained without power at 9 p.m., spokeman Jeffery Kotkin said.</s>

<s docid="AP891116-0198" num="35" wdcount="16"> Tornadoes were reported Wednesday in Mississippi, Alabama, Georgia, South Carolina, North Carolina, Kentucky, Ohio and Indiana.</s>

<s docid="AP891116-0198" num="36" wdcount="15"> A severe thunderstorm in Illinois claimed one life and caused several million dollars in damage.</s>

<s docid="AP891116-0198" num="37" wdcount="19"> Altogether, the storms were blamed for at least 27 deaths and more than 500 injuries over the two days.</s>

<s docid="AP891116-0198" num="38" wdcount="28"> In Alabama, Gov. Guy Hunt said he would ask President Bush to declare Huntsville a disaster area to open the door to millions of dollars in federal relief.</s>

<s docid="AP891116-0198" num="39" wdcount="21"> Mayor Steve Hettinger said no firm damage estimates were expected until Friday, but he put the number of homeless at 1,000.</s>

<s docid="AP891116-0198" num="40" wdcount="17"> Hunt assigned nearly 200 Guardsmen to assist in the cleanup and help law officers guard against looting.</s>

<s docid="AP891116-0198" num="41" wdcount="18"> Police spokeswoman Susan Williamson said there had been minor looting the night of the storm but no arrests.</s>

<s docid="AP891116-0198" num="42" wdcount="28"> The temperature, which had risen to 73 before the storm Wednesday, plunged into the 30s early Thursday while rescuers worked through the night under the glare of floodlights.</s>

<s docid="AP891116-0198" num="43" wdcount="18"> The lights, powered by generators, produced an eerie glow in a area that was otherwise largely without power.</s>

<s docid="AP891116-0198" num="44" wdcount="15"> Tall cranes lifted the heavy rubble, while workers with flashlights picked through the smaller pieces.</s>

<s docid="AP891116-0198" num="45" wdcount="24"> As daybreak came, people began returning to the scene, some to look for valuables in ravaged cars or businesses, others simply out of curiosity.</s>

<s docid="AP891116-0198" num="46" wdcount="6"> Many carried cameras or videocassette recorders.</s>

<s docid="AP891116-0198" num="47" wdcount="2"> Police Maj.</s>

<s docid="AP891116-0198" num="48" wdcount="14"> Robert Moder said there was no indication that anyone was left in the rubble.</s>

<s docid="AP891116-0198" num="49" wdcount="12"> ``We don't have any reports of people missing,'' he said Thursday morning.</s>

<s docid="AP891116-0198" num="50" wdcount="18"> Moder said 463 people were injured and more than 150 of those required at least overnight hospital treatment.</s>

<s docid="AP891116-0198" num="51" wdcount="15"> Authorities had said 19 people were killed but later lowered the death toll by two.</s>

<s docid="AP891116-0198" num="52" wdcount="35"> All but one of the victims, who ranged in age from 7 to 67, were killed along Airport Boulevard, a busy thoroughfare that seemed to be a guide for the tornado on its deadly march.</s>

<s docid="AP891116-0198" num="53" wdcount="10"> The other victim perished on the city's outskirts, authorities said.</s>

<s docid="AP891116-0198" num="54" wdcount="22"> Most of the dead were in apartments and stores that were torn into twisted wreckage, or in cars blown off the pavement.</s>

<s docid="AP891116-0198" num="55" wdcount="8"> The tornado seemed to catch everyone by surprise.</s>

<s docid="AP891116-0198" num="56" wdcount="21"> ``It was fast,'' said Lucy Lee Rusk, who moved to a Red Cross shelter after her apartment was battered by debris.</s>

<s docid="AP891116-0198" num="57" wdcount="11"> ``It was like one big pop and that's when everything went''.</s>

<s docid="AP891116-0198" num="58" wdcount="28"> The National Weather Service had issued a severe thunderstorm warning at 3:54 p.m., but the tornado struck with no real warning, said Brenda Page of the service's office.</s>

<s docid="AP891116-0198" num="59" wdcount="23"> A tornado warning was broadcast at 4:39 p.m., two minutes after the twister was sighted on the ground at the old Huntsville airport.</s>

<s docid="AP891116-0198" num="60" wdcount="16"> Ms. Page said radar showed a strong storm but not the conditions usually visible during tornadoes.</s>

<s docid="AP891116-0198" num="61" wdcount="29"> Danny Cooper, director of the Alabama Emergency Management Agency, said three people were seriously injured in an earlier tornado that hit a home in Clay County in eastern Alabama.</s>

<s docid="AP891116-0198" num="62" wdcount="12"> He said a tornado in northwestern Alabama's Lauderdale County destroyed three homes.</s>

<s docid="AP891116-0198" num="63" wdcount="32"> Alabama Power Co. reported Thursday that violent winds had battered the switchyard of the Farley Nuclear Power Plant near Dothan on Wednesday night, causing about three gallons of concentrated PCBs to spill.</s>

<s docid="AP891116-0198" num="64" wdcount="24"> A spokesman said no one was injured, the nuclear plant was not affected and a cleanup of the cancer-causing chemicals was under way .</s>
</TEXT>
</DOC>
