<DOC>
<DOCNO>

<s docid="AP891116-0035" num="1" wdcount="1"> AP891116-0035</s>
</DOCNO>
<FILEID>

<s docid="AP891116-0035" num="2" wdcount="2"> AP-NR-11-16-89 0234EST</s>
</FILEID>
<FIRST>

<s docid="AP891116-0035" num="3" wdcount="7"> u a AM-AlabamaTornado 7thLd-Writethru a0444-a0439 11-16 0834</s>
</FIRST>
<SECOND>

<s docid="AP891116-0035" num="4" wdcount="7"> AM-Alabama Tornado, 7th Ld - Writethru, a0444-a0439,0856</s>
</SECOND>
<HEAD>

<s docid="AP891116-0035" num="5" wdcount="1"> URGENT</s>
</HEAD>
<HEAD>

<s docid="AP891116-0035" num="6" wdcount="6"> Deadly Twister Smashes Huntsville, Ala .</s>
</HEAD>
<HEAD>

<s docid="AP891116-0035" num="7" wdcount="16"> Eds: LEADS with 3 grafs to UPDATE with 15th fatality; picks up 4th graf pvs .</s>
</HEAD>
<HEAD>

<s docid="AP891116-0035" num="8" wdcount="4"> LaserPhotos ATN1, HUN1,2,3; LaserGraphic</s>
</HEAD>
<BYLINE>

<s docid="AP891116-0035" num="9" wdcount="3"> By HOYT HARWELL</s>
</BYLINE>
<BYLINE>

<s docid="AP891116-0035" num="10" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP891116-0035" num="11" wdcount="3"> HUNTSVILLE, Ala. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP891116-0035" num="12" wdcount="32"> A tornado slammed into a shopping district, a residential area and a school Wednesday, killing at least 15 people, injuring more than 300 and trapping people in cars and homes, authorities said.</s>

<s docid="AP891116-0035" num="13" wdcount="7"> ``It's total destruction where the tornado hit.</s>

<s docid="AP891116-0035" num="14" wdcount="26"> Cars are piled on top of each other under piles of rubble where buildings used to be,'' said Danny Cooper, state emergency management director in Montgomery.</s>

<s docid="AP891116-0035" num="15" wdcount="22"> Emergency officials in Huntsville reported 15 confirmed deaths, said Henry Jurnigan, a duty officer with the state Emergency Management Agency in Montgomery.</s>

<s docid="AP891116-0035" num="16" wdcount="28"> Mayor Steve Hettinger said 305 people were injured and about 500 displaced by the tornado that struck while streets of this northeastern Alabama city filled with rush-hour traffic.</s>

<s docid="AP891116-0035" num="17" wdcount="16"> Rescue teams with cranes and floodlights searched the rubble through the night for injured or dead.</s>

<s docid="AP891116-0035" num="18" wdcount="33"> ``Several people are still trapped in vehicles and apartment complexes and shopping areas,'' said police spokesman Ben Jennings after the twister touched down between 4 and 4:30 p.m. in the city's south section.</s>

<s docid="AP891116-0035" num="19" wdcount="21"> ``It may be tomorrow before we have a final count,'' Gov. Guy Hunt said at the state's disaster center in Montgomery.</s>

<s docid="AP891116-0035" num="20" wdcount="12"> The governor dispatched 50 National Guardsmen, along with search and rescue equipment.</s>

<s docid="AP891116-0035" num="21" wdcount="25"> Rescuers picked through piles of rubble 10 to 14 feet deep, and Cooper said police were unable to determine the extent of the damaged area.</s>

<s docid="AP891116-0035" num="22" wdcount="9"> Rescuers also were hampered by darkness and plunging temperatures.</s>

<s docid="AP891116-0035" num="23" wdcount="8"> ``We're even having a few snowflakes,'' said Cooper.</s>

<s docid="AP891116-0035" num="24" wdcount="14"> High temperatures in Huntsville were expected to be in the 30s Thursday, he said.</s>

<s docid="AP891116-0035" num="25" wdcount="23"> Witnesses said the downtown Jones Valley Elementary School, the Waterford Square and adjacent Queensbury apartment complexes were reduced to rubble by the tornado.</s>

<s docid="AP891116-0035" num="26" wdcount="28"> ``The only thing left standing was a door frame,'' news photographer Mike Mercier said of the school, which was empty of staff and pupils when the tornado hit.</s>

<s docid="AP891116-0035" num="27" wdcount="11"> Police reported one person killed in a car outside the school.</s>

<s docid="AP891116-0035" num="28" wdcount="32"> Authorities said at least five were killed at Waterford Square apartments, three at a business school, Southern Junior College, which is located in a converted movie theater, and others in scattered areas.</s>

<s docid="AP891116-0035" num="29" wdcount="11"> ``Rescuers are digging in the rubble,'' state trooper W.L. Kelly said.</s>

<s docid="AP891116-0035" num="30" wdcount="18"> He said two people were killed when the twister hit house trailers in rural areas east of Huntsville.</s>

<s docid="AP891116-0035" num="31" wdcount="9"> The fifth death was reported near the shopping district.</s>

<s docid="AP891116-0035" num="32" wdcount="28"> The city is home to Marshall Space Flight Center and the Army's Redstone Arsenal, but no serious damage was reported from the space agency or weapons testing center.</s>

<s docid="AP891116-0035" num="33" wdcount="12"> ``We've called in troopers from around the state to help,'' Kelly said.</s>

<s docid="AP891116-0035" num="34" wdcount="19"> Telephone communication and electricity were disrupted by the tornadoes and WAAY-TV, the only station still broadcasting, reported widespread damage.</s>

<s docid="AP891116-0035" num="35" wdcount="41"> ``It came in with a huge roar, an enormous amount of water, and it just started shaking and tearing at everything it could get hold of,'' said real estate broker Ike Carroll, who was in his car when the twister struck.</s>

<s docid="AP891116-0035" num="36" wdcount="10"> ``It started picking cars up and pushing them around, ...</s>

<s docid="AP891116-0035" num="37" wdcount="13"> some of them upside down, some of them just strewn around,'' he said.</s>

<s docid="AP891116-0035" num="38" wdcount="17"> Heavy overhead power lines ``started snapping just like a circus performer would snap his whip,'' Carroll said.</s>

<s docid="AP891116-0035" num="39" wdcount="19"> ``All of these heavy arcing, flashing lines that were just popping and snapping over the top of us ...</s>

<s docid="AP891116-0035" num="40" wdcount="16"> it was as if you were looking into an arc-welder, they were so bright,'' he said.</s>

<s docid="AP891116-0035" num="41" wdcount="22"> WAAY reported at least one person died when the roof of a business collapsed from winds that overturned cars in the area.</s>

<s docid="AP891116-0035" num="42" wdcount="7"> A nearby shopping center also was damaged.</s>

<s docid="AP891116-0035" num="43" wdcount="17"> Humana Hospital administrator David Miller said doctors were having difficulty reaching the hospital because of blocked roads.</s>

<s docid="AP891116-0035" num="44" wdcount="26"> The National Weather Service earlier said a tornado hit the east Alabama hamlet of Mellow Valley, severely damaging at least one home and causing some injuries.</s>

<s docid="AP891116-0035" num="45" wdcount="10"> Weather officials said people were trapped inside a collapsed house.</s>

<s docid="AP891116-0035" num="46" wdcount="24"> A spokeswoman for the Clay County Sheriff's Department said people were injured at one house in a rural area 30 miles east of Sylacauga.</s>

<s docid="AP891116-0035" num="47" wdcount="29"> Another tornado touched down about 1:30 p.m. as severe weather swept across much of Alabama and the National Weather Service placed most of the state under a tornado watch.</s>

<s docid="AP891116-0035" num="48" wdcount="22"> A third tornado was reported shortly before 3:30 p.m. crossing the Coosa River near Titus in east Alabama, the Weather Service said.</s>

<s docid="AP891116-0035" num="49" wdcount="36"> In Georgia, five people were injured, four critically, and at least 200 people evacuated after a tornado struck two mobile home parks and an interstate highway near Palmetto, about 25 miles southeast of Atlanta, authorities said.</s>

<s docid="AP891116-0035" num="50" wdcount="22"> Authorities in southwestern North Carolina said a pair of storm-spawned tornadoes struck around 10:45 p.m., destroying a vacant house in Henderson County.</s>

<s docid="AP891116-0035" num="51" wdcount="16"> The National Weather Service also reported tornadoes inflicting minor property damage in Kentucky and Mississippi .</s>
</TEXT>
</DOC>
