<DOC>
<DOCNO>

<s docid="LA111689-0160" num="1" wdcount="1"> LA111689-0160</s>
</DOCNO>
<DOCID>

<s docid="LA111689-0160" num="2" wdcount="1"> 135664</s>
</DOCID>
<DATE>
<P>

<s docid="LA111689-0160" num="3" wdcount="6"> November 16, 1989, Thursday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA111689-0160" num="4" wdcount="8"> Part A; Page 20; Column 1; National Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA111689-0160" num="5" wdcount="2"> 631 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA111689-0160" num="6" wdcount="8"> ALABAMA TORNADO KILLS 14; 300 INJURED; OTHERS TRAPPED</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA111689-0160" num="7" wdcount="3"> From Associated Press</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA111689-0160" num="8" wdcount="3"> HUNTSVILLE, Ala .</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA111689-0160" num="9" wdcount="34"> A tornado slammed into a shopping district, a residential area and a school Wednesday, killing at least 14 people, injuring nearly 300 and trapping many others in their cars and homes, police said .</s>
</P>
<P>

<s docid="LA111689-0160" num="10" wdcount="34"> "Several people are still trapped in vehicles and apartment complexes and shopping areas," said police spokesman Ben Jennings after the twister touched down between 4 and 4:30 p.m. in this northeastern Alabama city .</s>
</P>
<P>

<s docid="LA111689-0160" num="11" wdcount="31"> Mayor Steve Hettinger said 14 deaths had been confirmed, with 285 people injured and about 500 displaced by the tornado that struck while city streets were filled with rush-hour traffic .</s>
</P>
<P>

<s docid="LA111689-0160" num="12" wdcount="28"> Gov. Guy Hunt, at the state's disaster center in Montgomery, said rescue teams with cranes and floodlights would search the rubble through the night for injured or dead.</s>

<s docid="LA111689-0160" num="13" wdcount="13"> "It may be tomorrow before we have a final count," he said .</s>
</P>
<P>

<s docid="LA111689-0160" num="14" wdcount="19"> The governor said 50 National Guard troops were dispatched to the city, along with search and rescue equipment .</s>
</P>
<P>

<s docid="LA111689-0160" num="15" wdcount="24"> Witnesses said the downtown Jones Valley Elementary School, the Waterford Square and adjacent Queensbury apartment complexes were reduced to rubble by the tornado .</s>
</P>
<P>

<s docid="LA111689-0160" num="16" wdcount="28"> "The only thing left standing was a door frame," news photographer Mike Mercier said of the school, which was empty of staff and pupils when the tornado hit.</s>

<s docid="LA111689-0160" num="17" wdcount="12"> Police reported one person killed in a car outside the school .</s>
</P>
<P>

<s docid="LA111689-0160" num="18" wdcount="33"> Authorities said at least five were killed at Waterford Square apartments, three at a business school, Southern Junior College, which is located in a converted movie theater, and others in scattered areas .</s>
</P>
<P>

<s docid="LA111689-0160" num="19" wdcount="9"> "Rescuers are digging in the rubble," state trooper W.</s>

<s docid="LA111689-0160" num="20" wdcount="3"> L. Kelly said.</s>

<s docid="LA111689-0160" num="21" wdcount="18"> He said two people were killed when the twister hit house trailers in rural areas east of Huntsville.</s>

<s docid="LA111689-0160" num="22" wdcount="10"> The fifth death was reported near the shopping district .</s>
</P>
<P>

<s docid="LA111689-0160" num="23" wdcount="13"> "We've called in troopers from around the state to help," Kelly said .</s>
</P>
<P>

<s docid="LA111689-0160" num="24" wdcount="29"> The city is home to Marshall Space Flight Center and the Army's Redstone Arsenal, but no serious damage was reported from the space agency or weapons testing center .</s>
</P>
<P>

<s docid="LA111689-0160" num="25" wdcount="20"> Telephone communication and electricity were disrupted by the tornadoes and WAAY-TV, the only station still broadcasting, reported widespread damage .</s>
</P>
<P>

<s docid="LA111689-0160" num="26" wdcount="42"> "It came in with a huge roar, an enormous amount of water, and it just started shaking and tearing at everything it could get hold of," said real estate broker Ike Carroll, who was in his car when the twister struck .</s>
</P>
<P>

<s docid="LA111689-0160" num="27" wdcount="26"> "It started picking cars up and pushing them around . . . some of them upside down, some of them just strewn around," he said .</s>
</P>
<P>

<s docid="LA111689-0160" num="28" wdcount="18"> Heavy overhead power lines "started snapping just like a circus performer would snap his whip," Carroll said .</s>
</P>
<P>

<s docid="LA111689-0160" num="29" wdcount="38"> "All of these heavy arcing, flashing lines that were just popping and snapping over the top of us . . . it was as if you were looking into an arc-welder, they were so bright," he said .</s>
</P>
<P>

<s docid="LA111689-0160" num="30" wdcount="22"> WAAY reported at least one person died when the roof of a business collapsed from winds that overturned cars in the area.</s>

<s docid="LA111689-0160" num="31" wdcount="8"> A nearby shopping center also was damaged .</s>
</P>
<P>

<s docid="LA111689-0160" num="32" wdcount="18"> Humana Hospital administrator David Miller said doctors were having difficulty reaching the hospital because of blocked roads .</s>
</P>
<P>

<s docid="LA111689-0160" num="33" wdcount="26"> The National Weather Service earlier said a tornado hit the east Alabama hamlet of Mellow Valley, severely damaging at least one home and causing some injuries.</s>

<s docid="LA111689-0160" num="34" wdcount="11"> Weather officials said people were trapped inside a collapsed house .</s>
</P>
<P>

<s docid="LA111689-0160" num="35" wdcount="25"> A spokeswoman for the Clay County Sheriff's Department said people were injured at one house in a rural area 30 miles east of Sylacauga .</s>
</P>
<P>

<s docid="LA111689-0160" num="36" wdcount="30"> Another tornado touched down about 1:30 p.m. as severe weather swept across much of Alabama and the National Weather Service placed most of the state under a tornado watch .</s>
</P>
<P>

<s docid="LA111689-0160" num="37" wdcount="23"> In Georgia, five people were injured, four critically, after a tornado struck two mobile home parks and an interstate highway near Palmetto .</s>
</P>
</TEXT>
<TYPE>
<P>

<s docid="LA111689-0160" num="38" wdcount="1"> Wire</s>
</P>
</TYPE>
<SUBJECT>
<P>

<s docid="LA111689-0160" num="39" wdcount="10"> TORNADOES; STORMS -- ALABAMA; CASUALTIES; DISASTERS -- ALABAMA; DISASTER VICTIMS</s>
</P>
</SUBJECT>
</DOC>
