<DOC>
<DOCNO>

<s docid="AP880818-0023" num="1" wdcount="1"> AP880818-0023</s>
</DOCNO>
<FILEID>

<s docid="AP880818-0023" num="2" wdcount="2"> AP-NR-08-18-88 0355EDT</s>
</FILEID>
<FIRST>

<s docid="AP880818-0023" num="3" wdcount="5"> r p PM-CVN--QuayletheLegend 08-18 0452</s>
</FIRST>
<SECOND>

<s docid="AP880818-0023" num="4" wdcount="3"> PM-CVN--Quayle the Legend,440</s>
</SECOND>
<HEAD>

<s docid="AP880818-0023" num="5" wdcount="8"> Republicans Quickly Elevate Quayle Into The American Pantheon</s>
</HEAD>
<BYLINE>

<s docid="AP880818-0023" num="6" wdcount="4"> By HARRY F. ROSENTHAL</s>
</BYLINE>
<BYLINE>

<s docid="AP880818-0023" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880818-0023" num="8" wdcount="3"> NEW ORLEANS (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880818-0023" num="9" wdcount="23"> Dan Quayle has not yet been nominated for vice president and already Republicans are comparing him to Thomas Jefferson and John F. Kennedy.</s>

<s docid="AP880818-0023" num="10" wdcount="32"> Sen. John Warner of Virginia, who served with Quayle on a Senate subcommittee, told an audience that whenever he heard the Indiana senator speak, ``I'd say, `there stands the next Thomas Jefferson'''.</s>

<s docid="AP880818-0023" num="11" wdcount="20"> And, added Warner, ``he does have the same fire in his belly as our great forefather Thomas Jefferson of Virginia''.</s>

<s docid="AP880818-0023" num="12" wdcount="11"> Former president Gerald Ford made the comparison with Kennedy, a Democrat.</s>

<s docid="AP880818-0023" num="13" wdcount="24"> ``In 1960, the American people voted for John F. Kennedy for president and he was the relatively same age as Dan Quayle,'' said Ford.</s>

<s docid="AP880818-0023" num="14" wdcount="22"> ``John Kennedy had been in the House and Senate 14 years before he was elected president and Dan Quayle's had 12 years''.</s>

<s docid="AP880818-0023" num="15" wdcount="8"> What Quayle thinks of those references isn't known.</s>

<s docid="AP880818-0023" num="16" wdcount="15"> But he doesn't like it when people say he looks like movie idol Robert Redford.</s>

<s docid="AP880818-0023" num="17" wdcount="15"> Whether, indeed, he looks like Redford seems to be in the eye of the beholder.</s>

<s docid="AP880818-0023" num="18" wdcount="8"> In the parlance of politics, it's an issue.</s>

<s docid="AP880818-0023" num="19" wdcount="4"> They are both male.</s>

<s docid="AP880818-0023" num="20" wdcount="4"> They are both blond.</s>

<s docid="AP880818-0023" num="21" wdcount="17"> The so-called resemblance became a point of contention in the 1980 Senate race and Redford took umbrage.</s>

<s docid="AP880818-0023" num="22" wdcount="31"> The actor, who once played the role of a presidential office seeker in ``The Candidate'' sent Quayle a telegram telling him to stop the look-alike references in his congressional campaign literature.</s>

<s docid="AP880818-0023" num="23" wdcount="23"> Quayle said the news media had made the comparison, not he, and after he was elected sent Redford an autographed picture of himself.</s>

<s docid="AP880818-0023" num="24" wdcount="14"> And this week, he told reporters he considered the so-called Redford look ``a stigma''.</s>

<s docid="AP880818-0023" num="25" wdcount="14"> He wasn't asked how he felt about being painted as another Jefferson or Kennedy.</s>

<s docid="AP880818-0023" num="26" wdcount="19"> Meanwhile, fellow senators were trying to publicize Quayle who, at 41, hasn't had a chance to become a legend.</s>

<s docid="AP880818-0023" num="27" wdcount="20"> He is a Republican vice presidential candidate who is not, as Spiro Agnew once said of himself, a household word.</s>

<s docid="AP880818-0023" num="28" wdcount="18"> To help him get known, eight fellow senators Wednesday took turns telling reporters how much they liked him.</s>

<s docid="AP880818-0023" num="29" wdcount="8"> ``We know him well,'' said Strom Thurmond, R-S.C.</s>

<s docid="AP880818-0023" num="30" wdcount="17"> ``He's attractive because of his looks, he's attractive because of his enthusiasm,'' said Sen. John McCain, R-Ariz.</s>

<s docid="AP880818-0023" num="31" wdcount="34"> ``I think Dan Quayle, although he's 41 years of age, he's going to send a message to the American people that the Republican Party respects young people who achieve,'' said Sen. Pete Domenici, R-N.M.</s>

<s docid="AP880818-0023" num="32" wdcount="15"> Oh, yes, he's also rich, but the senators said that should not hold him back.</s>

<s docid="AP880818-0023" num="33" wdcount="13"> ``Let's not start this business of who's wealthy,'' Sen. Alfonse D'Amato, R-N.Y .</s>
</TEXT>
</DOC>
