<DOC>
<DOCNO>

<s docid="AP880826-0226" num="1" wdcount="1"> AP880826-0226</s>
</DOCNO>
<FILEID>

<s docid="AP880826-0226" num="2" wdcount="2"> AP-NR-08-26-88 2049EDT</s>
</FILEID>
<FIRST>

<s docid="AP880826-0226" num="3" wdcount="7"> u p AM-Quayle-Resume 2ndLd-Writethru a0678 08-26 0586</s>
</FIRST>
<SECOND>

<s docid="AP880826-0226" num="4" wdcount="4"> AM-Quayle-Resume, 2nd Ld-Writethru, a0678,560</s>
</SECOND>
<HEAD>

<s docid="AP880826-0226" num="5" wdcount="8"> Quayle's Biography Inflates State Job; Quayle Concedes Error</s>
</HEAD>
<NOTE>

<s docid="AP880826-0226" num="6" wdcount="22"> Eds: INSERTS 1 graf after 14th graf pvs, bgng: ``Theodore Sendak ''... to UPDATE with statement from former assistant attorney general .</s>
</NOTE>
<BYLINE>

<s docid="AP880826-0226" num="7" wdcount="3"> By ROBERT DVORCHAK</s>
</BYLINE>
<BYLINE>

<s docid="AP880826-0226" num="8" wdcount="3"> AP National Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880826-0226" num="9" wdcount="2"> INDIANAPOLIS (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880826-0226" num="10" wdcount="28"> Republican vice presidential candidate Dan Quayle's official resume says he was the Indiana Consumer Protection Division's chief investigator a year before the unit was created, state records show.</s>

<s docid="AP880826-0226" num="11" wdcount="14"> The law creating the unit passed April 14, 1971, and took effect July 1.</s>

<s docid="AP880826-0226" num="12" wdcount="18"> Officials said Quayle served as chief investigator from July until mid-September, when he became administrative assistant to then-Gov.</s>

<s docid="AP880826-0226" num="13" wdcount="3"> Edgar D. Whitcomb.</s>

<s docid="AP880826-0226" num="14" wdcount="29"> Quayle's Senate biography, which his campaign is using as his official background, says he was chief investigator of the unit in the Attorney General's office from 1970 to 1971.</s>

<s docid="AP880826-0226" num="15" wdcount="24"> ``He was assigned to our section in the spring of 1971,'' said Robert Smith, the unit's first director and now an attorney in Indianapolis.</s>

<s docid="AP880826-0226" num="16" wdcount="7"> ``He was in fact the chief investigator.</s>

<s docid="AP880826-0226" num="17" wdcount="7"> He helped get the unit set up.</s>

<s docid="AP880826-0226" num="18" wdcount="15"> (But) it would not have been before 1971,'' Smith said Friday in a telephone interview.</s>

<s docid="AP880826-0226" num="19" wdcount="6"> ``We formally began operations July 1''.</s>

<s docid="AP880826-0226" num="20" wdcount="17"> Quayle conceded Friday that the resume entry was ``inaccurate'' and said his staff had written the document.</s>

<s docid="AP880826-0226" num="21" wdcount="7"> ``If it indicated that, that is inaccurate.</s>

<s docid="AP880826-0226" num="22" wdcount="15"> I didn't hold that job for two years,'' Quayle told reporters aboard his campaign plane.</s>

<s docid="AP880826-0226" num="23" wdcount="21"> Earlier, however, Quayle spokesman David Prosperi called the revelation of the error by The Plain Dealer of Cleveland ``a cheap shot''.</s>

<s docid="AP880826-0226" num="24" wdcount="32"> Quayle was hired as an entry-level research assistant by the state Attorney General's office in 1970 after he returned from six months of basic and advanced training for the Indiana National Guard.</s>

<s docid="AP880826-0226" num="25" wdcount="16"> Quayle, a 1969 graduate of DePauw University, was attending Indiana University Law School at the time.</s>

<s docid="AP880826-0226" num="26" wdcount="18"> M. Stanton Evans, then an editor with the Indianapolis News, helped arrange his job interview with the state.</s>

<s docid="AP880826-0226" num="27" wdcount="13"> Evans worked for Eugene C. Pulliam, Quayle's grandfather and publisher of the News.</s>

<s docid="AP880826-0226" num="28" wdcount="28"> ``At no point in any of this did Dan Quayle ask any favors or use any influence,'' said Evans, now with the National Journalism Center in Washington, D.C.</s>

<s docid="AP880826-0226" num="29" wdcount="9"> ``He wouldn't have been hired as a chief investigator.</s>

<s docid="AP880826-0226" num="30" wdcount="19"> He was hired in an entry-level job and was promoted to a whole bunch of jobs on his merits.</s>

<s docid="AP880826-0226" num="31" wdcount="6"> It's a nothing story,'' Evans said.</s>

<s docid="AP880826-0226" num="32" wdcount="22"> Theodore Sendak, the Attorney General at the time, recently had surgery and is unable to comment, according to his son, Timothy Sendak.</s>

<s docid="AP880826-0226" num="33" wdcount="34"> Patricia Gifford, a Marion Superior Court judge who was then an assistant attorney general, said Friday that prior to the establishment of the Consumer Protection Division, ``all complaints and inquiries were handled by me.</s>

<s docid="AP880826-0226" num="34" wdcount="15"> The legal assistant assigned to me and utilized as my chief investigator was Dan Quayle''.</s>

<s docid="AP880826-0226" num="35" wdcount="8"> Her statement was released by the Quayle campaign.</s>

<s docid="AP880826-0226" num="36" wdcount="26"> The Consumer Protection Division was created by the state legislature to resolve complaints over defective products, false claims in ads, faulty speedometer readings and mail-order fraud.</s>

<s docid="AP880826-0226" num="37" wdcount="26"> In 1980, Quayle referred to himself as a ``Vietnam-era veteran'' in campaign literature when he was running against three-term incumbent Birch Bayh in a Senate race.</s>

<s docid="AP880826-0226" num="38" wdcount="18"> Quayle, who enlisted in the Indiana National Guard, dropped the reference after objections by some Vietnam combat veterans.</s>

<s docid="AP880826-0226" num="39" wdcount="23"> In that same election, which he won, Quayle said he was ``on active duty for several periods during his tenure'' in the Guard.</s>

<s docid="AP880826-0226" num="40" wdcount="19"> The statement referred to periods when Quayle was in basic training and 15 days of camp each summer .</s>
</TEXT>
</DOC>
