<DOC>
<DOCNO>

<s docid="AP880819-0023" num="1" wdcount="1"> AP880819-0023</s>
</DOCNO>
<FILEID>

<s docid="AP880819-0023" num="2" wdcount="2"> AP-NR-08-19-88 0247EDT</s>
</FILEID>
<FIRST>

<s docid="AP880819-0023" num="3" wdcount="6"> r p PM-CVN--Quayle Bjt 08-19 0588</s>
</FIRST>
<SECOND>

<s docid="AP880819-0023" num="4" wdcount="2"> PM-CVN--Quayle, Bjt,560</s>
</SECOND>
<HEAD>

<s docid="AP880819-0023" num="5" wdcount="4"> Quayle's Triumph Quickly Tarnished</s>
</HEAD>
<BYLINE>

<s docid="AP880819-0023" num="6" wdcount="3"> By EILEEN PUTMAN</s>
</BYLINE>
<BYLINE>

<s docid="AP880819-0023" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880819-0023" num="8" wdcount="3"> NEW ORLEANS (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880819-0023" num="9" wdcount="22"> Dan Quayle's vice presidential nomination was supposed to be a triumph for the precocious young Indiana senator, but the dream faded overnight.</s>

<s docid="AP880819-0023" num="10" wdcount="46"> Bush's surprise choice for his running mate was supposed to ignite a campaign that has seemed at times to suffer from lack of inspiration, but he quickly encountered questions over his military record and suggestions he could best serve the Republicans by withdrawing from the ticket.</s>

<s docid="AP880819-0023" num="11" wdcount="33"> Though he found himself in danger of fizzling Thursday, Quayle managed to stir the convention hall with his upbeat speech about family, generations and the rosy future he foresaw under a Bush administration.</s>

<s docid="AP880819-0023" num="12" wdcount="13"> ``Let's go on to victory''! Quayle exhorted, as the crowd erupted in cheers.</s>

<s docid="AP880819-0023" num="13" wdcount="29"> The 41-year-old nominee delivered the speech with calm self-assurance, sticking close to his text and avoiding his penchant for extemporaneous remarks _ perhaps another result of the unanticipated controversy.</s>

<s docid="AP880819-0023" num="14" wdcount="20"> Bush, who followed his running mate to the podium, said he was ``proud to have Dan Quayle at my side''.</s>

<s docid="AP880819-0023" num="15" wdcount="20"> The two will stress the unity of their ticket as they campaign together this weekend through Indiana, Ohio and Illinois.</s>

<s docid="AP880819-0023" num="16" wdcount="18"> But beyond the optimistic words was an unsettling undercurrent that threatened Quayle's candidacy just as it was launched.</s>

<s docid="AP880819-0023" num="17" wdcount="2"> Retired Maj.</s>

<s docid="AP880819-0023" num="18" wdcount="46"> Gen. Wendell C. Phillippi _ who worked for Quayle's grandfather, Eugene C. Pulliam, as managing editor of The Indianapolis News _ said he contacted the National Guard on behalf of Quayle when the young man applied in 1969 and ``recommended him very highly,'' the News reported.</s>

<s docid="AP880819-0023" num="19" wdcount="18"> Quayle, a hardliner on defense matters, has said he sought guard duty so he could attend law school.</s>

<s docid="AP880819-0023" num="20" wdcount="38"> A Bush aide said the matter was discussed with the Indiana senator during the process that led to his selection for the Bush ticket, and Quayle had denied that he used influence to gain admittance to the Guard.</s>

<s docid="AP880819-0023" num="21" wdcount="18"> Bush aides said no thought had been given to dropping Quayle from the ticket, as some Republicans suggested.</s>

<s docid="AP880819-0023" num="22" wdcount="20"> Quayle was tense and refused to answer reporters' questions about the topic during a brief walk-through at the convention hall.</s>

<s docid="AP880819-0023" num="23" wdcount="28"> It was a daunting change for the senator, whose youthful vigor, rapid political rise, striking good looks and wealth have been compared to those of John F. Kennedy.</s>

<s docid="AP880819-0023" num="24" wdcount="20"> Quayle alluded to the National Guard issue during his speech, saying he was proud of the six years he served.</s>

<s docid="AP880819-0023" num="25" wdcount="15"> He also addressed his relative anonymity: ``Many this week have asked, `Who is Dan Quayle'?</s>

<s docid="AP880819-0023" num="26" wdcount="11"> The people of Indiana know me and now the nation will''.</s>

<s docid="AP880819-0023" num="27" wdcount="13"> Those who addressed the convention on his behalf also pulled out their ammunition.</s>

<s docid="AP880819-0023" num="28" wdcount="27"> Sen. Bob Dole of Kansas, who placed Quayle's name in nomination, stressed his campaign skills and sought to deflect concerns that he lacked experience for the job.</s>

<s docid="AP880819-0023" num="29" wdcount="10"> ``He's already spent 12 years as a congressman and senator.</s>

<s docid="AP880819-0023" num="30" wdcount="20"> ... That is 12 more years of national experience than Michael Dukakis, and he is running for president,'' Dole said.</s>

<s docid="AP880819-0023" num="31" wdcount="32"> Sen. Alan Simpson of Wyoming, one of those who seconded the nomination, said Quayle would ``bring vim, vigor and vitality'' to the party and would bring ``sparks and voltage to this campaign''.</s>

<s docid="AP880819-0023" num="32" wdcount="15"> Whether Quayle can overcome his difficult start on the national ticket remains to be seen.</s>

<s docid="AP880819-0023" num="33" wdcount="14"> Others, notably Democratic vice presidential nominee Geraldine Ferraro in 1984, found they could not.</s>

<s docid="AP880819-0023" num="34" wdcount="15"> But Quayle, ever upbeat, was determined Thursday night not to be daunted by the prospect.</s>

<s docid="AP880819-0023" num="35" wdcount="8"> ``Miracles do happen,'' he told his party .</s>
</TEXT>
</DOC>
