<DOC>
<DOCNO>

<s docid="AP881114-0006" num="1" wdcount="1"> AP881114-0006</s>
</DOCNO>
<FILEID>

<s docid="AP881114-0006" num="2" wdcount="2"> AP-NR-11-14-88 0127EST</s>
</FILEID>
<FIRST>

<s docid="AP881114-0006" num="3" wdcount="6"> r w PM-QuayleAsVeep Bjt 11-14 0979</s>
</FIRST>
<SECOND>

<s docid="AP881114-0006" num="4" wdcount="4"> PM-Quayle As Veep, Bjt,970</s>
</SECOND>
<HEAD>

<s docid="AP881114-0006" num="5" wdcount="13"> Quayle Likely To Be Odd Man Out In Bush White House, Pundits Say</s>
</HEAD>
<BYLINE>

<s docid="AP881114-0006" num="6" wdcount="3"> By EILEEN PUTMAN</s>
</BYLINE>
<BYLINE>

<s docid="AP881114-0006" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP881114-0006" num="8" wdcount="2"> WASHINGTON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP881114-0006" num="9" wdcount="32"> Dan Quayle is likely to be a ``man on the outside'' in George Bush's White House following a vice presidential candidacy that began in a furor but settled into obscurity, experts say.</s>

<s docid="AP881114-0006" num="10" wdcount="33"> Encumbered by his image as a political novice who needed a bevy of professional handlers to survive early campaign controversies, Quayle enters a Bush administration in which he has few intimates or allies.</s>

<s docid="AP881114-0006" num="11" wdcount="48"> Relegated in the campaign to small towns and safe GOP areas, Quayle as vice president is likely to be given a traditional ceremonial role _ going to political gatherings and state funerals _ rather than the advisory role that Walter Mondale and even Bush had, some scholars feel.</s>

<s docid="AP881114-0006" num="12" wdcount="15"> ``Dan Quayle is going to set the vice presidency back about a decade or more.</s>

<s docid="AP881114-0006" num="13" wdcount="18"> One thing that political scientists have been talking about is just how much the vice presidency has grown.</s>

<s docid="AP881114-0006" num="14" wdcount="35"> ... With Quayle, it's just going to retreat to the old days of politics and funerals,'' said Ryan Barilleaux, a professor of political science at Miami University in Oxford, Ohio, who studies the American presidency.</s>

<s docid="AP881114-0006" num="15" wdcount="10"> Bush rarely mentioned his 41-year-old running mate during the campaign.</s>

<s docid="AP881114-0006" num="16" wdcount="36"> When asked, Bush employed the stock lines that Quayle would ``make an outstanding vice president'' and had been ``tempered by steel'' as he weathered the early furor over his military service, academic record and personal life.</s>

<s docid="AP881114-0006" num="17" wdcount="21"> The president-elect told reporters Quayle would have access to the same papers, information and intelligence that is available to the president.</s>

<s docid="AP881114-0006" num="18" wdcount="14"> But he would go no further in describing what assignments he would give Quayle.</s>

<s docid="AP881114-0006" num="19" wdcount="25"> Quayle says Bush has talked to him about heading a space council, and that he assumes he'll have a role in the administration's anti-drug efforts.</s>

<s docid="AP881114-0006" num="20" wdcount="12"> ``I will be a very close adviser to the president,'' Quayle said.</s>

<s docid="AP881114-0006" num="21" wdcount="8"> But that's not the way everyone sees it.</s>

<s docid="AP881114-0006" num="22" wdcount="30"> Both Bush and Mondale came to their vice presidential campaigns with substantial reputations and were able to place key staffers in important positions in the respective presidential campaigns, Barilleaux notes.</s>

<s docid="AP881114-0006" num="23" wdcount="14"> ``Dan Quayle has contributed nothing in the way of staff to the Bush campaign.</s>

<s docid="AP881114-0006" num="24" wdcount="10"> He doesn't have his own big reputation on Capitol Hill.</s>

<s docid="AP881114-0006" num="25" wdcount="16"> ... Dan Quayle has no friends in a Bush White House except George Bush,'' Barilleaux says.</s>

<s docid="AP881114-0006" num="26" wdcount="27"> ``They're going to give him a lot of window dressing, a space council, drug task force, but he's going to be a man on the outside ...</s>

<s docid="AP881114-0006" num="27" wdcount="17"> not a man who's going to be consulted in a crisis, except on a pro forma basis''.</s>

<s docid="AP881114-0006" num="28" wdcount="33"> But Eddie Mahe Jr., a GOP consultant who worked with the Bush campaign, says Bush is likely to give Quayle a more active role in the administration than he had in the campaign.</s>

<s docid="AP881114-0006" num="29" wdcount="3"> ``Vindication demands that.</s>

<s docid="AP881114-0006" num="30" wdcount="14"> Both of them will want to prove how right the decision was,'' Mahe says.</s>

<s docid="AP881114-0006" num="31" wdcount="28"> Democrats portrayed Quayle during the campaign as a lightweight, a man with little or no legislative accomplishments, untested and unqualified to be a heartbeat away from the presidency.</s>

<s docid="AP881114-0006" num="32" wdcount="12"> Even some members of Quayle's own party were dismayed at Bush's choice.</s>

<s docid="AP881114-0006" num="33" wdcount="34"> Quayle didn't help his case by making a number of celebrated gaffes during the campaign, perhaps the worst being his garbled explanation of the Holocaust and his declaration, ``I didn't live in this century''.</s>

<s docid="AP881114-0006" num="34" wdcount="20"> Norman Ornstein, of the American Enterprise Institute, says Quayle, while ``not the world's leading intellectual,'' is not ``a complete dummy''.</s>

<s docid="AP881114-0006" num="35" wdcount="14"> He was simply thrust into a situation for which he was unprepared, Ornstein says.</s>

<s docid="AP881114-0006" num="36" wdcount="4"> ``I think he's immature.</s>

<s docid="AP881114-0006" num="37" wdcount="5"> He's not stupid,'' Ornstein says.</s>

<s docid="AP881114-0006" num="38" wdcount="35"> But Quayle comes to the White House with ``a very damaging stereotype that's developed about him that's widely believed in the political community and that's believed by a large segment of the electorate,'' Ornstein says.</s>

<s docid="AP881114-0006" num="39" wdcount="10"> ``That's going to give him a good deal to overcome.</s>

<s docid="AP881114-0006" num="40" wdcount="11"> It's going to give him an enormous impetus to prove himself.</s>

<s docid="AP881114-0006" num="41" wdcount="8"> That's going to be difficult, given the office''.</s>

<s docid="AP881114-0006" num="42" wdcount="23"> Both Barilleaux and Stephen Hess of the Brookings Institution see parallels in Quayle's vice presidency and those of Richard Nixon and Spiro Agnew.</s>

<s docid="AP881114-0006" num="43" wdcount="26"> The choice of Nixon was viewed as a move by Dwight Eisenhower to appease the party's right wing, and Agnew was seen as a political nonentity.</s>

<s docid="AP881114-0006" num="44" wdcount="18"> ``The natural response is to use him (Quayle) sparingly, as Nixon did with Agnew in 1968,'' Hess says.</s>

<s docid="AP881114-0006" num="45" wdcount="38"> ``However, Quayle has four years to prove himself, and I think you're going to see stories in two years about how much he's learned, how much he's acted responsibly, how far he's come from the campaign of 1988''.</s>

<s docid="AP881114-0006" num="46" wdcount="8"> Quayle admits the campaign was a learning process.</s>

<s docid="AP881114-0006" num="47" wdcount="19"> After the controversies subsided, Quayle declared his independence from his Bush handlers, saying he would be his own man.</s>

<s docid="AP881114-0006" num="48" wdcount="25"> He became more accessible to the media but continued to adhere to the schedule handed down from Washington and to deliver the party's scripted message.</s>

<s docid="AP881114-0006" num="49" wdcount="7"> Soon, he dropped off the front pages.</s>

<s docid="AP881114-0006" num="50" wdcount="36"> And although he occasionally spoke out in frustration at having little control over his schedule and at ceasing to make national news, he played the role of loyal No. 2 and even trumpeted his new anonymity.</s>

<s docid="AP881114-0006" num="51" wdcount="26"> ``We have arrived as being a traditional vice presidential nominee because we are either on the back pages or either not on the pages at all.</s>

<s docid="AP881114-0006" num="52" wdcount="9"> That's what we're supposed to be,'' he told reporters.</s>

<s docid="AP881114-0006" num="53" wdcount="31"> That willingness to be a team player could serve him well in a Bush White House, Mahe feels, since Bush wants ``a private adviser, whose experience and opinion he respected ...</s>

<s docid="AP881114-0006" num="54" wdcount="6"> (who) has never had another agenda''.</s>

<s docid="AP881114-0006" num="55" wdcount="15"> ``Dan Quayle owes his political life to one man and one man alone,'' Mahe says.</s>

<s docid="AP881114-0006" num="56" wdcount="12"> ``You're never going to see Dan Quayle telling tales out of school.''</s>
</TEXT>
</DOC>
