<DOC>
<DOCNO>

<s docid="AP880817-0040" num="1" wdcount="1"> AP880817-0040</s>
</DOCNO>
<FILEID>

<s docid="AP880817-0040" num="2" wdcount="2"> AP-NR-08-17-88 0409EDT</s>
</FILEID>
<FIRST>

<s docid="AP880817-0040" num="3" wdcount="5"> r p PM-CVN--QuayleFamily 08-17 0577</s>
</FIRST>
<SECOND>

<s docid="AP880817-0040" num="4" wdcount="2"> PM-CVN--Quayle Family,580</s>
</SECOND>
<HEAD>

<s docid="AP880817-0040" num="5" wdcount="6"> Quayle Called A Dedicated Family Man</s>
</HEAD>
<BYLINE>

<s docid="AP880817-0040" num="6" wdcount="3"> By DOUG RICHARDSON</s>
</BYLINE>
<BYLINE>

<s docid="AP880817-0040" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880817-0040" num="8" wdcount="3"> NEW ORLEANS (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880817-0040" num="9" wdcount="24"> Dan Quayle's sister believes the Indiana senator won't let his candidacy for vice president hurt the family life he and his wife, Marilyn, enjoy.</s>

<s docid="AP880817-0040" num="10" wdcount="20"> ``I don't think it will be tough on the family,'' said Martha Saddler, Quayle's sister, who lives in Huntington, Ind.</s>

<s docid="AP880817-0040" num="11" wdcount="22"> ``Since he's been in politics, we all kind of shake our heads at his hectic schedule and wonder how he does it.</s>

<s docid="AP880817-0040" num="12" wdcount="7"> But he does it and loves it''.</s>

<s docid="AP880817-0040" num="13" wdcount="27"> The Quayle family and friends were celebrating Tuesday afternoon after George Bush announced he wants the 41-year-old Indiana senator to be the Republican nominee for vice president.</s>

<s docid="AP880817-0040" num="14" wdcount="24"> Those who have known the Quayles for years said the senator and his wife have remained relatively unchanged by their years in public life.</s>

<s docid="AP880817-0040" num="15" wdcount="28"> Dan and Marilyn Quayle met as law students in Indianapolis, married while they were still in school and remain close to many of their friends from that period.</s>

<s docid="AP880817-0040" num="16" wdcount="32"> ``One of the greatest things about him is the job of being a senator has not changed him a bit,'' said Indianapolis attorney William R. Neale, treasurer of Quayle's 1986 re-election campaign.</s>

<s docid="AP880817-0040" num="17" wdcount="10"> ``He's the same nice guy he was in law school''.</s>

<s docid="AP880817-0040" num="18" wdcount="31"> Neale, who grew up with Marilyn Tucker Quayle in Indianapolis, introduced Dan Quayle to his future wife at a student gathering at the Indiana University law school in the early 1970s.</s>

<s docid="AP880817-0040" num="19" wdcount="31"> Dan Quayle, who grew up in Huntington, graduated from DePauw University, a small liberal arts college in Greencastle, Ind., before going to work in the Indiana attorney general's office in 1970.</s>

<s docid="AP880817-0040" num="20" wdcount="21"> Daniel F. Evans, also a law school classmate of Dan Quayle, said he doesn't expect Quayle's national candidacy to change him.</s>

<s docid="AP880817-0040" num="21" wdcount="23"> ``I think his strength is he'll remember who his friends are even after this,'' said Evans, who was chairman of Quayle's 1986 campaign.</s>

<s docid="AP880817-0040" num="22" wdcount="24"> Friends said the Quayles are devoted to their three children and prefer quiet nights at home to nights out on the town in Washington.</s>

<s docid="AP880817-0040" num="23" wdcount="30"> ``His family looks like the family both parties are trying to appeal to,'' said Mitch Daniels, former political chief in the White House and now president of the Hudson Institute.</s>

<s docid="AP880817-0040" num="24" wdcount="4"> ``It's a beautiful family.</s>

<s docid="AP880817-0040" num="25" wdcount="7"> I think they'll be a real asset''.</s>

<s docid="AP880817-0040" num="26" wdcount="20"> The couple, who married in 1972, have a 14-year-old son, Tucker; a 12-year-old son, Benjamin; and a 9-year-old daughter, Corinne.</s>

<s docid="AP880817-0040" num="27" wdcount="29"> When they campaign in Indiana, the Quayles often tour in two groups _ the boys riding in parades with Marilyn Quayle and Corinne and her father visiting county fairs.</s>

<s docid="AP880817-0040" num="28" wdcount="9"> ``The kids are nonchalant, normal kids,'' said Mrs. Saddler.</s>

<s docid="AP880817-0040" num="29" wdcount="7"> ``They take it in stride and play''.</s>

<s docid="AP880817-0040" num="30" wdcount="28"> In an interview with Indiana reporters Monday, the Quayles said they had worried during the vice presidential speculation about the family's loss of privacy during a national campaign.</s>

<s docid="AP880817-0040" num="31" wdcount="16"> ``The total lack of privacy is going to be the biggest minus,'' said Mrs. Quayle, 39.</s>

<s docid="AP880817-0040" num="32" wdcount="22"> Quayle said he had questioned each of his children about whether he should accept the vice presidential spot if Bush offered it.</s>

<s docid="AP880817-0040" num="33" wdcount="8"> Tucker was fascinated by the idea, Quayle said.</s>

<s docid="AP880817-0040" num="34" wdcount="22"> Benjamin was ambiguous but he thought Secret Service agents might be able to help him on tests at school, Mrs. Quayle said.</s>

<s docid="AP880817-0040" num="35" wdcount="17"> Corinne didn't like the prospect of having her father spend more time away from home, Quayle said.</s>

<s docid="AP880817-0040" num="36" wdcount="15"> ``She told me, `Daddy, I really hope George Bush picks Bob Dole,''' said Quayle .</s>
</TEXT>
</DOC>
