<DOC>
<DOCNO>

<s docid="AP880818-0226" num="1" wdcount="1"> AP880818-0226</s>
</DOCNO>
<FILEID>

<s docid="AP880818-0226" num="2" wdcount="2"> AP-NR-08-18-88 2113EDT</s>
</FILEID>
<FIRST>

<s docid="AP880818-0226" num="3" wdcount="5"> u p BC-CVN--DoleText 08-18 0516</s>
</FIRST>
<SECOND>

<s docid="AP880818-0226" num="4" wdcount="2"> BC-CVN--Dole Text,530</s>
</SECOND>
<DATELINE>

<s docid="AP880818-0226" num="5" wdcount="3"> NEW ORLEANS (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880818-0226" num="6" wdcount="30"> Here is a transcript of the speech by Sen. Bob Dole of Kansas nominating Sen. Dan Quayle of Indiana for vice president at the Republican National Convention on Thursday night.</s>

<s docid="AP880818-0226" num="7" wdcount="2"> Thank you.</s>

<s docid="AP880818-0226" num="8" wdcount="2"> Thank you.</s>

<s docid="AP880818-0226" num="9" wdcount="24"> Mr. Chairman, four of my congressional colleagues and I are here for the purpose of nominating the next vice president of the United States.</s>

<s docid="AP880818-0226" num="10" wdcount="32"> We are here to nominate one of the bright young lights in the Republican Party, a man I am proud to say is my colleague, the junior senator from Indiana, Dan Quayle.</s>

<s docid="AP880818-0226" num="11" wdcount="8"> You know, senators get a lot of mail.</s>

<s docid="AP880818-0226" num="12" wdcount="5"> Party leaders more than most.</s>

<s docid="AP880818-0226" num="13" wdcount="13"> And almost every one of these letters asks for help with some problem.</s>

<s docid="AP880818-0226" num="14" wdcount="27"> Well, three years ago, I received a handwritten plea from a 6-year-old girl who after several days of long, long Senate sessions had a very special problem.</s>

<s docid="AP880818-0226" num="15" wdcount="11"> She wrote, and I quote: ``I have my second-grade play tonight.</s>

<s docid="AP880818-0226" num="16" wdcount="11"> Please make sure my daddy can come home and watch me''.</s>

<s docid="AP880818-0226" num="17" wdcount="17"> I knew Corinne Quayle was from a political family because she invited me to come along, too.</s>

<s docid="AP880818-0226" num="18" wdcount="24"> Corinne and her brothers, Tucker and Benjamin, and their mother, Marilyn, share Dan Quayle with the people of Indiana and the United States Senate.</s>

<s docid="AP880818-0226" num="19" wdcount="12"> Dan Quayle is a dedicated public servant and a devoted family man.</s>

<s docid="AP880818-0226" num="20" wdcount="39"> And whenever I needed him, whenever I needed him, Dan was there _ ready and willing to make the tough choices, to cast the tough votes, to transform President Reagan's vision of America into the law of the land.</s>

<s docid="AP880818-0226" num="21" wdcount="28"> Whether it was the budget or defense, tax reform or the INF treaty, Dan Quayle was there, a forceful advocate, and a staunch supporter of the Reagan revolution.</s>

<s docid="AP880818-0226" num="22" wdcount="10"> And now he is ready to carry that revolution forward.</s>

<s docid="AP880818-0226" num="23" wdcount="22"> And believe me he is ready, and just let the Democrats try to use experience as a measuring stick in this campaign.</s>

<s docid="AP880818-0226" num="24" wdcount="4"> Just let them try.</s>

<s docid="AP880818-0226" num="25" wdcount="11"> Now, I don't mean to suggest their presidential candidate lacks experience.</s>

<s docid="AP880818-0226" num="26" wdcount="37"> He's got plenty of experience, plenty of experience _ experience in raising taxes again and again, experience in vetoing the pledge of allegiance in public schools, experience in increasing spending year after year after year in Massachusetts.</s>

<s docid="AP880818-0226" num="27" wdcount="17"> And I just don't believe the American people want that kind of experience in the White House.</s>

<s docid="AP880818-0226" num="28" wdcount="8"> It sounds like a Dukak-eyed idea to me.</s>

<s docid="AP880818-0226" num="29" wdcount="6"> But Dan Quayle's got experience, too.</s>

<s docid="AP880818-0226" num="30" wdcount="31"> He's already spent 12 years as a congressman and a senator, tackling the vital national and international issues that affect the lives of all Americans and the future of our country.</s>

<s docid="AP880818-0226" num="31" wdcount="18"> That is 12 more years of national experience than Michael Dukakis _ and he is running for president.</s>

<s docid="AP880818-0226" num="32" wdcount="15"> As I said at the start, Dan Quayle is a man I know and trust.</s>

<s docid="AP880818-0226" num="33" wdcount="11"> I am honored to nominate him for vice president, Mr. Chairman.</s>

<s docid="AP880818-0226" num="34" wdcount="28"> And for the purpose of debate only, I yield the balance of my time to the outstanding, distinguished senior from Indiana, my good friend, Sen. Dick Lugar .</s>
</TEXT>
<HEAD>

<s docid="AP880818-0226" num="35" wdcount="6"> End Dole Text _ 1 Take</s>
</HEAD>
</DOC>
