<DOC>
<DOCNO>

<s docid="LA111289-0035" num="1" wdcount="1"> LA111289-0035</s>
</DOCNO>
<DOCID>

<s docid="LA111289-0035" num="2" wdcount="1"> 133531</s>
</DOCID>
<DATE>
<P>

<s docid="LA111289-0035" num="3" wdcount="6"> November 12, 1989, Sunday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA111289-0035" num="4" wdcount="9"> View; Part E; Page 1; Column 4; View Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA111289-0035" num="5" wdcount="2"> 879 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA111289-0035" num="6" wdcount="7"> ROGER SIMON: A STRATEGY THAT BEARS REPEATING</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA111289-0035" num="7" wdcount="3"> By ROGER SIMON</s>
</P>
</BYLINE>
<TEXT>
<P>

<s docid="LA111289-0035" num="8" wdcount="18"> One year after his election, Dan Quayle has achieved all he ever wanted: He has become dull .</s>
</P>
<P>

<s docid="LA111289-0035" num="9" wdcount="17"> His coming-out party last Sunday was a true test of his new ability to not make news.</s>

<s docid="LA111289-0035" num="10" wdcount="7"> He went on "Meet the Press" .</s>
</P>
<P>

<s docid="LA111289-0035" num="11" wdcount="5"> This was no small thing.</s>

<s docid="LA111289-0035" num="12" wdcount="17"> During his entire campaign for the vice presidency, Quayle refused all requests from such national interview shows.</s>

<s docid="LA111289-0035" num="13" wdcount="18"> He didn't appear on "Meet the Press" or "This Week With David Brinkley" or "Face the Nation" .</s>
</P>
<P>

<s docid="LA111289-0035" num="14" wdcount="14"> And he didn't do so because back then he was making too much news.</s>

<s docid="LA111289-0035" num="15" wdcount="12"> His every slip, his every gaffe, his every goof was news .</s>
</P>
<P>

<s docid="LA111289-0035" num="16" wdcount="8"> He was the stuff of nightly TV monologues.</s>

<s docid="LA111289-0035" num="17" wdcount="19"> "A lot of people feel Quayle is just too inexperienced for a do-nothing job," Jay Leno once said .</s>
</P>
<P>

<s docid="LA111289-0035" num="18" wdcount="52"> That joke was not only funny, but it got to the heart of a strange phenomenon: Americans didn't give a damn about the vice presidency (Mike Dukakis tried to make Quayle a major issue and failed), but some also felt that Quayle wasn't qualified for a job that had no qualifications .</s>
</P>
<P>

<s docid="LA111289-0035" num="19" wdcount="22"> So when Quayle got to Washington, he got there with one goal: Support the President and make himself a very small target.</s>

<s docid="LA111289-0035" num="20" wdcount="17"> Stay out of the headlines and give no reason for anyone to dump him in 1992 .</s>
</P>
<P>

<s docid="LA111289-0035" num="21" wdcount="25"> "We had asked him on the show a number of times," Christie Basham, senior producer of "Meet the Press" told me, "but he always declined.</s>

<s docid="LA111289-0035" num="22" wdcount="22"> We renewed our request and then after saying he would not do the show, he changed his mind and said he would.</s>

<s docid="LA111289-0035" num="23" wdcount="19"> It was the 42nd anniversary of the show and we wanted someone above and beyond the usual guest" .</s>
</P>
<P>

<s docid="LA111289-0035" num="24" wdcount="19"> And it says something about Dan Quayle's reputation that he would be considered "above and beyond" the usual guest.</s>

<s docid="LA111289-0035" num="25" wdcount="7"> Normally, a vice president would not be.</s>

<s docid="LA111289-0035" num="26" wdcount="8"> That's because vice presidents don't actually do anything.</s>

<s docid="LA111289-0035" num="27" wdcount="7"> They don't run departments or make policy.</s>

<s docid="LA111289-0035" num="28" wdcount="9"> They mostly wait for heads of state to expire.</s>

<s docid="LA111289-0035" num="29" wdcount="16"> As George Bush once joked about his duties as vice president: "You die; I fly" .</s>
</P>
<P>

<s docid="LA111289-0035" num="30" wdcount="13"> But Quayle was considered a hot TV guest because he might screw up.</s>

<s docid="LA111289-0035" num="31" wdcount="15"> He might make a mistake or say something outrageous or disagree with the President .</s>
</P>
<P>

<s docid="LA111289-0035" num="32" wdcount="4"> None of this happened.</s>

<s docid="LA111289-0035" num="33" wdcount="4"> The show was uneventful.</s>

<s docid="LA111289-0035" num="34" wdcount="15"> Quayle answered all the questions put to him and he made little if any news.</s>

<s docid="LA111289-0035" num="35" wdcount="14"> Some major newspapers didn't even bother to do a story the next day .</s>
</P>
<P>

<s docid="LA111289-0035" num="36" wdcount="8"> It was everything Quayle had hoped for .</s>
</P>
<P>

<s docid="LA111289-0035" num="37" wdcount="20"> I asked David Beckwith, his spokesman, why Quayle had waited so long to go on a major interview show .</s>
</P>
<P>

<s docid="LA111289-0035" num="38" wdcount="15"> "Well, he wanted to concentrate on the more important part of the job," Beckwith said.</s>

<s docid="LA111289-0035" num="39" wdcount="18"> "He wanted to solidify his relationship with the President and learn the inner workings of the administration" .</s>
</P>
<P>

<s docid="LA111289-0035" num="40" wdcount="5"> So why go on now?</s>
</P>
<P>

<s docid="LA111289-0035" num="41" wdcount="9"> "It seemed like a particularly opportune week," Beckwith said.</s>

<s docid="LA111289-0035" num="42" wdcount="9"> George Bush and Mikhail Gorbachev had announced a summit.</s>

<s docid="LA111289-0035" num="43" wdcount="7"> Central America was back in the news.</s>

<s docid="LA111289-0035" num="44" wdcount="16"> And, oh yeah, Bush had said Dan Quayle would be on the ticket in 1992 .</s>
</P>
<P>

<s docid="LA111289-0035" num="45" wdcount="16"> "And Marlin (Fitzwater, Bush's spokesman) called and just suggested we do the show," Beckwith said .</s>
</P>
<P>

<s docid="LA111289-0035" num="46" wdcount="20"> The selection of Dan Quayle had been Bush's first major (and some would say only) decision of his presidential campaign.</s>

<s docid="LA111289-0035" num="47" wdcount="15"> He had input from a number of people, but Quayle was George Bush's choice .</s>
</P>
<P>

<s docid="LA111289-0035" num="48" wdcount="20"> Many thought it was a terrible choice, but there is nothing like a victory to give everything a rosy glow.</s>

<s docid="LA111289-0035" num="49" wdcount="23"> And Bush's announcement that Quayle would be his running mate again was Bush's way of saying: "I didn't screw up the first time.</s>

<s docid="LA111289-0035" num="50" wdcount="25"> I made a decision and it was the right decision and just to show you how right it was, I am making it again" .</s>
</P>
<P>

<s docid="LA111289-0035" num="51" wdcount="24"> And now was the time for Quayle to go on "Meet the Press" and show everybody just how right George Bush had been .</s>
</P>
<P>

<s docid="LA111289-0035" num="52" wdcount="15"> I asked Beckwith if Quayle had been pleased by how the show had gone .</s>
</P>
<P>

<s docid="LA111289-0035" num="53" wdcount="12"> "He was especially pleased with the seriousness of the questions," Beckwith said.</s>

<s docid="LA111289-0035" num="54" wdcount="14"> "A lot of the time, you never know what you're going to get into.</s>

<s docid="LA111289-0035" num="55" wdcount="9"> Sometimes the questions can be not particularly serious" .</s>
</P>
<P>

<s docid="LA111289-0035" num="56" wdcount="23"> A typical example of a "non-serious" question often put to Dan Quayle is: "Why does everyone say your wife is smarter than you"?</s>
</P>
<P>

<s docid="LA111289-0035" num="57" wdcount="9"> But Quayle got no questions like that last week.</s>

<s docid="LA111289-0035" num="58" wdcount="19"> I asked Christie Basham of "Meet the Press" if Quayle had asked in advance who the questioners would be.</s>

<s docid="LA111289-0035" num="59" wdcount="10"> "Yes," Basham said, "but almost all the guests do" .</s>
</P>
<P>

<s docid="LA111289-0035" num="60" wdcount="23"> Quayle's questioners were David Broder of the Washington Post and Elizabeth Drew of the New Yorker, both of whom stuck to serious questions.</s>

<s docid="LA111289-0035" num="61" wdcount="28"> (If Quayle had been told the questioners were going to be Hunter Thompson and Jimmy Breslin, I have a feeling Quayle might have come down with laryngitis) .</s>
</P>
<P>

<s docid="LA111289-0035" num="62" wdcount="21"> After the show, Fitzwater called Quayle to express his, and presumably the President's, pleasure at how Quayle had handled himself .</s>
</P>
<P>

<s docid="LA111289-0035" num="63" wdcount="13"> Quayle had said very little and he had said it very well .</s>
</P>
<P>

<s docid="LA111289-0035" num="64" wdcount="16"> "The very limitations of a vice president's role don't make him an ideal guest," Beckwith admitted.</s>

<s docid="LA111289-0035" num="65" wdcount="15"> "Almost by job description, a vice president is not permitted to make serious news" .</s>
</P>
<P>

<s docid="LA111289-0035" num="66" wdcount="10"> And Quayle knows his future is in sticking to that.</s>

<s docid="LA111289-0035" num="67" wdcount="24"> During the 1988 campaign, I interviewed Quayle and I came away with one overwhelming impression: Dan Quayle would run for President in 1996 .</s>
</P>
<P>

<s docid="LA111289-0035" num="68" wdcount="25"> And he will do so, I believe, by being a vice president who keeps his head down, his nose clean and his life dull .</s>
</P>
<P>

<s docid="LA111289-0035" num="69" wdcount="8"> After all, it worked for George Bush .</s>
</P>
</TEXT>
<TYPE>
<P>

<s docid="LA111289-0035" num="70" wdcount="1"> Column</s>
</P>
</TYPE>
</DOC>
