<DOC>
<DOCNO>

<s docid="SJMN91-06140099" num="1" wdcount="1"> SJMN91-06140099</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06140099" num="2" wdcount="1"> 06140099</s>
</ACCESS>
<CAPTION>

<s docid="SJMN91-06140099" num="3" wdcount="30"> Photos (2); PHOTO: David Schenkel, who coordinated the Premiere Dan Quayle Memorabilia Exhibit in Huntington, Ind., holds a sweat shirt the vice president wore to play basketball as a boy.</s>

<s docid="SJMN91-06140099" num="4" wdcount="21"> PHOTO: New York Times; New York Times; Marj Hiner of Huntington, Ind., and her mom, Dottie Watson, tote a cardboard Quayle</s>
</CAPTION>
<DESCRIPT>

<s docid="SJMN91-06140099" num="5" wdcount="5"> US; VICE-PRESIDENT; CITY; INDIANA; REACTION</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06140099" num="6" wdcount="31"> PEOPLE in this picture-postcard town of Victorian houses and clean streets don't care what Jay Leno or the polls or the Democrats or disgruntled Republicans have been saying about Dan Quayle.</s>

<s docid="SJMN91-06140099" num="7" wdcount="42"> Despite the fact that President Bush's health problems have made the vice president a national preoccupation, to people here he's just Danny Quayle from Polk Street -- a really nice guy from a really nice family that runs the local newspaper .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06140099" num="8" wdcount="1"> Living</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06140099" num="9" wdcount="5"> QUAYLE'S HOMETOWN FLUSHED WITH PRIDE</s>
</HEADLINE>
<MEMO>

<s docid="SJMN91-06140099" num="10" wdcount="2"> Cover Story</s>
</MEMO>
<TEXT>

<s docid="SJMN91-06140099" num="11" wdcount="42"> He is the most important person ever to come out of this town, and even as the world considers his fitness for the presidency, Huntington is celebrating his life in what is ambitiously being billed as the Premiere Dan Quayle Memorabilia Exhibit.</s>

<s docid="SJMN91-06140099" num="12" wdcount="33"> To those who say Quayle does not merit his own exhibition, Quayle devotees say with a mixture of defiance and dignity that he is, after all, the vice president of the United States.</s>

<s docid="SJMN91-06140099" num="13" wdcount="9"> "We're preserving history," says David Schenkel, the exhibition coordinator.</s>

<s docid="SJMN91-06140099" num="14" wdcount="19"> "A century from now someone may want to do a dissertation on him."; If so, Huntington will be ready.</s>

<s docid="SJMN91-06140099" num="15" wdcount="49"> Relatives, former classmates and longtime neighbors of Quayle have donated yearbooks, report cards, poems, letters, his Little League uniform, a coffee cup he drank from, a chair he once stood on during the 1988 presidential campaign and just about anything else he ever touched, wrote, signed or posed for.</s>

<s docid="SJMN91-06140099" num="16" wdcount="12"> The vice president's mother, Corinne, donated a lock of his baby hair.</s>

<s docid="SJMN91-06140099" num="17" wdcount="23"> The 1972 Indianapolis 500 queen produced a picture of Quayle, then an aide to Indiana Gov. Edgar Whitcomb, accompanying her to the race.</s>

<s docid="SJMN91-06140099" num="18" wdcount="18"> And a former housekeeper turned in a 20-year-old piece of carpeting she saved from one of Quayle's floors.</s>

<s docid="SJMN91-06140099" num="19" wdcount="37"> The exhibition, which runs through May 20, was put together by the Dan Quayle Commemorative Foundation, a sort of fan-club-turned-archive devoted to documenting the life and times of the nation's 44th and, they say, least-understood vice president.</s>

<s docid="SJMN91-06140099" num="20" wdcount="13"> "He has taken such a bad rap," said Schenkel, a foundation board member.</s>

<s docid="SJMN91-06140099" num="21" wdcount="10"> "If people knew him, they'd see he's a regular person.</s>

<s docid="SJMN91-06140099" num="22" wdcount="38"> If they had a chance to sit down with Dan as a neighbor, they would see the extremely good values in the man."; These are the faithful, who have long since stopped expecting "good press" on their man.</s>

<s docid="SJMN91-06140099" num="23" wdcount="69"> Instead they measure news reports on him by their relative negativity, describing the best coverage as "more upbeat" or "halfway decent."; They defend the relatively young age of Quayle, who turned 44 in February ("All he needs is a little seasoning"); his limited experience ("Look at what they said about Truman -- he was a haberdasher"), and his passion for golf ("He has to have some form of relaxation").</s>

<s docid="SJMN91-06140099" num="24" wdcount="9"> But they are careful not to stretch the superlatives.</s>

<s docid="SJMN91-06140099" num="25" wdcount="7"> The description "nice" comes up a lot.</s>

<s docid="SJMN91-06140099" num="26" wdcount="23"> "He's not the fool that the talk show hosts think he is," says Dottie Watson, president of the Republican Women of Huntington County.</s>

<s docid="SJMN91-06140099" num="27" wdcount="8"> "He's a very nice person, a capable person.</s>

<s docid="SJMN91-06140099" num="28" wdcount="22"> Everybody I know says he can do it."; That is not to say some people don't have some friendly advice for Quayle.</s>

<s docid="SJMN91-06140099" num="29" wdcount="38"> "If he would slow down, talk an octave lower and think about what he's saying, I don't think people would take him the way they do," said Jean Anne Drabenstot, the owner of Nick's Kitchen, Quayle's favorite restaurant.</s>

<s docid="SJMN91-06140099" num="30" wdcount="32"> Hayden Schenkel, chairman of the Huntington County Democratic Party and a distant cousin of David Schenkel, says, "Some people would shudder and shiver if he accidentally became president of the United States.</s>

<s docid="SJMN91-06140099" num="31" wdcount="28"> Most of the Democrats and even some of the Republicans would say they're tickled to death to have him as vice president, and they're 100 percent behind him.</s>

<s docid="SJMN91-06140099" num="32" wdcount="26"> But in all due respect, we sure hope nothing happens to President Bush."; Quayle has declined an invitation to attend the tribute, citing a busy schedule.</s>

<s docid="SJMN91-06140099" num="33" wdcount="31"> Nonetheless, most of Huntington's 17,000 residents have rallied around their native son for the exhibition, which tracks his life from infancy through law school, from the Senate to the vice presidency.</s>

<s docid="SJMN91-06140099" num="34" wdcount="19"> The free exhibition has turned a gray room in the town's public library into a virtual Dan Quayle museum.</s>

<s docid="SJMN91-06140099" num="35" wdcount="16"> The display patches together pieces of a life that until the last decade was strikingly ordinary.</s>

<s docid="SJMN91-06140099" num="36" wdcount="26"> There is Dan Quayle and his brother Chris riding horseback and wearing cowboy hats, or sitting in front of the fireplace in their pajamas at Christmas.</s>

<s docid="SJMN91-06140099" num="37" wdcount="47"> There is Dan Quayle with his Vacation Bible School class, Dan Quayle with the high school golf team, Dan Quayle at 5 or 6 years of age with Sharon McEachern when they were named king and queen of the swim festival at the Fort Wayne Country Club.</s>

<s docid="SJMN91-06140099" num="38" wdcount="13"> It is all very 50s, very Middle American, almost surreal in its innocence.</s>

<s docid="SJMN91-06140099" num="39" wdcount="11"> There are windows into the workings of the Quayle family, too.</s>

<s docid="SJMN91-06140099" num="40" wdcount="25"> For example, his father, James, signed the report cards when Dan brought home poor grades, and his mother signed when he brought home good ones.</s>

<s docid="SJMN91-06140099" num="41" wdcount="28"> And there are letters and poems that he wrote, which only go to show that one does not have to be a Yeats to make it in politics.</s>

<s docid="SJMN91-06140099" num="42" wdcount="31"> Dan wrote this rather thoughtful verse on Nov. 22, 1960, when he was 13 years old:; My Dad is very very nice; But he is not made of sugar and spice.</s>

<s docid="SJMN91-06140099" num="43" wdcount="20"> Sometimes he acts as if he has been disturbed; But at other times he is as cheerful as a bird.</s>

<s docid="SJMN91-06140099" num="44" wdcount="46"> The exhibit also includes the 1972 newspaper announcement of Dan and Marilyn Quayle's wedding, the wooden "Quayle & Quayle" shingle the couple hung when they opened their law practice here, and assorted campaign souvenirs, including the official air sickness bag from the 1988 Republican National Convention.</s>

<s docid="SJMN91-06140099" num="45" wdcount="11"> Ultimately, the foundation wants to build a repository for the memorabilia.</s>

<s docid="SJMN91-06140099" num="46" wdcount="35"> It has already organized a walking tour of historic Quayle sites, like the white, ranch-style house where he spent his early days, and Nick's Kitchen, where he likes to order tenderloins, fries and a milkshake.</s>

<s docid="SJMN91-06140099" num="47" wdcount="24"> "We want everybody to know he's a winner -- I don't care what the newspapers say," said Marge Hiner, one of the exhibit organizers.</s>

<s docid="SJMN91-06140099" num="48" wdcount="30"> "What a role model for our children, to know that you can be a normal person, come from a normal family and become vice president of the United States" .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06140099" num="49" wdcount="5"> ISABEL WILKERSON, New York Times</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06140099" num="50" wdcount="1"> USA</s>
</COUNTRY>
<CITY>

<s docid="SJMN91-06140099" num="51" wdcount="3"> Huntington, Ind .</s>
</CITY>
<EDITION>

<s docid="SJMN91-06140099" num="52" wdcount="2"> Morning Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06140099" num="53" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06140099" num="54" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06140099" num="55" wdcount="1"> 910519</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06140099" num="56" wdcount="1"> Sunday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06140099" num="57" wdcount="1"> May</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06140099" num="58" wdcount="1"> 1L</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06140099" num="59" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06140099" num="60" wdcount="1"> WEST</s>
</REGION>
<FEATURE>

<s docid="SJMN91-06140099" num="61" wdcount="1"> PHOTO</s>
</FEATURE>
<STATE>

<s docid="SJMN91-06140099" num="62" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06140099" num="63" wdcount="1"> 1,107</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06140099" num="64" wdcount="5"> Sunday May 19, 1991 00140099,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06140099" num="65" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06140099" num="66" wdcount="1"> 0</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06140099" num="67" wdcount="1"> ENG</s>
</LANGUAGE>
</DOC>
