<DOC>
<DOCNO>

<s docid="FT922-2972" num="1" wdcount="1"> FT922-2972</s>
</DOCNO>
<PROFILE>

<s docid="FT922-2972" num="2" wdcount="1"> _AN-CFMAHADPFT</s>
</PROFILE>
<DATE>

<s docid="FT922-2972" num="3" wdcount="1"> 920613</s>
</DATE>
<HEADLINE>

<s docid="FT922-2972" num="4" wdcount="12"> FT 13 JUN 92 / Banks did not discuss their Maxwell fears</s>
</HEADLINE>
<BYLINE>

<s docid="FT922-2972" num="5" wdcount="6"> By ROBERT PESTON and BRONWEN MADDOX</s>
</BYLINE>
<TEXT>

<s docid="FT922-2972" num="6" wdcount="26"> ABOUT 20 banks became con-cerned last summer at the behaviour of businesses run by Robert Maxwell several months before he died and his business empire collapsed.</s>

<s docid="FT922-2972" num="7" wdcount="18"> Their concern arose when Maxwell Communication Corporation made late payments to them, a Financial Times investigation has discovered.</s>

<s docid="FT922-2972" num="8" wdcount="34"> Yet although some banks became alarmed at the implications for the financial health of his empire, they did not discuss their concerns with each other or with authorities such as the Bank of England.</s>

<s docid="FT922-2972" num="9" wdcount="33"> Mr Basil Brookes, MCC's former finance director, has described his shock to the FT at discovering last August that MCC had failed to settle foreign currency transactions with about 20 banks on time.</s>

<s docid="FT922-2972" num="10" wdcount="27"> Starting about July 4 1991, MCC's treasury, under the authority of Maxwell and his son, Kevin, had begun to buy and sell enormous amounts of foreign currencies.</s>

<s docid="FT922-2972" num="11" wdcount="20"> In these 'spot' transactions, MCC would buy a currency in one financial centre promising to make payment in another centre.</s>

<s docid="FT922-2972" num="12" wdcount="22"> On a number of occasions, MCC received the currency, but did not make the payment - thereby giving itself an unauthorised loan.</s>

<s docid="FT922-2972" num="13" wdcount="26"> Mr Brookes says about 20 banks, including Lloyds, Bank of America, Goldman Sachs and Swiss Bank Corporation, were involved in the flurry of foreign exchange deals.</s>

<s docid="FT922-2972" num="14" wdcount="17"> At least Dollars 100m (Pounds 55m) in unapproved credit is thought to have been raised this way.</s>

<s docid="FT922-2972" num="15" wdcount="15"> A former Maxwell employee said some appeared to have been channelled into private Maxwell businesses.</s>

<s docid="FT922-2972" num="16" wdcount="27"> One banker said attempts to raise money by making late payments in the foreign market was a relatively well-known ruse with the nickname called 'teaming and lading'.</s>

<s docid="FT922-2972" num="17" wdcount="35"> It also emerged yesterday that National Westminster Bank, the biggest lender to the Maxwell private companies, felt badly let down by Maxwell because he failed to deliver funds on time at the end of July.</s>

<s docid="FT922-2972" num="18" wdcount="25"> At a meeting between Maxwell and Mr John Melbourn, a NatWest director, on July 10, NatWest refused Maxwell's request for a loan of Pounds 45m.</s>

<s docid="FT922-2972" num="19" wdcount="39"> NatWest was upset three weeks later when it provided funds - less than Pounds 100m - to the Maxwell empire on the understanding that it would be repaid the same day, and then found that repayment was not made.</s>

<s docid="FT922-2972" num="20" wdcount="16"> NatWest was forced to convert this 'intra-day' transaction into a short-term loan, which was eventually repaid.</s>

<s docid="FT922-2972" num="21" wdcount="36"> The bank told both Robert Maxwell and Mr Kevin Maxwell that it was concerned that repayment had not been made, but it did not discuss the problem with other banks or with the Bank of England.</s>

<s docid="FT922-2972" num="22" wdcount="18"> Instead, it pressed on with its policy of reducing the size of its loans to the Maxwell businesses.</s>

<s docid="FT922-2972" num="23" wdcount="17"> NatWest's loans to the Maxwell empire now total Pounds 182m, half the level of two years ago.</s>

<s docid="FT922-2972" num="24" wdcount="39"> Later last year, Robert Maxwell made many repayments to banks by looting pension fund assets and also carrying out unusual fundraising exercises with US investment banks, from which tens of millions of dollars were borrowed at a high price.</s>

<s docid="FT922-2972" num="25" wdcount="8"> 'Trust me', Weekend I Maxwell lessons, Weekend IV</s>
</TEXT>
<PUB>

<s docid="FT922-2972" num="26" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT922-2972" num="27" wdcount="3"> London Page 1</s>
</PAGE>
</DOC>
