<DOC>
<DOCNO>

<s docid="FT922-3446" num="1" wdcount="1"> FT922-3446</s>
</DOCNO>
<PROFILE>

<s docid="FT922-3446" num="2" wdcount="1"> _AN-CFKBHADDFT</s>
</PROFILE>
<DATE>

<s docid="FT922-3446" num="3" wdcount="1"> 920611</s>
</DATE>
<HEADLINE>

<s docid="FT922-3446" num="4" wdcount="11"> FT 11 JUN 92 / Maxwells' MCC share purchasing involvement documented</s>
</HEADLINE>
<BYLINE>

<s docid="FT922-3446" num="5" wdcount="6"> By ANDREW JACK and ROBERT PESTON</s>
</BYLINE>
<TEXT>

<s docid="FT922-3446" num="6" wdcount="41"> DOCUMENTS which show for the first time that both Mr Robert Maxwell and his son Kevin were intimately involved in substantial purchases of shares in Maxwell Communication Corporation, one of their own public companies, have been obtained by the Financial Times.</s>

<s docid="FT922-3446" num="7" wdcount="47"> Meanwhile, a director of a secretive Swiss trust, Mr Werner Rechsteiner, has broken his silence and has admitted that transfers of MCC shares to his trust, which are at the centre of an investigation by the Serious Fraud Office, were made on the instructions of Robert Maxwell.</s>

<s docid="FT922-3446" num="8" wdcount="24"> This is the first time that Mr Rechsteiner has given details of the relationship between his mysterious trust, Yakosa Finanzierungs, and the Maxwell family.</s>

<s docid="FT922-3446" num="9" wdcount="40"> The FT has also obtained a letter and has seen a corroborating fax which shows that Mr Kevin Maxwell was intimately involved in the purchase of 9m shares by Yakosa and a further 16m shares by Servex, another Swiss Trust.</s>

<s docid="FT922-3446" num="10" wdcount="27"> The MCC purchases by Yakosa and Servex are the object of an investigation by the SFO into an alleged illegal scheme to support the MCC share price.</s>

<s docid="FT922-3446" num="11" wdcount="30"> The SFO is also investigating whether Mr Robert Maxwell or Mr Kevin Maxwell breached the Companies Act by failing to disclose the purchases of the shares by the Swiss trusts.</s>

<s docid="FT922-3446" num="12" wdcount="26"> If either had a financial interest in the Swiss trusts, the purchases should have been disclosed under company law, because they were both directors of MCC.</s>

<s docid="FT922-3446" num="13" wdcount="35"> The documents demonstrate that Bishopsgate Investment Trust, a private UK company controlled by the Maxwell family, provided Pounds 55.33m on behalf of the two Swiss trusts so that they could pay for the MCC shares.</s>

<s docid="FT922-3446" num="14" wdcount="12"> Goldman Sachs, the US investment bank, acted as broker to the deals.</s>

<s docid="FT922-3446" num="15" wdcount="8"> Goldman's lawyers are convinced that it acted properly.</s>

<s docid="FT922-3446" num="16" wdcount="25"> Mr Rechsteiner yesterday broke the silence he has maintained since Robert Maxwell's death in November on the subject of his relationship with the Maxwell family.</s>

<s docid="FT922-3446" num="17" wdcount="14"> He said MCC share purchases had been 'going on for some time' through Yakosa.</s>

<s docid="FT922-3446" num="18" wdcount="11"> He denied that the shares were bought for Yakosa's 'own account'.</s>

<s docid="FT922-3446" num="19" wdcount="16"> He said the shares were bought for other 'foundations' and then 'held for a certain time'.</s>

<s docid="FT922-3446" num="20" wdcount="31"> He also stressed that ownership of the MCC shares no longer rested with Robert Maxwell once they had been received by Yakosa: 'Yakosa is owned by the Maxwell Foundation,' he said.</s>

<s docid="FT922-3446" num="21" wdcount="24"> Mr Rechsteiner refused to say who controlled the Maxwell Foundation, which is based in Liechtenstein, but said it was neither Robert nor Kevin Maxwell.</s>

<s docid="FT922-3446" num="22" wdcount="32"> The FT has however obtained documents showing that Mr Kevin Maxwell was closely involved in the process of paying for 25m MCC shares on behalf of two Swiss trusts, Yakosa and Servex.</s>

<s docid="FT922-3446" num="23" wdcount="48"> On May 29 last year, Mr Kevin Maxwell sent a fax to Mr Larry Wood, an executive director of Goldman Sachs, telling him that two parcels of 12.5m MCC shares each would be bought by the Swiss trusts with Pounds 55.33m provided by BIT, a Maxwell private company.</s>

<s docid="FT922-3446" num="24" wdcount="31"> The fax, signed by Mr Maxwell, said that the funds would be remitted to Goldman Sachs 'by Bishopsgate Investment Trust PLC from its account at National Westminter Bank plc, 41 Lothbury'.</s>

<s docid="FT922-3446" num="25" wdcount="35"> Two other faxes sent by Mr Kevin Maxwell to Mr Wood on the same day show that the former was equally involved in the other end of the transaction, the sale of the 25m shares.</s>

<s docid="FT922-3446" num="26" wdcount="29"> The Swiss trusts bought the shares, using Goldman as broker, from two Maxwell pension funds, Maxwell Communication Pension Trustee (Works Scheme) and Mirror Group Newspaper Pension Trustee (Works Scheme).</s>

<s docid="FT922-3446" num="27" wdcount="18"> Each pension fund sold 12.5m shares at a price of 219.78p a share, or Pounds 27.47m in total.</s>

<s docid="FT922-3446" num="28" wdcount="22"> At 6.29pm on May 29, Mr Maxwell sent the two other faxes to Mr Wood on behalf of the two pension funds.</s>

<s docid="FT922-3446" num="29" wdcount="41"> As a director of MGPT and as a trustee of MCCPT, he told Mr Wood to pay each pension fund what it was owed to the NatWest account of BIT, which Mr Maxwell described as 'nominee' for the two pension funds.</s>

<s docid="FT922-3446" num="30" wdcount="35"> In other words, he told Mr Wood that the shares were being bought for the Swiss trusts with funds provided by BIT and that these funds should then be sent by Goldman back to BIT.</s>

<s docid="FT922-3446" num="31" wdcount="19"> In the event, on May 31, Goldman received the Pounds 55.3m by wire transfer in its account at Barclays.</s>

<s docid="FT922-3446" num="32" wdcount="22"> Goldman then levied its commission and expenses on the deal of Pounds 385,000 and wired the remainder back to BIT's NatWest account.</s>

<s docid="FT922-3446" num="33" wdcount="12"> Scots bank bows out, Page 8 Claims to Israeli shares, Page 8</s>
</TEXT>
<PUB>

<s docid="FT922-3446" num="34" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT922-3446" num="35" wdcount="3"> London Page 1</s>
</PAGE>
</DOC>
