<DOC>
<DOCNO>

<s docid="FT924-12616" num="1" wdcount="1"> FT924-12616</s>
</DOCNO>
<PROFILE>

<s docid="FT924-12616" num="2" wdcount="1"> _AN-CJTB8ADVFT</s>
</PROFILE>
<DATE>

<s docid="FT924-12616" num="3" wdcount="1"> 921020</s>
</DATE>
<HEADLINE>

<s docid="FT924-12616" num="4" wdcount="15"> FT 20 OCT 92 / UK Company News: Master takes Maxwell's chess and bridge side</s>
</HEADLINE>
<BYLINE>

<s docid="FT924-12616" num="5" wdcount="3"> By RAYMOND SNODDY</s>
</BYLINE>
<TEXT>

<s docid="FT924-12616" num="6" wdcount="30"> THE LATE Mr Robert Maxwell liked to think of himself as a 'strong ' chess player and there was always a chess set in his suite in his London headquarters.</s>

<s docid="FT924-12616" num="7" wdcount="47"> 'There is no evidence to suggest that Maxwell actually was a strong player or that he played in any tournaments,' said Mr Malcolm Pein, international chess master and director of Chess and Bridge, which yesterday took over the business and assets of Maxwell Macmillan Chess and Bridge.</s>

<s docid="FT924-12616" num="8" wdcount="19"> There may be doubts about Robert Maxwell's strength as a player but less about his enthusiasm for the game.</s>

<s docid="FT924-12616" num="9" wdcount="18"> In 1990, through The European newspaper, he sponsored a section of the World Chess championships in New York.</s>

<s docid="FT924-12616" num="10" wdcount="17"> And when Pergamon was sold to Elsevier last year Maxwell kept the chess and bridge publishing businesses.</s>

<s docid="FT924-12616" num="11" wdcount="32"> Mr Pein said it had taken most of the year since Mr Maxwell's death to prise the businesses, which include Chess Monthly and Bridge Monthly from the administrators to the Maxwell empire.</s>

<s docid="FT924-12616" num="12" wdcount="18"> 'Price Waterhouse took months and months to come up with any information about the company,' said Mr Pein.</s>

<s docid="FT924-12616" num="13" wdcount="35"> Even when the new company had reached agreement to buy the business from Price Waterhouse, administrator to the public Maxwell companies they then ran into trouble with Arthur Andersen, administrator to the private Maxwell businesses.</s>

<s docid="FT924-12616" num="14" wdcount="35"> Mr Pein said the new company wanted to use and pay for the premises of Maxwell Macmillan Chess and Bridge - prefabricated buildings in the village of Wheatley, Oxfordshire - until they found permanent premises.</s>

<s docid="FT924-12616" num="15" wdcount="11"> However, he said that Arthur Andersen wanted two years back rent.</s>

<s docid="FT924-12616" num="16" wdcount="19"> Despite the year of difficulties, Chess and Bridge is now set up in new premises in Euston Road, London.</s>

<s docid="FT924-12616" num="17" wdcount="19"> The company said it had the largest collection of chess and bridge books and products in the UK .</s>
</TEXT>
<PUB>

<s docid="FT924-12616" num="18" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT924-12616" num="19" wdcount="3"> London Page 28</s>
</PAGE>
</DOC>
