<DOC>
<DOCNO>

<s docid="FT922-1115" num="1" wdcount="1"> FT922-1115</s>
</DOCNO>
<PROFILE>

<s docid="FT922-1115" num="2" wdcount="1"> _AN-CFXBMAD4FT</s>
</PROFILE>
<DATE>

<s docid="FT922-1115" num="3" wdcount="1"> 920624</s>
</DATE>
<HEADLINE>

<s docid="FT922-1115" num="4" wdcount="27"> FT 24 JUN 92 / MGN threatens legal action over transfers: Maxwell chief named over Pounds 180m 'unusual' transactions; Annual report reveals extraordinary losses of Pounds 421.5m</s>
</HEADLINE>
<BYLINE>

<s docid="FT922-1115" num="5" wdcount="3"> By ANDREW JACK</s>
</BYLINE>
<TEXT>

<s docid="FT922-1115" num="6" wdcount="50"> MR MICHAEL STONEY, a senior executive in a number of Maxwell companies, is named as one of three people primarily responsible for more than Pounds 180m of 'unusual' payments from Mirror Group Newspapers bank accounts during the last financial year, according to the chairman's statement released with MGN accounts yesterday.</s>

<s docid="FT922-1115" num="7" wdcount="26"> Mr Kevin Maxwell and Mr Ian Maxwell, two sons of the late Robert Maxwell, are named as the other two people most involved in these transactions.</s>

<s docid="FT922-1115" num="8" wdcount="15"> Mr Kevin Maxwell and Mr Stoney refused to provide MGN with information, the statement says.</s>

<s docid="FT922-1115" num="9" wdcount="31"> Sir Robert Clark, chairman of MGN, lists a series of transactions - some of which he stresses may have been perfectly legitimate - that took place in the past few months.</s>

<s docid="FT922-1115" num="10" wdcount="40"> He says legal action may be taken against a number of organisations, including Goldman Sachs, the US investment bank, over more than Pounds 40m in transfers from MGN if the bank was aware that they were 'effected for improper purposes'.</s>

<s docid="FT922-1115" num="11" wdcount="34"> Notes to the accounts show that MGN made extraordinary provisions of Pounds 421.5m in the year to December 29 1991, including Pounds 208.6m in pension deficiencies and Pounds 122.4m in transactions with Maxwell-controlled companies.</s>

<s docid="FT922-1115" num="12" wdcount="32"> Sir Robert says that during the year there were at least 28 'unusual' payments for more than Pounds 1m from the group's bank accounts, making a total of more than Pounds 180m.</s>

<s docid="FT922-1115" num="13" wdcount="12"> 'Some may well ultimately be established to have arisen under legitimate transactions'.</s>

<s docid="FT922-1115" num="14" wdcount="10"> Nine of the payments were authorised solely by Robert Maxwell.</s>

<s docid="FT922-1115" num="15" wdcount="18"> The others were authorised mainly by Mr Kevin Maxwell, Mr Ian Maxwell and Mr Michael Stoney, he says.</s>

<s docid="FT922-1115" num="16" wdcount="28"> One transfer to Goldman Sachs was countersigned by Mr Ernest Burrington, former managing director, at the request of Mr Kevin Maxwell on the reported instruction of Robert Maxwell.</s>

<s docid="FT922-1115" num="17" wdcount="12"> Two authorisations were countersigned by Mr Lawrence Guest, former MGN finance director.</s>

<s docid="FT922-1115" num="18" wdcount="24"> Sir Robert says the MGN directors do not believe that either Mr Burrington or Mr Guest knew there was anything improper about these payments.</s>

<s docid="FT922-1115" num="19" wdcount="25"> With these exceptions, 'the independent directors . . . were not involved in, and did not authorise or approve any of these payments,' he says.</s>

<s docid="FT922-1115" num="20" wdcount="37"> Sir Robert says the group finance department accepted assurances from the treasury department - which was headed by Mr Stoney - about 'the nature of certain transactions' including payments to financial institutions which were recorded as deposits.</s>

<s docid="FT922-1115" num="21" wdcount="25"> 'The treasury department arranged for it to appear that sums of interest had been credited to the group in respect of those 'deposits',' he says.</s>

<s docid="FT922-1115" num="22" wdcount="97"> In his report Sir Robert points to 'certain weaknesses' accepted by the MGN board: Internal controls and operating procedures which failed to identify related party transactions and bring them to the attention of independent directors for approval; Bank mandates authorised by Robert Maxwell and Mr Stoney which permitted the movement of group funds on the authority of Maxwell or directors who were also directors of Maxwell-controlled companies; The audit committee of non-executive directors, which might have reviewed systems and mandates, but was not convened; The finance department's inadequate authority to verify and record the treasury department's activities.</s>

<s docid="FT922-1115" num="23" wdcount="79"> The report details a Pounds 50m loan made by Bankers Trust in London last October which appears to have been used to pay off a loan from Bankers Trust in New York to Robert Maxwell Group, parent of the Maxwell private interests, Separately, the statement highlights three transfers of more than Pounds 40m from MGN to Goldman Sachs - Pounds 11m of this was transferred on Robert Maxwell's signature to pay for previous dealings in Maxwell Communication Corporation stock.</s>

<s docid="FT922-1115" num="24" wdcount="19"> The balance was for foreign exchange trade exposures incurred by Bishopsgate Investment Trust and Robert Maxwell Group, it says.</s>

<s docid="FT922-1115" num="25" wdcount="30"> He says MGN is inquiring to see whether it can establish if Goldman Sachs was 'aware or should have been aware' that the transfers 'had been effected for improper purposes'.</s>

<s docid="FT922-1115" num="26" wdcount="20"> If so, he says 'it will be possible to seek orders against them . . . for the sums paid'.</s>

<s docid="FT922-1115" num="27" wdcount="31"> He says MGN is considering legal action against professional advisers in relation to property leases, and hopes to recover money through claims on insurance policies written on Robert Maxwell's life .</s>
</TEXT>
<PUB>

<s docid="FT922-1115" num="28" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT922-1115" num="29" wdcount="3"> London Page 8</s>
</PAGE>
</DOC>
