<DOC>
<DOCNO>

<s docid="FT941-11518" num="1" wdcount="1"> FT941-11518</s>
</DOCNO>
<PROFILE>

<s docid="FT941-11518" num="2" wdcount="1"> _AN-EBDDEAACFT</s>
</PROFILE>
<DATE>

<s docid="FT941-11518" num="3" wdcount="1"> 940204</s>
</DATE>
<HEADLINE>

<s docid="FT941-11518" num="4" wdcount="12"> FT 04 FEB 94 / Maxwell musical injunction could stop the show</s>
</HEADLINE>
<BYLINE>

<s docid="FT941-11518" num="5" wdcount="6"> By JOHN MASON, Law Courts Correspondent</s>
</BYLINE>
<TEXT>

<s docid="FT941-11518" num="6" wdcount="31"> Sir Nicholas Lyell QC, the attorney-general, will attempt to stop the curtain rising on Maxwell: The Musical, the West End show chronicling the life and times of the late Robert Maxwell.</s>

<s docid="FT941-11518" num="7" wdcount="36"> Fears that the musical might prejudice the criminal trial of the late publisher's sons, Kevin and Ian, have prompted Sir Nicholas to apply to the High Court on Monday for an injunction to halt the production.</s>

<s docid="FT941-11518" num="8" wdcount="17"> The musical tells the tycoon's life story through updated versions of familiar tunes from Gilbert and Sullivan.</s>

<s docid="FT941-11518" num="9" wdcount="16"> Now in rehearsal, the show is due to open at London's Criterion theatre on February 11.</s>

<s docid="FT941-11518" num="10" wdcount="19"> The attorney-general's move to close down a West End production before its first night is regarded as without precedent.</s>

<s docid="FT941-11518" num="11" wdcount="49"> However, it is no more unprecedented, most lawyers say, than the prospect of the Maxwell brothers having to commute to their trial at the Old Bailey past a theatre advertising the story of their father as 'the musical review that will make you laugh, sing - and be angry'.</s>

<s docid="FT941-11518" num="12" wdcount="26"> The musical, which has cost Pounds 1.1m to put on, has been produced by Mr Evan Steadman, a former chairman of one of Maxwell's private companies.</s>

<s docid="FT941-11518" num="13" wdcount="22"> Mr Steadman indicated yesterday he intended the show to go on and that the attorney-general's application for an injunction would be contested.</s>

<s docid="FT941-11518" num="14" wdcount="13"> However, he said he was leaving matters in the hands of his lawyers.</s>

<s docid="FT941-11518" num="15" wdcount="57"> Press coverage of the late publisher since his death has already caused deep concern to the Maxwell brothers' lawyers . Mr Alun Jones QC, Kevin Maxwell's barrister, led calls for reporting restrictions to be placed on a recent High Court ruling that Robert Maxwell had been fraudulent in his dealings with shares in Berlitz, the publishing company.</s>

<s docid="FT941-11518" num="16" wdcount="25"> Turning down his request, the judge asked him: 'Is it going to be your client's defence that Mr Robert Maxwell was not guilty of misappropriation'?</s>

<s docid="FT941-11518" num="17" wdcount="11"> At that point, lawyers in court themselves fell about laughing .</s>
</TEXT>
<XX>

<s docid="FT941-11518" num="18" wdcount="1"> Countries:-</s>
</XX>
<CN>

<s docid="FT941-11518" num="19" wdcount="5"> GBZ United Kingdom, EC .</s>
</CN>
<XX>

<s docid="FT941-11518" num="20" wdcount="1"> Industries:-</s>
</XX>
<IN>

<s docid="FT941-11518" num="21" wdcount="3"> P9211 Courts .</s>
</IN>
<XX>

<s docid="FT941-11518" num="22" wdcount="1"> Types:-</s>
</XX>
<TP>

<s docid="FT941-11518" num="23" wdcount="4"> NEWS General News .</s>
</TP>
<PUB>

<s docid="FT941-11518" num="24" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT941-11518" num="25" wdcount="3"> London Page 1</s>
</PAGE>
</DOC>
