<DOC>
<DOCNO>

<s docid="FT942-12054" num="1" wdcount="1"> FT942-12054</s>
</DOCNO>
<PROFILE>

<s docid="FT942-12054" num="2" wdcount="1"> _AN-EECCXABUFT</s>
</PROFILE>
<DATE>

<s docid="FT942-12054" num="3" wdcount="1"> 940503</s>
</DATE>
<HEADLINE>

<s docid="FT942-12054" num="4" wdcount="12"> FT 03 MAY 94 / Bank accused over Maxwell Pounds 55m switch</s>
</HEADLINE>
<BYLINE>

<s docid="FT942-12054" num="5" wdcount="5"> By NORMA COHEN, Investments Correspondent</s>
</BYLINE>
<TEXT>

<s docid="FT942-12054" num="6" wdcount="37"> Two writs have been filed alleging that Goldman Sachs, the US-based investment bank, assisted in diverting Pounds 55m from two pension schemes controlled by Robert Maxwell to ensure its own debts from Maxwell interests would be repaid.</s>

<s docid="FT942-12054" num="7" wdcount="29"> The writs were filed late last week in the State Supreme Court in Manhattan by trustees for Mirror Group Newspapers Pension Scheme and Maxwell Communication Corpora-tion Works Pension Scheme.</s>

<s docid="FT942-12054" num="8" wdcount="32"> The trustees seek more than Dollars 100m for the sale of shares plus interest, commission charges and punitive damages from Goldman and Mr Eric Sheinberg, partner in charge of international equities trading.</s>

<s docid="FT942-12054" num="9" wdcount="36"> The writs centre on the purchase of Pounds 55m of MCC shares from the pension schemes by two Swiss trusts, Servex and Yakosa, which were transacted through Goldman and for which the schemes were never paid.</s>

<s docid="FT942-12054" num="10" wdcount="13"> The writs allege Goldman was aware the trusts were controlled by Robert Maxwell.</s>

<s docid="FT942-12054" num="11" wdcount="53"> The writs also allege that on May 28 1991 - the same date Mr Kevin Maxwell arranged for the pension fund share transaction to be paid for - Goldman was due to receive Dollars 58.2m for an unrelated transaction selling MCC stock to an unnamed American lawyer 'with close connections to Robert Maxwell'.</s>

<s docid="FT942-12054" num="12" wdcount="17"> The writs claim that Goldman was 'competing directly with its customer, the pension fund trustee, for payment'.</s>

<s docid="FT942-12054" num="13" wdcount="22"> On April 26 1991, they say, Mr Kevin Maxwell told Mr Sheinberg to sell the pension scheme shares to the Swiss trusts.</s>

<s docid="FT942-12054" num="14" wdcount="36"> On May 23 he told Goldman to remit the proceeds of the sale not to the pension schemes but to Bishopsgate Investment Trust, which Goldman knew or should have known was controlled by the Maxwell family.</s>

<s docid="FT942-12054" num="15" wdcount="43"> The writs allege that after the deal was struck Mr Trevor Cook, MGN pension fund administrator, told Goldman that proceeds of the sale should be paid to the pension scheme, but when Mr Kevin Maxwell ordered the proceeds to be paid to BIT.</s>

<s docid="FT942-12054" num="16" wdcount="46"> The writs say that Goldman and Sheinberg 'made no reasonable effort to determine who had actual authority to direct for the pension fund that the shares be sold and where the more than Dollars 47m in proceeds from the transfer of the 12.5m shares should go'.</s>

<s docid="FT942-12054" num="17" wdcount="42"> Goldman said it had 'received no money or other benefit from these transactions other than its brokerage commissions of Pounds 110,000 which were substantially less than the amount of the applicable stamp duties paid to the Inland Revenue of Pounds 215,000' .</s>
</TEXT>
<XX>

<s docid="FT942-12054" num="18" wdcount="1"> Companies:-</s>
</XX>
<CO>

<s docid="FT942-12054" num="19" wdcount="6"> Goldman Sachs Group Limited Partnership .</s>
</CO>
<XX>

<s docid="FT942-12054" num="20" wdcount="1"> Countries:-</s>
</XX>
<CN>

<s docid="FT942-12054" num="21" wdcount="6"> USZ United States of America .</s>
</CN>
<XX>

<s docid="FT942-12054" num="22" wdcount="1"> Industries:-</s>
</XX>
<IN>

<s docid="FT942-12054" num="23" wdcount="3"> P9211 Courts .</s>
</IN>
<XX>

<s docid="FT942-12054" num="24" wdcount="1"> Types:-</s>
</XX>
<TP>

<s docid="FT942-12054" num="25" wdcount="4"> COMP Company News .</s>
</TP>
<PUB>

<s docid="FT942-12054" num="26" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT942-12054" num="27" wdcount="3"> London Page 9</s>
</PAGE>
</DOC>
