<DOC>
<DOCNO>

<s docid="LA060590-0086" num="1" wdcount="1"> LA060590-0086</s>
</DOCNO>
<DOCID>

<s docid="LA060590-0086" num="2" wdcount="1"> 229172</s>
</DOCID>
<DATE>
<P>

<s docid="LA060590-0086" num="3" wdcount="6"> June 5, 1990, Tuesday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA060590-0086" num="4" wdcount="9"> Business; Part D; Page 3; Column 1; Financial Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA060590-0086" num="5" wdcount="2"> 292 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA060590-0086" num="6" wdcount="7"> MAXWELL SEEKS TO BUY BIG U.S. NEWSPAPER</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA060590-0086" num="7" wdcount="6"> By PAUL RICHTER, TIMES STAFF WRITER</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA060590-0086" num="8" wdcount="2"> NEW YORK</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA060590-0086" num="9" wdcount="27"> British media entrepreneur Robert Maxwell said Monday that he is involved in negotiations to buy a U.S. newspaper valued "in the hundreds of millions of dollars" .</s>
</P>
<P>

<s docid="LA060590-0086" num="10" wdcount="30"> Maxwell declined to identify the newspaper, but his comments prompted industry speculation that it might be Gannett's USA Today, Tribune Co.'s New York Daily News or the Chicago Sun-Times .</s>
</P>
<P>

<s docid="LA060590-0086" num="11" wdcount="14"> Officials of each of those newspapers denied that they were negotiating with Maxwell .</s>
</P>
<P>

<s docid="LA060590-0086" num="12" wdcount="32"> Maxwell's comments were made to reporters at the annual meeting in New York of Maxwell's Berlitz International and were confirmed later by a spokesman for Maxwell Communications, the investor's London-based holding company.</s>

<s docid="LA060590-0086" num="13" wdcount="17"> The spokesman declined to elaborate on the remarks, and said Maxwell had left the United States .</s>
</P>
<P>

<s docid="LA060590-0086" num="14" wdcount="31"> The Daily News has one of the United States' largest circulations, but in recent years it has struggled to restore profitability and maintain circulation in a market with three other dailies.</s>

<s docid="LA060590-0086" num="15" wdcount="12"> The paper is conducting difficult labor contract negotiations with its unions .</s>
</P>
<P>

<s docid="LA060590-0086" num="16" wdcount="37"> Some analysts said it might make sense for Maxwell to try to purchase USA Today, since it would mesh well with his efforts to print and distribute his month-old "pan-European" English-language paper, The European, in this country.</s>

<s docid="LA060590-0086" num="17" wdcount="18"> Maxwell has already been in negotiations with USA Today officials about printing the paper for U.S. distribution .</s>
</P>
<P>

<s docid="LA060590-0086" num="18" wdcount="29"> Other industry officials conjectured that Maxwell might be talking to the Chicago Sun-Times, which has seen daily circulation slide more than 100,000 papers, to about 533,000, since 1985 .</s>
</P>
<P>

<s docid="LA060590-0086" num="19" wdcount="25"> Maxwell, who publishes Britain's Daily Mirror, recently bought three U.S. supermarket tabloids, the Globe, National Examiner and the Sun, for an estimated $100 million .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA060590-0086" num="20" wdcount="4"> Photo, Donna F. Tuttle</s>
</P>
</GRAPHIC>
<SUBJECT>
<P>

<s docid="LA060590-0086" num="21" wdcount="7"> ACQUISITIONS; MAXWELL, ROBERT; NEWSPAPERS -- UNITED STATES</s>
</P>
</SUBJECT>
</DOC>
