<DOC>
<DOCNO>

<s docid="SJMN91-06346032" num="1" wdcount="1"> SJMN91-06346032</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06346032" num="2" wdcount="1"> 06346032</s>
</ACCESS>
<DESCRIPT>

<s docid="SJMN91-06346032" num="3" wdcount="13"> UK; PUBLICATION; MEDIA; COMPANY; OFFICIAL; SUICIDE; DEATH; ACCIDENT; BOAT; PENSION; EMPLOYEE; FRAUD; PROBE</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06346032" num="4" wdcount="35"> A son of the late publishing magnate Robert Maxwell thinks there is no chance Maxwell employees will recover any of the hundreds of millions of dollars in pension funds that disappeared, a report said today.</s>

<s docid="SJMN91-06346032" num="5" wdcount="36"> Kevin Maxwell also was quoted as saying that much of the criticism calling his father a crook is fair and that there's "not the remotest possibility" his father's death a month ago was a suicide .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06346032" num="6" wdcount="1"> Business</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06346032" num="7" wdcount="5"> SON: MAXWELL'S DEATH WASN'T SUICIDE</s>
</HEADLINE>
<TEXT>

<s docid="SJMN91-06346032" num="8" wdcount="20"> Investigators have said Maxwell siphoned money from his companies in a desperate attempt to deal with his empire's crushing debts.</s>

<s docid="SJMN91-06346032" num="9" wdcount="13"> They also have said some questionable transactions may have occurred after Maxwell's death.</s>

<s docid="SJMN91-06346032" num="10" wdcount="29"> In an interview published today by the Daily Mirror, Robert Maxwell's London flagship newspaper, Kevin Maxwell was quoted as saying of the pensioners:; "I am desperately sorry for them.</s>

<s docid="SJMN91-06346032" num="11" wdcount="6"> But I have to be honest.</s>

<s docid="SJMN91-06346032" num="12" wdcount="39"> The debts are so enormous that when everything is sorted out there will be nothing left."; One week ago, the Serious Fraud Office, a government prosecution agency, began investigating Mirror Group Newspapers PLC's pension fund assets and related matters.</s>

<s docid="SJMN91-06346032" num="13" wdcount="14"> The company says about $630 million was taken from its pension fund without authority.</s>

<s docid="SJMN91-06346032" num="14" wdcount="30"> Kevin Maxwell spoke with the Daily Mirror as he flew to New York on Tuesday for talks on the future of the Daily News, which his father bought in March.</s>

<s docid="SJMN91-06346032" num="15" wdcount="6"> Kevin Maxwell is now the publisher.</s>

<s docid="SJMN91-06346032" num="16" wdcount="38"> In a report today, The Washington Post quoted unidentified sources as saying Robert Maxwell never created the pension fund for Daily News managers he promised to start with funding from Tribune Co., which sold the paper to Maxwell.</s>

<s docid="SJMN91-06346032" num="17" wdcount="10"> Pension money accumulated before the sale wasn't affected, it said.</s>

<s docid="SJMN91-06346032" num="18" wdcount="16"> Revelations of Maxwell's financial manipulations have led to numerous newspaper characterizations of him as a crook.</s>

<s docid="SJMN91-06346032" num="19" wdcount="36"> "I have to say to myself that given the sequence of events and looking at the whole picture, that a lot of it is fair comment," Kevin Maxwell was quoted as saying by the Daily Mirror.</s>

<s docid="SJMN91-06346032" num="20" wdcount="13"> Asked how he thought his father died, he was quoted as saying: "Suicide?</s>

<s docid="SJMN91-06346032" num="21" wdcount="18"> Not the remotest possibility."; Maxwell's body was found in the sea off the Canary Islands on Nov. 5.</s>

<s docid="SJMN91-06346032" num="22" wdcount="7"> He had been cruising on his yacht.</s>

<s docid="SJMN91-06346032" num="23" wdcount="17"> Preliminary findings by Spanish pathologists indicated he could have fallen into the sea after a heart attack.</s>

<s docid="SJMN91-06346032" num="24" wdcount="25"> Kevin Maxwell has been linked to transactions of a pension fund management firm at the center of the controversy over the missing money, investigators say.</s>

<s docid="SJMN91-06346032" num="25" wdcount="33"> He and brother Ian are under court order to disclose by next week what they know about the affairs of Bishopsgate Investment Management Ltd., one of about 40 companies controlled by their father.</s>

<s docid="SJMN91-06346032" num="26" wdcount="27"> In another development, The Financial Times said today that documents show creditors face losses of at least $905 million on loans to Robert Maxwell's private companies .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06346032" num="27" wdcount="2"> Associated Press</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06346032" num="28" wdcount="1"> USA</s>
</COUNTRY>
<CITY>

<s docid="SJMN91-06346032" num="29" wdcount="1"> London</s>
</CITY>
<EDITION>

<s docid="SJMN91-06346032" num="30" wdcount="2"> Stock Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06346032" num="31" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06346032" num="32" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06346032" num="33" wdcount="1"> 911211</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06346032" num="34" wdcount="1"> Wednesday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06346032" num="35" wdcount="1"> December</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06346032" num="36" wdcount="1"> 1D</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06346032" num="37" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06346032" num="38" wdcount="1"> WEST</s>
</REGION>
<STATE>

<s docid="SJMN91-06346032" num="39" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06346032" num="40" wdcount="1"> 466</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06346032" num="41" wdcount="5"> Wednesday, December 11, 1991 00346032,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06346032" num="42" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06346032" num="43" wdcount="1"> 1</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06346032" num="44" wdcount="1"> ENG</s>
</LANGUAGE>
</DOC>
