<DOC>
<DOCNO>

<s docid="SJMN91-06311092" num="1" wdcount="1"> SJMN91-06311092</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06311092" num="2" wdcount="1"> 06311092</s>
</ACCESS>
<CAPTION>

<s docid="SJMN91-06311092" num="3" wdcount="11"> Photo, Map; PHOTO: Maxwell; MAP: Associated Press; Robert Maxwell's body found</s>
</CAPTION>
<DESCRIPT>

<s docid="SJMN91-06311092" num="4" wdcount="7"> MEDIA; PUBLISH; BUSINESS; MAN; DEATH; BOAT; ACCIDENT</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06311092" num="5" wdcount="29"> Robert Maxwell, the flamboyant billionaire who built a global publishing empire, was found dead Tuesday in waters off the Canary Islands, where he had been vacationing on his yacht.</s>

<s docid="SJMN91-06311092" num="6" wdcount="22"> Authorities said Maxwell, 68, who earlier this year had bought the New York Daily News, vanished overnight from the 180-foot Lady Ghislaine.</s>

<s docid="SJMN91-06311092" num="7" wdcount="9"> His unclothed body was found several hours later .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06311092" num="8" wdcount="1"> Front</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06311092" num="9" wdcount="12"> BILLIONAIRE PUBLISHER ROBERT MAXWELL DIES MEDIA MOGUL'S BODY FOUND NEAR CANARY ISLANDS</s>
</HEADLINE>
<TEXT>

<s docid="SJMN91-06311092" num="10" wdcount="30"> Maxwell's death ended the reign of a contentious media baron who battled unions, barked out orders in eight languages and bullied editors as he built a $2 billion media conglomerate.</s>

<s docid="SJMN91-06311092" num="11" wdcount="38"> "He was larger than life . . . the Citizen Kane of his time," said British Conservative Party lawmaker Anthony Beaumont-Dark, referring to Orson Welles' classic movie about a publishing baron, presumed to have been William Randolph Hearst.</s>

<s docid="SJMN91-06311092" num="12" wdcount="29"> "If you wrote a film about his life, it would be rejected as unrealistic."; A labor union leader once said Maxwell "could charm the birds out of the trees.</s>

<s docid="SJMN91-06311092" num="13" wdcount="26"> And then shoot them."; The Czechoslovak-born Maxwell, who escaped the Holocaust and emigrated to Britain in 1940, personally ran his publishing empire, often making minute-to-minute decisions.</s>

<s docid="SJMN91-06311092" num="14" wdcount="13"> Maxwell's sons, Kevin, 32, and Ian, 35, took over running the businesses Tuesday.</s>

<s docid="SJMN91-06311092" num="15" wdcount="22"> "What normal people consider pressure was meat and drink to Robert Maxwell," said Charles Wilson, editorial director of Maxwell's Mirror Group Newspapers.</s>

<s docid="SJMN91-06311092" num="16" wdcount="34"> His death prompted immediate concern in British financial circles about the future of his debt-laden empire and in New York about the future of the Daily News, one of the nation's largest metropolitan papers.</s>

<s docid="SJMN91-06311092" num="17" wdcount="34"> Among Maxwell's assets were the Macmillan publishing house in New York, Britain's No. 2 paper, the Daily Mirror, The Daily Record, and The European and British Printing & Communications Corp., Britain's largest printing company.</s>

<s docid="SJMN91-06311092" num="18" wdcount="29"> On the steps of Mirror Group Newspapers in London, Ian Maxwell told reporters the moment was tragic not only for his family but also for Maxwell's thousands of employees.</s>

<s docid="SJMN91-06311092" num="19" wdcount="47"> "This paper has lost its publisher and its chairman and its savior."; British Prime Minister John Major called Maxwell "a great character who will be missed."; "Maxwell was a passionate friend of Israel, and we are sorry about this heavy tragedy," Israeli Prime Minister Yitzhak Shamir said.</s>

<s docid="SJMN91-06311092" num="20" wdcount="28"> "God bless his memory."; His body was found 20 miles northwest of Grand Canary Island after an extensive air-and-sea search, officials at the rescue center in Madrid said.</s>

<s docid="SJMN91-06311092" num="21" wdcount="32"> The body was taken by helicopter to the Gando air base on Grand Canary Island, where it was identified by Maxwell's wife of more than 40 years, Elizabeth, and their son, Phillip.</s>

<s docid="SJMN91-06311092" num="22" wdcount="15"> An autopsy is planned for today, and the cause of death is officially still unknown.</s>

<s docid="SJMN91-06311092" num="23" wdcount="6"> Details of Maxwell's death are sketchy.</s>

<s docid="SJMN91-06311092" num="24" wdcount="21"> He was last seen alive on the deck of his yacht at 4:45 a.m. EST, Daily News spokesman John Campi said.</s>

<s docid="SJMN91-06311092" num="25" wdcount="19"> At 11 a.m., a business call arrived from New York, and the crew discovered that Maxwell was not aboard.</s>

<s docid="SJMN91-06311092" num="26" wdcount="10"> Campi said Capt. Gus Rankin then radioed a distress call.</s>

<s docid="SJMN91-06311092" num="27" wdcount="7"> The body was found several hours later.</s>

<s docid="SJMN91-06311092" num="28" wdcount="10"> Wilson said there had been no suggestion of foul play.</s>

<s docid="SJMN91-06311092" num="29" wdcount="13"> "We can only assume that Mr. Maxwell slipped and fell overboard," he said.</s>

<s docid="SJMN91-06311092" num="30" wdcount="29"> His mysterious death came as Maxwell was embroiled in an international controversy, something common in a life that had the improbable, extravagant and sometimes mysterious character of British fiction.</s>

<s docid="SJMN91-06311092" num="31" wdcount="21"> Maxwell had just been accused in a book by reporter Seymour Hersh of having close ties to the Israeli secret service.</s>

<s docid="SJMN91-06311092" num="32" wdcount="6"> Maxwell had denied the accusations .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06311092" num="33" wdcount="4"> Mercury News Wire Services</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06311092" num="34" wdcount="1"> USA</s>
</COUNTRY>
<CITY>

<s docid="SJMN91-06311092" num="35" wdcount="3"> Tenerife, Canary Islands</s>
</CITY>
<EDITION>

<s docid="SJMN91-06311092" num="36" wdcount="2"> Morning Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06311092" num="37" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06311092" num="38" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06311092" num="39" wdcount="1"> 911106</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06311092" num="40" wdcount="1"> Wednesday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06311092" num="41" wdcount="1"> November</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06311092" num="42" wdcount="1"> 1A</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06311092" num="43" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06311092" num="44" wdcount="1"> WEST</s>
</REGION>
<FEATURE>

<s docid="SJMN91-06311092" num="45" wdcount="2"> PHOTO; MAP</s>
</FEATURE>
<STATE>

<s docid="SJMN91-06311092" num="46" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06311092" num="47" wdcount="1"> 596</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06311092" num="48" wdcount="5"> Wednesday, November 6, 1991 00311092,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06311092" num="49" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06311092" num="50" wdcount="1"> 1</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06311092" num="51" wdcount="2"> ENG FRONT</s>
</LANGUAGE>
</DOC>
