<DOC>
<DOCNO>

<s docid="WSJ910418-0159" num="1" wdcount="1"> WSJ910418-0159</s>
</DOCNO>
<DOCID>

<s docid="WSJ910418-0159" num="2" wdcount="2"> 910418-0159 .</s>
</DOCID>
<HL>

<s docid="WSJ910418-0159" num="3" wdcount="13"> International: Robert Maxwell Plans To Sell 45% to 49% Of His Mirror Group</s>
</HL>
<DATE>

<s docid="WSJ910418-0159" num="4" wdcount="1"> 04/18/91</s>
</DATE>
<SO>

<s docid="WSJ910418-0159" num="5" wdcount="6"> WALL STREET JOURNAL (J), PAGE A13</s>
</SO>
<CO>

<s docid="WSJ910418-0159" num="6" wdcount="2"> U.MXC WNEWS</s>
</CO>
<MS>

<s docid="WSJ910418-0159" num="7" wdcount="3"> CONSUMER CYCLICAL (CYC)</s>
</MS>
<IN>

<s docid="WSJ910418-0159" num="8" wdcount="11"> MEDIA, PUBLISHING, BROADCASTING, ELECTRONIC PUBLISHING (MED) TENDER OFFERS, MERGERS, ACQUISITIONS (TNM)</s>
</IN>
<NS>

<s docid="WSJ910418-0159" num="9" wdcount="12"> PERSONNEL ANNOUNCEMENTS, PROMOTIONS, APPOINTMENTS (PER) ACQUISITIONS & MERGERS, TAKEOVERS, BOARD BATTLES (TNM)</s>
</NS>
<RE>

<s docid="WSJ910418-0159" num="10" wdcount="3"> GREAT BRITAIN (UK)</s>
</RE>
<LP>

<s docid="WSJ910418-0159" num="11" wdcount="37"> LONDON -- Following his takeover of the unprofitable New York Daily News, British publisher Robert Maxwell plans to raise around #250 million ($448 million) through the sale of shares in his Mirror Group Newspapers Ltd. of Britain.</s>

<s docid="WSJ910418-0159" num="12" wdcount="25"> In a flotation organized by Samuel Montagu & Co., Mirror is to sell 45% to 49% of its shares to investors in Britain and abroad.</s>

<s docid="WSJ910418-0159" num="13" wdcount="6"> Terms will be set April 30.</s>

<s docid="WSJ910418-0159" num="14" wdcount="14"> The offering is expected to value Mirror Group at more than #500 million .</s>
</LP>
<TEXT>

<s docid="WSJ910418-0159" num="15" wdcount="15"> Mirror's flagship publication is the tabloid Daily Mirror, with sales of three million copies daily.</s>

<s docid="WSJ910418-0159" num="16" wdcount="7"> Last month, in another money-raising move, Mr.</s>

<s docid="WSJ910418-0159" num="17" wdcount="13"> Maxwell's Maxwell Communication Corp. sold its Pergamon Press PLC unit for #440 million.</s>

<s docid="WSJ910418-0159" num="18" wdcount="4"> In other changes, Mr.</s>

<s docid="WSJ910418-0159" num="19" wdcount="27"> Maxwell's son Ian, who has been appointed deputy chairman of Mirror Group, will resign from his post at Maxwell Communication, where he was joint deputy managing director.</s>

<s docid="WSJ910418-0159" num="20" wdcount="17"> Maxwell Communication said last month that its management would be taken over by Kevin Maxwell, Ian's brother.</s>

<s docid="WSJ910418-0159" num="21" wdcount="14"> Robert Maxwell bought Mirror Group in 1984 from Reed International PLC for #113 million.</s>

<s docid="WSJ910418-0159" num="22" wdcount="21"> Through staff cuts and heavy spending on printing facilities, Mr. Maxwell built Mirror into one of Britain's most profitable newspaper groups.</s>

<s docid="WSJ910418-0159" num="23" wdcount="18"> In 1990, Mirror had profit of #37.2 million, or 28.2 pence a share, on revenue of #445 million.</s>

<s docid="WSJ910418-0159" num="24" wdcount="16"> Proceeds from the share flotation will be used to strengthen and refinance the group's balance sheet.</s>

<s docid="WSJ910418-0159" num="25" wdcount="27"> About #210 million will be used to pay back bank loans and the rest to pay in full a loan from Robert Maxwell Holdings Ltd. Salomon Bros.</s>

<s docid="WSJ910418-0159" num="26" wdcount="30"> International is underwriting the international part of the offering, covering approximately one-third of the shares on sale, to be privately placed with institutional investors in the U.S., Canada and Europe.</s>

<s docid="WSJ910418-0159" num="27" wdcount="17"> The other two-thirds of the shares are to be divided between private and institutional investors in Britain.</s>

<s docid="WSJ910418-0159" num="28" wdcount="20"> A relatively low minimum-investment figure of #250 has been set to attract small investors, particularly readers of Mirror publications .</s>
</TEXT>
</DOC>
