<DOC>
<DOCNO>

<s docid="AP880916-0025" num="1" wdcount="1"> AP880916-0025</s>
</DOCNO>
<FILEID>

<s docid="AP880916-0025" num="2" wdcount="2"> AP-NR-09-16-88 0030EDT</s>
</FILEID>
<FIRST>

<s docid="AP880916-0025" num="3" wdcount="7"> u a AM-HurricaneGilbert 4thLd-Writethru a0799 09-16 1214</s>
</FIRST>
<SECOND>

<s docid="AP880916-0025" num="4" wdcount="5"> AM-Hurricane Gilbert, 4th Ld-Writethru, a0799,1245</s>
</SECOND>
<HEAD>

<s docid="AP880916-0025" num="5" wdcount="10"> Gulf Coast from Mexico to Louisiana Braces for Hurricane Gilbert</s>
</HEAD>
<HEAD>

<s docid="AP880916-0025" num="6" wdcount="8"> LaserColor MH1, MH3, LaserGraphic NY32, LaserPhotos CLU1, CCI1</s>
</HEAD>
<NOTE>

<s docid="AP880916-0025" num="7" wdcount="23"> Eds: LEADS with 6 grafs to UPDATE with midnight EDT position, latest landfall estimate, edits to conform; SUBS 3rd graf, `The death ...</s>

<s docid="AP880916-0025" num="8" wdcount="6"> and 35th graf, `Seaga said ...</s>

<s docid="AP880916-0025" num="9" wdcount="15"> to CLARIFY that Jamaica declaration is ``public emergency,'' sted ``state of emergency;'' ^By JOEL WILLIAMS</s>
</NOTE>
<BYLINE>

<s docid="AP880916-0025" num="10" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880916-0025" num="11" wdcount="3"> BROWNSVILLE, Texas (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880916-0025" num="12" wdcount="30"> Thousands of coastal residents from Mexico to Louisiana fled to higher ground Thursday as fierce Hurricane Gilbert sent the first of its storms against Texas after thrashing the Yucatan Peninsula.</s>

<s docid="AP880916-0025" num="13" wdcount="17"> ``This is a killer storm,'' said Gordon Guthrie, director of the Florida Division of Emergency of Management.</s>

<s docid="AP880916-0025" num="14" wdcount="8"> ``I feel sorry for anybody wherever this hits''.</s>

<s docid="AP880916-0025" num="15" wdcount="24"> The death toll from the storm's onslaught through the Caribbean islands and the Yucatan was at least 47, and damage estimates reached $8 billion.</s>

<s docid="AP880916-0025" num="16" wdcount="10"> Jamaican Prime Minister Edward Seaga declared a one-month public emergency.</s>

<s docid="AP880916-0025" num="17" wdcount="10"> By late evening, a torrential rain was falling in Brownsville.</s>

<s docid="AP880916-0025" num="18" wdcount="50"> At 11 p.m. CDT, the storm center was near latitude 22.8 north, longitude 94.4 west, or about 275 miles southeast of Brownsville, moving west-northwest between 12 and 15 mph, with maximum sustained winds of 120 mph and accompanied by a 5- to 10-inch rainfall, according to the National Weather Service.</s>

<s docid="AP880916-0025" num="19" wdcount="24"> ``If this motion continues, the center of the hurricane will cross the coast near the Texas-Mexico border on Friday evening,'' the weather service said.</s>

<s docid="AP880916-0025" num="20" wdcount="15"> ``If a northwest turn should occur, the landfall could be further up the Texas coast''.</s>

<s docid="AP880916-0025" num="21" wdcount="29"> The weather service issued a hurricane warning for Mexico's northern coast and the southern half of the 370-mile Texas coast from Brownsville to Port O'Connor, including 250,000-resident Corpus Christi.</s>

<s docid="AP880916-0025" num="22" wdcount="24"> A hurricane watch remained in effect for the remainder of the Texas coast, from Port O'Connor north to Port Arthur near the Louisiana border.</s>

<s docid="AP880916-0025" num="23" wdcount="18"> The weather service said warnings might be extended northward, depending on the path of the 450-mile wide storm.</s>

<s docid="AP880916-0025" num="24" wdcount="28"> Texas Gov. Bill Clements sent National Guard units to Alice, McAllen and Corpus Christi, the first such deployment for the hurricane, to assist in communications and rescue duties.</s>

<s docid="AP880916-0025" num="25" wdcount="32"> Clements also issued an emergency proclamation allowing local authorities to suspend laws ``to preserve the health, safety and welfare of the public,'' including such things as the direction of travel on highways.</s>

<s docid="AP880916-0025" num="26" wdcount="17"> Grocery stores ran low on bottled water, batteries, canned tuna and bread as people laid in supplies.</s>

<s docid="AP880916-0025" num="27" wdcount="11"> Homeowners covered windows and doors with plywood and shatter-proofing hurricane tape.</s>

<s docid="AP880916-0025" num="28" wdcount="11"> Offshore oil workers left their rigs in the Gulf of Mexico.</s>

<s docid="AP880916-0025" num="29" wdcount="17"> On Galveston Island, City Manager Doug Matthews recommended Thursday evening that the city's 62,000 residents start evacuating.</s>

<s docid="AP880916-0025" num="30" wdcount="17"> ``We are dealing with people's lives therefore at 8 o'clock we are recommending evacuation of the island.</s>

<s docid="AP880916-0025" num="31" wdcount="33"> We feel that we cannot wait until the morning to make that decision,'' Matthews said, adding that roadblocks would be set up at midnight on Interstate 45 to limit access to the island.</s>

<s docid="AP880916-0025" num="32" wdcount="15"> In Brownsville, Texas' southernmost city, winds began to pick up around noon under overcast skies.</s>

<s docid="AP880916-0025" num="33" wdcount="14"> Police said they were asking residents to consider evacuating, but were not ordering it.</s>

<s docid="AP880916-0025" num="34" wdcount="21"> ``We've never evacuated the city and the point is, where are you going to move 100,000 people''? said Sgt. Dean Poos.</s>

<s docid="AP880916-0025" num="35" wdcount="20"> A Greyhound-Trailways bus spokesman said the company was doubling its schedule of outbound buses to accommodate those fleeing the storm.</s>

<s docid="AP880916-0025" num="36" wdcount="17"> Lorena Curry, who has lived in Brownsville since 1935, said she plans to ride out the storm.</s>

<s docid="AP880916-0025" num="37" wdcount="5"> ``I've been through them before.</s>

<s docid="AP880916-0025" num="38" wdcount="8"> I'm going to stick around at my home''.</s>

<s docid="AP880916-0025" num="39" wdcount="12"> But she added, ``I could get along without a hurricane very well''.</s>

<s docid="AP880916-0025" num="40" wdcount="22"> Gilbert surged into the gulf after battering the Yucatan Peninsula in Mexico with 160 mph winds, forcing tens of thousands to flee.</s>

<s docid="AP880916-0025" num="41" wdcount="24"> After crossing the peninsula, Gilbert's winds weakened to 120 mph, but forecasters predicted the storm would intensify again as it moves over open water.</s>

<s docid="AP880916-0025" num="42" wdcount="38"> ``The shower and thunderstorm activity that we see taking place around the hurricane itself is getting better organized, more vigorous, so we think it's starting to strengthen,'' said Bob Sheets, director of the National Hurricane Center in Miami.</s>

<s docid="AP880916-0025" num="43" wdcount="15"> Sheets said the hurricane's sustained winds would ``certainly increase to 130, 140 miles per hour''.</s>

<s docid="AP880916-0025" num="44" wdcount="22"> In the coastal resort of South Padre Island, about 25 miles southeast of Brownsville, the mayor ordered its 1,000 residents to evacuate.</s>

<s docid="AP880916-0025" num="45" wdcount="30"> ``We can't force them to leave, but it doesn't make any sense to stay,'' said Mayor Bob Pinkerton Jr., adding that water and electricity would be turned off Thursday afternoon.</s>

<s docid="AP880916-0025" num="46" wdcount="26"> Tropical storm force winds, at least 39 mph, extended outward up to 250 miles to the north and 200 miles to the south of the center.</s>

<s docid="AP880916-0025" num="47" wdcount="28"> The storm's first landfall earlier this week left at least 26 people dead in Jamaica, five in the Dominican Republic, 10 in Haiti and the six in Mexico.</s>

<s docid="AP880916-0025" num="48" wdcount="17"> It also left a half-million people homeless in Jamaica and caused widespread damage to the Cayman Islands.</s>

<s docid="AP880916-0025" num="49" wdcount="27"> The storm barreled into the Yucatan coast at dawn Wednesday, thrashing beaches with 23-foot waves, uprooting trees, knocking out electricity and water supplies and severing telephone lines.</s>

<s docid="AP880916-0025" num="50" wdcount="27"> In Campeche, the state capital on the peninusula's west coast, boats and seaweed littered the streets of hundreds of yards from the shore after Gilbert passed through.</s>

<s docid="AP880916-0025" num="51" wdcount="5"> ``The whole city is flooded.</s>

<s docid="AP880916-0025" num="52" wdcount="14"> Everything is dark,'' said Ramon Castillo, a watchman at the newspaper Novedades de Campeche.</s>

<s docid="AP880916-0025" num="53" wdcount="15"> ``I've lived here all my life and I have never seen bad weather like this.</s>

<s docid="AP880916-0025" num="54" wdcount="3"> People are scared''.</s>

<s docid="AP880916-0025" num="55" wdcount="26"> Mexican officials reported six deaths, including two babies who drowned, and at least seven people were injured, but authorities were unable to reach many isolated villages.</s>

<s docid="AP880916-0025" num="56" wdcount="35"> Gilbert pounded the provincial capital of Merida and the gulf port cities of Puerto Progreso, Campeche and Ciudad del Carmen, closing airports and roads and knocking out communications and power and flooding streets and highways.</s>

<s docid="AP880916-0025" num="57" wdcount="25"> About 20,000 people were evacuated from Puerto Progreso and other coastal towns, a spokesman for the Interior Ministry in Mexico City said by telephone Thursday.</s>

<s docid="AP880916-0025" num="58" wdcount="7"> Hundreds of homes were destroyed, he said.</s>

<s docid="AP880916-0025" num="59" wdcount="26"> On Mexico's northern coast, people were evacuated from fishing villages and towns into shelters in Matamoros, a city of 400,000 about 12 miles inland near Brownsville.</s>

<s docid="AP880916-0025" num="60" wdcount="41"> The hurricane center said Gilbert at one point was the most intense storm on record in terms of barometric pressure, which was measured Tuesday at 26.13 inches, breaking the 26.35 inches recorded for the 1935 hurricane that devastated the Florida Keys.</s>

<s docid="AP880916-0025" num="61" wdcount="15"> The storm, spawned Saturday southeast of Puerto Rico, appeared to have hit Jamaica the hardest.</s>

<s docid="AP880916-0025" num="62" wdcount="10"> Seaga said it destroyed about 100,000 of Jamaica's 500,000 homes.</s>

<s docid="AP880916-0025" num="63" wdcount="6"> He estimated damage at $8 billion.</s>

<s docid="AP880916-0025" num="64" wdcount="44"> Seaga said in a nationwide radio broadcast Thursday that the one-month ``period of public emergency,'' including a dawn-to-dusk curfew to prevent looting, was put into effect ``to enable normalcy to resume in the shortest possible time and to allow the rebuilding process to begin''.</s>

<s docid="AP880916-0025" num="65" wdcount="17"> On Wednesday, Gilbert was classified as a Category 5 storm, the strongest and deadliest type of hurricane.</s>

<s docid="AP880916-0025" num="66" wdcount="15"> Such storms have maximum sustained winds greater than 155 mph and can cause catastrophic damage.</s>

<s docid="AP880916-0025" num="67" wdcount="22"> By Wednesday night, the National Hurricane Center downgraded it to a Category 4 and to a Category 3 by Thursday morning .</s>
</TEXT>
</DOC>
