<DOC>
<DOCNO>

<s docid="AP880911-0016" num="1" wdcount="1"> AP880911-0016</s>
</DOCNO>
<FILEID>

<s docid="AP880911-0016" num="2" wdcount="2"> AP-NR-09-11-88 0423EDT</s>
</FILEID>
<FIRST>

<s docid="AP880911-0016" num="3" wdcount="5"> r i BC-HurricaneGilbert 09-11 0339</s>
</FIRST>
<SECOND>

<s docid="AP880911-0016" num="4" wdcount="2"> BC-Hurricane Gilbert,0348</s>
</SECOND>
<HEAD>

<s docid="AP880911-0016" num="5" wdcount="6"> Hurricane Gilbert Heads Toward Dominican Coast</s>
</HEAD>
<BYLINE>

<s docid="AP880911-0016" num="6" wdcount="3"> By RUDDY GONZALEZ</s>
</BYLINE>
<BYLINE>

<s docid="AP880911-0016" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880911-0016" num="8" wdcount="5"> SANTO DOMINGO, Dominican Republic (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880911-0016" num="9" wdcount="28"> Hurricane Gilbert swept toward the Dominican Republic Sunday, and the Civil Defense alerted its heavily populated south coast to prepare for high winds, heavy rains and high seas.</s>

<s docid="AP880911-0016" num="10" wdcount="17"> The storm was approaching from the southeast with sustained winds of 75 mph gusting to 92 mph.</s>

<s docid="AP880911-0016" num="11" wdcount="20"> ``There is no need for alarm,'' Civil Defense Director Eugenio Cabral said in a television alert shortly before midnight Saturday.</s>

<s docid="AP880911-0016" num="12" wdcount="13"> Cabral said residents of the province of Barahona should closely follow Gilbert's movement.</s>

<s docid="AP880911-0016" num="13" wdcount="22"> An estimated 100,000 people live in the province, including 70,000 in the city of Barahona, about 125 miles west of Santo Domingo.</s>

<s docid="AP880911-0016" num="14" wdcount="15"> Tropical Storm Gilbert formed in the eastern Caribbean and strengthened into a hurricane Saturday night.</s>

<s docid="AP880911-0016" num="15" wdcount="35"> The National Hurricane Center in Miami reported its position at 2 a.m. Sunday at latitude 16.1 north, longitude 67.5 west, about 140 miles south of Ponce, Puerto Rico, and 200 miles southeast of Santo Domingo.</s>

<s docid="AP880911-0016" num="16" wdcount="33"> The National Weather Service in San Juan, Puerto Rico, said Gilbert was moving westward at 15 mph with a ``broad area of cloudiness and heavy weather'' rotating around the center of the storm.</s>

<s docid="AP880911-0016" num="17" wdcount="21"> The weather service issued a flash flood watch for Puerto Rico and the Virgin Islands until at least 6 p.m. Sunday.</s>

<s docid="AP880911-0016" num="18" wdcount="23"> Strong winds associated with the Gilbert brought coastal flooding, strong southeast winds and up to 12 feet feet to Puerto Rico's south coast.</s>

<s docid="AP880911-0016" num="19" wdcount="6"> There were no reports of casualties.</s>

<s docid="AP880911-0016" num="20" wdcount="18"> San Juan, on the north coast, had heavy rains and gusts Saturday, but they subsided during the night.</s>

<s docid="AP880911-0016" num="21" wdcount="20"> On Saturday, Hurricane Florence was downgraded to a tropical storm and its remnants pushed inland from the U.S. Gulf Coast.</s>

<s docid="AP880911-0016" num="22" wdcount="16"> Residents returned home, happy to find little damage from 80 mph winds and sheets of rain.</s>

<s docid="AP880911-0016" num="23" wdcount="15"> Florence, the sixth named storm of the 1988 Atlantic storm season, was the second hurricane.</s>

<s docid="AP880911-0016" num="24" wdcount="16"> The first, Debby, reached minimal hurricane strength briefly before hitting the Mexican coast last month .</s>
</TEXT>
</DOC>
