<DOC>
<DOCNO>

<s docid="AP880914-0004" num="1" wdcount="1"> AP880914-0004</s>
</DOCNO>
<FILEID>

<s docid="AP880914-0004" num="2" wdcount="2"> AP-NR-09-14-88 0001EDT</s>
</FILEID>
<FIRST>

<s docid="AP880914-0004" num="3" wdcount="7"> u i AM-HurricaneGilbert 4thLd-Writethru a0839 09-14 1054</s>
</FIRST>
<SECOND>

<s docid="AP880914-0004" num="4" wdcount="5"> AM-Hurricane Gilbert, 4th Ld-Writethru, a0839,1082</s>
</SECOND>
<HEAD>

<s docid="AP880914-0004" num="5" wdcount="9"> Killer Hurricane Roars Toward Mexico With 175 mph Winds</s>
</HEAD>
<NOTE>

<s docid="AP880914-0004" num="6" wdcount="19"> Eds: LEADS with 15 grafs to UPDATE with report from Jamaica of six dead, 60,000 homeless; storm midnight advisory.</s>

<s docid="AP880914-0004" num="7" wdcount="8"> PICKS up 14th pvs `The center said '...</s>

<s docid="AP880914-0004" num="8" wdcount="20"> SUBS 20th pvs `Gene Graves '... with 1 graf to CORRECT that helicopters working to evacuate 10,000 in gulf .</s>
</NOTE>
<BYLINE>

<s docid="AP880914-0004" num="9" wdcount="4"> By The Associated Press</s>
</BYLINE>
<TEXT>

<s docid="AP880914-0004" num="10" wdcount="34"> Gilbert, an ``extremely dangerous hurricane'' and one of the strongest storms in history, roared toward Mexico's Yucatan Peninsula Tuesday with 175 mph winds after battering the Dominican Republic, Jamaica and the tiny Cayman Islands.</s>

<s docid="AP880914-0004" num="11" wdcount="16"> The hurricane killed at least five people Sunday in the Dominican Republic, civil defense officials said.</s>

<s docid="AP880914-0004" num="12" wdcount="15"> Six people died and 60,000 were left homeless in Jamaica on Monday, officials there said.</s>

<s docid="AP880914-0004" num="13" wdcount="20"> Prime Minister Edward Seaga said the hurricane swept the full length of Jamaica, ``leaving a trail of wreckage behind it''.</s>

<s docid="AP880914-0004" num="14" wdcount="21"> ``It will take us some time before we can assess the full damage without any doubt,'' Seaga said in a statement.</s>

<s docid="AP880914-0004" num="15" wdcount="21"> ``But I have no doubt that this going to be the worst disaster that we have experienced in our modern history''.</s>

<s docid="AP880914-0004" num="16" wdcount="23"> Communications were down with many storm-ravaged areas and the death toll was expected to rise with the arrival of damage and casualty reports.</s>

<s docid="AP880914-0004" num="17" wdcount="22"> The hurricane, traveling westward across the Caribbean Sea, was upgraded Tuesday to a Category 5, the strongest and deadliest type of hurricane.</s>

<s docid="AP880914-0004" num="18" wdcount="15"> Such storms have maximum sustained winds greater than 155 mph and can cause catastrophic damage.</s>

<s docid="AP880914-0004" num="19" wdcount="19"> Bob Sheets, director of the National Hurricane Center in Coral Gables, Fla., described Gilbert as ``a great hurricane ...</s>

<s docid="AP880914-0004" num="20" wdcount="14"> in the top 10 percent (historically) as far as intensity, size and destructive potential''.</s>

<s docid="AP880914-0004" num="21" wdcount="34"> Only two Category 5 hurricanes have hit the United States _ a 1935 storm that killed 408 people in Florida, and Hurricane Camille, which devastated the Mississippi coast in 1969 and killed 256 people.</s>

<s docid="AP880914-0004" num="22" wdcount="24"> ``The people who need to be concerned now are those people over on the Yucatan Peninsula _ Cancun, Cozumel, that whole area,'' Sheets said.</s>

<s docid="AP880914-0004" num="23" wdcount="17"> Mexico's news media reported beachfront hotels were evacuated in the Yucatan resorts of Cancun and Cozumel Island.</s>

<s docid="AP880914-0004" num="24" wdcount="29"> They gave no figures on the numer of evacuees, but said people in Cancun were being sent from the hotel zone into the city center, about 6 miles away.</s>

<s docid="AP880914-0004" num="25" wdcount="23"> Cozumel is south of Cancun and the reports said hotel guests also were being moved to more secure areas away from the shoreline.</s>

<s docid="AP880914-0004" num="26" wdcount="13"> Mexican officials expected the storm to hit in the early morning hours Wednesday.</s>

<s docid="AP880914-0004" num="27" wdcount="5"> At midnight EDT the U.S.</s>

<s docid="AP880914-0004" num="28" wdcount="21"> National Weather Service said Gilbert was centered near latitude 19.9 north, longitude 84.8 west, or about 150 miles east-southeast of Cozumel.</s>

<s docid="AP880914-0004" num="29" wdcount="17"> It said Gilbert was moving west-northwest at about 15 mph with maximum sustained winds of 175 mph.</s>

<s docid="AP880914-0004" num="30" wdcount="24"> The center said tropical storm-force winds extend outward up to 250 miles to the north and 200 miles to the south of the center.</s>

<s docid="AP880914-0004" num="31" wdcount="18"> ``People in the warned areas should have completed all possible preparations for this extremely dangerous hurricane,'' it said.</s>

<s docid="AP880914-0004" num="32" wdcount="17"> The center said Hurricane Gilbert was the most intense storm on record in terms of barometric pressure.</s>

<s docid="AP880914-0004" num="33" wdcount="26"> It said by 8 p.m. EDT it was measured at 26.13 inches, breaking the 26.35 inches recorded for the 1935 hurricane that devastated the Florida Keys.</s>

<s docid="AP880914-0004" num="34" wdcount="14"> ``That's the lowest pressure ever measured in the Western Hemisphere,'' said forecaster Mark Zimmer.</s>

<s docid="AP880914-0004" num="35" wdcount="25"> ``There is very serious flooding'' in the Cayman Islands, Erina Nichols, a tourism official in Miami, said Tuesday after speaking with residents of the islands.</s>

<s docid="AP880914-0004" num="36" wdcount="9"> ``The Run Point (community) is taking a real beating''.</s>

<s docid="AP880914-0004" num="37" wdcount="23"> The storm later knocked out all telephone service to the Cayman Islands, a British dependency of 23,000 people that was expecting 12-foot tides.</s>

<s docid="AP880914-0004" num="38" wdcount="26"> Warren Chase, an amateur radio operator in Fort Myers, Fla., said he received a report of sailboat with seven people aboard missing near the Cayman Islands.</s>

<s docid="AP880914-0004" num="39" wdcount="19"> Oil companies evacuated thousands of workers from rigs in the Gulf of Mexico, according to reports from New Orleans.</s>

<s docid="AP880914-0004" num="40" wdcount="32"> Gene Graves, marketing director for Petroleum Helicopters Inc. in Lafayette, La., said his company's 18 helipads were working at full capacity to evacuate about 10,000 oil rigs in the Gulf of Mexico.</s>

<s docid="AP880914-0004" num="41" wdcount="37"> The Cuban news agency Prensa Latina said 40,000 people, many of them foreign vacationers and students, were evacuated Tuesday from the Isle of Youth off the southwestern coast as the hurricane passed 200 miles to the south.</s>

<s docid="AP880914-0004" num="42" wdcount="31"> In New York City, a ham radio operator who was monitoring amateur radio communications in Jamaica said Tuesday, ``Kingston is devastated, Montego Bay is hit hard and Ocho Rios is flooded.</s>

<s docid="AP880914-0004" num="43" wdcount="22"> The operator, Norm Chwat, an officer with the American Red Cross Radio Club, said therth coast had been wrecked by the hurricane.</s>

<s docid="AP880914-0004" num="44" wdcount="28"> Herb Schoenbaum, a radio ham operator in the Virgin Islands, said he spoke Tuesday with Dave Porter, an American staying in the Wyndham Hotel on Jamaica's Montego Bay.</s>

<s docid="AP880914-0004" num="45" wdcount="21"> ``Porter reported that the hotel `peeled apart like a banana' when the force of Hurricane Gilbert hit last night,'' Schoenbaum said.</s>

<s docid="AP880914-0004" num="46" wdcount="9"> ``This morning he says there is just nothing left.</s>

<s docid="AP880914-0004" num="47" wdcount="32"> Boats that were on the beach, the little rental Sailfishes or Sunfishes, were driven into cars like spears _ power lines down, almost every tree in the area is on the ground''.</s>

<s docid="AP880914-0004" num="48" wdcount="29"> Schoenbaum said Porter told him people who were trying to enter the hotel on their hands and knees at the height of the storm were swept into the ocean.</s>

<s docid="AP880914-0004" num="49" wdcount="33"> Glenn Baxter of Belgrade Lakes, Me., said he spoke with a ham operator in Jamaica who told him the roof of a hospital in Mandeville ripped off ``and the hospital has caved in.</s>

<s docid="AP880914-0004" num="50" wdcount="24"> And that is the worst horror show that I've heard about because that would imply that a lot of people could have been hurt''.</s>

<s docid="AP880914-0004" num="51" wdcount="19"> The Jamaican consulate in Miami said today it had n immediate information on the extent of damages or casualties.</s>

<s docid="AP880914-0004" num="52" wdcount="14"> Jamaica was still out of contact with the rest of the world by telephone.</s>

<s docid="AP880914-0004" num="53" wdcount="20"> Roger Myers, southern regional spokesman for the Federal Aviation Administration in Atlanta, said both international airports in Jamaica are closed.</s>

<s docid="AP880914-0004" num="54" wdcount="22"> ``We've been told the government has asked commercial radio stations to remain silent so Radio Jamaica can broadcast information,'' Myers said .</s>
</TEXT>
</DOC>
