<DOC>
<DOCNO>

<s docid="AP880914-0131" num="1" wdcount="1"> AP880914-0131</s>
</DOCNO>
<FILEID>

<s docid="AP880914-0131" num="2" wdcount="2"> AP-NR-09-14-88 1343EDT</s>
</FILEID>
<FIRST>

<s docid="AP880914-0131" num="3" wdcount="7"> u i PM-HurricaneGilbert 9thLd-Writethru a0635 09-14 0807</s>
</FIRST>
<SECOND>

<s docid="AP880914-0131" num="4" wdcount="5"> PM-Hurricane Gilbert, 9th Ld-Writethru, a0635,0827</s>
</SECOND>
<HEAD>

<s docid="AP880914-0131" num="5" wdcount="5"> Gilbert Slams Into Yucatan Peninsula</s>
</HEAD>
<NOTE>

<s docid="AP880914-0131" num="6" wdcount="19"> Eds: Leads with 13 grafs to UPDATE with winds at 160 mph, latest position on storm, may reach U.S.</s>

<s docid="AP880914-0131" num="7" wdcount="8"> Pickup 13th graf pvs, ``Gilbert pounded''... TRIMS .</s>
</NOTE>
<BYLINE>

<s docid="AP880914-0131" num="8" wdcount="3"> By CHRIS ANGELO</s>
</BYLINE>
<BYLINE>

<s docid="AP880914-0131" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880914-0131" num="10" wdcount="3"> CANCUN, Mexico (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880914-0131" num="11" wdcount="17"> Hurricane Gilbert battered the resorts of the Yucatan Peninsula today with 160 mph winds and torrential rains.</s>

<s docid="AP880914-0131" num="12" wdcount="9"> Thousands of people fled coastal areas for shelters inland.</s>

<s docid="AP880914-0131" num="13" wdcount="22"> ``The wind was blowing out windows everywhere'' in Cancun, an official said of the resort where thousands of Americans vacation each year.</s>

<s docid="AP880914-0131" num="14" wdcount="20"> Residents along the gulf coast of Texas, 560 miles to the north, stockpiled food and supplies and prepared to evacuate.</s>

<s docid="AP880914-0131" num="15" wdcount="28"> Robert Sheets, director of the National Hurricane Center in Florida, said early today he expects Gilbert to make landfall on the Texas-Louisiana coast in 48 to 60 hours.</s>

<s docid="AP880914-0131" num="16" wdcount="13"> The hurricane, one of the strongest in history, is ``extremely dangerous,'' the U.S.</s>

<s docid="AP880914-0131" num="17" wdcount="4"> National Weather Service said.</s>

<s docid="AP880914-0131" num="18" wdcount="19"> The storm's winds reached 175 mph earlier today, but later fell slightly to 160 mph, the weather service said.</s>

<s docid="AP880914-0131" num="19" wdcount="19"> Oil companies evacuated thousands of workers from rigs in the Gulf of Mexico, according to reports from New Orleans.</s>

<s docid="AP880914-0131" num="20" wdcount="33"> Gilbert, which has killed at least 11 people, moved over the island of Cozumel at 10 a.m. EDT, said Jose Pereira, a spokesman for the governor's office in Merida, capital of Yucatan state.</s>

<s docid="AP880914-0131" num="21" wdcount="24"> Pereira, who spoke by telephone from Mexico City, said heavy rain was falling over the peninsula and communications with Cancun and Cozumel were out.</s>

<s docid="AP880914-0131" num="22" wdcount="7"> Cancun is 240 miles east of Medira.</s>

<s docid="AP880914-0131" num="23" wdcount="8"> Cozumel is 12 miles off the Yucatan coast.</s>

<s docid="AP880914-0131" num="24" wdcount="25"> Military and civilian teams evacuated more than 16,000 people from coastal areas on the upper Yucatan coast between Puerto Progreso to Rio Lagartos, Pereira said.</s>

<s docid="AP880914-0131" num="25" wdcount="9"> Most are in shelters in inland towns, he said.</s>

<s docid="AP880914-0131" num="26" wdcount="10"> ``Many people were reluctant to leave their homes,'' Pereira said.</s>

<s docid="AP880914-0131" num="27" wdcount="11"> ``They had to be convinced of the seriousness of the threat''.</s>

<s docid="AP880914-0131" num="28" wdcount="18"> Officials in Merida last spoke with people in Cancun early today before the center of the storm hit.</s>

<s docid="AP880914-0131" num="29" wdcount="5"> ``Electricity is down,'' he said.</s>

<s docid="AP880914-0131" num="30" wdcount="17"> ``We talked to them early in the morning and they said it was impressive _ all dark.</s>

<s docid="AP880914-0131" num="31" wdcount="4"> The people were afraid.</s>

<s docid="AP880914-0131" num="32" wdcount="7"> The wind was blowing out windows everywhere''.</s>

<s docid="AP880914-0131" num="33" wdcount="23"> Heavy rains began in Merida about 6 a.m. EDT, and the storm was expected to dump 5 to 10 inches on the area.</s>

<s docid="AP880914-0131" num="34" wdcount="19"> The National Weather Service in Miami said the eye of the storm was over northeast Yucatan at noon EDT.</s>

<s docid="AP880914-0131" num="35" wdcount="22"> The center of the storm was located near latitude 20.7 north and longitude 87.3 west, or about 150 miles east of Merida.</s>

<s docid="AP880914-0131" num="36" wdcount="26"> The hurricane was moving toward the west northwest at 15 mph. Gilbert pounded the Dominican Republic, Jamaica and the low-lying Cayman Islands Sunday, Monday and Tuesday.</s>

<s docid="AP880914-0131" num="37" wdcount="16"> At least 11 people were reported killed, and at least 60,000 were left homeless in Jamaica.</s>

<s docid="AP880914-0131" num="38" wdcount="13"> Rescue teams worked desperately to restore utilities and communications in the shattered areas.</s>

<s docid="AP880914-0131" num="39" wdcount="32"> In a telephone call early today, receptionist Pablo Torres of the Carrillos Hotel in Cancun said about 150 people, most of them tourists, were crowded in the lobby on sofas and chairs.</s>

<s docid="AP880914-0131" num="40" wdcount="17"> ``We are full, and there is not one tourist now in the beach hotel zone,'' he said.</s>

<s docid="AP880914-0131" num="41" wdcount="8"> ``The sound of the wind outside is horrible.</s>

<s docid="AP880914-0131" num="42" wdcount="8"> You couldn't leave even if you wanted to''.</s>

<s docid="AP880914-0131" num="43" wdcount="18"> He said the winds felled utility poles and trees and that sheets of rain were hitting the city.</s>

<s docid="AP880914-0131" num="44" wdcount="7"> Jennie Valdez, a representative of the U.S.</s>

<s docid="AP880914-0131" num="45" wdcount="23"> Consul, said she did not know how many tourists were in Cancun, but that government figures estimate between 40,000 and 65,000 a month.</s>

<s docid="AP880914-0131" num="46" wdcount="9"> Cancun has a population of about 100,000, she said.</s>

<s docid="AP880914-0131" num="47" wdcount="25"> High winds also were reported in Valladolid, a city of 80,000 located 80 miles southwest of Cancun, said Jose Joaquin Martil, local Red Cross president.</s>

<s docid="AP880914-0131" num="48" wdcount="33"> Jamaican Prime Minister Edward Seaga said late Tuesday that at least six people were killed, and an estimated 60,000 were left homeless in ``the worst natural disaster in the modern history of Jamaica''.</s>

<s docid="AP880914-0131" num="49" wdcount="18"> Civil defense officials in the Dominican Republic, sideswiped Sunday by the storm, reported five people were known dead.</s>

<s docid="AP880914-0131" num="50" wdcount="17"> The hurricane center said Gilbert was the most intense storm on record in terms of barometric pressure.</s>

<s docid="AP880914-0131" num="51" wdcount="20"> It was measured at 26.31 inches, breaking the 26.35 inches recorded for the 1935 hurricane that devastated the Florida Keys.</s>

<s docid="AP880914-0131" num="52" wdcount="14"> ``That's the lowest pressure ever measured in the Western Hemisphere,'' said forecaster Mark Zimmer.</s>

<s docid="AP880914-0131" num="53" wdcount="13"> Gilbert is a Category 5 storm, the strongest and deadliest type of hurricane.</s>

<s docid="AP880914-0131" num="54" wdcount="15"> Such storms have maximum sustained winds greater than 155 mph and can cause catastrophic damage.</s>

<s docid="AP880914-0131" num="55" wdcount="35"> Only two Category 5 hurricanes have hit the United States _ the 1935 storm that killed 408 people in Florida and Hurricane Camille that devastated the Mississippi coast in 1969 and killed 256 people .</s>
</TEXT>
</DOC>
