<DOC>
<DOCNO>

<s docid="AP880914-0027" num="1" wdcount="1"> AP880914-0027</s>
</DOCNO>
<FILEID>

<s docid="AP880914-0027" num="2" wdcount="2"> AP-NR-09-14-88 0239EDT</s>
</FILEID>
<FIRST>

<s docid="AP880914-0027" num="3" wdcount="5"> r a PM-HurricaneFacts 09-14 0488</s>
</FIRST>
<SECOND>

<s docid="AP880914-0027" num="4" wdcount="2"> PM-Hurricane Facts,0499</s>
</SECOND>
<HEAD>

<s docid="AP880914-0027" num="5" wdcount="7"> Gilbert: Third Force 5 Hurricane This Century</s>
</HEAD>
<BYLINE>

<s docid="AP880914-0027" num="6" wdcount="3"> By MICHAEL WARREN</s>
</BYLINE>
<BYLINE>

<s docid="AP880914-0027" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880914-0027" num="8" wdcount="2"> MIAMI (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880914-0027" num="9" wdcount="27"> With the winds of Hurricane Gilbert clocked at 175 miles per hour, U.S. weather officials called Gilbert the most intense hurricane ever recorded in the Western Hemisphere.</s>

<s docid="AP880914-0027" num="10" wdcount="31"> Mark Zimmer, a meterologist at the National Hurricane Center, reported an Air Force reconnaissance plane measured the barometric pressure at Gilbert's center at 26.13 inches at 5:52 p.m. EDT on Tuesday.</s>

<s docid="AP880914-0027" num="11" wdcount="7"> Gilbert was barreling toward Mexico's Yucatan Peninsula.</s>

<s docid="AP880914-0027" num="12" wdcount="12"> ``That's the lowest pressure ever measured in the Western Hemisphere,'' Zimmer said.</s>

<s docid="AP880914-0027" num="13" wdcount="31"> The previous record low pressure of 26.35 inches was set by the 1935 Labor Day hurricane that struck the Florida Keys with winds above 150 mph, killing 408 people, he said.</s>

<s docid="AP880914-0027" num="14" wdcount="24"> With tropical storm force winds extending 250 miles north and 200 miles south of the hurricane's center, Gilbert also was one of the largest.</s>

<s docid="AP880914-0027" num="15" wdcount="26"> But because the circumference of a hurricane changes so often during its course, no records are kept on their overall size, said center meterologist Jesse Moore.</s>

<s docid="AP880914-0027" num="16" wdcount="25"> Hurricane Debby, which barely crossed the 74 mph threshold to hurricane strength before striking Mexico last month, was probably about half that size, Moore said.</s>

<s docid="AP880914-0027" num="17" wdcount="19"> Gilbert is one of only three Category 5 storms in the hemisphere since weather officials began keeping detailed records.</s>

<s docid="AP880914-0027" num="18" wdcount="34"> The others were the 1935 Labor Day hurricane and Hurricane Camille, which bulldozed the Mississippi Coast with 172 mph winds and a 28-foot wave in 1969, leaving $1.4 billion in damage and 256 dead.</s>

<s docid="AP880914-0027" num="19" wdcount="14"> A 1900 hurricane is responsible for the worst natural disaster in U.S. history, however.</s>

<s docid="AP880914-0027" num="20" wdcount="13"> That storm hit Galveston, Texas, Sept. 8 and killed more than 6,000 people.</s>

<s docid="AP880914-0027" num="21" wdcount="24"> Category 5 storms have winds greater than 155 mph, barometric pressure of less than 27.17 inches and a storm surge higher than 18 feet.</s>

<s docid="AP880914-0027" num="22" wdcount="32"> The storm surge _ a great dome of water that follows the eye of the hurricane across coastlines, bulldozing everything in its path _ accounts for nine out of 10 hurricane fatalities.</s>

<s docid="AP880914-0027" num="23" wdcount="23"> Camille's storm surge was 25 feet high, but the hurricane center was forecasting a surge of only 8-12 feet for Gilbert, Zimmer said.</s>

<s docid="AP880914-0027" num="24" wdcount="29"> The damage from these worst-case hurricanes is catastrophic _ shrubs and trees blown down, all street signs gone, roofs and windows blown away and shattered, and mobile homes destroyed.</s>

<s docid="AP880914-0027" num="25" wdcount="10"> ``Moisture and heat are what drives the hurricane,'' Zimmer said.</s>

<s docid="AP880914-0027" num="26" wdcount="14"> ``The engine itself is this tall chimney of warm, moist air in the center.</s>

<s docid="AP880914-0027" num="27" wdcount="26"> If the atmospheric conditions in general allow this warm chimney to build to very high levels, 10-12 miles high, then you can have a severe hurricane''.</s>

<s docid="AP880914-0027" num="28" wdcount="23"> Category 4 storms cause extreme damage with winds from 131 to 155 mph, surge of 13-18 feet and pressure of 27.17 to 27.90.</s>

<s docid="AP880914-0027" num="29" wdcount="25"> The weakest hurricanes, Category 1, cause minimal damage with winds of 74 to 95 mph, 4-5 foot surge and pressure at 28.94 or more .</s>
</TEXT>
</DOC>
