<DOC>
<DOCNO>

<s docid="AP880917-0096" num="1" wdcount="1"> AP880917-0096</s>
</DOCNO>
<FILEID>

<s docid="AP880917-0096" num="2" wdcount="2"> AP-NR-09-17-88 1200EDT</s>
</FILEID>
<FIRST>

<s docid="AP880917-0096" num="3" wdcount="7"> u i PM-Hurricane-Mexico 4thLd-Writethru a0562 09-17 0764</s>
</FIRST>
<SECOND>

<s docid="AP880917-0096" num="4" wdcount="4"> PM-Hurricane-Mexico, 4th Ld-Writethru, a0562,0785</s>
</SECOND>
<HEAD>

<s docid="AP880917-0096" num="5" wdcount="10"> Floods From Hurricane Kill 10 Police In Monterrey, Overturn Buses</s>
</HEAD>
<NOTE>

<s docid="AP880917-0096" num="6" wdcount="18"> Eds: Subs 1 graf for 10th graf pvs, ``Heavy rains''... to UPDATE with overall death toll from hurricane.</s>

<s docid="AP880917-0096" num="7" wdcount="6"> Pickup 11th graf pvs, ``In Matamoros...''</s>
</NOTE>
<HEAD>

<s docid="AP880917-0096" num="8" wdcount="3"> LaserPhotos HRX2, HRX7</s>
</HEAD>
<HEAD>

<s docid="AP880917-0096" num="9" wdcount="4"> With PM-Hurricane Gilbert, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP880917-0096" num="10" wdcount="3"> By CAM ROSSIE</s>
</BYLINE>
<BYLINE>

<s docid="AP880917-0096" num="11" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880917-0096" num="12" wdcount="3"> MATAMOROS, Mexico (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880917-0096" num="13" wdcount="32"> Rains from Hurricane Gilbert sent a river raging over its banks in Monterrey, sweeping at least 10 policemen to their deaths and overturning buses loaded with evacuees from Matamoros, police said today.</s>

<s docid="AP880917-0096" num="14" wdcount="25"> The flooding occurred in Monterrey, an industrial city of 3 million people, located 110 miles from the Texas border and 140 miles inland from Matamoros.</s>

<s docid="AP880917-0096" num="15" wdcount="20"> At least 10 police officers were swept away while on a rescue mission around midnight, a judicial police officer said.</s>

<s docid="AP880917-0096" num="16" wdcount="15"> Several buses loaded with evacuees overturned in the raging water and more were feared drowned.</s>

<s docid="AP880917-0096" num="17" wdcount="20"> The officer, who spoke on condition of anonymity, said early today it had been raining for more than 24 hours.</s>

<s docid="AP880917-0096" num="18" wdcount="26"> A trailer truck also slid into the Santa Catarina river in the driving rain and its two occupants were missing, the local newspaper El Norte said.</s>

<s docid="AP880917-0096" num="19" wdcount="23"> Recreational areas with soccer fields, basketball courts, tennis courts and jogging trails have been built along the river in the last few years.</s>

<s docid="AP880917-0096" num="20" wdcount="14"> Monterrey is a major northern industrial center and the capital of Nuevo Leon state.</s>

<s docid="AP880917-0096" num="21" wdcount="6"> The Santa Catarina river crosses Monterrey.</s>

<s docid="AP880917-0096" num="22" wdcount="14"> The storm slammed into Mexico for the second time in a week Friday afternoon.</s>

<s docid="AP880917-0096" num="23" wdcount="32"> The eye of 450-mile-wide hurricane, with 120 mph winds, crossed onto land at 5:35 p.m. EDT, sweeping ashore in a sparsely populated area 120 miles south of Brownsville, Texas, weather reports said.</s>

<s docid="AP880917-0096" num="24" wdcount="19"> Although the storm had lost much of its muscle, it caused floods and mudslides after it barreled into Mexico.</s>

<s docid="AP880917-0096" num="25" wdcount="18"> Earlier in the week, Gilbert killed at least 29 and left 300,000 people homeless in the Yucatan Peninsula.</s>

<s docid="AP880917-0096" num="26" wdcount="30"> The hurricane has killed at least 109 people, including one in Texas, 39 in Mexico, 26 in Jamaica, 30 in Haiti, five in the Dominican Republic and eight in Honduras.</s>

<s docid="AP880917-0096" num="27" wdcount="8"> However, the death toll is expected to rise.</s>

<s docid="AP880917-0096" num="28" wdcount="27"> In Matamoros just across the Rio Grande from Brownsville, the storm felled trees, downed power lines and flattened dozens of tin shack homes on the evacuated beachfront.</s>

<s docid="AP880917-0096" num="29" wdcount="6"> About 5,000 people were evacuated inland.</s>

<s docid="AP880917-0096" num="30" wdcount="8"> Nearly two dozen tornadoes were reported around Brownsville.</s>

<s docid="AP880917-0096" num="31" wdcount="11"> Much of the Yucatan Peninsula remained without communications and supplies today.</s>

<s docid="AP880917-0096" num="32" wdcount="37"> At 9 a.m. EDT today, Gilbert's center was located near latitude 25.1 north and longitude 100.3 west, or 185 miles west southwest of Brownsville and 40 miles south of Monterrey, said the National Hurricane Center in Florida.</s>

<s docid="AP880917-0096" num="33" wdcount="23"> Maximum sustained winds were estimated to be near 50 mph and the storm was expected to weaken further during the next 24 hours.</s>

<s docid="AP880917-0096" num="34" wdcount="19"> The center said rainfall of 10 to 15 inches was accompanying the storm with up to 20 inches locally.</s>

<s docid="AP880917-0096" num="35" wdcount="6"> Flash floods were likely, it said.</s>

<s docid="AP880917-0096" num="36" wdcount="27"> The storm was moving west-northwest at about 12 mph, and was expected to follow that track through midday today before turning gradually to the northwest, forecasters said.</s>

<s docid="AP880917-0096" num="37" wdcount="14"> In Matamoros, officials said the worst part of the storm appeared to have passed.</s>

<s docid="AP880917-0096" num="38" wdcount="18"> ``Up to now the damages are not considered very grave,'' said Jose Inez Gonzalez, a Matamoros government spokesman.</s>

<s docid="AP880917-0096" num="39" wdcount="21"> Officials distributed crackers and water to thousands of people in shelters and rged them to stay put until the storm ended.</s>

<s docid="AP880917-0096" num="40" wdcount="27"> Gilbert hit Soto la Marina, a town of 8,000 people 20 miles inland from La Pesca on late Friday, its mayor told The Associated Press by telephone.</s>

<s docid="AP880917-0096" num="41" wdcount="8"> ``There is considerable material damage to the town.</s>

<s docid="AP880917-0096" num="42" wdcount="11"> It is still raining very hard,'' said Mayor Ruben Hinojosa Cortina.</s>

<s docid="AP880917-0096" num="43" wdcount="15"> ``We will just have to stay in and wait until tomorrow to survey the situation''.</s>

<s docid="AP880917-0096" num="44" wdcount="30"> Hinojosa Cortina said about 3,000 refugees from La Pesca were sheltered in Soto la Marina but other coastal residents had not been evacuated or decided to ride out the storm.</s>

<s docid="AP880917-0096" num="45" wdcount="28"> The Sierra de Tamaulipas, a small mountain range between Monterrey and the coast, should blunt the hurricane's strength, said Mark Zimmer, a meterologist at the National Hurricane Center.</s>

<s docid="AP880917-0096" num="46" wdcount="8"> Zimmer expected the last of hurricane-force winds today.</s>

<s docid="AP880917-0096" num="47" wdcount="21"> But he predicted very heavy rains as warm hurricane winds rise into cooler mountain air, possibly causing flash floods and mudslides.</s>

<s docid="AP880917-0096" num="48" wdcount="23"> The Mexican armed forces began emergency flights Friday of food, medicines and water to Cancun, Cozumel and other disaster sites in the Yucatan.</s>

<s docid="AP880917-0096" num="49" wdcount="18"> In many locations, hurricane victims were without food, drinking water, electrical power, gasoline and communications since Wednesday .</s>
</TEXT>
</DOC>
