<DOC>
<DOCNO>

<s docid="AP880915-0142" num="1" wdcount="1"> AP880915-0142</s>
</DOCNO>
<FILEID>

<s docid="AP880915-0142" num="2" wdcount="2"> AP-NR-09-15-88 1519EDT</s>
</FILEID>
<FIRST>

<s docid="AP880915-0142" num="3" wdcount="7"> u i PM-HurricaneGilbert 5thLd-Writethru a0599 09-15 0894</s>
</FIRST>
<SECOND>

<s docid="AP880915-0142" num="4" wdcount="7"> PM-Hurricane Gilbert, 5th Ld - Writethru, a0599,0915</s>
</SECOND>
<HEAD>

<s docid="AP880915-0142" num="5" wdcount="9"> After Battering Yucatan, Gilbert Strengthens, Heads For Gulf Coast</s>
</HEAD>
<NOTE>

<s docid="AP880915-0142" num="6" wdcount="13"> Eds: LEADS with 5 grafs to UPDATE with 3 p.m. position of storm.</s>

<s docid="AP880915-0142" num="7" wdcount="7"> Pick up 6th graf pvs: `Brownsville was...'</s>
</NOTE>
<BYLINE>

<s docid="AP880915-0142" num="8" wdcount="3"> By CHRIS ANGELO</s>
</BYLINE>
<BYLINE>

<s docid="AP880915-0142" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880915-0142" num="10" wdcount="3"> CANCUN, Mexico (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880915-0142" num="11" wdcount="31"> The most intense hurricane on record surged toward Texas today after battering the Yucatan Peninsula with 160 mph winds, leveling slums, pummeling posh resorts and forcing tens of thousands to flee.</s>

<s docid="AP880915-0142" num="12" wdcount="43"> Hurricane Gilbert, which has left nearly one in four Jamaicans homeless, slackened somewhat as it swirled over land, but the storm was beginning to gain strength over open water as it moved toward the U.S. Gulf Coast with sustained winds of 120 mph.</s>

<s docid="AP880915-0142" num="13" wdcount="13"> The storm was headed west northwest, said National Hurricane Center director Bob Sheets.</s>

<s docid="AP880915-0142" num="14" wdcount="14"> It was moving at 15 mph and dumping up to 10 inches of rain.</s>

<s docid="AP880915-0142" num="15" wdcount="31"> ``The area that we have the most likely possibility that this hurricane will make landfall is in the northern part of Mexico or the southeastern, southern part of Texas,'' he said.</s>

<s docid="AP880915-0142" num="16" wdcount="31"> At 3 p.m. today, the center of the storm was near latitude 22.3 north and longitude 92.9 west, or about 380 miles southeast of Brownsville, Texas, the National Weather Service said.</s>

<s docid="AP880915-0142" num="17" wdcount="31"> Brownsville was given a 21 percent probability of being hit, though a hurricane watch was in effect along the entire Texas coast as well as the northeastern Mexican coast from Tampico.</s>

<s docid="AP880915-0142" num="18" wdcount="30"> Earlier this week the storm struck the Carribean, ravaging Jamaica, the Dominican Repubic, the Cayman Islands and Haiti, killing at least 19 in Jamaica and five in the Dominican Republic.</s>

<s docid="AP880915-0142" num="19" wdcount="19"> Haiti declared a state of emergency across its southern peninsula, where at least 10 hurricane-related deaths have been reported.</s>

<s docid="AP880915-0142" num="20" wdcount="30"> The storm, about 450 miles wide, hit the Yucatan coast at dawn Wednesday, thrashing beaches with 23-foot waves, uprooting trees, knocking out electricity and water supplies and severing telephone lines.</s>

<s docid="AP880915-0142" num="21" wdcount="7"> Mexican officials reported at least seven injuries.</s>

<s docid="AP880915-0142" num="22" wdcount="6"> There were no reports of deaths.</s>

<s docid="AP880915-0142" num="23" wdcount="35"> Gilbert battered the provincial capital of Merida and the gulf port cities of Puerto Progreso, Campeche and Ciudad del Carmen, closing airports and roads and knocking out communications and power and innundating streets and highways.</s>

<s docid="AP880915-0142" num="24" wdcount="25"> About 20,000 people were evacuated from Puerto Progreso and other coastal towns, a spokesman for the Interior Ministry in Mexico City said by telephone today.</s>

<s docid="AP880915-0142" num="25" wdcount="7"> Hundreds of homes were destroyed, he said.</s>

<s docid="AP880915-0142" num="26" wdcount="30"> The ministry said the storm seriously damaged the luxury hotel zone in the resort of Cancun and destroyed about a quarter of the homes on the nearby island of Cozumel.</s>

<s docid="AP880915-0142" num="27" wdcount="20"> Ham radio operators in Mexico City also told The Associated Press they had reports of massive damage to several hotels.</s>

<s docid="AP880915-0142" num="28" wdcount="18"> Authorities were particularly concerned about the people trapped on another resort island just off Cancun, tiny Isla Mujeres.</s>

<s docid="AP880915-0142" num="29" wdcount="21"> A navy spokesman in Mexico City said he had no word on the plight of an estimated 15,000 people stranded there.</s>

<s docid="AP880915-0142" num="30" wdcount="20"> Three ferries linking the island with the mainland were lost in the storm, but there were no reports of casualties.</s>

<s docid="AP880915-0142" num="31" wdcount="28"> In Campeche, boats were driven onto the street running along the waterfront, Ramon Castillo, a night watchman at the newspaper Novedades of Campeche, said in a telephone interview.</s>

<s docid="AP880915-0142" num="32" wdcount="11"> ``There is no light, there is no radio, there is nothing.</s>

<s docid="AP880915-0142" num="33" wdcount="4"> There is much damage.</s>

<s docid="AP880915-0142" num="34" wdcount="7"> The whole city is flooded,'' he said.</s>

<s docid="AP880915-0142" num="35" wdcount="26"> Sheets said the hurricane was expected to hit land midday Friday and that its sustained winds would today ``certainly increase to 130, 140 miles per hour''.</s>

<s docid="AP880915-0142" num="36" wdcount="17"> ``It's going to have an impact over a fairly large area,'' Sheets said on CBS-TV's ``This Morning''.</s>

<s docid="AP880915-0142" num="37" wdcount="16"> ``Those major destructive winds are going to be in there fairly tight close to the center.</s>

<s docid="AP880915-0142" num="38" wdcount="14"> But the impacts are going to be felt over most of the Texas area''.</s>

<s docid="AP880915-0142" num="39" wdcount="37"> The hurricane center said Gilbert was the most intense storm on record in terms of barometric pressure, which was measured at 26.31 inches, breaking the 26.35 inches recorded for the 1935 hurricane that devastated the Florida Keys.</s>

<s docid="AP880915-0142" num="40" wdcount="37"> In the Yucatan state capital of Merida, the storm's 160 mph winds destroyed nearly all the thatched houses in one district, uprooted trees, road signs and cut off water supplies, said Gonzalez Correa, news editor of Novedades.</s>

<s docid="AP880915-0142" num="41" wdcount="23"> A spokeswoman with the National Civil Defense System in Mexico City said at least 20,000 people had flocked to Merida from coastal areas.</s>

<s docid="AP880915-0142" num="42" wdcount="17"> Civil defense officials said 6,000 tourists left beachside motels and 30,000 local people also sought temporary shelter.</s>

<s docid="AP880915-0142" num="43" wdcount="21"> U.S. consular officials said they did not know how many tourists were in Cancun, which receives about 50,000 visitors per month.</s>

<s docid="AP880915-0142" num="44" wdcount="15"> The storm, spawned Saturday southeast of Puerto Rico, appeared to have hit Jamaica the hardest.</s>

<s docid="AP880915-0142" num="45" wdcount="18"> That island nation's prime minister, Edward Seaga, said Wednesday that it destroyed about 100,000 of Jamaica's 500,000 homes.</s>

<s docid="AP880915-0142" num="46" wdcount="6"> He estimated damage at $8 billion.</s>

<s docid="AP880915-0142" num="47" wdcount="17"> Earlier Wednesday, Gilbert was classified as a Category 5 storm, the strongest and deadliest type of hurricane.</s>

<s docid="AP880915-0142" num="48" wdcount="15"> Such storms have maximum sustained winds greater than 155 mph and can cause catastrophic damage.</s>

<s docid="AP880915-0142" num="49" wdcount="21"> By Wednesday night, the National Hurricane Center downgraded it to a Category 4 and to a Category 3 by this morning.</s>

<s docid="AP880915-0142" num="50" wdcount="35"> Only two Category 5 hurricanes have hit the United States _ the 1935 storm that killed 408 people in Florida and Hurricane Camille, which devastated the Mississippi coast in 1969 and killed 256 people .</s>
</TEXT>
</DOC>
