<DOC>
<DOCNO>

<s docid="AP880917-0095" num="1" wdcount="1"> AP880917-0095</s>
</DOCNO>
<FILEID>

<s docid="AP880917-0095" num="2" wdcount="2"> AP-NR-09-17-88 1157EDT</s>
</FILEID>
<FIRST>

<s docid="AP880917-0095" num="3" wdcount="7"> u a PM-HurricaneGilbert 3rdLd-Writethru a0498 09-17 0892</s>
</FIRST>
<SECOND>

<s docid="AP880917-0095" num="4" wdcount="7"> PM-Hurricane Gilbert, 3rd Ld - Writethru, a0498,0913</s>
</SECOND>
<HEAD>

<s docid="AP880917-0095" num="5" wdcount="9"> Gilbert Downgraded to Tropical Storm; Floods And Tornadoes Feared</s>
</HEAD>
<NOTE>

<s docid="AP880917-0095" num="6" wdcount="24"> Eds: Leads with 9 grafs to update with 109 deaths, one in Texas, tornadoes, picking up at the 10th graf previous, ``At 6 a.m...''</s>
</NOTE>
<HEAD>

<s docid="AP880917-0095" num="7" wdcount="5"> LaserPhotos HRX2, HRX7, LaserGraphic NY18</s>
</HEAD>
<BYLINE>

<s docid="AP880917-0095" num="8" wdcount="3"> By DAVID SEDENO</s>
</BYLINE>
<BYLINE>

<s docid="AP880917-0095" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880917-0095" num="10" wdcount="3"> BROWNSVILLE, Texas (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880917-0095" num="11" wdcount="29"> Hurricane Gilbert weakened to a tropical storm as it blustered northwestward today but it threw tornadoes and sheets of rain at thousands of shuttered evacuees along the Texas-Mexico border.</s>

<s docid="AP880917-0095" num="12" wdcount="40"> At least 109 people have been killed and more than 800,000 left homeless since Gilbert ripped through the Caribbean with 175 mph wind earlier this week, then crossed the Yucatan Peninsula and Gulf of Mexico before slamming into northeastern Mexico.</s>

<s docid="AP880917-0095" num="13" wdcount="12"> One person died today in Texas after being injured in a tornado.</s>

<s docid="AP880917-0095" num="14" wdcount="30"> But by this morning, the once massive storm's maximum sustained winds had flagged to 65 mph, nine less than hurricane strength, and forecasters said the eye had all but disappeared.</s>

<s docid="AP880917-0095" num="15" wdcount="10"> However, they warned of continued danger from flash flooding inland.</s>

<s docid="AP880917-0095" num="16" wdcount="39"> Gilbert was downgraded to a tropical storm at 6 a.m. EDT as it proceeded 50 miles southeast of the city of Monterrey in northern Mexico, said Noel Rishnychok, a meteorologist with the National Hurricane Center in Coral Gables, Fla.</s>

<s docid="AP880917-0095" num="17" wdcount="14"> Winds were still weakening as the storm moved west-northwest at 12 mph, he said.</s>

<s docid="AP880917-0095" num="18" wdcount="34"> Gulf Coast residents expressed relief that the storm, which earlier was deemed the most powerful ever tracked in the Western Hemisphere, pulled its punch as it came ashore despite delivering a spate of tornadoes.</s>

<s docid="AP880917-0095" num="19" wdcount="9"> ``We're thankful,'' said Betty Turner, mayor of Corpus Christi.</s>

<s docid="AP880917-0095" num="20" wdcount="17"> ``What could have been one of the most deadly storms in history appears to have missed us''.</s>

<s docid="AP880917-0095" num="21" wdcount="21"> Corpus Christi residents who evacuated were eager to return, but Turner said, ``We're saying don't do it because of the flooding''.</s>

<s docid="AP880917-0095" num="22" wdcount="29"> At least a dozen tornadoes peppered southern Texas today, following 14 on Friday, killing one woman, striking a hospital complex, military bases and a mobile home park, authorities said.</s>

<s docid="AP880917-0095" num="23" wdcount="4"> Some injuries were reported.</s>

<s docid="AP880917-0095" num="24" wdcount="36"> At 6 a.m. CDT, the center of the storm was in northern Mexico near latitude 25.0 degrees north and longitude 99.8 west, or about 150 miles southwest of Brownsville, located at the southernmost tip of Texas.</s>

<s docid="AP880917-0095" num="25" wdcount="37"> Gilbert's remnants should bring very heavy rains to Rio Grande valley before heading north up the Mississippi River Valley as a ``huge rain-making machine,'' said Mark Zimmer, meteorologist at the National Hurricane Center in Coral Gables, Fla.</s>

<s docid="AP880917-0095" num="26" wdcount="12"> ``The danger of flash flooding in Texas is very great,'' Zimmer said.</s>

<s docid="AP880917-0095" num="27" wdcount="16"> ``Rainfall as high as 10 to 15 inches _ maybe even 20 inches _ is expected''.</s>

<s docid="AP880917-0095" num="28" wdcount="27"> By midweek, the storm should be in the lower Ohio River Valley and end up in the Great Lakes as nothing more than foul weather, forecasters said.</s>

<s docid="AP880917-0095" num="29" wdcount="12"> ``The people in the Midwest better dust off their umbrellas,'' Zimmer said.</s>

<s docid="AP880917-0095" num="30" wdcount="38"> Gilbert, responsible for billions of dollars in damage during a weeklong rampage across the Caribbean and Gulf of Mexico, barreled ashore Friday afternoon in Tamaulipas state, a sparsely populated area of Mexico about 120 miles south of Brownsville.</s>

<s docid="AP880917-0095" num="31" wdcount="33"> The eye passed over Santa Rosa and Santa Cruz, two small villages a few miles north of La Pesca, Mexico, where ocean tides coursed over two miles of flatlands and into the town.</s>

<s docid="AP880917-0095" num="32" wdcount="17"> ``We presume (the Mexican villages) are getting a good pounding from 120 mph winds,'' Zimmer said Friday.</s>

<s docid="AP880917-0095" num="33" wdcount="24"> Thousands of people evacuated in areas of northeastern Mexico, including the entire beach area of Matamoros, a city of 280,000 just across the border.</s>

<s docid="AP880917-0095" num="34" wdcount="31"> To the south, about 300,000 people were homeless in Yucatan state and 10,000 more were homeless in Campeche, on the west coast of the peninsula, the government news agency Notimex said.</s>

<s docid="AP880917-0095" num="35" wdcount="14"> The storm had left more than 500,000 homeless in Jamaica earlier in the week.</s>

<s docid="AP880917-0095" num="36" wdcount="29"> In Texas, heavy rains fell on Brownsville, with gusts up to 82 mph recorded at nearby Padre Island, but the vulnerable coastal area escaped the worst of the storm.</s>

<s docid="AP880917-0095" num="37" wdcount="24"> Police in nearby Harlingen said the windows of 20 to 30 cars in a parking lot were shattered by high winds or a tornado.</s>

<s docid="AP880917-0095" num="38" wdcount="8"> Low-lying coastal roads were closed by high water.</s>

<s docid="AP880917-0095" num="39" wdcount="24"> About 125 shelters holding 50,000 people were open in a four-county area of southern Texas around Brownsville, said American Red Cross spokeswoman Barbara Lohman.</s>

<s docid="AP880917-0095" num="40" wdcount="18"> When the eye of the storm passed to the south, evacuees were eager to return to their homes.</s>

<s docid="AP880917-0095" num="41" wdcount="3"> ``We're going home.</s>

<s docid="AP880917-0095" num="42" wdcount="20"> We think everything is going to be OK,'' Philip Gibbons said Friday night, leaving a Brownsville shelter into a downpour.</s>

<s docid="AP880917-0095" num="43" wdcount="17"> ``We don't think it's going to get bad and there was no need to stay here anymore''.</s>

<s docid="AP880917-0095" num="44" wdcount="5"> Others, however, were more cautious.</s>

<s docid="AP880917-0095" num="45" wdcount="32"> ``I wouldn't want to go home and then have my family hurt by a tornado,'' said Praxedis Lindsey, 25, of Brownsville, who was at a shelter with his pregnant wife and son.</s>

<s docid="AP880917-0095" num="46" wdcount="25"> Elsewhere, most of the estimated 25,000 people evacuated in southern Louisiana and 20,000 in the island city of Galveston were allowed to return home Friday.</s>

<s docid="AP880917-0095" num="47" wdcount="17"> In Alabama, tornadoes were reported in seven counties, uprooting trees but causing no major damage or injuries.</s>

<s docid="AP880917-0095" num="48" wdcount="9"> One Texas drowning was indirectly related to the hurricane.</s>

<s docid="AP880917-0095" num="49" wdcount="20"> A 3-year-old boy fell from his family's shrimp boat when they moved the vessel for safe mooring, officials said .</s>
</TEXT>
</DOC>
