<DOC>
<DOCNO>

<s docid="AP890925-0124" num="1" wdcount="1"> AP890925-0124</s>
</DOCNO>
<FILEID>

<s docid="AP890925-0124" num="2" wdcount="2"> AP-NR-09-25-89 1627EDT</s>
</FILEID>
<FIRST>

<s docid="AP890925-0124" num="3" wdcount="5"> r i AM-Britain-Blast 09-25 0360</s>
</FIRST>
<SECOND>

<s docid="AP890925-0124" num="4" wdcount="1"> AM-Britain-Blast,0371</s>
</SECOND>
<HEAD>

<s docid="AP890925-0124" num="5" wdcount="8"> Prime Minister Condemns IRA for Music School Explosion</s>
</HEAD>
<DATELINE>

<s docid="AP890925-0124" num="6" wdcount="3"> DEAL, England (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890925-0124" num="7" wdcount="34"> Prime Minister Margaret Thatcher said Monday the Irish Republican Army members who blew up the Royal Marines School of Music and killed 10 bandsmen last week are ``monsters'' who will be found and punished.</s>

<s docid="AP890925-0124" num="8" wdcount="42"> ``The young men whom we lost were murdered by common murderers who must be found and brought to justice and put behind bars for a very long time,'' she said following a tour of the school's wrecked barracks in Deal, southeast England.</s>

<s docid="AP890925-0124" num="9" wdcount="23"> ``We lost 10 remarkable musicians, not fighting men, just because some people try to bomb others out of their democratic views,'' she said.</s>

<s docid="AP890925-0124" num="10" wdcount="7"> ``They are very evil people, absolute monsters''.</s>

<s docid="AP890925-0124" num="11" wdcount="18"> Gerry Adams, president of Sinn Fein, the legal political arm of the IRA, issued a statement disputing Mrs.</s>

<s docid="AP890925-0124" num="12" wdcount="21"> Thatcher's remarks, saying ``she knows in her heart of hearts the real nature of the conflict, its cause and the remedy''.</s>

<s docid="AP890925-0124" num="13" wdcount="24"> The IRA is fighting to end British rule in Northern Ireland and unite the predominantly Protestant province with the Roman Catholic Republic of Ireland.</s>

<s docid="AP890925-0124" num="14" wdcount="20"> ``We want an end to all violent deaths arising out of the present relationship between our two countries,'' Adams said.</s>

<s docid="AP890925-0124" num="15" wdcount="19"> ``We want a new peaceful relationship based on an acceptance and respect for our rights as a sovereign nation''.</s>

<s docid="AP890925-0124" num="16" wdcount="30"> After visiting some of the 11 injured bandsmen still in the hospital, Mrs. Thatcher pledged: ``The hunt for the bombers will be pursued with all possible speed, vigor and dedication''.</s>

<s docid="AP890925-0124" num="17" wdcount="25"> Raymond Kendall, the secretary-general of the international police organization Interpol, pledged the organization's full support in the hunt for those who blew up the school.</s>

<s docid="AP890925-0124" num="18" wdcount="24"> ``I hope we will have a part to play in finding them,'' said Kendall after opening the International Police Exhibition and Conference in London.</s>

<s docid="AP890925-0124" num="19" wdcount="14"> ``They are criminals of the worst sort and should be dealt with as such''.</s>

<s docid="AP890925-0124" num="20" wdcount="5"> Before landing in Deal, Mrs.</s>

<s docid="AP890925-0124" num="21" wdcount="13"> Thatcher's helicopter flew over the rubble that had been the band's recreation center.</s>

<s docid="AP890925-0124" num="22" wdcount="27"> The IRA claimed responsibility for the explosion, and police said they are looking for three men with Irish accents who rented a house overlooking the barracks .</s>
</TEXT>
</DOC>
