<DOC>
<DOCNO>

<s docid="AP890924-0025" num="1" wdcount="1"> AP890924-0025</s>
</DOCNO>
<FILEID>

<s docid="AP890924-0025" num="2" wdcount="2"> AP-NR-09-24-89 1336EDT</s>
</FILEID>
<FIRST>

<s docid="AP890924-0025" num="3" wdcount="5"> r i AM-Britain-IRA 09-24 0522</s>
</FIRST>
<SECOND>

<s docid="AP890924-0025" num="4" wdcount="1"> AM-Britain-IRA,0537</s>
</SECOND>
<HEAD>

<s docid="AP890924-0025" num="5" wdcount="7"> Prince Philip Condemns IRA, Clergy Urge Forgiveness</s>
</HEAD>
<DATELINE>

<s docid="AP890924-0025" num="6" wdcount="3"> DEAL, Britain (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890924-0025" num="7" wdcount="33"> Prince Philip on Sunday condemned the ``senseless'' killing of 10 Royal Marines musicians in an IRA bombing, and Britain's defense secretary said he warned all military bases of the risk of similar attacks.</s>

<s docid="AP890924-0025" num="8" wdcount="14"> Clergyman urged relatives and friends of dead and maimed musicians to forgive the bombers.</s>

<s docid="AP890924-0025" num="9" wdcount="17"> ``Only forgiveness breaks the tie between the hater and the hated,'' the Rev. George Lings told mourners.</s>

<s docid="AP890924-0025" num="10" wdcount="34"> The prince, husband of Queen Elizabeth II and captain general of the Royal Marines, visited injured men in the hospital and toured the severely damaged Royal Marines School of Music in Deal, southeast Britain.</s>

<s docid="AP890924-0025" num="11" wdcount="16"> ``It will not help the IRA win anything,'' said Philip, who wore a Royal Marines tie.</s>

<s docid="AP890924-0025" num="12" wdcount="3"> ``It is senseless.</s>

<s docid="AP890924-0025" num="13" wdcount="13"> One simply wonders what sort of mentality can even contemplate such meaningless acts.</s>

<s docid="AP890924-0025" num="14" wdcount="3"> It is appalling''.</s>

<s docid="AP890924-0025" num="15" wdcount="14"> He paid tribute to the 12 injured men, five of whom were critically wounded.</s>

<s docid="AP890924-0025" num="16" wdcount="23"> The prince was accompanied by Viscountess Mountbatten, daughter of Lord Mountbatten, who was killed by an IRA bomb on his boat in 1979.</s>

<s docid="AP890924-0025" num="17" wdcount="11"> Mountbatten was India's last viceroy and a cousin of the queen.</s>

<s docid="AP890924-0025" num="18" wdcount="35"> British military installations are a frequent target of the Irish Republican Army in its campaign to end British rule in Northern Ireland and unite the predominantly Protestant province with the Roman Catholic Republic of Ireland.</s>

<s docid="AP890924-0025" num="19" wdcount="19"> Defense Secretary Tom King said Sunday he has issued an alert to all military installations to prevent other attacks.</s>

<s docid="AP890924-0025" num="20" wdcount="5"> He would not give details.</s>

<s docid="AP890924-0025" num="21" wdcount="19"> ``The perpetrators of the latest outrage are at large and there is a risk of other attacks,'' King said.</s>

<s docid="AP890924-0025" num="22" wdcount="11"> ``That is why we are taking a number of other steps''.</s>

<s docid="AP890924-0025" num="23" wdcount="22"> King defended the use of private security firms hired to guard the Deal school and 29 other ``low-risk'' military installations in Britain.</s>

<s docid="AP890924-0025" num="24" wdcount="18"> Local residents and grieving relatives have said security was lax and should be turned back to the marines.</s>

<s docid="AP890924-0025" num="25" wdcount="7"> King said the private firms will remain.</s>

<s docid="AP890924-0025" num="26" wdcount="25"> ``It is important to remember that what we need in these cases are eyes and ears and observation,'' King said on British Broadcasting Corp. radio.</s>

<s docid="AP890924-0025" num="27" wdcount="10"> ``Private security guards can be a very useful additional assistance.</s>

<s docid="AP890924-0025" num="28" wdcount="24"> They also help to reduce the amount of time soldiers have to spend on what is not the most enjoyable part of their activity''.</s>

<s docid="AP890924-0025" num="29" wdcount="17"> At church services throughout the small port, clergymen urged mourners to pray for and forgive the bombers.</s>

<s docid="AP890924-0025" num="30" wdcount="24"> The Rev. Charles Howard, a Royal Navy chaplain, asked the 300-member congregation inside the barracks, ``if you can find room in your hearts ...</s>

<s docid="AP890924-0025" num="31" wdcount="24"> pray for the men who perpetrated this terrible act, that God will soften their hearts and turn them from their violent and evil ways''.</s>

<s docid="AP890924-0025" num="32" wdcount="20"> Many cried as Howard read aloud the names of the 10 servicemen killed during a coffee break between band practices.</s>

<s docid="AP890924-0025" num="33" wdcount="13"> It was the worst IRA attack on the British mainland since July 1982.</s>

<s docid="AP890924-0025" num="34" wdcount="3"> At nearby St.</s>

<s docid="AP890924-0025" num="35" wdcount="22"> George's Church, formerly the Royal Marines' church, Lings said, ``no one says forgiveness is easy; no one says the terrorist deserves forgiveness.</s>

<s docid="AP890924-0025" num="36" wdcount="2"> ``But ...</s>

<s docid="AP890924-0025" num="37" wdcount="7"> forgive them, they not what they do.''</s>
</TEXT>
</DOC>
