<DOC>
<DOCNO>

<s docid="AP890923-0012" num="1" wdcount="1"> AP890923-0012</s>
</DOCNO>
<FILEID>

<s docid="AP890923-0012" num="2" wdcount="2"> AP-NR-09-23-89 0100EDT</s>
</FILEID>
<FIRST>

<s docid="AP890923-0012" num="3" wdcount="6"> u i PM-Britain-Blast Bjt 09-23 0782</s>
</FIRST>
<SECOND>

<s docid="AP890923-0012" num="4" wdcount="2"> PM-Britain-Blast, Bjt,0808</s>
</SECOND>
<HEAD>

<s docid="AP890923-0012" num="5" wdcount="5"> IRA Attack Stirs Security Controversy</s>
</HEAD>
<HEAD>

<s docid="AP890923-0012" num="6" wdcount="3"> By MAUREEN JOHNSON</s>
</HEAD>
<BYLINE>

<s docid="AP890923-0012" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890923-0012" num="8" wdcount="3"> DEAL, England (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890923-0012" num="9" wdcount="29"> The IRA bombing that killed 10 men and blew apart a building at the Royal Marines Music School outraged Britons and stirred recriminations over safety standards at the school.</s>

<s docid="AP890923-0012" num="10" wdcount="28"> A huge explosion in a barracks staff room Friday morning leveled the three-story building as bandsmen took a coffee break between practice sessions on the school's parade ground.</s>

<s docid="AP890923-0012" num="11" wdcount="16"> Twelve of the 22 people injured were hospitalized, eight of them in serious condition, police said.</s>

<s docid="AP890923-0012" num="12" wdcount="16"> They said nine of the dead were bandsmen and one other man was not immediately identified.</s>

<s docid="AP890923-0012" num="13" wdcount="15"> Dozens of neighboring homes in the quiet southeastern English seaside town of Deal were damaged.</s>

<s docid="AP890923-0012" num="14" wdcount="28"> Although trainees at the school range in age from 16 to 20, Col. John Ware, principal director of music, said the slain bandsmen all were trained, adult musicians.</s>

<s docid="AP890923-0012" num="15" wdcount="13"> They held military ranks but none had been trained as a fighting soldier.</s>

<s docid="AP890923-0012" num="16" wdcount="33"> The outlawed Irish Republican Army, engaged in a 20-year-old campaign to drive the British from the province of Northern Ireland, claimed responsibility in a telephone call to Ireland International, a Dublin news agency.</s>

<s docid="AP890923-0012" num="17" wdcount="27"> Residents of the area adjoining the Marines school said Friday that despite government calls for stepped-up public alertness against terrorists, security at the school had eased noticeably.</s>

<s docid="AP890923-0012" num="18" wdcount="22"> ``Anyone in Deal will tell you how easy it is to get into the base,'' said Fred Verge, a 70-year-old army veteran.</s>

<s docid="AP890923-0012" num="19" wdcount="14"> Local people laid wreaths and bouquets of flowers at the entrance to the barracks.</s>

<s docid="AP890923-0012" num="20" wdcount="17"> ``There is a great sense of anger'' in the community, Kent police Chief Constable Paul Condon said.</s>

<s docid="AP890923-0012" num="21" wdcount="22"> The Royal Marines Music School is one of 30 military establishments in Britain that use private security firms, Defense Ministry figures show.</s>

<s docid="AP890923-0012" num="22" wdcount="25"> Unidentified defense sources quoted by the Times newspaper today said the civilian guards were backed up by armed Marines who patrolled regularly inside the perimeter.</s>

<s docid="AP890923-0012" num="23" wdcount="19"> Defense Secretary Tom King promised a security review and said new measures had already been taken at the base.</s>

<s docid="AP890923-0012" num="24" wdcount="4"> He did not elaborate.</s>

<s docid="AP890923-0012" num="25" wdcount="36"> Martin O'Neill, the opposition Labor Party's spokesman on defense, said on Friday: ``Serious questions must be asked about the penny-pinching policy of the Ministry of Defense, which may well put our armed services at dreadful risk''.</s>

<s docid="AP890923-0012" num="26" wdcount="15"> O'Neill later told British Broadcasting Corp. television the IRA was ``prepared to take out anybody.</s>

<s docid="AP890923-0012" num="27" wdcount="15"> The cowardly nature of their attacks is such that every military establishment is under threat''.</s>

<s docid="AP890923-0012" num="28" wdcount="14"> He said private security firms were assigned to areas considered low risks for attacks.</s>

<s docid="AP890923-0012" num="29" wdcount="28"> ``If we designate places as being low-risk categories, then it is likely they will be attacked, given the way that the IRA is forced to operate,'' O'Neill added.</s>

<s docid="AP890923-0012" num="30" wdcount="19"> ``The big prizes are no longer available to them, so they're picking off the ones which they regard ...</s>

<s docid="AP890923-0012" num="31" wdcount="22"> vulnerable''. Prime Minister Margaret Thatcher received news of the bombing while aboard a jet over Siberia en route from Japan to Moscow.</s>

<s docid="AP890923-0012" num="32" wdcount="7"> She called it a ``deeply serious outrage''.</s>

<s docid="AP890923-0012" num="33" wdcount="8"> King visited the scene soon after the explosion.</s>

<s docid="AP890923-0012" num="34" wdcount="39"> ``I know that the people who committed it, the godfathers who sent them, actually know in their hearts that it is not going to make any difference; that it is just killing for the sake of killing,'' he said.</s>

<s docid="AP890923-0012" num="35" wdcount="31"> The defense minister, anger clearly written on his face, said that rather than erode the will of the security forces, the attack ``redoubles their determination to ensure that terrorism cannot win''.</s>

<s docid="AP890923-0012" num="36" wdcount="21"> Prime Minister Charles Haughey of Ireland condemned the attack and sent Mrs. Thatcher a message of sympathy at ``this outrage ...</s>

<s docid="AP890923-0012" num="37" wdcount="12"> which has caused severe and tragic loss of life and many injuries''.</s>

<s docid="AP890923-0012" num="38" wdcount="35"> The mainly Roman Catholic IRA claim gave no details of the operation, but said it was a response to a ``message of war'' delivered by Mrs. Thatcher when she visited Northern Ireland nine days ago.</s>

<s docid="AP890923-0012" num="39" wdcount="33"> It was an apparent reference to her speech praising the locally recruited Ulster Defense Regiment as ``a very, very brave group of men'' who have lost 179 members in IRA attacks since 1970.</s>

<s docid="AP890923-0012" num="40" wdcount="36"> The mainly Protestant UDR is regarded by many Catholics as a sectarian force, and is at present under a cloud over allegations that some recruits leaked names, addresses and photos of IRA suspects to Protestant assassins.</s>

<s docid="AP890923-0012" num="41" wdcount="11"> British military installations are a frequent target of the IRA campaign.</s>

<s docid="AP890923-0012" num="42" wdcount="20"> Friday's attack was the worst since July 1982 when 11 servicemen were fatally wounded in two bombings in central London.</s>

<s docid="AP890923-0012" num="43" wdcount="12"> The music school trains young recruits for the seven Royal Marines bands.</s>

<s docid="AP890923-0012" num="44" wdcount="22"> Up to 250 young men, most ages 16 to 20, undergo military and musical training there, working with older, professional bandsmen .</s>
</TEXT>
</DOC>
