<DOC>
<DOCNO>

<s docid="AP890922-0071" num="1" wdcount="1"> AP890922-0071</s>
</DOCNO>
<FILEID>

<s docid="AP890922-0071" num="2" wdcount="2"> AP-NR-09-22-89 0634EDT</s>
</FILEID>
<FIRST>

<s docid="AP890922-0071" num="3" wdcount="7"> u i Britain-Blast 3rdLd-Writethru a0526 09-22 0467</s>
</FIRST>
<SECOND>

<s docid="AP890922-0071" num="4" wdcount="4"> Britain-Blast, 3rd Ld-Writethru, a0526,0477</s>
</SECOND>
<HEAD>

<s docid="AP890922-0071" num="5" wdcount="12"> Eight Dead, Up to 18 Missing After Explosion at Marine Band Complex</s>
</HEAD>
<HEAD>

<s docid="AP890922-0071" num="6" wdcount="23"> Eds: LEADS with 7 grafs to UPDATE with eight dead, Scotland Yard sending anti-terrorist unit to investigate; pickup 7th graf pvs, `Ten doctors...'</s>
</HEAD>
<BYLINE>

<s docid="AP890922-0071" num="7" wdcount="3"> By LESLIE SHEPHERD</s>
</BYLINE>
<BYLINE>

<s docid="AP890922-0071" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890922-0071" num="9" wdcount="2"> LONDON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890922-0071" num="10" wdcount="26"> An explosion rocked the Royal Marines School of Music in a southeastern coastal town today, causing one building to collapse and killing eight people, officials said.</s>

<s docid="AP890922-0071" num="11" wdcount="16"> Thirty people were injured and up to 18 were missing and feared trapped in the rubble.</s>

<s docid="AP890922-0071" num="12" wdcount="25"> The blast occurred at at 8:26 a.m. in a lounge in the barracks near Deal, about 70 miles southeast of London, the Defense Ministry said.</s>

<s docid="AP890922-0071" num="13" wdcount="15"> ``The building has collapsed,'' said a ministry spokesman, speaking anonymously in keeping with British custom.</s>

<s docid="AP890922-0071" num="14" wdcount="12"> ``We've no idea of the cause of the blast at the moment.</s>

<s docid="AP890922-0071" num="15" wdcount="6"> It is too early to tell''.</s>

<s docid="AP890922-0071" num="16" wdcount="17"> Scotland Yard said a forensic team from its anti-terrorist squad had been called in to help investigate.</s>

<s docid="AP890922-0071" num="17" wdcount="23"> Firefighters used heavy lifting equipment and thermal cameras to search for those trapped in the debris, said Kent Fire Brigade spokesman Kevin Simmons.</s>

<s docid="AP890922-0071" num="18" wdcount="9"> Kent police said 17 or 18 people were trapped.</s>

<s docid="AP890922-0071" num="19" wdcount="7"> The Defense Ministry said seven were missing.</s>

<s docid="AP890922-0071" num="20" wdcount="21"> Ten doctors gave emergency treatment at the scene and 11 ambulances took the injured to two hospitals, the ambulance service said.</s>

<s docid="AP890922-0071" num="21" wdcount="36"> ``They are suffering from flash burns to their head and arms, fractures, and the sort of injuries you would expect after an explosion,'' said a spokesman for Buckland Hospital in Dover, 20 miles south of Deal.</s>

<s docid="AP890922-0071" num="22" wdcount="24"> South Eastern British Gas sent investigators to the scene but said there was nothing to indicate the explosion was caused by a gas leak.</s>

<s docid="AP890922-0071" num="23" wdcount="14"> Gas supplies to the barracks were cut as a precautionary measure, a spokesman said.</s>

<s docid="AP890922-0071" num="24" wdcount="25"> Guy Platts, who owns a bookstore in Deal, located 20 miles north of the English Channel port of Dover, said he heard a ``massive explosion.</s>

<s docid="AP890922-0071" num="25" wdcount="14"> ... There are dozens of ambulances, police and fire brigade making their way there''.</s>

<s docid="AP890922-0071" num="26" wdcount="32"> Military targets on the British mainland have been attacked several times by the Irish Republican Army in the past year as part of its campaign to rid Northern Ireland of British rule.</s>

<s docid="AP890922-0071" num="27" wdcount="21"> One soldier was killed and nine wounded in an IRA attack on an army barracks in north London in August 1988.</s>

<s docid="AP890922-0071" num="28" wdcount="26"> About 60 soldiers narrowly escaped death or injury in February when they were evacuated from their barracks in Shropshire, western England, just before a bomb exploded.</s>

<s docid="AP890922-0071" num="29" wdcount="34"> In July 1982, eight soldiers died in IRA bombings near the Household Cavalry barracks at Knightsbridge in central London and at a bandstand in the capital's Regent's Park where an army band was playing.</s>

<s docid="AP890922-0071" num="30" wdcount="15"> Three people died later and a total of 51 were injured in the bombings .</s>
</TEXT>
</DOC>
