<DOC>
<DOCNO>

<s docid="AP890923-0091" num="1" wdcount="1"> AP890923-0091</s>
</DOCNO>
<FILEID>

<s docid="AP890923-0091" num="2" wdcount="2"> AP-NR-09-23-89 1402EDT</s>
</FILEID>
<FIRST>

<s docid="AP890923-0091" num="3" wdcount="5"> u i AM-Britain-Blast 09-23 0521</s>
</FIRST>
<SECOND>

<s docid="AP890923-0091" num="4" wdcount="1"> AM-Britain-Blast,0538</s>
</SECOND>
<HEAD>

<s docid="AP890923-0091" num="5" wdcount="9"> Police Search Local House for Clues to Marines Attack</s>
</HEAD>
<DATELINE>

<s docid="AP890923-0091" num="6" wdcount="3"> DEAL, England (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890923-0091" num="7" wdcount="30"> Family members on Saturday grieved for their slain loved ones and criticized the security arrangements at the Royal Marines Music School, where an IRA terrorist attack killed 10 military musicians.</s>

<s docid="AP890923-0091" num="8" wdcount="33"> Jean Cleatheroe, whose son Andrew was killed, joined local residents and opposition politicians in denouncing the use of private security firms to protect the music school and 29 other military establishments in Britain.</s>

<s docid="AP890923-0091" num="9" wdcount="8"> ``The security at those barracks was absolutely abysmal.</s>

<s docid="AP890923-0091" num="10" wdcount="6"> We had seen it for ourselves.</s>

<s docid="AP890923-0091" num="11" wdcount="15"> We have always said how easy it would be for anyone to get in ...</s>

<s docid="AP890923-0091" num="12" wdcount="11"> What could ordinary security men do to stop terrorists''? she said.</s>

<s docid="AP890923-0091" num="13" wdcount="32"> British military installations are a frequent target of the IRA's campaign to end British rule in Northern Ireland and unite the predominantly Protestant province with the mainly Roman Catholic Republic of Ireland.</s>

<s docid="AP890923-0091" num="14" wdcount="19"> Friday's attack was the worst since July 1982, when 11 servicemen were fatally wounded in bombings in central London.</s>

<s docid="AP890923-0091" num="15" wdcount="21"> Shocked residents of Deal gathered outside the barracks to lay flowers in tribute to the young men they called the ``Bandies''.</s>

<s docid="AP890923-0091" num="16" wdcount="20"> An 11-year-old Royal Marines cadet in full dress uniform marched to the barracks and smartly saluted the Royal Marines sign.</s>

<s docid="AP890923-0091" num="17" wdcount="14"> ``I'm proud of my uniform and I'm proud of all the Marines I knew.</s>

<s docid="AP890923-0091" num="18" wdcount="12"> I hate the people who did this to them,'' said Scott Roberts.</s>

<s docid="AP890923-0091" num="19" wdcount="31"> Archbishop of Canterbury Robert Runcie, spiritual leader of the Church of England, visited the injured and said he was impressed ``by their strength and determination that evil will not defeat them''.</s>

<s docid="AP890923-0091" num="20" wdcount="23"> Runcie said one of the men's main concerns was that their hands would heal properly so they could continue playing their musical instruments.</s>

<s docid="AP890923-0091" num="21" wdcount="20"> Police investigating the attack were searching a nearby house that had been rented briefly by three men with Irish accents.</s>

<s docid="AP890923-0091" num="22" wdcount="24"> ``We know when the men arrived and when they left,'' Cmdr. George Churchill-Coleman, head of Scotland Yard's anti-terrorist squad, said at a news conference.</s>

<s docid="AP890923-0091" num="23" wdcount="10"> ``It appears the men left several days before the explosion''.</s>

<s docid="AP890923-0091" num="24" wdcount="30"> He said the house, which overlooks the barracks recreation center destroyed by the Friday morning blast, was rented by its English owners to three men for two to three weeks.</s>

<s docid="AP890923-0091" num="25" wdcount="13"> There was no proof the house was an IRA hideout, the commander said.</s>

<s docid="AP890923-0091" num="26" wdcount="28"> ``By virtue of the fact that the house is very near the base and the men are Irish, we are very anxious to talk to them,'' he said.</s>

<s docid="AP890923-0091" num="27" wdcount="25"> Explosives experts wearing white protective overalls were painstakingly examining the house Saturday, and Churchill-Coleman said they would continue for the next two or three days.</s>

<s docid="AP890923-0091" num="28" wdcount="16"> Police said all 10 men killed during a coffee break between morning band practices were servicemen.</s>

<s docid="AP890923-0091" num="29" wdcount="12"> Of 22 men injured, 12 remained hospitalized Saturday, five in serious condition.</s>

<s docid="AP890923-0091" num="30" wdcount="18"> The Irish Republican Army on Friday claimed responsibility for the explosion, which also severely damaged several nearby houses.</s>

<s docid="AP890923-0091" num="31" wdcount="24"> Police have not determined what caused the blast, but Churchill-Coleman said, ``It would seem to be some form of improvised device using high explosives''.</s>

<s docid="AP890923-0091" num="32" wdcount="11"> The IRA did not specify how it caused the blast .</s>
</TEXT>
</DOC>
