<DOC>
<DOCNO>

<s docid="AP890922-0103" num="1" wdcount="1"> AP890922-0103</s>
</DOCNO>
<FILEID>

<s docid="AP890922-0103" num="2" wdcount="2"> AP-NR-09-22-89 1143EDT</s>
</FILEID>
<FIRST>

<s docid="AP890922-0103" num="3" wdcount="6"> u i PM-Blast-Witnesses 1stLd-Writethru 09-22 0511</s>
</FIRST>
<SECOND>

<s docid="AP890922-0103" num="4" wdcount="3"> PM-Blast-Witnesses, 1st Ld-Writethru,a0566,0525</s>
</SECOND>
<HEAD>

<s docid="AP890922-0103" num="5" wdcount="11"> Neighbors Tell of Being Jolted out of Bed by `Blitz' Blast</s>
</HEAD>
<HEAD>

<s docid="AP890922-0103" num="6" wdcount="15"> Eds: Subs 3rd pvs, ``The Irish'... with 1 graf to ADD police count of casualties.</s>

<s docid="AP890922-0103" num="7" wdcount="5"> Pickup 4th pvs, `Nearby resident...'</s>
</HEAD>
<HEAD>

<s docid="AP890922-0103" num="8" wdcount="2"> With PM-Britain-Blast</s>
</HEAD>
<BYLINE>

<s docid="AP890922-0103" num="9" wdcount="3"> By MAUREEN JOHNSON</s>
</BYLINE>
<BYLINE>

<s docid="AP890922-0103" num="10" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890922-0103" num="11" wdcount="3"> DEAL, England (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890922-0103" num="12" wdcount="34"> Neighbors were breakfasting, heading to work or asleep in bed when an explosion at a military barracks turned their homes to rubble and they were confronted with the sight of bodies being carried away.</s>

<s docid="AP890922-0103" num="13" wdcount="11"> ``There was a terrific crash which reminded me of the Blitz.</s>

<s docid="AP890922-0103" num="14" wdcount="33"> After that, the ceiling started to fall down around me,'' said Joan Betteridge, a pensioner in the southern England town of Deal, where the blast at the Royal Marines School of Music occurred.</s>

<s docid="AP890922-0103" num="15" wdcount="18"> The Irish Republican Army claimed reponsibilty for the explosion, which police said killed 11 people and injured 22.</s>

<s docid="AP890922-0103" num="16" wdcount="18"> Nearby resident Sean Minnock said: ``I was asleep but woke up with a hell of a jolt ...</s>

<s docid="AP890922-0103" num="17" wdcount="7"> the bedroom ceiling fell in on me.</s>

<s docid="AP890922-0103" num="18" wdcount="13"> I woke to find huge slabs of plaster on the bed and floor''.</s>

<s docid="AP890922-0103" num="19" wdcount="12"> From the wrecked, smoke-clouded barracks, ``I could hear terrified screams of agony.</s>

<s docid="AP890922-0103" num="20" wdcount="8"> People started rushing about all over the place.</s>

<s docid="AP890922-0103" num="21" wdcount="11"> It was horrible to watch and listen to,'' said Minnock, 28.</s>

<s docid="AP890922-0103" num="22" wdcount="7"> ``I knew people had been seriously hurt.</s>

<s docid="AP890922-0103" num="23" wdcount="8"> I saw the rescuers pull out two bodies.</s>

<s docid="AP890922-0103" num="24" wdcount="19"> I knew they were dead when they put them on the floor and put bed blankets right over them''.</s>

<s docid="AP890922-0103" num="25" wdcount="19"> Minnock's wife, Janet, said the roof of their house was torn off and all the back windows were shattered.</s>

<s docid="AP890922-0103" num="26" wdcount="9"> ``The house has been blown to bits,'' she said.</s>

<s docid="AP890922-0103" num="27" wdcount="24"> Mrs. Minnock was feeding her 2-year-old son Thomas his breakfast when the explosion wrecked four terraced houses in the street backing onto the barracks.</s>

<s docid="AP890922-0103" num="28" wdcount="23"> Her next-door neighbor, Heather Hackett, 26, was standing at her kitchen window facing the barracks, holding her 4-month-old son Luke in her arms.</s>

<s docid="AP890922-0103" num="29" wdcount="12"> Her other boys, Ben, 3, and Joshua, 2, were at her side.</s>

<s docid="AP890922-0103" num="30" wdcount="16"> ``I looked up from the sink and I just saw the whole building explode,'' she said.</s>

<s docid="AP890922-0103" num="31" wdcount="19"> ``I told the boys to run and as Joshua turned a sliver of glass embedded itself in his back.</s>

<s docid="AP890922-0103" num="32" wdcount="8"> ``The whole window was blown across the kitchen.</s>

<s docid="AP890922-0103" num="33" wdcount="9"> I just screamed and ran out of the room.</s>

<s docid="AP890922-0103" num="34" wdcount="13"> The bang was so loud I thought the whole house was coming in.</s>

<s docid="AP890922-0103" num="35" wdcount="11"> ``At first I thought for sure Joshua had been seriously injured.</s>

<s docid="AP890922-0103" num="36" wdcount="8"> There was blood coming out of his back''.</s>

<s docid="AP890922-0103" num="37" wdcount="8"> Doctors removed the glass and sent him home.</s>

<s docid="AP890922-0103" num="38" wdcount="19"> College student Simon Mitford, 17, narrowly escaped being injured in the explosion because he got up earlier than usual.</s>

<s docid="AP890922-0103" num="39" wdcount="12"> ``His room was completely wrecked by the blast,'' his brother Alex said.</s>

<s docid="AP890922-0103" num="40" wdcount="19"> Of the barracks, he said: ``I heard music playing and then it went bang and there was glass everywhere.</s>

<s docid="AP890922-0103" num="41" wdcount="13"> It was a two-story building but now 90 percent of it is rubble.</s>

<s docid="AP890922-0103" num="42" wdcount="11"> ``I heard a marine scream out, `The band is under there'.</s>

<s docid="AP890922-0103" num="43" wdcount="11"> I was scared there was going to be a second explosion.''</s>
</TEXT>
</DOC>
