<DOC>
<DOCNO>

<s docid="AP890922-0117" num="1" wdcount="1"> AP890922-0117</s>
</DOCNO>
<FILEID>

<s docid="AP890922-0117" num="2" wdcount="2"> AP-NR-09-22-89 1241EDT</s>
</FILEID>
<FIRST>

<s docid="AP890922-0117" num="3" wdcount="7"> u i PM-Britain-Blast 9thLd-Writethru a0619 09-22 0844</s>
</FIRST>
<SECOND>

<s docid="AP890922-0117" num="4" wdcount="4"> PM-Britain-Blast, 9th Ld-Writethru, a0619,0865</s>
</SECOND>
<HEAD>

<s docid="AP890922-0117" num="5" wdcount="7"> 11 Dead, 22 Injured in IRA Explosion</s>
</HEAD>
<HEAD>

<s docid="AP890922-0117" num="6" wdcount="17"> Eds: Leads with 4 grafs to UPDATE with all accounted for, many of the injured seriously hurt.</s>

<s docid="AP890922-0117" num="7" wdcount="5"> Pickup 4th graf, ``There was...''</s>
</HEAD>
<HEAD>

<s docid="AP890922-0117" num="8" wdcount="2"> LaserPhoto LON6</s>
</HEAD>
<BYLINE>

<s docid="AP890922-0117" num="9" wdcount="3"> By MAUREEN JOHNSON</s>
</BYLINE>
<BYLINE>

<s docid="AP890922-0117" num="10" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890922-0117" num="11" wdcount="3"> DEAL, England (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890922-0117" num="12" wdcount="20"> An explosion today flattened a military barracks and tore through nearby homes, killing 11 people and injuring 22, police said.</s>

<s docid="AP890922-0117" num="13" wdcount="7"> The IRA claimed responsibility for the blast.</s>

<s docid="AP890922-0117" num="14" wdcount="25"> More than 100 rescue workers frantically dug through the rubble of a three-story building that collapsed at the Royal Marines School of Music near Deal.</s>

<s docid="AP890922-0117" num="15" wdcount="10"> Stunned neighbors gathered outside homes that were damaged or destroyed.</s>

<s docid="AP890922-0117" num="16" wdcount="32"> Chief Police Inspector Alan Butterfield of Kent, who who provided the casualty figures and coordinated the rescue effort, first reported that one person was missing but later said everyone was accounted for.</s>

<s docid="AP890922-0117" num="17" wdcount="9"> He said many of the injured were seriously hurt.</s>

<s docid="AP890922-0117" num="18" wdcount="11"> ``There was a terrific crash which reminded me of the Blitz.</s>

<s docid="AP890922-0117" num="19" wdcount="14"> After that, the ceiling started to fall down around me,'' said pensioner Joan Betteridge.</s>

<s docid="AP890922-0117" num="20" wdcount="32"> Defense Secretary Tom King, inspecting the wreckage, said: ``It is not yet absolutely confirmed that it is a bomb, but all the evidence is quite clearly that this is an IRA atrocity''.</s>

<s docid="AP890922-0117" num="21" wdcount="49"> British military installations are a frequent bombing target of the Irish Republican Army in its campaign to rid Northern Ireland of British rule, but today's explosion in the coastal town 70 miles southeast of London was the worst IRA attack on the British mainland in more than seven years.</s>

<s docid="AP890922-0117" num="22" wdcount="13"> The explosion occurred at at 8:26 a.m. in a lounge in the barracks.</s>

<s docid="AP890922-0117" num="23" wdcount="23"> One of the bands had just stopped playing on the parade ground, said a ministry spokesman, speaking anonymously in keeping with British custom.</s>

<s docid="AP890922-0117" num="24" wdcount="13"> Dozens of homes near the school were damaged, including four that were destroyed.</s>

<s docid="AP890922-0117" num="25" wdcount="8"> Witnesses reported hearing the explosion two miles away.</s>

<s docid="AP890922-0117" num="26" wdcount="17"> The Defense Ministry would not say how many servicemen and civilians were included in the casualty figures.</s>

<s docid="AP890922-0117" num="27" wdcount="11"> However, King told reporters the attack was directed against ``unarmed bandsmen''.</s>

<s docid="AP890922-0117" num="28" wdcount="20"> Firefighters used heavy lifting equipment and thermal cameras to search through the debris, said Kent Fire Brigade spokesman Kevin Simmons.</s>

<s docid="AP890922-0117" num="29" wdcount="23"> Ten doctors were giving emergency treatment at the scene and 11 ambulances were taking the injured to two hospitals, the ambulance service said.</s>

<s docid="AP890922-0117" num="30" wdcount="33"> A statement telephoned to Ireland International, a Dublin news agency, said ``we have visited the Royal Marines in Kent'' in response to Prime Minister Margaret Thatcher's visit to Northern Ireland nine days ago.</s>

<s docid="AP890922-0117" num="31" wdcount="30"> The IRA said Mrs. Thatcher went to the British province ``with a message of war,'' but ``we still want peace and we want the British government to leave our country''.</s>

<s docid="AP890922-0117" num="32" wdcount="21"> It was signed P. O'Neill, a nom de guerre the IRA usually uses to claim responsibility for actions outside Northern Ireland.</s>

<s docid="AP890922-0117" num="33" wdcount="17"> Irish Prime Minister Charles Haughey issued a statement in Dublin condemning the attack, calling it an ``outrage''.</s>

<s docid="AP890922-0117" num="34" wdcount="30"> The last IRA bomb attempt on the British mainland was in February when about 60 soldiers were evacuated from their barracks in Shropshire, western England, just before a bomb exploded.</s>

<s docid="AP890922-0117" num="35" wdcount="22"> One soldier was killed and nine wounded in an IRA bomb attack on an army barracks in north London in August 1988.</s>

<s docid="AP890922-0117" num="36" wdcount="32"> In July 1982, eight soldiers died in IRA bombings near the Household Cavalry barracks in central London and at a bandstand in the capital's Regent's Park where an army band was playing.</s>

<s docid="AP890922-0117" num="37" wdcount="14"> Three people died later and a total of 51 were injured in the bombings.</s>

<s docid="AP890922-0117" num="38" wdcount="20"> The music school is the training center for young recruits who want to play in the seven Royal Marines bands.</s>

<s docid="AP890922-0117" num="39" wdcount="22"> Up to 250 young men, most between 16 and 20, are based at the school, where they receive military and musical training.</s>

<s docid="AP890922-0117" num="40" wdcount="22"> The roof of Janet Minnock's house was torn off by the force of the blast and all the back windows were shattered.</s>

<s docid="AP890922-0117" num="41" wdcount="9"> ``The house has been blown to bits,'' she said.</s>

<s docid="AP890922-0117" num="42" wdcount="5"> ``We are all shaken up''.</s>

<s docid="AP890922-0117" num="43" wdcount="23"> Mrs. Minnock's next-door neighbor, Heather Hackett, said she was standing at her kitchen window facing the barracks at the time of the explosion.</s>

<s docid="AP890922-0117" num="44" wdcount="22"> She was holding her 4-month-old son Luke in her arms with her other boys, Ben, 3, and Joshua, 2, at her side.</s>

<s docid="AP890922-0117" num="45" wdcount="16"> ``I looked up from the sink and I just saw the whole building explode,'' she said.</s>

<s docid="AP890922-0117" num="46" wdcount="19"> ``I told the boys to run and as Joshua turned a slither of glass embedded itself in his back.</s>

<s docid="AP890922-0117" num="47" wdcount="8"> The whole window was blown across the kitchen.</s>

<s docid="AP890922-0117" num="48" wdcount="9"> I just screamed and ran out of the room.</s>

<s docid="AP890922-0117" num="49" wdcount="13"> The bang was so loud I thought the whole house was coming in''.</s>

<s docid="AP890922-0117" num="50" wdcount="15"> Sean Minnock said: ``I was asleep but woke up with a hell of a jolt''.</s>

<s docid="AP890922-0117" num="51" wdcount="18"> As workers tried to patch holes in his roof, he said: ``The bedroom ceiling fell in on me.</s>

<s docid="AP890922-0117" num="52" wdcount="13"> I woke to find huge slabs of plaster on the bed and floor.</s>

<s docid="AP890922-0117" num="53" wdcount="5"> I wondered what it was.</s>

<s docid="AP890922-0117" num="54" wdcount="22"> As soon as I got up I looked out of what was left of the window and knew it was the barracks.''</s>
</TEXT>
</DOC>
