<DOC>
<DOCNO>

<s docid="LA092389-0092" num="1" wdcount="1"> LA092389-0092</s>
</DOCNO>
<DOCID>

<s docid="LA092389-0092" num="2" wdcount="1"> 111274</s>
</DOCID>
<DATE>
<P>

<s docid="LA092389-0092" num="3" wdcount="6"> September 23, 1989, Saturday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA092389-0092" num="4" wdcount="8"> Part 1; Page 1; Column 3; Foreign Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA092389-0092" num="5" wdcount="2"> 980 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA092389-0092" num="6" wdcount="10"> 10 KILLED, 22 HURT BY IRA BOMB AT ENGLAND BARRACKS</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA092389-0092" num="7" wdcount="6"> By DAN FISHER, Times Staff Writer</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA092389-0092" num="8" wdcount="1"> LONDON</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA092389-0092" num="9" wdcount="33"> The Irish Republican Army claimed responsibility for a huge explosion Friday that reduced a three-story military barracks on the southeast coast of England to rubble, killing 10 people and injuring 22, eight seriously.</s>

<s docid="LA092389-0092" num="10" wdcount="16"> It would be one of the outlawed IRA's deadliest attacks on the main British island .</s>
</P>
<P>

<s docid="LA092389-0092" num="11" wdcount="24"> Nine marine musicians and one civilian died in the blast, which also damaged dozens of nearby homes and could be heard two miles away.</s>

<s docid="LA092389-0092" num="12" wdcount="20"> The musicians were between the ages of 16 and 20 as are most of the recruits in the school .</s>
</P>
<P>

<s docid="LA092389-0092" num="13" wdcount="22"> A police spokesman said forensic experts are still trying to determine with certainty that the explosion was the result of a bomb.</s>

<s docid="LA092389-0092" num="14" wdcount="25"> But he said the characteristics of the blast and a statement claiming responsibility appeared to confirm that it was the work of the IRA .</s>
</P>
<P>

<s docid="LA092389-0092" num="15" wdcount="28"> Security sources said they believe that at least two IRA "active service" units, each composed of four or five members, are operating in Britain and continental Europe .</s>
</P>
<P>

<s docid="LA092389-0092" num="16" wdcount="27"> One member, known as the "Jackal" after the assassin in the Frederick Forsyth novel "The Day of the Jackal," has been eluding the authorities for two years.</s>

<s docid="LA092389-0092" num="17" wdcount="30"> He has been identified as Patrick Sheehy and has been linked to the IRA's last successful mainland bombing attack -- on an army barracks at Mill Hill in August, 1988.</s>

<s docid="LA092389-0092" num="18" wdcount="8"> One soldier was killed in that incident .</s>
</P>
<P>

<s docid="LA092389-0092" num="19" wdcount="31"> Sheehy and another wanted Irishman, John Conaghty, were linked to an IRA bomb factory in North London that the police stumbled upon last December while in pursuit of a car thief.</s>

<s docid="LA092389-0092" num="20" wdcount="34"> A search turned up automatic and semiautomatic weapons, ammunition, 150 pounds of Semtex high explosive and a "hit list" of 100 British political figures and other officials headed by Prime Minister Margaret Thatcher .</s>
</P>
<P>

<s docid="LA092389-0092" num="21" wdcount="27"> Friday's explosion occurred about 8:30 a.m. in a lounge at the Royal Marines School of Music near Deal, on the English Channel in the county of Kent.</s>

<s docid="LA092389-0092" num="22" wdcount="19"> At the school are about 250 recruits who receive military and musical training before joining Royal Marines bands .</s>
</P>
<P>

<s docid="LA092389-0092" num="23" wdcount="12"> The roof of the three-story barracks collapsed, trapping victims beneath the rubble.</s>

<s docid="LA092389-0092" num="24" wdcount="14"> Firefighters used thermal cameras and dogs to search the debris for victims and survivors.</s>

<s docid="LA092389-0092" num="25" wdcount="23"> Heavy lifting gear was brought to the scene from a nearby site where a tunnel is being built beneath the English Channel .</s>
</P>
<P>

<s docid="LA092389-0092" num="26" wdcount="21"> Rescuers shouted for quiet as they used high-technology listening equipment in an effort to trace the sound of faint heartbeats .</s>
</P>
<P>

<s docid="LA092389-0092" num="27" wdcount="25"> "I looked up from the sink and I just saw the whole building explode," Heather Hackett, a 26-year-old Deal housewife, told the British Press Assn.</s>

<s docid="LA092389-0092" num="28" wdcount="19"> She said she told her children to run for cover, but as they did, her kitchen window shattered .</s>
</P>
<P>

<s docid="LA092389-0092" num="29" wdcount="10"> "The whole window was blown across the kitchen," Hackett recalled.</s>

<s docid="LA092389-0092" num="30" wdcount="21"> Her 2-year-old son, Joshua, was hit by a shard that embedded itself in his back but caused no serious injury .</s>
</P>
<P>

<s docid="LA092389-0092" num="31" wdcount="11"> "I just screamed and ran out of the room," she said.</s>

<s docid="LA092389-0092" num="32" wdcount="14"> "The bang was so loud I thought the whole house was coming in" .</s>
</P>
<P>
</P>
<P>

<s docid="LA092389-0092" num="33" wdcount="2"> 'Appalling Outrage'</s>
</P>
<P>

<s docid="LA092389-0092" num="34" wdcount="40"> Defense Secretary Tom King visited the scene and called the bombing "an appalling outrage committed against unarmed bandsmen -- people who worked for charity, who have given great enjoyment to millions right across the country, right across the world .</s>
</P>
<P>

<s docid="LA092389-0092" num="35" wdcount="28"> "The real evil of these murders is that the people who commit them, the 'godfathers' who send them to commit them, know that they will actually achieve nothing.</s>

<s docid="LA092389-0092" num="36" wdcount="6"> Terrorism is not going to win.</s>

<s docid="LA092389-0092" num="37" wdcount="33"> We shall find the people responsible for this outrage sooner or later, as we have already found some of those responsible for the earlier outrages, and they will be brought to justice" .</s>
</P>
<P>

<s docid="LA092389-0092" num="38" wdcount="26"> The authorities have been on high alert, expecting IRA attacks in connection with last month's 20th anniversary of the introduction of British troops into Northern Ireland.</s>

<s docid="LA092389-0092" num="39" wdcount="28"> The republican underground organization opposes British rule in the predominantly Protestant province and is fighting to join the mainly Roman Catholic south in a united, independent Ireland .</s>
</P>
<P>
</P>
<P>

<s docid="LA092389-0092" num="40" wdcount="3"> Visit to Ulster</s>
</P>
<P>

<s docid="LA092389-0092" num="41" wdcount="33"> But in a statement telephoned to a Dublin news agency, Ireland International, Friday's attack was linked to Thatcher's visit last week to units of the controversial Ulster Defense Regiment in Northern Ireland .</s>
</P>
<P>

<s docid="LA092389-0092" num="42" wdcount="32"> The locally recruited, overwhelmingly Protestant Ulster Defense Regiment has come under fire in connection with an investigation into the leak of secret government lists of suspected IRA members to Protestant assassination squads.</s>

<s docid="LA092389-0092" num="43" wdcount="25"> It is widely hated by the Catholic minority in the province, and the Irish government in Dublin has urged Britain to disband the force .</s>
</P>
<P>

<s docid="LA092389-0092" num="44" wdcount="25"> "Mrs. Thatcher visited Ireland with a message of war at a time when we want peace," the statement claiming responsibility for the Deal attack said.</s>

<s docid="LA092389-0092" num="45" wdcount="11"> "Now in turn we have visited the Royal Marines in Kent.</s>

<s docid="LA092389-0092" num="46" wdcount="16"> But we still want peace, and we want the British government to leave our country" .</s>
</P>
<P>

<s docid="LA092389-0092" num="47" wdcount="5"> The statement was signed "P.</s>

<s docid="LA092389-0092" num="48" wdcount="16"> O'Neill, Irish Republican Publicity Bureau," a signature that has appeared on earlier IRA bombing claims .</s>
</P>
<P>

<s docid="LA092389-0092" num="49" wdcount="28"> Friday's attack was the worst on the mainland since the virtually simultaneous bombings of July, 1982, directed at ceremonial military units in London's Hyde Park and Regent's Park.</s>

<s docid="LA092389-0092" num="50" wdcount="11"> Eleven bandsmen and mounted guards were killed in those incidents .</s>
</P>
<P>

<s docid="LA092389-0092" num="51" wdcount="35"> Eight persons were killed by IRA car bombs outside Harrods department store here in December, 1983, and 21 were killed and 162 injured in two Birmingham public house bombings in the fall of 1974 .</s>
</P>
<P>

<s docid="LA092389-0092" num="52" wdcount="27"> An attempted barracks bombing was averted last February when a sentry came upon two intruders who had managed to get inside a military camp in Shropshire .</s>
</P>
<P>

<s docid="LA092389-0092" num="53" wdcount="23"> There has been a series of bomb and automatic rifle attacks this year on British soldiers and their families stationed in West Germany.</s>

<s docid="LA092389-0092" num="54" wdcount="24"> Earlier this month an IRA gunman shot to death an army wife, Heidi Hazell, 25, in her car near her home at Dortmund .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA092389-0092" num="55" wdcount="23"> Photo, Rescue workers use earth mover to dig through barracks at Royal Marines School of Music in frantic effort to locate bomb victims.</s>

<s docid="LA092389-0092" num="56" wdcount="11"> Associated Press; Map, Barracks Blast Site, AP / Los Angeles Times</s>
</P>
</GRAPHIC>
<SUBJECT>
<P>

<s docid="LA092389-0092" num="57" wdcount="24"> IRISH REPUBLICAN ARMY; BOMBINGS -- ENGLAND; ENGLAND -- ARMED FORCES; TERRORISM -- ENGLAND; ENGLAND -- FOREIGN RELATIONS -- NORTHERN IRELAND; NORTHERN IRELAND -- REVOLTS</s>
</P>
</SUBJECT>
</DOC>
