<DOC>
<DOCNO>

<s docid="AP890603-0122" num="1" wdcount="1"> AP890603-0122</s>
</DOCNO>
<FILEID>

<s docid="AP890603-0122" num="2" wdcount="2"> AP-NR-06-03-89 2002EST</s>
</FILEID>
<FIRST>

<s docid="AP890603-0122" num="3" wdcount="5"> u i AM-China-ClashChronology 06-03 0451</s>
</FIRST>
<SECOND>

<s docid="AP890603-0122" num="4" wdcount="2"> AM-China-Clash Chronology,0470</s>
</SECOND>
<HEAD>

<s docid="AP890603-0122" num="5" wdcount="6"> Chronology of Violence Around Tiananmen Square</s>
</HEAD>
<HEAD>

<s docid="AP890603-0122" num="6" wdcount="3"> With AM-China, Bjt</s>
</HEAD>
<DATELINE>

<s docid="AP890603-0122" num="7" wdcount="2"> BEIJING (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890603-0122" num="8" wdcount="38"> Here is a chronology of events that began Saturday in Tiananmen Square: 1 a.m. Saturday (12 noon EDT Friday) _ Tens of thousands of troops enter Beijing from the east marching toward Tiananmen Square, China's symbolic political heart.</s>

<s docid="AP890603-0122" num="9" wdcount="11"> Military units also seen approaching from the west and the north.</s>

<s docid="AP890603-0122" num="10" wdcount="2"> 2 a.m.</s>

<s docid="AP890603-0122" num="11" wdcount="20"> _ The main body of troops is stopped several hundred yards east of the vast square by thousands of people.</s>

<s docid="AP890603-0122" num="12" wdcount="5"> 2 a.m. to 9 a.m.</s>

<s docid="AP890603-0122" num="13" wdcount="18"> _ Troops straggle away from their positions near the square, walking in small groups followed by watchful residents.</s>

<s docid="AP890603-0122" num="14" wdcount="24"> 12 noon _ Two truckloads of People's Armed Police attack crowds outside Beijing Hotel east of the square and up to 30 people injured.</s>

<s docid="AP890603-0122" num="15" wdcount="2"> 2 p.m.</s>

<s docid="AP890603-0122" num="16" wdcount="23"> _ About 5,000 troops emerge from Great Hall of the People on the western side of the square and are surrounded by crowds.</s>

<s docid="AP890603-0122" num="17" wdcount="20"> People's Armed Police fire tear gas and use clubs to beat protesters west of the square in a 30-minute attack.</s>

<s docid="AP890603-0122" num="18" wdcount="2"> 4:30 p.m.</s>

<s docid="AP890603-0122" num="19" wdcount="12"> _ Stone- and bottle-throwing demonstrators skirmish with troops outside the Great Hall.</s>

<s docid="AP890603-0122" num="20" wdcount="5"> Troops swinging belts attack crowds.</s>

<s docid="AP890603-0122" num="21" wdcount="6"> Some soldiers injured by flying debris.</s>

<s docid="AP890603-0122" num="22" wdcount="2"> 6 p.m.</s>

<s docid="AP890603-0122" num="23" wdcount="15"> _ Thousands of residents surround two troop convoys on a main highway in northeastern Beijing.</s>

<s docid="AP890603-0122" num="24" wdcount="2"> 7 p.m.</s>

<s docid="AP890603-0122" num="25" wdcount="20"> _ National television repeats martial law regulations and warns people to stay off the streets and away from Tiananmen Square.</s>

<s docid="AP890603-0122" num="26" wdcount="2"> 8:30 p.m.</s>

<s docid="AP890603-0122" num="27" wdcount="7"> _ Troops retreat into the Great Hall.</s>

<s docid="AP890603-0122" num="28" wdcount="2"> 9 p.m.</s>

<s docid="AP890603-0122" num="29" wdcount="30"> _ More than 20,000 people block a 26-truck convoy about 2 miles east of the square and thousands of others converge on the square to protect students demanding demoncratic reforms.</s>

<s docid="AP890603-0122" num="30" wdcount="11"> Crowds throw rocks at troop contingent 4 miles west of Tiananmen.</s>

<s docid="AP890603-0122" num="31" wdcount="3"> 9 p.m.-10 p.m.</s>

<s docid="AP890603-0122" num="32" wdcount="11"> _ Troops hurl tear gas then open fire on the crowds.</s>

<s docid="AP890603-0122" num="33" wdcount="23"> 12 midnight _ Armored vehicles break through barricades and about 40 trucks carrying military personnel slowly advance toward the square from the west.</s>

<s docid="AP890603-0122" num="34" wdcount="3"> 1 a.m. Sunday.</s>

<s docid="AP890603-0122" num="35" wdcount="19"> Troops dash through flames caused by a burning-bus barricade at the major intersection of Xidan west of the square.</s>

<s docid="AP890603-0122" num="36" wdcount="8"> More people shot as troops fire at crowds.</s>

<s docid="AP890603-0122" num="37" wdcount="17"> A smaller group of about 1,000 military personnel enters the square from the east and shooting erupts.</s>

<s docid="AP890603-0122" num="38" wdcount="2"> 2 a.m.</s>

<s docid="AP890603-0122" num="39" wdcount="19"> _ Thousands of troops arrive at the west side of the square and some of the riflemen open fire.</s>

<s docid="AP890603-0122" num="40" wdcount="2"> 3:30 a.m.</s>

<s docid="AP890603-0122" num="41" wdcount="11"> _ Military units surround the square, trapping several thousand students inside.</s>

<s docid="AP890603-0122" num="42" wdcount="2"> 4:30 a.m.</s>

<s docid="AP890603-0122" num="43" wdcount="7"> _ Armored personnel carriers enter the square.</s>

<s docid="AP890603-0122" num="44" wdcount="14"> Students are told by loudspeaker that troops will move in and clear the area.</s>

<s docid="AP890603-0122" num="45" wdcount="2"> 5 a.m.</s>

<s docid="AP890603-0122" num="46" wdcount="14"> _ Demonstrators, many walking hand-in-hand, begin leaving the square, ending their three-week occupation .</s>
</TEXT>
</DOC>
