<DOC>
<DOCNO>

<s docid="AP890603-0103" num="1" wdcount="1"> AP890603-0103</s>
</DOCNO>
<FILEID>

<s docid="AP890603-0103" num="2" wdcount="2"> AP-NR-06-03-89 1636EST</s>
</FILEID>
<FIRST>

<s docid="AP890603-0103" num="3" wdcount="6"> u i AM-China 5thLd-Writethru-2Takes 06-03 0808</s>
</FIRST>
<SECOND>

<s docid="AP890603-0103" num="4" wdcount="6"> AM-China, 5th Ld-Writethru - 2 Takes,a0583,0832</s>
</SECOND>
<HEAD>

<s docid="AP890603-0103" num="5" wdcount="1"> URGENT</s>
</HEAD>
<HEAD>

<s docid="AP890603-0103" num="6" wdcount="9"> Death Toll at 32 as Troops Storm Tiananmen Square</s>
</HEAD>
<HEAD>

<s docid="AP890603-0103" num="7" wdcount="15"> Eds: LEADS throughout to UPDATE with armored personal carriers entering square; U.S. reaction; no pickup</s>
</HEAD>
<BYLINE>

<s docid="AP890603-0103" num="8" wdcount="3"> By JOHN POMFRET</s>
</BYLINE>
<BYLINE>

<s docid="AP890603-0103" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890603-0103" num="10" wdcount="2"> BEIJING (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890603-0103" num="11" wdcount="29"> Chinese troops stormed Tiananmen Square early Sunday, shooting and beating their way through crowds of pro-democracy protesters in clashes that witnesses and doctors said killed at least 32 people.</s>

<s docid="AP890603-0103" num="12" wdcount="3"> Hundreds were wounded.</s>

<s docid="AP890603-0103" num="13" wdcount="27"> The troops cut a violent swath through the heart of Beijing to get to the the square, rolling through barricades and surging masses on the surrounding streets.</s>

<s docid="AP890603-0103" num="14" wdcount="27"> By 3:30 a.m., soldiers and riot police had surrounded Tiananmen, boxing off several thousand students and supporters concentrated around a monument to revolutionary heroes in the center.</s>

<s docid="AP890603-0103" num="15" wdcount="8"> A half hour later, lights were turned out.</s>

<s docid="AP890603-0103" num="16" wdcount="5"> The square was in darkness.</s>

<s docid="AP890603-0103" num="17" wdcount="15"> ``You have to give up all hope,'' students said over their loudspeaker at the monument.</s>

<s docid="AP890603-0103" num="18" wdcount="9"> ``You have to give your life to the movement''.</s>

<s docid="AP890603-0103" num="19" wdcount="7"> Students sang the ``Internationale,'' the communist anthem.</s>

<s docid="AP890603-0103" num="20" wdcount="28"> At 4:30 a.m., armored personnel carriers entered the square and troops began moving slowly toward several thousand students clustered around a monument to revolutionary heroes in the center.</s>

<s docid="AP890603-0103" num="21" wdcount="19"> Sporadic gunfire could still be heard on the outskirts of the square as troops shot at crowds of thousands.</s>

<s docid="AP890603-0103" num="22" wdcount="11"> The death and casualty toll was believed to be mounting rapidly.</s>

<s docid="AP890603-0103" num="23" wdcount="12"> Ambulances and bicycle pedicabs went back and forth hauling away the wounded.</s>

<s docid="AP890603-0103" num="24" wdcount="12"> One man was seen shot in the back, another in the head.</s>

<s docid="AP890603-0103" num="25" wdcount="26"> An official loudspeaker on the square announced that the troops were moving in to clear the area as soldiers prepared to advance from all four sides.</s>

<s docid="AP890603-0103" num="26" wdcount="24"> Ho Te-chien, a Taiwanese singer who defected to China in 1983 and has been active in the student movement, urged the students to leave.</s>

<s docid="AP890603-0103" num="27" wdcount="18"> ``We're not afraid to die, but we've already lost too much blood,'' he said over a student loudspeaker.</s>

<s docid="AP890603-0103" num="28" wdcount="16"> A 33-foot-high replica of the Statue of Liberty, set up by students last week, remained standing.</s>

<s docid="AP890603-0103" num="29" wdcount="13"> The main streets leading to the Tiananmen, China's symbolic political center, were sealed.</s>

<s docid="AP890603-0103" num="30" wdcount="23"> Thousands fled from the square, where hundreds of thousands of people had gathered to support students in the third week of a sit-in.</s>

<s docid="AP890603-0103" num="31" wdcount="20"> The assault came two weeks after Premier Li Peng declared martial law in Beijing and sent troops to the city.</s>

<s docid="AP890603-0103" num="32" wdcount="14"> Hundreds of thousands of residents responded by blocking roads with trucks and their bodies.</s>

<s docid="AP890603-0103" num="33" wdcount="20"> In Washington, Secretary of State James A. Baker III said Saturday the situation in China had become ``ugly and chaotic.</s>

<s docid="AP890603-0103" num="34" wdcount="16"> ``This will disturb the United States government, and will disturb the American people, considerably,'' he said.</s>

<s docid="AP890603-0103" num="35" wdcount="15"> The secretary hinted that there could be repercussions to the Chinese government's use of violence.</s>

<s docid="AP890603-0103" num="36" wdcount="34"> The standoff between troops and protesters had been tense but largely peaceful for weeks, with soldiers seemingly reluctant or unable to move against the crowds until the first widespread violence broke out Saturday afternoon.</s>

<s docid="AP890603-0103" num="37" wdcount="35"> A doctor from the Fuxing Hospital in western Beijing, where troops began firing on street people, said the hospital had taken in 15 dead and so many wounded they had to be put in garages.</s>

<s docid="AP890603-0103" num="38" wdcount="10"> A doctor from another hospital said 12 people died there.</s>

<s docid="AP890603-0103" num="39" wdcount="31"> One soldier was killed when he was run over by an armored personnel carrier rushing toward the square, and another man was reported shot to death in a street clash elsewhere.</s>

<s docid="AP890603-0103" num="40" wdcount="19"> A Swedish visitor, Tom Hansson, said he saw three people shot to death in clashes south of the square.</s>

<s docid="AP890603-0103" num="41" wdcount="4"> ``The government is fascist!</s>

<s docid="AP890603-0103" num="42" wdcount="7"> How can they do this to me?</s>

<s docid="AP890603-0103" num="43" wdcount="18"> How can they do this to the people''? cried a 28-year-old man who was shot in the leg.</s>

<s docid="AP890603-0103" num="44" wdcount="20"> Most of those shot on the square were hurling rocks at the troops and people close to their front lines.</s>

<s docid="AP890603-0103" num="45" wdcount="24"> A government loudspeaker on the square charged the students with ``counterrevolutionary turmoil'' and said the military was taking necessary means to end their rebellion.</s>

<s docid="AP890603-0103" num="46" wdcount="19"> Sporadic clashes and dozens of injuries were reported on Saturday as soldiers made several attempts to reach the square.</s>

<s docid="AP890603-0103" num="47" wdcount="35"> They retreated momentarily under barrages of rocks, shoes and other objects, then resumed their most violent push at about 8 p.m. Saturday, firing weapons and using tear gas and clubs as they moved toward Tiananmen.</s>

<s docid="AP890603-0103" num="48" wdcount="21"> Thousands of troops armed with rifles marched up the east side of the square, beating people who got in their way.</s>

<s docid="AP890603-0103" num="49" wdcount="9"> Students threw Molotov cocktails and other objects at them.</s>

<s docid="AP890603-0103" num="50" wdcount="24"> One armored personnel carrier rammed into a burning bus on Changan Avenue, the main street running along the square, and was torched by students.</s>

<s docid="AP890603-0103" num="51" wdcount="12"> Two people inside were dragged out by the crowds and beaten severely.</s>

<s docid="AP890603-0103" num="52" wdcount="27"> Other armored personnel carriers drove up and down the avenue smashing down lane dividers and other barriers set up by citizens to block the army's way .</s>
</TEXT>
<NOTE>

<s docid="AP890603-0103" num="53" wdcount="1"> MORE</s>
</NOTE>
</DOC>
