<DOC>
<DOCNO>

<s docid="AP890607-0067" num="1" wdcount="1"> AP890607-0067</s>
</DOCNO>
<FILEID>

<s docid="AP890607-0067" num="2" wdcount="2"> AP-NR-06-07-89 0844EST</s>
</FILEID>
<FIRST>

<s docid="AP890607-0067" num="3" wdcount="5"> u i PM-China-Casualties 06-07 0447</s>
</FIRST>
<SECOND>

<s docid="AP890607-0067" num="4" wdcount="1"> PM-China-Casualties,0466</s>
</SECOND>
<HEAD>

<s docid="AP890607-0067" num="5" wdcount="6"> Reports Vary on Number of Casualties</s>
</HEAD>
<HEAD>

<s docid="AP890607-0067" num="6" wdcount="3"> With PM-China, Bjt</s>
</HEAD>
<DATELINE>

<s docid="AP890607-0067" num="7" wdcount="2"> BEIJING (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890607-0067" num="8" wdcount="21"> The Chinese government says that 300 soldiers, ``thugs,'' bystanders and students have been killed during the martial law occupation of Beijing.</s>

<s docid="AP890607-0067" num="9" wdcount="9"> But most other estimates of casualties are far higher.</s>

<s docid="AP890607-0067" num="10" wdcount="29"> State Council spokesman Yuan Mu said on Tuesday that 7,000 people, including 5,000 soldiers, have been injured and 400 other soldiers are missing and may be dead or wounded.</s>

<s docid="AP890607-0067" num="11" wdcount="22"> Non-official sources say Yuan's figures on civilian casualties are far too low, but most have different estimates on the number of victims.</s>

<s docid="AP890607-0067" num="12" wdcount="8"> They range from 500 to 12,000 people slain.</s>

<s docid="AP890607-0067" num="13" wdcount="22"> In Washington, U.S. intelligence reports indicate 3,000 people probably were killed, according to a U.S. official who spoke on condition of anonymity.</s>

<s docid="AP890607-0067" num="14" wdcount="11"> He said estimates of the number of dead could go higher.</s>

<s docid="AP890607-0067" num="15" wdcount="33"> Nearly all of the deaths and injuries occurred Saturday night and early Sunday when troops, firing randomly into large crowds, smashed through barricades to reach Tiananmen square and attack demonstrators demanding democratic reforms.</s>

<s docid="AP890607-0067" num="16" wdcount="17"> One doctor said Sunday that a quick check of 10 hospitals placed the death toll at 500.</s>

<s docid="AP890607-0067" num="17" wdcount="15"> Other sources, compiling various reports and surveys, estimated more than 1,000 people had been killed.</s>

<s docid="AP890607-0067" num="18" wdcount="11"> That number has increased with additional details and rumors of killings.</s>

<s docid="AP890607-0067" num="19" wdcount="22"> Some officials of China's Red Cross said 2,600 people were killed but Beijing's Red Cross office has refused to provide any figures.</s>

<s docid="AP890607-0067" num="20" wdcount="10"> One Hong Kong newspaper reported 5,000 deaths and 30,000 injured.</s>

<s docid="AP890607-0067" num="21" wdcount="26"> An Eastern European diplomat, whose country has good relations with China, insisted that 12,000 people were slain by soldiers as they attacked protesters in Tiananmen Square.</s>

<s docid="AP890607-0067" num="22" wdcount="5"> That figure is certainly high.</s>

<s docid="AP890607-0067" num="23" wdcount="21"> Probably fewer than 10,000 people were in the square when the troops moved in and most were able to escape unharmed.</s>

<s docid="AP890607-0067" num="24" wdcount="36"> But students who had joined the Tiananmen occupation said hundreds of colleagues from the Academy of Fine Arts who were huddled around their ``Goddess of Democracy'' statue in the square were shot or crushed by tanks.</s>

<s docid="AP890607-0067" num="25" wdcount="16"> Beijing University students said 150 of their fellow students who were in the square are missing.</s>

<s docid="AP890607-0067" num="26" wdcount="31"> There were rumors that after the square was cleared troops burned many corpses in large bonfires and other bodies were removed by helicopters and garbage trucks to minimize the death count.</s>

<s docid="AP890607-0067" num="27" wdcount="13"> Yuan's statement said only 23 of the 300 people fatally injured were students.</s>

<s docid="AP890607-0067" num="28" wdcount="10"> The exact number of people killed may never be known.</s>

<s docid="AP890607-0067" num="29" wdcount="24"> Victims were taken to dozens of hospitals, clinics and homes, and there is no indication the government will reveal many details of the tragedy.</s>

<s docid="AP890607-0067" num="30" wdcount="5"> And the death toll mounts.</s>

<s docid="AP890607-0067" num="31" wdcount="16"> Troops manning checkpoints in central Beijing continue to fire on unfriendly crowds and victims fall .</s>
</TEXT>
</DOC>
