<DOC>
<DOCNO>

<s docid="AP890609-0036" num="1" wdcount="1"> AP890609-0036</s>
</DOCNO>
<FILEID>

<s docid="AP890609-0036" num="2" wdcount="2"> AP-NR-06-09-89 0231EST</s>
</FILEID>
<FIRST>

<s docid="AP890609-0036" num="3" wdcount="6"> u i PM-TiananmenRevealed Bjt 06-09 0506</s>
</FIRST>
<SECOND>

<s docid="AP890609-0036" num="4" wdcount="3"> PM-Tiananmen Revealed, Bjt,0518</s>
</SECOND>
<HEAD>

<s docid="AP890609-0036" num="5" wdcount="10"> Freedom Signs Gone, Tiananmen Square is Now an Armed Camp</s>
</HEAD>
<HEAD>

<s docid="AP890609-0036" num="6" wdcount="6"> With PM-Six Days in China, Bjt</s>
</HEAD>
<HEAD>

<s docid="AP890609-0036" num="7" wdcount="3"> An AP Extra</s>
</HEAD>
<BYLINE>

<s docid="AP890609-0036" num="8" wdcount="3"> By JOHN POMFRET</s>
</BYLINE>
<BYLINE>

<s docid="AP890609-0036" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890609-0036" num="10" wdcount="2"> BEIJING (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890609-0036" num="11" wdcount="26"> Gone from Tiananmen Square are the pro-democracy banners and the tents of China's freedom movement, replaced by tanks, armed guards and the chants of drilling soldiers.</s>

<s docid="AP890609-0036" num="12" wdcount="36"> The army on Thursday allowed the people of Beijing their first glance of the 100-acre expanse since the military swept into the capital six days ago, leaving hundreds dead and crushing a movement for political change.</s>

<s docid="AP890609-0036" num="13" wdcount="30"> Troops moved back their barricades, making it possible for city residents to walk to the edge of the square, which for seven weeks stood at the heart of the movement.</s>

<s docid="AP890609-0036" num="14" wdcount="19"> Buses and bicyclists today were allowed to pass by Changan Avenue, which borders the north edge of the square.</s>

<s docid="AP890609-0036" num="15" wdcount="25"> The spot once occupied by the Goddess of Democracy, a 33-foot-high replica of the Statue of Liberty, was taken by a tread-wheeled armored personnel carrier.</s>

<s docid="AP890609-0036" num="16" wdcount="27"> When students built the statue last week, for a few days it became a symbol of the movement for democratic reforms and an end to official corruption.</s>

<s docid="AP890609-0036" num="17" wdcount="7"> On Sunday morning, a tank crushed it.</s>

<s docid="AP890609-0036" num="18" wdcount="16"> In all, 80 tanks and 40 armored personnel carriers lined the northern part of the square.</s>

<s docid="AP890609-0036" num="19" wdcount="17"> The Monument to Revolutionary Martyrs, where the students took a final stand early Sunday, was swept clean.</s>

<s docid="AP890609-0036" num="20" wdcount="14"> Poems and posters calling for a more open China have disappeared from its sides.</s>

<s docid="AP890609-0036" num="21" wdcount="28"> Chinese Red Cross officials estimate 3,600 people were killed and 60,000 injured over the weekend, citing a Chinese students' organization, the Union of Chinese Students in West Germany.</s>

<s docid="AP890609-0036" num="22" wdcount="18"> The government says nearly 300 people, mostly soldiers, were killed; diplomats and Chinese say up to 3,000 died.</s>

<s docid="AP890609-0036" num="23" wdcount="13"> Soldiers drilled in Tiananmen's center, their cadenced shouting echoing around the vast expanse.</s>

<s docid="AP890609-0036" num="24" wdcount="18"> A crowd of officials stood on the roof of the Great Hall of the People, overlooking the square.</s>

<s docid="AP890609-0036" num="25" wdcount="25"> From this same roof five days earlier officials watched as a jubilant mass of demonstrators enveloped 5,000 troops and blocked their entry to the square.</s>

<s docid="AP890609-0036" num="26" wdcount="18"> Inside the square, soldiers could be seen shuffling about, their uniformed jackets stripped off, wash basins in hand.</s>

<s docid="AP890609-0036" num="27" wdcount="26"> There was a relaxed air of the inside of an army barracks as unarmed troops carried food and walked slowly together, talking and laughing in groups.</s>

<s docid="AP890609-0036" num="28" wdcount="18"> The area once housing students' tents has become a holding area for a huge fleet of troop trucks.</s>

<s docid="AP890609-0036" num="29" wdcount="29"> On the southern perimeter, a single line of tanks and a cordon of soldiers blocked the square from the thousands of bicylists who pedaled slowly by, peering into Tiananmen.</s>

<s docid="AP890609-0036" num="30" wdcount="12"> Near the square, troops placed barbed wire in front of one street.</s>

<s docid="AP890609-0036" num="31" wdcount="14"> Soldiers were billeted in a construction site, their laundered fatigues drying on the scaffolding.</s>

<s docid="AP890609-0036" num="32" wdcount="17"> Next door, troops, their assault rifles slung nonchalantly over their shoulders, stood and chatted outside a discotheque.</s>

<s docid="AP890609-0036" num="33" wdcount="8"> ``They look like they,'' said one local resident.</s>

<s docid="AP890609-0036" num="34" wdcount="11"> ``I hope they know that we still don't want them here.''</s>
</TEXT>
</DOC>
