<DOC>
<DOCNO>

<s docid="AP890603-0108" num="1" wdcount="1"> AP890603-0108</s>
</DOCNO>
<FILEID>

<s docid="AP890603-0108" num="2" wdcount="2"> AP-NR-06-03-89 1735EST</s>
</FILEID>
<FIRST>

<s docid="AP890603-0108" num="3" wdcount="6"> u i BC-China-Chronology 1stLd-Writethru 06-03 0833</s>
</FIRST>
<SECOND>

<s docid="AP890603-0108" num="4" wdcount="5"> BC-China-Chronology, 1st Ld - Writethru,a0557,0856</s>
</SECOND>
<HEAD>

<s docid="AP890603-0108" num="5" wdcount="5"> Chronology of Events in China</s>
</HEAD>
<HEAD>

<s docid="AP890603-0108" num="6" wdcount="13"> Eds: UPDATES with latest developments, includes events between May 26 and June 2</s>
</HEAD>
<DATELINE>

<s docid="AP890603-0108" num="7" wdcount="2"> BEIJING (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890603-0108" num="8" wdcount="34"> Here is a look at key events in the student pro-democracy movement that led to Sunday's assault by soldiers on protesters in Tiananmen Square: April 15 _ Former Communist Party chief Hu Yaobang dies.</s>

<s docid="AP890603-0108" num="9" wdcount="21"> Beijing University students put up posters praising him and indirectly criticizing opponents who forced his resignation after student demonstrations in 1986-87.</s>

<s docid="AP890603-0108" num="10" wdcount="16"> April 17 _ Thousands of students march in Beijing and Shanghai, shouting ``Long live Hu Yaobang!</s>

<s docid="AP890603-0108" num="11" wdcount="32"> Long live democracy''! April 27 _ More than 150,000 students, with wide support from people on the street, surge past police lines and fill Tiananmen Square, chanting slogans for democracy and freedom.</s>

<s docid="AP890603-0108" num="12" wdcount="23"> April 29 _ Officials meet with student leaders, but independent student groups are not satisfied and continue a class boycott at 41 universities.</s>

<s docid="AP890603-0108" num="13" wdcount="13"> April 30 _ Beijing's Communist Party chief, Zhao Ziyang, meets with student representatives.</s>

<s docid="AP890603-0108" num="14" wdcount="22"> May 4 _ About 100,000 students and supporters march on Tiananmen Square to celebrate the 70th anniversary of China's first student movement.</s>

<s docid="AP890603-0108" num="15" wdcount="9"> Demonstrations are held in Shanghai, Nanjing and other cities.</s>

<s docid="AP890603-0108" num="16" wdcount="10"> About 300 journalists protest outside the official Xinhua News Agency.</s>

<s docid="AP890603-0108" num="17" wdcount="10"> May 9 _ Journalists petition the government for press freedom.</s>

<s docid="AP890603-0108" num="18" wdcount="16"> May 10 _ Thousands of students bicycle to major media offices in a press freedom demonstration.</s>

<s docid="AP890603-0108" num="19" wdcount="10"> Another protest is held in the provincial capital of Taiyuan.</s>

<s docid="AP890603-0108" num="20" wdcount="13"> May 13 _ About 2,000 students begin a hunger strike in Tiananmen Square.</s>

<s docid="AP890603-0108" num="21" wdcount="12"> May 14 _ Thousands flock to the square to back the students.</s>

<s docid="AP890603-0108" num="22" wdcount="6"> The number fasting rises to 3,000.</s>

<s docid="AP890603-0108" num="23" wdcount="13"> May 15 _ The government deadline for students to leave the square passes.</s>

<s docid="AP890603-0108" num="24" wdcount="4"> Soviet President Mikhail S.</s>

<s docid="AP890603-0108" num="25" wdcount="13"> Gorbachev's welcoming ceremony planned near the square must be moved to the airport.</s>

<s docid="AP890603-0108" num="26" wdcount="9"> May 16 _ Hundreds of thousands occupy the square.</s>

<s docid="AP890603-0108" num="27" wdcount="6"> Journalists and intellectuals join the protest.</s>

<s docid="AP890603-0108" num="28" wdcount="9"> May 17 _ Zhao pleas for students to leave.</s>

<s docid="AP890603-0108" num="29" wdcount="14"> Students reject his appeal and hold marches that generate 1 million supporters in Beijing.</s>

<s docid="AP890603-0108" num="30" wdcount="23"> May 18 _ About 1 million people, including many workers, again take to the streets to show their support for the hunger strikers.</s>

<s docid="AP890603-0108" num="31" wdcount="15"> Li Peng issues a stern lecture to student leaders and refuses to discuss their demands.</s>

<s docid="AP890603-0108" num="32" wdcount="10"> May 19 _ A tearful Zhao visits weakened hunger strikers.</s>

<s docid="AP890603-0108" num="33" wdcount="6"> Li also visits the students briefly.</s>

<s docid="AP890603-0108" num="34" wdcount="9"> The students later decide to end the hunger strike.</s>

<s docid="AP890603-0108" num="35" wdcount="11"> May 20 _ Martial law is declared in parts of Beijing.</s>

<s docid="AP890603-0108" num="36" wdcount="13"> Zhao reportedly resigns after failing to persuade Li and other hardliners to compromise.</s>

<s docid="AP890603-0108" num="37" wdcount="18"> Students resume their hunger strike, then abandon it, saying they will need their strength for the struggle ahead.</s>

<s docid="AP890603-0108" num="38" wdcount="21"> May 21 _ Students claim to reject an order by Li Peng to leave the Tiananman Square or face military action.</s>

<s docid="AP890603-0108" num="39" wdcount="21"> Defying martial law, hundreds of thousands of people remain in the square or block intersections to prevent troops from reaching it.</s>

<s docid="AP890603-0108" num="40" wdcount="28"> May 22 _ Hundreds of thousands of people again block major roads and senior military leaders say they are resisting orders to order their troops on the protesters.</s>

<s docid="AP890603-0108" num="41" wdcount="9"> At least one military convoy is reported to withdraw.</s>

<s docid="AP890603-0108" num="42" wdcount="14"> May 23 _ One million people take to the streets to demonstrate for democracy.</s>

<s docid="AP890603-0108" num="43" wdcount="12"> May 25 _ Li makes his first appearance since declaring martial law.</s>

<s docid="AP890603-0108" num="44" wdcount="19"> State- run radio says 27 of 29 provinces support martial law, and military units announce they support martial law.</s>

<s docid="AP890603-0108" num="45" wdcount="20"> May 26 _ Sources say Zhao and another leading liberal, Wan Li, head of the legislature, are under house arrest.</s>

<s docid="AP890603-0108" num="46" wdcount="14"> May 27 _ Beijing student leaders propose students end their occupation of Tiananmen Square.</s>

<s docid="AP890603-0108" num="47" wdcount="7"> Non-Beijing students resist and the sit-in continues.</s>

<s docid="AP890603-0108" num="48" wdcount="23"> May 28 _ About 80,000 people, many students from outside the capital, stage a demonstration, but unlike in past rallies few workers participate.</s>

<s docid="AP890603-0108" num="49" wdcount="19"> May 30 _ Students unveil their ``Goddess of Democracy,'' a replica of the Statue of Liberty, on the square.</s>

<s docid="AP890603-0108" num="50" wdcount="9"> The government calls it an insult to the nation.</s>

<s docid="AP890603-0108" num="51" wdcount="17"> Students rally outside police headquarters to protest the detention of three members of an independent labor union.</s>

<s docid="AP890603-0108" num="52" wdcount="18"> May 31 _ The first of several pro-government rallies is staged by farmers and workers in Beijing suburbs.</s>

<s docid="AP890603-0108" num="53" wdcount="9"> The participants, ordered to show up, show little enthusiasm.</s>

<s docid="AP890603-0108" num="54" wdcount="22"> June 1 _ The Beijing Municipal Government warns foreign journalists that under martial law they must receive approval for all press coverage.</s>

<s docid="AP890603-0108" num="55" wdcount="6"> Coverage of the demonstrations is banned.</s>

<s docid="AP890603-0108" num="56" wdcount="17"> June 2 _ More than 1,000 troops appear outside the railway station in a show of force.</s>

<s docid="AP890603-0108" num="57" wdcount="31"> June 3-4 _ Tens of thousands of troops make several attempts to move on the square but are driven back by crowds of hundreds of thousands of people supporting the students.</s>

<s docid="AP890603-0108" num="58" wdcount="9"> Riot squads beat and fire tear gas at demonstrators.</s>

<s docid="AP890603-0108" num="59" wdcount="16"> A final push is made the evening of June 3, and soldiers begin firing on crowds.</s>

<s docid="AP890603-0108" num="60" wdcount="18"> Troops surround and enter the square June 4 in the early morning hours and thousands of protesters flee.</s>

<s docid="AP890603-0108" num="61" wdcount="7"> Hundreds are wounded and many dead .</s>
</TEXT>
</DOC>
