<DOC>
<DOCNO>

<s docid="AP890608-0094" num="1" wdcount="1"> AP890608-0094</s>
</DOCNO>
<FILEID>

<s docid="AP890608-0094" num="2" wdcount="2"> AP-NR-06-08-89 1307EST</s>
</FILEID>
<FIRST>

<s docid="AP890608-0094" num="3" wdcount="5"> r i BC-China-Chronology 06-08 0993</s>
</FIRST>
<SECOND>

<s docid="AP890608-0094" num="4" wdcount="1"> BC-China-Chronology,1025</s>
</SECOND>
<HEAD>

<s docid="AP890608-0094" num="5" wdcount="4"> Chronology of Beijing Spring</s>
</HEAD>
<TEXT>

<s docid="AP890608-0094" num="6" wdcount="25"> Here is a look at key events in the student pro-democracy movement and at events since Sunday's assault by soldiers on protesters in Tiananmen Square:</s>
</TEXT>
<TEXT>

<s docid="AP890608-0094" num="7" wdcount="10"> April 15 _ Former Communist Party chief Hu Yaobang dies.</s>

<s docid="AP890608-0094" num="8" wdcount="21"> Beijing University students put up posters praising him and indirectly criticizing opponents who forced his resignation after student demonstrations in 1986-87.</s>

<s docid="AP890608-0094" num="9" wdcount="22"> April 18 _ Thousands of students march in Beijing and Shanghai, expressing dissatisfaction with the government and shouting ``Long live Hu Yaobang!</s>

<s docid="AP890608-0094" num="10" wdcount="3"> Long live democracy''!</s>

<s docid="AP890608-0094" num="11" wdcount="24"> About 1,000 stage a sit-in at the Great Hall of the People to demand greater democracy, a free press, and more money for education.</s>

<s docid="AP890608-0094" num="12" wdcount="9"> April 24 _ Students begin boycott of university classes.</s>

<s docid="AP890608-0094" num="13" wdcount="40"> April 27 _ In the largest to date of a continuing series of protests, more than 150,000 students, with wide support from people on the street, surge past police lines and fill Tiananmen Square, chanting slogans for democracy and freedom.</s>

<s docid="AP890608-0094" num="14" wdcount="23"> April 29 _ Officials meet with student leaders, but independent student groups are not satisfied and continue a class boycott at 41 universities.</s>

<s docid="AP890608-0094" num="15" wdcount="22"> May 4 _ About 100,000 students and supporters march on Tiananmen Square to celebrate the 70th anniversary of China's first student movement.</s>

<s docid="AP890608-0094" num="16" wdcount="9"> Demonstrations are held in Shanghai, Nanjing and other cities.</s>

<s docid="AP890608-0094" num="17" wdcount="10"> About 300 journalists protest outside the official Xinhua News Agency.</s>

<s docid="AP890608-0094" num="18" wdcount="13"> May 13 _ About 2,000 students begin a hunger strike in Tiananmen Square.</s>

<s docid="AP890608-0094" num="19" wdcount="12"> May 14 _ Thousands flock to the square to back the students.</s>

<s docid="AP890608-0094" num="20" wdcount="6"> The number fasting rises to 3,000.</s>

<s docid="AP890608-0094" num="21" wdcount="13"> May 15 _ The government deadline for students to leave the square passes.</s>

<s docid="AP890608-0094" num="22" wdcount="4"> Soviet President Mikhail S.</s>

<s docid="AP890608-0094" num="23" wdcount="13"> Gorbachev's welcoming ceremony planned near the square must be moved to the airport.</s>

<s docid="AP890608-0094" num="24" wdcount="9"> May 16 _ Hundreds of thousands occupy the square.</s>

<s docid="AP890608-0094" num="25" wdcount="6"> Journalists and intellectuals join the protest.</s>

<s docid="AP890608-0094" num="26" wdcount="9"> May 17 _ Zhao pleads for students to leave.</s>

<s docid="AP890608-0094" num="27" wdcount="14"> Students reject his appeal and hold marches that generate 1 million supporters in Beijing.</s>

<s docid="AP890608-0094" num="28" wdcount="23"> May 18 _ About 1 million people, including many workers, again take to the streets to show their support for the hunger strikers.</s>

<s docid="AP890608-0094" num="29" wdcount="15"> Li Peng issues a stern lecture to student leaders and refuses to discuss their demands.</s>

<s docid="AP890608-0094" num="30" wdcount="10"> May 19 _ A tearful Zhao visits weakened hunger strikers.</s>

<s docid="AP890608-0094" num="31" wdcount="6"> Li also visits the students briefly.</s>

<s docid="AP890608-0094" num="32" wdcount="9"> The students later decide to end the hunger strike.</s>

<s docid="AP890608-0094" num="33" wdcount="11"> May 20 _ Martial law is declared in parts of Beijing.</s>

<s docid="AP890608-0094" num="34" wdcount="13"> Zhao reportedly resigns after failing to persuade Li and other hardliners to compromise.</s>

<s docid="AP890608-0094" num="35" wdcount="18"> Students resume their hunger strike, then abandon it, saying they will need their strength for the struggle ahead.</s>

<s docid="AP890608-0094" num="36" wdcount="20"> May 21 _ Students claim to reject an order by Li Peng to leave Tiananman Square or face military action.</s>

<s docid="AP890608-0094" num="37" wdcount="21"> Defying martial law, hundreds of thousands of people remain in the square or block intersections to prevent troops from reaching it.</s>

<s docid="AP890608-0094" num="38" wdcount="28"> May 22 _ Hundreds of thousands of people again block major roads and senior military leaders say they are resisting orders to order their troops on the protesters.</s>

<s docid="AP890608-0094" num="39" wdcount="9"> At least one military convoy is reported to withdraw.</s>

<s docid="AP890608-0094" num="40" wdcount="14"> May 23 _ One million people take to the streets to demonstrate for democracy.</s>

<s docid="AP890608-0094" num="41" wdcount="12"> May 25 _ Li makes his first appearance since declaring martial law.</s>

<s docid="AP890608-0094" num="42" wdcount="18"> State-run radio says 27 of 29 provinces support martial law, and military units announce they support martial law.</s>

<s docid="AP890608-0094" num="43" wdcount="20"> May 26 _ Sources say Zhao and another leading liberal, Wan Li, head of the legislature, are under house arrest.</s>

<s docid="AP890608-0094" num="44" wdcount="14"> May 27 _ Beijing student leaders propose students end their occupation of Tiananmen Square.</s>

<s docid="AP890608-0094" num="45" wdcount="7"> Non-Beijing students resist and the sit-in continues.</s>

<s docid="AP890608-0094" num="46" wdcount="23"> May 28 _ About 80,000 people, many students from outside the capital, stage a demonstration, but unlike in past rallies few workers participate.</s>

<s docid="AP890608-0094" num="47" wdcount="19"> May 30 _ Students unveil their ``Goddess of Democracy,'' a replica of the Statue of Liberty, on the square.</s>

<s docid="AP890608-0094" num="48" wdcount="9"> The government calls it an insult to the nation.</s>

<s docid="AP890608-0094" num="49" wdcount="17"> Students rally outside police headquarters to protest the detention of three members of an independent labor union.</s>

<s docid="AP890608-0094" num="50" wdcount="18"> May 31 _ The first of several pro-government rallies is staged by farmers and workers in Beijing suburbs.</s>

<s docid="AP890608-0094" num="51" wdcount="9"> The participants, ordered to show up, show little enthusiasm.</s>

<s docid="AP890608-0094" num="52" wdcount="22"> June 1 _ The Beijing Municipal Government warns foreign journalists that under martial law they must receive approval for all press coverage.</s>

<s docid="AP890608-0094" num="53" wdcount="6"> Coverage of the demonstrations is banned.</s>

<s docid="AP890608-0094" num="54" wdcount="17"> June 2 _ More than 1,000 troops appear outside the railway station in a show of force.</s>

<s docid="AP890608-0094" num="55" wdcount="31"> June 3-4 _ Tens of thousands of troops make several attempts to move on the square but are driven back by crowds of hundreds of thousands of people supporting the students.</s>

<s docid="AP890608-0094" num="56" wdcount="9"> Riot squads beat and fire tear gas at demonstrators.</s>

<s docid="AP890608-0094" num="57" wdcount="16"> A final push is made the evening of June 3, and soldiers begin firing on crowds.</s>

<s docid="AP890608-0094" num="58" wdcount="18"> Troops surround and enter the square June 4 in the early morning hours and thousands of protesters flee.</s>

<s docid="AP890608-0094" num="59" wdcount="6"> Hundreds are killed and thousands wounded.</s>

<s docid="AP890608-0094" num="60" wdcount="12"> June 5 _ Soldiers terrorize Beijing with random shooting of unarmed civilians.</s>

<s docid="AP890608-0094" num="61" wdcount="6"> Army reinforces positions in city center.</s>

<s docid="AP890608-0094" num="62" wdcount="14"> Reports spread of a split in the army and a battle between military factions.</s>

<s docid="AP890608-0094" num="63" wdcount="15"> Demonstrations in Shanghai, Nanjing and other major Chinese cities to protest the slaughter in Beijing.</s>

<s docid="AP890608-0094" num="64" wdcount="7"> Chorus of condemnation from around the world.</s>

<s docid="AP890608-0094" num="65" wdcount="20"> U.S. announces suspension of all military sales and visits of Chinese military leaders, but stops short of severing diplomatic ties.</s>

<s docid="AP890608-0094" num="66" wdcount="13"> June 6 _ Armies loyal to rival factions are reported to be clashing.</s>

<s docid="AP890608-0094" num="67" wdcount="7"> Soldiers continue firing into crowds around Beijing.</s>

<s docid="AP890608-0094" num="68" wdcount="11"> Anti-government demonstrations spread to Shanghai, Nanjing, Chengdu, Shenyang and other cities.</s>

<s docid="AP890608-0094" num="69" wdcount="8"> Other nations urge their citizens to leave Beijing.</s>

<s docid="AP890608-0094" num="70" wdcount="19"> June 7 _ Soldiers sprayed a diplomatic compound with bullets and foreign embassies ordered their nationals to leave Beijing.</s>

<s docid="AP890608-0094" num="71" wdcount="6"> Hundreds of foreigners leave the country.</s>

<s docid="AP890608-0094" num="72" wdcount="8"> The U.S. government called the situation ``increasingly dangerous''.</s>

<s docid="AP890608-0094" num="73" wdcount="22"> June 8 _ Premier Li Peng makes his first public appearance since May 25 and praises the soldiers who crushed the demonstrations.</s>

<s docid="AP890608-0094" num="74" wdcount="13"> The government issued new martial law orders demanding that student leaders surrender .</s>
</TEXT>
</DOC>
