<DOC>
<DOCNO>

<s docid="AP890609-0094" num="1" wdcount="1"> AP890609-0094</s>
</DOCNO>
<FILEID>

<s docid="AP890609-0094" num="2" wdcount="2"> AP-NR-06-09-89 1216EST</s>
</FILEID>
<FIRST>

<s docid="AP890609-0094" num="3" wdcount="5"> r a PM-ChineseProtest 06-09 0237</s>
</FIRST>
<SECOND>

<s docid="AP890609-0094" num="4" wdcount="2"> PM-Chinese Protest,0241</s>
</SECOND>
<HEAD>

<s docid="AP890609-0094" num="5" wdcount="10"> 5,000 Turn Out for Tiananmen Square Memorial In NYC's Chinatown</s>
</HEAD>
<HEAD>

<s docid="AP890609-0094" num="6" wdcount="3"> With PM-China, Bjt</s>
</HEAD>
<DATELINE>

<s docid="AP890609-0094" num="7" wdcount="3"> NEW YORK (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890609-0094" num="8" wdcount="26"> More than 5,000 people chanting ``Freedom will survive''! packed a Chinatown park this morning in a memorial service for students slain by soldiers in Tiananmen Square.</s>

<s docid="AP890609-0094" num="9" wdcount="10"> They then marched through the streets in a funeral procession.</s>

<s docid="AP890609-0094" num="10" wdcount="10"> ``The gods are crying for what's happening in China today.</s>

<s docid="AP890609-0094" num="11" wdcount="22"> It's a great tragedy,'' said Harry Zinn of International Ladies Garment Workers Union Local 2325, addressing the crowd through a steady rain.</s>

<s docid="AP890609-0094" num="12" wdcount="9"> ``Our hearts go out to the people of China''.</s>

<s docid="AP890609-0094" num="13" wdcount="29"> The crowd, which stood respectfully and silently during a traditional funeral ceremony, waved banners and wore buttons honoring ``the martyrs of Tiananmen Square'' and calling for democracy in China.</s>

<s docid="AP890609-0094" num="14" wdcount="28"> After the service and several speeches, the crowd marched through the streets of Chinatown, led by a casket and a traditional Chinese funeral bier containing fruit and incense.</s>

<s docid="AP890609-0094" num="15" wdcount="22"> As they headed up Mulberry Street, a major street in Chinatown, they walked beneath a 30-foot black banner strung across the road.</s>

<s docid="AP890609-0094" num="16" wdcount="28"> ``This has united the Chinese people for one cause _ to overthrow the government and establish democracy,'' said Peter Lee, one of the student organizers of the service.</s>

<s docid="AP890609-0094" num="17" wdcount="9"> ``We must never allow them to crush another body''.</s>

<s docid="AP890609-0094" num="18" wdcount="11"> The funeral procession stretched for blocks through Chinatown, tying up traffic.</s>

<s docid="AP890609-0094" num="19" wdcount="13"> Demonstrators planned another rally later in the day outside the United Nations .</s>
</TEXT>
</DOC>
