<DOC>
<DOCNO>

<s docid="AP890603-0126" num="1" wdcount="1"> AP890603-0126</s>
</DOCNO>
<FILEID>

<s docid="AP890603-0126" num="2" wdcount="2"> AP-NR-06-03-89 2033EST</s>
</FILEID>
<FIRST>

<s docid="AP890603-0126" num="3" wdcount="5"> u i AM-China-SquareScene 06-03 0517</s>
</FIRST>
<SECOND>

<s docid="AP890603-0126" num="4" wdcount="2"> AM-China-Square Scene,0531</s>
</SECOND>
<HEAD>

<s docid="AP890603-0126" num="5" wdcount="8"> Tiananmen Square Resembles Battlefield in Assault on Students</s>
</HEAD>
<HEAD>

<s docid="AP890603-0126" num="6" wdcount="3"> With AM-China, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP890603-0126" num="7" wdcount="3"> By DAN BIERS</s>
</BYLINE>
<BYLINE>

<s docid="AP890603-0126" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890603-0126" num="9" wdcount="2"> BEIJING (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890603-0126" num="10" wdcount="31"> Dawn broke Sunday over a battle-scarred Tiananmen Square with tanks and rifle-toting troops ruling the vast expanse occupied the day before by students seeking a freer society from their communist rulers.</s>

<s docid="AP890603-0126" num="11" wdcount="21"> A low cloud of smoke covered much of the 100-acre square as bonfires set during the night's confrontation continued to smolder.</s>

<s docid="AP890603-0126" num="12" wdcount="23"> Hundreds of helmeted troops were deployed on the monument to revolutionary heroes in the square's center and thousands more at important intersections nearby.</s>

<s docid="AP890603-0126" num="13" wdcount="20"> Tanks moved into place on what had hours earlier been a rag-tag squatter's camp of tents for the pro-democracy students.</s>

<s docid="AP890603-0126" num="14" wdcount="34"> The battle for Tiananmen was primarily fought in the streets leading to the square, where scores of people fell trying to prevent columns of troops and armored military vehicles from moving on the students.</s>

<s docid="AP890603-0126" num="15" wdcount="28"> Gunfire could be heard from several sides, and tracers zipped through the sky above Mao Tse-tung's mausoleum, one of the main monuments to Chinese communism in the square.</s>

<s docid="AP890603-0126" num="16" wdcount="13"> Torched buses and army vehicles on the streets around Tiananmen billowed acrid smoke.</s>

<s docid="AP890603-0126" num="17" wdcount="19"> Troops first entered the square from the south, when a column trotted toward the student encampment about 1 a.m.</s>

<s docid="AP890603-0126" num="18" wdcount="3"> (noon EDT Saturday).</s>

<s docid="AP890603-0126" num="19" wdcount="17"> They took up positions to the east after a brief skirmish involving clubs and sticks with students.</s>

<s docid="AP890603-0126" num="20" wdcount="31"> More soldiers were deployed in front of the Great Hall of the People to the west, and a huge convoy with armored vehicles rolled down Changan Avenue to the north side.</s>

<s docid="AP890603-0126" num="21" wdcount="21"> The few thousand students remaining in the square stayed calm as they quietly gathered on the steps of the heroes' monument.</s>

<s docid="AP890603-0126" num="22" wdcount="11"> ``I'm not afraid,'' several said as the heavily armed troops encircled.</s>

<s docid="AP890603-0126" num="23" wdcount="20"> Hundreds of supporters continued to mill around the square, many dressed more for a summer outing than a military battle.</s>

<s docid="AP890603-0126" num="24" wdcount="15"> Loudspeakers blaring government and student announcements engaged in a noisy propaganda battle throughout the night.</s>

<s docid="AP890603-0126" num="25" wdcount="10"> ``The government is corrupt, you've been tricked,'' the students roared.</s>

<s docid="AP890603-0126" num="26" wdcount="27"> The state-run speaker warned that troops would use every means at their disposal to clear the square and that remaining students would bear responsibility for the consequences.</s>

<s docid="AP890603-0126" num="27" wdcount="22"> At 4 a.m., the lamposts that dot the square went ominously dark, and the student loudspeaker played the Internationale, the socialist anthem.</s>

<s docid="AP890603-0126" num="28" wdcount="19"> A Taiwan singer staging a hunger strike for democracy took the microphone and proclaimed: ``We've achieved a big victory.</s>

<s docid="AP890603-0126" num="29" wdcount="13"> ... We're not afraid to die, but we've already lost too much blood''.</s>

<s docid="AP890603-0126" num="30" wdcount="27"> After the lights went back on a half hour later, a voice vote by the students showed most wanted to leave the square to avoid further bloodshed.</s>

<s docid="AP890603-0126" num="31" wdcount="23"> They quickly filed out under the banners of their schools, carrying the quilts and padded jackets that offered warmth during the 22-day sit-in.</s>

<s docid="AP890603-0126" num="32" wdcount="16"> Neither the students nor the Beijing residents who arrived to show support could control their tears.</s>

<s docid="AP890603-0126" num="33" wdcount="14"> ``Go with us,'' they told their supporters, who applauded the students as they retreated.</s>

<s docid="AP890603-0126" num="34" wdcount="15"> As they sobbed, many students defiantly shouted: ``We shall return''! and flashed V-for-victory signs .</s>
</TEXT>
</DOC>
