<DOC>
<DOCNO>

<s docid="AP890427-0098" num="1" wdcount="1"> AP890427-0098</s>
</DOCNO>
<FILEID>

<s docid="AP890427-0098" num="2" wdcount="2"> AP-NR-04-27-89 1051EST</s>
</FILEID>
<FIRST>

<s docid="AP890427-0098" num="3" wdcount="7"> r a PM-Obit-Ball 1stLd-Writethru a0448 04-27 1041</s>
</FIRST>
<SECOND>

<s docid="AP890427-0098" num="4" wdcount="6"> PM-Obit-Ball, 1st Ld - Writethru, a0448,1068</s>
</SECOND>
<HEAD>

<s docid="AP890427-0098" num="5" wdcount="5"> Lucy's Legacy Will Be Eternal</s>
</HEAD>
<HEAD>

<s docid="AP890427-0098" num="6" wdcount="14"> Eds: INSERTS one graf after 24th graf, `Admirers included'... to add Reagan statement .</s>
</HEAD>
<HEAD>

<s docid="AP890427-0098" num="7" wdcount="2"> LaserPhoto NY8</s>
</HEAD>
<BYLINE>

<s docid="AP890427-0098" num="8" wdcount="3"> By JOHN HORN</s>
</BYLINE>
<BYLINE>

<s docid="AP890427-0098" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890427-0098" num="10" wdcount="3"> LOS ANGELES (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890427-0098" num="11" wdcount="34"> An outpouring of sympathy from presidents to childhood neighbors followed the death of Lucille Ball, but many said the queen mother of comedy will live on through television reruns and her influence on comedy.</s>

<s docid="AP890427-0098" num="12" wdcount="29"> The daffy, redheaded comedian whose harebrained schemes drove her television family crazy and delighted viewers for four decades died Wednesday of a ruptured abdominal artery at Cedars-Sinai Medical Center.</s>

<s docid="AP890427-0098" num="13" wdcount="11"> She was 77 and died eight days after emergency heart surgery.</s>

<s docid="AP890427-0098" num="14" wdcount="16"> A private burial was planned, reportedly with no funeral services in accordance with Miss Ball's wishes.</s>

<s docid="AP890427-0098" num="15" wdcount="19"> ``God has her now, and, thanks to television, we'll have her forever,'' said comedian and longtime friend Bob Hope.</s>

<s docid="AP890427-0098" num="16" wdcount="19"> Hospital switchboards were swamped with condolence calls and thousands of cards after Miss Ball's death, spokesman Ron Wise said.</s>

<s docid="AP890427-0098" num="17" wdcount="20"> Miss Ball's family requested that any flowers sent to the Medical Center in her memory be distributed to other patients.</s>

<s docid="AP890427-0098" num="18" wdcount="13"> Miss Ball maintained her sense of humor even when she was critically ill.</s>

<s docid="AP890427-0098" num="19" wdcount="29"> Following her operation last week, her first words to her daughter, Lucie, were: ``Wouldn't you know _ this is the day I was going to get my hair done''.</s>

<s docid="AP890427-0098" num="20" wdcount="17"> Miss Ball had been improving steadily from the heart surgery, so her death came as a shock.</s>

<s docid="AP890427-0098" num="21" wdcount="8"> ``She had been walking, her spirits were up.</s>

<s docid="AP890427-0098" num="22" wdcount="7"> Her family was with her,'' Wise said.</s>

<s docid="AP890427-0098" num="23" wdcount="13"> ``She responded as well as anyone could respond to that kind of surgery''.</s>

<s docid="AP890427-0098" num="24" wdcount="34"> He said she woke up early Wednesday complaining about a sudden pain in her back, and in a matter of seconds went into a full cardiac arrest that was caused by a ruptured aorta.</s>

<s docid="AP890427-0098" num="25" wdcount="18"> Miss Ball and her late former husband, Desi Arnaz, starred in ``I Love Lucy'' from 1951 to 1957.</s>

<s docid="AP890427-0098" num="26" wdcount="23"> In the ground-breaking show, still seen in syndication worldwide, the late Vivian Vance and William Frawley played their neighbors, Fred and Ethel Mertz.</s>

<s docid="AP890427-0098" num="27" wdcount="24"> ``Probably a lot of what she did rubbed off on what I do,'' said actress-comedian Jane Curtin, star of the sitcom ``Kate and Allie''.</s>

<s docid="AP890427-0098" num="28" wdcount="10"> ``But it couldn't be helped, because I memorized her shows''.</s>

<s docid="AP890427-0098" num="29" wdcount="24"> The show, one of the most popular in television history, was distinguished by Miss Ball's faultless timing, rubber-faced expressions, wide-mouthed wails and extravagant pratfalls.</s>

<s docid="AP890427-0098" num="30" wdcount="16"> ``Working with Lucy was like receiving an M.A. or a Ph.D. in comedy,'' recalled Joan Rivers.</s>

<s docid="AP890427-0098" num="31" wdcount="20"> ``What she forgot about comic timing and delivery is more than most of us will ever learn in a lifetime''.</s>

<s docid="AP890427-0098" num="32" wdcount="12"> Comedian Whoopi Goldberg said: ``Lucy was great because she represented every person.</s>

<s docid="AP890427-0098" num="33" wdcount="14"> She showed us human foibles and gave us a chance to laugh at ourselves''.</s>

<s docid="AP890427-0098" num="34" wdcount="28"> Miss Goldberg said her favorite episode involved a visit by the ``I Love Lucy'' characters to Hollywood, where Lucy and Ethel spotted actor William Holden in a restaurant.</s>

<s docid="AP890427-0098" num="35" wdcount="18"> ``That was how we would all react to seeing a movie star in a restaurant,'' Miss Goldberg said.</s>

<s docid="AP890427-0098" num="36" wdcount="16"> ``She was looking at him in a compact mirror, and trying to look at him surreptitiously.</s>

<s docid="AP890427-0098" num="37" wdcount="12"> And that's just an example of how everyone can identify with Lucy''.</s>

<s docid="AP890427-0098" num="38" wdcount="47"> Bob Rosati, who lives down the street from the Beverly Hills home Miss Ball shared with husband Gary Morton, said he was watching a rerun of ``I Love Lucy'' on Wednesday morning when the screen went black and the words ``In Memory of Lucille Ball, 1911-1989'' appeared.</s>

<s docid="AP890427-0098" num="39" wdcount="9"> ``I felt I had lost someone in my family.</s>

<s docid="AP890427-0098" num="40" wdcount="7"> I couldn't believe it,'' said Rosati, 40.</s>

<s docid="AP890427-0098" num="41" wdcount="9"> ``I was watching Lucy like I do every morning.</s>

<s docid="AP890427-0098" num="42" wdcount="9"> She's one of the most-admired ladies in this town''.</s>

<s docid="AP890427-0098" num="43" wdcount="26"> He was among a group of fans who stood reverently outside Miss Ball's home on Roxbury Drive as florists delivered baskets of flowers to the house.</s>

<s docid="AP890427-0098" num="44" wdcount="8"> Tour vans passed by in a non-stop procession.</s>

<s docid="AP890427-0098" num="45" wdcount="24"> On Hollywood Boulevard's Walk of Fame, flower arrangements were placed on Miss Ball's two stars _ one for her film work, one for television.</s>

<s docid="AP890427-0098" num="46" wdcount="18"> Budd Friedman, owner of the Improvisation comedy clubs, said, ``The world of comedy has lost its first lady.</s>

<s docid="AP890427-0098" num="47" wdcount="7"> Her death is an irreparable loss ...</s>

<s docid="AP890427-0098" num="48" wdcount="3"> to our industry''.</s>

<s docid="AP890427-0098" num="49" wdcount="23"> Actor Danny DeVito recalled getting a personal congratulation from Miss Ball in 1981 when he won an Emmy for the TV series ``Taxi''.</s>

<s docid="AP890427-0098" num="50" wdcount="10"> ``It made it like it had been blessed,'' he recalled.</s>

<s docid="AP890427-0098" num="51" wdcount="18"> Admirers included President Bush, in Southern California at the time of Miss Ball's passing, and former President Reagan.</s>

<s docid="AP890427-0098" num="52" wdcount="30"> ``Her red hair, her antics on the screen, her timing and her zest for life made her an American institution,'' the former president and Nancy Reagan said in a statement.</s>

<s docid="AP890427-0098" num="53" wdcount="9"> ``Just the mention of her name brings a smile.</s>

<s docid="AP890427-0098" num="54" wdcount="9"> ... We love Lucy and will miss her deeply''.</s>

<s docid="AP890427-0098" num="55" wdcount="9"> ``Lucille Ball possessed the gift of laughter,'' Bush said.</s>

<s docid="AP890427-0098" num="56" wdcount="13"> ``But she also embodied an even greater treasure _ the gift of love.</s>

<s docid="AP890427-0098" num="57" wdcount="10"> She appealed to the gentler impulses of the human spirit.</s>

<s docid="AP890427-0098" num="58" wdcount="8"> She was not merely an actress or comedienne.</s>

<s docid="AP890427-0098" num="59" wdcount="7"> She was Lucy and she was loved''.</s>

<s docid="AP890427-0098" num="60" wdcount="35"> ``To baby boomers, a happy chunk of our childhood is missing,'' said ``Saturday Night Live'' comedian Victoria Jackson, who was born two years after ``I Love Lucy'' went off the air as a regular series.</s>

<s docid="AP890427-0098" num="61" wdcount="16"> ``She didn't make me laugh out loud, I remember, she just made me happy about life''.</s>

<s docid="AP890427-0098" num="62" wdcount="17"> Said comic Tim Conway: ``We're going to miss this lady, but not really, because she's still here.</s>

<s docid="AP890427-0098" num="63" wdcount="8"> All those wonderful things they did together ...</s>

<s docid="AP890427-0098" num="64" wdcount="5"> those wonderful TV shows ...</s>

<s docid="AP890427-0098" num="65" wdcount="3"> are still available''.</s>

<s docid="AP890427-0098" num="66" wdcount="24"> Although Miss Ball hadn't visited her hometown of Jamestown, N.Y, since 1956 and had no family there, she had stayed in touch with friends.</s>

<s docid="AP890427-0098" num="67" wdcount="25"> Irene Rosseti, who now lives in Celoron, N.Y., said Miss Ball recently had sent her and her husband a letter on their 50th wedding anniversary.</s>

<s docid="AP890427-0098" num="68" wdcount="17"> ``Even though she was a big star, she was still just Lucy to us,'' she recalled .</s>
</TEXT>
<NOTE>

<s docid="AP890427-0098" num="69" wdcount="2"> EDITOR'S NOTE</s>
</NOTE>
<TEXT>

<s docid="AP890427-0098" num="70" wdcount="34"> Hospital spokesman Wise said that the family has asked that donations be sent to the Lucille Ball Foundation, in care of Irella-Manella, 1800 Ave. of the Stars, Suite 900, Los Angeles, Ca. 90067 .</s>
</TEXT>
</DOC>
