<DOC>
<DOCNO>

<s docid="AP890913-0253" num="1" wdcount="1"> AP890913-0253</s>
</DOCNO>
<FILEID>

<s docid="AP890913-0253" num="2" wdcount="2"> AP-NR-09-13-89 1335EDT</s>
</FILEID>
<FIRST>

<s docid="AP890913-0253" num="3" wdcount="6"> a e BC-WeekendTV-BobHope Adv22-23 09-13 0904</s>
</FIRST>
<SECOND>

<s docid="AP890913-0253" num="4" wdcount="5"> BC-Weekend TV-Bob Hope, Adv 22-23,0919</s>
</SECOND>
<HEAD>

<s docid="AP890913-0253" num="5" wdcount="1"> $adv22</s>
</HEAD>
<HEAD>

<s docid="AP890913-0253" num="6" wdcount="1"> $adv23</s>
</HEAD>
<HEAD>

<s docid="AP890913-0253" num="7" wdcount="8"> For Release Weekend Editions, Sept. 22-23, and thereafter</s>
</HEAD>
<HEAD>

<s docid="AP890913-0253" num="8" wdcount="9"> Bob Hope Remembers Moments With Lucy in NBC Special</s>
</HEAD>
<HEAD>

<s docid="AP890913-0253" num="9" wdcount="5"> LaserPhoto LA1 of Sept. 11</s>
</HEAD>
<BYLINE>

<s docid="AP890913-0253" num="10" wdcount="3"> By JERRY BUCK</s>
</BYLINE>
<BYLINE>

<s docid="AP890913-0253" num="11" wdcount="3"> AP Television Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890913-0253" num="12" wdcount="3"> LOS ANGELES (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890913-0253" num="13" wdcount="35"> Bob Hope keeps voluminous files, including the jokes he delivered and people he has performed with, and his first entry under Lucille Ball is an appearance with Hope in 1945 on a show called ``G.I.</s>

<s docid="AP890913-0253" num="14" wdcount="24"> Journal''. ``I really can't remember many details about it,'' said Hope, who pays tribute to his frequent co-star in an NBC special Saturday night.</s>

<s docid="AP890913-0253" num="15" wdcount="9"> It's called ``Bob Hope's Love Affair With Lucille Ball''.</s>

<s docid="AP890913-0253" num="16" wdcount="7"> She died in April of this year.</s>

<s docid="AP890913-0253" num="17" wdcount="26"> That first time together was followed by four movies, frequent visits by Hope on ``I Love Lucy'' and regular appearances by Lucy on his television shows.</s>

<s docid="AP890913-0253" num="18" wdcount="8"> ``Lucy was a very funny woman,'' Hope said.</s>

<s docid="AP890913-0253" num="19" wdcount="11"> ``Even in private she could get off a great ad lib.</s>

<s docid="AP890913-0253" num="20" wdcount="10"> But it's hard to compare her with other funny women.</s>

<s docid="AP890913-0253" num="21" wdcount="7"> It's like asking who's the best golfer.</s>

<s docid="AP890913-0253" num="22" wdcount="7"> You have to go to the records.</s>

<s docid="AP890913-0253" num="23" wdcount="10"> I don't think anyone ever had the success she had.</s>

<s docid="AP890913-0253" num="24" wdcount="6"> She certainly holds the most records''.</s>

<s docid="AP890913-0253" num="25" wdcount="26"> A secretary dug the details of that first joint appearance out of one of two vaults where Hope keeps everything pertaining to his long comic career.</s>

<s docid="AP890913-0253" num="26" wdcount="28"> There are written records of all his shows, copies of all the scripts, monologues and comic routines, audio tapes of his radio shows and thousands of other mementos.</s>

<s docid="AP890913-0253" num="27" wdcount="7"> ``G.I. Journal'' was on May 4, 1945.</s>

<s docid="AP890913-0253" num="28" wdcount="7"> Hope's file reads: ``Spot: Lucille Ball ...</s>

<s docid="AP890913-0253" num="29" wdcount="3"> English play ...</s>

<s docid="AP890913-0253" num="30" wdcount="3"> For Charity Bazaar''.</s>

<s docid="AP890913-0253" num="31" wdcount="13"> Hope and Ball had actually known each other before they began working together.</s>

<s docid="AP890913-0253" num="32" wdcount="13"> In fact, the late Desi Arnaz, her then husband, worked for Hope first.</s>

<s docid="AP890913-0253" num="33" wdcount="22"> He said Ball asked him nearly 50 years ago to find a place on his popular radio show for band leader Arnaz.</s>

<s docid="AP890913-0253" num="34" wdcount="10"> ``Stan Kenton was leaving as my orchestra leader,'' Hope said.</s>

<s docid="AP890913-0253" num="35" wdcount="8"> ``I gave Desi a spot on my show.</s>

<s docid="AP890913-0253" num="36" wdcount="8"> We also gave him some lines to speak.</s>

<s docid="AP890913-0253" num="37" wdcount="12"> Every time he walked up to the microphone he dropped an enchilada.</s>

<s docid="AP890913-0253" num="38" wdcount="9"> He could hardly talk, let alone get a laugh.</s>

<s docid="AP890913-0253" num="39" wdcount="11"> When they started `I Love Lucy,' I said, `What's going on?</s>

<s docid="AP890913-0253" num="40" wdcount="4"> This man is funny'''.</s>

<s docid="AP890913-0253" num="41" wdcount="13"> ``The night before she died I performed at the Music Center,'' he said.</s>

<s docid="AP890913-0253" num="42" wdcount="20"> ``Lucy was in the hospital and I saw her daughter, Lucie Arnaz, and said, `Isn't it wonderful she's doing better'.</s>

<s docid="AP890913-0253" num="43" wdcount="11"> They called me the next day and said she had died.</s>

<s docid="AP890913-0253" num="44" wdcount="11"> I said, `God has her now, but we'll have her forever'.</s>

<s docid="AP890913-0253" num="45" wdcount="10"> We'll be watching her performances for a long, long time''.</s>

<s docid="AP890913-0253" num="46" wdcount="27"> ``Bob Hope's Love Affair With Lucy'' will include clips from their movies and TV appearances, plus such guest stars as Betty White, George Burns and Danny Thomas.</s>

<s docid="AP890913-0253" num="47" wdcount="11"> ``I'm going through everything myself picking out the clips,'' Hope said.</s>

<s docid="AP890913-0253" num="48" wdcount="15"> ``The last time she was on my show was my birthday show two years ago.</s>

<s docid="AP890913-0253" num="49" wdcount="6"> We sang `I Remember It Well'.</s>

<s docid="AP890913-0253" num="50" wdcount="13"> Our last time together in public was at the Academy Awards in March.</s>

<s docid="AP890913-0253" num="51" wdcount="16"> I think I'll do my tribute to her over a shot of that in the background.</s>

<s docid="AP890913-0253" num="52" wdcount="5"> I think everyone remembers that''.</s>

<s docid="AP890913-0253" num="53" wdcount="12"> She was on his radio show on May 27, 1947, at Detroit.</s>

<s docid="AP890913-0253" num="54" wdcount="11"> The program notes say, ``Lucille Ball: New York, clothes, cars, pictures''.</s>

<s docid="AP890913-0253" num="55" wdcount="25"> ``I could do a fashion show with her walking on stage,'' Hope said of the show clips he had been watching in preparing the special.</s>

<s docid="AP890913-0253" num="56" wdcount="6"> ``She had great gowns and hairdos.</s>

<s docid="AP890913-0253" num="57" wdcount="8"> When she performed she would use different styles.</s>

<s docid="AP890913-0253" num="58" wdcount="8"> She'd change the way she read a line.</s>

<s docid="AP890913-0253" num="59" wdcount="17"> She'd throw a line away one time, then she'd turn around and milk a line for laughs''.</s>

<s docid="AP890913-0253" num="60" wdcount="18"> Hope recalled his funny co-star in a sunny alcove in the living room of his Los Angeles home.</s>

<s docid="AP890913-0253" num="61" wdcount="17"> It overlooks the one-hole golf course in the back yard, and he was attired in golfing clothes.</s>

<s docid="AP890913-0253" num="62" wdcount="18"> Occasionally, he called his office in another building on the grounds to check on a piece of information.</s>

<s docid="AP890913-0253" num="63" wdcount="18"> Soon after the interview, he was aboard a plane for a series of personal appearances around the country.</s>

<s docid="AP890913-0253" num="64" wdcount="19"> Ball made 22 appearances on Hope's specials and he was on her shows 10 or 12 times, he said.</s>

<s docid="AP890913-0253" num="65" wdcount="35"> In their first movie, ``Sorrowful Jones'' in 1949, Hope played a racetrack bookie who's forced to become the foster father of a young girl whose real father was killed by gangsters in a racehorse fix.</s>

<s docid="AP890913-0253" num="66" wdcount="12"> Ball was a nightclub singer who helps him look after the girl.</s>

<s docid="AP890913-0253" num="67" wdcount="14"> It was a remake of ``Little Miss Marker,'' which starred Shirley Temple in 1934.</s>

<s docid="AP890913-0253" num="68" wdcount="13"> Next was ``Fancy Pants'' in 1950, a remake of ``Ruggles of Red Gap''.</s>

<s docid="AP890913-0253" num="69" wdcount="13"> Ball played a rich rancher who acquires an English butler, played by Hope.</s>

<s docid="AP890913-0253" num="70" wdcount="17"> ``Facts of Life'' was in 1960, with Hope and Ball as married lovers who have a tryst.</s>

<s docid="AP890913-0253" num="71" wdcount="28"> Their last film was ``Critic's Choice'' in 1963, in which Hope is a Broadway critic who has to review a play written by his wife, played by Ball.</s>

<s docid="AP890913-0253" num="72" wdcount="26"> ``Someone reminded me the other night of a bus tour we did of movie theaters in New York to promote one our of pictures,'' he said.</s>

<s docid="AP890913-0253" num="73" wdcount="6"> ``I think it was `Critic's Choice'.</s>

<s docid="AP890913-0253" num="74" wdcount="7"> I found her very cooperative, very wonderful.</s>

<s docid="AP890913-0253" num="75" wdcount="8"> We always had a lot of fun together.''</s>
</TEXT>
<NOTE>

<s docid="AP890913-0253" num="76" wdcount="5"> End Adv for Sept. 22-23</s>
</NOTE>
</DOC>
