<DOC>
<DOCNO>

<s docid="AP890427-0014" num="1" wdcount="1"> AP890427-0014</s>
</DOCNO>
<FILEID>

<s docid="AP890427-0014" num="2" wdcount="2"> AP-NR-04-27-89 0048EST</s>
</FILEID>
<FIRST>

<s docid="AP890427-0014" num="3" wdcount="5"> r a PM-LucyRemembrance 04-27 0542</s>
</FIRST>
<SECOND>

<s docid="AP890427-0014" num="4" wdcount="2"> PM-Lucy Remembrance,0554</s>
</SECOND>
<HEAD>

<s docid="AP890427-0014" num="5" wdcount="11"> Lucy Always Credited Others And Never Knew How Great She Was</s>
</HEAD>
<HEAD>

<s docid="AP890427-0014" num="6" wdcount="3"> With PM-Obit-Ball, Bjt</s>
</HEAD>
<HEAD>

<s docid="AP890427-0014" num="7" wdcount="7"> Eds: Also in Thursday AMs report .</s>
</HEAD>
<NOTE>

<s docid="AP890427-0014" num="8" wdcount="2"> EDITOR'S NOTE</s>
</NOTE>
<TEXT>

<s docid="AP890427-0014" num="9" wdcount="13"> Bob Thomas has covered Hollywood for The Associated Press for 45 years .</s>
</TEXT>
<NOTE>

<s docid="AP890427-0014" num="10" wdcount="3"> By BOB THOMAS</s>
</NOTE>
<NOTE>

<s docid="AP890427-0014" num="11" wdcount="3"> Associated Press Writer</s>
</NOTE>
<DATELINE>

<s docid="AP890427-0014" num="12" wdcount="2"> HOLLYWOOD (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890427-0014" num="13" wdcount="7"> She never knew how great she was.</s>

<s docid="AP890427-0014" num="14" wdcount="16"> Amid the blimp-size egos of the entertainment world, Lucille Ball stood out like an orange beacon.</s>

<s docid="AP890427-0014" num="15" wdcount="3"> She never bragged.</s>

<s docid="AP890427-0014" num="16" wdcount="6"> She never exercised her considerable power.</s>

<s docid="AP890427-0014" num="17" wdcount="12"> She always seemed astonished, even embarrassed, when honors inevitably came her way.</s>

<s docid="AP890427-0014" num="18" wdcount="35"> When she was to receive a humanitarian award from Variety Clubs on a CBS special five years ago, she told me: ``There comes a time in your life when you get a lot of plaques.</s>

<s docid="AP890427-0014" num="19" wdcount="14"> It's very flattering and I'll go along with it, especially if it benefits children''.</s>

<s docid="AP890427-0014" num="20" wdcount="26"> Whenever she was praised for ``I Love Lucy,'' she invariably replied: ``Well, all of the credit should go to (writers) Madelyn Pugh and Bob Carroll Jr''.</s>

<s docid="AP890427-0014" num="21" wdcount="12"> Or, ``Desi was a genius: He was responsible for the show's success''.</s>

<s docid="AP890427-0014" num="22" wdcount="10"> Or she cited co-stars Desi, Vivian Vance and Bill Frawley.</s>

<s docid="AP890427-0014" num="23" wdcount="20"> Yes, the writing and producing and casting of ``I Love Lucy'' were marvelous, but Lucy's performance added the quantum force.</s>

<s docid="AP890427-0014" num="24" wdcount="32"> Her inspired pantomime could be written by no one: the growing panic as the chocolate assembly line speeded up; her catalog of pained expressions after tasting the patent medicine she was demonstrating.</s>

<s docid="AP890427-0014" num="25" wdcount="9"> Unlike many stars, Lucille Ball rarely indulged in self-analysis.</s>

<s docid="AP890427-0014" num="26" wdcount="40"> But on one occasion she revealed why her feelings about the ``I Love Lucy'' triumph might have been ambivalent: Living through the last five years of the show, she said, ``took the edge off any enjoyment I might have had.</s>

<s docid="AP890427-0014" num="27" wdcount="13"> Desi's drinking and carousing were a terrible embarrassment, bad for a woman's self-esteem.</s>

<s docid="AP890427-0014" num="28" wdcount="7"> The talk around town was `poor Lucy'.</s>

<s docid="AP890427-0014" num="29" wdcount="14"> Because I couldn't face people, I became a recluse for more than 5 years.</s>

<s docid="AP890427-0014" num="30" wdcount="15"> ``I never demonstrated my unhappiness at the studio, and actually, working together was a blessing.</s>

<s docid="AP890427-0014" num="31" wdcount="14"> Desi had everything so well organized that it was easy to do the work''.</s>

<s docid="AP890427-0014" num="32" wdcount="8"> Lucy was late in reaching her comedy potential.</s>

<s docid="AP890427-0014" num="33" wdcount="13"> She was 40 when ``I Love Lucy'' started on CBS and revolutionized television.</s>

<s docid="AP890427-0014" num="34" wdcount="39"> And although she spent many years in Hollywood, ``none of the studios ever designed comedies for me the way MGM did for Red Skelton, Paramount did for Bob Hope and Sam Goldwyn did for Danny Kaye,'' she once said.</s>

<s docid="AP890427-0014" num="35" wdcount="40"> ``Television was the medium for me, the medium for anyone who wanted to be well known a lot faster than waiting a year and a half for a movie to come out,'' she said in an interview late in life.</s>

<s docid="AP890427-0014" num="36" wdcount="11"> ``Television is an instant barometer, especially the way we did it.</s>

<s docid="AP890427-0014" num="37" wdcount="4"> ``It was all new.</s>

<s docid="AP890427-0014" num="38" wdcount="5"> Nobody knew anything about television.</s>

<s docid="AP890427-0014" num="39" wdcount="11"> Nobody was there to say, `No, don't do that, it's wrong'!</s>

<s docid="AP890427-0014" num="40" wdcount="10"> We never knew what was wrong and what was right.</s>

<s docid="AP890427-0014" num="41" wdcount="6"> We were all feeling our way.</s>

<s docid="AP890427-0014" num="42" wdcount="23"> Desi was very innovative and very showmanship-conscious and was very intent on going ahead and doing it: `That sounds all right, let's go'!</s>

<s docid="AP890427-0014" num="43" wdcount="3"> So we went''.</s>

<s docid="AP890427-0014" num="44" wdcount="6"> Always the credit to someone else.</s>

<s docid="AP890427-0014" num="45" wdcount="10"> But millions upon millions of television watchers know otherwise .</s>
</TEXT>
</DOC>
