<DOC>
<DOCNO>

<s docid="AP890509-0040" num="1" wdcount="1"> AP890509-0040</s>
</DOCNO>
<FILEID>

<s docid="AP890509-0040" num="2" wdcount="2"> AP-NR-05-09-89 0350EST</s>
</FILEID>
<FIRST>

<s docid="AP890509-0040" num="3" wdcount="5"> r a PM-LucyMemorial 05-09 0575</s>
</FIRST>
<SECOND>

<s docid="AP890509-0040" num="4" wdcount="2"> PM-Lucy Memorial,0591</s>
</SECOND>
<HEAD>

<s docid="AP890509-0040" num="5" wdcount="12"> Lucille Ball Memorials: Fans Shed Tears for Woman Who Made Them Laugh</s>
</HEAD>
<BYLINE>

<s docid="AP890509-0040" num="6" wdcount="3"> By MICHAEL FLEEMAN</s>
</BYLINE>
<BYLINE>

<s docid="AP890509-0040" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890509-0040" num="8" wdcount="3"> LOS ANGELES (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890509-0040" num="9" wdcount="31"> Thousands of Lucille Ball's fans shed tears for the woman who made them laugh, as three cities held memorial services in which the redheaded comedian was remembered with prayers and applause.</s>

<s docid="AP890509-0040" num="10" wdcount="5"> ``She was a whole package.</s>

<s docid="AP890509-0040" num="11" wdcount="8"> There never will be another one like her.</s>

<s docid="AP890509-0040" num="12" wdcount="16"> I love her,'' said a tearful Carol Burnett following a memorial Mass in suburban Santa Monica.</s>

<s docid="AP890509-0040" num="13" wdcount="37"> More than a thousand people who packed the St. Monica's Catholic Church rose to their feet and clapped for several minutes after television minister the Rev. Robert Schuller asked them to ``applaud the Lord for Lucille Ball''.</s>

<s docid="AP890509-0040" num="14" wdcount="17"> About 1,000 people also crowded a church in New York and 200 gathered in a Chicago church.</s>

<s docid="AP890509-0040" num="15" wdcount="20"> All three memorial Masses began at 8 p.m. Monday, the time Miss Ball's three most popular programs were often broadcast.</s>

<s docid="AP890509-0040" num="16" wdcount="33"> The 77-year-old comedian who starred in one of television's biggest all-time hits, ``I Love Lucy,'' died here April 26 of a ruptured aorta, a major blood vessel, eight days after emergency open-heart surgery.</s>

<s docid="AP890509-0040" num="17" wdcount="37"> Miss Ball, known for her honed comedic timing, wide-mouthed expressions and wacky antics, was popular among generations of fans who watched ``I Love Lucy'' as a first-run show in the '50s and in three decades of reruns.</s>

<s docid="AP890509-0040" num="18" wdcount="34"> ``She showed her love in the only way she knew how, by making you laugh,'' the Rev. James Fox told those gathered for the Roman Catholic Mass at St. Ignatius Loyola in New York.</s>

<s docid="AP890509-0040" num="19" wdcount="26"> Broadcaster Diane Sawyer told the crowd that the death of Miss Ball may have settled a longstanding theological debate over whether there is laughter in heaven.</s>

<s docid="AP890509-0040" num="20" wdcount="19"> ``A God who would have created her would never let her laughter be far from Him,'' said Ms. Sawyer.</s>

<s docid="AP890509-0040" num="21" wdcount="37"> In Chicago, the Rev. Jack Wall told people at Old St. Patrick Church that God gave the world talents like Miss Ball ``to show us life is not a tragedy, but a comedy with a happy ending''.</s>

<s docid="AP890509-0040" num="22" wdcount="15"> ``She taught us that if we could love Lucy, we could love ourselves,'' Wall said.</s>

<s docid="AP890509-0040" num="23" wdcount="24"> In announcing the services, Miss Ball's family said: ``Monday night was the time when most of the nation was used to being with Lucy''.</s>

<s docid="AP890509-0040" num="24" wdcount="21"> Two of the three long-running comedy shows in which Miss Ball starred, ``The Lucy Show'' and ``Here's Lucy,'' aired Monday nights.</s>

<s docid="AP890509-0040" num="25" wdcount="11"> ``I Love Lucy'' had starting times on Mondays and other days.</s>

<s docid="AP890509-0040" num="26" wdcount="17"> ``Lucille Ball gave the gift of humor which produced happiness,'' said Schuller at the Santa Monica service.</s>

<s docid="AP890509-0040" num="27" wdcount="17"> ``Only God knows how many husbands and wives weren't speaking _ and then Monday night rolled around''.</s>

<s docid="AP890509-0040" num="28" wdcount="16"> Fans lined up to get in the Santa Monica church as much as four hours early.</s>

<s docid="AP890509-0040" num="29" wdcount="18"> Florists delivered arrangements including a 3-foot heart of red carnations with the words ``I Love Lucy'' written across.</s>

<s docid="AP890509-0040" num="30" wdcount="23"> Hundreds of people came forward during Holy Communion to receive blessings from three priests, including a woman wearing an ``I Love Lucy'' T-shirt.</s>

<s docid="AP890509-0040" num="31" wdcount="35"> ``I think she would have loved it very much, and she lived her life for the people who were in that room tonight,'' said Lucie Arnaz, daughter of Miss Ball and the late Desi Arnaz.</s>

<s docid="AP890509-0040" num="32" wdcount="19"> Gary Morton, Miss Ball's husband for more than two decades, attended a private service for his wife last month.</s>

<s docid="AP890509-0040" num="33" wdcount="14"> The actress' remains were buried at Forest Lawn Memorial Park in Hollywood Hills .</s>
</TEXT>
</DOC>
