<DOC>
<DOCNO>

<s docid="AP890427-0052" num="1" wdcount="1"> AP890427-0052</s>
</DOCNO>
<FILEID>

<s docid="AP890427-0052" num="2" wdcount="2"> AP-NR-04-27-89 0456EST</s>
</FILEID>
<FIRST>

<s docid="AP890427-0052" num="3" wdcount="5"> r a PM-Lucy'sHometown 04-27 0528</s>
</FIRST>
<SECOND>

<s docid="AP890427-0052" num="4" wdcount="2"> PM-Lucy's Hometown,0547</s>
</SECOND>
<HEAD>

<s docid="AP890427-0052" num="5" wdcount="6"> Lucille Ball Remembered In Her Hometown</s>
</HEAD>
<HEAD>

<s docid="AP890427-0052" num="6" wdcount="3"> With PM-Obit-Ball, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP890427-0052" num="7" wdcount="3"> By DARREN DOPP</s>
</BYLINE>
<BYLINE>

<s docid="AP890427-0052" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890427-0052" num="9" wdcount="3"> JAMESTOWN, N.Y. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890427-0052" num="10" wdcount="29"> As a young girl in western New York, Lucille Ball hawked hot dogs and popcorn at an amusement park as she dreamed of starring in movies, hometown friends recalled.</s>

<s docid="AP890427-0052" num="11" wdcount="24"> ``She always talked about being a star,'' said Pauline Lopus, who went to school with Miss Ball and had kept in touch with her.</s>

<s docid="AP890427-0052" num="12" wdcount="25"> Miss Ball, born 60 miles south of Buffalo in Jamestown on Aug. 6, 1911, grew up in nearby Celoron, a rural hamlet on Chautauqua Lake.</s>

<s docid="AP890427-0052" num="13" wdcount="13"> Mrs. Lopus remembered the sitcom star on Wednesday as ``daring in many ways''.</s>

<s docid="AP890427-0052" num="14" wdcount="11"> ``She tried to get me to run off (to Broadway),'' Mrs.</s>

<s docid="AP890427-0052" num="15" wdcount="2"> Lopus added.</s>

<s docid="AP890427-0052" num="16" wdcount="6"> ``But I didn't have the nerve''.</s>

<s docid="AP890427-0052" num="17" wdcount="26"> At 15, Miss Ball worked as a barker at the amusement park, screaming for people to buy popcorn and hot dogs until she lost her voice.</s>

<s docid="AP890427-0052" num="18" wdcount="28"> Later, she starred in high school plays and got her start in front of a large audience on the vaudeville stage at the defunct Palace Theater in Jamestown.</s>

<s docid="AP890427-0052" num="19" wdcount="19"> Although Miss Ball hadn't visited Jamestown since 1956 and had no family there, she stayed in touch with friends.</s>

<s docid="AP890427-0052" num="20" wdcount="19"> ``Even though she was a big star, she was still just Lucy to us,'' said Irene Rosseti of Celoron.</s>

<s docid="AP890427-0052" num="21" wdcount="18"> Mrs. Rosseti said Miss Ball recently sent her and her husband a letter on their 50th wedding anniversary.</s>

<s docid="AP890427-0052" num="22" wdcount="18"> Miss Ball regularly donated money to charities, civic events and Jamestown Community College, said Jamestown Mayor Steven Carlson.</s>

<s docid="AP890427-0052" num="23" wdcount="27"> On May 20, Miss Ball was to receive an honorary degree from the college and had planned to return to Jamestown, now a city of about 40,000.</s>

<s docid="AP890427-0052" num="24" wdcount="14"> Residents had put up posters saying ``Jamestown Loves Lucy'' in storefronts and home windows.</s>

<s docid="AP890427-0052" num="25" wdcount="24"> After Miss Ball suffered a heart attack last week, residents decided to sign the posters and send them to her as a get-well greeting.</s>

<s docid="AP890427-0052" num="26" wdcount="9"> More than 150 posters were sent with 10,000 signatures.</s>

<s docid="AP890427-0052" num="27" wdcount="30"> The 77-year-old comedian died Wednesday of a ruptured aorta, the main heart artery, at Cedars-Sinai Medical Center in Los Angeles, where she was recovering from last week's emergency heart surgery.</s>

<s docid="AP890427-0052" num="28" wdcount="18"> ``It is a sad day for all of us,'' said Nelson Garifi, an organizer of the welcoming event.</s>

<s docid="AP890427-0052" num="29" wdcount="13"> ``But I'm sure that feeling is shared by many people around the world''.</s>

<s docid="AP890427-0052" num="30" wdcount="16"> Garifi, community relations director for the community college, said the honorary degree will be awarded posthumously.</s>

<s docid="AP890427-0052" num="31" wdcount="32"> Future generations in Celoron will have a reminder of their famous resident every time they drive or walk down the street where she grew up _ it will be renamed Lucy Lane.</s>

<s docid="AP890427-0052" num="32" wdcount="18"> Village officials had planned formal ceremonies renaming the street when she was due in the area next month.</s>

<s docid="AP890427-0052" num="33" wdcount="14"> ``But it will happen anyway,'' John Goodell of the village's historical society said Wednesday.</s>

<s docid="AP890427-0052" num="34" wdcount="34"> When the society was formed about a year ago, Goodell said: ``We sent an invitation to Lucille Ball to be a member, and she sent back a check for $500 for a life membership.</s>

<s docid="AP890427-0052" num="35" wdcount="18"> ``It was a check written in a very bold hand with a signature about a half inch high.''</s>
</TEXT>
</DOC>
