<DOC>
<DOCNO>

<s docid="AP890426-0204" num="1" wdcount="1"> AP890426-0204</s>
</DOCNO>
<FILEID>

<s docid="AP890426-0204" num="2" wdcount="2"> AP-NR-04-26-89 2211EST</s>
</FILEID>
<FIRST>

<s docid="AP890426-0204" num="3" wdcount="5"> r i AM-Ball-Gordon 04-26 0412</s>
</FIRST>
<SECOND>

<s docid="AP890426-0204" num="4" wdcount="1"> AM-Ball-Gordon,0422</s>
</SECOND>
<HEAD>

<s docid="AP890426-0204" num="5" wdcount="6"> Longtime Sidekick Remembers Lucy Back When</s>
</HEAD>
<HEAD>

<s docid="AP890426-0204" num="6" wdcount="3"> With AM-Obit-Ball, Bjt</s>
</HEAD>
<DATELINE>

<s docid="AP890426-0204" num="7" wdcount="3"> EDMONTON, Alberta (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890426-0204" num="8" wdcount="32"> Actor Gale Gordon, a sidekick of Lucille Ball from radio days who appeared with her in three television series, recalled on Wednesday how the comedian never thought of herself as particularly funny.</s>

<s docid="AP890426-0204" num="9" wdcount="31"> ``Oh, but when she told a story or recalled an event that happened she always illustrated it with her body and her face,'' the 83-year-old Gordon said in a telephone interview.</s>

<s docid="AP890426-0204" num="10" wdcount="9"> ``She never saw it, but she was extremely amusing''.</s>

<s docid="AP890426-0204" num="11" wdcount="38"> Gordon, who is appearing in a play in Edmonton, spent the day in an Edmonton hotel room, mourning the death of Lucille Ball in a Los Angeles hospital Wednesday at age 77 and quietly remembering his funny friend.</s>

<s docid="AP890426-0204" num="12" wdcount="9"> ``The world will miss her greatly,'' the actor said.</s>

<s docid="AP890426-0204" num="13" wdcount="16"> ``I personally will remember her as the best talent of her kind in the world ...</s>

<s docid="AP890426-0204" num="14" wdcount="18"> a wonderful, warm friend and a bit of a genius _ the only one I've ever really known''.</s>

<s docid="AP890426-0204" num="15" wdcount="21"> In his first television series alongside Miss Ball, Gordon was the flustered banker Mr. Mooney in ``The Lucy Show'' from 1962-68.</s>

<s docid="AP890426-0204" num="16" wdcount="12"> The next six years saw him as Harrison Carter on ``Here's Lucy''.</s>

<s docid="AP890426-0204" num="17" wdcount="12"> They were reunited briefly in 1986 for the short-lived ``Life With Lucy''.</s>

<s docid="AP890426-0204" num="18" wdcount="22"> Gordon first met Miss Ball in 1947 on the radio program ``My Favorite Husband,'' which later became ``I Love Lucy'' on television.</s>

<s docid="AP890426-0204" num="19" wdcount="14"> ``I thought she was a very good-looking young woman, and very talented,'' he recalled.</s>

<s docid="AP890426-0204" num="20" wdcount="7"> ``She was very pleasant to work with.</s>

<s docid="AP890426-0204" num="21" wdcount="21"> None of us knew what was going to happen _ television was very young then and it wasn't taken too seriously.</s>

<s docid="AP890426-0204" num="22" wdcount="12"> We never dreamed it would ever become the power it was ...</s>

<s docid="AP890426-0204" num="23" wdcount="7"> and the great stars it would produce''.</s>

<s docid="AP890426-0204" num="24" wdcount="30"> Gordon last spoke to Miss Ball from Edmonton on his birthday, Feb. 20, when ``she called to wish me a happy birthday as she has done for years and years''.</s>

<s docid="AP890426-0204" num="25" wdcount="17"> Gordon has done regular stints for years at a chain of Edmonton-based dinner theatres called Stage West.</s>

<s docid="AP890426-0204" num="26" wdcount="18"> He is currently appearing with that company's Mayfair Dinner Theatre as a priest in the play ``Mass Appeal''.</s>

<s docid="AP890426-0204" num="27" wdcount="21"> The play has another month to run and Gordon says that means he won't be able to attend Miss Ball's funeral.</s>

<s docid="AP890426-0204" num="28" wdcount="14"> ``I couldn't do that because it would put people out of work,'' he said.</s>

<s docid="AP890426-0204" num="29" wdcount="15"> ``She would be the first one to scream her head off if I did that.''</s>
</TEXT>
</DOC>
