<DOC>
<DOCNO>

<s docid="AP890426-0160" num="1" wdcount="1"> AP890426-0160</s>
</DOCNO>
<FILEID>

<s docid="AP890426-0160" num="2" wdcount="2"> AP-NR-04-26-89 1747EST</s>
</FILEID>
<FIRST>

<s docid="AP890426-0160" num="3" wdcount="5"> u a AM-Ball-Hometown 04-26 0509</s>
</FIRST>
<SECOND>

<s docid="AP890426-0160" num="4" wdcount="1"> AM-Ball-Hometown,0527</s>
</SECOND>
<HEAD>

<s docid="AP890426-0160" num="5" wdcount="6"> Lucille Ball Remembered In Her Hometown</s>
</HEAD>
<HEAD>

<s docid="AP890426-0160" num="6" wdcount="3"> With AM-Obit-Ball, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP890426-0160" num="7" wdcount="3"> By DARREN DOPP</s>
</BYLINE>
<BYLINE>

<s docid="AP890426-0160" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890426-0160" num="9" wdcount="3"> JAMESTOWN, N.Y. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890426-0160" num="10" wdcount="21"> Lucille Ball was mourned Wednesday by the western New York hometown she left for Hollywood more than half a century ago.</s>

<s docid="AP890426-0160" num="11" wdcount="9"> ``It is a sad day for all of us.</s>

<s docid="AP890426-0160" num="12" wdcount="31"> But I'm sure that feeling is shared by many people around the world,'' said Nelson Garifi, organizer of a homecoming for Miss Ball that was to have been held next month.</s>

<s docid="AP890426-0160" num="13" wdcount="24"> ``She was always so full of life,'' said Pauline Lopus, who went to school with Miss Ball and had kept in touch with her.</s>

<s docid="AP890426-0160" num="14" wdcount="9"> ``It seemed like she would just go on forever''.</s>

<s docid="AP890426-0160" num="15" wdcount="29"> The 77-year-old comedian died of a ruptured aorta, the main heart artery, at Cedars-Sinai Medical Center in Los Angeles, where she was recovering from emergency heart surgery last week.</s>

<s docid="AP890426-0160" num="16" wdcount="23"> The American Heart Association's Jamestown office was deluged with calls from Miss Ball's fans who wanted to make a memorial donation, officials said.</s>

<s docid="AP890426-0160" num="17" wdcount="15"> ``We just can't process as many memorials as we've received,'' said office manager Nathan Lax.</s>

<s docid="AP890426-0160" num="18" wdcount="28"> Miss Ball was born Aug. 6, 1911, in this city of 40,000 people about 60 miles south of Buffalo, the daughter of an electrician and a concert pianist.</s>

<s docid="AP890426-0160" num="19" wdcount="12"> She grew up in nearby Celoron, a rural hamlet on Chautauqua Lake.</s>

<s docid="AP890426-0160" num="20" wdcount="27"> Friends said some of the characteristics of her most famous role _ the zany, excitable star of television's ``I Love Lucy'' _ were evident during her childhood.</s>

<s docid="AP890426-0160" num="21" wdcount="24"> Mrs. Lopus said Miss Ball dreamed of fame, either as a dramatic actress in New York City or as a dancing girl in musicals.</s>

<s docid="AP890426-0160" num="22" wdcount="25"> At age 15, she worked as a barker at a local amusement park, screaming pitches for popcorn and hot dogs until she lost her voice.</s>

<s docid="AP890426-0160" num="23" wdcount="24"> In high school, she starred in high school plays and made her first appearance before a large audience at the now-defunct Palace Theater here.</s>

<s docid="AP890426-0160" num="24" wdcount="15"> As a model, she caught Hollywood's eye and in 1933, she was off to Hollywood.</s>

<s docid="AP890426-0160" num="25" wdcount="29"> Although the comedian hadn't visited Jamestown since 1956 and had no family there, she regularly donated money to charities, civic events and Jamestown Community College, said Mayor Steven Carlson.</s>

<s docid="AP890426-0160" num="26" wdcount="19"> Miss Ball was to have received an honorary degree from the college at the homecoming scheduled for May 20.</s>

<s docid="AP890426-0160" num="27" wdcount="13"> Residents had hung posters saying ``Jamestown Loves Lucy'' in storefronts and house windows.</s>

<s docid="AP890426-0160" num="28" wdcount="19"> After she fell ill last week, residents signed the posters and sent them to her as a get-well greeting.</s>

<s docid="AP890426-0160" num="29" wdcount="9"> They sent more than 150 posters with 10,000 signatures.</s>

<s docid="AP890426-0160" num="30" wdcount="17"> The honorary degree will be awarded posthumously, said Garifi, who is community relations director at the college.</s>

<s docid="AP890426-0160" num="31" wdcount="30"> Celoron had planned to rename a street in Miss Ball's honor during her visit, and still plans to rename it as Lucy Lane, said John Goodell of Celoron's Historical Society.</s>

<s docid="AP890426-0160" num="32" wdcount="35"> Goodell said that when the group was formed about a year ago, ``We sent an invitation to Lucille Ball to be a member, and she sent back a check for $500 for a life membership.''</s>
</TEXT>
</DOC>
