<DOC>
<DOCNO>

<s docid="AP890426-0185" num="1" wdcount="1"> AP890426-0185</s>
</DOCNO>
<FILEID>

<s docid="AP890426-0185" num="2" wdcount="2"> AP-NR-04-26-89 1951EST</s>
</FILEID>
<FIRST>

<s docid="AP890426-0185" num="3" wdcount="7"> u a AM-Obit-Ball 1stLd-Writethru a0693 04-26 1210</s>
</FIRST>
<SECOND>

<s docid="AP890426-0185" num="4" wdcount="4"> AM-Obit-Ball, 1st Ld-Writethru, a0693,1242</s>
</SECOND>
<HEAD>

<s docid="AP890426-0185" num="5" wdcount="6"> Actress-Comedian Lucille Ball Dies at 77</s>
</HEAD>
<HEAD>

<s docid="AP890426-0185" num="6" wdcount="9"> Eds: INSERTS 1 graf after 9th, `I and ...</s>

<s docid="AP890426-0185" num="7" wdcount="16"> , to UPDATE with comment from President Bush; picks up 10th graf: ``Her red .. .</s>
</HEAD>
<HEAD>

<s docid="AP890426-0185" num="8" wdcount="8"> LaserPhotos LA4, NY28, 36, 38, 40, LaserColor NY31</s>
</HEAD>
<BYLINE>

<s docid="AP890426-0185" num="9" wdcount="3"> By JOHN HORN</s>
</BYLINE>
<BYLINE>

<s docid="AP890426-0185" num="10" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890426-0185" num="11" wdcount="3"> LOS ANGELES (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890426-0185" num="12" wdcount="26"> Lucille Ball, the daffy comedian whose harebrained schemes drove her television family crazy but delighted viewers for four decades, died Wednesday of a ruptured abdominal artery.</s>

<s docid="AP890426-0185" num="13" wdcount="3"> She was 77.</s>

<s docid="AP890426-0185" num="14" wdcount="27"> The actress, star of the hugely popular ``I Love Lucy'' and related situation comedies seen in more than 80 countries, had undergone major heart surgery April 18.</s>

<s docid="AP890426-0185" num="15" wdcount="40"> She had been recovering steadily, getting out of bed and joking with the staff, but shortly before dawn Wednesday, she went into cardiac arrest due to internal bleeding and could not be revived, said Cedars-Sinai Medical Center spokesman Ronald Wise.</s>

<s docid="AP890426-0185" num="16" wdcount="19"> She suffered a complete heart failure at 5 a.m. and 47 minutes of resuscitation efforts proved fruitless, Wise said.</s>

<s docid="AP890426-0185" num="17" wdcount="10"> ``There was nothing to indicate this would happen,'' Wise said.</s>

<s docid="AP890426-0185" num="18" wdcount="12"> ``The heart itself apparently was not involved in Miss Ball's sudden death''.</s>

<s docid="AP890426-0185" num="19" wdcount="13"> In the 6-hour surgery at Cedars-Sinai, doctors replaced her aorta and aortic valve.</s>

<s docid="AP890426-0185" num="20" wdcount="28"> Although the replaced portion of Miss Ball's aorta did not apparently fail, the entire artery was in poor condition when she was operated upon, said Dr. Robert Kass.</s>

<s docid="AP890426-0185" num="21" wdcount="23"> Kass, who performed the operation, said at the time the tearing in Miss Ball's aorta ``progressed all the way down into her abdomen''.</s>

<s docid="AP890426-0185" num="22" wdcount="24"> Miss Ball, with her fire-engine red hair and siren wail, was considered the queen of situation comedy and a pioneer of the sitcom format.</s>

<s docid="AP890426-0185" num="23" wdcount="12"> ``I and 100 million others will miss her,'' said comedian George Burns.</s>

<s docid="AP890426-0185" num="24" wdcount="21"> ``But we haven't lost Lucille Ball because she's still with us on television and we can see her on and on''.</s>

<s docid="AP890426-0185" num="25" wdcount="7"> ``Lucille Ball possessed the gift of laughter.</s>

<s docid="AP890426-0185" num="26" wdcount="19"> But she also embodied an even greater treasure _ the gift of love,'' President Bush said in a statement.</s>

<s docid="AP890426-0185" num="27" wdcount="10"> ``She appealed to the gentler impulses of the human spirit.</s>

<s docid="AP890426-0185" num="28" wdcount="8"> She was not merely an actress or comedienne.</s>

<s docid="AP890426-0185" num="29" wdcount="7"> She was Lucy and she was loved''.</s>

<s docid="AP890426-0185" num="30" wdcount="29"> ``Her red hair, her antics on the screen, her timing and her zest for life made her an American institution,'' former President and Nancy Reagan said in a statement.</s>

<s docid="AP890426-0185" num="31" wdcount="9"> ``Just the mention of her name brings a smile.</s>

<s docid="AP890426-0185" num="32" wdcount="9"> ... We love Lucy and will miss her deeply''.</s>

<s docid="AP890426-0185" num="33" wdcount="28"> ``It's a shock after working very closely with her and loving her for over 35 years,'' said Miss Ball's frequent sidekick, Gale Gordon, who was in Edmonton, Alberta.</s>

<s docid="AP890426-0185" num="34" wdcount="26"> While in the hospital, the comedian was deluged with thousands of cards, letters, flowers and phone calls from fans as far away as Australia and Europe.</s>

<s docid="AP890426-0185" num="35" wdcount="27"> Miss Ball and her late former husband, Desi Arnaz, starred in ``I Love Lucy'' from 1951 to 1957 and have been seen since in widely syndicated reruns.</s>

<s docid="AP890426-0185" num="36" wdcount="14"> The late Vivian Vance and William Frawley played their neighbors, Fred and Ethel Mertz.</s>

<s docid="AP890426-0185" num="37" wdcount="22"> Her split-second timing, wide-mouthed wails and exaggerated pratfalls made the ``I Love Lucy'' show one of the most popular in television history.</s>

<s docid="AP890426-0185" num="38" wdcount="28"> Bridge clubs and bowling teams changed their meeting nights to watch Lucy and Ethel cook up still another ridiculous scheme that would push their long-suffering husbands to exasperation.</s>

<s docid="AP890426-0185" num="39" wdcount="39"> Miss Ball's real, onscreen pregnancy marked a milestone in television, and an estimated 44 million viewers _ more than for the inauguration of President Eisenhower _ tuned in on Jan. 19, 1953, to watch Lucy Ricardo have Little Ricky.</s>

<s docid="AP890426-0185" num="40" wdcount="13"> The real birth occurred just four hours before the previously-filmed show was broadcast.</s>

<s docid="AP890426-0185" num="41" wdcount="15"> Miss Ball's singularity as a comedian was matched by her talent as a show-business entrepreneur.</s>

<s docid="AP890426-0185" num="42" wdcount="11"> She and Arnaz established one of TV's first major independent studios.</s>

<s docid="AP890426-0185" num="43" wdcount="30"> Desilu, as their production company was called, made some of the top comedy shows of the 1950s and '60s, including ``December Bride,'' ``Our Miss Brooks'' and ``Make Room for Daddy''.</s>

<s docid="AP890426-0185" num="44" wdcount="42"> As testament to their value as prime-time stars, Miss Ball and Arnaz signed an $8 million, no-cancellation, two-year contract with CBS in 1953 _ the largest in television history at the time and a figure scarcely any TV star can touch today.</s>

<s docid="AP890426-0185" num="45" wdcount="11"> The couple stopped making weekly ``I Love Lucy'' shows in 1957.</s>

<s docid="AP890426-0185" num="46" wdcount="18"> Despite riches and two children, Lucie and Desi Jr., their marriage foundered, and the couple divorced in 1960.</s>

<s docid="AP890426-0185" num="47" wdcount="31"> In 1961, Miss Ball married nightclub comic Gary Morton, who became her executive producer, and remained on TV for 12 more years in the weekly ``Here's Lucy'' and ``The Lucy Show''.</s>

<s docid="AP890426-0185" num="48" wdcount="19"> Miss Ball was born Aug. 6, 1911, in Jamestown, N.Y., the daughter of an electrician and a concert pianist.</s>

<s docid="AP890426-0185" num="49" wdcount="46"> Young Lucy, a brunette, was dazzled by the stage, but her ambitions were discouraged by an acting school _ ``They sent my mother a letter saying she was wasting her money,'' Miss Ball once said _ and she turned to modeling under the name Diane Belmont.</s>

<s docid="AP890426-0185" num="50" wdcount="15"> Her ads for Chesterfield cigarettes caught Hollywood's eye, and in 1933 she went to California.</s>

<s docid="AP890426-0185" num="51" wdcount="29"> As a blonde, she appeared with the Marx Brothers in ``Room Service,'' with Fred Astaire in ``Follow the Fleet'' and with Katharine Hepburn and Ginger Rogers in ``Stage Door''.</s>

<s docid="AP890426-0185" num="52" wdcount="9"> In all, she appeared in more than 75 movies.</s>

<s docid="AP890426-0185" num="53" wdcount="16"> In 1940, her tresses colored the fiery trademark red, Miss Ball met Arnaz, a rumba star.</s>

<s docid="AP890426-0185" num="54" wdcount="5"> They married within six months.</s>

<s docid="AP890426-0185" num="55" wdcount="23"> In 1951, when CBS decided to move her radio series, ``My Favorite Husband,'' to television, Miss Ball insisted that Arnaz be her co-star.</s>

<s docid="AP890426-0185" num="56" wdcount="14"> But the network wasn't sure Arnaz would be a hit with the American public.</s>

<s docid="AP890426-0185" num="57" wdcount="26"> The couple went on a nationwide vaudeville tour and proved audiences would watch a leggy, blue-eyed comedian and a Cuban-born band leader with a heavy accent.</s>

<s docid="AP890426-0185" num="58" wdcount="10"> They also produced their own pilot episode on borrowed money.</s>

<s docid="AP890426-0185" num="59" wdcount="10"> CBS relented, and ``I Love Lucy'' was an immediate success.</s>

<s docid="AP890426-0185" num="60" wdcount="11"> The show revolutionized television sitcom production in the days before videotape.</s>

<s docid="AP890426-0185" num="61" wdcount="21"> It was filmed in advance before a live audience, employing three cameras instead of the traditional one used for motion pictures.</s>

<s docid="AP890426-0185" num="62" wdcount="31"> The actress was last seen at the 61st Academy Awards ceremony March 29, where the svelte actress received a standing ovation and laughed freely throughout her brief bit with Bob Hope.</s>

<s docid="AP890426-0185" num="63" wdcount="23"> Her last series _ ``Life with Lucy,'' once again co-starring Gordon _ was carried by ABC at the start of the 1986 season.</s>

<s docid="AP890426-0185" num="64" wdcount="22"> But the show, her first series in 12 years, was canceled after less than two months when it drew spectacularly low ratings.</s>

<s docid="AP890426-0185" num="65" wdcount="3"> She ``felt terrible.</s>

<s docid="AP890426-0185" num="66" wdcount="12"> ... It really devastated her,'' daughter Lucie Arnaz said at the time.</s>

<s docid="AP890426-0185" num="67" wdcount="24"> Miss Ball also played a bag lady in the 1985 TV movie ``Stone Pillow,'' considered one of the most challenging roles of her career.</s>

<s docid="AP890426-0185" num="68" wdcount="19"> She was hospitalized for dehydration when it was over, but the movie was a minor critical and ratings success.</s>

<s docid="AP890426-0185" num="69" wdcount="19"> Just this month, Miss Ball had signed a deal for a reported $750,000 with Putnam to publish her autobiography.</s>

<s docid="AP890426-0185" num="70" wdcount="15"> Said CBS Chairman William Paley: ``Lucille Ball will always be the first lady of CBS.</s>

<s docid="AP890426-0185" num="71" wdcount="20"> ... Lucy's extraordinary ability to light up the screen and brighten our lives is a legacy that will last forever''.</s>

<s docid="AP890426-0185" num="72" wdcount="5"> Funeral arrangements were pending .</s>
</TEXT>
</DOC>
