<DOC>
<DOCNO>

<s docid="AP890426-0126" num="1" wdcount="1"> AP890426-0126</s>
</DOCNO>
<FILEID>

<s docid="AP890426-0126" num="2" wdcount="2"> AP-NR-04-26-89 1457EST</s>
</FILEID>
<FIRST>

<s docid="AP890426-0126" num="3" wdcount="5"> r a AM-Lucy'sLittleRicky 04-26 0483</s>
</FIRST>
<SECOND>

<s docid="AP890426-0126" num="4" wdcount="3"> AM-Lucy's Little Ricky,0493</s>
</SECOND>
<HEAD>

<s docid="AP890426-0126" num="5" wdcount="9"> Little Ricky, Now 38, Remembers Lucy as Surrogate Mom</s>
</HEAD>
<HEAD>

<s docid="AP890426-0126" num="6" wdcount="3"> With AM-Obit-Ball, Bjt</s>
</HEAD>
<HEAD>

<s docid="AP890426-0126" num="7" wdcount="2"> LaserPhoto JX2</s>
</HEAD>
<BYLINE>

<s docid="AP890426-0126" num="8" wdcount="3"> By RON HARRIST</s>
</BYLINE>
<BYLINE>

<s docid="AP890426-0126" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890426-0126" num="10" wdcount="3"> JACKSON, Miss. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890426-0126" num="11" wdcount="38"> The actor who played Little Ricky on the ``I Love Lucy'' show said Wednesday he spent more time with Lucille Ball than he did with his own family in the five years he played the comedian's TV son.</s>

<s docid="AP890426-0126" num="12" wdcount="19"> Miss Ball died of a ruptured aorta at Cedars-Sinai Medical Center in Los Angeles Wednesday morning, hospital officials said.</s>

<s docid="AP890426-0126" num="13" wdcount="3"> She was 77.</s>

<s docid="AP890426-0126" num="14" wdcount="44"> ``She was old and, of course, I knew about the heart attack, so I was not shocked by her death,'' said Keith Thibodeaux, who at age 6 began playing Miss Ball's drum-playing son on the comedy series that continues in syndication around the world.</s>

<s docid="AP890426-0126" num="15" wdcount="13"> ``I'm sure all this is going to hit me a little later on''.</s>

<s docid="AP890426-0126" num="16" wdcount="18"> Thibodeaux grew up on the set, playing Little Ricky from 1956 until 1961 under Miss Ball's watchful eye.</s>

<s docid="AP890426-0126" num="17" wdcount="49"> ``I think the thing I remember most about Lucy was that she was very much in control of everything,'' said Thibodeaux, who began playing the drums at age 2, was a professional drummer at age 4 and is now drummer with David and the Giants, a Christian rock group.</s>

<s docid="AP890426-0126" num="18" wdcount="10"> He lives in Jackson with his wife, Kathy, a ballerina.</s>

<s docid="AP890426-0126" num="19" wdcount="47"> Thibodeaux, 38, said he got his break in show business when big band leader Horace Heidt persuaded his father to bring him from Lafayette, La., to California for the ``Swift Premium Hour,'' a traveling radio show that led to a string of one-night stands across the country.</s>

<s docid="AP890426-0126" num="20" wdcount="13"> That led to an audition for the ``I Love Lucy'' role in Hollywood.</s>

<s docid="AP890426-0126" num="21" wdcount="23"> ``I remember Lucy saying, `that's him,' and from that time I was Little Ricky,'' said Thibodeaux, who then used the name Richard Keith.</s>

<s docid="AP890426-0126" num="22" wdcount="29"> ``I signed a seven-year contract with the studio in 1956 and the first episode I was in was aired that December with Bob Hope _ I just turned 6''.</s>

<s docid="AP890426-0126" num="23" wdcount="22"> Thibodeaux said that during the series' run he spent as much time with Miss Ball as with his own family in Lafayette.</s>

<s docid="AP890426-0126" num="24" wdcount="19"> ``And I spent more time with her off the set at her home than at the studio,'' he said.</s>

<s docid="AP890426-0126" num="25" wdcount="12"> ``I remember her as very strict but with a lot of love.</s>

<s docid="AP890426-0126" num="26" wdcount="15"> She had her ways but despite all, she was a great person, very, very talented.</s>

<s docid="AP890426-0126" num="27" wdcount="16"> ``I know everybody remembers her as zany and wacky but that was only on the show.</s>

<s docid="AP890426-0126" num="28" wdcount="10"> Actually, she was just the opposite and was very serious.</s>

<s docid="AP890426-0126" num="29" wdcount="8"> ... That's what made her a great actress''.</s>

<s docid="AP890426-0126" num="30" wdcount="20"> He said Miss Ball often gave him gifts and that he remembers spending at least one Christmas at her home.</s>

<s docid="AP890426-0126" num="31" wdcount="16"> ``I remember she once gave me an Indian tepee, then my own dressing room,'' he said.</s>

<s docid="AP890426-0126" num="32" wdcount="10"> ``She gave me bicycles and an identical set of drums.''</s>
</TEXT>
</DOC>
