<DOC>
<DOCNO>

<s docid="AP890426-0123" num="1" wdcount="1"> AP890426-0123</s>
</DOCNO>
<FILEID>

<s docid="AP890426-0123" num="2" wdcount="2"> AP-NR-04-26-89 1404EST</s>
</FILEID>
<FIRST>

<s docid="AP890426-0123" num="3" wdcount="5"> r a AM-Ball-Career 04-26 0310</s>
</FIRST>
<SECOND>

<s docid="AP890426-0123" num="4" wdcount="1"> AM-Ball-Career,0325</s>
</SECOND>
<HEAD>

<s docid="AP890426-0123" num="5" wdcount="5"> Career Highlights Of Lucille Ball</s>
</HEAD>
<HEAD>

<s docid="AP890426-0123" num="6" wdcount="3"> With AM-Obit-Ball Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP890426-0123" num="7" wdcount="4"> By The Associated Press</s>
</BYLINE>
<TEXT>

<s docid="AP890426-0123" num="8" wdcount="26"> Here are highlights of Lucille Ball's career: 1911 _ Born Aug. 6, 1911, in Jamestown N.Y., the daughter of an electrician and concert pianist Desiree Ball.</s>

<s docid="AP890426-0123" num="9" wdcount="14"> 1926 _ Begins career in show business in New York as a chorus girl.</s>

<s docid="AP890426-0123" num="10" wdcount="21"> 1933 _ Goes to Hollywood as movie showgirl for RKO, later becoming a successful actress appearing in more than 75 films.</s>

<s docid="AP890426-0123" num="11" wdcount="19"> 1940 _ Marries Desi Arnaz, a Cuban percussionist and bandleader when both were making the movie ``Too Many Girls''.</s>

<s docid="AP890426-0123" num="12" wdcount="20"> 1951 _ They form Desilu Productions with $5,000 and ``I Love Lucy'' begins its historic six-year domination of television comedy.</s>

<s docid="AP890426-0123" num="13" wdcount="9"> Earlier in the year, they have their first child.</s>

<s docid="AP890426-0123" num="14" wdcount="44"> 1953 _ ``I Love Lucy'' episode in which Lucy Ricardo gives birth to Little Ricky is telecast the same day that Lucille Ball, in real life, gives birth to second child, Desi Jr. 1957 _ Desilu purchases RKO studios and begins producing other programs.</s>

<s docid="AP890426-0123" num="15" wdcount="18"> 1960 _ The Arnazes divorce, with Desi selling his share of the studio to Lucy for $3 million.</s>

<s docid="AP890426-0123" num="16" wdcount="14"> 1961 _ Miss Ball marries night-club comic Gary Morton, who becomes her executive producer.</s>

<s docid="AP890426-0123" num="17" wdcount="14"> 1962 _ Miss Ball goes solo, returning to the airwaves in ``The Lucy Show''.</s>

<s docid="AP890426-0123" num="18" wdcount="13"> 1967 _ Miss Ball sells company to Gulf & Western for $18 million.</s>

<s docid="AP890426-0123" num="19" wdcount="11"> 1968 _ ``The Lucy Show'' is redesigned and becomes ``Here's Lucy''.</s>

<s docid="AP890426-0123" num="20" wdcount="4"> It runs until 1974.</s>

<s docid="AP890426-0123" num="21" wdcount="14"> 1974 _ Miss Ball plays the title role in the movie version of ``Mame''.</s>

<s docid="AP890426-0123" num="22" wdcount="24"> 1985 _ In her first serious dramatic role in years, Miss Ball plays a New York bag lady in the CBS-TV movie ``Stone Pillow''.</s>

<s docid="AP890426-0123" num="23" wdcount="11"> She is hospitalized for dehydration following strenuous work on the film.</s>

<s docid="AP890426-0123" num="24" wdcount="13"> 1986 _ Miss Ball returns to sitcom television in ABC's ``Life With Lucy''.</s>

<s docid="AP890426-0123" num="25" wdcount="7"> The show is canceled within months .</s>
</TEXT>
</DOC>
