<DOC>
<DOCNO>

<s docid="LA042789-0068" num="1" wdcount="1"> LA042789-0068</s>
</DOCNO>
<DOCID>

<s docid="LA042789-0068" num="2" wdcount="1"> 49414</s>
</DOCID>
<DATE>
<P>

<s docid="LA042789-0068" num="3" wdcount="6"> April 27, 1989, Thursday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA042789-0068" num="4" wdcount="9"> Calendar; Part 6; Page 1; Column 1; Entertainment Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA042789-0068" num="5" wdcount="2"> 643 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA042789-0068" num="6" wdcount="3"> EVERYBODY LOVED LUCY;</s>
</P>
<P>

<s docid="LA042789-0068" num="7" wdcount="7"> LUCILLE BALL MADE IT ALL LOOK SPONTANEOUS</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA042789-0068" num="8" wdcount="6"> By CHARLES CHAMPLIN, Times Arts Editor</s>
</P>
</BYLINE>
<TEXT>
<P>

<s docid="LA042789-0068" num="9" wdcount="32"> Lucille Ball, whose death Wednesday morning at the age of 77 will be the most widely and deeply felt show-business loss in recent memory, was the movies' greatest gift to television .</s>
</P>
<P>

<s docid="LA042789-0068" num="10" wdcount="34"> It turned out to be one of Sam Goldwyn's finest and most prophetic hours when he signed her as one of his Goldwyn Girls to appear in "Roman Scandals" with Eddie Cantor in 1933.</s>

<s docid="LA042789-0068" num="11" wdcount="30"> She had had bit parts in two earlier films but "Roman Scandals" was the one that gave her a firmer foothold on the slippery slopes of a Hollywood career .</s>
</P>
<P>

<s docid="LA042789-0068" num="12" wdcount="6"> The movies prepared her for television.</s>

<s docid="LA042789-0068" num="13" wdcount="26"> She perfected her matchless craft as a comedienne in dozens of films, including three of Fred Astaire's and one of the Marx Brothers ("Room Service") .</s>
</P>
<P>

<s docid="LA042789-0068" num="14" wdcount="16"> A lot of the other films caused few ripples on the wide surface of film history.</s>

<s docid="LA042789-0068" num="15" wdcount="40"> But in those years Lucy was refining her enduring, endearing public image as a perky, saucy woman who was likelier (at least in the early days) to end up with the hero's funny pal than with the hero himself .</s>
</P>
<P>

<s docid="LA042789-0068" num="16" wdcount="35"> Yet as often happened with supporting performers, her verve, an engagingly sharp tongue and a rather salty view of the world made her more interesting than the square-cut principals, and led to leading roles .</s>
</P>
<P>

<s docid="LA042789-0068" num="17" wdcount="23"> To look at the "I Love Lucy" reruns today, as everybody does, again and again, is to realize how superbly professional they are.</s>

<s docid="LA042789-0068" num="18" wdcount="19"> Today many sitcoms still use the three-camera technique, shooting in front of live audiences, that Desi Arnaz pioneered .</s>
</P>
<P>

<s docid="LA042789-0068" num="19" wdcount="43"> The idea now seems as inevitable as the wheel or pre-sliced muffins, and yet you wonder if it would have worked nearly as well or caught on at all without Lucy's sheer expertise as a physical as well as a verbal comedienne .</s>
</P>
<P>

<s docid="LA042789-0068" num="20" wdcount="33"> She made it all -- even the wildest, craziest capers -- look as if it were happening now -- spontaneous, unrehearsed, accidental, the inevitable consequences of the screen Lucy's scatterbrained and lovable personality.</s>

<s docid="LA042789-0068" num="21" wdcount="26"> Her foils -- Desi himself, Vivian Vance and William Frawley -- were superb farceurs themselves, but Lucy was the dynamo that made it all work .</s>
</P>
<P>

<s docid="LA042789-0068" num="22" wdcount="12"> The craft was invisible, the skills so perfected they concealed themselves totally.</s>

<s docid="LA042789-0068" num="23" wdcount="25"> It was a brilliant illusion, generating a charm that hid the hard work and the artful writing and editing as well as the performing .</s>
</P>
<P>

<s docid="LA042789-0068" num="24" wdcount="18"> The result was probably the finest and certainly the most durable single series in television's history thus far.</s>

<s docid="LA042789-0068" num="25" wdcount="18"> The appeal of the Lucy shows was also the most universal that American television has yet provided .</s>
</P>
<P>

<s docid="LA042789-0068" num="26" wdcount="13"> They were wholly, prototypically American, and that is central to their popularity abroad.</s>

<s docid="LA042789-0068" num="27" wdcount="22"> Yet they have been embraced as the kind of middle-class goings-on that might possibly arise almost anywhere there is a middle class.</s>

<s docid="LA042789-0068" num="28" wdcount="11"> Lucy was all-American but, equally, a citizen of the world .</s>
</P>
<P>

<s docid="LA042789-0068" num="29" wdcount="26"> Her successful career in films, in which she ultimately earned star billing if not superstar status, gave her an invaluable identification when "I Love Lucy" began.</s>

<s docid="LA042789-0068" num="30" wdcount="28"> The irony is that, created by the movies, she was to achieve fame and fortune in television on a scale that had eluded her in the movies .</s>
</P>
<P>

<s docid="LA042789-0068" num="31" wdcount="38"> Indeed, when Lucy began to commandeer our hearts on "I Love Lucy" in 1951, the movies were already in considerable trouble, their audiences staying home in large numbers to watch the likes of Lucy in their living rooms.</s>

<s docid="LA042789-0068" num="32" wdcount="7"> As always, her timing was impeccable .</s>
</P>
<P>

<s docid="LA042789-0068" num="33" wdcount="7"> Lucille Ball was not Lucy, of course.</s>

<s docid="LA042789-0068" num="34" wdcount="23"> She had come a hard road from Jamestown, N.Y., in a line of work in which you did not survive by being scatterbrained.</s>

<s docid="LA042789-0068" num="35" wdcount="19"> She was smart, hard-working and a perfectionist who knew that whatever else it was, comedy was not accidental .</s>
</P>
<P>

<s docid="LA042789-0068" num="36" wdcount="45"> Then again, the cameras, television or film, have X-ray properties, and the millions who saw and loved her were not wrong to think they perceived a generous and loving woman, as well as a glorious clown who knew the world was better off laughing .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA042789-0068" num="37" wdcount="20"> Photo, The appeal of 'I Love Lucy' is the most universal that American television has yet provided . . .</s>
</P>
</GRAPHIC>
<TYPE>
<P>

<s docid="LA042789-0068" num="38" wdcount="1"> Profile</s>
</P>
</TYPE>
<SUBJECT>
<P>

<s docid="LA042789-0068" num="39" wdcount="7"> BALL, LUCILLE; HUMOR; COMEDIANS; TELEVISION -- HISTORY</s>
</P>
</SUBJECT>
</DOC>
