<DOC>
<DOCNO>

<s docid="LA042789-0032" num="1" wdcount="1"> LA042789-0032</s>
</DOCNO>
<DOCID>

<s docid="LA042789-0032" num="2" wdcount="1"> 49324</s>
</DOCID>
<DATE>
<P>

<s docid="LA042789-0032" num="3" wdcount="6"> April 27, 1989, Thursday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA042789-0032" num="4" wdcount="8"> Part 1; Page 3; Column 2; Metro Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA042789-0032" num="5" wdcount="2"> 795 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA042789-0032" num="6" wdcount="7"> FANS AND FAMOUS -- ALL LOVED LUCY</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA042789-0032" num="7" wdcount="9"> By CHARISSE JONES and HECTOR TOBAR, Times Staff Writers</s>
</P>
</BYLINE>
<TEXT>
<P>

<s docid="LA042789-0032" num="8" wdcount="12"> Presidents, famous actors, television executives, neighbors and tourists all had their memories.</s>

<s docid="LA042789-0032" num="9" wdcount="8"> Some had known her; most had not .</s>
</P>
<P>

<s docid="LA042789-0032" num="10" wdcount="12"> In form their sentiments ranged from flowers to telegrams to hand-lettered signs.</s>

<s docid="LA042789-0032" num="11" wdcount="9"> Through them all ran a single, constant thread .</s>
</P>
<P>

<s docid="LA042789-0032" num="12" wdcount="11"> They all said they loved Lucy, and they'll miss her .</s>
</P>
<P>

<s docid="LA042789-0032" num="13" wdcount="21"> From former President and Mrs. Ronald Reagan: "Lucille Ball was a gifted comedienne who brought laughter to millions the world over.</s>

<s docid="LA042789-0032" num="14" wdcount="21"> Her red hair, her antics on the screen, her timing and her zest for life made her an American institution" .</s>
</P>
<P>

<s docid="LA042789-0032" num="15" wdcount="16"> Reagan's successor extended his "deepest sympathy" to Miss Ball's family and called her a "legendary figure".</s>

<s docid="LA042789-0032" num="16" wdcount="4"> "We too loved Lucy.</s>

<s docid="LA042789-0032" num="17" wdcount="11"> So did the world," President Bush said in a statement .</s>
</P>
<P>

<s docid="LA042789-0032" num="18" wdcount="14"> Lucille Ball had last appeared in public in March at the Academy Awards ceremony.</s>

<s docid="LA042789-0032" num="19" wdcount="27"> Her co-presenter was Bob Hope, who a few hours after her death said simply, "God has her now, but thanks to television, we'll have her forever" .</s>
</P>
<P>

<s docid="LA042789-0032" num="20" wdcount="31"> The scene on North Roxbury Drive in Beverly Hills where Miss Ball spent her last and what she said were her happiest years was one of curiousity coupled with genuine mourning.</s>

<s docid="LA042789-0032" num="21" wdcount="22"> About 20 people gathered on the sidewalk, some snapping photographs of the home and of the dozen television crews standing outside .</s>
</P>
<P>

<s docid="LA042789-0032" num="22" wdcount="40"> Andy Stern, a neighbor, said that the large white house surrounded by snapdragons and bougainvillea was the most popular of all the homes on the Hollywood Stars' tours: "They (the buses) stop at her house more than any other" .</s>
</P>
<P>

<s docid="LA042789-0032" num="23" wdcount="29"> Another neighbor, Bob Rosati, said he was watching a rerun of "I Love Lucy" when the screen went black and the words "In Memory of Lucille Ball, 1911-1989" appeared.</s>

<s docid="LA042789-0032" num="24" wdcount="12"> "I felt I had lost someone in my family," he said .</s>
</P>
<P>

<s docid="LA042789-0032" num="25" wdcount="36"> Karen Pope, who described herself as an aspiring actress, drove from her Los Angeles home with a little container of flowers and a sign that read: "Lucy is seen in the smile of everyone's eyes" .</s>
</P>
<P>

<s docid="LA042789-0032" num="26" wdcount="20"> She left them with a guard at Miss Ball's home, turned away and said quietly: "She's touched all of us.</s>

<s docid="LA042789-0032" num="27" wdcount="3"> She's not gone.</s>

<s docid="LA042789-0032" num="28" wdcount="8"> She's just playing to a larger audience" .</s>
</P>
<P>

<s docid="LA042789-0032" num="29" wdcount="30"> Many of the people outside the house were like Karen Mestichelli from Philadelphia, a tourist who had purchased a map to the neighborhoods where many of the entertainment greats live.</s>

<s docid="LA042789-0032" num="30" wdcount="10"> "This is the first house we stopped at," she said.</s>

<s docid="LA042789-0032" num="31" wdcount="3"> "I loved her.</s>

<s docid="LA042789-0032" num="32" wdcount="4"> She was good" .</s>
</P>
<P>

<s docid="LA042789-0032" num="33" wdcount="20"> In Paris, entertainer Sammy Davis Jr. called Miss Ball a "great artist -- one of the world's greatest clowns" .</s>
</P>
<P>

<s docid="LA042789-0032" num="34" wdcount="12"> In Boston, comedian Lily Tomlin said: "It's a sad day for me.</s>

<s docid="LA042789-0032" num="35" wdcount="14"> She was a great role model for me and a great funny woman" .</s>
</P>
<P>

<s docid="LA042789-0032" num="36" wdcount="21"> Comedian George Burns, another friend of many years, said, "As long as the world goes on, Lucy will be seen" .</s>
</P>
<P>

<s docid="LA042789-0032" num="37" wdcount="12"> Burns likened Miss Ball's death to that of his wife, Gracie Allen.</s>

<s docid="LA042789-0032" num="38" wdcount="11"> "When Gracie died, it was a shock to me," he said.</s>

<s docid="LA042789-0032" num="39" wdcount="4"> "This is a shock.</s>

<s docid="LA042789-0032" num="40" wdcount="8"> Lucy and Gracie had one quality exactly alike.</s>

<s docid="LA042789-0032" num="41" wdcount="10"> They both dressed like ladies and were very feminine" .</s>
</P>
<P>

<s docid="LA042789-0032" num="42" wdcount="30"> Television and film actor Danny DeVito recalled getting a personal congratulation from Miss Ball in 1981 when he won an Emmy for his work on the TV series "Taxi" .</s>
</P>
<P>

<s docid="LA042789-0032" num="43" wdcount="11"> "It made it like it had been blessed," he recalled .</s>
</P>
<P>

<s docid="LA042789-0032" num="44" wdcount="37"> "To baby boomers, a happy chunk of our childhood is missing," said "Saturday Night Live" comedian Victoria Jackson, who was born two years after the "I Love Lucy" show went off the air as a regular series.</s>

<s docid="LA042789-0032" num="45" wdcount="17"> "She didn't make me laugh out loud, I remember, she just made me happy about life" .</s>
</P>
<P>

<s docid="LA042789-0032" num="46" wdcount="27"> From William S. Paley, chairman of CBS Inc., where "I Loved Lucy" reigned for all those years: "Lucille Ball will always be the first lady of CBS.</s>

<s docid="LA042789-0032" num="47" wdcount="14"> With 'I Love Lucy,' she helped establish television as the nation's leading entertainment medium.</s>

<s docid="LA042789-0032" num="48" wdcount="20"> Lucy's extraordinary ability to light up the screen and brighten our lives is a legacy that will last forever" .</s>
</P>
<P>

<s docid="LA042789-0032" num="49" wdcount="12"> And then there were those at Cedars-Sinai Medical Center where she died.</s>

<s docid="LA042789-0032" num="50" wdcount="19"> They had admired her as a celebrity for years but known her as a person for only days .</s>
</P>
<P>

<s docid="LA042789-0032" num="51" wdcount="26"> A bouquet of red roses had been left in front of the center's north tower and calls were coming in from all over the world .</s>
</P>
<P>

<s docid="LA042789-0032" num="52" wdcount="7"> "The telephone is ringing off the hook.</s>

<s docid="LA042789-0032" num="53" wdcount="10"> People crying on the phone," said hospital spokeswoman Paula Correia.</s>

<s docid="LA042789-0032" num="54" wdcount="10"> "It's a massive outpouring of grief from all ages" .</s>
</P>
<P>

<s docid="LA042789-0032" num="55" wdcount="21"> Maureen LaMour, a hospital admittance representative, said she heard the news of Miss Ball's death on her way to work .</s>
</P>
<P>

<s docid="LA042789-0032" num="56" wdcount="36"> "We (the staff) always kept in touch with how she was doing and kept up with all the gifts and cards she received, because it was like they were for a family member," she said .</s>
</P>
<P>

<s docid="LA042789-0032" num="57" wdcount="6"> "Everyone has grown up with her.</s>

<s docid="LA042789-0032" num="58" wdcount="7"> Our children have grown up with her.</s>

<s docid="LA042789-0032" num="59" wdcount="3"> She's a legend.</s>

<s docid="LA042789-0032" num="60" wdcount="13"> It's like losing a friend, a family member, instead of a celebrity" .</s>
</P>
<P>

<s docid="LA042789-0032" num="61" wdcount="10"> Staff writer Burt A. Folkart contributed to this article .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA042789-0032" num="62" wdcount="18"> Photo, Lucille Ball teamed with Bob Hope at the March 29 Academy Awards show, her last public appearance.</s>

<s docid="LA042789-0032" num="63" wdcount="6"> RANDY LEFFINGWELL / Los Angeles Times</s>
</P>
</GRAPHIC>
<SUBJECT>
<P>

<s docid="LA042789-0032" num="64" wdcount="5"> BALL, LUCILLE; FANS; MEMORIALS; HONORS</s>
</P>
</SUBJECT>
</DOC>
