<DOC>
<DOCNO>

<s docid="LA042689-0146" num="1" wdcount="1"> LA042689-0146</s>
</DOCNO>
<DOCID>

<s docid="LA042689-0146" num="2" wdcount="1"> 49274</s>
</DOCID>
<DATE>
<P>

<s docid="LA042689-0146" num="3" wdcount="6"> April 26, 1989, Wednesday, P.M. Final</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA042689-0146" num="4" wdcount="9"> Part A; Page 1; Column 1; Late Final Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA042689-0146" num="5" wdcount="2"> 1108 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA042689-0146" num="6" wdcount="5"> LUCILLE BALL DIES AT 77;</s>
</P>
<P>

<s docid="LA042689-0146" num="7" wdcount="9"> THE WHOLE WORLD LOVED LUCY DURING TV'S GOLDEN AGE;</s>
</P>
<P>

<s docid="LA042689-0146" num="8" wdcount="6"> SUFFERS AORTA RUPTURE AFTER HEART SURGERY</s>
</P>
</HEADLINE>
<TEXT>
<P>

<s docid="LA042689-0146" num="9" wdcount="35"> Lucille Ball, the leggy showgirl, model and B-grade movie queen whose pumpkin-colored hair and genius for comedy made her an icon of television's early years, died early today, a week after undergoing emergency heart surgery.</s>

<s docid="LA042689-0146" num="10" wdcount="4"> She was 77 .</s>
</P>
<P>

<s docid="LA042689-0146" num="11" wdcount="43"> The high-spirited star of "I Love Lucy," a show that the nation took to its heart as no other and that continues in syndication around the world, died of a ruptured abdominal aorta at Cedars-Sinai Medical Center, hospital spokesman Ronald Wise said .</s>
</P>
<P>

<s docid="LA042689-0146" num="12" wdcount="45"> Miss Ball, who had a heart attack and had throat surgery in 1988, underwent surgery at Cedars-Sinai on April 18 to replace her aorta and aortic valve and had been getting out of bed, eating and even walking around the room in recent days .</s>
</P>
<P>

<s docid="LA042689-0146" num="13" wdcount="19"> Her recovery had seemed so certain that her husband, comedian Gary Morton, had been exchanging jokes with his wife.</s>

<s docid="LA042689-0146" num="14" wdcount="10"> She had been asking about their white poodle, Tinker .</s>
</P>
<P>

<s docid="LA042689-0146" num="15" wdcount="23"> Wise said the rupture occurred in a portion of the aorta, the main heart artery, far from where the operation was performed .</s>
</P>
<P>

<s docid="LA042689-0146" num="16" wdcount="18"> Since the surgery fans had flooded the hospital with hundreds of cards, telegrams and even facsimile machine messages.</s>

<s docid="LA042689-0146" num="17" wdcount="13"> Hospital officials said it was the largest outpouring they had ever seen .</s>
</P>
<P>
</P>
<P>

<s docid="LA042689-0146" num="18" wdcount="4"> 'Name Brings a Smile'</s>
</P>
<P>

<s docid="LA042689-0146" num="19" wdcount="5"> Tributes were plentiful and immediate:</s>
</P>
<P>

<s docid="LA042689-0146" num="20" wdcount="29"> "Her red hair, her antics on the screen, her timing and her zest for life made her an American institution," former President and Nancy Reagan said in a statement.</s>

<s docid="LA042689-0146" num="21" wdcount="9"> "Just the mention of her name brings a smile.</s>

<s docid="LA042689-0146" num="22" wdcount="12"> . . . We love Lucy and will miss her deeply" .</s>
</P>
<P>

<s docid="LA042689-0146" num="23" wdcount="4"> "Oh, what a blow.</s>

<s docid="LA042689-0146" num="24" wdcount="10"> What a shame," said fellow TV clown Dick Van Dyke.</s>

<s docid="LA042689-0146" num="25" wdcount="10"> "She didn't deal in jokes, she dealt in human behavior.</s>

<s docid="LA042689-0146" num="26" wdcount="14"> She was a great physical mime with all the instincts of a Chaplin" .</s>
</P>
<P>

<s docid="LA042689-0146" num="27" wdcount="21"> William S. Paley, chairman of CBS Inc., said from New York: "Lucille Ball will always be the first lady of CBS.</s>

<s docid="LA042689-0146" num="28" wdcount="14"> With 'I Love Lucy' she helped establish television as the nation's leading entertainment medium.</s>

<s docid="LA042689-0146" num="29" wdcount="20"> Lucy's extraordinary ability to light up the screen and brighten our lives is a legacy that will last forever" .</s>
</P>
<P>

<s docid="LA042689-0146" num="30" wdcount="15"> That legacy involved Miss Ball and her late former husband, Cuban band leader Desi Arnaz.</s>

<s docid="LA042689-0146" num="31" wdcount="16"> They starred regularly from 1951 to 1957 as Lucy and Ricky Ricardo in "I Love Lucy".</s>

<s docid="LA042689-0146" num="32" wdcount="15"> The late Vivian Vance and William Frawley played their neighbors, Fred and Ethel Mertz .</s>
</P>
<P>

<s docid="LA042689-0146" num="33" wdcount="9"> The series continued irregularly into the early 1960s .</s>
</P>
<P>
</P>
<P>

<s docid="LA042689-0146" num="34" wdcount="3"> Talent as Entrepreneur</s>
</P>
<P>

<s docid="LA042689-0146" num="35" wdcount="14"> Her singularity as a comedian was matched by her talent as a show-business entrepreneur.</s>

<s docid="LA042689-0146" num="36" wdcount="12"> She and Arnaz established one of TV's first major independent studios .</s>
</P>
<P>

<s docid="LA042689-0146" num="37" wdcount="31"> Desilu, as their production company was called, made some of the top comedy shows of the 1950s and '60s, including "December Bride," "Our Miss Brooks" and "Make Room for Daddy" .</s>
</P>
<P>

<s docid="LA042689-0146" num="38" wdcount="44"> As testament to their value as prime-time stars, Miss Ball and Arnaz signed an $8-million, no-cancellation, two-year contract with CBS in 1953 -- the largest in television history at the time and a figure scarcely any TV star can touch 36 years later .</s>
</P>
<P>

<s docid="LA042689-0146" num="39" wdcount="26"> The actress was last seen introducing the "Young Hollywood" production number with Bob Hope at the 61st Academy Awards ceremony March 29, receiving a standing ovation.</s>

<s docid="LA042689-0146" num="40" wdcount="27"> Looking svelte for her years in a fashionable slit skirt, she seemed to be in good health and laughed freely throughout a brief routine with Hope .</s>
</P>
<P>

<s docid="LA042689-0146" num="41" wdcount="24"> Her last series -- "Life With Lucy," co-starring frequent sidekick Gale Gordon -- was carried by ABC at the start of the 1986 season.</s>

<s docid="LA042689-0146" num="42" wdcount="23"> But the show, Miss Ball's first series in 12 years, was canceled after less than two months when it drew spectacularly low ratings.</s>

<s docid="LA042689-0146" num="43" wdcount="24"> Miss Ball also played a bag lady in the 1985 TV movie "Stone Pillow," considered one of the most challenging roles of her career.</s>

<s docid="LA042689-0146" num="44" wdcount="21"> Her timing, wails and pratfalls had made the "I Love Lucy" show one of the most popular in television history .</s>
</P>
<P>

<s docid="LA042689-0146" num="45" wdcount="34"> Bridge clubs and bowling teams changed their meeting nights to watch Lucy Ricardo and Ethel Mertz come up with yet another harebrained scheme to drive their long-suffering husbands, Ricky and Fred, to desperation .</s>
</P>
<P>
</P>
<P>

<s docid="LA042689-0146" num="46" wdcount="2"> On-Screen Pregnancy</s>
</P>
<P>

<s docid="LA042689-0146" num="47" wdcount="19"> A Chicago department store changed the night it stayed open because shoppers were staying home to watch television .</s>
</P>
<P>

<s docid="LA042689-0146" num="48" wdcount="41"> Miss Ball's real, on-screen pregnancy marked a milestone in television, and an estimated 44 million viewers -- more than watched the inauguration of President Dwight D. Eisenhower -- tuned in on Jan. 19, 1953, the night Lucy Ricardo delivered Little Ricky.</s>

<s docid="LA042689-0146" num="49" wdcount="16"> Her real son was born just four hours before the previously filmed show was broadcast .</s>
</P>
<P>

<s docid="LA042689-0146" num="50" wdcount="17"> Lucille Ball was born in Jamestown, N.Y., the daughter of an electrician and a concert pianist .</s>
</P>
<P>

<s docid="LA042689-0146" num="51" wdcount="44"> Young Lucy, a natural brunette, was dazzled by the stage, but her ambitions were discouraged by an acting school -- "They sent my mother a letter saying she was wasting her money" -- and she turned to modeling under the name Diane Belmont .</s>
</P>
<P>

<s docid="LA042689-0146" num="52" wdcount="18"> Her ads for Chesterfield cigarettes caught the attention of Hollywood, and in 1933 she was off to California.</s>

<s docid="LA042689-0146" num="53" wdcount="30"> As a blonde, she appeared with the Marx Brothers in "Room Service," with Fred Astaire in "Follow the Fleet" and with Katharine Hepburn and Ginger Rogers in "Stage Door" .</s>
</P>
<P>

<s docid="LA042689-0146" num="54" wdcount="10"> In all, she appeared in more than 75 movies .</s>
</P>
<P>
</P>
<P>

<s docid="LA042689-0146" num="55" wdcount="4"> CBS Wary of Arnaz</s>
</P>
<P>

<s docid="LA042689-0146" num="56" wdcount="16"> In 1940, her tresses now the fiery trademark red, Miss Ball met Arnaz, a rumba star.</s>

<s docid="LA042689-0146" num="57" wdcount="6"> They married within six months .</s>
</P>
<P>

<s docid="LA042689-0146" num="58" wdcount="23"> In 1951, when CBS decided to move her radio series, "My Favorite Husband," to television, Miss Ball insisted that Arnaz be her co-star.</s>

<s docid="LA042689-0146" num="59" wdcount="16"> But the network wasn't sure that Arnaz would be a hit with the American public .</s>
</P>
<P>

<s docid="LA042689-0146" num="60" wdcount="30"> The couple went on a nationwide vaudeville tour and proved that audiences would sit still to watch a leggy, blue-eyed comedian and a Cuban-born band leader with a heavy accent.</s>

<s docid="LA042689-0146" num="61" wdcount="55"> CBS relented and her antics became comedy classics: Lucy putting too much yeast in the bread, which quickly fills up her kitchen and pins her against the wall; Lucy fighting with a fellow grape-presser in a giant wine-making vat; Lucy rehearsing a commercial for a health tonic and becoming drunk from its alcohol content .</s>
</P>
<P>

<s docid="LA042689-0146" num="62" wdcount="12"> The show also revolutionized television sitcom production in the days before videotape.</s>

<s docid="LA042689-0146" num="63" wdcount="22"> It was filmed in advance before a live audience, employing three cameras instead of the traditional one used for motion pictures .</s>
</P>
<P>

<s docid="LA042689-0146" num="64" wdcount="21"> Filming the shows also made them marketable as reruns, and they continue to be seen in more than 80 countries .</s>
</P>
<P>

<s docid="LA042689-0146" num="65" wdcount="24"> Despite riches and two children, Lucie and Desi Jr., both of whom became actors, the marriage foundered, and the couple divorced in 1960 .</s>
</P>
<P>

<s docid="LA042689-0146" num="66" wdcount="13"> Arnaz died in 1986, Miss Vance in 1979 and Frawley in 1966 .</s>
</P>
<P>

<s docid="LA042689-0146" num="67" wdcount="12"> Photos of Miss Ball's family and television show on Page 2 .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA042689-0146" num="68" wdcount="19"> Photo, Desi Arnaz, Lucille Ball's first husband, gives his wife and business partner a kiss in this 1955 photo.</s>

<s docid="LA042689-0146" num="69" wdcount="4"> Miss Ball died today.</s>

<s docid="LA042689-0146" num="70" wdcount="20"> United Press International; Photo, Lucille Ball with co-stars Desi Arnaz, Vivian Vance and William Frawley in "I Love Lucy" scene.</s>

<s docid="LA042689-0146" num="71" wdcount="9"> With Miss Ball's death today, all four are dead.</s>

<s docid="LA042689-0146" num="72" wdcount="26"> Associated Press; Photo, Below, she is shown with two children, Desi Arnaz Jr. and Lucie, and second husband Gary Morton at a 1984 Variety Club fete.</s>

<s docid="LA042689-0146" num="73" wdcount="5"> Photo, Lucille Ball in 1968</s>
</P>
</GRAPHIC>
<TYPE>
<P>

<s docid="LA042689-0146" num="74" wdcount="2"> Obituary; Wire</s>
</P>
</TYPE>
</DOC>
