<DOC>
<DOCNO>

<s docid="LA042789-0025" num="1" wdcount="1"> LA042789-0025</s>
</DOCNO>
<DOCID>

<s docid="LA042789-0025" num="2" wdcount="1"> 49311</s>
</DOCID>
<DATE>
<P>

<s docid="LA042789-0025" num="3" wdcount="6"> April 27, 1989, Thursday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA042789-0025" num="4" wdcount="8"> Part 1; Page 1; Column 2; Metro Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA042789-0025" num="5" wdcount="2"> 2861 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA042789-0025" num="6" wdcount="8"> LUCILLE BALL DIES; TV'S COMIC GENIUS WAS 77;</s>
</P>
<P>

<s docid="LA042789-0025" num="7" wdcount="14"> DEATH CAUSED BY RUPTURED ABDOMINAL AORTA AS SHE APPEARED TO BE RECOVERING FROM SURGERY</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA042789-0025" num="8" wdcount="6"> By ROXANE ARNOLD, Times Staff Writer</s>
</P>
</BYLINE>
<TEXT>
<P>

<s docid="LA042789-0025" num="9" wdcount="34"> Lucille Ball, the leggy showgirl, model and B-grade movie queen whose pumpkin hair and genius for comedy made her an icon of television, died early Wednesday, a week after undergoing emergency heart surgery .</s>
</P>
<P>

<s docid="LA042789-0025" num="10" wdcount="40"> The co-creator and star of "I Love Lucy," a product of TV's Golden Age that continues via syndication to be viewed by millions around the world, was 77 and died at Cedars-Sinai Medical Center of a ruptured abdominal aorta .</s>
</P>
<P>

<s docid="LA042789-0025" num="11" wdcount="52"> Known simply as "Lucy" to four decades of smitten television fans, she had undergone surgery at Cedars-Sinai on April 18 to replace part of her aorta and aortic valve and had recovered from the 6 1/2-hour operation to a point where she was eating and even walking around her hospital room .</s>
</P>
<P>

<s docid="LA042789-0025" num="12" wdcount="26"> Hospital spokesman Ronald Wise said the rupture occurred in a portion of the aorta, the main heart artery, far from where the operation was performed .</s>
</P>
<P>

<s docid="LA042789-0025" num="13" wdcount="19"> She suffered a complete heart failure at 5 a.m., and 47 minutes of resuscitation efforts proved fruitless, Wise said.</s>

<s docid="LA042789-0025" num="14" wdcount="10"> "There was nothing to indicate this would happen," Wise said.</s>

<s docid="LA042789-0025" num="15" wdcount="13"> "The heart itself apparently was not involved in Miss Ball's sudden death" .</s>
</P>
<P>

<s docid="LA042789-0025" num="16" wdcount="21"> Since last week's surgery, fans had flooded the hospital with thousands of get-well cards, sent via telegram and even facsimile machine.</s>

<s docid="LA042789-0025" num="17" wdcount="13"> Hospital officials said it was the largest outpouring they had ever seen .</s>
</P>
<P>

<s docid="LA042789-0025" num="18" wdcount="33"> Miss Ball was a tough-talking woman who had used her stardom and show business savvy to become, with her then-husband, the late Desi Arnaz, head of one of Hollywood's major studios, Desilu .</s>
</P>
<P>

<s docid="LA042789-0025" num="19" wdcount="12"> Despite her business acumen, she remained the unquestioned queen of television comedy.</s>

<s docid="LA042789-0025" num="20" wdcount="41"> From her star-struck childhood through her struggles as a wisecracking movie actress in the 1930s and '40s to the television career that made her a legend, Miss Ball's life was in the best show business tradition of rags to riches .</s>
</P>
<P>

<s docid="LA042789-0025" num="21" wdcount="27"> Almost humbly, she liked to say she owed her enormous success, not so much to talent, but to a magical combination of guts and good supporting players.</s>

<s docid="LA042789-0025" num="22" wdcount="34"> Her greatest achievements, she always would add, were not any milestones in her career but ranked somewhere under the birth of her two children, Lucie in 1951 and Desi Jr., two years later .</s>
</P>
<P>

<s docid="LA042789-0025" num="23" wdcount="14"> "I am not funny," Ball told an interviewer for Rolling Stone magazine in 1983.</s>

<s docid="LA042789-0025" num="24" wdcount="4"> "My writers were funny.</s>

<s docid="LA042789-0025" num="25" wdcount="4"> My directors were funny.</s>

<s docid="LA042789-0025" num="26" wdcount="4"> The situations were funny.</s>

<s docid="LA042789-0025" num="27" wdcount="8"> . . . What I am is brave.</s>

<s docid="LA042789-0025" num="28" wdcount="5"> I have never been scared.</s>

<s docid="LA042789-0025" num="29" wdcount="21"> Not when I did movies, certainly not when I was a model and not when I did "I Love Lucy" .</s>
</P>
<P>

<s docid="LA042789-0025" num="30" wdcount="22"> It was "I Love Lucy," which premiered on CBS on Oct. 15, 1951, that earned Miss Ball her niche in television history.</s>

<s docid="LA042789-0025" num="31" wdcount="20"> The 30-minute comedy starred Miss Ball and the Cuban-born Arnaz as the wacky Lucy Ricardo and her conga-playing husband Ricky.</s>

<s docid="LA042789-0025" num="32" wdcount="23"> The show was a weekly dash into absurdity that boasted the biggest television audience of its time -- of almost any time .</s>
</P>
<P>
</P>
<P>

<s docid="LA042789-0025" num="33" wdcount="3"> Stopped the Nation</s>
</P>
<P>

<s docid="LA042789-0025" num="34" wdcount="28"> In creating the show, Miss Ball and Arnaz -- who died in 1986 -- set a pattern of television that was to be repeated in decades to come.</s>

<s docid="LA042789-0025" num="35" wdcount="22"> They filmed the programs in front of a live audience and in doing so, invented the popular and financially rewarding rerun .</s>
</P>
<P>

<s docid="LA042789-0025" num="36" wdcount="23"> The show was so popular during the 1950s that it literally stopped the nation every Monday night from 9 p.m. to 9:30 p.m.</s>

<s docid="LA042789-0025" num="37" wdcount="38"> In fact, nighttime shoppers became so scarce in Chicago that the mammoth Marshall Field department store posted a sign that read: "We Love Lucy, too, so from now on we will be open Thursday night instead of Monday".</s>

<s docid="LA042789-0025" num="38" wdcount="21"> When presidential candidate Adlai E. Stevenson interrupted the show once for a political message, he was flooded with angry mail .</s>
</P>
<P>

<s docid="LA042789-0025" num="39" wdcount="23"> Even a charge that Miss Ball was a Communist, made by the House Un-American Activities Committee in 1952, failed to dent her popularity.</s>

<s docid="LA042789-0025" num="40" wdcount="29"> The charges, based on her registering to vote as a Communist in 1936, were dropped when Miss Ball explained she had done so only to please her ailing grandfather.</s>

<s docid="LA042789-0025" num="41" wdcount="10"> Millions of sympathetic fans and a pragmatic CBS understood .</s>
</P>
<P>

<s docid="LA042789-0025" num="42" wdcount="18"> A phenomenal 40 million viewers watched the antics each week as Lucy would always try to outwit Ricky.</s>

<s docid="LA042789-0025" num="43" wdcount="37"> With their best friends and landlords, Fred and Ethel Mertz, played by veterans William Frawley and Vivian Vance as the perfect foils, the Ricardos found themselves mired in situations that frequently were rowdy and always ridiculous .</s>
</P>
<P>

<s docid="LA042789-0025" num="44" wdcount="17"> A generation of Americans grew to recap their favorite Lucy episodes, plot twist by crazy twist .</s>
</P>
<P>

<s docid="LA042789-0025" num="45" wdcount="34"> There was the time Lucy schemed her way onto Ricky's television show to do a commercial for a vegetable drink with a high alcoholic content and got hilariously tipsy during the many retakes .</s>
</P>
<P>

<s docid="LA042789-0025" num="46" wdcount="32"> Then there was the time she threw in two packages of yeast while baking homemade bread and ended up pinned against the wall of her Manhattan kitchen by a monster loaf .</s>
</P>
<P>

<s docid="LA042789-0025" num="47" wdcount="40"> And there was the time Lucy and Ethel, trying to impress their New York friends with the ultimate souvenir from a trip to Hollywood, pried loose the cement block containing John Wayne's footprints from in front of Grauman's Chinese Theater.</s>

<s docid="LA042789-0025" num="48" wdcount="6"> Of course, the block broke .</s>
</P>
<P>

<s docid="LA042789-0025" num="49" wdcount="32"> Week after week, Lucy would find herself trapped in a vat of laundry starch, locked in a meat freezer, or lost on a subway with a loving cup stuck on her head.</s>

<s docid="LA042789-0025" num="50" wdcount="15"> Her turmoils permanently positioned her in the hearts of most Americans, including the critics .</s>
</P>
<P>

<s docid="LA042789-0025" num="51" wdcount="22"> "An extraordinary discipline and intuitive understanding of farce give 'I Love Lucy' an engaging lilt," wrote New York Times critic Jack Gould.</s>

<s docid="LA042789-0025" num="52" wdcount="19"> In its Lucy cover story, Time magazine said: "This is the sort of cheerful rowdiness that has been rare.</s>

<s docid="LA042789-0025" num="53" wdcount="14"> . . . Lucille submits enthusiastically to being hit with pies; falls over furniture.</s>

<s docid="LA042789-0025" num="54" wdcount="30"> . . . Tricked out as a ballerina or a Hindu maharani or a toothless hillbilly, she takes her assorted lumps and pratfalls with unflagging zest and good humor" .</s>
</P>
<P>

<s docid="LA042789-0025" num="55" wdcount="15"> In a 1981 interview in The Times, even Miss Ball admitted, "I love Lucy" .</s>
</P>
<P>

<s docid="LA042789-0025" num="56" wdcount="10"> "There were two key qualities to her," the comedienne said.</s>

<s docid="LA042789-0025" num="57" wdcount="33"> "She was always in financial trouble -- if she wanted a fur collar, a ratty little fur collar, she had to figure out a way to make some extra money to get it.</s>

<s docid="LA042789-0025" num="58" wdcount="6"> . . . God, that's universal.</s>

<s docid="LA042789-0025" num="59" wdcount="9"> And she always had a domineering figure over her.</s>

<s docid="LA042789-0025" num="60" wdcount="12"> . . . Lucy was forever knocking somebody's top hat off" .</s>
</P>
<P>

<s docid="LA042789-0025" num="61" wdcount="14"> Miss Ball's personal favorite episodes were filmed when she was pregnant with Desi Jr.</s>

<s docid="LA042789-0025" num="62" wdcount="27"> An amazing 44 million viewers, 90% of the television audience, gleefully watched on Jan. 19, 1953, when she gave birth on film to the show's little Ricky.</s>

<s docid="LA042789-0025" num="63" wdcount="20"> To the unabashed delight of a nation, it was the same night she had given birth in real life .</s>
</P>
<P>

<s docid="LA042789-0025" num="64" wdcount="26"> "I was so damned happy -- just floating on a cloud -- and I think the way I felt came across on the film," she said.</s>

<s docid="LA042789-0025" num="65" wdcount="8"> "I loved doing all those pregnant shows" .</s>
</P>
<P>

<s docid="LA042789-0025" num="66" wdcount="21"> Astoundingly, or so it seems in retrospect, early reviews of Miss Ball's talents gave little hint of what was to come.</s>

<s docid="LA042789-0025" num="67" wdcount="26"> In fact, when she was a plucky 15-year-old looking for that first break on Broadway, Miss Ball was told by a drama teacher to give up.</s>

<s docid="LA042789-0025" num="68" wdcount="8"> Luckily, the turquoise-eyed teen-ager ignored the advice .</s>
</P>
<P>

<s docid="LA042789-0025" num="69" wdcount="30"> Born to an electrician father and pianist mother on Aug. 6, 1911, in a suburb of Jamestown, N.Y., Miss Ball had set her sights on stardom almost from the first.</s>

<s docid="LA042789-0025" num="70" wdcount="10"> By 5, the brown-haired little girl was taking music lessons.</s>

<s docid="LA042789-0025" num="71" wdcount="23"> Each spring that followed she would head toward New York City, walking until someone found her and returned her to her home .</s>
</P>
<P>

<s docid="LA042789-0025" num="72" wdcount="19"> Leaving school at 15, Miss Ball finally made it to New York and the John Murray Anderson dramatic school.</s>

<s docid="LA042789-0025" num="73" wdcount="23"> There was a brief stint in a Ziegfeld Follies road show and some short-lived appearances in a handful of Broadway chorus lines .</s>
</P>
<P>

<s docid="LA042789-0025" num="74" wdcount="32"> Changing her name to Diane Belmont ("I always loved the name Diane and I was driving past the Belmont race track, and the names seemed to fit together") she turned to modeling.</s>

<s docid="LA042789-0025" num="75" wdcount="29"> At various times a dress model and a hat model, Miss Ball, with long legs peeking out the bottom of a oversized cigarette pack, ultimately became a "Chesterfield girl".</s>

<s docid="LA042789-0025" num="76" wdcount="17"> America grew to know her on billboards, magazine ads and on posters in its drugstore windows .</s>
</P>
<P>

<s docid="LA042789-0025" num="77" wdcount="7"> Then in 1933, she headed to Hollywood.</s>

<s docid="LA042789-0025" num="78" wdcount="25"> Her curly hair bleached a Jean Harlow platinum, Miss Ball was hired to work for six weeks in the chorus of Samuel Goldwyn's "Roman Scandals".</s>

<s docid="LA042789-0025" num="79" wdcount="40"> Bit part after bit part stretched her stay to six months and she became a Hollywood fixture, taking second billing in the years that followed to everyone from The Three Stooges and Buster Keaton to Katharine Hepburn and Spencer Tracy.</s>

<s docid="LA042789-0025" num="80" wdcount="22"> Along the way, she dyed her hair a fiery red and was given the unofficial title of "Queen of the Bs" .</s>
</P>
<P>

<s docid="LA042789-0025" num="81" wdcount="11"> Reviewers noted her "pert presence" and talent for "rubber-faced slapstick clowning".</s>

<s docid="LA042789-0025" num="82" wdcount="19"> She was described in one newspaper as a "slangy, breezy wisecracking gal with a bebop rhythm to her walk".</s>

<s docid="LA042789-0025" num="83" wdcount="18"> Said another, "Pretty Lucille Ball . . . was born for the parts Ginger Rogers sweats over" .</s>
</P>
<P>

<s docid="LA042789-0025" num="84" wdcount="23"> Playing the ingenue lead in the 1940 musical "Too Many Girls," Miss Ball met rumba singer Arnaz, cast as a Cuban football player.</s>

<s docid="LA042789-0025" num="85" wdcount="17"> She later told an interviewer, "It was, at least for me, true love from the start" .</s>
</P>
<P>

<s docid="LA042789-0025" num="86" wdcount="17"> Exchanging vows seven months later, the pair began what was for the most part a troubled marriage.</s>

<s docid="LA042789-0025" num="87" wdcount="13"> All but three of their first 11 years of marriage were spent apart.</s>

<s docid="LA042789-0025" num="88" wdcount="28"> With Arnaz traveling the country with his band and Miss Ball committed to Hollywood sound stages, the pair spent almost $30,000 on telegrams and long-distance telephone calls .</s>
</P>
<P>

<s docid="LA042789-0025" num="89" wdcount="18"> "We would end up talking on the phone -- no, fighting on the phone," Miss Ball told interviewers.</s>

<s docid="LA042789-0025" num="90" wdcount="8"> "You can't have a marriage over the phone.</s>

<s docid="LA042789-0025" num="91" wdcount="7"> You can't have children over the phone.</s>

<s docid="LA042789-0025" num="92" wdcount="10"> It became obvious that something had to be done" .</s>
</P>
<P>

<s docid="LA042789-0025" num="93" wdcount="12"> What was done to salvage the marriage was "I Love Lucy" .</s>
</P>
<P>

<s docid="LA042789-0025" num="94" wdcount="39"> Since CBS was stubbornly opposed to the idea of the heavily accented Arnaz playing the husband, the determined Arnazes created their own Desilu company and took a stage version of their show on the road to gauge public opinion.</s>

<s docid="LA042789-0025" num="95" wdcount="16"> It was a smash, and television executives reluctantly gave "I Love Lucy" a time slot .</s>
</P>
<P>

<s docid="LA042789-0025" num="96" wdcount="16"> "I wanted our characters to have problems," Miss Ball said of her concept for the show.</s>

<s docid="LA042789-0025" num="97" wdcount="7"> "I wanted to be an average housewife.</s>

<s docid="LA042789-0025" num="98" wdcount="7"> A very nosy but very average housewife.</s>

<s docid="LA042789-0025" num="99" wdcount="9"> And I wanted my husband to love me .</s>
</P>
<P>

<s docid="LA042789-0025" num="100" wdcount="16"> "CBS thought we were out of our minds to want to do it on film" .</s>
</P>
<P>

<s docid="LA042789-0025" num="101" wdcount="28"> The episodes were filmed before a live audience by Academy Award-winning cinematographer Karl Freund, famous for his work on such films as "The Good Earth" and Garbo's "Camille".</s>

<s docid="LA042789-0025" num="102" wdcount="22"> When the Arnazes negotiated to keep the films "to show our kids someday," few in the industry predicted what would happen .</s>
</P>
<P>

<s docid="LA042789-0025" num="103" wdcount="17"> "I remember (someone) saying, 'These films may be worth something someday,' " Miss Ball told The Times.</s>

<s docid="LA042789-0025" num="104" wdcount="5"> "You should hang onto them.</s>

<s docid="LA042789-0025" num="105" wdcount="10"> If Desi had that in mind, I never knew it.</s>

<s docid="LA042789-0025" num="106" wdcount="15"> Maybe he knew he was creating the rerun but he never told me about it.</s>

<s docid="LA042789-0025" num="107" wdcount="30"> All I knew was I was 40 years old and was having my first baby and I didn't want to do these shows and let them disappear into the air.</s>

<s docid="LA042789-0025" num="108" wdcount="10"> I felt we could save the films for home movies.</s>

<s docid="LA042789-0025" num="109" wdcount="4"> . . " .</s>
</P>
<P>

<s docid="LA042789-0025" num="110" wdcount="35"> Instead, in the years since the original 153 "I Love Lucy" episodes were telecast, they have been shown and reshown in virtually every country around the globe, earning an estimated $50 million to $100 million.</s>

<s docid="LA042789-0025" num="111" wdcount="12"> Miss Ball's face was one of the most recognized on Earth .</s>
</P>
<P>

<s docid="LA042789-0025" num="112" wdcount="12"> But all of it was not enough to save her troubled marriage.</s>

<s docid="LA042789-0025" num="113" wdcount="16"> To the horror of their television fans, Miss Ball and Arnaz were divorced in 1960 .</s>
</P>
<P>

<s docid="LA042789-0025" num="114" wdcount="11"> "He (Arnaz) was like Jekyll and Hyde," she said years later.</s>

<s docid="LA042789-0025" num="115" wdcount="12"> "He drank and he gambled and he went around with other women.</s>

<s docid="LA042789-0025" num="116" wdcount="9"> It was always the same: booze and broads" .</s>
</P>
<P>

<s docid="LA042789-0025" num="117" wdcount="19"> Breaking with the past, Miss Ball left Hollywood for New York and a starring role in the musical "Wildcat".</s>

<s docid="LA042789-0025" num="118" wdcount="22"> The 1960 production floundered after only a few performances but during her stay in the East, she met stand-up comedian Gary Morton.</s>

<s docid="LA042789-0025" num="119" wdcount="5"> They married in 1961 .</s>
</P>
<P>

<s docid="LA042789-0025" num="120" wdcount="36"> Meanwhile, Arnaz and Miss Ball had sold their "I Love Lucy" films to CBS for $6 million and she bought her ex-husband's interest in Desilu, becoming in effect, the first woman to head a major studio.</s>

<s docid="LA042789-0025" num="121" wdcount="19"> It was by then home to 18 shows, including such hits as "The Untouchables" and "The Ann Sothern Show".</s>

<s docid="LA042789-0025" num="122" wdcount="9"> Friend Bob Hope called her business sense "startling" .</s>
</P>
<P>

<s docid="LA042789-0025" num="123" wdcount="34"> "I never wanted to be an executive, but when my marriage to Desi broke up after 19 years, I couldn't just walk away from my obligations and say 'forget it,' " Miss Ball explained.</s>

<s docid="LA042789-0025" num="124" wdcount="4"> "We were an institution.</s>

<s docid="LA042789-0025" num="125" wdcount="3"> Life takes guts.</s>

<s docid="LA042789-0025" num="126" wdcount="16"> If you don't take chances, you'll never bathe again because you might get dirty again" .</s>
</P>
<P>

<s docid="LA042789-0025" num="127" wdcount="13"> Husband Morton said Miss Ball was blessed with an "innate business sense" .</s>
</P>
<P>

<s docid="LA042789-0025" num="128" wdcount="40"> "When she was running Desilu," he said, "she made decisions affecting the future of the company that often amazed board members, not because they were coming from a woman but because time usually proved her judgment to be correct" .</s>
</P>
<P>

<s docid="LA042789-0025" num="129" wdcount="29"> Among the shows Miss Ball tutored to success was her own "The Lucy Show," a series without Arnaz but with the same madcap clowning that kept her fans delighted.</s>

<s docid="LA042789-0025" num="130" wdcount="22"> Among the guest stars attracted by the madness were Elizabeth Taylor and Richard Burton, the most glittering couple of the day .</s>
</P>
<P>

<s docid="LA042789-0025" num="131" wdcount="29"> In 1967, with Desilu churning out a gold mine of televisions hits, "Star Trek" and "Mission: Impossible" among them, an exhausted Miss Ball decided that she had had enough.</s>

<s docid="LA042789-0025" num="132" wdcount="13"> Gulf & Western Industries bought the property for a reported $17 million .</s>
</P>
<P>

<s docid="LA042789-0025" num="133" wdcount="32"> In place of Desilu, Miss Ball, along with Morton, launched the much smaller Lucille Ball Productions Inc. and in 1968, began filming "Here's Lucy," a series featuring Desi Jr. and Lucie .</s>
</P>
<P>

<s docid="LA042789-0025" num="134" wdcount="14"> "My life started when my children were born," Miss Ball said at the time.</s>

<s docid="LA042789-0025" num="135" wdcount="7"> "I couldn't wait to work with them.</s>

<s docid="LA042789-0025" num="136" wdcount="18"> . . . Even when they moved out of the house, they were still home at the studio.</s>

<s docid="LA042789-0025" num="137" wdcount="4"> I liked that" .</s>
</P>
<P>

<s docid="LA042789-0025" num="138" wdcount="5"> The series aired through 1974.</s>

<s docid="LA042789-0025" num="139" wdcount="21"> With her children's careers off the launching pad, the comedienne, then 63, decided it was time to retire her legendary character.</s>

<s docid="LA042789-0025" num="140" wdcount="17"> "The Lucy character is too old to run around like an idiot," she said in explanation .</s>
</P>
<P>

<s docid="LA042789-0025" num="141" wdcount="16"> That same year, she filmed her final motion picture, "Mame," a version of the Broadway musical.</s>

<s docid="LA042789-0025" num="142" wdcount="18"> Although by now the world's best-known television star, as a movie star Miss Ball again received mixed reviews.</s>

<s docid="LA042789-0025" num="143" wdcount="21"> Times critic Charles Champlin wrote, "The shame about 'Mame' is that it managed to deny us a Lucy to love" .</s>
</P>
<P>

<s docid="LA042789-0025" num="144" wdcount="31"> With those final starring credits to her name, she settled into co-producing shows, making occasional television appearances and accepting one after another of a continual barrage of awards and tributes .</s>
</P>
<P>

<s docid="LA042789-0025" num="145" wdcount="29"> In addition to her 13 Emmy nominations (she won four), Miss Ball was feted in 1976 with a nostalgic television tribute saluting the 25th anniversary of "I Love Lucy".</s>

<s docid="LA042789-0025" num="146" wdcount="14"> Danny Kaye was among those who gave testimonials during the two hours of reminiscing.</s>

<s docid="LA042789-0025" num="147" wdcount="17"> "Calling Lucille Ball just a comedienne is like calling Margot Fonteyn just a dancer," Kaye said .</s>
</P>
<P>

<s docid="LA042789-0025" num="148" wdcount="32"> In 1984, when she was named one of seven initial inductees in the Television Hall of Fame, she credited the many "talented and creative people" around her for making her a legend.</s>

<s docid="LA042789-0025" num="149" wdcount="9"> "I have been absolutely blessed," Miss Ball said .</s>
</P>
<P>
</P>
<P>

<s docid="LA042789-0025" num="150" wdcount="4"> Role as Bag Lady</s>
</P>
<P>

<s docid="LA042789-0025" num="151" wdcount="24"> The following year she took on one of the most challenging roles of her career: a bag lady in the television movie "Stone Pillow".</s>

<s docid="LA042789-0025" num="152" wdcount="18"> She was hospitalized for dehydration when it was over, but it was a critical and ratings success .</s>
</P>
<P>

<s docid="LA042789-0025" num="153" wdcount="26"> Her last flirtation with television came with her ill-fated and short-lived 1986 series, "Life With Lucy," in which she again teamed with longtime sidekick Gale Gordon.</s>

<s docid="LA042789-0025" num="154" wdcount="12"> It was quickly pulled by the network because of abysmal ratings .</s>
</P>
<P>

<s docid="LA042789-0025" num="155" wdcount="28"> Her final public appearance proved to be during the 61st annual Academy Awards ceremony on March 29 when she joined her old friend Hope as a presenter .</s>
</P>
<P>

<s docid="LA042789-0025" num="156" wdcount="21"> She had signed a contract with Putnam to publish her autobiography but died before she could begin work on it .</s>
</P>
<P>

<s docid="LA042789-0025" num="157" wdcount="25"> Tearfully sentimental when it came to her husband and family, she reveled in life as a grandmother and glowed whenever she talked of her children.</s>

<s docid="LA042789-0025" num="158" wdcount="10"> Their struggles and early failed marriages seemed not to matter.</s>

<s docid="LA042789-0025" num="159" wdcount="20"> While she always spoke fondly of Arnaz, Miss Ball claimed that she had found the perfect mate in Morton .</s>
</P>
<P>

<s docid="LA042789-0025" num="160" wdcount="17"> "He (Morton) takes care of me like I was his mother," she told an interviewer in 1981.</s>

<s docid="LA042789-0025" num="161" wdcount="4"> "Gary gives me protection".</s>

<s docid="LA042789-0025" num="162" wdcount="19"> On a scale of 1 to 10, Miss Ball said, "I rate my marriage to Gary a 12" .</s>
</P>
<P>

<s docid="LA042789-0025" num="163" wdcount="39"> But to her countless television fans -- from the postwar babies who adored her during the '50s to their children and children's children who roared at her antics through decades of reruns -- it was always Lucy and Ricky.</s>

<s docid="LA042789-0025" num="164" wdcount="12"> More than a quarter-century of marriage to Morton could not erase that.</s>

<s docid="LA042789-0025" num="165" wdcount="21"> There was always the hilarious image of the redhead and "that Cuban bongo player," as Miss Ball affectionately called him .</s>
</P>
<P>

<s docid="LA042789-0025" num="166" wdcount="16"> Even years after the Lucy shows ended, the comedienne openly admitted to missing the characterization .</s>
</P>
<P>

<s docid="LA042789-0025" num="167" wdcount="19"> "After Lucy ended, I thought, 'I'll live a few more years and then I'll die," she said in 1983.</s>

<s docid="LA042789-0025" num="168" wdcount="7"> "I didn't plan on living this long.</s>

<s docid="LA042789-0025" num="169" wdcount="7"> . . . Now I miss her.</s>

<s docid="LA042789-0025" num="170" wdcount="4"> . . " .</s>
</P>
<P>

<s docid="LA042789-0025" num="171" wdcount="8"> Related Stories: Page 3 and Calendar, Page 1</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA042789-0025" num="172" wdcount="23"> Photo, Ana Martinez Holler of the Hollywood Chamber of Commerce places memorial card under floral arrangement at Lucille Ball's star on Hollywood Boulevard.</s>

<s docid="LA042789-0025" num="173" wdcount="37"> KEN LUBAS / Los Angeles Times; Photo, Lucille Ball and Desi Arnaz reading a telegram from a well-wisher at their Chatsworth home in 1953, and the comedienne as she looked in, from left, 1942, '66 and '79.</s>

<s docid="LA042789-0025" num="174" wdcount="3"> Los Angeles Times</s>
</P>
</GRAPHIC>
<TYPE>
<P>

<s docid="LA042789-0025" num="175" wdcount="2"> Profile; Obituary</s>
</P>
</TYPE>
<SUBJECT>
<P>

<s docid="LA042789-0025" num="176" wdcount="4"> BALL, LUCILLE; ACTRESSES; COMEDIANS</s>
</P>
</SUBJECT>
</DOC>
