<DOC>
<DOCNO>

<s docid="FT923-6455" num="1" wdcount="1"> FT923-6455</s>
</DOCNO>
<PROFILE>

<s docid="FT923-6455" num="2" wdcount="1"> _AN-CHZBXAACFT</s>
</PROFILE>
<DATE>

<s docid="FT923-6455" num="3" wdcount="1"> 920825</s>
</DATE>
<HEADLINE>

<s docid="FT923-6455" num="4" wdcount="12"> FT 25 AUG 92 / US insurers face heaviest hurricane damage claims</s>
</HEADLINE>
<BYLINE>

<s docid="FT923-6455" num="5" wdcount="6"> By MARTIN DICKSON and NORMA COHEN</s>
</BYLINE>
<DATELINE>

<s docid="FT923-6455" num="6" wdcount="3"> NEW YORK, LONDON</s>
</DATELINE>
<TEXT>

<s docid="FT923-6455" num="7" wdcount="37"> US CITIES along the Gulf of Mexico from Alabama to eastern Texas were on storm watch last night as Hurricane Andrew headed west after sweeping across southern Florida, causing at least eight deaths and severe property damage.</s>

<s docid="FT923-6455" num="8" wdcount="25"> The hurricane was one of the fiercest in the US in decades and the first to hit Miami directly in a quarter of a century.</s>

<s docid="FT923-6455" num="9" wdcount="18"> In the Bahamas, government spokesman Mr Jimmy Curry said four deaths had been reported on outlying eastern islands.</s>

<s docid="FT923-6455" num="10" wdcount="24"> Mr Justin Balcombe, of UK-based insurance adjuster Balcombe Group, said total losses could exceed Dollars 15bn if business interruption claims were taken into account.</s>

<s docid="FT923-6455" num="11" wdcount="28"> That compares with the Dollars 4bn-Dollars 6n (Pounds 2.1bn-Pounds 3.1bn) of insurance industry losses caused by the last big US hurricane, Hugo, which hit South Carolina in 1989.</s>

<s docid="FT923-6455" num="12" wdcount="17"> The brunt of the losses are likely to be concentrated among US insurers, industry analysts said yesterday.</s>

<s docid="FT923-6455" num="13" wdcount="25"> Mr George Lloyd-Roberts, chairman of Lloyd's Underwriters' Non-Marine Association, said that, unless damage claims exceeded Pounds 3bn, the Lloyd's insurance market would feel little impact.</s>

<s docid="FT923-6455" num="14" wdcount="30"> Because the reinsurance of reinsurance risk - known as the retrocession market - has shrunk considerably in recent years, US insurers have placed far fewer of their risks through Lloyd's.</s>

<s docid="FT923-6455" num="15" wdcount="26"> Mr Roger Hill, insurance analyst at Warburg Securities, said he estimated that mainline UK insurers faced no more than Pounds 75m in damage claims so far.</s>

<s docid="FT923-6455" num="16" wdcount="10"> 'At the moment we are relaxed about it,' he said.</s>

<s docid="FT923-6455" num="17" wdcount="15"> The real question, he added, is the level of reinsurance available to the UK underwriters.</s>

<s docid="FT923-6455" num="18" wdcount="12"> Royal Insurance estimated the company's losses at no more than Pounds 20m.</s>

<s docid="FT923-6455" num="19" wdcount="34"> Among other UK insurers, Mr Hill estimated that General Accident may face losses of up to Pounds 30m, while Guardian Royal Exchange faced Pounds 5m and Sun Alliance and Commercial Union Pounds 10m each.</s>

<s docid="FT923-6455" num="20" wdcount="38"> However, Hurricane Andrew gathered fresh strength as it moved across the Gulf of Mexico and there was concern last night that it might head towards New Orleans, which is especially low lying and could suffer severe flood damage.</s>

<s docid="FT923-6455" num="21" wdcount="24"> Scientists said the storm could make landfall anywhere between the Alabama port of Mobile and the Louisiana-Texas border, probably tomorrow night or early Thursday.</s>

<s docid="FT923-6455" num="22" wdcount="16"> It could threaten the large concentration of offshore oil production facilities in the Gulf of Mexico.</s>

<s docid="FT923-6455" num="23" wdcount="16"> Shell Oil was evacuating most of the 900 workers on its offshore platforms as a precaution.</s>

<s docid="FT923-6455" num="24" wdcount="32"> A substantial part of America's oil refining industry is concentrated on the Gulf coast, in Louisiana and Texas, and officials there were reviewing emergency plans to curtail or shut down plant operations.</s>

<s docid="FT923-6455" num="25" wdcount="20"> Andrew, the first Caribbean hurricane of the season, hit the eastern coast of Florida early yesterday, gusting up to 165mph.</s>

<s docid="FT923-6455" num="26" wdcount="21"> It ripped roofs off houses, smashed cars and trucks, snapped power lines and uprooted trees before heading out over the Gulf.</s>

<s docid="FT923-6455" num="27" wdcount="23"> A million people had been ordered to flee their homes in southern Florida as the hurricane moved in from the Bahamas on Sunday.</s>

<s docid="FT923-6455" num="28" wdcount="20"> The Florida Power and Light company said that about 1.2m of its customers, or 32 per cent, were without power.</s>

<s docid="FT923-6455" num="29" wdcount="24"> Some of the strongest winds were in the affluent suburb of Coral Gables, just south of Miami, where the National Hurricane Center is located.</s>

<s docid="FT923-6455" num="30" wdcount="8"> Its radar and satellite antennae were blown away.</s>

<s docid="FT923-6455" num="31" wdcount="20"> President Bush authorised federal disaster assistance for the affected areas and made plans for an inspection tour of the state.</s>

<s docid="FT923-6455" num="32" wdcount="3"> Picture, Page 14</s>
</TEXT>
<PUB>

<s docid="FT923-6455" num="33" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT923-6455" num="34" wdcount="3"> London Page 1</s>
</PAGE>
</DOC>
