<DOC>
<DOCNO>

<s docid="FT923-6038" num="1" wdcount="1"> FT923-6038</s>
</DOCNO>
<PROFILE>

<s docid="FT923-6038" num="2" wdcount="1"> _AN-CH1BVABKFT</s>
</PROFILE>
<DATE>

<s docid="FT923-6038" num="3" wdcount="1"> 920827</s>
</DATE>
<HEADLINE>

<s docid="FT923-6038" num="4" wdcount="14"> FT 27 AUG 92 / Hurricane batters southern US but lets insurers off lightly</s>
</HEADLINE>
<BYLINE>

<s docid="FT923-6038" num="5" wdcount="6"> By MARTIN DICKSON and ROBERT PESTON</s>
</BYLINE>
<DATELINE>

<s docid="FT923-6038" num="6" wdcount="3"> NEW YORK, LONDON</s>
</DATELINE>
<TEXT>

<s docid="FT923-6038" num="7" wdcount="36"> HURRICANE Andrew, claimed to be the costliest natural disaster in US history, yesterday smashed its way through the state of Louisiana, inflicting severe damage on rural communities but narrowly missing the low-lying city of New Orleans.</s>

<s docid="FT923-6038" num="8" wdcount="38"> The storm, which brought havoc to southern Florida on Monday and then headed north-west across the Gulf of Mexico, had made landfall late on Tuesday night some 60 miles south-west of the city in the agricultural Cajun country.</s>

<s docid="FT923-6038" num="9" wdcount="42"> Although the damage from the hurricane's landfall in Florida on Monday was much greater than initially esti mated, insurers' losses there are likely to total less than Dollars 1bn, well below earlier expectations, a senior member of Lloyd's insurance market said yesterday.</s>

<s docid="FT923-6038" num="10" wdcount="30"> In Louisiana, the hurricane landed with wind speeds of about 120 miles per hour and caused severe damage in small coastal centres such as Morgan City, Franklin and New Iberia.</s>

<s docid="FT923-6038" num="11" wdcount="10"> Associated tornadoes devastated Laplace, 20 miles west of New Orleans.</s>

<s docid="FT923-6038" num="12" wdcount="11"> Then, however, Andrew lost force as it moved north over land.</s>

<s docid="FT923-6038" num="13" wdcount="19"> By yesterday afternoon, it had been down-graded to tropical storm, in that its sustained windspeeds were below 75 mph.</s>

<s docid="FT923-6038" num="14" wdcount="31"> Initial reports said at least one person had died, 75 been injured and thousands made homeless along the Louisiana coast, after 14 confirmed deaths in Florida and three in the Bahamas.</s>

<s docid="FT923-6038" num="15" wdcount="21"> The storm caused little damage to Louisiana's important oil-refining industry, although some plants had to halt production when electricity was cut.</s>

<s docid="FT923-6038" num="16" wdcount="20"> The Lloyd's member, in close contact with leading insurers in Florida, said that damage to insured property was remarkably small.</s>

<s docid="FT923-6038" num="17" wdcount="20"> More than Dollars 15bn of damage may have been caused in all, but was mostly to uninsured property, he said.</s>

<s docid="FT923-6038" num="18" wdcount="6"> In north Miami, damage is minimal.</s>

<s docid="FT923-6038" num="19" wdcount="9"> Worst affected is one hotel, whose basement was flooded.</s>

<s docid="FT923-6038" num="20" wdcount="29"> Most of the destruction occurred in a 10-mile band across Homestead, 25 miles to the south of Miami, where a typical house sells for Dollars 100,000 to Dollars 150,000.</s>

<s docid="FT923-6038" num="21" wdcount="17"> US insurers will face a bill in respect of such properties, but Lloyd's exposure there is minimal.</s>

<s docid="FT923-6038" num="22" wdcount="19"> Many destroyed power lines are thought to be uninsured, as are trees and shrubs uprooted across a wide area.</s>

<s docid="FT923-6038" num="23" wdcount="14"> Only one big hotel in that area has been badly damaged, a Holiday Inn.</s>

<s docid="FT923-6038" num="24" wdcount="24"> Across Florida, some 2m people remained without electric ity yesterday and health officials were warning the public to boil or chemically treat all water.</s>

<s docid="FT923-6038" num="25" wdcount="17"> Hurricane Hugo, which devastated much of South Carolina in 1989, cost the insurance industry some Dollars 4.2bn.</s>

<s docid="FT923-6038" num="26" wdcount="13"> Further uninsured losses may have raised the total to Dollars 6bn-Dollars 10bn .</s>
</TEXT>
<PUB>

<s docid="FT923-6038" num="27" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT923-6038" num="28" wdcount="3"> London Page 6</s>
</PAGE>
</DOC>
