<DOC>
<DOCNO>

<s docid="FT923-5797" num="1" wdcount="1"> FT923-5797</s>
</DOCNO>
<PROFILE>

<s docid="FT923-5797" num="2" wdcount="1"> _AN-CIBBCACSFT</s>
</PROFILE>
<DATE>

<s docid="FT923-5797" num="3" wdcount="1"> 920828</s>
</DATE>
<HEADLINE>

<s docid="FT923-5797" num="4" wdcount="9"> FT 28 AUG 92 / Cleaning up after Andrew</s>
</HEADLINE>
<BYLINE>

<s docid="FT923-5797" num="5" wdcount="2"> By AGENCIES</s>
</BYLINE>
<DATELINE>

<s docid="FT923-5797" num="6" wdcount="3"> FLORIDA, NEW ORLEANS</s>
</DATELINE>
<TEXT>

<s docid="FT923-5797" num="7" wdcount="36"> SQUADS of workers fanned out across storm-battered Louisiana yesterday to begin a massive rebuilding effort after Hurricane Andrew had flattened whole districts, killing two people and injuring dozens more, agencies report from Florida and New Orleans.</s>

<s docid="FT923-5797" num="8" wdcount="35"> However, local officials in Florida, hit earlier in the week by the hurricane, were critical of what they called a delay in supplying food, drinking water and other supplies for thousands of people in need.</s>

<s docid="FT923-5797" num="9" wdcount="31"> Federal emergency officials acknowledged distribution problems, Transportation Secretary Andrew Card yesterday promised 'dramatic' improvements within 24 hours and President George Bush last night ordered troops to Florida, without specifying a number.</s>

<s docid="FT923-5797" num="10" wdcount="24"> The government estimated it would cost Dollars 20bn-Dollars 30bn to tidy and rebuild in Florida, and to care for residents displaced by the storm.</s>

<s docid="FT923-5797" num="11" wdcount="19"> Louisiana state officials said they had no overall count of storm-related injuries but initial estimates reckoned fewer than 100.</s>

<s docid="FT923-5797" num="12" wdcount="16"> The Federal Emergency Management Agency said it was setting aside Dollars 77m to help Louisiana recover.</s>

<s docid="FT923-5797" num="13" wdcount="29"> Most of the storm's fury was spent against sparsely populated farming communities and swampland in the state, sparing it the widespread destruction caused in Florida, where 15 people died.</s>

<s docid="FT923-5797" num="14" wdcount="27"> Official estimates in Miami reported that the hurricane had wiped out the homes of one Dade County resident in eight - a quarter of a million people.</s>

<s docid="FT923-5797" num="15" wdcount="21"> Andrew had become little more than a strong rainstorm early yesterday, moving across Mississippi state and heading for the north-eastern US.</s>

<s docid="FT923-5797" num="16" wdcount="13"> Several of Louisiana's main industries were affected, including those of oysters and alligators.</s>

<s docid="FT923-5797" num="17" wdcount="16"> Wildlife and fisheries secretary Joe Herring estimated a 50 per cent decline in the alligator industry.</s>

<s docid="FT923-5797" num="18" wdcount="12"> The cotton and sugar-cane crops were threatened, the state agriculture department said.</s>

<s docid="FT923-5797" num="19" wdcount="19"> Most Louisiana oil refineries, however, were barely affected and deliveries of crude oil were expected to resume yesterday .</s>
</TEXT>
<PUB>

<s docid="FT923-5797" num="20" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT923-5797" num="21" wdcount="3"> London Page 4</s>
</PAGE>
</DOC>
