<DOC>
<DOCNO>

<s docid="FT923-6110" num="1" wdcount="1"> FT923-6110</s>
</DOCNO>
<PROFILE>

<s docid="FT923-6110" num="2" wdcount="1"> _AN-CH0BVADPFT</s>
</PROFILE>
<DATE>

<s docid="FT923-6110" num="3" wdcount="1"> 920826</s>
</DATE>
<HEADLINE>

<s docid="FT923-6110" num="4" wdcount="18"> FT 26 AUG 92 / Hurricane damage put at Dollars 20bn as 2m people told to leave homes</s>
</HEADLINE>
<BYLINE>

<s docid="FT923-6110" num="5" wdcount="6"> By MARTIN DICKSON and NORMA COHEN</s>
</BYLINE>
<DATELINE>

<s docid="FT923-6110" num="6" wdcount="3"> NEW YORK, LONDON</s>
</DATELINE>
<TEXT>

<s docid="FT923-6110" num="7" wdcount="34"> DAMAGE CAUSED by Hurricane Andrew could rise to Dollars 20bn, it was estimated yesterday, as one of the costliest US storms this century threatened a further devastating landfall near the city of New Orleans.</s>

<s docid="FT923-6110" num="8" wdcount="19"> Government officials in Louisiana, Mississippi and Texas yesterday advised or ordered more than 2m people to evacuate coastal areas.</s>

<s docid="FT923-6110" num="9" wdcount="40"> The hurricane tore through southern Florida early on Monday morning, causing billions of dollars of property damage and at least 12 deaths, and yesterday was moving north-west across the Gulf of Mexico with winds of about 140 miles an hour.</s>

<s docid="FT923-6110" num="10" wdcount="13"> At least three people died on Sunday when Hurricane Andrew crossed the Bahamas.</s>

<s docid="FT923-6110" num="11" wdcount="34"> Ms Kate Hale, director of emergency services in Florida's Dade County, which bore the brunt of the storm, estimated that Andrew had already caused Dollars 15bn to Dollars 20bn (Pounds 7.5bn-Pounds 10bn) of damage.</s>

<s docid="FT923-6110" num="12" wdcount="15"> However, insurance industry analysts cautioned that it was too early to assess the costs accurately.</s>

<s docid="FT923-6110" num="13" wdcount="23"> The US industry's Property Claims Service, the official compiler of disaster losses, had yet to compile a preliminary tally of the Florida bill.</s>

<s docid="FT923-6110" num="14" wdcount="19"> A hurricane warning was in effect yesterday along 470 miles of Gulf coast from Pascagoula, Mississippi, to Galvestone, Texas.</s>

<s docid="FT923-6110" num="15" wdcount="24"> Several forecasting agencies suggested the likeliest landfall was in central Louisiana, to the west of New Orleans, possibly late last night or this morning.</s>

<s docid="FT923-6110" num="16" wdcount="33"> New Orleans, with a population of 1.6m, is particularly vulnerable because the city lies below sea level, has the Mississippi River running through its centre and a large lake immediately to the north.</s>

<s docid="FT923-6110" num="17" wdcount="21"> Much of America's oil refining industry is concentrated along coastal Texas and Louisiana and several refineries were yesterday partially shut down.</s>

<s docid="FT923-6110" num="18" wdcount="9"> These included British Petroleum's Belle Chasse plant in Louisiana.</s>

<s docid="FT923-6110" num="19" wdcount="17"> In Florida, Andrew caused greatest havoc in a largely suburban swathe some 10-15 miles south of Miami.</s>

<s docid="FT923-6110" num="20" wdcount="19"> The town of Homestead, near the centre of the storm, was largely flattened, including a local air force base.</s>

<s docid="FT923-6110" num="21" wdcount="8"> Miami's city centre escaped with relatively light damage.</s>

<s docid="FT923-6110" num="22" wdcount="16"> More than 24 hours after the hurricane, some 825,000 households and businesses were still without power.</s>

<s docid="FT923-6110" num="23" wdcount="35"> The brunt of insurance claims from the Florida storm will fall on the US industry, and companies with a heavy local exposure include the State Farm Group and the Allstate Insurance unit of Sears Roebuck.</s>

<s docid="FT923-6110" num="24" wdcount="17"> These are also the leading property/casualty and home insurance groups in Louisiana, together with American International Group.</s>

<s docid="FT923-6110" num="25" wdcount="20"> A spokesman for State Farm Insurance said he believed the company had roughly 20 per cent of the Florida market.</s>

<s docid="FT923-6110" num="26" wdcount="6"> The mutually-owned company has no reinsurance.</s>

<s docid="FT923-6110" num="27" wdcount="19"> Its size has made obtaining reinsurance cover difficult and its reserves, at about Dollars 24bn, have made it unnecessary.</s>

<s docid="FT923-6110" num="28" wdcount="24"> According to Balcombe Group, a UK-based claims adjustment firm, other insurers with large exposure in the hurricane-hit area are Hartford Insurance, Aetna and Travellers.</s>

<s docid="FT923-6110" num="29" wdcount="18"> Travellers said it had flown 50 claims adjusters in to Florida late on Monday and was assessing losses.</s>

<s docid="FT923-6110" num="30" wdcount="24"> About 12 per cent of Travellers' home insurance premium income came from Florida last year, and 4.6 per cent of its commercial insurance premiums.</s>

<s docid="FT923-6110" num="31" wdcount="35"> The last serious US hurricane, Hugo, which struck South Carolina in 1989, cost the industry Dollars 4.2bn from insured losses, though estimates of the total damage caused ranged between Dollars 6bn and Dollars 10bn .</s>
</TEXT>
<PUB>

<s docid="FT923-6110" num="32" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT923-6110" num="33" wdcount="3"> London Page 14</s>
</PAGE>
</DOC>
