<DOC>
<DOCNO>

<s docid="FT923-5589" num="1" wdcount="1"> FT923-5589</s>
</DOCNO>
<PROFILE>

<s docid="FT923-5589" num="2" wdcount="1"> _AN-CIBBTACQFT</s>
</PROFILE>
<DATE>

<s docid="FT923-5589" num="3" wdcount="1"> 920829</s>
</DATE>
<HEADLINE>

<s docid="FT923-5589" num="4" wdcount="16"> FT 29 AUG 92 / Markets: Hurricane rages but dollar storm blows out - Wall Street</s>
</HEADLINE>
<BYLINE>

<s docid="FT923-5589" num="5" wdcount="3"> By PATRICK HARVERSON</s>
</BYLINE>
<TEXT>

<s docid="FT923-5589" num="6" wdcount="47"> WHILE Hurricane Andrew was wreaking havoc across large parts of southern Florida and Louisiana this week, a grade two dollar crisis (on a one-to-four scale, four being most severe) was blowing itself out at the end of a tumultuous few days for US and world financial markets.</s>

<s docid="FT923-5589" num="7" wdcount="39"> On Wall Street, most of the damage from the currency storm was inflicted a week ago Friday and on the following Monday, when bond yields jumped sharply and the Dow Jones industrial average plunged by more than 75 points.</s>

<s docid="FT923-5589" num="8" wdcount="46"> The flimsy walls erected hastily by the Federal Reserve and other big central banks to protect the vulnerable dollar from a tidal wave of selling on foreign exchange markets failed to hold; and as the sellers poured through the breached barricades, the currency dropped to DM1.40.</s>

<s docid="FT923-5589" num="9" wdcount="8"> This was its lowest-ever point against the D-mark.</s>

<s docid="FT923-5589" num="10" wdcount="17"> The conditions necessary for a dollar crisis had been building up in currency markets for some time.</s>

<s docid="FT923-5589" num="11" wdcount="23"> Interest rate differentials between US and Germany widened over the summer as the Fed eased, and the Bundesbank tightened, their respective monetary policies.</s>

<s docid="FT923-5589" num="12" wdcount="25"> The failure of the US economy to climb out of recession with any vigour was also making overseas investors increasingly unhappy about holding the dollar.</s>

<s docid="FT923-5589" num="13" wdcount="30"> So, too, was the political hole President Bush had dug for himself in a re-election battle that only a year ago was supposed to be a shoo-in for the incumbent.</s>

<s docid="FT923-5589" num="14" wdcount="38"> Moreover, the fact that almost every central bank worth its salt was in the markets trying to prop up the dollar served only to convince foreign exchange dealers that the currency was heading in one direction - down.</s>

<s docid="FT923-5589" num="15" wdcount="30"> While there were plenty of reasons for the dealers to sell the dollar, the logic for such a strongly negative reaction from bond and stock markets was less obviously compelling.</s>

<s docid="FT923-5589" num="16" wdcount="14"> There are two standard explanations why a weak dollar prompts bond prices to fall.</s>

<s docid="FT923-5589" num="17" wdcount="16"> The first is that it raises import prices and, as a result, adds to inflationary pressures.</s>

<s docid="FT923-5589" num="18" wdcount="39"> The second is that it makes it hard for the Fed to engineer another cut in interest rates to stimulate the flagging recovery, and raises the possibility that rates may actually have to go up to protect the currency.</s>

<s docid="FT923-5589" num="19" wdcount="45"> The first explanation is not particularly convincing - imports account for not much more than 10 per cent of US gross domestic product, so higher import prices do not greatly effect the overall price level, which is now around 3 per cent and heading lower.</s>

<s docid="FT923-5589" num="20" wdcount="6"> The second explanation carries more weight.</s>

<s docid="FT923-5589" num="21" wdcount="43"> Although there is not much chance, given the present economic and political climate, that the Fed will raise rates to help the dollar, there is little doubt that the currency's weakness makes it extremely difficult for the Fed to ease monetary policy again.</s>

<s docid="FT923-5589" num="22" wdcount="25"> The fear that the Fed may be done with interest rate cuts for the present economic cycle was also behind the selling in equity markets.</s>

<s docid="FT923-5589" num="23" wdcount="16"> But investors in stocks were equally, if not more, troubled by the rise in bond yields.</s>

<s docid="FT923-5589" num="24" wdcount="36"> Just over a week ago, the yield on the benchmark 30-year bond, which has remained stubbornly high all year despite the poor state of the economy, looked as if it might drop below 7.3 per cent.</s>

<s docid="FT923-5589" num="25" wdcount="31"> The dollar put paid to those hopes and, by the middle of this week, it was approaching 7.45 per cent, putting an upward pressure on the all-important mortgage rate for home-buyers.</s>

<s docid="FT923-5589" num="26" wdcount="30"> The dollar was not the only story in financial markets this week, and the devastating effect of Hurricane Andrew produced a typically hard-eyed, although nonetheless logical, reaction from Wall Street.</s>

<s docid="FT923-5589" num="27" wdcount="24"> The stocks of those insurance companies with the greatest exposure in southern Florida, the area hit worst by the hurricane, all took a tumble.</s>

<s docid="FT923-5589" num="28" wdcount="27"> But the relatively modest losses in Geico, Travelers and Progressive suggested that the market believed the insurers were reserved or reinsured adequately enough to cover hurricane-related claims.</s>

<s docid="FT923-5589" num="29" wdcount="29"> The flip side of the hurricane's coin was a strong showing from the stocks of home construction companies expected to benefit from demand for rebuilding damaged or destroyed homes.</s>

<s docid="FT923-5589" num="30" wdcount="21"> Since there are an estimated 250,000 people left homeless by the storm, there is a lot of work to be done.</s>

<s docid="FT923-5589" num="31" wdcount="28"> The biggest gains among construction stocks this week were posted by Lennar, Oakwood Homes, Engle Homes and Fleetwood, the largest maker of pre-manufactured homes in the US .</s>
</TEXT>
<PUB>

<s docid="FT923-5589" num="32" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT923-5589" num="33" wdcount="3"> London Page II</s>
</PAGE>
</DOC>
