<DOC>
<DOCNO>

<s docid="FT923-5835" num="1" wdcount="1"> FT923-5835</s>
</DOCNO>
<PROFILE>

<s docid="FT923-5835" num="2" wdcount="1"> _AN-CIBBCABPFT</s>
</PROFILE>
<DATE>

<s docid="FT923-5835" num="3" wdcount="1"> 920828</s>
</DATE>
<HEADLINE>

<s docid="FT923-5835" num="4" wdcount="18"> FT 28 AUG 92 / UK Company News: GA says hurricane claims could reach 'up to Dollars 40m'</s>
</HEADLINE>
<BYLINE>

<s docid="FT923-5835" num="5" wdcount="3"> By ROBERT PESTON</s>
</BYLINE>
<TEXT>

<s docid="FT923-5835" num="6" wdcount="23"> GENERAL ACCIDENT, the leading British insurer, said yesterday that insurance claims arising from Hurricane Andrew could 'cost it as much as Dollars 40m'.</s>

<s docid="FT923-5835" num="7" wdcount="52"> Lord Airlie, the chairman who was addressing an extraordinary shareholders' meeting, said: 'On the basis of emerging information, General Accident advise that the losses to their US operations arising from Hurricane Andrew, which struck Florida and Louisiana, might in total reach the level at which external catastrophe reinsurance covers would become exposed'.</s>

<s docid="FT923-5835" num="8" wdcount="24"> What this means is that GA is able to pass on its losses to external reinsurers once a certain claims threshold has been breached.</s>

<s docid="FT923-5835" num="9" wdcount="13"> It believes this threshold may be breached in respect of Hurricane Andrew claims.</s>

<s docid="FT923-5835" num="10" wdcount="15"> However, if this happens, it would suffer a post-tax loss of Dollars 40m (Pounds 20m).</s>

<s docid="FT923-5835" num="11" wdcount="22"> Mr Nelson Robertson, GA's chief general manager, explained later that the company has a 1/2 per cent share of the Florida market.</s>

<s docid="FT923-5835" num="12" wdcount="6"> It has a branch in Orlando.</s>

<s docid="FT923-5835" num="13" wdcount="13"> The company's loss adjusters are in the area trying to estimate the losses.</s>

<s docid="FT923-5835" num="14" wdcount="17"> Their guess is that losses to be faced by all insurers may total more than Dollars 8bn.</s>

<s docid="FT923-5835" num="15" wdcount="24"> Not all damaged property in the area is insured and there have been estimates that the storm caused more than Dollars 20bn of damage.</s>

<s docid="FT923-5835" num="16" wdcount="16"> However, other insurers have estimated that losses could be as low as Dollars 1bn in total.</s>

<s docid="FT923-5835" num="17" wdcount="15"> Mr Robertson said: 'No one knows at this time what the exact loss is' .</s>
</TEXT>
<PUB>

<s docid="FT923-5835" num="18" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT923-5835" num="19" wdcount="3"> London Page 16</s>
</PAGE>
</DOC>
