<DOC>
<DOCNO>

<s docid="AP900118-0029" num="1" wdcount="1"> AP900118-0029</s>
</DOCNO>
<FILEID>

<s docid="AP900118-0029" num="2" wdcount="2"> AP-NR-01-18-90 0329EST</s>
</FILEID>
<FIRST>

<s docid="AP900118-0029" num="3" wdcount="5"> r i PM-EastGermany-Honecker 01-18 0544</s>
</FIRST>
<SECOND>

<s docid="AP900118-0029" num="4" wdcount="2"> PM-East Germany-Honecker,0562</s>
</SECOND>
<HEAD>

<s docid="AP900118-0029" num="5" wdcount="6"> Honecker's Final Weeks In Power Described</s>
</HEAD>
<HEAD>

<s docid="AP900118-0029" num="6" wdcount="3"> With PM-East Germany</s>
</HEAD>
<BYLINE>

<s docid="AP900118-0029" num="7" wdcount="3"> By KEVIN COSTELLOE</s>
</BYLINE>
<BYLINE>

<s docid="AP900118-0029" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900118-0029" num="9" wdcount="3"> WEST BERLIN (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900118-0029" num="10" wdcount="32"> As protests gathered strength last fall, East Germany's longtime orthodox leader Erich Honecker ``lost touch with reality,'' according to the man who succeeded him as Communist leader only to be ousted later.</s>

<s docid="AP900118-0029" num="11" wdcount="26"> Egon Krenz, the successor, and former Politburo member Guenter Schabowski on Wednesday gave their versions of the bunker mentality that engulfed the hard-liners toward the end.</s>

<s docid="AP900118-0029" num="12" wdcount="38"> ``There was the notion in the former party leadership that everything outside of planned events and demonstrations staged by the Communist youth group was an action organized by enemy forces,'' Krenz told an investigating commission in East Berlin.</s>

<s docid="AP900118-0029" num="13" wdcount="8"> The testimony was broadcast on East German television.</s>

<s docid="AP900118-0029" num="14" wdcount="22"> Schabowski said Honecker had personally ordered police attacks against demonstrators in early October, working closely with his then-secret police chief, Erich Mielke.</s>

<s docid="AP900118-0029" num="15" wdcount="9"> ``Honecker took things into his own hands,'' Schabowski said.</s>

<s docid="AP900118-0029" num="16" wdcount="22"> ``All decisions and orders that led to the police actions against demonstrators and to their arrrest went exclusively through Honecker and Mielke''.</s>

<s docid="AP900118-0029" num="17" wdcount="17"> Like Krenz, Schabowski denied any personal responsibility for the orders to attack the demonstrators in the capital.</s>

<s docid="AP900118-0029" num="18" wdcount="21"> The attempts at suppression were engineered by Honecker and Mielke, bypassing the other 19 members of the ruling Politburo, Krenz insisted.</s>

<s docid="AP900118-0029" num="19" wdcount="33"> ``Then-general secretary Erich Honecker and the internal security chief Erich Mielke immediately after each session of the Politburo consulted with each other on the security situation of the German Democratic Republic,'' Krenz said.</s>

<s docid="AP900118-0029" num="20" wdcount="12"> Honecker and Mielke are now targeted for an indictment for high treason.</s>

<s docid="AP900118-0029" num="21" wdcount="22"> The East Berlin city government commission is probing possible criminal charges stemming from police brutality during the October attacks in the capital.</s>

<s docid="AP900118-0029" num="22" wdcount="26"> Club-swinging riot police brutally beat demonstrators on Oct. 7 and 8, when Soviet President Mikhail S. Gorbachev was in town to commemorate the country's 40th anniversary.</s>

<s docid="AP900118-0029" num="23" wdcount="13"> The uprising was a turning point that speeded Honecker's downfall 10 days later.</s>

<s docid="AP900118-0029" num="24" wdcount="21"> Krenz, who had responsibility for many internal security functions before Honecker's ouster, criticized the use of force during his testimony Wednesday.</s>

<s docid="AP900118-0029" num="25" wdcount="24"> ``The excessive action of law enforcement authorities was neither politically nor morally justifiable,'' he told the panel, speaking confidently and wearing a gray suit.</s>

<s docid="AP900118-0029" num="26" wdcount="23"> Krenz, who was thrown out six weeks after succeeding Honecker on Oct. 18, insisted he knew nothing about any orders to shoot demonstrators.</s>

<s docid="AP900118-0029" num="27" wdcount="13"> Numerous news media accounts have said Honecker either planned or issued such orders.</s>

<s docid="AP900118-0029" num="28" wdcount="15"> Krenz said he accepted ``joint responsibility for misjudging dissident citizens and dissident groups for years''.</s>

<s docid="AP900118-0029" num="29" wdcount="32"> ``From today's viewpoint it is incomprehensible that there was no general Politburo discussion about the negative developments then taking place in society,'' said Krenz, an influential Politburo member even before Honecker's fall.</s>

<s docid="AP900118-0029" num="30" wdcount="31"> Krenz added that he and other then-members of the Politburo failed to realize that the Roman Catholic and Lutheran churches were ``not working against but rather for the German Democratic Republic''.</s>

<s docid="AP900118-0029" num="31" wdcount="24"> ``Honecker had lost touch with reality and had unrealistic perspectives,'' Krenz said of his one-time patron, who for years treated him like a son.</s>

<s docid="AP900118-0029" num="32" wdcount="11"> Honecker has been in ill health following gallbladder surgery last summer.</s>

<s docid="AP900118-0029" num="33" wdcount="10"> He was recently operated on for a malignant kidney tumor.</s>

<s docid="AP900118-0029" num="34" wdcount="17"> Krenz's current occupation has not been publicized, following his fall as party chief on Dec. 3 .</s>
</TEXT>
</DOC>
