<DOC>
<DOCNO>

<s docid="AP900730-0116" num="1" wdcount="1"> AP900730-0116</s>
</DOCNO>
<FILEID>

<s docid="AP900730-0116" num="2" wdcount="2"> AP-NR-07-30-90 2101EDT</s>
</FILEID>
<FIRST>

<s docid="AP900730-0116" num="3" wdcount="5"> r i AM-Honecker 07-30 0279</s>
</FIRST>
<SECOND>

<s docid="AP900730-0116" num="4" wdcount="1"> AM-Honecker,0287</s>
</SECOND>
<HEAD>

<s docid="AP900730-0116" num="5" wdcount="11"> Panel: Honecker Unfit to be Held but Fit to be Tried</s>
</HEAD>
<DATELINE>

<s docid="AP900730-0116" num="6" wdcount="3"> EAST BERLIN (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900730-0116" num="7" wdcount="29"> East Germany's deposed Communist leader Erich Honecker is too sick to be held in jail but is fit enough to be tried, the official news agency ADN reported Monday.</s>

<s docid="AP900730-0116" num="8" wdcount="26"> ADN, quoting a Health Ministry statement, said Honecker was still recovering from surgery for kidney cancer in January and was not well enough to be incarcerated.</s>

<s docid="AP900730-0116" num="9" wdcount="22"> But a medical exam by a team of doctors found him in condition to be questioned and to stand trial, ADN said.</s>

<s docid="AP900730-0116" num="10" wdcount="39"> Honecker, 77, ruled East Germany for 19 years until he was ousted in October as a wave of pro-democracy demonstrations swept the country, leading to the peaceful overthrow of the Communist government and the opening of the Berlin Wall.</s>

<s docid="AP900730-0116" num="11" wdcount="30"> The medical panel concluded that seven other former Communist officials, who had been among Honecker's closest aides, were all fit to prosecute and to be placed in custody, ADN said.</s>

<s docid="AP900730-0116" num="12" wdcount="28"> It said former secret police chief Erich Mielke, former economics czar Guenter Mittag and former labor chief Harry Tisch were under arrest, while the other four remained free.</s>

<s docid="AP900730-0116" num="13" wdcount="11"> All three had been members of the ruling Politburo under Honecker.</s>

<s docid="AP900730-0116" num="14" wdcount="5"> Mielke was arrested on Thursday.</s>

<s docid="AP900730-0116" num="15" wdcount="12"> Honecker and the seven are charged with corruption and abuse of office.</s>

<s docid="AP900730-0116" num="16" wdcount="19"> They had been arrested soon after Honecker's fall but were later released because of advanced age and poor health.</s>

<s docid="AP900730-0116" num="17" wdcount="12"> Honecker has been staying at a Soviet military hospital outside East Berlin.</s>

<s docid="AP900730-0116" num="18" wdcount="29"> ADN quoted Federal Prosecutor Guenter Seidel as saying he intended to continue his investigation against the former East German leaders, although their poor health often disrupted the proceedings .</s>
</TEXT>
</DOC>
