<DOC>
<DOCNO>

<s docid="AP900825-0099" num="1" wdcount="1"> AP900825-0099</s>
</DOCNO>
<FILEID>

<s docid="AP900825-0099" num="2" wdcount="2"> AP-NR-08-25-90 1720EST</s>
</FILEID>
<FIRST>

<s docid="AP900825-0099" num="3" wdcount="5"> r i AM-EastGermany-Honecker 08-25 0263</s>
</FIRST>
<SECOND>

<s docid="AP900825-0099" num="4" wdcount="2"> AM-East Germany-Honecker,0270</s>
</SECOND>
<HEAD>

<s docid="AP900825-0099" num="5" wdcount="10"> Report: Honecker Unlikely To Go to Trial in East Germany</s>
</HEAD>
<DATELINE>

<s docid="AP900825-0099" num="6" wdcount="3"> WEST BERLIN (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900825-0099" num="7" wdcount="26"> Ousted East German leader Erich Honecker will not stand trial in East Germany as long as the formerly Communist country exists, a West German newspaper reported.</s>

<s docid="AP900825-0099" num="8" wdcount="30"> The Hamburg-based Bild am Sonntag said Saturday that it would report in its Sunday editions that Honecker could be prosecuted in a united Germany, however, for violation of property laws.</s>

<s docid="AP900825-0099" num="9" wdcount="29"> Bild quoted Guenter Seidel, an East German prosecutor, as saying that Honecker had used $42 million for stocking a private housing estate for leaders of the former Communist government.</s>

<s docid="AP900825-0099" num="10" wdcount="30"> However, Seidel said that the investigation was not far enough along to determine whether charges could be filed against Honecker before East Germany merges with West Germany on Oct. 3.</s>

<s docid="AP900825-0099" num="11" wdcount="13"> Negotiators are still working out the merger of the two German legal systems.</s>

<s docid="AP900825-0099" num="12" wdcount="23"> Honecker, 78, was ousted as East Germany's leader on Oct. 18, paving the way for the country's first freely elected government in March.</s>

<s docid="AP900825-0099" num="13" wdcount="18"> Honecker is in poor health and remains confined to a Soviet military hospital in Beelitz outside East Berlin.</s>

<s docid="AP900825-0099" num="14" wdcount="33"> He is under investigation on allegations of abuse of power, corruption, harboring terrorists and issuing shoot-to-kill orders to prevent East Germans from escaping to West Germany when he served as the country's leader.</s>

<s docid="AP900825-0099" num="15" wdcount="23"> Bild said that Erich Mielke, the ex-head of East Germany's former secret police, was also unlikely to go to court in East Germany.</s>

<s docid="AP900825-0099" num="16" wdcount="21"> ``I am at the end. I am a dead man,'' Bild quoted Mielke, 82, as saying at his last interrogation .</s>
</TEXT>
</DOC>
