<DOC>
<DOCNO>

<s docid="AP900129-0036" num="1" wdcount="1"> AP900129-0036</s>
</DOCNO>
<FILEID>

<s docid="AP900129-0036" num="2" wdcount="2"> AP-NR-01-29-90 0413EST</s>
</FILEID>
<FIRST>

<s docid="AP900129-0036" num="3" wdcount="7"> u i BC-HoneckerArrested 1stLd-Writethru a0462 01-29 0275</s>
</FIRST>
<SECOND>

<s docid="AP900129-0036" num="4" wdcount="5"> BC-Honecker Arrested, 1st Ld-Writethru, a0462,0277</s>
</SECOND>
<HEAD>

<s docid="AP900129-0036" num="5" wdcount="5"> Honecker Arrested, Taken to Prison</s>
</HEAD>
<NOTE>

<s docid="AP900129-0036" num="6" wdcount="19"> Eds: UPDATES with physician saying Honecker still not well enough to be jailed, unclear if prison has hospital unit.</s>

<s docid="AP900129-0036" num="7" wdcount="3"> No pickup .</s>
</NOTE>
<DATELINE>

<s docid="AP900129-0036" num="8" wdcount="3"> EAST BERLIN (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900129-0036" num="9" wdcount="34"> Ousted East German leader Erich Honecker, who is expected to be indicted for high treason, was arrested Monday morning upon release from a hospital and taken to prison, the official news agency ADN said.</s>

<s docid="AP900129-0036" num="10" wdcount="27"> The news agency said the 77-year-old Honecker was arrested after being released from East Berlin's Charite hospital, where he had undergone surgery for a malignant kidney tumor.</s>

<s docid="AP900129-0036" num="11" wdcount="13"> Honecker was immediately taken to East Berlin's Rummelsburg prison, the brief dispatch said.</s>

<s docid="AP900129-0036" num="12" wdcount="13"> Honecker joins other members of his ousted Politburo already in prison awaiting trial.</s>

<s docid="AP900129-0036" num="13" wdcount="31"> Earlier this month, East German prosecutors said Honecker and former state security chief Erich Mielke would be charged with treason and corruption charges for misuse of their positions and state funds.</s>

<s docid="AP900129-0036" num="14" wdcount="28"> Honecker, the aging hard-line Stalinist leader who ruled East Germany for 18 years until his ouster on Oct. 18, had previously been declared too ill to withstand imprisonment.</s>

<s docid="AP900129-0036" num="15" wdcount="28"> ADN said that the director of Charite urology clinic, Dr. Peter Althaus, repeated on Monday that in his opinion Honecker was still not well enough to be jailed.</s>

<s docid="AP900129-0036" num="16" wdcount="26"> On Sunday, West Germany's mass-circulation Bild newspaper said Honecker would be arrested, but that he would be held at a prison hospital because of his condition.</s>

<s docid="AP900129-0036" num="17" wdcount="13"> ADN made not mention if Rummelsburg prison was equipped with a medical facility.</s>

<s docid="AP900129-0036" num="18" wdcount="26"> Earlier this month, East Germany's Luthern Church had offered to put Honecker up in a home for the aged upon his release from the hospital .</s>
</TEXT>
</DOC>
