<DOC>
<DOCNO>

<s docid="AP901208-0106" num="1" wdcount="1"> AP901208-0106</s>
</DOCNO>
<FILEID>

<s docid="AP901208-0106" num="2" wdcount="2"> AP-NY-12-08-90 1735EST</s>
</FILEID>
<FIRST>

<s docid="AP901208-0106" num="3" wdcount="5"> r i AM-Germany-Honecker 12-08 0225</s>
</FIRST>
<SECOND>

<s docid="AP901208-0106" num="4" wdcount="1"> AM-Germany-Honecker,0230</s>
</SECOND>
<HEAD>

<s docid="AP901208-0106" num="5" wdcount="8"> Report: High-Ranking German Demands Soviets Hand Over Honecker</s>
</HEAD>
<DATELINE>

<s docid="AP901208-0106" num="6" wdcount="3"> BONN, Germany (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP901208-0106" num="7" wdcount="30"> A ranking member of Chancellor Helmut Kohl's party demanded the Soviet Union hand over Erich Honecker, who is wanted by German authorities on manslaughter charges, a newspaper reported on Saturday.</s>

<s docid="AP901208-0106" num="8" wdcount="29"> Federal lawmaker Johannes Gerster said refusal to turn over the deposed East German leader for trial could ``burden'' Bonn and Moscow's ``outstanding relations,'' the Neue Osnabruecker Zeitung newspaper reported.</s>

<s docid="AP901208-0106" num="9" wdcount="15"> A Berlin court has issued an arrest warrant for Honecker, 78, on the manslaughter charges.</s>

<s docid="AP901208-0106" num="10" wdcount="16"> He is accused of issuing shoot-to-kill orders to East German guards at the now-fallen Berlin Wall.</s>

<s docid="AP901208-0106" num="11" wdcount="26"> Honecker has denied all charges against him, including that he was personally responsible for the estimated 200 people who died trying to escape his repressive government.</s>

<s docid="AP901208-0106" num="12" wdcount="13"> He has taken refuge at a Soviet military hospital in Beelitz, outside Berlin.</s>

<s docid="AP901208-0106" num="13" wdcount="24"> Soviet officials have said Honecker is staying at the hospital for humanitarian reasons, and German police need permission from the Soviets to gain entry.</s>

<s docid="AP901208-0106" num="14" wdcount="30"> ``I demand that the Soviet government immediately release Erich Honecker and extradite him to German justice officials,'' the Osnabrueck newspaper quoted Gerster, a member of Kohl's Christian Democrats, as saying.</s>

<s docid="AP901208-0106" num="15" wdcount="26"> Honecker's fate is one of the first issues facing Bonn and Moscow since they signed several treaties designed to draw the two nations closer together .</s>
</TEXT>
</DOC>
