<DOC>
<DOCNO>

<s docid="AP900103-0077" num="1" wdcount="1"> AP900103-0077</s>
</DOCNO>
<FILEID>

<s docid="AP900103-0077" num="2" wdcount="2"> AP-NR-01-03-90 1240EDT</s>
</FILEID>
<FIRST>

<s docid="AP900103-0077" num="3" wdcount="5"> r i AM-Honecker 01-03 0311</s>
</FIRST>
<SECOND>

<s docid="AP900103-0077" num="4" wdcount="1"> AM-Honecker,0322</s>
</SECOND>
<HEAD>

<s docid="AP900103-0077" num="5" wdcount="10"> Report Honecker May be Moved to Monastery For His Safety</s>
</HEAD>
<HEAD>

<s docid="AP900103-0077" num="6" wdcount="4"> With AM-East Germany, Bjt</s>
</HEAD>
<DATELINE>

<s docid="AP900103-0077" num="7" wdcount="4"> HAMBURG, West Germany (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900103-0077" num="8" wdcount="26"> Former East German leader Erich Honecker may be moved to a monastery to protect him from a possible lynching by enraged citizens, a newspaper said Wednesday.</s>

<s docid="AP900103-0077" num="9" wdcount="18"> In a front-page story, the mass-circulation Bild newspaper said ``Lynch Danger _ Church Wants to Grant Honecker Asylum''.</s>

<s docid="AP900103-0077" num="10" wdcount="33"> Since Honecker was ousted Oct. 18, the former Communist Party leader and other party officials have come under investigation for charges of corruption and living in luxury at the cost of the state.</s>

<s docid="AP900103-0077" num="11" wdcount="25"> In December, seven former Politburo members were arrested, and Honecker was placed under house arrest in the government housing area of Wandlitz outside East Berlin.</s>

<s docid="AP900103-0077" num="12" wdcount="21"> The Wandlitz homes, including the one in which Honecker still lives, are being converted to a medical rehabilitation center for children.</s>

<s docid="AP900103-0077" num="13" wdcount="12"> Honecker is expected to be forced out of the compound in February.</s>

<s docid="AP900103-0077" num="14" wdcount="25"> Bild said it had information that ``Lutheran and Catholic church sources have offered Honecker _ who is threated by public rage _ protection and refuge''.</s>

<s docid="AP900103-0077" num="15" wdcount="23"> ``This is the only possibility to protect Erich Honecker from the rage of the East German people,'' Bild quoted the source as saying.</s>

<s docid="AP900103-0077" num="16" wdcount="22"> It was the churches that became the venues for gathering of pro-democracy groups that eventually brought the overthrow of his 18-year leadership.</s>

<s docid="AP900103-0077" num="17" wdcount="24"> In recent weeks, East German groups have called for punishing Honecker and for moving him to smaller quarters ``with an outside toilet,'' Bild said.</s>

<s docid="AP900103-0077" num="18" wdcount="22"> The current leadership fears that in such a situation, Honecker ``might be attacked and become a victim of lynch justice,'' Bild said.</s>

<s docid="AP900103-0077" num="19" wdcount="16"> Honecker, 77, underwent gall-bladder surgery in August, and East German media reported he remains seriously ill.</s>

<s docid="AP900103-0077" num="20" wdcount="23"> ``Sources say the ailing ex-leader may be placed in a church-operated home for the elderly, or even in a monastery,'' Bild reported .</s>
</TEXT>
</DOC>
