<DOC>
<DOCNO>

<s docid="AP900810-0120" num="1" wdcount="1"> AP900810-0120</s>
</DOCNO>
<FILEID>

<s docid="AP900810-0120" num="2" wdcount="2"> AP-NR-08-10-90 2233EDT</s>
</FILEID>
<FIRST>

<s docid="AP900810-0120" num="3" wdcount="5"> r i AM-Honecker 08-10 0217</s>
</FIRST>
<SECOND>

<s docid="AP900810-0120" num="4" wdcount="1"> AM-Honecker,0224</s>
</SECOND>
<HEAD>

<s docid="AP900810-0120" num="5" wdcount="6"> Authorities Interrogate Honecker in Murder Probe</s>
</HEAD>
<DATELINE>

<s docid="AP900810-0120" num="6" wdcount="3"> EAST BERLIN (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900810-0120" num="7" wdcount="25"> East Germany authorities on Friday interrogated former Communist leader Erich Honecker about his role in the killings of people who tried to flee the country.</s>

<s docid="AP900810-0120" num="8" wdcount="24"> Honecker and Erich Mielke, head of East Germany's once-feared secret police agency, were interrogated by federal prosecutors, said Peter Przybylski, a Justice Ministry spokesman.</s>

<s docid="AP900810-0120" num="9" wdcount="23"> More than 200 people were shot to death or killed by land mines as they tried to escape from East Germany's Communist rule.</s>

<s docid="AP900810-0120" num="10" wdcount="24"> The government announced in June that Honecker, Mielke and several border guards would be investigated on possible murder charges in connection with those deaths.</s>

<s docid="AP900810-0120" num="11" wdcount="24"> Honecker, 77 and in failing health, and several other members of his ousted regime already have been charged with corruption and abuse of power.</s>

<s docid="AP900810-0120" num="12" wdcount="17"> The murder charge could put Honecker behind bars for life, but his poor health makes prosecution questionable.</s>

<s docid="AP900810-0120" num="13" wdcount="9"> He is staying in a Soviet hospital outside Berlin.</s>

<s docid="AP900810-0120" num="14" wdcount="22"> Last month, a medical panel ruled that Honecker was too ill to be jailed pending investigation but fit enough to be prosecuted.</s>

<s docid="AP900810-0120" num="15" wdcount="4"> Mielke was ordered jailed.</s>

<s docid="AP900810-0120" num="16" wdcount="33"> East Germany's democratic government has changed its mind several times on whether to pursue charges against the aging members of the former hard-line regime that was toppled in last autumn's pro-democracy protests .</s>
</TEXT>
</DOC>
