<DOC>
<DOCNO>

<s docid="AP900129-0071" num="1" wdcount="1"> AP900129-0071</s>
</DOCNO>
<FILEID>

<s docid="AP900129-0071" num="2" wdcount="2"> AP-NR-01-29-90 1223EST</s>
</FILEID>
<FIRST>

<s docid="AP900129-0071" num="3" wdcount="6"> u i PM-Honecker 2ndLd-Writethru 01-29 0445</s>
</FIRST>
<SECOND>

<s docid="AP900129-0071" num="4" wdcount="5"> PM-Honecker, 2nd Ld - Writethru,a0509,0454</s>
</SECOND>
<HEAD>

<s docid="AP900129-0071" num="5" wdcount="7"> Ousted East German Leader Arrested And Jailed</s>
</HEAD>
<NOTE>

<s docid="AP900129-0071" num="6" wdcount="26"> Eds: LEADS with 9 grafs to UPDATE with Honecker to be tried in March, four associates also to be tried; picks up 11th pvs, `East Germany...'</s>
</NOTE>
<HEAD>

<s docid="AP900129-0071" num="7" wdcount="4"> With PM-East Germany, Bjt</s>
</HEAD>
<DATELINE>

<s docid="AP900129-0071" num="8" wdcount="3"> EAST BERLIN (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900129-0071" num="9" wdcount="25"> Ousted East German leader Erich Honecker was arrested and taken to prison today, and a prosecutor said he will tried for high treason in March.</s>

<s docid="AP900129-0071" num="10" wdcount="28"> Honecker, 77, was detained after his release from East Berlin's Charite hospital, where he had undergone surgery for a malignant kidney tumor, the official ADN news agency said.</s>

<s docid="AP900129-0071" num="11" wdcount="31"> Chief Prosecutor Hans-Juergen Joseph told Parliament that Honecker and former Politburo members Erich Mielke, Guenter Mittag and Joachim Herrmann would be tried by the Supreme Court on treason charges in March.</s>

<s docid="AP900129-0071" num="12" wdcount="8"> All four have been expelled from the party.</s>

<s docid="AP900129-0071" num="13" wdcount="16"> Mielke was Honecker's security chief, Mittag oversaw the economy and Herrmann headed the party's propaganda department.</s>

<s docid="AP900129-0071" num="14" wdcount="12"> Eleven members of Honecker's ousted Politburo already are in prison awaiting trial.</s>

<s docid="AP900129-0071" num="15" wdcount="32"> Honecker's lawyer, Wolfgang Vogel, asked the chief prosecutor to free the former leader from Rummelburg prison based on a doctor's statement that he is too ill to stay in jail, ADN said.</s>

<s docid="AP900129-0071" num="16" wdcount="7"> Vogel is East Germany's most prominent lawyer.</s>

<s docid="AP900129-0071" num="17" wdcount="25"> One of Honecker's doctors, Horst Vogler, said the former leader was ``very depressed'' and his mental state ``impaired'' following two major surgical operations since August.</s>

<s docid="AP900129-0071" num="18" wdcount="20"> West German television showed an impassive Honecker being led out of the hospital by his wife, Margot, in pre-dawn darkness.</s>

<s docid="AP900129-0071" num="19" wdcount="13"> She kissed him goodbye before he was taken away in a large limousine.</s>

<s docid="AP900129-0071" num="20" wdcount="20"> Honecker's daughter, son-in-law and youngest grandchild also came to see him off at the hospital, ADN quoted Vogler as saying.</s>

<s docid="AP900129-0071" num="21" wdcount="10"> The charge of high treason carries a maximum life imprisonment.</s>

<s docid="AP900129-0071" num="22" wdcount="20"> The conviction used to carry the death penalty, but that was abolished in reforms that followed Honecker's ouster Oct. 18.</s>

<s docid="AP900129-0071" num="23" wdcount="18"> East Germany has been caught up in a virtual frenzy to root out corruption and abuse of office.</s>

<s docid="AP900129-0071" num="24" wdcount="22"> Honecker, the aging hard-line Stalinist leader who ruled East Germany for 18 years, had previously been declared too ill to withstand imprisonment.</s>

<s docid="AP900129-0071" num="25" wdcount="26"> ADN said the director of Charite urology clinic, Dr. Peter Althaus, repeated today that in his opinion Honecker is still not well enough to be jailed.</s>

<s docid="AP900129-0071" num="26" wdcount="26"> On Sunday, West Germany's mass-circulation Bild newspaper said Honecker would be arrested but that he would be held at a prison hospital because of his condition.</s>

<s docid="AP900129-0071" num="27" wdcount="13"> ADN did not say whether Rummelsburg prison is equipped with a medical facility.</s>

<s docid="AP900129-0071" num="28" wdcount="26"> Earlier this month, East Germany's Luthern Church had offered to put Honecker up in a home for the aged upon his release from the hospital .</s>
</TEXT>
</DOC>
