<DOC>
<DOCNO>

<s docid="AP900919-0122" num="1" wdcount="1"> AP900919-0122</s>
</DOCNO>
<FILEID>

<s docid="AP900919-0122" num="2" wdcount="2"> AP-NY-09-19-90 1706EDT</s>
</FILEID>
<FIRST>

<s docid="AP900919-0122" num="3" wdcount="5"> r i AM-Honecker 09-19 0304</s>
</FIRST>
<SECOND>

<s docid="AP900919-0122" num="4" wdcount="1"> AM-Honecker,0349</s>
</SECOND>
<HEAD>

<s docid="AP900919-0122" num="5" wdcount="8"> Report: Ousted Stasi Chief Threatened Honecker in Jail</s>
</HEAD>
<DATELINE>

<s docid="AP900919-0122" num="6" wdcount="4"> HAMBURG, West Germany (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900919-0122" num="7" wdcount="29"> East Germany's ousted secret police chief threatened to break former Communist leader Erich Honecker's neck when the two faced each other in jail, a West German newspaper reported Wednesday.</s>

<s docid="AP900919-0122" num="8" wdcount="15"> ``You traitor''! 82-year-old former security chief Erich Mielke shouted at Honecker, according to Bild newspaper.</s>

<s docid="AP900919-0122" num="9" wdcount="26"> Mielke also screamed at Honecker ``I'll break your neck''! the newspaper quoted witnesses as describing the scene when the two met in an East German jail.</s>

<s docid="AP900919-0122" num="10" wdcount="9"> Honecker, 78, was jailed for one day in January.</s>

<s docid="AP900919-0122" num="11" wdcount="28"> Mielke for years headed the dreaded secret police, known as Stasi, which built up files on 6 million East Germans and kept a tight rein on the population.</s>

<s docid="AP900919-0122" num="12" wdcount="7"> He was one of Honecker's closest aides.</s>

<s docid="AP900919-0122" num="13" wdcount="26"> After the popular revolt last fall that ousted the Communist regime and opened the way to German unification, Mielke and other former Communist leaders were jailed.</s>

<s docid="AP900919-0122" num="14" wdcount="4"> Mielke remains in custody.</s>

<s docid="AP900919-0122" num="15" wdcount="8"> Honecker was released from jail for health reasons.</s>

<s docid="AP900919-0122" num="16" wdcount="11"> West German authorities on Tuesday opened a criminal investigation of Mielke.</s>

<s docid="AP900919-0122" num="17" wdcount="29"> He is suspected of giving sanctuary to members of West Germany's leftist terrorist group, the Red Army Faction, and of setting up contacts between the group and Palestinian guerrillas.</s>

<s docid="AP900919-0122" num="18" wdcount="17"> Honecker is also the target of several criminal investigations, one in West Germany for obstruction of justice.</s>

<s docid="AP900919-0122" num="19" wdcount="19"> Bild said the imprisoned Mielke also accused other former Communist officials of betrayal and threatened to retaliate against them.</s>

<s docid="AP900919-0122" num="20" wdcount="33"> One prison warden told Bild that many of the guards had worked for Mielke's Stasi and that they might interpret his threat against Honecker as an order to kill the former Communist chief.</s>

<s docid="AP900919-0122" num="21" wdcount="24"> Bild said Mielke and other members of Honecker's ruling circle will be moved to a West Berlin prison after German unification on Oct. 3.</s>

<s docid="AP900919-0122" num="22" wdcount="19"> Honecker also will be moved to the same jail if his health improves enough for him to be imprisoned.</s>

<s docid="AP900919-0122" num="23" wdcount="19"> He is suffering from kidney cancer and is being kept at a Soviet military hospital oustide East Berlin .</s>
</TEXT>
</DOC>
