<DOC>
<DOCNO>

<s docid="FBIS4-42178" num="1" wdcount="1"> FBIS4-42178</s>
</DOCNO>
<HT>

<s docid="FBIS4-42178" num="2" wdcount="1"> "drweu104__a94019"</s>
</HT>
<HEADER>
<AU>

<s docid="FBIS4-42178" num="3" wdcount="1"> FBIS-WEU-94-104-A</s>
</AU>

<s docid="FBIS4-42178" num="4" wdcount="2"> Daily Report</s>
<DATE1>

<s docid="FBIS4-42178" num="5" wdcount="3"> 29 May 1994</s>
</DATE1>
</HEADER>
<F>

<s docid="FBIS4-42178" num="6" wdcount="1"> ANNEX</s>
</F>
<F>

<s docid="FBIS4-42178" num="7" wdcount="1"> Germany</s>
</F>
<H3>
<TI>

<s docid="FBIS4-42178" num="8" wdcount="7"> Erich Honecker Dies in Chile 29 May</s>
</TI>
</H3>
<HT>
<F>
<PHRASE>

<s docid="FBIS4-42178" num="9" wdcount="7"> Erich Honecker Dies in Chile 29 May</s>
</PHRASE>
</F>
</HT>
<F>

<s docid="FBIS4-42178" num="10" wdcount="15"> AU2905165694 Hamburg DPA in German 1602 GMT 29 May 94 -- FOR OFFICIAL USE ONLY</s>
</F>
<F>

<s docid="FBIS4-42178" num="11" wdcount="1"> AU2905165694</s>
</F>
<F>

<s docid="FBIS4-42178" num="12" wdcount="2"> Hamburg DPA</s>
</F>
<F>

<s docid="FBIS4-42178" num="13" wdcount="1"> German</s>
</F>
<TEXT>

<s docid="FBIS4-42178" num="14" wdcount="28"> BFN [Text] Berlin -- Erich Honecker, the former GDR head of state, died at his house in Santiago, Chile on Sunday morning [29 May], according to his lawyer.</s>

<s docid="FBIS4-42178" num="15" wdcount="28"> Lawyer Nicolas Becker, who had represented 81-year-old Honecker before the Berlin court in 1992 and early 1993, told DPA on Sunday afternoon that Honecker had rejected an operation.</s>

<s docid="FBIS4-42178" num="16" wdcount="13"> However, everything that was sensible had been done with regard to his cancer.</s>

<s docid="FBIS4-42178" num="17" wdcount="11"> Becker could not comment on the exact cause of Honecker's death.</s>

<s docid="FBIS4-42178" num="18" wdcount="23"> His colleague, Wolfgang Ziegler, had said earlier that the former most powerful man in the GDR had obviously died from his liver cancer.</s>

<s docid="FBIS4-42178" num="19" wdcount="19"> Becker said he did not know whether Honecker has left a will or where the funeral would be held.</s>

<s docid="FBIS4-42178" num="20" wdcount="7"> This will be decided by the family.</s>

<s docid="FBIS4-42178" num="21" wdcount="24"> He also said he cannot say whether Margot Honecker, who had informed Becker of her husband's death, will be allowed to stay in Chile.</s>

<s docid="FBIS4-42178" num="22" wdcount="22"> After being released from prison in 1993, Honecker had traveled to Santiago to join his daughter, who is married to a Chilean.</s>

<s docid="FBIS4-42178" num="23" wdcount="18"> Since then, he and his wife had been living in a house in a wealthy Santiago area .</s>
</TEXT>
</DOC>
