<DOC>
<DOCNO>

<s docid="SJMN91-06353190" num="1" wdcount="1"> SJMN91-06353190</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06353190" num="2" wdcount="1"> 06353190</s>
</ACCESS>
<CAPTION>

<s docid="SJMN91-06353190" num="3" wdcount="32"> Photo; PHOTO: Associated Press; A SONG FOR HONECKER -- Supporters of Erich Honecker sing communist songs Monday night in front of the Chilean Embassy in Moscow, where he has sought refuge .</s>
</CAPTION>
<DESCRIPT>

<s docid="SJMN91-06353190" num="4" wdcount="9"> PAST; EAST; GERMANY; MILITARY; OFFICIAL; USSR; PRESIDENT; SUPPORT; DELAY</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06353190" num="5" wdcount="34"> Mikhail Gorbachev urged all sides Tuesday to take their time in deciding the fate of Erich Honecker, as the fugitive former East German leader spent a seventh day of refuge inside the Chilean Embassy.</s>

<s docid="SJMN91-06353190" num="6" wdcount="25"> A day after the Russian government backed down from its threat to expel him, diplomats sought to settle the fate of the 79-year-old Honecker .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06353190" num="7" wdcount="1"> Front</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06353190" num="8" wdcount="9"> HONECKER FATE STILL UNDECIDED GORBACHEV URGES A GO-SLOW APPROACH</s>
</HEADLINE>
<TEXT>

<s docid="SJMN91-06353190" num="9" wdcount="23"> Germany wants to try him for ordering the shooting of people who attempted to flee to the West during his years in power.</s>

<s docid="SJMN91-06353190" num="10" wdcount="19"> But speculation lingers that German politicians have little real interest in trying a man who may possess embarrassing secrets.</s>

<s docid="SJMN91-06353190" num="11" wdcount="11"> "Let's forget about the issue of Erich Honecker for several days.</s>

<s docid="SJMN91-06353190" num="12" wdcount="20"> Let's hope this special issue will be resolved," Gorbachev's spokesman, Andrei Grachev, quoted the Soviet president as telling German media.</s>

<s docid="SJMN91-06353190" num="13" wdcount="25"> But Tass quoted Gorbachev as saying he did not exclude the possibility that Honecker would leave Russia for North Korea in the next few days.</s>

<s docid="SJMN91-06353190" num="14" wdcount="13"> Gorbachev had served as Honecker's protector until the Soviet leader's political fortunes declined.</s>

<s docid="SJMN91-06353190" num="15" wdcount="13"> Last week Russia abruptly ordered Honecker to leave the country or face expulsion.</s>

<s docid="SJMN91-06353190" num="16" wdcount="29"> North Korean and Russian diplomats confirmed that talks were held Tuesday about a North Korean offer for Honecker to travel to Pyongyang, the North Korean capital, for medical treatment.</s>

<s docid="SJMN91-06353190" num="17" wdcount="27"> Li Cher Gvan, a consul at the North Korean Embassy, said a commercial North Korean airliner remained at Moscow's Sheremetyevo Airport ready to fly Honecker to Pyongyang.</s>

<s docid="SJMN91-06353190" num="18" wdcount="21"> But he said his country was still awaiting a positive reply from the Russian government on the offer to accept Honecker.</s>

<s docid="SJMN91-06353190" num="19" wdcount="12"> The Russian Foreign Ministry said it had not yet formulated a response.</s>

<s docid="SJMN91-06353190" num="20" wdcount="16"> Outside the Chilean Embassy, several dozen demonstrators continued their vigil, demanding humane treatment for Honecker .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06353190" num="21" wdcount="2"> Associated Press</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06353190" num="22" wdcount="1"> USA</s>
</COUNTRY>
<CITY>

<s docid="SJMN91-06353190" num="23" wdcount="1"> Moscow</s>
</CITY>
<EDITION>

<s docid="SJMN91-06353190" num="24" wdcount="2"> Morning Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06353190" num="25" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06353190" num="26" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06353190" num="27" wdcount="1"> 911218</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06353190" num="28" wdcount="1"> Wednesday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06353190" num="29" wdcount="1"> December</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06353190" num="30" wdcount="1"> 6A</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06353190" num="31" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06353190" num="32" wdcount="1"> WEST</s>
</REGION>
<FEATURE>

<s docid="SJMN91-06353190" num="33" wdcount="1"> PHOTO</s>
</FEATURE>
<STATE>

<s docid="SJMN91-06353190" num="34" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06353190" num="35" wdcount="1"> 318</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06353190" num="36" wdcount="5"> Wednesday, December 18, 1991 00353190,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06353190" num="37" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06353190" num="38" wdcount="1"> 1</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06353190" num="39" wdcount="1"> ENG</s>
</LANGUAGE>
</DOC>
