<DOC>
<DOCNO>

<s docid="AP880912-0137" num="1" wdcount="1"> AP880912-0137</s>
</DOCNO>
<FILEID>

<s docid="AP880912-0137" num="2" wdcount="2"> AP-NR-09-12-88 1555EDT</s>
</FILEID>
<FIRST>

<s docid="AP880912-0137" num="3" wdcount="6"> u i AM-HurricaneGilbert Bjt 09-12 0681</s>
</FIRST>
<SECOND>

<s docid="AP880912-0137" num="4" wdcount="3"> AM-Hurricane Gilbert, Bjt,0702</s>
</SECOND>
<HEAD>

<s docid="AP880912-0137" num="5" wdcount="9"> Hurricane Hits Jamaica With 115 mph Winds; Communications Disrupted</s>
</HEAD>
<BYLINE>

<s docid="AP880912-0137" num="6" wdcount="3"> By LLOYD WILLIAMS</s>
</BYLINE>
<BYLINE>

<s docid="AP880912-0137" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880912-0137" num="8" wdcount="3"> KINGSTON, Jamaica (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880912-0137" num="9" wdcount="27"> Hurricane Gilbert slammed into Kingston on Monday with torrential rains and 115 mph winds that ripped roofs off homes and buildings, uprooted trees and downed power lines.</s>

<s docid="AP880912-0137" num="10" wdcount="24"> No serious injuries were immediately reported in the city of 750,000 people, which was hit by the full force of the hurricane around noon.</s>

<s docid="AP880912-0137" num="11" wdcount="22"> For half an hour, the hurricane lashed the city, tearing branches from trees, blowing down fences and whipping paper through the air.</s>

<s docid="AP880912-0137" num="12" wdcount="16"> The National Weather Service reported heavy damage to Kingston's airport and aircraft parked on its fields.</s>

<s docid="AP880912-0137" num="13" wdcount="15"> The first shock let up as the eye of the storm moved across the city.</s>

<s docid="AP880912-0137" num="14" wdcount="20"> Skies brightened, the winds died down and people waited for an hour before the second blow of the hurricane arrived.</s>

<s docid="AP880912-0137" num="15" wdcount="9"> All Jamaica-bound flights were canceled at Miami International Airport.</s>

<s docid="AP880912-0137" num="16" wdcount="23"> Flights from the Cayman Islands, reportedly next in the path of the hurricane, arrived in Miami packed with travelers cutting short their vacations.</s>

<s docid="AP880912-0137" num="17" wdcount="25"> ``People were running around in the main lobby of our hotel (on Grand Cayman Island) like chickens with their heads cut off,'' said one man.</s>

<s docid="AP880912-0137" num="18" wdcount="21"> A National Weather Service report said the hurricane was moving west at 17 mph with maximum sustained winds of 115 mph.</s>

<s docid="AP880912-0137" num="19" wdcount="19"> It said Jamaica would receive up to 10 inches of rain that would cause flash floods and mud slides.</s>

<s docid="AP880912-0137" num="20" wdcount="18"> ``Right now it's actually moving over Jamaica,'' said Bob Sheets, director of the National Hurricane Center in Miami.</s>

<s docid="AP880912-0137" num="21" wdcount="27"> ``It looks like the eye is going to move lengthwise across that island, and they're going to bear the full brunt of this powerful hurricane,'' he said.</s>

<s docid="AP880912-0137" num="22" wdcount="13"> Gilbert reached Jamaica after skirting southern Puerto Rico, Haiti and the Dominican Republic.</s>

<s docid="AP880912-0137" num="23" wdcount="27"> Hurricane warnings were issued Monday for the south coast of Cuba east of Camaguey, the Cayman Islands, and Haiti, while warnings were discontinued for the Dominican Republic.</s>

<s docid="AP880912-0137" num="24" wdcount="21"> High winds and heavy rain preceding the storm drenched Kingston overnight, toppling trees, causing local flooding and littering streets with branches.</s>

<s docid="AP880912-0137" num="25" wdcount="16"> Most of Jamaica's 2.3 million people stayed home, boarding up windows in preparation for the hurricane.</s>

<s docid="AP880912-0137" num="26" wdcount="39"> The popular north coast resort area, on the other side of the mountains, was expected to receive heavy rain but not as much damage from the hurricane as the south coast, where officials urged residents to seek higher ground.</s>

<s docid="AP880912-0137" num="27" wdcount="31"> Havana Radio, meanwhile, reported Monday that 25,000 people were evacuated from coastal areas in Guantanamo Province on the nation's southeastern coast as Gilbert's winds and rain began to brush the island.</s>

<s docid="AP880912-0137" num="28" wdcount="32"> In Washington, the Navy reported its bases at Guantanamo Bay, Cuba, and Roosevelt Roads, Puerto Rico, had taken various precautionary steps but appeared to be safe from the brunt of the hurricane.</s>

<s docid="AP880912-0137" num="29" wdcount="29"> Lt. Ken Ross, a spokesman, said the Navy station at Guantanamo reported that as of 2:30 p.m. EDT, the brunt of the storm appeared to be passing southeastern Cuba.</s>

<s docid="AP880912-0137" num="30" wdcount="16"> ``They have reported maximum winds of 25 knots and gusts up to 50 knots,'' said Ross.</s>

<s docid="AP880912-0137" num="31" wdcount="9"> ``But there are no reports of injuries or damage''.</s>

<s docid="AP880912-0137" num="32" wdcount="32"> The spokesman said earlier in the day, Guantanamo had moved to ``Condition Two,'' meaning electrical power usage was cut back to only essential uses and ``all non-essential personnel sent to their barracks''.</s>

<s docid="AP880912-0137" num="33" wdcount="15"> The storm also skirted Puerto Rico without causing any damage to military facilities, Ross said.</s>

<s docid="AP880912-0137" num="34" wdcount="30"> Sheets said Gilbert was expected next to sweep over the Cayman Islands, on its westward track, and in two to three days veer northwest into the southern Gulf of Mexico.</s>

<s docid="AP880912-0137" num="35" wdcount="18"> Residents of the neighboring Caymans, a British dependency to the northwest, were urged to ``rush all preparatory actions''.</s>

<s docid="AP880912-0137" num="36" wdcount="22"> The National Weather Service warned that the Caymans could expect high waters and large waves ``which may undermine buildings along the beaches''.</s>

<s docid="AP880912-0137" num="37" wdcount="19"> ``All interests in the Western Caribbean should continue to monitor the progress of this dangerous hurricane,'' the service advised.</s>

<s docid="AP880912-0137" num="38" wdcount="22"> Forecaster Hal Gerrish on Sunday described Gilbert ``certainly one of the larger systems we've seen in the Caribbean for a long time.''</s>
</TEXT>
</DOC>
