<DOC>
<DOCNO>

<s docid="AP880912-0095" num="1" wdcount="1"> AP880912-0095</s>
</DOCNO>
<FILEID>

<s docid="AP880912-0095" num="2" wdcount="2"> AP-NR-09-12-88 1300EDT</s>
</FILEID>
<FIRST>

<s docid="AP880912-0095" num="3" wdcount="7"> u i PM-HurricaneGilbert 5thLd-Writethru a0539 09-12 0829</s>
</FIRST>
<SECOND>

<s docid="AP880912-0095" num="4" wdcount="7"> PM-Hurricane Gilbert, 5th Ld - Writethru, a0539,0851</s>
</SECOND>
<HEAD>

<s docid="AP880912-0095" num="5" wdcount="8"> Gilbert Reaches Jamaican Capital With 110 Mph Winds</s>
</HEAD>
<NOTE>

<s docid="AP880912-0095" num="6" wdcount="14"> Eds: LEADS 10 grafs with hurricane reaching Kingston with 110 mph winds, details, quotes.</s>

<s docid="AP880912-0095" num="7" wdcount="8"> Picks up graf 3 pvs, `Most Jamaicans '...</s>

<s docid="AP880912-0095" num="8" wdcount="10"> DELETES graf 12 pvs, `Storm warnings '... as outdated .</s>
</NOTE>
<BYLINE>

<s docid="AP880912-0095" num="9" wdcount="3"> By LLOYD WILLIAMS</s>
</BYLINE>
<BYLINE>

<s docid="AP880912-0095" num="10" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880912-0095" num="11" wdcount="3"> KINGSTON, Jamaica (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880912-0095" num="12" wdcount="24"> Hurricane Gilbert, packing 110 mph winds and torrential rain, moved over this capital city today after skirting Puerto Rico, Haiti and the Dominican Republic.</s>

<s docid="AP880912-0095" num="13" wdcount="7"> There were no immediate reports of casualties.</s>

<s docid="AP880912-0095" num="14" wdcount="4"> Telephone communications were affected.</s>

<s docid="AP880912-0095" num="15" wdcount="18"> ``Right now it's actually moving over Jamaica,'' said Bob Sheets, director of the National Hurricane Center in Miami.</s>

<s docid="AP880912-0095" num="16" wdcount="12"> ``We've already had reports of 110 mph winds on the eastern tip.</s>

<s docid="AP880912-0095" num="17" wdcount="27"> ``It looks like the eye is going to move lengthwise across that island, and they're going to bear the full brunt of this powerful hurricane,'' Sheets said.</s>

<s docid="AP880912-0095" num="18" wdcount="28"> Forecasters say Gilbert was expected to lash Jamaica throughout the day and was on track to later strike the Cayman Islands, a small British dependency northwest of Jamaica.</s>

<s docid="AP880912-0095" num="19" wdcount="28"> Meanwhile, Havana Radio reported today that 25,000 people were evacuated from Guantanamo Province on Cuba's southeastern coast as strong winds fanning out from Gilbert began brushing the island.</s>

<s docid="AP880912-0095" num="20" wdcount="26"> All Jamaica-bound flights were canceled at Miami International Airport, while flights from Grand Cayman, the main island of the three-island chain, arrived packed with frightened travelers.</s>

<s docid="AP880912-0095" num="21" wdcount="32"> ``People were running around in the main lobby of our hotel (on Grand Cayman) like chickens with their heads cut off,'' said one vacationer who was returning home to California through Miami.</s>

<s docid="AP880912-0095" num="22" wdcount="11"> Hurricane warnings were posted for the Cayman Islands, Cuba and Haiti.</s>

<s docid="AP880912-0095" num="23" wdcount="7"> Warnings were discontinued for the Dominican Republic.</s>

<s docid="AP880912-0095" num="24" wdcount="38"> ``All interests in the Western Caribbean should continue to monitor the progress of this dangerous hurricane,'' the service said, adding, ``Little change in strength is expected for the next several hours as the hurricane moves westward over Jamaica''.</s>

<s docid="AP880912-0095" num="25" wdcount="42"> The Associated Press' Caribbean headquarters in San Juan, Puerto Rico, was unable to get phone calls through to Kingston, where high winds and heavy rain preceding the storm drenched the capital overnight, toppling trees, causing local flooding and littering streets with branches.</s>

<s docid="AP880912-0095" num="26" wdcount="12"> Most Jamaicans stayed home, boarding up windows in preparation for the hurricane.</s>

<s docid="AP880912-0095" num="27" wdcount="12"> Some companies broadcast appeals for technicians and electricians to report to work.</s>

<s docid="AP880912-0095" num="28" wdcount="25"> The weather bureau predicted Gilbert's center, 140 miles southeast of Kingston before dawn, would pass south of Kingston and hit the southern parish of Clarendon.</s>

<s docid="AP880912-0095" num="29" wdcount="19"> Flash flood warnings were issued for the parishes of Portland on the northeast and St. Mary on the north.</s>

<s docid="AP880912-0095" num="30" wdcount="34"> The north coast tourist region from Montego Bay on the west and Ocho Rios on the east, far from the southern impact zone and separated by mountains, was expected only to receive heavy rain.</s>

<s docid="AP880912-0095" num="31" wdcount="16"> Officials urged residents in the higher risk areas along the south coast to seek higher ground.</s>

<s docid="AP880912-0095" num="32" wdcount="25"> ``It's certainly one of the larger systems we've seen in the Caribbean for a long time,'' said Hal Gerrish, forecaster at the National Hurricane Center.</s>

<s docid="AP880912-0095" num="33" wdcount="18"> Forecasters at the center said the eye of Gilbert was 140 miles southeast of Kingston at dawn today.</s>

<s docid="AP880912-0095" num="34" wdcount="25"> Maximum sustained winds were near 110 mph, with tropical-storm force winds extending up to 250 miles to the north and 100 miles to the south.</s>

<s docid="AP880912-0095" num="35" wdcount="43"> Prime Minister Edward Seaga of Jamaica alerted all government agencies, saying Sunday night: ``Hurricane Gilbert appears to be a real threat and everyone should follow the instructions and hurricane precautions issued by the Office of Disaster Preparedness in order to minimize the danger''.</s>

<s docid="AP880912-0095" num="36" wdcount="35"> Forecasters said the hurricane had been gaining strength as it passed over the ocean after it dumped 5 to 10 inches of rain on the Dominican Republic and Haiti, which share the island of Hispaniola.</s>

<s docid="AP880912-0095" num="37" wdcount="27"> ``We should know within about 72 hours whether it's going to be a major threat to the United States,'' said Martin Nelson, another meteorologist at the center.</s>

<s docid="AP880912-0095" num="38" wdcount="21"> ``It's moving at about 17 mph to the west and normally hurricanes take a northward turn after they pass central Cuba''.</s>

<s docid="AP880912-0095" num="39" wdcount="27"> Cuba's official Prensa Latina news agency said a state of alert was declared at midday in the Cuban provinces of Guantanamo, Holguin, Santiago de Cuba and Granma.</s>

<s docid="AP880912-0095" num="40" wdcount="32"> In the report from Havana received in Mexico City, Prensa Latina said civil defense officials were broadcasting bulletins on national radio and television recommending emergency measures and providing information on the storm.</s>

<s docid="AP880912-0095" num="41" wdcount="37"> Heavy rain and stiff winds downed power lines and caused flooding in the Dominican Republic on Sunday night as the hurricane's center passed just south of the Barahona peninsula, then less than 100 miles from neighboring Haiti.</s>

<s docid="AP880912-0095" num="42" wdcount="25"> The storm ripped the roofs off houses and flooded coastal areas of southwestern Puerto Rico after reaching hurricane strength off the island's southeast Saturday night.</s>

<s docid="AP880912-0095" num="43" wdcount="35"> Flights were canceled Sunday in the Dominican Republic, where civil defense director Eugenio Cabral reported some flooding in parts of the capital of Santo Domingo and power outages there and in other southern areas .</s>
</TEXT>
</DOC>
