<DOC>
<DOCNO>

<s docid="AP880916-0060" num="1" wdcount="1"> AP880916-0060</s>
</DOCNO>
<FILEID>

<s docid="AP880916-0060" num="2" wdcount="2"> AP-NR-09-16-88 0410EDT</s>
</FILEID>
<FIRST>

<s docid="AP880916-0060" num="3" wdcount="5"> r a PM-Hurricane-Strength 09-16 0543</s>
</FIRST>
<SECOND>

<s docid="AP880916-0060" num="4" wdcount="1"> PM-Hurricane-Strength,0560</s>
</SECOND>
<HEAD>

<s docid="AP880916-0060" num="5" wdcount="5"> What Makes Gilbert So Strong?</s>
</HEAD>
<HEAD>

<s docid="AP880916-0060" num="6" wdcount="4"> With PM-Hurricane Gilbert, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP880916-0060" num="7" wdcount="3"> By A.J. DICKERSON</s>
</BYLINE>
<BYLINE>

<s docid="AP880916-0060" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880916-0060" num="9" wdcount="2"> MIAMI (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880916-0060" num="10" wdcount="33"> Hurricane Gilbert's growth from a harmless low pressure zone off Africa to a ferocious killer in the Gulf of Mexico was fueled by a combination of heat, moisture and wind that baffles forecasters.</s>

<s docid="AP880916-0060" num="11" wdcount="24"> ``It's a matter of getting everything together in the right place in the right time,'' Gil Clark of the National Hurricane Center said Thursday.</s>

<s docid="AP880916-0060" num="12" wdcount="5"> ``It doesn't happen very often.</s>

<s docid="AP880916-0060" num="13" wdcount="6"> How it develops, we don't know''.</s>

<s docid="AP880916-0060" num="14" wdcount="21"> Gilbert came to the attention of center forecasters Sept. 3 as a dry low pressure trough moving west out of Africa.</s>

<s docid="AP880916-0060" num="15" wdcount="11"> ``We get 50 or 60 of these off Africa every summer.</s>

<s docid="AP880916-0060" num="16" wdcount="7"> About one of six develop,'' said Clark.</s>

<s docid="AP880916-0060" num="17" wdcount="8"> By Sept. 8, the system became a depression.</s>

<s docid="AP880916-0060" num="18" wdcount="11"> It reached tropical storm status by Saturday and a hurricane Sunday.</s>

<s docid="AP880916-0060" num="19" wdcount="10"> A tropical wave becomes a depression when winds start swirling.</s>

<s docid="AP880916-0060" num="20" wdcount="13"> When sustained winds reach 39 mph, the system becomes a named tropical storm.</s>

<s docid="AP880916-0060" num="21" wdcount="10"> It reaches hurricane status when sustained winds hit 74 mph.</s>

<s docid="AP880916-0060" num="22" wdcount="23"> Why Gilbert organized and strengthened while other systems didn't ``is a mystery more or less,'' said University of Miami meteorology Professor Rainer Bleck.</s>

<s docid="AP880916-0060" num="23" wdcount="21"> ``The first part of the summer we were biting our nails, wondering why these (other) disturbances didn't develop,'' he said Thursday.</s>

<s docid="AP880916-0060" num="24" wdcount="9"> ``That's something meteorologists would like to know more about''.</s>

<s docid="AP880916-0060" num="25" wdcount="13"> But the scientists do know what fuels a budding storm once development begins.</s>

<s docid="AP880916-0060" num="26" wdcount="19"> And they know that development is sparked when winds converge, and that growth is affected by time and place.</s>

<s docid="AP880916-0060" num="27" wdcount="33"> ``If that happens in an area where there's plenty of moisture in the lower atmosphere (the bottom 10,000 feet or so), this convergence may lead to upward motion and cloud formation,'' Bleck said.</s>

<s docid="AP880916-0060" num="28" wdcount="18"> ``If clouds form, the heat of condensation in the clouds occasionally provides `positive feedback' to the convergence pattern.</s>

<s docid="AP880916-0060" num="29" wdcount="20"> That strengthens it,'' he said, adding that storms can begin budding only off the equator because of the Earth's rotation.</s>

<s docid="AP880916-0060" num="30" wdcount="5"> Eventually, a vortex is created.</s>

<s docid="AP880916-0060" num="31" wdcount="11"> ``Any time you contract an air mass, they will start spinning.</s>

<s docid="AP880916-0060" num="32" wdcount="13"> That's what makes the tornadoes, hurricanes and blizzards, those winter storms,'' Bleck said.</s>

<s docid="AP880916-0060" num="33" wdcount="7"> Hurricanes ``are useful to the climate machine.</s>

<s docid="AP880916-0060" num="34" wdcount="16"> Their primary role is to transport heat from the lower to the upper atmosphere,'' he said.</s>

<s docid="AP880916-0060" num="35" wdcount="18"> ``The sun puts energy into the water, the top of the oceans and lowest part of the atmosphere.</s>

<s docid="AP880916-0060" num="36" wdcount="14"> That has to be distributed from the bottom to higher levels of the atmosphere''.</s>

<s docid="AP880916-0060" num="37" wdcount="14"> When the depression that would become Gilbert neared Barbados, warm Atlantic waters nurtured it.</s>

<s docid="AP880916-0060" num="38" wdcount="14"> ``This time of year in the northwest Caribbean is best for development,'' Clark said.</s>

<s docid="AP880916-0060" num="39" wdcount="18"> ``If you get a storm in this area in September, when the water's warmest, it can just explode.</s>

<s docid="AP880916-0060" num="40" wdcount="18"> This is where Camille formed and exploded,'' referring to the 1969 storm that slammed into the Gulf Coast.</s>

<s docid="AP880916-0060" num="41" wdcount="7"> ``It is an exciting thing to watch.</s>

<s docid="AP880916-0060" num="42" wdcount="15"> If you're on the beach watching the storm surge, it's a different story,'' he said.</s>

<s docid="AP880916-0060" num="43" wdcount="23"> The hurricane center said Gilbert was the most intense storm on record in terms of barometric pressure, measured at 26.13 inches Tuesday night.</s>

<s docid="AP880916-0060" num="44" wdcount="15"> That broke the 26.35 inches of the 1935 hurricane that devastated the Florida Keys .</s>
</TEXT>
</DOC>
