<DOC>
<DOCNO>

<s docid="AP880915-0003" num="1" wdcount="1"> AP880915-0003</s>
</DOCNO>
<FILEID>

<s docid="AP880915-0003" num="2" wdcount="2"> AP-NR-09-15-88 0004EDT</s>
</FILEID>
<FIRST>

<s docid="AP880915-0003" num="3" wdcount="6"> u i AM-HurricaneGilbert 4thLd-Writethru 09-15 1136</s>
</FIRST>
<SECOND>

<s docid="AP880915-0003" num="4" wdcount="6"> AM-Hurricane Gilbert, 4th Ld - Writethru,a0897,1167</s>
</SECOND>
<HEAD>

<s docid="AP880915-0003" num="5" wdcount="5"> Storms Batter Yucatan; Thousands Flee</s>
</HEAD>
<NOTE>

<s docid="AP880915-0003" num="6" wdcount="24"> Eds: SUBS 6th graf pvs, `Army officials'... with two grafs to UPDATE with total known evacuations on Yucatan; PICKS up 7th pvs: The eye...</s>

<s docid="AP880915-0003" num="7" wdcount="10"> SUBS grafs 17-21 `At 9 p.m EDT ...a Category 4'.</s>

<s docid="AP880915-0003" num="8" wdcount="22"> with seven grafs to UPDATE with new wind speeds, distances, hurricane forming double eye; PICKS up 22nd graf pvs: Only two.. .</s>
</NOTE>
<HEAD>

<s docid="AP880915-0003" num="9" wdcount="4"> LaserGraphic NY36, LaserMap WX14</s>
</HEAD>
<BYLINE>

<s docid="AP880915-0003" num="10" wdcount="3"> By CHRIS ANGELO</s>
</BYLINE>
<BYLINE>

<s docid="AP880915-0003" num="11" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880915-0003" num="12" wdcount="3"> CANCUN, Mexico (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880915-0003" num="13" wdcount="33"> Hurricane Gilbert, one of the strongest storms ever, slammed into the Yucatan Peninsula Wednesday and leveled thatched homes, tore off roofs, uprooted trees and cut off the Caribbean resorts of Cancun and Cozumel.</s>

<s docid="AP880915-0003" num="14" wdcount="14"> Looters roamed the streets of Cancun, stealing from stores whose windows were blown away.</s>

<s docid="AP880915-0003" num="15" wdcount="10"> Huge waves battered the beach resorts and thousands were evacuated.</s>

<s docid="AP880915-0003" num="16" wdcount="17"> Despite the intensity of the onslaught and the ensuing heavy flooding, officials reported only two minor injuries.</s>

<s docid="AP880915-0003" num="17" wdcount="18"> The storm killed 19 people in Jamaica and five in the Dominican Republic before moving west to Mexico.</s>

<s docid="AP880915-0003" num="18" wdcount="24"> Prime Minister Edward Seaga of Jamaica said Wednesday the storm destroyed an estimated 100,000 of Jamaica's 500,000 homes when it throttled the island Monday.</s>

<s docid="AP880915-0003" num="19" wdcount="15"> The Jamaican Embassy reported earlier that 500,000 of the nation's 2.3 million people were homeless.</s>

<s docid="AP880915-0003" num="20" wdcount="32"> In Cancun, amateur radio operators said an oil tanker from the fleet of the government oil monopoly Pemex, the Lazaro Cardenas, had run aground on the beach in the Cancun hotel zone.</s>

<s docid="AP880915-0003" num="21" wdcount="9"> Pemex officials however said all their vessels were secure.</s>

<s docid="AP880915-0003" num="22" wdcount="23"> Army officials in Mexico City said about 35,000 people were evacuated from Cancun, but Cancun Mayor Jose Sanchez Zapata said about 11,000 fled.</s>

<s docid="AP880915-0003" num="23" wdcount="16"> More than 120,000 people on the northeast Yucatan coast were evacuated, the Yucatan state government said.</s>

<s docid="AP880915-0003" num="24" wdcount="22"> The eye of the storm passed over Cozumel and Cancun with howling winds clocked at 160 mph at about 8 a.m. EDT.</s>

<s docid="AP880915-0003" num="25" wdcount="11"> The winds bent and toppled utility poles and uprooted slum dwellings.</s>

<s docid="AP880915-0003" num="26" wdcount="23"> Ham radio operators around Cancun said Gilbert knocked down a radio and television communications tower, uprooted trees and blew the roofs off buildings.</s>

<s docid="AP880915-0003" num="27" wdcount="21"> Floods prevented officials from reaching the hotel zone in Cancun and there were no relief efforts under way by late Wednesday.</s>

<s docid="AP880915-0003" num="28" wdcount="13"> Shelters had little or no food, water or blankets and power was out.</s>

<s docid="AP880915-0003" num="29" wdcount="5"> ``We can't do it yet.</s>

<s docid="AP880915-0003" num="30" wdcount="19"> The wind would blow them away,'' said an army official at city hall who declined to give his name.</s>

<s docid="AP880915-0003" num="31" wdcount="28"> Bands of 25-30 youths roamed the streets of Cancun Wednesday, looting stores with shattered windows, said Alfredo Moro Sanchez, investigative coordinator of the Quintana Roo state judicial police.</s>

<s docid="AP880915-0003" num="32" wdcount="18"> He said he asked for army troops to halt the looting but none had arrived by late Wednesday.</s>

<s docid="AP880915-0003" num="33" wdcount="10"> About 150 tourists took refuge at the Cancun city hall.</s>

<s docid="AP880915-0003" num="34" wdcount="20"> Honeymooner Sheila Fournier of Long Island said she and her husband, Pete, had been evacuated from the Villas Playa Hotel.</s>

<s docid="AP880915-0003" num="35" wdcount="13"> ``It had an ocean-front view _ which is now washed away,'' she said.</s>

<s docid="AP880915-0003" num="36" wdcount="10"> Officials were checking low-lying areas of Cancun for stranded residents.</s>

<s docid="AP880915-0003" num="37" wdcount="16"> There was heavy damage visible to the humble wood and thatch homes typical of the Yucatan.</s>

<s docid="AP880915-0003" num="38" wdcount="15"> ``There were some people who did not want to leave yesterday,'' the army official said.</s>

<s docid="AP880915-0003" num="39" wdcount="4"> ``It was something new.</s>

<s docid="AP880915-0003" num="40" wdcount="7"> They didn't know what a cyclone was''.</s>

<s docid="AP880915-0003" num="41" wdcount="38"> At midnight EDT Gilbert was centered near latitude 21.5 north, longitude 90.2 west and approaching the north coast of Yucatan, about 60 miles east-northeast of the provincial capital, Merida, the National Hurricane Center in Coral Gables, Fla., said.</s>

<s docid="AP880915-0003" num="42" wdcount="16"> The storm was about 550 miles southeast of Brownsville, Texas, the center said in a statement.</s>

<s docid="AP880915-0003" num="43" wdcount="14"> Gilbert was moving west-northwest at 15 mph and winds had decreased to 125 mph.</s>

<s docid="AP880915-0003" num="44" wdcount="21"> The Mexican National Weather Service reported winds gusting as high as 218 mph earlier Wednesday with sustained winds of 179 mph.</s>

<s docid="AP880915-0003" num="45" wdcount="17"> Earlier Wednesday Gilbert was classified as a Category 5 storm, the strongest ad deadliest type of hurricane.</s>

<s docid="AP880915-0003" num="46" wdcount="15"> Such storms have maximum sustained winds greater than 155 mph and can cause catastrophic damage.</s>

<s docid="AP880915-0003" num="47" wdcount="37"> By Wednesday night the National Hurricane Center downgraded it to a Category 4, but center director Bob Sheets said:``There's no question it'll strengthen again once it comes off the Yucatan Peninsula and gets back in open water''.</s>

<s docid="AP880915-0003" num="48" wdcount="38"> As Gilbert moved away from the Yucatan Peninsula Wednesday night, the hurricane formed a double eye, two concentric circles of thunderstorms often characteristic of a strong storm that has crossed land and is moving over the water again.</s>

<s docid="AP880915-0003" num="49" wdcount="20"> One eye was about eight miles wide, and the second about 25 miles wide, said hurricane center meteorologist Jesse Moore.</s>

<s docid="AP880915-0003" num="50" wdcount="26"> ``This is one of the features that we expected to see as the hurricane moved back over the water, and we do expect intensification,'' he said.</s>

<s docid="AP880915-0003" num="51" wdcount="33"> Only two Category 5 hurricanes have hit the United States _ the 1935 storm that killed 408 people in Florida and Hurricane Camille that devastated the Mississippi coast in 1969, killing 256 people.</s>

<s docid="AP880915-0003" num="52" wdcount="13"> Oil companies evacuated thousands of workers from rigs in the Gulf of Mexico.</s>

<s docid="AP880915-0003" num="53" wdcount="25"> The peninsula ports of Campeche, Celestum, Progreso, Sinzal, Ucaltepen, Tel-Chac, Cancun, Puerto Morelos, and Ciudad del Carmen were closed, the government news agency Notimex said.</s>

<s docid="AP880915-0003" num="54" wdcount="6"> Airports in the region were closed.</s>

<s docid="AP880915-0003" num="55" wdcount="20"> ``The sound of the wind outside is horrible,'' said receptionist Pablo Torres at Cancun's Hotel Carrillos as the storm approached.</s>

<s docid="AP880915-0003" num="56" wdcount="30"> The National Hurricane Center said a hurricane watch was in effect on the Texas coast from Brownsville to Port Arthur and along the coast of northeast Mexico from Tampico north.</s>

<s docid="AP880915-0003" num="57" wdcount="22"> In Mexico City, the National Civil Defense System said it lost telephone contact with Cancun and Cozumel at about 8 a.m. EDT.</s>

<s docid="AP880915-0003" num="58" wdcount="25"> Public buildings in Cancun were used as shelters, said Cecila Lavalle, a spokesman for Quintana Roo state government in Chetumal, 155 miles southeast of Cozumel.</s>

<s docid="AP880915-0003" num="59" wdcount="28"> Jennie Valdez, a U.S. consular representative in Cancun, said she did not know how many tourists were in Cancun, but government figures estimate 40,000 to 65,000 monthly visitors.</s>

<s docid="AP880915-0003" num="60" wdcount="15"> Hurricane warnings were in effect for the entire Yucatan Peninsula and widespread evacuations were reported.</s>

<s docid="AP880915-0003" num="61" wdcount="29"> Winds destroyed at least 100 homes in slums of Valladolid, a town of about 45,000 about 100 miles from Cozumel, Alberto Pol, a judicial police officer, said by telephone.</s>

<s docid="AP880915-0003" num="62" wdcount="18"> The National Hurricane Center said Gilbert was the most intense storm on record in terms of barometric pressure.</s>

<s docid="AP880915-0003" num="63" wdcount="20"> It was measured at 26.31 inches, breaking the 26.35 inches recorded for the 1935 hurricane that devastated the Florida Keys.</s>

<s docid="AP880915-0003" num="64" wdcount="14"> ``That's the lowest pressure ever measured in the Western Hemisphere,'' said forecaster Mark Zimmer.</s>

<s docid="AP880915-0003" num="65" wdcount="15"> On Sunday, Monday and Tuesday, Gilbert pounded the Dominican Republic, Jamaica and the Cayman Islands.</s>

<s docid="AP880915-0003" num="66" wdcount="9"> Seaga said Jamaica would need $8 billion in aid.</s>

<s docid="AP880915-0003" num="67" wdcount="13"> Officials in the Dominican Republic, sideswiped Sunday by the storm, reported five dead.</s>

<s docid="AP880915-0003" num="68" wdcount="12"> Gilbert also buffeted the Cayman Islands, but no deaths were reported .</s>
</TEXT>
</DOC>
