<DOC>
<DOCNO>

<s docid="WSJ880912-0064" num="1" wdcount="1"> WSJ880912-0064</s>
</DOCNO>
<HL>

<s docid="WSJ880912-0064" num="2" wdcount="9"> Hurricane Gilbert Heading for Jamaica With 100 MPH Winds</s>
</HL>
<SO>
</SO>
<CO>

<s docid="WSJ880912-0064" num="3" wdcount="1"> LATAM</s>
</CO>
<DATELINE>

<s docid="WSJ880912-0064" num="4" wdcount="5"> SANTO DOMINGO, Dominican Republic (AP)</s>
</DATELINE>
<TEXT>

<s docid="WSJ880912-0064" num="5" wdcount="26"> Hurricane Gilbert swept toward Jamaica yesterday with 100-mile-an-hour winds, and officials issued warnings to residents on the southern coasts of the Dominican Republic, Haiti and Cuba.</s>

<s docid="WSJ880912-0064" num="6" wdcount="14"> The storm ripped the roofs off houses and caused coastal flooding in Puerto Rico.</s>

<s docid="WSJ880912-0064" num="7" wdcount="18"> In the Dominican Republic, all domestic flights and flights to and from Puerto Rico and Miami were canceled.</s>

<s docid="WSJ880912-0064" num="8" wdcount="38"> Forecasters said the hurricane was gaining strength as it passed over the ocean and would dump heavy rain on the Dominican Republic and Haiti as it moved south of Hispaniola, the Caribbean island they share, and headed west.</s>

<s docid="WSJ880912-0064" num="9" wdcount="4"> "It's still gaining strength.</s>

<s docid="WSJ880912-0064" num="10" wdcount="29"> It's certainly one of the larger systems we've seen in the Caribbean for a long time," said Hal Gerrish, forecaster at the National Hurricane Center in Coral Gables, Fla.</s>

<s docid="WSJ880912-0064" num="11" wdcount="25"> At 3 p.m. EDT, the center of the hurricane was about 100 miles south of the Dominican Republic and 425 miles east of Kingston, Jamaica.</s>

<s docid="WSJ880912-0064" num="12" wdcount="21"> The hurricane was moving west at about 15 mph and was expected to continue this motion for the next 24 hours.</s>

<s docid="WSJ880912-0064" num="13" wdcount="15"> Forecasters said the hurricane's track would take it about 50 miles south of southwestern Haiti.</s>

<s docid="WSJ880912-0064" num="14" wdcount="20"> The hurricane center said small craft in the Virgin Islands and Puerto Rico should remain in port until conditions improve.</s>

<s docid="WSJ880912-0064" num="15" wdcount="26"> The forecasters said the Dominican Republic would get as much as 10 inches of rain yesterday, with similar amounts falling in Haiti last night and tonight.</s>

<s docid="WSJ880912-0064" num="16" wdcount="16"> Hurricane warnings were issued for the south coast of Haiti and Cuba by their respective governments.</s>

<s docid="WSJ880912-0064" num="17" wdcount="12"> In Jamaica, the government issued a hurricane watch for the entire island.</s>

<s docid="WSJ880912-0064" num="18" wdcount="15"> Tropical Storm Gilbert formed in the eastern Caribbean and strengthened into a hurricane Saturday night.</s>

<s docid="WSJ880912-0064" num="19" wdcount="30"> In Puerto Rico, besides tearing off several roofs, the storm caused coastal flooding and brought down power lines and trees along roads and highways in the west and southwestern regions.</s>

<s docid="WSJ880912-0064" num="20" wdcount="23"> Three people were injured in Guayanilla, Puerto Rico, when a tree fell on their vehicle as they traveled along Route 97, police reported.</s>

<s docid="WSJ880912-0064" num="21" wdcount="22"> Four policemen stationed on Mona Island, between Puerto Rico and the Dominican Republic, were stranded as a result of the weather .</s>
</TEXT>
</DOC>
