<DOC>
<DOCNO>

<s docid="AP880622-0184" num="1" wdcount="1"> AP880622-0184</s>
</DOCNO>
<FILEID>

<s docid="AP880622-0184" num="2" wdcount="2"> AP-NR-06-22-88 2103EST</s>
</FILEID>
<FIRST>

<s docid="AP880622-0184" num="3" wdcount="5"> r a AM-People-Bernstein 06-22 0211</s>
</FIRST>
<SECOND>

<s docid="AP880622-0184" num="4" wdcount="1"> AM-People-Bernstein,0216</s>
</SECOND>
<HEAD>

<s docid="AP880622-0184" num="5" wdcount="9"> Stars Will Perform at Birthday Bash Honoring Leonard Bernstein</s>
</HEAD>
<DATELINE>

<s docid="AP880622-0184" num="6" wdcount="3"> LENOX, Mass. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880622-0184" num="7" wdcount="30"> Beverly Sills, Lauren Bacall, Betty Comden and Phyllis Newman are among performers who will sing, act and make guest appearances at a birthday bash in August for conductor Leonard Bernstein.</s>

<s docid="AP880622-0184" num="8" wdcount="32"> The Leonard Bernstein Gala Birthday Performance is a benefit concert scheduled for the composer's 70th birthday, Aug. 25, to raise money for the Tanglewood Music Center, where Bernstein got his conducting start.</s>

<s docid="AP880622-0184" num="9" wdcount="4"> Sills will be host.</s>

<s docid="AP880622-0184" num="10" wdcount="32"> Performances will include the Boston Symphony Orchestra, the Boston Pops Orchestra and the Tanglewood Festival Chorus under the direction of some of the many conductors whose careers have been guided by Bernstein.</s>

<s docid="AP880622-0184" num="11" wdcount="15"> Bacall and soprano Barbara Hendricks will perform a movement from Bernstein's Symphony No. 3, ``Kaddish''.</s>

<s docid="AP880622-0184" num="12" wdcount="10"> Violin soloist Midori will play two movements from his ``Serenade''.</s>

<s docid="AP880622-0184" num="13" wdcount="20"> The concert will celebrate Bernstein's accomplishments in popular music with excerpts from ``West Side Story,'' ``On the Town'' and others.</s>

<s docid="AP880622-0184" num="14" wdcount="27"> Dame Gwyneth Jones and Frederica von Stade will be among those performing highlights from ``Fidelio,'' ``Tristan und Isolde'' and other works to honor Bernstein's landmark opera recordings.</s>

<s docid="AP880622-0184" num="15" wdcount="26"> Tickets start at $20 for a spot on the lawn and run up to $5,000 for benefactors, who get a seat in the open-air auditorium .</s>
</TEXT>
</DOC>
