<DOC>
<DOCNO>

<s docid="AP881115-0011" num="1" wdcount="1"> AP881115-0011</s>
</DOCNO>
<FILEID>

<s docid="AP881115-0011" num="2" wdcount="2"> AP-NR-11-15-88 0129EST</s>
</FILEID>
<FIRST>

<s docid="AP881115-0011" num="3" wdcount="5"> r a BC-Bernstein 11-15 0424</s>
</FIRST>
<SECOND>

<s docid="AP881115-0011" num="4" wdcount="1"> BC-Bernstein,0445</s>
</SECOND>
<HEAD>

<s docid="AP881115-0011" num="5" wdcount="5"> Bernstein Celebrates 45th Conducting Anniversary</s>
</HEAD>
<NOTE>

<s docid="AP881115-0011" num="6" wdcount="4"> Eds: No PMs planned</s>
</NOTE>
<BYLINE>

<s docid="AP881115-0011" num="7" wdcount="3"> By MARY CAMPBELL</s>
</BYLINE>
<BYLINE>

<s docid="AP881115-0011" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP881115-0011" num="9" wdcount="3"> NEW YORK (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP881115-0011" num="10" wdcount="36"> Leonard Bernstein, whose 70th birthday in August was marked with a gala at Tanglewood, returned to Carnegie Hall with the New York Philharmonic 45 years after he made his triumphant conducting debut there with the orchestra.</s>

<s docid="AP881115-0011" num="11" wdcount="16"> And of course, Monday night's program consisted of three Bernstein compositions that were played shimmeringly well.</s>

<s docid="AP881115-0011" num="12" wdcount="13"> As well it should: It was the 1,215th time Bernstein conducted the orchestra.</s>

<s docid="AP881115-0011" num="13" wdcount="23"> On Nov. 14, 1943, Bernstein, the Philharmonic's then-assistant conductor, filled for an ailing Bruno Walter on such short notice there was no rehearsal.</s>

<s docid="AP881115-0011" num="14" wdcount="7"> The concert was broadcast nationally on radio.</s>

<s docid="AP881115-0011" num="15" wdcount="25"> And there was such acclaim that Bernstein, who had never led the orchestra in concert until that day, was catapulted to fame, at age 25.</s>

<s docid="AP881115-0011" num="16" wdcount="26"> At intermission, Mrs. Artur Rodzinski, whose late husband was the Philharmonic music's director in 1943 and hired Bernstein as his assistant, was introduced from a box.</s>

<s docid="AP881115-0011" num="17" wdcount="20"> Violinist Jacques Margolies, who played in the Philharmonic that Sunday, is still a member and was playing on Monday night.</s>

<s docid="AP881115-0011" num="18" wdcount="39"> Eight others who also were members in 1943 _ violinist Louis Fishzohn, oboist Albert Goltzer, timpanist Saul Goodman, bassist Homer Mensch, cellist Martin Ormandy, assistant concertmaster Michael Rosenker, and trumpeters James Smith and William Vacchiano _ went on stage.</s>

<s docid="AP881115-0011" num="19" wdcount="7"> Bernstein gave bear hugs to all nine.</s>

<s docid="AP881115-0011" num="20" wdcount="9"> ``I feel older than all of them,'' said Bernstein.</s>

<s docid="AP881115-0011" num="21" wdcount="41"> Bernstein was given a silver box engraved with a reproduction of Monday evening's program cover _ a caricature of him, with jutting chin, bright eye, flowing hair and baton, and reading ``with love and thanks of the Philharmonic family to Lennie''.</s>

<s docid="AP881115-0011" num="22" wdcount="9"> ``Will this birthday never end?,'' he told the audience.</s>

<s docid="AP881115-0011" num="23" wdcount="13"> Monday's concert began with Bernstein's ``Chichester Psalms,'' with the splendid Westminster Symphonic Choir.</s>

<s docid="AP881115-0011" num="24" wdcount="19"> Todd Caruso, a member of the American Boychoir whose voice is high, pure and moving, sang the solo part.</s>

<s docid="AP881115-0011" num="25" wdcount="26"> Violinist Gidon Kremer, a native of the Latvian town of Riga in the Soviet Union, was soloist in ``Serenade for Violin, String Orchestra, Harp and Percussion''.</s>

<s docid="AP881115-0011" num="26" wdcount="9"> Kremer's sound isn't warm but his technique is breathtaking.</s>

<s docid="AP881115-0011" num="27" wdcount="15"> Pianist Krystian Zimerman, who was born in Zabrze, Poland, often performs with Bernstein in Europe.</s>

<s docid="AP881115-0011" num="28" wdcount="32"> He was the respectful and thoroughly engaged soloist in the final work on the program, Bernstein's ``Symphony No. 2 for Piano and Orchestra,'' subtitled ``The Age of Anxiety'' after W.H. Auden's poem.</s>

<s docid="AP881115-0011" num="29" wdcount="18"> All the performers donated their services, with proceeds benefiting the Philharmonic's efforts on behalf of American conductors .</s>
</TEXT>
</DOC>
