<DOC>
<DOCNO>

<s docid="AP880720-0262" num="1" wdcount="1"> AP880720-0262</s>
</DOCNO>
<FILEID>

<s docid="AP880720-0262" num="2" wdcount="2"> AP-NR-07-20-88 1027EDT</s>
</FILEID>
<FIRST>

<s docid="AP880720-0262" num="3" wdcount="6"> a e PM-APArts:Tanglewood Adv26 07-20 0703</s>
</FIRST>
<SECOND>

<s docid="AP880720-0262" num="4" wdcount="5"> PM-AP Arts: Tanglewood, Adv 26,0723</s>
</SECOND>
<NOTE>

<s docid="AP880720-0262" num="5" wdcount="2"> $Adv 26</s>
</NOTE>
<NOTE>

<s docid="AP880720-0262" num="6" wdcount="8"> For Release Tues PMs, July 26 and Thereafter</s>
</NOTE>
<BYLINE>

<s docid="AP880720-0262" num="7" wdcount="3"> By CAROLYN LUMSDEN</s>
</BYLINE>
<BYLINE>

<s docid="AP880720-0262" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880720-0262" num="9" wdcount="3"> LENOX, Mass. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880720-0262" num="10" wdcount="32"> Actresses Lauren Bacall, Betty Comden and Phyllis Newman are among performers in the birthday bash being thrown in August for conductor Leonard Bernstein at the music center where he got his start.</s>

<s docid="AP880720-0262" num="11" wdcount="39"> The Tanglewood Music Center also is celebrating the 50th anniversary of its Music Shed this summer with a special concert by the resident Boston Symphony Orchestra featuring the same music, Beethoven's Ninth Symphony, that inaugurated the building in 1938.</s>

<s docid="AP880720-0262" num="12" wdcount="30"> The Bernstein weekend alone, with tickets as high as $5,000 each, may bring in more than $1 million for the festival's endowment fund, according to Caroline Smedvig of the symphony.</s>

<s docid="AP880720-0262" num="13" wdcount="28"> ``Because Tanglewood is so special for him and, conversely, he's so special to us, the combination will produce what we hope will be a unique event,'' she said.</s>

<s docid="AP880720-0262" num="14" wdcount="25"> The Leonard Bernstein Gala Birthday Performance is a four-day affair beginning on the composer's 70th birthday, Aug. 25, to raise money for the music center.</s>

<s docid="AP880720-0262" num="15" wdcount="27"> Beverly Sills, who announced last month that she will step down as general director of the New York City Opera, will be the host of the event.</s>

<s docid="AP880720-0262" num="16" wdcount="15"> Bacall and soprano Barbara Hendricks will perform a movement from Bernstein's Symphony No. 3, ``Kaddish''.</s>

<s docid="AP880720-0262" num="17" wdcount="10"> Violin soloist Midori will play two movements from his ``Serenade''.</s>

<s docid="AP880720-0262" num="18" wdcount="24"> Dame Gwyneth Jones and Frederica von Stade will be among those performing highlights from ``Fidelio'' and other works to honor Bernstein's landmark opera recordings.</s>

<s docid="AP880720-0262" num="19" wdcount="23"> The concert will also celebrate Bernstein's accomplishments in popular music with excerpts from such works as ``West Side Story'' and ``On the Town''.</s>

<s docid="AP880720-0262" num="20" wdcount="20"> The orchestra opened the nine-week season with the special July 1 concert marking the first half-century of the Music Shed.</s>

<s docid="AP880720-0262" num="21" wdcount="27"> The season of classical music will be expanded with performances by such popular rock, jazz and folk artists as The Beach Boys, George Benson and Leo Kottke.</s>

<s docid="AP880720-0262" num="22" wdcount="13"> But the highlight of the new season is the celebration of Bernstein's birthday.</s>

<s docid="AP880720-0262" num="23" wdcount="28"> The BSO is even billing the birthday party as ``one of the music world's great occasions'' and is negotiating the television rights in the United States and Europe.</s>

<s docid="AP880720-0262" num="24" wdcount="34"> Among the conductor's friends who have been invited to the bash are pop star Michael Jackson and British Princess Diana, although Tanglewood officials say the have not yet received an answer from the celebrities.</s>

<s docid="AP880720-0262" num="25" wdcount="23"> Bernstein was a member of the original Tanglewood Music Center class of 1940, where he became a protege of Tanglewood founder Serge Koussevitzky.</s>

<s docid="AP880720-0262" num="26" wdcount="34"> When Koussevitzky retired in 1949, he tried to have the young Bernstein named as his successor, but the BSO's trustees chose Charles Munch because they considered Bernstein too young and tainted by popular music.</s>

<s docid="AP880720-0262" num="27" wdcount="19"> He later wrote the score for the musical ``West Side Story'' and returned every summer to conduct and teach.</s>

<s docid="AP880720-0262" num="28" wdcount="26"> Conductors Seiji Ozawa, John Williams, John Mauceri and Michael Tillson Thomas will share the poduim featuring some of his works on the night of his birth.</s>

<s docid="AP880720-0262" num="29" wdcount="25"> The following night, Ozawa and special guests will appear in a Music Shed concert for a performance intended to show Bernstein's influence on other musicians.</s>

<s docid="AP880720-0262" num="30" wdcount="23"> Aug. 27 will be given over to a performance of Bernstein's ``Mass'' by a 250-member troupe from the Indiana University school of music.</s>

<s docid="AP880720-0262" num="31" wdcount="26"> The four-day celebration concludes with Bernstein conducting the annual Serge and Ola Koussevitzky Memorial Concert, including a performance of Tchaikovsky's Symphony No. 5, on Aug. 28.</s>

<s docid="AP880720-0262" num="32" wdcount="19"> All proceeds go to the music center's endowment fund, and to a fund Bernstein established for aspiring young conductors.</s>

<s docid="AP880720-0262" num="33" wdcount="22"> Ticket prices start at $20 for a space on the lawn and go up to $5,000 for front row seats for benefactors.</s>

<s docid="AP880720-0262" num="34" wdcount="47"> Other highlights of the new season include several major debuts, including that of Soviet painist Vladimir Feltsman, who arrived in the United States last August after an an eight-year battle to emigrate; a return visit by the Israel Philharmonic; and a recital by Irish flutist James Galway.</s>

<s docid="AP880720-0262" num="35" wdcount="14"> This summer is the second in a four-year jubilee of the festival's 50th anniversary.</s>

<s docid="AP880720-0262" num="36" wdcount="18"> Events climax in 1990 with observances marking the 50th year of the music center, the festival's school .</s>
</TEXT>
<NOTE>

<s docid="AP880720-0262" num="37" wdcount="6"> End Adv PM Tues July 26</s>
</NOTE>
</DOC>
