<DOC>
<DOCNO>

<s docid="AP900716-0007" num="1" wdcount="1"> AP900716-0007</s>
</DOCNO>
<FILEID>

<s docid="AP900716-0007" num="2" wdcount="2"> AP-NR-07-16-90 0027EDT</s>
</FILEID>
<FIRST>

<s docid="AP900716-0007" num="3" wdcount="5"> r i PM-LeonardBernstein 07-16 0328</s>
</FIRST>
<SECOND>

<s docid="AP900716-0007" num="4" wdcount="2"> PM-Leonard Bernstein,0336</s>
</SECOND>
<HEAD>

<s docid="AP900716-0007" num="5" wdcount="6"> 71-Year-Old Conductor Cancels Performances, Cites Exhaustion</s>
</HEAD>
<DATELINE>

<s docid="AP900716-0007" num="6" wdcount="2"> TOKYO (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900716-0007" num="7" wdcount="28"> Conductor Leonard Bernstein has canceled several performances in Japan due to exhaustion and lingering illness and will return to the United States to recover, his manager announced today.</s>

<s docid="AP900716-0007" num="8" wdcount="28"> ``Leonard Bernstein is suffering from exhaustion as a result of trying to fulfill his professional obligations while not having fully recovered from several ailments he suffered this spring.</s>

<s docid="AP900716-0007" num="9" wdcount="28"> Complete rest for an extended period is required if this remarkable man is to regain his usual high energy level,'' said Dr. Kevin Cahill, the conductor's personal physician.</s>

<s docid="AP900716-0007" num="10" wdcount="27"> Bernstein, 71, has suffered from severe influenza, pleurisy, and pneumonia since the beginning of the year, Cahill said in a statement released by Harry Kraut, Bernstein's manager.</s>

<s docid="AP900716-0007" num="11" wdcount="20"> Dr. Angelo Aquista, an associate of Cahill, flew to Japan to accompany the conductor back to New York, it said.</s>

<s docid="AP900716-0007" num="12" wdcount="11"> Kraut did not provide the time or date of Bernstein's departure.</s>

<s docid="AP900716-0007" num="13" wdcount="22"> Bernstein had been scheduled to conduct the London Symphony Orchestra in four performances in Japan, ending with a concert on July 22.</s>

<s docid="AP900716-0007" num="14" wdcount="33"> Bernstein issued a separate statement apologizing to his fans and sponsors and saying that he had asked LSO principal conductor Michael Tilson Thomas and Japanese conductor Eiji Oue to fulfill his conducting responsibilities.</s>

<s docid="AP900716-0007" num="15" wdcount="35"> On Saturday and Sunday, Bernstein canceled appearances with an orchestra of young musicians from the Pacific-Asia region who had been training under principals of the LSO during the three-week Pacific Music Festival in northern Japan.</s>

<s docid="AP900716-0007" num="16" wdcount="6"> Bernstein inaugurated the festival last month.</s>

<s docid="AP900716-0007" num="17" wdcount="23"> He started the event along the lines of the Tanglewood music festival in Massachusetts, where young musicians train with the Boston Symphony Orchestra.</s>

<s docid="AP900716-0007" num="18" wdcount="21"> The Japan festival is believed to be the first festival in Asia where young musicians can train with a professional orchestra.</s>

<s docid="AP900716-0007" num="19" wdcount="34"> Kraut's statement said it was not known whether Bernstein would be able to conduct next month at the Tanglewood festival or during the Tanglewood Music Center Orchestra Tour in Europe later this summer .</s>
</TEXT>
</DOC>
