<DOC>
<DOCNO>

<s docid="AP901019-0072" num="1" wdcount="1"> AP901019-0072</s>
</DOCNO>
<FILEID>

<s docid="AP901019-0072" num="2" wdcount="2"> AP-NY-10-19-90 0855EDT</s>
</FILEID>
<FIRST>

<s docid="AP901019-0072" num="3" wdcount="6"> r e BC-Bernstein-Philharmoni 2ndLd-Writethru 10-19 0521</s>
</FIRST>
<SECOND>

<s docid="AP901019-0072" num="4" wdcount="6"> BC-Bernstein-Philharmonic, 2nd Ld - Writethru, a0475,0606</s>
</SECOND>
<HEAD>

<s docid="AP901019-0072" num="5" wdcount="8"> Bernstein's Philharmonic Lets His Music Speak for Them</s>
</HEAD>
<NOTE>

<s docid="AP901019-0072" num="6" wdcount="8"> Eds: Fixes typo in Philharmonic in 1st graf</s>
</NOTE>
<BYLINE>

<s docid="AP901019-0072" num="7" wdcount="3"> By MARTIN STEINBERG</s>
</BYLINE>
<BYLINE>

<s docid="AP901019-0072" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP901019-0072" num="9" wdcount="3"> NEW YORK (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP901019-0072" num="10" wdcount="16"> For the New York Philharmonic, it was supposed to be a night of Beethoven and Shostakovich.</s>

<s docid="AP901019-0072" num="11" wdcount="9"> The fates made it a night of Leonard Bernstein.</s>

<s docid="AP901019-0072" num="12" wdcount="11"> The official catalog of his works says Bernstein led 74 orchestras.</s>

<s docid="AP901019-0072" num="13" wdcount="29"> But this was HIS orchestra, and the musicians came to pay tribute to THEIR laureate conductor, who led them through 1,244 concerts during his 47-year association with the Philharmonic.</s>

<s docid="AP901019-0072" num="14" wdcount="7"> They let his music do the talking.</s>

<s docid="AP901019-0072" num="15" wdcount="39"> ``Tonight's concert is not an evening in which we want to dwell on the passing of a giant, but rather what he has left us,'' guest conductor Leonard Slatkin told the audience at Avery Fisher Hall on Thursday night.</s>

<s docid="AP901019-0072" num="16" wdcount="37"> So four nights after Bernstein's death at age 72, Beethoven's ``Violin Concerto'' became Bernstein's ``Serenade for Solo Violin, String Orchestra, Harp and Percussion'' (1954); Shostakovich's ``Symphony No. 4'' became Bernstein's ``Symphony No. 1 (Jeremiah),'' written in 1942.</s>

<s docid="AP901019-0072" num="17" wdcount="13"> Also added were his ``Chichester Psalms'' (1965) and his overture to ``Candide'' (1956).</s>

<s docid="AP901019-0072" num="18" wdcount="12"> The substitute Bernstein program was being repeated Friday night, Saturday and Tuesday.</s>

<s docid="AP901019-0072" num="19" wdcount="5"> It was an extraordinary concert.</s>

<s docid="AP901019-0072" num="20" wdcount="10"> There weren't many smiling faces among the audience or musicians.</s>

<s docid="AP901019-0072" num="21" wdcount="14"> Slatkin's brief introductory comments, followed by the whimsical ``Candide,'' broke some of the tension.</s>

<s docid="AP901019-0072" num="22" wdcount="18"> Then came the eclectic ``Serenade,'' which Bernstein's program notes says is supposed to be based on Plato's ``Symposium''.</s>

<s docid="AP901019-0072" num="23" wdcount="13"> It begins with a lyrical praise of the Eros, the god of love.</s>

<s docid="AP901019-0072" num="24" wdcount="12"> The piece is sometimes jocular, sometimes melancholy, sometimes assaulting and sometimes hedonistic.</s>

<s docid="AP901019-0072" num="25" wdcount="27"> It ends in drunken revelry, an intrusion of jazz - as if Bernstein was looking down from heaven and telling the audience, ``It's O.K. to smile tonight''.</s>

<s docid="AP901019-0072" num="26" wdcount="25"> The soloist - concertmaster Glenn Dicterow - played with much agility, especially through the difficult double stops and especially considering the lack of preparation time.</s>

<s docid="AP901019-0072" num="27" wdcount="9"> The mourning returned after intermission, but not without optimism.</s>

<s docid="AP901019-0072" num="28" wdcount="24"> ``Jeremiah'' begins with suspenseful strings, followed by a cantorial French horn, a melodic return to the strings and then a prophetic blaring of brass.</s>

<s docid="AP901019-0072" num="29" wdcount="21"> The second movement continues the point-counterpoint of brass versus strings (Jeremiah versus the corrupt priests, with Nebuchadnezzar looming on the horizon).</s>

<s docid="AP901019-0072" num="30" wdcount="11"> In the third movement, Jerusalem has fallen to the Babylonian king.</s>

<s docid="AP901019-0072" num="31" wdcount="3"> Judea is exiled.</s>

<s docid="AP901019-0072" num="32" wdcount="2"> Jeremiah weeps.</s>

<s docid="AP901019-0072" num="33" wdcount="19"> ``How she sits desolate - ``The city once so full of people - ``She is become as a widow''.</s>

<s docid="AP901019-0072" num="34" wdcount="18"> During her chanting of the prophet's ``Lamentations,'' mezzo-soprano Wendy White had to wipe a tear from her eye.</s>

<s docid="AP901019-0072" num="35" wdcount="6"> S did members of the audience.</s>

<s docid="AP901019-0072" num="36" wdcount="10"> Last on the program was another Hebraic elegy, ``Chichester Psalms''.</s>

<s docid="AP901019-0072" num="37" wdcount="12"> The New York Choral Artists and a boy soloist joined the orchestra.</s>

<s docid="AP901019-0072" num="38" wdcount="9"> Two harpists dominated the center of the crowded stage.</s>

<s docid="AP901019-0072" num="39" wdcount="9"> ``Awake, psaltery and harp''! the choir begins in Hebrew.</s>

<s docid="AP901019-0072" num="40" wdcount="5"> ``I will rouse the dawn''.</s>

<s docid="AP901019-0072" num="41" wdcount="23"> In the second movement an angelic 8th-grader, Evan Weber, sings King David's 23rd Psalm, ``The Lord is my shepherd, I shall not want''.</s>

<s docid="AP901019-0072" num="42" wdcount="12"> After he finishes, the men's chorus bellows: ``Why do the nations rage''?</s>

<s docid="AP901019-0072" num="43" wdcount="33"> The piece, however, ends in a Mahlerian motif and chorus declaring a message Bernstein had sought for society: ``Behold how good, ``And how pleasant it is, ``For brethren to dwell ``Together in unity''.</s>

<s docid="AP901019-0072" num="44" wdcount="18"> To emphasize the point after the final note, Slatkin suspended his hands for several long moments of silence.</s>

<s docid="AP901019-0072" num="45" wdcount="6"> Then came the cascade of applause.</s>

<s docid="AP901019-0072" num="46" wdcount="4"> For Leonard Bernstein .</s>
</TEXT>
</DOC>
