<DOC>
<DOCNO>

<s docid="AP901010-0030" num="1" wdcount="1"> AP901010-0030</s>
</DOCNO>
<FILEID>

<s docid="AP901010-0030" num="2" wdcount="2"> AP-NY-10-10-90 0251EDT</s>
</FILEID>
<FIRST>

<s docid="AP901010-0030" num="3" wdcount="5"> r a PM-LeonardBernstein 10-10 0451</s>
</FIRST>
<SECOND>

<s docid="AP901010-0030" num="4" wdcount="2"> PM-Leonard Bernstein,0519</s>
</SECOND>
<HEAD>

<s docid="AP901010-0030" num="5" wdcount="5"> Leonard Bernstein Giving Up Conducting</s>
</HEAD>
<DATELINE>

<s docid="AP901010-0030" num="6" wdcount="3"> NEW YORK (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP901010-0030" num="7" wdcount="29"> Conductor Leonard Bernstein, the ``West Side Story'' composer who mesmerized audiences with his passion and physical flair at the podium, is giving up the baton because of poor health.</s>

<s docid="AP901010-0030" num="8" wdcount="31"> The 72-year-old maestro suffers from a lung tumor, emphysema and pulmonary infections and has been told by his doctor to stop conducting and performing on the piano, his spokeswoman said Tuesday.</s>

<s docid="AP901010-0030" num="9" wdcount="16"> ``Leonard Bernstein will henceforth devote his professional energies to composing, writing and education,'' said Margaret Carson.</s>

<s docid="AP901010-0030" num="10" wdcount="13"> He last conducted Aug. 19 at the Tanglewood Music Center in western Massachusetts.</s>

<s docid="AP901010-0030" num="11" wdcount="23"> Bernstein's announcement was met with dismay in the music world, especially at the New York Philharmonic, which he directed from 1958 to 1969.</s>

<s docid="AP901010-0030" num="12" wdcount="13"> ``I receive this unfortunate news in utter shock,'' said Zubin Mehta, music director.</s>

<s docid="AP901010-0030" num="13" wdcount="22"> Albert K. Webster, managing director of the Philharmonic, said: ``Leonard Bernstein has BEEN the New York Philharmonic for more than 45 years.</s>

<s docid="AP901010-0030" num="14" wdcount="12"> We all will be less for the loss of his magic baton''.</s>

<s docid="AP901010-0030" num="15" wdcount="37"> Bernstein still hopes to participate in an AIDS benefit at Carnegie Hall on Oct. 28 but canceled all appearances with orchestras in New York, Israel, Vienna and London and with festival orchestras at Tanglewood, Germany and Japan.</s>

<s docid="AP901010-0030" num="16" wdcount="19"> Bernstein, known for his vigorous style at the podium, once led an orchestra performance at a liberated concentration camp.</s>

<s docid="AP901010-0030" num="17" wdcount="15"> Last Christmas, he celebrated the tumbling of the Berlin Wall by conducting Beethoven's ``Ninth Symphony''.</s>

<s docid="AP901010-0030" num="18" wdcount="22"> In May, he canceled plans to conduct opening night of the Spoleto Festival in Charleston, S.C., citing ``a near brush with pneumonia''.</s>

<s docid="AP901010-0030" num="19" wdcount="11"> Carson said Bernstein has had increased difficulty breathing in past weeks.</s>

<s docid="AP901010-0030" num="20" wdcount="16"> Dr. Kevin M. Cahill attributed the problem to emphysema complicated by a tumor and pulmonary infections.</s>

<s docid="AP901010-0030" num="21" wdcount="6"> Bernstein was once a heavy smoker.</s>

<s docid="AP901010-0030" num="22" wdcount="4"> Bernstein is not hospitalized.</s>

<s docid="AP901010-0030" num="23" wdcount="17"> Carson said the conductor was told that rest offers the best hope for returning to limited activities.</s>

<s docid="AP901010-0030" num="24" wdcount="41"> She said Bernstein plans to continue work on a new chamber music piece to be performed next spring, a new musical theater work he hopes to finish by summer and several educational, film and recording projects, as well as his memoirs.</s>

<s docid="AP901010-0030" num="25" wdcount="24"> Bernstein was the wunderkind of American music at a time when all respected conductors in the United States were born and trained in Europe.</s>

<s docid="AP901010-0030" num="26" wdcount="10"> His first published composition was ``The Clarinet Sonata'' in 1942.</s>

<s docid="AP901010-0030" num="27" wdcount="13"> He conducted his first symphony, the ``Jeremiah,'' with the Pittsburgh Symphony in 1944.</s>

<s docid="AP901010-0030" num="28" wdcount="22"> That year his ballet, ``Fancy Free,'' choreographed by Jerome Robbins, opened and became the basis for the Broadway musical ``On the Town''.</s>

<s docid="AP901010-0030" num="29" wdcount="21"> After Boston Symphony Orchestra conductor Serge Koussevitzky died in 1951, Bernstein became head of the orchestra and conducting departments at Tanglewood.</s>

<s docid="AP901010-0030" num="30" wdcount="10"> His first opera, ``Trouble in Tahiti,'' was performed in 1952.</s>

<s docid="AP901010-0030" num="31" wdcount="11"> He composed ``Candide'' in 1956 and ``West Side Story'' in 1957.</s>

<s docid="AP901010-0030" num="32" wdcount="20"> In 1969, he retired from the post to concentrate on composing and was appointed the Philharmonic's laureate conductor for life.</s>

<s docid="AP901010-0030" num="33" wdcount="14"> He has conducted 1,244 New York Philharmonic concerts, more than any other conductor .</s>
</TEXT>
</DOC>
