<DOC>
<DOCNO>

<s docid="AP901016-0097" num="1" wdcount="1"> AP901016-0097</s>
</DOCNO>
<FILEID>

<s docid="AP901016-0097" num="2" wdcount="2"> AP-NY-10-16-90 1510EDT</s>
</FILEID>
<FIRST>

<s docid="AP901016-0097" num="3" wdcount="7"> u a PM-BernsteinMemorial 1stLd-Writethru a0483 10-16 0286</s>
</FIRST>
<SECOND>

<s docid="AP901016-0097" num="4" wdcount="5"> PM-Bernstein Memorial, 1st Ld-Writethru, a0483,0313</s>
</SECOND>
<HEAD>

<s docid="AP901016-0097" num="5" wdcount="5"> Leonard Bernstei Buried In Brooklyn</s>
</HEAD>
<NOTE>

<s docid="AP901016-0097" num="6" wdcount="11"> Eds: LEADS with two grafs to UPDATE with Bernstein buried today.</s>

<s docid="AP901016-0097" num="7" wdcount="8"> Picks up in 3rd graf, `Flags at ...'</s>
</NOTE>
<BYLINE>

<s docid="AP901016-0097" num="8" wdcount="3"> By JUDIE GLAVE</s>
</BYLINE>
<BYLINE>

<s docid="AP901016-0097" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP901016-0097" num="10" wdcount="3"> NEW YORK (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP901016-0097" num="11" wdcount="26"> Leonard Bernstein, whose wide-ranging talents and flamboyant personality helped make him the first American maestro to conquer music's international podium, was buried today alongside his wife.</s>

<s docid="AP901016-0097" num="12" wdcount="22"> Bernstein, who died of lung failure Sunday at age 72, was buried this afternoon in private ceremonies at Greenwood Cemetery in Brooklyn.</s>

<s docid="AP901016-0097" num="13" wdcount="7"> His wife, Felicia Montealegre, died in 1978.</s>

<s docid="AP901016-0097" num="14" wdcount="21"> Flags at Lincoln Center, where the New York Philharmonic performs, were lowered in memory of the orchestra's first American-born music director.</s>

<s docid="AP901016-0097" num="15" wdcount="15"> Bernstein was appointed in 1958 and stepped down in 1969 to spend more time composing.</s>

<s docid="AP901016-0097" num="16" wdcount="14"> The Philharmonic will perform an all-Bernstein program beginning Thursday and continuing through Oct. 23.</s>

<s docid="AP901016-0097" num="17" wdcount="10"> The schedule had called for works by Shostakovich and Beethoven.</s>

<s docid="AP901016-0097" num="18" wdcount="19"> A memorial concert also is planned for Carnegie Hall on Nov. 14, the 47th anniversary of Bernstein's Philharmonic debut.</s>

<s docid="AP901016-0097" num="19" wdcount="28"> Famed for his gymnastics at the podium, Bernstein composed symphonies as well as movie scores and Broadway shows such as ``West Side Story,'' ``On the Town'' and ``Candide''.</s>

<s docid="AP901016-0097" num="20" wdcount="12"> His Emmy-winning ``Young People's Concerts'' on television introduced thousands to classical music.</s>

<s docid="AP901016-0097" num="21" wdcount="30"> ``He was the most unique musician of this century, there is no doubt about it,'' said Zubin Mehta, music director of the New York Philharmonic and the Israel Philharmonic Orchestra.</s>

<s docid="AP901016-0097" num="22" wdcount="23"> Larry Kert, who played Tony in the Broadway production of ``West Side Story,'' said Bernstein himself played the piano for him during rehearsals.</s>

<s docid="AP901016-0097" num="23" wdcount="14"> ``He could have gotten a rehearsal pianist, but he cared too much,'' Kert said.</s>

<s docid="AP901016-0097" num="24" wdcount="26"> ``I was the new kid on the block and he stroked me and took care of me - and I will never forget him for that.''</s>
</TEXT>
</DOC>
