<DOC>
<DOCNO>

<s docid="AP901114-0087" num="1" wdcount="1"> AP901114-0087</s>
</DOCNO>
<FILEID>

<s docid="AP901114-0087" num="2" wdcount="2"> AP-NY-11-14-90 1514EST</s>
</FILEID>
<FIRST>

<s docid="AP901114-0087" num="3" wdcount="5"> r e AM-BernsteinConcert 1-14 0305</s>
</FIRST>
<SECOND>

<s docid="AP901114-0087" num="4" wdcount="2"> AM-Bernstein Concert,0327</s>
</SECOND>
<HEAD>

<s docid="AP901114-0087" num="5" wdcount="8"> Bernstein Remembered at Concert on His Magical Day</s>
</HEAD>
<BYLINE>

<s docid="AP901114-0087" num="6" wdcount="3"> By MARY CAMPBELL</s>
</BYLINE>
<BYLINE>

<s docid="AP901114-0087" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP901114-0087" num="8" wdcount="3"> NEW YORK (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP901114-0087" num="9" wdcount="34"> On the stage where Leonard Bernstein made his sensational New York Philharmonic conducting debut 47 years ago, the orchestra remembered the maestro at a concert that included selections from his ``Mass'' and ``Chichester Psalms''.</s>

<s docid="AP901114-0087" num="10" wdcount="20"> Wednesday's midday concert at Carnegie Hall also came on the 90th birthday of the late composer-conductor's close friend, Aaron Copland.</s>

<s docid="AP901114-0087" num="11" wdcount="17"> And it was the 36th anniversary of the first TV broadcast by Bernstein, who died Oct. 16.</s>

<s docid="AP901114-0087" num="12" wdcount="22"> Speakers, introducing various selections and often quoting from Bernstein's writings, included Bernstein's three children, son-in-law and friends Lauren Bacall and Schuyler Chapin.</s>

<s docid="AP901114-0087" num="13" wdcount="18"> Bernstein's daughter Jamie Thomas said her father had loved numerical coincidences ``and today there's a flock of them''.</s>

<s docid="AP901114-0087" num="14" wdcount="34"> The concert began with selections from Bernstein's ``Mass,'' which he composed for the opening of the Kennedy Center for Performing Arts in Washington, and ended with Psalm 133, in Hebrew, from Bernstein's ``Chichester Psalms''.</s>

<s docid="AP901114-0087" num="15" wdcount="12"> Conductors were Michael Tilson Thomas, Michael Barrett, Christoph Eschenbach and James Levine.</s>

<s docid="AP901114-0087" num="16" wdcount="26"> The orchestra played the overture to Bernstein's ``Candide'' with a symbolically empty podium, which brought tears to some of the invited audience and a standing ovation.</s>

<s docid="AP901114-0087" num="17" wdcount="7"> Cellist Mstislav Rostropovich played a Bach sarabande.</s>

<s docid="AP901114-0087" num="18" wdcount="24"> Singers were the Westminster Choir, mezzo-sopranos Marilyn Horne and Christa Ludwig, soprano Clamma Dale, tenor Jerry Hadley and baritones Thomas Hampson and Chester Ludgin.</s>

<s docid="AP901114-0087" num="19" wdcount="26"> First chair musicians from the Boston Symphony, Israel Philharmonic, London Symphony, Santa Cecilia Orchestra and Vienna Philharmonic flew here, at their orchestras' expense, to take part.</s>

<s docid="AP901114-0087" num="20" wdcount="6"> Two pieces by Copland were played.</s>

<s docid="AP901114-0087" num="21" wdcount="16"> The concert also included Schumann, Haydn and Mahler as well as excerpts from six Bernstein works.</s>

<s docid="AP901114-0087" num="22" wdcount="27"> Bernstein was the New York Philharmonic's 25-year-old assistant conductor on Nov. 14, 1943, when he filled in at the last minute for an ailing Bruno Walter .</s>
</TEXT>
</DOC>
