<DOC>
<DOCNO>

<s docid="LA101990-0114" num="1" wdcount="1"> LA101990-0114</s>
</DOCNO>
<DOCID>

<s docid="LA101990-0114" num="2" wdcount="1"> 294832</s>
</DOCID>
<DATE>
<P>

<s docid="LA101990-0114" num="3" wdcount="6"> October 19, 1990, Friday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA101990-0114" num="4" wdcount="9"> Calendar; Part F; Page 20; Column 1; Entertainment Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA101990-0114" num="5" wdcount="2"> 722 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA101990-0114" num="6" wdcount="7"> HOME TECH: MORE LEONARD BERNSTEIN RELEASES SET;</s>
</P>
<P>

<s docid="LA101990-0114" num="7" wdcount="16"> MUSIC: SONY AND DEUTSCHE GRAMMOPHON PLAN EXPANDED RELEASE SCHEDULES OF RECORDINGS BY THE LATE CONDUCTOR .</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA101990-0114" num="8" wdcount="6"> By DANIEL CARIAGA, TIMES MUSIC WRITER</s>
</P>
</BYLINE>
<TEXT>
<P>

<s docid="LA101990-0114" num="9" wdcount="35"> Recordings by Leonard Bernstein, one of the most documented conductors in history, will undergo expanded release programs following the conductor's death on Sunday, said representatives of the recording companies controlling the late Bernstein's catalogues .</s>
</P>
<P>

<s docid="LA101990-0114" num="10" wdcount="33"> Executives of Sony Classical and Deutsche Grammophon, which control the bulk of Bernstein's recorded legacy, and BMG Classics/RCA Red Seal plan to step up timetables to deliver more Bernstein recordings to the marketplace.</s>

<s docid="LA101990-0114" num="11" wdcount="19"> However, most of the repertory will be from previously released recordings, including some made early in his career .</s>
</P>
<P>

<s docid="LA101990-0114" num="12" wdcount="23"> In fact, the only new recordings will be out next month -- as originally scheduled, reported Karen Moody, vice president of Deutsche Grammophon.</s>

<s docid="LA101990-0114" num="13" wdcount="32"> These are recent recordings Bernstein made with the New York Philharmonic (Tchaikovsky's Fifth Symphony), the Vienna Philharmonic (two Mozart symphonies and the clarinet concerto) and Concertgebouw Orchestra of Amsterdam (Schubert's Symphonies Nos.</s>

<s docid="LA101990-0114" num="14" wdcount="4"> 5 and 8) .</s>
</P>
<P>

<s docid="LA101990-0114" num="15" wdcount="74"> At Sony Classical (formerly CBS Records) in New York City, Peter Munves, director of marketing, said this week that in January the company will begin its three-year release of "The Bernstein Collection": "We will release 75 CDs of Bernstein performances, including not only symphonic music by Beethoven and others, but also oratorio performances -- works by Haydn, and the Requiems by Berlioz and Verdi -- and other music never before released on CD" .</s>
</P>
<P>

<s docid="LA101990-0114" num="16" wdcount="34"> At Deutsche Grammophon, also in New York, Wende Persons, director of promotion, reported: "We are looking at (Bernstein's) active DG discography, which contains over 100 different recordings, and making sure everything is available .</s>
</P>
<P>

<s docid="LA101990-0114" num="17" wdcount="18"> "That's 120 titles (of standard classical repertory) and some of Bernstein's own (non-theatrical) music, plus another dozen videos".</s>

<s docid="LA101990-0114" num="18" wdcount="10"> In his last years, Bernstein recorded exclusively for DG .</s>
</P>
<P>

<s docid="LA101990-0114" num="19" wdcount="22"> In August, Deutsche Grammophon released in this country a 12-CD set of Bernstein recordings with the Vienna Philharmonic, Israel Philharmonic and L.A.</s>

<s docid="LA101990-0114" num="20" wdcount="21"> Philharmonic. These recordings were made between 1977 and 1985 of music by Beethoven, Brahms, Bernstein, Haydn, Mozart, Stravinsky, Tchaikovsky and Gershwin.</s>

<s docid="LA101990-0114" num="21" wdcount="16"> Called "The Bernstein Edition," it is being sold concurrently in Europe in a 25-CD set .</s>
</P>
<P>

<s docid="LA101990-0114" num="22" wdcount="42"> Karen Moody, vice president of the classical label, would not reveal sales figures for "The Bernstein Edition," but said: "I can say that it is selling very well in this country, surprisingly well, given the U.S. market aversion to CD sets" .</s>
</P>
<P>

<s docid="LA101990-0114" num="23" wdcount="64"> In Los Angeles, Carol Brown, West Coast manager of sales and marketing for BMG Classics/RCA Red Seal, told The Times on Thursday that her label now plans a March release of recordings by Bernstein conducting the RCA Symphony in Copland's "Billy the Kid" and a suite from Bernstein's "On the Town," recordings made in the 1940s, and representing the conductor/composer's first commercial recordings .</s>
</P>
<P>

<s docid="LA101990-0114" num="24" wdcount="38"> BMG also plans, according to spokesman Carl Pritzkat, the spring release of an early Bernstein recording as pianist -- in which he plays Copland's Piano Variations -- as well as other recorded documents of the young composer/pianist .</s>
</P>
<P>

<s docid="LA101990-0114" num="25" wdcount="22"> The entire Bernstein catalogue encompasses well over 200 classical recordings and occupies more than a full page in the Schwann catalogue .</s>
</P>
<P>

<s docid="LA101990-0114" num="26" wdcount="25"> There is very little available on Bernstein in the home-video market, which is no surprise considering there are so few classical music titles on cassette.</s>

<s docid="LA101990-0114" num="27" wdcount="15"> Three tapes of programs recorded in 1971, all on Phoenix/BFA Films and Video, are out:</s>
</P>
<P>

<s docid="LA101990-0114" num="28" wdcount="19"> * "Bernstein on Beethoven: a Tribute," featuring Bernstein playing sections of Piano Concerto No. 1 in C Major .</s>
</P>
<P>

<s docid="LA101990-0114" num="29" wdcount="20"> * "Bernstein on Beethoven: Fidelio," with rehearsal and concert footage of Bernstein working with the Vienna State Opera Company .</s>
</P>
<P>

<s docid="LA101990-0114" num="30" wdcount="22"> * "Bernstein on Beethoven: Ode to Joy From the Ninth Symphony," featuring the Vienna State Opera Chorus and the Vienna Philharmonic .</s>
</P>
<P>

<s docid="LA101990-0114" num="31" wdcount="11"> Three movies whose scores he composed are also on home video:</s>
</P>
<P>

<s docid="LA101990-0114" num="32" wdcount="12"> * MGM/UA's "On the Town" (1949), co-starring Gene Kelly and Frank Sinatra.</s>

<s docid="LA101990-0114" num="33" wdcount="10"> The lyrics are by Adolph Green and Betty Comden .</s>
</P>
<P>

<s docid="LA101990-0114" num="34" wdcount="11"> * MGM/UA's "West Side Story" (1961), featuring Stephen Sondheim's lyrics .</s>
</P>
<P>

<s docid="LA101990-0114" num="35" wdcount="12"> * RCA/Columbia's "On the Waterfront" (1954), the Oscar-winner for best picture .</s>
</P>
<P>

<s docid="LA101990-0114" num="36" wdcount="9"> Staff writer Dennis Hunt contributed to this story .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA101990-0114" num="37" wdcount="12"> Photo, Bernstein conducts the Vienna, Israel and L.A. orchestras on DG .</s>
</P>
</GRAPHIC>
<TYPE>
<P>

<s docid="LA101990-0114" num="38" wdcount="3"> Recording Review; Column</s>
</P>
</TYPE>
</DOC>
