<DOC>
<DOCNO>

<s docid="LA102690-0005" num="1" wdcount="1"> LA102690-0005</s>
</DOCNO>
<DOCID>

<s docid="LA102690-0005" num="2" wdcount="1"> 297971</s>
</DOCID>
<DATE>
<P>

<s docid="LA102690-0005" num="3" wdcount="6"> October 26, 1990, Friday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA102690-0005" num="4" wdcount="9"> Metro; Part B; Page 6; Column 3; Letters Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA102690-0005" num="5" wdcount="2"> 200 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA102690-0005" num="6" wdcount="2"> CONDUCTOR BERNSTEIN</s>
</P>
</HEADLINE>
<TEXT>
<P>

<s docid="LA102690-0005" num="7" wdcount="35"> I assume that anyone who was ever touched by the genius of Leonard Bernstein will have his own memory of the Renaissance man of music, as you aptly described him (Part A, Oct. 15) .</s>
</P>
<P>

<s docid="LA102690-0005" num="8" wdcount="25"> Mine dates back to October, 1948, when I was serving as an American volunteer in the Israeli army during the country's War of Independence .</s>
</P>
<P>

<s docid="LA102690-0005" num="9" wdcount="36"> With a two-day pass in hand, I hitchhiked to Jerusalem, where the Israeli equivalent of the USO scrounged up a ticket for the evening's performance of the Israel Philharmonic, with Bernstein as the guest conductor .</s>
</P>
<P>

<s docid="LA102690-0005" num="10" wdcount="13"> The audience was a mix of black-tie patrons and soldiers dressed in fatigues.</s>

<s docid="LA102690-0005" num="11" wdcount="25"> Bernstein raised the baton for Beethoven's Fifth Symphony, emotional at any time, but never more so than for a people engaged in a life-and-death struggle.</s>

<s docid="LA102690-0005" num="12" wdcount="29"> Toward the end of the first movement, machine-gun fire started crackling from the old city, held by the Jordanian Legion, and continued intermittently through the rest of the symphony.</s>

<s docid="LA102690-0005" num="13" wdcount="26"> What would have been a distracting disturbance at any other time, melded, with the music as entirely appropriate to the mood and circumstances of the occasion.</s>

<s docid="LA102690-0005" num="14" wdcount="9"> Lenny and the orchestra, never missed a beat .</s>
</P>
<P>

<s docid="LA102690-0005" num="15" wdcount="2"> TOM TUGEND</s>
</P>
<P>

<s docid="LA102690-0005" num="16" wdcount="2"> Sherman Oaks</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA102690-0005" num="17" wdcount="3"> Photo, Leonard Bernstein</s>
</P>
</GRAPHIC>
<TYPE>
<P>

<s docid="LA102690-0005" num="18" wdcount="4"> Letter to the Editor</s>
</P>
</TYPE>
</DOC>
