<DOC>
<DOCNO>

<s docid="LA101590-0066" num="1" wdcount="1"> LA101590-0066</s>
</DOCNO>
<DOCID>

<s docid="LA101590-0066" num="2" wdcount="1"> 292731</s>
</DOCID>
<DATE>
<P>

<s docid="LA101590-0066" num="3" wdcount="6"> October 15, 1990, Monday, Home Edition</s>
</P>
</DATE>
<P>

<s docid="LA101590-0066" num="4" wdcount="2"> LEONARD BERNSTEIN</s>
</P>
<SECTION>
<P>

<s docid="LA101590-0066" num="5" wdcount="8"> Part A; Page 1; Column 3; Metro Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA101590-0066" num="6" wdcount="2"> 2706 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA101590-0066" num="7" wdcount="5"> LEONARD BERNSTEIN DIES; CONDUCTOR, COMPOSER;</s>
</P>
<P>

<s docid="LA101590-0066" num="8" wdcount="8"> MUSIC: RENAISSANCE MAN OF HIS ART WAS 72.</s>

<s docid="LA101590-0066" num="9" wdcount="6"> THE LONGTIME LEADER OF THE N.Y.</s>

<s docid="LA101590-0066" num="10" wdcount="11"> PHILHARMONIC CARVED A NICHE IN HISTORY WITH 'WEST SIDE STORY' .</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA101590-0066" num="11" wdcount="6"> By MYRNA OLIVER, TIMES STAFF WRITER</s>
</P>
</BYLINE>
<TEXT>
<P>

<s docid="LA101590-0066" num="12" wdcount="33"> Leonard Bernstein, the Renaissance man of music who excelled as pianist, composer, conductor and teacher and was, as well, the flamboyant ringmaster of his own nonstop circus, died Sunday in his Manhattan apartment.</s>

<s docid="LA101590-0066" num="13" wdcount="4"> He was 72 .</s>
</P>
<P>

<s docid="LA101590-0066" num="14" wdcount="37"> Bernstein, known and beloved by the world as "Lenny," died at 6:15 p.m. in the presence of his son, Alexander, and physician, Kevin M. Cahill, who said the cause of death was complications of progressive lung failure.</s>

<s docid="LA101590-0066" num="15" wdcount="12"> On Cahill's advice, the conductor had announced Tuesday that he would retire.</s>

<s docid="LA101590-0066" num="16" wdcount="24"> Cahill said progressive emphysema complicated by a pleural tumor and a series of lung infections had left Bernstein too weak to continue working .</s>
</P>
<P>

<s docid="LA101590-0066" num="17" wdcount="9"> In recent months, Bernstein canceled performances with increasing frequency.</s>

<s docid="LA101590-0066" num="18" wdcount="12"> His last conducting appearance was at Tanglewood, Mass., on Aug. 19 .</s>
</P>
<P>

<s docid="LA101590-0066" num="19" wdcount="29"> Bernstein was the first American-born conductor to lead a major symphony orchestra, often joining his New York Philharmonic in playing his own pieces, while conducting from the piano .</s>
</P>
<P>

<s docid="LA101590-0066" num="20" wdcount="27"> He etched other niches in history by composing the indelible "West Side Story" and teaching a generation about classical music via the innovative television series "Omnibus" .</s>
</P>
<P>

<s docid="LA101590-0066" num="21" wdcount="39"> Exhibiting remarkable talent and expertise in four areas that most artists wish they possessed in merely one, Bernstein still might have remained an obscure musician without the unique theatrical flair that dominated his personal as well as professional life.</s>

<s docid="LA101590-0066" num="22" wdcount="27"> With it, he became a personality, well known even to people who never bought a ticket to a musical performance or watched a serious television show .</s>
</P>
<P>

<s docid="LA101590-0066" num="23" wdcount="20"> The dervish persona, including his upstart gymnastics on the podium, never lessened throughout his long life in the spotlight .</s>
</P>
<P>

<s docid="LA101590-0066" num="24" wdcount="10"> He made classical music understandable and palatable to the masses.</s>

<s docid="LA101590-0066" num="25" wdcount="22"> And he lifted popular music to a higher plane, infusing performers and listeners with his manic joy in creating tonal sound .</s>
</P>
<P>

<s docid="LA101590-0066" num="26" wdcount="22"> "Some conductors mellow with age," commented Times music critic Martin Bernheimer when Bernstein conducted the Los Angeles Philharmonic at UCLA in 1986.</s>

<s docid="LA101590-0066" num="27" wdcount="34"> "(But) Bernstein, at 68, remains a frenetic combination of orbiting rocket, aerobics master, super-juggler, matinee idol, booming cannon, hysterical mime, heart-rending tragedian, bouncing ball, sky writer, riveting machine, mawkish sentimentalist and danseur ignoble" .</s>
</P>
<P>

<s docid="LA101590-0066" num="28" wdcount="35"> Describing the conductor in the same concert, Bernheimer referred to him as "the shrugging, jumping, sighing, soaring, gushing, crouching, rocking, rolling, bounding, bobbing, leaping, jiggling, stabbing, hunching, bumping, grinding and grunting maestro in excelsis" .</s>
</P>
<P>

<s docid="LA101590-0066" num="29" wdcount="31"> Critics also were quick to agree that had his envied and often-criticized showmanship masked lazy, sloppy or inept musicianship, Bernstein could never have remained an internationally sought-after conductor for five decades.</s>

<s docid="LA101590-0066" num="30" wdcount="27"> He knew what he was doing, and the musicians he accompanied, wrote for, conducted, or lectured to and taught admired him as one of their own .</s>
</P>
<P>

<s docid="LA101590-0066" num="31" wdcount="21"> Louis Bernstein (so-named because his maternal grandmother insisted) was born Aug. 25, 1918, in Lawrence, Mass., to two Russian Jewish immigrants.</s>

<s docid="LA101590-0066" num="32" wdcount="17"> His father, Samuel Joseph Bernstein, was an entrepreneur of women's hair care products and a Talmudic scholar.</s>

<s docid="LA101590-0066" num="33" wdcount="17"> His mother, Jennie Resnick Bernstein, who survives him, said her son always had an ear for music.</s>

<s docid="LA101590-0066" num="34" wdcount="16"> "When he was 4 or 5, he would play an imaginary piano on his windowsill" .</s>
</P>
<P>

<s docid="LA101590-0066" num="35" wdcount="11"> The parents preferred the name "Leonard" and called the boy that.</s>

<s docid="LA101590-0066" num="36" wdcount="25"> When his kindergarten teacher asked "Louis Bernstein" to stand up, he remained seated and looked around the room to see who shared his last name.</s>

<s docid="LA101590-0066" num="37" wdcount="16"> Bernstein changed his name legally at age 16, when he got his first driver's license .</s>
</P>
<P>

<s docid="LA101590-0066" num="38" wdcount="11"> His mega musical talent emerged belatedly and almost by accident .</s>
</P>
<P>

<s docid="LA101590-0066" num="39" wdcount="29"> When Bernstein was 10, a divorcing aunt stored her old upright piano with his parents, and the boy who used to play at the windowsill became fascinated with it.</s>

<s docid="LA101590-0066" num="40" wdcount="21"> He asked for lessons, and soon was playing better than his teacher, a neighbor's daughter who charged $1 a lesson .</s>
</P>
<P>

<s docid="LA101590-0066" num="41" wdcount="35"> By age 12, he was studying at the New England Conservatory of Music and had determined, despite his father's objections, that music -- at that point playing the piano -- would be his career .</s>
</P>
<P>

<s docid="LA101590-0066" num="42" wdcount="23"> Bernstein's stunning instinctive talents for sight-reading, remembering complicated scores, and improvisation became evident as he played, and altered, classical, jazz and popular music.</s>

<s docid="LA101590-0066" num="43" wdcount="27"> He produced his own shows and versions of "The Mikado" and "Carmen," and performed as piano soloist with his school orchestra and the State Symphony Orchestra .</s>
</P>
<P>

<s docid="LA101590-0066" num="44" wdcount="20"> He reveled in music while excelling in athletics and the classical subjects taught at the 300-year-old Boston Latin School .</s>
</P>
<P>

<s docid="LA101590-0066" num="45" wdcount="23"> At Harvard University, Bernstein studied piano and composition, but developed a serious interest in composing only after meeting American composer Aaron Copland .</s>
</P>
<P>

<s docid="LA101590-0066" num="46" wdcount="15"> A fan and practitioner of his music, Bernstein met Copland in a typical it-could-only-happen-to-Lenny incident.</s>

<s docid="LA101590-0066" num="47" wdcount="21"> Invited to a dance recital in New York, Bernstein sat in the balcony next to a man he did not recognize.</s>

<s docid="LA101590-0066" num="48" wdcount="18"> Invited afterward to a post-recital birthday party for Copland, Bernstein commandeered the piano and played Copland's "Piano Variations".</s>

<s docid="LA101590-0066" num="49" wdcount="17"> His performance captivated the man he had met in the balcony, who of course was Copland .</s>
</P>
<P>

<s docid="LA101590-0066" num="50" wdcount="4"> They became lifelong friends.</s>

<s docid="LA101590-0066" num="51" wdcount="21"> Copland introduced Bernstein to several composers and got him his first job -- transcribing music for the publisher Boosey and Hawkes.</s>

<s docid="LA101590-0066" num="52" wdcount="20"> Ironically, Copland subsequently urged the torn Bernstein to make conducting, rather than composing or even piano playing, his career .</s>
</P>
<P>

<s docid="LA101590-0066" num="53" wdcount="32"> Conducting emerged as a possibility to Bernstein that same year -- 1937, his sophomore year at Harvard -- when he met the Greek conductor Dimitri Mitropoulos during the maestro's visit to campus.</s>

<s docid="LA101590-0066" num="54" wdcount="18"> Mitropoulos was so impressed with Bernstein's playing that he invited him to attend rehearsals with the Boston Symphony.</s>

<s docid="LA101590-0066" num="55" wdcount="19"> The maestro also talked with Bernstein privately in his dressing room after concerts, promising to keep in touch .</s>
</P>
<P>

<s docid="LA101590-0066" num="56" wdcount="61"> "The influence of Mitropoulos on my life, on my conducting life is enormous and usually greatly underrated or not known at all," Bernstein wrote years later, after his mentors had all died, "because ordinarily the two great conductors with whom I studied are the ones who receive the credit for whatever conducting prowess I have, namely Serge Koussevitzky and Fritz Reiner.</s>

<s docid="LA101590-0066" num="57" wdcount="56"> . . . But long before I met either of them, I had met Dimitri Mitropoulos . . . and watching him conduct those two weeks of rehearsals and concerts with the Boston Symphony laid some kind of conductorial passion and groundwork in my psyche which I wasn't even aware of until many years later" .</s>
</P>
<P>

<s docid="LA101590-0066" num="58" wdcount="21"> Graduated from Harvard and out of work after a summer in New York, Bernstein asked Mitropoulos what he should do .</s>
</P>
<P>

<s docid="LA101590-0066" num="59" wdcount="21"> "You must be a conductor," Mitropoulos replied, urging him to study at Juilliard or with Reiner at Curtis Institute in Philadelphia.</s>

<s docid="LA101590-0066" num="60" wdcount="19"> It was fall and conducting classes at Juilliard were full, so Bernstein went to Philadelphia for two years .</s>
</P>
<P>

<s docid="LA101590-0066" num="61" wdcount="26"> During the summers he studied under Koussevitzky, conductor of the Boston Symphony, at the new school Koussevitzky was starting at the orchestra's summer home, Tanglewood .</s>
</P>
<P>

<s docid="LA101590-0066" num="62" wdcount="18"> "He became like a surrogate father to me," Bernstein later said of Koussevitzky, his third major conducting mentor.</s>

<s docid="LA101590-0066" num="63" wdcount="27"> "He had no children of his own and I had a father whom I loved very much but who was not for this musical thing at all.</s>

<s docid="LA101590-0066" num="64" wdcount="16"> . . . And so I found another father: first Mitropoulos, then Reiner, and now Koussevitzky.</s>

<s docid="LA101590-0066" num="65" wdcount="10"> But the Koussevitzky relationship was very special, very warm" .</s>
</P>
<P>

<s docid="LA101590-0066" num="66" wdcount="14"> Bernstein later became Koussevitzky's assistant and returned to Tanglewood annually to conduct and teach.</s>

<s docid="LA101590-0066" num="67" wdcount="23"> He so revered the maestro that he was married in Koussevitzky's shoes and white suit and always conducted wearing his cuff links .</s>
</P>
<P>

<s docid="LA101590-0066" num="68" wdcount="22"> It was Koussevitzky -- and fate -- who arranged Bernstein's meteoric ascension to world-class conductor at the unheard-of age of 25 .</s>
</P>
<P>

<s docid="LA101590-0066" num="69" wdcount="34"> On his 25th birthday, Aug. 25, 1943, Bernstein was told by the Koussevitzkys that he should visit Artur Rodzinsky, newly appointed music director of the New York Philharmonic, at his Stockbridge, Conn., farm .</s>
</P>
<P>

<s docid="LA101590-0066" num="70" wdcount="11"> "I am going to need an assistant conductor," Rodzinsky told him.</s>

<s docid="LA101590-0066" num="71" wdcount="43"> "I have gone through all the conductors I know of in my mind and I finally asked God whom I shall take and God said, 'Take Bernstein,' " he said, granting the position as a favor not to God but to Koussevitzky .</s>
</P>
<P>

<s docid="LA101590-0066" num="72" wdcount="24"> Remarkable as his appointment was considering that he was an American and so young, Bernstein was given little chance of actually taking the podium.</s>

<s docid="LA101590-0066" num="73" wdcount="13"> In the orchestra's history, no assistant conductor had ever been called on .</s>
</P>
<P>

<s docid="LA101590-0066" num="74" wdcount="9"> But for "Lucky Lenny" history made an exception .</s>
</P>
<P>

<s docid="LA101590-0066" num="75" wdcount="27"> On Nov. 14, less than three months after Bernstein got the job, guest conductor Bruno Walter fell ill and Rodzinsky was snowed in at his farm .</s>
</P>
<P>

<s docid="LA101590-0066" num="76" wdcount="39"> Jennie Tourel had sung Bernstein's "I Hate Music" at her Town Hall debut the previous night, in itself an event big enough to bring his parents to town, and he had played for her and the post-recital party .</s>
</P>
<P>

<s docid="LA101590-0066" num="77" wdcount="22"> With no rehearsal, a hangover and three hours sleep, Bernstein was to conduct a complex program broadcast nationwide on CBS radio .</s>
</P>
<P>

<s docid="LA101590-0066" num="78" wdcount="17"> The New York Times chronicled the epic event on Page One and stated in an editorial: "Mr.</s>

<s docid="LA101590-0066" num="79" wdcount="14"> Bernstein had to have something approaching genius to make full use of his opportunity.</s>

<s docid="LA101590-0066" num="80" wdcount="9"> . . . It's a good American success story.</s>

<s docid="LA101590-0066" num="81" wdcount="15"> The warm, friendly triumph of it filled Carnegie Hall and spread over the airwaves" .</s>
</P>
<P>

<s docid="LA101590-0066" num="82" wdcount="18"> Bernstein was not to get his own orchestra until he took over the New York Philharmonic in 1957-58.</s>

<s docid="LA101590-0066" num="83" wdcount="6"> He had no time for one.</s>

<s docid="LA101590-0066" num="84" wdcount="15"> He was too much in demand around the world as the wunderkind guest conductor .</s>
</P>
<P>

<s docid="LA101590-0066" num="85" wdcount="28"> Successful as a pianist, composer and conductor, Bernstein, according to Joan Peyser in a controversial biography, consulted psychiatrists because of his internal conflict over the three pursuits .</s>
</P>
<P>

<s docid="LA101590-0066" num="86" wdcount="18"> "It is impossible for me to make an exclusive choice among the various activities," Bernstein wrote in 1946.</s>

<s docid="LA101590-0066" num="87" wdcount="14"> "What seems right for me at any given moment is what I must do.</s>

<s docid="LA101590-0066" num="88" wdcount="19"> . . . The ends are music itself . . . and the means are my private problem" .</s>
</P>
<P>

<s docid="LA101590-0066" num="89" wdcount="12"> The piano became an occasional solo onstage or a celebrated party pastime.</s>

<s docid="LA101590-0066" num="90" wdcount="13"> Bernstein concentrated seriously on composing while developing and commercializing his conducting career .</s>
</P>
<P>

<s docid="LA101590-0066" num="91" wdcount="30"> His first major composition, a symphony titled "Jeremiah," was introduced in 1942, and his first ballet, "Fancy Free," and related first musical, "On the Town," both debuted in 1944 .</s>
</P>
<P>

<s docid="LA101590-0066" num="92" wdcount="41"> He sought to be a classical composer, winning plaudits for symphonies ("Jeremiah" was followed by "The Age of Anxiety" in 1949 and "Kaddish" in 1963), sonatas, and the operas "Trouble in Tahiti" in 1953 and "A Quiet Place" in 1983 .</s>
</P>
<P>

<s docid="LA101590-0066" num="93" wdcount="17"> In writing music, Bernstein achieved greater success on Broadway, and even in Hollywood, than in Lincoln Center.</s>

<s docid="LA101590-0066" num="94" wdcount="32"> He followed "On the Town" with the musicals "Wonderful Town" in 1953, the score for the film "On the Waterfront" in 1954, and the critically acclaimed but less popular "Candide" in 1956.</s>

<s docid="LA101590-0066" num="95" wdcount="12"> His best and best-remembered work, "West Side Story," debuted in 1957 .</s>
</P>
<P>

<s docid="LA101590-0066" num="96" wdcount="34"> "If I can write one real, moving American opera that any American can understand (and one that is, notwithstanding, a serious musical work), I shall be a happy man," Bernstein said in 1948 .</s>
</P>
<P>

<s docid="LA101590-0066" num="97" wdcount="37"> When many suggested a decade later that he had achieved his dream with "West Side Story," he disagreed, saying: "There are moments when I think so, but as a sum total it fails to be an opera.</s>

<s docid="LA101590-0066" num="98" wdcount="12"> Because at the denouement, at the dramatic unraveling, the music stops .</s>
</P>
<P>

<s docid="LA101590-0066" num="99" wdcount="23"> "But I don't love it any less," he added, reveling in the adulation his adaptation of the Romeo and Juliet conflict had produced.</s>

<s docid="LA101590-0066" num="100" wdcount="10"> "It doesn't make it a stepchild or a foundling" .</s>
</P>
<P>

<s docid="LA101590-0066" num="101" wdcount="32"> In teaching, his fourth area of expertise, Bernstein taught regularly at Tanglewood and won his place in academic annals with his Charles Eliot Norton Lectures on tonality at Harvard in 1973 .</s>
</P>
<P>

<s docid="LA101590-0066" num="102" wdcount="25"> It was on television in the 1950s and 1960s, with his "Young People's Concerts" of the Philharmonic and "Omnibus," that Bernstein taught the nation .</s>
</P>
<P>

<s docid="LA101590-0066" num="103" wdcount="42"> "An assessment of Bernstein must include his talent and contribution as a teacher and popularizer of music, a role that has set him apart most from other performers," conductor, historian and Bard College President Leon Botstein wrote in Harper's in 1983 .</s>
</P>
<P>

<s docid="LA101590-0066" num="104" wdcount="26"> Instinctively adept at television, Bernstein became a prototype for Carl Sagan, Alistair Cooke and others now familiar on instructive programs on the Public Broadcasting System .</s>
</P>
<P>

<s docid="LA101590-0066" num="105" wdcount="27"> Bernstein's programs, Botstein said, "displayed his gift for analyzing and enthusing about classical music without sacrificing the integrity of the score, its complexity, or its simple genius.</s>

<s docid="LA101590-0066" num="106" wdcount="27"> No one before or since Bernstein has been so effective -- artistically and commercially -- in proselytizing and bringing alive serious music to a mass audience" .</s>
</P>
<P>

<s docid="LA101590-0066" num="107" wdcount="10"> The television classics won Bernstein a coveted Peabody award .</s>
</P>
<P>

<s docid="LA101590-0066" num="108" wdcount="23"> Bernstein was able to apply his innate ability for commercializing his art that had made him wealthy to the struggling New York Philharmonic.</s>

<s docid="LA101590-0066" num="109" wdcount="22"> He introduced free concerts in the park and put the orchestra on television, widening its audience and tripling paid concert attendance .</s>
</P>
<P>

<s docid="LA101590-0066" num="110" wdcount="24"> He left the orchestra in 1969, after a record 11-year tenure at the helm, to have more time for composing and guest conducting .</s>
</P>
<P>

<s docid="LA101590-0066" num="111" wdcount="22"> If two rings of the Bernstein circus rested in popular and classical music, the third was anchored in his uproarious personal life.</s>

<s docid="LA101590-0066" num="112" wdcount="30"> Known for his emotional embraces of both sexes, Bernstein loved crowds and kept friends and family with him throughout the night at his Manhattan apartment or Connecticut country home .</s>
</P>
<P>

<s docid="LA101590-0066" num="113" wdcount="28"> A heavy smoker and drinker who partied or worked until dawn and slept until noon, he claimed he composed or studied scores even when surrounded by people .</s>
</P>
<P>

<s docid="LA101590-0066" num="114" wdcount="19"> "God knows, I should be dead by now," he said as he approached 70, characteristically cavalier about his health.</s>

<s docid="LA101590-0066" num="115" wdcount="2"> "I smoke.</s>

<s docid="LA101590-0066" num="116" wdcount="2"> I drink.</s>

<s docid="LA101590-0066" num="117" wdcount="5"> I stay up all night.</s>

<s docid="LA101590-0066" num="118" wdcount="5"> I'm overcommitted on all fronts.</s>

<s docid="LA101590-0066" num="119" wdcount="17"> . . . I was told that if I didn't stop smoking I'd be dead at 35.</s>

<s docid="LA101590-0066" num="120" wdcount="6"> Well, I beat the rap" .</s>
</P>
<P>

<s docid="LA101590-0066" num="121" wdcount="28"> Raising the high-brow music world's eyebrows, Bernstein campaigned with other celebrities for the civil rights of blacks in the 1960s and against the Vietnam War in the 1970s.</s>

<s docid="LA101590-0066" num="122" wdcount="22"> Criticized for "radical chic," his leftist political philosophy prompted him to host a storied fund-raising party for the Black Panthers in 1970.</s>

<s docid="LA101590-0066" num="123" wdcount="33"> In 1989, he rejected a National Medal of the Arts in protest of the withdrawn $10,000 grant (later reinstated) of the National Endowment for the Arts to an art show on AIDS .</s>
</P>
<P>

<s docid="LA101590-0066" num="124" wdcount="34"> Although Peyser made a strong case in her 1987 biography that Bernstein had many homosexual affairs (Bernstein promised his children never to read the book), there was no question that he adored his family.</s>

<s docid="LA101590-0066" num="125" wdcount="39"> On Sept. 9, 1951, he married Chilean actress Felicia Montealegre, and, despite a short separation and subsequent reconciliation in 1976, remained devoted to her and went into a severe depression when she died of lung cancer in 1978 .</s>
</P>
<P>

<s docid="LA101590-0066" num="126" wdcount="20"> Bernstein is also survived by two daughters, Jamie and Nina, as well as his sister, Shirley, and brother, Burton .</s>
</P>
<P>

<s docid="LA101590-0066" num="127" wdcount="10"> Spokeswoman Margaret Carson said the funeral would be private .</s>
</P>
<P>

<s docid="LA101590-0066" num="128" wdcount="36"> Staunchly opposed to retiring, until last Tuesday, Bernstein continued his guest conducting, composing, and recording, perhaps topping his more than 200 records with the best of his best, a re-recording of "West Side Story" in 1985.</s>

<s docid="LA101590-0066" num="129" wdcount="29"> The effort became Deutsche Grammaphon's all-time best-selling record and prompted Will Crutchfield to write in the New York Times that Bernstein was in a class with Giuseppe Verdi .</s>
</P>
<P>

<s docid="LA101590-0066" num="130" wdcount="23"> French President Francois Mitterrand saluted "West Side Story" anew in 1986 when he made Bernstein a commander of the Legion of Honor .</s>
</P>
<P>

<s docid="LA101590-0066" num="131" wdcount="33"> After a nationwide series of concerts and parties celebrating his 70th birthday in 1988, Bernstein said with uncharacteristic modesty: "I have no further requests of the fates . . . except for time.</s>

<s docid="LA101590-0066" num="132" wdcount="10"> I've achieved more than I had any right to expect.</s>

<s docid="LA101590-0066" num="133" wdcount="9"> Nobody has been as lucky as I have" .</s>
</P>
<P>

<s docid="LA101590-0066" num="134" wdcount="12"> SUPERSTAR LENNY: Too much talent, too little time, says Martin Bernheimer. A23</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA101590-0066" num="135" wdcount="10"> Photo, COLOR, Leonard Bernstein conducting special 1989 concert in Poland.</s>

<s docid="LA101590-0066" num="136" wdcount="18"> Agence France-Presse; Photo, Views of Bernstein: Leonard Bernstein's last conducting appearance, above, at Tanglewood, Mass., on Aug. 19.</s>

<s docid="LA101590-0066" num="137" wdcount="25"> 1990 ALAN SOLOMON; Photo, Bernstein, left, as he appeared at the Hollywood Bowl in 1982, and guiding the Los Angeles Philharmonic, below, also in 1982.</s>

<s docid="LA101590-0066" num="138" wdcount="10"> Los Angeles Times; Photo, (Southland Edition) Leonard Bernstein in 1988.</s>

<s docid="LA101590-0066" num="139" wdcount="3"> STEVE J. SHERMAN</s>
</P>
</GRAPHIC>
<TYPE>
<P>

<s docid="LA101590-0066" num="140" wdcount="3"> Obituary; Main Story</s>
</P>
</TYPE>
</DOC>
