<DOC>
<DOCNO>

<s docid="LA102090-0146" num="1" wdcount="1"> LA102090-0146</s>
</DOCNO>
<DOCID>

<s docid="LA102090-0146" num="2" wdcount="1"> 295402</s>
</DOCID>
<DATE>
<P>

<s docid="LA102090-0146" num="3" wdcount="6"> October 20, 1990, Saturday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA102090-0146" num="4" wdcount="9"> Calendar; Part F; Page 5; Column 1; Entertainment Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA102090-0146" num="5" wdcount="2"> 378 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA102090-0146" num="6" wdcount="3"> LEONARD BERNSTEIN REMEMBRANCES;</s>
</P>
<P>

<s docid="LA102090-0146" num="7" wdcount="12"> MUSIC: MORE LOCAL TRIBUTES FOR THE CONDUCTOR-COMPOSER ARE PLANNED ON SUNDAY .</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA102090-0146" num="8" wdcount="3"> By GREGG WAGER</s>
</P>
</BYLINE>
<TEXT>
<P>

<s docid="LA102090-0146" num="9" wdcount="26"> In addition to the Leonard Bernstein tribute that is part of the Los Angeles Philharmonic program this weekend, other local orchestras are also planning special remembrances.</s>

<s docid="LA102090-0146" num="10" wdcount="37"> Sunday at Royce Hall, the American Youth Symphony has added local composer Leon Levitch's Elegy for Strings -- a personal choice from conductor Mehli Mehta -- to the program to honor Bernstein, who died last Sunday .</s>
</P>
<P>

<s docid="LA102090-0146" num="11" wdcount="34"> Also, opening the new season of the Glendale Symphony season on Sunday at Dorothy Chandler Pavilion, music director Lalo Schifrin will observe a moment of silence to honor his longtime friend and colleague .</s>
</P>
<P>

<s docid="LA102090-0146" num="12" wdcount="42"> Last Monday, KUSC-FM (91.5) devoted its entire day of live broadcasting, from 6 a.m. to 10 p.m., to performances -- as conductor and pianist -- and compositions of Bernstein, including an unusual recording from 1956 of him discussing Beethoven's Fifth Symphony .</s>
</P>
<P>

<s docid="LA102090-0146" num="13" wdcount="17"> KKGO-FM (105.1) also devoted a considerable amount air time to Bernstein's work on Tuesday and Wednesday .</s>
</P>
<P>

<s docid="LA102090-0146" num="14" wdcount="29"> Another measure of grief came from the obituary section of the New York Times, which includes a section of special classified ads for public condolences at $15.85 a line.</s>

<s docid="LA102090-0146" num="15" wdcount="21"> The outpouring of emotions following Bernstein's death filled almost 200 lines (15 inches of small type) and encompassed 14 separate tributes.</s>

<s docid="LA102090-0146" num="16" wdcount="30"> Among the contributors were conductors Zubin Mehta and Kurt Masur, as well as Peter Martins of the New York Ballet and Christopher Keene of the New York City Opera .</s>
</P>
<P>

<s docid="LA102090-0146" num="17" wdcount="13"> "Leonard Bernstein . . . is now being mourned by the entire world.</s>

<s docid="LA102090-0146" num="18" wdcount="7"> I personally have lost a dear friend".</s>

<s docid="LA102090-0146" num="19" wdcount="5"> wrote Mehta in his tribute.</s>

<s docid="LA102090-0146" num="20" wdcount="25"> "I was proud to be associated with him at the New York Philharmonic and the Israel Philharmonic Orchestra, both of which he considered family" .</s>
</P>
<P>

<s docid="LA102090-0146" num="21" wdcount="26"> "This is perhaps not unusual for a prominent member of the Jewish community involved with philanthropic activities," reported Irv Horowitz, the New York Times obituary editor.</s>

<s docid="LA102090-0146" num="22" wdcount="23"> He said the biggest similar reaction he could recall came after the recent death of the mother of the New York Times publisher.</s>

<s docid="LA102090-0146" num="23" wdcount="7"> "That was considerably larger," Horowitz said .</s>
</P>
<P>

<s docid="LA102090-0146" num="24" wdcount="30"> The Bernstein family has requested contributions in lieu of flowers be made to the Bernstein Education Through the Arts Fund Inc., 25 C.P.W., Suite 1B, New York, N.Y. 10023 .</s>
</P>
</TEXT>
<SUBJECT>
<P>

<s docid="LA102090-0146" num="25" wdcount="5"> BERNSTEIN, LEONARD; MEMORIALS; ORCHESTRAS; CONCERTS</s>
</P>
</SUBJECT>
</DOC>
