<DOC>
<DOCNO>

<s docid="LA121490-0148" num="1" wdcount="1"> LA121490-0148</s>
</DOCNO>
<DOCID>

<s docid="LA121490-0148" num="2" wdcount="1"> 322394</s>
</DOCID>
<DATE>
<P>

<s docid="LA121490-0148" num="3" wdcount="6"> December 14, 1990, Friday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA121490-0148" num="4" wdcount="9"> Calendar; Part F; Page 1; Column 5; Entertainment Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA121490-0148" num="5" wdcount="2"> 696 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA121490-0148" num="6" wdcount="5"> A BROADWAY GOODBY TO BERNSTEIN;</s>
</P>
<P>

<s docid="LA121490-0148" num="7" wdcount="14"> MEMORIAL: LONGTIME FRIENDS AND COLLEAGUES LAUGH, CRY, SING AT NEW YORK'S MAJESTIC THEATER .</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA121490-0148" num="8" wdcount="7"> By SUSAN REITER, SPECIAL TO THE TIMES</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA121490-0148" num="9" wdcount="2"> NEW YORK</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA121490-0148" num="10" wdcount="20"> Laughter and tears flowed freely as the Broadway theatrical community said goodby Thursday to Leonard Bernstein at the Majestic Theater.</s>

<s docid="LA121490-0148" num="11" wdcount="28"> Longtime friends and colleagues -- those who knew him as Lenny -- paid tribute to the musical-theater dynamo with heartfelt and humorous words, and often in song .</s>
</P>
<P>

<s docid="LA121490-0148" num="12" wdcount="49"> The capacity audience -- invited friends, relatives and theatrical personalities as well as 850 members of the public who started lining up at 7 a.m. -- heard recollections of an energetic Bernstein who danced until dawn in discos as well as a poignant account of his final days .</s>
</P>
<P>

<s docid="LA121490-0148" num="13" wdcount="21"> Arthur Laurents, who wrote the book for "West Side Story," hosted the 75-minute tribute to Bernstein, 72, who died Oct. 14.</s>

<s docid="LA121490-0148" num="14" wdcount="22"> "Wherever Lenny was, was theater; his every move was a stage direction," he said, as many in the audience laughed knowingly .</s>
</P>
<P>

<s docid="LA121490-0148" num="15" wdcount="38"> Another "West Side Story" collaborator, director-choreographer Jerome Robbins, had earned a laugh before he even spoke, thanks to Laurents' introductory words: "Fearless as Lenny was, there were two figures he did fear -- God and Jerome Robbins" .</s>
</P>
<P>

<s docid="LA121490-0148" num="16" wdcount="37"> After noting that he wished he were young enough to pay homage to Bernstein by performing the sailor's variation he created in the ballet "Fancy Free," Robbins, 72, recalled that halcyon 1944 collaboration between the two 25-year-olds.</s>

<s docid="LA121490-0148" num="17" wdcount="25"> He also reflected on the joyous nature of their 1957 "West Side Story" collaboration, even while the show faced repeated obstacles before reaching Broadway .</s>
</P>
<P>

<s docid="LA121490-0148" num="18" wdcount="8"> "Lenny's music was the lifeblood of that show.</s>

<s docid="LA121490-0148" num="19" wdcount="30"> His theater scores weren't just a collection of songs but were more like a symphonic work," noted Robbins, who also collaborated on several other ballet and theater works with Bernstein.</s>

<s docid="LA121490-0148" num="20" wdcount="15"> He concluded in subdued tones, "We have lost a maker and shaker of our century.</s>

<s docid="LA121490-0148" num="21" wdcount="7"> A light went out for me" .</s>
</P>
<P>

<s docid="LA121490-0148" num="22" wdcount="18"> Carol Lawrence, the original Maria of "West Side Story," sang a medley of "I Feel Pretty" and "Tonight".</s>

<s docid="LA121490-0148" num="23" wdcount="42"> The "West Side Story" reunion was not as complete as had been scheduled; Larry Kert was unable to be there, and Stephen Sondheim (who, then a newcomer to Broadway, wrote the lyrics) could not attend due to illness in his family .</s>
</P>
<P>

<s docid="LA121490-0148" num="24" wdcount="14"> Original cast members from Bernstein shows sang numbers they had helped launch into history.</s>

<s docid="LA121490-0148" num="25" wdcount="13"> Nancy Walker sang her sassy "I Can Cook Too" from "On the Town".</s>

<s docid="LA121490-0148" num="26" wdcount="36"> Her fellow cast members, Betty Comden and Adolph Green (who also teamed with Bernstein as the show's creators), after fondly recalling their 50-year friendship with Bernstein, poignantly sang the show's bittersweet finale, "Some Other Time" .</s>
</P>
<P>

<s docid="LA121490-0148" num="27" wdcount="21"> Barbara Cook, the original Cunegonde in Bernstein's "Candide" (1956), displayed her still-gleaming voice in "A Simple Song" from Bernstein's 1971 "Mass".</s>

<s docid="LA121490-0148" num="28" wdcount="21"> "Candide" itself was represented by "Glitter and Be Gay," the coloratura aria Cook made famous, as performed by Constance Haumann .</s>
</P>
<P>

<s docid="LA121490-0148" num="29" wdcount="28"> Winging in from the West Coast (as was Walker) was Lauren Bacall, who teamed up with Phyllis Newman for a sly rendition of "Ohio" from Bernstein's "Wonderful Town".</s>

<s docid="LA121490-0148" num="30" wdcount="26"> Kurt Ollmann, familiar from Bernstein's 1985 "West Side Story" recording, sang "Take Care of This House" from Bernstein's last (1976), unsuccessful, Broadway show, "1600 Pennsylvania Ave".</s>

<s docid="LA121490-0148" num="31" wdcount="12"> -- a work the composer often spoke of wanting to revise .</s>
</P>
<P>

<s docid="LA121490-0148" num="32" wdcount="28"> Bernstein's son, Alexander, delivered a funny, knowing, affectionate talk about his father's unappreciated skills as an actor, singer and dancer as only a family member could know them.</s>

<s docid="LA121490-0148" num="33" wdcount="36"> Michael Wager, a very close friend of Bernstein's who was with him at the end, spoke movingly of how difficult it was for Bernstein to continue when illness had robbed him of his creative energy .</s>
</P>
<P>

<s docid="LA121490-0148" num="34" wdcount="48"> Marilyn Horne closed the program with "Somewhere," the emotional anthem from "West Side Story," after which Laurents directed the audience's attention to the large photo that hung over the stage: an exuberant 39-year-old Bernstein, nearly levitating outside the theater where "West Side Story" had opened in Washington .</s>
</P>
<P>

<s docid="LA121490-0148" num="35" wdcount="28"> Since "Lenny didn't like silence," Laurents asked instead for a final round of applause for the man who inspired and moved so many people for so many years.</s>

<s docid="LA121490-0148" num="36" wdcount="9"> The audience responded with a sustained standing ovation .</s>
</P>
</TEXT>
<SUBJECT>
<P>

<s docid="LA121490-0148" num="37" wdcount="3"> MEMORIALS; BERNSTEIN, LEONARD</s>
</P>
</SUBJECT>
</DOC>
