<DOC>
<DOCNO>

<s docid="AP891018-0301" num="1" wdcount="1"> AP891018-0301</s>
</DOCNO>
<FILEID>

<s docid="AP891018-0301" num="2" wdcount="2"> AP-NR-10-18-89 1832EDT</s>
</FILEID>
<FIRST>

<s docid="AP891018-0301" num="3" wdcount="5"> u f AM-SFQuake-Insurance 10-18 0653</s>
</FIRST>
<SECOND>

<s docid="AP891018-0301" num="4" wdcount="2"> AM-SF Quake-Insurance,0672</s>
</SECOND>
<HEAD>

<s docid="AP891018-0301" num="5" wdcount="10"> Many Homeowners Not Insured; Analysts Say Disaster May Benefit Insurers</s>
</HEAD>
<BYLINE>

<s docid="AP891018-0301" num="6" wdcount="3"> By DEAN GOLEMBESKI</s>
</BYLINE>
<BYLINE>

<s docid="AP891018-0301" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP891018-0301" num="8" wdcount="3"> HARTFORD, Conn. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP891018-0301" num="9" wdcount="34"> Most San Francisco-area homeowners may have to pay for damage from Tuesday's earthquake out of their own pockets, while insurance companies may reap long-term benefits from higher rates, industry spokesmen and analysts said Wednesday.</s>

<s docid="AP891018-0301" num="10" wdcount="35"> Only 15 percent to 20 percent of California homeowners have earthquake insurance, which typically requires a 10 percent deductible and costs between $200 to $400 a year for a $100,000 home, according to industry spokesmen.</s>

<s docid="AP891018-0301" num="11" wdcount="26"> The Association of California Insurance Cos. in Sacramento said that in the San Francisco area roughly 25 to 30 percent of the homes have earthquake insurance.</s>

<s docid="AP891018-0301" num="12" wdcount="23"> The organization estimated residential damages from Tuesday's earthquake at $500 million in the Bay area, with between $100 million to $150 million insured.</s>

<s docid="AP891018-0301" num="13" wdcount="40"> Insured homeowners without earthquake protection will get reimbursed only if their homes were ravaged by fire, which is covered under basic homeowner insurance polices, said Hugh Strawn, director of catastrophe services at the Property Loss Research Bureau in Schaumburg, Ill.</s>

<s docid="AP891018-0301" num="14" wdcount="17"> Insurance companies attempted Wednesday to assess the amount of quake-related damages they're likely to have to pay.</s>

<s docid="AP891018-0301" num="15" wdcount="31"> In addition to home damage, the companies likely will get claims for automobile damage, broken glass, theft and burglary, business interruption due to electrical outages, water damage and, possibly, workers compensation.</s>

<s docid="AP891018-0301" num="16" wdcount="15"> Some estimated that insurers might face bills totaling $1 billion or more from the quake.</s>

<s docid="AP891018-0301" num="17" wdcount="17"> But industry observers said they don't expect any company to suffer serious financial damage from quake-related claims.</s>

<s docid="AP891018-0301" num="18" wdcount="27"> ``We don't think any company is going to have problems paying claims,'' said Elisa Siegal, public affairs manager for the American Insurance Association, a Washington-based trade group.</s>

<s docid="AP891018-0301" num="19" wdcount="5"> The insurers actually could benefit.</s>

<s docid="AP891018-0301" num="20" wdcount="51"> Industry analysts predicted insurers would be able to reverse three years of declining rates and win rate hikes from state regulators due to the quake damages and the estimated $4 billion in damages from Hurricane Hugo, which hammered South Carolina and other parts of the southeastern United States earlier this month.</s>

<s docid="AP891018-0301" num="21" wdcount="17"> An increase in insurance rates could translate into greater profitability in the long term, the analysts said.</s>

<s docid="AP891018-0301" num="22" wdcount="10"> ``There's a perception that this could turn the cycle ...</s>

<s docid="AP891018-0301" num="23" wdcount="23"> that this could be enough to firm pricing,'' said Gloria L. Vogel, an analyst with Bear, Stearns & Co. Inc. in New York.</s>

<s docid="AP891018-0301" num="24" wdcount="21"> Despite their predictions for the long run, the analysts warned that fourth-quarter earnings among insurance companies are likely to be disappointing.</s>

<s docid="AP891018-0301" num="25" wdcount="21"> ``It's going to be a meaningful loss, perhaps as big as Hugo,'' said Robert Glasspiegel, an analyst with Hartford-based Langen McAlenney.</s>

<s docid="AP891018-0301" num="26" wdcount="13"> On the New York Stock Exchange, some insurance company stock rose on Wednesday.</s>

<s docid="AP891018-0301" num="27" wdcount="31"> Aetna Life & Casualty Co. rose $2.37 to $59.50 a share; ITT Corp., parent of The Hartford, was up 37 cents to $59; and the Travelers Cos. rose $1 to $40.87.</s>

<s docid="AP891018-0301" num="28" wdcount="11"> Reinsurance companies, which absorb risk from policy writers, did especially well.</s>

<s docid="AP891018-0301" num="29" wdcount="16"> General Re Corp. rose $2.75 to $86.50 and Marsh & McLennan Cos. rose $3.12 to $75.87.</s>

<s docid="AP891018-0301" num="30" wdcount="10"> In California, earthquake insurance is an emotional and politically-charged issue.</s>

<s docid="AP891018-0301" num="31" wdcount="25"> Roughly two-thirds of all insurance policies written in the United States are sold in California, where many of the nation's most damaging earthquakes have occurred..</s>

<s docid="AP891018-0301" num="32" wdcount="23"> Under a 1985 California law, insurers are required to offer earthquake insurance to homebuyers, but homebuyers are not required to buy the coverage.</s>

<s docid="AP891018-0301" num="33" wdcount="26"> Insurers aren't required to offer earthquake insurance to commercial property owners, but the percentage of business property with the coverage is very high, industry spokesmen said.</s>

<s docid="AP891018-0301" num="34" wdcount="15"> They estimated that at least 25 percent, and probably many more, business properties are insured.</s>

<s docid="AP891018-0301" num="35" wdcount="22"> Because of its high costs, earthquake insurance has become a target of the controversial Proposition 103 approved by California voters last year.</s>

<s docid="AP891018-0301" num="36" wdcount="11"> The proposition calls for a 20 percent rollback in insurance rates.</s>

<s docid="AP891018-0301" num="37" wdcount="14"> Insurers and state regulators are battling over the rates and how they're set .</s>
</TEXT>
</DOC>
