<DOC>
<DOCNO>

<s docid="LA102489-0131" num="1" wdcount="1"> LA102489-0131</s>
</DOCNO>
<DOCID>

<s docid="LA102489-0131" num="2" wdcount="1"> 125161</s>
</DOCID>
<DATE>
<P>

<s docid="LA102489-0131" num="3" wdcount="6"> October 24, 1989, Tuesday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA102489-0131" num="4" wdcount="10"> Metro; Part B; Page 6; Column 1; Editorial Writers Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA102489-0131" num="5" wdcount="2"> 652 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA102489-0131" num="6" wdcount="5"> A SPECIAL SESSION, WITH SPEED</s>
</P>
</HEADLINE>
<TEXT>
<P>

<s docid="LA102489-0131" num="7" wdcount="28"> Gov. George Deukmejian is right to call the Legislature into special session within the next two weeks to deal with the effects of last Tuesday's Northern California earthquake.</s>

<s docid="LA102489-0131" num="8" wdcount="44"> With Congress already moving to grant up to $3 billion in relief, earthquake victims need to know that state officials are prepared to come up with the state's share of disaster and reconstruction aid as soon as possible, and as soon as is practical.</s>

<s docid="LA102489-0131" num="9" wdcount="30"> Deukmejian should be commended, as well, for advising state officials to do all they can to expedite aid to earthquake victims without getting too tangled up in red tape .</s>
</P>
<P>

<s docid="LA102489-0131" num="10" wdcount="42"> The governor is wrong, however, in his campaign to distance himself from the California Department of Transportation on the issue of what caused the Nimitz Freeway in Oakland to collapse, and what could or should have been done to have prevented it.</s>

<s docid="LA102489-0131" num="11" wdcount="28"> While Deukmejian is not necessarily blaming Caltrans, he seems to be preparing himself for such investigatory questions as: "What did you know and when did you know it"?</s>
</P>
<P>

<s docid="LA102489-0131" num="12" wdcount="31"> The governor's answer, which he has been repeating ever since the day of the quake, was that no one in Caltrans ever told him a freeway might collapse in an earthquake.</s>

<s docid="LA102489-0131" num="13" wdcount="9"> He was shocked that such a thing would happen.</s>

<s docid="LA102489-0131" num="14" wdcount="36"> This has the earmarks of a preemptive defense against any allegation that California stinted on highway reinforcement because transportation funds have been short during his administration, possibly because he had opposed a gasoline tax increase .</s>
</P>
<P>

<s docid="LA102489-0131" num="15" wdcount="18"> There is keen interest, of course, in why the freeway collapsed, and whether something might have been done.</s>

<s docid="LA102489-0131" num="16" wdcount="25"> The major reason is so that California can learn from the experience as it designs new roads and reinforces existing ones against the next quake.</s>

<s docid="LA102489-0131" num="17" wdcount="9"> There has been no widespread outcry against the governor.</s>

<s docid="LA102489-0131" num="18" wdcount="28"> While the Department of Transportation and the state Transportation Commission do exercise considerable control over the allocation of highway funds, the governor also sets general state priorities .</s>
</P>
<P>

<s docid="LA102489-0131" num="19" wdcount="25"> The governor complained on Sunday that the highway engineers never came to him and told him that bridges or freeways might collapse in an earthquake.</s>

<s docid="LA102489-0131" num="20" wdcount="31"> But no one who has lived in California more than a few months would rule out the chance that any bridge or freeway could collapse in the right kind of earthquake.</s>

<s docid="LA102489-0131" num="21" wdcount="19"> California is on the edge of earthquake-related technology, but still does not know everything that needs to be known.</s>

<s docid="LA102489-0131" num="22" wdcount="22"> The state learns more from every earthquake and a critical need now is to learn everything possible from Tuesday, Oct. 17 .</s>
</P>
<P>

<s docid="LA102489-0131" num="23" wdcount="44"> But it is also the time to concentrate on helping quake victims through these most trying days of their experience -- the period when the emergency response is over and people face the dreary details of restoring their life to some kind of normality.</s>

<s docid="LA102489-0131" num="24" wdcount="26"> In the Bay Area, that includes hundreds of thousands of commuters who did not suffer personal damage, but face massive obstacles in getting to work .</s>
</P>
<P>

<s docid="LA102489-0131" num="25" wdcount="20"> The governor and legislative leaders will meet again next Monday to determine the timing and agenda of a special session.</s>

<s docid="LA102489-0131" num="26" wdcount="26"> It almost certainly would include a temporary gasoline-tax increase to deal with highway reconstruction and repair and possible general revenues for other forms of disaster relief.</s>

<s docid="LA102489-0131" num="27" wdcount="25"> Existing law already gives the governor considerable discretion in diverting reserve funds on hand to the Office of Emergency Services for allocation to local governments.</s>

<s docid="LA102489-0131" num="28" wdcount="9"> But the need could well exceed the present reserve.</s>

<s docid="LA102489-0131" num="29" wdcount="13"> The scope of the disaster would seem to justify a temporary surcharge .</s>
</P>
<P>

<s docid="LA102489-0131" num="30" wdcount="34"> The governor and Legislature should not wait too long to start the session, although they do not yet have precise damage estimates or know just how much the federal government will send to California.</s>

<s docid="LA102489-0131" num="31" wdcount="25"> The Legislature can begin organizing its staff and committees now so the appropriate legislation can be passed as soon as that information is obtained .</s>
</P>
</TEXT>
<TYPE>
<P>

<s docid="LA102489-0131" num="32" wdcount="1"> Editorial</s>
</P>
</TYPE>
</DOC>
