<DOC>
<DOCNO>

<s docid="WSJ891019-0021" num="1" wdcount="1"> WSJ891019-0021</s>
</DOCNO>
<DD>

<s docid="WSJ891019-0021" num="2" wdcount="2"> = 891019</s>
</DD>
<AN>

<s docid="WSJ891019-0021" num="3" wdcount="2"> 891019-0021 .</s>
</AN>
<HL>

<s docid="WSJ891019-0021" num="4" wdcount="15"> The Bay Area Earthquake: @ Bush Makes Sure He Acts @ Speedily on Quake Crisis</s>
</HL>
<DD>

<s docid="WSJ891019-0021" num="5" wdcount="1"> 10/19/89</s>
</DD>
<SO>

<s docid="WSJ891019-0021" num="6" wdcount="4"> WALL STREET JOURNAL (J)</s>
</SO>
<GV>

<s docid="WSJ891019-0021" num="7" wdcount="2"> EXECUTIVE (EXE)</s>
</GV>
<DATELINE>

<s docid="WSJ891019-0021" num="8" wdcount="1"> WASHINGTON</s>
</DATELINE>
<TEXT>

<s docid="WSJ891019-0021" num="9" wdcount="15"> The White House is making sure nobody will accuse it of taking this crisis lightly.</s>

<s docid="WSJ891019-0021" num="10" wdcount="21"> In the aftermath of the California earthquake, President Bush and his aides flew into a whirlwind of earthquake-related activity yesterday morning.</s>

<s docid="WSJ891019-0021" num="11" wdcount="27"> Some of it was necessary to get federal help flowing to victims, but some seemed designed mostly to project an image of a White House in action.</s>

<s docid="WSJ891019-0021" num="12" wdcount="40"> Mr. Bush and his aides were accused of responding too slowly after the Exxon Valdez oil tanker split open in Alaskan waters and Hurricane Hugo struck the Carolina coast, and they clearly don't want a repeat of those charges now.</s>

<s docid="WSJ891019-0021" num="13" wdcount="25"> So the White House announced that Mr. Bush got his first earthquake briefing of the day at 6:30 a.m. from chief of staff John Sununu.</s>

<s docid="WSJ891019-0021" num="14" wdcount="42"> By noon, Mr. Bush had taken two phone calls from Vice President Dan Quayle, who was in California; made a televised statement of concern; signed a disaster proclamation; received a written report from the Federal Emergency Management Agency; and visited FEMA headquarters.</s>

<s docid="WSJ891019-0021" num="15" wdcount="16"> Mr. Bush himself essentially acknowledged that he and his aides were trying to head off criticism.</s>

<s docid="WSJ891019-0021" num="16" wdcount="35"> On his FEMA visit, Mr. Bush said that he hoped there would be "less carping" about the emergency office's performance this time, adding that the agency "took a hit" for its reaction to Hurricane Hugo.</s>

<s docid="WSJ891019-0021" num="17" wdcount="16"> The White House already is talking of Mr. Bush visiting the California earthquake site this weekend.</s>

<s docid="WSJ891019-0021" num="18" wdcount="17"> He visited the Hugo devastation but not until after local leaders urged him to do so .</s>
</TEXT>
</DOC>
