<DOC>
<DOCNO>

<s docid="WSJ891019-0086" num="1" wdcount="1"> WSJ891019-0086</s>
</DOCNO>
<DD>

<s docid="WSJ891019-0086" num="2" wdcount="2"> = 891019</s>
</DD>
<AN>

<s docid="WSJ891019-0086" num="3" wdcount="2"> 891019-0086 .</s>
</AN>
<HL>

<s docid="WSJ891019-0086" num="4" wdcount="32"> The Bay Area Earthquake: @ Insurance Firms Expected @ To Pay Billions of Dollars @ ---- @ By Beatrice E. Garcia and Karen Slater @ Staff Reporters of The Wall Street Journal</s>
</HL>
<DD>

<s docid="WSJ891019-0086" num="5" wdcount="1"> 10/19/89</s>
</DD>
<SO>

<s docid="WSJ891019-0086" num="6" wdcount="4"> WALL STREET JOURNAL (J)</s>
</SO>
<CO>

<s docid="WSJ891019-0086" num="7" wdcount="7"> S AET FFC CI AIG GRN MMC</s>
</CO>
<IN>

<s docid="WSJ891019-0086" num="8" wdcount="2"> INSURANCE (INS)</s>
</IN>
<TEXT>

<s docid="WSJ891019-0086" num="9" wdcount="18"> Insurers face the prospect of paying out billions of dollars for damages caused by this week's California earthquake.</s>

<s docid="WSJ891019-0086" num="10" wdcount="32"> Getting a grip on the extent of the damages is proving a far more difficult task than what insurers faced after Hurricane Hugo ripped through the Caribbean and the Carolinas last month.</s>

<s docid="WSJ891019-0086" num="11" wdcount="34"> The earthquake's toll, including possible deep structural damage, goes far beyond the more easily observed damage from a hurricane, says George Reider, a vice president in Aetna Life & Casualty Insurance Co.'s claims division.</s>

<s docid="WSJ891019-0086" num="12" wdcount="33"> But investors are betting that the financial and psychological impact of the earthquake, coming so soon after the hurricane, will help stem more than two years of intense price-cutting wars among business insurers.</s>

<s docid="WSJ891019-0086" num="13" wdcount="8"> Reflecting that logic, insurance-company stocks posted strong gains.</s>

<s docid="WSJ891019-0086" num="14" wdcount="15"> Aetna and other insurers are hiring engineers and architects to help them assess structural damage.</s>

<s docid="WSJ891019-0086" num="15" wdcount="18"> Most insurers already have mobilized their "catastrophe" teams to begin processing claims from their policyholders in northern California.</s>

<s docid="WSJ891019-0086" num="16" wdcount="31"> Since commercial air travel is interrupted, Aetna, based in Hartford, Conn., chartered three planes to fly claims adjusters into Sacramento and then planned for them to drive to the Bay area.</s>

<s docid="WSJ891019-0086" num="17" wdcount="16"> About 25 adjusters were dispatched yesterday afternoon, along with laptop computers, cellular phones and blank checks.</s>

<s docid="WSJ891019-0086" num="18" wdcount="27"> Some adjusters, already in other parts of California, drove to the disaster area with recreational vehicles and mobile homes that could be used as makeshift claims-processing centers.</s>

<s docid="WSJ891019-0086" num="19" wdcount="24"> Insurers will be advertising 800 numbers -- probably on the radio -- that policyholders can call to get assistance on how to submit claims.</s>

<s docid="WSJ891019-0086" num="20" wdcount="41"> State Farm Mutual Automobile Insurance Co., the largest home and auto insurer in California, believes the losses from the earthquake could be somewhat less than the $475 million in damages it expects to pay out for claims resulting from Hurricane Hugo.</s>

<s docid="WSJ891019-0086" num="21" wdcount="17"> State Farm, based in Bloomington, Ind., is also the largest writer of personal-property earthquake insurance in California.</s>

<s docid="WSJ891019-0086" num="22" wdcount="26"> Earthquake insurance is sold as a separate policy or a specific endorsement "rider" on a homeowner's policy in California, because of the area's vulnerability to earthquakes.</s>

<s docid="WSJ891019-0086" num="23" wdcount="15"> State Farm said about 25% of its policyholders in California have also purchased earthquake insurance.</s>

<s docid="WSJ891019-0086" num="24" wdcount="31"> Allstate Insurance Co., a unit of Sears, Roebuck & Co., said about 23% of its personal property policyholders -- about 28% in the San Franciso area -- also have earthquake coverage.</s>

<s docid="WSJ891019-0086" num="25" wdcount="26"> The Association of California Insurance Companies estimated damage to residential property could total $500 million, but only $100 million to $150 million is insured, it said.</s>

<s docid="WSJ891019-0086" num="26" wdcount="31"> Officials from the American Insurance Association's property-claim service division, which coordinates the efforts of the claims adjusters in an area after a natural disaster, will be flying to San Francisco today.</s>

<s docid="WSJ891019-0086" num="27" wdcount="15"> They expect to have a preliminary estimate of the damages in a day or two.</s>

<s docid="WSJ891019-0086" num="28" wdcount="17"> Roads and bridges in the Bay area appear to have suffered some of the most costly damage.</s>

<s docid="WSJ891019-0086" num="29" wdcount="17"> Highways, such as the section of Interstate 880 that collapsed in Oakland, generally don't have insurance coverage.</s>

<s docid="WSJ891019-0086" num="30" wdcount="34"> Industry officials say the Bay Bridge -- unlike some bridges -- has no earthquake coverage, either, so the cost of repairing it probably would have to be paid out of state general operating funds.</s>

<s docid="WSJ891019-0086" num="31" wdcount="33"> However, the bridge, which charges a $1 toll each way, does have "loss of income" insurance to replace lost revenue if the operation of the bridge is interrupted for more than seven days.</s>

<s docid="WSJ891019-0086" num="32" wdcount="24"> That coverage is provided by a syndicate of insurance companies including Fireman's Fund Corp., based in Novato, Calif., and Cigna Corp., based in Philadelphia.</s>

<s docid="WSJ891019-0086" num="33" wdcount="16"> Earthquake-related claims aren't expected to cause significant financial problems for the insurance industry as a whole.</s>

<s docid="WSJ891019-0086" num="34" wdcount="33"> Instead, even with the liabilities of two natural disasters in recent weeks, analysts said the total capital of the industry is likely to be higher at year end than it was at midyear.</s>

<s docid="WSJ891019-0086" num="35" wdcount="17"> Indeed, the earthquake could contribute to a turnaround in the insurance cycle in a couple of ways.</s>

<s docid="WSJ891019-0086" num="36" wdcount="20"> For example, insurers may seek to limit their future exposure to catastrophes by increasing the amount of reinsurance they buy.</s>

<s docid="WSJ891019-0086" num="37" wdcount="35"> Such increased demand for reinsurance, along with the losses the reinsurers will bear from these two disasters, are likely to spur increases in reinsurance prices that will later be translated into an overall price rise.</s>

<s docid="WSJ891019-0086" num="38" wdcount="10"> Reinsurance is protection taken out by the insurance firms themselves.</s>

<s docid="WSJ891019-0086" num="39" wdcount="38"> "We are saying this is the breaking point, this is the event that will change the psychology of the marketplace," said William Yankus, an analyst with Conning & Co., a Hartford firm that specializes in the insurance industry.</s>

<s docid="WSJ891019-0086" num="40" wdcount="14"> His firm, along with some others, issued new buy recommendations on insurer stocks yesterday.</s>

<s docid="WSJ891019-0086" num="41" wdcount="35"> Among the insurance stocks, big gainers included American International Group, up $3.25 to $102.625; General Re Corp., up $2.75 to $86.50; Aetna, up $2.375 to $59.50; and Marsh & McLennan Inc., up $3.125 to $75.875.</s>

<s docid="WSJ891019-0086" num="42" wdcount="12"> Still, a few individual companies, most likely smaller ones, could be devastated.</s>

<s docid="WSJ891019-0086" num="43" wdcount="24"> "I think there is a damned good chance someone is going to hit the skids on this," said Oppenheimer & Co. analyst Myron Picoult.</s>

<s docid="WSJ891019-0086" num="44" wdcount="24"> He suspects some insurers who had purchased reinsurance to limit their exposure to catastrophes will discover that reinsurance was used up by Hurricane Hugo.</s>

<s docid="WSJ891019-0086" num="45" wdcount="19"> British, West German, Scandinavian and other overseas insurers are bracing for big claims from the San Francisco earthquake disaster.</s>

<s docid="WSJ891019-0086" num="46" wdcount="23"> Although it's unclear how much exposure the London market will face, U.K. underwriters traditionally have a large reinsurance exposure to U.S. catastrophe coverage.</s>

<s docid="WSJ891019-0086" num="47" wdcount="20"> Jack Byrne, chairman of Fireman's Fund, said this disaster will test the catastrophe reinsurance market, causing these rates to soar.</s>

<s docid="WSJ891019-0086" num="48" wdcount="29"> The catastrophe losses sustained by insurers this year will probably be the worst on an inflation-adjusted basis since 1906 -- when another earthquake sparked the Great San Francisco Fire.</s>

<s docid="WSJ891019-0086" num="49" wdcount="25"> Orin Kramer, an insurance consultant in New York, estimates that the 1906 San Francisco destruction, on an inflation-adjusted basis, included insured losses of $5.8 billion.</s>

<s docid="WSJ891019-0086" num="50" wdcount="28"> He is estimating this week's disaster will generate insured losses of $2 billion to $4 billion, following about $4 billion in costs to insurers from Hurricane Hugo .</s>
</TEXT>
</DOC>
