<DOC>
<DOCNO>

<s docid="AP880921-0201" num="1" wdcount="1"> AP880921-0201</s>
</DOCNO>
<FILEID>

<s docid="AP880921-0201" num="2" wdcount="2"> AP-PX-09-21-88 1144EDT</s>
</FILEID>
<FIRST>

<s docid="AP880921-0201" num="3" wdcount="6"> s e BC-APArts:Goldman ADV25 09-21 0660</s>
</FIRST>
<SECOND>

<s docid="AP880921-0201" num="4" wdcount="5"> BC-AP Arts: Goldman, ADV 25,0675</s>
</SECOND>
<NOTE>

<s docid="AP880921-0201" num="5" wdcount="1"> $Adv25</s>
</NOTE>
<NOTE>

<s docid="AP880921-0201" num="6" wdcount="7"> For Release Sunday, Sept 25, and Thereafter</s>
</NOTE>
<HEAD>

<s docid="AP880921-0201" num="7" wdcount="6"> `Lennon' Biographer Sticks to His Guns</s>
</HEAD>
<HEAD>

<s docid="AP880921-0201" num="8" wdcount="5"> With BC-AP Arts: Lennon Furor</s>
</HEAD>
<BYLINE>

<s docid="AP880921-0201" num="9" wdcount="3"> By LARRY McSHANE</s>
</BYLINE>
<BYLINE>

<s docid="AP880921-0201" num="10" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880921-0201" num="11" wdcount="3"> NEW YORK (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880921-0201" num="12" wdcount="28"> When celebrity biographer Albert Goldman began digging into ``The Lives of John Lennon,'' his first move was to mail a long, reverential request for help to Yoko Ono.</s>

<s docid="AP880921-0201" num="13" wdcount="10"> ``She was Numero Uno, you've got to start with her.</s>

<s docid="AP880921-0201" num="14" wdcount="20"> I sent her a sincere letter, because at that time I was a true believer in rock's greatest love story.</s>

<s docid="AP880921-0201" num="15" wdcount="10"> ... I told her, `I'm in your corner,''' Goldman recalled.</s>

<s docid="AP880921-0201" num="16" wdcount="3"> Ono never responded.</s>

<s docid="AP880921-0201" num="17" wdcount="21"> And after 1,200 interviews and 6 years, the dream was over for Goldman, his mythic view of Lennon the Great altered.</s>

<s docid="AP880921-0201" num="18" wdcount="34"> Expecting the best, Goldman claims to have uncovered the worst: a volatile, debauched Lennon who evolved into the Howard Hughes of rock 'n' roll, tucked in his Dakota bed for days at a time.</s>

<s docid="AP880921-0201" num="19" wdcount="35"> That vision of the ex-Beatle has infuriated Lennon supporters, family and friends and prompted charges of fiction writing; it also taught Goldman _ who says he is a John Lennon fan _ a hard lesson.</s>

<s docid="AP880921-0201" num="20" wdcount="7"> ``It doesn't pay to meet your idols.</s>

<s docid="AP880921-0201" num="21" wdcount="11"> Just enjoy them; don't try to see the reality,'' Goldman said.</s>

<s docid="AP880921-0201" num="22" wdcount="8"> ``My books are a cold dose of reality.</s>

<s docid="AP880921-0201" num="23" wdcount="12"> You get in the Beatle shower, and suddenly the water goes cold''.</s>

<s docid="AP880921-0201" num="24" wdcount="32"> Goldman, whose past tell-all biographies dealt with Elvis Presley and Lenny Bruce, remains unmoved by the hue and cry from the music industry, from Ono and from Lennon's Beatle buddy, Paul McCartney.</s>

<s docid="AP880921-0201" num="25" wdcount="16"> ``My books are bad for business,'' Goldman said in a phone interview from Munich, West Germany.</s>

<s docid="AP880921-0201" num="26" wdcount="17"> ``They're bad for Paul's business, bad for Yoko's business, back for the jive myth of rock business.</s>

<s docid="AP880921-0201" num="27" wdcount="6"> Those people have to hate me''.</s>

<s docid="AP880921-0201" num="28" wdcount="9"> Myth-shattering is a not a bad thing, Goldman said.</s>

<s docid="AP880921-0201" num="29" wdcount="13"> For example, he cites Lennon's disillusioning meeting with Presley at Graceland in 1965.</s>

<s docid="AP880921-0201" num="30" wdcount="6"> ``John was very hooked into Elvis.</s>

<s docid="AP880921-0201" num="31" wdcount="8"> Elvis was his measure of success,'' said Goldman.</s>

<s docid="AP880921-0201" num="32" wdcount="6"> ``And the myth of Elvis: awesome.</s>

<s docid="AP880921-0201" num="33" wdcount="7"> But the reality of Elvis: a mess''.</s>

<s docid="AP880921-0201" num="34" wdcount="30"> Goldman also rejected the complaint raised by Ono, McCartney, Julian Lennon and others that Lennon is an easy target to defame because he's no longer around to answer the allegations.</s>

<s docid="AP880921-0201" num="35" wdcount="7"> ``You can't say John lacks for defenders.</s>

<s docid="AP880921-0201" num="36" wdcount="4"> And Yoko isn't dead.</s>

<s docid="AP880921-0201" num="37" wdcount="6"> Colonel Parker (Presley's manager) isn't dead.</s>

<s docid="AP880921-0201" num="38" wdcount="10"> Ninety-five percent of the people in my books aren't dead.</s>

<s docid="AP880921-0201" num="39" wdcount="11"> They can do something about it,'' said Goldman, his voice quickening.</s>

<s docid="AP880921-0201" num="40" wdcount="11"> ``This business of making it easy for defending myself is insane.</s>

<s docid="AP880921-0201" num="41" wdcount="7"> I'm the target of scores of attacks.</s>

<s docid="AP880921-0201" num="42" wdcount="9"> I can't imagine a harder thing for an author''.</s>

<s docid="AP880921-0201" num="43" wdcount="21"> Those attacks don't really bother him, unless they come from someone who hasn't read ``The Lives of John Lennon,'' Goldman said.</s>

<s docid="AP880921-0201" num="44" wdcount="9"> ``A lot of people already made up their minds.</s>

<s docid="AP880921-0201" num="45" wdcount="28"> They hear Albert Goldman, John Lennon, homosexuality _ bang, let him have it! I resent people commenting on a book they haven't read, including Yoko,'' the author said.</s>

<s docid="AP880921-0201" num="46" wdcount="11"> Ono's reaction came on a nationally broadcast response to the book.</s>

<s docid="AP880921-0201" num="47" wdcount="24"> She labeled Goldman's version of life with the Lennons ``totally fiction'' and brought out Lennon's sons, Julian and 12-year-old Sean, to refute the biography.</s>

<s docid="AP880921-0201" num="48" wdcount="23"> ``These giant promotions of Yoko are presented as honest documentaries, when they're in-house documentaries,'' said Goldman, who complimented Ono on a well-prepared show.</s>

<s docid="AP880921-0201" num="49" wdcount="4"> ``She takes no chances.</s>

<s docid="AP880921-0201" num="50" wdcount="5"> This was another no-chance Yoko''.</s>

<s docid="AP880921-0201" num="51" wdcount="36"> As for the sensational charges of bisexuality, drug abuse by Yoko and John, wild drinking binges, anorexia and reclusiveness, Goldman says it all fits together with the image of Lennon presented by those who knew him.</s>

<s docid="AP880921-0201" num="52" wdcount="9"> ``My thesis is John Lennon was a divided mind.</s>

<s docid="AP880921-0201" num="53" wdcount="7"> Every yin had a yang,'' said Goldman.</s>

<s docid="AP880921-0201" num="54" wdcount="14"> ``There is nothing more natural than for John to try the other side (sexually).</s>

<s docid="AP880921-0201" num="55" wdcount="8"> That's just the kind of guy he was.</s>

<s docid="AP880921-0201" num="56" wdcount="6"> He wanted to try everything once.''</s>
</TEXT>
<NOTE>

<s docid="AP880921-0201" num="57" wdcount="5"> End Adv for Sept. 25</s>
</NOTE>
</DOC>
