<DOC>
<DOCNO>

<s docid="AP881007-0207" num="1" wdcount="1"> AP881007-0207</s>
</DOCNO>
<FILEID>

<s docid="AP881007-0207" num="2" wdcount="2"> AP-NR-10-07-88 1539EDT</s>
</FILEID>
<FIRST>

<s docid="AP881007-0207" num="3" wdcount="6"> s e BC-APArts:Lennon ADV09 10-07 1039</s>
</FIRST>
<SECOND>

<s docid="AP881007-0207" num="4" wdcount="5"> BC-AP Arts: Lennon, ADV 09,1104</s>
</SECOND>
<NOTE>

<s docid="AP881007-0207" num="5" wdcount="1"> $Adv09</s>
</NOTE>
<NOTE>

<s docid="AP881007-0207" num="6" wdcount="7"> For Release Sunday, Oct. 9, and Thereafter</s>
</NOTE>
<HEAD>

<s docid="AP881007-0207" num="7" wdcount="5"> Imagine: A John Lennon Elegy</s>
</HEAD>
<TEXT>

<s docid="AP881007-0207" num="8" wdcount="7"> ``I believe in fairies, the myths, dragons.</s>

<s docid="AP881007-0207" num="9" wdcount="9"> It all exists, even if it's in your mind.</s>

<s docid="AP881007-0207" num="10" wdcount="15"> Who's to say that dreams and nightmares aren't as real as the here and now?</s>

<s docid="AP881007-0207" num="11" wdcount="7"> Reality leaves a lot to the imagination''.</s>

<s docid="AP881007-0207" num="12" wdcount="4"> _ John Lennon .</s>
</TEXT>
<BYLINE>

<s docid="AP881007-0207" num="13" wdcount="3"> By MARY CAMPBELL</s>
</BYLINE>
<BYLINE>

<s docid="AP881007-0207" num="14" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP881007-0207" num="15" wdcount="3"> NEW YORK (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP881007-0207" num="16" wdcount="17"> Watching the new movie, ``Imagine: John Lennon,'' was very painful for the late Beatle's wife, Yoko Ono.</s>

<s docid="AP881007-0207" num="17" wdcount="25"> ``The only reason why I did watch it to the end is because I'm responsible for it, even though somebody else made it,'' she said.</s>

<s docid="AP881007-0207" num="18" wdcount="14"> Cassettes, film footage and other elements of the acclaimed movie were collected by Ono.</s>

<s docid="AP881007-0207" num="19" wdcount="20"> She also took cassettes of interviews by Lennon, which were edited in such a way that he narrates the picture.</s>

<s docid="AP881007-0207" num="20" wdcount="19"> Andrew Solt (``This Is Elvis'') directed, Solt and David L. Wolper produced and Solt and Sam Egan wrote it.</s>

<s docid="AP881007-0207" num="21" wdcount="17"> ``I think this is really the definitive documentary of John Lennon's life,'' Ono said in an interview.</s>

<s docid="AP881007-0207" num="22" wdcount="15"> ``What John was really about is depicted in this film, very accurately and without whitewashing.</s>

<s docid="AP881007-0207" num="23" wdcount="4"> ``I did view it.</s>

<s docid="AP881007-0207" num="24" wdcount="8"> I didn't have them take any footage out.</s>

<s docid="AP881007-0207" num="25" wdcount="4"> ``I wanted the truth.</s>

<s docid="AP881007-0207" num="26" wdcount="22"> In the sense you had to put a 40-year life into an hour and a half; balance is a very serious consideration.</s>

<s docid="AP881007-0207" num="27" wdcount="11"> I think they did a remarkable job and very tastefully so''.</s>

<s docid="AP881007-0207" num="28" wdcount="25"> There is a soundtrack album and a coffeetable book with comments primarily by Lennon, tied in with the film and using the same title .</s>
</TEXT>
<TEXT>

<s docid="AP881007-0207" num="29" wdcount="25"> ``Imagine there's no heaven ``It's easy if you try ``No hell below us ``Above us only sky ``Imagine all the people ``Living for today. ...''</s>
</TEXT>
<TEXT>

<s docid="AP881007-0207" num="30" wdcount="7"> ``Imagine'' is more than a Lennon elegy.</s>

<s docid="AP881007-0207" num="31" wdcount="36"> Though it fails to delve too deeply into the darker side of Lennon and the Beatles (drug use, abusive tempers, manager Brian Epstein's death), it does capture the music and the times in which Lennon lived.</s>

<s docid="AP881007-0207" num="32" wdcount="33"> One intriguing episode in ``Imagine'' shows cartoonist Al Capp (``L'il Abner'') being antagonistic toward the Lennons during their bed-in, when they stayed in bed for a week to publicize their concern for peace.</s>

<s docid="AP881007-0207" num="33" wdcount="5"> ``We were naive,'' Ono said.</s>

<s docid="AP881007-0207" num="34" wdcount="9"> ``A lot of things happened because we were naive.</s>

<s docid="AP881007-0207" num="35" wdcount="5"> Maybe that was our strength.</s>

<s docid="AP881007-0207" num="36" wdcount="21"> To us, Al Capp was just a cartoonist and you naturally assume a cartoonist is liberal, with a sense of humor.</s>

<s docid="AP881007-0207" num="37" wdcount="4"> We didn't expect hostility.</s>

<s docid="AP881007-0207" num="38" wdcount="8"> ``Al Capp is one incident that was filmed.</s>

<s docid="AP881007-0207" num="39" wdcount="14"> In those days we did numerous interviews because of our stand for world peace.</s>

<s docid="AP881007-0207" num="40" wdcount="7"> ... There were some very rough interviews.</s>

<s docid="AP881007-0207" num="41" wdcount="15"> The hostility that was shown to us bluntly by reporters in those days was incredible.</s>

<s docid="AP881007-0207" num="42" wdcount="7"> Each time, I think we were hurt''.</s>

<s docid="AP881007-0207" num="43" wdcount="11"> Ono said Lennon wrote the song ``Imagine'' in 1969 or '70.</s>

<s docid="AP881007-0207" num="44" wdcount="12"> ``We did the bed-in, the Toronto Peace Festival, the `War's Over' billboard.</s>

<s docid="AP881007-0207" num="45" wdcount="14"> He was saying we need an anthem for this whole concept of world peace.</s>

<s docid="AP881007-0207" num="46" wdcount="16"> I think it's one of the songs that will really go on forever in people's minds.''</s>
</TEXT>
<TEXT>

<s docid="AP881007-0207" num="47" wdcount="28"> ``Imagine there's no countries ``It isn't hard to do ``Nothing to kill or die for ``And no religion too ``Imagine all the people ``Living life in peace ...</s>

<s docid="AP881007-0207" num="48" wdcount="24"> ``You may say i'm a dreamer ``But i'm not the only one ``i hope someday you'll join us ``and the world be as one.''</s>
</TEXT>
<TEXT>

<s docid="AP881007-0207" num="49" wdcount="6"> Lennon was born Oct. 9, 1940.</s>

<s docid="AP881007-0207" num="50" wdcount="13"> He was shot and killed outside his Manhattan apartment on Dec. 8, 1980.</s>

<s docid="AP881007-0207" num="51" wdcount="8"> Ono was a painter when Lennon met her.</s>

<s docid="AP881007-0207" num="52" wdcount="12"> She later joined him in music and in public demonstrations for peace.</s>

<s docid="AP881007-0207" num="53" wdcount="35"> ``I think that for somebody like me, because I feel that I'm an artist and a creative artist, that it is a very strange turn of events that I'm known as a widow,'' she said.</s>

<s docid="AP881007-0207" num="54" wdcount="13"> ``But it is stranger to me that I'm not that disturbed by it.</s>

<s docid="AP881007-0207" num="55" wdcount="36"> I think that John promoted my work a lot in his lifetime and somehow it seems like it is a pleasure for me to sort of still work in a context of a partnership with him.</s>

<s docid="AP881007-0207" num="56" wdcount="10"> ... I think it is my turn to promote him.</s>

<s docid="AP881007-0207" num="57" wdcount="3"> He promoted me''.</s>

<s docid="AP881007-0207" num="58" wdcount="28"> When Albert Goldman's ``The Lives of John Lennon'' was published in September, depicting the former Beatle as riddled with vices, faults and neuroses, Ono called it ``totally fiction''.</s>

<s docid="AP881007-0207" num="59" wdcount="13"> Since then she's received a tremendous amount of support from friends and fans.</s>

<s docid="AP881007-0207" num="60" wdcount="20"> ``I was very touched and thankful that people sent letters to me and extended hands at this time, very warmly.</s>

<s docid="AP881007-0207" num="61" wdcount="4"> I really appreciate that.</s>

<s docid="AP881007-0207" num="62" wdcount="15"> I was also surprised that so many people stood up against it (the Goldman book).</s>

<s docid="AP881007-0207" num="63" wdcount="6"> I didn't expect that,'' Ono said.</s>

<s docid="AP881007-0207" num="64" wdcount="15"> Lennon's half sister, Julia Baird, also has written a new book, ``John Lennon, My Brother''.</s>

<s docid="AP881007-0207" num="65" wdcount="22"> She has no idea how many books have been written about Lennon; she's been sent some of them but hasn't read them.</s>

<s docid="AP881007-0207" num="66" wdcount="14"> ``I know the life and it is too painful to read somebody else's version''.</s>

<s docid="AP881007-0207" num="67" wdcount="18"> There's still enough footage, Ono said, for another movie _ perhaps a music or political or art film.</s>

<s docid="AP881007-0207" num="68" wdcount="10"> And there's another big John Lennon project on her horizon.</s>

<s docid="AP881007-0207" num="69" wdcount="11"> ``It's from unpublished songs which were written for a Broadway musical.</s>

<s docid="AP881007-0207" num="70" wdcount="10"> I don't know if it would have gotten to Broadway.</s>

<s docid="AP881007-0207" num="71" wdcount="7"> You aim for the stars, you know.</s>

<s docid="AP881007-0207" num="72" wdcount="6"> The songs might be strung together.</s>

<s docid="AP881007-0207" num="73" wdcount="10"> They might become a record, might eventually become a musical.</s>

<s docid="AP881007-0207" num="74" wdcount="5"> There are enough finished songs.</s>

<s docid="AP881007-0207" num="75" wdcount="7"> They were never recorded in the studio.</s>

<s docid="AP881007-0207" num="76" wdcount="3"> They're on cassettes''.</s>

<s docid="AP881007-0207" num="77" wdcount="18"> Their son Sean, 13, like his older half-brother, Julian, has become interested in music and started playing guitar.</s>

<s docid="AP881007-0207" num="78" wdcount="10"> ``I had reservations about Sean going into the music field.</s>

<s docid="AP881007-0207" num="79" wdcount="3"> I still do.</s>

<s docid="AP881007-0207" num="80" wdcount="10"> But I kind of gave up on it,'' Ono said.</s>

<s docid="AP881007-0207" num="81" wdcount="5"> ``He is into guitar now.</s>

<s docid="AP881007-0207" num="82" wdcount="10"> A session musician, a very good one, was teaching him.</s>

<s docid="AP881007-0207" num="83" wdcount="11"> According to this teacher, it seems like he is very good.</s>

<s docid="AP881007-0207" num="84" wdcount="23"> He is just totally involved in it, listening to Eric Clapton, Jimi Hendrix, his dad's songs _ only for guitar playing, I think.</s>

<s docid="AP881007-0207" num="85" wdcount="10"> ``He is into it so much, good luck to him.''</s>
</TEXT>
<NOTE>

<s docid="AP881007-0207" num="86" wdcount="2"> End Adv</s>
</NOTE>
</DOC>
