<DOC>
<DOCNO>

<s docid="AP880915-0066" num="1" wdcount="1"> AP880915-0066</s>
</DOCNO>
<FILEID>

<s docid="AP880915-0066" num="2" wdcount="2"> AP-NR-09-15-88 0608EDT</s>
</FILEID>
<FIRST>

<s docid="AP880915-0066" num="3" wdcount="5"> r a PM-Yoko-Biography 09-15 0563</s>
</FIRST>
<SECOND>

<s docid="AP880915-0066" num="4" wdcount="1"> PM-Yoko-Biography,0578</s>
</SECOND>
<HEAD>

<s docid="AP880915-0066" num="5" wdcount="6"> Yoko: Goldman's Lennon Bio `Totally Fiction'</s>
</HEAD>
<BYLINE>

<s docid="AP880915-0066" num="6" wdcount="3"> By LARRY McSHANE</s>
</BYLINE>
<BYLINE>

<s docid="AP880915-0066" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880915-0066" num="8" wdcount="3"> NEW YORK (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880915-0066" num="9" wdcount="32"> A biography that portrays John Lennon as a drug-addled, anorexic bisexual who raged his way from Liverpool to New York City is ``totally fiction,'' Yoko Ono said in a national radio broadcast.</s>

<s docid="AP880915-0066" num="10" wdcount="9"> ``It's amazing that somebody took such a poetic license.</s>

<s docid="AP880915-0066" num="11" wdcount="7"> I don't see John in there ...</s>

<s docid="AP880915-0066" num="12" wdcount="26"> It's a very dramatically described something, but it's not about John,'' Ono said Wednesday night in her first broadcast comments on the book by Albert Goldman.</s>

<s docid="AP880915-0066" num="13" wdcount="31"> The usually reclusive Ono agreed to the interview to counter Goldman's ``The Lives of John Lennon,'' which presents the ex-Beatle as a violent, drug-addicted drunk who wanted to dump his wife.</s>

<s docid="AP880915-0066" num="14" wdcount="19"> As for Ono, Goldman shows her as a gold-digger who snorted heroin up to the time of Lennon's death.</s>

<s docid="AP880915-0066" num="15" wdcount="30"> Goldman also charges she was responsible for Paul McCartney's 1980 marijuana bust in Japan, had affairs while they were married and was just as intent on a divorce as Lennon.</s>

<s docid="AP880915-0066" num="16" wdcount="27"> Ono refuted virtually all of these charges, and countered through taped interviews with Lennon friends and employees that Goldman's book was based on unreliable sources and misquotes.</s>

<s docid="AP880915-0066" num="17" wdcount="25"> ``It's totally fiction,'' Yoko said during the hour-long program, which opened with Lennon's song, ``Gimme Some Truth,'' and coincided with the book's national release Wednesday.</s>

<s docid="AP880915-0066" num="18" wdcount="8"> ``These people in this book are not us.</s>

<s docid="AP880915-0066" num="19" wdcount="7"> It's not John and me,'' Ono continued.</s>

<s docid="AP880915-0066" num="20" wdcount="9"> ``It's unfair he's been assaulted and can't hit back.</s>

<s docid="AP880915-0066" num="21" wdcount="23"> ... For some reason this book is attempting to rob both John and I of the basic human dignity that we're entitled to''.</s>

<s docid="AP880915-0066" num="22" wdcount="23"> The Ono interview was taped Aug. 28 at the Dakota, where the Lennons lived _ and Yoko still lives with their son, Sean.</s>

<s docid="AP880915-0066" num="23" wdcount="14"> Lennon was murdered by Mark David Chapman outside the Dakota on Dec. 8, 1980.</s>

<s docid="AP880915-0066" num="24" wdcount="28"> The interview was broadcast nationwide via the Westwood One Network; spokeswoman Laurie Wilde said an exact figure on how many stations picked up the broadcast was not available.</s>

<s docid="AP880915-0066" num="25" wdcount="9"> Also appearing were Sean and Lennon other son, Julian.</s>

<s docid="AP880915-0066" num="26" wdcount="27"> Ono was interviewed by longtime associate Elliot Mintz, who is described in Goldman's book as a spy for Yoko _ a charge Mintz denied during the show.</s>

<s docid="AP880915-0066" num="27" wdcount="15"> ``It is, for one, very upsetting, but most of all it is lies, untruths ...</s>

<s docid="AP880915-0066" num="28" wdcount="19"> The whole thing is just sickening,'' said Julian, who also refuted Goldman's tales of Lennon as a violent father.</s>

<s docid="AP880915-0066" num="29" wdcount="17"> Mintz read excerpts from the book to Yoko, who then responded to the allegations point by point.</s>

<s docid="AP880915-0066" num="30" wdcount="31"> She denied that Lennon was homosexual; that he was using drugs while living at the Dakota with his son, Sean; that he had become a reclusive rock 'n' roll Howard Hughes.</s>

<s docid="AP880915-0066" num="31" wdcount="21"> She did acknowledge having a heroin problem during the late 1970s, but rejected Goldman's assertion that she had a $5,000-a-week habit.</s>

<s docid="AP880915-0066" num="32" wdcount="33"> The book has already drawn angry responses from friends of Lennon and Ono McCartney, who contradicted one anecdote involving Lennon smashing a painting in Paul's home, has urged a boycott of the book.</s>

<s docid="AP880915-0066" num="33" wdcount="25"> After Yoko's rebuttal, listeners were invited to dial 900-digit telephone numbers to vote on whether the book was an accurate portrayal of the Lennons' life.</s>

<s docid="AP880915-0066" num="34" wdcount="7"> Results were not expected until later today.</s>

<s docid="AP880915-0066" num="35" wdcount="23"> Goldman, who conducted more than 1,200 interviews for his Lennon book, has written controversial biographies of comedian Lenny Bruce and Elvis Presley .</s>
</TEXT>
</DOC>
