<DOC>
<DOCNO>

<s docid="AP881001-0104" num="1" wdcount="1"> AP881001-0104</s>
</DOCNO>
<FILEID>

<s docid="AP881001-0104" num="2" wdcount="2"> AP-NR-10-01-88 1419EDT</s>
</FILEID>
<FIRST>

<s docid="AP881001-0104" num="3" wdcount="5"> r a AM-People-CynthiaLennon 10-01 0420</s>
</FIRST>
<SECOND>

<s docid="AP881001-0104" num="4" wdcount="2"> AM-People-Cynthia Lennon,0432</s>
</SECOND>
<HEAD>

<s docid="AP881001-0104" num="5" wdcount="10"> Former Wife of Late Beatle Also Denounces New Lennon Bio</s>
</HEAD>
<DATELINE>

<s docid="AP881001-0104" num="6" wdcount="3"> NEW YORK (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP881001-0104" num="7" wdcount="26"> Cynthia Lennon joins the throng denouncing the new, unauthorized biography of her late former husband, John Lennon, as written by a money-hungry author capitalizing on untruths.</s>

<s docid="AP881001-0104" num="8" wdcount="36"> ``People who write books like this, it is for greed, and as far as I'm concerned, they're gravediggers, no more, no less,'' Mrs. Lennon says on the CBS show ``60 Minutes'' scheduled for broadcast Sunday evening.</s>

<s docid="AP881001-0104" num="9" wdcount="10"> ``Grave robbers, body snatchers, you name it, they are it''.</s>

<s docid="AP881001-0104" num="10" wdcount="30"> The biography by Albert Goldman, ``The Lives of John Lennon,'' depicts the former Beatle as an anorexic bisexual addled by drugs who raged his way from Liverpool to New York.</s>

<s docid="AP881001-0104" num="11" wdcount="5"> It was released Sept. 14.</s>

<s docid="AP881001-0104" num="12" wdcount="26"> Goldman, who defends his Lennon book and said it is based on 1,200 interviews, also has written controversial biographies of comedian Lenny Bruce and Elvis Presley.</s>

<s docid="AP881001-0104" num="13" wdcount="17"> Lennon was murdered outside his Upper West Side home on Dec. 8, 1980, by Mark David Chapman.</s>

<s docid="AP881001-0104" num="14" wdcount="32"> ``All I know and all the people that love John know that we had our years (and) that nobody, no film, no book will ever complete what went on in our lives.</s>

<s docid="AP881001-0104" num="15" wdcount="19"> That's our part of our hearts that has to stay with us, must not be public,'' Mrs. Lennon said.</s>

<s docid="AP881001-0104" num="16" wdcount="3"> ``I love John.</s>

<s docid="AP881001-0104" num="17" wdcount="10"> I've always loved John because he was my first love.</s>

<s docid="AP881001-0104" num="18" wdcount="9"> But, I mean, I've loved him in different ways.</s>

<s docid="AP881001-0104" num="19" wdcount="4"> I love his memory.</s>

<s docid="AP881001-0104" num="20" wdcount="5"> I loved what he did.</s>

<s docid="AP881001-0104" num="21" wdcount="6"> I understood his madness, his phases.</s>

<s docid="AP881001-0104" num="22" wdcount="6"> I just feel that I understood''.</s>

<s docid="AP881001-0104" num="23" wdcount="13"> The couple divorced a few months before Lennon married Yoko Ono in 1969.</s>

<s docid="AP881001-0104" num="24" wdcount="23"> Ms. Ono already has trashed the book, calling it ``totally fiction'' in a nationwide broadcast that coincided with the release of the book.</s>

<s docid="AP881001-0104" num="25" wdcount="13"> She too was interviewed on the ``60 Minutes'' show, entitled ``The Two Mrs.</s>

<s docid="AP881001-0104" num="26" wdcount="9"> Lennons''. ``These people in this book are not us.</s>

<s docid="AP881001-0104" num="27" wdcount="12"> It's not John and me,'' Ono said in the taped radio broadcast.</s>

<s docid="AP881001-0104" num="28" wdcount="27"> Cynthia and John's son, Julian Lennon, also denounced the book on the radio taping, calling it ``lies, untruths,'' and adding that ``the whole thing is just sickening''.</s>

<s docid="AP881001-0104" num="29" wdcount="28"> Sean Lennon, the son of Yoko and John who is now 12, added his voice on the CBS broadcast, rebutting charges that his father was inattentive to parenting.</s>

<s docid="AP881001-0104" num="30" wdcount="18"> ``I think he did a lot of fathering in the five years that I knew him,'' Sean says.</s>

<s docid="AP881001-0104" num="31" wdcount="15"> ``He spent so much time with me not just at home, but everywhere, you know.''</s>
</TEXT>
</DOC>
