<DOC>
<DOCNO>

<s docid="AP880808-0040" num="1" wdcount="1"> AP880808-0040</s>
</DOCNO>
<FILEID>

<s docid="AP880808-0040" num="2" wdcount="2"> AP-NR-08-08-88 0631EDT</s>
</FILEID>
<FIRST>

<s docid="AP880808-0040" num="3" wdcount="5"> r a PM-LennonBiography 08-08 0308</s>
</FIRST>
<SECOND>

<s docid="AP880808-0040" num="4" wdcount="2"> PM-Lennon Biography,0318</s>
</SECOND>
<HEAD>

<s docid="AP880808-0040" num="5" wdcount="6"> Slain Beatle Portrayed as Reclusive, Anorexic</s>
</HEAD>
<DATELINE>

<s docid="AP880808-0040" num="6" wdcount="3"> NEW YORK (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880808-0040" num="7" wdcount="37"> John Lennon spent much of a three-year span tucked away in his room, sleeping or sitting in a lotus position with his head enveloped in tobacco or marijuana smoke, according to a biography of the slain Beatle.</s>

<s docid="AP880808-0040" num="8" wdcount="39"> An excerpt from the book, ``The Lives of John Lennon'' by journalist and biographer Albert Goldman, appearing in the Aug. 15 issue of People magazine, discloses a sometimes unflattering portrait of both Lennon and his second wife, Yoko Ono.</s>

<s docid="AP880808-0040" num="9" wdcount="16"> The book is scheduled to be published later this month by William Morrow & Co. Inc.</s>

<s docid="AP880808-0040" num="10" wdcount="12"> Between 1976 and 1979, Goldman writes, Lennon ``could not be more remote''.</s>

<s docid="AP880808-0040" num="11" wdcount="27"> Apart from a few hours in the morning and evening, including time spent with his son, Sean, ``Lennon is back here in his room, alone and silent''.</s>

<s docid="AP880808-0040" num="12" wdcount="23"> The author says the idolized Beatle spent most of his adult life as an anorexic, starving himself to what he perceived as perfection.</s>

<s docid="AP880808-0040" num="13" wdcount="24"> The onset of the eating disorder can be traced to 1965, Goldman writes, ``when some fool described him in print as the `fat Beatle'.</s>

<s docid="AP880808-0040" num="14" wdcount="17"> '' ``That phrase struck such a blow to his fragile ego that the wound has never healed''.</s>

<s docid="AP880808-0040" num="15" wdcount="19"> Lennon rarely wore clothing, other than a pair of backless slippers, and avoided touching anyone, according to the book.</s>

<s docid="AP880808-0040" num="16" wdcount="12"> The 719-page biography also details Yoko Ono's $5,000-a-week heroin habit in 1979.</s>

<s docid="AP880808-0040" num="17" wdcount="5"> She reportedly snorted the drug.</s>

<s docid="AP880808-0040" num="18" wdcount="15"> According to the book, Lennon also took heroin and consumed a great deal of LSD.</s>

<s docid="AP880808-0040" num="19" wdcount="13"> ``I must have taken a thousand trips,'' the book quotes Lennon as saying.</s>

<s docid="AP880808-0040" num="20" wdcount="9"> ``I just ate it all the time like candy''.</s>

<s docid="AP880808-0040" num="21" wdcount="27"> Goldman spent more than six years researching the book, interviewing 1,200 friends, relatives and associates of Lennon, who was murdered eight years ago in New York .</s>
</TEXT>
</DOC>
