<DOC>
<DOCNO>

<s docid="AP890119-0266" num="1" wdcount="1"> AP890119-0266</s>
</DOCNO>
<FILEID>

<s docid="AP890119-0266" num="2" wdcount="2"> AP-NR-01-19-89 0823EST</s>
</FILEID>
<FIRST>

<s docid="AP890119-0266" num="3" wdcount="6"> a e PM-APArts:LennonBook ADV20 01-19 1013</s>
</FIRST>
<SECOND>

<s docid="AP890119-0266" num="4" wdcount="6"> PM-AP Arts: Lennon Book, ADV 20,1036</s>
</SECOND>
<HEAD>

<s docid="AP890119-0266" num="5" wdcount="2"> $Adv 20</s>
</HEAD>
<HEAD>

<s docid="AP890119-0266" num="6" wdcount="8"> For Release Fri PMs, Jan 20 and Thereafter</s>
</HEAD>
<HEAD>

<s docid="AP890119-0266" num="7" wdcount="6"> Life With John Lennon And Mummy</s>
</HEAD>
<BYLINE>

<s docid="AP890119-0266" num="8" wdcount="3"> By DAVID GERMAIN</s>
</BYLINE>
<BYLINE>

<s docid="AP890119-0266" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890119-0266" num="10" wdcount="3"> LOCKPORT, N.Y. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890119-0266" num="11" wdcount="24"> The image of a dour, shoeless English boy and his absent, carefree mother prompted Julia Baird and Geoffrey Giuliano to collaborate on a book.</s>

<s docid="AP890119-0266" num="12" wdcount="15"> The boy is the public image of young John Lennon, Baird's half-brother and Giuliano's idol.</s>

<s docid="AP890119-0266" num="13" wdcount="20"> But the neglected urchin and his live-it-up mother _ who was also Baird's mother _ never existed, the authors say.</s>

<s docid="AP890119-0266" num="14" wdcount="17"> ``That woman laughing, singing, dancing, saying goodbye to John, and John standing there alone crying `Mummy, Mummy'!</s>

<s docid="AP890119-0266" num="15" wdcount="36"> That's not my brother, that's not my mother, that's not my children's grandmother,'' said Baird, who recently spent three weeks in the United States promoting her book, a family portrait of Lennon and his Liverpool roots.</s>

<s docid="AP890119-0266" num="16" wdcount="30"> Published in North America last fall, ``John Lennon, My Brother'' was co-authored by Giuliano, a Beatles aficionado who lives in this Erie Canal city about 25 miles north of Buffalo.</s>

<s docid="AP890119-0266" num="17" wdcount="9"> The two-year, cross-Atlantic collaboration came from two different motives.</s>

<s docid="AP890119-0266" num="18" wdcount="8"> Giuliano wanted to do a book about Lennon.</s>

<s docid="AP890119-0266" num="19" wdcount="16"> Baird wanted to do a book about the ex-Beatle's maligned mother, whose name also was Julia.</s>

<s docid="AP890119-0266" num="20" wdcount="29"> The result is a little of both, a mishmash of anecdotes showing a moody but generally happy Liverpool boy singing with his mother in a bathroom with good acoustics.</s>

<s docid="AP890119-0266" num="21" wdcount="33"> Baird disagrees with other biographies which say that after his father decamped and Julia turned her son over to her sister, Mimi, Lennon was a grim youth who felt abandoned by his mother.</s>

<s docid="AP890119-0266" num="22" wdcount="8"> ``I didn't do it for John,'' said Baird.</s>

<s docid="AP890119-0266" num="23" wdcount="16"> ``I wanted to set the record straight about our mother, and that ties in with John.</s>

<s docid="AP890119-0266" num="24" wdcount="11"> I feel my mother has been badly misrepresented in the press''.</s>

<s docid="AP890119-0266" num="25" wdcount="22"> Baird, a 41-year-old teacher in Cheshire, England, was born seven years after Lennon to Julia and her common-law second husband, John Dykins.</s>

<s docid="AP890119-0266" num="26" wdcount="24"> She and her younger sister, Jacqui, grew up with their parents amid an extended family of aunts, uncles, cousins _ and big brother John.</s>

<s docid="AP890119-0266" num="27" wdcount="28"> The book tells of the sisters getting hauled out of the bathtub when teen-agers Lennon, Paul McCartney and George Harrison drop by for bathroom jam sessions with Julia.</s>

<s docid="AP890119-0266" num="28" wdcount="54"> It tells of an alternately thoughtless and protective brother who leaves his step-sisters at the movies for hours while he goes on a date, who between songs at a Beatles concert shouts for security guards to lift the Dykins girls out of the front row, away from screaming fans threatening to storm the stage.</s>

<s docid="AP890119-0266" num="29" wdcount="17"> But mostly it tells of a mother and son who, while living apart, had a loving relationship.</s>

<s docid="AP890119-0266" num="30" wdcount="21"> The book got its start after Baird watched a British television special in 1985 marking the fifth anniversary of Lennon's murder.</s>

<s docid="AP890119-0266" num="31" wdcount="14"> The show presented Julia ``as an unfit mother, no mother at all,'' Baird said.</s>

<s docid="AP890119-0266" num="32" wdcount="9"> Baird complained and was urged to tell her story.</s>

<s docid="AP890119-0266" num="33" wdcount="11"> She wrote an essay and arranged to publish it in Liverpool.</s>

<s docid="AP890119-0266" num="34" wdcount="17"> Then she met Giuliano, who was in Liverpool to promote his first book, ``The Beatles: A Celebration''.</s>

<s docid="AP890119-0266" num="35" wdcount="24"> Giuliano, 35, a self-proclaimed huckster, convinced Baird to work with him on a book, which he pieced together from interviews with Baird in England.</s>

<s docid="AP890119-0266" num="36" wdcount="10"> While proofreading the text, Baird sent a copy to McCartney.</s>

<s docid="AP890119-0266" num="37" wdcount="13"> He sent his blessing, plus a bonus: a brief foreword for the book.</s>

<s docid="AP890119-0266" num="38" wdcount="17"> With a collection of rare early photos, the book is more a family album than a biography.</s>

<s docid="AP890119-0266" num="39" wdcount="27"> Giuliano's text reads like oral history, as if a British schoolteacher had spread the family scrapbook across the reader's knees to boast about her brother, the musician.</s>

<s docid="AP890119-0266" num="40" wdcount="16"> However, the book is a narrow view of Lennon, a child's recollections of an aspiring brother.</s>

<s docid="AP890119-0266" num="41" wdcount="34"> After Julia was killed in a traffic accident in 1958, Baird saw less and less of Lennon, losing contact with him for years when he and wife Yoko Ono moved to the United States.</s>

<s docid="AP890119-0266" num="42" wdcount="29"> The end of the book describes what Baird calls Lennon's desire to regain his lost Liverpool roots, when she and her step-brother exchanged letters and phone calls during 1975-80.</s>

<s docid="AP890119-0266" num="43" wdcount="24"> Baird has been accused of cashing in on her step-brother but insists she just wants to tell the family's story of Lennon's early years.</s>

<s docid="AP890119-0266" num="44" wdcount="11"> ``I could have cashed in when John was alive,'' Baird said.</s>

<s docid="AP890119-0266" num="45" wdcount="19"> ``When John died the tabloids in England were knocking on the door saying, `Write your story, name your price'.</s>

<s docid="AP890119-0266" num="46" wdcount="6"> We quickly showed them the door''.</s>

<s docid="AP890119-0266" num="47" wdcount="24"> Also shown the door was Albert Goldman, whose sordid biography, ``The Lives of John Lennon,'' hit bookstores about the same time as Baird's book.</s>

<s docid="AP890119-0266" num="48" wdcount="26"> Baird, who read Goldman's scathing biography of Elvis Presley, said she turned down an interview with Goldman, who brands Lennon homosexual, anorexic and possibly a murderer.</s>

<s docid="AP890119-0266" num="49" wdcount="21"> ``I had heard Goldman was doing the book six years ago, and I knew what the tone would be,'' Baird said.</s>

<s docid="AP890119-0266" num="50" wdcount="15"> ``Most people, including Goldman, write books based on other books that have it all wrong''.</s>

<s docid="AP890119-0266" num="51" wdcount="3"> Giuliano was harsher.</s>

<s docid="AP890119-0266" num="52" wdcount="12"> ``Goldman was in it for the money from day one,'' Giuliano said.</s>

<s docid="AP890119-0266" num="53" wdcount="10"> ``Goldman knows the formula: the more sleaze, the more dough.</s>

<s docid="AP890119-0266" num="54" wdcount="4"> So what's his motive?</s>

<s docid="AP890119-0266" num="55" wdcount="11"> If he writes the sleaziest book he makes the most dough''.</s>

<s docid="AP890119-0266" num="56" wdcount="10"> Baird herself wasn't blind to the business end of publishing.</s>

<s docid="AP890119-0266" num="57" wdcount="15"> She agreed to change the title from ``My Brother John'' to ``John Lennon, My Brother''.</s>

<s docid="AP890119-0266" num="58" wdcount="23"> The cover's look-alike photos of Baird and Lennon in granny specs also help, but she said she didn't don them to sell books.</s>

<s docid="AP890119-0266" num="59" wdcount="18"> They're on the National Health, Britain's medical plan, and she and Lennon inherited their mother's short-sightedness, Baird said.</s>

<s docid="AP890119-0266" num="60" wdcount="17"> The book itself is a loving look through rose-colored specs of a brother whose art touched millions.</s>

<s docid="AP890119-0266" num="61" wdcount="7"> ``It's not a major biography,'' Giuliano said.</s>

<s docid="AP890119-0266" num="62" wdcount="16"> ``This book is a little slice out of a big pie, out of a big life.</s>

<s docid="AP890119-0266" num="63" wdcount="12"> It offers a lot of previously unknown details on Lennon's early life.</s>

<s docid="AP890119-0266" num="64" wdcount="10"> It's a sympathetic view, sure, but what's not to love?''</s>
</TEXT>
<NOTE>

<s docid="AP890119-0266" num="65" wdcount="6"> End Adv PM Fri Jan. 20</s>
</NOTE>
</DOC>
