<DOC>
<DOCNO>

<s docid="AP901009-0072" num="1" wdcount="1"> AP901009-0072</s>
</DOCNO>
<FILEID>

<s docid="AP901009-0072" num="2" wdcount="2"> AP-NY-10-09-90 1208EDT</s>
</FILEID>
<FIRST>

<s docid="AP901009-0072" num="3" wdcount="7"> r a PM-Lennon50th 2ndLd-Writethru a0570 10-09 0521</s>
</FIRST>
<SECOND>

<s docid="AP901009-0072" num="4" wdcount="5"> PM-Lennon 50th, 2nd Ld-Writethru, a0570,0636</s>
</SECOND>
<HEAD>

<s docid="AP901009-0072" num="5" wdcount="7"> Lennon's `Imagine' Broadcast Worldwide on 50th Birthday</s>
</HEAD>
<NOTE>

<s docid="AP901009-0072" num="6" wdcount="23"> Eds: Leads with 7 grafs to UPDATE with Ono quotes, U.N. observance, Hollywood observance, picking up at the 4th graf previous, ``Beatles fans.''</s>
</NOTE>
<DATELINE>

<s docid="AP901009-0072" num="7" wdcount="3"> NEW YORK (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP901009-0072" num="8" wdcount="30"> The 50th anniversary of John Lennon's birth was observed with a global celebration today as his peace anthem ``Imagine'' was played for an estimated 1 billion people in 130 nations.</s>

<s docid="AP901009-0072" num="9" wdcount="23"> The song was played shortly after 10 a.m. following a brief ceremony at the United Nations that featured the ex-Beatle's widow, Yoko Ono.</s>

<s docid="AP901009-0072" num="10" wdcount="15"> Marcela Perez de Cuellar, wife of the U.N. secretary general, also provided a brief introduction.</s>

<s docid="AP901009-0072" num="11" wdcount="11"> A recorded message from the slain Beatle was played as well.</s>

<s docid="AP901009-0072" num="12" wdcount="13"> ``In celebration of John's life, let's use our power of dreaming,'' Ono said.</s>

<s docid="AP901009-0072" num="13" wdcount="23"> ``Let's dream of trees growing in abundance, birds flying in clear air, fish swimming in clear water and our children living in joy.</s>

<s docid="AP901009-0072" num="14" wdcount="22"> ``Let's dream of men and women feeling good together and people embracing each other regardless of their creed and religion,'' she said.</s>

<s docid="AP901009-0072" num="15" wdcount="20"> ``Let's dream of all races praising one another in the knowledge that the differences are what makes the human race''.</s>

<s docid="AP901009-0072" num="16" wdcount="2"> The U.N.</s>

<s docid="AP901009-0072" num="17" wdcount="28"> Trusteeship Council Chamber was about one-third full with a couple of hundred people for the observance and about 150 people watched on television monitors in the visitors' lobby.</s>

<s docid="AP901009-0072" num="18" wdcount="18"> A group of 10 teen-agers in blue jeans and T-shirts sat on the floor, held hands and meditated.</s>

<s docid="AP901009-0072" num="19" wdcount="20"> More than 1,000 radio stations and networks from 50 countries had signed on for the satellite broadcast by last week.</s>

<s docid="AP901009-0072" num="20" wdcount="12"> U.S. Armed Forces television and radio beamed the event to 80-plus countries.</s>

<s docid="AP901009-0072" num="21" wdcount="14"> MTV was to broadcast the program in 25 countries, said network spokeswoman Andrea Smith.</s>

<s docid="AP901009-0072" num="22" wdcount="24"> More than 50 fans gathered at the late Beatle's sidewalk star on the Hollywood Walk of Fame in Los Angeles to honor the singer-songwriter.</s>

<s docid="AP901009-0072" num="23" wdcount="8"> Some held candles and others carried birthday balloons.</s>

<s docid="AP901009-0072" num="24" wdcount="11"> Beatles fans gathered in Liverpool today to pay tribute to Lennon.</s>

<s docid="AP901009-0072" num="25" wdcount="27"> Civic dignitaries planned to join them at the city's Cavern Walks shopping precinct - on the ite of the legendary Cavern Club where the group was discovered.</s>

<s docid="AP901009-0072" num="26" wdcount="25"> In New York, fans planned a tearful pilgrimage to the spot outside the Dakota apartment building where Lennon was gunned down almost 10 years ago.</s>

<s docid="AP901009-0072" num="27" wdcount="59"> ``Lennon always symbolized for us somebody who was able to handle rock and roll with a sense of humor and later, even more importantly, as someone who cared for the rights of an individual, human rights in general, and who had the right concept of freedom and peace,'' said Ondrej Konrad, the editor of Czechoslovakia's leading popular music publication.</s>

<s docid="AP901009-0072" num="28" wdcount="19"> Jeff Pollack, head of the California-based Pollack Media Group, proposed the idea to Ono, who gave it the go-ahead.</s>

<s docid="AP901009-0072" num="29" wdcount="25"> She believes recent events around the world - in Germany, Eastern Europe and particularly the Middle East - show the importance of Lennon's peace message.</s>

<s docid="AP901009-0072" num="30" wdcount="18"> ``When this was discussed, we had no knowledge of what would happen in Iraq and Kuwait, you know.</s>

<s docid="AP901009-0072" num="31" wdcount="16"> And now it seems very appropriate that this be sung all over the world,'' Ono said.</s>

<s docid="AP901009-0072" num="32" wdcount="7"> ``I don't know, the timing is incredible.</s>

<s docid="AP901009-0072" num="33" wdcount="4"> It's beyond me ...</s>

<s docid="AP901009-0072" num="34" wdcount="2"> It's beautiful''.</s>

<s docid="AP901009-0072" num="35" wdcount="13"> ``Imagine'' is Lennon's musical vision of a world free of war and poverty.</s>

<s docid="AP901009-0072" num="36" wdcount="24"> Lennon was born Oct. 9, 1940 and helped lead the Beatles to international stardom, along with co-members Paul McCartney, George Harrison and Ringo Starr.</s>

<s docid="AP901009-0072" num="37" wdcount="16"> He fatally gunned down by an obsessed fan outside his Manhattan apartment building in December 1980.</s>

<s docid="AP901009-0072" num="38" wdcount="19"> The tribute coincides with the release of a four-compact disc set of 73 songs, including 61 written by Lennon.</s>

<s docid="AP901009-0072" num="39" wdcount="15"> Also in honor of Lennon's 50th birthday, McCartney is releasing his live version of ``Birthday.''</s>
</TEXT>
</DOC>
