<DOC>
<DOCNO>

<s docid="AP901121-0207" num="1" wdcount="1"> AP901121-0207</s>
</DOCNO>
<FILEID>

<s docid="AP901121-0207" num="2" wdcount="2"> AP-NY-11-21-90 1448EST</s>
</FILEID>
<FIRST>

<s docid="AP901121-0207" num="3" wdcount="6"> a e BC-APArts:Lennon-FinalSe Adv25 11-21 0671</s>
</FIRST>
<SECOND>

<s docid="AP901121-0207" num="4" wdcount="6"> BC-AP Arts: Lennon-Final Sessions, Adv 25,0874</s>
</SECOND>
<NOTE>

<s docid="AP901121-0207" num="5" wdcount="2"> $Adv 25</s>
</NOTE>
<NOTE>

<s docid="AP901121-0207" num="6" wdcount="7"> For Release Sunday, Nov. 25 and Thereafter</s>
</NOTE>
<HEAD>

<s docid="AP901121-0207" num="7" wdcount="5"> With BC-AP Arts: Lennon Anniversary</s>
</HEAD>
<HEAD>

<s docid="AP901121-0207" num="8" wdcount="8"> Just a Working Musician: John Lennon's Final Sessions</s>
</HEAD>
<BYLINE>

<s docid="AP901121-0207" num="9" wdcount="3"> By HILLEL ITALIE</s>
</BYLINE>
<BYLINE>

<s docid="AP901121-0207" num="10" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP901121-0207" num="11" wdcount="3"> NEW YORK (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP901121-0207" num="12" wdcount="31"> Drummer Andy Newmark was touring with Roxy Music in the summer of 1980 when he got the call that changed his life: He was to play on John Lennon's new album.</s>

<s docid="AP901121-0207" num="13" wdcount="22"> Lennon had been in virtual seclusion for five years, busy taking care of his son, Sean, and admittedly out of songwriting ideas.</s>

<s docid="AP901121-0207" num="14" wdcount="24"> But in 1980, he suddenly felt inspired again and planned to return to the studio to make an album with his wife, Yoko Ono.</s>

<s docid="AP901121-0207" num="15" wdcount="7"> It was more than a superstar session.</s>

<s docid="AP901121-0207" num="16" wdcount="12"> Afterall, Lennon gave no press conferences, and didn't attend clubs or concerts.</s>

<s docid="AP901121-0207" num="17" wdcount="22"> Rare photos occasionally emerged and he looked different in each one (Lennon jokingly referred to himself as ``Greta Hughes'' and ``Howard Garbo'').</s>

<s docid="AP901121-0207" num="18" wdcount="25"> Producer Jack Douglas, who had worked with Lennon as an engineer, recruited Newmark, bassist Tony Levin, guitarist Hugh McCracken and other New York-based sessions players.</s>

<s docid="AP901121-0207" num="19" wdcount="11"> Recording was to take place at the Hit Factory in Manhattan.</s>

<s docid="AP901121-0207" num="20" wdcount="10"> To Newmark, Lennon was a hero and only a hero.</s>

<s docid="AP901121-0207" num="21" wdcount="11"> He didn't know him and was nervous about working with him.</s>

<s docid="AP901121-0207" num="22" wdcount="21"> The drummer guessed he was something like the intense, irreverent young man of the movies ``Help''! and ``A Hard Day's Night''.</s>

<s docid="AP901121-0207" num="23" wdcount="7"> Lennon was those things - and more.</s>

<s docid="AP901121-0207" num="24" wdcount="31"> ``His personality seemed so consistent with all we had ever heard about John Lennon,'' said Newmark, who still lives in New York and works with former Roxy Music singer Bryan Ferry.</s>

<s docid="AP901121-0207" num="25" wdcount="15"> ``His straightforwardness was as visible and apparant as the stories and images we had created.</s>

<s docid="AP901121-0207" num="26" wdcount="11"> I didn't see anything that seemed startlingly new to the myth.</s>

<s docid="AP901121-0207" num="27" wdcount="20"> It just appeared to be what we had imagined: down to earth, direct, so direct it could not offend people''.</s>

<s docid="AP901121-0207" num="28" wdcount="26"> Newmark spent just one month in the studio, playing on the songs that eventually ended up on ``Double Fantasy'' and ``Milk and Honey,'' Lennon's final albums.</s>

<s docid="AP901121-0207" num="29" wdcount="10"> It was the ``best experience of my life,'' he insisted.</s>

<s docid="AP901121-0207" num="30" wdcount="5"> ``The highlight of my career''.</s>

<s docid="AP901121-0207" num="31" wdcount="4"> The nerves quickly settled.</s>

<s docid="AP901121-0207" num="32" wdcount="19"> Once recording began, Lennon was just a ``working musician'' with the same goal as everyone else: finishing the album.</s>

<s docid="AP901121-0207" num="33" wdcount="12"> The music was mostly mainstream pop; no 18-minute jams or political anthems.</s>

<s docid="AP901121-0207" num="34" wdcount="10"> ``I hate all that fancy stuff,'' Lennon told his drummer.</s>

<s docid="AP901121-0207" num="35" wdcount="5"> ``Keep it simple, like Ringo''.</s>

<s docid="AP901121-0207" num="36" wdcount="18"> He was a happy man at this point and his singing was higher, sweeter than on earlier albums.</s>

<s docid="AP901121-0207" num="37" wdcount="19"> Lennon was hoping to get back in touch with his audience, and the songs were melodic, the production lush.</s>

<s docid="AP901121-0207" num="38" wdcount="12"> ``Dear Yoko'' and ``Grow Old With Me'' were tributes to his wife.</s>

<s docid="AP901121-0207" num="39" wdcount="7"> ``Beautiful Boy (Darling Boy)'' was for Sean.</s>

<s docid="AP901121-0207" num="40" wdcount="32"> Lennon defended his self-imposed retirement on ``Watching the Wheels'' and summed up his feelings about turning 40 on ``Borrowed Time,'' capping the line ``Good to be older'' with a self-assured ``you bet''.</s>

<s docid="AP901121-0207" num="41" wdcount="11"> Between takes, Lennon jammed on Buddy Holly songs and played host.</s>

<s docid="AP901121-0207" num="42" wdcount="6"> Sushi was the food of choice.</s>

<s docid="AP901121-0207" num="43" wdcount="8"> The strongest drug was Brazilian coffee, freshly ground.</s>

<s docid="AP901121-0207" num="44" wdcount="13"> ``Guys, I'm taking off,'' Lennon would say as he poured himself another cup.</s>

<s docid="AP901121-0207" num="45" wdcount="16"> And there were plenty of stories about the Beatles - the ``B's,'' as John called them.</s>

<s docid="AP901121-0207" num="46" wdcount="25"> Reunions were out of the question, a return to adolescence in his opinion, but talking about the old days seemed the nicest kind of high.</s>

<s docid="AP901121-0207" num="47" wdcount="21"> ``By this time he was old enough to look upon the work they did and be proud of it,'' Newmark said.</s>

<s docid="AP901121-0207" num="48" wdcount="14"> ``When he talked about the `B's,' it was as if it was his band.</s>

<s docid="AP901121-0207" num="49" wdcount="5"> He was the spiritual leader.</s>

<s docid="AP901121-0207" num="50" wdcount="8"> I felt that a lot through the sessions''.</s>

<s docid="AP901121-0207" num="51" wdcount="24"> By the fall, Newmark had finished working on the album, and his contact with Lennon was limited to an occasional visit to the studio.</s>

<s docid="AP901121-0207" num="52" wdcount="9"> But he had planned on working with him again.</s>

<s docid="AP901121-0207" num="53" wdcount="21"> ``Milk and Honey'' was to come out the following year and Lennon wanted to tour, using many of the same musicians.</s>

<s docid="AP901121-0207" num="54" wdcount="13"> ``Life is what happens when you're busy making other plans,'' Lennon once sang.</s>

<s docid="AP901121-0207" num="55" wdcount="36"> It took the drummer a long time to recover from Lennon's murder the night of Dec. 8, 1980; he didn't even feel like working for the next few years - everything else suddenly seemed ``second rate''.</s>

<s docid="AP901121-0207" num="56" wdcount="13"> Newmark never listens to the record, but still hears ``Woman'' on the radio.</s>

<s docid="AP901121-0207" num="57" wdcount="29"> When he thinks about it now, it's not so much a particular song that hurts him, it's the day-to-day stuff: the jokes and wisecracks, the coffee and the stories.</s>

<s docid="AP901121-0207" num="58" wdcount="19"> No one had a reason to remember all that at the time; those weren't supposed to be farewell sessions.</s>

<s docid="AP901121-0207" num="59" wdcount="28"> ``When I looked in his eyes, I felt a tremendous depth of character and a tremendous understanding of the human condition, a tremendous amount of compassion,,'' Newmark said.</s>

<s docid="AP901121-0207" num="60" wdcount="11"> ``He was totally friendly and open to everybody, including the janitor.</s>

<s docid="AP901121-0207" num="61" wdcount="5"> He had time for everybody.</s>

<s docid="AP901121-0207" num="62" wdcount="13"> That working class hero thing, he was trying to be real about that.''</s>
</TEXT>
<NOTE>

<s docid="AP901121-0207" num="63" wdcount="5"> End Adv Sunday Nov. 25</s>
</NOTE>
<TEXT>
</TEXT>
</DOC>
