<DOC>
<DOCNO>

<s docid="AP901208-0076" num="1" wdcount="1"> AP901208-0076</s>
</DOCNO>
<FILEID>

<s docid="AP901208-0076" num="2" wdcount="2"> AP-NY-12-08-90 1311EST</s>
</FILEID>
<FIRST>

<s docid="AP901208-0076" num="3" wdcount="5"> r i AM-LennonAnniversary 12-08 0343</s>
</FIRST>
<SECOND>

<s docid="AP901208-0076" num="4" wdcount="2"> AM-Lennon Anniversary,0424</s>
</SECOND>
<HEAD>

<s docid="AP901208-0076" num="5" wdcount="11"> Crowds in Liverpool to Mark 10th Anniversary of John Lennon's Death</s>
</HEAD>
<DATELINE>

<s docid="AP901208-0076" num="6" wdcount="3"> LIVERPOOL, England (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP901208-0076" num="7" wdcount="29"> Dozens of fans of rock legend and former Beatle John Lennon gathered in the snow on a windy Saturday for a ceremony marking the 10th anniversary of his death.</s>

<s docid="AP901208-0076" num="8" wdcount="27"> Liverpool's mayor, Dorothy Gavin, led Lennon devotees who laid wreaths at the foot of a bronze statue of The Beatles in the city's Cavern Walks shopping center.</s>

<s docid="AP901208-0076" num="9" wdcount="29"> The center was built on the original site of the Cavern Club, made famous when The Beatles played there in the 1960s, and has become a place of pilgrimage.</s>

<s docid="AP901208-0076" num="10" wdcount="19"> ``Give peace a chance,'' the title of one of singer-songwriter Lennon's greatest hits, was the theme for the day.</s>

<s docid="AP901208-0076" num="11" wdcount="24"> Many friends and followers of Lennon were present, including Father Tom McKenzie, immortalized as Father MacKenzie in The Beatles' l966 hit song ``Eleanor Rigby''.</s>

<s docid="AP901208-0076" num="12" wdcount="28"> On Friday, a small group of invited guests had gathered at Liverpool's Beatles Museum to watch Mrs. Gavin unveil a plaque marking the 10th anniversary of Lennon's death.</s>

<s docid="AP901208-0076" num="13" wdcount="36"> ``John was always a son of Liverpool and over the last 10 years Liverpool has been very slow to recognize the fact that the Beatles came from Liverpool,'' said Lennon biographer Ray Coleman after the unveiling.</s>

<s docid="AP901208-0076" num="14" wdcount="20"> ``It is right that a world figure like Lennon should be recognized at last,'' said Coleman, author of ``John Lennon''.</s>

<s docid="AP901208-0076" num="15" wdcount="48"> Lennon and his wife, Yoko Ono, were returning to their apartment in New York's Dakota apartment building after a recording session on Dec. 8, 1980, when Lennon was shot to death by Mark David Chapman, a deranged fan to whom Lennon had given his autograph only hours before.</s>

<s docid="AP901208-0076" num="16" wdcount="3"> Lennon was 40.</s>

<s docid="AP901208-0076" num="17" wdcount="23"> A spokesman for the Lennon family said Ms. Ono and the couple's son, Sean, were in Europe and would spend the anniversary privately.</s>

<s docid="AP901208-0076" num="18" wdcount="35"> Journalist Andy Peebles, the last person to interview Lennon before he was shot, said in an interview with Sky satellitetelevision news: ``Ten years on, it's a ghastly feeling to think that you had spent ...</s>

<s docid="AP901208-0076" num="19" wdcount="3"> seven hours ...</s>

<s docid="AP901208-0076" num="20" wdcount="16"> with somebody you have been a fan of for years, and I think I left ...</s>

<s docid="AP901208-0076" num="21" wdcount="9"> thinking `This is great, he's in really good shape'''.</s>

<s docid="AP901208-0076" num="22" wdcount="28"> Peebles said late in 1980 that Lennon had just recovered from a period when he had ``gone off the rails'' and his relationship with Ms. Ono had suffered.</s>

<s docid="AP901208-0076" num="23" wdcount="17"> ``But (when I saw him) they'd had the baby, Sean had been born, and everything was great.''</s>
</TEXT>
</DOC>
