<DOC>
<DOCNO>

<s docid="AP900505-0127" num="1" wdcount="1"> AP900505-0127</s>
</DOCNO>
<FILEID>

<s docid="AP900505-0127" num="2" wdcount="2"> AP-NR-05-05-90 2047EDT</s>
</FILEID>
<FIRST>

<s docid="AP900505-0127" num="3" wdcount="7"> u i AM-LennonConcert 2ndLd-Writethru a0575 05-05 0439</s>
</FIRST>
<SECOND>

<s docid="AP900505-0127" num="4" wdcount="5"> AM-Lennon Concert, 2nd Ld-Writethru, a0575,0451</s>
</SECOND>
<HEAD>

<s docid="AP900505-0127" num="5" wdcount="7"> Lennon Tribute in His Hometown Draws Thousands</s>
</HEAD>
<NOTE>

<s docid="AP900505-0127" num="6" wdcount="8"> Eds: UPDATES throughout with concert over, details, color.</s>

<s docid="AP900505-0127" num="7" wdcount="2"> No pickup</s>
</NOTE>
<HEAD>

<s docid="AP900505-0127" num="8" wdcount="2"> LaserPhoto XLIV1</s>
</HEAD>
<DATELINE>

<s docid="AP900505-0127" num="9" wdcount="3"> LIVERPOOL, England (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900505-0127" num="10" wdcount="26"> Thousands of John Lennon fans, some too young to remember the Beatles, swayed and sang along with songs including his anthem ``Imagine'' at a hometown tribute.</s>

<s docid="AP900505-0127" num="11" wdcount="6"> ``It's a great day, isn't it''?</s>

<s docid="AP900505-0127" num="12" wdcount="7"> Lennon's widow, Yoko Ono, asked the crowd.</s>

<s docid="AP900505-0127" num="13" wdcount="7"> ``I think John would be happy, too''.</s>

<s docid="AP900505-0127" num="14" wdcount="21"> At the close of the concert, she and son Sean, 14, wept and hugged some of the musicians, who included B.B.</s>

<s docid="AP900505-0127" num="15" wdcount="17"> King, Joe Cocker, Roberta Flack, the Moody Blues, Hall and Oates, Wet Wet Wet and Randy Travis.</s>

<s docid="AP900505-0127" num="16" wdcount="10"> However, the turnout was only 15,000, according to police estimates.</s>

<s docid="AP900505-0127" num="17" wdcount="6"> Organizers had hoped for about 45,000.</s>

<s docid="AP900505-0127" num="18" wdcount="17"> Tickets were $41 for the charity benefit concert, which featured a program of Beatles and Lennon songs.</s>

<s docid="AP900505-0127" num="19" wdcount="26"> The concert was televised in Britain and was to be rebroadcast worldwide in October in a 50th birthday tribute to Lennon a decade after his death.</s>

<s docid="AP900505-0127" num="20" wdcount="28"> Cyndi Lauper, in a white minidress, sang ``Hey Bulldog,'' and Dave Edmunds, backed by the Royal Liverpool Philharmonic Orchestra, did the Beatles classic, ``A Day in the Life''.</s>

<s docid="AP900505-0127" num="21" wdcount="8"> Soul singer Al Green was the opening act.</s>

<s docid="AP900505-0127" num="22" wdcount="20"> His version of ``All You Need is Love,'' turned into a singalong with the crowd, and Kylie Minogue did ``Help''.</s>

<s docid="AP900505-0127" num="23" wdcount="11"> American actor Christopher Reeve was among the hosts of the concert.</s>

<s docid="AP900505-0127" num="24" wdcount="18"> Ex-Beatles George Harrison, Paul McCartney and Ringo Starr did not attend, but McCartney and Starr made taped contributions.</s>

<s docid="AP900505-0127" num="25" wdcount="25"> On tape, Starr performed ``I Call Your Name'' and said, ``John had the biggest heart of any man I have ever met to this day.</s>

<s docid="AP900505-0127" num="26" wdcount="8"> He was a giving, loving, caring human being.</s>

<s docid="AP900505-0127" num="27" wdcount="16"> He was crazy as well some days _ but the guy would give you his heart''.</s>

<s docid="AP900505-0127" num="28" wdcount="23"> Lennon's co-songwriter, Paul McCartney, said on his tape: ``Hello Liverpool, scene of many great memories, John, me and the rest of the lads''.</s>

<s docid="AP900505-0127" num="29" wdcount="14"> The Beatles were raised in Liverpool and got their start in the Merseyside bars.</s>

<s docid="AP900505-0127" num="30" wdcount="20"> All the musicians assembled on stage for ``Give Peace a Chance,'' as the enthusiastic audience sang along, waved and clapped.</s>

<s docid="AP900505-0127" num="31" wdcount="20"> The concert closed with a recording of Lennon singing ``Imagine,'' while giant screens showed a video featuring John and Yoko.</s>

<s docid="AP900505-0127" num="32" wdcount="33"> Proceeds are to go to the Spirit Foundation, the charity founded by the Lennons in 1978, two years before Lennon was shot to death in front of his apartment in New York City.</s>

<s docid="AP900505-0127" num="33" wdcount="11"> Lennon was slain on Dec. 8, 1980, when he was 40.</s>

<s docid="AP900505-0127" num="34" wdcount="12"> The confessed killer, Mark Chapman, is serving a life prison sentence .</s>
</TEXT>
</DOC>
