<DOC>
<DOCNO>

<s docid="AP901121-0206" num="1" wdcount="1"> AP901121-0206</s>
</DOCNO>
<FILEID>

<s docid="AP901121-0206" num="2" wdcount="2"> AP-NY-11-21-90 1447EST</s>
</FILEID>
<FIRST>

<s docid="AP901121-0206" num="3" wdcount="6"> a e BC-APArts:LennonAnnivers 1stAdd 11-21 0506</s>
</FIRST>
<SECOND>

<s docid="AP901121-0206" num="4" wdcount="6"> BC-AP Arts: Lennon Anniversary, 1st Add,0626</s>
</SECOND>
<NOTE>

<s docid="AP901121-0206" num="5" wdcount="2"> $Adv 25</s>
</NOTE>
<NOTE>

<s docid="AP901121-0206" num="6" wdcount="7"> For Release Sunday, Nov. 25 and Thereafter</s>
</NOTE>
<HEAD>

<s docid="AP901121-0206" num="7" wdcount="5"> NEW YORK: in 1975 .</s>
</HEAD>
<TEXT>

<s docid="AP901121-0206" num="8" wdcount="18"> At this point, Lennon says he became a househusband to their child while Yoko ran the family business.</s>

<s docid="AP901121-0206" num="9" wdcount="18"> The arrangement continued until Lennon told the woman he called ``Mother'' it was time to make music again.</s>

<s docid="AP901121-0206" num="10" wdcount="16"> ``Double Fantasy'' followed just before John's death, although it was not to be Lennon's swan song.</s>

<s docid="AP901121-0206" num="11" wdcount="11"> Bruce Springsteen has released three albums since 1980; Michael Jackson two.</s>

<s docid="AP901121-0206" num="12" wdcount="39"> In contrast, Lennon - or, more accurately, Ono - has released five albums: ``Milk and Honey,'' ``Menlove Ave.,'' the movie soundtrack ``Imagine,'' the ``John Lennon - Live in New York'' collection and a boxed CD collection for Christmas '90.</s>

<s docid="AP901121-0206" num="13" wdcount="18"> In addition, ``The Lost Lennon Tapes,'' featuring hours of unreleased Lennon music, became a popular syndicated radio program.</s>

<s docid="AP901121-0206" num="14" wdcount="6"> Ono has overseen all these projects.</s>

<s docid="AP901121-0206" num="15" wdcount="29"> ``People ask me, `What would he have done in the '80s'? I say, `Let's talk about what he HAS done in the '80s,' because he has definitely,'' she said.</s>

<s docid="AP901121-0206" num="16" wdcount="11"> ``In spirit, I think he's alive, and we're getting the benefit''.</s>

<s docid="AP901121-0206" num="17" wdcount="14"> Others charge Ono with turning her memories into millions without concern for Lennon's image.</s>

<s docid="AP901121-0206" num="18" wdcount="24"> A Fame magazine profile derided her as ``The Merry Widow''; the now-defunct weekly 7 Days described her as the decade's ``premier celebrity civil defendant''.</s>

<s docid="AP901121-0206" num="19" wdcount="3"> Greed, insensitivity, egomania.</s>

<s docid="AP901121-0206" num="20" wdcount="10"> None of Ono's alleged faults are apparent in an interview.</s>

<s docid="AP901121-0206" num="21" wdcount="23"> In October, a barefoot Ono greeted a visitor to the Dakota in a high-ceilinged first-floor room with white carpet and black onyx walls.</s>

<s docid="AP901121-0206" num="22" wdcount="29"> Curled up on a chair, she serenely sipped herbal tea from a mug decorated with a Lennon drawing of John and Yoko with the inscription, ``Grow Old With Me''.</s>

<s docid="AP901121-0206" num="23" wdcount="28"> The mug is one of an assortment of Lennon collectibles available (by appointment only) from Bag One Arts Inc., the entity that controls reproductions of Lennon's art work.</s>

<s docid="AP901121-0206" num="24" wdcount="35"> Some of that black on white artwork - which includes doodles jotted down on napkins, the margins of letters or stray scraps of paper - has been colorized or redone in neon at Ono's order.</s>

<s docid="AP901121-0206" num="25" wdcount="18"> ``People would ask if we had anything in color,'' says Lynne Clifford, who runs Bag One for Yoko.</s>

<s docid="AP901121-0206" num="26" wdcount="12"> ``And Yoko said, `I feel confident enough to add the color myself.</s>

<s docid="AP901121-0206" num="27" wdcount="14"> So she took the original sketches and we made plates and she added colors''.</s>

<s docid="AP901121-0206" num="28" wdcount="27"> Lithographs that sold for $400 four years ago have increased as much as 10 times in value, she says, and new ones cost between $600 and $700.</s>

<s docid="AP901121-0206" num="29" wdcount="27"> Although Bag One's gallery a few blocks from the Dakota deals primarily in lithographs, it also sells the collectibles, including $3 laminated bags that bear Lennon's drawings.</s>

<s docid="AP901121-0206" num="30" wdcount="13"> ``Yoko wanted everybody to be able to walk away with something,'' explained Clifford.</s>

<s docid="AP901121-0206" num="31" wdcount="6"> Where does all the money go?</s>

<s docid="AP901121-0206" num="32" wdcount="10"> ``Yoko is very funny about (saying) where the money goes.</s>

<s docid="AP901121-0206" num="33" wdcount="10"> ... But some goes to the Spirit Foundation,'' she said.</s>

<s docid="AP901121-0206" num="34" wdcount="28"> The foundation, established by Lennon and Ono before John's death, has contributed to causes ranging from a home for drug addicted children to bulletproof vests for police officers.</s>

<s docid="AP901121-0206" num="35" wdcount="9"> Is there anything that will never bear Lennon's sketch-work?</s>

<s docid="AP901121-0206" num="36" wdcount="3"> Socks, Clifford said.</s>

<s docid="AP901121-0206" num="37" wdcount="11"> ``Yoko said she couldn't imagine people walking around on John's drawings''.</s>

<s docid="AP901121-0206" num="38" wdcount="13"> Back at the Dakota, Ono receives a familiar question: Is this all commercialism?</s>

<s docid="AP901121-0206" num="39" wdcount="7"> Has the iconoclastic ex-Beatle been sold out?</s>

<s docid="AP901121-0206" num="40" wdcount="2"> She laughs.</s>

<s docid="AP901121-0206" num="41" wdcount="6"> ``No. I didn't sell out John.</s>

<s docid="AP901121-0206" num="42" wdcount="13"> And I'm sure John would be happy I'm still keeping him out there.</s>

<s docid="AP901121-0206" num="43" wdcount="23"> ... There's a commercial aspect, yes, but I mean, why not? I was a partner, and I still feel that I'm a partner.''</s>
</TEXT>
<NOTE>

<s docid="AP901121-0206" num="44" wdcount="4"> End Adv Sunday Nov.25</s>
</NOTE>
<TEXT>
</TEXT>
</DOC>
