<DOC>
<DOCNO>

<s docid="AP901009-0148" num="1" wdcount="1"> AP901009-0148</s>
</DOCNO>
<FILEID>

<s docid="AP901009-0148" num="2" wdcount="2"> AP-NY-10-09-90 1804EDT</s>
</FILEID>
<FIRST>

<s docid="AP901009-0148" num="3" wdcount="5"> r i AM-Soviet-Lennon 10-09 0452</s>
</FIRST>
<SECOND>

<s docid="AP901009-0148" num="4" wdcount="1"> AM-Soviet-Lennon,0535</s>
</SECOND>
<HEAD>

<s docid="AP901009-0148" num="5" wdcount="11"> Lennon, Not Lenin, On Minds of Soviet Youth for Birthday Bash</s>
</HEAD>
<HEAD>

<s docid="AP901009-0148" num="6" wdcount="2"> With AM-Lennon-50th</s>
</HEAD>
<BYLINE>

<s docid="AP901009-0148" num="7" wdcount="3"> By ANDREW KATELL</s>
</BYLINE>
<BYLINE>

<s docid="AP901009-0148" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP901009-0148" num="9" wdcount="2"> MOSCOW (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP901009-0148" num="10" wdcount="13"> On the spot where Lenin once spoke, the focus Tuesday was on Lennon.</s>

<s docid="AP901009-0148" num="11" wdcount="35"> Official newspapers, which once denounced the Beatles as harmful pests from the decadent West, joined a worldwide celebration and ran stories of tribute about the late John Lennon, who would have turned 50 on Tuesday.</s>

<s docid="AP901009-0148" num="12" wdcount="9"> State radio broadcast his music and interviews about him.</s>

<s docid="AP901009-0148" num="13" wdcount="20"> Two concerts devoted to the songwriter, guitarist and singer, who was shot to death in 1980, were held in Moscow.</s>

<s docid="AP901009-0148" num="14" wdcount="10"> Even the staid state television program ``Vremya'' got into act.</s>

<s docid="AP901009-0148" num="15" wdcount="25"> An anchorman, more accustomed to reading official government news, reported on the worldwide Lennon birthday bash and called his song ``Imagine,'' an ``anthem of peace''.</s>

<s docid="AP901009-0148" num="16" wdcount="20"> The broadcast ended with an instrumental version of ``Yesterday'' playing as temperatures from around the nation rolled across the screen.</s>

<s docid="AP901009-0148" num="17" wdcount="21"> The celebration was a dramatic turnabout from Soviet authorities' repression of Beatles fans and supression of their music in earlier times.</s>

<s docid="AP901009-0148" num="18" wdcount="10"> Their music was banned and the Soviet press condemned them.</s>

<s docid="AP901009-0148" num="19" wdcount="17"> A 1964 article, for instance, commented, ``These bugs can swiftly ignite the very darkest and primitive passions''.</s>

<s docid="AP901009-0148" num="20" wdcount="28"> About 1,000 Soviets, mostly second generation Beatles fans, flocked to the Moscow Electrical Lamp Factory's cultural hall in northeastern part of the city to rejoice in Lennon's music.</s>

<s docid="AP901009-0148" num="21" wdcount="29"> A plaque outside the hall reminded Beatles fans that Lennon's near namesake, Vladimir Lenin, the founder of the Soviet state, had spoken at the spot in 1917 and 1919.</s>

<s docid="AP901009-0148" num="22" wdcount="28"> Inside, fans listened to recordings of Lennon's music, attended a concert of about a dozen Soviet rock bands, bought his albums and posters and reflected on his life.</s>

<s docid="AP901009-0148" num="23" wdcount="35"> ``He's like a hero, a symbol for every person: a symbol of honesty, talent, devotion to his ideals, notion of love, equality between people and goodness,'' said Irina Dykomkina, the 21-year-old secretary of the Sgt.</s>

<s docid="AP901009-0148" num="24" wdcount="11"> Pepper's Club, a Soviet Beatles fan club formed two years ago.</s>

<s docid="AP901009-0148" num="25" wdcount="7"> Lennon's music, she said, crosses borders easily.</s>

<s docid="AP901009-0148" num="26" wdcount="15"> ``His music is so sincere, it's so understandable, even to people who don't know English.</s>

<s docid="AP901009-0148" num="27" wdcount="4"> They feel the music''.</s>

<s docid="AP901009-0148" num="28" wdcount="44"> Andrei Trushkin, a correspondent for Komsomolskaya Pravda - the Communist Party youth newspaper that devoted a full page Tuesday to Lennon - said he appeals to Soviet youth in part because he was a rebel, like many of them, and was a ``difficult teen-ager''.</s>

<s docid="AP901009-0148" num="29" wdcount="16"> ``The cops would have locked him up many times,'' said Trushkin, who helped organize the concert.</s>

<s docid="AP901009-0148" num="30" wdcount="10"> Tuesday's concert opened in the spirit of a birthday party.</s>

<s docid="AP901009-0148" num="31" wdcount="15"> Balloons floated down from the balconies as a tape of Lennon's song, ``Starting Over,'' played.</s>

<s docid="AP901009-0148" num="32" wdcount="23"> The stage was adorned with a painting of Lennon and life-size cardboard cutouts of the Fab Four in front of the British flag.</s>

<s docid="AP901009-0148" num="33" wdcount="12"> ``Oorah! Oorah''! shouted the audience, which included a few soldiers in uniform.</s>

<s docid="AP901009-0148" num="34" wdcount="40"> Onstage, the groups Sprint, Quiet Hour and Optimal Variant played in Beatles style but were joined by a group that didn't quite fit in the genre, an American-style country ensemble that wore plaid vests and performed ``Night Train to Memphis.''</s>
</TEXT>
</DOC>
