<DOC>
<DOCNO>

<s docid="AP901009-0186" num="1" wdcount="1"> AP901009-0186</s>
</DOCNO>
<FILEID>

<s docid="AP901009-0186" num="2" wdcount="2"> AP-NY-10-09-90 2156EDT</s>
</FILEID>
<FIRST>

<s docid="AP901009-0186" num="3" wdcount="7"> r a AM-Lennon50th 3rdLd-Writethru a0789 10-09 0528</s>
</FIRST>
<SECOND>

<s docid="AP901009-0186" num="4" wdcount="5"> AM-Lennon 50th, 3rd Ld-Writethru, a0789,0680</s>
</SECOND>
<HEAD>

<s docid="AP901009-0186" num="5" wdcount="7"> Imagine All the People Listening to John</s>
</HEAD>
<NOTE>

<s docid="AP901009-0186" num="6" wdcount="13"> Eds: SUBS 7th graf pvs, `Other observances '... to DELETE duplicated sentence .</s>
</NOTE>
<BYLINE>

<s docid="AP901009-0186" num="7" wdcount="3"> By LARRY McSHANE</s>
</BYLINE>
<BYLINE>

<s docid="AP901009-0186" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP901009-0186" num="9" wdcount="3"> NEW YORK (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP901009-0186" num="10" wdcount="32"> John Lennon's worldwide message of peace was delivered Tuesday as his song ``Imagine'' was played simultaneously for 1 billion people in 130 countries to celebrate what would have been his 50th birthday.</s>

<s docid="AP901009-0186" num="11" wdcount="17"> ``A dream we dream alone is only a dream, but the dream we dream together is reality.</s>

<s docid="AP901009-0186" num="12" wdcount="3"> Happy birthday, John.</s>

<s docid="AP901009-0186" num="13" wdcount="24"> The world is better today for sharing a time with you,'' Yoko Ono said at a United Nations ceremony before the playing of ``Imagine''.</s>

<s docid="AP901009-0186" num="14" wdcount="22"> The slain former Beatle himself issued a call for harmony in a taped message that served as an introduction to the music.</s>

<s docid="AP901009-0186" num="15" wdcount="10"> ``We all want peace, whatever sort of job we have.</s>

<s docid="AP901009-0186" num="16" wdcount="5"> ... Think of your children.</s>

<s docid="AP901009-0186" num="17" wdcount="10"> Do you want them to be killed or don't you?</s>

<s docid="AP901009-0186" num="18" wdcount="10"> And that's the choice we have in front of us.</s>

<s docid="AP901009-0186" num="19" wdcount="11"> War or peace,'' said Lennon, whose son Sean turned 15 Tuesday.</s>

<s docid="AP901009-0186" num="20" wdcount="31"> None of the other Beatles were at the United Nations, but a tribute came from Lennon's old songwriting partner, Paul McCartney, who released a live version of the Beatles' tune ``Birthday''.</s>

<s docid="AP901009-0186" num="21" wdcount="20"> The song, originally on the ``White Album,'' was the first Lennon-McCartney single released since the Beatles broke up in 1969.</s>

<s docid="AP901009-0186" num="22" wdcount="26"> ``The release date and John's birthday is just a happy coincidence, but it's also a nod and a wink to my old mate,'' said McCartney, 47.</s>

<s docid="AP901009-0186" num="23" wdcount="11"> Other observances were held from Liverpool to Moscow to Los Angeles.</s>

<s docid="AP901009-0186" num="24" wdcount="20"> In Lennon's hometown in England, fans gathered at the former site of the Cavern Club, where the Beatles were discovered.</s>

<s docid="AP901009-0186" num="25" wdcount="9"> Among those attending was Lennon's 71-year-old uncle, Charlie Lennon.</s>

<s docid="AP901009-0186" num="26" wdcount="42"> When asked how his nephew would have reacted to the ceremonies, he said: ``If he had been alive I doubt he would have come and even if he had, he would sat with me in the pub and had a good laugh''.</s>

<s docid="AP901009-0186" num="27" wdcount="72"> On the West Coast, about 50 people - part of an estimated 1 billion people worldwide who had access to the event - stood near Lennon's star on the Walk of Fame and listened to the ``Imagine'' broadcast: ``Imagine all the people, living life in peace ``You may say I'm a dreamer, but I'm not the only one ``I hope some day you'll join us ``And the world will live as one''.</s>

<s docid="AP901009-0186" num="28" wdcount="21"> ``His spirit still lives in all of us whose lives have been touched with him,'' Ono said of her late husband.</s>

<s docid="AP901009-0186" num="29" wdcount="34"> ``I would like us to remember and celebrate his birthday as a day of love, because he was a man of love, and because love is much needed at this time in our lives''.</s>

<s docid="AP901009-0186" num="30" wdcount="13"> Ono was greeted by Marcela Perez de Cuellar, wife of the U.N. secretary-general.</s>

<s docid="AP901009-0186" num="31" wdcount="27"> During her brief remarks, Ono also quoted a line from another of Lennon's songs, ``Happy Xmas (War is Over)'': ``Remember, war is over if you want it''.</s>

<s docid="AP901009-0186" num="32" wdcount="14"> More than 1,000 radio stations and networks from 50 countries broadcast the 10-minute event.</s>

<s docid="AP901009-0186" num="33" wdcount="12"> U.S. Armed Forces television and radio beamed it to 80-plus other countries.</s>

<s docid="AP901009-0186" num="34" wdcount="16"> MTV televised the ``Imagine'' video in 25 countries, said Andrea Smith, a spokeswoman for the network.</s>

<s docid="AP901009-0186" num="35" wdcount="30"> In Moscow, about 1,000 Soviets gathered at the Moscow Electrical Lamp Factory's cultural hall to listen to Lennon's music, snap up his albums and posters and reflect on his life.</s>

<s docid="AP901009-0186" num="36" wdcount="11"> Even the staid state television program ``Vremya'' got into the act.</s>

<s docid="AP901009-0186" num="37" wdcount="15"> An anchorman, reporting on the worldwide birthday bash, described ``Imagine'' as an ``anthem of peace''.</s>

<s docid="AP901009-0186" num="38" wdcount="9"> The broadcast ended with an instrumental version of ``Yesterday''.</s>

<s docid="AP901009-0186" num="39" wdcount="13"> Not so long ago, the Beatles' music was banned in the Soviet Union.</s>

<s docid="AP901009-0186" num="40" wdcount="17"> In 1964, one commentator warned that ``these bugs can swiftly ignite the very darkest and primitive passions''.</s>

<s docid="AP901009-0186" num="41" wdcount="19"> Lennon was shot to death by a deranged fan outside his Manhattan apartment building on Dec. 8, 1980 .</s>
</TEXT>
</DOC>
