<DOC>
<DOCNO>

<s docid="SJMN91-06231192" num="1" wdcount="1"> SJMN91-06231192</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06231192" num="2" wdcount="1"> 06231192</s>
</ACCESS>
<CAPTION>

<s docid="SJMN91-06231192" num="3" wdcount="4"> Photo; PHOTO: (Yoko Ono)</s>
</CAPTION>
<DESCRIPT>

<s docid="SJMN91-06231192" num="4" wdcount="6"> PAST; MUSIC; CELEBRITY; SPOUSE; ARTS; PROFILE</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06231192" num="5" wdcount="15"> NIXON, disco, LSD -- it's no surprise, really, that those '70s rejects have staged comebacks.</s>

<s docid="SJMN91-06231192" num="6" wdcount="3"> But Yoko Ono?</s>

<s docid="SJMN91-06231192" num="7" wdcount="20"> The flaky avant-garde artist whose idea of music was to scream inside a plastic bag while John Lennon played guitar?</s>

<s docid="SJMN91-06231192" num="8" wdcount="15"> The Evil One who single-handedly killed the Beatles and destroyed her husband's talent and ambition?</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06231192" num="9" wdcount="3"> Arts & Books</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06231192" num="10" wdcount="8"> AFTER A HARD DAY'S DECADE, YOKO ONO THRIVES</s>
</HEADLINE>
<MEMO>

<s docid="SJMN91-06231192" num="11" wdcount="1"> Personality</s>
</MEMO>
<TEXT>

<s docid="SJMN91-06231192" num="12" wdcount="15"> Who could possibly regard her as anything other than a crackpot and a public menace?</s>

<s docid="SJMN91-06231192" num="13" wdcount="25"> Well, let's see: there's party rockers the B52s and cult singer Lene Lovich -- successful, critically acclaimed musicians who credit Ono's music as an influence.</s>

<s docid="SJMN91-06231192" num="14" wdcount="25"> There's the Whitney Museum of Art, which exhibited Ono's artwork last year -- one of the 10 museum shows she has had around the world.</s>

<s docid="SJMN91-06231192" num="15" wdcount="18"> There's also the American Film Institute, which Ono says is staging an international tour of her experimental films.</s>

<s docid="SJMN91-06231192" num="16" wdcount="23"> And Ono's record label -- "they want to put out all my songs in a kind of CD box or something," Ono says.</s>

<s docid="SJMN91-06231192" num="17" wdcount="3"> Surprised? So's Ono.</s>

<s docid="SJMN91-06231192" num="18" wdcount="5"> She's used to rougher treatment.</s>

<s docid="SJMN91-06231192" num="19" wdcount="7"> Acceptance is a difficult concept for her.</s>

<s docid="SJMN91-06231192" num="20" wdcount="27"> "I'm used to sort of knocking the door rather than having the door opened and having to cope with entering it," Ono says during a telephone interview.</s>

<s docid="SJMN91-06231192" num="21" wdcount="21"> She's speaking from the New York office of Bag One Arts, the company Ono founded to promote Lennon's art and image.</s>

<s docid="SJMN91-06231192" num="22" wdcount="70"> Marketing an icon; Since his death in 1980, Ono has steadily kept Lennon products coming out: the albums "Milk and Honey" and "Menlove Avenue" and the 4-CD boxed set "The John Lennon Collection"; the book "Skywriting by Word of Mouth," a collection of Lennon's unpublished writings; Lennon's art, which Ono says was his main interest in his final years; and Lennon-inspired merchandise, such as a line of John Lennon eyeglasses.</s>

<s docid="SJMN91-06231192" num="23" wdcount="13"> "I told the fans that I'm going to do 10 years of it.</s>

<s docid="SJMN91-06231192" num="24" wdcount="15"> Every year, hopefully, give a new product and share it with the fans," Ono says.</s>

<s docid="SJMN91-06231192" num="25" wdcount="26"> "Some years, we had two or three products of John that came out."; The 10-year promise ended with last year's year-long celebration of Lennon's 50th birthday.</s>

<s docid="SJMN91-06231192" num="26" wdcount="36"> In 1991, Ono says, she has tried to "relax a little and do my own stuff."; Ono, 57, has been going into a recording studio every day to work on the proposed boxed-set of her music.</s>

<s docid="SJMN91-06231192" num="27" wdcount="13"> She continues to produce art and recently had a museum exhibit in Iceland.</s>

<s docid="SJMN91-06231192" num="28" wdcount="12"> Ono began her art career as an abstract impressionist, then went avant-garde.</s>

<s docid="SJMN91-06231192" num="29" wdcount="21"> She began doing performance art in the early '60s, long before the form was legitimized by art critics and government grants.</s>

<s docid="SJMN91-06231192" num="30" wdcount="15"> A life in two worlds; Ono declines to put a label on her current works.</s>

<s docid="SJMN91-06231192" num="31" wdcount="8"> She says that's for the critics to decide.</s>

<s docid="SJMN91-06231192" num="32" wdcount="7"> "I just like to create," she says.</s>

<s docid="SJMN91-06231192" num="33" wdcount="20"> Ono still lives in the Dakota apartment house in New York, the site of Lennon's murder by a crazed fan.</s>

<s docid="SJMN91-06231192" num="34" wdcount="37"> On Dec. 8, 1980, the couple was returning home from the recording studio where they had been remixing "Walking on Thin Ice," one of the songs that would appear on Ono's most successful album, "Season of Glass".</s>

<s docid="SJMN91-06231192" num="35" wdcount="12"> As they approached the entrance to the building, someone called out "Mr.</s>

<s docid="SJMN91-06231192" num="36" wdcount="15"> Lennon"? Lennon turned, and Mark David Chapman shot him five times with a .38 revolver.</s>

<s docid="SJMN91-06231192" num="37" wdcount="14"> After Lennon's death, there was speculation that Ono would leave the United States forever.</s>

<s docid="SJMN91-06231192" num="38" wdcount="7"> She did begin living part-time in Geneva.</s>

<s docid="SJMN91-06231192" num="39" wdcount="14"> "My theory was that I would live more and more in Geneva," Ono says.</s>

<s docid="SJMN91-06231192" num="40" wdcount="16"> "But it seems like circumstances are making me come back more and more to New York.</s>

<s docid="SJMN91-06231192" num="41" wdcount="10"> This is my hometown, that's how I feel about it.</s>

<s docid="SJMN91-06231192" num="42" wdcount="32"> It's a place where I can work very well."; Ono was born in Tokyo -- her name means "Ocean Child" -- and came with her family to the United States in 1936.</s>

<s docid="SJMN91-06231192" num="43" wdcount="23"> Ono lived with her family in San Francisco and New York until the Japanese attack of Pearl Harbor forced them to return home.</s>

<s docid="SJMN91-06231192" num="44" wdcount="8"> In 1951, the Onos returned to New York.</s>

<s docid="SJMN91-06231192" num="45" wdcount="9"> Yoko married a Japanese composer when she was 23.</s>

<s docid="SJMN91-06231192" num="46" wdcount="5"> The marriage lasted seven years.</s>

<s docid="SJMN91-06231192" num="47" wdcount="12"> Ono married a second time in 1963, to avant-garde artist Tony Cox.</s>

<s docid="SJMN91-06231192" num="48" wdcount="9"> The couple had one child, a daughter named Kyoko.</s>

<s docid="SJMN91-06231192" num="49" wdcount="6"> In 1966, Ono and Lennon met.</s>

<s docid="SJMN91-06231192" num="50" wdcount="9"> He too was married and had a child, Julian.</s>

<s docid="SJMN91-06231192" num="51" wdcount="7"> Ono and Lennon were married in 1970.</s>

<s docid="SJMN91-06231192" num="52" wdcount="10"> There has been much speculation on Ono and Lennon's relationship.</s>

<s docid="SJMN91-06231192" num="53" wdcount="5"> Some say she controlled him.</s>

<s docid="SJMN91-06231192" num="54" wdcount="8"> "John was an extremely strong person," Ono says.</s>

<s docid="SJMN91-06231192" num="55" wdcount="39"> "There was no way to dominate him, even if I wanted to."; Others say Lennon used his relationship with Ono as an escape from things in his life that he felt were controlling him -- such as the Beatles.</s>

<s docid="SJMN91-06231192" num="56" wdcount="29"> In May 1968, when the Beatles came together at the studio to work on "The Beatles," the two-record set commonly called "The White Album," Ono was at Lennon's side.</s>

<s docid="SJMN91-06231192" num="57" wdcount="4"> The two were inseparable.</s>

<s docid="SJMN91-06231192" num="58" wdcount="16"> According to at least one Beatles biographer, Ono even accompanied Lennon on trips to the bathroom.</s>

<s docid="SJMN91-06231192" num="59" wdcount="15"> The relationship between the Beatles -- especially Lennon and Paul McCartney -- was already strained.</s>

<s docid="SJMN91-06231192" num="60" wdcount="15"> Having Ono in the studio, offering suggestions and backing Lennon up in arguments, didn't help.</s>

<s docid="SJMN91-06231192" num="61" wdcount="26"> Still, the group already seemed headed toward a break-up, which finally came when McCartney sued the other Beatles to resolve an argument over the group's management.</s>

<s docid="SJMN91-06231192" num="62" wdcount="8"> So, no, Ono didn't break up the Beatles.</s>

<s docid="SJMN91-06231192" num="63" wdcount="12"> But it's also true that three of them didn't like her much.</s>

<s docid="SJMN91-06231192" num="64" wdcount="20"> Life after John; "I think the very fact that John and I got together hurt them a lot," she says.</s>

<s docid="SJMN91-06231192" num="65" wdcount="2"> "It's 50/50.</s>

<s docid="SJMN91-06231192" num="66" wdcount="7"> We hurt them and they hurt us.</s>

<s docid="SJMN91-06231192" num="67" wdcount="18"> I can't really say it's a one-sided situation."; Ono says she feels no bitterness toward the surviving Beatles.</s>

<s docid="SJMN91-06231192" num="68" wdcount="10"> "Songwriters in this world are pretty harmless people," she says.</s>

<s docid="SJMN91-06231192" num="69" wdcount="18"> "They're not doing anything like creating a nuclear bomb or trying to decide whether people should be killed.</s>

<s docid="SJMN91-06231192" num="70" wdcount="11"> They're pretty peaceful people and their songs will hopefully inspire people.</s>

<s docid="SJMN91-06231192" num="71" wdcount="18"> I have a lot of respect for them."; But how do the Beatles feel toward Ono these days?</s>

<s docid="SJMN91-06231192" num="72" wdcount="4"> "It varies," she says.</s>

<s docid="SJMN91-06231192" num="73" wdcount="16"> "Sometimes they are friendly, sometimes they are not . . . like all relationships with friends.</s>

<s docid="SJMN91-06231192" num="74" wdcount="29"> I think that's natural."; Many of the books that have been written about Lennon and the Beatles, especially Albert Goldman's loathing portrait of Lennon, have been painful to Ono.</s>

<s docid="SJMN91-06231192" num="75" wdcount="11"> But she says she isn't sure about writing her own version.</s>

<s docid="SJMN91-06231192" num="76" wdcount="19"> "I was hurt very much, and my son, too, by some of the things that were written," she says.</s>

<s docid="SJMN91-06231192" num="77" wdcount="8"> "They were lies and that's what hurt us.</s>

<s docid="SJMN91-06231192" num="78" wdcount="35"> "Then again, when I think of writing my true story . . . I could say 'this is the truth' and write about things somebody did or whatever, but then I think about their children.</s>

<s docid="SJMN91-06231192" num="79" wdcount="21"> If you look at it from the big picture, maybe there was not such an incredible crime done to me" .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06231192" num="80" wdcount="6"> DOUG MASON, Scripps Howard News Service</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06231192" num="81" wdcount="1"> USA</s>
</COUNTRY>
<EDITION>

<s docid="SJMN91-06231192" num="82" wdcount="2"> Morning Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06231192" num="83" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06231192" num="84" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06231192" num="85" wdcount="1"> 910818</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06231192" num="86" wdcount="1"> Sunday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06231192" num="87" wdcount="1"> August</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06231192" num="88" wdcount="1"> 26</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06231192" num="89" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06231192" num="90" wdcount="1"> WEST</s>
</REGION>
<FEATURE>

<s docid="SJMN91-06231192" num="91" wdcount="1"> PHOTO</s>
</FEATURE>
<STATE>

<s docid="SJMN91-06231192" num="92" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06231192" num="93" wdcount="1"> 1,165</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06231192" num="94" wdcount="5"> Sunday, August 18, 1991 00231192,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06231192" num="95" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06231192" num="96" wdcount="1"> 0</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06231192" num="97" wdcount="1"> ENG</s>
</LANGUAGE>
</DOC>
