<DOC>
<DOCNO>

<s docid="WSJ881021-0008" num="1" wdcount="1"> WSJ881021-0008</s>
</DOCNO>
<HL>

<s docid="WSJ881021-0008" num="2" wdcount="10"> LEISURE & ARTS -- Bookshelf: Slimy Portrait of an Ex-Beatle</s>
</HL>
<AUTHOR>

<s docid="WSJ881021-0008" num="3" wdcount="2"> Andrew Ferguson</s>
</AUTHOR>
<SO>
</SO>
<TEXT>

<s docid="WSJ881021-0008" num="4" wdcount="34"> Say what you want about Albert Goldman, the author of the new biography, "The Lives of John Lennon" (Morrow, $22.95), but you've got to hand it to him: This guy is one ambitious sleazemonger.</s>

<s docid="WSJ881021-0008" num="5" wdcount="46"> Most best-selling pop biographers play it safe: They choose a celeb of respectable, not to say pristine, reputation, and then they proceed to blacken it, preferably by recounting vaguely sourced tales of sexual excess, chemical dependency, personal unkindness, raw business dealings, even, in some cases, dyslexia.</s>

<s docid="WSJ881021-0008" num="6" wdcount="38"> The resulting portrait of a dissipated ogre who can't spell is duly presented in hardback form to the public, which in turn is so shocked and disgusted that it forces itself to buy the biography by the millions.</s>

<s docid="WSJ881021-0008" num="7" wdcount="4"> A can't-miss formula, surely.</s>

<s docid="WSJ881021-0008" num="8" wdcount="10"> Albert Goldman's previous victim in the genre was Elvis Presley.</s>

<s docid="WSJ881021-0008" num="9" wdcount="17"> Now Mr. Presley was, if you'll forgive the expression, a fat target for a writer of Mr.</s>

<s docid="WSJ881021-0008" num="10" wdcount="2"> Goldman's methods.</s>

<s docid="WSJ881021-0008" num="11" wdcount="34"> His title notwithstanding, the "King of Rock 'n' Roll" was in truth more a creature of the old show biz, a star whose wholesome image, carefully created by P.R. wizards, was ripe for debunking.</s>

<s docid="WSJ881021-0008" num="12" wdcount="19"> But in choosing Mr. Lennon as his next target, Mr. Goldman appears to be trying to debunk the undebunkable.</s>

<s docid="WSJ881021-0008" num="13" wdcount="7"> For apart from his puerile politics, Mr.</s>

<s docid="WSJ881021-0008" num="14" wdcount="30"> Lennon's favorite topic in the thousands of interviews he gave was his own squalid history: His voracious drug use, his perfidy to employees, his unquenchable sexual promiscuity and so on.</s>

<s docid="WSJ881021-0008" num="15" wdcount="18"> By his own accounting, then, Mr. Lennon was not about to dethrone Ward Cleaver as the all-American dad.</s>

<s docid="WSJ881021-0008" num="16" wdcount="16"> His public loved him in spite of it all -- or perhaps because of it all.</s>

<s docid="WSJ881021-0008" num="17" wdcount="22"> Mr. Lennon grew to celebrity during a time when such transgressions as intemperance and adultery (quaint terms)! were losing their social sting.</s>

<s docid="WSJ881021-0008" num="18" wdcount="15"> His candor -- if that's what it was, and not simple logorrhea -- redeemed everything.</s>

<s docid="WSJ881021-0008" num="19" wdcount="21"> And so it is on the grounds of insufficient candor that the resourceful Mr. Goldman, hot to debunk, attacks his subject.</s>

<s docid="WSJ881021-0008" num="20" wdcount="4"> The leitmotif of Mr.</s>

<s docid="WSJ881021-0008" num="21" wdcount="28"> Lennon's confessions was that his worst days were behind him, and that with Yoko Ono he had at last learned to prize the virtues of quietude and domesticity.</s>

<s docid="WSJ881021-0008" num="22" wdcount="15"> Now Mr. Goldman is here to announce: He didn't tell you the half of it.</s>

<s docid="WSJ881021-0008" num="23" wdcount="65"> Hence this 718-page stew of unrelieved sordidness, percolating with the "scoops" that have by now been widely publicized in People magazine, "West 57th" and other scholarly venues: that Mr. Lennon had a thing for young boys; that his marriage to Ms. Ono was pocked by the same faithlessness and rancor that characterized his first marriage; that he had a sweet tooth that just wouldn't quit.</s>

<s docid="WSJ881021-0008" num="24" wdcount="13"> The squalid revelations dribble out like a chemical leak, sliming up every page.</s>

<s docid="WSJ881021-0008" num="25" wdcount="8"> Remarkably, then, the sleazemonger's art has triumphed: Mr.</s>

<s docid="WSJ881021-0008" num="26" wdcount="11"> Goldman's John Lennon is even worse than John Lennon's John Lennon.</s>

<s docid="WSJ881021-0008" num="27" wdcount="37"> A great deal of this muck manages to splash onto Ms. Ono, whom Mr. Goldman portrays as a cynical manipulator whose major talent lay in exploiting Mr. Lennon to further her own craving for fame and wealth.</s>

<s docid="WSJ881021-0008" num="28" wdcount="22"> Mr. Goldman, alas, allows to pass unremarked the obvious irony that this is a rather fine thumbnail sketch of himself as well.</s>

<s docid="WSJ881021-0008" num="29" wdcount="15"> The keepers of the Lennon flame have of course been quick to point this out.</s>

<s docid="WSJ881021-0008" num="30" wdcount="23"> Ms. Ono and her son have taken the path preferred by offended celebrities, they have hit the talk shows to display their wounds.</s>

<s docid="WSJ881021-0008" num="31" wdcount="34"> And Rolling Stone magazine, long the house organ for the Lennon publicity machine, recently published an extensive rebuttal to the book, which was undercut by a tone of priggish indignation bordering on the comic.</s>

<s docid="WSJ881021-0008" num="32" wdcount="29"> Criticizing "The Lives of John Lennon" for insufficient respect to the fallen Beatle's legacy is rather off the point -- like condemning Charles Manson for his bad table manners.</s>

<s docid="WSJ881021-0008" num="33" wdcount="10"> The book may indeed be inaccurate, as critics have charged.</s>

<s docid="WSJ881021-0008" num="34" wdcount="20"> But one can only hope that quibbles about its veracity do not obscure the countless other reasons to hate Mr.</s>

<s docid="WSJ881021-0008" num="35" wdcount="2"> Goldman's book.</s>

<s docid="WSJ881021-0008" num="36" wdcount="35"> There is, for starters, the sloppy, pompous prose, so suggestive of the grad-school smoking lounge -- Mr. Goldman is the sort of writer who refers to pop songs as "pieces," as though they were concerti.</s>

<s docid="WSJ881021-0008" num="37" wdcount="19"> There is his knowing, hipper-than-thou approach -- toward drugs, sex, music -- that gives him license to second-guess Mr.</s>

<s docid="WSJ881021-0008" num="38" wdcount="3"> Lennon's every move.</s>

<s docid="WSJ881021-0008" num="39" wdcount="47"> And there is the awkward organization, in which minor events assume large proportions for the simple reason that they reflect badly on Mr. Lennon, while major events are skipped over lightly because -- there goes the advance! -- they might reveal Mr. Lennon in a flattering light.</s>

<s docid="WSJ881021-0008" num="40" wdcount="54"> All of which indicates why "The Lives of John Lennon" is such a wretched book: not because it makes a good man look bad, but because it shows no other purpose than to make a man -- whether a good man or a bad one, we laymen will probably never know -- look bad.</s>

<s docid="WSJ881021-0008" num="41" wdcount="18"> John Lennon, while he was alive, did enough of that himself to satisfy all but the lowest appetites.</s>

<s docid="WSJ881021-0008" num="42" wdcount="12"> --- Mr. Ferguson is assistant managing editor of The American Spectator .</s>
</TEXT>
</DOC>
