<DOC>
<DOCNO>

<s docid="AP900803-0008" num="1" wdcount="1"> AP900803-0008</s>
</DOCNO>
<FILEID>

<s docid="AP900803-0008" num="2" wdcount="2"> AP-NR-08-03-90 0242EDT</s>
</FILEID>
<FIRST>

<s docid="AP900803-0008" num="3" wdcount="5"> r i PM-Iraq-KuwaitChronology 08-03 0431</s>
</FIRST>
<SECOND>

<s docid="AP900803-0008" num="4" wdcount="2"> PM-Iraq-Kuwait Chronology,0439</s>
</SECOND>
<HEAD>

<s docid="AP900803-0008" num="5" wdcount="12"> A Chronology of Key Events in the Dispute Between Iraq and Kuwait</s>
</HEAD>
<HEAD>

<s docid="AP900803-0008" num="6" wdcount="3"> With PM-Iraq-Kuwait, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP900803-0008" num="7" wdcount="4"> By The Associated Press</s>
</BYLINE>
<TEXT>

<s docid="AP900803-0008" num="8" wdcount="19"> Here is a brief chronology in the dispute between Iraq and Kuwait over oil production and their common border.</s>

<s docid="AP900803-0008" num="9" wdcount="35"> July 17 _ Iraqi President Saddam Hussein accuses Kuwait and the United Arab Emirates of flooding the oil market and driving prices down, and that the move cost Iraq $14 billion in lost oil revenue.</s>

<s docid="AP900803-0008" num="10" wdcount="27"> He further charges that Arab states in the Persian Gulf are conspiring with the United States and Israel to weaken Iraq's economy and undermine its military buildup.</s>

<s docid="AP900803-0008" num="11" wdcount="36"> July 18 _ Iraq accuses Kuwait of stealing $2.4 billion worth of oil from wells along the disputed border with Iraq and of seeking to wreck Iraq's economy by overproducing oil and thus pushing down prices.</s>

<s docid="AP900803-0008" num="12" wdcount="34"> July 20 _ Kuwaiti officials suggest Iraq's sudden outburst of belligerence is aimed at getting its creditors _ including Kuwait _ to write off billions of dollars in debts from the 1980-88 Iran-Iraq war.</s>

<s docid="AP900803-0008" num="13" wdcount="5"> July 24 _ The U.S.</s>

<s docid="AP900803-0008" num="14" wdcount="5"> Defense Department announces that U.S.</s>

<s docid="AP900803-0008" num="15" wdcount="26"> Navy warships and aircraft are holding a ``short-notice exercise'' in the Persian Gulf with the United Arab Emirates, about 600 miles southeast of the Kuwait-Iraqi border.</s>

<s docid="AP900803-0008" num="16" wdcount="22"> Kuwait reinstates a state of alert it declared July 16 and canceled after three days of tension between the two oil-producing countries.</s>

<s docid="AP900803-0008" num="17" wdcount="33"> July 25 _ The Iraqi government in Baghdad says that it will not be intimidated by U.S. pressure in its oil dispute with neighboring Kuwait, and Saddams summons the U.S. ambassador for talks.</s>

<s docid="AP900803-0008" num="18" wdcount="22"> President Hosni Mubarak of Egypt says Iraq and Kuwait plan to meet in Saudi Arabia in an effort to resolve their dispute.</s>

<s docid="AP900803-0008" num="19" wdcount="21"> July 26 _ OPEC ministers in Geneva agree to halt overproduction in hopes of pushing up the price of crude oil.</s>

<s docid="AP900803-0008" num="20" wdcount="12"> Kuwait and the United Arab Emirates pledge to abide by the agreement.</s>

<s docid="AP900803-0008" num="21" wdcount="10"> Analysts say Saddam clearly influenced the outcome of the meetings.</s>

<s docid="AP900803-0008" num="22" wdcount="19"> July 31 _ Kuwaiti and Iraqi delegations meet in Jiddah, Saudi Arabia, to negotiate the oil and border dispute.</s>

<s docid="AP900803-0008" num="23" wdcount="17"> Diplomats say Iraq has massed 100,000 troops on Kuwait's border, more than triple the number originally estimated.</s>

<s docid="AP900803-0008" num="24" wdcount="14"> That number dwarfs the Kuwaiti army, which has a total of about 20,000 troops.</s>

<s docid="AP900803-0008" num="25" wdcount="29"> Aug. 1 _ Iraq pulls out of talks on the 2-week-old border, oil and money dispute with Kuwait shortly before it sends its forces to invade the oil-rich sheikdom.</s>

<s docid="AP900803-0008" num="26" wdcount="23"> Aug. 2 _ Iraq's powerful army overruns Kuwait before dawn with tank-led troops quickly seized the ruler's palace and other government buildings .</s>
</TEXT>
</DOC>
