<DOC>
<DOCNO>

<s docid="AP900807-0029" num="1" wdcount="1"> AP900807-0029</s>
</DOCNO>
<FILEID>

<s docid="AP900807-0029" num="2" wdcount="2"> AP-NR-08-07-90 0235EDT</s>
</FILEID>
<FIRST>

<s docid="AP900807-0029" num="3" wdcount="5"> r i PM-Iran-Iraq-Rhetoric 08-07 0422</s>
</FIRST>
<SECOND>

<s docid="AP900807-0029" num="4" wdcount="1"> PM-Iran-Iraq-Rhetoric,0437</s>
</SECOND>
<HEAD>

<s docid="AP900807-0029" num="5" wdcount="9"> In Iran, Saddam is Generalissimo, Foster Child and Frankenstein</s>
</HEAD>
<BYLINE>

<s docid="AP900807-0029" num="6" wdcount="7"> With PM-Iraq-Kuwait Rdp, Bjt ^By NEIL MacFARQUHAR</s>
</BYLINE>
<BYLINE>

<s docid="AP900807-0029" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900807-0029" num="8" wdcount="3"> NICOSIA, Cyprus (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900807-0029" num="9" wdcount="23"> Iranian editorial writers are rejoicing now that the world is waking up to one of their most hated bogeymen: Iraqi President Saddam Hussein.</s>

<s docid="AP900807-0029" num="10" wdcount="12"> A Monday headline: ``We warned you Frankenstein would torment his own creators''.</s>

<s docid="AP900807-0029" num="11" wdcount="22"> Saddam attacked Iran in September 1980 after a series of border skirmishes, spawning a war that dragged until an August 1988 cease-fire.</s>

<s docid="AP900807-0029" num="12" wdcount="7"> The conflict has still not formally ended.</s>

<s docid="AP900807-0029" num="13" wdcount="14"> Iran's late fundamentalist patriarch, the Ayatollah Ruhollah Khomeini, vowed for years to unseat Saddam.</s>

<s docid="AP900807-0029" num="14" wdcount="18"> Never at a loss for a vivid phrase, he compared accepting the cease-fire with Saddam to drinking poison.</s>

<s docid="AP900807-0029" num="15" wdcount="21"> The status of Great Satan was reserved for the United States, the all-encompassing public enemy No. 1 for the Islamic Republic.</s>

<s docid="AP900807-0029" num="16" wdcount="15"> Iran frequently accuses both the U.S. and Saddam of trying to undermine the Islamic revolution.</s>

<s docid="AP900807-0029" num="17" wdcount="12"> Saddam conveniently boasts of having alone staunched the tide of radical Islam.</s>

<s docid="AP900807-0029" num="18" wdcount="39"> In fact one of his reasons for invading Kuwait on Thursday, the Iraqi press noted, was its gall in demanding back tens of billions of dollars loaned to Iraq during the war Saddam says he fought for all Arabs.</s>

<s docid="AP900807-0029" num="19" wdcount="25"> Over the past six months, successful U.N.-sponsored efforts toward face-to-face negotiations between Iraq and Iran robbed Iranian newspapers and television commentators of a favorite target.</s>

<s docid="AP900807-0029" num="20" wdcount="10"> Saddam's overthrow of the emir of Kuwait changed all that.</s>

<s docid="AP900807-0029" num="21" wdcount="7"> Old scores came brimming to the surface.</s>

<s docid="AP900807-0029" num="22" wdcount="23"> Kuwait, after all, reflagged tankers in the United States during the Iran-Iraq war, ushering in the reason for the arrival of the U.S.</s>

<s docid="AP900807-0029" num="23" wdcount="7"> Navy in the Persian Gulf in force.</s>

<s docid="AP900807-0029" num="24" wdcount="26"> Iran's official Islamic Republic News Agency printed excerpts Mondya of an editorial from the Ettela'at newspaper that was headlined: ``Foster child turns rapaciously on nourisher Kuwait''.</s>

<s docid="AP900807-0029" num="25" wdcount="21"> It noted that Kuwait had blindly supported Iraq, ``little knowing that it was feeding a wild beast in her own neighborhood''.</s>

<s docid="AP900807-0029" num="26" wdcount="9"> Saddam has also been called generalissimo and The Invader.</s>

<s docid="AP900807-0029" num="27" wdcount="17"> Under the Frankenstein headline, IRNA said in its own commentary: ``For the time being, tiny Kuwait ...</s>

<s docid="AP900807-0029" num="28" wdcount="3"> breathes no more.</s>

<s docid="AP900807-0029" num="29" wdcount="29"> With its sheikh a stateless person, and its powerful dinar which bankrolled the Iraqi military mere garbage, Kuwait is a nonentity, swallowed up by the dangerous pet it reared''.</s>

<s docid="AP900807-0029" num="30" wdcount="15"> Despite all the attention to the dangerous pet, the Great Satan has not been forgotton.</s>

<s docid="AP900807-0029" num="31" wdcount="10"> According to Iran's pundits, the Great Satan planned it all.</s>

<s docid="AP900807-0029" num="32" wdcount="12"> It wanted to get the Navy back in the Persian Gulf .</s>
</TEXT>
</DOC>
