<DOC>
<DOCNO>

<s docid="AP900807-0093" num="1" wdcount="1"> AP900807-0093</s>
</DOCNO>
<FILEID>

<s docid="AP900807-0093" num="2" wdcount="2"> AP-NR-08-07-90 1354EDT</s>
</FILEID>
<FIRST>

<s docid="AP900807-0093" num="3" wdcount="7"> u i PM-Iraq-Foreigners 4thLd-Writethru a0588 08-07 0368</s>
</FIRST>
<SECOND>

<s docid="AP900807-0093" num="4" wdcount="4"> PM-Iraq-Foreigners, 4th Ld-Writethru, a0588,0375</s>
</SECOND>
<HEAD>

<s docid="AP900807-0093" num="5" wdcount="1"> URGENT</s>
</HEAD>
<HEAD>

<s docid="AP900807-0093" num="6" wdcount="7"> 78 Foreigners Arrive in Amman from Iraq</s>
</HEAD>
<DATELINE>

<s docid="AP900807-0093" num="7" wdcount="3"> AMMAN, Jordan (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900807-0093" num="8" wdcount="32"> An Iraqi airways jet carrying 78 foreigners and a number of Iraqi citizens arrived today, the first commercial flight allowed out of Iraq since it invaded Kuwait, a Japanese Embassy spokesman said.</s>

<s docid="AP900807-0093" num="9" wdcount="11"> The mostly Japanese tourists arrived at Amman airport at 6:15 p.m.</s>

<s docid="AP900807-0093" num="10" wdcount="2"> (11:15 a.m.</s>

<s docid="AP900807-0093" num="11" wdcount="17"> EDT) along with 34 members of an Iraqi football team, said the spokesman on condition of anonymity.</s>

<s docid="AP900807-0093" num="12" wdcount="11"> It was not immediately known if there were Americans on board.</s>

<s docid="AP900807-0093" num="13" wdcount="14"> He said that the plane was due to leave Amman for an undisclosed destination.</s>

<s docid="AP900807-0093" num="14" wdcount="17"> The spokesman said the plane was supposed to land in Vienna, but it was denied landing rights.</s>

<s docid="AP900807-0093" num="15" wdcount="2"> The U.N.</s>

<s docid="AP900807-0093" num="16" wdcount="16"> Security Council on Monday voted economic sanctions that ban all trade and military ties with Iraq.</s>

<s docid="AP900807-0093" num="17" wdcount="27"> Jordan's information minister, Ibrahim Izzedine, said earlier today that the U.S. government had asked Jordan to facilitate the entrance from Iraq of American diplomats and their dependents.</s>

<s docid="AP900807-0093" num="18" wdcount="9"> Izzedine said the request was made through the U.S.</s>

<s docid="AP900807-0093" num="19" wdcount="3"> Embassy in Amman.</s>

<s docid="AP900807-0093" num="20" wdcount="16"> Thousands of Westerners have been stranded in Kuwait and Iraq since Iraq invaded Kuwait on Thursday.</s>

<s docid="AP900807-0093" num="21" wdcount="20"> They include more than 350 who were on a British Airways flight that was caught in the unrest in Kuwait.</s>

<s docid="AP900807-0093" num="22" wdcount="18"> A British Airways spokeswoman said today a ``substantial'' number of those passengers arrived safely in Baghdad on Monday.</s>

<s docid="AP900807-0093" num="23" wdcount="25"> Among the passengers were 28 Americans, who also turned up in a Baghdad hotel and appear to be fine, a U.S. official said in Washington.</s>

<s docid="AP900807-0093" num="24" wdcount="20"> In addition, a Kuwaiti businessman said about 1,000 people a day were fleeing Kuwait through the desert to Saudi Arabia.</s>

<s docid="AP900807-0093" num="25" wdcount="28"> The businessman, who arrived in London on a British Airways flight from Bahrain today, said Kuwaitis and expatriates, including Westerners, were joining convoys to escape the Iraqi forces.</s>

<s docid="AP900807-0093" num="26" wdcount="18"> Jordan's borders with Iraq had been closed from the Iraqi side since Thursday morning, when Iraq invaded Kuwait.</s>

<s docid="AP900807-0093" num="27" wdcount="23"> The ``provisional government of free Kuwait'' set up by Iraq had threatened Sunday to hold hostage citizens of countries imposing sanctions on it.</s>

<s docid="AP900807-0093" num="28" wdcount="21"> A U.S. diplomat said Washington had instructed ``American citizens living in or visiting Iraq and Kuwait to leave when circumstances permit.''</s>
</TEXT>
</DOC>
