<DOC>
<DOCNO>

<s docid="AP900808-0030" num="1" wdcount="1"> AP900808-0030</s>
</DOCNO>
<FILEID>

<s docid="AP900808-0030" num="2" wdcount="2"> AP-NR-08-08-90 0317EDT</s>
</FILEID>
<FIRST>

<s docid="AP900808-0030" num="3" wdcount="5"> r i PM-Iraq-Embargoes 08-08 0532</s>
</FIRST>
<SECOND>

<s docid="AP900808-0030" num="4" wdcount="1"> PM-Iraq-Embargoes,0547</s>
</SECOND>
<HEAD>

<s docid="AP900808-0030" num="5" wdcount="6"> Worldwide Embargoes Against Iraq Gain Momentum</s>
</HEAD>
<HEAD>

<s docid="AP900808-0030" num="6" wdcount="4"> With PM-Iraq-Kuwait Rdp, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP900808-0030" num="7" wdcount="3"> By TERRIL JONES</s>
</BYLINE>
<BYLINE>

<s docid="AP900808-0030" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900808-0030" num="9" wdcount="2"> PARIS (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900808-0030" num="10" wdcount="18"> Hitting Baghdad where it hurts, more countries have joined a U.N.-sanctioned boycott of oil from Iraq and Kuwait.</s>

<s docid="AP900808-0030" num="11" wdcount="34"> On Tuesday, countries ranging from powerful Japan to neutral Switzerland to tiny Cyprus cut off petroleum imports in an effort to convince the Baghdad government to withdraw its troops that invaded Kuwait on Thursday.</s>

<s docid="AP900808-0030" num="12" wdcount="32"> Turkey announced it was shut down the twin Iraqi oil pipelines that run through it to the Mediterranean _ carrying half of Baghdad's crude output _ and cutting off trade with Iraq.</s>

<s docid="AP900808-0030" num="13" wdcount="18"> Baghdad's only other major pipelines exporting crude run through Saudi Arabia, where the flow has been drastically reduced.</s>

<s docid="AP900808-0030" num="14" wdcount="2"> The U.N.</s>

<s docid="AP900808-0030" num="15" wdcount="17"> Security Council on Monday voted to impose broad economic sanctions against Iraq for invading small oil-rich Kuwait.</s>

<s docid="AP900808-0030" num="16" wdcount="26"> The measure forbids loans to Iraq or Kuwait and prohibits any activities, including the transfer of money, that would help the two countries export their goods.</s>

<s docid="AP900808-0030" num="17" wdcount="23"> Sanctions adopted by the European Economic Community on Saturday froze Iraqi assets and suspended the purchase of oil from the two Arab countries.</s>

<s docid="AP900808-0030" num="18" wdcount="15"> More than 90 percent of imports from Iraq to the 12-nation EEC are petroleum products.</s>

<s docid="AP900808-0030" num="19" wdcount="8"> The EEC also suspended arms sales to Iraq.</s>

<s docid="AP900808-0030" num="20" wdcount="29"> Switzerland, which is not a member of the United Nations, made the unusual move Tuesday of joining the U.N. sanctions and banned all trade with Iraq and Iraqi-occupied Kuwait.</s>

<s docid="AP900808-0030" num="21" wdcount="14"> In addition, Switzerland prohibited all payments and other financial transfers to Iraq and Kuwait.</s>

<s docid="AP900808-0030" num="22" wdcount="13"> Denmark, Norway and Sweden also announced embargoes on all trade with both countries.</s>

<s docid="AP900808-0030" num="23" wdcount="30"> Japan's participation in the U.N. sanctions was seen as especially key since Tokyo usually has taken a low profile in the Middle East, which supplies much of its petroleum needs.</s>

<s docid="AP900808-0030" num="24" wdcount="7"> Japan imports 99 percent of its oil.</s>

<s docid="AP900808-0030" num="25" wdcount="24"> China joined the U.N. decision to embargo arms sales to Iraq, but has been less vocal than other major countries in condemning the invasion.</s>

<s docid="AP900808-0030" num="26" wdcount="19"> China sold arms to both Iran and Iraq during their eight-year war and is a major Iraqi trade partner.</s>

<s docid="AP900808-0030" num="27" wdcount="21"> Cyprus' sacrifice in joining the embargo was to give up 70 percent of its oil imports, government spokesman Akis Fantis said.</s>

<s docid="AP900808-0030" num="28" wdcount="29"> Cyprus has sufficient oil supplies to last until the end of August, he said, but ``we are already in the process of taking steps to secure alternative sources ''...</s>

<s docid="AP900808-0030" num="29" wdcount="36"> The worldwide closing of ranks against Iraqi oil imports is likely to lead to even higher petroleum prices, which have already risen dramatically since the invasion and could have a major impact on the world economy.</s>

<s docid="AP900808-0030" num="30" wdcount="12"> Wholesale oil prices soared to five-year highs in New York on Monday.</s>

<s docid="AP900808-0030" num="31" wdcount="31"> France will introduce controls Thursday on prices of petroleum products to prevent refiners from using Iraq's invasion of Kuwait as an excuse to raise prices, acting Premier Pierre Beregovoy announced Tuesday.</s>

<s docid="AP900808-0030" num="32" wdcount="23"> An official with the Petroleum Association of Japan said he was unaware of any increase yet in the price of gasoline for consumers.</s>

<s docid="AP900808-0030" num="33" wdcount="30"> The official, who refused to be further identified, said it would be at least three months before the sanctions could be expected to force higher gas prices in Japan .</s>
</TEXT>
</DOC>
