<DOC>
<DOCNO>

<s docid="AP900802-0118" num="1" wdcount="1"> AP900802-0118</s>
</DOCNO>
<FILEID>

<s docid="AP900802-0118" num="2" wdcount="2"> AP-NR-08-02-90 1335EDT</s>
</FILEID>
<FIRST>

<s docid="AP900802-0118" num="3" wdcount="5"> r i BC-Iraq-Kuwait-Quotes 08-02 0177</s>
</FIRST>
<SECOND>

<s docid="AP900802-0118" num="4" wdcount="1"> BC-Iraq-Kuwait-Quotes,0184</s>
</SECOND>
<HEAD>

<s docid="AP900802-0118" num="5" wdcount="6"> Quotes on Iraqi Invasion of Kuwait</s>
</HEAD>
<HEAD>

<s docid="AP900802-0118" num="6" wdcount="3"> With AM-Iraq-Kuwait, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP900802-0118" num="7" wdcount="4"> By The Associated Press</s>
</BYLINE>
<TEXT>

<s docid="AP900802-0118" num="8" wdcount="9"> Here are some quotes on Iraq's invasion of Kuwait:</s>
</TEXT>
<TEXT>

<s docid="AP900802-0118" num="9" wdcount="22"> ``The Iraqi government firmly believes and states that Iraq is pursuing no goal or objective and wishes only cordial relations with Kuwait.</s>

<s docid="AP900802-0118" num="10" wdcount="24"> Furthermore, it is the Kuwaitis themselves who will determine their own future and Iraqi forces will withdraw as soon as order has been restored''.</s>

<s docid="AP900802-0118" num="11" wdcount="13"> _ Sabah Talat Kadrat, Iraq's deputy permanent representative to the United Nations .</s>
</TEXT>
<TEXT>

<s docid="AP900802-0118" num="12" wdcount="13"> ``The pretext to invade an independent, sovereign state is a false, flimsy pretext.</s>

<s docid="AP900802-0118" num="13" wdcount="26"> This kind of pretext, if it's not going to be deterred in a decisive manner and by this august assembly, all international relations will be threatened.</s>

<s docid="AP900802-0118" num="14" wdcount="9"> No country at all will be safe after this''.</s>

<s docid="AP900802-0118" num="15" wdcount="10"> _ Mohammad Abulhasan, Kuwait's ambassador to the United Nations .</s>
</TEXT>
<TEXT>

<s docid="AP900802-0118" num="16" wdcount="19"> ``We remain committed to take whatever actions are necessary to defend our longstanding, vital interests in the (Persian) Gulf''.</s>

<s docid="AP900802-0118" num="17" wdcount="15"> _ President Bush, who said his advisers would ``consider all possible options available to us.''</s>
</TEXT>
</DOC>
