<DOC>
<DOCNO>

<s docid="LA080890-0078" num="1" wdcount="1"> LA080890-0078</s>
</DOCNO>
<DOCID>

<s docid="LA080890-0078" num="2" wdcount="1"> 258632</s>
</DOCID>
<DATE>
<P>

<s docid="LA080890-0078" num="3" wdcount="6"> August 8, 1990, Wednesday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA080890-0078" num="4" wdcount="8"> Part A; Page 12; Column 2; Foreign Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA080890-0078" num="5" wdcount="2"> 248 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA080890-0078" num="6" wdcount="9"> INVADERS TAKING OVER LIVES, HOMES OF KUWAITIS, AMBASSADOR CHARGES</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA080890-0078" num="7" wdcount="6"> By GERALDINE BAUM, TIMES STAFF WRITER</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA080890-0078" num="8" wdcount="1"> WASHINGTON</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA080890-0078" num="9" wdcount="35"> Invading Iraqis have been permitted to take over the homes and even wear the clothes of Kuwaitis who have been killed or have fled their homeland, Kuwait's ambassador to the United States charged Tuesday .</s>
</P>
<P>

<s docid="LA080890-0078" num="10" wdcount="40"> Sheik Saud al Nasir al Sabah said in an interview that he had spoken by telephone to several Kuwaitis taking refuge in Saudi Arabia and Bahrain, who reported that the Iraqis had made it easy for them to leave .</s>
</P>
<P>

<s docid="LA080890-0078" num="11" wdcount="23"> That is because the fleeing Kuwaitis apparently are being replaced by Iraqis seeking to meld in with the local population, he contended .</s>
</P>
<P>

<s docid="LA080890-0078" num="12" wdcount="36"> "They are trucking them in, busing them in, trying to replace the population, to change the makeup of the place," Saud said, adding they were issuing the new residents cards that identify them as Kuwaiti citizens.</s>

<s docid="LA080890-0078" num="13" wdcount="19"> "They are giving them Kuwaiti clothes in order to make it appear that these are the people of Kuwait.</s>

<s docid="LA080890-0078" num="14" wdcount="9"> They are taking the houses, robbing the houses" .</s>
</P>
<P>

<s docid="LA080890-0078" num="15" wdcount="26"> Kuwaiti officials who have been detained by the Iraqi military and who have refused to cooperate have been executed, Saud claimed, adding: "We have eyewitness reports.</s>

<s docid="LA080890-0078" num="16" wdcount="9"> Some were bused back to Baghdad for further interrogation.</s>

<s docid="LA080890-0078" num="17" wdcount="9"> We don't know what has become of them" .</s>
</P>
<P>

<s docid="LA080890-0078" num="18" wdcount="21"> Kuwaiti refugees have also reported that almost all government buildings and palaces have been blown up and destroyed, Saud said .</s>
</P>
<P>

<s docid="LA080890-0078" num="19" wdcount="21"> There has been "mass destruction," he said, noting that all official installations except the water system and oil equipment are ruined.</s>

<s docid="LA080890-0078" num="20" wdcount="4"> "Everything is gone" .</s>
</P>
</TEXT>
<SUBJECT>
<P>

<s docid="LA080890-0078" num="21" wdcount="21"> IRAQ -- FOREIGN RELATIONS -- KUWAIT; IRAQ -- ARMED FORCES -- KUWAIT; MILITARY CONFRONTATIONS; IRAQ -- ARMED FORCES -- KUWAIT; ASSIMILATION</s>
</P>
</SUBJECT>
</DOC>
