<DOC>
<DOCNO>

<s docid="LA080290-0037" num="1" wdcount="1"> LA080290-0037</s>
</DOCNO>
<DOCID>

<s docid="LA080290-0037" num="2" wdcount="1"> 255721</s>
</DOCID>
<DATE>
<P>

<s docid="LA080290-0037" num="3" wdcount="6"> August 2, 1990, Thursday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA080290-0037" num="4" wdcount="8"> Part A; Page 12; Column 5; Foreign Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA080290-0037" num="5" wdcount="2"> 299 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA080290-0037" num="6" wdcount="4"> HOW THE CONFLICT DEVELOPED</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA080290-0037" num="7" wdcount="3"> From Associated Press</s>
</P>
</BYLINE>
<TEXT>
<P>

<s docid="LA080290-0037" num="8" wdcount="20"> Here is a brief chronology in the dispute between Iraq and Kuwait over oil production and their common border .</s>
</P>
<P>

<s docid="LA080290-0037" num="9" wdcount="23"> July 17: Iraqi President Saddam Hussein accuses Kuwait and the United Arab Emirates of flooding the oil market and driving prices down .</s>
</P>
<P>

<s docid="LA080290-0037" num="10" wdcount="14"> He said that the move cost Iraq $14 billion in lost oil revenue .</s>
</P>
<P>

<s docid="LA080290-0037" num="11" wdcount="33"> July 18: Iraq accuses Kuwait of stealing $2.4 billion worth of oil from wells along disputed border with Iraq and seeking to wreck Iraq's economy by overproducing oil and pushing down prices .</s>
</P>
<P>

<s docid="LA080290-0037" num="12" wdcount="34"> July 20: Kuwaiti officials suggest Iraq's sudden outburst of belligerence is aimed at getting its creditors -- including Kuwait -- to write off billions of dollars in debts from the 1980-88 Iran-Iraq war .</s>
</P>
<P>

<s docid="LA080290-0037" num="13" wdcount="4"> July 24: The U.S.</s>

<s docid="LA080290-0037" num="14" wdcount="30"> Defense Department announces that Navy warships and aircraft are holding a "short-notice exercise" in the Persian Gulf with the United Arab Emirates, about 600 miles southeast of the Kuwait-Iraqi border.</s>

<s docid="LA080290-0037" num="15" wdcount="7"> Kuwait goes on state of alert .</s>
</P>
<P>

<s docid="LA080290-0037" num="16" wdcount="28"> July 25: Baghdad says that it will not be intimidated by U.S. pressure in its oil dispute with neighboring Kuwait, and Hussein summons the U.S. ambassador for talks.</s>

<s docid="LA080290-0037" num="17" wdcount="17"> President Hosni Mubarak of Egypt says Iraq and Kuwait will meet in Saudi Arabia for talks .</s>
</P>
<P>

<s docid="LA080290-0037" num="18" wdcount="20"> July 26: OPEC ministers in Geneva agree to halt overproduction in hopes of pushing up the price of crude oil.</s>

<s docid="LA080290-0037" num="19" wdcount="13"> Kuwait and the United Arab Emirates pledge to abide by the agreement .</s>
</P>
<P>

<s docid="LA080290-0037" num="20" wdcount="16"> July 31: Kuwaiti, Iraqi delegations meet in Jidda, Saudi Arabia, to negotiate oil and border dispute.</s>

<s docid="LA080290-0037" num="21" wdcount="16"> Diplomats say Iraq has 100,000 troops on Kuwait's border; Kuwait army numbers about 20,000 troops .</s>
</P>
<P>

<s docid="LA080290-0037" num="22" wdcount="14"> Aug. 1: Unconfirmed reports say Iraq has moved more troops toward the Kuwaiti border.</s>

<s docid="LA080290-0037" num="23" wdcount="5"> Talks in Jidda collapse .</s>
</P>
<P>

<s docid="LA080290-0037" num="24" wdcount="12"> Aug. 2: Iraqi troops invade Kuwait at 2 a.m. local time .</s>
</P>
</TEXT>
<TYPE>
<P>

<s docid="LA080290-0037" num="25" wdcount="3"> Sidebar; Chronology; Wire</s>
</P>
</TYPE>
<SUBJECT>
<P>

<s docid="LA080290-0037" num="26" wdcount="28"> IRAQ -- FOREIGN RELATIONS -- KUWAIT; MILITARY CONFRONTATIONS; OIL INDUSTRY -- KUWAIT; OIL INDUSTRY -- IRAQ; UNITED STATES -- FOREIGN RELATIONS -- IRAQ; IRAQ -- BORDERS -- KUWAIT</s>
</P>
</SUBJECT>
</DOC>
