<DOC>
<DOCNO>

<s docid="LA080690-0111" num="1" wdcount="1"> LA080690-0111</s>
</DOCNO>
<DOCID>

<s docid="LA080690-0111" num="2" wdcount="1"> 258363</s>
</DOCID>
<DATE>
<P>

<s docid="LA080690-0111" num="3" wdcount="6"> August 6, 1990, Monday, P.M. Final</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA080690-0111" num="4" wdcount="9"> Part P; Page 1; Column 6; Late Final Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA080690-0111" num="5" wdcount="2"> 502 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA080690-0111" num="6" wdcount="3"> IRAQIS SEIZE WESTERNERS;</s>
</P>
<P>

<s docid="LA080690-0111" num="7" wdcount="8"> HUNDREDS ROUNDED UP DURING SWEEP OF KUWAIT HOTELS;</s>
</P>
<P>

<s docid="LA080690-0111" num="8" wdcount="5"> U.N. COUNCIL VOTES BROAD SANCTIONS</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA080690-0111" num="9" wdcount="4"> From Times Wire Services</s>
</P>
</BYLINE>
<TEXT>
<P>

<s docid="LA080690-0111" num="10" wdcount="18"> Iraq struck back against the West today, rounding up hundreds of foreign nationals in Kuwait, as the U.N.</s>

<s docid="LA080690-0111" num="11" wdcount="19"> Security Council overwhelming approved sweeping trade and military sanctions against Iraq to punish it for invading the emirate .</s>
</P>
<P>

<s docid="LA080690-0111" num="12" wdcount="21"> The Iraqi invaders scoured hotels looking for some of the thousands of Westerners based in Kuwait or caught by the invasion.</s>

<s docid="LA080690-0111" num="13" wdcount="11"> More than 1 million foreigners live and work in Kuwait .</s>
</P>
<P>

<s docid="LA080690-0111" num="14" wdcount="27"> Several hundred Britons, Americans and West Germans were grabbed in the hotels, and some were taken to Iraq, the West German and British foreign ministries said .</s>
</P>
<P>

<s docid="LA080690-0111" num="15" wdcount="28"> Britain said Baghdad had given no reason for detaining 366 people, most of them passengers from a British Airways flight stranded at Kuwait airport by the invasion .</s>
</P>
<P>

<s docid="LA080690-0111" num="16" wdcount="22"> The U.N. sanctions, which included a ban on oil purchases, came on a vote of 13 to 0, on the 15-member council.</s>

<s docid="LA080690-0111" num="17" wdcount="15"> Cuba and Yemen abstained on the resolution, which was proposed by the United States .</s>
</P>
<P>

<s docid="LA080690-0111" num="18" wdcount="35"> The Iraqi-installed Kuwait government had earlier warned foreign countries that they should not forget their citizens in Kuwait while heaping on economic punishments, and today's roundup appeared to be a reaction against the sanctions .</s>
</P>
<P>

<s docid="LA080690-0111" num="19" wdcount="21"> Iraqi troops rolled into its New Jersey-sized neighbor Thursday, conquering the capital and moving south toward the Saudi Arabian border .</s>
</P>
<P>

<s docid="LA080690-0111" num="20" wdcount="37"> Persian Gulf oil sources said today that they had seen Saudi troops moving north toward the Kuwaiti frontier near the oil port of Khafji, but the Saudis denied that they had sent reinforcements to the border .</s>
</P>
<P>

<s docid="LA080690-0111" num="21" wdcount="30"> Iraqi authorities today told Turkey's state-run pipeline company that one of the twin pipelines that carry Baghdad's oil through Turkey will be closed "for reasons of marketing," officials said .</s>
</P>
<P>

<s docid="LA080690-0111" num="22" wdcount="33"> World oil prices soared to their highest level in more than four years today as more countries joined the attempt to strangle Baghdad's economy and force it to withdraw its invasion troops .</s>
</P>
<P>

<s docid="LA080690-0111" num="23" wdcount="10"> Iraq's oil revenues totaled more than $11 billion last year.</s>

<s docid="LA080690-0111" num="24" wdcount="29"> It has been pressing for higher oil prices to rebuild an economy damaged by the 1980-88 war with Iran and settle foreign debts of up to $80 billion .</s>
</P>
<P>

<s docid="LA080690-0111" num="25" wdcount="33"> One of the reasons Iraq gave for invading Kuwait was Kuwaiti reluctance to slow its flow of oil and push oil prices higher, but it was Iraqi oil that had slowed today .</s>
</P>
<P>

<s docid="LA080690-0111" num="26" wdcount="30"> "There are very few tankers loading Iraqi oil at Yumurtalik," a senior Turkish government official said, referring to the export jetties on the Turkish side of the Mediterranean Sea .</s>
</P>
<P>

<s docid="LA080690-0111" num="27" wdcount="18"> In Baghdad, President Saddam Hussein ordered drills for millions of people in case mass evacuations were needed .</s>
</P>
<P>

<s docid="LA080690-0111" num="28" wdcount="17"> He warned his nation's 17 million people to be on alert for possible U.S. or Israeli attacks.</s>

<s docid="LA080690-0111" num="29" wdcount="26"> The United States has warned Iraq against any attack on Saudi Arabia, and President Bush has said all options are open for the United States .</s>
</P>
<P>

<s docid="LA080690-0111" num="30" wdcount="23"> Hundreds of Kuwaitis took to the desert to flee into Saudi Arabia, their children and a few belongings crammed into four-wheel-drive vehicles .</s>
</P>
<P>

<s docid="LA080690-0111" num="31" wdcount="4"> RELATED STORIES: Pages 2,3</s>
</P>
</TEXT>
<TYPE>
<P>

<s docid="LA080690-0111" num="32" wdcount="1"> Wire</s>
</P>
</TYPE>
</DOC>
