<DOC>
<DOCNO>

<s docid="SJMN91-06255434" num="1" wdcount="1"> SJMN91-06255434</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06255434" num="2" wdcount="1"> 06255434</s>
</ACCESS>
<CAPTION>

<s docid="SJMN91-06255434" num="3" wdcount="35"> Photo; PHOTO: Knight-Ridder News Service; HI, HONEY -- Supreme Court nominee Clarence Thomas waves to his wife, Virginia, on Tuesday amid a flurry of media attention on day one of his Senate confirmation hearings .</s>
</CAPTION>
<DESCRIPT>

<s docid="SJMN91-06255434" num="4" wdcount="6"> US; COURT; JUDGE; CANDIDATE; SPOUSE; PROFILE</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06255434" num="5" wdcount="10"> Virginia Thomas is a soft-spoken, hard-working daughter of the heartland.</s>

<s docid="SJMN91-06255434" num="6" wdcount="4"> A brainy Omaha, Neb.</s>

<s docid="SJMN91-06255434" num="7" wdcount="11"> , lawyer who has scaled the sheer cliffs of professional Washington.</s>

<s docid="SJMN91-06255434" num="8" wdcount="9"> A churchgoer who invites homeless people out to lunch.</s>

<s docid="SJMN91-06255434" num="9" wdcount="3"> A good friend.</s>

<s docid="SJMN91-06255434" num="10" wdcount="5"> Why the fuss over Mrs.</s>

<s docid="SJMN91-06255434" num="11" wdcount="3"> Supreme Court Nominee?</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06255434" num="12" wdcount="1"> Front</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06255434" num="13" wdcount="12"> THOMAS' SPOUSE ALSO IN SPOTLIGHT CRITICS SAY HER VIEWS COULD INFLUENCE CASES</s>
</HEADLINE>
<MEMO>

<s docid="SJMN91-06255434" num="14" wdcount="1"> U.S.</s>

<s docid="SJMN91-06255434" num="15" wdcount="18"> Supreme Court: The Thomas Nomination; See also related stories on pages 1A and 8A of this section .</s>
</MEMO>
<TEXT>

<s docid="SJMN91-06255434" num="16" wdcount="31"> Her critics see her as more than the supportive spouse who'll accompany her husband, Clarence, through his Senate confirmation hearings, which began Tuesday and are likely to run through next week.</s>

<s docid="SJMN91-06255434" num="17" wdcount="17"> They see a woman with strong opinions on issues that are bound to come before the court.</s>

<s docid="SJMN91-06255434" num="18" wdcount="14"> Some women's-rights activists are upset by her lobbying against such issues as comparable-worth legislation.</s>

<s docid="SJMN91-06255434" num="19" wdcount="21"> Some religious rights groups are troubled by her anti-cult activities in light of her former involvement with Lifespring, a motivational group.</s>

<s docid="SJMN91-06255434" num="20" wdcount="21"> Skin color an issue; Even the color of her skin is being used to determine the content of Clarence Thomas's character.</s>

<s docid="SJMN91-06255434" num="21" wdcount="25"> The fact that she is white has drawn criticism from some blacks who see the marriage as evidence that Clarence Thomas has rejected his roots.</s>

<s docid="SJMN91-06255434" num="22" wdcount="25"> In their respective careers, the Thomases have embraced the view that women and minorities are hindered, rather than helped, by affirmative action and government programs.</s>

<s docid="SJMN91-06255434" num="23" wdcount="13"> True equality is achieved by holding everyone to the same standard, they believe.</s>

<s docid="SJMN91-06255434" num="24" wdcount="24"> "I don't think it's fair to say she's anti-women's rights," said Ricky Silberman, vice chairwoman of the EEOC and a friend of the Thomases.</s>

<s docid="SJMN91-06255434" num="25" wdcount="57"> She said Virginia Thomas opposed legislation on comparable worth because it would have involved the government in determining wages, which is "not good for the economy, not good for workers, not good for women."; Conservative viewpoint; Virginia Thomas has represented the conservative viewpoint in her jobs as a staffer for a Republican congressman, spokeswoman at the U.S.</s>

<s docid="SJMN91-06255434" num="26" wdcount="12"> Chamber of Congress and deputy assistant secretary at the Department of Labor.</s>

<s docid="SJMN91-06255434" num="27" wdcount="16"> Clarence Thomas advocates a colorblind society, and his marriage may be an example of that philosophy.</s>

<s docid="SJMN91-06255434" num="28" wdcount="6"> But others see a different symbolism.</s>

<s docid="SJMN91-06255434" num="29" wdcount="26"> "His marrying a white woman is a sign of his rejection of the black community," said Russell Adams, chairman of Howard University's department of Afro-American studies.</s>

<s docid="SJMN91-06255434" num="30" wdcount="15"> "Great justices have had community roots that served as a basis for understanding the Constitution.</s>

<s docid="SJMN91-06255434" num="31" wdcount="21"> Clarence's lack of a sense of community makes his nomination troubling."; Religious leaders wonder; Some religious leaders are troubled as well.</s>

<s docid="SJMN91-06255434" num="32" wdcount="31"> Dean Kelley, the National Council of Churches' counselor on religious liberty, wrote a critique of Clarence Thomas that was used as grounds for his organization's opposition to the Supreme Court nominee.</s>

<s docid="SJMN91-06255434" num="33" wdcount="37"> The author did not mention Virginia Thomas in his text, but has said he was concerned about her involvement in the Cult Awareness Network (CAN), a Chicago-based organization that says it educates the public about "destructive" cults.</s>

<s docid="SJMN91-06255434" num="34" wdcount="20"> That involvement, he said, might affect her husband's handling of religious-liberty cases if he shares her views on the subject.</s>

<s docid="SJMN91-06255434" num="35" wdcount="21"> During the early '80s, Virginia Thomas enrolled in Lifespring, a self-help course that challenges students to take responsibility for their lives.</s>

<s docid="SJMN91-06255434" num="36" wdcount="20"> A small percentage of the program's 300,000 graduates have been deeply disturbed by Lifespring's methods, which involve intense emotional self-examination.</s>

<s docid="SJMN91-06255434" num="37" wdcount="18"> A clean break; Virginia Thomas was troubled by some of Lifespring's activities and eventually broke with the organization.</s>

<s docid="SJMN91-06255434" num="38" wdcount="11"> Since 1985, she has been a public advocate against cult activities.</s>

<s docid="SJMN91-06255434" num="39" wdcount="10"> When she served as a labor-relations attorney at the U.S.</s>

<s docid="SJMN91-06255434" num="40" wdcount="31"> Chamber of Commerce from 1985 to 1989, she represented the interests of the business community at congressional hearings on such issues as comparable worth, affirmative action and federal child-care legislation .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06255434" num="41" wdcount="4"> LAURA BLUMENFELD, Washington Post</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06255434" num="42" wdcount="1"> USA</s>
</COUNTRY>
<CITY>

<s docid="SJMN91-06255434" num="43" wdcount="1"> Washington</s>
</CITY>
<EDITION>

<s docid="SJMN91-06255434" num="44" wdcount="2"> Morning Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06255434" num="45" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06255434" num="46" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06255434" num="47" wdcount="1"> 910911</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06255434" num="48" wdcount="1"> Wednesday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06255434" num="49" wdcount="1"> September</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06255434" num="50" wdcount="1"> 9A</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06255434" num="51" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06255434" num="52" wdcount="1"> WEST</s>
</REGION>
<FEATURE>

<s docid="SJMN91-06255434" num="53" wdcount="1"> PHOTO</s>
</FEATURE>
<STATE>

<s docid="SJMN91-06255434" num="54" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06255434" num="55" wdcount="1"> 651</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06255434" num="56" wdcount="5"> Wednesday, September 11, 1991 00255434,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06255434" num="57" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06255434" num="58" wdcount="1"> 1</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06255434" num="59" wdcount="1"> ENG</s>
</LANGUAGE>
</DOC>
