<DOC>
<DOCNO>

<s docid="SJMN91-06255336" num="1" wdcount="1"> SJMN91-06255336</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06255336" num="2" wdcount="1"> 06255336</s>
</ACCESS>
<CAPTION>

<s docid="SJMN91-06255336" num="3" wdcount="19"> Photo; PHOTO: Associated Press; Supreme Court nominee Clarence Thomas is sworn in before the Senate Judiciary Committee on Tuesday.</s>

<s docid="SJMN91-06255336" num="4" wdcount="12"> Both supporters and opponents of the federal judge are lobbying senators .</s>
</CAPTION>
<DESCRIPT>

<s docid="SJMN91-06255336" num="5" wdcount="6"> US; COURT; JUDGE; CANDIDATE; MEETING; CONGRESS</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06255336" num="6" wdcount="31"> While the 14-member Senate Judiciary Committee presses Clarence Thomas to explain his qualifications for the Supreme Court, all 100 senators are under mounting pressure to explain their views of the judge.</s>

<s docid="SJMN91-06255336" num="7" wdcount="7"> There were these signs of pressure Tuesday:</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06255336" num="8" wdcount="1"> Front</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06255336" num="9" wdcount="10"> SENATORS PRESSED FOR OPINIONS ON JUDGE PARTISAN GROUPS TARGET LAWMAKERS</s>
</HEADLINE>
<MEMO>

<s docid="SJMN91-06255336" num="10" wdcount="1"> U.S.</s>

<s docid="SJMN91-06255336" num="11" wdcount="18"> Supreme Court: The Thomas Nomination; See also related stories on pages 1A and 8-9A of this section .</s>
</MEMO>
<TEXT>

<s docid="SJMN91-06255336" num="12" wdcount="40"> (check) About 300 black pastors, representing congregations totaling more than 1 million churchgoers in 30 states, held a rally on the steps of the Supreme Court and then lobbied their senators to support confirmation of President Bush's Supreme Court nominee.</s>

<s docid="SJMN91-06255336" num="13" wdcount="28"> The ministers were recently organized into a conservative Coalition for the Restoration of the Black Family and Society, with the first item on its agenda being Thomas' confirmation.</s>

<s docid="SJMN91-06255336" num="14" wdcount="44"> (check) A television ad supporting Thomas, shown in four Southern states where senators face re-election campaigns next year, attracted 10,000 calls between Friday and Sunday, according to Gary Bauer, organizer of the conservative Citizens Committee to Confirm Clarence Thomas, which financed the ad's production.</s>

<s docid="SJMN91-06255336" num="15" wdcount="36"> The ad carries a toll-free telephone number that viewers are asked to call to register their support for Thomas; callers are then sorted by states, and the state lists will be sent to the targeted senators.</s>

<s docid="SJMN91-06255336" num="16" wdcount="49"> (check) On the other side of the Thomas confirmation issue, the National Abortion Rights Action League reported that senators had begun to receive the first of 500,000 anti-Thomas post cards the group has provided to the constituents of targeted lawmakers whose votes against Thomas' confirmation are regarded as critical.</s>

<s docid="SJMN91-06255336" num="17" wdcount="41"> (check) The Lawyers' Committee for Civil Rights Under Law, a bipartisan group organized in 1963 to assist the government in civil-rights law enforcement, announced that 86 of about 110 members of its board of directors had decided to oppose Thomas' confirmation.</s>

<s docid="SJMN91-06255336" num="18" wdcount="20"> The announcement said Thomas' legal philosophy reflected a "hostility to and rejection of the core of civil rights jurisprudence" .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06255336" num="19" wdcount="2"> Baltimore Sun</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06255336" num="20" wdcount="1"> USA</s>
</COUNTRY>
<CITY>

<s docid="SJMN91-06255336" num="21" wdcount="1"> Washington</s>
</CITY>
<EDITION>

<s docid="SJMN91-06255336" num="22" wdcount="2"> Morning Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06255336" num="23" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06255336" num="24" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06255336" num="25" wdcount="1"> 910911</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06255336" num="26" wdcount="1"> Wednesday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06255336" num="27" wdcount="1"> September</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06255336" num="28" wdcount="1"> 8A</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06255336" num="29" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06255336" num="30" wdcount="1"> WEST</s>
</REGION>
<FEATURE>

<s docid="SJMN91-06255336" num="31" wdcount="1"> PHOTO</s>
</FEATURE>
<STATE>

<s docid="SJMN91-06255336" num="32" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06255336" num="33" wdcount="1"> 349</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06255336" num="34" wdcount="5"> Wednesday, September 11, 1991 00255336,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06255336" num="35" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06255336" num="36" wdcount="1"> 1</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06255336" num="37" wdcount="1"> ENG</s>
</LANGUAGE>
</DOC>
