<DOC>
<DOCNO>

<s docid="SJMN91-06261053" num="1" wdcount="1"> SJMN91-06261053</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06261053" num="2" wdcount="1"> 06261053</s>
</ACCESS>
<CAPTION>

<s docid="SJMN91-06261053" num="3" wdcount="28"> Photo; PHOTO: Associated Press; GOING WAY BACK -- Supreme Court nominee Clarence Thomas greets Sister Virgilius Reidy, his eighth-grade teacher, before Monday's continuation of his confirmation hearings .</s>
</CAPTION>
<DESCRIPT>

<s docid="SJMN91-06261053" num="4" wdcount="6"> US; CONGRESS; COURT; JUDGE; APPOINTMENT; PROBE</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06261053" num="5" wdcount="28"> Clarence Thomas completed five grueling days of Senate questioning Monday, apparently well on his way to becoming the second black justice in the history of the Supreme Court.</s>

<s docid="SJMN91-06261053" num="6" wdcount="28"> "I have been honored to participate in this process," Thomas said before breaking into a broad grin and effusively gripping the hands of his Judiciary Committee interrogators .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06261053" num="7" wdcount="1"> Front</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06261053" num="8" wdcount="12"> SENATE QUESTIONING OF THOMAS ENDS BUSH NOMINEE APPEARS HEADED FOR HIGH COURT</s>
</HEADLINE>
<TEXT>

<s docid="SJMN91-06261053" num="9" wdcount="29"> The committee will continue to hear testimony for and against Thomas at least through the end of the week, but the outcome does not seem to be in doubt.</s>

<s docid="SJMN91-06261053" num="10" wdcount="21"> Several committee members said they expected the committee to recommend, by a 10-4 or 9-5 vote, that the Senate confirm Thomas.</s>

<s docid="SJMN91-06261053" num="11" wdcount="37"> Regardless of the outcome, Thomas said on his way out of the hearing, "I have been treated fairly."; Before Thomas' testimony ended, the unflappable 43-year-old federal judge was criticized, sometimes in harsh terms, by several liberal Democrats.</s>

<s docid="SJMN91-06261053" num="12" wdcount="23"> They accused him of being evasive and of disavowing many controversial statements he made while an official of the Reagan and Bush administrations.</s>

<s docid="SJMN91-06261053" num="13" wdcount="21"> Thomas repeatedly explained that he made the speeches as an advocate for administration policy, acknowledging that they often contained overheated rhetoric.</s>

<s docid="SJMN91-06261053" num="14" wdcount="52"> Sen. Howard Metzenbaum, D-Ohio, said he found it "difficult to accept the notion that the moment you put on a judge's robe all the views and positions which you held prior to going on the bench just magically disappear."; "I want to look into the window of your soul," Patrick Leahy, D-Vt.</s>

<s docid="SJMN91-06261053" num="15" wdcount="4"> , said to Thomas.</s>

<s docid="SJMN91-06261053" num="16" wdcount="13"> "but I find the shade down quite a bit."; Sen. Edward Kennedy, D-Mass.</s>

<s docid="SJMN91-06261053" num="17" wdcount="39"> , delivered a long, stinging lecture to Thomas, declaring: "The vanishing views of Judge Thomas have become a major issue in these hearings."; Kennedy listed 10 instances in which he said Thomas had abandoned or contradicted his previous positions.</s>

<s docid="SJMN91-06261053" num="18" wdcount="41"> Kennedy told Thomas he had "walked away" from his record on the right to privacy, refused to comment on its application to abortion and asked lawmakers "to believe that an intelligent and outspoken person like yourself has never discussed Roe vs.</s>

<s docid="SJMN91-06261053" num="19" wdcount="40"> Wade (the landmark 1973 abortion-rights ruling) with another human being."; Moderate Republican Arlen Specter of Pennsylvania, who often casts a swing vote on the committee, said he was not troubled by Thomas' shift toward more moderate views at the hearings.</s>

<s docid="SJMN91-06261053" num="20" wdcount="9"> "I believe he's going to be a surprising justice.</s>

<s docid="SJMN91-06261053" num="21" wdcount="10"> I don't think you can pigeonhole this man," Specter said.</s>

<s docid="SJMN91-06261053" num="22" wdcount="36"> If Thomas is confirmed as expected, he made it clear that, for the first time in decades, there would be not one justice on the Supreme Court who is convinced that capital punishment is unconstitutionally cruel.</s>

<s docid="SJMN91-06261053" num="23" wdcount="22"> Justice Thurgood Marshall, whom Thomas would replace, was the last member of the court who opposed the death penalty in all cases.</s>

<s docid="SJMN91-06261053" num="24" wdcount="53"> Thomas told the Judiciary Committee that "philosophically, there is nothing that would bother me personally about upholding it (the death penalty) in appropriate cases."; After Thomas left the hearing room, an American Bar Association evaluation committee told the senators that his articles in law journals were deficient in presentation, content, scholarship and analysis.</s>

<s docid="SJMN91-06261053" num="25" wdcount="34"> But those limitations were outweighed by his "brief but highly satisfactory performance on the Court of Appeals," the committee said, noting that "we found only one opinion to criticize and many to praise" .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06261053" num="26" wdcount="6"> AARON EPSTEIN, Mercury News Washington Bureau</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06261053" num="27" wdcount="1"> USA</s>
</COUNTRY>
<CITY>

<s docid="SJMN91-06261053" num="28" wdcount="1"> Washington</s>
</CITY>
<EDITION>

<s docid="SJMN91-06261053" num="29" wdcount="2"> Morning Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06261053" num="30" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06261053" num="31" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06261053" num="32" wdcount="1"> 910917</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06261053" num="33" wdcount="1"> Tuesday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06261053" num="34" wdcount="1"> September</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06261053" num="35" wdcount="1"> 3A</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06261053" num="36" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06261053" num="37" wdcount="1"> WEST</s>
</REGION>
<FEATURE>

<s docid="SJMN91-06261053" num="38" wdcount="1"> PHOTO</s>
</FEATURE>
<STATE>

<s docid="SJMN91-06261053" num="39" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06261053" num="40" wdcount="1"> 571</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06261053" num="41" wdcount="5"> Tuesday, September 17, 1991 00261053,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06261053" num="42" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06261053" num="43" wdcount="1"> 1</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06261053" num="44" wdcount="1"> ENG</s>
</LANGUAGE>
</DOC>
