<DOC>
<DOCNO>

<s docid="SJMN91-06256124" num="1" wdcount="1"> SJMN91-06256124</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06256124" num="2" wdcount="1"> 06256124</s>
</ACCESS>
<CAPTION>

<s docid="SJMN91-06256124" num="3" wdcount="17"> Photos (2); PHOTO: Clarence Thomas (color); PHOTO: Knight-Ridder News Service; Thomas with wife Virginia during hearings .</s>
</CAPTION>
<DESCRIPT>

<s docid="SJMN91-06256124" num="4" wdcount="7"> US; COURT; JUDGE; CANDIDATE; APPOINTMENT; ABORTION; CONTROVERSY</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06256124" num="5" wdcount="29"> Supreme Court nominee Clarence Thomas told the Senate Judiciary Committee today it is "irrelevant" whether he holds any personal opinion on abortion, spurring new frustration among the committee's Democrats.</s>

<s docid="SJMN91-06256124" num="6" wdcount="21"> But as the hearings' third day got under way, no groundswell of opposition to his confirmation seemed to be emerging .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06256124" num="7" wdcount="1"> Front</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06256124" num="8" wdcount="13"> SENATORS DOUBTING THOMAS COURT NOMINEE SAYS HIS PERSONAL OPINION OF ABORTION IS 'IRRELEVANT'</s>
</HEADLINE>
<MEMO>

<s docid="SJMN91-06256124" num="9" wdcount="10"> Additional information attached to the end of this article .</s>
</MEMO>
<TEXT>

<s docid="SJMN91-06256124" num="10" wdcount="8"> Asked several times by Sen. Herb Kohl, D-Wis.</s>

<s docid="SJMN91-06256124" num="11" wdcount="55"> , about women's right to end their pregnancies, Thomas said, "Whether or not I have a view is irrelevant."; President Bush, asked at a news conference whether Thomas' claim not to have an opinion on abortion is credible, answered, "That's a question for the Senate to decide."; "He's handling himself very well," the president said.</s>

<s docid="SJMN91-06256124" num="12" wdcount="9"> "I think he's doing a beautiful job up there.</s>

<s docid="SJMN91-06256124" num="13" wdcount="25"> I feel more confident than ever that he will be confirmed."; Thomas' answers have frustrated the committee's Democrats, who say he is an evasive witness.</s>

<s docid="SJMN91-06256124" num="14" wdcount="18"> They also have voiced skepticism about his backing away from stands he took in past writings and speeches.</s>

<s docid="SJMN91-06256124" num="15" wdcount="5"> Committee Chairman Joseph Biden, D-Del.</s>

<s docid="SJMN91-06256124" num="16" wdcount="28"> , began to show signs of exasperation today during spirited questioning about the nominee's views on "natural law," a theory that certain rights exist independent of written law.</s>

<s docid="SJMN91-06256124" num="17" wdcount="10"> At one point, Biden accused Thomas of using "tortuous logic".</s>

<s docid="SJMN91-06256124" num="18" wdcount="15"> Later, he referred to one of Thomas' replies as "the most unartful dodge I've heard".</s>

<s docid="SJMN91-06256124" num="19" wdcount="29"> After still another Thomas answer, Biden said, "That's not the question I asked you, judge."; Republicans tried to deflect criticism over Thomas' refusal to answer questions from the Democrats.</s>

<s docid="SJMN91-06256124" num="20" wdcount="15"> "It is, in my view, inappropriate to keep this up," said Sen. Orrin Hatch, R-Utah.</s>

<s docid="SJMN91-06256124" num="21" wdcount="19"> He said Thomas had been asked more than 70 questions about his abortion views even though Justice David H.</s>

<s docid="SJMN91-06256124" num="22" wdcount="13"> Souter was asked only 36 such questions during his confirmation hearings last year.</s>

<s docid="SJMN91-06256124" num="23" wdcount="6"> "What are we going to have?</s>

<s docid="SJMN91-06256124" num="24" wdcount="10"> Sixty-four-thousand questions on abortion before we're done with this approach"?</s>

<s docid="SJMN91-06256124" num="25" wdcount="2"> Hatch asked.</s>

<s docid="SJMN91-06256124" num="26" wdcount="47"> "Enough is enough."; Thomas said Senate confirmation of his nomination would give him "an opportunity to serve and give back" and to "bring something different to the court."; "I can walk in the shoes of the people who are affected by what the court does," Thomas said.</s>

<s docid="SJMN91-06256124" num="27" wdcount="22"> Several senators were openly skeptical Wednesday over Thomas' insistence that he has no opinion on the 1973 Supreme Court decision legalizing abortion.</s>

<s docid="SJMN91-06256124" num="28" wdcount="8"> If that's so, said Sen. Paul Simon, D-Ill.</s>

<s docid="SJMN91-06256124" num="29" wdcount="88"> , "he's the only person gathered in the room who does not have an opinion."; Kohl added, "I'm concerned about his candor, his willingness to be forthcoming."; Today, Kohl asked the nominee, "Is it fair of you to say to us, for the most part, just view me on what I'm saying here this week?"; Kohl asked the black federal judge whether he was offended by published comments calling his appointment by President Bush a "quota."; "That would trouble anyone," Thomas said, adding, "I don't think it's accurate".</s>

<s docid="SJMN91-06256124" num="30" wdcount="19"> He said Bush assured him he was picked because he was the best qualified of those potential nominees considered.</s>

<s docid="SJMN91-06256124" num="31" wdcount="8"> Thomas is expected to continue testifying through Friday.</s>

<s docid="SJMN91-06256124" num="32" wdcount="9"> The committee next week will hear from other witnesses.</s>

<s docid="SJMN91-06256124" num="33" wdcount="11"> Two pivotal members of the 14-member committee -- Howell Heflin, D-Ala.</s>

<s docid="SJMN91-06256124" num="34" wdcount="5"> , and Arlen Specter, R-Pa.</s>

<s docid="SJMN91-06256124" num="35" wdcount="7"> -- also voiced concern about Thomas' answers.</s>

<s docid="SJMN91-06256124" num="36" wdcount="10"> But the panel's traditional third swing vote, Dennis DeConcini, D-Ariz.</s>

<s docid="SJMN91-06256124" num="37" wdcount="6"> , said Thomas was doing well.</s>

<s docid="SJMN91-06256124" num="38" wdcount="27"> Thomas' opponents believe Republicans Strom Thurmond of South Carolina, Hatch, Charles Grassley of Iowa, Alan Simpson of Wyoming and Hank Brown of Colorado are solid Thomas backers.</s>

<s docid="SJMN91-06256124" num="39" wdcount="4"> But they hope Sens.</s>

<s docid="SJMN91-06256124" num="40" wdcount="4"> Edward M. Kennedy, D-Mass.</s>

<s docid="SJMN91-06256124" num="41" wdcount="27"> , and Howard Metzenbaum, D-Ohio, will be joined by the three swing-vote senators and Biden, Patrick Leahy of Vermont, Simon and Kohl in voting against the nominee.</s>

<s docid="SJMN91-06256124" num="42" wdcount="114"> THOMAS' VIEWS; Excerpts from Clarence Thomas' testimony:; On abortion: "I have no reason or agenda to prejudge the issue . . . or a predilection to rule one way or another on the issue of abortion."; On affirmative action: "The line that I drew was a line that said that we shouldn't have preferences, or goals, or timetables or quotas."; On natural law: "At no time did I feel, nor do I feel now, that natural law is anything more than the background to our Constitution."; HEAR IT, SEE IT; Senate confirmation hearings for Supreme Court nominee Clarence Thomas are scheduled to run through Friday this week and every weekday except Wednesday next week.</s>

<s docid="SJMN91-06256124" num="43" wdcount="15"> RADIO; (box) KQED, 88.5 FM Tape delay beginning at 9 a.m. repeated at 9:30 p.m.</s>

<s docid="SJMN91-06256124" num="44" wdcount="10"> (box) KPFA, 94.1 FM Live coverage begins at 6:30 a.m.</s>

<s docid="SJMN91-06256124" num="45" wdcount="13"> TELEVISION; (box) C-SPAN Live coverage begins at 7 a.m. repeated at 5 p.m.</s>

<s docid="SJMN91-06256124" num="46" wdcount="5"> (box) CNN Intermittent coverage .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06256124" num="47" wdcount="2"> Associated Press</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06256124" num="48" wdcount="1"> USA</s>
</COUNTRY>
<CITY>

<s docid="SJMN91-06256124" num="49" wdcount="1"> Washington</s>
</CITY>
<EDITION>

<s docid="SJMN91-06256124" num="50" wdcount="2"> Stock Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06256124" num="51" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06256124" num="52" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06256124" num="53" wdcount="1"> 910912</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06256124" num="54" wdcount="1"> Thursday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06256124" num="55" wdcount="1"> September</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06256124" num="56" wdcount="1"> 1A</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06256124" num="57" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06256124" num="58" wdcount="1"> WEST</s>
</REGION>
<FEATURE>

<s docid="SJMN91-06256124" num="59" wdcount="1"> PHOTO</s>
</FEATURE>
<STATE>

<s docid="SJMN91-06256124" num="60" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06256124" num="61" wdcount="1"> 806</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06256124" num="62" wdcount="5"> Thursday, September 12, 1991 00256124,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06256124" num="63" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06256124" num="64" wdcount="1"> 1</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06256124" num="65" wdcount="2"> ENG FRONT</s>
</LANGUAGE>
</DOC>
