<DOC>
<DOCNO>

<s docid="SJMN91-06255421" num="1" wdcount="1"> SJMN91-06255421</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06255421" num="2" wdcount="1"> 06255421</s>
</ACCESS>
<CAPTION>

<s docid="SJMN91-06255421" num="3" wdcount="4"> Photo; PHOTO: Virginia Thomas</s>
</CAPTION>
<DESCRIPT>

<s docid="SJMN91-06255421" num="4" wdcount="6"> US; COURT; JUDGE; CANDIDATE; SPOUSE; PROBE</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06255421" num="5" wdcount="14"> Virginia Thomas is a soft-spoken, hard-working daughter of the heartland: a brainy Omaha, Neb.</s>

<s docid="SJMN91-06255421" num="6" wdcount="23"> , lawyer who has scaled the sheer cliffs of professional Washington; a churchgoer who invites homeless people out to lunch; a good friend.</s>

<s docid="SJMN91-06255421" num="7" wdcount="5"> Why the fuss over Mrs.</s>

<s docid="SJMN91-06255421" num="8" wdcount="3"> Supreme Court Nominee?</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06255421" num="9" wdcount="1"> Front</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06255421" num="10" wdcount="5"> THOMAS' WIFE ALSO UNDERGOES SCRUTINY</s>
</HEADLINE>
<TEXT>

<s docid="SJMN91-06255421" num="11" wdcount="31"> Her critics see her as more than the supportive spouse who'll accompany her husband, Clarence, through his Senate confirmation hearings, which began Tuesday and are likely to run through next week.</s>

<s docid="SJMN91-06255421" num="12" wdcount="17"> They see a woman with strong opinions on issues that are bound to come before the court.</s>

<s docid="SJMN91-06255421" num="13" wdcount="14"> Some women's-rights activists are upset by her lobbying against such issues as comparable-worth legislation.</s>

<s docid="SJMN91-06255421" num="14" wdcount="20"> Some religious-rights groups are troubled by her anti-cult activities in light of her former involvement with Lifespring, a motivational group.</s>

<s docid="SJMN91-06255421" num="15" wdcount="21"> Her race draws criticism; Even the color of her skin is being used to determine the content of Clarence Thomas's character.</s>

<s docid="SJMN91-06255421" num="16" wdcount="25"> The fact that she is white has drawn criticism from some blacks who see the marriage as evidence that Clarence Thomas has rejected his roots.</s>

<s docid="SJMN91-06255421" num="17" wdcount="25"> In their respective careers, the Thomases have embraced the view that women and minorities are hindered, rather than helped, by affirmative action and government programs.</s>

<s docid="SJMN91-06255421" num="18" wdcount="13"> True equality is achieved by holding everyone to the same standard, they believe.</s>

<s docid="SJMN91-06255421" num="19" wdcount="21"> Virginia Thomas has represented the conservative viewpoint in her jobs as a staffer for a Republican congressman, spokeswoman at the U.S.</s>

<s docid="SJMN91-06255421" num="20" wdcount="12"> Chamber of Congress and deputy assistant secretary at the Department of Labor.</s>

<s docid="SJMN91-06255421" num="21" wdcount="16"> Clarence Thomas advocates a colorblind society, and his marriage may be an example of that philosophy.</s>

<s docid="SJMN91-06255421" num="22" wdcount="6"> But others see a different symbolism.</s>

<s docid="SJMN91-06255421" num="23" wdcount="29"> 'Sign of rejection'; "His marrying a white woman is a sign of his rejection of the black community," said Russell Adams, chairman of Howard University's department of Afro-American studies.</s>

<s docid="SJMN91-06255421" num="24" wdcount="15"> "Great justices have had community roots that served as a basis for understanding the Constitution.</s>

<s docid="SJMN91-06255421" num="25" wdcount="18"> Clarence's lack of a sense of community makes his nomination troubling."; Some religious leaders are troubled as well.</s>

<s docid="SJMN91-06255421" num="26" wdcount="31"> Dean Kelley, the National Council of Churches' counselor on religious liberty, wrote a critique of Clarence Thomas that was used as grounds for his organization's opposition to the Supreme Court nominee.</s>

<s docid="SJMN91-06255421" num="27" wdcount="37"> The author did not mention Virginia Thomas in his text but has said he was concerned about her involvement in the Cult Awareness Network (CAN), a Chicago-based organization that says it educates the public about "destructive" cults.</s>

<s docid="SJMN91-06255421" num="28" wdcount="20"> That involvement, he said, might affect her husband's handling of religious-liberty cases if he shares her views on the subject.</s>

<s docid="SJMN91-06255421" num="29" wdcount="21"> During the early '80s, Virginia Thomas enrolled in Lifespring, a self-help course that challenges students to take responsibility for their lives.</s>

<s docid="SJMN91-06255421" num="30" wdcount="14"> She was troubled by some of the activities and eventually broke with the organization.</s>

<s docid="SJMN91-06255421" num="31" wdcount="11"> Since 1985, she has been a public advocate against cult activities.</s>

<s docid="SJMN91-06255421" num="32" wdcount="10"> When she served as a labor-relations attorney at the U.S.</s>

<s docid="SJMN91-06255421" num="33" wdcount="31"> Chamber of Commerce from 1985 to 1989, she represented the interests of the business community at congressional hearings on such issues as comparable worth, affirmative action and federal child-care legislation .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06255421" num="34" wdcount="2"> Washington Post</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06255421" num="35" wdcount="1"> USA</s>
</COUNTRY>
<CITY>

<s docid="SJMN91-06255421" num="36" wdcount="1"> Washington</s>
</CITY>
<EDITION>

<s docid="SJMN91-06255421" num="37" wdcount="2"> Stock Final</s>
</EDITION>
<CODE>

<s docid="SJMN91-06255421" num="38" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06255421" num="39" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06255421" num="40" wdcount="1"> 910911</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06255421" num="41" wdcount="1"> Wednesday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06255421" num="42" wdcount="1"> September</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06255421" num="43" wdcount="1"> 8A</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06255421" num="44" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06255421" num="45" wdcount="1"> WEST</s>
</REGION>
<FEATURE>

<s docid="SJMN91-06255421" num="46" wdcount="1"> PHOTO</s>
</FEATURE>
<STATE>

<s docid="SJMN91-06255421" num="47" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06255421" num="48" wdcount="1"> 517</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06255421" num="49" wdcount="5"> Wednesday, September 11, 1991 00255421,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06255421" num="50" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06255421" num="51" wdcount="1"> 1</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06255421" num="52" wdcount="1"> ENG</s>
</LANGUAGE>
</DOC>
