<DOC>
<DOCNO>

<s docid="SJMN91-06256107" num="1" wdcount="1"> SJMN91-06256107</s>
</DOCNO>
<ACCESS>

<s docid="SJMN91-06256107" num="2" wdcount="1"> 06256107</s>
</ACCESS>
<CAPTION>

<s docid="SJMN91-06256107" num="3" wdcount="17"> Photos (2); PHOTO: Clarence Thomas (color); PHOTO: Knight-Ridder News Service; Thomas with wife Virginia during hearings .</s>
</CAPTION>
<DESCRIPT>

<s docid="SJMN91-06256107" num="4" wdcount="7"> US; COURT; JUDGE; CANDIDATE; APPOINTMENT; ABORTION; CONTROVERSY</s>
</DESCRIPT>
<LEADPARA>

<s docid="SJMN91-06256107" num="5" wdcount="29"> Frustrated Democrats on the Senate Judiciary Committee say Supreme Court nominee Clarence Thomas is an evasive witness, but no groundswell of opposition to his confirmation seems to be emerging.</s>

<s docid="SJMN91-06256107" num="6" wdcount="23"> Several senators were openly skeptical Wednesday over Thomas' insistence that he has no opinion on the 1973 Supreme Court decision legalizing abortion .</s>
</LEADPARA>
<SECTION>

<s docid="SJMN91-06256107" num="7" wdcount="1"> Front</s>
</SECTION>
<HEADLINE>

<s docid="SJMN91-06256107" num="8" wdcount="14"> SENATORS DOUBTING THOMAS ONE CALLS HIM 'ONLY PERSON IN ROOM' WITHOUT OPINION ON ABORTION</s>
</HEADLINE>
<MEMO>

<s docid="SJMN91-06256107" num="9" wdcount="10"> Additional information attached to the end of this article .</s>
</MEMO>
<TEXT>

<s docid="SJMN91-06256107" num="10" wdcount="8"> If that's so, said Sen. Paul Simon, D-Ill.</s>

<s docid="SJMN91-06256107" num="11" wdcount="19"> , "he's the only person gathered in the room who does not have an opinion."; Sen. Herb Kohl, D-Wis.</s>

<s docid="SJMN91-06256107" num="12" wdcount="12"> , added, "I'm concerned about his candor, his willingness to be forthcoming".</s>

<s docid="SJMN91-06256107" num="13" wdcount="12"> Kohl was today's leadoff questioner as the hearings entered their third day.</s>

<s docid="SJMN91-06256107" num="14" wdcount="11"> Two pivotal members of the 14-member committee -- Howell Heflin, D-Ala.</s>

<s docid="SJMN91-06256107" num="15" wdcount="5"> , and Arlen Specter, R-Pa.</s>

<s docid="SJMN91-06256107" num="16" wdcount="7"> -- also voiced concern about Thomas' answers.</s>

<s docid="SJMN91-06256107" num="17" wdcount="10"> But the panel's traditional third swing vote, Dennis DeConcini, D-Ariz.</s>

<s docid="SJMN91-06256107" num="18" wdcount="6"> , said Thomas was doing well.</s>

<s docid="SJMN91-06256107" num="19" wdcount="43"> Heflin cited the "appearance of a confirmation conversion" and said it may raise questions of Thomas' "integrity and temperament."; But Heflin added, "I am not at this time of any firm opinion one way or the other" on whether Thomas should be confirmed.</s>

<s docid="SJMN91-06256107" num="20" wdcount="56"> And Simon said Thomas' performance thus far "has neither helped him nor hurt him."; Specter blamed fellow committee members more than Thomas in concluding, "We really haven't moved very far in the process."; Thomas, a black federal appeals judge, was picked by President Bush to replace the retiring Thurgood Marshall, the high court's only black justice.</s>

<s docid="SJMN91-06256107" num="21" wdcount="19"> DeConcini said he thought the conservative Thomas "handled the privacy questions very well" without taking a stand on abortion.</s>

<s docid="SJMN91-06256107" num="22" wdcount="42"> "I don't see how you could ask him to do anything more."; Thomas expanded earlier testimony by saying Wednesday that he believed the right of marital privacy was "fundamental" -- a status that accords it the fullest judicial protection from government intrusion.</s>

<s docid="SJMN91-06256107" num="23" wdcount="19"> But he repeatedly refused to state his views on the 1973 abortion decision based on women's right of privacy.</s>

<s docid="SJMN91-06256107" num="24" wdcount="56"> To give such an answer, he said, "would undermine my ability to sit in an impartial way on such an important case."; Thomas, who sat alone at the witness table with no notes or reference materials, also claimed a lack of familiarity with the subject matter when asked about some of his former speeches and articles.</s>

<s docid="SJMN91-06256107" num="25" wdcount="7"> That moved committee Chairman Joseph Biden, D-Del.</s>

<s docid="SJMN91-06256107" num="26" wdcount="22"> , to give Thomas a stack of the judge's past speeches so the nominee could "help me understand them" during future questioning.</s>

<s docid="SJMN91-06256107" num="27" wdcount="21"> Thomas, testifying calmly but warily, did offer fuller comment on another hot issue before the high court: prayer in public schools.</s>

<s docid="SJMN91-06256107" num="28" wdcount="63"> After Simon discussed the feelings decades ago of a Jewish elementary schoolboy who left the room each day while his classmates recited a prayer, Thomas said, "Any policy of exclusion should be considered inappropriate."; Outside the hearing room, abortion-rights advocates said Thomas should not be allowed to disavow past comments they say show he would vote to ban most, if not all, abortions.</s>

<s docid="SJMN91-06256107" num="29" wdcount="41"> "His most unimpressive testimony poses two equally disturbing possibilities: he is either willfully misleading the committee about his views to win confirmation, or he is a man whose convictions have shallow roots," said Arthur Kropp of People for the American Way.</s>

<s docid="SJMN91-06256107" num="30" wdcount="4"> Sen. Patrick Leahy, D-Vt.</s>

<s docid="SJMN91-06256107" num="31" wdcount="24"> , said he could not understand how Thomas' prior statements touching on the 1973 abortion decision could have been made without considering its content.</s>

<s docid="SJMN91-06256107" num="32" wdcount="8"> "I'm not satisfied with the answers," Leahy said.</s>

<s docid="SJMN91-06256107" num="33" wdcount="56"> Although Thomas appeared to back away from comments made in past speeches or articles, he told the committee, "My view is that I have been consistent."; Thomas' opponents believe Republicans Strom Thurmond of South Carolina, Orrin Hatch of Utah, Charles Grassley of Iowa, Alan Simpson of Wyoming and Hank Brown of Colorado are solid Thomas backers.</s>

<s docid="SJMN91-06256107" num="34" wdcount="4"> But they hope Sens.</s>

<s docid="SJMN91-06256107" num="35" wdcount="4"> Edward M. Kennedy, D-Mass.</s>

<s docid="SJMN91-06256107" num="36" wdcount="24"> , and Howard Metzenbaum, D-Ohio, will be joined by the three swing-vote senators and Biden, Leahy, Simon and Kohl in voting against the nominee.</s>

<s docid="SJMN91-06256107" num="37" wdcount="9"> Biden and Kennedy declined comment Wednesday on their leanings.</s>

<s docid="SJMN91-06256107" num="38" wdcount="130"> Metzenbaum said Thomas' refusal to give direct answers "makes it more difficult to vote for him."; THOMAS' VIEWS; Excerpts from Clarence Thomas' testimony:; On abortion: "I have no reason or agenda to prejudge the issue . . . or a predilection to rule one way or another on the issue of abortion."; On affirmative action: "The line that I drew was a line that said that we shouldn't have preferences, or goals, or timetables or quotas."; On natural law: "At no time did I feel, nor do I feel now, that natural law is anything more than the background to our Constitution."; HEAR IT, SEE IT; Senate confirmation hearings for Supreme Court nominee Clarence Thomas are scheduled to run through Friday this week and every weekday except Wednesday next week.</s>

<s docid="SJMN91-06256107" num="39" wdcount="15"> RADIO; (box) KQED, 88.5 FM Tape delay beginning at 9 a.m. repeated at 9:30 p.m.</s>

<s docid="SJMN91-06256107" num="40" wdcount="10"> (box) KPFA, 94.1 FM Live coverage begins at 6:30 a.m.</s>

<s docid="SJMN91-06256107" num="41" wdcount="13"> TELEVISION; (box) C-SPAN Live coverage begins at 7 a.m. repeated at 5 p.m.</s>

<s docid="SJMN91-06256107" num="42" wdcount="5"> (box) CNN Intermittent coverage .</s>
</TEXT>
<BYLINE>

<s docid="SJMN91-06256107" num="43" wdcount="2"> Associated Press</s>
</BYLINE>
<COUNTRY>

<s docid="SJMN91-06256107" num="44" wdcount="1"> USA</s>
</COUNTRY>
<CITY>

<s docid="SJMN91-06256107" num="45" wdcount="1"> Washington</s>
</CITY>
<EDITION>

<s docid="SJMN91-06256107" num="46" wdcount="1"> Street</s>
</EDITION>
<CODE>

<s docid="SJMN91-06256107" num="47" wdcount="1"> SJ</s>
</CODE>
<NAME>

<s docid="SJMN91-06256107" num="48" wdcount="4"> San Jose Mercury News</s>
</NAME>
<PUBDATE>

<s docid="SJMN91-06256107" num="49" wdcount="1"> 910912</s>
</PUBDATE>
<DAY>

<s docid="SJMN91-06256107" num="50" wdcount="1"> Thursday</s>
</DAY>
<MONTH>

<s docid="SJMN91-06256107" num="51" wdcount="1"> September</s>
</MONTH>
<PG.COL>

<s docid="SJMN91-06256107" num="52" wdcount="1"> 1A</s>
</PG.COL>
<PUBYEAR>

<s docid="SJMN91-06256107" num="53" wdcount="1"> 1991</s>
</PUBYEAR>
<REGION>

<s docid="SJMN91-06256107" num="54" wdcount="1"> WEST</s>
</REGION>
<FEATURE>

<s docid="SJMN91-06256107" num="55" wdcount="1"> PHOTO</s>
</FEATURE>
<STATE>

<s docid="SJMN91-06256107" num="56" wdcount="1"> CA</s>
</STATE>
<WORD.CT>

<s docid="SJMN91-06256107" num="57" wdcount="1"> 864</s>
</WORD.CT>
<DATELINE>

<s docid="SJMN91-06256107" num="58" wdcount="5"> Thursday, September 12, 1991 00256107,SJ1</s>
</DATELINE>
<COPYRGHT>

<s docid="SJMN91-06256107" num="59" wdcount="6"> Copyright 1991, San Jose Mercury News</s>
</COPYRGHT>
<LIMLEN>

<s docid="SJMN91-06256107" num="60" wdcount="1"> 1</s>
</LIMLEN>
<LANGUAGE>

<s docid="SJMN91-06256107" num="61" wdcount="2"> ENG FRONT</s>
</LANGUAGE>
</DOC>
