<DOC>
<DOCNO>

<s docid="AP880324-0193" num="1" wdcount="1"> AP880324-0193</s>
</DOCNO>
<FILEID>

<s docid="AP880324-0193" num="2" wdcount="2"> AP-NR-03-24-88 1514EST</s>
</FILEID>
<FIRST>

<s docid="AP880324-0193" num="3" wdcount="6"> u i AM-CommunistMcDonalds Bjt 03-24 0613</s>
</FIRST>
<SECOND>

<s docid="AP880324-0193" num="4" wdcount="3"> AM-Communist McDonalds, Bjt,0630</s>
</SECOND>
<HEAD>

<s docid="AP880324-0193" num="5" wdcount="7"> Police Keep Crowds From Crashing First McDonald's</s>
</HEAD>
<BYLINE>

<s docid="AP880324-0193" num="6" wdcount="3"> By DUSAN STOJANOVIC</s>
</BYLINE>
<BYLINE>

<s docid="AP880324-0193" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP880324-0193" num="8" wdcount="3"> BELGRADE, Yugoslavia (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880324-0193" num="9" wdcount="36"> Communism suffered its first Big Mac attack Thursday as McDonald's opened a restaurant in Yugoslavia, and police were called in to keep customers who lined up for hours from getting too unruly under the golden arches.</s>

<s docid="AP880324-0193" num="10" wdcount="26"> ``I just wanted to taste genuine American hamburgers,'' said Milica Nikolic, a high school student who waited for three hours to taste her first Big Mac.</s>

<s docid="AP880324-0193" num="11" wdcount="27"> People curiously examined the renovated restaurant's plush interior and the back-lit signs depicting the hamburgers, french fries, milk shakes and other fare more familiar in the West.</s>

<s docid="AP880324-0193" num="12" wdcount="15"> It also featured amber-colored tables and floors, pastel-colored upholstery, modern art paintings and discreet illumination.</s>

<s docid="AP880324-0193" num="13" wdcount="23"> The fast-food outlet, located on a downtown square, had drawn crowds in recent days, and they began gathering long before it opened Thursday.</s>

<s docid="AP880324-0193" num="14" wdcount="23"> Police kept watch on the lines of customers snaking around the block, and they regulated the number who came inside to avoid overcrowding.</s>

<s docid="AP880324-0193" num="15" wdcount="19"> ``No opening of a restaurant in Belgrade has created such a sensation as this one today,'' one policeman said.</s>

<s docid="AP880324-0193" num="16" wdcount="21"> ``I think this restaurant has no competition in Belgrade,'' said Milica Danic, a housewife who treated her son to a cheeseburger.</s>

<s docid="AP880324-0193" num="17" wdcount="18"> ``It is much cleaner, the service is faster, the interior is nicer and it is not too expensive''.</s>

<s docid="AP880324-0193" num="18" wdcount="35"> The Belgrade media have suggested that the success of McDonald's in Yugoslavia depends on its acceptance by citizens long accustomed to a hamburger-like fast-food dish called the Pljeskavica: ground pork and onions on a bun.</s>

<s docid="AP880324-0193" num="19" wdcount="32"> ``In fact, this is a clash between the Big Mac and Pljeskavica,'' said Vesna Milosevic, an official of Genex, a Yugoslav state-run enterprise that has contracted a joint venture agreement with McDonald's.</s>

<s docid="AP880324-0193" num="20" wdcount="20"> ``Our aim is not to destroy the Pljeskavica on the Yugoslav market,'' said Predrag Dostanic, managing director of the Genex-McDonald's.</s>

<s docid="AP880324-0193" num="21" wdcount="15"> ``We want to change customs of the local people used to completly different eating habits''.</s>

<s docid="AP880324-0193" num="22" wdcount="18"> He said that lounging at tables for a long time after a finished meal will draw a warning.</s>

<s docid="AP880324-0193" num="23" wdcount="10"> Also, smoking is forbidden and alcohol will not be served.</s>

<s docid="AP880324-0193" num="24" wdcount="24"> This contrasts sharply with the Balkan and Yugoslav custom of sitting with a drink in smoke-filled restaurants and chatting with friends after the meal.</s>

<s docid="AP880324-0193" num="25" wdcount="33"> The Big Mac meal, consisting of a hamburger, soft drink and french fries costs the equivalent of $2.57, or about as much the similar meal would cost in numerous Pljeskavica joints around town.</s>

<s docid="AP880324-0193" num="26" wdcount="31"> Sadik Seljami, a waiter in a small Pljeskavica outlet just a few hundred yards from the McDonald's, suggested that the American restaurant wants to drive Yugoslav fast-food outlets out of business.</s>

<s docid="AP880324-0193" num="27" wdcount="18"> ``However, we will not give up the fight even if we have to lower the prices,'' said Seljami.</s>

<s docid="AP880324-0193" num="28" wdcount="46"> Glen Cook, an executive of the McDonald's Corp., said during the opening ceremonies, ``We are very excited about the opening of this restaurant, not only because it is the first one in a communist country, but also because it is one of the nicest in Europe''.</s>

<s docid="AP880324-0193" num="29" wdcount="11"> McDonald's and Genex contribute $1 million each for the flagship restaurant.</s>

<s docid="AP880324-0193" num="30" wdcount="16"> They will also share the profits equally even though it will be managed entirely by Yugoslavs.</s>

<s docid="AP880324-0193" num="31" wdcount="16"> The restaurant has 350 seats and employs 110 people capable of serving 2,500 meals per hour.</s>

<s docid="AP880324-0193" num="32" wdcount="22"> In an effort to keep a high level of services, the management is entitled to fire any employees who fail to perform.</s>

<s docid="AP880324-0193" num="33" wdcount="15"> The American corporation plans to open five additional restaurants Yugoslavia in the next five years.</s>

<s docid="AP880324-0193" num="34" wdcount="22"> The next East European McDonald's, and the first in a Soviet bloc country, is to open next month in Budapest, Hungary .</s>
</TEXT>
</DOC>
