<DOC>
<DOCNO>

<s docid="AP880314-0110" num="1" wdcount="1"> AP880314-0110</s>
</DOCNO>
<FILEID>

<s docid="AP880314-0110" num="2" wdcount="2"> AP-NR-03-14-88 1223EST</s>
</FILEID>
<FIRST>

<s docid="AP880314-0110" num="3" wdcount="5"> r i AM-Yugoslavia-McDonalds 03-14 0243</s>
</FIRST>
<SECOND>

<s docid="AP880314-0110" num="4" wdcount="1"> AM-Yugoslavia-McDonalds,0250</s>
</SECOND>
<HEAD>

<s docid="AP880314-0110" num="5" wdcount="7"> First McDonald's to Open in Communist Country</s>
</HEAD>
<HEAD>

<s docid="AP880314-0110" num="6" wdcount="3"> With AM-Gorbachev, Bjt</s>
</HEAD>
<DATELINE>

<s docid="AP880314-0110" num="7" wdcount="3"> BELGRADE, Yugoslavia (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP880314-0110" num="8" wdcount="29"> The communist world gets its first McDonald's next week, and some people here are wondering whether its American hamburgers will be as popular as the local fast-food treat, Pljeskavica.</s>

<s docid="AP880314-0110" num="9" wdcount="42"> The long-awaited opening of the restaurant on one of Belgrade's main downtown squares will take place March 24, the Yugoslav news agency Tanjug reported, and it will offer Big Macs, fries and the other specialities familiar to McDonald's customers in the West.</s>

<s docid="AP880314-0110" num="10" wdcount="26"> The Belgrade media have suggested that the success of the American restaurant depends on its acceptance by Yugoslavians who are long accustomed to the hamburger-like Pljeskavica.</s>

<s docid="AP880314-0110" num="11" wdcount="19"> Pljeskavica is made of ground pork and onions, and it is served on bread and eaten with the hands.</s>

<s docid="AP880314-0110" num="12" wdcount="14"> It is sold at fast-food restaurants across the country and costs about a dollar.</s>

<s docid="AP880314-0110" num="13" wdcount="26"> ``In fact, this is a clash between the Big Mac and Pljeskavica,'' said an official of Genex, Yugoslavia's largest state-run enterprise that will operate the McDonald's.</s>

<s docid="AP880314-0110" num="14" wdcount="23"> John Onoda, a spokesman at McDonald's Oak Brook, Ill., headquarters, said it was the first of the chain's outlets in a communist country.</s>

<s docid="AP880314-0110" num="15" wdcount="25"> The next East European McDonald's is scheduled to be opened in Budapest, Hungary, by the end of this year, said Vesna Milosevic, another Genex official.</s>

<s docid="AP880314-0110" num="16" wdcount="23"> Negotiations have been going on for years for expanding the fast-food chain to the Soviet Union, but no agreement has been announced .</s>
</TEXT>
</DOC>
