<DOC>
<DOCNO>

<s docid="AP901008-0136" num="1" wdcount="1"> AP901008-0136</s>
</DOCNO>
<FILEID>

<s docid="AP901008-0136" num="2" wdcount="2"> AP-NY-10-08-90 2027EDT</s>
</FILEID>
<FIRST>

<s docid="AP901008-0136" num="3" wdcount="5"> r i AM-China-McDonald's 10-08 0499</s>
</FIRST>
<SECOND>

<s docid="AP901008-0136" num="4" wdcount="1"> AM-China-McDonald's,0614</s>
</SECOND>
<HEAD>

<s docid="AP901008-0136" num="5" wdcount="6"> McDonald's Opens First Restaurant in China</s>
</HEAD>
<HEAD>

<s docid="AP901008-0136" num="6" wdcount="1"> LaserPhoto</s>
</HEAD>
<BYLINE>

<s docid="AP901008-0136" num="7" wdcount="3"> By WONG SAU-YING</s>
</BYLINE>
<BYLINE>

<s docid="AP901008-0136" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP901008-0136" num="9" wdcount="3"> SHENZHEN, China (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP901008-0136" num="10" wdcount="27"> McDonald's hamburgers, fries and golden arches came to China on Monday when the fast-food chain opened its first restaurant in a nation famed for its distinctive cuisine.</s>

<s docid="AP901008-0136" num="11" wdcount="29"> Hundreds of Chinese waited for hours outside the restaurant in Shenzhen, an economic boom town near Hong Kong, for their first taste of a McDonald's hamburger, fries or shake.</s>

<s docid="AP901008-0136" num="12" wdcount="25"> ``I travelled for four hours from a village to get here,'' said Huang Rongti, 70, who has lost most of her teeth because of age.</s>

<s docid="AP901008-0136" num="13" wdcount="9"> ``You think hamburgers are too challenging for my age''?</s>

<s docid="AP901008-0136" num="14" wdcount="15"> Later, after purchasing her first Big Mac, she inspected it carefully before taking a bite.</s>

<s docid="AP901008-0136" num="15" wdcount="13"> ``It tastes good, I like it,'' she announced before slowly eating the rest.</s>

<s docid="AP901008-0136" num="16" wdcount="23"> The opening of a U.S. fast-food restaurant in China, where cooking has long been considered a culinary art, may seem odd to gourmets.</s>

<s docid="AP901008-0136" num="17" wdcount="11"> It is estimated there are more than 5,000 different Chinese dishes.</s>

<s docid="AP901008-0136" num="18" wdcount="59"> In Canton, 125 miles northwest of Shenzhen, chefs specialize in some of the more exotic Chinese dishes, such as cat stew, bear paws, chicken feet and a famed snake dish - ``Dragon and Tiger Locked in Battle'' - made from three kinds of poisonous snakes stewed with leopard meat, and garnished with 20 spices, lemon leaves and chrysanthemum petals.</s>

<s docid="AP901008-0136" num="19" wdcount="19"> However, many Chinese, who earn an average $32 a month, are still unable to afford fancy meals at restaurants.</s>

<s docid="AP901008-0136" num="20" wdcount="25"> In Shenzhen, a Chinese special economic zone where foreign investors have built factories, salaries are higher and workers earn an average of $53 a month.</s>

<s docid="AP901008-0136" num="21" wdcount="19"> At the restaurant, a Big Mac costs $1.14, a bag of fries 48 cents and a shake 74 cents.</s>

<s docid="AP901008-0136" num="22" wdcount="22"> Another U.S. fast food outlet, Kentucky Fried Chicken, opened a restaurant in Beijing in 1987, and it now has four outlets there.</s>

<s docid="AP901008-0136" num="23" wdcount="9"> McDonald's hopes to open a restaurant in Beijing later.</s>

<s docid="AP901008-0136" num="24" wdcount="29"> Although Kentucky Fried Chicken has become popular, the average Chinese still regards a meal there as a treat, rather than a convenience, and McDonald's could face the same problems.</s>

<s docid="AP901008-0136" num="25" wdcount="23"> The 500-seat McDonald's restaurant in a three-story building is operated by McDonald's Restaurant Shenzhen Ltd., a wholly owned subsidiary of McDonald's Hong Kong.</s>

<s docid="AP901008-0136" num="26" wdcount="14"> McDonald's Hong Kong is a 50-50 joint venture with McDonald's in the United States.</s>

<s docid="AP901008-0136" num="27" wdcount="19"> It is managed by a Chinese national, Chen Tikang, and his son, Chen Yin, who is the restaurant manager.</s>

<s docid="AP901008-0136" num="28" wdcount="16"> The younger Chen returned recently from a course at McDonald's hamburger university in Oak Brook, Ill.</s>

<s docid="AP901008-0136" num="29" wdcount="14"> Most of the ingredients used at the restaurant are now imported from Hong Kong.</s>

<s docid="AP901008-0136" num="30" wdcount="15"> But McDonald's executives hope eventually to get their supplies of beef and potatoes from China.</s>

<s docid="AP901008-0136" num="31" wdcount="31"> Daniel Ng, chairman of McDonald's Restaurant Shenzhen Ltd., said it took two years to prepare for the restaurant's opening and his ambition now is to serve 10 million burgers a year.</s>

<s docid="AP901008-0136" num="32" wdcount="24"> Last month, when McDonald's advertized for 240 staffers for the restaurant, it received applications from more than 9,000 persons, including college graduates, officials said.</s>

<s docid="AP901008-0136" num="33" wdcount="27"> ``I feel I have a better job prospect working here, and it pays better,'' said Henry He, 25, who has a master's degree in garment and textile.</s>

<s docid="AP901008-0136" num="34" wdcount="8"> He is an assistant manager at the restaurant.</s>

<s docid="AP901008-0136" num="35" wdcount="11"> A waiter at the restaurant can earn 53 cents an hour.</s>

<s docid="AP901008-0136" num="36" wdcount="40"> A factory worker, who waited several hours before she was able to purchase her hamburger, said she liked it because of its ``sweet taste'' - the result of tomato ketchup, which is not commonly used in traditional Chinese cooking .</s>
</TEXT>
</DOC>
