<DOC>
<DOCNO>

<s docid="AP900131-0200" num="1" wdcount="1"> AP900131-0200</s>
</DOCNO>
<FILEID>

<s docid="AP900131-0200" num="2" wdcount="2"> AP-NR-01-31-90 2051EST</s>
</FILEID>
<FIRST>

<s docid="AP900131-0200" num="3" wdcount="7"> u i AM-Soviet-McDonald's 2ndLd-Writethru a0764 01-31 0748</s>
</FIRST>
<SECOND>

<s docid="AP900131-0200" num="4" wdcount="4"> AM-Soviet-McDonald's, 2nd Ld-Writethru, a0764,0767</s>
</SECOND>
<HEAD>

<s docid="AP900131-0200" num="5" wdcount="10"> A Bolshoi Mac Attack in Moscow as First McDonald's Opens</s>
</HEAD>
<NOTE>

<s docid="AP900131-0200" num="6" wdcount="12"> Eds: INSERTS graf after 6th `Big Macs' to ADD official exchange rates.</s>

<s docid="AP900131-0200" num="7" wdcount="4"> Pickup 7th `Half the...'</s>
</NOTE>
<HEAD>

<s docid="AP900131-0200" num="8" wdcount="2"> LaserPhotos MOSB4,6</s>
</HEAD>
<BYLINE>

<s docid="AP900131-0200" num="9" wdcount="3"> By ANN IMSE</s>
</BYLINE>
<BYLINE>

<s docid="AP900131-0200" num="10" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900131-0200" num="11" wdcount="2"> MOSCOW (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900131-0200" num="12" wdcount="31"> Thousands of queue-hardened Soviets on Wednesday cheerfully lined up to get a taste of ``gamburgers,'' ``chizburgers'' and ``Filay-o-feesh'' sandwiches as McDonald's opened in the land of Lenin for the first time.</s>

<s docid="AP900131-0200" num="13" wdcount="27"> The world's largest version of the landmark American fast-food chain rang up 30,000 meals on 27 cash registers, breaking the opening-day record for McDonald's worldwide, officials said.</s>

<s docid="AP900131-0200" num="14" wdcount="27"> The Soviets, bundled in fur coats and hats, seemed unfazed, lining up before dawn outside the 700-seat restaurant, the first of 20 planned across the Soviet Union.</s>

<s docid="AP900131-0200" num="15" wdcount="18"> The crush of customers was so intense the company stayed open until midnight, two hours later than planned.</s>

<s docid="AP900131-0200" num="16" wdcount="24"> ``I only waited an hour and I think they served thousands before me,'' said a happy middle-aged woman who works at an aluminum plant.</s>

<s docid="AP900131-0200" num="17" wdcount="11"> ``And it was only 10 rubles for all this,'' she said.</s>

<s docid="AP900131-0200" num="18" wdcount="12"> ``I'm taking it back for the girls at the factory to try''.</s>

<s docid="AP900131-0200" num="19" wdcount="39"> Big Macs were priced at 3.75 rubles and double cheeseburgers at 3 rubles _ about two hours' pay for a starting McDonald's staffer or the average Soviet, but much cheaper than other private restaurants that have sprung up recently.</s>

<s docid="AP900131-0200" num="20" wdcount="28"> The official exchange rate is $1.59 per ruble but foreign visitors can buy rubles for 16 cents each, about what the currency is worth on the black market.</s>

<s docid="AP900131-0200" num="21" wdcount="33"> Half the day's sales were donated to the Soviet Children's Fund, which provides medical care and assistance to orphans and disadvantaged children, Gary Reinblatt, senior vice president of McDonald's Canada, said from Toronto.</s>

<s docid="AP900131-0200" num="22" wdcount="30"> The restaurant, built by the company in a joint venture with the city of Moscow that began 14 years ago, brought to 52 the number of countries where McDonald's operates.</s>

<s docid="AP900131-0200" num="23" wdcount="12"> The previous opening-day record for sales was in Budapest, company officials said.</s>

<s docid="AP900131-0200" num="24" wdcount="20"> Besides its restaurants in the United States, the leading number of McDonald's are in Canada and Japan, the officials said.</s>

<s docid="AP900131-0200" num="25" wdcount="15"> Soviets got a first-hand look at such alien concepts as efficiency and fast, friendly service.</s>

<s docid="AP900131-0200" num="26" wdcount="26"> Normally dour citizens broke into grins as they caught the infectious cheerful mood from youthful Soviet staffers hired for their ability to smile and work hard.</s>

<s docid="AP900131-0200" num="27" wdcount="25"> Accordions played folk songs and women in traditional costumes danced with cartoon characters, including Mickey Mouse and Baba Yaga, a witch of Russian fairy tales.</s>

<s docid="AP900131-0200" num="28" wdcount="36"> One Muscovite, accustomed to clerks who snarl if they say anything at all, asked for a straw and was startled when a smiling young Soviet woman found him one and popped it straight into his drink.</s>

<s docid="AP900131-0200" num="29" wdcount="11"> For most customers, it was their first experience with a hamburger.</s>

<s docid="AP900131-0200" num="30" wdcount="22"> Sandwiches were served in the familiar bag marked with the golden arches, but were packed in wrappers bearing Cyrillic letters, approximating ``gamburger''.</s>

<s docid="AP900131-0200" num="31" wdcount="4"> They tried them one-handed.</s>

<s docid="AP900131-0200" num="32" wdcount="9"> They picked their sandwiches apart to examine the contents.</s>

<s docid="AP900131-0200" num="33" wdcount="14"> One young woman finally squashed her ``Beeg Mak'' to fit her lips around it.</s>

<s docid="AP900131-0200" num="34" wdcount="7"> ``It tasted great''! a 14-year-old boy said.</s>

<s docid="AP900131-0200" num="35" wdcount="29"> ``It's a lot different from a stolovaya,'' he continued with a smile, referring to the much cheaper but run-down dirty cafeterias that slop rice and fat or boiled sausage.</s>

<s docid="AP900131-0200" num="36" wdcount="49"> Under the sign of the golden arches, accented by the Soviet hammer-and-sickle flag, hundreds lined up for the long-awaited grand opening at 10 a.m. on Pushkin Square, reaching out excitedly for McDonald's flags and pins as the hamburger chain's army fulfilled the Soviet penchant for souvenirs with Western logos.</s>

<s docid="AP900131-0200" num="37" wdcount="18"> Publicity-conscious managers had the staff shout ``Good morning, America''! in English and Russian, for an American TV network.</s>

<s docid="AP900131-0200" num="38" wdcount="34"> McDonald's of Canada Chairman George Cohon, the man behind the deal, said many people were buying multiple orders and the restaurant served 15,000 to 20,000 people in just the first five hours of operation.</s>

<s docid="AP900131-0200" num="39" wdcount="15"> The restaurant limited purchases to 10 Big Macs per customer in hopes of preventing burger-scalping.</s>

<s docid="AP900131-0200" num="40" wdcount="38"> McDonald's built its own factory, including bakery, dairy, meat-processing plant and even potato storage yard, to provide its own guaranteed supplies in a country where up to 25 percent of the harvest rots en route to the consumer.</s>

<s docid="AP900131-0200" num="41" wdcount="32"> One McDonald's associate said the company wound up importing wooden crates from Finland for storing potatoes because ``when they went to build crates, they found there was no wood, and no nails.</s>

<s docid="AP900131-0200" num="42" wdcount="9"> They found you need a permit to buy nails.''</s>
</TEXT>
</DOC>
