<DOC>
<DOCNO>

<s docid="FT932-5869" num="1" wdcount="1"> FT932-5869</s>
</DOCNO>
<PROFILE>

<s docid="FT932-5869" num="2" wdcount="1"> _AN-DFBBWAAOFT</s>
</PROFILE>
<DATE>

<s docid="FT932-5869" num="3" wdcount="1"> 930602</s>
</DATE>
<HEADLINE>

<s docid="FT932-5869" num="4" wdcount="11"> FT 02 JUN 93 / Big Macs rake in the roubles</s>
</HEADLINE>
<BYLINE>

<s docid="FT932-5869" num="5" wdcount="3"> By LEYLA BOULTON</s>
</BYLINE>
<DATELINE>

<s docid="FT932-5869" num="6" wdcount="1"> MOSCOW</s>
</DATELINE>
<TEXT>

<s docid="FT932-5869" num="7" wdcount="33"> AS THE value of the rouble plunges and potential foreign investors worry about a host of obstacles to investing in Russia, Russian officials had several reasons yesterday to feel thankful for McDonald's hamburgers.</s>

<s docid="FT932-5869" num="8" wdcount="33"> Opening the second McDonald's restaurant in Moscow, along with a 12-storey office block, Mr George Cohon, head of McDonald's Canada, could well be described as the Russian authorities' idea of a model investor.</s>

<s docid="FT932-5869" num="9" wdcount="39"> McDonald's proven determination 'to be here for the long term' and to serve Russians in their own currency as opposed to the dollars charged by most other foreign joint ventures are just a couple of reasons for Russian gratitude.</s>

<s docid="FT932-5869" num="10" wdcount="29"> Mr Viktor Khlystun, the agriculture minister, praised the fact that McDonald's gets most of its supplies from inside Russia after setting up a Dollars 45m processing plant outside Moscow.</s>

<s docid="FT932-5869" num="11" wdcount="29"> He also thanked McDonald's for providing jobs, a model of western standards for the country's decrepit service industry, and finally for what he described as 'the most delicious food'.</s>

<s docid="FT932-5869" num="12" wdcount="42"> But despite the jolly opening ceremony - with Big Macs, musicians playing the balalaika, and hundreds of yellow balloons forming a giant M - life has been tough for McDonald's since it opened its first restaurant in Moscow 3 1/2 years ago.</s>

<s docid="FT932-5869" num="13" wdcount="46"> Although the first Moscow restaurant is the busiest McDonald's in the world the plunging rouble, high inflation and constantly changing tax rules have been a challenge to McDonald's management, who admitted that they have no idea of when it could recoup its initial Dollars 50m investment.</s>

<s docid="FT932-5869" num="14" wdcount="24"> 'It will depend on how rapidly we can open new restaurants, what happens to the rouble, what happens to raw materials that we buy.</s>

<s docid="FT932-5869" num="15" wdcount="11"> We don't have an estimate of how long it will take.</s>

<s docid="FT932-5869" num="16" wdcount="8"> There are too many variables,' said Mr Cohon.</s>

<s docid="FT932-5869" num="17" wdcount="36"> Apart from housing the restaurant on the ground floor, the McDonald's office block is rented out to western companies in an attempt to generate hard currency alongside the mountains of roubles made from selling hamburgers .</s>
</TEXT>
<XX>

<s docid="FT932-5869" num="18" wdcount="1"> Companies:-</s>
</XX>
<CO>

<s docid="FT932-5869" num="19" wdcount="3"> McDonald's Corp .</s>
</CO>
<XX>

<s docid="FT932-5869" num="20" wdcount="1"> Countries:-</s>
</XX>
<CN>

<s docid="FT932-5869" num="21" wdcount="4"> RUZ Russia, East Europe.</s>

<s docid="FT932-5869" num="22" wdcount="6"> USZ United States of America .</s>
</CN>
<XX>

<s docid="FT932-5869" num="23" wdcount="1"> Industries:-</s>
</XX>
<IN>

<s docid="FT932-5869" num="24" wdcount="4"> P5812 Eating Places .</s>
</IN>
<XX>

<s docid="FT932-5869" num="25" wdcount="1"> Types:-</s>
</XX>
<TP>

<s docid="FT932-5869" num="26" wdcount="3"> RES Facilities .</s>
</TP>
<PUB>

<s docid="FT932-5869" num="27" wdcount="3"> The Financial Times</s>
</PUB>
<PAGE>

<s docid="FT932-5869" num="28" wdcount="3"> London Page 2</s>
</PAGE>
</DOC>
