<DOC>
<DOCNO>

<s docid="LA020190-0038" num="1" wdcount="1"> LA020190-0038</s>
</DOCNO>
<DOCID>

<s docid="LA020190-0038" num="2" wdcount="1"> 169832</s>
</DOCID>
<DATE>
<P>

<s docid="LA020190-0038" num="3" wdcount="6"> February 1, 1990, Thursday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA020190-0038" num="4" wdcount="8"> Part A; Page 1; Column 5; Foreign Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA020190-0038" num="5" wdcount="2"> 1057 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA020190-0038" num="6" wdcount="7"> 1ST 'BEEG MAK' ATTACK LEAVES MOSCOW AGOG</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA020190-0038" num="7" wdcount="6"> By MASHA HAMILTON, TIMES STAFF WRITER</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA020190-0038" num="8" wdcount="1"> MOSCOW</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA020190-0038" num="9" wdcount="40"> When the doors swung open Wednesday at the first McDonald's restaurant in the Soviet Union, thousands of Muscovites poured in to sip "milk cocktails" and taste their first "Beeg Mak Gamburgers," picking them apart to marvel at the fixin's .</s>
</P>
<P>

<s docid="LA020190-0038" num="10" wdcount="27"> Some expressed wonder at the speedy service -- "only an hour in line" -- while others heralded the event as the first evidence that President Mikhail S.</s>

<s docid="LA020190-0038" num="11" wdcount="12"> Gorbachev's economic reforms are finally filtering down to the average Muscovite .</s>
</P>
<P>

<s docid="LA020190-0038" num="12" wdcount="45"> Although cynics might complain of the steady homogenizing of world cultures, the arrival of the fast-food chain here -- 14 years after a Canadian McDonald's official broached the idea with Soviet officials at the 1976 Montreal Olympics -- was without doubt a major event .</s>
</P>
<P>

<s docid="LA020190-0038" num="13" wdcount="23"> Most customers seemed thrilled to be part of it, even though some of them gave the Big Mac sandwich a mixed review .</s>
</P>
<P>

<s docid="LA020190-0038" num="14" wdcount="14"> "It tasted very, I would say, unusual," Lubov Sereda, 45, said with a smile.</s>

<s docid="LA020190-0038" num="15" wdcount="7"> "Everything was very soft and mild" .</s>
</P>
<P>

<s docid="LA020190-0038" num="16" wdcount="6"> "But those strawberry milk cocktails, well.</s>

<s docid="LA020190-0038" num="17" wdcount="11"> . .," her husband put in, flashing a thumbs-up sign .</s>
</P>
<P>

<s docid="LA020190-0038" num="18" wdcount="25"> "It was very interesting, that gamburger," Zvetlana Generotova, 25, said, leaving with a large paper bag filled with take-out food, also a new concept here.</s>

<s docid="LA020190-0038" num="19" wdcount="12"> "I certainly want my family to try it, at least once" .</s>
</P>
<P>

<s docid="LA020190-0038" num="20" wdcount="19"> Russians say "gamburger" because they pronounce Western words that begin with "h" as though they begin with "g" .</s>
</P>
<P>

<s docid="LA020190-0038" num="21" wdcount="11"> Another customer, Victor Kunyasev, said: "Well, my wife makes better food.</s>

<s docid="LA020190-0038" num="22" wdcount="18"> But it was nice, a good place to take a break and grab a bite to eat" .</s>
</P>
<P>

<s docid="LA020190-0038" num="23" wdcount="20"> Some reported waiting up to 1 hour and 45 minutes to be served, but most did not seem to mind.</s>

<s docid="LA020190-0038" num="24" wdcount="35"> In honor of the grand opening, a brigade of workers distributed McDonald's flags and pins; entertainers performed on the accordion and sang folk songs under golden arches adorned with the Soviet hammer and sickle .</s>
</P>
<P>

<s docid="LA020190-0038" num="25" wdcount="37"> The world's largest McDonald's, with 27 cash registers and a seating capacity of 900, brings to Moscow not only hamburgers, french fries and shakes (called "milk cocktails" here), but also a living lesson in Western-style marketing .</s>
</P>
<P>

<s docid="LA020190-0038" num="26" wdcount="42"> At training sessions before opening day, cashiers were taught the importance of greeting customers cheerfully, of saying "please" and "thank you" -- all of which promises something distinctly different from the typically surly service at most of Moscow's dingy state cafes .</s>
</P>
<P>

<s docid="LA020190-0038" num="27" wdcount="14"> "This is very different from anything I've ever done before," cashier Larissa Lebedeva said.</s>

<s docid="LA020190-0038" num="28" wdcount="37"> Lebedeva, 25, who formerly worked as deputy director of a small food store, said that "to be this polite and to have everything this clean is new for the workers as well as for the customers" .</s>
</P>
<P>

<s docid="LA020190-0038" num="29" wdcount="41"> Sam Yahel, from McDonald's in Atlanta, who helped train the 630 Soviet workers, said the Soviet trainees were at a disadvantage because in most other parts of the world, new workers had at least eaten at one of the restaurants .</s>
</P>
<P>

<s docid="LA020190-0038" num="30" wdcount="11"> Most of the Soviet workers had never tasted a Western-style hamburger.</s>

<s docid="LA020190-0038" num="31" wdcount="24"> They practiced cooking using yellow cardboard squares in place of cheese and different colored poker chips in place of onions, tomatoes and pickles .</s>
</P>
<P>

<s docid="LA020190-0038" num="32" wdcount="10"> "The Soviet Union is definitely a different world," Yahel said.</s>

<s docid="LA020190-0038" num="33" wdcount="9"> "Our food and our standards -- it's all new.</s>

<s docid="LA020190-0038" num="34" wdcount="25"> For example, we had to teach our employees that when there were still crumbs on the counter, it needed to be wiped off again" .</s>
</P>
<P>

<s docid="LA020190-0038" num="35" wdcount="26"> While most of the Soviet workers trained for a matter of days, the four Soviet managers of the restaurant spent nine months abroad learning their jobs.</s>

<s docid="LA020190-0038" num="36" wdcount="9"> They graduated from the Canadian Institute of Hamburgerology .</s>
</P>
<P>

<s docid="LA020190-0038" num="37" wdcount="30"> The Moscow McDonald's will be open for 12 hours a day beginning at 10 a.m. and will be able, they say, to serve more than 15,000 customers a day .</s>
</P>
<P>

<s docid="LA020190-0038" num="38" wdcount="17"> On Wednesday, though, it stayed open an extra two hours and served a McDonald's record 30,000 meals.</s>

<s docid="LA020190-0038" num="39" wdcount="26"> The previous record for opening-day transactions was 9,100 in Budapest, Hungary, and the previous record sales for a single day was 14,000 in Hong Kong .</s>
</P>
<P>

<s docid="LA020190-0038" num="40" wdcount="13"> There is a brass plaque near the entrance that announces, "Soviet Rubles Only".</s>

<s docid="LA020190-0038" num="41" wdcount="27"> Virtually every other foreign firm that has come into the Soviet Union in recent years accepts only hard currencies, meaning that it caters primarily to foreigners .</s>
</P>
<P>

<s docid="LA020190-0038" num="42" wdcount="20"> The McDonald's prices are high compared to the state restaurants, where a large meal seldom costs more than a ruble.</s>

<s docid="LA020190-0038" num="43" wdcount="32"> The Big Mac costs 3.75 rubles, or about $5 at the official exchange rate, and dinner out for the family can come to two days' wages for the average Soviet worker .</s>
</P>
<P>

<s docid="LA020190-0038" num="44" wdcount="23"> McDonald's employees are paid 1.50 rubles an hour, with a chance for an increase of up to 50 kopecks in three months' time.</s>

<s docid="LA020190-0038" num="45" wdcount="8"> The staff was chosen from 25,000 applicants .</s>
</P>
<P>

<s docid="LA020190-0038" num="46" wdcount="38"> Canadian and American officials who have helped train the Soviet personnel know that the allure of working for a Western firm was a drawing factor, but they nonetheless expect a 20% turnover rate, twice their normal average .</s>
</P>
<P>

<s docid="LA020190-0038" num="47" wdcount="28"> McDonald's invested $50 million in setting up the restaurant and a food processing plant in a Moscow suburb that turns out everything from meat patties to sesame-seed buns.</s>

<s docid="LA020190-0038" num="48" wdcount="22"> Soviet farmers, who are supplying most of the products, have been given special training and disease-resistant seed for potatoes and cucumbers .</s>
</P>
<P>

<s docid="LA020190-0038" num="49" wdcount="27"> The extra effort was necessary to guarantee supplies in a country where as much as 25% of the harvest spoils on the way to the consumer .</s>
</P>
<P>

<s docid="LA020190-0038" num="50" wdcount="11"> Despite all of the planning, some shortages still affect the operation.</s>

<s docid="LA020190-0038" num="51" wdcount="14"> Coffee is not on the menu, for example, because supplies cannot be guaranteed .</s>
</P>
<P>

<s docid="LA020190-0038" num="52" wdcount="37"> The joint venture agreement between McDonald's of Canada and the Moscow City Council calls for 20 restaurants, though there is no timetable or even a definite plan for when or where the second McDonald's will open .</s>
</P>
<P>

<s docid="LA020190-0038" num="53" wdcount="50"> Is there any fear that when the golden arches become as common as the cupolas of Russian Orthodox churches, it will be a sign that capitalism is making real inroads in the Communist capital? McDonald's officials say it is not a question that worries them or their Soviet counterparts .</s>
</P>
<P>

<s docid="LA020190-0038" num="54" wdcount="25"> "There weren't many ideological discussions during these negotiations," said Marc Winer, 43, a native of Nashua, N.H., who is general director of the Moscow outlet.</s>

<s docid="LA020190-0038" num="55" wdcount="18"> "The Soviets understood that the food was going to move very efficiently from the field to the mouth.</s>

<s docid="LA020190-0038" num="56" wdcount="13"> That is more important to them right now than almost anything else" .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA020190-0038" num="57" wdcount="20"> Photo, COLOR, Crowd gathers for opening of first McDonald's in Soviet Union, where some waited an hour for fast food.</s>

<s docid="LA020190-0038" num="58" wdcount="20"> Agence France-Presse; Photo, Soviet police officer, woman and two youngsters chow down at Moscow's giant new McDonald's, near City Hall.</s>

<s docid="LA020190-0038" num="59" wdcount="15"> With seats for 900 and 27 cash registers, it served 30,000 people on opening day.</s>

<s docid="LA020190-0038" num="60" wdcount="11"> Associated Press; Reuters; Map, Moscow McDonald's, AP / Los Angeles Times</s>
</P>
</GRAPHIC>
<SUBJECT>
<P>

<s docid="LA020190-0038" num="61" wdcount="28"> FAST FOOD INDUSTRY -- USSR; MCDONALD'S RESTAURANTS OF CANADA LTD; CANADA -- FOREIGN INVESTMENTS -- USSR; JOINT VENTURES; OCCUPATIONAL TRAINING; USSR -- LABOR; CUSTOMER SERVICE; USSR -- CULTURE</s>
</P>
</SUBJECT>
</DOC>
