<DOC>
<DOCNO>

<s docid="WSJ880412-0015" num="1" wdcount="1"> WSJ880412-0015</s>
</DOCNO>
<HL>

<s docid="WSJ880412-0015" num="2" wdcount="9"> McDonald's Outlet In Korea to Target New Middle Class</s>
</HL>
<AUTHOR>

<s docid="WSJ880412-0015" num="3" wdcount="5"> Joseph P. Manguno (WSJ Staff)</s>
</AUTHOR>
<SO>
</SO>
<CO>

<s docid="WSJ880412-0015" num="4" wdcount="2"> FREST MCD</s>
</CO>
<IN>

<s docid="WSJ880412-0015" num="5" wdcount="1"> RFD</s>
</IN>
<DATELINE>

<s docid="WSJ880412-0015" num="6" wdcount="1"> SEOUL</s>
</DATELINE>
<TEXT>

<s docid="WSJ880412-0015" num="7" wdcount="19"> Two corporate executives sat down in an office here last month to talk business with a bunch of clowns.</s>

<s docid="WSJ880412-0015" num="8" wdcount="17"> The subject was no laughing matter, but rather the serious endeavor of finding South Korea's Ronald McDonald.</s>

<s docid="WSJ880412-0015" num="9" wdcount="24"> Seven years after the U.S. hamburger giant first tried to bring its Big Macs to South Korea, the golden arches were finally going up.</s>

<s docid="WSJ880412-0015" num="10" wdcount="20"> McAhn Industries Ltd. recently opened the first of what it expects will be a string of burger outlets in Seoul.</s>

<s docid="WSJ880412-0015" num="11" wdcount="19"> The company is a 50-50 joint venture of McDonald's Corp., Oak Brook, Ill., and an accountant-turned-entrepreneur, Ahn Hyo Young.</s>

<s docid="WSJ880412-0015" num="12" wdcount="10"> McDonald's is flourishing in 11 other nations in the region.</s>

<s docid="WSJ880412-0015" num="13" wdcount="30"> But its entry into South Korea, which has Asia's fastest-growing economy, had been frustrated by its inability to find a suitable partner and to win agreement from Seoul on terms.</s>

<s docid="WSJ880412-0015" num="14" wdcount="14"> South Korea may be one of McDonald's most promising foreign markets, business analysts say.</s>

<s docid="WSJ880412-0015" num="15" wdcount="17"> The country is developing an essential ingredient for the success of a fast-food enterprise: a middle class.</s>

<s docid="WSJ880412-0015" num="16" wdcount="22"> Hamburger-related fast-food sales in South Korea totaled $87.5 million last year, a 30% rise from 1986, according to the Ministry of Finance.</s>

<s docid="WSJ880412-0015" num="17" wdcount="25"> Analysts say this year's rise could be much bigger, helped by a 25% increase in wages in mid-1987 and another big pay increase expected soon.</s>

<s docid="WSJ880412-0015" num="18" wdcount="23"> The business is likely to profit from the 1988 Olympic Games in Seoul in September, and from an anticipated post-Olympic economic boom here.</s>

<s docid="WSJ880412-0015" num="19" wdcount="40"> However, the competition is heating up, and there is "a good possibility that South Korea already has reached the fast-food saturation point for its current average income bracket," an official for the South Korea Chamber of Commerce and Industry says.</s>

<s docid="WSJ880412-0015" num="20" wdcount="21"> The competition, besides Wendy's International's 11 shops and six of Burger King, a unit of Pillsbury Co., includes home-grown burger chains.</s>

<s docid="WSJ880412-0015" num="21" wdcount="10"> McDonald's strategy is to take things slowly, avoiding extravagances, Mr.</s>

<s docid="WSJ880412-0015" num="22" wdcount="8"> Ahn and Awad Sifri, McDonald's marketing director, say.</s>

<s docid="WSJ880412-0015" num="23" wdcount="6"> "We are starting small," says Mr.</s>

<s docid="WSJ880412-0015" num="24" wdcount="13"> Ahn. "We're hoping to open three outlets this year and five next year.</s>

<s docid="WSJ880412-0015" num="25" wdcount="9"> After that, we'd like to open five every year".</s>

<s docid="WSJ880412-0015" num="26" wdcount="24"> Equally modest, he says, will be the initial menu: no breakfast, no Chicken McNuggets and no products tailored to national tastes, as offered elsewhere.</s>

<s docid="WSJ880412-0015" num="27" wdcount="27"> The venture is rejecting television commercials in favor of a cheaper, more oldfashioned approach: a brief advertising campaign in newspapers, distribution of fliers and word of mouth.</s>

<s docid="WSJ880412-0015" num="28" wdcount="31"> Mr. Sifri says the emphasis will be on developing McDonald's image as an affordable place for the emerging middle class, rather than as a familiar name for foreigners in South Korea.</s>

<s docid="WSJ880412-0015" num="29" wdcount="9"> Attention will be given to attracting children, he adds.</s>

<s docid="WSJ880412-0015" num="30" wdcount="16"> Mr. Ahn says McDonald's talked to 16 potential partners before choosing the Harvard-trained accountant in 1984.</s>

<s docid="WSJ880412-0015" num="31" wdcount="6"> Two years later, McDonald's and Mr.</s>

<s docid="WSJ880412-0015" num="32" wdcount="17"> Ahn each put up $1 million in capital and borrowed an additional $4 million to form McAhn.</s>

<s docid="WSJ880412-0015" num="33" wdcount="27"> McDonald's struggled with the government over McAhn's royalty payments to the U.S. partner -- the issue was resolved -- and over tight import restrictions on food products.</s>

<s docid="WSJ880412-0015" num="34" wdcount="22"> The import question "came down to finding a supplier locally who could supply high-quality beef and potatoes at a value," McDonald's said.</s>

<s docid="WSJ880412-0015" num="35" wdcount="19"> Even McDonald's golden arches symbol ran into red tape, since the city regulates the size and color of signs.</s>

<s docid="WSJ880412-0015" num="36" wdcount="13"> "It may be against the law, but we're putting them up anyway," Mr.</s>

<s docid="WSJ880412-0015" num="37" wdcount="3"> Ahn says .</s>
</TEXT>
</DOC>
