<DOC>
<DOCNO>

<s docid="AP900616-0123" num="1" wdcount="1"> AP900616-0123</s>
</DOCNO>
<FILEID>

<s docid="AP900616-0123" num="2" wdcount="2"> AP-NR-06-16-90 2056EDT</s>
</FILEID>
<FIRST>

<s docid="AP900616-0123" num="3" wdcount="5"> u a AM-FlashFloods-Missing 06-16 0492</s>
</FIRST>
<SECOND>

<s docid="AP900616-0123" num="4" wdcount="2"> AM-Flash Floods-Missing,0506</s>
</SECOND>
<HEAD>

<s docid="AP900616-0123" num="5" wdcount="9"> Mother Clings to Hope that 12-Year-Old Daughter is Alive</s>
</HEAD>
<HEAD>

<s docid="AP900616-0123" num="6" wdcount="4"> With AM-Flash Floods, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP900616-0123" num="7" wdcount="3"> By MARGARET CALDWELL</s>
</BYLINE>
<BYLINE>

<s docid="AP900616-0123" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900616-0123" num="9" wdcount="3"> SHADYSIDE, Ohio (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900616-0123" num="10" wdcount="32"> The mother of a 12-year-old girl swept away by a flash flood was clinging to hope that her daughter was alive but perhaps unable to get home, a family friend said Saturday.</s>

<s docid="AP900616-0123" num="11" wdcount="21"> Janice Trigg's daughter, Kerri, was among nearly three dozen still missing Saturday night, two days after the floods hit eastern Ohio.</s>

<s docid="AP900616-0123" num="12" wdcount="15"> ``She keeps saying Kerri Jo may have amnesia, or she can't move to get help.</s>

<s docid="AP900616-0123" num="13" wdcount="10"> That's a mother's hope,'' said the friend, Betty Kreiter, 67.</s>

<s docid="AP900616-0123" num="14" wdcount="39"> Searchers for the missing used trained dogs to sniff through the rubble and along the banks of the Wegee and Pipe creeks, which empty into the Ohio River, in an effort that stretched five miles south of this town.</s>

<s docid="AP900616-0123" num="15" wdcount="21"> Workers also sifted through debris that collected at the Hannibal locks and dam on the Ohio River, about 25 miles south.</s>

<s docid="AP900616-0123" num="16" wdcount="28"> Relatives of the missing were staying with friends and family, said the Rev. Robert Gracey, who was counseling flood victims at a school turned into a relief center.</s>

<s docid="AP900616-0123" num="17" wdcount="21"> Kerri had been playing at a friend's house when the one-story home suddenly was washed away in the flood Thursday night.</s>

<s docid="AP900616-0123" num="18" wdcount="35"> The friend, 9-year-old Amber Colvin, was swept down Wegee Creek and into the Ohio River, but survived a seven-mile ordeal by clinging to logs.Amber was released from a hospital Saturday after treatment for minor injuries.</s>

<s docid="AP900616-0123" num="19" wdcount="22"> She said she last saw Kerri when the two, alone in the house, jumped into a bathtub for safety in the storm.</s>

<s docid="AP900616-0123" num="20" wdcount="7"> The tub was washed into the creek.</s>

<s docid="AP900616-0123" num="21" wdcount="12"> Throughout the town, there were stories of fear, luck and close calls.</s>

<s docid="AP900616-0123" num="22" wdcount="27"> Deanna Hulderman, 48, said she and her husband, Clancey, were pulled under by Wegee Creek flood water at a bar but were reunited about a half-hour later.</s>

<s docid="AP900616-0123" num="23" wdcount="23"> Mrs. Hulderman said she, her husband and about seven others were in the 3Ks bar when a wall collapsed and water rushed through.</s>

<s docid="AP900616-0123" num="24" wdcount="10"> ``I saw my husband go under and get washed away.</s>

<s docid="AP900616-0123" num="25" wdcount="16"> He was yelling how much he loved me, and then I went under,'' Mrs. Hulderman said.</s>

<s docid="AP900616-0123" num="26" wdcount="27"> ``I began praying `God, don't let me die like this,' and the next thing I knew I was standing on my feet, and the water went down''.</s>

<s docid="AP900616-0123" num="27" wdcount="17"> Mrs. Hulderman said firefighters rescued her husband at the mouth of the creek near the Ohio River.</s>

<s docid="AP900616-0123" num="28" wdcount="21"> Capt. James Boling of the Ohio National Guard said local authorities told him some of the bar patrons remained unaccounted for.</s>

<s docid="AP900616-0123" num="29" wdcount="19"> Kathy Schramm, 37, said she, her husband and their two children fled their two-story house before water washed through.</s>

<s docid="AP900616-0123" num="30" wdcount="19"> When they returned, the basement and first floor were flooded, and the surrounding area ``looked like a big lake''.</s>

<s docid="AP900616-0123" num="31" wdcount="24"> ``I looked up at a house on the hill, and it looked like it was on stilts on the water,'' Mrs. Schramm said .</s>
</TEXT>
</DOC>
