<DOC>
<DOCNO>

<s docid="AP900615-0115" num="1" wdcount="1"> AP900615-0115</s>
</DOCNO>
<FILEID>

<s docid="AP900615-0115" num="2" wdcount="2"> AP-NR-06-15-90 1353EDT</s>
</FILEID>
<FIRST>

<s docid="AP900615-0115" num="3" wdcount="7"> u a PM-OhioFlooding 5thLd-Writethru a0597 06-15 0760</s>
</FIRST>
<SECOND>

<s docid="AP900615-0115" num="4" wdcount="7"> PM-Ohio Flooding, 5th Ld - Writethru, a0597,0782</s>
</SECOND>
<HEAD>

<s docid="AP900615-0115" num="5" wdcount="7"> At Least Ten Dead in Ohio Flooding</s>
</HEAD>
<NOTE>

<s docid="AP900615-0115" num="6" wdcount="14"> Eds: Leads with 5 grafs to UPDATE with ten now dead, source of information.</s>

<s docid="AP900615-0115" num="7" wdcount="6"> Picks up 5th graf pvs: `Gov.</s>

<s docid="AP900615-0115" num="8" wdcount="2"> Richard ...'</s>
</NOTE>
<BYLINE>

<s docid="AP900615-0115" num="9" wdcount="3"> By MARGARET CALDWELL</s>
</BYLINE>
<BYLINE>

<s docid="AP900615-0115" num="10" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900615-0115" num="11" wdcount="3"> SHADYSIDE, Ohio (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900615-0115" num="12" wdcount="29"> Thunderstorms swept through central and eastern Ohio, causing flooding that killed at least ten people, left dozens missing and forced hundreds of others from their homes, officials said today.</s>

<s docid="AP900615-0115" num="13" wdcount="25"> Two creeks just outside this Ohio River village of 4,300 people overflowed when about 4 inches of rain fell Thursday night in about an hour.</s>

<s docid="AP900615-0115" num="14" wdcount="15"> ``It created a wall of water,'' said Jim Williams of the Ohio Emergency Management Agency.</s>

<s docid="AP900615-0115" num="15" wdcount="14"> ``The problem we're having right now is accounting for the people we can't find''.</s>

<s docid="AP900615-0115" num="16" wdcount="11"> Williams said 40 to 60 people remained unaccounted for at midday.</s>

<s docid="AP900615-0115" num="17" wdcount="12"> Belmont County's sheriff's Sgt. Bart Giesey said 10 people were confirmed dead.</s>

<s docid="AP900615-0115" num="18" wdcount="12"> Gov. Richard Celeste declared a state of emergency and surveyed the area.</s>

<s docid="AP900615-0115" num="19" wdcount="23"> The raging waters knocked homes off their foundations and washed away a bar filled with people in Shadyside, an Appalachian Mountain foothill town.</s>

<s docid="AP900615-0115" num="20" wdcount="15"> Temporary morgues were set up at Bellaire City Hospital and a funeral home in Shadyside.</s>

<s docid="AP900615-0115" num="21" wdcount="16"> Four bodies were brought to the hospital from the Shadyside area, hospital spokesman Lawrence England said.</s>

<s docid="AP900615-0115" num="22" wdcount="14"> England said the four bodies were taken to the Bauknecht Funeral Home in Shadyside.</s>

<s docid="AP900615-0115" num="23" wdcount="14"> Patty Valloric, director of the funeral home, said seven bodies had been brought there.</s>

<s docid="AP900615-0115" num="24" wdcount="18"> The Shadyside Fire Department set up a command center at the Jefferson Elementary School to coordinate rescue efforts.</s>

<s docid="AP900615-0115" num="25" wdcount="13"> Command center spokeswoman Karen Bovek said officials had no complete death toll figure.</s>

<s docid="AP900615-0115" num="26" wdcount="8"> Authorities were searching for victims in rural areas.</s>

<s docid="AP900615-0115" num="27" wdcount="16"> ``You're talking miles and miles of country roads that haven't been gotten to yet,'' she said.</s>

<s docid="AP900615-0115" num="28" wdcount="4"> ``It's a disaster here''.</s>

<s docid="AP900615-0115" num="29" wdcount="9"> Shadyside _ about 10 miles south of Wheeling, W.Va.</s>

<s docid="AP900615-0115" num="30" wdcount="13"> _ is in Belmont County, a mostly hilly, rural area in eastern Ohio.</s>

<s docid="AP900615-0115" num="31" wdcount="16"> Acting Mayor James Amato said the storms created a deluge that knocked homes off their foundations.</s>

<s docid="AP900615-0115" num="32" wdcount="15"> ``There are a lot of trailers out in this area that got hit,'' he said.</s>

<s docid="AP900615-0115" num="33" wdcount="24"> Belmont County Sheriff's Department spokeswoman Judy Phillips said a Shadyside bar full of people was washed away when water caved in the back wall.</s>

<s docid="AP900615-0115" num="34" wdcount="7"> Two people were accounted for, she said.</s>

<s docid="AP900615-0115" num="35" wdcount="13"> But she could offer no estimate of how many were in the bar.</s>

<s docid="AP900615-0115" num="36" wdcount="24"> Shadyside Fire Chief Mark Badia said rescuers pulled people from three cars in Wegee Creek, which flows through Shadyside and into the Ohio River.</s>

<s docid="AP900615-0115" num="37" wdcount="8"> ``I don't know how to describe it ...</s>

<s docid="AP900615-0115" num="38" wdcount="10"> you've got to see it to believe it,'' Badia said.</s>

<s docid="AP900615-0115" num="39" wdcount="16"> There also was flooding in Jefferson County, north of Belmont, and Licking County in central Ohio.</s>

<s docid="AP900615-0115" num="40" wdcount="39"> The Ohio departments of transportation and natural resources, the State Highway Patrol, the Public Utilities Commission of Ohio and the American Red Cross are assisting state government in assessing the damage, Ohio Emergency Management Agency spokeswoman Stacie Gilg said.</s>

<s docid="AP900615-0115" num="41" wdcount="27"> About 200 residents were evacuated from their homes in central Ohio after 3 inches of rain fell in an hour, flooding streets and washing out rural roads.</s>

<s docid="AP900615-0115" num="42" wdcount="24"> Residents from Newark and Marne in Licking County spent Thursday night in three emergency shelters, said Licking County Disaster Services Agency spokesman Neil Snelling.</s>

<s docid="AP900615-0115" num="43" wdcount="8"> Sixty residents were from one street in Newark.</s>

<s docid="AP900615-0115" num="44" wdcount="12"> ``Nobody has been hurt, but everything is pretty wet here,'' Snelling said.</s>

<s docid="AP900615-0115" num="45" wdcount="28"> The Newark Fire Department and other agencies evacuated residents in low-lying areas of Newark and the neighboring village of Marne, said Wayne Tresemer, Licking County Disaster Services director.</s>

<s docid="AP900615-0115" num="46" wdcount="32"> He said water was standing up to 5 feet deep in some streets on the city's east side, and the Newark Fire Department and other agencies used boats to evacuated some residents.</s>

<s docid="AP900615-0115" num="47" wdcount="38"> Licking County was already among 14 Ohio counties covered in a disaster declaration issued by President Bush for storms earlier this month, and people who suffered losses from Thursday night's storms will also be eligible for assistance, Ms.</s>

<s docid="AP900615-0115" num="48" wdcount="2"> Gilg said.</s>

<s docid="AP900615-0115" num="49" wdcount="25"> In Jefferson County, 50 to 60 residents were evacuated in Adena, where water was 6 to 8 feet deep in streets because of creek flooding.</s>

<s docid="AP900615-0115" num="50" wdcount="30"> Two inches of rain caused flooding in Franklin County in central Ohio and 3.75 inches of rain was dumped on Holmes County in north-central Ohio, the National Weather Service said.</s>

<s docid="AP900615-0115" num="51" wdcount="17"> Flood waters in most areas had subsided by Thursday night, the weather service and local authorities said.</s>

<s docid="AP900615-0115" num="52" wdcount="17"> The forecast for today called for a slight chance of thunderstorms in central and southern Ohio .</s>
</TEXT>
</DOC>
