<DOC>
<DOCNO>

<s docid="AP900616-0032" num="1" wdcount="1"> AP900616-0032</s>
</DOCNO>
<FILEID>

<s docid="AP900616-0032" num="2" wdcount="2"> AP-NR-06-16-90 0428EDT</s>
</FILEID>
<FIRST>

<s docid="AP900616-0032" num="3" wdcount="6"> r a PM-FlashFlood-Scene Bjt 06-16 0543</s>
</FIRST>
<SECOND>

<s docid="AP900616-0032" num="4" wdcount="3"> PM-Flash Flood-Scene, Bjt,0561</s>
</SECOND>
<HEAD>

<s docid="AP900616-0032" num="5" wdcount="9"> Homes Swept Away, Muddy Streams Remain After Flash Flood</s>
</HEAD>
<NOTE>

<s docid="AP900616-0032" num="6" wdcount="11"> Eds: Gilg is cq in 16th graf, `At least ...' .</s>
</NOTE>
<BYLINE>

<s docid="AP900616-0032" num="7" wdcount="3"> By RICH HARRIS</s>
</BYLINE>
<BYLINE>

<s docid="AP900616-0032" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900616-0032" num="9" wdcount="3"> SHADYSIDE, Ohio (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900616-0032" num="10" wdcount="33"> Cement blocks were all that remained of homes, fallen branches stood where trees used to be and muddy streams meandered through the outskirts of this Ohio River town after a furious flash flood.</s>

<s docid="AP900616-0032" num="11" wdcount="39"> Residents donned shorts and hip-waders Friday to begin putting their lives back together after 5 inches of rain fell in 3 hours late Thursday, churning floodwaters that left at least 11 people dead and 51 others missing early today.</s>

<s docid="AP900616-0032" num="12" wdcount="35"> The shock had not worn off, said police officer Bruce Fink, whose bristly face bore signs of more than 20 hours on duty, including work at a temporary morgue set up at a funeral home.</s>

<s docid="AP900616-0032" num="13" wdcount="11"> ``We have counselors back there now, but we've lost whole families.</s>

<s docid="AP900616-0032" num="14" wdcount="8"> It's just been devastating,'' he said Friday night.</s>

<s docid="AP900616-0032" num="15" wdcount="22"> Fink said he feared there wouldn't be enough funeral homes to handle the dead in this eastern Ohio town of 4,300 people.</s>

<s docid="AP900616-0032" num="16" wdcount="8"> Allan Hans called the flooding ``the devil's work''.</s>

<s docid="AP900616-0032" num="17" wdcount="13"> ``I lost everything but my car and the clothes I'm wearing,'' he said.</s>

<s docid="AP900616-0032" num="18" wdcount="21"> Hans said he was sitting in his trailer when he heard a branch crack and went to check out the noise.</s>

<s docid="AP900616-0032" num="19" wdcount="12"> He saw rushing water, ran to tell neighbors and moved his car.</s>

<s docid="AP900616-0032" num="20" wdcount="11"> The trailer was swept away by the time he returned home.</s>

<s docid="AP900616-0032" num="21" wdcount="21"> John and Sue Wright, whose home rests on the banks of Pipe Creek, estimated they lost about $20,000 worth of property.</s>

<s docid="AP900616-0032" num="22" wdcount="7"> ``I was one of the lucky ones.</s>

<s docid="AP900616-0032" num="23" wdcount="8"> What I lost, I can replace,'' Wright said.</s>

<s docid="AP900616-0032" num="24" wdcount="15"> Although it was the center of rescue operations, downtown Shadyside suffered no apparent flood damage.</s>

<s docid="AP900616-0032" num="25" wdcount="19"> But it was a different story on the outskirts of town, in the heart of Ohio's richest coal fields.</s>

<s docid="AP900616-0032" num="26" wdcount="16"> Cars were mired roof-deep in mud, and guardrails and chunks of concrete were torn from roads.</s>

<s docid="AP900616-0032" num="27" wdcount="33"> A 20-foot, 18-inch thick beam that held a sign leading to 3K's Bar near Pipe Creek was twisted like a pretzel by the force of what witnesses described as a wall of water.</s>

<s docid="AP900616-0032" num="28" wdcount="20"> People moved rubble and made makeshift repairs to bridges that span McMann Creek, which links homes to Ohio Route 147.</s>

<s docid="AP900616-0032" num="29" wdcount="5"> Many bridges were washed away.</s>

<s docid="AP900616-0032" num="30" wdcount="17"> Small tractors and four-wheel-drive vehicles were the only means of transportation in much of the stricken area.</s>

<s docid="AP900616-0032" num="31" wdcount="31"> At least 170 members of the Ohio National Guard were called in to patrol and to help rebuild flood-swept roads, said Stacie Gilg, a spokeswoman for the Ohio Emergency Management Agency.</s>

<s docid="AP900616-0032" num="32" wdcount="11"> Disasters always bring out the curious, and this was no exception.</s>

<s docid="AP900616-0032" num="33" wdcount="21"> By Friday night, traffic jammed Ohio Route 7, which skirts the Ohio River and is the main north-south road through town.</s>

<s docid="AP900616-0032" num="34" wdcount="15"> Belmont County Sheriff Tom McCort said he suspected many of the vehicles belonged to sightseers.</s>

<s docid="AP900616-0032" num="35" wdcount="9"> McCort said there were no serious attempts at looting.</s>

<s docid="AP900616-0032" num="36" wdcount="11"> He said he was pleased with the assistance of young people.</s>

<s docid="AP900616-0032" num="37" wdcount="18"> One young man turned in a strongbox filled with valuable coins lost in the flood, the sheriff said.</s>

<s docid="AP900616-0032" num="38" wdcount="3"> ``The kid ...</s>

<s docid="AP900616-0032" num="39" wdcount="10"> handed me this box and it was unlocked,'' McCort said.</s>

<s docid="AP900616-0032" num="40" wdcount="6"> ``It really made me feel good.''</s>
</TEXT>
</DOC>
