<DOC>
<DOCNO>

<s docid="AP900618-0069" num="1" wdcount="1"> AP900618-0069</s>
</DOCNO>
<FILEID>

<s docid="AP900618-0069" num="2" wdcount="2"> AP-NR-06-18-90 1205EDT</s>
</FILEID>
<FIRST>

<s docid="AP900618-0069" num="3" wdcount="7"> r a PM-FlashFloods 2ndLd-Writethru a0516 06-18 0699</s>
</FIRST>
<SECOND>

<s docid="AP900618-0069" num="4" wdcount="7"> PM-Flash Floods, 2nd Ld - Writethru, a0516,0713</s>
</SECOND>
<HEAD>

<s docid="AP900618-0069" num="5" wdcount="9"> Searchers Find 21st Flood Victim; Little Hope for Missing</s>
</HEAD>
<NOTE>

<s docid="AP900618-0069" num="6" wdcount="10"> Eds: SUBS lead and subs 5th graf, `The body ...</s>

<s docid="AP900618-0069" num="7" wdcount="24"> , with 2 grafs to UPDATE with authorities now saying 14 people are missing, sted 16; pick up 6th graf, `Four bodies .. .</s>
</NOTE>
<HEAD>

<s docid="AP900618-0069" num="8" wdcount="2"> LaserPhoto NY8</s>
</HEAD>
<BYLINE>

<s docid="AP900618-0069" num="9" wdcount="3"> By BOB LEWIS</s>
</BYLINE>
<BYLINE>

<s docid="AP900618-0069" num="10" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900618-0069" num="11" wdcount="3"> SHADYSIDE, Ohio (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900618-0069" num="12" wdcount="36"> The death toll from last week's flash floods mounted to 21 today when a body was found in the Ohio River, and authorities said there was little hope for the 14 people still listed as missing.</s>

<s docid="AP900618-0069" num="13" wdcount="5"> ``It's just been too long.</s>

<s docid="AP900618-0069" num="14" wdcount="8"> I don't think there's anybody alive out there.</s>

<s docid="AP900618-0069" num="15" wdcount="18"> You can't swim out there that long in the Ohio River,'' said Chuck Vogt, Belmont County coroner's investigator.</s>

<s docid="AP900618-0069" num="16" wdcount="17"> The search for the missing was suspended briefly this morning when a thunderstorm rolled through the area.</s>

<s docid="AP900618-0069" num="17" wdcount="21"> Heavy rain fell for about 45 minutes, swelling Wegee Creek, one of two creeks that overflowed in Thursday night's flash flood.</s>

<s docid="AP900618-0069" num="18" wdcount="22"> By midmorning, the muddy creek was nearly crossing a road about three miles upstream from where the floods inflicted the most damage.</s>

<s docid="AP900618-0069" num="19" wdcount="19"> Lt. Dean Irvin of the Ohio Army National Guard said there were no immediate reports of additional property damage.</s>

<s docid="AP900618-0069" num="20" wdcount="27"> The body found this morning was in the Ohio River near Moundsville, W.Va., about 10 miles south of Shadyside, according to Chuck Vogt, Belmont County coroner's investigator.</s>

<s docid="AP900618-0069" num="21" wdcount="34"> The number of names on the list of missing dropped from 18 to 14 with the identities of three victims and a call by one person alerting authorities that she was safe, Vogt said.</s>

<s docid="AP900618-0069" num="22" wdcount="7"> One of the recovered bodies remains unidentified.</s>

<s docid="AP900618-0069" num="23" wdcount="17"> Authorities are not ruling out the possibility that other people not on the list could be missing.</s>

<s docid="AP900618-0069" num="24" wdcount="5"> Four bodies were recovered Sunday.</s>

<s docid="AP900618-0069" num="25" wdcount="35"> Officials said Friday that 60 people were missing; some of those later were found dead, while others notified authorities that they were safe and officials learned that still more had moved out of the area.</s>

<s docid="AP900618-0069" num="26" wdcount="16"> Wegee and Pipe creeks overflowed during storms that dumped 5 inches of rain in 3 hours.</s>

<s docid="AP900618-0069" num="27" wdcount="14"> The floods destroyed as many as 70 houses and damaged up to 40 others.</s>

<s docid="AP900618-0069" num="28" wdcount="28"> Most of those whose homes and belongings were swept away by the wall of water will have to put their lives back together largely without benefit of insurance.</s>

<s docid="AP900618-0069" num="29" wdcount="25"> Few people in the coal-mining and steel-making area carried flood insurance, and homeowners' insurance will not cover damage from Thursday's flood, residents and insurers said.</s>

<s docid="AP900618-0069" num="30" wdcount="9"> ``We didn't think we needed to have flood insurance.</s>

<s docid="AP900618-0069" num="31" wdcount="2"> For what?</s>

<s docid="AP900618-0069" num="32" wdcount="4"> That creek never flooded.</s>

<s docid="AP900618-0069" num="33" wdcount="2"> Then this.</s>

<s docid="AP900618-0069" num="34" wdcount="8"> Everybody just got wiped out,'' said Julia Kulazenka.</s>

<s docid="AP900618-0069" num="35" wdcount="23"> Rainwater running down hillsides had forced debris into the creeks and formed dams at bridges spanning them, Shadyside Fire Chief Mark Badia said.</s>

<s docid="AP900618-0069" num="36" wdcount="7"> ``Eventually the bridges couldn't hold any more.</s>

<s docid="AP900618-0069" num="37" wdcount="16"> The debris broke loose, and that's when we got three big gushes of water,'' Badia said.</s>

<s docid="AP900618-0069" num="38" wdcount="22"> The home Mrs. Kulazenka shared with her husband until his death last July was damaged as Wegee Creek raged out of control.</s>

<s docid="AP900618-0069" num="39" wdcount="20"> She said replacing a machine shop, garage, deck and automobiles she and her son owned would cost more than $80,000.</s>

<s docid="AP900618-0069" num="40" wdcount="9"> ``They told us homeowners' won't do us no good.</s>

<s docid="AP900618-0069" num="41" wdcount="19"> So unless the government helps us rebuild, I don't know what I'll do with this place,'' Mrs. Kulazenka said.</s>

<s docid="AP900618-0069" num="42" wdcount="28"> The Federal Emergency Management Agency said it will open an office Tuesday in Shadyside to accept applications from residents for low-interest loans and grants to help them rebuild.</s>

<s docid="AP900618-0069" num="43" wdcount="17"> Before the flood, land in the Wegee Creek valley fetched handsome prices, said Kulazenka's son, Charles Kulazenka.</s>

<s docid="AP900618-0069" num="44" wdcount="30"> That was especially welcome to residents, many of whom were either retired or laid off from jobs in coal mines in Belmont County, where unemployment in April was 6.8 percent.</s>

<s docid="AP900618-0069" num="45" wdcount="19"> ``Ground was at a premium down here before this because it was just outside the city limits (of Shadyside).</s>

<s docid="AP900618-0069" num="46" wdcount="17"> It was quiet and peaceful and people were looking to buy and build new homes out here.</s>

<s docid="AP900618-0069" num="47" wdcount="8"> Now, you couldn't give it away,'' Kulazenka said.</s>

<s docid="AP900618-0069" num="48" wdcount="23"> ``But we can't be bitter, though, because we've got our lives, and a lot of our neighbors, real close buddies, weren't that lucky.''</s>
</TEXT>
</DOC>
