<DOC>
<DOCNO>

<s docid="AP900618-0018" num="1" wdcount="1"> AP900618-0018</s>
</DOCNO>
<FILEID>

<s docid="AP900618-0018" num="2" wdcount="2"> AP-NR-06-18-90 0052EDT</s>
</FILEID>
<FIRST>

<s docid="AP900618-0018" num="3" wdcount="7"> u a AM-FlashFloods 4thLd-Writethru a0717 06-18 0668</s>
</FIRST>
<SECOND>

<s docid="AP900618-0018" num="4" wdcount="7"> AM-Flash Floods, 4th Ld - Writethru, a0717,0684</s>
</SECOND>
<HEAD>

<s docid="AP900618-0018" num="5" wdcount="7"> Search Continues for Missing in Ohio Flood</s>
</HEAD>
<NOTE>

<s docid="AP900618-0018" num="6" wdcount="31"> Eds: LEADS with 7 grafs to UPDATE with 20th victim found, number of missing dropping to 16; PICKS UP 7th graf, `Twenty-three ...'; DELETES outdated 14th graf pvs, `That left ...'</s>
</NOTE>
<HEAD>

<s docid="AP900618-0018" num="7" wdcount="7"> LaserPhoto XBLR1, XBLR3, XBLR5, XBLR7, LaserColor XBLR2</s>
</HEAD>
<BYLINE>

<s docid="AP900618-0018" num="8" wdcount="3"> By RICH HARRIS</s>
</BYLINE>
<BYLINE>

<s docid="AP900618-0018" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900618-0018" num="10" wdcount="3"> SHADYSIDE, Ohio (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900618-0018" num="11" wdcount="31"> The death toll from flash floods that swept through a rural area of eastern Ohio rose to 20 Sunday as searchers dug along two creeks and dived into the Ohio River.</s>

<s docid="AP900618-0018" num="12" wdcount="4"> Sixteen people remained missing.</s>

<s docid="AP900618-0018" num="13" wdcount="35"> Workers used shovels and picks to dig along the creek banks, and sifted through debris at places marked with red flags, where search dogs indicated they'd detected human scents, said National Guard Capt. Jim Boling.</s>

<s docid="AP900618-0018" num="14" wdcount="10"> Divers worked where the two creeks empty into the Ohio.</s>

<s docid="AP900618-0018" num="15" wdcount="5"> Four bodies were found Sunday.</s>

<s docid="AP900618-0018" num="16" wdcount="20"> But two of those were not immediately identified, and the list of missing was not revised to account for them.</s>

<s docid="AP900618-0018" num="17" wdcount="43"> The number missing dropped to 16 with the other two bodies and the removal of two other names: a woman who called to say she was safe and a person who authorities weren't sure lived in the area, said coroner's investigator Chuck Vogt.</s>

<s docid="AP900618-0018" num="18" wdcount="23"> The 20th victim was pulled from the mouth of Pipe Creek at the Ohio River, about seven miles south of Shadyside, Vogt said.</s>

<s docid="AP900618-0018" num="19" wdcount="20"> Another body was found in debris along Wegee Creek, and two bodies were found earlier in the Ohio, he said.</s>

<s docid="AP900618-0018" num="20" wdcount="14"> That brought the confirmed death toll in Thursday's floods to 20, including five children.</s>

<s docid="AP900618-0018" num="21" wdcount="12"> Twenty-three dog teams from four states were searching for victims, said Boling.</s>

<s docid="AP900618-0018" num="22" wdcount="13"> The digging will continue at least through Tuesday, said Fire Chief Mark Badia.</s>

<s docid="AP900618-0018" num="23" wdcount="29"> ``The thing you find once you start into these brush piles and piles of trees are cars, and they have to be torn apart and searched separately,'' Badia said.</s>

<s docid="AP900618-0018" num="24" wdcount="8"> ``Everything you turn up creates a different situation''.</s>

<s docid="AP900618-0018" num="25" wdcount="13"> But Vogt said he doubted many of the missing would be found alive.</s>

<s docid="AP900618-0018" num="26" wdcount="5"> ``It's just been too long.</s>

<s docid="AP900618-0018" num="27" wdcount="10"> I don't think there's anybody alive out there,'' he said.</s>

<s docid="AP900618-0018" num="28" wdcount="11"> ``You can't swim out there that long in the Ohio River''.</s>

<s docid="AP900618-0018" num="29" wdcount="22"> The Wegee and Pipe creeks overflowed Thursday night during storms that poured 5 inches of rain onto eastern Ohio in 3 hours.</s>

<s docid="AP900618-0018" num="30" wdcount="14"> The floods destroyed as many as 70 houses and damaged up to 40 others.</s>

<s docid="AP900618-0018" num="31" wdcount="23"> Authorities said Friday that 60 people were missing; some of those were later found dead, while others notified authorities that they were safe.</s>

<s docid="AP900618-0018" num="32" wdcount="15"> Officials also learned that some of those feared missing had moved out of the area.</s>

<s docid="AP900618-0018" num="33" wdcount="20"> Officials were comparing county property lists and data from the Census Bureau with information from residents and relatives, Boling said.</s>

<s docid="AP900618-0018" num="34" wdcount="22"> Investigators Sunday blamed the flash floods on an unusually heavy rainstorm that overwhelmed the designed flow capacities of threebridges over the creeks.</s>

<s docid="AP900618-0018" num="35" wdcount="16"> Badia said rainwater running down hillsides forced debris into the creeks, forming dams at each bridge.</s>

<s docid="AP900618-0018" num="36" wdcount="7"> The ``dams'' broke under the water pressure.</s>

<s docid="AP900618-0018" num="37" wdcount="7"> ``Eventually the bridges couldn't hold any more.</s>

<s docid="AP900618-0018" num="38" wdcount="16"> The debris broke loose, and that's when we got three big gushes of water,'' he said.</s>

<s docid="AP900618-0018" num="39" wdcount="16"> As rescue efforts continued, the National Guard cleared roads and bridges leading into the stricken area.</s>

<s docid="AP900618-0018" num="40" wdcount="17"> Eighteen Ohio counties have been declared federal disaster areas since tornadoes and flooding first struck May 25.</s>

<s docid="AP900618-0018" num="41" wdcount="43"> Across the border in West Virginia, Gov. Gaston Caperton said Sunday he had no precise dollar figure on damage from flooding Friday along a five-mile stretch near New Martinsville and in nearby Ohio County, but estimated it will run into millions of dollars.</s>

<s docid="AP900618-0018" num="42" wdcount="7"> No deaths or serious injuries were reported.</s>

<s docid="AP900618-0018" num="43" wdcount="14"> Caperton toured flooded areas in Wheeling and the Doolin Run community near New Martinsville.</s>

<s docid="AP900618-0018" num="44" wdcount="14"> He said he saw ``tremendous devastation'' to hundreds of houses, house trailers and cars.</s>

<s docid="AP900618-0018" num="45" wdcount="18"> State Public Safety Secretary Joseph Skaff estimated that repairing and replaceing bridges and roads will cost about $750,000.</s>

<s docid="AP900618-0018" num="46" wdcount="8"> National Guard soldiers helped with cleanup Sunday .</s>
</TEXT>
</DOC>
