<DOC>
<DOCNO>

<s docid="AP900615-0164" num="1" wdcount="1"> AP900615-0164</s>
</DOCNO>
<FILEID>

<s docid="AP900615-0164" num="2" wdcount="2"> AP-NR-06-15-90 2245EDT</s>
</FILEID>
<FIRST>

<s docid="AP900615-0164" num="3" wdcount="7"> u a AM-FlashFlood 4thLd-Writethru a0736 06-15 1081</s>
</FIRST>
<SECOND>

<s docid="AP900615-0164" num="4" wdcount="7"> AM-Flash Flood, 4th Ld - Writethru, a0736,1112</s>
</SECOND>
<HEAD>

<s docid="AP900615-0164" num="5" wdcount="9"> Water Wall Hits Ohio Town; 11 Dead, 51 Missing</s>
</HEAD>
<NOTE>

<s docid="AP900615-0164" num="6" wdcount="39"> Eds: Leads with 12 grafs to UPDATE to show that missing persons all from flood area, describe location of victims, move up reference to 51 missing, DELETE comment of unnamed firefighter; Picks up 14th graf, `Some of ... '</s>
</NOTE>
<HEAD>

<s docid="AP900615-0164" num="7" wdcount="5"> LaserPhoto PG1-3; LaserColor PG100; LaserGraphic</s>
</HEAD>
<BYLINE>

<s docid="AP900615-0164" num="8" wdcount="3"> By MARGARET CALDWELL</s>
</BYLINE>
<BYLINE>

<s docid="AP900615-0164" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP900615-0164" num="10" wdcount="3"> SHADYSIDE, Ohio (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP900615-0164" num="11" wdcount="31"> Torrential thunderstorms sent a flash flood surging through a valley into this Ohio River town, killing at least 11 people, leaving 51 missing and scores of others homeless Friday, authorities said.</s>

<s docid="AP900615-0164" num="12" wdcount="12"> Raging floodwaters late Thursday swept homes off foundations and washed away cars.</s>

<s docid="AP900615-0164" num="13" wdcount="9"> About 200 people were reported evacuated in central Ohio.</s>

<s docid="AP900615-0164" num="14" wdcount="21"> ``The valleys are choked with debris,'' Gov. Richard Celeste told reporters after flying over the hilly Appalachian region in eastern Ohio.</s>

<s docid="AP900615-0164" num="15" wdcount="10"> ``A wall of water wiped a path through the area''.</s>

<s docid="AP900615-0164" num="16" wdcount="16"> The governor declared a state of emergency, and dispatched about 50 National Guardsmen to the area.</s>

<s docid="AP900615-0164" num="17" wdcount="24"> The Federal Emergency Management Agency declared Belmont County, which includes Shadyside, and Jefferson and Franklin counties disaster areas, making federal aid available to residents.</s>

<s docid="AP900615-0164" num="18" wdcount="16"> Seventeen counties now have been declared disaster areas because of flooding or tornadoes since May 29.</s>

<s docid="AP900615-0164" num="19" wdcount="16"> Ten bodies were taken to the Bauknecht Funeral Home in Shadyside, said Bob Bell, funeral director.</s>

<s docid="AP900615-0164" num="20" wdcount="10"> One body was taken to Bellaire City Hospital, he said.</s>

<s docid="AP900615-0164" num="21" wdcount="13"> Chuck Vogt, Belmont County coroner's investigator, also said there were 11 confirmed dead.</s>

<s docid="AP900615-0164" num="22" wdcount="14"> Earlier, Fire Chief Mark Badia had said 14 adults and two children were dead.</s>

<s docid="AP900615-0164" num="23" wdcount="9"> The names of the victims have not been released.</s>

<s docid="AP900615-0164" num="24" wdcount="35"> County Sheriff Tom McCort, who said he was running the recovery effort, said 51 people in Shadysville and Meade Township, where the two creeks run south of the village, were missing as of 8:45 p.m.</s>

<s docid="AP900615-0164" num="25" wdcount="19"> The list was compiled through telephone inquiries with townspeople and relatives and interviews with people evacuated from the area.</s>

<s docid="AP900615-0164" num="26" wdcount="21"> About 200 people came and went from a Shadyside disaster center during the day, seeking news of missing friends and relatives.</s>

<s docid="AP900615-0164" num="27" wdcount="24"> Vogt said two bodies were found in the Ohio River and one was found in a field next to the river after water receded.</s>

<s docid="AP900615-0164" num="28" wdcount="14"> He said the rest were found in the creeks, which flow into the river.</s>

<s docid="AP900615-0164" num="29" wdcount="25"> Some of the bodies were taken to a funeral home that set up a temporary morgue in Shadyside, about 10 miles south of Wheeling, W.Va.</s>

<s docid="AP900615-0164" num="30" wdcount="8"> Officials from Ohio, West Virginia and the U.S.</s>

<s docid="AP900615-0164" num="31" wdcount="25"> Coast Guard were searching the Ohio River for survivors and bodies, and Badia said National Guardsmen were to continue searching the creeks throughout the night.</s>

<s docid="AP900615-0164" num="32" wdcount="22"> At least five houses along Wegee Creek were washed away, and two cars were floating in water in one of the basements.</s>

<s docid="AP900615-0164" num="33" wdcount="20"> Anything that was still standing was covered with at least 6 feet of debris such as trees, appliances and furniture.</s>

<s docid="AP900615-0164" num="34" wdcount="28"> The National Weather Service issued no flood warning before the disaster, although it did issue a flood watch, said Al Wheeler, deputy meteorologist in the bureau's Cleveland office.</s>

<s docid="AP900615-0164" num="35" wdcount="24"> Weather service offices in Cleveland, Akron, Columbus and Pittsburgh showed the storm had diminished over eastern Ohio when it had actually intensified, Wheeler said.</s>

<s docid="AP900615-0164" num="36" wdcount="21"> Thursday night's thunderstorms caused flash flooding across a wide area of central and eastern Ohio, northern West Virginia and western Pennsylvania.</s>

<s docid="AP900615-0164" num="37" wdcount="13"> The floods closed roads, damaged homes and forced hundreds of people to evacuate.</s>

<s docid="AP900615-0164" num="38" wdcount="15"> But no place was hit with anything approaching the ferocity of the flooding in Shadyside.</s>

<s docid="AP900615-0164" num="39" wdcount="26"> About 5.5 inches of rain fell between 7:30 p.m. and 11 p.m., turning two Ohio River tributaries outside the village of 4,300 people into dangerous torrents.</s>

<s docid="AP900615-0164" num="40" wdcount="36"> About 35 buildings, including a tavern, were damaged along Wegee Creek, and 50 buildings were hit by a flood along Pipe Creek, four miles south of Wegee Creek, said Dick Quinlin, Belmont County emergency services coordinator.</s>

<s docid="AP900615-0164" num="41" wdcount="21"> Part of the tavern was washed away when water caved in the back wall, said Judy Phillips, a sheriff's department spokeswoman.</s>

<s docid="AP900615-0164" num="42" wdcount="21"> She said two patrons were accounted for, but she could offer no estimate of how many were inside at the time.</s>

<s docid="AP900615-0164" num="43" wdcount="18"> One man was found clinging to a bar stool, said state Sen. Robert Ney, whose district includes Shadyside.</s>

<s docid="AP900615-0164" num="44" wdcount="7"> ``I've never seen anything of this magnitude.</s>

<s docid="AP900615-0164" num="45" wdcount="6"> There was no warning,'' Ney said.</s>

<s docid="AP900615-0164" num="46" wdcount="20"> Rescuers pulled people from three cars in Wegee Creek, which flows through Shadyside and into the Ohio River, said Badia.</s>

<s docid="AP900615-0164" num="47" wdcount="7"> ``I don't know how to describe it.</s>

<s docid="AP900615-0164" num="48" wdcount="11"> ... You've got to see it to believe it,'' Badia said.</s>

<s docid="AP900615-0164" num="49" wdcount="18"> One resident, Robert Ramsey, said his wife, Rose, was crushed to death in their house by the water.</s>

<s docid="AP900615-0164" num="50" wdcount="24"> There was no complete accounting of deaths, said Karen Bovek, a spokeswoman at a Shadyside Fire Department command center set up an a school.</s>

<s docid="AP900615-0164" num="51" wdcount="16"> ``You're talking miles and miles of country roads that haven't been gotten to yet,'' she said.</s>

<s docid="AP900615-0164" num="52" wdcount="4"> ``It's a disaster here''.</s>

<s docid="AP900615-0164" num="53" wdcount="24"> There also was flooding in Jefferson County, north of Belmont, in Licking County in central Ohio, and in northwestern West Virginia and western Pennsylvania.</s>

<s docid="AP900615-0164" num="54" wdcount="27"> ``It's a pretty good mess, especially in the northern end of the county,'' said Clarence Weston, a dispatcher with the Marshall County Sheriff's Department in Moundsville, W.Va.</s>

<s docid="AP900615-0164" num="55" wdcount="12"> ``We had 3.5 inches of rain in a two-hour period last night''.</s>

<s docid="AP900615-0164" num="56" wdcount="15"> Most of the problems in West Virginia were confined to road closures and basement flooding.</s>

<s docid="AP900615-0164" num="57" wdcount="33"> At least 25 people were evacuated during the night in the Pittsburgh suburb of Etna, where some homes had up to 5 feet of water in their basements, said borough manager Bill Skertich.</s>

<s docid="AP900615-0164" num="58" wdcount="6"> They returned to their homes Friday.</s>

<s docid="AP900615-0164" num="59" wdcount="16"> Landslides were reported in the Pittsburgh area, and many city streets were closed during the storm.</s>

<s docid="AP900615-0164" num="60" wdcount="9"> The flooding was more serious in Licking County, Ohio.</s>

<s docid="AP900615-0164" num="61" wdcount="37"> Wayne Tresemer, the county's Disaster Services director, said water was standing up to 5 feet deep in some streets in the town of Newark, and the fire department and other agencies used boats to evacuate some residents.</s>

<s docid="AP900615-0164" num="62" wdcount="30"> Two inches of rain caused flooding in Franklin County in central Ohio and 3.75 inches of rain was dumped on Holmes County in north-central Ohio, the National Weather Service said.</s>

<s docid="AP900615-0164" num="63" wdcount="37"> In Jefferson County, just north of Belmont County in the eastern part of the state, 50 to 60 residents were evacuated in Adena, where water was 6 to 8 feet deep in streets because of creek flooding.</s>

<s docid="AP900615-0164" num="64" wdcount="14"> Flood waters in most areas had subsided by Thursday night, according to authorities .</s>
</TEXT>
</DOC>
