<DOC>
<DOCNO>

<s docid="LA061890-0066" num="1" wdcount="1"> LA061890-0066</s>
</DOCNO>
<DOCID>

<s docid="LA061890-0066" num="2" wdcount="1"> 235382</s>
</DOCID>
<DATE>
<P>

<s docid="LA061890-0066" num="3" wdcount="6"> June 18, 1990, Monday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA061890-0066" num="4" wdcount="8"> Part A; Page 13; Column 1; National Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA061890-0066" num="5" wdcount="2"> 497 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA061890-0066" num="6" wdcount="15"> DEATH TOLL REACHES 19, WITH 18 MISSING, AS CREWS DIG IN OHIO FLASH FLOOD DEBRIS;</s>
</P>
<P>

<s docid="LA061890-0066" num="7" wdcount="9"> SEARCH: WORKERS PROBE CREEKS WHERE DOGS SIGNAL HUMAN SCENTS.</s>

<s docid="LA061890-0066" num="8" wdcount="6"> THREE MORE BODIES ARE LOCATED .</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA061890-0066" num="9" wdcount="3"> From Associated Press</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA061890-0066" num="10" wdcount="2"> SHADYSIDE, Ohio</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA061890-0066" num="11" wdcount="31"> The death toll from flash floods that swept through a rural area of eastern Ohio increased to 19 Sunday as searchers dug along two creeks and dived into the Ohio River.</s>

<s docid="LA061890-0066" num="12" wdcount="5"> Eighteen people remained missing .</s>
</P>
<P>

<s docid="LA061890-0066" num="13" wdcount="37"> Workers used shovels and picks to dig along the creek banks, and sifted through debris at places marked with red flags, where search dogs indicated they had detected human scents, National Guard Capt. Jim Boling said .</s>
</P>
<P>

<s docid="LA061890-0066" num="14" wdcount="11"> Divers worked where the two creeks empty into the Ohio .</s>
</P>
<P>

<s docid="LA061890-0066" num="15" wdcount="26"> One body was found Sunday in debris along Wegee Creek, about three miles from where it meets the river, said Belmont County coroner's investigator Chuck Vogt.</s>

<s docid="LA061890-0066" num="16" wdcount="12"> Another was pulled from the Ohio near a bridge at Moundsville, W.</s>

<s docid="LA061890-0066" num="17" wdcount="10"> Va., about 10 miles south of Shadyside, he said .</s>
</P>
<P>

<s docid="LA061890-0066" num="18" wdcount="32"> The body of a man was found Sunday afternoon in the Ohio River, a half-mile south of the mouth of Wegee Creek and about seven miles south of Shadyside, Vogt said .</s>
</P>
<P>

<s docid="LA061890-0066" num="19" wdcount="15"> That brought the confirmed death toll in Thursday's floods to 19, including five children .</s>
</P>
<P>

<s docid="LA061890-0066" num="20" wdcount="10"> Twenty-three dog teams from four states were searching for victims.</s>

<s docid="LA061890-0066" num="21" wdcount="14"> The digging will continue at least through Tuesday, Fire Chief Mark Badia said .</s>
</P>
<P>

<s docid="LA061890-0066" num="22" wdcount="29"> "The thing you find once you start into these brush piles and piles of trees are cars, and they have to be torn apart and searched separately," Badia said.</s>

<s docid="LA061890-0066" num="23" wdcount="9"> "Everything you turn up creates a different situation" .</s>
</P>
<P>

<s docid="LA061890-0066" num="24" wdcount="13"> Vogt said he doubted many of the missing would be found alive .</s>
</P>
<P>

<s docid="LA061890-0066" num="25" wdcount="5"> "It's just been too long.</s>

<s docid="LA061890-0066" num="26" wdcount="10"> I don't think there's anybody alive out there," he said.</s>

<s docid="LA061890-0066" num="27" wdcount="12"> "You can't swim out there that long in the Ohio River" .</s>
</P>
<P>

<s docid="LA061890-0066" num="28" wdcount="24"> The Wegee and Pipe creeks overflowed Thursday night during storms that poured 5 1/2 inches of rain onto eastern Ohio in 3 1/2 hours.</s>

<s docid="LA061890-0066" num="29" wdcount="15"> The floods destroyed as many as 70 houses and damaged up to 40 others .</s>
</P>
<P>

<s docid="LA061890-0066" num="30" wdcount="24"> Authorities said Friday that 60 people were missing; some of those were later found dead, while others notified authorities that they were safe .</s>
</P>
<P>

<s docid="LA061890-0066" num="31" wdcount="15"> Officials also learned that some of those feared missing had moved out of the area.</s>

<s docid="LA061890-0066" num="32" wdcount="21"> Officials were comparing county property lists and data from the Census Bureau with information from residents and relatives, Boling said .</s>
</P>
<P>

<s docid="LA061890-0066" num="33" wdcount="7"> That left 18 still missing, Vogt said.</s>

<s docid="LA061890-0066" num="34" wdcount="22"> The list was not revised to account for the third body found Sunday afternoon because the man had not been identified .</s>
</P>
<P>

<s docid="LA061890-0066" num="35" wdcount="23"> Investigators Sunday blamed the flash floods on an unusually heavy rainstorm that overwhelmed the designed flow capacities of three bridges over the creeks.</s>

<s docid="LA061890-0066" num="36" wdcount="16"> Badia said rainwater running down hillsides forced debris into the creeks, forming dams at each bridge.</s>

<s docid="LA061890-0066" num="37" wdcount="8"> The "dams" broke under the water pressure .</s>
</P>
<P>

<s docid="LA061890-0066" num="38" wdcount="7"> "Eventually the bridges couldn't hold any more.</s>

<s docid="LA061890-0066" num="39" wdcount="17"> The debris broke loose, and that's when we got three big gushes of water," he said .</s>
</P>
<P>

<s docid="LA061890-0066" num="40" wdcount="17"> As rescue efforts continued, the National Guard cleared roads and bridges leading into the stricken area .</s>
</P>
<P>

<s docid="LA061890-0066" num="41" wdcount="18"> Eighteen Ohio counties have been declared federal disaster areas since tornadoes and flooding first struck May 25 .</s>
</P>
</TEXT>
<GRAPHIC>
<P>

<s docid="LA061890-0066" num="42" wdcount="20"> Photo, Team of divers in Ohio searches near junction of Pipe Creek and Ohio River for victims of flash flooding.</s>

<s docid="LA061890-0066" num="43" wdcount="28"> Associated Press; Photo, COLOR, A Lifetime's Loss: Shirley Dunfee is consoled by her husband, Bill, as they stand amid rubble of what was their farmhouse in Shadyside, Ohio.</s>

<s docid="LA061890-0066" num="44" wdcount="12"> The death toll from floods that swept the area rose to 19.</s>

<s docid="LA061890-0066" num="45" wdcount="2"> Associated Press</s>
</P>
</GRAPHIC>
<TYPE>
<P>

<s docid="LA061890-0066" num="46" wdcount="1"> Wire</s>
</P>
</TYPE>
<SUBJECT>
<P>

<s docid="LA061890-0066" num="47" wdcount="19"> RAIN -- MIDWESTERN UNITED STATES; STORMS -- OHIO; FLOODS -- OHIO; MISSING PERSONS; DISASTER VICTIMS; CASUALTIES; SEARCH AND RESCUES</s>
</P>
</SUBJECT>
</DOC>
