<DOC>
<DOCNO>

<s docid="LA061590-0176" num="1" wdcount="1"> LA061590-0176</s>
</DOCNO>
<DOCID>

<s docid="LA061590-0176" num="2" wdcount="1"> 234324</s>
</DOCID>
<DATE>
<P>

<s docid="LA061590-0176" num="3" wdcount="6"> June 15, 1990, Friday, P.M. Final</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA061590-0176" num="4" wdcount="9"> Part P; Page 2; Column 3; Late Final Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA061590-0176" num="5" wdcount="2"> 386 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA061590-0176" num="6" wdcount="8"> 10 DEAD, DOZENS MISSING IN OHIO FLASH FLOODS</s>
</P>
</HEADLINE>
<BYLINE>
<P>

<s docid="LA061590-0176" num="7" wdcount="4"> From Times Wire Services</s>
</P>
</BYLINE>
<DATELINE>
<P>

<s docid="LA061590-0176" num="8" wdcount="2"> SHADYSIDE, Ohio</s>
</P>
</DATELINE>
<TEXT>
<P>

<s docid="LA061590-0176" num="9" wdcount="34"> A flash flood sent a wall of water 15 to 20 feet high rampaging through hill communities along the Ohio River, killing at least 10 people and leaving dozens missing, authorities said today .</s>
</P>
<P>

<s docid="LA061590-0176" num="10" wdcount="27"> Two creeks just outside this Ohio River village of 4,300 residents overflowed when thunderstorms dumped about 4 inches of rain Thursday night in about an hour .</s>
</P>
<P>

<s docid="LA061590-0176" num="11" wdcount="15"> "It created a wall of water," said Jim Williams of the Ohio Emergency Management Agency.</s>

<s docid="LA061590-0176" num="12" wdcount="15"> "The problem we're having right now is accounting for the people we can't find" .</s>
</P>
<P>

<s docid="LA061590-0176" num="13" wdcount="12"> Williams said 40 to 60 people were unaccounted for at midday .</s>
</P>
<P>

<s docid="LA061590-0176" num="14" wdcount="13"> Belmont County's sheriff's Sgt. Bart Giesey said 10 people were confirmed dead .</s>
</P>
<P>

<s docid="LA061590-0176" num="15" wdcount="14"> Gov. Richard F. Celeste declared a state of emergency and surveyed the area .</s>
</P>
<P>

<s docid="LA061590-0176" num="16" wdcount="23"> The raging waters knocked homes off their foundations and washed away a bar filled with people in Shadyside, an Appalachian foothill town .</s>
</P>
<P>

<s docid="LA061590-0176" num="17" wdcount="19"> The Shadyside Fire Department set up a command center at the Jefferson Elementary School to coordinate rescue efforts .</s>
</P>
<P>

<s docid="LA061590-0176" num="18" wdcount="13"> Command center spokeswoman Karen Bovek said officials had no complete death toll figure.</s>

<s docid="LA061590-0176" num="19" wdcount="9"> Authorities were searching for victims in rural areas .</s>
</P>
<P>

<s docid="LA061590-0176" num="20" wdcount="16"> "You're talking miles and miles of country roads that haven't been gotten to yet," she said.</s>

<s docid="LA061590-0176" num="21" wdcount="5"> "It's a disaster here" .</s>
</P>
<P>

<s docid="LA061590-0176" num="22" wdcount="23"> Shadyside -- about 10 miles south of Wheeling, W.Va. -- is in Belmont County, a mostly hilly, rural area in eastern Ohio .</s>
</P>
<P>

<s docid="LA061590-0176" num="23" wdcount="16"> Acting Mayor James Amato said the storms created a deluge that knocked homes off their foundations.</s>

<s docid="LA061590-0176" num="24" wdcount="16"> "There are a lot of trailers out in this area that got hit," he said .</s>
</P>
<P>

<s docid="LA061590-0176" num="25" wdcount="24"> Belmont County Sheriff's Department spokeswoman Judy Phillips said a Shadyside bar full of people was washed away when water caved in the back wall.</s>

<s docid="LA061590-0176" num="26" wdcount="7"> Two people were accounted for, she said.</s>

<s docid="LA061590-0176" num="27" wdcount="14"> But she could offer no estimate of how many were in the bar .</s>
</P>
<P>

<s docid="LA061590-0176" num="28" wdcount="25"> Shadyside Fire Chief Mark Badia said rescuers pulled people from three cars in Wegee Creek, which flows through Shadyside and into the Ohio River .</s>
</P>
<P>

<s docid="LA061590-0176" num="29" wdcount="21"> "I don't know how to describe it . . . you've got to see it to believe it," Badia said .</s>
</P>
<P>

<s docid="LA061590-0176" num="30" wdcount="17"> There also was flooding in Jefferson County, north of Belmont, and Licking County in central Ohio .</s>
</P>
<P>

<s docid="LA061590-0176" num="31" wdcount="28"> About 200 residents were evacuated from their homes in central Ohio after 3 inches of rain fell in an hour, flooding streets and washing out rural roads .</s>
</P>
</TEXT>
<TYPE>
<P>

<s docid="LA061590-0176" num="32" wdcount="1"> Wire</s>
</P>
</TYPE>
</DOC>
