<DOC>
<DOCNO>

<s docid="AP881020-0157" num="1" wdcount="1"> AP881020-0157</s>
</DOCNO>
<FILEID>

<s docid="AP881020-0157" num="2" wdcount="2"> AP-NR-10-20-88 1450EDT</s>
</FILEID>
<FIRST>

<s docid="AP881020-0157" num="3" wdcount="5"> r i AM-Hirohito 10-20 0341</s>
</FIRST>
<SECOND>

<s docid="AP881020-0157" num="4" wdcount="1"> AM-Hirohito,0353</s>
</SECOND>
<HEAD>

<s docid="AP881020-0157" num="5" wdcount="5"> Emperor's Blood Pressure Drops Briefly</s>
</HEAD>
<BYLINE>

<s docid="AP881020-0157" num="6" wdcount="3"> By TERRIL JONES</s>
</BYLINE>
<BYLINE>

<s docid="AP881020-0157" num="7" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP881020-0157" num="8" wdcount="2"> TOKYO (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP881020-0157" num="9" wdcount="24"> Emperor Hirohito's blood pressure and pulse dropped sharply Thursday, but the vital signs later returned to normal as the ailing monarch's internal bleeding continued.</s>

<s docid="AP881020-0157" num="10" wdcount="21"> Hirohito, 87, discharged more blood and was given emergency transfusions, but was resting peacefully by nightfall, an imperial palace spokesman said.</s>

<s docid="AP881020-0157" num="11" wdcount="44"> Hirohito's blood pressure fell from 132 over 60 in the afternoon to 112 over 50 by evening, and his pulse from 104 per minute in the morning to 84 in the evening, said Kenji Maeda, chief of the Imperial Household Agency's General Affairs Division.</s>

<s docid="AP881020-0157" num="12" wdcount="24"> ``The emperor's blood pressure has returned to what is normal for him, and the head court physician says he is not worried,'' Maeda said.</s>

<s docid="AP881020-0157" num="13" wdcount="24"> One of Hirohito's daughters, Atsuko Ikeda, said Wednesday the emperor had coughed severely during her visit to him and had hardly responded to her.</s>

<s docid="AP881020-0157" num="14" wdcount="26"> On Thursday morning, Hirohito's two sons, Crown Prince Akihito and Prince Hitachi, visited him, and he was fully conscious and alert, a senior palace source said.</s>

<s docid="AP881020-0157" num="15" wdcount="12"> The monarch has been bedridden for a month with an intestinal hemorrhage.</s>

<s docid="AP881020-0157" num="16" wdcount="15"> There was renewed bleeding Thursday and the pace of the discharges was quickening, Maeda said.</s>

<s docid="AP881020-0157" num="17" wdcount="30"> Hirohito has received nearly 22 pints of blood since his illness worsened Sept. 19, and the transfusions had put a strain on Hirohito's heart and kidneys, Maeda said without elaborating.</s>

<s docid="AP881020-0157" num="18" wdcount="16"> The only solid food Hirohito has eaten since falling ill are a few spoonfuls of porridge.</s>

<s docid="AP881020-0157" num="19" wdcount="23"> Otherwise he is being fed intravenously, which gives him 600-700 calories a day, said the senior palace official, who refused to be identified.</s>

<s docid="AP881020-0157" num="20" wdcount="13"> Before his illness, Hirohito was taking about 1,300 calories daily, the official said.</s>

<s docid="AP881020-0157" num="21" wdcount="15"> The emperor complains of fatigue but does not appear to be in pain, he said.</s>

<s docid="AP881020-0157" num="22" wdcount="23"> Crown Princess Michiko, Hirohito's daughter-in-law, scaled down celebrations for her 54th birthday Thursday, canceling a traditional birthday news conference, another palace official said.</s>

<s docid="AP881020-0157" num="23" wdcount="15"> She planned a quiet gathering with members of the imperial family, the official said .</s>
</TEXT>
</DOC>
