<DOC>
<DOCNO>

<s docid="AP881118-0104" num="1" wdcount="1"> AP881118-0104</s>
</DOCNO>
<FILEID>

<s docid="AP881118-0104" num="2" wdcount="2"> AP-NR-11-18-88 1658EST</s>
</FILEID>
<FIRST>

<s docid="AP881118-0104" num="3" wdcount="5"> r i AM-Hirohito 11-18 0225</s>
</FIRST>
<SECOND>

<s docid="AP881118-0104" num="4" wdcount="1"> AM-Hirohito,0232</s>
</SECOND>
<HEAD>

<s docid="AP881118-0104" num="5" wdcount="6"> Hirohito Weakening, Weighs Only 66 Pounds</s>
</HEAD>
<HEAD>

<s docid="AP881118-0104" num="6" wdcount="3"> With AM-Hirohito-Gloom, Bjt</s>
</HEAD>
<DATELINE>

<s docid="AP881118-0104" num="7" wdcount="2"> TOKYO (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP881118-0104" num="8" wdcount="29"> Emperor Hirohito has lost nearly 40 pounds in the two months since he fell ill and now weighs only 66 pounds, a palace official was quoted as saying Friday.</s>

<s docid="AP881118-0104" num="9" wdcount="28"> The 87-year-old emperor's condition weakened Friday, but doctors speculated that a scab had stopped internal bleeding in his upper intestinal area, said Imperial Household Agency spokesman Kenji Maeda.</s>

<s docid="AP881118-0104" num="10" wdcount="15"> Hirohito has suffered repeated bouts of bleeding but has not discharged blood in nine days.</s>

<s docid="AP881118-0104" num="11" wdcount="16"> The emperor responds to queries from aides but is ``less talkative than before,'' Maeda told reporters.</s>

<s docid="AP881118-0104" num="12" wdcount="12"> He added that doctors sometimes have trouble determining whether Hirohito is awake.</s>

<s docid="AP881118-0104" num="13" wdcount="24"> News reports quoted Maeda as saying Hirohito has shed much of his normal 104 pounds during his confinement and now weighs about 66 pounds.</s>

<s docid="AP881118-0104" num="14" wdcount="14"> Hirohito had a temperature of 99.1 degrees Friday evening, up slightly from the morning.</s>

<s docid="AP881118-0104" num="15" wdcount="7"> His normal temperature is about 95.9 degrees.</s>

<s docid="AP881118-0104" num="16" wdcount="9"> Doctors have said he suffers from jaundice and anemia.</s>

<s docid="AP881118-0104" num="17" wdcount="10"> Maeda said the emperor's heart and kidneys were functioning normally.</s>

<s docid="AP881118-0104" num="18" wdcount="22"> Since Sept. 19, when he was confined to intensive care after vomiting blood, Hirohito has received 42 pints of blood in transfusions.</s>

<s docid="AP881118-0104" num="19" wdcount="25"> Palace officials have not given details on Hirohito's illness, and they would not comment on Japanese news reports that the emperor has pancreatic cancer .</s>
</TEXT>
</DOC>
