<DOC>
<DOCNO>

<s docid="AP890821-0100" num="1" wdcount="1"> AP890821-0100</s>
</DOCNO>
<FILEID>

<s docid="AP890821-0100" num="2" wdcount="2"> AP-NR-08-21-89 1744EDT</s>
</FILEID>
<FIRST>

<s docid="AP890821-0100" num="3" wdcount="5"> r i AM-Emperor 08-21 0211</s>
</FIRST>
<SECOND>

<s docid="AP890821-0100" num="4" wdcount="1"> AM-Emperor,0216</s>
</SECOND>
<HEAD>

<s docid="AP890821-0100" num="5" wdcount="7"> Hirohito Leaves $13 Million in Taxable Property</s>
</HEAD>
<DATELINE>

<s docid="AP890821-0100" num="6" wdcount="2"> TOKYO (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890821-0100" num="7" wdcount="17"> Emperor Hirohito left $13.06 million in taxable property, a tax office near the Imperial Palace announced Monday.</s>

<s docid="AP890821-0100" num="8" wdcount="25"> It was the first time that tax authorities have disclosed the amount of an emperor's taxable estate, an official in the Kojimachi Tax Office said.</s>

<s docid="AP890821-0100" num="9" wdcount="13"> Until the end of World War II, emperors were regarded as living gods.</s>

<s docid="AP890821-0100" num="10" wdcount="10"> Hirohito died of cancer on Jan. 7 at age 87.</s>

<s docid="AP890821-0100" num="11" wdcount="8"> He was succeeded by Akihito, his eldest son.</s>

<s docid="AP890821-0100" num="12" wdcount="6"> Hirohito's wife, Nagako, became empress dowager.</s>

<s docid="AP890821-0100" num="13" wdcount="22"> Akihito has paid $2.99 million in inheritance taxes on his half of his father's estate, which he divided evenly with his mother.</s>

<s docid="AP890821-0100" num="14" wdcount="16"> The empress dowager, as Hirohito's spouse, was exempt from paying inheritance taxes, Kyodo News Service reported.</s>

<s docid="AP890821-0100" num="15" wdcount="33"> The Japanese constitution, drafted by U.S. occupation forces shortly after the end of World War II in 1945, stipulates the emperor is the ``symbol of the state and the unity of the people''.</s>

<s docid="AP890821-0100" num="16" wdcount="8"> Hirohito's estate included stocks and other personal belongings.</s>

<s docid="AP890821-0100" num="17" wdcount="41"> Three sacred treasures _ a mirror, sword and jewels _ which were transferred from emperor to emperor, were tax-exempt, as were about 3,180 items of art owned by Hirohito that were donated to the state, the tax office official said .</s>
</TEXT>
</DOC>
