<DOC>
<DOCNO>

<s docid="AP890107-0119" num="1" wdcount="1"> AP890107-0119</s>
</DOCNO>
<FILEID>

<s docid="AP890107-0119" num="2" wdcount="2"> AP-NR-01-07-89 1709EST</s>
</FILEID>
<FIRST>

<s docid="AP890107-0119" num="3" wdcount="5"> u i AM-Hirohito-WorldReax 01-07 0674</s>
</FIRST>
<SECOND>

<s docid="AP890107-0119" num="4" wdcount="2"> AM-Hirohito-World Reax,0695</s>
</SECOND>
<HEAD>

<s docid="AP890107-0119" num="5" wdcount="4"> World Marks Emperor's Death</s>
</HEAD>
<HEAD>

<s docid="AP890107-0119" num="6" wdcount="3"> With AM-Hirohito, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP890107-0119" num="7" wdcount="3"> By CHRISTOPHER BURNS</s>
</BYLINE>
<BYLINE>

<s docid="AP890107-0119" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<TEXT>

<s docid="AP890107-0119" num="9" wdcount="32"> World leaders sent Japan messages of condolences and some declared states of mourning after Emperor Hirohito's death Saturday, but painful memories of World War II still generated criticism of the Japanese monarch.</s>

<s docid="AP890107-0119" num="10" wdcount="25"> President Reagan said Hirohito's 62-year reign ``spanned one of the most tumultuous, and yet at the same time constructive eras in the history of mankind.</s>

<s docid="AP890107-0119" num="11" wdcount="8"> ``It was also an era of unprecedented reconciliation.</s>

<s docid="AP890107-0119" num="12" wdcount="28"> His Majesty played a truly heroic role in bringing hostilities between our two peoples to an end,'' Reagan said, referring to Hirohito's decision to end World War II.</s>

<s docid="AP890107-0119" num="13" wdcount="19"> President Mikhail S. Gorbachev of the Soviet Union sent his ``sincere condolences'' and ``profound sympathy'' to the Japanese people.</s>

<s docid="AP890107-0119" num="14" wdcount="18"> His two-sentence telegram made no mention of wartime hostilities with what still is known officially as ``militarist Japan''.</s>

<s docid="AP890107-0119" num="15" wdcount="13"> The Kremlin currently is striving for better ties and increased trade with Japan.</s>

<s docid="AP890107-0119" num="16" wdcount="22"> India declared a three-day national state of mourning in honor of Hirohito and Norway's King Olav V announced a three-week court mourning.</s>

<s docid="AP890107-0119" num="17" wdcount="17"> President Francois Mitterrand of France opened an international conference on chemical weapons with a minute of silence.</s>

<s docid="AP890107-0119" num="18" wdcount="20"> But some reaction to Hirohito's death was cool in South Korea, which endured years of harsh colonial rule by Japan.</s>

<s docid="AP890107-0119" num="19" wdcount="28"> While President Roh Tae-woo of South Korea sent his condolences, a government party statement added, ``We reserve further comment, considering the unhappy past and the current Korea-Japan relationship''.</s>

<s docid="AP890107-0119" num="20" wdcount="14"> China extended condolences and Taiwan said it will send a delegation to the funeral.</s>

<s docid="AP890107-0119" num="21" wdcount="37"> But Taiwan's daily United Evening News said: ``It was an irony that while Hirohito apologized to the United States and Europe for the war, he did not direct a single word to China to show his sorrow''.</s>

<s docid="AP890107-0119" num="22" wdcount="32"> Most historians believe Hirohito was a powerless figurehead but had approved orders that led to the attack on Pearl Harbor and put most of East Asia under an often brutal Japanese rule.</s>

<s docid="AP890107-0119" num="23" wdcount="9"> Hirohito called on his nation to surrender in 1945.</s>

<s docid="AP890107-0119" num="24" wdcount="25"> The emperor's death drew mixed reaction in the Netherlands, which lost more than 20,000 people under Japan's wartime occupation of the former Dutch East Indies.</s>

<s docid="AP890107-0119" num="25" wdcount="40"> The government said it sent its sympathy for ``the loss that has befallen the Japanese people,'' without mentioning the name of Hirohito, branded a war criminal by survivors of the wartime occupation of the colony that became Indonesia in 1949.</s>

<s docid="AP890107-0119" num="26" wdcount="36"> ``To many war victims, only now has World War II finally come to an end,'' said Gen. Ruud Boekholt, chairman of the August 15 Commemoration Foundation, a group representing 127,000 Dutch citizens who underwent Japanese internment.</s>

<s docid="AP890107-0119" num="27" wdcount="26"> ``Daily, they still feel the pain of the wartime suffering that was inflicted on them in the name of Emperor Hirohito,'' Boekholt told The Associated Press.</s>

<s docid="AP890107-0119" num="28" wdcount="35"> But Indonesian President Suharto cabled his condolences to Crown Prince Akihito, Hirohito's eldest son who immediately ascended the Chrysanthemum Throne, and said he will personally pay the last homage to Hirohito, presidential spokesman Moerdiono said.</s>

<s docid="AP890107-0119" num="29" wdcount="16"> Pope John Paul II expressed his condolences and sent telegrams to Hirohito's family, Vatican radio reported.</s>

<s docid="AP890107-0119" num="30" wdcount="19"> Queen Elizabeth II said she was saddened and Prime Minister Margaret Thatcher said she shares the Japanese people's sorrow.</s>

<s docid="AP890107-0119" num="31" wdcount="9"> But opposition lawmakers said Britain should boycott his funeral.</s>

<s docid="AP890107-0119" num="32" wdcount="31"> ``No one should go to that funeral from this country,'' said Ron Brown, a lawmaker of the opposition Labor Party, who denounced Hirohito as ``a war criminal of the worst kind''.</s>

<s docid="AP890107-0119" num="33" wdcount="13"> ``It would be a grave insult to the many men and women ...</s>

<s docid="AP890107-0119" num="34" wdcount="6"> imprisoned in slave camps,'' he said.</s>

<s docid="AP890107-0119" num="35" wdcount="11"> ``Many of them died, but those who survived still suffer today''.</s>

<s docid="AP890107-0119" num="36" wdcount="30"> King Juan Carlos of Spain, King Faisal of Saudi Arabia and other Persian Gulf monarchs, King Birendra of Nepal and Sultan Mahmood Iskandar of Malaysia also sent condolences to Akihito.</s>

<s docid="AP890107-0119" num="37" wdcount="38"> Brazil called Hirohito ``a superior symbol of the Japanese nation, its culture and its anxieties in a period of drastic transformations in the world and his country and in a time of grave new challenges in the world.''</s>
</TEXT>
</DOC>
