<DOC>
<DOCNO>

<s docid="AP890107-0039" num="1" wdcount="1"> AP890107-0039</s>
</DOCNO>
<FILEID>

<s docid="AP890107-0039" num="2" wdcount="2"> AP-NR-01-07-89 0424EST</s>
</FILEID>
<FIRST>

<s docid="AP890107-0039" num="3" wdcount="5"> u i PM-Hirohito-WorldRdp 01-07 0718</s>
</FIRST>
<SECOND>

<s docid="AP890107-0039" num="4" wdcount="2"> PM-Hirohito-World Rdp,0736</s>
</SECOND>
<HEAD>

<s docid="AP890107-0039" num="5" wdcount="9"> Most Of World, Except Asian Opponents, Mourn Hirohito's Death</s>
</HEAD>
<HEAD>

<s docid="AP890107-0039" num="6" wdcount="3"> With PM-Obit-Hirohito, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP890107-0039" num="7" wdcount="4"> By The Associated Press</s>
</BYLINE>
<TEXT>

<s docid="AP890107-0039" num="8" wdcount="34"> World leaders from President Reagan to Malaysia's king mourned today's death of Emperor Hirohito, who surrendered a broken nation to the Allies in World War II but presided over its rise to economic pre-eminence.</s>

<s docid="AP890107-0039" num="9" wdcount="27"> Reaction to Hirohito's death at age 87, however, was decidedly cool in several Asian countries, including South Korea, which endured years of harsh colonial rule by Japan.</s>

<s docid="AP890107-0039" num="10" wdcount="27"> While South Korea President Roh Tae-Woo sent his condolences, a government party statement added, ``We reserve further comment, considering the unhappy past and the current Korea-Japan relationship''.</s>

<s docid="AP890107-0039" num="11" wdcount="29"> The main opposition party led by Kim Dae-jung said, ``We have complex feelings at the death of Hirohito in view of Japan's 20-year rule over Korea during his reign''.</s>

<s docid="AP890107-0039" num="12" wdcount="24"> A leading newspaper in Seoul, The Joong-Ang Daily News, wrote that Hirohito's death ``reminds all the Korean people of a disgraced period and ...</s>

<s docid="AP890107-0039" num="13" wdcount="2"> humiliation. ...</s>

<s docid="AP890107-0039" num="14" wdcount="20"> Hirohito is the symbolic figure who must assume most and final responsibility for (Japan's) preposterous crimes to the Korean people''.</s>

<s docid="AP890107-0039" num="15" wdcount="32"> Korea was divided into the communist north and the capitalist south in 1945, when U.S. and Soviet troops ended Japan's rule that began in 1910 with Japan's forced annexation of the peninsula.</s>

<s docid="AP890107-0039" num="16" wdcount="54"> There was no official comment from the nationalist Chinese government because of the lack of diplomatic relations between Taiwan and Japan, but the mass circulation Chinese daily United Evening News said: ``Asian people who suffered from the slavery and invasion of Japan's militarists during World War II may bury their animosity with Hirohito's death.</s>

<s docid="AP890107-0039" num="17" wdcount="9"> ... Chinese suffered the most from the Japanese invasion.</s>

<s docid="AP890107-0039" num="18" wdcount="33"> ``It was an irony that while Hirohito apologized to the United States and Europe for the war, he did not direct a single word to China to show his sorrow.Now, Hirohito has died.</s>

<s docid="AP890107-0039" num="19" wdcount="17"> We may not want to collect the reparations, but we shall never forget the painful historic lessions''.</s>

<s docid="AP890107-0039" num="20" wdcount="56"> In the United States, President Reagan said in a statement, ``His Majesty's 62-year reign spanned one of the most tumultuous, and yet at the same time constructive eras in the history of mankind _ an age of unprecedented economic collapse, a most vicious war, astonishing scientific acheivement, and dramatic political and social changes throughout the world.</s>

<s docid="AP890107-0039" num="21" wdcount="8"> ``It was also an era of unprecedented reconciliation.</s>

<s docid="AP890107-0039" num="22" wdcount="28"> His Majesty played a truly heroic role in bringing hostilities between our two peoples to an end,'' Reagan said, referring to Hirohito's decision to end World War II.</s>

<s docid="AP890107-0039" num="23" wdcount="16"> In New Zealand, Prime Minister David Lange said Hirohito's death marks the end of an era.</s>

<s docid="AP890107-0039" num="24" wdcount="25"> ``During his reign he saw the transition from the most turbulent period in Japan's modern history to the stability and prosperity of today,'' Lange said.</s>

<s docid="AP890107-0039" num="25" wdcount="40"> President Corazon Aquino of the Philippines sent condolences to the imperial family and her foreign secretary, Raul Manglapus, a Japanese prisoner of war during World War II, praised Hirohito as ``a stabilizing factor'' in the creation of a democratic Japan.</s>

<s docid="AP890107-0039" num="26" wdcount="21"> ``He provided a figurehead that kept the Japanese people firmly committed to peaceful means of achieving their national goals,'' Manglapus said.</s>

<s docid="AP890107-0039" num="27" wdcount="23"> Condolences also came from King Sultan Mahmood Iskandar of Malaysia to Hirohito's oldest son, Crown Prince Akihito, who immediately ascended the Chrysanthemum Throne.</s>

<s docid="AP890107-0039" num="28" wdcount="33"> Prime Minister Bob Hawke of Australia paid his respects in a message to Japanese Prime Minister Noburu Takeshita: ``Throughout his long life, the emperor was held in the highest esteem by his people.</s>

<s docid="AP890107-0039" num="29" wdcount="19"> Now, as Japan enters a period of mourning and prepares for a new age, our thoughts are with you''.</s>

<s docid="AP890107-0039" num="30" wdcount="29"> But Bruce Ruxton, an official of the Returned Services League, which representing almost 300,000 Australian war veterans, said there would not ``be too many tears shed around the world''.</s>

<s docid="AP890107-0039" num="31" wdcount="18"> He described Hirohito, whose role in the war has been debated, as ``one of the worst war criminals''.</s>

<s docid="AP890107-0039" num="32" wdcount="21"> Marine biologists paid homage to another facet of the monarch's life _ his 12 books published on hydrozoa, or sea animals.</s>

<s docid="AP890107-0039" num="33" wdcount="24"> Robert Hessler of the Scripps Institution of Oceanography in La Jolla, Calif., said Hirohito preferred the quiet study to his destined role as leader.</s>

<s docid="AP890107-0039" num="34" wdcount="13"> ``The poor man didn't really get to do what he wanted to do.</s>

<s docid="AP890107-0039" num="35" wdcount="17"> He had to be emperor first, then second a scientist and normal human being,'' Hessler said .</s>
</TEXT>
</DOC>
