<DOC>
<DOCNO>

<s docid="AP890224-0003" num="1" wdcount="1"> AP890224-0003</s>
</DOCNO>
<FILEID>

<s docid="AP890224-0003" num="2" wdcount="2"> AP-NR-02-24-89 0134EST</s>
</FILEID>
<FIRST>

<s docid="AP890224-0003" num="3" wdcount="5"> r i PM-Hirohito-Name 02-24 0410</s>
</FIRST>
<SECOND>

<s docid="AP890224-0003" num="4" wdcount="1"> PM-Hirohito-Name,0419</s>
</SECOND>
<HEAD>

<s docid="AP890224-0003" num="5" wdcount="8"> To The Japanese, Hirohito Has Become Emperor Showa</s>
</HEAD>
<HEAD>

<s docid="AP890224-0003" num="6" wdcount="7"> Eds: Also in Friday AMs report .</s>
</HEAD>
<HEAD>

<s docid="AP890224-0003" num="7" wdcount="4"> With PM-Hirohito Funeral, Bjt</s>
</HEAD>
<DATELINE>

<s docid="AP890224-0003" num="8" wdcount="2"> TOKYO (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890224-0003" num="9" wdcount="21"> To the rest of the world, he was known as Emperor Hirohito, but in Japan his given name was seldom used.</s>

<s docid="AP890224-0003" num="10" wdcount="13"> In Japanese he was simply called Tenno Heika, meaning His Majesty The Emperor.</s>

<s docid="AP890224-0003" num="11" wdcount="24"> The foreign habit of using his name rankled some Japanese, who found it impolite, and unnecessary since to them there is only one emperor.</s>

<s docid="AP890224-0003" num="12" wdcount="24"> Some Japanese complained that after his death it even became inaccurate to call him Hirohito because he has been given the posthumous name Showa.</s>

<s docid="AP890224-0003" num="13" wdcount="24"> In Japanese histories, he will be recorded as Emperor Showa, the name he chose for his reign soon after he became emperor in 1926.</s>

<s docid="AP890224-0003" num="14" wdcount="34"> It means Enlightened Peace, and has been succeeded by Heisei, or Achieving Peace, the name the government chose for the reign of Hirohito's son Akihito a few hours after the emperor died Jan. 7.</s>

<s docid="AP890224-0003" num="15" wdcount="36"> But for the convenience of the rest of the world, which is not so able to keep track of the person behind the changed name, even official agencies have used the name Hirohito in English-language publications.</s>

<s docid="AP890224-0003" num="16" wdcount="25"> The obituary issued in English by the Foreign Press Center, which is supported by the Foreign Ministry, was headed ``His late Majesty The Emperor Hirohito''.</s>

<s docid="AP890224-0003" num="17" wdcount="41"> English-language newspapers published in Japan quickly began using the name Showa for Hirohito after his death, but it did not become truly official until Jan. 31, when Emperor Akihito conducted a ceremony in which Showa became the late emperor's posthumous name.</s>

<s docid="AP890224-0003" num="18" wdcount="22"> A stone tablet placed in his tomb is engraved only with the posthumous name and the dates of his death and burial.</s>

<s docid="AP890224-0003" num="19" wdcount="22"> The custom of renaming emperors after the completion of their reigns began after the death in 1912 of Emperor Meiji, Hirohito's grandfather.</s>

<s docid="AP890224-0003" num="20" wdcount="13"> In Japan, years are numbered according to the emperor's tenure on the throne.</s>

<s docid="AP890224-0003" num="21" wdcount="22"> Thus 1926 became Showa 1 as Crown Prince Hirohito ascended to the throne on Dec. 25 when his father, Emperor Taisho, died.</s>

<s docid="AP890224-0003" num="22" wdcount="17"> The year 1927 was Showa 2, and 1989 was Showa 64 until Hirohito's death on Jan. 7.</s>

<s docid="AP890224-0003" num="23" wdcount="6"> Now this year is Heisei 1.</s>

<s docid="AP890224-0003" num="24" wdcount="28"> The Japanese custom of changing imperial names is not unique among world royalty, where an individual may have a variety of names and titles in a royal career.</s>

<s docid="AP890224-0003" num="25" wdcount="15"> In Britain, Prince Andrew became the Duke of York upon his marriage in 1986 .</s>
</TEXT>
</DOC>
