<DOC>
<DOCNO>

<s docid="AP890112-0071" num="1" wdcount="1"> AP890112-0071</s>
</DOCNO>
<FILEID>

<s docid="AP890112-0071" num="2" wdcount="2"> AP-NR-01-12-89 0929EST</s>
</FILEID>
<FIRST>

<s docid="AP890112-0071" num="3" wdcount="5"> r i PM-Britain-Hirohito 01-12 0347</s>
</FIRST>
<SECOND>

<s docid="AP890112-0071" num="4" wdcount="1"> PM-Britain-Hirohito,0361</s>
</SECOND>
<HEAD>

<s docid="AP890112-0071" num="5" wdcount="4"> BBC Show Says U.S.</s>

<s docid="AP890112-0071" num="6" wdcount="7"> Helped Spare Hirohito From War Crimes Trial</s>
</HEAD>
<HEAD>

<s docid="AP890112-0071" num="7" wdcount="2"> LaserPhoto NY6</s>
</HEAD>
<BYLINE>

<s docid="AP890112-0071" num="8" wdcount="3"> By MICHAEL WEST</s>
</BYLINE>
<BYLINE>

<s docid="AP890112-0071" num="9" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890112-0071" num="10" wdcount="2"> LONDON (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890112-0071" num="11" wdcount="28"> U.S. prosecutors pressured Japan's wartime prime minister, Gen. Hideki Tojo, into changing testimony at his trial to avoid incriminating Emperor Hirohito in war crimes, a television documentary claims.</s>

<s docid="AP890112-0071" num="12" wdcount="35"> The British Broadcasting Corp. documentary, details of which were released Wednesday by its maker Edward Behr, said the U.S. prosecutors worked with the emperor's aides to find a way to avoid putting Hirohito on trial.</s>

<s docid="AP890112-0071" num="13" wdcount="49"> The documentary challenges Hirohito's image as a peaceful man forced to go along with his generals' plans and alleges among other things that he: _Must have known about the massacre of at least 20,000 Chinese at Nanking in 1937 because he received regular detailed reports from the China front.</s>

<s docid="AP890112-0071" num="14" wdcount="22"> _Knew more than a month in advance of Japanese plans to attack the U.S. navy at Pearl Harbor on Dec. 7, 1941.</s>

<s docid="AP890112-0071" num="15" wdcount="12"> The BBC will show ``Hirohito _ Behind the Myth'' on Jan. 24.</s>

<s docid="AP890112-0071" num="16" wdcount="5"> Behr is a Paris-based journalist.</s>

<s docid="AP890112-0071" num="17" wdcount="15"> His biography of China's last monarch was used for the award-winning film ``The Last Emperor''.</s>

<s docid="AP890112-0071" num="18" wdcount="38"> It has been reported previously that American prosecutors wanted to keep Hirohito out of the war crimes trial and asked Tojo to suggest the emperor had consented reluctantly to the war on the advice of the High Command.</s>

<s docid="AP890112-0071" num="19" wdcount="37"> Gen. Douglas MacArthur, commander of the U.S. forces occupying Japan, wrote in his book ``Reminiscences'' that he fended off pressure from Britain and the Soviet Union to indict Hirohito, arguing that would touch off a guerrilla war.</s>

<s docid="AP890112-0071" num="20" wdcount="25"> Behr told The Associated Press in a telephone interview Wednesday that the documentary will be shown in the United States by PBS on March 13.</s>

<s docid="AP890112-0071" num="21" wdcount="20"> The BBC has also sold it to Australia, Austria, Canada, Hong Kong, Israel, Korea, the Netherlands, Norway, Spain and Sweden.</s>

<s docid="AP890112-0071" num="22" wdcount="8"> Hirohito died Saturday at the age of 87.</s>

<s docid="AP890112-0071" num="23" wdcount="29"> The documentary says the decision not to prosecute Hirohito came from President Harry S. Truman and that Tojo's evidence was altered so the emperor would not be incriminated .</s>
</TEXT>
</DOC>
