<DOC>
<DOCNO>

<s docid="AP890107-0016" num="1" wdcount="1"> AP890107-0016</s>
</DOCNO>
<FILEID>

<s docid="AP890107-0016" num="2" wdcount="2"> AP-NR-01-07-89 0142EST</s>
</FILEID>
<FIRST>

<s docid="AP890107-0016" num="3" wdcount="6"> r i PM-Hirohito-Profile 2Takes 01-07 1066</s>
</FIRST>
<SECOND>

<s docid="AP890107-0016" num="4" wdcount="3"> PM-Hirohito-Profile, 2 Takes,1096</s>
</SECOND>
<HEAD>

<s docid="AP890107-0016" num="5" wdcount="13"> The Biggest Decision of a 62-Year Reign _ Surrender in World War II</s>
</HEAD>
<HEAD>

<s docid="AP890107-0016" num="6" wdcount="3"> With PM-Obit-Hirohito, Bjt</s>
</HEAD>
<HEAD>

<s docid="AP890107-0016" num="7" wdcount="6"> Eds: First available for Saturday AMs</s>
</HEAD>
<TEXT>

<s docid="AP890107-0016" num="8" wdcount="37"> TOKYO (AP _ Emperor Hirohito will be remembered for one overwhelming decision during his 62-year reign: Japan must bow to defeat for the first time in its history and end the Pacific conflict in World War II.</s>

<s docid="AP890107-0016" num="9" wdcount="31"> Shortly after that decision, and for most of his reign, Hirohito became a figurehead, isolated from his subjects by tradition and steeped in his great love, the study of marine biology.</s>

<s docid="AP890107-0016" num="10" wdcount="15"> He was the last survivor among the national leaders of the World War II era.</s>

<s docid="AP890107-0016" num="11" wdcount="21"> But in his first 20 years, the ``Son of Heaven'' was worshiped as a divinity descended from the Sun Goddess Amaterasu.</s>

<s docid="AP890107-0016" num="12" wdcount="48"> The solitude of animal and plant life under the seas which so intrigued Hirohito was in keeping with the character of the man who became the 124th occupant of the Chrysanthemum Throne at the age of 25 on Christmas Day 1926, designating his reign ``Showa'' _ ``enlightened peace''.</s>

<s docid="AP890107-0016" num="13" wdcount="24"> The emperor was generally portrayed as having played no significant role in planning or carrying out Japan's military adventures in the 1930s and 1940s.</s>

<s docid="AP890107-0016" num="14" wdcount="18"> But it was his first effective decision as emperor, and his most courageous, that ended the Pacific conflict.</s>

<s docid="AP890107-0016" num="15" wdcount="48"> On Aug. 10, 1945, four days after history's first atomic bomb devastated Hiroshima and one day after a U.S. bomber dropped the second atomic bomb on Nagasaki, the generals and admirals of Imperial Japan's wartime government argued for hours in the sweltering bombproof shelter beneath the Tokyo palace.</s>

<s docid="AP890107-0016" num="16" wdcount="13"> Should Japan agree to the Allies' surrender demand, or fight on until annihilation?</s>

<s docid="AP890107-0016" num="17" wdcount="28"> Speaking in what some of those present described as a slow and obviously nervous monotone, Hirohito, the spiritual and titular leader, offered his opinion for the first time.</s>

<s docid="AP890107-0016" num="18" wdcount="24"> He spoke of his sorrow over the soldiers and sailors killed in the long war, and of families who lost everything in air raids.</s>

<s docid="AP890107-0016" num="19" wdcount="13"> ``I cannot bear to see my innocent people suffer any longer,'' he said.</s>

<s docid="AP890107-0016" num="20" wdcount="25"> ``Ending the war is the only way to restore world peace and to relieve the nation from the terrible distress with which it is burdened''.</s>

<s docid="AP890107-0016" num="21" wdcount="41"> Then, evoking a memory of his grandfather, the Emperor Meiji, whose reign (1867-1912) saw the end of 250 years of feudal Japanese isolation from the outside world, Hirohito told the officers: ``The time has come when we must bear the unbearable''.</s>

<s docid="AP890107-0016" num="22" wdcount="11"> In the days that followed, Hirohito continued his break with tradition.</s>

<s docid="AP890107-0016" num="23" wdcount="26"> In a national radio broadcast Aug. 15 _ the first time ordinary Japanese ever actually heard his voice _ he personally announced the decision to surrender.</s>

<s docid="AP890107-0016" num="24" wdcount="16"> He told the ravaged nation that ``the war situation has developed not necessarily to our advantage''.</s>

<s docid="AP890107-0016" num="25" wdcount="23"> Three weeks later, Hirohito donned a silk cutaway coat, striped trousers and a top hat to meet the Allied commander, Gen. Douglas A.</s>

<s docid="AP890107-0016" num="26" wdcount="4"> MacArthur, at the U.S.</s>

<s docid="AP890107-0016" num="27" wdcount="3"> Embassy in Tokyo.</s>

<s docid="AP890107-0016" num="28" wdcount="34"> It was the first time Hirohito had ever gone to see anyone, and the first of several calls on the general who had led the Pacific war against Japan and became its postwar governor.</s>

<s docid="AP890107-0016" num="29" wdcount="14"> On New Year's Day 1946, at MacArthur's insistence, the emperor publicly renounced his divinity.</s>

<s docid="AP890107-0016" num="30" wdcount="33"> It was a choice that enabled Hirohito to remain as the symbolic head of his nation and assured that he would not face charges as a war criminal, as some abroad had demanded.</s>

<s docid="AP890107-0016" num="31" wdcount="29"> It also was an act that seemed to relieve no one as much as this gentle, shy and retiring man who never seemed very comfortable as a ``living god''.</s>

<s docid="AP890107-0016" num="32" wdcount="16"> The emperor's status in the eyes of many Japanese changed to that of a kind uncle.</s>

<s docid="AP890107-0016" num="33" wdcount="9"> He became a widely respected authority on marine biology.</s>

<s docid="AP890107-0016" num="34" wdcount="26"> He possessed rare collections of marine life, discovered several species himself and wrote or co-authored at least 12 books on hydrozoa, or sea animals, his specialty.</s>

<s docid="AP890107-0016" num="35" wdcount="15"> In recent years, his life had become the subject of a popular comic book series.</s>

<s docid="AP890107-0016" num="36" wdcount="10"> Still, Hirohito and the imperial system remained important to Japan.</s>

<s docid="AP890107-0016" num="37" wdcount="34"> A nationwide survey by the daily newspaper Mainichi Shimbun in March 1987 indicated more than 80 percent of 2,184 people polled supported the imperial system, while only 11 percent said it should be abolished.</s>

<s docid="AP890107-0016" num="38" wdcount="9"> Five percent said the emperor should have more power.</s>

<s docid="AP890107-0016" num="39" wdcount="13"> From 1946 to 1954, Hirohito toured Japan to encourage the people to rebuild.</s>

<s docid="AP890107-0016" num="40" wdcount="40"> The Imperial Household Agency, which ran his affairs, said Hirohito considered the postwar period one of the most fulfilling times of his life, in which the nation made a phenomenal recovery from a war that cost 3.1 million Japanese lives.</s>

<s docid="AP890107-0016" num="41" wdcount="17"> Despite the humanization of the Imperial family, Hirohito remained under strict control of the Imperial Household Agency.</s>

<s docid="AP890107-0016" num="42" wdcount="17"> Protocol was maintained at nearly all times and he was prohibited from speaking on any controversial subject.</s>

<s docid="AP890107-0016" num="43" wdcount="7"> Hirohito was born on April 29, 1901.</s>

<s docid="AP890107-0016" num="44" wdcount="31"> In accordance with age-old imperial custom, he was taken from his parents as an infant to be reared in isolation by household functionaries and trained for one role, that of emperor.</s>

<s docid="AP890107-0016" num="45" wdcount="10"> His education came as Japan surged into the modern world.</s>

<s docid="AP890107-0016" num="46" wdcount="33"> The feudal samurai ethic was still strong; when his grandfather died, Gen. Maresuke Nogi, the mentor for the 11-year-old prince, calmly committed ritual suicide to follow the emperor, his master, to the grave.</s>

<s docid="AP890107-0016" num="47" wdcount="8"> Hirohito studied government and law with private tutors.</s>

<s docid="AP890107-0016" num="48" wdcount="26"> When he was 20, his father, Emperor Taisho, sent him abroad _ the first time any member of the immediate imperial family was allowed outside Japan.</s>

<s docid="AP890107-0016" num="49" wdcount="13"> Hirohito visited England, Scotland, France, Belgium, the Netherlands and Italy, receiving various decorations.</s>

<s docid="AP890107-0016" num="50" wdcount="8"> He was also received by Pope Benedict XV.</s>

<s docid="AP890107-0016" num="51" wdcount="17"> The young man handled money for the first time, paying his own fare on the Paris subway.</s>

<s docid="AP890107-0016" num="52" wdcount="15"> He developed a passion for bacon and eggs and it became a lifelong breakfast habit.</s>

<s docid="AP890107-0016" num="53" wdcount="23"> A palace chamberlain said in a 1980 interview that Hirohito shunned Japanese food ``unless it is forced on him by an unwitting host''.</s>

<s docid="AP890107-0016" num="54" wdcount="8"> Hirohito also acquired a preference for Western clothes.</s>

<s docid="AP890107-0016" num="55" wdcount="26"> He was never seen in public wearing traditional Japanese garb, and a palace official confided that the Emperor of Japan did not even own a kimono.</s>

<s docid="AP890107-0016" num="56" wdcount="29"> Hirohito became prince regent on Nov. 25, 1921, after his father became a mental and physical invalid, became emperor five years later and was formally enthroned in 1928 .</s>
</TEXT>
<NOTE>

<s docid="AP890107-0016" num="57" wdcount="1"> MORE</s>
</NOTE>
</DOC>
