<DOC>
<DOCNO>

<s docid="LA012289-0055" num="1" wdcount="1"> LA012289-0055</s>
</DOCNO>
<DOCID>

<s docid="LA012289-0055" num="2" wdcount="1"> 8533</s>
</DOCID>
<DATE>
<P>

<s docid="LA012289-0055" num="3" wdcount="6"> January 22, 1989, Sunday, Home Edition</s>
</P>
</DATE>
<SECTION>
<P>

<s docid="LA012289-0055" num="4" wdcount="9"> Opinion; Part 5; Page 4; Column 6; Letters Desk</s>
</P>
</SECTION>
<LENGTH>
<P>

<s docid="LA012289-0055" num="5" wdcount="2"> 230 words</s>
</P>
</LENGTH>
<HEADLINE>
<P>

<s docid="LA012289-0055" num="6" wdcount="3"> DEATH OF HIROHITO</s>
</P>
</HEADLINE>
<TEXT>
<P>

<s docid="LA012289-0055" num="7" wdcount="36"> The death of Emperor Hirohito finished the list of political and military leaders of the World War II era, one of the darkest and bloodiest eras of history on either the European or Asian continents .</s>
</P>
<P>

<s docid="LA012289-0055" num="8" wdcount="19"> The political and military role that Emperor Hirohito played before and during the war was never clear to us.</s>

<s docid="LA012289-0055" num="9" wdcount="27"> He may not have had that kind of influence now, but before the war he was regarded as god and was worshiped in Japan with religious vigor.</s>

<s docid="LA012289-0055" num="10" wdcount="28"> At the surrender of the Imperial Japanese government, Hirohito was spared punishment because "it was his ambitious military generals who made the decision to invade the neighbors" .</s>
</P>
<P>

<s docid="LA012289-0055" num="11" wdcount="46"> I found it is very hard to believe that a man in his middle age, in his position, in his culture and in his country at that time had nothing much to do with all the military aggravations that his armies imposed on neighboring countries .</s>
</P>
<P>

<s docid="LA012289-0055" num="12" wdcount="18"> Of course, some Japanese military leaders were executed after the war for criminal acts they were responsible for.</s>

<s docid="LA012289-0055" num="13" wdcount="25"> I often wonder if Hirohito ever felt grateful to those generals who were sacrificed, in part, so that he could live for another 43 years.</s>

<s docid="LA012289-0055" num="14" wdcount="43"> I only wish that the soul of Emperor Hirohito be ready to face the ultimate justice when he meets with the waiting souls of millions of innocent men, women and children who were tortured and murdered in his name during the war .</s>
</P>
<P>

<s docid="LA012289-0055" num="15" wdcount="3"> STEVE T. HU</s>
</P>
<P>

<s docid="LA012289-0055" num="16" wdcount="1"> Cerritos</s>
</P>
</TEXT>
<TYPE>
<P>

<s docid="LA012289-0055" num="17" wdcount="4"> Letter to the Editor</s>
</P>
</TYPE>
</DOC>
