<DOC>
<DOCNO>

<s docid="AP890922-0167" num="1" wdcount="1"> AP890922-0167</s>
</DOCNO>
<FILEID>

<s docid="AP890922-0167" num="2" wdcount="2"> AP-NR-09-22-89 2031EDT</s>
</FILEID>
<FIRST>

<s docid="AP890922-0167" num="3" wdcount="5"> r a AM-Hugo-Tracking 09-22 0533</s>
</FIRST>
<SECOND>

<s docid="AP890922-0167" num="4" wdcount="1"> AM-Hugo-Tracking,0554</s>
</SECOND>
<HEAD>

<s docid="AP890922-0167" num="5" wdcount="9"> Forecasting Aided By Supercomputers, But Still An Uncertain Science</s>
</HEAD>
<HEAD>

<s docid="AP890922-0167" num="6" wdcount="3"> With AM-Hugo, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP890922-0167" num="7" wdcount="4"> By KIM S. MARTIN</s>
</BYLINE>
<BYLINE>

<s docid="AP890922-0167" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890922-0167" num="9" wdcount="2"> MIAMI (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890922-0167" num="10" wdcount="28"> Supercomputers, satellites and the expertise of several hurricane forecasters predicted the destructive path Hurricane Hugo would follow, giving people plenty of time to flee the South Carolina coast.</s>

<s docid="AP890922-0167" num="11" wdcount="7"> But hurricane tracking remains an uncertain science.</s>

<s docid="AP890922-0167" num="12" wdcount="16"> Forecasters at the National Hurricane Center used computer models to track Hugo's path into Charleston, S.C.</s>

<s docid="AP890922-0167" num="13" wdcount="30"> ``All the world's knowledge about meteorological conditions and forecasting changes in those conditions is embodied in those models,'' said Thomas Pyke, head of National Oceanic and Atmospheric Administration's satellite service.</s>

<s docid="AP890922-0167" num="14" wdcount="22"> Pinpointing the exact point of Hugo's landfall was difficult, but forecasters said Friday that the landfall was predicted in time for evacuation.</s>

<s docid="AP890922-0167" num="15" wdcount="32"> ``Overall, I think the tracking models gave us a very good idea where Hugo would be so officials in South Carolina could act in a timely manner,'' said research meteorologist Colin McAdie.</s>

<s docid="AP890922-0167" num="16" wdcount="28"> The real forecasting problem with Hugo was predicting the intensity of the storm, which was upgraded to a Category 4 hurricane just hours before it slammed into Charleston.</s>

<s docid="AP890922-0167" num="17" wdcount="21"> ``It is very difficult to predict changes in intensity because we don't have very reliable computer models for that,'' McAdie said.</s>

<s docid="AP890922-0167" num="18" wdcount="11"> ``We really need to improve on our forecasting ability of strength''.</s>

<s docid="AP890922-0167" num="19" wdcount="21"> The hurricane specialists were surprised by the last-minute increase in wind speed, which was reported to them by Air Force reconnaissance.</s>

<s docid="AP890922-0167" num="20" wdcount="28"> Hurricane specialist Gil Clark, who has tracked hurricanes for 35 years, said that a couple of decades ago, the only forecasting tools were reports from aircraft or ships.</s>

<s docid="AP890922-0167" num="21" wdcount="18"> ``We had no radar or satellites then, so needless to say our forecasts were less accurate,'' Clark said.</s>

<s docid="AP890922-0167" num="22" wdcount="16"> In the late 1960s, the weather service began using satellites to obtain a global weather picture.</s>

<s docid="AP890922-0167" num="23" wdcount="20"> Information from the satellite is used to improve the accuracy of the large-scale models that television viewers see every night.</s>

<s docid="AP890922-0167" num="24" wdcount="39"> Using the information from the satellite, supercomputers at the National Meteorological Center in Suitland, Md., send information to the hurricane center where a tracking model constantly changes to account for current weather conditions and the position of the hurricane.</s>

<s docid="AP890922-0167" num="25" wdcount="26"> To determine the track of the storm, the forecasters analyze supercomputer predictions, satellite data, the history of similar storms and the current path of the hurricane.</s>

<s docid="AP890922-0167" num="26" wdcount="9"> Then they make an educated guess about the landfall.</s>

<s docid="AP890922-0167" num="27" wdcount="16"> Meteorology professor Kerry A. Emmanuel of the Massachussetts Institute of Technology criticizes the current forecasting system.</s>

<s docid="AP890922-0167" num="28" wdcount="27"> ``Congress and the American people are suffering from the collective delusion that our data problems have been solved by satellites and that just isn't true,'' Emmanuel said.</s>

<s docid="AP890922-0167" num="29" wdcount="22"> Satellites can give a ``pretty picture,'' he said, but not enough information about the wind and temperatures that affect a hurricane's path.</s>

<s docid="AP890922-0167" num="30" wdcount="25"> ``Most of the information actually used to predict hurricanes comes from flying airplanes into the hurricane, and they do a very good job,'' Emmanuel said.</s>

<s docid="AP890922-0167" num="31" wdcount="18"> Forecasters say the accuracy of satellite pictures is improving every year so long-range forecasting should become more precise.</s>

<s docid="AP890922-0167" num="32" wdcount="28"> ``We have to remember that those models used are only guidance products,'' Pyke said, ``and that it's ultimately the job of the forecaster to predict the storm's path.''</s>
</TEXT>
</DOC>
