<DOC>
<DOCNO>

<s docid="AP890922-0193" num="1" wdcount="1"> AP890922-0193</s>
</DOCNO>
<FILEID>

<s docid="AP890922-0193" num="2" wdcount="2"> AP-NR-09-22-89 2114EDT</s>
</FILEID>
<FIRST>

<s docid="AP890922-0193" num="3" wdcount="7"> r a AM-Hugo-Chronology 1stLd-Writethru a0714 09-22 0718</s>
</FIRST>
<SECOND>

<s docid="AP890922-0193" num="4" wdcount="4"> AM-Hugo-Chronology, 1st Ld-Writethru, a0714,0735</s>
</SECOND>
<HEAD>

<s docid="AP890922-0193" num="5" wdcount="4"> Hugo's Path of Destruction</s>
</HEAD>
<HEAD>

<s docid="AP890922-0193" num="6" wdcount="11"> Eds: UPDATES with Hugo losing designation, no longer being tracked .</s>
</HEAD>
<HEAD>

<s docid="AP890922-0193" num="7" wdcount="3"> With AM-Hugo Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP890922-0193" num="8" wdcount="4"> By The Associated Press</s>
</BYLINE>
<TEXT>

<s docid="AP890922-0193" num="9" wdcount="15"> Here is a chronology of Hurricane Hugo's destructive path across the Caribbean into South Carolina:</s>
</TEXT>
<TEXT>

<s docid="AP890922-0193" num="10" wdcount="18"> Sept. 11 _ Forecasters monitor new tropical wave forming off West Africa, southwest of the Cape Verde Islands.</s>

<s docid="AP890922-0193" num="11" wdcount="15"> Sept. 12 _ Storm reaches the 39 mph tropical storm threshold and is named Hugo.</s>

<s docid="AP890922-0193" num="12" wdcount="13"> Sept. 13 _ Hugo develops into a hurricane as winds reach 74 mph.</s>

<s docid="AP890922-0193" num="13" wdcount="12"> Storm is about 1,000 miles east of the Lesser Antilles island chain.</s>

<s docid="AP890922-0193" num="14" wdcount="16"> Sept. 14 _ Winds increase to 115 mph; storm is 650 miles east of Lesser Antilles.</s>

<s docid="AP890922-0193" num="15" wdcount="7"> Sept. 15 _ Winds reach 150 mph.</s>

<s docid="AP890922-0193" num="16" wdcount="10"> Storm, designated a Category 4 hurricane, is considered ``extremely dangerous''.</s>

<s docid="AP890922-0193" num="17" wdcount="10"> Located 340 east miles of French territorial island of Guadeloupe.</s>

<s docid="AP890922-0193" num="18" wdcount="15"> Sept. 16 _ Hugo bears down on Guadeloupe and Dominica with winds reaching 140 mph.</s>

<s docid="AP890922-0193" num="19" wdcount="10"> Sept. 17 _ Eye of Hugo is directly over Guadeloupe.</s>

<s docid="AP890922-0193" num="20" wdcount="10"> Guadeloupe is devasted by winds measuring up to 150 mph.</s>

<s docid="AP890922-0193" num="21" wdcount="18"> Five people are reported killed, 84 injured and more than 15,000 homeless on the island of 340,000 people.</s>

<s docid="AP890922-0193" num="22" wdcount="10"> Roofs were torn off, power lines downed and crops damaged.</s>

<s docid="AP890922-0193" num="23" wdcount="9"> Sept. 17 _ Hugo hits British island of Montserrat.</s>

<s docid="AP890922-0193" num="24" wdcount="10"> Nine people are killed and hundreds of buildings are flattened.</s>

<s docid="AP890922-0193" num="25" wdcount="13"> The British government says nearly all of the 12,000 island residents are homeless.</s>

<s docid="AP890922-0193" num="26" wdcount="17"> Sept. 17 _ On Antigua, two people are killed and there is widespread wind and rain damage.</s>

<s docid="AP890922-0193" num="27" wdcount="7"> Island hotels report water and wind damage.</s>

<s docid="AP890922-0193" num="28" wdcount="21"> Sept. 17 _ No casualties are reported on the island of St. Kitts, but houses are damaged and communications nearly severed.</s>

<s docid="AP890922-0193" num="29" wdcount="17"> Sept. 17 _ On the British Virgin Islands, trees are uprooted and power and communications knocked out.</s>

<s docid="AP890922-0193" num="30" wdcount="17"> On the resort island of Tortola, residents say there are numerous injuries and scores of homes destroyed.</s>

<s docid="AP890922-0193" num="31" wdcount="3"> In the U.S.</s>

<s docid="AP890922-0193" num="32" wdcount="15"> Virgin Islands, the popular tourist islands of St. Croix and St. Thomas are hard hit.</s>

<s docid="AP890922-0193" num="33" wdcount="10"> At least one person is reported killed on St. Croix.</s>

<s docid="AP890922-0193" num="34" wdcount="17"> Early reports say 97 percent of the buildings were damaged or destroyed on St. Croix, population 53,000.</s>

<s docid="AP890922-0193" num="35" wdcount="18"> Sailboats were blown out of the water and thrown up to 150 feet on shore in St. Thomas.</s>

<s docid="AP890922-0193" num="36" wdcount="4"> Some waterfront businesses disappeared.</s>

<s docid="AP890922-0193" num="37" wdcount="12"> On St. Croix, widespread looting is reported, including raids by machete-wielding gangs.</s>

<s docid="AP890922-0193" num="38" wdcount="21"> Some reports say prisoners escaped from jail and were roaming free and National Guardsman and police were joining in the looting.</s>

<s docid="AP890922-0193" num="39" wdcount="12"> Sept. 18 (daybreak) _ Hugo crosses the northeast corner of Puerto Rico.</s>

<s docid="AP890922-0193" num="40" wdcount="20"> Damage is estimated at hundreds of millions of dollars and homes of at least 50,000 people were destroyed or damaged.</s>

<s docid="AP890922-0193" num="41" wdcount="6"> At least three people are killed.</s>

<s docid="AP890922-0193" num="42" wdcount="12"> National Guardsmen were aiding the cleanup and trying to stop widespread looting.</s>

<s docid="AP890922-0193" num="43" wdcount="9"> The Pentagon said some of its facilities, including U.S.</s>

<s docid="AP890922-0193" num="44" wdcount="11"> Naval Station at Roosevelts Roads in Puerto Rico, were heavily damaged.</s>

<s docid="AP890922-0193" num="45" wdcount="17"> Sept. 19 _ On the Bahamas, islanders boarded up homes and stocked up as Hugo moved westward.</s>

<s docid="AP890922-0193" num="46" wdcount="17"> The storm brushes past the islands, with minimal damage, moving on a course parallel to the islands.</s>

<s docid="AP890922-0193" num="47" wdcount="18"> Sept. 20 _ Headed toward the southeast coast of the United States, Hugo has winds of 105-125 mph.</s>

<s docid="AP890922-0193" num="48" wdcount="9"> Sept. 21 _ Hugo picks up speed and power.</s>

<s docid="AP890922-0193" num="49" wdcount="4"> Winds reach 135 mph.</s>

<s docid="AP890922-0193" num="50" wdcount="13"> Hurricane is again classified as a Category 4 hurricane, capable of extreme damage.</s>

<s docid="AP890922-0193" num="51" wdcount="19"> Sept. 21 (midnight) _ Hugo crashes into Charleston, S.C., with winds of 135 mph, leveling buildings and flooding streets.</s>

<s docid="AP890922-0193" num="52" wdcount="12"> In addition to flooding, fires from natural gas leaks erupt in Charleston.</s>

<s docid="AP890922-0193" num="53" wdcount="8"> Several other coastal communities also suffer heavy damage.</s>

<s docid="AP890922-0193" num="54" wdcount="7"> Ten people in the Carolinas are killed.</s>

<s docid="AP890922-0193" num="55" wdcount="20"> Sept. 22 _ The hurricane, with steadily diminishing winds, continues to move inland and is downgraded to a tropical storm.</s>

<s docid="AP890922-0193" num="56" wdcount="14"> Further weakening is expected as it moves north with its load of heavy rain.</s>

<s docid="AP890922-0193" num="57" wdcount="14"> Sept. 22 _ Hugo was downgraded to a tropical storm at 6 a.m. Friday.</s>

<s docid="AP890922-0193" num="58" wdcount="31"> Twelve hours later it had all but lost the characteristics of a tropical storm and was weakening, although the weather system featured maximum sustained winds of 40 mph and torrential rains.</s>

<s docid="AP890922-0193" num="59" wdcount="19"> Its last location was just west of Pittsburgh, Pa., at latitude 40.5 degrees north and longitude 81 degrees west.</s>

<s docid="AP890922-0193" num="60" wdcount="9"> Officials said no further tracking would be done .</s>
</TEXT>
</DOC>
