<DOC>
<DOCNO>

<s docid="AP890923-0035" num="1" wdcount="1"> AP890923-0035</s>
</DOCNO>
<FILEID>

<s docid="AP890923-0035" num="2" wdcount="2"> AP-NR-09-23-89 0536EDT</s>
</FILEID>
<FIRST>

<s docid="AP890923-0035" num="3" wdcount="5"> r a PM-Hugo-Future 09-23 0468</s>
</FIRST>
<SECOND>

<s docid="AP890923-0035" num="4" wdcount="1"> PM-Hugo-Future,0484</s>
</SECOND>
<HEAD>

<s docid="AP890923-0035" num="5" wdcount="7"> Scientists: Warming Trends Could Mean Fiercer Hurricanes</s>
</HEAD>
<HEAD>

<s docid="AP890923-0035" num="6" wdcount="3"> With PM-Hugo, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP890923-0035" num="7" wdcount="3"> By RICHARD COLE</s>
</BYLINE>
<BYLINE>

<s docid="AP890923-0035" num="8" wdcount="3"> Associated Press Writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890923-0035" num="9" wdcount="2"> MIAMI (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890923-0035" num="10" wdcount="28"> The ``greenhouse effect'' may breed bigger and deadlier hurricanes in the future, storms up to 50 percent stronger than Hugo and last year's record-setting Gilbert, some meteorologists say.</s>

<s docid="AP890923-0035" num="11" wdcount="20"> Hugo blasted the eastern Caribbean and the Carolinas with 135 mph winds this past week, killing at least 41 people.</s>

<s docid="AP890923-0035" num="12" wdcount="14"> Just before Hugo struck the U.S. coast, its pressure was measured at 940 millibars.</s>

<s docid="AP890923-0035" num="13" wdcount="23"> That made it among the 12 strongest hurricanes this century to hit the United States, the National Hurricane Center's Miles Lawrence said today.</s>

<s docid="AP890923-0035" num="14" wdcount="19"> Gilbert, whose winds reached 180 mph, tore up the Caribbean last year, killing 300 and causing $2 billion damage.</s>

<s docid="AP890923-0035" num="15" wdcount="8"> It was the most powerful hurricane ever recorded.</s>

<s docid="AP890923-0035" num="16" wdcount="28"> Gilbert seems to be about the upper limit of a hurricane with current ocean temperatures, said Kerry Emanuel of the meteorology department at the Massachusetts Institute of Technology.</s>

<s docid="AP890923-0035" num="17" wdcount="36"> But if the seas warm up, say by 3 to 6 degrees Fahrenheit, ``the wind speeds might be 25 percent higher _ which means the destructive force would be more like 50 percent higher,'' he said.</s>

<s docid="AP890923-0035" num="18" wdcount="23"> Stephen Schneider, deputy director of the National Center for Atmospheric Research in Denver, said his research suggests the warming trend is already here.</s>

<s docid="AP890923-0035" num="19" wdcount="30"> Schneider, an expert on the greenhouse effect and author of a new book ``Global Warming,'' said six of the 10 hottest years in the last 100 occurred in the 1980s.</s>

<s docid="AP890923-0035" num="20" wdcount="9"> He projects that the 1990s will be even hotter.</s>

<s docid="AP890923-0035" num="21" wdcount="32"> Hugo demonstrated the effect of warm Atlantic waters when its winds jumped from 105 mph to 135 mph as it passed over the Gulf Stream before hitting the East Coast, Schneider said.</s>

<s docid="AP890923-0035" num="22" wdcount="11"> ``You'll get worse hurricanes if the Caribbean is warmer,'' he said.</s>

<s docid="AP890923-0035" num="23" wdcount="13"> ``And I think there are better-than-even odds that you will have stronger hurricanes''.</s>

<s docid="AP890923-0035" num="24" wdcount="25"> Emanuel said if the ocean temperature climbs, moderate hurricanes of the future could grow to Gilbert's strength _ and future Gilberts will be even stronger.</s>

<s docid="AP890923-0035" num="25" wdcount="36"> Gilbert was so strong that Bob Sheets, director of the national hurricane center, said forecasters may have to use an intensity scale of 1-6 in the future, instead of the current 1-5, with five the highest.</s>

<s docid="AP890923-0035" num="26" wdcount="46"> The computer models Schneider uses show that in a worst-case scenario, over the next 100 years the world's temperature could jump by 10 degrees if carbon dioxide and methane gas _ which both contribute to the greenhouse effect _ continue to pour into the atmosphere unchecked.</s>

<s docid="AP890923-0035" num="27" wdcount="19"> It is possible that even though the world as a whole heats up, the Caribbean could somehow remain cooler.</s>

<s docid="AP890923-0035" num="28" wdcount="6"> But he said that is unlikley.</s>

<s docid="AP890923-0035" num="29" wdcount="9"> ``That's not what the models are showing,'' Schneider said.</s>

<s docid="AP890923-0035" num="30" wdcount="11"> ``And that's another reason I'd like to slow down global warming.''</s>
</TEXT>
</DOC>
