<DOC>
<DOCNO>

<s docid="AP890922-0072" num="1" wdcount="1"> AP890922-0072</s>
</DOCNO>
<FILEID>

<s docid="AP890922-0072" num="2" wdcount="2"> AP-NR-09-22-89 0652EDT</s>
</FILEID>
<FIRST>

<s docid="AP890922-0072" num="3" wdcount="5"> r a PM-HurricaneCenter-Scene 09-22 0462</s>
</FIRST>
<SECOND>

<s docid="AP890922-0072" num="4" wdcount="2"> PM-Hurricane Center-Scene,0473</s>
</SECOND>
<HEAD>

<s docid="AP890922-0072" num="5" wdcount="6"> Hurricane Forecasters Carry On Amid Chaos</s>
</HEAD>
<HEAD>

<s docid="AP890922-0072" num="6" wdcount="3"> With PM-Hugo, Bjt</s>
</HEAD>
<BYLINE>

<s docid="AP890922-0072" num="7" wdcount="3"> By CAROL PUGH</s>
</BYLINE>
<BYLINE>

<s docid="AP890922-0072" num="8" wdcount="3"> Associated Press writer</s>
</BYLINE>
<DATELINE>

<s docid="AP890922-0072" num="9" wdcount="4"> CORAL GABLES, Fla. (AP)</s>
</DATELINE>
<TEXT>

<s docid="AP890922-0072" num="10" wdcount="28"> Amid the uproar of live coverage by the major networks and scores of other media organizations, National Hurricane Center forecasters went about their business of monitoring Hurricane Hugo.</s>

<s docid="AP890922-0072" num="11" wdcount="14"> ``The whole system looks chaotic, but it works,'' said Bob Sheets, the center's director.</s>

<s docid="AP890922-0072" num="12" wdcount="36"> On one side of a large room dominated by a U-shaped bank of monitoring equipment were the forecasters, making meticulous calculations about where the deadly hurricane will strike and getting emergency operations going in those areas.</s>

<s docid="AP890922-0072" num="13" wdcount="27"> On the other side were the media _ a pack of reporters, camera operators and technicians, jockeying for seconds of Sheets' time and tidbits of his expertise.</s>

<s docid="AP890922-0072" num="14" wdcount="6"> In the center was Sheets himself.</s>

<s docid="AP890922-0072" num="15" wdcount="34"> Surrounded by cameras, wires and two dozen journalists with pads and telephones, the ubiquitous red-headed meteorologist has appeared on television all week next to a large satellite monitor showing colorful images of Hurricane Hugo.</s>

<s docid="AP890922-0072" num="16" wdcount="24"> During prime news time, competing technicians and cameramen shout and make rude hand gestures for people to get out of their shots of Sheets.</s>

<s docid="AP890922-0072" num="17" wdcount="19"> At his back, casually dressed forecasters who have been working 12-hour days tracked the storm via computers and satellites.</s>

<s docid="AP890922-0072" num="18" wdcount="25"> ``We obviously don't like this and could probably do a better job, but everyone knows now because of the media,'' said hurricane specialist Max Mayfield.</s>

<s docid="AP890922-0072" num="19" wdcount="12"> ``In the Caribbean, we were not so certain the word got out.</s>

<s docid="AP890922-0072" num="20" wdcount="8"> But we know the Carolinas have been evacuated''.</s>

<s docid="AP890922-0072" num="21" wdcount="35"> When a hurricane warning goes into effect, ``It's a $50 million statement,'' said meteorologist Joel Cline, referring to the cost of emergency preparations and evacuation plans that must be implemented when the warning is posted.</s>

<s docid="AP890922-0072" num="22" wdcount="16"> ``If we weren't here, then you wouldn't know that a storm was out there,'' he said.</s>

<s docid="AP890922-0072" num="23" wdcount="18"> Before the hurricane warning system was established, a storm of Hugo's power would have cost thousands of lives.</s>

<s docid="AP890922-0072" num="24" wdcount="30"> But early today, after days of warnings and proper evacuation procedures, there were no immediate reports of deaths despite widespread damage in Charleston and other coastal areas of South Carolina.</s>

<s docid="AP890922-0072" num="25" wdcount="18"> ``I like to think that we make a difference a far as human lives are concerned,'' Cline said.</s>

<s docid="AP890922-0072" num="26" wdcount="24"> After Hugo's landfall, Sheets and the other forecasters began to wind down from the hectic pace they had maintained for the last several days.</s>

<s docid="AP890922-0072" num="27" wdcount="31"> But, he warned, the hurricane center still is following three other weather systems that have moved into the Atlantic between the United States and Africa, and another storm in the Pacific.</s>

<s docid="AP890922-0072" num="28" wdcount="27"> ``I hate to say we're breathing a sigh of relief because people are getting clobbered to death,'' meteorologist Mark Zimmer said as the storm pounded Charleston, S.C.</s>

<s docid="AP890922-0072" num="29" wdcount="6"> ``But we've done all we can.''</s>
</TEXT>
</DOC>
